Yoast/wordpress-seo

package.json, yarn.lock
* [not-userfacing] Updated `react-svg-loader` to 0.4.6.
*
*
Fixes #
=> Update react-svg-loader to 0.4.6

admin/class-yoast-form.php, admin/config-ui/fields/class-field-company-name.php, admin/config-ui/fields/class-field-person-name.php, admin/views/tabs/metas/paper-content/general/knowledge-graph.php, css/src/yoast-components.scss, css/src/yst_plugin_tools.scss, js/src/components/MailchimpSignup.js, js/src/wp-seo-admin.js
* Add support for browsers auto-fill in the form fields that collect user information
- use the proper field type `email` on the Configuration wizard newsletter subscription field, this allows assistive technologies to properly identify the field type
- adds `autocomplete` attributes to the Person/Company and newsletter fields: this enables the browsers auto-fill to work
Both points are required by the WCAG 1.3.5 Identify Input Purpose
https://www.w3.org/TR/WCAG21/#identify-input-purpose
And allow us to declare support for this item in the Voluntary Product Accessibility Template (VPAT) we're preparing for Yoast SEO.
Additionally, removes the Select2 used for Company/Person and uses a styled select element.
- yarn link the …
=> Add autocomplete support to fields collecting user information

inc/class-wpseo-meta.php, inc/options/class-wpseo-option-titles.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemap-cache-data.php, inc/sitemaps/class-sitemaps-cache-validator.php, src/models/indexable.php
* _N/A_
Docblocks `/** .... */` are intended for use with structural elements, like functions, classes, hooks etc.
For "ordinary" multi-line inline comments, block comment style `/* ... */` should be used.
* _N/A_
=> Documentation: don't use docblocks for inline comments

inc/class-upgrade.php
* _N/A_
These docs were set up with a weird alignment way past the end of the code.
The inline docs have now been placed above each line they apply to.
* _N/A_
=> Documentation: fix inline docs in a specific function

inc/class-wpseo-utils.php
* _N/A_
These methods were not _added_ in `9.5`, but _deprecated_ in `9.5`. Fixed the tag annotating this.
Also added the `@codeCoverageIgnore` tag which is required for all deprecated methods.
* _N/A_
=> Documentation: use correct tag for deprecated methods

inc/class-wpseo-meta.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-option-ms.php, inc/options/class-wpseo-options.php, inc/options/class-wpseo-taxonomy-meta.php
* _N/A_
> Note: This tag has been used in the past, but should no longer be used.
Just using the static keyword in your code is enough for PhpDocumentor on PHP5 to recognize static variables and methods, and PhpDocumentor will mark them as static.
Ref: https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#phpdoc-tags
* _N/A_
=> Documentation: don't use the @static tag

inc/wpseo-functions.php
* _N/A_
The docblock should be above the function, not above the condition wrapping the function.
* _N/A_
=> Documentation: move an incorrectly placed function docblock

admin/config-ui/class-configuration-structure.php, admin/config-ui/fields/class-field-profile-url-wikipedia.php
* [not user-facing] Fixes a bug where the Youtube input field would not show in the configuration wizard, and the Wikipedia input field would have an incorrect id.
* Use the correct profileUrls field for Wikipedia
* Go to the configuration wizard.
* Go to Step 4.
* See the Youtube and Wikipedia input field. 
* Check that their ids are the correct ones.
* Add a Youtube and Wikipedia URL.
* Go to the settings in Yoast SEO > Social. See that the Youtube and Wikipedia URL are filled.
* Change the Youtube and Wikipedia URL. 
* Go back to step 4 of the config wizard, and see the changed URLs.
Fixes #12400
=> Show Youtube and Wikipedia input fields correctly in the configuration wizard

.travis.yml, admin/views/tabs/dashboard/features.php, admin/views/tabs/network/features.php
* _N/A_
* It was failing because of a bug in Node 11. I think for wordpress-seo
in general it is better to run lts/*. We check our code with the
latest node in the Yoast/javascript repository.
Check https://stackoverflow.com/questions/55059748/travis-jest-typeerror-cannot-assign-to-read-only-property-symbolsymbol-tostr.
* Travis is greeeeeeeen.
Fixes https://github.com/Yoast/yoast-components/issues/844.
=> Fix Travis build

grunt/config/copy.js
* [not user-facing] Removes the `vendor_prefixed` folder from `Yoast-dist`
* In the `composer-artifact` command, the `vendor_prefixed` folder is no longer copied
* Run `grunt artifact` and then `grunt composer-artifact` on `trunk`. You should see the `vendor_prefixed` folder in the `artifact_composer` folder.
* Check out this branch, and run `grunt artifact` and then `grunt composer-artifact`. You should NOT see the `vendor_prefixed` folder in the `artifact_composer` folder.
Fixes #12371
=> Do not copy the vendor_prefixed folder when running composer-artifact

inc/class-my-yoast-api-request.php, tests/src/unit-tests/oauth/client-test.php, wp-seo-main.php
* N/A -
* Made a wrapper for easily disabling the oauth feature. This returns false at the moment. Should be returning the commented value when oAuth is implemented.
* Also commented out the oAuth loader, to make sure the oAuth feature isn't loaded.
Previously the add-ons update process would go through the license manager. This got rewritten with the MyYoast connection flow. Unfortunately, this is more complicated and should get reverted a bit for now.
Therefore, we should test if the detecting and actual updating of the add-ons functions as before.
* Install an older version of an add-on (see releases tab on GitHub).
* Ensure that it still detects that there is a newer version …
=> Introduces a wrapper method for easily disabling the oAuth way.

phpunit.xml.dist
* _N/A_
No need for several `<testsuites>` tags.
Ref: https://phpunit.de/manual/6.5/en/appendixes.configuration.html#appendixes.configuration.testsuites
* Run `phpunit --testsuite php52` and `phpunit --testsuite php5.6+` on both the `trunk` branch as well as this branch. Verify that they both run as expected and that the numbers in the test summary match.
* Check a Travis PHP 5.6+ build on `trunk` and the build for this branch and verify that the numbers in the test summary match.
=> PHPUnit config: minor simplification

grunt/config/aliases.yaml, grunt/config/remove-vendor-prefixed-folder.js
* [not user-facing] Fixes a bug where the plugin could not be installed using composer.
* This tasks removes the reference to the vendor_prefixed folder in the composer.json in the artifact-composer folder, because that folder doesn't contain a vendor_prefixed folder.
* Run `grunt composer-artifact`.
* See that the autoload classmap array in the composer.json in the created composer-artifact folder does not contain `vendor_prefixed/` anymore.
Fixes #12433
=> Introduce the remove-vendor-prefixed-folder grunt task.

inc/class-wpseo-image-utils.php
* Adds `filesize` to whitelisted properties on `$image`. Props to [cmmarslender](https://github.com/cmmarslender)
* Needs to be whitelisted in order for the check in `WPSEO_Image_Utils::get_file_size()` to work properly.
Fixes #12367
=> Add filesize to the whitelist of parameters allowed on $image. 

admin/class-bulk-editor-list-table.php, admin/class-help-center.php, admin/class-social-admin.php, admin/metabox/class-metabox.php, frontend/class-breadcrumbs.php, frontend/class-frontend.php, frontend/class-opengraph-image.php, inc/class-rewrite.php, inc/class-wpseo-meta.php, inc/class-wpseo-replace-vars.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-option-ms.php, inc/options/class-wpseo-option-social.php, inc/options/class-wpseo-option-titles.php, inc/options/class-wpseo-option-wpseo.php, inc/options/class-wpseo-option.php, inc/options/class-wpseo-options.php, inc/options/class-wpseo-taxonomy-meta.php, inc/wpseo-functions.php, tests/doubles/class-wpseo-option-social-double.php, tests/frontend/test-class-wpseo-handle-404.php, tests/test-class-wpseo-meta.php
* _N/A_
Improve method docblock `@return` tag formatting
Includes minor punctuation fixes.
* _N/A_
=> Documentation: improve method docblock @return tag formatting

inc/class-wpseo-custom-fields.php, inc/class-wpseo-custom-taxonomies.php, inc/class-wpseo-endpoint-factory.php, inc/class-wpseo-replace-vars.php, inc/class-wpseo-replacement-variable.php, inc/class-wpseo-utils.php, inc/indexables/class-indexable.php, inc/indexables/class-object-type.php, inc/indexables/class-post-indexable.php, inc/indexables/class-term-indexable.php, inc/indexables/validators/class-robots-validator.php, inc/options/class-wpseo-option-ms.php, inc/options/class-wpseo-option-social.php, inc/options/class-wpseo-option-titles.php, inc/options/class-wpseo-taxonomy-meta.php, tests/admin/test-class-yoast-network-admin.php, tests/config-ui/test-class-configuration-components.php, tests/config-ui/test-class-configuration-endpoint.php, tests/config-ui/test-class-configuration-options-adapter.php, tests/config-ui/test-class-configuration-service.php, tests/config-ui/test-class-configuration-storage.php, tests/config-ui/test-class-configuration-structure.php, tests/doubles/class-indexable-double.php, tests/doubles/class-wpseo-plugin-availability-double.php, tests/inc/test-class-wpseo-primary-term.php, tests/sitemaps/test-class-wpseo-sitemaps-cache-data.php, tests/taxonomy/test-class-taxonomy-content-fields.php, tests/taxonomy/test-class-taxonomy-presenter.php, tests/taxonomy/test-class-taxonomy-settings-fields.php, tests/taxonomy/test-class-taxonomy-social-fields.php
* _N/A_
More of the same as #11876, #11895 and #12270.
* _N/A_
=> Documentation: use full property docblocks

inc/options/class-wpseo-taxonomy-meta.php, tests/config-ui/test-class-configuration-service.php, tests/formatter/test-metabox-formatter.php, tests/inc/options/test-class-wpseo-taxonomy-meta.php, tests/inc/test-class-addon-manager.php
* _N/A_
`wp_json_encode()` is basically `json_encode()` with PHP cross-version compatibility handling, which is why it should be used instead.
Refs:
* http://php.net/manual/en/function.json-encode.php
* https://developer.wordpress.org/reference/functions/wp_json_encode/
* _N/A_
This is a code-only change and should have no effect on the functionality (other than for low PHP versions).
=> QA: replace json_encode() calls with wp_json_encode()

composer.json
* _N/A_
As discussed in https://github.com/Yoast/wordpress-seo/pull/11961#pullrequestreview-189052603.
This PR adds a `premium-fix-cs` script to the `composer.json` file.
This script does not need a separate run with a different `testVersion` setting for PHPCompatibility as that standard doesn't contain fixers, so one run over the code should work fine.
Might be difficult depending on one's setup, but if both the Free as well as the Premium repos are setup as remotes for the same local repo, this is testable.
* Create a branch for the Premium plugin.
* Introduce some (fixable) errors in the Premium code, think: whitespace errors.
* Check that PHPCS picks up on the errors by running …
=> Composer: add "premium-fix-cs" script

admin/class-yoast-network-admin.php, readme.txt
* Fixes a bug where side-wide settings were not saved on multisite environments.
* I removed the `sanitize_text_field ` that was added in the CS week in https://github.com/Yoast/wordpress-seo/pull/11896/files. This function expects a string, but receives an array. As a result, it returns an empty string, which means all settings are gone. 
* See #12440 
Fixes #12440
=> Remove sanitize_text_field that breaks the saving of settings

admin/class-admin-asset-manager.php, admin/class-admin.php, admin/class-primary-term-admin.php, admin/class-yoast-dashboard-widget.php, js/src/edit.js, js/src/wp-seo-metabox-category.js
* [not-userfacing] Move the primary term picker to the JS file that actually manages the primary taxonomy.
* Turned `WPSEO_Primary_Term_Admin` and `Yoast_Dashboard_Widget` into `WPSEO_Wordpress_Integration`s.
* Make sure the primary taxonomy picker still works in Gutenberg and the classic editor.
=> Moved primary term selector to separate script

admin/class-yoast-form.php
* [not user-facing] Reintroduces `echo '<br class="clear"/>';` at the end of select boxes to avoid breaking the local SEO settings page.
* Reintroduces `echo '<br class="clear"/>';` at the end of select boxes to avoid breaking the local SEO settings page.
* Build this branch and test in combination with local SEO. See https://github.com/Yoast/wordpress-seo-local/issues/1437
Fixes https://github.com/Yoast/wordpress-seo-local/issues/1437
=> Reintroduce <br class="clear"/>' at the end of select boxes

.gitignore, package.json, scripts/link_monorepo_to_plugin.sh
We need a new script for linking the monorepo since we can no longer use the direct URLs of the repo's. This adds that.
* N/A - Not userfacing. Adds a script to link the monorepo to the plugin.
* Script is written in Bash, GL HF.
* Check that `yarn link-monorepo` works locally.
* Check the script also works on Travis.
Fixes Yoast/javascript#27
=> Build development workflow for plugin and monorepo

inc/class-addon-manager.php, tests/inc/test-class-addon-manager.php
* [not-userfacing] Fix bug where the addon manager would throw an error due to a non-existing value.
*
* In `WPSEO_Addon_Manager` in the `get_site_information_transient` comment out the first 5 lines to avoid the transient from being used:
```
$site_information = $this->get_site_information_transient();
if ( $site_information ) {
return $site_information;
}
```
* In `WPSEO_Addon_Manager` in the `get_site_information` you can now check the new results from `get_site_information_transient` by doing a `$this->get_site_information(); die;`.
Fixes #
=> Use expiryDate instead of expires in addon manager

admin/class-add-keyword-modal.php, admin/class-keyword-synonyms-modal.php, admin/class-multiple-keywords-modal.php, admin/class-premium-popup.php, admin/formatter/class-metabox-formatter.php, js/src/components/modals/KeywordSynonyms.js, js/src/components/modals/MultipleKeywords.js, js/src/components/modals/RedirectUpsell.js
* [Not for changelog] Changes the text below the upsell buttons.
* Changes all occurrences of `1 year free updates and upgrades included!` to `1 year free support and updates included!`.
* Find all the upsells and verify that the text has changed.
* Or: find one modal and one other occurrence, and believe in the power of PHP 😄 
Fixes https://github.com/Yoast/wordpress-seo/issues/12448
=> Change description below upsell button

admin/class-admin.php, admin/class-extensions.php, admin/class-yoast-form.php, admin/views/licenses.php, inc/class-addon-manager.php, tests/inc/test-class-addon-manager.php
* [not-userfacing] Replaces usage of WPSEO_Extension_Manager in favor of WPSEO_Addon_Manager.
* Added a helper function called `has_valid_subscription` to the `WPSEO_Addon_Manager` that gets the subscription via a slug and checks if the subscription is expired.
* Create contants for the addon slugs in `WPSEO_Addon_Manager`. This is so we can access them seperately from the protected $addons array, not having to know the key.
* `WPSEO_Extension_Manager` was used in the following locations:
* `admin/class-admin.php` (`WPSEO_Admin`) -> `add_action_link`: the premium activated check.
* `admin/class-extensions.php` (`WPSEO_Extensions`) -> `is_valid`: extensions activated check.
* `admin/class-yoast-form.php` (`Yoast_Form`) -> …
=> Replace usage of WPSEO_Extension_Manager in favor of WPSEO_Addon_Manager

tests/inc/options/test-class-wpseo-option-wpseo.php, tests/inc/test-class-wpseo-upgrade-history.php
=> Test documentation: add some missing property docblocks

inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps.php
* Add filters to handle custom post statuses when generating sitemap
1. Create a custom post type
2. Enable Edit Flow plugin or otherwise create custom post status for the custom post type
3. Create one or more posts with the custom post status - see that they do not appear in the sitemap.xml created by Yoast SEO
4. Add a filter for 'wpseo_sitemap_poststatus' and 'wpseo_sitemap_poststatus_lastmodified' to add the custom post status to the array of post status names.
5. See that the posts are now included in the sitemap.xml
* This PR does not change the UI in the plugin.
Fixes #12074
=> Add filters to handle custom post statuses when generating sitemap

admin/class-bulk-editor-list-table.php, admin/google_search_console/class-gsc-category-filters.php, admin/google_search_console/class-gsc.php, inc/class-upgrade.php, inc/options/class-wpseo-option-titles.php, inc/options/class-wpseo-option-wpseo.php, inc/sitemaps/class-sitemaps-cache-validator.php, inc/structured-data-blocks/class-faq-block.php, inc/structured-data-blocks/class-how-to-block.php, inc/wpseo-functions.php, tests/sitemaps/test-class-wpseo-sitemaps-cache-validator.php, tests/test-class-admin-asset-manager.php, tests/test-class-primary-term-admin.php
* _N/A_
A _short description_ should normally be a short sentence, while an additional _long description_ can be used to expand on that.
* _N/A_
=> Documentation: improve function docblock short vs long description layout

admin/ajax/class-yoast-dismissable-notice.php, admin/class-admin-asset-manager.php, inc/class-wpseo-meta.php, inc/options/class-wpseo-option.php
* _N/A_
A _short description_ should normally be a short sentence, while an additional _long description_ can be used to expand on that.
* _N/A_
=> Documentation: improve class docblock short vs long description layout

tests/test-class-wpseo-json-ld.php
* _N/A_
The short description should always be the first thing in a docblock, before any tags.
Includes minor punctuation fixes.
* _N/A_
=> Test documentation: short description should be first

admin/class-my-yoast-proxy.php, admin/views/tabs/dashboard/webmaster-tools.php, frontend/class-json-ld.php, frontend/class-opengraph-oembed.php, frontend/class-opengraph.php, inc/class-wpseo-custom-fields.php, inc/class-wpseo-replace-vars.php, inc/class-wpseo-utils.php, inc/sitemaps/class-author-sitemap-provider.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemap-timezone.php, src/yoast-model.php, src/yoast-orm-wrapper.php, tests/admin/test-class-database-proxy.php, tests/onpage/test-class-onpage.php, tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php, tests/sitemaps/test-class-wpseo-sitemap-image-parser.php
* _N/A_
`@see` is intended for structural elements, not for links. For links, the `@link` tag should be used.
Also, when links are used inline, the link tag should be surrounded by curly braces.
Ref: https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc-tags.md#56-link
* _N/A_
=> Documentation: use (inline) @link tag where appropriate

admin/views/licenses.php
* _security hardening_
Translated text should also be escaped.
* _N/A_
This is a code-only change and should have no effect on the functionality (except when a translation would add (malicious) HTML).
=> QA/XSS: always escape output - 35

css/src/structured-data-blocks.scss, grunt/config/eslint.js, js/src/structured-data-blocks/faq/components/FAQ.js, js/src/structured-data-blocks/faq/components/Question.js, js/src/structured-data-blocks/how-to/components/HowTo.js, js/src/structured-data-blocks/how-to/components/HowToStep.js
* Fix the buttons position in the structured data blocks.
- Gutenberg moved some components from `editor` to `block-editor`
- as a consequence, also some Gutenberg CSS classes have now different names e.g. `editor-inserter__toggle` became `block-editor-inserter__toggle`
- we shouldn't use Gutenberg CSS class names in our components to start with, as they're not part of a formalized API (or so they _dixit_)
- this PR removes any usage of `editor-inserter__toggle`
- removes `components-icon-button` from the JS, though it's still used in our stylesheet
- changes the "Add total time" Button component to IconButton: this was a hack made necessary by the IconButton lack of support for `ref`s. So we used a Button and manually added the …
=> Remove Gutenberg CSS classes and adjust CSS accordingly.

admin/class-admin.php, admin/class-yoast-form.php
* [not user-facing] Fixes a bug where the premium ads and `FAQ` and `Premium Support` links would not be shown when a site has a valid premium license but not an active premium plugin.
* Adds a check whether the premium plugin is active to the check that there is a valid license.
* Have a website that does have a valid premium license (local.wordpress.test does have one. I'm not sure about one.wordpress.test. When in doubt, check with team platform).
* On release/10.1: 
* Install and activate wordpress-seo (free!)
* Click `Yoast SEO` in the sidebar to go to our notification center.
* See that there are no upsells for premium on the righthand side.
* Go to the plugin overview. Check …
=> Show ads and `FAQ` and `Premium Support` links when Premium is not active

composer.json, scripts/maybe-restore-composer-lock.php, scripts/maybe_restore_composer_lock.php
* N/A
* Don't checkout composer.lock on Travis. This breaks the build because the composer.json is changed as well, which results in a mismatch.
* Travis should pass without problems. Locally, the composer.lock should be checked out during `after-premium-cs`. 
Fixes #
=> Premium cs only checkout outside travis

package.json, scripts/link_monorepo_to_plugin.sh, webpack/webpack.config.js
* _N/A_
This fixes two things:
* Link all packages inside the monorepo instead of only the ones in the package.json. Because of how webpack builds the files, we cannot build on the packages required in `package.json`. Because a package we require could have a different dependency and then that dependency is not linked. If it is not linked then webpack cannot find it.
* Run babel over the `@yoast` packages because we are running those from source in the monorepo.
* :point_up:
* Run `yarn link-monorepo`
* Run grunt build:js
* You should have a limited amount of errors. Before this PR you had errors that `@yoast/components`, `@yoast/helpers` were missing. After this PR you don't have …
=> Fix development of monorepo in plugin

inc/class-wpseo-shortlinker.php
In order to increase cache efficiency for `yoa.st` links, I'm slightly changing some parameters.
- We add a `role` parameter to `yoa.st` links that we don't use, so we're removing that.
- PHP now is only `x.y` instead of `x.y.z`
- `days_active` is now divided into 4 cohorts, instead of outputting the specific number of days.
* no changelog needed.
* See any yoa.st link in the plugin, see that it changed.
=> Slightly change yoa.st query params

css/src/alerts.scss, css/src/yoast-components.scss, js/src/configuration-wizard.js
* We moved the configuration-wizard to its own package. As a result, it lost access to its `scss`. This PR makes sure that the configuration-wizard contains its own sass.
Make sure that the configuration-wizard can still be build and looks the same.
This PR should not create any UI changes. If that happens, please reject this PR.
Related Yoast/javascript#141
Related Yoast/javascript#148
=> Make sure that the configuration-wizard has access to its own scss.

frontend/schema/class-schema-organization.php
Adds an `image` attribute to the `Organization` output that points to the `@id` for `logo`. 
Simple change, I'm guessing this will just pass tests, @dariaknl / @igorschoester ?
=> Add image attribute to organization

frontend/schema/class-schema-webpage.php
Instead of having the page type be an array, @jono-alderson and I have decided to always make it a single string. This might need some small changes to tests, @dariaknl / @igorschoester ?
=> Make WebPage always be a string

package.json, yarn.lock
* [non-user-facing] Version bump for YoastSEO (to 1.50.0)
[non-user-facing] Version bump for Yoast Components (to 4.23.0)
* Build the files, see no errors.
=> Bump yoastseo to 1.50 and yoast-components to 4.23

css/src/metabox.scss
It seems that the classes provided in the loadingSpinner are not used in the wordpress-seo repo and since we are removing the file altogether we should remove the import.
* Remove the loadingSpinner.scss import from metabox.scss.
* See Yoast/javascript#152
* Check that the build works and everything looks the same.
Related Yoast/javascript#152
=> Remove the loadingSpinner import from metabox.scss

inc/class-my-yoast-api-request.php, tests/doubles/class-my-yoast-api-request-double.php, tests/inc/test-class-myyoast-api-request.php
Instead of a string, as most error codes in WordPress are.
* Fixes a bug where a fatal error can occur on license requests which return an unexpected result.
* Make sure the Exception second argument is always a number or not given at all
* Trigger a `WP_Error` in the license request (`$response = new WP_Error( 'error-code', 'Error' );`)
* Go to either: Dashboard, Yoast SEO Dashboard, Plugin page or Premium page.
Fixes #12560
=> Make sure error-code is a number

inc/class-addon-manager.php
Only add it conditionally when Premium is active.
This is needed for the translations updates of the free translations.
* Fixes the situation where Yoast SEO would contact Yoast.com for license checks even when no Yoast addons are installed.
* Conditionally add the Free plugin as addon when relevant (in Premium to make sure we can fetch the Free translation file updates from WordPress.org)
*
Fixes https://github.com/Yoast/wordpress-seo/issues/12571
=> Remove Free from default addons list

inc/class-addon-manager.php, readme.txt
* Fixes a bug where the license information from MyYoast is being saved aggressively, causing updates in MyYoast to take 24 hours to show up in the site.
* Statically cache the response on the current request
* Early return `false` for the transient content on certain pages in the admin, because the upgrade notification needs the information on all pages and we don't want to do the request on all the pages.
*
Fixes #
=> Backport transient updates form Premium patch

admin/class-admin.php, admin/class-yoast-form.php, admin/views/licenses.php
Before doing a license check on the Premium slug, this avoids doing calls to MyYoast.
* tbd
* Doing a check if Premium is activated before additional checks on the license.
* Install Yoast SEO on a site where no other addons (or Premium) is present
* Visiting any page in site should not trigger an HTTP request to MyYoast
* The previous patch has removed this request from -most- pages, this PR removes it from the `Plugins`, `Premium` and settings pages (which have upsells).
* Makes sure to check: Post overview, Post edit, Taxonomy overview, Taxonomy edit, Yoast SEO settings pages, Configuration Wizard, Plugin overview, dashboard, WordPress Core updates pages.
* Checking this can be …
=> Check if we are in Premium first

admin/courses-overview.php, js/src/courses-overview.js
I see no reason for us to add the type of plugin to the courses feed. Updating the URL for caching reasons.
* None needed.
* Courses tab should still work.
Fixes #
=> Change the URL for the courses feed

frontend/class-frontend.php, frontend/class-json-ld.php, inc/options/class-wpseo-option-social.php, tests/frontend/test-class-wpseo-frontend.php
* Fixes a bug where the `rel="publisher"` Google+ tag was being output on the frontend if that profile was provided in the past.
*
*
Fixes #12588
=> Remove publisher tag

admin/class-admin.php, wp-seo-main.php
Instead of only when doing AJAX and `inline-save`
*
* Always register the Addon Manager hooks, these were not hooked on AJAX requests.
*
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2316
=> Always load the Addon Manager

js/src/components/CornerstoneToggle.js, package.json, yarn.lock
* [not-user-facing] Updates dependency for `yoastseo` and `yoast-components` for release 11.0
*
* Link the monorepo, build the files, see no errors.
Fixes #
=> Bump yoastseo and components for release 11.0

admin/ajax.php, admin/ajax/class-recalculate-scores-ajax.php, admin/ajax/class-shortcode-filter.php, admin/class-collector.php, admin/class-yoast-alerts.php, admin/class-yoast-notification-center.php, admin/class-yoast-notification.php, admin/google_search_console/class-gsc-ajax.php, admin/import/plugins/class-import-seopressor.php, admin/views/tool-bulk-editor.php, frontend/schema/class-schema.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-taxonomy-meta.php, inc/structured-data-blocks/class-faq-block.php, inc/structured-data-blocks/class-how-to-block.php, src/oauth/client.php, tests/config-ui/test-class-configuration-service.php, tests/formatter/test-metabox-formatter.php, tests/inc/options/test-class-wpseo-taxonomy-meta.php, tests/inc/test-class-addon-manager.php, tests/inc/test-class-myyoast-api-request.php, tests/notifications/test-class-yoast-notification.php
This introduces `WPSEO_Utils::format_json_encode` which has two advantages:
* we use unescaped slashes everywhere when possible, which improves readability and makes our JSON strings smaller.
* we always output JSON nicely when we can and `WPSEO_DEBUG` is on.
Because these advantages both seem useful _everywhere_, at the suggestion of @omarreiss  I've made this change everywhere we called `wp_json_encode` and replaced it with this new util. This new function also replaces the `format_data` function we had previously introduce in `WPSEO_Schema`.
Would like some dev and architect feedback on this, @atimmer @IreneStr @moorscode
=> Introduce `WPSEO_Utils::format_json_encode`

admin/class-product-upsell-notice.php, admin/google_search_console/class-gsc.php
The "please rate this plugin" and "connect your GSC" notifications should not be shown anymore.
* [not-user-facing] Disabled the "please rate" notification & the "connect to Google Search Console" notification
*
Google Search Console:
* Make sure you don't see the Google Search Console-connect notification, even when not connected to Google Search Console.
5-star rating:
* Make sure you meet all the conditions to show the `5-star rating` notification:
* Have the following database option settings:
* `wpseo` -> `wpseofirst_activated_on` - timestamp larger than two weeks in the past (`1491392325`)
* User meta option: `wpseo-remove-upsell-notice` should be removed if present
* Don't …
=> Remove two notifications

js/src/wp-seo-dashboard-widget.js
Partially fixes https://github.com/Yoast/javascript/issues/205
The WordPress Feed component's classname was changed. This PR restores it.
OLD
---
NEW
---
* N/A
* I choose to overwrite the new classname with the old classname so we can maintain BC (and it's the easiest solution).
* Verify that the dashboard widget looks like in the screenshot.
=> Restore classname

frontend/schema/class-schema.php
* No changelog needed.
* Brought the filter `wpseo_json_ld_output` back, return `false` or an empty array on it and it will disable all Schema output. Done after a search on WPDirectory.net showed too many plugins use that filter to disable our output.
*
Fixes #12619
=> Reinstate wpseo_json_ld_output filter

js/src/components.js, webpack/webpack.config.js
* [not user-facing] Decrease bundle size by removing some bundle duplication.
* I've added some `@yoast` packages to the externals in the main config.
* I've created a new config for the components bundle, which doesn't need those `@yoast` packages externals.
* Don't forget to test https://github.com/Yoast/wordpress-seo-premium/pull/2327 as well. The main goal is to have a premium zip < 5 MB.
* Build a zip with this branch and make sure everything still works, especially things related to components and the `@yoast` packages: the configuration wizard, the metabox, the dashboard widget.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2322
=> Decrease bundle size

tests/admin/test-class-my-yoast-proxy.php
* _N/A_
PHPUnit offers the following annotations for testing `Exception`s:
* `@expectedException` to indicate an exception is expected and the type of the exception.
* `@expectedExceptionCode` to narrow this down to a specific error code if set/available.
* `@expectedExceptionMessage` to test whether the received message from the Exception is as expected.
* `@expectExceptionMessageRegExp` to test whether the received message from the Exception follows an expected pattern.
Adding the `message` as part of the `@expectedException` annotation does _not_ actually test the message and prevent the "expected Exception" from being tested.
Refs:
* https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writi …
=> Test documentation: use correct @expectedException annotations

tests/test-class-wpseo-meta.php
* _N/A_
Ref: http://docs.phpdoc.org/references/phpdoc/tags/see.html
* _N/A_
=> Documentation: use @see tag

inc/sitemaps/class-sitemap-cache-data.php, src/config/admin.php
* _N/A_
A method/function docblock has guidelines for information order and such. It is typically laid out like:
```php
/**
* Short description.
*
* Long description....
*
* @tag Tag description.
* @tag Tag description.
*
* @param type $name Parameter description.
*
* @return type Description.
*/
```
While the order of some of these is not 100% clearly defined, the short and long description _have_ to be at the top and the `@param` and `@return` tags have to be at the bottom and shouldn't be combined in a block with other tags.
* _N/A_
=> Documentation: some method docblock format improvements

package.json, webpack/webpack.config.js, yarn.lock
* _N/A_
The configuration wizard was broken when running `grunt release` build. This has been fixed with this PR. Also other issues should be fixed with this.
*
* Create a zip using `grunt artifact`.
* Test this zip in a clean installation
* The configuration wizard should work.
Fixes #12636
Fixes #12641
=> Fix configuration wizard on release

admin/views/licenses.php
* _N/A_
`array_merge()` is a "heavy" function and if all that is needed is to add something to an existing array, there are simpler ways to do this.
Also, keep in mind that `array_merge()` will renumber numeric array indexes which may be undesired.
* This is a code-only change and should have no effect on the functionality. Cursory testing recommended, but should be sufficient.
=> QA: don't use array_merge when its not needed

grunt/config/eslint.js, js/src/structured-data-blocks/how-to/components/HowTo.js
* Fixed TypeError when attempting to set focus on the How-to add duration button
Prior to Gutenberg 5.3 the IconButton doesn't support refs. The ref returns the Component instance and attempting to set focus on it triggers a TypeError.
I guess we could fix this by using ReactDOM / findDOMNode for Gutenberg 5.3 and previous but that wouldn't be great.
Considering the how-to block is going to be refactored and to keep it simple, I'd propose we accept a focus loss in WordPress 5.1.
Starting from WordPress 5.2, Iconbutton does support refs and everything will work correctly.
- build the plugin
- add a How-To block
- click on "Add total time"
- then click on the trash icon ("Delete total time")
- in WordPress trunk 5.2: focus is moved …
=> Fix TypeError when attempting to set focus on the How-to add duration button

package.json, yarn.lock
* [not-user-facing] Updates `yoast-components` to 4.23.1.
* Build the files and check whether nothing breaks.
Fixes #
=> Bump yoast components to v. 4.23.1

admin/views/tabs/metas/paper-content/general/knowledge-graph.php, inc/options/class-wpseo-option-titles.php
* Make `company` the default entity type on a new installation.
* Removed option to choose on entity type on the search appearance page.
*
* Create a new WordPress site.
* Install the plugin from this PR. You can take my word for it or build it yourself:
[wordpress-seo-test.zip](https://github.com/Yoast/wordpress-seo/files/3088524/wordpress-seo-test.zip)
* Don't go through the configuration wizard, check `SEO` > `Search Appearance` first to see whether the site entity is set to `Organization`. Be sure you can no longer select `Choose whether this site represents a person or an organization...`.
* Go through the configuration wizard and make sure everything works as intended.
Fixes #
=> Made company default entity and removed option to select no entity

frontend/schema/class-schema-image.php
* None needed
* Retrieve `full` size instead of default `thumbnail`.
=> Use full size instead of thumbnail image

inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps.php, inc/sitemaps/class-taxonomy-sitemap-provider.php
* Use unique filter _wpseo_sitemap_post_statuses_ for the root sitemap or a CPT sitemap. Props to [stodorovic](https://github.com/stodorovic) and [tolnem](https://github.com/tolnem)
* Populates correct _post_status_ in post object (sitemaps) Props to [stodorovic](https://github.com/stodorovic)
* Create new method _get_post_statuses_ in _class WPSEO_Sitemaps_ which returns post statuses
* Create a custom post type
* Enable Edit Flow plugin or otherwise create custom post status for the custom post type
* Create one or more posts with the custom post status
* Add a filter for `wpseo_sitemap_post_statuses` to include custom post status into CPT sitemap.
=> Introduces method get_post_statuses in sitemaps

inc/sitemaps/class-sitemaps-router.php, inc/sitemaps/class-sitemaps.php, tests/sitemaps/test-class-wpseo-sitemaps-router.php
* Fixes a bug where URLs with a non-Yoast SEO related xsl query string parameter would result in a blank page. Props [@stodorovic](https://github.com/stodorovic) and [@yiska](https://github.com/yiska).
* We have changed query variable to avoid possible conflicts with other plugins.
* Apply changes from this PR. 
* Save Permalinks to flush new rewrite rules.
*  Test xsl style-sheets:
_https&#58;//example&#46;com/main-sitemap.xsl_ 
_https&#58;//example&#46;com/?yoast-sitemap-xsl=main_ 
* Install and activate _Yoast SEO: News_
*  Test xsl style-sheets:
_https&#58;//example&#46;com/news-sitemap.xsl_ 
_https&#58;//example&#46;com/?yoast-sitemap-xsl=news_ 
* Test that YoastSEO is not …
=> Replace xsl variable with yoast_xsl

frontend/schema/class-schema-person.php
* Fixes copy-pasta in `WPSEO_Schema_Person` constructor comment.
=> Fix copy-pasta in constructor comment

js/src/components/WordPressUserSelector.js, js/src/components/WordPressUserSelectorOnboardingWizard.js, js/src/redux/utils/configureEnhancers.js, package.json, yarn.lock
* [non-userfacing because only in the trunk so far] Fixes a console error due to incorrect PropTypes in the WordPressUserSelector component.
* [non-userfacing] Removes development dependency of `redux-logger`, that was used on the search-appearance page.
* Added a PropTypes export in the WordPressUserSelector file.
* Added the WordPressUserSelectorPropTypes in the WordPressUserSelectorOnboardingWizard.
* Removed `redux-logger` middleware; used only in the search-appearance store. Please use the Redux development tool browser extension instead.
* Replicate the issue by activating the plugin of `release/11.1`.
* Go to the `SEO -> Search Appearance` page.
* Check the console for the …
=> Fix search-appearance React error

package.json, scripts/link_monorepo_to_plugin.js
This *probably* fixes the problems Daria has. Also, it ensures that those commands can be used on other filesystems as long as node is installed.
=> No longer execute the link-monorepo scripts using a shebang (#!)

admin/class-admin.php, admin/class-config.php, admin/class-schema-person-upgrade-notification.php, admin/class-yoast-form.php, admin/views/tabs/metas/paper-content/general/knowledge-graph.php, admin/views/tabs/social/accounts.php, frontend/class-frontend.php, frontend/schema/class-schema-author.php, frontend/schema/class-schema-breadcrumb.php, frontend/schema/class-schema-image.php, frontend/schema/class-schema.php, frontend/schema/interface-wpseo-graph-piece.php, inc/class-addon-manager.php, inc/class-wpseo-utils.php, tests/admin/test-class-schema-person-upgrade-notification.php
* _N/A_
Mixed bag of fixes:
* Various whitespace fixes;
* Added missing translators comments x 2;
* Added missing output escape around a URL x 3;
* Added missing output escaping for link text x 1;
* Removed an unnecessary empty return at end of function;
* Added missing `@codeCoverageIgnore` tag for deprecated method.
* _N/A_
=> CS: clean up after merges

inc/class-upgrade.php, inc/options/class-wpseo-option-titles.php
* [not-userfacing] Fixes edgecase where you could set the site entity to "".
* Added upgrade routine that will set `company_or_person` to company when an invalid value is stored at the moment of upgrading.
* Added validation for `company_or_person` in `class-wpseo-option-titles.php`.
* Reproduce steps in #12725 
Fixes #12725
=> Set company or person in upgrade routine

admin/taxonomy/class-taxonomy.php
* Fixes a bug where the Yoast SEO metabox on category and tag pages would not load. 
* The list of feature flags is now also injected into the javascript side of the metabox on taxonomy and category pages. 
**High**: Can cause the entire metabox to not load on category and tag pages.
* Checkout the `trunk` branch.
* Start your local `wordpress-seo` development environment.
* Go to a category or tag page.
* The page should have an empty Yoast SEO metabox.
* The browser's console should give this error:
```
Uncaught ReferenceError: wpseoFeaturesL10n is not defined
```
* Checkout this branch (`12745-wpseofeaturesl10n-is-not-defined`)
* Start your local `wordpress-seo` development …
=> Enabled features are now also available on category and tag pages.

admin/class-admin-init.php
* Changes compatibility notifications to only show for active plugins.
* I left the `$type` in there to still be able to remove any current warning notifications.
* Install old add-on versions but do not activate them.
* Go to the SEO Dashboard.
* There should no longer be notifications about updating the installed but inactive add-ons.
* Activate the add-ons.
* There should be an error notification about updating the active add-ons.
Fixes #12650
=> Only show compatibility notifications for active plugins

package.json, yarn.lock
* [not-user-facing] Updates dependencies for `yoastseo` and `yoast-components` and `search-metadatea-previews` for release 11.0.
* There only was a change in yoastseo. `yoast-components` and `search-metadatea-previews` were bumped because they also include `yoastseo` as a dependency.
* See https://github.com/Yoast/javascript/pull/247
Fixes #
=> Bump packages to newest RC version

inc/options/class-wpseo-option.php, tests/admin/test-class-database-proxy.php, tests/frontend/test-class-wpseo-frontend.php, tests/frontend/test-class-wpseo-opengraph-image.php, tests/sitemaps/test-class-wpseo-sitemaps-cache.php, tests/test-class-rewrite.php
* _N/A_
Includes two minor tweaks to existing inline block comments.
* _N/A_
=> Documentation: use multi-line comment format for long inline comments

admin/capabilities/class-capability-manager-integration.php, frontend/class-opengraph.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-option-wpseo.php, inc/wpseo-functions.php, src/models/primary-term.php, tests/admin/services/test-class-endpoint-indexable.php, tests/admin/services/test-class-indexable-post-provider.php, tests/admin/test-class-admin-recommended-replace-vars.php, tests/admin/test-class-yoast-network-admin.php, tests/config-ui/test-class-configuration-options-adapter.php, tests/inc/indexables/test-class-indexable.php, tests/inc/indexables/test-class-post-indexable.php, tests/inc/indexables/test-class-term-indexable.php, tests/inc/options/test-class-wpseo-option-wpseo.php, tests/inc/options/test-class-wpseo-option.php, tests/inc/test-class-addon-manager.php, tests/sitemaps/test-class-wpseo-sitemaps-router.php, tests/test-class-admin-asset-manager.php, tests/test-class-wpseo-meta-columns.php, tests/test-class-wpseo-utils.php
* _N/A_
Tag alignment and grouping fixes:
* Tags of the same kind should be grouped without blank lines between them.
* Different tags may sometimes be grouped, but not always.
* The content of grouped tags should start one space after the longest tag.
* _N/A_
=> Documentation: improve miscellaneous tag alignment and grouping

tests/admin/test-class-admin-editor-specific-replace-vars.php, tests/test-class-wpseo-rank.php
=> Test documentation: add some missing @covers tags

admin/config-ui/class-configuration-page.php, admin/views/js-templates-primary-term.php, admin/views/licenses.php
* _N/A_
Multi-line embedded PHP should have the PHP open and close tags on a line by themselves.
Depending on the HTML tags in which the code is embedded, adding these additional line-breaks may or may not influence how things display on screen. For block elements, it should normally have no influence. For inline HTML elements, like `<span>` or `<a>`, it will add a space to the displayed text on screen.
For most cases addressed in this PR, moving the multi-line function call to a variable declared before the HTML section starts and only echo-ing the variable in the embedded PHP is the simplest solution around this.
In one case, adding the above mentioned line-breaks should be just …
=> CS: Move multi-line function call out of embedded PHP

frontend/class-opengraph-image.php, frontend/class-twitter.php, frontend/schema/class-schema-webpage.php, inc/class-wpseo-image-utils.php
* Fallback to first image in content for schema when no featured image is set.
* Created helper function `get_first_usable_content_image_for_post`.
* Didn't write unit tests because the code relies heavily on wp functions.
* When a post/page has a featured image, check whether the same image is used for `og:image`, `twitter:image` and the `WebPage` graph's `image` object.
* When a post/page has no featured image, but other images, check whether the first  image is used for `og:image`, `twitter:image` and the `WebPage` graph's `image` object.
* When a post/page has no featured image, and no images, check whether there are no `og:image` or `twitter:image` meta tags, and the `WebPage` …
=> Fallback to first content image when no featured image is available

frontend/class-opengraph.php, tests/frontend/test-class-opengraph.php
* Removed the OGP.me html namespace as it's no longer needed.
* Didn't deprecate the filter, a search on WP Directory showed 0 uses.
* See that the ogp.me namespace is no longer on the HTML attribute.
Fixes #12083
=> Remove the OGP namespace as it's no longer needed

css/src/_wp.scss
* Imports in the Configuration Wizard the scss file containing the `screen-reader-text` class 
Missed in https://github.com/Yoast/wordpress-seo/pull/12531
- go to Configuration wizard > step 3 > click 'Choose image'.
- check the screen reader texts are hidden (see screenshot on the issue #12798)
Fixes #12798
=> Import the accessibility scss file in the Configuration Wizard

inc/class-upgrade.php
* [not-userfacing] Fixes bug where upgrade routine would set the site entity to company when person is selected.
*
* Install Yoast SEO 11.0
* Set site entity (`SEO` > `Search Appearance` > `General` ) to Person.
* Install Yoast SEO 11.1
* Check if site entity is still Person.
Fixes #
=> Fixed upgrade routine

package.json, scripts/bump_monorepo_packages.js
Adds a script with which all monorepo packages can be updated at once.
`yarn bump-monorepo-packages` or `yarn bump-monorepo-packages ${version}`. (e.g. `yarn bump-monorepo-packages rc`)
* _N/A_
* The script tries to update all packages at once (first the dependencies, then the devDependencies). This is faster than every package on its own. If the installation fails, it falls back on updating every package one by one. 
* Run `yarn bump-monorepo-packages` from the root with different version constraints and see if the monorepo packages are all properly updated. 
you can expect output like this:
Fixes https://github.com/Yoast/javascript/issues/238
=> Add script to bump all installed @yoast packages

admin/class-help-center.php
Two translation strings in translate.wordpress.org that can be merged:
* i18n: Merge similar translation strings in help center
*
*
Fixes #
=> i18n: Merge similar translation strings in help center

admin/class-plugin-conflict.php
For consistency across the plugin:
* [OpenGraph](https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/stable/he/default/?filters%5Bterm%5D=OpenGraph&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) - 2 strings.
* [Open Graph](https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/stable/he/default/?filters%5Bterm%5D=Open+Graph&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) - 6 strings.
* i18n: replace OpenGraph with Open Graph (with space)
*
*
Fixes #
=> i18n: replace OpenGraph with Open Graph (with space)

admin/config-ui/class-configuration-page.php
Translation strings in translate.wordpress.org that can be merged:
* i18n: Merge similar translation strings in configuration page
*
*
Fixes #
=> i18n: Merge similar translation strings in configuration page

admin/views/licenses.php
Translation strings in translate.wordpress.org that can be merged:
* i18n: Merge similar translation strings in licenses
*
*
Fixes #
=> i18n: Merge similar translation strings in licenses

admin/class-product-upsell-notice.php
Current string in translate.wordpress.org has two placeholders `%1$s` and `%2$s` that should not be part of the translation string.
This PR replaces the current translation string with the placeholders
`%1$sPlease don't show me this notification anymore%2$s`
with a simpler string without placeholders
`Please don't show me this notification anymore`
See related PR #12776
* i18n: simpler translation string
*
*
Fixes #
=> i18n: simpler translation string

admin/google_search_console/class-gsc-category-filters.php
All the 6 strings can be merged to 1 string with `%s` placeholder:
`Show information about errors in category %s`
Instead of `%s` placeholder we use a category names, this translations string is already exist.
This way we reduce the total amount of translations strings.
* i18n: Merge similar translation strings in gsc category filters
*
*
Fixes #
=> i18n: Merge 6 similar translation strings in gsc category filters to one string

admin/class-help-center.php
Two translation strings in translate.wordpress.org that can be merged:
* i18n: Replace %s with %d to merge similar translation string
*
*
Fixes #
=> i18n: Replace %s with %d to merge similar translation string

admin/class-help-center.php, admin/class-premium-upsell-admin-block.php
Two translation strings in translate.wordpress.org that can be merged:
* i18n: Merge similar translation strings in premium upsell admin block
*
*
Fixes #
=> i18n: Merge similar translation strings in premium upsell admin block

js/src/components/modals/KeywordSynonyms.js, js/src/components/modals/MultipleKeywords.js
* i18n: Merge similar translation strings in `KeywordSynonyms.js` and `MultipleKeywords.js`
* Read more info at: https://github.com/Yoast/wordpress-seo/pull/12783
*
Fixes #
=> i18n: Merge similar translation strings

frontend/schema/class-schema-image.php
When the wp_get_attachment_metadata filter is used and the result is a metadata object without width or height, we don't want to output the width and height in the schema (because we don't know it). Before this fix, we would output `"width":null,"height":null`.
* Fixes a bug where an empty width and height would be outputted in the image schema when there was no retrievable width and height. 
* I've discussed this with @jono-alderson and came to the following conclusions:
* When we don't know the width and the height of the image, we don't want to output them in the schema.
* When we only know the width OR the height, we output neither.
* On trunk:
* In your theme's functions.php, …
=> Don't always output the image width and height

admin/views/sidebar.php
Translation strings in translate.wordpress.org that can be merged:
* i18n: Merge similar translation strings in admin sidebar
*
*
Fixes #
=> i18n: Merge similar translation strings in admin sidebar

admin/views/tabs/metas/paper-content/general/homepage.php
Current:
New:
* i18n: replace `&raquo;` with a period at the end of a sentence
*
*
Fixes #
=> i18n: replace &raquo; with a period at the end of a sentence

admin/config-ui/class-configuration-structure.php, readme.txt
* Removes the Google Search Console from the configuration wizard.
* I've only commented out the step. All things behind it are still in place.
* Go to the config wizard
* See that the GSC step is gone
* Check that there are no console errors in the config wizard when you click through it.
Fixes #12829
=> Removes the Google Search Console from the configuration wizard.

readme.txt
Removes all occurrences of Google Search Console from `readme.txt`.
=> Remove GSC from the readme.txt

js/src/wp-seo-metabox.js
Reverts Yoast/wordpress-seo#12813 for `feature/internal-linking`.
* [non-user-facing] Enables feature-flag functionality for `metabox`.
* Add a new feature-flag feature in your `wp-config`
```
define( 'YOAST_SEO_ENABLED_FEATURES', 'some_feature' );
```
* Add an import for `enabledFeatures()` from `@yoast/feature-flag` and a `console.log` that calls `enabledFeatures()` in the [`Free metabox`](https://github.com/Yoast/wordpress-seo/blob/de6ea6d2e06c37f248d5ff8450b367896446efbf/js/src/wp-seo-metabox.js) to check if `some_feature` is enabled.
=> Add feature flag package import

admin/google_search_console/views/gsc-display.php
Translation strings in translate.wordpress.org that can be merged:
In one string the plugin uses `%s` placeholder, in the other it uses the `Google Search Console` string. The placeholder is not translatable white the string can be translated. Not consistent. The PR removes the `%s` placeholder.
* i18n: Merge similar translation strings in Google Search Console
*
*
Fixes #
=> i18n: Merge similar translation strings in Google Search Console

admin/formatter/class-metabox-formatter.php, admin/statistics/class-statistics-service.php, inc/class-wpseo-rank.php
Three translation strings in translate.wordpress.org that can be simplified:
The old strings:
* `Posts with the SEO score: %1$sgood%2$s`
* `Posts with the SEO score: %1$sneeds improvement%2$s`
* `Posts with the SEO score: %1$sOK%2$s`
The new string:
* `Posts with the SEO score: %s`
Notes:
The plugin already has the following strings: `OK`, `Good`, `Needs improvement`.
This PR actually simplifies the translations strings, merges similar strings and reduce the number of strings. 
* i18n: Split translation strings to simplify translation
*
*
Fixes #
=> i18n: Split translation strings to simplify translation

admin/class-help-center.php, admin/class-premium-upsell-admin-block.php, admin/views/sidebar.php, js/src/components/modals/KeywordSynonyms.js, js/src/components/modals/MultipleKeywords.js
translation strings in translate.wordpress.org that can be merged:
* i18n: Merge similar translation strings in sidebar
*
*
Fixes #
=> i18n: Merge similar translation strings in sidebar

admin/class-help-center.php
All over the code, we see the button `Get Yoast SEO Premium`. In all the places (9 occurrences) the plugin uses standard button text `Get %s`. Only one place is different:
This PR merge similar translation strings. Replacing the string in the screenshot with the standard `Get %s`.
This will further reduce the total number of translation strings. And standardize the button text.
* i18n: Merge similar translation strings - standard button strings
*
*
Fixes #
=> i18n: Merge similar translation strings - standard button text

admin/google_search_console/views/gsc-display.php
* Adds an error notification on the Search Console page.
* Inline HTML, CSS and SVG because this is a quick and temporary patch.
* Go to the `SEO -> Search Console` page.
* Verify you see the notification as per design (and screenshot below).
* Verify the `Read our statement on this, for further information.` link goes to `https://yoa.st/google-search-console-deprecated`.
* The `please visit Google Search Console` link can have 2 different values:
* When you have no integration it should be `https://search.google.com/search-console/index`.
* When you have an active integration it should be `https://search.google.com/search-console/index?resource_id=[SITE URL]`. This can be achieved …
=> Add an error notification on the Search Console page

package.json, webpack/webpack.config.js
* _N/A_
* This makes is so all different bundles can be analyzed, even the ones
we generate to duplicate WordPress behavior.
* Run `yarn webpack-analyze-bundle` to analyze the JavaScript bundles and see 6 browser tabs opened that contain a size analysis of the different bundles.
=> Add webpack bundle analyzer to all bundles

frontend/schema/class-schema.php, readme.txt
* Fixes a bug where using the `$context` argument in the deprecated `wpseo_json_ld_output` filter would result in a fatal error when using PHP 7.1 or higher.
* I've added an empty string because the `$context` parameter in the filter before the deprecation was a string as well.
* Have query monitor installed.
* Add the following to your theme's functions.php:
```
add_filter( 'wpseo_json_ld_output', function( $data, $context ) {
return $data;
}, 10, 2 );
```
Fixes #12846
=> Add missing argument to deprecated filter to avoid fatal error

admin/class-admin.php, admin/class-help-center.php, admin/views/class-yoast-feature-toggles.php, admin/views/sidebar.php, admin/views/tabs/tool/import-seo.php, admin/views/tabs/tool/wpseo-import.php
This PR replaces the `Yoast SEO` string with `%s` placeholder. To match the convention in other translation strings.
* i18n: Move `Yoast SEO` out of translation string
*
*
Fixes #
=> i18n: Move "Yoast SEO" out of translation string

inc/structured-data-blocks/class-faq-block.php
* [not-userfacing] Fixes bug where FAQ output was not shown on the frontend.
*
* See #12868 to reproduce issue.
Fixes #12868
=> Fixed FAQ output

admin/views/tabs/metas/paper-content/breadcrumbs-content.php
Hello,
This patch is to fix the 'Content type archive to show in breadcrumbs for taxonomies' section re-enabling the builtin taxonomies for Category, Tag, Format so users can specify the Blog archive as it's parent.
Without this change the breadcrumbs for these builtin taxonomies aren't able to contain 'Blog' or the parent Blog archive page.
Thanks
* Enable builtin Taxonomies for the 'Content type archive to show in breadcrumbs for taxonomies' section to allow the Blog archive page be added to the breadcrumbs.
* 
* Navigate to the Breadcrumb settings and find the 'Category', 'Tag', 'Format' entries are now present under 'Content type archive to show in breadcrumbs for taxonomies', …
=> Don't suppress builtin taxonomies.

frontend/schema/class-schema-article.php
* Removes redundant `name` attribute from `author` in `Article` schema markup piece.
*
Fixes #12841
=> Remove redundant name

package.json, yarn.lock
* Upgrades `grunt-contrib-compress` to `1.5.0`.
*
* Use `./create-beta` script from `Yoast/Wiki` to build a beta.
Fixes #12828
=> Upgraded grunt-contrib-compress in order to upgrade tar-fs

admin/links/class-link-watcher.php
* Add the `wpseo_should_index_links` filter that can be used to disable the link indexation.
Currently, the link counter feature toggle only disables the UI: the link count columns on the post overview are hidden (as well as the orphaned content filter in Premium). However, all 'calculations' in the background are still done. These could lead to a slow backend as described in #9474. 
The first option was to stop doing those calculations when the feature is disabled and remove the link indexation data from the database. This would lead to a clean database, but would also mean that when a user would disable the toggle temporarily, a complete reindexation of possibly thousands of posts would need to take place when the feature is …
=> Add wpseo_should_index_links filter

frontend/schema/class-schema-context.php, js/src/components/WordPressUserSelector.js
* Fixes an issue where when having the knowledge graph user set as a deleted user it would no longer be possible to change this user. The schema output would be incorrect as well.
* 
* Create a user (`Users -> Add new`).
* Set that user as knowledge graph person (`SEO -> Search Appearance`).
* Delete that user (`Users -> delete under that user`).
* Go to the frontend of a post.
* Ensure you no longer get these errors (only output when `WP_DEBUG` is defined as true):
```
Notice: Trying to get property 'display_name' of non-object in /srv/www/wordpress-default/public_html/wp-content/plugins/wordpress-seo/frontend/schema/class-schema-person.php on line 133
Notice: Trying to get …
```
=> Add safety check around the knowledge graph user

scripts/link_monorepo_to_plugin.js
Don't throw error in case of no-upstream when using yarn link-monorepo but instead display a warning notifying the user of the error and continuing the script.
* Ensure that `yarn link-monorepo` also works on branches that only exist locally.
1. Run `git checkout -b random-branch` in your monorepo location.
2. Run `yarn link-monorepo`, this should give a warning message notifying you that `git pull` was not successful. The script should continue running.
Fixes Yoast/javascript#273
=> Don't throw error in case of no-upstream when using yarn link-monorepo.

scripts/link_monorepo_to_plugin.js
This fixes `yarn link-monorepo` on Windows.
Fixes Yoast/javascript#259
=> Make yarn link-monorepo work on Windows.

frontend/schema/class-schema-person.php
* Fix `Person cannot be publisher` error in Google's Structured Data Testing Tool by making the `Person` node be a `[Person, Organization]` node.
*
Fixes #12822
=> Fix person cannot be publisher

admin/views/tabs/metas/paper-content/general/knowledge-graph.php, frontend/schema/class-schema-organization.php, frontend/schema/class-schema-person.php, inc/class-wpseo-image-utils.php, inc/options/class-wpseo-option-titles.php
* Performance optimization to how we retrieve logo images in schema.
* Add an avatar / logo input field to the settings for Person in the Company or Person choosing.
* Don't show avatars when the discussion settings don't allow it.
* Made sure we store `company_logo_id` and `person_logo_id`, as that's much faster.
* Set site to Person, see the new input field.
* Use it, see the output uses it too.
* Set site to not use avatars (under Discussion), see we don't output anything if nothing is set in the above tested input field.
Fixes #12717
=> Person image fixes

composer.json
Related to https://github.com/Yoast/wordpress-seo-premium/pull/2392
* [non-userfacing] Ignores the premium `tests` folder in the `composer premium-check-cs` command. This is to give us some time to fix the linting errors in the new tests.
*
* Test in combination with https://github.com/Yoast/wordpress-seo-premium/pull/2393 (test instructions are there).
Fixes #
=> Ignore the premium BrainMonkey tests folder for PHPCS for now

js/src/decorator/gutenberg.js
* Fixes a bug where the metabox would be empty when both the classic editor plugin as well as the Gutenberg plugin were installed.
* 
* Install an instance of WordPress `4.9.8` + 5.0 + 5.1 + 5.2.
* For all those versions:
* Check if the metabox is working on a post edit page.
* Check if the metabox is working on a taxonomy edit page.
* Check if the metabox is working on a page edit page.
* Check if the metabox is working on a custom post type edit page.
* Check the same for all installations + classic editor plugin.
* Check the same for all installations + Gutenberg plugin.
* Check the same for all installations + Gutenberg + classic editor plugin.
Fixes Yoast/bugreports#345
=> Fixes metabox when Classic Editor and Gutenberg plugins are active

webpack/webpack.config.js
* Fixes a bug where the metabox would be empty on WordPress versions below 5.0.
*
* Install an instance of WordPress `4.9.8` + 5.0 + 5.1 + 5.2.
* For all those versions:
* Check if the metabox is working on a post edit page.
* Check if the metabox is working on a taxonomy edit page.
* Check if the metabox is working on a page edit page.
* Check if the metabox is working on a custom post type edit page.
* Check the same for all installations + classic editor plugin.
* Check the same for all installations + Gutenberg plugin.
* Check the same for all installations + Gutenberg + classic editor plugin.
Fixes #12950
=> Reverted backport wordpress externals

integration-tests/frontend/test-class-wpseo-opengraph-image.php, integration-tests/test-wpseo-functions.php, tests/watchers/indexable-post-watcher-test.php
* _N/A_
The parent method will automatically be called by PHP/PHPUnit if the `setUp(BeforeClass)()` method is defined in the parent and not in the child, so there is absolutely no need to redeclare the method when all it does is call the parent.
* _N/A_
=> QA: remove useless override methods

frontend/schema/class-schema-article.php
* Don't output author URLs in Schema when author archives are disabled.
* Disable author archives in the Yoast SEO settings, see the author `@id` changes.
Fixes #12718
=> Don't output author URL when those are disabled

admin/taxonomy/class-taxonomy-metabox.php
* [non-userfacing] Removes "Loading Help Center" text from taxonomy pages.
*
* Go to a taxonomy edit page and make sure the help center is gone.
Fixes #12958
=> Remove help center remnants from taxonomy edit pages

tests/TestCase.php, tests/admin/admin-features-test.php, tests/config/admin-test.php, tests/config/database-migration-test.php, tests/config/dependency-management-test.php, tests/config/frontend-test.php, tests/config/plugin-test.php, tests/config/upgrade-test.php, tests/doubles/database-migration.php, tests/doubles/indexable-author-formatter-double.php, tests/doubles/indexable-post-formatter-double.php, tests/doubles/indexable-term-formatter-double.php, tests/doubles/oauth/client.php, tests/doubles/plugin.php, tests/doubles/wpseo-shortlinker-double.php, tests/exceptions/no-indexable-found-test.php, tests/formatters/indexable-author-formatter-test.php, tests/formatters/indexable-post-formatter-test.php, tests/formatters/indexable-term-formatter-test.php, tests/oauth/client-test.php, tests/watchers/indexable-author-watcher-test.php, tests/watchers/indexable-post-watcher-test.php, tests/watchers/indexable-term-watcher-test.php, tests/wordpress/integration-group-test.php
* No user facing changes
Updates the namespaces used in the tests directory to match our standards.
* Run `composer test`. It should pass.
* All namespaces in `tests` should start with `Yoast\WP\Free\Tests`.
=> Fix namespaces in the tests directory

inc/class-wpseo-utils.php, js/src/ui/trafficLight.js
* Set the Traffic Light icon to show grey bullets when the readability and keyword analysis are disabled/
- When the readability and keyword analysis are disabled, `indicator.className` is an empty string so the icon doesn't get a CSS class to show any bullet. Simplest fix: default to `na`.
- The initial CSS class applied to the Traffic Light icon displays bullets with a darker grey. This produced a "flash effect" when the bullets change from dark grey to light grey (see animated GIF below for clarity). As I couldn't think of a reason why the default bullets should be darker, I've changed them to use the light grey, avoiding the flash.
Bullets changing grey on page load:
- disable the readability and keyword analysis
- edit a …
=> Set traffic light icon default to grey bullets.

js/src/wp-seo-help-center.js
* Fixes a bug where following links to page fragments made the Help Center video tab disappear.
Test 1:
- go to any settings page e.g. SEO > General
- open the Help Center by clicking on the "Need Help?" button
- see the first Help Center tab is the Video Tutorial one
- see the loaded video is "General - Dashboard"
- refresh the page
- use the keyboard, navigate pressing the Tab key
- the two WordPress "skip links" appear in the tab order
- activate one of them by pressing the Enter key
- open the Help Center by clicking on the "Need Help?" button
- see the Help Center video tab is still visible and loads the correct video 
Test 2:
- go to (for example) SEO > Search Appearance
- open the Help Center by clicking on the "Need …
=> Fix the Help Center video tab when clicking the skip links.

inc/class-my-yoast-api-request.php
As the response from MyYoast can be as large as 300kb (due to changelogs) - servers in areas that don't have good connection to MyYoast or CloudFlare can hit the timeout limit of 1 second.
* Increased the MyYoast API request timeout from 1 to 5 seconds, to give servers with a less optimal connection to our services more room to fetch the data.
*
*
Fixes #
=> Restore timeout to more than 1 second

tests/TestCase.php, tests/config/dependency-management-test.php, tests/config/plugin-test.php, tests/config/upgrade-test.php
* _N/A_
When PHP encounters an unqualified function call in a namespaced file, it will first try and find the function within the namespace and only when it can not find it in the namespace, fall-back to the global function.
Using fully qualified function names when calling a global function ensures that PHP will bypass the search within the namespace and call the global function directly.
It also ensures that optimal use is made of the PHP7 opcodes on VM level which have been implemented for a select group of PHP internal functions resulting in faster code execution.
Ref: https://www.php.net/manual/en/language.namespaces.fallback.php
* _N/A_
This is a test-code-only change and …
=> [tests] QA: call global functions using a fully qualified name

tests/TestCase.php, tests/admin/admin-features-test.php, tests/config/admin-test.php, tests/config/database-migration-test.php, tests/config/dependency-management-test.php, tests/config/frontend-test.php, tests/config/plugin-test.php, tests/config/upgrade-test.php, tests/exceptions/no-indexable-found-test.php, tests/formatters/indexable-author-formatter-test.php, tests/formatters/indexable-post-formatter-test.php, tests/formatters/indexable-term-formatter-test.php, tests/oauth/client-test.php, tests/watchers/indexable-author-watcher-test.php, tests/watchers/indexable-post-watcher-test.php, tests/watchers/indexable-term-watcher-test.php, tests/wordpress/integration-group-test.php
* _N/A_
A lot of the time, the new tests did used external classes, without importing them with `use` statements.
As it is good practice to always import all classes used within a namespaced file using `use` statements, this has now been fixed.
This is on the one hand about consistency across the classes, on the other hand about documenting which classes are used in a file.
Only one exception is made and that is for the PHP native `Exception` class as using that in its fully qualified form makes it unambiguous whether the PHP native `Exception` class or a userland `Exception` class has been used.
As for the order of the `use` statements, I've listed those as such:
* Functional classes first in alphabetic order.
* Test related …
=> [tests] QA: consistently use `use` statements

tests/config/plugin-test.php
* _N/A_
* _N/A_
This is a test-code-only change and should have no effect on the functionality.
If the tests still run & pass without PHP errors being thrown, we're good (and yes, they do, I tested).
=> [tests] QA: fix typo in method name

tests/doubles/oauth/client.php
* _N/A_
If a class is not used in a file, it shouldn't be imported.
Note: use within documentation or as text strings, for instance for a `instanceOf` test, does not mean the class needs to be imported.
Also: use FQCN name in the documentation.
* _N/A_
This is a test-code-only change and should have no effect on the functionality.
If the tests still run & pass without PHP errors being thrown, we're good (and yes, they do, I tested).
=> [doubles] QA: remove unused `use` statement

src/config/dependency-management.php, src/formatters/indexable-author-formatter.php, src/formatters/indexable-post-formatter.php, src/formatters/indexable-term-formatter.php, src/oauth/client.php, src/watchers/primary-term-watcher.php, src/yoast-model.php
* _N/A_
If a class is not used in a file, it shouldn't be imported.
Note: use within documentation or as text strings, for instance for a `instanceOf` test, does not mean the class needs to be imported.
* Good question... the unit tests covering this code don't throw any errors, so we should be good providing the code is tested in depth. If not, then ask @atimmer or @herregroen how to test this.
=> [src] QA: remove unused `use` statement

src/loggers/logger.php
* _N/A_
As it states in the PHP documentation (emphasis is mine):
> Note that for namespaced names (fully qualified namespace names containing namespace separator, such as Foo\Bar as opposed to global names that do not, such as FooBar), **_the leading backslash is unnecessary and not recommended_**, as import names must be fully qualified, and are not processed relative to the current namespace.
Ref: https://www.php.net/manual/en/language.namespaces.importing.php
* _N/A_
=> [src] QA: removed leading backslash from FQCN in `use` statements

src/yoast-model.php, src/yoast-orm-wrapper.php
* _N/A_
`false` and `true` are a special kind of global constant and using a leading backslash with them is unnecessary.
* _N/A_
=> [src] QA: don't use leading backslash on `false`

tests/config/database-migration-test.php, tests/config/dependency-management-test.php, tests/config/plugin-test.php, tests/formatters/indexable-term-formatter-test.php, tests/oauth/client-test.php
* _N/A_
Best practice: using fully qualified class names in annotations results in unambiguous phpDocs.
* _N/A_
=> [tests] Documentation: use FQCN in docblocks

admin/formatter/class-metabox-formatter.php, js/src/ui/publishBox.js
* Adds links to the SEO and readability scores in the classic editor publish box that make the page scroll to the corresponding analysis in the metabox.
* I combined (1) adding `href`s with hashes to `SEO` and `Readbility` with (2) jQuery scrolling on element click to have both (1) a sensible, a11y-friendly `href` and (2) javascript-based scrolling that can take the admin bar height into account and sets focus.
* Use the classic editor.
* Go to a post, and click 'SEO' in the publish box. It should scroll to the SEO collapsible in the metabox, and open the collapsible. If the collapsible was already opened, it should stay open. Focus should move to the collapsible.
* Change your …
=> Scroll to the analysis when clicking the overall score in the publish box

frontend/schema/class-schema-context.php
* Schema output now uses the "unoverridden" canonical, not the overridden one.
* Set a canonical on the advanced tab of the Yoast SEO metabox.
* See that the Schema output doesn't use that canonical but instead uses the "unoverridden" canonical.
Fixes #12861
=> Use the "true" canonical, not the overridden one

inc/class-wpseo-statistics.php
* _N/A_
This is primarily a bug in WP Core which states that `$found_posts` will be an integer, but then doesn't necessarily ensure that it is
All the same, this bug in WP Core does not need to have any effect in WPSEO and a simple cast to `int` will negate the effect of the bug.
Bug discovered while reviewing the unit tests.
Refs:
* https://developer.wordpress.org/reference/classes/wp_query/
* https://developer.wordpress.org/reference/classes/wp_query/set_found_posts/
* _N/A_
This is a code-only change and should have no significant effect on the functionality.
=> WPSEO_Statistics: bug fix

scripts/link_monorepo_to_plugin.js
Changed 
```javascript
const IS_TRAVIS = process.env.CI === "1";
``` 
to 
```javascript
const IS_TRAVIS = process.env.CI === "true";
```
Add an additional try/catch to have a fallback for when there is no remote branch.
This should be done because we want to test Travis against the same version of the monorepo as we test it locally whenever that is possible. By adding this integration, we ensure that users can enforce this by creating equally named branches on `wordpress-seo` and `javascript`.
* [non-user-facing] Travis should try to checkout the same branch on the monorepo.
**Travis was not doing what we expected it to do. Now, we should be able to check that Travis checkouts the …
=> Add additional logging for travis.

src/watchers/primary-term-watcher.php
* Removed redundant caching call for primary terms.
* Seems that this causes a cache call to say a redis / memcached cache, when there is no database query that it prevents.
=> Remove primary term cache, as it only slows down

inc/options/class-wpseo-option-titles.php, integration-tests/inc/options/test-class-wpseo-option-titles.php
* Fix over-enthusiastic use of `wp_cache` in `WPSEO_Option_Titles`.
* Implemented suggestions by @herregroen in #12570
* Everything everywhere (both in front and backend editing of posts) should keep working as it does.
Fixes #12570 
Fixes #11976
=> fix enrich defaults

inc/class-wpseo-image-utils.php
* Performance optimization: don't try to get an attachment ID for external images.
Fixes #10884
=> Don't try to get an attachment ID for external images

tests/config/plugin-test.php, tests/oauth/client-test.php
* _N/A_
If a class is not used in a file, it shouldn't be imported.
Note: use within documentation or as text strings, for instance for a `instanceOf` test, does not mean the class needs to be imported.
* _N/A_
This is a test-code-only change and should have no effect on the functionality. If the unit tests pass the build, we're good.
=> [tests] QA: remove unused `use` statement

grunt/config/postcss.js
* Update the CSS autoprefixer configuration to drop support for old Internet Explorer versions.
No special testing necessary. This change saves a few KB in the built CSS files.
Fixes #11149
=> CSS autoprefixer drop support for IE less than 11.

js/src/components/contentAnalysis/KeywordInput.js
* Fixes duplicate IDs for the "Focus keyphrase" input field
- build the JS
- edit a post
- open the plugin sidebar
- verify the "Focus keyphrase" input field in the sidebar and the one in the metabox have different IDs
- click on the "Focus keyphrase" **label** in the Sidebar and verify the field below the label gets focused
- verify the same in the metabox
See https://github.com/Yoast/wordpress-seo-premium/pull/2407 for Premium.
Fixes #13002
=> Fix KeywordInput duplicate IDs

yarn.lock
* N/A
* I ran `yarn upgrade grunt-contrib-compress`. Because there was no newer version, it updated grunt-contrib-compress's dependencies and dependecies of dependencies. Fstream was one of them, and has been upgraded to 1.0.12.
* Run `grunt artifact` and see no errors. 
* Upload the artifact.zip as a plugin to your local installation.
* Activate the plugin and see that it works.
Fixes #13063
=> Upgrade fstream to 1.0.12

inc/sitemaps/class-post-type-sitemap-provider.php, integration-tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php, tests/doubles/class-wpseo-post-type-sitemap-provider-double.php
* Fixes missing trailing slash  for the homepage on post sitemap.
* Uses method _WPSEO_Utils::home_url()_ to retrieve the homepage URL for post and page sitemaps.
* Set the homepage to show the latest posts in Settings → Reading.
* Check post and page sitemaps. They should shown same URL for the homepage.
Fixes #12190
Partially fixes #6926
=> Uses WPSEO_Utils::home_url() if home page shows latest posts

integration-tests/admin/test-class-yoast-network-admin.php, integration-tests/capabilities/test-class-register-capabilities.php, integration-tests/framework/class-wpseo-unit-test-case.php, integration-tests/inc/options/test-class-wpseo-option-wpseo.php, integration-tests/inc/options/test-class-wpseo-option.php, integration-tests/inc/options/test-class-wpseo-options.php, integration-tests/notifications/test-class-yoast-notification-center.php
* _N/A_
First off, it looks like this code made it into WP Core as of v 3.5.0, so there is no need to have this duplicate method around.
Secondly, as of PHPUnit 7.0, the upstream method has become private, so this method isn't called anymore.
This is problematic as it means that the test skipping via `@group` annotations will no longer work in combination with PHPUnit 7.0. However, this is a problem which should primarily be fixed upstream in WP Core, not locally in WPSEO.
Ref: https://github.com/sebastianbergmann/phpunit/commit/932238a6a3018cdfac6c2a7d8f1d5d49e65f5dc0
As the test skipping via custom `@group` annotations no longer works as of PHPUnit 7.0, this is a (temporary?) work around.
Instead of relying on the `@group` …
=> [integration-tests] QA: remove the `checkRequirements()` method

.travis.yml, scripts/link_monorepo_to_plugin.js
The automated tests are currently failing because the tests are running on the `master` branch. Due to the changes introduced in #13036, `link-monorepo` now actually tries to checkout the branch on which it is running when run inside Travis. Thus, the link-monorepo script checks out the `master` branch of the monorepo when running the automated tests on the master branch.
This PR can be summarised in the following changelog entry:
* This PR adds an additional environment variable that can be set to allow Travis to automatically set the monorepo branch. If `AUTO_CHECKOUT_MONOREPO_BRANCH` is set to `1`, `link_monorepo_to_plugin.js` will automatically try to checkout a branch based on the branch on which it is currently running.
* #13036 was created to hopefully fix the difference in …
=> Fix automated tests by ensuring that the correct branch is checked out.

src/config/database-migration.php, src/config/dependency-management.php, src/config/plugin.php, src/config/upgrade.php, src/exceptions/no-indexable-found.php, src/formatters/indexable-author-formatter.php, src/formatters/indexable-post-formatter.php, src/formatters/indexable-term-formatter.php, src/loggers/logger.php, src/models/indexable-meta.php, src/models/indexable.php, src/models/primary-term.php, src/models/seo-meta.php, src/oauth/client.php, src/watchers/indexable-author-watcher.php, src/watchers/indexable-post-watcher.php, src/watchers/indexable-term-watcher.php, src/watchers/primary-term-watcher.php, src/wordpress/integration-group.php, src/yoast-model.php, src/yoast-orm-wrapper.php
* _N/A_
Best practice: using fully qualified class names in annotations results in unambiguous phpDocs.
* _N/A_
=> [src] Documentation: use FQCN in docblocks

tests/admin/admin-asset-analysis-worker-location-test.php, tests/config/database-migration-test.php, tests/config/dependency-management-test.php, tests/metabox/metabox-editor-test.php
* _N/A_
When PHP encounters an unqualified constant in a namespaced file, it will first try and find the constant within the namespace and only when it can not find it in the namespace, fall-back to the global constant.
Using fully qualified constant names when using a global constant ensures that PHP will bypass the search within the namespace and use the global constant directly.
Ref: https://www.php.net/manual/en/language.namespaces.fallback.php
* _N/A_
=> [tests] QA: use global constants with a fully qualified name

src/exceptions/no-indexable-found.php, src/formatters/indexable-post-formatter.php, src/formatters/indexable-term-formatter.php, src/loaders/oauth.php, src/oauth/client.php, src/watchers/primary-term-watcher.php
* _N/A_
A lot of the time, the new files within `src` did used external classes, without importing them with `use` statements.
As it is good practice to always import all classes used within a namespaced file using `use` statements, this has now been fixed.
This is on the one hand about consistency across the classes, on the other hand about documenting which classes are used in a file.
Only one exception is made and that is for the PHP native `Exception` class as using that in its fully qualified form makes it unambiguous whether the PHP native `Exception` class or a userland `Exception` class has been used.
As for the order of the `use` statements, I've listed those as such:
* Functional classes first in alphabetic order.
* …
=> [src] QA: consistently use `use` statements

tests/admin/admin-asset-analysis-worker-location-test.php, tests/admin/admin-features-test.php, tests/config/database-migration-test.php, tests/config/plugin-test.php, tests/config/upgrade-test.php, tests/exceptions/no-indexable-found-test.php, tests/formatters/indexable-author-formatter-test.php, tests/formatters/indexable-post-formatter-test.php, tests/formatters/indexable-term-formatter-test.php, tests/metabox/metabox-editor-test.php, tests/oauth/client-test.php, tests/roles/role-manager-factory-test.php, tests/roles/role-manager-test.php, tests/wordpress/integration-group-test.php
* _N/A_
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available have been extended  hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for the new tests in the WPSEO plugin, while keeping in mind that at this time, PHPUnit 5.x should still be supported.
Refs:
* https://phpunit.de/manual/5.7/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* …
=> [tests] QA: use the most specific PHPUnit assertion possible

src/config/database-migration.php, src/config/dependency-management.php, src/config/plugin.php, src/config/upgrade.php, src/exceptions/missing-method.php, src/formatters/indexable-author-formatter.php, src/formatters/indexable-post-formatter.php, src/formatters/indexable-term-formatter.php, src/loggers/logger.php, src/models/indexable-meta.php, src/models/indexable.php, src/models/primary-term.php, src/oauth/client.php, src/watchers/primary-term-watcher.php, src/wordpress/integration-group.php, src/yoast-model.php
* _N/A_
When PHP encounters an unqualified function call in a namespaced file, it will first try and find the function within the namespace and only when it can not find it in the namespace, fall-back to the global function.
Using fully qualified function names when calling a global function ensures that PHP will bypass the search within the namespace and call the global function directly.
It also ensures that optimal use is made of the PHP7 opcodes on VM level which have been implemented for a select group of PHP internal functions resulting in faster code execution.
Ref: https://www.php.net/manual/en/language.namespaces.fallback.php
* _N/A_
This is a code-only change and should …
=> [src] QA: call global functions using a fully qualified name

integration-tests/frontend/test-class-wpseo-frontend-robots.php
* _N/A_
The `WPSEO_UnitTestCase::expectOutput()` method expects two parameters, the first the `$expected` output, the second a `$description` for when the test fails.
The method was being incorrectly called from within this test, causing the unit test to error out on the stricter PHPUnit7,
* If the tests pass in Travis we're good.
=> [integration-tests] QA/PHPUnit 7: fix faulty unit test

src/config/database-migration.php, src/config/dependency-management.php, src/config/plugin.php, src/watchers/indexable-author-watcher.php, src/watchers/indexable-post-watcher.php, src/watchers/indexable-term-watcher.php, src/watchers/primary-term-watcher.php
* _N/A_
When PHP encounters an unqualified constant in a namespaced file, it will first try and find the constant within the namespace and only when it can not find it in the namespace, fall-back to the global constant.
Using fully qualified constant names when using a global constant ensures that PHP will bypass the search within the namespace and use the global constant directly.
Ref: https://www.php.net/manual/en/language.namespaces.fallback.php
* _N/A_
=> [src] QA: use global constants with a fully qualified name

js/src/components/MediaUpload.js, js/src/structured-data-blocks/faq/components/Question.js, js/src/structured-data-blocks/how-to/components/HowToStep.js, js/src/wp-seo-admin-media.js
* Filter the Media Modals to show only images.
Check in the following places:
SEO > Search appearance > Knowledge Graph & Schema.org > Organization > Upload image
SEO > General > Configuration wizard step 3 > Organization > Choose an image
FAQ block > Question > Add image 
How-to block > Step > Add image 
When the media modal opens, check it's displaying only images and not other attachment types.
Fixes #13074
=> Filter the media modals to show only images.

integration-tests/notifications/test-class-yoast-notification.php
* _N/A_
* Made sure skipped tests will always have an explanation on why the test has been skipped.
**Note**: as this skipping of the test applies to a WP version which is no longer supported, it would also be a very valid choice to remove this test skip logic completely.
Let me know if that change is desired.
* _N/A_
* Ok, if you really want to test it:
- Check out the `trunk` branch & make sure your WP install for the unit tests is at WP < 4.2.
- Run `phpunit -c phpunit-integration.xml.dist --verbose` and take note of the notices at the bottom of the run showing why tests are being skipped and two tests not …
=> Tests: improve test skipping

css/src/metabox.scss
* Override CSS rules inherited from Gutenberg that break the Snippet Editor title and description
- install and activate the Gutenberg plugin, current version: 5.9.2 
- on Yoast SEO trunk, edit a post, go to the metabox and open the snippet editor
- see the SEO title and description fields display some unexpected spacing, e.g.:
- switch to this branch and build the CSS
- refresh the page
- see the SEO title and description fields look as expected, e.g.:
Note: a PR has been submitted upstream to better scope the offending CSS selector, see https://github.com/WordPress/gutenberg/pull/16207
Fixes #13145
=> Override CSS margins inherited from Gutenberg.

admin/metabox/class-metabox-section-readability.php, admin/metabox/class-metabox.php, css/src/metabox.scss, grunt/config/eslint.js, js/src/components/contentAnalysis/ReadabilityAnalysis.js, js/src/components/contentAnalysis/ScoreIconPortal.js, js/src/components/contentAnalysis/SeoAnalysis.js
**Note:** After merging this the `feature/horizontal-metabox-tabs` can be merged into trunk.
* Splits the content optimization into two separate SEO and Readability tabs.
* I used React portals to display the readability tab as well as the icons in the tabs.
* Make sure the tabs' appearance are according to https://github.com/Yoast/design/issues/383#issuecomment-492248230.
* That the tabs icon is initially blank is a bug that was introduced prior to this PR.
Fixes #12916
=> Add readability tab.

scripts/bump_monorepo_packages.js
The day before the release, we use `yarn bump-monorepo-packages` to update all monorepo packages in the release branch. Until now, this script updated all packages from the package.json starting with `@yoast` plus a limited list of defined legacy packages. However, we also have a package starting with `@yoast` that is not part of the monorepo: @yoast/grunt-plugin-tasks. 
In https://github.com/Yoast/wordpress-seo/pull/13127/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R51 `yarn bump-monorepo-packages` was used, but as a result, @yoast/grunt-plugin-tasks was updated as well. This meant that changes from that package, which were not tested during RC testing, became part of the 11.4 release. We need to prevent that situation in the feature. 
This PR can be summarized in the following changelog …
=> Don't bump @yoast/grunt-plugin-tasks when updating monorepo packages

css/src/metabox.scss
* [non-userfacing] Metabox tabs: wraps to multiple lines when the screen is not wide enough (starting from the bottom).
* [non-userfacing] Metabox tabs: adds a border and changes the box-shadow.
* After some feedback changed the flow to `wrap-reverse` so the tabs start on the bottom.
* Go to the metabox and play around with the screen size. It should match the design:
* Also check with an RTL language.
Fixes #13123
=> Metabox tabs: responsive, border and other box-shadow

frontend/schema/class-schema-article.php, frontend/schema/class-schema-author.php, frontend/schema/class-schema-context.php, frontend/schema/class-schema-organization.php, frontend/schema/class-schema-webpage.php, inc/class-wpseo-image-utils.php, tests/TestCase.php, tests/frontend/schema/class-schema-webpage-test.php
* Fixes a bug where the `Organization` and `Article` Schema nodes would incorrectly be output when a website had not set their organization's name and/or logo.  
* Codescout: Removed `WPSEO_Schema_Author->determine_schema_id` because it isn't used (I think it was replaced by `WPSEO_Schema_Utils::get_user_schema_id`).
* Added setting the company logo to `WPSEO_Schema_Context` so the `site_represents` is set to `false` when the `Organization` has no name and/or logo.
* Go to your `SEO -> Search Appearance` settings. Set the knowledge graph to `Organization` without a name and logo.
* Check the output of the Schema (use [GSDTT](https://search.google.com/structured-data/testing-tool/) …
=> Remove invalid organization nodes

frontend/class-frontend.php
* Remove the `noindex` from feeds as this causes issues for podcasts and other feeds.
* Check RSS feed, see no `X-Robots-Tag` is set anymore.
Fixes #12857, #10262
=> Remove noindex from feeds

composer.lock
* _N/A_
[PHPCompatibility 9.2.0](https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.2.0) has been released a few days ago.
No update to the version restrictions in `composer.json` needed, but an update of the `composer.lock` file is warranted.
I've done a selective update, updating just the PHPCompatibility package.
* If the build passes, we're good.
=> CS/QA: Update for PHPCompatibility 9.2.0

frontend/schema/class-schema-faq-question-list.php, frontend/schema/class-schema-howto.php, tests/frontend/schema/class-schema-how-to-test.php
* [not-userfacing (only in the release branch)] Fixes a bug where the HowTo and FAQ Schema is not stitched correctly when the site is not represented (company but no name/logo or person with an invalid user account).
*
1. See the issue steps to reproduce.
1. Keep the knowledge graph settings (SEO -> Search Appearance) but update Yoast SEO to the code of this branch.
1. Create a post or page with a HowTo block and publish it.
1. Go to the frontend of that post/page and view the source.
1. Copy the `<script type='application/ld+json' class='yoast-schema-graph yoast-schema-graph--main'>` script content and check it in the [GSDTT](https://search.google.com/structured-data/testing-tool). …
=> HowTo and FAQ Schema: fix errors without an article piece

frontend/schema/class-schema-howto.php, tests/frontend/schema/class-schema-image-test.php
* [non-userfacing] Fixes a bug where the how to step image schema url was `false` when using a proxy server.
*
* Create a test site using `Local by FlyWheel`.
* Create a post with a How To block with a step containing an image and publish it.
* In Local by Flywheel activate the `Live Link` feature.
* Open the provided link and open the post you created on the front end.
* Run the page source through the structured data testing tool.
* Check that the `HowToStep` graph piece has an image object containing a valid url.
* The image should have and `@id` that looks something like this: `http://[domain.com]/#schema-image-[md5-hash]`.
Fixes Yoast/wordpress-seo-premium#2458
=> Fix malformed image schema

admin/taxonomy/class-taxonomy.php
Replaces https://github.com/Yoast/wordpress-seo/pull/13219 because that one was based on trunk.
Fixes Yoast/wordpress-seo-premium#2470
See issue for details.
=> Apply wp_kses_post to allowed html if needed

frontend/schema/class-schema-webpage.php, tests/frontend/schema/class-schema-webpage-test.php
* N/A (fixes a regression).
* Although the original issue was only about pages, I verified with Jono that an author should never be output for everything that is not a post (= pages, attachment pages, etc).
* View the following singular posts/pages and check the schema output:
- Post -> should have author.
- Post with FAQ -> should have author.
- Post with HowTo -> should have author.
- Page -> shouldn't have author.
- Static homepage -> shouldn't have author.
- Custom post type -> shouldn't have author.
Fixes https://github.com/Yoast/wordpress-seo/issues/13224
=> Don't output an author to pages, not even when the site is not represented.

package.json, yarn.lock
* [not-userfacing] Bumps `@yoast/plugin-grunt-tasks` to `1.4.1`.
*
* See the changes in the PR: https://github.com/Yoast/plugin-grunt-tasks/pull/10
Fixes #
Related https://github.com/Yoast/plugin-grunt-tasks/pull/10
=> Bump plugin-grunt-tasks to 1.4.1

frontend/class-frontend.php
* [non-user-facing] Exposes the default SEO title to make sure that we can use it in the internal linking functionality.
*
See [this PR](https://github.com/Yoast/wordpress-seo-premium/pull/2472) for testing instructions.
Fixes #https://github.com/Yoast/wordpress-seo-premium/issues/2464
=> Expose default title to use in internal linking suggestions

inc/class-wpseo-image-utils.php
In `get_absolute_path` remove the concatenation of `DIRECTORY_SEPARATOR` to `$uploads['basedir']` in the `strpos` since this character may not match the character in the `$path`. The DIRECTORY_SEPARATOR in Windows is '\', but the `$path` may contain a forward slash ( '/' ).
I haven't developed an automated test for this simple function change.
* Fixes a bug on Windows filesystems where a PHP filesize warning was raised for image metadata on a post.
*
* On a Linux server, set a Facebook image on the Yoast Social tab for a post.
* Clone the site from the Linux server to Windows by exporting and importing the database
and copying all the files.
* Visit the post. 
Without the fix I get …
=> Fix for issue #10002

admin/links/class-link-columns.php
The `WP_Query::get_posts()` method must not be called several times for the same object, otherwise
the results of the second call may be wrong. This is the case if the query includes several taxonomy terms. 
Here is an experiment to demonstrate the issue that you can do with WordPress without any plugin:
```php
$query = new WP_Query(
array(
'post_type' => 'post',
'tag'       => 'tag1,tag2',
)
);
$query->get_posts();
$query->get_posts();
```
The first corresponding SQL query looks like: 
```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1 AND ( 
wp_term_relationships.term_taxonomy_id IN (127,128)
) AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = …
```
=> Fix WP_Query usage

js/src/wp-seo-analysis-worker.js
* [not-userfacing] Use importScripts inside the worker instead of module imports to replicate webpack external behavior.
* This change ensures that code is not duplicated in the distributed ZIP.
* In Free:
* Go to the edit page. See no console errors.
* Test *all* assessments for posts and make sure the outcomes are as expected. 
* In premium: test all word-form related assessments. 
* Local + video + woo: test all assessments they add.
* Free + premium: Build a zip, see that the zipsize has decreased.
Fixes #
=> Use importScripts inside the worker instead of module imports to replicate webpack external behavior

package.json, yarn.lock
* [not-user-facing] Updates all Yoast packages to the stable release versions for 11.7.
* n/a
* n/a
Fixes #
=> Bump packages for 11.7 release

admin/ajax.php
* I've searched for both `wpseo-replace-vars`, `wp_ajax_wpseo_replace_vars` and `wpseo_replace_vars` in the entire codebase of the Yoast organization on GitHub, and didn't find any uses.
* I also didn't see the ajax request in the Network tab anywhere.
* Test if the replace vars are still working, either in the backend as well as the frontend:
* All fields in the snippet editor on posts, pages, categories, tags, CPTs: check both the replacement in the editor itself, as well as the output on the frontend. Please compare to a previous Yoast SEO version because not all replace vars are functioning correctly.
* All replacevar fields in the …
=> Deprecate unused wpseo_ajax_replace_vars

admin/class-bulk-description-editor-list-table.php, admin/class-bulk-editor-list-table.php, admin/class-bulk-title-editor-list-table.php
*
```
vendor/bin/phpcs -p ./admin/class-bulk-editor-list-table.php --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./
vendor/bin/phpcs -p ./admin/class-bulk-description-editor-list-table.php --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./
vendor/bin/phpcs -p ./admin/class-bulk-title-editor-list-table.php --standard=WordPress --sniffs=WordPress.Security.EscapeOutput …
```
=> Fixed output sanitation errors in PHPCS regarding the bulk editor.

admin/class-export.php
* All error-related things from this class became obsolete in  https://github.com/Yoast/wordpress-seo/pull/4975/files#diff-e9ef37a839756dcbe1e776428c21fb98L97. Therefore, I 
* removed `private $error`
* deprecated `has_error`
* deprecated `set_error_hook`
* I've added `esc_textarea` around `$this->export` to output escape the exported data.
* Go to Yoast SEO > Tools > Import and Export
* Click the `Export settings tab`
* Export the settings.
* Do the same on `trunk`, compare the exports, and see that they are the same.
Fixes #
=> Output escaping class export

admin/class-yoast-alerts.php
*
```
vendor/bin/phpcs -p ./admin/class-yoast-alerts.php --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./
```
Fixes #
=> Fixed CS Error in `class-yoast-alerts.php`

admin/class-admin-init.php
* [non-userfacing] Fix output escaping in `class-admin-init`.
* Added PHPCS ignore to the first error in this file because it uses only hardcoded values.
* Added `esc_url` around the `Shortlinker` URL.
* Removed entries from deprecated notifications because they are too old.
* Refactored long `echo` line to `printf` multiline.
* Replaced `<i>` with `<em>`.
The notice for permalink settings still has to work:
* Go to the WP permalink settings and change it to something that does not include the `postname`.
* Go to the Yoast SEO dashboard.
* Ensure there is now a notice: `You do not have your postname in the URL of your posts and pages, it is highly recommended that you do. Consider …
=> Output escaping: class-admin-init

admin/class-premium-upsell-admin-block.php
* The $identifier and $url are escaped in $upgrade_button on line 76.
* The translation in the $button_text is escaped on line 74.
* Therefore, $upgrade_button on line 102 doesn't have to be escaped anymore, which is why I've added the `@phpcs:ignore`. 
* Navigate to Yoast SEO > General, and verify that the upgrade button at the bottom of the page is still functioning and its id is correct (i.e. contains `premium_upsell_admin_block`). 
Fixes #
=> Add output escaping to $upgrade_button

admin/class-meta-columns.php
* I've added `// @phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Correctly escaped in render_score_indicator() method.`, which can be removed as soon as `render_score_indicator` is added to the list of escaping functions.
* Go to All posts.
* Inspect the score icon, and see that `screen-reader-text wpseo-score-text` is still present and has content.
Fixes #
=> Escape the outputted screen reader text

admin/ajax.php
* Add phpcs:ignore comment above things that are already escaped using `WPSEO_Utils::format_json_encode`.
* N/A
Fixes #
=> Add phpcs:ignore about format_json_encode output escaping

admin/views/licenses.php
* _Improved I18n support_
Fix some output escaping function calls to make sure they use the "translate + escape" variant instead of just escape the (untranslated) text.
On `trunk`:
* Select a non-English language which is 100% translated for your admin interface.
* Go to the `licenses` page and see that four text strings are still in English.
* Switch to this branch and see the difference.
=> QA: make text translatable

css/src/metabox.scss
* Fixe the Snippet Title and Meta fields style for right-to-left languages.
- looks like the `rtl:ignore` control directive doesn't work as expected any longer for imported stylesheets
- two possible causes:
- either `postcss`, which runs before `rtlcss` now strips out the comments e.g. `/*rtl:begin:ignore*/` so the imported file is not ignored
- or maybe related: https://github.com/MohammadYounes/rtlcss/issues/137
This PR seeks to fix the bug by adding an exclamation mark to the comment, as suggested on the [cssnano documentation](https://cssnano.co/optimisations/discardcomments). 
The comments need to be written exactly as follows, without spaces:
```
/*!rtl:begin:ignore*/
@import "../../node_modules/draft-js/dist/Draft"; …
```
=> Fix rtlcss ignore directive for the Draft.js stylesheet.

wp-seo-main.php
This feature flag prevents loading the code in the `src` folder.
The code is currently breaking composer installations, thus we can't ship this way.
This change needs to be merged in the premium release branch to make sure we can acceptance test on Yoast.com
=> Introduce feature flag to prevent loading the code in src

admin/ajax/class-recalculate-scores-ajax.php
* Add phpcs:ignore comment above things that are already escaped using `WPSEO_Utils::format_json_encode`.
```
vendor/bin/phpcs -p --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./ ./admin/ajax/class-recalculate-scores-ajax.php
```
Fixes #
=> Output escaping: class-recalculate-scores-ajax

admin/ajax/class-shortcode-filter.php
* Add phpcs:ignore comment above things that are already escaped using `WPSEO_Utils::format_json_encode`.
```
vendor/bin/phpcs -p --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./ ./admin/ajax/class-shortcode-filter.php
```
Fixes #
=> Output escaping: class-shortcode-filter

admin/links/class-link-reindex-dashboard.php
* Add phpcs:ignore comment above things that are already escaped properly: `message_already_indexed` and `message_start_indexing`.
* Add missing escaping around translation.
* Removed deprecated function instead of fixing it.
```
vendor/bin/phpcs -p --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./ ./admin/links/class-link-reindex-dashboard.php
```
Fixes #
=> Output escaping: class-link-reindex-dashboard

admin/ajax.php, admin/class-yoast-notification-center.php
* N/A: improves output escaping.
* A $notification contains html. An example is: 
`<div class="yoast-alert"><p>Yoast SEO: Local needs a Google Maps browser key to show Google Maps on your website. You haven't set a Google Maps browser key yet. Go to the <a href="http://local.wordpress.test/wp-admin/admin.php?page=wpseo_local#top#api_keys">Yoast SEO: Local API keys page</a> to set the key, or <a href="https://yoa.st/gm-api-browser-key" target="_blank">visit the knowledge base</a> for more information.</p></div>`
* Therefore, I chose for `wp_kses_post`.
* Go to `Yoast SEO > General` and look at the notification center. See that all notifications are still present and look good …
=>  Escape the outputted notifications and add ignore above format_json_encode

admin/class-option-tabs-formatter.php
* N/A Improves output escaping.
* The only place where we use the filter to add a tab is in the search index purge plugin: https://github.com/Yoast/search-index-purge/pull/27/files. All HTML in that file can be used with `wp_kses_post`.
* Install the Search Index Purge plugin.
* Navigate to Yoast SEO > Search appearance > Media.
* See that the entire content from the Search Index Purge plugin is still there. See https://github.com/Yoast/search-index-purge/pull/27/files#diff-3af5e6ebf1e0d76175c1d63505acd3c0R17.
Fixes #
=> Escape the option_tab_content output

frontend/schema/class-schema-webpage.php, inc/class-wpseo-utils.php, readme.txt, tests/frontend/schema/class-schema-webpage-test.php
* Fixes a bug where too many HTML tags were allowed in the description in the Schema output.
* I've allowed the same tags as in https://github.com/Yoast/wordpress-seo/pull/13204/files.
* See https://github.com/Yoast/bugreports/issues/502.
* Also put tags that don't get stripped in the description, for example `<h1>`.
* After this and https://github.com/Yoast/wordpress-seo/issues/13327 have been merged, please create new RCs.
Fixes https://github.com/Yoast/bugreports/issues/502
=> Don't allow all HTML tags in the schema description

css/src/yst_plugin_tools.scss
* [not-userfacing] Makes the inner width of the search appearance's papers are 600px, as before.
*
* Go to Yoast search appearance.
* Check that the papers' elements get moved to the next line just as in `11.7`, see the issue for a screenshot example.
Fixes #13327
=> Adapt the max inner width to match our previous of 600px

frontend/schema/class-schema-author.php
* Fixes a bug where news-article pages and custom post-types included in the news sitemap would not receive an author in their schema.
* Reuse `WPSEO_Schema_Article::is_article_post_type` in `WPSEO_Schema_Author::is_post_author` to avoid applying the same filter twice.
* Include pages in the News sitemap under `SEO` > `News SEO`.
* Create a page and inspect it's schema. Make sure it has an author.
* Note: to properly output article schema you your site has to represent a person or a company including a name and a logo.
Fixes Yoast/bugreports#454
=> Reuse existing apply_filter in class-schema-article.php in class-schema-author.php

admin/notifiers/class-configuration-notifier.php, integration-tests/notifiers/test-class-configuration-notifier.php
* Add missing empty alt attribute to the Configuration wizard onboarding image
Quick PR to fix the Configuration wizard onboarding image:
It misses an empty alt attribute `alt=""`. In absence of an alt attribute, screen readers will try to announce _something_, in most of the cases: part of the image URL, which is far from ideal.
Decorative images just need an empty `alt=""`.
Noticed while working on https://github.com/Yoast/bugreports/issues/400 and validating the HTML source.
=> Configuration wizard onboarding image: Add missing empty alt attribute

inc/class-wpseo-shortlinker.php
This was giving trouble with output escaping
* [non-userfacing] Change the shortlinker's `days_active` from `>30` to `30plus` to avoid output escaping trouble.
* This change has been communicated with Annelieke and Jono (because of UTM tags).
* Use WordPress 4.9.10
* See the issue.
* The notice when you trash a post in free was also broken for the same reason.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2495
=> Change the shortlinker's days_active to not contain HTML characters

config/dependency-injection/container-compiler.php, config/dependency-injection/custom-loader.php, config/dependency-injection/loader-pass.php, config/dependency-injection/services.php, src/builders/indexable-post-builder.php, src/conditionals/feature-flag-conditional.php, src/config/dependency-management.php, src/database/database-setup.php, src/database/migration-runner.php, src/database/ruckusing-framework.php, src/loggers/logger.php, src/loggers/migration-logger.php, src/main.php, src/models/indexable-extension.php, src/models/indexable.php, src/orm/yoast-model.php, src/repositories/indexable-repository.php, src/repositories/primary-term-repository.php, src/repositories/seo-links-repository.php, src/repositories/seo-meta-repository.php, src/watchers/indexable-post-watcher.php, tests/TestCase.php, tests/admin/admin-features-test.php, tests/admin/metabox/metabox-editor-test.php, tests/admin/metabox/metabox-section-additional-test.php, tests/admin/metabox/metabox-test.php, tests/database/migration-runner-test.php, tests/frontend/schema/schema-how-to-test.php, tests/frontend/schema/schema-webpage-test.php
* _N/A_
Variety of fixes:
* Don't backslash prefix the class name in a `use` statement.
* Backslash prefix all global functions and constants.
* Use fully qualified names in docblocks.
* Remove unused `use` statements.
* _N/A_
=> CS: clean up after merges / namespaced files

css/src/metabox.scss
* https://github.com/Yoast/wordpress-seo/issues/13268
* Set `max-width: 800px`
* Edit any post, the Yoast metabox content shouldn't span the whole width
Fixes #
Set metabox max-width to 800px
=> set maxwidth to 800

admin/metabox/class-metabox-section-react.php, inc/class-wpseo-utils.php
* [not-userfacing] Adds aria and data attributes to the filters we use for `wp_kses_post`. This is to support WordPress < 5.1. This affects only the tab content of the React tabs (SEO & Readability) and the collapsible sections, since this is where we currently apply the filters before using `wp_kses_post`.
In WordPress 5.1 support was added for:
- `data-*` attributes: https://github.com/WordPress/WordPress/commit/a0309e80b6a4d805e4f230649be07b4bfb1a56a5
- (a couple of) `aria-` attributes: https://github.com/WordPress/WordPress/commit/32e9dea3ea0a0a27ecae89b40c274420ea49a8ff
As of writing we also support WordPress 4.9.10 and 5.0.4.
* Refactored `display_content` in `metabox-section-react` to surround the content and after_html …
=> Whitelist more attributes in the wp_kses_post filters

inc/sitemaps/class-author-sitemap-provider.php, integration-tests/sitemaps/test-class-wpseo-author-sitemap-provider.php
* Fixes a bug where a 404 error would be shown for half of the author sitemaps in case of multiple author sitemaps.
When the number of authors (users) passes the maximum amount of entries set for a sitemap (offset), the second author sitemap (local.wordpress.test/author-sitemap2.xml) gives a 404.
This PR changes the logic for when an exception should be thrown. Before, we would check if the offset was greater than the number of users (thus an exception should be thrown), but we assumed the `count( $users )` would contain the total amount of users. But it contains the amount of users in the _current offset_.
So if there are `200` users, and the offset is `150`, we would always expect the `count( $user )` to be `200`, in reality, …
=> Fixed user check which caused a false 404

.travis.yml
* _N/A_
When there are several commands within the same condition, Travis will only look at the exit code of the last command to determine whether the build should pass/fail.
For commands not in the `script` section, this is normally not an issue as if something goes wrong there, the commands in `script` will likely fail too.
For the commands in the `script` section, however, we do want the build to fail, so we cannot have more than one command per condition.
The problem condition was the `$COVERAGE` check.
I have now:
* Moved the creating of the temporary directory to `before_script`.
* Split the remaining two unit test run commands and the command to merge the log files each into their own condition. …
=> Travis: only one command per condition

admin/taxonomy/class-taxonomy-fields-presenter.php
This PR replaces https://github.com/Yoast/wordpress-seo-premium/pull/2515 which was accidentally created in premium.
Fixes https://github.com/Yoast/bugreports/issues/514
=> Hide the free social previews in premium

inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-taxonomy-sitemap-provider.php
Add a filter to allow excluding images from XML sitemap.
* Adds a filter, `wpseo_xml_sitemap_include_images`, by returning false, images are excluded from the XML sitemap.
* Chose to implement in two spots as that's easier than refactoring all this code.
*
=> Add a filter to allow excluding images from XML sitemap

inc/sitemaps/class-taxonomy-sitemap-provider.php
Add a filter,  `wpseo_exclude_from_sitemap_by_term_ids`, that allows excluding a term by ID.
* Add a filter,  `wpseo_exclude_from_sitemap_by_term_ids`, that allows excluding a term by ID.
*
=> Add a filter that allows excluding a term by ID

admin/class-social-admin.php, admin/taxonomy/class-taxonomy-metabox.php
* Fixes the duplicate social previews in Premium.
* Used the same logic as for posts/pages.
* On free & premium, check the following:
* On categories, tags, posts, pages and custom post types, check the following:
1. Go to the SEO tab's advanced collapsible. The content should not be empty anymore.
1. Go to the Social tab. The content of the Facebook and Twitter collapsibles should not be duplicated anymore.
Fixes https://github.com/Yoast/bugreports/issues/514
=> Apply the same premium logic for the taxonomy social tabs as for posts

admin/pages/tools.php
* Go to Yoast SEO > Tools. 
* See that the tools and their descriptions are unchanged.
=> Add output escaping to tool desc and attr in admin/pages/tools.php

admin/notifiers/class-configuration-notifier.php, integration-tests/notifiers/test-class-configuration-notifier.php
* Improves the wording in the configuration wizard notification. Props [@emilyatmobtown](https://github.com/emilyatmobtown)
This PR replaces #13253, you can find more information in that PR.
=> Improves wording for the configuration wizard notification

migrations/20190813111111_WpYoastProminentWordIndexableColumns.php, src/models/indexable.php
* Added prominent_words_version column and index to indexables table.
* Added prominent_words_vector_length to indexables table.
* Added a prominent words version index as per https://github.com/Yoast/wordpress-seo/issues/13350#issuecomment-521667771
* Checkout branch, build plugin.
* Go to your VVV wordpress/wp-admin.
* View your database, and verify that the `prominent_words_version` and `prominent_words_vector_length` columns exist (e.g. by viewing the structure tab in SQLPro) and verify that there is an index called `prominent_words_version` too.
Fixes #13350
=> 13350 add internal linking columns to indexables table

inc/class-structured-data-blocks.php
* Adds a filter, `wpseo_enable_structured_data_blocks`, to allow disabling Yoast's Structured Data block editor blocks.
* Use the latest version of granular control plugin, check "Disable Gutenberg blocks" under "General".
=> Add a filter to allow disabling the structured data blocks

admin/formatter/class-metabox-formatter.php, js/src/containers/SnippetEditor.js, js/src/edit.js
If a site icon is set, it will be used as favicon in the snippet preview.
* Enhances the favicon in the snippet preview, uses the site icon as favicon, if set.
* Added the siteIconUrl to the PostScraper and TermScraper store. 
* Mapped the siteIconUrl (as faviconSrc) to the snippet editor component.
* Go to Appearance -> Customize.
* Go to Site identity -> Site icon and upload an icon.
* Add and edit a post.
* Scroll down to the snippet preview.
* Check if the site icon shows as favicon (example screenshot below). 
* Also check if it shows when editing a tag and category.
* Remove the site icon, and check if the default site icon shows in the snippet preview (example below)
* In …
=> Show site icon as favicon in mobile snippet preview

js/src/components/TaxonomyPicker.js
* Fixes a bug where the primary term selector would not display HTML entities properly. Props to [@dlh01](https://github.com/dlh01).
* The use of `lodash.unescape` mirrors the handling of term names in the Gutenberg repo:
https://github.com/WordPress/gutenberg/blob/c148164001ef981c4b903672cb5449da30737a10/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js#L330
https://github.com/WordPress/gutenberg/blob/c148164001ef981c4b903672cb5449da30737a10/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L39-L52
* Follow the replication steps in #13356.
* Observe that the term name displays as expected in step (3) of the replication steps.
Fixes …
=> Apply lodash.unescape to term names in TaxonomyPicker

frontend/schema/class-schema-context.php
Example scenario - Yoast Organization schema is not generated when either the company name or logo is not set in Yoast settings. As a user/theme developer, often name and/or logo is set separately in Theme Options or similar settings. I propose adding a filter for the company name and the company logo to allow developers to filter in Company Name or Company Logo from their options so the user doesn't need to set them in both theme options and yoast options.
*Add filter **wpseo_schema_company_name** - allows filtering Yoast company name setting
*Add filter **wpseo_schema_company_logo_id** - allows filtering Yoast company logo setting
* [x ] I have written documentation for this change.
* [x ] I have tested this code to the best of …
=> Add filter for company_name and company_logo_id

frontend/schema/class-schema-organization.php
* Added filter to modify social profiles (sameAs attribute) in the Oranization schema object.
* Keep naming of 'social profiles' despite sameAs stands for more generic links
* Add the filter `wpseo_schema_organization_social_profiles` and modify the array appending an element.
No UI changes.
- There is no test for Organization
=> Added filter to modify organization sameAs attributes.

frontend/class-frontend.php
* updates robots() to have an echo param like other frontend methods
*
* Verify meta robots tag doesn't render as usual if index,follow
* verify meta robots tag renders correctly if noindexed, etc
* $wpseo_frontend = WPSEO_Frontend::get_instance();
* $robots = $wpseo_frontend->robots( false );
* ensure no echo on page
* var_dump($robots) returns correct robots info
Fixes #13291
=> updates robots() to have an echo param like other frontend methods

admin/class-yoast-input-validation.php
Quick PR to update `@since` notations after https://github.com/Yoast/wordpress-seo/pull/13304
=> Update Yoast_Input_Validation methods since notations.

phpcs.xml.dist, src/repositories/indexable-repository.php
* Adds a method to the Indexable_Repository class that allows simultaneous extraction of multiple indexables by an array of `object_id`s, and `object_type`.
*
* Please see the Premium PR https://github.com/Yoast/wordpress-seo-premium/pull/2521 for testing instructions.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2349
=> Add a method to the indexable repository class to extract multiple indexables with one request

inc/sitemaps/class-taxonomy-sitemap-provider.php
* Add a more specifc filter (`wpseo_sitemap_exclude_empty_terms_taxonomy`) to make the hide or show empty terms decision _per taxonomy_.
* Use the granular control plugin, latest version.
Fixes #
=> Add a more specifc filter to make the hide or show empty terms decision per taxonomy

admin/class-paper-presenter.php, admin/views/paper-collapsible.php, admin/views/partial-alerts-errors.php, admin/views/partial-alerts-template.php, admin/views/partial-alerts-warnings.php, admin/views/tabs/dashboard/dashboard.php, css/src/alerts.scss
* Adds collapsible around the hidden problems and notifications on the Yoast dashboard.
* Fixed a confusing naming convention where the error alerts were called alerts in code, which is also used as the global name of them.
* Adds the `collapsible_header_class` option to the WPSEO_Paper_Presenter. Using this to add the `yoast-alert` class to the header (giving the colored border amongst other things).
* Adds the `paper_id_prefix` option to the paper collapsible view. This is to prevent the hardcoded default of `wpseo` in this case.
* Adds the `dismissed_total` variable to the partial alerts files. Which is used for the issue title translation.
* Moved CSS rules that where specific to the dashboard to clearer classes or ids. There …
=> Add a paper collapsible around the hidden Yoast alerts

admin/class-plugin-availability.php, inc/class-upgrade.php
**NOTE:** If this is not merged before the 12.1 RC's are created, make sure to update the upgrade routine or rebase this on the release branch.
* Removes the AMP Glue plugin suggestion from the SEO dashboard when AMP and Yoast SEO are installed. The AMP Glue plugin by Yoast is being discontinued.
* Reset notifications on upgrade to 12.1 or higher.
* Install `AMP` and `Yoast SEO` plugin.
* Go to SEO dashboard.
* Make the AMP glue plugin is not being suggested.
Fixes #13415
=> Remove AMP glue suggestion notification

admin/class-yoast-dashboard-widget.php, js/src/wp-seo-dashboard-widget.js
* Allows showing specific dashboard feeds based on the wp_version and php_version of a site.
* Go to WordPress dashboard
* Open network tab in inspector.
* See that the url contains the following structure:
yoast.com/feed/widget/?wp_version=`$wp_version`-`$with_classic_editor_active`&php_version=`$php_version`
* Test with classic editor and without.
* If possible, test with two different WordPress versions.
* If possible, test with two different PHP versions.
=> Add wp_version and php_version to the feed request

admin/class-remote-request.php, inc/class-my-yoast-api-request.php
* Changes the `sslverify` argument for remote requests to `true` (the default).
* If you search for `sslverify` you will come across 2 vendor packages. `yoast/api-libs` and the License manager. `yoast/api-libs` Is only used for the Google Search Console which is currently not working due to google disabling the API and the License manager is only for backwards compatibility, therefore we decided to leave these as-is.
* Make sure you are testing this in Premium and you have all add-ons installed.
* Disable transients using the transients manager. 
* Go to the premium page and see that all licenses are still enabled.
Fixes Yoast/bugreports#360
=> Make sure sslverify is true for remote requests

package.json, yarn.lock
* [not-user-facing] Updates all Yoast packages to the stable release versions for 12.0.
*
*
Fixes #
=> Bump package versions for 12.0 release

inc/class-wpseo-replace-vars.php, wp-seo-main.php
Call it on WordPress's `init` to have it run after all the plugins and themes are loaded.
This is to make the extra replacement variables action working again.
* [wordpress-seo-premium] Fixes a bug where custom replacement variables would not be replaced in some implementations.
*
* Add the code to the theme's function.php file (copied from the issue for convenience):
```
// define the custom replacement callback
function get_myname() {
return 'My name is Moses';
}
// define the action for register yoast_variable replacments
function register_custom_yoast_variables() {
wpseo_register_var_replacement( '%%myname%%', 'get_myname', 'advanced', 'some help text' );
}
// Add action …
```
=> Move the WPSEO_Replace_Vars::setup_statics_once call

admin/views/sidebar.php, css/src/yst_plugin_tools.scss, js/src/wp-seo-admin.js
* Fixes a bug where the banners in the sidebar of Yoast SEO were no longer responsive.
* Created a selector called `product-list` to capture the two banners that should appear next to each other. This is the reason that it seems like there are many changes in the `sidebar.php` file, but this is only caused by the indentation.
* Used `flex` to display the two banners next to each other.
* Because the images in the banners are `50px` but contribute to `p`'s width, the text width is calculated as `100% - 50px`.
* When shifting the screen width, the banner text wraps to the next line.
* Hid the submit button container on tabs that have no saveable options.
* Check out this branch, and …
=> 13141 responsive banners sidebar

admin/taxonomy/class-taxonomy-metabox.php
* Add phpcs:ignore comments because the variable is hardcoded.
```
vendor/bin/phpcs -p --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./ admin/taxonomy/class-taxonomy-metabox.php
```
Fixes #
=> Output escaping: admin/taxonomy/class-taxonomy-metabox.php

admin/views/form/fieldset.php, deprecated/admin/config-ui/fields/class-field-profile-url-googleplus.php, deprecated/class-cornerstone.php, deprecated/class-metabox-addon-section.php, deprecated/class-recalibration-beta-notification.php, deprecated/class-recalibration-beta.php, deprecated/class-wpseo-option-permalinks.php, deprecated/class-yoast-form-fieldset.php, deprecated/class-yoast-modal.php
* Deprecated the whole class and related view file because it is not used.
* Replaced other `_deprecated_constructor` calls because I learned this is only for PHP4 style constructors (see commit message).
* Add phpcs:ignore comment instead of fixing it to save time.
```
vendor/bin/phpcs -p --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./ deprecated/class-yoast-form-fieldset.php
```
* Run `composer after-premium-cs`. This reverts the PHP …
=> Output escaping class yoast form fieldset

admin/metabox/class-metabox-section-readability.php
* `display_link`: Moved the HTML out of the replacement variable and into the `printf` format.
* `display_content`: Slight refactor to prevent a "PHPCS ignore" line.
```
vendor/bin/phpcs -p --standard=WordPress --sniffs=WordPress.Security.EscapeOutput --report=full,summary,source --basepath=./ ./admin/metabox/class-metabox-section-readability.php
```
* Build this branch and check the `Readability` tab in the metabox, it …
=> Output escaping: admin/metabox/class-metabox-section-readability.php

admin/metabox/class-metabox.php
* N/A Deprecates do_tab and improves output escaping.
* Deprecating do_tab is a remnant from https://github.com/Yoast/wpseo-video/pull/700/files and https://github.com/Yoast/wpseo-news/pull/518.
* I searched for occurrences in our plugins, which were absent: https://github.com/search?q=org%3AYoast+-repo%3AYoast%2Fprivate-archive+-repo%3AYoast%2Fyoast-release-helper+do_tab&type=Code
* See that the metabox including the News and Video addons are still functioning and no deprecation warnings are being thrown.
Fixes #
=> Deprecate do_tab and add phpcs:ignore about get_content_sections

frontend/schema/class-schema-context.php, frontend/schema/class-schema-organization.php, readme.txt
Renamed filters to use the old `wpseo_` prefix, adjusted documentation changelog and added a changelog item for `wpseo_schema_organization_social_profiles`
* Renamed filters to use the old `wpseo_` prefix, adjusted documentation changelog and added a changelog item for `wpseo_schema_organization_social_profiles`.
*
* Test the filters with the new names instead of the old ones.
Fixes #13452
=> Renamed filters to use the old wpseo_ prefix

inc/class-addon-manager.php, inc/class-my-yoast-api-request.php, inc/class-my-yoast-plugin-installer-skin.php, inc/endpoints/class-myyoast-download-activate.php, inc/endpoints/class-myyoast-download-install.php, integration-tests/inc/test-class-myyoast-api-request.php, tests/inc/endpoints/myyoast-download-activate-test.php, tests/inc/endpoints/myyoast-download-install-test.php, wp-seo-main.php
* Adds the ability to install the addons, in the Yoast SEO plugin, when they are bought via my-yoast.
* I added the `WPSEO_MyYoast_Plugin_Installer_Skin` to make sure no output is given when installing the plugin via the api. 
1. Make sure you are testing in an environment with active subscriptions. For example: `acceptance.test`. Also make sure you have no git repos for our plugins on these repos, otherwise they might get lost while following the test instructions.
1. Navigate to the dashboard and enter `wpApiSettings.nonce` in the javascript console. This nonce is needed when accessing the api endpoints.
1. Remove all other Yoast addons.
1. First of all navigate to …
=> Add install and activation endpoints for addons.

admin/class-config.php, admin/config-ui/class-configuration-storage.php, admin/config-ui/class-configuration-structure.php, admin/config-ui/fields/class-field-company-info-missing.php, admin/views/tabs/metas/paper-content/general/knowledge-graph.php, inc/class-wpseo-utils.php, inc/language-utils.php, js/src/components/CompanyInfoMissing.js, js/src/components/CompanyInfoMissingOnboardingWizard.js, js/src/configuration-wizard.js, js/src/search-appearance.js, js/tests/components/CompanyInfoMissing.test.js, js/tests/components/CompanyInfoMissingOnboardingWizard.test.js, js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap, js/tests/components/__snapshots__/CompanyInfoMissingOnboardingWizard.test.js.snap, tests/TestCase.php, tests/inc/language-utils-test.php, tests/inc/options/option-social-test.php
* Adds an alert when organization information is missing.
* Adds a component for the configuration wizard in order to detect on the fly changes to the company fields.
* On the search appearance in JS: use the existence of the div as toggle whether to show the alert. As all the data is readily available in the view.
* Go to the search appearance settings, general tab.
* Set the knowledge graph to represent an organization.
* The following situations need to be tested (save in between):
1. _No alert_ when the name and logo are set.
1. _Alert_ when the name is not set and the logo is set.
1. _Alert_ when the name is set and the logo is not set.
1. _Alert_ when the name and logo are not …
=> Add alert when organization info is missing

inc/class-wpseo-utils.php
* The `retrieve_enabled_features` function was incorrectly marked as deprecated.
* The function was added below the 'deprecated methods' comment in `WPSEO_Utils`, erroneously marking it as deprecated.
It is now moved above the comment, within the same file.
* 
Fixes #
=> Moves the retrieve_enabled_features function out of the area of deprecated functions

admin/class-help-center.php, admin/views/sidebar.php
* Changes mentions of the Yoast SEO for WordPress training, which is now free.
*
* In the sidebar, the word **`Free:`** (in boldface) should appear before `Yoast SEO for WordPress training`.
* In the help center, the word `free` (not in boldface, see [here](https://github.com/Yoast/wordpress-seo-premium/issues/2530#issuecomment-532133904)) should appear in the text and hyperlink of `Want to be a Yoast SEO expert?`
When merging this PR, please check the relevant boxes in [#2530](https://github.com/Yoast/wordpress-seo-premium/issues/2530).
Fixes [#2530](https://github.com/Yoast/wordpress-seo-premium/issues/2530) (in premium)
=> Mention that training is free

admin/class-yoast-form.php
As discussed and confirmed in #local-seo channel by @luckickken and @omarreiss we decided to remove the colon at the and of the settings form fields.
* [wordpress-seo] Removed the colon from admin form labels
* [wordpress-seo-local] Fixes a regression where admin form labels looked odd, because of the colon.
* Check all the settings pages in Yoast SEO, and see the colon is removed at the end of each label.
Fixes #13499
=> Remove colon from labels in option form fields

admin/class-admin-asset-manager.php, inc/class-wpseo-admin-bar-menu.php
In https://github.com/ampproject/amp-wp/pull/3187 the AMP plugin added support for the new AMP dev mode. This allows normally invalid elements to be exempted from validation when being used in certain contexts, such as when the admin bar is being shown to authenticated users. AMP plugin v1.3 prevents the admin bar CSS from being processed and thus it is not counted against the 50KB limit in the `style[amp-custom]` stylesheet. This PR does the same for the admin bar CSS added by WordPress SEO, which avoids the CSS from being tree-shaken/converted and it prevents it from being counted against the 50KB limit.
The CSS is included in the custom styles:
```html
```
```html
...
<link rel="stylesheet" id="yoast-seo-adminbar-css" href="https://wordpressdev.lndo.site/content/plugins/wordpress-seo/cs …
```
=> Include yoast-seo-adminbar style in AMP dev mode

inc/health-check.php
* Added the basis for adding checks in the WordPress Site Health page.
*
* Create the following class and make sure to run `composer dump-autoload` 
```php
class WPSEO_Example_Check extends WPSEO_Health_Check {
protected $test = 'yoast_test_health_check';
protected $name = 'test_health_check';
public function run() {
$this->label = __( 'Your site failed the test check!' );
$this->status = self::STATUS_CRITICAL;
$this->description = __( 'Lorum ipsum' );
$this->actions = '<a href="https://yoa.st/test-check-failed">Click here!</a>';
}
}
```
* Add the following lines to the end of the `wp-seo-main.php` file
```php
$check = new …
```
=> Adds abstract WPSEO Health Check class

admin/class-plugin-installation.php, admin/views/licenses.php, css/src/extensions.scss, inc/class-addon-manager.php, js/src/components/PluginInstallation.js, js/src/install-plugin/actions.js, js/src/install-plugin/reducer.js, js/src/plugin-installation.js
* Adds a way for plugins to be installed from MyYoast.
* We expect an object from the popup in the following form:
```js
{
success: true,
url: 'http://your-domain.wordpress.test',
plugins: [ 'the-slug' ],
}
```
* Multiple plugins can be installed at once. The texts change based on whether you install one or more plugin at a time. 
MyYoast plugin slugs:
Premium: `yoast-seo-wordpress-premium`
Local: `yoast-seo-local`
News: `yoast-seo-news`
Video: `yoast-seo-video`
WooCommerce: `yoast-seo-woocommerce`
* Link https://github.com/Yoast/javascript/pull/359
* Test plugin installation from URL:
* Go to `/wp-admin/admin.php?page=wpseo_licenses&install_plugins=` + a comma separated list of …
=> Plugin installation flow

readme.txt
* N/A
* I've used the example in https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/ to fix the readme.
* I've changed `=` to `###` in headings we came up with. Only 'official' WordPress headings can have `=` or `==`.
* I've added a newline between the question and the answer in the FAQ.
* Just to be sure, I used increasing numbers in the ordered list.
*
Fixes #12121
=> Fix the heading structure of the readme

admin/class-admin.php, admin/tracking/class-tracking-settings-data.php, admin/tracking/class-tracking.php
Made WPSEO_Tracking an integration.
`should_send_tracking()` now checks for everything that might impact if we should send or not. Default off. Can be enabled through a filter.
=> Let free do the tracking, default off.

grunt/config/aliases.yaml
Because the `artifact` is not needed. Only the zip.
* Removes the `artifact` folder again when running `grunt artifact`.
*
* Run `grunt artifact`.
* Ensure there is no `artifact` folder (where before there would be).
* Ensure there still is the `artifact.zip` file.
Fixes #
=> Add clean:artifact after compress:artifact

admin/views/form/select.php, wp-seo-main.php
* N/A Improves output escaping
* 	Added an ignore comment because $attributes is properly escaped in parse_attribute via get_attributes in class-yoast-input-select.php.
- Not needed. There are no code changes.
Fixes #
=> Add output escaping to select attributes

admin/formatter/class-metabox-formatter.php, inc/class-wpseo-rank.php, integration-tests/test-class-wpseo-rank.php, integration-tests/test-class-wpseo-utils.php
Reverts Yoast/wordpress-seo#13242
The change from 'Not available' to 'Focus Keyphrase not set' in `inc/class-wpseo-rank.php` had some unwanted consequences for the readability scores if they were not available. Since WPSEO_Rank is being used for both the readability score as well as the SEO score, the readability score aria-label in the post overview and the readability scores in the scores export (in Premium) were 'Focus Keyphrase not set'. However, the readability score is not dependent on a keyphrase being set.
Of course, it would be nicer if those two analyses could have their own score strings, but for now we chose for reverting the changes.
=> Revert "Replace 'SEO Available' with more descriptive text"

integration-tests/frontend/test-class-wpseo-frontend-robots.php
* N/A
* N/A
* See the tests pass
Fixes #
=> Fix failing unit test by adding newly introduced robots string

inc/sitemaps/class-sitemaps.php
Make the HTTP headers output before the XML sitemap filterable. Should help team Local fix https://github.com/Yoast/bugreports/issues/564
* Introduces a new filter `wpseo_sitemap_http_headers` which allows filtering the HTTP headers we send for XML sitemaps.
* Decided to move the XML sitemap request hijack to earlier in the process, as that way we are hijacking the request before WordPress sends any HTTP headers.
* This should leave the XML sitemap output unharmed.
=> Move header output to its own function and make it filterable

grunt/config/aliases.yaml
The `wp_deploy` task needs the `artifact` folder. We found this out during the RC process.
The new plan (to be done on `trunk`) is to add the `clean:artifact` as step in the `deploy:trunk` and `deploy:master` tasks (after `wp_deploy` of course). Because it would still be nice to remove the `artifact` folder after releasing to have the environment ready for the next release. This means the `remove artifact folder` step can be removed from the release steps.
* Reverts Yoast/wordpress-seo#13531
*
*
Fixes #
=> Revert "Add clean:artifact after compress:artifact"

frontend/class-frontend.php, src/helpers/current-page-helper.php, src/helpers/taxonomy-helper.php, src/models/indexable.php, src/orm/yoast-model.php, src/presentations/indexable-term-archive-presentation.php, tests/presentations/indexable-term-archive-presentation/presentation-instance-builder.php, tests/presentations/indexable-term-archive-presentation/robots-test.php, tests/presentations/indexable-term-archive-presentation/twitter-description-test.php, tests/presentations/indexable-term-archive-presentation/twitter-image-test.php
* N/A
*
* Set `SEO` > `Search Appearance` > `Taxonomies` > `Categories` > `Show Categories in search results?` to `Yes`.
* Create a new category (use all default SEO settings).
* Visit the category page, make sure there is no robots meta tag.
* Set `SEO` > `Search Appearance` > `Taxonomies` > `Categories` > `Show Categories in search results?` to `No`.
* Create a new category (use all default SEO settings).
* Visit the category page, make sure there is a `noindex,follow` robots meta tag.
* Set `SEO` > `Search Appearance` > `Taxonomies` > `Categories` > `Show Categories in search results?` to `No`.
* Create a new category, and edit it.
* In the Yoast SEO metabox set `SEO` > …
=> Added `generate_robots` for term archive pages

src/presentations/indexable-post-type-presentation.php, src/presentations/indexable-presentation.php, src/presenters/title-presenter.php, src/presenters/twitter/card-presenter.php, src/presenters/twitter/image-presenter.php, src/presenters/twitter/title-presenter.php, tests/presentations/indexable-post-type-presentation/robots-test.php, tests/presentations/indexable-post-type-presentation/twitter-description-test.php, tests/presentations/indexable-presentation/robots-test.php, tests/presentations/indexable-presentation/title-test.php, tests/presentations/indexable-presentation/twitter-title-test.php, tests/presenters/robots-presenter-test.php, tests/presenters/title-presenter-test.php, tests/presenters/twitter/description-presenter-test.php, tests/presenters/twitter/image-presenter-test.php, tests/presenters/twitter/title-presenter-test.php
* N/A
* Implemented `twitter_title`, including unit tests
* Also added unit tests for `title`, since they were missing and `twitter_title` is based on this
* Fixed CS and documentation in unrelated files when I came across problems
* The page source should show an indented `twitter-title` tag with the correct title. This is the example for a simple post:
* When testing, (also) use snippet variables in your `twitter-title`, for example `%%date%%`. Make sure they are output correctly (this example should be output as a formatted date, for example `"September 26, 2019"`).
* You should check whether the `twitter-title` tag is present for the following types of content
* Post 
* Create a …
=> Add twitter title presenter

phpcs.xml.dist, src/loggers/logger.php, src/orm/yoast-model.php, tests/TestCase.php, tests/admin/admin-features-test.php, tests/admin/formatter/term-metabox-formatter-test.php, tests/admin/metabox/metabox-editor-test.php, tests/admin/myyoast-proxy-test.php, tests/admin/roles/role-manager-test.php, tests/admin/watchers/indexable-author-watcher-test.php, tests/admin/watchers/indexable-post-watcher-test.php, tests/admin/watchers/indexable-term-watcher-test.php, tests/frontend/schema/schema-faq-questions-test.php, tests/frontend/schema/schema-webpage-test.php, tests/inc/class-wpseo-content-images-test.php, tests/inc/options/option-social-test.php
* _N/A_
WordPressCS will demand long arrays and forbid the use of short arrays as of WPCS 2.2.0.
See: https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/
For YoastCS, however, a choice has been made to demand short arrays.
For now, while WP 4.9, and therefore PHP 5.2 still needs to be supported, this is only possible in the directories containing files with PHP 5.6+ code.
So in this interim period, we will enforce short arrays in the PHP 5.6+ code and long arrays everywhere else.
Once the minimum supported WP version has moved up to WP 5.2 / PHP 5.6, short arrays will be enforced for all code and the change-over can be done automatically using the auto-fixer included in the relevant sniff.
This PR can be …
=> CS: enforce consistent array format

admin/class-admin-init.php
* Enhances the old WP version notice, by getting and calculating the current and next WP version.
* Added the function "get_latest_major_wordpress_version", which gets the latest WP version.
* Calculates current and next major WP version, to be shown in the old WP version notice.
* Enhances the old WP version notice, by getting and calculating the current and next WP version.
* I imported the latest WordPress version from the 'stable-check' API from WordPress (http://api.wordpress.org/core/stable-check/1.0/).
CR: Please check if this is done safely!
* I converted the JSON object to a PHP object and the PHP object to an array and took the latest wp version from that array. 
* I used `bcadd()` to calculate the next major WP …
=> Makes "old WP version notice" dynamic

.travis.yml, composer.json
* _N/A_
This is the sister-PR to the ruleset update pulled in the Premium repo - https://github.com/Yoast/wordpress-seo-premium/pull/2567.
This makes it so the `premium-check-cs` script will now use YoastCS 1.3.0.
It also ensures that files in the new `/tests/premium/` will be scanned and scanned against the correct PHP version (5.6+).
Lastly, it addresses the previously discussed issue that - as both repos currently still allow warnings -, errors can be hard to find in the report displayed by Travis. So for the Travis runs, CS `warning`s will now be hidden.
* _N/A_
This is a build-script-only change and should have no effect on the functionality.
=> CS: update Premium to use YoastCS 1.3.0

inc/class-upgrade.php
Added the remove_default_from_option function to class-upgrade.php, which can be called on upgrade performs. This enables us to remove defaults from options in the database, for example when they're deprecated and removed, just like the Google Plus defaults.
Removed the 'google_plus_url' and 'plus-publisher' defaults from the social option, via the remove_default_from_option function.
* Fixes a bug where Google+ data would still be exported in the settings export.
* Created remove_default_from_option function, which gets the option, removes a default and uploads it back to the database. Both the option and default are provided via the parameters.
* Called the remove_default_from_option function from the upgrade_123 function, …
=> Add logic to remove defaults from options, remove Google+ defaults

src/integrations/front-end-integration.php, src/presentations/indexable-author-archive-presentation.php, src/presentations/indexable-error-page-presentation.php, src/presentations/indexable-search-result-page-presentation.php, tests/presentations/indexable-error-page-presentation/presentation-instance-builder.php, tests/presentations/indexable-error-page-presentation/robots-test.php, tests/presentations/indexable-search-result-page-presentation/presentation-instance-builder.php, tests/presentations/indexable-search-result-page-presentation/robots-test.php
* Add search result page and error page presentations with robots output.
*
* Go to a search page and ensure that the robots meta has `noindex,follow`.
* Go to a 404 page and ensure that the robots meta has `noindex,follow`.
Fixes #
=> Add search result page and error page presentations with robots output

inc/sitemaps/class-sitemaps.php
* Updates URLs to ping Google and Bing with a sitemap.
*
* URLs can be verified against official documents here:
https://developers.google.com/search/docs/guides/submit-URLs
https://www.bing.com/webmaster/help/how-to-submit-sitemaps-82a15bd4
* Opening the following URLs in a browser confirm that the requested HTTPS versions work as expected:
https://www.google.com/ping?sitemap=https://www.example.org/sitemap_index.xml
https://www.bing.com/ping?sitemap=https://www.example.org/sitemap_index.xml
Fixes #11570
=> Update URLs to ping Google and Bing

admin/metabox/class-metabox.php
* Fixes a bug where a nested paragraph was present in the noindex metabox warning.
* Paragraphs can not be nested according to HTML standards. Replaced the inner element with a span instead of trying to merge the 2 paragraph elements. The latter option would require extra logic.
Copied from https://github.com/Yoast/wordpress-seo/issues/13596
1. Under Settings > Reading, check the "Discourage search engines from indexing this site" box
2. Add a new post, or edit an existing one
3. Scroll to Yoast metabox "advanced" section, ensuring that the "Allow search engines to show this {post type} in search results?" option is set to Yes, and inspect the warning
With this fix, it should read: …
=> Fix nested paragraph in description field

src/context/meta-tags-context.php, src/helpers/robots-helper.php, src/helpers/site-helper.php, src/helpers/taxonomy-helper.php, src/integrations/front-end-integration.php, src/presentations/indexable-presentation.php, src/presenters/open-graph/image-presenter.php, src/presenters/open-graph/site-name-presenter.php, src/presenters/open-graph/title-presenter.php, src/presenters/twitter/card-presenter.php, src/presenters/twitter/title-presenter.php, tests/_mocks/meta-tags-context.php, tests/presentations/indexable-presentation/og-site-name-test.php, tests/presentations/indexable-presentation/presentation-instance-builder.php, tests/presenters/open-graph/image-presenter-test.php, tests/presenters/open-graph/site-name-presenter-test.php
* Implements the OpenGraph site name meta tag via the front-end integration.
* Adds a site helper with the method to get the site name. This differs from the already existing site name in the context object. Created an issue to address this: https://github.com/Yoast/wordpress-seo/issues/13598
* Go to the front-end of a post/page/category/whatever.
* Ensure the head has a meta tag with `og:site_name`. The value should be the same as you have entered in the WordPress settings.
* Adapt your site name and check if it has changed in the front-end.
Fixes #
=> Implements the OpenGraph site name meta tag via the front-end integration

src/presentations/indexable-post-type-presentation.php, src/presentations/indexable-presentation.php, src/presenters/twitter/creator-presenter.php, tests/presentations/indexable-post-type-presentation/twitter-creator-test.php, tests/presenters/twitter/creator-presenter-test.php
* N/A
* Removed support for twitter URLs. Decided internally: https://yoast.slack.com/archives/C5SUKMF2T/p1570517299281300
* Create a new user, only give him a username and a password.
* Set `SEO` > `Social` > `Accounts` > `Twitter username` to be **empty**.
* Create a post with the new user, inspect it, make sure he has not `twitter:creator` tag.
* Set `SEO` > `Social` > `Accounts` > `Twitter username` to be **SiteTwitterHandle**.
* Inspect the post you created with your new user, make sure there is a `twitter:creator` meta tag with the value `@SiteTwitterHandle`.
* Edit your user and give him a twitter handle (without `@`).
* Inspect the post you created with your new user, make …
=> Added presenter and presentation for single page twitter creator metatag

src/helpers/image-helper.php, src/helpers/open-graph/image-helper.php, src/presentations/indexable-presentation.php, src/presenters/open-graph/image-presenter.php, tests/presentations/indexable-presentation-test.php, tests/presenters/open-graph/image-presenter-test.php
* N/A
* Let `get_attachment_url_by_id` return a single URL instead of an entire image data array. 
* Renamed `get_attachment_variations` to `get_best_attachment_variation` to let the name better reflect what the function is doing. 
* Changed the test accordingly
* Added PHP_EOL to the list of `og:image` tags to make sure each of them is printed on a new line.
* Changed the test accordingly
* Go to Yoast SEO > Social > Facebook
* Have open graph enabled
* Upload a default image.
* Write a post without Twitter image, without Facebook image, without featured image, without image gallery and without post content image.
* Inspect the source of the post on the frontend.
* On the feature …
=> Return attachment url instead of entire attachment array

js/src/structured-data-blocks/faq/block.js, js/src/structured-data-blocks/how-to/block.js
* Add 'Google' and 'schema' as keywords to the structured data Gutenberg blocks to make them show up for those search terms in the block search as well.
* I didn't make Google translatable. I posted a question on the Yoast Translate slack to make sure this is the way to go for non-Latin-script languages. 
* Search in the block search on 'Google' and 'schema' and see both of our blocks show up.
Fixes #
=> Add schema and google keyword to Gutenblocks

tests/presenters/open-graph/title-presenter-test.php
* N/A
* Only adds unit tests for open graph title presenter.
*
Fixes #
=> Added tests for open graph title presenter

src/presenters/open-graph/type-presenter.php, tests/presenters/open-graph/type-presenter-test.php
* N\A
* Presentations were already implemented. Only created the presenter.
* Go throught all page types described in https://github.com/Yoast/wordpress-seo/issues/13475#issue-492414675.
* Make sure the corresponding `og:type` tag is output for each page type. But in short, the page type should always be website except for single post pages.
Fixes #
=> Added open graph type presenter

admin/import/plugins/class-import-rankmath.php, admin/import/plugins/class-importers.php, integration-tests/admin/import/test-class-import-rankmath.php, integration-tests/admin/import/test-class-importers.php
* Adds a RankMath post meta value importer.
* Create a new site, create some posts.
* Install RankMath, add some meta data to those posts.
* Activate Yoast SEO, deactivate RankMath.
* Go to Tools → Import → Import from other SEO plugins, it should detect RankMath
* Run the import, see the data is correctly imported.
* Run the clean, see all `rank_math_` prefixed meta values are deleted from the database tables and the plugin no longer finds RankMath to import from.
Fixes #12067
=> Add a rankmath importer

frontend/schema/class-schema-faq-questions.php, frontend/schema/class-schema-howto.php, tests/TestCase.php
* _N/A_
The `wp_strip_all_tags()` function is more comprehensive than the PHP native `strip_tags()` function.
The advantage of `wp_strip_all_tags()` over `strip_tags()` is that it does not leave the content of removed `<script>` and `<style>` tags behind.
> This differs from `strip_tags()` because it removes the contents of the `<script>` and `<style>` tags. E.g. `strip_tags( '<script>something</script>' )` will return ‘something’. `wp_strip_all_tags()` will return ”
It can also remove superfluous whitespace within the string which may be left behind after removing the tags. For this, the second parameter `$remove_breaks` needs to be passed and set to `true`.
Refs:
* https://developer.wordpress.org/reference/functions/wp_strip_all …
=> CS/QA: use `wp_strip_all_tags()` [2]

tests/bootstrap.php
* _N/A_
`opcache_reset()` is a PHP function, not a class.
Ref: https://www.php.net/manual/en/function.opcache-reset.php
* _N/A_
This is a code-only change and should have no (significant) effect on the functionality.
=> Bug fix: use the correct function

.travis.yml
* _N/A_
To get an honest impression about how PHP 7.4 ready the plugin is, the PHP 7.4 build needs to be run against the `trunk` version of WP (WP 5.3) as earlier WP versions weren't ready for PHP 7.4, so you would never get a passing build.
By running against `master`, any failures remaining should be PHP 7.4 issues in the plugin, not in WP itself.
* _N/A_
This is a build-script-only change and should have no effect on the functionality.
=> Travis: run PHP 7.4 against WP master

admin/views/paper-collapsible.php, inc/class-wpseo-utils.php
* [non-userfacing] Adds proper escaping to `paper-collapsible.php`.
*
* Make sure the search appearance pages and the metabox are still working.
Fixes #
=> Escape output in paper-collapsible.php

admin/views/paper-collapsible.php
* Reverts the output escaping of the collapsible paper content.
* There is something going wrong with the filters. Even though those filters should allow `<input>`, `aria-describedby` and more, those elements were still stripped from the $content. We chose to revert this change for now, to fix trunk, but will look in a real solution soon. 
Output differences:
Left: after this revert, right: before this revert.
* Go to the metabox
* Open the social tab
* See the facebook title input, facebook image input, twitter title input and twitter image input.
Fixes #13627
=> Revert the escaping of content collapsible paper because it stripped too much

css/src/yst_plugin_tools.scss
* Adds `inline-block` property to the `wpseo-checkmark-ok-icon` to make sure the text after the checkmark gets aligned properly.
* Please see https://github.com/Yoast/wordpress-seo-premium/pull/2570 for testing instructions.
Fixes #https://github.com/Yoast/wordpress-seo-premium/issues/2560
=> Use inline-block to display ok checkmark

admin/metabox/class-metabox.php
* Fixes a bug where it is impossible to open the media library for social images on attachment pages.
* For attachments the value of `get_queried_object_id ` is always 0 and this results in not enqueueing the media library.
* Go to an attachment page and make sure you can set an image for facebook and twitter.
Fixes #
=> Add fallback for getting the post id

package.json, yarn.lock
Bumps the JavaScript monorepo packages for release 12.3.
=> Bumped Yoast javascript package dependencies after release.

admin/tracking/class-tracking-plugin-data.php, admin/tracking/class-tracking-settings-data.php
* Reduces the amount of settings we track to a whitelist. Reduces the amount of plugin information we track.
* Chose to includelist the settings we want to track.
* Added a filter to extend the includelist.
* Remove the `wpseo_tracking_last_request` option to trigger a new tracking request.
* Inspect the tracking data using Query monitor and compare it to what the current version tracks.
=> Reduce tracking

admin/class-admin-init.php
* N/A
* Use the core transient to get the latest version update instead of sending requests to wordpress.org.
* Change your WordPress version in `wp-includes/version.php` to something old.
* Be sure to visit the updates page to make WordPress check for updates
* You should see a notification in the Yoast notification center that you're not running the latest version.
Fixes https://github.com/Yoast/bugreports/issues/635
=> Use get_core_updates to get the latest major WordPress version

readme.txt
* Increases the required PHP version to PHP5.6, in line with the supported PHP versions of WordPress.
* I've taken the actual patch version from https://wordpress.org/about/requirements/ as we would want to be identical to WordPress in this regard.
* This change is required to make sure people can't install/update Yoast SEO if their PHP version is inadequate.
* N/A
=> Increase minimally required PHP version

src/presentations/indexable-error-page-presentation.php, src/presentations/indexable-home-page-presentation.php, src/presentations/indexable-post-type-archive-presentation.php, src/presentations/indexable-presentation.php, src/presentations/indexable-term-archive-presentation.php, tests/presentations/indexable-error-page-presentation/title-test.php, tests/presentations/indexable-home-page-presentation/title-test.php, tests/presentations/indexable-post-type-archive-presentation/title-test.php, tests/presentations/indexable-post-type-presentation/title-test.php, tests/presentations/indexable-presentation/og-site-name-test.php, tests/presentations/indexable-presentation/og-title-test.php, tests/presentations/indexable-presentation/title-test.php, tests/presentations/indexable-presentation/twitter-title-test.php, tests/presentations/indexable-term-archive-presentation/robots-test.php, tests/presentations/indexable-term-archive-presentation/title-test.php, tests/presenters/open-graph/site-name-presenter-test.php, tests/presenters/open-graph/title-presenter-test.php
* Adds meta tags for `title`, makes `twitter-title` fall back to `og-title`, and makes `og-title` fall back to `title`.
* In consultation with @jdevalk, it was decided to fall back to the option title defaults in case no title is set by the user (rather than using the more complex fallback logic from `class-frontend`).
For `term archive`:
* In the backend you should enter an `SEO title`, an `OG title` and a `Twitter title`
* `Posts` --> `Categories` --> Hoover over a category --> `Edit` --> `Edit snippet` --> `SEO title`
* `Posts` --> `Categories` --> Hoover over a category --> `Edit` --> `Social` --> `Facebook title`
* `Posts` --> `Categories` --> Hoover over a category --> `Edit` …
=> All remaining title metatags

admin/class-yoast-form.php, admin/views/tabs/social/twitterbox.php, css/src/toggle-switch.scss
A notice about Twitter using OpenGraph was added to the Twitter social tab (in [this](https://github.com/Yoast/wordpress-seo/pull/13635) PR). To make sure the label of the light switch below it stands out, a `strong` parameter was added to the light switch component. 
For more info on this decision, see: https://github.com/Yoast/wordpress-seo/issues/13631#issuecomment-542170823
* See #13631 for the initial issue.
* See #13635 for the PR about the Twitter OpenGraph notice text.
* Adds OpenGraph notice to the user in the Twitter social tab. Props to @stevenfranks.
* The strong parameter was added to the light switch component, so it would stand out with a text above.
* See that the …
=> Added "Strong" parameter to Light Switch component

src/presentations/indexable-post-type-presentation.php, tests/presentations/indexable-post-type-presentation/title-test.php
* Fixes a bug where no title meta tag was output for posts and pages in case the `SEO title` field was empty in the backend
* In case the `SEO title` field is empty at the level of a specific post or page, and also is empty in `Search appearance` --> `Content Types` --> `Posts`/`Pages`, we now output the installation default title.
* Set a 'post-specific' `SEO title` (in the snippet editor)
* Check whether a 'general' `SEO title` is also set in `Search appearance` --> `Content Types` --> `Posts` (if not, set it)
* In the frontend, check whether the post-specific title is output under the `title` tag
* Now delete the post-specific title in the backend
* In the …
=> Show installation default title when SEO title is not set for posts

admin/class-config.php
* Removes unnecessary API calls related to the Local SEO upsell on the search appearance settings page.
* Instead of checking for an active license, we now check for an active plugin. 
* Use Free, not Premium.
* Don't have Local SEO active.
* Go to the search appearance page.
* Set your Knowledge graph to Organization
* See the Local SEO upsell.
* Install and activate Local SEO.
* See no Local SEO upsell on the search appearance page.
Fixes https://github.com/Yoast/bugreports/issues/649
=> Don't check for active local license but for active local plugin

src/generators/schema/article.php, src/generators/schema/webpage.php, src/helpers/date-helper.php, src/presentations/indexable-post-type-presentation.php, tests/generators/schema/article-test.php, tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php, tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php, tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
* Implements a date helper to wrap mysql2date.
* I've replaced all occurrences of `mysql2date` in the `src` folder by `mysql_date_to_w3c_format` from the new date helper class.  
* See that the tests still pass in Travis.
Fixes #
=> Add date helper to wrap mysql2date

css/src/admin-global.scss, css/src/yst_plugin_tools.scss
Needed for this PR: https://github.com/Yoast/javascript/pull/378
*  Improves custom form controls styling for consistency with the new WordPress 5.3 admin styles.
* This PR fixes only the _heights_ of some input fields: borders and focus style will need a decision bt product
* Fixes also the styling of the upsell box "close" button
* Please refer to the screenshots on the related issue https://github.com/Yoast/bugreports/issues/642
- this PR needs to be checked on both WordPress 5.3 RC and on WordPress 5.2
- the CSS changes in this PR aim to make things look the same on WordPress after and before the WP admin CSS changes
- switch the JavaScript repo to the …
=> Adjust custom form controls styling for WP 5.3.

admin/taxonomy/class-taxonomy.php
Fixes a bug when working in a MultilingualPress environment and editing the Snippet Preview's values (including the keyword) for a *term*. Before this fix, any changes made would be synced across all additional languages.
* Fixes a bug for terms where keywords and snippet preview data would be synced across all languages in a MultilingualPress multisite environment.
* The reason that we need to add this is due to limitations within WordPress and its handling of data across multiple sites in a multisite environment. This isn't necessarily an issue with MLP itself; Every plugin that runs in a multisite environment can potentially have similar issues.
*Note: To acquire a copy of MLP, …
=> Added ms_is_switched check to terms

admin/class-export.php, admin/views/tabs/tool/wpseo-import.php, admin/views/tool-file-editor.php, css/src/yst_plugin_tools.scss
- https://github.com/Yoast/bugreports/issues/623
- adds missing label to the export settings textarea
- makes the import settings textarea label visible
- changes the import settings description text by merging into it some text that was used for the visually hidden label
- associates the descriptions to the textareas with `aria-describedby`
- adds a 8px bottom margin to the `yoast-inline-label` CSS class
- makes the robots.txt and htaccess textarea labels use the same bottom margin for consistency
- go to SEO > Tools > Import and Export
- on the Import settings tab: see the new text description
- click the textarea label and verify the textarea receives focus
- on the Export …
=> Improve the import and export settings textarea labels and descriptions.

src/helpers/robots-helper.php, tests/helpers/robots-helper-test.php
* N/A
*
* Set the noindex and nosnippet value for a post and verify that the additional robots values are rendered.
Fixes #
=> Adds logic for having the values in case of noindex and nosnippet

js/src/components/WordPressUserSelector.js
* Improved the Configuration Wizard user selector styling for better compatibility with WordPress 5.3.
*
- built all the things
- go to SEO > General > Configuration Wizard > step 3
- choose "Person": the user selector appears
- verify its height is the same as in WordPress 5.2
- click it
- verify the focus style looks like in WordPress 5.2 
Screenshot before:
Screenshot after:
Fixes https://github.com/Yoast/bugreports/issues/658
=> Adjust the Configuration Wizard user selector styling for WP 5.3.

admin/taxonomy/class-taxonomy.php
Fix for PR https://github.com/Yoast/wordpress-seo/pull/13676
* Fixes a bug where saving taxonomies would result in a fatal error in non-multisite environments.
*
* Go to a single-site environment.
* Checkout trunk.
* Edit a taxonomy and save it.
* Observe the fatal error.
* Edit a taxonomy and save it.
* Observe there is no longer a fatal error.
You could check if the original PR implementation still works. See the test-instructions there https://github.com/Yoast/wordpress-seo/pull/13676
Fixes #
=> Fix fatal by adding multisite check

composer.json
*
* Adds the `premium/src` folder to the phpcs checks for 5.6 and explicitly ignores it for the 5.2 tests
*
Fixes #
=> Add premium/src folder to rules in premium-check-cs script

tests/repositories/indexable-repository-test.php
* Adds the missing indexable date archive builder mock argument to the tested indexable repo.
* Makes sure that the wpdb mock is properly initialized when no global wpdb exists yet.
* Renames the test class to Indexable_Repository_Test.
*
* Run the PHP tests on free (by running `composer test`).
* Check that no tests fail.
Fixes #
=> Fixes the indexable repository tests.

src/builders/indexable-home-page-builder.php, src/builders/indexable-post-builder.php, src/builders/indexable-term-builder.php, tests/builders/indexable-home-page-builder-test.php, tests/builders/indexable-post-builder-test.php, tests/builders/indexable-term-builder-test.php
* N/A
*
* Set a twitter image for a post and verify in the indexables db table that the twitter_image_id is set.
* Do the same for a term
* Set an opengraph image for the homepage and make sure that in the record (db) for the homepage indexable the og-image-id is set
Fixes #
=> Make sure twitter image id is set when building indexable

css/src/admin-global.scss
* Fixes a bug where the size of select2 input boxes would not increase in WordPress 5.3 when zooming in in Firefox.
* This CSS ensures that the 28px height of select2 inputs is only overwritten on wordpress-seo and wpseo-local admin pages.
* See #13722 
Fixes #13722 
In case of questions, please ask @rubsel. I merely put his code in this PR.
=> Fix the height of select2 inputs when zooming in in WP 5.3

js/src/analysis/classicEditorData.js
* Fixes jQuery assignment after https://github.com/Yoast/wordpress-seo/pull/13692
- There was a missing assignment for the `$` alias, added `const $ = jQuery;`
- With Classic Editor activated this was causing the meta box to not render
- to reproduce the error on release/12.4: activate the Classic Editor plugin
- edit a post
- see the meta box doesn't render
- console error in Chrome: `classicEditorData.js?7ad1:101 Uncaught TypeError: $ is not a function`
- switch to this branch and build
- edit a post (maybe refresh)
- see the meta box renders correctly
- test setting / removing a featured image and check everything works as expected
=> Assign jQuery to its $ alias.

js/src/analysis/classicEditorData.js
Fixed bug where snippet preview image was set to content image when featured image was set
* N/A
*
In the **classic editor** and **Gutenberg**
With **storefront** and **twentynineteen** theme.
For **post** and **term** edit pages.
* Add a featured image.
* Mobile snippet preview image should be the featured image.
* Add a content image.
* Make sure the mobile snippet preview image is not overwritten with the content image.
Fixes #
=> Fix snippet preview image bug.

frontend/class-twitter.php, integration-tests/frontend/test-class-twitter.php
* N/A
*
* Make sure the twitter:site tag is no longer rendered in the frontend.
Fixes #
=> Remove the functionality regarding Twitter site

inc/class-upgrade.php
* N/A 
*
* Have a Yoast SEO version <= 10.0 installed 
* Run the following code:
```php
$option = get_option( 'wpseo_social' );
$option['google_plus_url'] = 'plus-url-doesnt-matter';
$option['plus-publisher']  = 'plus-publisher-and-so';
update_option( 'wpseo_social', $option );
} );
```
* Check in the DB if the values are set
* Run the upgrade routine
* Check if the two options are removed correctly.
Fixes #
=> Call the method the right way

css/src/admin-global.scss
Mobile fix for https://github.com/Yoast/wordpress-seo/pull/13736
* N/A
*
* Please check the dashboard banner.
* Resize your browser window. Ensure the banner remains visible.
Fixes #
=> Fix banner for mobile

inc/class-upgrade.php
* When theme has `title-tag` support and the forcerewritetitle option is enabled, we should disable it.
*
* Put the next line of code somewhere in your WordPress installation:
```php
WPSEO_Options::set( 'forcerewritetitle', true );
} ); 
```
* Check in your database if the option is set correctly (table `wp_options` where the `option_name` is `wpseo_titles`).
* Remove the code you added above.
* Run the upgrade routine
* Check the option value for `forcerewritetitle` is set to false.
Fixes #
=> Disables the forcerewritetitle option

admin/class-admin-init.php, inc/class-upgrade.php
* Removed the WordPress update notice, because it is no longer needed after WordPress 5.3 has been released.
*
* Check out `trunk` and build.
* In `class-admin-init.php` in `wordpress_upgrade_notice` replace `global $wp_version;` by `$wp_version = '4.9'`.
* Go to the SEO dashboard and make sure the notification is present.
* Undo the change.
* Check out `13747-remove-wp-update-notice` (this PR's branch) and build.
* Install the `Yoast test helper`, and trigger the upgrade routine by setting `Yoast SEO` version to 12.3 and saving. 
* Check if the notification is gone in the SEO dashboard.
Fixes #13747
=> Removed WordPress update notice

migrations/20191029111111_WpYoastProminentWordIndexableColumn.php, src/models/indexable.php
* Adds a migration for the `prominent_word_version` column on `indexable`
*
* Remove the columns `prominent_word_version` and `prominent_word_vector_length` from the `wp-yoast-indexable` table of the database of your local WP site [if you have those].
* Remove the migration `20190813111111` from the list in `wp_yoast_migrations`[if you have it].
* Check out the `feature/indexables-frontend` branch.
* Open any page in your local environment (e.g., Post Editor).
* Verify that there is no column `prominent_word_version` in the `wp-yoast-indexable` table of the database.
* Remove the columns `prominent_word_version` and `prominent_word_vector_length` from the …
=> Add a migration for prominent word indexable column

frontend/class-frontend.php, integration-tests/frontend/test-class-wpseo-frontend.php, src/integrations/front-end/indexing-controls.php, tests/integrations/front-end/indexing-controls-test.php
* N/A
* Go to the frontpage of your installation and in the meta widget you should have a login or logout link. Verify this one has the `rel="nofollow"` attribute.
* The other one is tricky, you have to be a robot to test this. Are you 3CPO? Maybe you can ask Bassie and Adriaan to help you.
* I would test this by reversing the if-statement in the code. Go to the line that says `! is_robot()` and change it to `is_robot()` and check if you have the header. This can be done by checking the network tab in the webmaster tools.
=> Add indexing controls integration

inc/class-wpseo-utils.php, src/conditionals/wpml-conditional.php, src/integrations/compatibility/wpml.php
Moves the `WPSEO_Utils::get_home_url()` method to an integration, as this method is only necessary if WPML is installed.
* Moves the `WPSEO_Utils::get_home_url()` method to an integration.
* This is purely a move of some code and doesn't change any of the workings.
**Please note: We have a login for WPML in the LastPass shared-licenses vault**
* Ensure that the tests pass.
**Testing the 'moved' filters**
* Ensure you have added `define( 'YOAST_SEO_EXPERIMENTAL_PHP56', true );` to your `wp-config.php`.
* Ensure you have an environment running with WPML and have a primary and secondary language configured.
* First, add the following snippet to your theme's `functions.php`: `var_dump( …
=> Move wpml filter to integration

tests/admin/admin-asset-analysis-worker-location-test.php, tests/admin/admin-features-test.php, tests/admin/metabox/metabox-test.php, tests/admin/myyoast-proxy-test.php
* _N/A_
`@covers ClassName::<!public>` means that a test covers the methods in a class that are _not_ public.
Most of these tests are actually testing `public` methods, so the indicator is incorrect. Aside from that that, `<!public>` without class or `::` is incorrect as an annotation and PHPUnit has been complaining about this for a while (see detailed Travis output).
* _N/A_
=> Tests: remove incorrect `@covers` tags

tests/inc/options/option-social-test.php
* _N/A_
The tags were referring to a class which didn't contain the method being tested.
* _N/A_
=> Tests: fix incorrect `@covers` tags

js/src/wp-seo-analysis-worker.js
* Fixes the dev server
The dev server was broken after the importScripts were introduced.
This was because the web worker would sometimes be loaded in a blob.
When loaded in a blob `self.location.href` is the blob URL and the
URLs of the other URLs cannot be deduced. The `createWorker` method
now adds a global variable `yoastOriginalUrl` so we can use that
instead of `self.location.href`.
* Make sure the dev server works.
Needs to be tested together with https://github.com/Yoast/javascript/pull/391
Fixes #13367
=> Fixes the dev server with YoastSEO.js

src/generators/schema/faq.php, src/generators/schema/howto.php
I fixed two problems;
- The HowTo block missed some `isset` checks, which caused warnings.
- The Faq block wasn't properly getting the questions, because we didn't check inside the block container.
* Fixes a bug where a notice would be thrown when fields in the FAQ or HowTo blocks were left empty.
* For the HowTo block:
* Added checks to assure all required keys exist. If not, `return`.
* For the Faq block:
We were looking for the `questions` in `$context->blocks['yoast/faq-block']['attrs']['questions']`, while the blocks are put in a block container (by us). So we should be looking in `$context->blocks['yoast/faq-block'][$blockNumber]['attrs']['questions']`. I changed the function, so we now loop through the …
=> Fixes empty faq and howto errors

frontend/class-opengraph.php
Fixes a bug where where the needle in a strpos() check is empty, which causes a PHP Warning.
This commit attempts to fix #13795 by checking that $unpaged_url is not empty before using it as the needle in a `strpos()` check.
* Fixes a PHP Warning when using an empty string as the needle in a strpos() check. Props [Chris Thompson](https://github.com/ChrisThompsonTLDR).
*
*
Fixes #13795
=> Fixing a bug where the needle for strpos

admin/metabox/class-metabox.php, css/src/admin-global.scss
* Improved form controls alignments after CSS changes in WordPress 5.3.
- on large screens:
- input fields have a 28 pixels height vs. the 30 pixels height from core
- this way they have the same height of buttons and selects
- on small screens:
- input fields have a 32 pixels height vs. the 40 pixels height from core
- this way, they have the same height of buttons and selects
- I also added a missing space between an image input field and its upload image button
- build the CSS
- enable Yoast SEO and Yoast SEO: Video
- check input fields and buttons alignments look OK, for example:
- metabox > social > Facebook > Facebook Image
- metabox > video > Video Thumbnail
- SEO > Social > Facebook > Frontpage settings > Image URL
- SEO …
=> Adjust input fields heights after WordPress 5.3 CSS changes.

src/helpers/robots-helper.php, src/integrations/front-end-integration.php, src/presentations/indexable-presentation.php, src/presenters/googlebot-presenter.php, tests/helpers/robots-helper-test.php, tests/presentations/indexable-presentation/googlebot-test.php, tests/presentations/indexable-presentation/robots-test.php, tests/presenters/canonical-presenter-test.php, tests/presenters/googlebot-presenter-test.php, tests/presenters/robots-presenter-test.php
* N/A
* Also added a missing unit test to `robots-presenter-test` and fixed codestyle in `canonical-presenter-test`.
* In the frontend, see that the `googlebot` meta tag is rendered with the following content: `max-snippet:-1,max-image-preview:large,max-video-preview:-1`.
* See that the `robots` meta tag renders the historical logic (e.g., `noindex`, `nofollow`, etc.), but not the content that now resides with `googlebot`.
Fixes #
=> Create google robots meta tag

admin/metabox/class-metabox.php, inc/class-wpseo-meta.php, integration-tests/test-class-wpseo-meta.php
* Removes the `Site-wide default: None` and the `None` options from the `Meta robots advanced` field in the metabox. 
*
* In `trunk`, see that the `Meta robots advanced` field in the post metabox contains the options `Site-wide default: None` and `None` (and three other options which will remain unchanged).
* Choose `Site-wide default: None` and update.
* Also see that the `Meta robots advanced` description is below the options field and contains this text: "Advanced `meta` robots settings for this page."
* See that the `Meta robots advanced` field is now empty.
* When clicking on the `Meta robots advanced` field, see that both `Site-wide default: None` and …
=> Remove (site-wide default) None from the meta robots advanced field

css/src/alerts.scss
* Fixes a bug where the notification center dismiss and restore buttons had no focus style.
- I'd like to propose to use the "rounded focus style" that is an established pattern in WordPress, see screenshots below
- before this patch
- go to SE) > General
- make sure you have Problems and Notifications showing up in the Notification center
- use the Tab key to navigate
- observe there's no focus style on the dismiss and restore buttons (the ones with the eyes icons)
- build the CSS
- repeat the steps above
- see the new focus style
- check the buttons can still be clicked with mouse and activated with keyboard
- check there are no layout glitches in the responsive view
Fixes …
=> Implement focus style for the notification center buttons

.travis.yml, composer.json, composer.lock, wp-seo-main.php
* _N/A_
Includes:
* Removing builds against PHP < 5.6.
* Adjusting the Travis matrix for dropped support of WP < 5.2.
* Adjusting the conditions for setting up the test environment to be environment variable based instead of PHP version based.
* Using the composer scripts to run various tasks.
* Removing the `xrstf/composer-php52` dependency and references to the  `vendor/autoload_52.php` file.
Also:
* Travis hasn't supported `sudo` for quite a while now, so removing it.
* And removing the `WP_VERSION` environment variable from the PHP 7.2 build.
This build doesn't need the WP environment as it doesn't run the PHP unit tests.
Related to https://github.com/Yoast/wordpress-seo/issues/13758 …
=> Stop explicit support for PHP < 5.6 /  WP < 5.2

package.json, yarn.lock
* Bumps the `search-metadata-previews` and `yoast-components` packages for 12.6-RC2
*
*
Fixes #
=> Bump monorepo packages for 12.6 RC2

inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps.php
* Don't render sub sitemaps if CPT isn't public.
* Throw an exception when the sitemap page requested isn't public _post_type_.
* Replace [get_post_types](https://developer.wordpress.org/reference/functions/get_post_types/) with _WPSEO_Post_Type::get_accessible_post_types()_.
* Add the code from issue #13862 to have private custom post type.
* Check sub sitemap - it should return 404.
Fixes #13862
=> Fixes private CPT in sitemaps

inc/sitemaps/class-sitemap-image-parser.php
* Optimize parsing gallery's shortcode with "lighter" regular expression. This solution is faster and it supports a case if gallery's shortcode is nested in other shortcodes. Use same "content" for parsing HTML images and gallery's shortcode.
* Since WP 4.4, _$tagnames_ is added as the parameter to the function [_get_shortcode_regex_](https://developer.wordpress.org/reference/functions/get_shortcode_regex/).
* Create simple shortcode (add following code into functions.php) which is simulation of  a "page builder":
```php
add_shortcode( 'my_content', function( $atts, $content = null ) {
return '<div class="my_content">' . do_shortcode( $content ) . '</div>';
}
);
```
* Create simple …
=> Optimize parsing gallery shortcode in sitemaps

admin/class-admin-asset-manager.php, admin/class-admin.php, admin/class-helpscout.php, js/src/help-scout-beacon.js, webpack/paths.js
* Introduced a HelpScout beacon as a replacement for the Help Center.
* 
* Go to the Yoast SEO settings, there should be a help scout beacon button on the bottom right of all the pages.
* Pay some extra attention to the pages with a sidebar, as the button should not be on top of the sidebar.
* When you click the `?` button, you should get a browser confirmation question.
* When you click cancel, nothing should happen.
* When you click confirm, the button should be replaced by the actual HelpScout button. The HelpScout beacon should open up too.
Not really implemented in this PR, but might be good to know/test when seeing this:
* When testing with an addon, the addon pages should not …
=> Implement HelpScout consent button

admin/tracking/class-tracking.php
We currently send tracking info for every site in a multisite instance, that's a bit nonsense.
* None needed.
* Used `is_main_site` which returns true on single site all the time.
*
Fixes #
=> Only send tracking info on the main site of a multi site install

js/src/help-scout-beacon.js
* N/A
*
* For developers:
* Merge this branch in `wordpress-seo-premium` `release/12.6` branch.
* Make sure ads are shown by disabling the subscription check in `class-yoast-form.php` on line 209.
* Go to the SEO dashboard, make sure the help scout button doesn't overlap the ads.
Fixes Yoast/wordpress-seo-premium#2619
=> Fixed overlapping of help scout beacon on pages iwth ads

admin/formatter/class-post-metabox-formatter.php, frontend/class-breadcrumbs.php, frontend/class-opengraph.php, frontend/schema/class-schema-article.php, frontend/schema/class-schema-webpage.php, inc/class-wpseo-replace-vars.php, inc/date-helper.php, tests/frontend/schema/schema-webpage-test.php
* Fixes a bug where the time in the `article:published_time` and `article:modified_time` meta tag output and in the `datePublished` and `dateModified` schema output was incorrect when in WordPress 5.2.
* For all the user-facing dates we still use the non-GMT date from WP.
* The date format helper presumes the same format as the WP database column.
* Change your timezone: `Settings` > `General` > `Timezone` to somewhere where the date is different than where you are now. E.g. Sydney or Honolulu.
* In the same spot, ensure you have the `Date Format` to something that includes the date.
* Ensure you have the date prefix for the snippet preview: `Yoast SEO` > `Search Appearance` > …
=> Introduce date format helper

inc/date-helper.php
This fixes a fatal when you pass an empty date string for example.
* Fixes a bug where a fatal would occur when an empty string would be passed to the `WPSEO_Date_Helper->format` method. Props to [@mpolek](https://github.com/mpolek).
*
* Add the following to your `function.php` of your theme:
```
$date = new WPSEO_Date_Helper();
$date->format( '' );
```
* Verify that it produces a fatal without this PR.
* Verify that is no longer produces a fatal with this PR.
Fixes #13948
=> Add safety check for when the PHP date format would return false

integration-tests/inc/options/test-class-wpseo-options.php, integration-tests/notifications/test-class-yoast-notification-center.php, integration-tests/onpage/test-class-onpage-option.php, integration-tests/onpage/test-class-onpage.php, integration-tests/onpage/test-class-ryte-service.php, integration-tests/recalculate/test-class-recalculate-posts.php, integration-tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php, integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-data.php, integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-validator.php, integration-tests/sitemaps/test-class-wpseo-sitemaps-cache.php, integration-tests/sitemaps/test-class-wpseo-sitemaps.php, integration-tests/statistics/test-class-statistics-service.php, integration-tests/taxonomy/test-class-taxonomy-content-fields.php, integration-tests/taxonomy/test-class-taxonomy-fields.php, integration-tests/taxonomy/test-class-taxonomy-settings-fields.php, integration-tests/taxonomy/test-class-taxonomy.php
* N/A - Just adding missing `@covers` to the tests
=> Adds missing `@covers` to unit tests

src/generators/schema/article.php, src/generators/schema/webpage.php, src/helpers/date-helper.php, src/presentations/indexable-post-type-presentation.php, tests/generators/schema/article-test.php, tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php, tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php
* N/A Implements the datehelper for formatting the date UTC+0.
*
* Change the timezone in `Settings` --> `General` to a city.
* Create a post and view the page source.
* Make sure the schema outputs the right `datePublished` fields.
* Edit the post and view the page source.
* Make sure the schema outputs the right `dateModified` fields.
* Change the timezone in `Settings` --> `General` to a manual offset.
* Repeat the above steps to check the schema output.
Fixes: #13907
=> Implement date helper

css/src/admin-global.scss, css/src/alerts.scss, css/src/extensions.scss, css/src/toggle-switch.scss, css/src/wpseo-dismissible.scss, css/src/yoast-components.scss, css/src/yst_plugin_tools.scss
* N/A
*
* Test in browsers other than IE11.
* `Social` : input fields and buttons should be same height (28px). 
* When hoovering over question marks (e.g. at `Social` > `Accounts`) the cursor should be a pointer.
* `Premium`: the extensions should be correctly formatted (see below).
* When clicking on a collapsable header (e.g. see `Social` for a specific post) a blue focus bar should appear around the header.
* Look at styled select element ( `SEO` > `Search Appearance` > `General` > `Knowledge Graph & Schema.org` ), see image below.
Fixes #13894
=> Remove all IE11-specific scss

integration-tests/test-filters.php
* _N/A_
If a test should not cause code coverage to be recorded, you can use the PHPUnit `@coversNothing` annotation.
Ref: https://phpunit.de/manual/5.7/en/appendixes.annotations.html#appendixes.annotations.coversNothing
@igorschoester If the build passes, this can be merged straight away. I would merge it myself, but figured it may be useful for you to know how to handle this situation for the future.
* _N/A_
=> Filter test: fix @covers tag

css/src/yst_plugin_tools.scss
* Restored the CSS fixed table layout on the settings pages after #13962 
* The fixed table layout algorithm was removed in https://github.com/Yoast/wordpress-seo/commit/0f6adc633b216e6e775e7165ab4a6e0773305be3#diff-a66b2fe73151a449fa79a2e7676283a2 as the inline comment was a bit misleading
* Looks like it's still needed by modern browsers. Difference between the two algorithms:
- normal (default): adapts the columns width based on the table cells content: the CSS widths are only a "hint"
- fixed: sets the columns width based on the specified CSS values _before even attempting_ to adapt to the cells content width
-  go in the settings pages
- see the two main layout columns render …
=> Restore the CSS fixed table layout on the settings pages.

frontend/schema/class-schema-breadcrumb.php
* Fixes a bug where an empty page title would cause the breadcrumbs schema to set a wrong url.
* N/A
* Enable breadcrumbs in SEO -> Search Appearance -> Breadcrumbs (no inclusion in theme or shortcode needed)
* Create a post, save it, remove the title and save it again
* Check the post on the frontend, specifically the HTML
* Note that all "url" references in the breadcrumbs schema are actually  valid URLs. Without this fix, the item referring to this post had the title set as the url.
Fixes https://github.com/Yoast/wordpress-seo/issues/13616
=> Fix an empty post title from changing a breadcrumb SD schema url

css/src/alerts.scss, grunt/config/eslint.js, js/src/wp-seo-admin-global.js
* Fixed a bug where clicking the notification center buttons would display a wrong icon and a misplaced focus style for the dismiss and restore buttons.
* Removed leftover code from the old implementation of the notification center, see https://github.com/Yoast/wordpress-seo/pull/4621
* Updated the ESLint max-warnings
* Go to SEO > General and observe the notification center
- make sure you have the "Get started" notification displayed: for testing purposes I temporarily altered the code to make it appear, not sure if there are better methods
- using the keyboard, tab through the interface and verify the "Get started" notification button focus style is displayed correctly
Previously …
=> Fix notification center buttons style.

js/src/wp-seo-featured-image.js
* Fixes a bug where the images alt attribute SEO assessment in the Classic Editor was wrong when the image had not alt attribute and did have a title attribute
* Since WordPress 4.7 the image alt attribute doesn't fallback to the image title attribute any longer. Yoast SEO still used the old fallback, which is now removed.
**To reproduce the bug on trunk:**
- use the Classic Editor 
- create a post
- set a featured image with no alt attribute
- see the analysis says the image does have an alt attribute
- set a test keyphrase `mykeyphrase`
- edit the featured image and set its title attribute to `mykeyphrase`
- see the analysis says: Image alt attributes: Good job!
- however, the image has no alt attribute so the assessment …
=> Remove featured image alt attribute fallback to image title.

css/src/yoastcom/0-tools/_mixins.scss, css/src/yoastcom/_promoblock.scss
* N/A
- Quick PR to continue to work from #13894 / #13962
- removes the `display-flex` mixin that was used only once and uses `display: flex` directly instead
- by doing so, a few `-ms-` prefixed CSS properties are removed as well as hacks for IE9
- also other browser-prefixed properties are removed, as they're no longer necessary
* go to SEO > Premium and check the "promoblock cards" layout is unchanged
Fixes https://github.com/Yoast/wordpress-seo/issues/13978
=>  prefixed CSS properties.

src/generators/schema/faq.php, src/generators/schema/howto.php
In #13896 we improved the security of the plugin by adding more output escaping.
As this impacts classes that have been moved in the feature branch this change should be replicated in the feature branch.
all outputs in the feature branch in schema blocks are escaped.
* Adds output escaping to schema blocks.
* Addes output escaping to schemas blocks in indexables, just as done in trunk.
* Check if outputs are correct and safely done.
Fixes #13897
=> escaped howto and faq IDs

css/src/toggle-switch.scss, css/src/yoastcom/0-tools/_mixins.scss, css/src/yst_plugin_tools.scss, package.json, yarn.lock
This remove all of the automatic `-ms-` prefixes everywhere. Does this by switching to new version of plugin-grunt-tasks, so as to switch to new browserslist implementation.
* Remove IE11 specific CSS.
* `yarn install`.
* `grunt build:css`: no -ms- prefixes should be found in the built css.
* Click through the plugin for 2 minutes.
Fixes #
=> Remove -ms- prefixes everywhere

.travis.yml, composer.json, composer.lock, integration-tests/admin/links/test-class-link-content-processor.php, integration-tests/admin/links/test-class-link-storage.php, integration-tests/admin/links/test-class-link-type-classifier.php, integration-tests/admin/services/test-class-file-size.php, integration-tests/admin/test-class-plugin-suggestions.php, integration-tests/config-ui/test-class-configuration-components.php, integration-tests/config-ui/test-class-configuration-endpoint.php, integration-tests/config-ui/test-class-configuration-options-adapter.php, integration-tests/config-ui/test-class-configuration-service.php, integration-tests/config-ui/test-class-configuration-storage.php, integration-tests/framework/class-wpseo-unit-test-case.php, integration-tests/inc/test-class-wpseo-admin-bar-menu.php, integration-tests/notifications/test-class-yoast-notification-center.php, integration-tests/notifiers/test-class-dismissible-notification.php, integration-tests/test-class-admin-asset-manager.php
* _N/A_
Includes:
* Adjusting the Travis matrix now WP 5.3 has been released
* Removing the build against PHP 7.4 from `allowed failures`.
* Adding (back) a build against PHP `nightly` (PHP 8) and adding it to  `allowed_failures`.
For now, this build will only lint the code. Unit testing is not yet possible with  the current setup.
* Updating BrainMonkey to `^2.4.0` which is the first release which supports PHP 7.4.
Note: the BrainMonkey dependencies have been updated as well, but _nothing else_.
Ref: https://github.com/Brain-WP/BrainMonkey/releases/tag/2.4.0
---
This has been discussed in depth with @herregroen and @IreneStr.
The short summary is:
* The `ReflectionType::__toString()` method has been deprecated since PHP 7.1 and …
=> Travis: don't allow builds against PHP 7.4 to fail

src/integrations/watchers/indexable-post-watcher.php, src/integrations/watchers/indexable-term-watcher.php, src/integrations/watchers/primary-term-watcher.php
* Fixes a bug where `create` and `update` actions could be done twice on multisite.
* The deletions are not covered: for some reason I don't fully understand, the deletions are not affected by multisite like the saves/updates are. If someone knows, please enlighten me.
These are kind of hard to test. The idea is that the code could get called twice when on multisite.
Therefore, some debugging is needed to verify this. [See this Wiki page to learn how](https://github.com/Yoast/Wiki/wiki/PHPStorm-debugging).
*Note: To acquire a copy of MultilingualPress, login to LastPass -> Shared-licenses vault. There's a login there for MultilingualPress so you can download the latest version.* …
=> [indexables] Add missing multisite checks for the actions

admin/views/tabs/social/pinterest.php, admin/views/tabs/social/twitterbox.php
* Updated text reference to Open Graph checkbox.
* This quick PR fixes the last pending part of https://github.com/Yoast/bugreports/issues/404
* A couple text strings on the SEO > Social > Twitter and SEO > Social > Pinterest still referenced an "Open Graph checkbox" on the Facebook tab that doesn't exist any longer
* Updated two text strings to reference the "Add Open Graph meta data setting"
* on trunk:
* go to the SEO > Social > Twitter and SEO > Social > Pinterest
* see the text referencing a "checkbox":
* go to the Facebook tab
* see there's no checkbox, instead there's a "switch toggle" control:
* switch to this branch
* go to the SEO > Social > Twitter and SEO > Social > …
=> Change text reference to Open Graph checkbox.

src/presentations/indexable-post-type-presentation.php
* Fixes a bug where the per post robot override was not being honored.
*
The following can be done with all post types (post, page, custom posts). I will use posts only for the test instructions.
* Set the indexing of a post type to `false`: SEO > Search Appearance > Content Types > Show Posts in search results? > No
* Set the indexing of an individual post to `true`: Metabox > SEO > Advanced > Allow search engines to show this Post in search results? > Yes
* Check the source of the frontend.
* No robots tag or with `index`: `<meta name="robots" content="index"/>`
* A canonical: `<link rel="canonical" href=""/>`
* A rel next/prev when applicable: `<link rel="next" href=""/>`
* Set …
=> Indexables: fix per-post robots setting

deprecated/frontend/class-opengraph-image.php
* N/A - It just deprecates the OpenGraph Image class gracefully.
*
* Add this to `wp-seo.php`
```php
$haha = new WPSEO_OpenGraph_Image();
} );
```
Fixes #13939
=> Extends the OG image class with the one that replaces it

frontend/class-breadcrumbs.php
* Changes `array` to `int` in property documentation. Props to [alfiosalanitri](https://github.com/alfiosalanitri)
=> @var type from array to int

inc/class-upgrade.php
* None needed
* Re-saved the `wpseo` option, which makes the validation run and thus removes the no longer valid keys.
* Make sure you have a database where `bf_banner_2019_dismissed` is stored, probably with value `true` in the `wpseo` option.
* In Yoast Test Helper, set the version to 12.6, see that the upgrade routine runs and the `bf_banner_2019_dismissed` key is removed from the `wpseo` option.
Fixes #13965
=> Remove BlackFriday option

frontend/schema/class-schema.php
* Adds the possibility to declare an identifier when integrating with schema output.
* This pull is looking for a public class property named `identifier` and will use that. This makes it possible to integrate in a situation where the class isn't named `WPSEO_Schema_*` or is using a namespace. 
A temporary fix was class aliasing the namespaced class to meet the class name requirement used in the code:
```
class_alias( \My\Namespace\Schema::class, 'WPSEO_Schema_Review' );
```
* For testing this I recommend using my private spare time project: https://github.com/andizer/review-block - This plugin adds a review block to the block editor. Clone this project, do a `yarn install` (or `npm …
=> Checks if class has identifier property and use that as the class name.

admin/class-admin.php, admin/links/class-link-watcher.php, admin/statistics/class-statistics-integration.php, admin/taxonomy/class-taxonomy.php
* Fixes a bug where `create` and `update` actions would be done twice on multisite environments in combination with MultilingualPress.
* The deletions are not covered: for some reason I don't fully understand, the deletions are not affected by multisite like the saves/updates are. If someone knows, please enlighten me.
* The rewrite is already covered for the full class. It is not loaded in on multisite.
These are kind of hard to test. The idea is that the code could get called twice when on multisite.
Therefore, some debugging is needed to verify this. [See this Wiki page to learn how](https://github.com/Yoast/Wiki/wiki/PHPStorm-debugging).
*Note: To acquire a copy of …
=> Add missing multisite checks for the actions

frontend/class-frontend.php, inc/class-rewrite.php, inc/sitemaps/class-sitemaps-router.php
* N/A - It just removes the manual set x-redirect-headers since this will be done by WordPress
*
* Open Chrome in incognito mode (or a similar feature in your preferred browser).
* Open the Network tab in the devtools, and make sure `Preserve log` action is checked.
* In the browser navigate to `http://local.wordpress.test/sitemap.xml`.
* Make sure you are redirected to `http://local.wordpress.test/sitemap_index.xml`.
* In the devtools, look for the request with the name `sitemap.xml` and status `301`.
* Inspect the `Request Headers` of this request and make sure it has the `X-Redirect-By: Yoast SEO` header.
Fixes #9993
=> Removal of manual set x-redirect-by headers

src/helpers/home-url-helper.php
* N/A - Introduces a home url helper class.
* The class will cache the value of the home url.
* There is no implementation. This one will be made in premium, where this pull will get merged into.
Needed for https://github.com/Yoast/wordpress-seo-premium/pull/2639
=> Introduces a home url helper

admin/metabox/class-metabox.php, css/src/admin-global.scss
This reverts commit 556e583f8bb4af0856dc5bd2f5034b3b572d12e4.
* Reverts the 5.3-specific CSS changes that are no longer needed when 5.3.1 has been released.
* N/A
* A round of testing with the desktop and responsive views wherever we use form controls would be recommended. Don’t forget the configuration wizard.
* Test in WP 5.2.x and 5.3.1 (RC). See that the styling is correct.
* NB: In 5.3.0, the styling will be off as shown in https://github.com/Yoast/bugreports/issues/686.
Fixes https://github.com/Yoast/bugreports/issues/768
=> Revert "Adjust input fields heights after WordPress 5.3 CSS changes."

js/src/analysis/collectAnalysisData.js, js/src/wp-seo-post-scraper.js, js/tests/__test-data__/blocksForAnalysisTestData.json, js/tests/__test-data__/gutenbergBlocksTestData.json, js/tests/collectAnalysisData.test.js
* Gutenberg blocks are now sent to the SEO- and Readability analysis web worker, so we can use its structure in the analysis.
* I chose to send this data for analysis:
* `attributes`: 
* `content`: The main HTML-content of the block (e.g. paragraph, heading content).
* `level`: Heading level, used in single-H1-assessment.
* `alt`: Alt text of images, used in keyword-in-alt-text-assessment.
* `clientId`: locally unique block identifier, used for e.g. markings.
* `name`: Type of block, e.g. `core/paragraph` for Gutenberg paragraphs.
**Note**: This PR needs to be tested in parallel with this PR on the JavaScript monorepo: 
* Open an existing post in the block editor.
* Open the …
=> 13996 send list of blocks to analysis

admin/tracking/class-tracking-server-data.php
Adds the `pdo_mysql` extension to tracking and removes the `modXml` extension ( there's no such extension ).
* N/A
* The `pdo_mysql` extension is required for idiorm to function.
* Use `wp shell`.
* Create an instance of `WPSEO_Tracking_Server_Data`.
* Call `get`.
* You should see whether or not `pdo_mysql` is enabled in the results.
Fixes #14047
=> Add pdo_mysql extension to tracking and remove modXml as it doesn't exist

admin/class-yoast-form.php, inc/wpseo-non-ajax-functions.php, integration-tests/admin/test-class-yoast-form.php
This uses `WPSEO_Options::get` where we can instead of a local `$this->options` everywhere.
* Optimized option retrieval on admin pages.
* See Summary.
* See Yoast SEO admin pages, make sure all forms still work as intended.
* Make sure you can still disable the admin bar.
* Do a quick check with the site-wide settings on multisite 
Fixes #
=> Use WPSEO_Options::get where we can

admin/metabox/class-metabox.php, tests/TestCase.php
* _Improved reliability of checking whether the user uses Internet Explorer_
>There is no guarantee that every web server will provide any of these; servers may omit some, or provide others not listed here.
Source: https://www.php.net/manual/en/reserved.variables.server.php
You can never be sure that all "expected" `$_SERVER` variables will be passed along. Always check whether the index exists before accessing it.
WP slashes all data in superglobals, so for this data to be usable in a comparison, it needs to be unslashed first.
The `stripos()` function will return an offset - which may be `0` - or false if the string is not found.
By doing a loose comparison using `!`, the _found_ case at position `0` would be incorrectly …
=> WPSEO_Metabox::is_internet_explorer(): bug fixes / input handling

frontend/schema/class-schema-howto.php
Multiple instances where HowTo was still displayed as FAQ in the code documentation.
* Fixes docs in the Schema HowTo files. Props to [timvaniersel](https://github.com/timvaniersel)
*
*
Fixes #
=> Fix HowTo naming in code documentation / comments

inc/class-upgrade.php
* Removes the "Upgrade WordPress to the most recent version" notification.
* The function that adds or removes this notification was removed in 12.5 with no upgrade routine to clean up the database. This made this a persistent message until dismissed or the plugin was deactivated and reactivated.
* Added a notification removal to the 12.8 upgrade routine.
This test is for the RC only. Testing this as a branch requires altering the version number in-code.
1. Install this RC and the Yoast Test Helper
2. Add the following database entry to the `wp_usermeta` table:
- `umeta_id`: the next one
- `user_id`: 1 (assuming you are the admin user)
- `meta_key`: wp_yoast_notifications
- …
=> Add upgrade routine to remove WordPress upgrade notice

migrations/20191211144248_WpYoastIndexablesAddIsPublicField.php, src/builders/indexable-post-builder.php, src/models/indexable.php, tests/builders/indexable-post-builder-test.php
* Adds `is_public` field to the indexables table.
*
* Set a password for a post
* Check in the post table that the is_public value is set to 0
* Remove the password
* The value should be 1
* Make the post a draft -> The value should be 0
* Publish it again -> It should be 1.
Fixes #13973
=> Add is_public to indexables table

src/helpers/redirect-helper.php, src/integrations/front-end/comment-link-fixer.php, src/integrations/front-end/redirects.php, tests/integrations/front-end/comment-link-fixer-test.php, tests/integrations/front-end/redirects-test.php
Also moved two methods that performs a redirect to the redirect helper.
* N/A - It removes the manual set x-redirect header
* I also used the redirect helper instead of defining two redirect methods in the class where I needed them. 
* Navigate to a comment (the oldstyle: `?replytocom={comment-id}`) and make sure you get redirected. The redirect should contain our x-redirect-by: Yoast header.
* Disable the date archive or the author archive. Navigate to the author / date archive and make sure the redirect contains x-redirect-by: Yoast.
Fixes #
=> Removal of the manual set x-redirect-header

.babelrc, package.json
* Switches to `babel-preset-env` using `@yoast/browserslist-config` (dropping IE11 support).
* See issue
- See no errors when running `grunt build`
- Create a post, make sure the language analysis doesn't throw errors in the console.
Partially fixes #13954
=> Use browserlist instead of babel targets directly

inc/options/class-wpseo-options.php, tests/TestCase.php
Make sure that when a new option is registered we fill the cache properly
* None needed.
* Call `fill_cache()` at the end of `register_option()`.
* Use this with Local trunk and make sure it works.
=> Fill cache properly when option is registered.

composer.json
* _N/A_
This updates the Composer script used to run the PHPCS check for Premium to YoastCS 2.0.0.
Includes:
* Removing the tweaks to the Composer `premium-check-cs` script to allow for different PHP requirements in different directories.
PHP 5.6 is now the minimum PHP version everywhere.
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.0.0
* This change in itself can't be tested in the Free repo. It needs the ruleset changes as pulled in PR https://github.com/Yoast/wordpress-seo-premium/pull/2649 and a merge-back for Free to Premium before this can be tested.
=> Premium: Update to YoastCS 2.0.0

src/presenters/open-graph/image-presenter.php, src/presenters/open-graph/type-presenter.php, tests/presenters/open-graph/image-presenter-test.php, tests/presenters/open-graph/type-presenter-test.php
* N/A - The `value` property has been changed into `content`
* I also changed it for the images, where value was used as property.
* Have a OG type and have an OG image.
* Verify that the property for `og:type` and `og:image` is `content` now.  
Fixes #14055
=> Uses content instead of value

inc/options/class-wpseo-option.php, inc/options/class-wpseo-options.php
* N/A - Fixes a bug where the option cache is refreshed after saving the options.
* When relying on option values when the option has been updated it will return the cached value. This has been fixed by refreshing the cache after option save.
Please merge trunk into the indexables feature branch when you have merged this one!!!!
* Make sure options are still saved correctly.
* Follow the steps in #14056 and make sure this pull solves it 
Fixes #14056 - Merge trunk into the indexables feature branch
=> Optimize the cache fill

admin/views/sidebar.php
* _N/A_
As this is an inline (non-block) HTML tag, a quick visual check should be done to make sure this change doesn't affect the rendered layout of the sidebar.
If it does, there is another way this can be solved, but let's try this first.
* Check out `trunk`, view the admin sidebar and take note of the layout for the Yoast SEO Academy block.
* Check out this branch and make sure the rendered layout has not changed.
=> CS: fix placement PHP open/close tags for embedded PHP

src/presenters/googlebot-presenter.php, tests/presenters/googlebot-presenter-test.php
* N/A
* Make sure we output `max-snippet:-1, max-image-preview:large, max-video-preview:-1` instead of `max-snippet:-1,max-image-preview:large,max-video-preview:-1` (without spaces)
* Go to the frontend of a post that is not `noindex` or `nosnippet`.
* See `max-snippet:-1, max-image-preview:large, max-video-preview:-1`
Fixes #
=> Add spaces to the googlebot meta tag

admin/class-admin-asset-manager.php
* Reintroduce register_wp_assets for backwards compatibility
* In https://github.com/Yoast/wordpress-seo/commit/5a62afe004b8917ce806f90df18727354f07953a we deleted `register_wp_assets ` from the asset manager. Local SEO extends the asset manager class and in 12.5 it calls the `register_wp_assets` method, which was deleted. This resulted in a fatal error if Local SEO was still on 12.5 and Yoast SEO was updated to 12.8. This PR reintroduces `register_wp_assets` as a deprecated function to prevent that fatal error.
* Install Yoast SEO 12.7 and Local 12.5.
* Checkout tags/12.8-RC2 on Yoast SEO.
* Navigate to Locations and see a fatal error.
* Navigate to …
=> Reintroduce register_wp_assets for backwards compatibility

inc/health-check-page-comments.php, tests/inc/health-check-page-comments-test.php
* Made sure the Paging comments Site Health test is listed in the Passed tests when it passes.
*
- repeat the steps from the issue https://github.com/Yoast/bugreports/issues/793
- at the last step, check the Paging comments test is listed within the "Passed tests" section
Most of the existing WordPress test labels include a verb, I guess to make the text more human-friendly. For example:
- Your site is set to display errors to site visitors
- You should remove inactive plugins
- Your site does not use HTTPS
- Background updates may not be working properly
For this reason and for consistency I changed "Paging comments enabled" to "Paging comments is enabled". Further improvements to …
=> Add Good result status to the Paging comments Site Health test.

admin/class-admin-init.php, inc/class-upgrade.php, inc/health-check-default-tagline.php, inc/health-check-tagline.php, inc/health-check.php, tests/TestCase.php, tests/inc/health-check-default-tagline-test.php, tests/inc/health-check-test.php
* Moved the Default Tagline notice from the SEO Dashboard to WordPress' Health Check
- Worth noting `WPSEO_Health_Check->get_test_result()` omitted to pass `$test` which represents the name of the test. Without this, multiple Site Health accordions won't work because they will have the same (incomplete) ID: `health-check-accordion-block-` produced by `health-check-accordion-block-{{ data.test }}`. This is fixed in this PR.
- Added two deprecations and one upgrade routine using a temporary `xx.x` for the plugin version. This should be updated when merging into trunk once the actual milestone will be determined.
- Better wording for the non-passed / passed test welcome.
- Go to …
=> Move the tagline notification to a site health test

admin/class-admin-init.php
The GA compatibility notice had already been deprecated in a [previous commit](https://github.com/Yoast/wordpress-seo/pull/13632/commits/7f17ffc20abea30f32ce60890e74582457dcd904). This PR only moves the method to the bottom of the class, with the other deprecated methods.
* N/A
*
*
Fixes #12901
=> Move deprecated method

admin/class-yoast-form.php
* Introduces a field for rendering a checkbox list field.
* 
* Check this branch out and do all building steps: yarn and composer
* This element is implemented in Yoast SEO Video. It's better to test it against video
* Go to https://github.com/Yoast/wpseo-video/pull/786 and make sure that on the admin page a list of post types and a list of taxonomies is rendered. 
Fixes #
=> Adds a checkbox list field

admin/views/tabs/metas/paper-content/general/knowledge-graph.php
* N/A - Fixes a bug where the alers is shown even when a company logo and company name are set. 
*
* On the search appareance set a company name and logo
* The alert should be gone.
Fixes #14137
=> Use the getters for retrieving the option value

composer.json
Replaces https://github.com/Yoast/wordpress-seo/pull/14002
* Fixes composer vendor compatibility for Windows
*
* Travis should pass.
* Should merge in premium and check if premium also passes (https://github.com/Yoast/wordpress-seo-premium/pull/2663).
* You could run the individual composer scripts to see if they still work.
Fixes #14002
=> Revert vendor/bin composer changes

src/integrations/front-end-integration.php, src/integrations/front-end/webmaster-tools-meta.php, src/presenters/googlebot-presenter.php, src/presenters/open-graph/image-presenter.php, src/presenters/open-graph/title-presenter.php, src/presenters/open-graph/type-presenter.php, src/presenters/open-graph/url-presenter.php, src/presenters/robots-presenter.php, tests/presenters/googlebot-presenter-test.php, tests/presenters/open-graph/image-presenter-test.php, tests/presenters/open-graph/title-presenter-test.php, tests/presenters/open-graph/type-presenter-test.php, tests/presenters/robots-presenter-test.php
Quite nit picky, but this pull makes sure we always:
* Close our tags like this `content" />`, instead of varying between that and `content"/>`.
* Properly add tabs to indent every element.
* None needed.
* Removed the `WPSEO_DEBUG` presenter comment for every presenter so you can actually see all this a bit more easily.
* See that all output has `" />`.
=> Consistent spacing in our tags

package.json, yarn.lock
* None needed.
* Bumps plugin grunt tasks dependency.
* Run `grunt release` and `grunt build:css`, see that the generated RTL files never have `.min.css` extensions.
=> bump plugin grunt task to fix RTL CSS minified files not being loaded

admin/views/class-view-utils.php, admin/views/tabs/metas/paper-content/post_type/post-type.php
* Renames 
I've added the non-user-facing label, because the change is already covered by the changelog item `Renames the 'Snippet preview' to 'Google preview'`.
* N/A
* See https://github.com/Yoast/bugreports/issues/675
Fixes https://github.com/Yoast/bugreports/issues/675
=> Rename snippet preview to Google preview in search appearance

integration-tests/admin/test-class-schema-person-upgrade-notification.php
Fixes 
```
FILE: integration-tests\admin\test-class-schema-person-upgrade-notification.php
--
FOUND 3 ERRORS AFFECTING 3 LINES
18 \| ERROR \| Each test function should have at least one @covers tag annotating which
\|       \| class/method/function is being tested. Tag missing for function
\|       \| test_remove_notification_not_person()
33 \| ERROR \| Each test function should have at least one @covers tag annotating which
\|       \| class/method/function is being tested. Tag missing for function
\|       \| test_remove_notification_user_id_set()
49 \| ERROR \| Each test function should …
```
=> Add @covers to WPSEO_Schema_Person_Upgrade_Notification_Test

src/generators/schema/article.php, src/generators/schema/author.php, src/generators/schema/faq.php, src/generators/schema/howto.php, src/generators/schema/organization.php, src/generators/schema/person.php, src/generators/schema/webpage.php, src/generators/schema/website.php, src/helpers/schema/html-helper.php, src/helpers/schema/id-helper.php, src/helpers/schema/image-helper.php, tests/generators/schema/article-test.php, tests/helpers/schema/html-helper-test.php
* Security fix: strip tags on the output of text fields in Schema.
@moorscode does this need attribution in the changelog?
* Uses a new method that does some smart replaces before applying `wp_strip_all_tags` everywhere we output text nodes.
* See steps in https://github.com/Yoast/bugreports/issues/776, although might be easier to do this with a post's title.
Fixes https://github.com/Yoast/bugreports/issues/776
Fixes https://github.com/Yoast/bugreports/issues/572
Fixes #12939
=> Schema: strip tags on text fields

admin/views/tabs/dashboard/dashboard.php, admin/views/tabs/metas/paper-content/breadcrumbs-content.php
* N/A
* "Improve speed and efficiency" by making 2 yoa.st shortlinker calls secure.
Make sure that the following 2 links show, are clickable and point to the "https" protocol:
- On `SEO -> General` at the `Credits` heading: "See who contributed to Yoast SEO."
- On `SEO -> Search Apprearance -> Tab:Breadcrumbs` scroll down to the bottom at the `How to insert breadcrumbs in your theme` header: "our knowledge-base article on breadcrumbs implementation"
Fixes https://github.com/Yoast/bugreports/issues/806
=> Make all shortlinker calls secure

css/src/admin-global.scss, inc/health-check-page-comments.php, inc/health-check.php, tests/inc/health-check-page-comments-test.php, tests/inc/health-check-test.php
Improves copy of the paging comments health check, adds the Yoast signature for health checks and adds the scenario for a 'good' result, where the check is moved to `Passed tests`. 
This PR should be merged to `trunk` and not `feature/site-health`. 
* N/A
*  "Comment Settings page" was changed to "Discussion Settings page", since the page is found at `Settings` > `Discussion` and then there is a subheading called `Other comment settings` (see image below).
* See whether everything is still working as desired : look at #14102 and #13522 and the screenshots below
`Recommended`:
`Passed tests`:
Fixes #14178
=> Improve paging comments health check

inc/wpseo-functions.php, src/conditionals/breadcrumbs-enabled-conditional.php, src/integrations/breadcrumbs-integration.php, tests/conditionals/breadcrumbs-enabled-conditional-test.php, tests/integrations/breadcrumbs-integration-test.php
* N/A - Fixed editor when yoast breadcrumbs are enabled and used.
* Created a breadcrumbs integration.
* Repeat the steps in #14101 .
Fixes #14101
=> Fix edit post breadcrumbs shortcode

src/generators/schema/main-image.php, tests/generators/schema/article-test.php, tests/generators/schema/main-image-test.php
* N/A - Fixes a bug where an image object is output when there is no image URL.
*
* Execute the steps in #14064 
* Make sure no `ImageObject` graph piece is present.
* Make sure the `WebPage` graph piece no longer has a `primaryImageOfPage` property.
Fixes #14064
=> Don't output and image object graph piece when the url is empty

src/generators/schema/website.php, tests/generators/schema/website-test.php
* N/A - Adds site description to webpage graph piece.
*
* See steps in #14063
Fixes #14063
=> 14063 add description to website

src/helpers/robots-helper.php, tests/admin/capabilities/capability-utils-test.php, tests/helpers/robots-helper-test.php, tests/inc/options/options-test.php
* N/A
* Filter the array to remove empty values.
* To reproduce the issue, see [here](https://github.com/Yoast/wordpress-seo/issues/14090).
* Check out this branch, build, and follow the same steps as above.
* See that the meta tag output has changed to `meta name="robots" content="noindex,follow"`.
Fixes #14090
=> Fix robots noindex on static homepage

tests/inc/health-check-test.php
* _N/A_
The return type of the PHPUnit `setUp()` method is explicitly `void`, so the method should not contain a `return` statement.
* _N/A_
=> QA: test `setUp()` should not return

admin/class-admin-asset-seo-location.php, admin/class-yoast-notification-center.php, frontend/class-frontend.php, inc/health-check-page-comments.php, inc/options/class-wpseo-options.php, inc/wpseo-non-ajax-functions.php, integration-tests/admin/links/test-class-link-internal-lookup.php, integration-tests/capabilities/test-class-capability-manager.php, integration-tests/frontend/test-class-opengraph.php, integration-tests/frontend/test-class-wpseo-frontend-robots.php, integration-tests/notifications/test-class-yoast-notification-center.php, integration-tests/test-class-admin-asset-manager.php, tests/admin/capabilities/capability-utils-test.php, tests/doubles/inc/options/options-double.php, tests/helpers/author-archive-helper-test.php, tests/helpers/date-helper-test.php, tests/inc/health-check-page-comments-test.php, tests/inc/health-check-test.php, tests/inc/options/options-test.php
* _N/A_
Minor CS fixes:
* Aligning of equal signs.
* Whitespace around commas.
* Multi-line function call formatting.
* Multi-item associative arrays should be multi-line.
* Use short arrays.
* Comma after last array item in a multi-line array.
* Blank lines before/after function declarations.
* No unnecessary string concat.
Minor docs fixes:
* Add some missing docblocks.
* Add some missing property descriptions.
* Add some missing parameter/return tags.
* Docblock tag description alignment.
* Ignoring deprecated methods for code coverage.
* Remove file docblocks for namespaced files.
* Fix some `@covers` tags
* Minor punctuation fixes.
* _N/A_
This is a code-only change and should …
=> CS/Docs: clean up after merges

admin/views/tabs/social/facebook.php, js/src/wp-seo-admin.js
* Hide facebook settings when Open Graph is disabled.
*
* Go to `SEO` > `Social` > `Facebook`.
* Disable `Add Open Graph meta data` and make sure the other facebook settings disappear.
* Save the settings.
* Disable `Add Open Graph meta data` and make sure the other facebook settings appear.
* Save the settings.
Fixes #14111
=> Hide facebook options when facebook is disabled

grunt/config/webpack.js, webpack/webpack.config.js
When the hackathon branch was merged (for the automated RC creation) we broke the webpack dev server, because the plugin version required to generate the file names was no longer injected in the webpack config. In this PR I fixed that by checking if the plugin version is available and if not it is extracted from the `package.json` file. 
* N/A - Fixed webpack dev server after hackaton branch was merged
* 
* Run `grunt webpack:buildProd`
* Run `grunt webpack:buildDev`
* Run `yarn start`
Fixes #
=> Fixed webpack dev server after hackaton branch was merged

migrations/20200121154000_WpYoastIndexablesAddFields.php, src/builders/indexable-post-builder.php, src/models/indexable.php, tests/builders/indexable-post-builder-test.php
* N/A - Adds the `is_protected` and `post_status` fields to the indexables table
*
* Make sure the migrations are run. I've returned true in the`Migrations_Conditional::is_met`
* Add a password to the post and publish the post
* Verify that in the database the `is_protected` value is set to 1 for the indexable. The `post_status` should be set to `publish`
* Remove the password - `is_protected` should be 0 now
* Unpublish the post by making it a draft - the `post_status` should be `draft` now
Fixes #14072
=> Adds two fields to the indexables table

frontend/class-frontend.php, integration-tests/frontend/test-class-wpseo-frontend.php
Replaces #13430
* Fixes a bug where the "force rewrite titles" option would removes title tag in svg tags. Props @dsktschy
* Remove support for 'title-tag' in the theme. You could use following code:
```php
add_action( 'after_setup_theme', function() {
remove_theme_support( 'title-tag' );
}, 9999 );
```
* Enable Force rewrite titles in SEO - Search Appearance under the General tab.
* Add SVG by the instructions in #6770 or #13430
* Check title tags in HTML source.
~~* [ ] I have written documentation for this change.~~
Fixes #6770
=> Limit targets for force rewrite titles option to title tags in head tag

inc/health-check-page-comments.php, tests/inc/health-check-page-comments-test.php
* Improved the copy for the paginated comments Site Health check.
**New copy for the "not passed" case:**
> Comments break into multiple pages
> Comments on your posts break into multiple pages. As this is not needed in 999 out of 1000 cases, we recommend you disable it. To fix this, uncheck "Break comments into pages..." on the Discussion Settings page. 
I removed also "the box in front" as it was not needed and potentially confusing (which "box"?). Also confusing for translators.
Screenshot:
**New copy for the "passed" case:**
> Comments are displayed on a single page
> Comments on your posts are displayed on a single page. Breaking comments into multiple pages is not needed in 999 out of 1000 cases. We recommend to display all …
=> Simpler copy for the paginated comments Site Health test.

inc/health-check-default-tagline.php, inc/health-check-postname-permalink.php, tests/inc/health-check-default-tagline-test.php, tests/inc/health-check-postname-permalink-test.php
* Added the "Yoast signature" at the bottom of the Site Health checks
* This PR add the "Yoast signature" to the "default tagline" and "post name in permalink" tests. The other tests already have the signature.
- switch to this branch, run composer install and build
- go to the Site Health page
- whether the "default tagline" and "post name in permalink" tests pass or not, they should display the "Yoast signature" e.g.:
Fixes https://github.com/Yoast/wordpress-seo/issues/14183
=> Add yoast signature

admin/class-admin.php
* Added the `yoast` body class to Yoast SEO admin pages for easier CSS targeting.
* See `yoast` as a body class on Yoast admin pages with this pull on Yoast SEO admin pages.
* See `yoast` _not_ as a body class on other admin pages.
Fixes #14286
=> Adds the `yoast` body class yoast SEO admin pages

src/builders/indexable-builder.php, src/integrations/watchers/indexable-post-watcher.php, tests/integrations/watchers/indexable-post-watcher-test.php
* N/A - Update related indexables when the post is saved.
* I introduced an action names `wpseo_save_indexable` that is triggered when the indexable is saved. It received the updated and the old indexable.
* Decided to not introduce any helper methods, because it is only used a couple of times between the same class.
* Create a post and attach some terms like categories and tags to it.
* Save it
* Make a change and save it again
* Open the indexables table in the database and verify the related indexables have a new date for the `updated_at` field. 
Fixes #14079
=> Update post relations on update

inc/class-wpseo-utils.php
* Prevent additional sanitation if the URL is already properly encoded.
* Temporarily remove reserved characters from the value (which are the delimiters between pieces of URI), then [encode](https://www.php.net/manual/en/function.rawurlencode.php)/[decode](https://www.php.net/manual/en/function.rawurldecode.php) this stripped value and check for differences. If it's same then apply only [esc_url_raw](https://developer.wordpress.org/reference/functions/esc_url_raw/).
* Go to _SEO_ -> _Social_
* Save URLs from #13735 and #14143.
Fixes #13735 
Fixes #14143
=> Don't sanitize  properly encoded URL

frontend/schema/class-schema-article.php, frontend/schema/class-schema-faq-questions.php, frontend/schema/class-schema-howto.php, frontend/schema/class-schema-image.php, frontend/schema/class-schema-utils.php, frontend/schema/class-schema-webpage.php, frontend/schema/class-schema-website.php, tests/frontend/schema/schema-faq-questions-test.php, tests/frontend/schema/schema-how-to-test.php, tests/frontend/schema/schema-image-test.php
* Added `inLanguage` property to the schema CreativeWork pieces
- introduces `WPSEO_Schema_Utils::add_piece_language()`
- introduces a `wpseo_schema_piece_language` filter 
- the filter is passed the schema piece `$data` array so that it can be used for some logic, for example to change the language of a specific piece type
- adjusts the tests 
Note:
Regarding this requirement from the issue:
> When the language of the content of a specific piece isn't explicitly set/known, we should fall back to ...
I don't see cases where a specific piece may have its own language setting. For example: it's not possible to set a language on a `HowTo` within the post content. Same for `Question`, `ImageObject`, `VideoObject`,  etc. 
I might be …
=> Add inlanguage property to the schema CreativeWork pieces

admin/menu/class-base-menu.php, inc/class-wpseo-admin-bar-menu.php
* Removed the Search Console item from the admin menu and the toolbar menu.
- I couldn't find a clean way to remove the menu item while keeping the page accessible
- `remove_submenu_page()` doesn't work in our case as using it also removes the page from the registered pages, thus the page can't be accessed any longer
- note: this seems to be a WP limitation 
- opted for a hackish approach: the page is now registered using a fake parent page slug
- this way, the menu item is not displayed but the page itself can still be accessed directly
- go to SEO in the admin menu
- see there's no "Search Console" sub-menu item
- directly access the page by manually editing the URL in your …
=> Remove the Search Console menu item

admin/capabilities/class-register-capabilities.php, inc/class-upgrade.php
* Added capability to view Site Health to the SEO Manager role.
- adds the `view_site_health_checks` capability to the `wpseo_manager` role
- since capabilities are registered by default only on plugin activation / deactivation, adds the new capability in the upgrade routine for the Site Health feature (it's temporarily marked as `xx.x-RC0`
version)
- fixes an "only only" dittography
- on the `feature/site-health` branch:
- set the SEO Manager role to one of your users
- log in with that user
- go to WordPress > Tools
- see there's a blank page with no sub-items in the menu: no access to Site Health
- deactivate and re-activate Yoast SEO 
- go to WordPress > …
=> Allow the SEO Manager role to view the Site Health checks.

admin/class-yoast-form.php, admin/pages/dashboard.php, admin/pages/metas.php, admin/pages/social.php, admin/pages/tools.php, admin/views/licenses.php
Remove `yoast` class from wrapper div. Can also remove / change more classes if needed, or the entire wrapping `div` it's not needed at all.
* None needed.
=> Remove yoast class from wrapper div

src/backwards-compatibility/frontend.php, src/context/meta-tags-context.php, src/presentations/indexable-post-type-presentation.php, src/presentations/indexable-presentation.php, src/presentations/indexable-term-archive-presentation.php, src/presenters/abstract-indexable-presenter.php, tests/presentations/indexable-post-type-presentation/og-article-author-test.php, tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php, tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php, tests/presentations/indexable-post-type-presentation/replace-vars-object-test.php, tests/presentations/indexable-post-type-presentation/twitter-creator-test.php, tests/presentations/indexable-presentation/replace-vars-object-test.php, tests/presentations/indexable-term-archive-presentation/canonical-test.php, tests/presentations/indexable-term-archive-presentation/replace-vars-object-test.php, tests/presentations/indexable-term-archive-presentation/robots-test.php, tests/presentations/indexable-term-archive-presentation/title-test.php, tests/presenters/open-graph/description-presenter-test.php, tests/presenters/open-graph/title-presenter-test.php, tests/presenters/title-presenter-test.php, tests/presenters/twitter/description-presenter-test.php, tests/presenters/twitter/title-presenter-test.php
* Renames `replace_vars` property of `Indexable_Presentation` class to `source`.
* `source` property is now used instead of the `context` property to retrieve the source of the indexable (post, archive, page etc.)
* N/A
* Do a smoke test on posts, pages, terms, custom post types, custom taxonomies, archives. See no PHP errors in query monitor or anywhere else.
Fixes #13825
=> 13825 generate replace vars object renaming

admin/class-admin-init.php, src/conditionals/jetpack-conditional.php, src/integrations/third-party/jetpack.php, src/presenters/open-graph/title-presenter.php, tests/conditionals/jetpack-conditional-test.php, tests/presenters/open-graph/title-presenter-test.php
* Deprecates the `wpseo_twitter_metatag_key` filter.
* Renames the `wpseo_og_title` filter to `wpseo_opengraph_title`.
* Adds a Jetpack integration to disable Open Graph when ours is enabled.
* The deprecation of the metatag keys was missing. We no longer support the changing of the keys themselves in the indexables branch. Andy told me this has been discussed and decided upon by product.
* About `wpseo_opengraph_title`. All the filters are named `opengraph`. We had a `wpseo_og_*` way, which is already deprecated. For title this produced `wpseo_og_og_title`, which is obviously wrong. So instead of creating the `wpseo_og_title`, we use the already existing `wpseo_opengraph_title`.
* While searching for the OG filters I found that …
=> Check whether all OG and Twitter filters are correct

inc/health-check-ryte.php
* Improves the copy for the "cannot be indexed" case of the Ryte indexability Site Health check.
- in the file `admin/ryte/class-ryte-request.php` add `$target_url = 'http://testingwceu2019.altervista.org/';` on the first line of the `get_remote()` method: this site is not indexable
- go to the Site Health page and make sure to fetch the Ryte status by clicking the Re-analyze link or by manually appending the URL query parameter `?wpseo-redo-ryte=1`
- see the test listed in the "critical issues" section and reporting "Your site cannot be found by search engines"
Copy before:
Copy after:
Fixes https://github.com/Yoast/wordpress-seo/issues/14253
=> Improve the Ryte health check "cannot be indexed" copy

admin/ryte/class-ryte-option.php, admin/ryte/class-ryte.php, inc/health-check-ryte.php, tests/inc/health-check-ryte-test.php
* Improves the usability of the Ryte indexability Site Health check.
- The check now fetches the Ryte indexability status on page load instead of requiring action from users.
- Keeps the 15 seconds interval set by `FETCH_LIMIT`: new fetches can only happen after 15 seconds from the previous one. Thinking it is good to keep this, can be removed if desired.
- The "not fetched yet" case is now pointless, as the test always runs and fetches on page load. Removed.
- Removed the "Check the indexability status" button that was initially displayed when the Ryte indexability wasn't fetched yet.
- Removed the "Re-analyze site indexability" button as no user action should be required.
- Adjusted the tests: please double check this part as …
=> Improve Ryte site health checks usability

js/src/structured-data-blocks/faq/block.js, js/src/structured-data-blocks/faq/components/Question.js, js/src/structured-data-blocks/faq/legacy/13.1.js, js/src/structured-data-blocks/faq/legacy/index.js, js/src/structured-data-blocks/how-to/block.js
* Adds an ID to the FAQ sections in the front end output.
- added an ID to the `Content` output
- added a block transform: please someone familiar with transforms double check this part: first time trying to code a block transform and it could be totally wrong 🙂 
- fixed a couple ESLint warnings to keep their amount under the current `max-warnings`
**Note:**
I'm not sure how a block transform is supposed to work. For me, the actual output is updated only after the post is updated. I was expecting the transform to be saved automatically. As it works now, it actually requires users to go through all the posts with a FAQ block and update all of them.
**For QA:**
- Install YoastSEO 13.1 …
=> Add an ID to the FAQ sections output

src/generators/schema-generator.php
* N/A - Fixes a bug where FAQ page was missing in the page type
* Altering the pagetype was done in the same loop as the generating was done. Because of this the `schema_page_type` was already set. I've solved this by splitting the logic. 
* In this case the `is_needed` method for the FAQblock was altering the schema_page_type. Unfortunately the `generate` method of the WebPage part was already executed. This causes the `schema_page_type` already been set and altering was not possible.
* Adds a FAQ block to a page and verify the JSON-LD has the right output for page type.
Fixes #14283
=> Show FAQPage as page type in schema output

admin/ajax.php, admin/class-admin.php, js/src/wp-seo-admin-global.js
* Removes remnants of the tagline notice for hte Notification Center.
*
- build
- under WordPress > General Settings make sure to have the default WordPress tagline `Just another WordPress site`
- go to the SEO Dashboard 
- verify there are no PHP or JS errors
Fixes https://github.com/Yoast/wordpress-seo/issues/14352
=> Remove dismiss tagline notice remnants

admin/ryte/class-ryte-request.php, admin/ryte/class-ryte.php, inc/health-check-ryte.php, tests/inc/health-check-ryte-test.php
* Adds errors handling for the Ryte indexability status request.
I'd like this PR to be discussed with a senior dev before CR / Acceptance for a couple important things:
1. Seems to me the `CANNOT_FETCH` case now happens only when users try a new request within the 15 seconds `FETCH_LIMIT` item interval. All errors should now be handled. If I'm correct, we could turn this to our advantage and display a proper message in the Site Health page. Right now, there's no feedback for users that the request didn't run because 15 seconds haven't passed yet.
2. To handle errors there's the need to check the actual response. I've implemented part of the logic within the `WPSEO_Ryte` class instead of putting everything into the …
=> Handle the Ryte API response errors

inc/class-wpseo-admin-bar-menu.php
* Removes the "Get Headers" from the page analysis, as it is no longer available.
* The quixapp was discontinued so the item was simply redirecting to the Yoast homepage.
1.  Install Yoast.
2. Visit a page, go to the admin bar Yoast icon and check the items under "Analyze this page".
3. No "Check Headers" should be visible.
4. All other items in the menu should still work as expected.
Fixes https://github.com/Yoast/bugreports/issues/893
=> Remove the "get headers" item from the adminbar

admin/class-yoast-form.php
* N/A - Created a wrapper that retrieves the values.
* The wrapper method makes it easier to extend the class when there is need to bypass the `WPSEO_Options::get` for getting a value from the options. For example in the Glue for Yoast & AMP plugin. This also makes testing easier.
Fixes #
=> Introduces a method for retrieving the value from the options

src/integrations/breadcrumbs-integration.php, src/surfaces/current-page-surface.php, tests/integrations/breadcrumbs-integration-test.php
* Fixes a bug where a fatal error was thrown when a breadcrumb shortcode was added to a post or page.
* Adds a new `get_presentation` method on the `current_page_surface`.
* Updates the unit tests as well in accordance with the changes.
* Make sure Breadcrumbs are enabled in _SEO_ > _Search Appearance_.
* Add a shortcode (either in a shortcode block in Gutenberg, or using the classic editor).
* Publish the post.
* View the post on the front end.
* The breadcrumbs should be output.
Fixes #14392
=> Fixes the breadcrumbs shortcode.

admin/class-my-yoast-proxy.php, tests/admin/myyoast-proxy-test.php
This is part of the Yoast CS sniff: `WordPress.WP.AlternativeFunctions.file_system_read_readfile`
Preventing the file system readfile.
* Removes the `readfile` flow in the Yoast Proxy (used for the analysis-worker).
*
*
Fixes #
=> Remove the readfile try - go straight into the wp_remote_get

src/integrations/front-end-integration.php
* N/A Fixes a bug where the `twitter:creator` tag was not shown on static homepages.
* Static homepages show the content of a single page, and therefore they should be considered as a singular page when it comes to meta tag output. I added the `Static_Home_Page` page type to a conditional, so that the singular page presenters will not be excluded for this page type.
* I didn't write unit tests because the whole `front-end-integration` class is not yet covered.
* See the issue #14375 
Fixes #14375
=> Consider static homepages to be a singular page

admin/formatter/class-metabox-formatter.php, js/src/edit.js, js/src/redux/actions/settings.js, js/src/redux/reducers/settings.js, js/tests/redux/actions/settings.test.js, js/tests/redux/reducers/settings.test.js
* add siteWideImage to the redux store. 
* add action to do so.
* add tests.
* Add sitewide_social_image to get_defaults function. So the variable is set on the window object. 
* Add a social previews object to the settings with the `sideWideImage` key.  The data for sidewide image is scraped from the window. 
* Add JS-doc in edit.js
* Add tests for the reducer and action.
* Check if the tests resolve.
* Check if `sideWideImage` is available in the yoast-seo/editor redux store.
* If in the Admin-social-settings the default url is set, see if the yoast-seo/editor redux store reflects this.
* Make sure this works in classic and gutenberg.
Fixes #14407
=> 14407 create redux store images

inc/health-check-curl-version.php, tests/inc/health-check-curl-version-test.php
Changes status of the cURL Health Check from recommended to critical (#14149).
* Changes cURL Health Check to `critical` instead of `recommended`.
*
* uninstall any premium plugin (just move out the plugins from the WP plugins directory) and keep just Yoast SEO Free
* go to the Site Health page: Tools > Site Health
* verify the test doesn't run
**Can connect case:**
* bring back at least one of the premium plugins e.g. Video (no need to activate it)
* go to the Site Health page
* the test should run and pass: expand the "Passed tests" section and verify the copy: 
- label: "Your site can connect to my.yoast.com"
- description: "Great! You can activate your premium plugin(s) and …
=> Changes cURL Health Check status from recommended to critical

frontend/schema/class-schema-article.php, frontend/schema/class-schema-webpage.php
* Adds a `potentialAction` entity to the `WebPage` and `Article` Schema pieces.
Introduces two new filters to extend the action targets.
> When a page contains a valid Article piece, and comments are _enabled_ for the page ...
I made it in a way that `potentialAction` is output only when there are _approved_ comments regardless whether comments are enabled. For example, a post might have comments initially enabled and get some comments. Later on, the admin might decide to disallow comments. Also, we need to take into consideration the WordPress setting `Automatically close comments on posts older than nn days` could be on.
> We assume that {{URL}}#comment ...
Note that the URL fragment identifier that WordPress uses by default is …
=> Add potentialAction to webpage and article Schema

admin/class-option-tabs-formatter.php, css/src/base/colors.css, css/src/components/tabs.css, css/src/editor/post-overview-global.scss, css/src/editor/yst_plugin_tools.scss, js/src/wp-seo-admin.js
* Both the HTML and the CSS for the navigation tabs is changed. 
*
* Checkout this PR, see the UI change. There's also a mobile view, with the tabs separated and wrapped next/below each other.
Fixes #14284
=> Change HTML and CSS for nav tabs

inc/class-wpseo-utils.php
* Compare URL percent-encoding as case insensitive
* According to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.1) we should use [strcasecmp](https://www.php.net/manual/en/function.strcasecmp.php) to compare percent-encoded characters:
> The uppercase hexadecimal digits 'A' through 'F' are equivalent to the lowercase digits 'a' through 'f', respectively. If two URIs differ only in the case of hexadecimal digits used in percent-encoded octets, they are equivalent.
* Try to save URLs (canonical or social account.) with lower-case and upper-case percent-encoded URLs
Partially fixes …
=> Use strcasecmp to compare encoded URLs

src/context/meta-tags-context.php, tests/context/meta-tags-context-test.php
* When a company does not have a logo set, it is not valid schema output.
* With the porting to indexables, a set should've been replaced to a return.
* Fixes a bug where article and company schema graph would be output when the site had a company without a logo.
* Added tests for the touched method.
* Set Knowledge graph to Organisation, enter a name but DO NOT upload logo.
* Open published post and grab schema.
* When company logo is not uploaded, then it is expected to get only WebSite, WebPage and Person (publisher) nodes (and no Organisation and Article).
Fixes #14426
=> Fix site represents checks in context

inc/class-wpseo-utils.php, integration-tests/test-class-wpseo-utils.php, tests/inc/options/option-social-test.php
* Force percent-encoding of URLs before saving to the database.
* Use [wp_parse](https://developer.wordpress.org/reference/functions/wp_parse_url/) and [parse_str](https://www.php.net/manual/en/function.parse-str.php) to get all parts of the URL, then sanitize all parts, encode them and re-build the URL.
* Save non-encoded URL (which contains utf8 characters) as canonical or social URL.
Fixes #14487, #7664.
=> Improve method sanitize_url

migrations/20171228151840_WpYoastIndexable.php, src/repositories/indexable-repository.php
Removes unused indices from the indexables migration.
* N/A
* Indices were optimized for the majority if sites. Indices that would only apply to a very small percentage of sites with large amounts of posts were not added.
* Remove all indexable-related tables.
* Run the migrations
* You should have all required tables and 3 indices on the indexables table ( one being the primary key index ).
=> Remove unused indexable indices

src/integrations/watchers/indexable-post-type-archive-watcher.php, src/integrations/watchers/indexable-term-watcher.php, tests/integrations/watchers/indexable-author-watcher-test.php, tests/integrations/watchers/indexable-date-archive-watcher-test.php, tests/integrations/watchers/indexable-home-page-watcher-test.php, tests/integrations/watchers/indexable-permalink-watcher-test.php, tests/integrations/watchers/indexable-post-type-archive-watcher-test.php, tests/integrations/watchers/indexable-post-watcher-test.php, tests/integrations/watchers/indexable-static-home-page-watcher-test.php, tests/integrations/watchers/indexable-system-page-watcher-test.php, tests/integrations/watchers/indexable-term-watcher-test.php, tests/integrations/watchers/primary-term-watcher-test.php
* It improves testcoverage for the integrations/watchers.
* N/A - It just adds tests
* I removed a `if ( ! is_array( $old_value ) || ! is_array( $new_value ) ) {` because it is not testable and the filter is called by WordPress. If the type is wrong, someone is hacking this makes me believe won't be our problem.
* I also formatted some expectation changes over more lines to make it more readable.
* If Travis is happy, merge!
Fixes #
=> Add tests for integrations/watchers

src/generators/schema/author.php, tests/generators/schema/author-test.php
* We want to take the code coverage of the indexables code to 100%.
* Takes the code coverage of the author Schema generator to 100%.
*
* Check that travis passes.
* Run the unit tests in `tests/generators/schema/author-test.php` with code coverage.
* Check that `generators/schema/author.php` has a coverage of 100%.
Fixes #
=> Adds tests for the author Schema generator

src/generators/schema/breadcrumb.php, tests/generators/schema/breadcrumb-test.php
* We do not want breadcrumbs on error pages.
* Fixes a bug where the breadcrumbs schema would be output on error pages.
*
* Make sure Breadcrumbs are enabled in Search Appearance - Yoast SEO.
* Browse to non-existing post.
* Check that you get 404 RC and grab schema. There should not be a `"@type":"BreadcrumbList"` graph included. See issue for what it was.
Fixes #14420
=> Don't output breadcrumb schema on error pages

src/generators/schema/article.php, tests/doubles/generators/schema/article-double.php, tests/generators/schema/article-test.php
* We want 100% code coverage in the indexables branch.
* N/A Add unit tests for article generator.
* There is one big unit test (`test_generate`) that walks through the `generate` function and a lot of the private functions (this was already the case before I started working on the code).
* I now give the `test_generate` function a provider to test all the different paths.
* This approach didn't work for the `add_terms` function, because there are `return` statements in different places depending on the path that is followed. You cannot return in the middle of a unit test.
* Therefore, `add_terms` is now covered in its own unit tests. I had to create a double to make `add_terms` testable, and change its visibility from `private` …
=> Add unit tests for article generator

admin/class-yoast-form.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-fields-presenter.php, admin/taxonomy/class-taxonomy-settings-fields.php, admin/views/tabs/social/accounts.php, frontend/class-frontend.php, frontend/class-opengraph.php, frontend/schema/class-schema-organization.php, inc/class-wpseo-meta.php
* We want urls to be human readable, both in our forms and in the metadata we output on the frontend.
When you input a url containing letters from a non-roman alphabet. The url will be escaped and encoded before it is stored.
It is also possible to submit a url in which these letters are already encoded.
In any case, these urls will now be shown unencoded the next time the users loads the form, and they will appear unencoded in the metadata on the frontend.
Only in the schema will they still remain encoded, but this is because the schema is a JSON string and the Array containing the string is JSON encoded.
This logic has been applied to:
- canonical field on posts and terms
- canonicals on the frontend
- OG urls on the frontend
- Social profiles fields for organization in the Yoast SEO …
=> Human readable url output

frontend/class-frontend.php
This makes sure that someone can no longer escape from the href field in the frontend.
Before, it was possible to escape the `href` field in the `<link>` tag by entering something like this as the canonical URL: `" onafterprint="console.log(0)`.
We circumvent this problem if we first decode the URL and then use `esc_url`.
Now, entering `" onafterprint="console.log(0)` is still allowed but creates the following link tag:
```
<link rel="canonical" href="http://%20onafterprint=console.log(0)" />
```
Which is fine™️.
**Note: we might still benefit from extra validation on the URL but that is something that can be picked up later.**
* Fixes a bug where entering `"` in the canonical URL would lead to HTML injection in the canonical …
=> Change the order in which the functions are executed

src/integrations/front-end-integration.php, tests/integrations/front-end-integration-test.php
Restores logic that used to be present in the plugin which sites, such as yoast.com, implicitly rely upon.
* N/A
* Logic was returned from the initial class-frontend. This logic was also present, although without checks, in class-opengraph and class-twitter.
* Deploy it to staging.yoast.com
* Posts should have content.
=> Restore wp_query logic that used to be present in the plugin

src/integrations/watchers/indexable-term-watcher.php
* Because of performance reasons, we want indexables to be built when posts, terms, pages etc. are created, instead of lazily building them when they are being output on the frontend. This PR introduces this behavior for terms.
* An indexable for a term will be built when a term is created.
* I looked at the hooks that build the home page and static home page indexables. It hooks into all the applicable hooks as far as I can tell.
* Create a new category or tag.
* Look in the `wp_yoast_indexable` table. There should be a row representing the newly created indexable.
* E.g. with `object_type` 'term' and `object_id` being the ID of the respective term.
Fixes #14516
=> An indexable is built for a term when it is created.

src/presentations/indexable-static-posts-page-presentation.php, tests/presentations/indexable-static-posts-page-presentation/open-graph-url-test.php, tests/presentations/indexable-static-posts-page-presentation/presentation-instance-builder.php
* On static posts pages, the `og:url` meta tag showed the home URL instead of the unpaginated URL of that page.
* N/A Fixes a bug where the `og:url` meta tag showed the home URL instead of the unpaginated URL of a static posts page.
* I considered whether `generate_open_graph_url()` should have any fallbacks. I looked for other examples. In `indexable-presentation`, `$this->model->permalink` is the final code, and there is no further fallback. In addition, if `$this->model->permalink` is not found in `generate_open_graph_url()`, the presenter will output an empty string. So it seems like the situation is safe enough.
* Create a new page
* In `Settings` -> `Reading`, set your …
=> Fix og:url for static posts pages

src/integrations/front-end-integration.php, src/presenters/title-presenter.php, tests/integrations/front-end-integration-test.php
Themes that don't support the title-tag and thus always output their own hardcoded title currently conflict with indexables and will result in two title tags being output.
This PR adds compatibility for those themes by removing the Title presenter and additionally always filtering the title to remain as compatible as possible with other themes and plugins.
* N/A
* Requires testing on staging.yoast.com, which means it needs to be merged to the feature branch first.
=> Handle themes that do not support title-tag

admin/links/class-link-reindex-dashboard.php, admin/pages/tools.php, css/src/admin/all.css, css/src/components/card.css, css/src/components/headings.css, css/src/components/lists.css, css/src/components/tabs.css
*
* Add some styling to the tools page
* Because of some minor differences in positioning of the default bullet points between Firefox and Chrome, I've decided to create custom bullet points.
*
Fixes #14295
=> Add styling for tools page

src/generators/schema/author.php, tests/generators/schema/author-test.php
* The schema author graph piece was output incorrectly when the site represented an Organization. 
* This was because the author schema generator wasn't called, even though it should be. 
* The reason was that a check which was meant to prevent duplicate code when the site represented a Person, was incorrectly applied also when the site represented an Organization.
* N/A
* There was already a check in place to prevent duplicate graph pieces being output when the site represents a Person, and the post author is the same as the person that the site represents.
* Now, we only call this check when the site is set to represent a Person, and not an Organization.
* To reproduce the …
=> Fix author not being output when site represents organization

inc/class-wpseo-utils.php, integration-tests/test-class-wpseo-utils.php
* Related PR #14502
* Removes reserved characters from host component.
*
Steps performed by @andizer:
* I've test this by navigating to the social fields and there I have given `https://" onafterprint="console.log(0)` as value for the facebook url.
* I also added the value as canonical in the metabox. 
Fixes #
=> Better checking authority/host parts in URL

src/generators/breadcrumbs-generator.php, src/repositories/indexable-repository.php, tests/generators/breadcrumbs-generator-test.php
This gathers the home page and page for posts indexables in the breadcrumbs using existing methods rather than custom queries so they are created automatically if they are missing.
* N/A
* Delete all indexables and all indexable hierarchies.
* Visit a random post that's not your homepage.
* Your homepage should be present in the schema output of that page.
Fixes #14545
=> Fix breadcrumbs home when indexables do not yet exist

inc/sitemaps/class-sitemaps.php
* We set the `Cache-Control` header of `.xsl` files with the intent to cache this file for a year. The current directive is written wrong (without a dash) so it's not working as intended.
* Fixes the cache control header of `.xsl` files to cache for a year.
Small performance improvement by having `.xsl` files cached for longer. The functional effect varies per browser / server / CDN, since this value can get overridden or ignored. But to make it work without any interference, `max-age` [should be written with a dash](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Cache_request_directives).
From a theoretical perspective, these are steps to verify that the …
=> Added a dash to max-age in caching headers of .xsl files

admin/tracking/class-tracking.php
* [wordpress-seo-premium] Non-user-facing: adds the `content-type: application/json` header to the tracking request.
* The tracking application now forces all requests as json, even when they may be not valid json. This fix will let the request set this value so that error handling will be clearer.
Once this pull is active, every tracking request should have a HTTP header with the value `content-type: application/json`. This is not easily tracked and will need cooperation from DevOps.
1. Install Yoast premium (this code only activates in premium at the moment).
2. Clear all site transients (just to make sure).
3. Visit the SEO dashboard page.
You will see nothing happen, but the …
=> Add content-type header to request

deprecated/frontend/schema/class-schema-image.php
* This pull request makes sure that the 'deprecated' schema classes are returning actual values instead empty arrays.
* N/A - It brings back a better backwards compatibility for `WPSEO_Schema_Image`
*
* Add this code somewhere in a theme or in the wp-seo.php file. 
```php
$image_helper = new WPSEO_Schema_Image( 'foo' );
print_r( $image_helper->generate_from_url( 'https://example.org/image.jpg', 'This is a caption' ) );
// I've used 12 as attachment id. You might have to check for on in your database.
print_r( $image_helper->generate_from_attachment_id( 12, 'This is a caption' ) );
print_r( $image_helper->simple_image_object( …
```
=> Improve backwards compatibility of deprecated methods.

src/integrations/front-end-integration.php, tests/integrations/front-end-integration-test.php
Themes differ in when they register their support for various features. During register_hooks `title-tag` support may not yet be registered. This delays the check so even if themes register support slightly later they will still get picked up.
* N/A
* Visit any page with twentytwenty active. You should see a title.
* error pages
* homepage
* search page
* custom post type
* custom taxonomy
* any other page you want to check, like normal post
Fixes https://github.com/Yoast/wordpress-seo/issues/14561
Fixes https://github.com/Yoast/wordpress-seo/issues/14562
Fixes https://github.com/Yoast/wordpress-seo/issues/14563
Fixes https://github.com/Yoast/wordpress-seo/issues/14564
=> Fix title interaction with themes

deprecated/frontend/schema/class-schema-utils.php
* This pull gives a better backwards compatibility experiences by returning actual values instead of empty values.
* N/A - It does a fallback on the new helpers.
*
* Add this somewhere in the code that is executed on your test environment
```php
$context = (object) [ 'site_url' => get_home_url() ];
print_r( WPSEO_Schema_Utils::get_user_schema_id( 1, $context ) );
print_r( WPSEO_Schema_Utils::get_post_title_with_fallback( 1 ) );
print_r( WPSEO_Schema_Utils::add_piece_language( [] ) );
} );
```
* Verify that there is output. 1. shows an url, 2. will show a post title and 3. will return an array with an inLanguage tag.
Fixes #14574
=> Have better BC in WPSEO_Schema_Utils

grunt/config/aliases.yaml, grunt/config/clean.js
* There were no RTL stylesheets for the monorepo css. This PR fixes that.
* N/A
* The issue was that the `build:js` step (which generates `monorepo-....css` took place after the `build:css` step (which creates the RTL stylesheets).
* Executing `build:js` first works, but `build:css` had a step that threw away the entire `css/dist` folder, including monorepo css. Therefore I added the responsibility of cleaning monorepo css to `clean:build-assets-js`, and ignored monorepo css for `clean:build-assets-css`.
* Link the monorepo on the develop branch.
* Build the plugin, (definitely run `grunt build`)
* Verify that it says ```Running "rtlcss:build" (rtlcss) task
[...]
File …
```
=> Make sure monorepo css survives grunt build steps

deprecated/frontend/schema/class-schema-breadcrumb.php
* This pull gives a better backwards compatibility experiences by returning actual values instead of empty values.
* The deprecated `WPSEO_Schema_Breadcrumb` class now falls back to the new `Yoast\WP\SEO\Generators\Schema\Breadcrumb` class.
*
* Add this to `wpseo.php` in your test environment
```php
add_action( 'wp_head', static function() {
$breadcrumbs = new WPSEO_Schema_Breadcrumb();
// Should output '1'.
print_r( $breadcrumbs->is_needed() );
// Should output a breadcrumb list Schema piece.
print_r( $breadcrumbs->generate() );
} );
```
* Open a post on the frontend of your website.
* Open the browser's console.
* Just below the `<body>` tag, you should see two things:
* The …
=> Implements BC for WPSEO_Schema_Breadcrumb.

src/generators/schema/webpage.php, src/generators/schema/website.php, tests/generators/schema-generator-test.php, tests/generators/schema/website-test.php
* To create an array of potentialAction elements to be future proof because there may occur more than one potentialAction in the future
* Implements a potentialAction array instead of a single value, so when more potentialActions are added in the future the website schema is able to adapt to it. 
* Created a simple array with adding [] 
* Webpage and article already implement the array the same way, this is the last one to be updated
* Create a page
* Add a title and some content
* Publish
* Inspect the schema output of website
* Note that the website schema output should have one potentialAction (SearchAction)
* Use the following filter:
```
add_filter( 'wpseo_schema_website', …
```
=> implemented potentialAction array in website schema

deprecated/frontend/schema/class-schema-article.php, deprecated/frontend/schema/class-schema-author.php, deprecated/frontend/schema/class-schema-faq.php, deprecated/frontend/schema/class-schema-howto.php, deprecated/frontend/schema/class-schema-main-image.php, deprecated/frontend/schema/class-schema-organization.php, deprecated/frontend/schema/class-schema-person.php, deprecated/frontend/schema/class-schema-webpage.php, deprecated/frontend/schema/class-schema-website.php, src/generators/schema/author.php
* This pull request makes sure that the 'deprecated' schema classes are returning actual values instead of empty arrays.
* Improves backwards compatibility for basic schema classes.
* Fixes a bug where the author schema output could generate a notice when not on a post.
*
* Add this code somewhere in a theme or in the `wp-seo.php` file. This is a hacky way of testing. Using the `wp_footer` hook to make sure the normal schema context is already filled. Which should be done as well when the normal implementation is used.
```php
add_action( 'wp_head', function () {
$schema    = new \WPSEO_Schema_Article();
$is_needed = $schema->is_needed();
$post_type = \get_post_type();
echo …
```
=> Improve backwards compatibility for basic schema classes

src/generators/schema/author.php, tests/generators/schema/author-test.php
* We want to short-circuit the output of author schema when no valid user ID is given out of the application of the `wpseo_schema_person_user_id` filter.
* We now check if the result of applying the `wpseo_schema_person_user_id` filter in the author schema outputs a valid user ID. If it is invalid, no author schema is output.
*
* Add this code somewhere in the code, for example in `wp-seo.php`:
```php
add_filter( 'wpseo_schema_person_user_id', function( $user_id ) {
return 'invalid_user_id';
} );
```
* Go to a post on the frontend.
* Check the schema. It should **not** contain a `Person` graph piece.
* Replace the above code with this code:
```php
add_filter( …
```
=> Add safety check around filter author schema

admin/class-yoast-form.php, js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap, js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
* Fixes a bug where form fields were validated inconsistently
* Fixes a bug where form fields were validated inconsistently.
* Just put novalidate on the form.
* Decided to let the other forms in the plugin alone where we don't run into this problem.
* Try to reproduce https://github.com/Yoast/bugreports/issues/930, see it's fixed.
Fixes https://github.com/Yoast/bugreports/issues/930
=> Add novalidate to our forms as we don't use native validation.

tests/generators/schema/website-test.php
* We want the cover all the code paths in the website schema generator to check if they work correctly and keep working correctly in the future.
* Adds unit tests for the website schema generator.
*
* Check that Travis passes.
* Run the unit tests, with coverage, locally. Check that the code coverage of `src/generators/schema/website.php` is 100%.
Fixes #
=> Add tests for website schema

admin/links/class-link-watcher.php, integration-tests/admin/links/test-class-link-watcher.php
* In some case the second argument given to the method which is executed by a hook isn't an instance of `WP_Post` resulting in fatal errors. By removing the type hint we can prevent these failures. These means we have to check the instance of given argument in the method itself and return early when the type is not a WP_Post
* Fixes a bug when a fatal error is given when saving a post.
* 
* Have error reporting enabled
* On trunk: Add this to your code and visit an admin page
```php
add_action( 'admin_init', function() {
$watcher = new WPSEO_Link_Watcher(
new WPSEO_Link_Content_Processor(
new WPSEO_Link_Storage(), new WPSEO_Meta_Storage()
)
);
$watcher->save_post( 12, null );
} ); …
```
=> Stop forcing WP_Post object

src/integrations/front-end/redirects.php, tests/integrations/front-end/redirects-test.php
* Attachment redirects should be 301.
* None needed, this was an unintended change.
* Attachment URLs should throw a 301 redirect now instead of 302.
Fixes https://github.com/Yoast/bugreports/issues/941
=> Attachment redirects should be a 301

src/integrations/watchers/option-titles-watcher.php, src/repositories/indexable-hierarchy-repository.php, src/repositories/indexable-repository.php, tests/integrations/watchers/option-titles-watcher-test.php, tests/repositories/indexable-hierarchy-repository-test.php, tests/repositories/indexable-repository-test.php
* When we change the taxonomy to show for a certain post type we want to remove the indexable hierarchy records for the belonging indexables. This allows us to recalculate the hierarchy for these posts
* N/A - Fixes a bug where wrong breadcrumbs are shown when changing the primary taxonomy to show for the breadcrumbs.
* Decided to add extra tests for the hierarchy repository, because I had the context.
* Temporary added `codeCoverageIgnore` for the query method, because testing this one was too complex. In mockery aliasing, overloading doesn't work. Also in combination with `@runInSeperateProcess` won't work. This needs more investigation... (but that is for a later moment)
* The `-1` check for ancestor_id has been changed to `0` …
=> Lazily update indexable hierarchy

deprecated/frontend/schema/class-schema-article.php, deprecated/frontend/schema/class-schema-author.php, deprecated/frontend/schema/class-schema-breadcrumb.php, deprecated/frontend/schema/class-schema-faq-question-list.php, deprecated/frontend/schema/class-schema-faq-questions.php, deprecated/frontend/schema/class-schema-faq.php, deprecated/frontend/schema/class-schema-howto.php, deprecated/frontend/schema/class-schema-image.php, deprecated/frontend/schema/class-schema-main-image.php, deprecated/frontend/schema/class-schema-organization.php, deprecated/frontend/schema/class-schema-person.php, deprecated/frontend/schema/class-schema-utils.php, deprecated/frontend/schema/class-schema-webpage.php, deprecated/frontend/schema/class-schema-website.php, deprecated/frontend/schema/class-schema.php
* Till we have a surface for easily accessing helper methods we shouldn't show any deprecation notices on the schema classes. We only do the Schema classes because we have publicly communicates its api.
* N/A - I've commented out all `_deprecate_function` calls.
*
* Nothing should break. Only deprecation notices shouldn't pop up.
Fixes #
=> Temporary disable the deprecation notices for schema.

src/presenters/open-graph/image-presenter.php, tests/presenters/open-graph/image-presenter-test.php
* After discussion with Facebook's developer relations team we've decided to drop the `og:image:secure_url` tag. We'd always output next to an `og:image` tag and there's basically no value in doing that.
* See output for any post with images that is on https, see we no longer have `og:image:secure_url` in our output.
Fixes #14644
Fixes #14635
=> Drop og:image:secure_url

src/initializers/initializer-interface.php, src/integrations/integration-interface.php, src/loadable-interface.php
* Local SEO uses the old `Initializer`, `Integration` and possibly `Loadable`. Yoast SEO is a dependency of Yoast SEO Local. In order to not throw fatal errors when someone updates Yoast SEO 14.0 when Local SEO is not updated yet, the new classes need an alias.
* Add class aliases for Initializer, Integration and Loadable
* N/A
* Run this branch together with the Local SEO 12.9 release branch.
* See no fatal errors.
Fixes #
=> Add aliases for Initializer, Integration and Loadable

src/backwards-compatibility/frontend.php, src/generators/schema/author.php, src/generators/schema/breadcrumb.php, src/generators/schema/faq.php, src/generators/schema/howto.php, src/generators/schema/main-image.php, src/generators/schema/organization.php, src/generators/schema/person.php, src/generators/schema/webpage.php, src/generators/schema/website.php, src/helpers/schema/id-helper.php, src/integrations/front-end/comment-link-fixer.php, src/integrations/front-end/indexing-controls.php, src/integrations/front-end/rss-footer-embed.php
* `@since` should only used to indicate public api. This means for hooks (actions and filters). 
* Most of the `@since` are copied from the old code and aren't backwards compatible because of the namespaces.
* N/A - It just removes `@since` annotations.
* Kept the `@since` for the hooks.
* It is a code wise change only
Fixes #
=> Removal of @since where possible

package.json, yarn.lock
*
* Bumps the monorepo packages for 14.0-RC1.
* Also bumped `yoastseo` from RC to actual version. Not sure why this was wrong here.
*
Fixes #
=> Bump monorepo packages for 14.0-RC1

src/integrations/front-end-integration.php, tests/integrations/front-end-integration-test.php
* When a theme does not explicitly support WordPress handling the title tags and force rewriting of the title is enabled, we remove the pre-existing title-tags from the webpage. However, since https://github.com/Yoast/wordpress-seo/pull/14555 removed our own title tag when a theme does not have support, we ended up without any title at all if force rewriting was enabled.
* Fixes a bug where no `title` tag was output when force rewriting titles is enabled.
*
* Have a theme that has a hardcoded `<title><?php wp_title(); ?></title>` in the `header.php`.
* The simplest way is to add it manually to your activated theme.
* Make sure the theme does not register support for title-tag.
* To …
=> Our own title tag is only removed is force rewriting of the title is disabled.

src/builders/indexable-hierarchy-builder.php
* In pull request #14652 an `is_wp_error` check was missing. I've added this.
* N/A - Extra safety check.
*
* This is an extension for #14652 and it adds an extra sanity check and therefore its hard to test.
Fixes #
=> Add is_wp_error check

admin/class-admin-init.php, deprecated/frontend/class-handle-404.php, deprecated/frontend/class-opengraph-image.php, deprecated/frontend/class-opengraph-oembed.php, deprecated/frontend/class-opengraph.php, deprecated/frontend/class-primary-category.php, deprecated/frontend/class-twitter.php, frontend/class-woocommerce-shop-page.php, inc/wpseo-functions-deprecated.php, inc/wpseo-functions.php, src/backwards-compatibility/frontend.php, src/integrations/front-end/theme-titles.php, tests/integrations/front-end/theme-titles-test.php, wp-seo-main.php
* We didn't know what the exact version of the indexables release has to be. Therefore we decided to set all version related things (e.g. deprecations) to xx.x. Now we know the version will be 14.0.
* N/A Updates all xx.x versioning to 14.0
*
* If the code looks good, just merge.
Fixes #13814
=> Sets the deprecated version to 14.0

src/functions.php, src/initializers/initializer-interface.php, src/integrations/integration-interface.php, src/loadable-interface.php, wp-seo-main.php
* Class aliasses were added to maintain compatibilty between Yoast SEO and Yoast SEO: Local. These were added by @IreneStr . However it turns out that the aliasses were called in a too late stadium resulting in fatal errors in Local. We have moved the aliasses to `/src/fuctions.php` to make sure they are called in time.
* Fixes issue where class aliasses are called too late, resulting in fatal erros in Local SEO
* Run this branch together with the Local SEO trunk branch and a .zip from Local SEO trunk
* See no fatal errors.
Fixes #
=> Move class aliasses

deprecated/frontend/schema/class-schema-person.php
* The BC should include protected functionality for class extensions.
* Adds person schema backward compatibility for the protected functionality.
*
Compare [old code](https://github.com/Yoast/wordpress-seo/blob/3c927425518c3529125b91a04e57e6bcde465a98/frontend/schema/class-schema-person.php) to the current and see that I did not skip any `public` or `protected` methods or properties.
Not really testing the protected functionality here. As this would require writing your own implementation. The following covers testing of the same tests as done before in https://github.com/Yoast/wordpress-seo/pull/14583:
* Add this code somewhere in a theme or in the `wp-seo.php` file.
``` …
```
=> Change backward compatibility of person schema to include protected functionality

admin/class-config.php, admin/class-yoast-dashboard-widget.php, admin/config-ui/class-configuration-page.php
* We want the Javascript monorepo styles to be available on the wordpress-seo admin pages.
* [non-user-facing] Adds Javascript monorepo stylesheets to admin pages.
* N/A
* Checkout branch, have monorepo linked to a recent branch (preferably develop) with `yarn link-monorepo`.
* Build everything.
* Verify that the stylesheets are present on the expected pages by searching for `monorepo` in the inspector of your browser.
* Visually inspect the admin pages.
Fixes #14580
=> Enqueue monorepo styles on admin pages

inc/class-rewrite.php, integration-tests/test-class-rewrite.php
The filter `category_link` is deprecated since WordPress 2.5. WordPress 5.4 will start displaying a warning. See https://github.com/WordPress/WordPress/blob/641c632b0c9fde4e094b217f50749984ca43a2fa/wp-includes/taxonomy.php#L4259-L4268
This PR replaces the use of the `category_link` filter by `term_link` as suggested by the warning.
=> WP 5.4: Fix category_link deprecated warning

src/generators/breadcrumbs-generator.php, tests/generators/breadcrumbs-generator-test.php
* Fixes issues with the breadcrumbs where the home crumb wasn't using the correct text and post type archives of custom post types weren't being added.
* N/A
* Enable our breadcrumbs
* Make sure you have a custom post type.
* Visit a post of that post type.
* You should see the custom post type archive in the breadcrumbs.
Fixes #14679
Fixes #14658
=> Breadcrumb fixes

src/integrations/front-end-integration.php, tests/integrations/front-end-integration-test.php
* Adds required open graph output to 404 pages.
* N/A
* Adds a separate array of open graph error presenters as to preserve the order of open graph presenters on other pages.
* Visit a 404 page. You should see open graph locale, title and site name tags.
Fixes #14654
=> Fix open graph output on 404 pages

src/models/indexable-hierarchy.php, src/models/indexable.php, src/models/primary-term.php, src/models/seo-links.php, src/models/seo-meta.php, src/orm/yoast-model.php
* Automatically casts all int values to ints instead of them being strings.
* N/A
* Uses the same implementation already used for booleans.
* All properties in int_columns should be ints.
=> Add support to automatically cast all int columns of yoast models

src/integrations/front-end-integration.php
* We need an extra filter to add additional presenters to the frontend integration. This allows our plugins to add extra meta tags. For example: https://github.com/Yoast/wpseo-news/pull/625
* N/A - Introduces an extra filter for adding presenter instances.
*
* It only introduces a filter, it's best to test this together with https://github.com/Yoast/wpseo-news/pull/625
Needed for https://github.com/Yoast/wpseo-news/pull/625
=> Introduces a filter to add presenter instances

admin/class-admin-asset-manager.php
* In https://github.com/Yoast/wordpress-seo/commit/2b2b4975d790d5c388dcba6a6ec35949cacc98b1#diff-dc369be3d1812b2810483ec8bdf3c377 we started enqueuing styles from the monorepo. However, those styles had unwanted consequences in the metabox of Free, Premium, News, and Local (see issues below). Those styles are needed in the upcoming reactifications, but not in the indexables release. @JoseeWouters will make sure those unwanted consequences will seize to exist, but in order to make the indexables release as risk-free as possible, this PR makes sure the monorepo styles are no longer enqueued. 
* Fixes a bug where styles from the monorepo were seeping through in the 14.0. 
* I didn't remove the following lines to make reverting this …
=> Don't enqueue the monorepo CSS

admin/class-admin-asset-dev-server-location.php, integration-tests/admin/test-class-admin-asset-dev-server-location.php
* The dev server was broken on trunk. All JS assets gave 404 errors. This PR fixes that.
* Fixes a bug where JS assets returned 404's when running Webpack dev server.
* I honestly don't understand how this could have worked before. But it seems that since we added the CSS loader in https://github.com/Yoast/wordpress-seo/pull/14548 the Webpack server is broken and no longer serves assets from the root, but from js/dist. As I think this actually makes more sense, I decided to not try to bring it back in the old condition and simply change the path for dev assets. 
* Confirm it is broken in trunk.
* Confirm this PR fixes it.
=> Fix devserver assets

src/generators/open-graph-image-generator.php, tests/generators/open-graph-image-generator-test.php
* Restores using the first content image if no open graph image or featured image has been set.
* N/A
* This does not use gallery images. The current code on master does not use them either and to keep things simple and consistent with previous behavior I've elected to not use them here either.
* Create a post that does have images it in it but no featured image or open graph image set.
* The first image from the content should be in the open graph tags.
Fixes #14695
=> 14695 restore og content image

src/integrations/front-end/backwards-compatiblity.php
* Ensures we're still calling the `wpseo_opengraph` and `wpseo_twitter` actions as we did previously.
* N/A
* Actions are called exactly as they were. This does mean that anything output during this time will no longer be between our debug markers.
* This also means we don't have to use output buffering to ensure we don't lose performance or memory over this.
* Add your own output to the `wpseo_opengraph` and `wpseo_twitter` actions.
* You should see your output.
* You should see deprecation warnings.
=> Restore open graph and twitter actions

inc/sitemaps/class-sitemaps.php
* Fix `ORDER BY` clause.
* Improve ORDER BY clause to match SQL standards. Props to [rafaelbernard](https://github.com/rafaelbernard).
* This is a non-brake change. I use Postgres as RDBMS. This is compatible with standard MySQL/MariaDB installations and as also "non-supported" as PG. :-)
* N/A - this is a code-only change and should have no effect on the functionality.
~~* [ ] I have written documentation for this change.~~
Fixes #
=> Fix ORDER BY for get_last_modified_gmt function

readme.txt
changelog: bugfix
- Fixes a bug where the Frequently asked questions were broken on WordPress.org plugin’s page. Props to [audrasjb](https://github.com/audrasjb).
* Open WordPress.org plugin’s page, and see errors in some FAQ items.
=> Fixes several mistakes on WordPress.org readme.txt file

src/integrations/front-end-integration.php
* The abstract (interface) has been changes this means some public properties has to be set manually. 
* N/A - Its a codewise change only.
*
* It was something I've spotted when having PHP storm opened. You can reproduce it by adding this to the bottom of wp-seo.php
```
add_action( 'wp_head', function() {
echo wp_title();
exit;
}, 999 );
``` 
- This will give errors on the release branch and that error should be gone on this branch.
Fixes #
=> Adapt the new presenter interface

src/integrations/front-end-integration.php, src/presenters/debug/marker-close-presenter.php, src/presenters/debug/marker-open-presenter.php, tests/presenters/debug/marker-close-presenter-test.php, tests/presenters/debug/marker-open-presenter-test.php
* The debug markers are misplaces when adding new presenters using the filter.
*  N/A - 
* Add an `is_array` check and show original presenters when the outcome is false.
* Introduced a filter to disable the debug markers.
* Verify the output of the meta tags, especially the debug markers, is still the same compared to the release branch
* Add the following filter and verify that the debug markers are gone:
```
add_filter( 'wpseo_debug_markers', '__return_false' ); 
```
Needs #14706
=> Add debug markers later

src/integrations/breadcrumbs-integration.php, tests/integrations/breadcrumbs-integration-test.php
*
* Fixes the breadcrumbs shortcode not being output
* Fix is also included in #14569 and was taken from there.
* Add `[wpseo_breadcrumb]` shortcode to any post.
* It should be output.
Fixes #14710
=> 14710 fix breadcrumbs shortcode

src/integrations/third-party/amp.php, tests/integrations/third-party/amp-test.php
* Ensures no duplicate tags are output on AMP pages with the official AMP plugin.
* A new integration has been added to keep things separated.
* Activate the official AMP plugin.
* Visit the AMP version of any post ( add `/amp/` to the URL ).
* There should be no duplicate title, schema or canonicals output.
Fixes #14713
=> Fix AMP meta output by adding new AMP integration

tests/generators/schema-generator-test.php, tests/generators/schema/article-test.php, tests/generators/schema/author-test.php, tests/generators/schema/breadcrumb-test.php, tests/generators/schema/faq-test.php, tests/generators/schema/organization-test.php, tests/generators/schema/website-test.php, tests/helpers/blocks-helper-test.php, tests/helpers/home-url-helper-test.php, tests/helpers/options-helper-test.php, tests/presentations/indexable-static-home-page-presentation/presentation-instance-builder.php
Use a comma after each array item, including after the last item.
* _N/A_
=> CS: comma after each array item in multi-line arrays

inc/health-check-ryte.php
* Translatable string was not being translated.
* Improved translatability.
The function call was already set up for a translatable string, just using the wrong function.
`esc_html()` only escapes. `esc_html__()` escapes and tranlates.
/cc @IreneStr Should this one be backported to `14.0` ?
* Using the `trunk` branch, switch to another language and see this text string still in English.
* Switch to this branch, make sure there is a translation available and see the text string in the chosen language.
* (or use the Pig Latin plugin to see that the text string is picked up as translatable)
=> Bug fix: make text string translatable

tests/integrations/breadcrumbs-integration-test.php, tests/integrations/front-end-integration-test.php
Import `use` statements MUST always be fully qualified. For that reason no leading backslash should be used.
> Note that for namespaced names (fully qualified namespace names containing namespace separator, such as Foo\Bar as opposed to global names that do not, such as FooBar), the leading backslash is unnecessary and **not recommended**, as import names must be fully qualified, and are not processed relative to the current namespace.
Ref: https://www.php.net/manual/en/language.namespaces.importing.php
* _N/A_
=> QA: fix import `use` statements

admin/class-yoast-input-validation.php, admin/class-yoast-notification-center.php, deprecated/frontend/schema/class-schema-howto.php, inc/sitemaps/class-author-sitemap-provider.php, src/builders/indexable-hierarchy-builder.php, src/commands/generate-indexables-command.php, src/generators/schema/faq.php, src/loggers/database-logger.php, src/presenters/breadcrumbs-presenter.php
* When a variable value has to be in/decremented by `1` in a stand-alone statement, the increment/decrement operators should be used.
* And when using increment/decrement operators, pre-in/decrement should be favoured over post-in/decrement.
Note: there is a difference in behaviour: the "pre" variant increments and returns, the "post" variant returns and increments after. This is a significant difference and the reason why "pre" should be favoured, though for stand-alone statement there is - in effect - no difference.
* Lastly, there should be no whitespace between the increment/decrement operator and the variable it applies to.
* …
=> CS: use (pre-)increment/decrement where appropriate

inc/class-wpseo-utils.php
=>  CS/QA: use `self` when referencing a (static) class member from within the same class

integration-tests/frontend/test-class-wpseo-image-utils.php, tests/presentations/indexable-date-archive-presentation/robots-test.php, tests/presentations/indexable-presentation/rel-next-test.php, tests/presentations/indexable-presentation/rel-prev-test.php
* Test coverage should be recorded for all tests
* QA: add missing test `@covers` tags
* Tests: fix incorrect `@covers` tags 
* _N/A_
=> QA: add missing test `@covers` tags + fix some incorrect ones

config/dependency-injection/custom-loader.php, src/repositories/indexable-repository.php, src/repositories/primary-term-repository.php, src/repositories/seo-meta-repository.php, tests/database/migration-status-test.php, tests/presentations/abstract_presentation_test.php, tests/presentations/indexable-post-type-presentation/robots-test.php
Chained method calls should be indented one tab in from the start of the chain, with each line being allowed one tab (more/less) difference, if so desired, with the minimum staying at one tab in from the start of the chain.
Precision alignment for the indentation is not allowed.
* _N/A_
=> CS: fix chained method call indentation

admin/class-yoast-form.php, admin/pages/tools.php, deprecated/admin/links/class-link-compatibility-notifier.php, deprecated/admin/onpage/class-onpage-option.php, deprecated/frontend/schema/class-schema-howto.php, deprecated/frontend/schema/class-schema-main-image.php, inc/class-wpseo-utils.php, integration-tests/test-class-wpseo-metabox.php, migrations/20171228151840_WpYoastIndexable.php, src/functions.php, src/helpers/post-helper.php, src/integrations/front-end/force-rewrite-title.php, src/presentations/indexable-post-type-presentation.php, src/presentations/indexable-presentation.php, src/presenters/open-graph/site-name-presenter.php, src/presenters/robots-presenter.php, src/surfaces/values/meta.php, src/values/images.php, tests/builders/indexable-hierarchy-builder-test.php, tests/database/migration-status-test.php
* No space between a unary +/- and the integer.
* No space between  case condition and the colon.
* No space before a comma and exactly one space (or a new line) after.
* For empty parentheses, there should be no space between them.
* One space between the last part of a class declaration and the open brace.
* Exactly one space between a keyword and whatever follows it.
* No superfluous whitespace at the end of lines.
* Use tab indentation, not space.
* Don't use precision alignment.
* _N/A_
=> CS: various whitespace fixes

admin/ryte/class-ryte.php, deprecated/frontend/class-opengraph.php, integration-tests/frontend/test-class-wpseo-image-utils.php, integration-tests/test-class-wpseo-utils.php, src/builders/indexable-social-image-trait.php, src/helpers/user-helper.php, src/integrations/front-end/comment-link-fixer.php, src/integrations/front-end/force-rewrite-title.php, tests/generators/breadcrumbs-generator-test.php, tests/generators/schema/article-test.php, tests/helpers/schema/image-helper-test.php
* Improve documentation
* Improve documentation
* Docs: fix tag order
* Docs: use short form types
`bool` instead of `boolean`, `int` instead of `integer`.
* Docs: docblock format fix
* Docs: add missing parameter tags
* Docs: minor tweaks
* Docs: fix tag alignment
* Docs: remove duplicate `@var` tag
* Docs: remove superfluous `@param` tags
These methods don't take parameters.
* _N/A_
=> Docs: various fixes

src/presenters/debug/marker-close-presenter.php, tests/presenters/debug/marker-close-presenter-test.php
* Remove the number of newlines after our meta block. There are already 2 `PHP_EOL`'s in `front-end-integration.php` after our presenters, we don't need any in the debug marker itself.
* None needed
Fixes #14716
=> Reduce the number of newlines below our debug marker

deprecated/frontend/schema/class-schema-article.php, deprecated/frontend/schema/class-schema-author.php, deprecated/frontend/schema/class-schema-breadcrumb.php, deprecated/frontend/schema/class-schema-faq.php, deprecated/frontend/schema/class-schema-howto.php, deprecated/frontend/schema/class-schema-main-image.php, deprecated/frontend/schema/class-schema-organization.php, deprecated/frontend/schema/class-schema-person.php, deprecated/frontend/schema/class-schema-webpage.php, deprecated/frontend/schema/class-schema-website.php, src/backwards-compatibility/breadcrumbs.php, src/backwards-compatibility/frontend.php, src/integrations/breadcrumbs-integration.php, src/integrations/front-end-integration.php, src/main.php, src/memoizers/meta-tags-context-memoizer.php, src/memoizers/presentation-memoizer.php, src/surfaces/meta-surface.php, src/surfaces/values/meta.php, tests/integrations/breadcrumbs-integration-test.php, tests/integrations/front-end-integration-test.php, tests/surfaces/meta-surface-test.php
:warning: **Once this PR is merged, everyone working with the codebase needs to do a `composer dump-autoload` to refresh their Composer autoload classmap!** :warning:
:question: Should this PR be backported to the `14.0` release ? /cc @IreneStr 
Both the classes in the `src/memoizers` folder used `Memoizer` in the namespace, instead of the expected `Memoizers` (note: plural).
Fixed now, including all uses of these.
Both the `Surfaces\Meta_Surface` class as well as the `Surfaces\Values\Meta` class, used the wrong namespace prefix.
Fixed now, including all uses of these.
* Check out this branch and run `composer dump-autoload`.
* Load pages using …
=> QA: fix namespaces (user facing)

tests/helpers/robots-helper-test.php
* Test what was intended to be tested.
* Improved tests
The array as previously defined, contained two entries with an empty string as key + value.
In effect, that meant that the array only contained one of those entries as the second empty key would overwrite the first.
Leaving the values empty, but passing keys will allow the test to actually test with two empty values in the array.
* _N/A_
This is a (test-)code-only change and should have no effect on the functionality. If the test still passes, we're good.
=> Tests: fix test data

inc/class-wpseo-utils.php, integration-tests/admin/import/test-class-import-settings.php
Nowdocs are to heredocs as double quoted strings are to single quoted strings.
In other words: the engine to find & interpolate variables won't kick in when a nowdoc is used, while it will for heredocs.
Nowdocs are available since PHP 5.3.
Ref: https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc
@IreneStr Nothing too exiting about this PR, but if I remember correctly, this is the first PR of this kind, so felt like something to leave for review.
* _N/A_
=> Modernize: use nowdoc instead of heredoc

src/generators/open-graph-image-generator.php, tests/generators/open-graph-image-generator-test.php
* We changed the type of the images container that we filter for opengraph images. This could cause type errors with integrators who typehint their filter callbacks. In order to prevent fatals from occurring, we ignore the filter if a filter like that breaks.
* Prevents integrations relying on the deprecated WPSEO_OpenGraph_Image class from creating Type Errors with the latest version of Yoast SEO.
* Follow the steps in the issue. See the fatal is solved.
Fixes #14689
=> Try catch opengraph image filters

.travis.yml
*
* Use WP 5.3 in the travis matrix because we no longer support 5.2
*
* See that the Travis build is run against WordPress 5.3 instead of 5.2
Fixes #
=> Use WP 5.3 in the travis matrix because we no longer support 5.2

src/context/meta-tags-context.php, src/generators/schema/webpage.php
* A search page should have WebPage schema output of the type `SearchResultsPage`.
* This is the fix for author archives and error pages https://github.com/Yoast/wordpress-seo/pull/14364
* Fixes a bug where the WebPage schema was not being output on a search page.
* 
* Navigate to a Search Page on your website.
* Check Schema for the Search Page.
* Ensure that `@type` is `SearchResultsPage` and the `@id` ends with `#webpage`. Like in the before screenshot of the issue.
* Go to an author archive page (e.g. http://basic.wordpress.test/author/admin/).
* Check the Schema that is output in the source code.
* It **should** contain a node with an `@type` property of `[ 'WebPage', …
=> Fix schema page type not being able to handle the system pages

src/presentations/indexable-term-archive-presentation.php, tests/presentations/indexable-term-archive-presentation/open-graph-type-test.php
* The OG:type for a term archive has to be `article`
* N/A - Fixes a 'bug' that the wrong OG:type is rendered.
*
* Visit a term archive and see in the source that the `og:type` is set to `article`. On the release branch it is `website`
Fixes #14774
=> Sets the type for term archives to article

admin/views/partial-notifications-errors.php
* Fix a typo
* N/A
* Removes a hyphen introduced in a typo in https://github.com/Yoast/wordpress-seo/commit/d4f539f34f40f282051a8807599d5755870de9f9
- go to the SEO Dashboard
- see there's a hyphen before the "Problems" heading (refer to the screenshot on the issue)
- see the hyphen is gone 
Fixes https://github.com/Yoast/wordpress-seo/issues/14776
=> Remove hyphen from the beginning of a PHP file.

src/initializers/database-setup.php
* Adds the `mysqli.default_socket` setting to the database config in order to support database that make connection using defaults rather than explicit config.
* @Djennez can test this.
Fixes #14791
=> Add MySQLi default socket to config

deprecated/frontend/schema/class-schema-author.php, src/generators/schema/author.php, src/generators/schema/person.php, tests/generators/schema/author-test.php, tests/generators/schema/person-test.php
We output a `person` piece because the site represents a `person`.
* This has the extra type `Organization`.
* This has the `logo` property, which can be changed on the site.
* This has the social profiles `sameAs`.
We output another `person` piece (through Author) because the author archive is from that `person`.
* This is the holder of the `mainEntitiyOfPage` pointing to the `WebPage`.
* This is a WP user and can only have Gravatar logo, which is why the images are different in this issue.
We output a `person` piece because the site represents a `person`.
* This has the extra type `Organization`.
* This has the `logo` property, which can be changed on the site.
* This has the social profiles `sameAs`.
* This is the holder of the `mainEntitiyOfPage` pointing to the `WebPage`.
* This has …
=> Move and adapt the site represents current author to person from author

inc/class-wpseo-replace-vars.php
* Add term meta support to variables
WordPress supports term meta for a long time now, so this PR adds support for term meta with the same %%cf_<custom-field-name>%% syntax used for posts.
* Add term meta to a taxonomy, with ACF or any other plugin
* Add a snippet variable to the taxonomy SEO Title or Meta Description in the %%cf_<custom-field-name>%% format
=> Support %%cf_<custom-field-name>%% for taxonomy terms

inc/class-wpseo-replace-vars.php
* Technical debt PR.
* Cleans-up code for non-static replacement variables.
* See rationale on the issue: https://github.com/Yoast/wordpress-seo/issues/14588#issuecomment-610872050
- install and activate Classic Editor because it seems some replacement variables don't work in Gutenberg e.g. "Category", see https://github.com/Yoast/bugreports/issues/952
- edit a post
- add the `Category` replacement variable to both the post title and description
- check it works as expected
- edit a Page that is a sub-page of another page
- add the `Parent title` replacement variable to both the post title and description
- check it works as expected
- edit a Category that is a sub-category of …
=> Remove redundant isset checks for non-static replacement variables.

src/presenters/googlebot-presenter.php, tests/presenters/googlebot-presenter-test.php
* When robots no index is true we should hide the google bot tag.
* Hides the Google bot metatag when the current page is set to robots `noindex`.
* Restructured the unit tests a little bit:
* Flipped the `actual` and `$expected`, this are given in the wrong sequence.
* Removed an assignment in an assigment (`$variable = $variable2 = 123`)
* Set the instances to use for testing in the `setUp` method
* On release branch: Set a post to robots no index
* The googlebot meta tag is rendered
* The metatag is gone!
Fixes #14804
=> Hide googlebot when robots noindex

src/presentations/indexable-search-result-page-presentation.php, tests/presentations/indexable-search-result-page-presentation/open-graph-type-test.php
* The OG type was wrong and should have the value article
* Fixes the `og:type` for a search result page
*
* Checkout the release branch
* Search on the frontend and view the source of the results page
* See that the og:type is website
* The type is `article` now
Fixes #14819
=> Sets article as og:type for the searchpage

package.json, yarn.lock
* The version bump of `@yoast/grunt-plugin-tasks` improves the compatibility of our plugin with node `v12.16.2` (the current LTS release).
When running `yarn install` locally, there is still an error about the `fsevents` package. This package is optional and the `install` will succeed without it.
On non-MacOS systems (i.e. Travis) this error will not be present since `fsevents` is only installed on `MacOS`.
* Bump the version of `@yoast/grunt-plugin-tasks` to improve compatibility with node `v12.16.2`.
* `fsevents` still errors. I will try to fix this tomorrow.
* Nothing should change in the build process. Everything should work as expected.
Fixes N/A
=> Bump version of @yoast/grunt-plugin-tasks

migrations/20200408101900_AddCollationToTables.php
* Fixes warnings when running migrations about `wpdb->prepare` not having any replacements.
*
* Remove your indexables tables.
* Run the migrations.
* You shouldn't have any warnings in your logs.
Fixes #14830
=> Fix the collation migration generating warnings

src/context/meta-tags-context.php, tests/context/meta-tags-context-test.php
* The page that is set to `page_for_posts` should have the `CollectionPage` as schema page type.
* Fixes a bug where the Schema page type was wrong for the page that has been set as posts page.
* I also added test in an attempt to have the complete method covered
* Set a page as posts for page, view the source and verify that the schema output contains `@type: CollectionPage` data.
Fixes #14827
=> Use CollectionPage when page_for_posts is the current indexable

src/actions/indexation/indexable-term-indexation-action.php, src/helpers/taxonomy-helper.php, src/integrations/admin/indexation-integration.php, src/routes/indexable-indexation-route.php, tests/actions/indexation/indexable-post-indexation-action-test.php, tests/actions/indexation/indexable-term-indexation-action-test.php, tests/helpers/taxonomy-helper-test.php
* See https://github.com/Yoast/wordpress-seo/pull/14797
* Adds term indexation to the indexation framework.
* Queried the term_taxonomy table because the term id and taxonomy names are there.
* Also added some coverage tests for the post.
* Run `TRUNCATE TABLE wp_yoast_indexable` to delete all your indexables.
* Go to SEO -> Tools and click on the button to index your content.
* You should have indexables again for every public term.
Partially Fixes #14824
=> Add indexation for terms

migrations/20171228151840_WpYoastIndexable.php, migrations/20171228151841_WpYoastPrimaryTerm.php
* Adjusts the max column lengths in the migrations so they do not fail on our Windows testing setup and better match the values used in WordPress.
* Has already been tested by @sannevndrmeulen and me.
* For future testers:
- Use the yoast test helper to reset the indexable tables.
- Visit a post on the front-end.
- It shouldn't crash.
- Note, that it only used to crash if your MySQL server was configured with a limit on composite indexes of 1000.
Fixes #14846
=> Adjust migrations to have max column lengths matching WordPress

.gitignore, src/actions/indexables/indexable-head-action.php, src/routes/indexables-head-route.php, src/surfaces/meta-surface.php, src/surfaces/values/meta.php, tests/bootstrap.php, tests/surfaces/meta-surface-test.php
* [Developer only feature] Adds the `/wp-json/yoast/v1/get_head` endpoint to get the our head for an url. This endpoint takes a single paramter, `url` which should be the absolute url of the page to get the head for.
* Date archives have their rel-next and rel-prev stripped as it's complicated to retrieve these when not in the full WordPress request and they add little value.
* Visit `/wp-json/yoast/v1/get_head?url=${some_url}` with a variety of URLs.
* You should always get an object that has a `head` and a `status` property.
* If you call it with a URL that has an indexable then the `head` should match what's seen in the head of that page ( excluding the exception described above …
=> Add new endpoint for getting the head by URL

js/src/wp-seo-indexation.js, src/presenters/admin/indexation-modal-presenter.php
* Makes sure indexation actually stops when someone stops indexation.
* Open your requests tab in your browser inspector.
* Start the indexation ( reset your indexable tables if they're already filled ).
* Click stop indexation.
* There should be no more requests being made to the indexation endpoint ( note: the page does refresh immediately after so there will be requests, just none should match `/wp-json/yoast/v1/indexation/*` ).
=> Make sure indexation actually stops if someone clicks stop indexation

admin/class-admin-init.php, inc/class-upgrade.php
* Remove unused code.
* Removes the code related to the "Recalculate the SEO scores" notification.
- removes the notification code, see `WPSEO_Admin_Init->recalculate_notice()`
- note: this was "temporarily" disabled more than 4 years ago in https://github.com/Yoast/wordpress-seo/pull/4001/files#diff-107adb4228cae05d2fd2293a098f17d4R204
- it's a public method and I'm removing it entirely because it doesn't do anything since 4 years
- if a deprecation is preferred, please do let me know
- removes private method `is_site_notice_dismissed()` that was only used here
- adds an upgrade routine to remove the notification from the notification center in the remote chance it's still there after 4 years for some users
This PR can be tested …
=> Remove unused code for the recalculate SEO scores notification.

src/builders/indexable-hierarchy-builder.php, tests/builders/indexable-hierarchy-builder-test.php
* Fixes a crash in the indexation when indexing a post with a post_parent that does not exist.
* In the database set that post's `post_parent` field to an ID that does not exist.
* Delete all indexables.
* Run the indexation, it should complete without issue.
=> Do not build post hierarchy for post parents that do not exist

src/presenters/admin/indexation-warning-presenter.php, tests/presenters/admin/indexation-warning-presenter-test.php
* We want to have full test coverage 💪 
* Adds unit tests for the indexation warning presenter.
* I also changed the way we build the warning
* I've change the presenter a little bit. Trigger the warning (it is shown on the admin pages) by removing all indexables. 
* If the test passed, just merge it.
=> Indexation notification presenter test

migrations/20200420073606_AddColumnsToIndexables.php, src/builders/indexable-author-builder.php, src/builders/indexable-date-archive-builder.php, src/builders/indexable-home-page-builder.php, src/builders/indexable-post-builder.php, src/builders/indexable-post-type-archive-builder.php, src/builders/indexable-system-page-builder.php, src/builders/indexable-term-builder.php, src/builders/primary-term-builder.php, src/models/indexable-hierarchy.php, src/models/indexable.php, src/models/primary-term.php, src/repositories/indexable-hierarchy-repository.php, tests/builders/indexable-author-builder-test.php, tests/builders/indexable-date-archive-builder-test.php, tests/builders/indexable-home-page-builder-test.php, tests/builders/indexable-post-builder-test.php, tests/builders/indexable-post-type-archive-builder-test.php, tests/builders/indexable-system-page-builder-test.php, tests/builders/indexable-term-builder-test.php, tests/builders/primary-term-builder-test.php, tests/mocks/primary-term.php, tests/repositories/indexable-hierarchy-repository-test.php
* The `blog_id` is to start keeping track of which blog the "indexable" row belongs too. While seemingly pointless now, this might become handy in a future where we only have 1 indexable table.
* Adding 4 more fields to the Indexable table, also to prepare for future things.
* Adds `blog_id` field to the Indexable, Indexable Hierarchy and Primary Term tables.
* Adds `language`, `region`, `schema_page_type` and `schema_article_type` fields to the Indexable table.
* `blog_id` has the same type and length as `wp_blogs`'s `blog_id`.
* `language` and `region` have a length of 32 to not be so large we can not use them in a merged index later. But should still be large enough to hold the largest values. Larger than the suggestion on …
=> Add indexable columns

js/src/containers/Facebook.js, js/src/containers/Twitter.js, js/src/redux/selectors/social.js
* All context and test instructions are in https://github.com/Yoast/wordpress-seo-premium/pull/2744
* [non-user-facing] Add siteUrl selector and let Facebook and Twitter containers use the selector to connect the props.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2734
=> Add siteUrl selector and connect containers

src/config/migration-status.php, src/initializers/migration-runner.php, src/orm/yoast-orm-wrapper.php, tests/database/migration-runner-test.php, tests/database/migration-status-test.php
* Reruns query if they failed after running migrations again. This is mostly relevant in multisite contexts where blog switches happen frequently.
* Get a multisite up and running.
* Delete all indexable tables in all sites ( don't use the reset feature in the test helper as that will recreate them ). Plus the migrations table. And then empty the `yoast_migrations_free` field in `wp_options`.
* Write a function that switches to another site, does a query on the indexables and then switches back.
* Call this function making sure the site you're switching to doesn't have any migrations.
=> Run migrations when a query throws an exception

js/src/wp-seo-indexation.js, src/integrations/admin/indexation-integration.php, src/presenters/admin/indexation-list-item-presenter.php, src/presenters/admin/indexation-warning-presenter.php, tests/integrations/admin/indexation-integration-test.php, tests/presenters/admin/indexation-warning-presenter-test.php
*
* Returns the indexation button back to the tools page, even if you have dismissed the warning.
*
* Remove all your indexables.
* Dismiss the warning.
* Go to the SEO -> tools page.
* You should still be able to index your content.
Fixes #
=> Return the indexation button to the tools page

src/integrations/front-end/rss-footer-embed.php, tests/integrations/front-end/rss-footer-embed-test.php
* `nofollow_rss_links` was renamed to `wpseo_nofollow_rss_links`, but the old one was not deprecated. This could lead to problems for integrators.
* Undoes the rename of a filter from `nofollow_rss_links` to `wpseo_nofollow_rss_links`.
* For now, we chose for the easiest option. Later, all unprefixed filters will be deprecated and renamed (in a separate CS-project).
*
Fixes #
=> Undo rename of nofollow_rss_links filter

js/src/components/AdvancedSettings.js
* Trunk production build is failing: 
<details>
<summary>Click to see error</summary>
```
ERROR in ./js/src/components/AdvancedSettings.js
Module not found: Error: Can't resolve '@yoast/components/src/inputs/TextInput' in '/home/travis/build/Yoast/wordpress-seo/js/src/components'
@ ./js/src/components/AdvancedSettings.js 21:17-66
@ ./js/src/components/Metabox.js
@ ./js/src/containers/Metabox.js
@ ./js/src/components/MetaboxPortal.js
@ ./js/src/edit.js
@ ./js/src/wp-seo-post-scraper.js
ERROR in ./js/src/components/AdvancedSettings.js
Module not found: Error: Can't resolve '@yoast/components/src/radiobutton/RadioButtonGroup' in '/home/travis/build/Yoast/wordpress-seo/js/src/components'
@ ./js/src/components/AdvancedSettings.js 17:24-85
@ ./js/src/components/Metabox.js
@ …
```
=> Import from @yoast/components root

admin/class-admin-init.php, readme.txt
*
* Deprecates the wp_seo_get_bc_ancestors filter. Developers should use the wpseo_breadcrumb_links filter instead to add and/or replace breadcrumbs.
* Add a filter to the wp_seo_get_bc_ancestors filter in, for example, your theme's functions.php:
```php
add_filter( 'wp_seo_get_bc_ancestors', function ( $post_ids ) {
return $post_ids;
} );
```
* Visit the admin.
* You should get a deprecation warning ( provided you're showing warnings ).
Fixes #14894
=> Add wp_seo_get_bc_ancestors to the list of deprecated filters

src/surfaces/meta-surface.php, tests/surfaces/meta-surface-test.php
* Ensures the new `get_head` endpoint works as expected on sites with a path in their site name.
* Note: this has already been tested on staging.
* Have a site with a path in the `site_url` ( for example: `https://developer.yoast.com/blog/` ).
* Visit the get_head route with a valid url you just visited ( this ensures the indexable exists )
* It should have a `status` of 200.
=> Fix rest endpoint for sites with a path in their site_url

inc/class-wpseo-admin-bar-menu.php, src/initializers/migration-runner.php, src/integrations/admin/indexation-integration.php, src/integrations/admin/migration-error-integration.php, src/presenters/admin/migration-error-presenter.php, tests/integrations/admin/indexation-integration-test.php, tests/integrations/admin/migration-error-integration-test.php, tests/integrations/watchers/indexable-post-meta-watcher-test.php, tests/presenters/admin/indexation-warning-presenter-test.php, tests/presenters/admin/migration-error-presenter-test.php
* Adds a notification to the admin in case migrations fail for whatever reason.
* Add the following to the `up` method of any migration: `throw new \Exception( 'Migration failed!' );`
* Reset your tables in the yoast test helper plugin.
* You should see a notification in the admin that migrations have failed.
=> Add migration failed notification

src/presentations/indexable-presentation.php
* We've decided to no longer remove the default robots meta values, to be more explicit. 
* We no longer remove the default robots meta values, to be more explicit. 
* On the homepage we should show `index, follow` in the robots tags.
Fixes #
=> robots no longer remove default

inc/class-wpseo-utils.php
* Make the Advanced settings working on non taxonomy pages.
* Fixes a bug where loading the metabox on a post would give a warning.
* Conditionally get the taxonomy object instead of always.
* Disable the query monitor
* Checkout `trunk`
* See the warning that appears when you load the post edit page
* See that the warning is gone when you reload the page
Fixes https://yoast.slack.com/archives/C5SUKMF2T/p1587714695319700
=> Conditionally get the taxonomy object

src/backwards-compatibility/breadcrumbs.php
*
* Fixes a fatal related to rendering breadcrumbs in the admin.
* Render the breadcrumbs using `WPSEO_Breadcrumbs::breadcrumb` while in the admin.
* For example by adding a `var_dump( yoast_breadcrumb( '<p id="breadcrumbs">','</p>' ) )` to an integration you know will be run in the admin.
* It should give valid HTML and not cause any fatals.
Fixes https://wordpress.org/support/topic/after-update-yoast-14-e_error-breadcrumbs-php-line-107/
=> Remove front end conditional from breadcrumbs

src/builders/indexable-hierarchy-builder.php
* Fixes the order of the breadcrumbs when more than 3 nested taxonomies are used.
* Create a grandparent category
* Create a parent category whose parent is the grandparent
* Create a child category whose parent is the parent.
* Create a post with the child category.
* Enable breadcrumbs.
* The breadcrumbs for the post should be in the correct order.
=> Fix the order of hierarchical taxonomies when more than 3 are present

migrations/20200428123747_BreadcrumbTitleAndHierarchyReset.php
* [non-user-facing] Removes all indexable hierarchy entries to account for https://github.com/Yoast/wordpress-seo/pull/14942
* Fixes a fatal error when breadcrumb titles were too long.
* Delete the `yoast_migrations_free` option or change the plugin version to 14.0.1.
* Load any page.
* Your indexable hierarchy table should be ( almost ) empty, it may contain entries for the current page.
* The breadcrumb title should be of type text in the indexable table.
Fixes #
=> Breadcrumb title and indexable hierarchy reset migration

js/src/wp-seo-indexation.js, src/presenters/admin/indexation-modal-presenter.php, src/presenters/admin/indexation-warning-presenter.php, tests/integrations/admin/indexation-integration-test.php, tests/presenters/admin/indexation-modal-presenter-test.php, tests/presenters/admin/indexation-warning-presenter-test.php
* Modals should have a title.
* Fixes a bug where no title was shown on the modal that you see when you click to speed up your site.
* I set the `data-title` attribute, so that `$( this ).data( "title" )` will no longer be `undefined`.
* Use the Yoast Test Helper to `Reset Indexables tables & migrations`.
* On the admin dashboard, click on the button that says `Click here to speed up your site now`.
* See that the title is `Yoast indexation status`.
Fixes https://github.com/Yoast/bugreports/issues/983
=> Fix missing modal title in 14.0 indexing window

src/initializers/migration-runner.php, tests/database/migration-runner-test.php
* Fixes a fatal error related to the Yoast migrations table not having a primary key.
* Adds the primary key.
* For anyone where the migrations have already been done it won't matter that their table doesn't have a primary key.
* Reset your indexable migrations.
* Your migrations table should have a primary key.
Fixes https://wordpress.org/support/topic/unable-to-create-database-tables-after-update-to-v14/page/2/#post-12743891
=> Add primary key to migrations table

src/presentations/indexable-author-archive-presentation.php, src/presentations/indexable-date-archive-presentation.php, src/presentations/indexable-error-page-presentation.php, src/presentations/indexable-post-type-archive-presentation.php, src/presentations/indexable-post-type-presentation.php, src/presentations/indexable-presentation.php, src/presentations/indexable-search-result-page-presentation.php, src/presentations/indexable-term-archive-presentation.php, src/presenters/robots-presenter.php, tests/presentations/indexable-post-type-presentation/robots-test.php, tests/presenters/robots-presenter-test.php
* Because the `wpseo_robots` filter runs on the presenter, the `googlebot` and `bingbot` presenter don't get the filtered value. This patch fixes that + the fact that REST API output would differ from frontend.
* Made sure changes through the `wpseo_robots` filter are shown in the `googlebot` and `bingbot` meta tag output too.
=> Move the robots filter to the generator

src/generators/schema/breadcrumb.php, src/presenters/breadcrumbs-presenter.php
* Allows HTML in Breadcrumbs settings.
* Stripped the tags in Schema output. Note that this _can_ cause the schema output to be empty.
* Set `<i class=”fa fa-home”></i>` as your "Anchor text for the homepage" in the breadcrumbs settings.
* See that it renders on the frontend.
Fixes #14940
=> Allow HTML in breadcrumbs settings

js/src/containers/SnippetEditor.js, js/src/helpers/replacementVariableHelpers.js
* We want to make the replacement variables work in the Social Previews.
* Move applyReplaceUsingPlugin to the replacementVariableHelpers file.
https://github.com/Yoast/wordpress-seo/pull/14930
https://github.com/Yoast/wordpress-seo-premium/pull/2753
https://github.com/Yoast/javascript/pull/648
* Checkout `14592-make-replacevars-work` on the monorepo and Premium.
* Merge `free/14592-make-replacevars-work` into premium using `git merge free/14592-make-replacevars-work --no-commit`
* Link the monorepo in the root and premium folder of wordpress-seo-premium.
* Build everything 👷 
* Checkout the Social Previews
* Enter a replacement variable in the input field
* Check that it is nicely …
=> Move applyReplaceUsingPlugin to the replacementVariableHelpers

tests/generators/schema/breadcrumb-test.php
* We want the unit tests to pass.
* Adds expectations for `smart_strip_tags`, on the `html_helper`, in the breadcrumbs schema unit tests.
* N/A
* Run `composer test`.
* Check that all the tests pass.
Fixes #
=> Adds expectations for smart_strip_tags in the breadcrumbs schema test.

src/backwards-compatibility/frontend.php
* Fixes a fatal error when using the WPSEO_Frontend class to get the meta description.
* Call `WPSEO_Frontend::get_instance()->metadesc()` in your `functions.php` file.
* It should not cause a fatal error.
* It should echo the meta description of the current page.
Fixes https://wordpress.org/support/topic/14-0-1-fatal-error/
=> Set all variables in wpseo_frontend for the presenters

tests/presentations/indexable-presentation/robots-test.php, tests/presentations/indexable-term-archive-presentation/robots-test.php, tests/presenters/robots-presenter-test.php
* The two arguments had the wrong sequence. We have to pass the expected value first and than the actual value.
* N/A - Flipped the two arguments
*
* No functional change.
Fixes #
=> Flipped the actual and expected values

src/integrations/third-party/woocommerce.php, tests/integrations/third-party/woocommerce-test.php
* Fixes a fatal error that could occur on WooCommerce installation when the `wpseo_metadesc` fitler was called with only 1 argument.
* Install WooCommerce.
* Add a call of `echo apply_filters( 'wpseo_metadesc', 'test' );` to your `functions.php`.
* While on the shop page that should output the meta description of your shop page.
Fixes https://wordpress.org/support/topic/fatal-errors-issue-2/
=> Fix fatal for the woocommerce integration when called using old filters

migrations/20200428194858_ExpandIndexableColumnLengths.php
*
* Fixes a bug where an import of the Modal was pointing to the moved one.
*
* Reset the indexables & migrations.
* No error should occur.
Fixes #14969
=> Fix forgotten move from Yoast_Model to Lib Model

src/generators/breadcrumbs-generator.php, tests/generators/breadcrumbs-generator-test.php, tests/repositories/indexable-hierarchy-repository-test.php, tests/repositories/indexable-repository-test.php
* Fixes the double breadcrumb on home pages.
* Simple fix, check against page type, don't output on home page.
* Create a basic site, add the breadcrumbs, go to the home page, see double breadcrumbs.
* Check out this pull, see the double breadcrumb is gone.
Fixes #14961
=> Fix double breadcrumb

src/models/indexable.php
* Fixes a bug where a fatal error would be thrown when a primary focus keyword is chosen that is more than 191 characters long.
* Thus far I can't reproduce it. It's something to do with MySQL settings but I can't find the correct combination.
Fixes https://wordpress.org/support/topic/fatal-error-14-0-1-2/
Fixes #14986
=> Truncate primary focus keyword on save

migrations/20200429105310_TruncateIndexableTables.php, src/initializers/migration-runner.php, src/presenters/admin/indexation-warning-presenter.php, tests/integrations/admin/indexation-integration-test.php, tests/presenters/admin/indexation-warning-presenter-test.php
* Truncate all indexable tables on upgrade.
* The option wasn't removed as the version number will change when this is released which automatically invalidates the option.
* Delete the `yoast_migrations_free` option ( only required if you've run 14.0.2 ) before.
* Your indexable tables should be reset ( both indexable and indexable_hierarchy ).
* [1] I have tested this code to the best of my abilities
=> Truncate tables on upgrade

deprecated/frontend/breadcrumbs.php, deprecated/frontend/frontend.php
* Fixes fatals when calling `WPSEO_Frontend` or `WPSEO_Breadcrumbs` before the `init` action.
* Add the following code where it gets loaded before `init`.
```
add_action( 'init', 'bananarama' );
function bananarama() {
WPSEO_Frontend::get_instance()->metadesc();
}
```
Fixes #
=> Fix the breadcrumbs and frontend classes fatalling if called before init

src/presenters/title-presenter.php, tests/presenters/title-presenter-test.php
* Fixes a bug where the `pre_get_document_title` filter could be skipped when other plugins were using this filter as well.
* Add the following to your functions.php:
```
add_filter( 'pre_get_document_title', 'my_custom_title', 40 );
function my_custom_title( $title ) {
return "THIS IS NOW THE TITLE ALWAYS!";
}
```
* Your title should change to the above.
* Change the priority from 40 to 10.
* Your title should revert to what it was.
Fixes #14997
=> Make sure the wp_get_document_title function still gets called for BC

deprecated/frontend/breadcrumbs.php, deprecated/frontend/frontend.php, src/integrations/breadcrumbs-integration.php, src/integrations/front-end-integration.php, src/surfaces/values/meta.php
* Adds the `wpseo_frontend_presentation` filter that can be used by third-party plugins to easily alter all our meta output with 1 single filter.
* Add a filter to `wpseo_frontend_presentation`.
* Set some properties on the presentation.
* They should be reflected in the meta tags output.
Fixes #14994
=> Adds the wpseo_frontend_presentation filter

admin/class-product-upsell-notice.php
* PHPCS warned that we should use `wp_safe_redirect`.
* Calls `wp_safe_redirect` instead of `wp_redirect` in `admin/class-product-upsell-notice.php`
* N/A
* 
Fixes #
=> PHPCS wp_redirect to wp_safe_redirect

src/models/indexable.php, tests/doubles/models/indexable-double.php, tests/models/indexable-test.php
* Write unit tests for https://github.com/Yoast/wordpress-seo/issues/14982
* Adds tests for models/indexable.
* Added missing `\` in models/indexable itself.
* Tricky to test due to the ORM layer and magic getter/setter.
* Tests the values by the get/set expectations in the ORM mock.
* Using a double to skip the timestamps since they would be prone to error. Could not be done via mocking due to the magic getter going to the ORM layer.
* Also using the double to mock `has_one`.
* Tests should look good, pass and cover 100%.
Fixes #
=> Add tests for models/indexable

inc/class-upgrade.php, inc/options/class-wpseo-option-wpseo.php, integration-tests/doubles/class-upgrade-double.php, src/config/migrations/20200430150130_ClearIndexableTables.php
* Due to tags being set to be indexed even if the settings were set to not show tags in search results the indexation will have to be run again. We apologize for this.
* Change the `WPSEO_VERSION`.
* You should have access to a `previous_version` from our options that shows the previous version the plugin was.
* Your indexable table should also be cleared.
Fixes #
=> Add previous version to options and clear indexable tables

tests/TestCase.php
* Ignores a CS rule applied within a stub. The suggested method was the method being stubbed.
* N/A - It excludes a specific CS rule.
*
* It just a comment, if travis is happy, we are happy.
Fixes #
=> Exclude line from phpcs because we are stubbing the suggested method

src/helpers/robots-helper.php, src/integrations/front-end/comment-link-fixer.php, src/integrations/front-end/indexing-controls.php, src/presentations/indexable-presentation.php, tests/helpers/robots-helper-test.php, tests/integrations/front-end/comment-link-fixer-test.php, tests/presentations/indexable-presentation/robots-test.php
* We already have a filter for filtering the robots string. But we also wanted one for filtering the robots array.
* Introduces a new filter for altering the robots array used for the robots meta tag.
*
For each step below you need a page that has set robots to index. 
* You have to add the following piece of code to a file on your site (e.g. `functions.php` in your theme, `wp-seo.php`)
```php
add_filter( 'wpseo_robots_array', function( $robots ) {
$robots['index'] = 'noindex';
return $robots;
} );
```
* Visit the page and make sure robots has `noindex` in its value.  
* Remove the added code.
* Make your blog private under Settings -> Reading and then check `Search Engine …
=> Adds the wpseo_robots_array filter

src/generators/breadcrumbs-generator.php, tests/generators/breadcrumbs-generator-test.php
* Fixes empty breadcrumbs when taxonomies where set to have a post type archive in their breadcrumb when that post type didn't have an archive.
* Get a custom post type that has an archive and a taxonomy.
* Set that post type to be the parent of the taxonomy in your breadcrumbs settings.
* Set that post type to no longer have an archive.
* Clear all your indexables and indexable hierarchies.
* Visit a term of that taxonomy.
* There should not be an empty breadcrumb in the schema.
Fixes #15005
=> Fix having breadcrumbs of post types without an archive

js/src/components/AdvancedSettings.js
* Fix #15029 
* Missing space in alert message.
* Wrong id for selecting canonical hidden field and bread crumbs on taxonomies.
* Fixes a bug where data entered into the breadcrumbs title and canonical url fields (advanced settings) in the taxonomy metabox was not saved and loaded.
* I could've either changed the queryselector id (the id "search value") or the id of the hidden field. As I was unsure, and everything was working when changing the queryselector id, I went with the former option.
* Changed the `isPost` from function to const, based on [this comment](https://github.com/Yoast/wordpress-seo/pull/14910#discussion_r417283522) on a PR in our feature branch. Basically, we can just check for presence of …
=> Save inputs advanced tab

src/integrations/watchers/indexable-term-watcher.php, tests/integrations/watchers/indexable-term-watcher-test.php
* No longer builds indexables for terms of taxonomies that aren't public.
* Register a non-public taxonomy ( note as we're not giving it labels it will be called `tags`, it's the bottom one. Check your url to be sure, it will mention `private_taxonomy` in there ):
```
register_taxonomy( 'private_taxonomy', array( 'post' ), array(
'public'   => false,
'show_ui' => true,
) );
```
* Create a term of this taxnomy.
* Check your indexables table, there should be no matching record in there.
=> Do not build private taxonomies

src/actions/indexation/indexable-general-indexation-action.php, src/actions/indexation/indexable-post-indexation-action.php, src/actions/indexation/indexable-term-indexation-action.php, tests/actions/indexation/indexable-general-indexation-action-test.php, tests/actions/indexation/indexable-post-indexation-action-test.php, tests/actions/indexation/indexable-term-indexation-action-test.php
* Fixes a bug where double indexable entries could be build on indexation.
* If an indexable was build during creating the hierarchy of another indexable it would be build again during it's own indexation pass. This would only happen if both were to be build in the same REST request. 
* Run the indexation so everything is indexed.
* Have a post be the parent of another post with a lower ID.
* Delete the indexables from both posts.
* Run the indexation again.
* There should be no duplicate indexables.
Fixes #15060
=> Indexation actions also check indexable existance before building

admin/class-yoast-columns.php
* We don't show the help tab anymore based on whether our metabox is present (and post type is accessible ).
* #14118  introduced changes in this regard, but goes a bit too far in removing the help tab.
* Fixes a bug where we didn't show a help tab about our internal linking columns, despite pointing to a help tab entry.
* The presence of linking tabs and meta tabs seems independent of eachother.
* Follow the test instructions here, **with the exception that the help tab *should* be visible if the metabox is disabled but posts are accessible:** #14118 
Fixes #
=> Adapt text in help tab on (custom)post overview according to which columns are shown

src/loader.php, tests/loader-test.php
* Third parties may hook into our code base, but this might not work in some case because we executed too early.
* Fixes a bug where the replytocom replacement can't be disabled by using the filter.
* Decided (after discussing with @herregroen) to load the integrations on `init`. This was the hook we loaded at before. We hook the `src` codebase on `plugins_loaded`. By hooking the integrations into init we give themes the chance to hook into our codebase, because themes are load between `plugins_loaded` and `init`/ 
1. Go to a post on the front end and add a comment.
2. Add a nested comment to your previous comment
3. Look the nested comment up in the source code and see that there …
=> Load integrations on init hook

src/generators/breadcrumbs-generator.php
* Fixes the URL in the schema breadcrumb of search pages, this was previously missing.
* Go to a search page.
* Find the breadcrumb in the schema.
* The last crumb should have a URL and name matching the current page and what's shown normally in the breadcrumb.
Fixes #14867
=> Set correct url in search breadcrumb

src/integrations/admin/migration-error-integration.php, src/presenters/admin/migration-error-presenter.php, tests/integrations/admin/migration-error-integration-test.php, tests/presenters/admin/migration-error-presenter-test.php
*
* Adds debug information to the migration error.
*
* Install the composer packages, prefix dependencies as normal: `composer install`.
* You can not be in development mode or it will throw an exception. Switch to production: `composer install --no-dev --no-scripts`. The no scripts is to prevent building the prefix dependencies, which is why the step before was there.
* To have a migration go wrong you can:
* Empty the `yoast_migrations_free` value in the `wp_options` table.
* Truncate the `wp_yoast_migrations` table.
* This will try to create the indexable table again, but it already exists.
* Visit any admin page, it should display the migration error. Now with a `Show debug …
=> Add debug info details to the migration error

src/builders/primary-term-builder.php, tests/builders/primary-term-builder-test.php
* Fixes a bug where primary terms of a custom taxonomy where not being reflected in the breadcrumb.
* For a custom taxonomy create multiple terms.
* Set the alphabetically last as the primary term.
* It should show up in the breadcrumb.
* Change the primary term.
* The breadcrumb should also change.
* Ideally also test with WooCommerce and a custom taxonomy from there.
Fixes #15071
Fixes https://github.com/Yoast/bugreports/issues/1005
=> Fix primary custom taxonomies

inc/class-wpseo-meta.php
* Optimizes the query used to check if a focus keyphrase has been previously used, by running it against our indexable table.
* I chose not to add a new index on the `primary_focus_keyword` as this is the only query using it and the query should already be significantly faster not having to query all postmeta. Adding indexes also has a cost on database size so given our varied userbase I felt it best to not prematurely optimize.
* The query for premium related keyphrases is not optimized as these aren't yet stored in our indexables table.
1. Merge this branch into premium to test it there as it interacts with the premium multiple focus keyphrases.
1. Have a set of 6 posts ready.
1. …
=> Check previously used keywords against our indexable table

src/builders/indexable-term-builder.php
* Fixes a bug where term indexation would keep going on forever due to plugin conflicts.
* Create 30 different terms.
* Delete all your indexables.
* Add a filter to `get_tag` to return a different tag:
```
add_filter( 'get_post_tag', function () {
return WP_Term::get_instance( 1 );
} );
```
* Run the indexation.
* It should not keep going on forever.
Fixes https://github.com/Yoast/wordpress-seo/issues/15050
=> Fix infinite indexation with wpml

js/src/wp-seo-indexation.js, src/integrations/admin/indexation-integration.php
* Prevents the indexation from going continuing even though it has already indexed all objects.
* If a very small amount of objects remain unindexed these will automatically be indexed without needing any user interaction. The default amount is a maximum of 25. This amount can be adjusted using the `wpseo_shutdown_indexation_limit` filter. Indexation happens as a shutdown function.
* In the `Indexation_Integration::get_total_unindexed` reduce the number by 100 before returning it.
* Clear all your indexables
* Make sure you have more than 100 objects to be indexed.
* Visit the dashboard, you should see the notification to index. This should not go over the limit by more than 25 even …
=> Make indexation more robust

js/src/components/contentAnalysis/KeywordInput.js
* Since #14989, we truncate the focus keyphrase that is saved to the indexable to 191 characters. This means only the first 191 characters are saved in the indexables table. We should show a warning in the UI to warn users if they enter a too long keyphrase.
* Adds a warning to the metabox when a user enters a focus keyphrase that contains more than 191 characters.
* It seems there are no tests yet (at all) for `KeywordInput.js`, so I didn't add any.
* With regard to the encoding of non-Latin languages (see #14998), I added a Hebrew focus keyphrase and saw in the indexables table that it showed in Hebrew. I also logged `this.props.keyword.length` to the browser and saw that it matched the number of Hebrew charachters that I had …
=> Show warning when focus keyphrase is too long

src/conditionals/yoast-admin-and-dashboard-conditional.php, tests/conditionals/yoast-admin-and-dashboard-conditional-test.php
* 
* The indexation notification is not shown anymore when updating themes or plugins via the WordPress updates page.
*
* Upload an outdated plugin.
* For example an outdated version of Akismet (https://downloads.wordpress.org/plugin/akismet.4.1.4.zip)
* Reset your indexables database tables using the Yoast Test Helper plugin.
* Go to the WordPress updates page ( _Dashboard_ > _Updates_ in the admin sidebar menu).
* You **should** see the indexation notification at the top of your screen.
* Select the outdated plugin in the list and click the 'Update Plugins' button.
* The plugin should be installed and you should **not** see the notification.
* Upload an outdated theme.
* For …
=> Indexation warning should not show when updating

src/presenters/admin/indexation-list-item-presenter.php
* We calculate the indexables in chunks on the background (shutdown). When the amount of indexables is lesser than the maximum amount of indexables that is calculated on background we shouldn't show a button to recalculate them. Because they are already indexed.
* Fixes a bug where the button to calculate the indexables is shown but there is nothing to index.
*
* Checkout the release branch
* Index your site.
* Delete one indexable row.
* Visit the SEO -> Tools page and see the Speed up your site button. It should not be there since it will be indexed in between rendering the page and the clicking of the button.
* Checkout this branch and follow the steps again
* The button should …
=> Hide the button when there is nothing to index

src/commands/index-command.php, tests/commands/index-command-test.php
* We want the WP CLI indexable indexation command to work on multisite environments, even when the migrations have not been run yet for one or more sites in the multisite network.
* Fixes a bug where the `yoast index --network` WordPress Command Line Interface (CLI) command gave an error when run on multisites, when the database migrations for one or more subsites had not been run yet.
* 
* Checkout the `release/14.1` branch.
* Startup a WordPress multisite environment.
* For example, startup your local Docker multisite development environment.
* Reset the database migrations for a subsite in the multisite network.
* Go to the database of your multisite environment en remove the …
=> WP CLI index command runs migrations for each site in a multisite.

js/src/components/AdvancedSettings.js
* Translator strings should be in the correct order.
* Fixes a bug where the translator strings would be in the wrong order.
* Check that the translator strings are in the correct order in the code.
Fixes N/A
=> Change translator string in the Advanced Settings tab

js/src/components/social/FacebookWrapper.js, js/src/components/social/SocialForm.js, js/src/components/social/TwitterWrapper.js, js/src/containers/FacebookEditor.js, js/src/containers/TwitterEditor.js
* Defaults needed to be set and passed to the new Social Previews.
* [non-user-facing] Pass the description placeholder, title placeholder, and social medium name in the FacebookWrapper and TwitterWrapper via the props.
* 
* Checkout the Javascript branch `631-add-defaults-to-social=previews` (sorry about the `=` typo), and `yarn link-monorepo`
* Verify that the description input still has a placeholder when it is emptied.
* Title input does not have a placeholder, which also isn't the case in the old social previews. We are mimicking those for now.
* Also test together with the *[premium PR](https://github.com/Yoast/wordpress-seo-premium/pull/2772)* by merging this into premium …
=> Add descriptionPlaceholder and pass it to social components

src/conditionals/yoast-admin-and-dashboard-conditional.php, tests/conditionals/yoast-admin-and-dashboard-conditional-test.php
* We want to avoid users to run the indexable indexation algorithm when doing a WordPress upgrade, since this may severely impact either the indexable process or the WP upgrade.
* Fixes a bug where the indexation notification is shown when WordPress is upgrading (after clicking 'upgrade' on the WordPress updates page).
* 
* Have an outdated WordPress installation.
* For example by setting up a docker container with an outdated WordPress image (plus a MySQL container).
* You can use this 'docker-compose.yml' file:
```yml
---
version: '3.3'
services:
db:
container_name: 'outdated-wordpress-db'
image: 'mysql:5.7'
volumes:
- './data/mysql:/var/lib/mysql'
ports:
- 18766:3306
environment: …
```
=> Indexation notification does not show up on WP upgrade page.

inc/class-upgrade.php
* Terms from private taxonomies have no use in the indexables table, since they cannot be indexed by search engines. We recently fixed this, but we should remove any pre-existing private terms from the indexable table.
* Fixes a bug where terms from private taxonomies were not removed from the indexable table after upgrading from a pre-14.1 version to 14.1 (or one of its release candidates).
* I decided to move the resetting of the permalinks of attachments to its own method, to clean up the `upgrade_141` a bit.
* Since that functionality still works as expected, I decided to leave it as is for the rest. E.g. to not let it run on `init` instead of directly when doing the upgrade routine. …
=> Private taxonomies are now removed on `init` when running the upgrade to 14.1.

inc/class-wpseo-utils.php
* See #15142 
* Fix a bug where the default value for no-index for taxonomies did not reflect settings
* Apparently, the no-index option can be retrieved using `WPSEO_Options::get( 'noindex-tax-' . 'YOUR_TAXONOMY_ADMIN_NAME' );`
* Change the default setting for some taxonomies in Settings > Search Appearance
* Check that the default setting is displayed correct in the Advanced Settings tab for those pages
* Also check for Custom Post Types and Custom Taxonomies.
Fixes #15142
=> Fix no index for taxonomies on the Advanced Settings tab

readme.txt, src/presenters/admin/indexation-modal-presenter.php, src/presenters/admin/indexation-warning-presenter.php, tests/integrations/admin/indexation-integration-test.php, tests/presenters/admin/indexation-modal-presenter-test.php, tests/presenters/admin/indexation-warning-presenter-test.php
* As @jono-alderson wrote: 
> 'indexing' and 'indexation' are completely different words with completely different meanings. We should change all of our strings (in product and marketing) to 'indexing' everywhere.
* Changes all occurrences of 'indexation' to 'indexing' in the changelogs and notifications.
* N/A
* There are only string changes, but if you want to test it: open the indexation modal and check the title and the `stop indexing` button. 
Fixes #
=> Use 'indexing' instead of 'indexation'

inc/options/class-wpseo-option-wpseo.php, js/src/wp-seo-indexation.js, src/integrations/admin/indexation-integration.php, src/presenters/admin/indexation-warning-presenter.php
*
* Fixes a bug where "Something went wrong while optimizing..." was shown briefly when the indexing process was stopped manually.
* Fixes a bug where an incorrect notification was shown when the indexing process had never been run before.
*
* Reset the indexables tables with the yoast test helper.
* Start the indexing
* Click the stop button.
* Don't see "Something went wrong while optimizing..."
* After `Test 1`: you won't see a notification, because the indexation process has run less than a month ago.
* In `wpseo` in `wp_options` in the database set `"indexation_started";i:5`
* See the notification containing "It looks like an indexing process was run earlier, but didn't …
=> Fix indexation notification bugs

inc/class-wpseo-utils.php
* Update the way we get the taxonomy slug as the previous method was not the most reliable.
* Use a filter_input to get the taxonomy_slug instead of relying on the labels_object.
* The labels_object might be altered by the user in some cases, in which the old code would have errored.
* Test that the default no-index option is displayed correctly in taxonomies:
- Categories
- Tags
- Custom taxonomies
Fixes N/A
=> Change the way we get taxonomy slug

deprecated/frontend/frontend.php
* Fixes replacement variables not being replaced when using the deprecated WPSEO_Frontend output without echo'ing it.
* Call `echo WPSEO_Frontend::get_instance()->metadesc( false );`.
* Replacement variables should be replaced in the string output.
Fixes #15126
=> Fix non-echo returns in the deprecated frontend class

admin/pages/tools.php, css/src/components/tabs.css
* Remove the the top line from pages that doesn't have tabs. The line doesn't line-up with the sidebar in the free version and looks very awkward. 
* Remove top line from the tools overview page.
*
* Pull this branch.
* Check if the lines from single pages are removed.
Fixes #FRO-64
=> FRO-64 Remove top lines from single pages.

src/builders/indexable-hierarchy-builder.php, src/config/migrations/20200513133401_ResetIndexableHierarchyTable.php, src/repositories/indexable-hierarchy-repository.php, src/repositories/indexable-repository.php, tests/builders/indexable-hierarchy-builder-test.php, tests/repositories/indexable-hierarchy-repository-test.php, tests/repositories/indexable-repository-test.php
* Fixes an issue where breadcrumbs were being saved in reversed order.
* The indexable hierarchy table is truncated in a migration. This table is only ever used as a cache and thus no reindex is required. For sites with very long breadcrumbs and/or a lot of terms the first request to each post may be slightly slower ( generating the breadcrumbs would be about the same speed as it was in 13.5 ).
* Make sure you have breadcrumbs at least 5 layers deep: home -> grandparent term -> parent term -> child term -> post.
* Save that post with the child term as the primary category. Check the breadcrumb.
* Save that post with the parent term as the primary category. Check the breadcrumb.
* Do …
=> Fix breadcrumb order

admin/views/tool-bulk-editor.php, admin/views/tool-import-export.php
* Change the tabs components to fit the new Yoast styling and restore functionality to them.
* Change the tabs components on the tool pages to fit the new Yoast styling.
*
* Pull this branch.
* Check on the tools `Import and Export` and `Bulk editor` pages if the tabs work and match the new styling.
Fixes #FRO-72
=> FRO 72 Restyle tabs on tools pages

inc/class-wpseo-utils.php
* The Advanced Settings tab was not being displayed on sites which had the setting `Security: no advanced settings for authors` set to `off`. This was not intentional.
* Fixes a bug where setting `Security: no advanced settings for authors` to `off` would remove the Advanced Settings tab for all users.
* The conditional statement was wrong.
Test the following cases:
1. As an Admin user:
- Set `Security: no advanced settings for authors` to `on`
- Edit a post
- Check that the Advanced Settings tab is visible
- Set `Security: no advanced settings for authors` to `off`
- Edit a post
- Check that the Advanced Settings tab is visible
2. As a normal user (the setting needs to be changed by an admin, prefixed _admin_):
- _admin_: Set …
=> Update conditional that was used to display the Advanced Setting tab

src/integrations/front-end-integration.php, tests/integrations/front-end-integration-test.php
* Removed a duplicate call to add the Yoast SEO output to the AMP plugin's output.
* This is done inside the integration (`integrations/third-party/amp.php`) and doesn't need to be done in front-end-integration.
* Set up a page with Yoast SEO meta data.
* Make sure you have the AMP plugin running.
* AMP pages should remain working as they do and should have valid Yoast SEO output.
=> Remove the AMP specific call from front-end-integration

src/integrations/front-end-integration.php
Strict type comparisons should be used as a rule, with loose type comparisons being the exception.
This is especially important when comparing variables which are expected to be strings, as when one of the two operands - for whatever reason, other plugins interfering, errors etc - is not a string, the other operand will be juggled to the type of the first operand which can lead to unexpected results and hard to debug bugs.
For array functions which do loose type comparisons, setting the third `$strict` parameter to `false`  can be seen as a clear indication that this is a conscious, well thought out decision by the developer.
In all other cases, `$strict` `true` should be used. …
=> QA: use strict comparisons with array functions

src/generators/schema/article.php, src/presenters/admin/indexation-modal-presenter.php
* Improved I18n support
* Improved I18n support
Fixes an output escaping function call to make sure they use the "translate + escape" variant instead of just escape the (untranslated) text.
`esc_html()` only escapes, `esc_html__()` escapes and translates.
Plugins/themes should use their own text domain. however, in some cases, using the WP Core translation for a string is warranted, like in this case.
The WP Core text-domain is `default` and while all gettext function call have a default value of `default` for the `$domain` parameter, explicitly setting the `$domain` in a gettext function call to `default` documents that the intention for this function call was to use the WP Core translation.
For CS purposes, the line still has …
=> I18n: various small fixes

inc/class-wpseo-utils.php
Use `self` when referencing a (static) class member from within the same class
* _N/A_
=> CS: use self when referring to current class

tests/conditionals/yoast-admin-and-dashboard-conditional-test.php, tests/presenters/canonical-presenter-test.php, tests/presenters/meta-description-presenter-test.php, tests/presenters/open-graph/article-author-presenter-test.php, tests/presenters/open-graph/article-publisher-presenter-test.php, tests/presenters/open-graph/description-presenter-test.php, tests/presenters/open-graph/locale-presenter-test.php, tests/presenters/open-graph/site-name-presenter-test.php, tests/presenters/open-graph/title-presenter-test.php, tests/presenters/open-graph/type-presenter-test.php, tests/presenters/open-graph/url-presenter-test.php, tests/presenters/rel-next-presenter-test.php, tests/presenters/rel-prev-presenter-test.php, tests/presenters/title-presenter-test.php, tests/presenters/twitter/card-presenter-test.php, tests/presenters/twitter/description-presenter-test.php, tests/presenters/twitter/image-presenter-test.php, tests/presenters/twitter/site-presenter-test.php, tests/presenters/twitter/title-presenter-test.php
* Improve code coverage recording
* Improved code coverage recording
The method under test for each of these tests has been renamed, while the `@covers` tags weren't updated yet.
* _N/A_
This is a test documentation-only change and should have no effect on the functionality.
=> Tests: fix `@covers` tags for renamed methods

tests/generators/schema/webpage-test.php
While PHP itself is not case-sensitive, the autoloader in Composer is, so the case of class names imported should be the same as when declared. And the name when used should also be the same again.
* _N/A_
=> CS: use correct case for class names

src/builders/indexable-post-builder.php, src/builders/indexable-rebuilder.php, src/integrations/watchers/indexable-post-watcher.php, tests/builders/indexable-post-builder-test.php, tests/builders/indexable-rebuilder-test.php, tests/integrations/watchers/indexable-post-watcher-test.php
* Since the issue we removed quite a few of these catch statements for the indexables and went to a fake indexable solution instead. Nevertheless there are some catch statements left. With a logger we can check if these result in problems. The standard logger (null logger) is still a not doing anything though.
* Adds logger calls to previously empty catch statements.
* Not sure about the logger with dependency injection like this. Seems like a bit overhead if we start using it on a lot of places.
* Add the following code somewhere (theme's functions.php?) to have a logger that actually does something. In this case it will output a "notice" with the exception message.
```php …
```
=> Add logger calls for the indexables

admin/class-plugin-availability.php, admin/class-suggested-plugins.php, inc/class-upgrade.php
* In https://github.com/Yoast/wordpress-seo-premium/issues/1632 we removed notifications like "Yoast SEO and WooCommerce can work together a lot better by adding a helper plugin. Please activate Yoast WooCommerce SEO to make your life better" from Premium. However, it was decided to bring them back. The only exception is the ACF notification, which will be removed from Free as well (slack me to ask why if you're curious ;) ).
* [wordpress-seo-premium only] Brings back the suggested plugins notification in premium
* Removes the ACF plugin suggestion notification
*
*Free*
* On trunk:
* Install the Advanced Custom Fields plugin.
* Make sure you don't have ACF Content Analysis for Yoast …
=> Bring back suggested plugins in premium and remove ACF notification

src/actions/indexation/indexable-post-indexation-action.php, src/actions/indexation/indexable-term-indexation-action.php, tests/actions/indexation/indexable-post-indexation-action-test.php, tests/actions/indexation/indexable-term-indexation-action-test.php
These are pulled separately as the tests include the hard-coded whitespace as part of the expectations, so the tests need to be updated as well for this change.
In all honesty, these tests would be better off to be whitespace-agnostic, but that's for another PR.
* _N/A_
=> CS: whitespace / minor function call formatting fixes

admin/class-admin-init.php, inc/class-wpseo-meta.php, inc/health-check-ryte.php, inc/options/class-wpseo-option-wpseo.php, src/actions/indexation/indexable-post-type-archive-indexation-action.php, src/commands/index-command.php, src/conditionals/yoast-admin-and-dashboard-conditional.php, src/config/migrations/20200420073606_AddColumnsToIndexables.php, src/config/migrations/20200428194858_ExpandIndexableColumnLengths.php, src/generators/breadcrumbs-generator.php, src/generators/schema-generator.php, src/generators/schema/article.php, src/generators/schema/faq.php, src/integrations/front-end-integration.php, src/repositories/indexable-hierarchy-repository.php, src/routes/indexables-head-route.php, src/surfaces/values/meta.php, tests/actions/indexation/indexable-post-type-archive-indexation-action-test.php, tests/context/meta-tags-context-test.php, tests/integrations/front-end-integration-test.php, tests/presentations/indexable-presentation/debug-info-test.php, tests/presentations/indexable-presentation/googlebot-test.php
Move arguments which are - or should be - multi-line out of select function calls in favour of declaring them as a variable and passing this variable to the function call.
Includes minor code de-duplication for a few arrays being re-declared time and again without any difference.
* _N/A_
=> CS: move multi-line arguments out of function calls

tests/builders/indexable-hierarchy-builder-test.php, tests/builders/indexable-post-builder-test.php, tests/builders/indexable-term-builder-test.php, tests/commands/index-command-test.php, tests/presenters/title-presenter-test.php
In a multi-line function call, each parameter should start on a new line and be indented one tab from the line containing the function call keyword.
This includes multi-line parameters.
Includes reformatting of chained function calls to have one call per line.
* _N/A_
=> CS: proper multi-line function call formatting [2]

src/integrations/watchers/indexable-date-archive-watcher.php, src/integrations/watchers/indexable-home-page-watcher.php, src/integrations/watchers/indexable-post-type-archive-watcher.php, src/integrations/watchers/indexable-system-page-watcher.php, tests/integrations/watchers/indexable-date-archive-watcher-test.php, tests/integrations/watchers/indexable-home-page-watcher-test.php, tests/integrations/watchers/indexable-post-type-archive-watcher-test.php, tests/integrations/watchers/indexable-system-page-watcher-test.php
* The builder's `build_for_id_and_type method` saves the indexable. However, `save` is still called outside of this method too in a lot of places. Those should be removed to prevent double saves.
* Removes redundant calls to save an indexable.
* Sometimes `save()` is executed when an indexable that was already built, is updated or deleted. In these cases, I didn't remove `save()`, because there is no double save. This applies to:
* `indexable->save()` in `indexable-static-home-page-watcher.php`.
* `$author_indexable->save()`and `indexable->save()` in `indexable-post-watcher.php`.
* I didn't remove `$indexable->save()` from `indexable-repository.php` because it is executed when a permalink is set for an indexable that was already …
=> Do not save indexables twice

tests/admin/admin-features-test.php, tests/doubles/models/indexable-double.php, tests/doubles/oauth/client-double.php, tests/doubles/shortlinker-double.php, tests/inc/language-utils-test.php, tests/models/indexable-test.php, tests/oauth/client-test.php
Includes:
* Adjusting the file names to mirror the new class names (if necessary).
* Adjusting the `use` statement and other references to the classes in the test files which uses these Doubles.
Note: the Composer `autoload.php` file has to be regenerated after this change for those people running tests locally!
* _N/A_
This is a test-only change and should have no effect on the functionality.
=> QA: rename three `double` classes to have `double` in the class name

tests/admin/metabox/metabox-section-additional-test.php, tests/admin/paper-presenter-test.php, tests/inc/health-check-curl-version-test.php, tests/inc/health-check-default-tagline-test.php, tests/inc/health-check-link-table-not-accessible-test.php, tests/inc/health-check-page-comments-test.php, tests/inc/health-check-postname-permalink-test.php, tests/inc/health-check-ryte-test.php, tests/inc/health-check-test.php, tests/inc/language-utils-test.php, tests/presentations/indexable-post-type-presentation/replace-vars-object-test.php, tests/presentations/indexable-presentation/replace-vars-object-test.php, tests/presentations/indexable-term-archive-presentation/replace-vars-object-test.php
The names of test classes in the new `tests` directory should not include the plugin prefix, nor should the file names be prefixed with `class-`.
These files were all called `replace-vars-object-test.php`, while the class contained therein was called `Generate_Source_Test`.
Per Herre:
> The `Generate_Source_Test` looks to be forgotten during a refactor.
> Originally, the files were called after the method under test and that got changed/renamed to the _values_ under test. Looks like the class name change was forgotten here.
>
> So, the file name is correct, the class name is not.
All tests should have the `Test` class suffix.
Note: the Composer …
=> CS: Tests - various class renames

config/dependency-injection/custom-loader.php, src/builders/indexable-post-builder.php, src/commands/index-command.php, src/conditionals/development-conditional.php, src/exceptions/missing-method.php, src/generators/open-graph-image-generator.php, src/helpers/date-helper.php, src/helpers/image-helper.php, src/helpers/meta-helper.php, src/helpers/product-helper.php, src/helpers/taxonomy-helper.php, src/integrations/primary-category.php, src/loader.php, src/main.php, src/presenters/admin/alert-presenter.php, src/presenters/admin/indexation-list-item-presenter.php, src/presenters/debug/marker-open-presenter.php, src/presenters/schema-presenter.php
Always be explicit about which classes are being used in a namespaced file.
* Always use _unqualified_ names for classes in code.
* Always have an import `use` statement for classes, unless the class is from the same namespace.
* _N/A_
=> QA: add missing import `use` statements for classes [src]

tests/builders/indexable-term-builder-test.php
Always be explicit about which classes are being used in a namespaced file.
* Always use _unqualified_ names for classes in code. Use aliases when necessary.
* Always have an import `use` statement for classes, unless the class is from the same namespace.
* _N/A_
=> QA: add missing import `use` statements for classes [with aliases]

config/dependency-injection/custom-loader.php, src/actions/indexation/indexable-post-type-archive-indexation-action.php, src/integrations/admin/indexation-integration.php, src/integrations/front-end/indexing-controls.php, src/integrations/watchers/indexable-static-home-page-watcher.php, src/presenters/robots-presenter.php, src/routes/yoast-head-rest-field.php, tests/admin/myyoast-proxy-test.php, tests/database/migration-runner-test.php, tests/doubles/generators/schema/article-double.php, tests/doubles/generators/schema/author-mock.php, tests/helpers/product-helper-test.php, tests/helpers/schema/image-helper-test.php, tests/presentations/indexable-author-archive-presentation/robots-test.php, tests/presentations/indexable-post-type-archive-presentation/canonical-test.php, tests/presentations/indexable-post-type-presentation/canonical-test.php, tests/presentations/indexable-presentation/presentation-instance-builder-trait.php, tests/presentations/indexable-presentation/twitter-description-test.php, tests/presentations/indexable-presentation/twitter-title-test.php, tests/presentations/presentation-instance-dependencies-trait.php, tests/presenters/admin/alert-presenter-test.php, tests/presenters/admin/indexation-list-item-presenter-test.php, tests/presenters/open-graph/type-presenter-test.php, tests/presenters/robots-presenter-test.php
Don't import classes if they're not being used, where "used" is taken in the widest sense of the term, i.e. use in docblocks is counted as "used".
* _N/A_
=> QA: remove unused `use` statements

js/src/components/social/SocialMetadata.js, js/src/redux/selectors/fallbacks.js
* Implement the feedback from UX on the styling.
* Update styling to incorporate the feedback from UX.
* * The Collapsibles have not been updated, this will be done in a later revision
* The `Insert Variable` button will be tackled by Rolf in https://github.com/Yoast/javascript/pull/668.
* Only styling changes. Have a look to see if you like them ;)
Nope. Since it only changes things that are not yet released.
Fixes #14617
=> Implement feedback from UX

admin/class-yoast-input-validation.php
* We want to escape the error message value of the social tab fields to prevent XSS scripting
* Fixes a bug where XSS scripting could be done in the social fields when entering something like `x3<img src=a onerror=alert(/Facebook-App-ID/)>%*|{}!#$^*&e3\`.
* Spoke with @moorscode and chose to validate with `esc_html`
For Twitter Username:
- Checkout this branch (xss-social-scripting-escaping), build and activate the plugin
- Navigate to "SEO"
- Navigate to "Social" sub-menu
- Set "Twitter Username" to:
`x3<img src=a onerror=alert(/Facebook-App-ID/)>%*|{}!#$^*&e3\`
- Click "Save Changes"
- Note that no popup appears
- Repeat these steps on trunk and make sure the popup **does appear** …
=> Escape social value to prevent xss scripting

css/src/metabox.css, js/src/components/AdvancedSettings.js, js/src/components/CollapsibleCornerstone.js, js/src/components/MetaboxCollapsible.js, js/src/components/SnippetPreviewSection.js, js/src/components/contentAnalysis/SeoAnalysis.js, js/src/components/fills/MetaboxFill.js, js/src/components/social/SocialMetadata.js, js/tests/__snapshots__/advancedSettings.test.js.snap, js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
* We want to update the styling of Collapsibles inside the Metabox, see [the new design](https://www.sketch.com/s/accd731d-dfb3-493e-bb2f-d4df01c8f1e8/a/znJ3Ab/play).
* Update the styling of Collapsibles in the Metabox.
- `max-width: 600px` has been added to the Metabox per [UX feedback](https://docs.google.com/document/d/1COUBBRYHClOdiqibIJNxXZe47ds1WdKNLqtPvTJ9lNo/edit?pli=1) and [the new design](https://www.sketch.com/s/accd731d-dfb3-493e-bb2f-d4df01c8f1e8/a/znJ3Ab/play).
- The color of the borders has changed slightly, to 20% #000000 as specified in the design and in the feedback. I used `rgba(0,0,0,0.2)` for this.
- `MetaboxCollapsible` has been created for the Collapsibles in the Metabox. `SidebarCollapsible` should be used …
=> Update collapsible styling

js/src/components/contentAnalysis/KeywordInput.js
* Adds a Slot after the Yoast Keyphrase input where Yoast add-ons or integrators can render their own components.
* Adds a Slot after the Yoast Keyphrase input where Yoast add-ons or integrators can render their own components.
* N/a
* I'll merge as soon as the build passes, better to test the Premium PR that depends on this.
=> Add Slot after keyphrase input

admin/metabox/class-metabox.php, inc/class-wpseo-meta.php
* We are going to add a schema tab.
* Adds hidden input fields for the schema tab.
* Add a new attribute to the meta_fields definitions that allows us to hide elements on pages.
* Visit a post:
* Check that `yoast_wpseo_schema_page_type` and `yoast_wpseo_schema_article_type` input fields are available.
* Visit a page:
* Check that `yoast_wpseo_schema_page_type` is available.
* Check that `yoast_wpseo_article_type` is not available.
Fixes #15229
=> Create hidden input fields for the schema tab

admin/metabox/class-metabox.php, inc/class-wpseo-replace-vars.php
* We want users to use safe values for the Google Preview and avoid PHP notices.
* FIxes a bug where replacement variable values that are a serialized array string break the Google Preview and output a PHP notice on the front end.
* Filtered out replacement variable values that are array / serialized array string
- on trunk: follow the steps from the issue https://github.com/Yoast/bugreports/issues/931
- additionally, add the custom field replacement variable also in the Meta description so that both title and description contain e.g. `%%cf_wpseo_global_identifier_values%% %%title%% `
- observe serialized array strings are displayed in the Google Preview
- go to the front end and …
=> PR-15 Exclude replacement variable values that are arrays.

admin/formatter/class-metabox-formatter.php, integration-tests/formatter/test-metabox-formatter.php, src/helpers/language-helper.php, src/surfaces/helpers-surface.php, tests/helpers/language-helper-test.php
* Until now, wordFormRecognitionActive was only set to true for English. This meant that the word form support upsell was only shown when the site language was set to English. However, we have many more languages with word form support, and because the upsell (for English) is quite effective, we'd like to show them for all supported languages.
* Shows the word form support upsell when the website is set to any of the supported languages, not only English.
* I tried porting the existing tests to brain monkey (together with Igor), but run into problems. For now I stuck with the oldskool tests. I'll contact Herre later to see if we can get the brain monkey test working. This shouldn't block merging. …
=> Set wordFormRecognitionActive to true for all languages with word form recognition

inc/class-wpseo-image-utils.php
* Fixes an edge case bug when people use external URLs for their images. Props to [	gr8shivam](https://github.com/gr8shivam)
Fixes the edge cases for external image URL check in https://github.com/Yoast/wordpress-seo/blob/trunk/inc/class-wpseo-image-utils.php#L28
The current `get_site_url()` works for cases where a user is using the Logo URL like
- http://example.com/wp-content/uploads/..
- http://example.com/mydata/uploads/..
But it misses out and treats as external URL when a user is using a different upload path like
- http://img.example.com/..
_Matching with the Upload directory base URL fixes this._
* Change default media path to a subdomain like img.example.com either manually …
=> Fix external URL check

wp-seo.php
WordPress core supports these headers now, this plugin should add these headers.
For reference, it seems this was added in WordPress 5.4 here:
https://core.trac.wordpress.org/ticket/46938
* Adds headers to the main plugin file for minimum supported WP version and minimum supported PHP version. WordPress will not activate the plugin anymore if incompatibilities are found.
*
*
Fixes #
=> Add required headers in plugin

inc/class-wpseo-replace-vars.php
* We want to fix a regression in trunk related to replacement variables introduced in https://github.com/Yoast/wordpress-seo/pull/15317
- Fixes a bug where the `date` replacement variable didn't output the year in the date archives.
- follow-up to https://github.com/Yoast/wordpress-seo/pull/15317
- makes sure all the replacement variable _values_ are string
- excludes custom fields values that come from a post meta that is an array
- found a few `retrieve_*` methods that returned an `int` although they're supposed to return a `string` as also stated in their `@return string` notation: I casted the returned values to `string`.
- now all the Yoast SEO built-in `retrieve_*` methods should return a string
- however, add-ons and other …
=> P3-25 Make sure all replacement variable values are strings.

src/generators/schema/faq.php, tests/generators/schema-generator-test.php, tests/generators/schema/faq-test.php
* Make sure we start a list at 1 instead of 0 in FAQ output.
* Fixes a bug where the FAQ schema list item's position would start at 0 instead of 1.
*
* Add an FAQ block to a page.
* View the source code.
* See that the {{itemList}} is no longer zero-indexed. Now starting at 1.
Fixes https://yoast.atlassian.net/browse/QAK-1849
=> Fix zero index

inc/class-wpseo-admin-bar-menu.php
Fixes #14731
* The link in the Admin Bar to the Facebook Debugger is not up to date.
* Admin Bar: fix link to Facebook Debugger
* View a post in the front end.
* Go to the Yoast menu button in Admin Bar, then Analyze this page, and click Facebook Debugger
* It should navigate to the correct Facebook Debugger page
Fixes #14731
=> Admin Bar: fix link to Facebook Debugger

yarn.lock
*
* Updates @yoast/browserslist-config to 1.2.1
* Even though https://github.com/Yoast/wordpress-seo-premium/pull/2791 is sufficient to fix the problem described in https://github.com/Yoast/wordpress-seo-premium/issues/2790, I created this PR to ensure the @yoast/browserslist-config version is the same in free and premium.
* Build and see no console errors.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2790
=> Update @yoast/browserslist-config to 1.2.1

src/builders/indexable-builder.php, src/builders/indexable-hierarchy-builder.php, src/config/migrations/20200609154515_AddHasAncestorsColumn.php, src/models/indexable.php, tests/builders/indexable-hierarchy-builder-test.php, tests/doubles/models/indexable-mock.php
* A lot of unnecessary delete queries are performed for records that can't exists. Added a field to determine if the indexable contains ancestors.
* Fixes a bug where a lot of delete queries are performed after clearing all indexables from the database
*
* The best way to test this is on the frontend.
* Make sure you have the breadcrumbs visible on your theme. For help with this see: https://yoast.com/help/implement-wordpress-seo-breadcrumbs/
* Have the query monitor enabled
* Checkout release/14.4
* Truncate the indexables and the indexables hierarchy tables in your database (or use the test helper with that)
* Visit a term page and see in the query monitor that a delete query on …
=> Introduces a field to have clear the indexable contains ancestors

readme.txt
This will have a tag named "Schema" show up on WordPress.org, making it a bit more clear for users we actually _do_ schema.
=> Add Schema as tag to readme.txt

js/src/edit.js
* In Options within default editor there is no option to enable/disable Yoast SEO in Document panel. This PR makes sure there is.
* Bugfix: makes sure there is an option to enable/disable the Yoast SEO panel in the document sidebar.
* Initially I used a normal Fill to get our panel in the sidebar, not realizing I would be breaking interoperability with how Gutenberg takes care of plugin panels. I reverted back to using the standard Gutenberg panel for this. 
* The reason I didn't go for the standard panel in the first place is because there was no way to have it be open on initial usage. I now added a function that checks upon initialization if our panel is loaded for the first time. If it is, it toggles it open. From then on, …
=> QAK-1874 Use standard plugin document panel

admin/views/tabs/metas/paper-content/rss-content.php
* Style the info table in the RSS tab conform the new Yoast styling
* Style the info table in the RSS tab conform the new Yoast styling
*
* Go to the `RSS` tab in `Search Appearance`
* Check if the `Available variables` table matches the new styling
Fixes https://yoast.atlassian.net/browse/FRO-70
=> FRO-70 Style the info table of the RSS tab

grunt/config/aliases.yaml, grunt/config/prompt.js, grunt/config/shell.js, grunt/custom/ensure-rc-dependencies.js
Inroduces two flags to use, when non-RC versions of the dependencies need to be installed.
--yoast-components-no-rc
--yoastseo-no-rc
* The `yoastseo` and `yoast-components` packages sometimes don't have an RC version released for the current release. This causes the script to think that the previous RC needs to be released, but there is a stable version available (14.0@rc.0 vs 14.0) The flags introduced give you control to pick the RC or non-RC version of these packages.
* [non-user-facing] Introduces two flags to control RC or stable version of YoastSEO & Yoast-component packages when creating an RC using the grunt command.
* n/a
For each of the following commands, the specific …
=> Introduce RC JavaScript-dependency version-level control

admin/class-gutenberg-compatibility.php, grunt/config/aliases.yaml, grunt/custom/sync-gutenberg-version.js
Fetches the latest version using the WordPress API and updates the PHP file containing the constants for the Gutenberg-supported version.
* Gutenberg plugin versions get released regularly, we want to keep the latest supported version in sync with the latest version upon RC creation. This should automatically be updated to the PHP file that contains the version checks.
* [non-user-facing] This will fetch the current Gutenberg version from the WordPress plugins directory and update the constants we check against in our code.
* n/a
* Use `grunt sync-gutenberg-version`; and see
* The file `admin/class-gutenberg-compatibility.php` being updated with the current Gutenberg version.
* The …
=> Sync the Gutenberg version to the PHP file

admin/config-ui/components/class-component-suggestions.php, grunt/config/eslint.js
* 
* [wordpress-seo-premium] Fixes a bug where the link for Local SEO was missing in the Configuration Wizard "Continue learning" step.
* Updates the ESLint `maxWarnings`. Note that the `eslint:grunt` task doesn't report any warning because all of them were fixed in https://github.com/Yoast/wordpress-seo/commit/e9fb5a590957299ff5352ea917ce9ba3e1857db6 but the `maxWarnings` wasn't updated.
The code for this feature is in Free but it affects Premium. To test it either copy the tiny change over to Premium or alter the code in 
https://github.com/Yoast/wordpress-seo/blob/18161f12edb55885439f5179f19e452e7ca19850/admin/config-ui/components/class-component-suggestions.php#L76
and change it …
=> P3-33 Fix configuration wizard local seo link

inc/options/class-wpseo-options.php, src/actions/indexation/indexable-term-indexation-action.php, src/integrations/admin/indexation-integration.php, src/integrations/watchers/indexable-category-permalink-watcher.php, src/presenters/admin/indexation-permalink-warning-presenter.php, src/presenters/admin/indexation-warning-presenter.php, tests/actions/indexation/indexable-term-indexation-action-test.php, tests/integrations/admin/indexation-integration-test.php, tests/integrations/watchers/indexable-category-permalink-watcher-test.php
* When the categories prefix option (called `stripcategorybase`) is switched between `Keep` and `Remove`, the permalink for category indexables should be updated. In this PR, we set it to `NULL`. It will be rebuilt whenever that category is visited, or when someone indexes all of their content.
* Fixes a bug where an indexable's permalink remained unchanged when the categories prefix option was changed.
* I copied some code (part of the content of `clear_category_permalinks`) from the `indexables-permalink-watcher`. Because it's so small, creating a helper, passing the `indexable-permalink-watcher` class to my new class, or extending the `indexable-permalink-watcher` class seemed overkill. …
=> Clear the category permalinks when stripcategorybase option changes

admin/class-admin-asset-manager.php, js/src/components/contentAnalysis/SeoAnalysis.js
* We want to have beter UI consistency and reduce the amount of component / packages used.
* Makes the Related keyphrases and Synonyms upsell modal dialogs use the Gutenberg Modal component.
*
- edit a post
- go the the meta box, open the SEO analysis panel
- click on the buttons "+ Add synonyms" and "+ Add related keyphrase" (visually, they look like links)
- observe they use our Modal component
**Test the modals with Classic Editor:**
- install and activate the Classic Editor plugin
- edit a post
- expand the SEO analysis panel
- click the links to open the modals and observe the modal styling is OK
Note: the visual difference is that the Gutenberg Modal uses an animation and …
=> P3-31 Use the Gutenberg modal for the related keyphrases synonyms upsell modals

lib/model.php, lib/orm.php, phpcs.xml.dist
* After https://github.com/Yoast/wordpress-seo/pull/15314 only the ORM and model files remained.
* Fixes CS issues in the CS folder.
* Un-excludes the lib folder from CS checks.
*
* CS should be fixed.
* Ignored warnings:
* Code comment warning in model. The comment IS commented out code.
* Warning about a loose comparison. This seems very intended. Integer whenever the float is loosely the same as the integer value. But I could not get the ignore to work, so I left it.
* Ignored the CS error about the usage of `MYSQL_MAX_IDENTIFIER_LENGTH`. Does not seem relevant to an adapter to me. But I could be terribly wrong here.
* Have an opinion on: the strict check changes in …
=> Fix CS in the lib folder

src/conditionals/yoast-admin-and-dashboard-conditional.php, src/integrations/watchers/indexable-category-permalink-watcher.php, src/integrations/watchers/indexable-permalink-watcher.php
* This is only the indexation part of the issue. There should be a notification part too.
* Ensures the indexation spots the indexables without a permalink.
* https://github.com/Yoast/wordpress-seo/pull/15427 already changed the term indexation action to count the permalink_hash as unindexed
* Add the permalinks options page to the conditional so the indexation runs on that page too. This will need to be split up later in https://github.com/Yoast/wordpress-seo/issues/15438
* Go to the WP permalink settings page.
* When you have more than 25 categories this will not run in shutdown function, but if you less than 25 you will not see the notice and it will autocorrect. Lower the limit …
=> Clear permalinks on taxonomy settings change
