tests/helpers/current-page-helper-test.php

CS: don't unnecessarily use double quotes for strings

---

admin/views/tabs/metas/archives.php
admin/views/tabs/metas/breadcrumbs.php
admin/views/tabs/metas/general.php
admin/views/tabs/metas/media.php
admin/views/tabs/metas/paper-content/general-content.php
admin/views/tabs/metas/paper-content/media-content.php
admin/views/tabs/metas/paper-content/post-type-content.php
admin/views/tabs/metas/post-types.php
admin/views/tabs/metas/rss.php
admin/views/tabs/metas/taxonomies.php
integration-tests/bootstrap.php

Minor code simplification which is possible now PHP 5.6 is the minimum version.
* _N/A_

Modernize: use `__DIR__` instead of `dirname( __FILE__ )`

---

deprecated/frontend/class-opengraph.php
deprecated/frontend/class-primary-category.php
deprecated/frontend/class-twitter.php

CS: use short arrays

---

src/presenters/abstract-indexable-presenter.php

The order of property and method scope modifiers should follow this pattern:
`abstract visibility static`
* _N/A_

CS: fix scope modifier order

---

inc/health-check-postname-permalink.php
inc/health-check-ryte.php
src/backwards-compatibility/frontend.php

QA: don't use Yoda conditions

---

src/memoizers/presentation-memoizer.php
tests/integrations/front-end-integration-test.php
tests/presenters/breadcrumbs-presenter-test.php
tests/presenters/canonical-presenter-test.php
tests/presenters/googlebot-presenter-test.php
tests/presenters/rel-next-presenter-test.php
tests/presenters/rel-prev-presenter-test.php
tests/presenters/robots-presenter-test.php
tests/presenters/schema-presenter-test.php
tests/presenters/twitter/card-presenter-test.php
tests/presenters/twitter/creator-presenter-test.php
tests/presenters/twitter/description-presenter-test.php
tests/presenters/twitter/image-presenter-test.php
tests/presenters/twitter/title-presenter-test.php
tests/presenters/twitter/twitter-site-presenter-test.php

Multiple assignments in one statement makes for harder to debug, harder to read code and is considered a code smell.
* _N/A_

CS: no multiple assignments in one statement

---

admin/class-admin.php
ruckusing.conf.php
tests/TestCase.php
tests/generators/schema-generator-test.php
tests/generators/schema/faq-test.php
tests/generators/schema/person-test.php
tests/integrations/front-end/open-graph-oembed-test.php
tests/integrations/third-party/woocommerce-test.php
tests/presentations/indexable-presentation/twitter-image-test.php

CS: fix array double arrow alignment

---

admin/taxonomy/class-taxonomy-settings-fields.php

Implicit array creation is a code smell.
* _N/A_

 QA: fix implicit array creation

---

admin/taxonomy/class-taxonomy.php
deprecated/frontend/schema/class-schema-author.php
inc/sitemaps/class-sitemaps-cache.php
src/builders/indexable-post-builder.php
src/generators/breadcrumbs-generator.php
src/generators/schema/author.php
src/integrations/watchers/indexable-post-type-archive-watcher.php
src/integrations/watchers/indexable-system-page-watcher.php
src/loggers/database-logger.php
src/presenters/breadcrumbs-presenter.php
src/presenters/robots-presenter.php

Place boolean operator at the start of the line in multi-line conditions.
This generally makes for a smaller diff if something changes and improves readability.
* _N/A_

CS: boolean operator at the start of the line in multi-line conditions

---

package.json
yarn.lock

*
* Bumps the monorepo packages for 13.5-RC1
*
*
Fixes #

Bump monorepo packages for 13.5-RC1

---

src/integrations/front-end/open-graph-oembed.php
tests/integrations/front-end/open-graph-oembed-test.php

* This fixes the embedding of posts on LinkedIn, by using the OpenGraph data to power the core oEmbed feature. We already had this, but it was broken.
* This fixes the embedding of posts on LinkedIn, by using the OpenGraph data to power the core oEmbed feature.
* Swapped out the `Meta_Helper` for the `Meta_Surface`, thereby making the code a lot more efficient as it doesn't have to retrieve image sizes etc. itself.
Assuming you're using `basic.wordpress.test`, otherwise replace hostnames / URLs where needed:
*  Go to your `hello-world` post. Set a Facebook title, description and make sure an image is somewhere, either featured, in content or in the OG settings.
* go to …

Fix OpenGraph data in oEmbed for LinkedIn

---

package.json
yarn.lock

*
* Bumps monorepo packages for 13.5
*
*
Fixes #

Bump monorepo packages for 13.5

---

migrations/20200408101900_AddCollationToTables.php

* This fixes the collation of the database tables to match that of the default WordPress tables.
* This means it's possible to join and compare these columns across tables.
* Make sure you can view the structure of your tables.
* Open any page in your site with this PR active.
* The collation of the yoast tables should match the collation of all other tables.

Fix table collation

---

src/context/meta-tags-context.php
tests/context/meta-tags-context-test.php

* ProfilePage extends the WebPage, thus having WebPage as schema page type isn't necessary. This can be simplified by saying it just is a ProfilePage.
* I've discussed this with @jono-alderson and he agreed that we can simplify this.
* The documentation about this is changed: https://developer.yoast.com/features/schema/pieces/webpage/#transformations
* Simplified the page type for a user profile page. It can be just ProfilePage instead of `[ ProfilePage, WebPage ]`
* Extends the page type for a search result it should be `[ CollectionPage, SearchResultsPage ]` 
*
* Visit a user profile and see the schema page type is ProfilePage instead of `[ ProfilePage, WebPage ]`
* Do a search …

Simplifies the page type for a user profile page

---

css/src/metabox.css

* In Premium the metabox CSS file is loaded, for some reason. Results in styling not being that nice.
* Fixes a bug where the score column heading has wrong styling.
* Premium is loading the metabox css for some reason. This css file contains styling for the `#wpseo-score`. That element doesn't exist anymore. However the column heading for the seo score contains the same ID and because of that it receives a float and margin. This misaligns the element on for example Google Chrome (windows). On mac the column is wider than expected.
* Checkout master on premium and do the building magic: `grunt build:css` in the root and the premium directory. See the column is aligned weird.
* …

Remove styling for unused element

---

src/builders/indexable-builder.php
tests/builders/indexable-builder-test.php

* When an indexable for a post is built and there is no indexable for its author we should create it.
* Build an indexable for the author when it doesn't exist on post indexable creation.
* I've added tests for all methods in the indexable builder.
* Remove all indexables
* Visit a post and check if the indexable for the post and the user is created (in the database)
* Remove all indexables
* Run the reindexing tool on (yoast seo -> tools -> index content) and verify that there are indexables made for the users belong to the posts.
Fixes #

Build author indexable if needed

---

src/presenters/admin/indexation-warning-presenter.php
tests/TestCase.php
tests/presenters/admin/indexation-modal-presenter-test.php
tests/presenters/admin/indexation-warning-presenter-test.php

* We want the test coverage to be 100%.
* Adds tests for the admin presenter files.
*
* Ensure the test coverage is 100%.
* Ensure the tests make sense and pass.
Fixes #

Indexation admin presenters tests

---

config/dependency-injection/services.php
src/conditionals/yoast-admin-and-dashboard-conditional.php
src/integrations/admin/indexation-integration.php
src/wordpress/wrapper.php
tests/TestCase.php
tests/conditionals/yoast-admin-and-dashboard-conditional-test.php
tests/integrations/admin/indexation-integration-test.php
tests/presenters/admin/indexation-warning-presenter-test.php

* We want the test coverage to be 100%, so we have an early warning when functionality breaks because of code changes.
* Adds unit tests for the indexation integration to up the test coverage of the class to 100%.
* The `WPSEO_Asset_Manager` is now registered as a custom service on the dependency injection container.
* (I checked this with Herre)
* This means that it can be injected into the classes, like the other classes in the container.
* This makes writing tests for classes that use the asset manager easier.
* Run the unit tests.
* Check that the code coverage of the `Indexation_Integration` class (located in `src/integrations/admin/indexation-integration.php`) is 100%.
Fixes #

Write tests for indexation integration

---

admin/views/class-yoast-feature-toggles.php
inc/options/class-wpseo-option-wpseo.php
src/conditionals/headless-rest-endpoints-enabled-conditional.php
src/routes/indexables-head-route.php
tests/conditionals/headless-rest-endpoints-enabled-conditional-test.php
tests/routes/indexable-indexation-route-test.php
tests/routes/indexables-head-route-test.php

* We want to offer the possibility disabled the headless rest route.
* Added a feature toggle to disable the headless rest routes.
*
* Go to Yoast SEO -> Features -> REST API: Head endpoint and make that the toggle is enabled.
* Visit http://basic.wordpress.test/wp-json/yoast/v1/get_head?url=http://basic.wordpress.test and make sure you have output.
* Go to Yoast SEO -> Features -> REST API: Head endpoint and make that the toggle is disabled.
* Visit the url again and make sure you don't have access.
Fixes #14872

Introduce a feature toggle for the headless rest endpoints

---

package.json
yarn.lock

*
* Bumps the JS monorepo packages for the 14.0 release.
*
*
Fixes #

Bump JS monorepo packages for 14.0 release

---

src/integrations/admin/indexation-integration.php
src/presenters/admin/indexation-list-item-presenter.php
src/presenters/admin/indexation-warning-presenter.php
tests/integrations/admin/indexation-integration-test.php
tests/presenters/admin/indexation-warning-presenter-test.php

* Trying to improve the copy for indexation alert.
Now looks like this:
* None needed.
* Indexation should still work. Should look like above.

Optimize indexing copy

---

package.json
yarn.lock

*
* Bumps the monorepo packages for `14.1-RC1`.
*
*
Fixes #

Bump monorepo packages for 14.1-RC1

---

inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-option-wpseo.php

* The feature control on network base didn't work.
* Fixes a bug where the feature toggle in the network admin didn't had any effect on the feature toggle per site.
*
* Follow the steps in #14915 and make sure this pull fixed it.
Fixes #14915

Adds the toggle to the feature toggles list for the network admin

---

README.md

* We want to inform developers of the existence of the dev-server, and how to use it.
* Added information of dev-server to readme.
*
*
Fixes #

Inform users of dev-server in Readme

---

package.json
yarn.lock

*
* Bumps the JS monorepo packages for 14.1-RC1.
*
*
Fixes #

Bump JS monorepo packages for 14.1-RC1

---

src/actions/indexation/indexable-post-indexation-action.php
src/actions/indexation/indexable-term-indexation-action.php
src/builders/indexable-builder.php
src/builders/indexable-hierarchy-builder.php
src/builders/indexable-post-builder.php
src/builders/indexable-term-builder.php
src/generators/breadcrumbs-generator.php
src/integrations/watchers/indexable-post-watcher.php
src/integrations/watchers/indexable-term-watcher.php
src/repositories/indexable-repository.php
tests/builders/indexable-builder-test.php
tests/builders/indexable-post-builder-test.php
tests/builders/indexable-term-builder-test.php
tests/integrations/watchers/indexable-post-watcher-test.php
tests/integrations/watchers/indexable-term-watcher-test.php

*
* Fixes a bug where we would throw an exception without catching it in the indexables post and term builders.
*
*
Fixes #14935

Indexable builders return false

---

admin/class-primary-term-admin.php

* Remove a (no longer needed) call to a deprecated primary category class.
* Primary category functionality should still work in the admin.
Fixes #

Remove call to deprecated class

---

migrations/20200428194858_ExpandIndexableColumnLengths.php

* Fixes fatal errors when titles were more than 191 characters long.
* Ensure the WPSEO_VERSION is higher than the last time you ran migrations.
* Open any page.
* Create a SEO title ( in the metabox, not the post title ) that's longer than 191 characters, preferably much, much longer.
* It should not cause a fatal error.
Fixes #

Expand the lengths of all indexable columns

---

composer.json
composer.lock
grunt/config/copy.js
grunt/config/shell.js
yoast_meta.md

* Removed idiorm dependency.
*
Fixes #

Remove idiorm everywhere

---

lib/orm.php

* Ensures new models created are always of the correct class.
* Run
```
$repository = YoastSEO()->classes->get( Yoast\WP\SEO\Repositories\Indexable_Repository::class );
$instance = $repository->query()->create( [ 'object_type' => 'unknown' ] );
```
* The returned value should be of the indexable class.
Fixes #14975

Ensure new models created by the ORM are of the correct class

---

src/models/indexable.php

* When permalink structure contains a `.html` we don't want to have a trailing slash.
* Only append a trailing slash when the permalink structure is configured to have one.
*
* Change the value in the permalink structure to have `.html` in it
* Checkout the release branch (`release/14.0.2`)
* Remove all indexables (or the one of the post you are about to visit in the next step.)
* Visit the post (indexable is calculated now)
* The canonical contains a trailing slash.
* Repeat the indexable removal step and visit the post again
* The canonical doesn't contain a trailing slash.
Fixes #14982

Only add trailing slash when permalink structure has one.

---

inc/class-upgrade.php
lib/orm.php
src/repositories/indexable-hierarchy-repository.php
src/repositories/indexable-repository.php
src/repositories/primary-term-repository.php
src/repositories/seo-links-repository.php
src/repositories/seo-meta-repository.php
src/routes/route-interface.php
tests/actions/indexation/indexable-post-type-archive-indexation-action-test.php
tests/builders/indexable-author-builder-test.php
tests/builders/indexable-date-archive-builder-test.php
tests/builders/indexable-post-type-archive-builder-test.php
tests/builders/indexable-system-page-builder-test.php
tests/repositories/indexable-hierarchy-repository-test.php
tests/repositories/indexable-repository-test.php

* Remove the `ORMWrapper` references in code.
*
Fixes #15013

Remove/fix all the ORMWrapper references

---

lib/ruckusing-adapter.php

* Change how we check if a table exists so it works with uppercase table prefixes.
* Suppressing errors, because this _can_ throw an error, but we're using that fact.
* Reset your indexable tables.
* Indexation should work.
Fixes #15017

change the table exists checks

---

admin/class-yoast-form.php
admin/views/tabs/network/features.php
admin/views/tabs/network/general.php
admin/views/tabs/network/restore-site.php
admin/views/tool-file-editor.php
css/src/components/headings.css

* We are gonna restyle the "General" and "Restore site" pages of the SEO dashboard in the multisite admin. We are gonna make changes so that they are gonna use the javascript monorepo.
* Restyle general and restore site pages of multisite dashboard
*
* Pull "14544-multisite-dashboard-updates" from the "wordpress-seo" and the "javascript" repository.
* Link the monorepo.
* In the multisite environment click on "SEO".
* Check if the "General" and "Restore" tabs are showing properly
Fixes #14544

Restyle general and restore site pages of multisite dashboard

---

lib/model.php
src/generators/breadcrumbs-generator.php

* Fixes the breadcrumb on search result pages.
* Also makes or models json serializable for easier debugging.
* Enable breadcrumbs.
* You should see a search breadcrumb when on a search result page.
Fixes #15041
Fixes #14867

Fix the search breadcrumb and make all our modes json serializable

---

src/builders/indexable-hierarchy-builder.php
src/repositories/indexable-hierarchy-repository.php
tests/builders/indexable-hierarchy-builder-test.php
tests/repositories/indexable-hierarchy-repository-test.php

* Fixes an error where indexation could not be completed due to posts or terms having themselves as a parent or grandparent.
* Edit your database to set a post to be it's own `post_parent`.
* Delete the indexable for that post.
* Index your site again to make the indexable ( note: do not go to the post edit of that post as WordPress will fix the parent, presumably bad plugins cause this situation ).
* Edit your database to set a post to have another post as it's parent and that other post to have the first post as it's parent, creating a loop.
* Delete the indexables for both posts.
* Index your site again, it should complete.
* In both cases the indexables should not have any …

Don't add duplicate ancestors and abort on hierarchy save error

---

inc/class-upgrade.php

* 
* Deletes indexables of private taxonomies.
*
* Run the indexation routine.
* Get indexable entries of private taxonomies.
* In premium this can be the prominent words as mentioned in the issue. In free you can create a menu to ensure you actually have entries.
* Alter [the line in the term indexation action](https://github.com/Yoast/wordpress-seo/blob/release/14.1/src/actions/indexation/indexable-term-indexation-action.php#L116) to `$public_taxonomies = \get_taxonomies( [ 'public' => false ], 'names' );`.
* Run the indexation (it should be available again now).
* Undo your change in the taxonomy helper.
* Verify you have one or more indexable entries for private terms in your …

Clean up indexables of private taxonomies

---

src/config/migrations/20200507054848_DeleteDuplicateIndexables.php

* Cleanup after the fix https://github.com/Yoast/wordpress-seo/pull/15062
* Adds a migration to clean up any double indexable entries.
*
* On the `release/14.1` branch
* Run the indexation
* Switch to this branch
* Duplicate a few indexation rows in your database and use higher IDs for those rows.
* Remove the `option_name` `yoast_migrations_free` from the `wp_options` table.
* Visit a page to let the migrations run.
* Check your database, the duplicated indexation rows should be gone again. Pay extra attention that the ones with the higher ID should be gone.
Fixes #15065

Add migration to delete duplicate indexables

---

inc/sitemaps/class-sitemaps.php

Refactor urlencode to rawurlencode

---

inc/class-upgrade.php
src/actions/indexation/indexable-general-indexation-action.php
src/builders/indexable-post-builder.php
src/generators/open-graph-image-generator.php
src/generators/twitter-image-generator.php
src/helpers/image-helper.php
src/models/indexable.php
src/repositories/indexable-repository.php
tests/models/indexable-test.php

* Optimizes finding attachments by URL. This should address a primary cause of higher server load issues starting with 14.0.
* Code review should check for any missed instances where we look up an attachment by URL even though we already have the ID.
* Set your version number to 14.0 so upgrade routines are run.
* For the following use-cases schema and meta tag output should remain the same:
1. Assigning an open graph image to a post.
1. Assigning a twitter image to a post.
1. Assigning a featured image and none of the above.
1. Not assigning any image but having an image in your content.
* As attachments are written to indexables as they are used please check the above over at …

Optimize finding attachments by url

---

package.json
yarn.lock

*
* Bumps the JS packages.
*
*
Fixes #

Bump JS packages

---

js/src/components/AdvancedSettings.js
js/tests/__snapshots__/advancedSettings.test.js.snap

See https://yoast.slack.com/archives/CSYSU835E/p1588843564001400 for details / discussion
* Update the copy in the Advanced Settings tab.
* Updates the copy in the Advanced Settings tab.
* See that the copy is updated.
Fixes N/A

Update copy in the advanced settings

---

src/presenters/admin/migration-error-presenter.php
tests/integrations/admin/migration-error-integration-test.php
tests/presenters/admin/migration-error-presenter-test.php

*
* Improves the notification that is shown when there were problems creating the necessary database tables.
*
* In `src/integrations/admin/migration-error-integration.php` comment out the return on line 48.
* Navigate to the post overview (or another admin page)
* See the new copy.
Fixes #15138

Update migration error copy

---

src/conditionals/yoast-admin-and-dashboard-conditional.php
tests/conditionals/yoast-admin-and-dashboard-conditional-test.php

CS: fix incorrect spelling of WordPress (dangit!)

---

admin/class-yoast-notifications.php
src/actions/indexation/indexable-post-indexation-action.php
src/integrations/front-end/open-graph-oembed.php
tests/integrations/admin/indexation-integration-test.php
tests/integrations/front-end-integration-test.php
tests/presenters/admin/alert-presenter-test.php
tests/presenters/admin/indexation-list-item-presenter-test.php
tests/routes/yoast-head-rest-field-test.php
tests/values/images-tests.php

* Improve documentation
* Improved documentation
Various documentation related changes:
* Minor docblock formatting fixes
* Fix duplicate variable name in param tag
* Minor `@param` description alignment fixes
* Add missing `@param` tag
* Fix incorrect `@covers` tag annotations
* Minor textual fixes 
* _N/A_

Docs: various fixes

---

tests/actions/indexation/indexable-post-type-archive-indexation-action-test.php

All files in the new `tests/` directory should have a namespace declaration.
* _N/A_

QA: add missing namespace declaration

---

admin/metabox/class-metabox.php
admin/taxonomy/class-taxonomy.php
inc/health-check-links-table-not-accessible.php
inc/health-check-ryte.php
src/builders/indexable-post-builder.php
src/builders/indexable-system-page-builder.php
src/generators/breadcrumbs-generator.php
src/generators/open-graph-image-generator.php
src/integrations/front-end-integration.php
src/integrations/front-end/open-graph-oembed.php
src/integrations/watchers/indexable-post-watcher.php
src/memoizers/meta-tags-context-memoizer.php
src/memoizers/presentation-memoizer.php
src/presenters/admin/indexation-list-item-presenter.php
src/presenters/admin/indexation-warning-presenter.php
src/presenters/admin/migration-error-presenter.php
tests/actions/indexation/indexable-post-indexation-action-test.php
tests/builders/indexable-builder-test.php
tests/builders/indexable-hierarchy-builder-test.php
tests/generators/schema/author-test.php
tests/integrations/admin/indexation-integration-test.php
tests/presenters/bingbot-presenter-test.php

CS: fix assignment operator alignment

---

tests/generators/schema/author-test.php

CS: type casts should be lowercase

---

admin/class-admin-init.php

CS: object instantiations should always use parentheses

---

src/generators/schema/person.php

CS: boolean operator placement

---

src/actions/indexables/indexable-head-action.php
src/config/migrations/20200428123747_BreadcrumbTitleAndHierarchyReset.php
src/context/meta-tags-context.php
src/presentations/indexable-presentation.php
src/repositories/indexable-repository.php
tests/builders/indexable-builder-test.php
tests/builders/indexable-term-builder-test.php
tests/database/migration-status-test.php
tests/generators/schema/article-test.php
tests/integrations/third-party/woocommerce-test.php
tests/models/indexable-test.php
tests/presenters/breadcrumbs-presenter-test.php
tests/routes/indexables-head-route-test.php
tests/routes/yoast-head-rest-field-test.php

CS: various array layout fixes

---

tests/values/images-tests.php

CS: tweak a function for CS and readability

---

src/routes/indexable-indexation-route.php

CS: minor refactor to remove duplication

---

src/routes/yoast-head-rest-field.php
tests/helpers/blocks-helper-test.php
tests/helpers/current-page-helper-test.php
tests/integrations/watchers/primary-term-watcher-test.php
tests/presentations/indexable-term-archive-presentation/robots-test.php
tests/presentations/indexable-term-archive-presentation/title-test.php
tests/presenters/open-graph/title-presenter-test.php
tests/routes/indexables-head-route-test.php

CS: multi-line function call formatting (to single line)

---

tests/surfaces/meta-surface-test.php

CS: fix readability of a test

---

tests/database/migration-status-test.php

CS: multi-line chained calls have one method call per line

---

admin/class-bulk-description-editor-list-table.php
admin/class-bulk-editor-list-table.php
admin/class-bulk-title-editor-list-table.php
admin/class-config.php
admin/class-social-admin.php
deprecated/frontend/class-opengraph.php
deprecated/frontend/class-twitter.php
inc/class-rewrite.php
inc/class-wpseo-meta.php
inc/class-wpseo-replace-vars.php
inc/sitemaps/class-sitemaps-admin.php

This is an old-style habit from when intelligent IDEs weren't the standard yet.
* _N/A_

CS: remove redundant "end" comments

---

inc/class-upgrade.php
tests/actions/indexation/indexable-post-type-archive-indexation-action-test.php

CS: clean up / whitespace fixes

---

src/builders/indexable-system-page-builder.php

CS: fix function declaration signature

---

package.json
yarn.lock

*
* Bumps the version of the `javascript` packages.
*
*
Fixes #

Bump monorepo versions

---

inc/health-check-ryte.php
tests/builders/indexable-author-builder-test.php
tests/builders/indexable-hierarchy-builder-test.php

CS: minor clean up after merges

---

src/conditionals/migrations-conditional.php
src/conditionals/yoast-admin-and-dashboard-conditional.php
src/config/migration-status.php
src/helpers/date-helper.php
src/helpers/url-helper.php
src/integrations/admin/indexation-integration.php
src/integrations/front-end-integration.php
src/integrations/front-end/comment-link-fixer.php
src/loader.php
src/presenters/admin/alert-presenter.php
src/presenters/admin/indexation-warning-presenter.php
src/presenters/open-graph/image-presenter.php
src/presenters/schema-presenter.php
src/routes/indexables-head-route.php
src/surfaces/meta-surface.php
src/surfaces/values/meta.php
tests/database/migration-status-test.php
tests/helpers/date-helper-test.php
tests/helpers/url-helper-test.php
tests/integrations/front-end-integration-test.php
tests/presenters/open-graph/image-presenter-test.php
tests/presenters/schema-presenter-test.php
tests/surfaces/meta-surface-test.php

QA: use FQN constants in namespaced files

---

src/integrations/watchers/indexable-permalink-watcher.php

* We want to give the possibility to have easily access to the method that resets the indexables.
* N/A - It just makes a method public
* I removed the `@codeCoverageIgnore` for all methods. We should have full coverage for these later.
* Chosen to make the method public. This is discussed with architects. The method is public and can be used where it is need. This makes it possible to have the permalink reset logic for specific cases in the plugins itself. This reduces the complexity.
* Change the permalink structure > Admin - Settings - Permalinks
* Verify that the permalinks are set to null in the indexables database table
Fixes #15233

Make the method public

---

package.json
yarn.lock

*
* Bumps JS packages for 14.3 RC.
*
*
Fixes #

Retry bump js packages for 14.3 rc

---

admin/class-meta-columns.php
src/models/indexable.php

* The filters aren't applied the new way which could lead to errors.
* Fixes a bug where the filters `wpseo_metadesc` and `wpseo_title` weren't called with the right argument, which could lead to errors.
* I've only changed the occurences for the columns in the post overview, because the other two places aren't used anymore. For these I will make an separate pull request to deprecate the code.
* I've not added tests for the new parts, because we've a mix between old and modern code. Instead of tests I just made this pull request: https://github.com/Yoast/wordpress-seo/issues/15289 in which I suggest to separate concerns (filtering and adding columns). Test should be written when that issue is about to be fixed by someone.
This PR …

Fixes the filter call

---

deprecated/frontend/abstract-class-deprecated-schema-piece.php
deprecated/frontend/schema/class-schema-article.php
deprecated/frontend/schema/class-schema-author.php
deprecated/frontend/schema/class-schema-breadcrumb.php
deprecated/frontend/schema/class-schema-faq.php
deprecated/frontend/schema/class-schema-howto.php
deprecated/frontend/schema/class-schema-main-image.php
deprecated/frontend/schema/class-schema-organization.php
deprecated/frontend/schema/class-schema-person.php
deprecated/frontend/schema/class-schema-webpage.php
deprecated/frontend/schema/class-schema-website.php

* Schema class property changed from private to public, which breaks BC. This PR fixes that.
* Fixes a bug where a property that was changed from private to public on `WPSEO_Schema_Article` led to to a BC break.
* Removed the class extension, now simply constructing a stable instance and delegating all methods towards it. 
* This pull contains some duplicated code, that's a decision made together with @omarreiss. We done this this because it makes it easier to have BC without having methods become public that doesn't have to be public.
* Add this somewhere (the functions.php, wp-seo.php). This will replace the current schema classes by the deprecated ones 😸 
```
add_filter( …
```

Fixes BC issue with private prop that was made public

---

package.json
yarn.lock

*
* Bumps the monorepo packages for the 14.3 release.
*
*
Fixes #

Bump the version of the monorepo packages

---

package.json
yarn.lock

*
* Bumps JS monorepo packages for 14.3.
*
*
Fixes #

Bump JS monorepo packages

---

css/src/metabox.css
js/src/components/DocumentSidebar.js
js/src/components/PrePublish.js
js/src/containers/DocumentSidebar.js
js/src/containers/PrePublish.js
js/src/edit.js
js/src/redux/selectors/index.js
js/src/redux/selectors/preferences.js

* Fixes three RC bugs that were found by QA
* Fixes a bug where the Yoast SEO panels in the sidebar would be displayed in purple.
* Fixes a bug where disabling both analyses would still show the analysis panel in the documentsidebar and in the prepublish panel.
* Fixes a bug where disabling one analysis would still display both in the panel.
*
* Check that the Purple color in the sidebar is gone
* Disable both analysis, check that the the panel is gone from the documentside bar and from the prepublish panel
* Enable one analysis: check that the prepublish panel and the documentsidebar only show that analysis.
Fixes https://yoast.atlassian.net/browse/QAK-1869

QAK-1869 Fix publish flow bugs

---

js/src/components/RelatedKeyPhrasesModal.js
js/src/components/modals/SemRushLimitReached.js

*
* Adds content for the SEMrush modal dialog for the scenario where the daily request limit has been reached.
* Introduce a simple `SemRushLimitReached` component in the `components/modals` directory
- waiting for the modal to be built, for now you can add this component somewhere in the UI
- for example inside the `KeywordInput` component before the closing `</KeywordInputContainer>`
- import the component at the top of the file: `import SemRushLimitReached from "../modals/SemRushLimitReached";`
- add it in the JSX code: `<SemRushLimitReached />`
- verify the content follows the design provided in the issue
- verify the link of the big yellow button opens in a new browser tab
- …

P3-2 Add SEMrush modal "limit reached" content

---

js/src/wp-seo-indexation.js
src/conditionals/yoast-tools-page-conditional.php
src/integrations/admin/indexation-integration.php
src/presenters/admin/indexation-list-item-presenter.php
src/presenters/admin/indexation-warning-presenter.php
src/routes/indexable-indexation-route.php
tests/conditionals/yoast-tools-page-conditional-test.php
tests/integrations/admin/indexation-integration-test.php
tests/presenters/admin/indexation-list-item-presenter-test.php
tests/presenters/admin/indexation-warning-presenter-test.php

* Free changes needed to make premium work.
* Changes the JS indexation to read it's settings from a data attribute.
* Adds a pre-indexation action to the JS indexation.
* Adds a Yoast's tools page conditional.
* The conditional is not actually used in free, but it makes sense to live here.
* Truncate your indexable table.
* Run the indexation.
* Verify it worked and no errors.
See https://github.com/Yoast/wordpress-seo-premium/pull/2820
Partially fixes https://github.com/Yoast/wordpress-seo-premium/issues/2764

Create prominent words integration

---

admin/class-collapsible-presenter.php
admin/class-paper-presenter.php
admin/views/collapsible.php
admin/views/tabs/metas/archives.php
admin/views/tabs/metas/post-types.php
admin/views/tabs/metas/taxonomies.php
css/src/admin/all.css
css/src/components/collapsible.css

* Change some papers in the search appearance to collapsibles so that the included content has more space.
* Link the monorepo
* Check if the paper looks like the design in sketch mentioned in the issue on Jira
*
*
Fixes https://yoast.atlassian.net/browse/FRO-101

FRO 101 collapsibles admin pages

---

admin/services/class-file-size.php

* Fixed a REST response for a file size request that was 404 on success to be 200.
*
Fixes #

Fix REST response to be 200

---

js/src/components/SettingsReplacementVariableField.js

*
* [@yoast/search-meta-data] Fixes a React error in the development build
*
*
Fixes #15459

Define required property Type on ReplacementVariableEditor

---

admin/class-admin-asset-manager.php
css/src/admin/admin.css

* Remove 404 error css files.
* Remove 404 error css files.
*
* Link the monorepo
* Browse the settings page and check in the console if there are no css 404 errors
Fixes https://yoast.atlassian.net/browse/FRO-119

FRO-119 remove 404 error css files

---

lib/migrations/migration.php

CS: method modifier order

---

inc/class-wpseo-utils.php

CS: use self for in-class references

---

lib/orm.php

CS: no implicit array creation

---

deprecated/frontend/schema/class-schema-person.php

QA: remove unused `use` statement

---

admin/metabox/class-metabox.php
lib/migrations/adapter.php
lib/orm.php
src/repositories/indexable-hierarchy-repository.php

* One argument per line in multi-line function calls.
* Selectively move multi-line function call argument out of the function call.
* _N/A_

CS: formatting of multiline function calls

---

lib/migrations/adapter.php
lib/migrations/table.php

CS: multi-item associative arrays should be multi-line

---

src/config/migrations/20200408101900_AddCollationToTables.php
src/helpers/author-archive-helper.php
src/helpers/language-helper.php
src/initializers/migration-runner.php

QA: use FQN function and constant names

---

lib/migrations/adapter.php
lib/orm.php
src/helpers/author-archive-helper.php

CS: don't use Yoda conditions

---

src/builders/indexable-post-builder.php
src/builders/indexable-social-image-trait.php
tests/builders/indexable-home-page-builder-test.php
tests/generators/open-graph-image-generator-test.php

QA: use WPSEO_Utils::format_json_encode()

---

js/src/components/modals/SemRushLimitReached.js
js/src/components/modals/SemRushLoading.js

*
* Fixes a few occurrences of uppercase R in SEMrush.
*
*
Fixes [P3-47]

P3-47 Fix uppercase R in SEMrush

---

admin/class-admin-asset-manager.php

* In [this commit](https://github.com/Yoast/wordpress-seo/commit/a6b7ab65a5d21b0e4066851f8df6bf2d594cf894), the `-` accidentally got removed from `'src'  => 'api-client' . $flat_version`. This PR restores the `-`.
* Adds a dash, that was accidentally removed in another PR, to a filename in the asset manager.
*
* Build Premium `trunk` and open the WordPress admin dashboard.
* In the console, see that `js/dist/api-client144-RC3.js?ver=14.4-RC3 ` (or another version number) could not be found.
* Merge this branch into Premium `trunk` and rebuild.
* Refresh the dashboard and see no errors in the console.
Fixes #

Add dash to file name

---

package.json
scripts/bump_monorepo_packages.js
yarn.lock

*
* Bumps JS packages for 14.5 RC.
*
*
Fixes #

Bump JS packages for 14.5 RC

---

package.json
yarn.lock

*
* Bumps social metadata forms.
*
*
Fixes #

Bump social metadata forms

---

admin/links/class-link-reindex-dashboard.php
css/src/admin/admin.css
src/presenters/admin/indexation-modal-presenter.php
tests/integrations/admin/indexation-integration-test.php
tests/presenters/admin/indexation-modal-presenter-test.php

* Reintroduce progress-bar css and update is to the new styling.
* Updates the progress-bar in the indexation to the new styling.
* The `Stop indexation` button has also been update to the new styling.
* Pull the `developer` branch of the `javascript` repo
* Link the `monorepo`
* In the `Tools` page under `SEO` click on the `Start processing and speed up your site now` button
* Check if the button and progress-bar are the new styling
Fixes https://yoast.atlassian.net/browse/FRO-125

FRO-125 Add progressbar css and update styling

---

admin/formatter/class-post-metabox-formatter.php

* Encountered one notice and proposed a fix.
`changelog: bugfix`
This PR can be summarized in the following change-log entry:
* Fixed a notice: Trying to access array offset on value of type bool fixed when the plugin is installed on fresh WordPress install.
* The value of return variable was not checked.
* Install the fresh WordPress setup.
* Set WP_DEBUG & WP_DEBUG_DISPLAY to true.
* Open any custom post's page where the feature image box is not available ( In my case it was CartFlows )
* As soon as the page is opened it throws the exception and the error will be displayed.
See: 
- https://share.getcloudapp.com/wbuWe7Qq
- https://share.getcloudapp.com/QwulQ0Ez
Fixes #

Notice: Trying to access array offset on value of type bool fixed

---

composer.json
config/composer/actions.php

Provides an easy way to pick what you want instead of having to go through the composer file to know which options there are.
* Using the check coding standards against the staged or branch files only is much quicker than doing the full run. This context is not known by many people. Introducing the interactive menu provides an easy discovery mechanism to do so.
* Introduces `composer cs` - interactive way to pick which composer coding standards action you want to run.
* N/A
* Use `composer cs` and test out the various options.
* Use `composer cs 1` to quickly execute the first option (works for all options 🙃)
Fixes #

Introduce coding standards interactive composer menu

---

css/src/admin/dashboard.css

* We want the Yoast SEO SVG icon to show on the admin dashboard.
* Fixes a bug where the Yoast SEO SVG icon was not loaded on the admin dashboard.
*
* Visit the WordPress admin dashboard.
* You should not get this `404` error:
```
http://local3.wordpress.test/wp-content/plugins/images/Yoast_SEO_Icon.svg 404 (Not Found)
```
Fixes https://yoast.atlassian.net/browse/QAK-1900

Fixed relative URL to SVG file.

---

admin/views/tabs/metas/paper-content/post-type-content.php
css/src/admin/admin.css

* Updates styling custom post designs in Content types
* N/A (regression)
* Also added missing padding to collapsible headers
* Make sure there is a custom post type with archive enables
* Check if the spacing is correct between the different elements
* Check if the `Breadcrumb settings for "post_type" archive` is a h3
Fixes #

FRO-144 custom post design content types

---

admin/views/partial-notifications-template.php

Restore translatable Hide button

---

css/src/components/sidebar.css

* Fixes the sidebar so it's beside the bulk editor table on desktop.
* Fixes the sidebar so it's beside the bulk editor table on desktop.
* 
* Go to Tools -> Bulk editor and check if the sidebar is beside the table if the browser is bigger than 1200px
Fixes https://yoast.atlassian.net/browse/FRO-154

FRO-154 fix sidebar placement

---

package.json
yarn.lock

*
* Bumps the monorepo packages for 14.5-RC3.
*
*
Fixes #

Bumped monorepo packages for 14.5-RC3.

---

js/src/help-scout-beacon.js

* Moves the help scout icon if the sidebar is set.
* N/A
* N/A
* Check if the help scout icon doesn't overlap the sidebar if it available.
Fixes https://yoast.atlassian.net/browse/FRO-137

FRO-137 Move help scout icon

---

admin/class-meta-columns.php

* Fixes a bug where the SEO title and meta description for posts that have a custom title and/or description would not be displayed in the posts overview.
* Reuses existing code from the meta surface rather than duplicating the context logic.
* Set a custom SEO title and meta description for a post using the snippet editor.
* Go to the posts overview and enable the SEO title and meta description columns in the screen options.
* You should see the title and description you just filled in for your post.
Fixes https://yoast.atlassian.net/browse/QAK-1877

Fix the meta columns for the title and description

---

admin/class-admin-asset-manager.php

* There were some errors on `/network/admin.php`, when visiting the edit files ( `?page=wpseo_files` ) page. I am not sure why this is the only network admin page showing errors, I assume it has to do with it being relatively lightweight and therefore "done" before React is loaded.
I have added `wp-element` (which contains React) and `wp-i18n` (which contains `__` ) as a dependency to the network admin script, which makes sure that those are there before loading the page.
* Fixes an unreleased bug where errors would appear in the console on the Network Admin's Edit Files page.
* 
* Checkout `trunk` and `develop` (on monorepo), and run your multisite docker. Go to the `network admin` …

P1-39 Add wp-element and wp-i18n as dependency to network admin

---

js/src/containers/FacebookEditor.js
js/src/containers/TwitterEditor.js
js/src/redux/reducers/facebookEditor.js
js/src/redux/reducers/twitterEditor.js

* We want to display a message to the users when they select an image that does not match our "requirements".
* Add image validation for the Twitter and Facebook preview.
1. Go the social previews for a post
2. Select an image that is smaller than 200x200
3. See that a warning is displayed that the size is too small (the input field should still be displayed)
4. Also verify for Twitter
*In premium*
1. Go the social previews for a post
2. Select an image that is smaller than 200x200
3. See that a warning is displayed that the size is too small
4. Verify that the preview does use that image
4. Also verify for Twitter
Fixes P1-33

Add image validation to Social previews

---

admin/class-admin-asset-manager.php
admin/class-admin-user-profile.php
css/src/admin/user-profile.css

*
* Restores the styling for the Yoast settings on the User Profile page.
- our form elements on this page use their own HTML that can't be styled with styles provided by WP core
- in fact, this page used to have some styling from `admin-global.css`
- this PR restores a reduced version of the styles that were in `admin-global.css`
- puts the styles in a `user-profile.css` file that is only enqueued on the User Profile page
- go to the User Profile page `wp-admin/profile.php`
- observe the Yoast SEO settings section is styled properly 
- compare with previous version 14.4
- see also the screenshots on the issue https://yoast.atlassian.net/browse/FRO-177 
- don't forget to check the …

FRO-177 Restore Yoast settings styling on the user profile page.

---

admin/class-admin-asset-yoast-components-l10n.php
admin/config-ui/class-configuration-translations.php
admin/formatter/class-metabox-formatter.php
admin/import/plugins/class-import-rankmath.php
admin/tracking/class-tracking-server-data.php
config/dependency-injection/custom-loader.php
integration-tests/inc/test-class-wpseo-upgrade.php
integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-data.php
integration-tests/sitemaps/test-class-wpseo-sitemaps-cache.php
src/integrations/front-end-integration.php

* Fix open technical debt issues in the CS cleanup sheet.
* N/A
*
* The code should work as before, but in general we're not testing CS PR's.
Fixes #

Fix CS in functions

---

package.json

I did some simple tests (using time on my machine) and these were the results:
`yarn start` before: 15,10 seconds
`yarn start` after: 9,54 seconds
Which is a saving of 5 seconds, or 33% of the original startup time.
I did a quick smoketest through the plugin but I was not able to find anything out of the ordinary. No additional warnings or errors were thrown and everything I clicked workes as expected.
* Decrease the time it takes for `yarn start` to be ready.
* Decrease the time it takes for `yarn start` to be ready.
* All JS files were being build twice. This is not necessary since we only need to copy the JS dependencies before building with the webpack dev server. 
* Start the …

P1-49 Decrease the time it takes to run yarn start

---

package.json
yarn.lock

*
* Bumps @yoast/social-metadata-forms.
*
*
Fixes #

Bump @yoast/social-metadata-forms

---

src/conditionals/cron-conditional.php
tests/conditionals/cron-conditional-test.php

*
* Adds a Cron conditional.
*
* I wrote unittests. The conditional is used in a premium PR. So not really needed to test this separately.
Fixes #

Add cron conditional

---

src/helpers/meta-helper.php

* The helper makes it easier to retrieve term meta value.
* N/A - It's needed for use in the premium plugin.
*
* Merge this branch into https://github.com/Yoast/wordpress-seo-premium/pull/2863/ and test it together.

Adds a term_value method

---

src/repositories/indexable-repository.php

*
* Removes an unused method.
* There is another unused method in `indexable-repository`: `find_by_multiple_ids_and_type`. However, I did not remove this method because it already yields results in a google search (see the Slack [discussion](https://yoast.slack.com/archives/C014DJSCXPW/p1594361015008400?thread_ts=1594295327.002300&cid=C014DJSCXPW) about this).
* Do a search in the code to verify that `find_by_indexable_ids` is used nowhere.
Fixes #

Remove an unused method

---

js/src/indexation.js
src/integrations/admin/indexation-integration.php
src/presenters/admin/indexation-modal-presenter.php
tests/integrations/admin/indexation-integration-test.php
tests/presenters/admin/indexation-modal-presenter-test.php

*
* N/A - Makes things more configurable to make it usable for 
*
* Checkout this branch. Build everything
* Reset the indexables and try to calculate these
* Cancel the calculation and start calculating again
* This should still work.
* Also test this with https://github.com/Yoast/wordpress-seo-premium/pull/2876
Fixes [#P2-70](https://yoast.atlassian.net/browse/P2-70)

Prevent conflicts by making ids configurable.

---

admin/class-admin-asset-manager.php
admin/filters/class-abstract-post-filter.php
admin/metabox/class-metabox.php
admin/taxonomy/class-taxonomy.php
css/src/editor/post-overview-global.css

* Remove console errors and align cornerstone notice.
* Remove console errors and align cornerstone notice.
* Also fixes https://yoast.atlassian.net/browse/FRO-187 because it's a similar issue.
* Pull this PR and link the develop branch of the javascript repo
* Check on the cornerstone post/page overview if there is no console error about a missing css file.
* Activate the Classic editor plugin and edit a post. Check if there is no console error about a missing css file.
Fixes https://yoast.atlassian.net/browse/FRO-194, https://yoast.atlassian.net/browse/FRO-187

Fro 194 console error cornerstone overview

---

inc/class-wpseo-utils.php
js/src/admin-global.js

* Cleans up unused code
* Cleaned up unused code.
* Did a search of all our repo's. This isn't used anywhere.
* This code wasn't used. Nothing should be touched.

Cleanup console notifications

---

js/src/components/SnippetPreviewModal.js

* 
* Fixes an unreleased bug where the Google Preview modal would resize when typing a description.
* This problem was really hard to solve in a manner that satisfies all conditions, because the component is re-used in the modal and the metabox. Specifying a width that works in both the modal and metabox, in all viewport sizes, proved problematic.
* I opted to add a div with a fixed width only in the modal, and only for viewport affected by the bug: width >`782px`. This is an ugly but pragmatic solution.
* Verify that bug disappears for mobile Google Preview in the modal
* Verify that other views (metabox, narrow views) are not broken.
Fixes P1-83

Fix jumping Google Preview modal

---

css/src/metabox.css

*
* In some configurations a line could be seen under the active tab in the metabox. This should now occur less.
*
*
Fixes #

Remove clip path because it doesn't work any longer

---

inc/options/class-wpseo-option.php

Context
* Currently if an option is updated to the value it already has the filter that ensures the default value is always set is not added back again. This can cause weird and unpredictable behavior as `false` will be returned while a usable value is expected.
* This will likely not go wrong very often as we're adding the filters back on any option change rather than just relevant option changes however doing it this way does mean we're calling `has_filter` very often, which while not expensive is still more effort than a simple string comparison.
Here is the relevant core code:
https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/option.php#L318
In the `sanitize_option` function our `validate` function is called which removes our default filters. On the `update_option` …

Fixes an issue where default filters were not added back if the option value didn't change

---

src/integrations/third-party/web-stories.php

*
* _N/A_ This is a code-only change and has no effect on functionality.

CS: no yoda conditions

---

lib/orm.php
src/presenters/url-list-presenter.php
src/repositories/indexable-repository.php
tests/helpers/capability-helper-test.php
tests/values/images-test.php

*
* _N/A_ This is a documentation-only change and has no effect on functionality.

Docs: various minor fixes

---

js/src/indexation.js

* When navigation to the tools page from a notice, and 'empty' modal will be shown. This is not handy.
* N/A Fixes a bug where the modals won't get opened
* Decided to use a modal, because it is triggered before the html for it is rendered properly. It seems to fix the issue
* Reset the indexables and make sure the notice is triggered. You probably need to remove the transients as well (if the test helper isn't doing this)
* Go the yoast dashboard and see a notice at the top
* Hit the button and see you are navigated to the tools page and the modal with content is shown.
* Get https://github.com/Yoast/wordpress-seo-premium/pull/2924 merged
Fixes …

Make sure the modal will be opened

---

grunt/custom/github-pre-release.js

*
* Fixes a bug when asking for the QA / GitHub changelog during the automated RC creation process.
*
* Can only be tested when creating another RC.
Fixes #

Fix GitHub pre release asking for changelog

---

src/generators/schema/author.php
src/generators/schema/person.php

*
* Fixes a bug where schema person was output while article is not.
*
* Set site represents to a company (as person will trigger a person graph piece).
* Go to a post and change the article type to none.
* Check the frontend, there will no longer be a person graph piece.
* Set site represents to a person other than the post author.
* Go to the post and change the article type to none.
* Go to the frontend and check the schema:
* There should be a person graph piece for the site represents person.
* There should NOT be a person graph piece for the post author.
* Set site represents to the same person as the posts's author.
* Go to the frontend and check the schema output:
* There …

Fixes schema person being output when article is not

---

js/src/redux/actions/index.js
js/src/redux/actions/postSettingsModal.js
js/src/redux/reducers/index.js
js/src/redux/reducers/postSettingsModal.js
js/src/redux/selectors/index.js
js/src/redux/selectors/postSettingsModal.js
js/tests/redux/actions/postSettingsModal.test.js
js/tests/redux/reducers/postSettingsModal.test.js
js/tests/redux/selectors/postSettingsModal.test.js

* Part of the metabox modal epic.
* Adds an action, reducer and selector for the post settings modal's isOpen.
*
* Go to a post edit page and check out the `yoast-seo/editor` redux state.
* It has a `postSettingsModal` object with a `isOpen` boolean that defaults to false.
* You can dispatch an `WPSEO_POST_SETTINGS_MODAL_SET_IS_OPEN` action with an `isOpen` key to change it (this can be done through the redux browser extension: `Dispatcher` button below the state), e.g.:
```
{
type: 'WPSEO_POST_SETTINGS_MODAL_SET_IS_OPEN',
isOpen: true
}
```
Fixes https://yoast.atlassian.net/browse/P1-101

Add post settings modal redux layer

---

js/src/dashboard-widget.js

*
* Fixes a bug where the Yoast Dashboard widget may trigger an error when other plugins or temporary conditions make the Yoat API response fail.
*
- reproduce the error on trunk:
- install and activate Yoast SEO and JWT Auth https://wordpress.org/plugins/jwt-auth/
- go to the WordPress Dashboard
- see the Yoast widget doesn't show the statistics
- see the JS `TypeError` in your browser's console
- switch to this branch and build
- refresh the WordPress Dashboard page
- see there's no error (and the statistics aren't rendered)
Note: the JWT Auth plugin is only used to easily reproduce the error: the response might fail for any other reason, also temporary reasons.
Fixes [P3-100]

P3-100 Check the Dashboard widget response.

---

package.json
yarn.lock

*
* Updates the `@yoast/grunt-plugin-tasks` dependency.
*
* Remove the local `node_modules` folder.
* Install packages: `yarn install`.
* Check if the grunt tasks still function like `grunt build`.
Fixes #

Update grunt plugin tasks

---

tests/unit/helpers/site-helper-test.php

* The test for the site helper was located in the wrong directory. It was created on a separate branch before the test directory were restructured, so it was added to the wrong directory.
* Moves the test of the site helper to the right directory (from `tests/helpers/` too `tests/unit/helpers/`).
*
* The unit tests should all still pass (e.g. the Travis build should succeed).
Fixes #

Moved site-helper-test.php to its appropriate subfolder.

---

js/src/initializers/term-scraper.js

* In the refactor PR https://github.com/Yoast/wordpress-seo/pull/15735 the `YoastSEO` value is being filled before we get to the term scraper. And we should now check if it already exists.
* Fixes a bug where the classic editor's react components would not be able to load in, e.g. the social previews in premium.
* This is the same change as in the refactor PR for posts: https://github.com/Yoast/wordpress-seo/pull/15735/files#diff-329711a31aab577d442b95d8a8b81475R421
* Test this PR in premium.
* Go to the social tab on an edit term page.
* Before this PR it would not fill in properly. Now they should work fine.
Fixes https://yoast.atlassian.net/browse/P1-124

P1-124 Do not overwrite our YoastSEO global (on terms)

---

admin/class-primary-term-admin.php

*
* Fixes a bug where the primary category would not work.
* There is no `primary-category` script. Therefor, the localization will not every be included. Changed now to `post-edit` and `post-edit-classic` for a quick-fix.
* Ensure you have WP 5.5
* Go to edit a post with multiple categories.
* See that you have a primary category picker.
* Also check with the classic editor plugin active.
Fixes https://yoast.atlassian.net/browse/P1-132

P1-132 Fix primary category

---

package.json
yarn.lock

*
* Bumps the monorepo packages for 14.8 release.
*
*
Fixes #

Bump monorepo packages for 14.8 release

---

package.json
yarn.lock

*
* Bumps the monorepo packages for 14.9-RC1.
*
*
Fixes #

Bump monorepo packages for 14.9-RC1

---

.travis.yml
composer.json
config/composer/actions.php

* Make use of the composer configuration introduced in Premium in https://github.com/Yoast/wordpress-seo-premium/pull/2955
**Process notes**
* This PR needs to be merged before https://github.com/Yoast/wordpress-seo-premium/pull/2955 will pass
* When this PR is merged, https://github.com/Yoast/wordpress-seo-premium/pull/2955 needs to be merged on Premium or otherwise all the builds will fail. So these need to be picked up together.
* Please close https://github.com/Yoast/wordpress-seo-premium/pull/2959 after merging this PR.
* N/A
* Introduced a `$IS_PREMIUM` variable instead of checking for the directory to exist everywhere
* Only running Premium `composer install` for Lint and CS checks in Premium
* Removed all the composer …

Use premium composer for checks

---

js/src/components/RelatedKeyphrasesModalContent.js
js/src/components/SEMrushRelatedKeyphrasesModal.js
js/src/components/SEMrushRelatedKeyphrasesModalContent.js
js/src/components/contentAnalysis/KeywordInput.js
js/src/components/fills/MetaboxFill.js
js/src/components/modals/SEMrushKeyphrasesTable.js
js/src/components/modals/SEMrushLimitReached.js
js/src/components/modals/SEMrushLoading.js
js/src/components/modals/SEMrushMaxRelatedKeyphrases.js
js/src/components/modals/SEMrushRequestFailed.js
js/src/components/modals/SEMrushUpsellAlert.js
js/src/containers/SEMrushRelatedKeyphrases.js
js/src/containers/SEMrushRelatedKeyphrasesModal.js

* Renames files and classes to ensure consistency.
* Renames files and classes to ensure consistency in the spelling of SEMrush.
*
* Check out this branch and build.
* Test the features related to the SEMrush modal and ensure nothing breaks/no console errors are thrown.
Fixes #

Renamed files and classes to ensure consistency

---

config/grunt/task-config/webpack.js

* 
* N/A
* Using the `<%= %>` variable notation makes sure the variable is read on run-time instead of initialization. This prevents the problem of not having the correct version after doing a version bump in the same grunt-sequence (alias progression).
* By using `grunt.config.process`, we make sure that this template variable is parsed to an actual version string, which makes sure that non-grunt scripts can use it (e.g. `webpack.config.js`).
* **Important**: Modify the `bump-rc-version` task to not add, commit and push any changes using git.
* To do this, comment out (or remove) these lines in `config/grunt/tasks/custom-tasks/bump-rc-version.js`:
```js
// Stage the version files. …
```

Fixes the building of the monorepo.css when running grunt artifact.

---

tests/unit/presentations/indexable-date-archive-presentation/presentation-instance-builder-trait.php
tests/unit/presentations/indexable-error-page-presentation/presentation-instance-builder-trait.php
tests/unit/presentations/indexable-home-page-presentation/presentation-instance-builder-trait.php
tests/unit/presentations/indexable-presentation/presentation-instance-builder-trait.php
tests/unit/presentations/indexable-presentation/title-test.php
tests/unit/presentations/indexable-presentation/twitter-description-test.php
tests/unit/presentations/indexable-presentation/twitter-title-test.php
tests/unit/presentations/indexable-search-result-page-presentation/presentation-instance-builder-trait.php
tests/unit/presentations/presentation-instance-dependencies-trait.php
tests/unit/presenters/admin/indexation-list-item-presenter-test.php
tests/unit/presenters/twitter/card-presenter-test.php
tests/unit/presenters/twitter/description-presenter-test.php
tests/unit/presenters/webmaster/baidu-presenter-test.php
tests/unit/presenters/webmaster/bing-presenter-test.php
tests/unit/presenters/webmaster/google-presenter-test.php
tests/unit/presenters/webmaster/pinterest-presenter-test.php
tests/unit/presenters/webmaster/yandex-presenter-test.php
tests/unit/surfaces/meta-surface-test.php
tests/unit/values/images-test.php
tests/unit/values/open-graph/images-test.php

* Added docs to the attributes and removes a couple of duplicate ones.
* N/A - It adds docs

Adds attribute docs.

---

src/integrations/admin/disable-concatenate-scripts-integration.php
tests/unit/integrations/admin/indexation-integration-test.php

* In WordPress 5.5 a core bug introduces JavaScript errors when Gutenberg is installed and concatenate scripts is turned on.
* Temporarily disables concatenate scripts as it was causing JavaScript errors due to a core bug introduced in 5.5.
* This integration can be removed again once the core bugs are fixed.
* Make sure you have `SCRIPT_DEBUG` set to `false`.
* Without this PR you should see scripts being loaded through `load-scripts.php`.
* With this PR that should not happen.
* Install Gutenberg, without this PR you should see console errors.
* With this PR you should not.

Add integration to disable concatenate scripts

---

tests/integration/sitemaps/test-class-wpseo-sitemaps.php

Merges #15838
* Add sitemap_index_links filter
* See other PR

Add wpseo_sitemap_index_links filter (Merge #15838)

---

wp-seo.php

* On September 8th, Woocommerce 4.5 will be released
* Set the WC tested up to version to 4.5 in preparation for the WooCommerce release on September 8th.
*
*
Fixes #

Up WC tested up to to 4.5.0

---

admin/config-ui/fields/class-field-tracking.php
js/src/components/WordPressUserSelector.js
package.json
yarn.lock

This prevents conflicts with the version of React-Select we'll be using in the monorepo
*
* Upgrade react-select to the latest version
* `react-select` in the plugin is only used in the Configuration Wizard for the WordPress User selector and in `Search appearance` settings: General -> Knowledge Graph & Schema.org (but it is the same component).
* Changed the tracking field to return an object instead of an array since this was causing an error from PropTypes.
* Open the Configuration Wizard
* Go to step 3
* Check that the user selector works as expected
* Data is fetched from the remote source
* User can be selected
* etc.
* Make sure that the choices made in the tracking tab (tab …

Upgrade react-select to the latest version

---

js/src/containers/SEMrushRelatedKeyphrases.js
js/src/containers/SEMrushRelatedKeyphrasesModal.js

* Cleans up the notation of the containers to ensure consistency across the code base.
* Cleans up the notation of the containers to ensure consistency across the code base.
* Based on feedback from Joost, I've altered the selector section to also use Object destructuring.
* Ensure you have a token in your database.
* Create a new post or edit an existing one.
* Add a keyphrase and click 'Get related keyphrases'
* Ensure that both the modal and modal content still work as expected and no errors are added to the console.
Fixes #

Cleaned up the containers to use a better notation

---

composer.json
tests/integration/sitemaps/test-class-wpseo-sitemaps.php
tests/unit/builders/indexable-social-image-trait-test.php

No unnecessary double quoted string usage
Includes lowering the threshold.
* _N/A_. This is a code only change and has no effect functionality

CS: no unnecessary double quoted string usage

---

composer.json
src/actions/indexation/abstract-link-indexing-action.php

Fix (function) modifier keyword order.
Includes ~~lowering~~ raising the threshold.
* _N/A_. This is a code only change and has no effect functionality

CS: fix modifier keyword order

---

composer.json
src/config/migrations/20200728095334_AddIndexesForProminentWordsOnIndexables.php
src/surfaces/meta-surface.php
src/values/open-graph/images.php
tests/integration/doubles/wpseo-capability-manager-double.php
tests/unit/helpers/pagination-helper-test.php
tests/unit/integrations/admin/indexation-integration-test.php
tests/unit/repositories/indexable-repository-test.php
tests/unit/surfaces/meta-surface-test.php

*
* _N/A_. This is a code only change and has no effect on functionality.

CS: more whitespace fixes

---

admin/class-admin-init.php
composer.json
lib/orm.php
src/actions/indexation/post-link-indexing-action.php
src/actions/indexation/term-link-indexing-action.php
src/builders/indexable-link-builder.php
src/config/migrations/20200617122511_CreateSEOLinksTable.php
src/routes/link-indexing-route.php
src/surfaces/meta-surface.php
tests/integration/sitemaps/test-class-wpseo-sitemaps.php
tests/unit/actions/indexation/post-link-indexing-action-test.php
tests/unit/actions/indexation/term-link-indexing-action-test.php
tests/unit/builders/indexable-link-builder-test.php
tests/unit/generators/schema-generator-test.php
tests/unit/helpers/pagination-helper-test.php
tests/unit/helpers/url-helper-test.php

Either format them as proper multi-line or rewrite them and move multi-line arguments out of the function call.
Includes making some closures static.
Includes lowering the threshold.
* _N/A_. This is a code only change and has no effect on functionality.

CS: multi-line array and function call fixes

---

js/src/containers/SnippetEditor.js

* Product wants the Edit button removed.
* Removes the "Edit snippet" button from the Snippet Editor.
It might be worth to check if there are any other usages of the `SnippetEditor` that do need the `closeButton,` otherwise it can be removed completely.
That is a bit too much for now, since that would require doing some investigation and doing a major release of the `SnippetEditor` package and we are on a tight schedule.
* Open the modal
* Check that Google Preview is opened
* Check that the "Edit Snippet" button is not present
* Open the Google Preview in the metabox
* Check that the "Edit Snippet" button is not present
Fixes P1-152

Remove the edit button from the Google Preview

---

js/src/components/SEMrushRelatedKeyphrasesModalContent.js
js/src/components/contentAnalysis/KeywordInput.js
js/tests/__mocks__/@wordpress/api-fetch.js
js/tests/__mocks__/@wordpress/components.js
js/tests/__mocks__/@wordpress/url.js
js/tests/components/SEMrushRelatedKeyphrasesModal.test.js
js/tests/components/SEMrushRelatedKeyphrasesModalContent.test.js
js/tests/components/contentAnalysis/KeywordInput.test.js

* Adds tests for SEMrushRelatedKeyphrasesModal and SEMrushRelatedKeyphrasesModalContent
* Adds tests for SEMrushRelatedKeyphrasesModal and SEMrushRelatedKeyphrasesModalContent.
*
* Run tests via `yarn test`.
* Ensure tests pass.
Fixes #

Adds tests for SEMrushRelatedKeyphrasesModal and SEMrushRelatedKeyphrasesModalContent

---

release-info.json

*
* add 14.9 notification
*
*
Fixes #

We've added the 14.9 notification

---

admin/views/sidebar.php

* Escape a URL for output in HTML.
* _N/A_. This is a code only change and has no effect on functionality.

QA: add output escaping

---

inc/options/class-wpseo-option.php

This documentation has a function, but the way it was written would cause violations.
By rewriting the documentation in a slightly different format, the documentation can remain without it throwing errors.
* _N/A_. This is a docs only change and has no effect on functionality.

Docs: clean up some code documentation

---

src/helpers/language-helper.php

*  Let Free users see an upsell notification that promotes Premium word form recognition.
* Activate word form recognition upsell banner for Arabic users.
*
* Set the languages of your website to Arabic.
* Check that you are seeing a morphology upsell. (See [this PR](https://github.com/Yoast/wordpress-seo/pull/15322) and the picture below for what the upsell looks like.)
Fixes https://yoast.atlassian.net/browse/LIN-565

Add Arabic to languages with word form support

---

src/config/migrations/20171228151840_WpYoastIndexable.php
src/config/migrations/20191011111109_WpYoastIndexableHierarchy.php

* Reformat function calls in migrations for multi-line associative arrays.
* _N/A_ this is a code layout only change and does not affect functionality.

CS: fixes for config/migrations

---

js/src/components/SEMrushRelatedKeyphrasesModal.js
js/src/components/modals/SEMrushCountrySelector.js

* Replaces internally linked components, with their exposed counterparts.
* Replaces internally linked ErrorBoundary and FieldGroup components, with their exposed counterparts.
*
* Ensure you have a valid SEMrush token present in your database.
* Add a new post or edit an existing one.
* Add a keyphrase and click 'Get related keyphrases'. See that the modal opens and all expected components are present.
* Refresh post.
* Ensure that the keyphrase is still present (if not, add it again) and click 'Get related keyphrases'. See that the modal opens and all expected components are still present.
* Ensure the console doesn't display any errors related to …

Replaces internally linked components, with their exposed counterparts

---

release-info.json

*
* Add release notification for free Yoast SEO 15.0
*
*
Fixes #

Update release notification for free 15.0

---

tests/unit/doubles/routes/abstract-indexation-route-mock.php

*
* Fixes one warning to make Travis pass again.
*
*
Fixes #

Remove comment to avoid warning about commented out code

---

.travis.yml

* As PRs that touch lines in a large file will trigger CS errors and warnings for that entire file. This is cluttering the usefulness of the checks as ignores must be added or PRs need to be merged that are failing the checks.
* N/A
* N/A
* See Travis pass
Fixes #

Remove check-branch-cs check from Travis conditions

---

admin/views/tabs/metas/paper-content/general/homepage.php

* Change the incorrect wording of "frontpage" to "posts page" in our settings.
* Change the incorrect wording of "frontpage" and "blog page"  to "posts page" in our settings.
* N/A, only copy changes.
1. Set a static home and posts page in WordPress' settings -> Reading
1. Check the SEO - Search Appearance page, it should now read:
- Title: `Homepage & Posts page`
- 1st paragraph: `front page` = `homepage`
- 2nd paragraph: `blog page` = `posts page`
Instead of

Change wording of frontpage to posts page in SEO - Search Appearance

---

src/presenters/admin/link-count-indexing-modal-presenter.php

*
* Fixes a bug where clicking on the 'Stop counting' button when using the text link counter on the tools page did not work.
*
* Make sure that you have uncounted links in your text.
* For example by resetting the link counts using the Yoast Test Helper plugin.
* Navigate to Yoast SEO tools page (_SEO_ > _Tools_ in the admin sidebar).
* Click on the button marked _Count links in your text_.
* A modal should pop up. Let the indexing process run for a few seconds.
* Click on the button marked _Stop counting_ in the modal.
* The modal should close and the page should reload.
* Click the _Count links in your text_ again.
* The indexing process should work as expected.
Fixes #

Added missing class to "stop link counting" button in modal.

---

src/builders/indexable-builder.php
src/integrations/watchers/indexable-ancestor-watcher.php
tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php

* Indexables had their hierarchy calculated before being saved, however the hierarchy needs an ID which didn't exist yet as it hadn't been saved yet.
* Fixes indexable hierarchies not being created during bulk indexing.
* Also makes a few changes in the ancestor watcher to ensure faulty queries are never made.
* Table names are also no longer sanitized as entering quotes around them causes MySQL errors.
* Has already been tested by @Djennez 
Fixes https://github.com/Yoast/wordpress-seo/issues/16048
Fixes https://github.com/Yoast/wordpress-seo/issues/16047

Fix indexable hierarchy errors during indexing

---

composer.json
src/actions/semrush/semrush-login-action.php
src/actions/semrush/semrush-options-action.php
src/actions/semrush/semrush-phrases-action.php
src/config/semrush-client.php
src/exceptions/semrush/tokens/empty-property-exception.php
src/exceptions/semrush/tokens/empty-token-exception.php
src/exceptions/semrush/tokens/failed-storage-exception.php
src/routes/semrush-route.php
src/values/semrush/semrush-token.php
tests/unit/routes/semrush-route-test.php

* Fixed several CS warnings and temporarily upped the warning threshold to ensure our branch will pass.
* Fixed several CS warnings and temporarily upped the warning threshold.
* Had to up the warning threshold as a solution that was proposed to solve CS errors, now results in CS warnings. This means we're kind of in limbo at the moment.
* Checkout this branch and run `composer check-cs-thresholds`.
* Ensure the thresholds aren't surpassed.
* Ensure Travis passes.
Fixes #

Fixed several CS warnings and temporarily upped the warning threshold

---

composer.json
src/presentations/indexable-post-type-presentation.php

*
* Replaces inheritDoc comments with a copy from the extended class.
*
*
Fixes #

Replace inheritDoc comments

---

composer.json
src/presentations/indexable-author-archive-presentation.php
src/presentations/indexable-date-archive-presentation.php
src/presentations/indexable-error-page-presentation.php
src/presentations/indexable-home-page-presentation.php
src/presentations/indexable-post-type-archive-presentation.php
src/presentations/indexable-search-result-page-presentation.php
src/presentations/indexable-static-home-page-presentation.php
src/presentations/indexable-static-posts-page-presentation.php
src/presentations/indexable-term-archive-presentation.php
src/presenters/url-list-presenter.php

* WPSEO CS Cleanup.
* Fix docs CS.
*
*
Fixes #

Fix docs CS

---

composer.json
src/integrations/front-end/backwards-compatibility.php
src/integrations/front-end/category-term-description.php
src/integrations/front-end/comment-link-fixer.php
src/integrations/front-end/force-rewrite-title.php
src/integrations/front-end/handle-404.php
src/integrations/front-end/indexing-controls.php
src/integrations/front-end/open-graph-oembed.php
src/integrations/front-end/redirects.php
src/integrations/front-end/rss-footer-embed.php
src/integrations/front-end/theme-titles.php
src/integrations/third-party/amp.php
src/integrations/third-party/bbpress.php
src/integrations/third-party/jetpack.php
src/integrations/third-party/web-stories.php
src/integrations/third-party/woocommerce.php
src/integrations/third-party/wpml.php
tests/unit/integrations/front-end/comment-link-fixer-test.php
tests/unit/integrations/front-end/force-rewrite-title-test.php
tests/unit/integrations/front-end/handle-404-test.php
tests/unit/integrations/front-end/open-graph-oembed-test.php
tests/unit/integrations/front-end/theme-titles-test.php
tests/unit/integrations/third-party/amp-test.php
tests/unit/integrations/third-party/bbpress-test.php
tests/unit/integrations/third-party/jetpack-test.php
tests/unit/integrations/third-party/web-stories-test.php
tests/unit/integrations/third-party/woocommerce-test.php
tests/unit/integrations/third-party/wpml-test.php

*
* Replaces inheritDoc comments with a copy from the extended class.
*
*
Fixes #

Fix inheritDoc in integrations/front-end and integrations/third-party

---

src/actions/semrush/semrush-phrases-action.php
tests/unit/actions/semrush/semrush-phrases-action-test.php

* Changed the endpoint to use SEMrush's broad search instead of related keyphrase search, to get better results.
* Changed the endpoint to use SEMrush's broad search instead of related keyphrase search.
*
* Ensure you've checked out this branch and have built it.
* Create a new post or edit an existing one.
* Enter a keyphrase and click 'Get related keyphrases'.
* If no valid token is found, you'll get prompted with the SEMrush login screen. Login and proceed.
* The modal pops up with a list of related results, sorted by volume.
Fixes [P3-163]

Changed the endpoint to use broad search

---

config/composer/actions.php

* Remove CS summary report to remove clutter from Travis.
* N/A
* N/A
* N/A
Fixes #

Remove CS summary output

---

js/src/components/modals/SEMrushCountrySelector.js
js/tests/components/SEMrushCountrySelector.test.js

* We want to change the text of the gray button, currently holding "Change Country" to "Select country".
* Fixes the button and updates a test description
* Also updated a test description
* Checkout trunk and build
* Create a post, enter a keyphrase and hit the "Get related keyphrases" button
* Make sure the button next to the select holds the content: "Change Country*
* Checkout this branch and build
* Go to the same post, enter a keyphrase and hit the "Get related keyphrases" button
* Make sure the button next to the select holds the content: "Select country"
* Make sure that everything still works as expected

Change semrush country select button content

---

js/src/components/modals/SEMrushKeyphrasesTable.js

* We want to remove the bottom margin of the get more insights link because it does not match the design.
* Removes the margin from the get more insights semrush link
* 
- Checkout trunk and build
- Create a post, enter a keyphrase and hit the "Get related keyphrases" button
- Make sure the `<p>` element of the get more insights link at the bottom has a top and bottom margin 
- Make sure the output looks like the following:
- Checkout this branch and build
- Go to the same post, enter a keyphrase and hit the "Get related keyphrases" button
- Make sure the `<p>` element of the get more insights link at the bottom has no bottom margin 
- Make sure the output looks like the following: …

Remove bottom margin of semrush insights link

---

config/composer/actions.php

* `check-branch-cs` was only showing errors, warnings are just as important!
* N/A
* N/A
* Run `composer cs 2` or `composer check-branch-cs` on a branch with errors and warnings and see both being output
Fixes #

Also output warnings on `composer check-branch-cs`

---

README.md

* We have 2 watch tasks that are useful in active development. Mention these in the README.
* Adds the watch tasks to the readme.
*
* Read the changes. Does it make sense?
Fixes #

Mention watch tasks in readme

---

admin/views/tabs/dashboard/integrations.php

*
* Updates the copy on the integrations page.
*
* See https://yoast.atlassian.net/browse/QAK-2283
Fixes https://yoast.atlassian.net/browse/QAK-2283

[QAK-2283] Update integration copy

---

js/src/components/modals/SEMrushLoading.js

*
* Improves the wording in the message about connecting to SEmrush
*
* See https://yoast.atlassian.net/browse/QAK-2287
Fixes https://yoast.atlassian.net/browse/QAK-2287

Improve wording of SEMrush connection message

---

readme.txt
wp-seo-main.php

* In https://github.com/Yoast/wordpress-seo/pull/15908, functionality was added to show the compatibility with WordPress versions of Premium and the addons. 
For plugins that are on the WordPress repository, the compatibility information doesn't have to be updated:
> “Tested up to – The version of WordPress that the plugin has been tested against. This field ignores minor versions, as plugins shouldn’t break with a minor update. This means a plugin only need to define the major version it is tested against and **the WordPress.org plugin directory will automatically add the minor version**. This should be numbers only, so ‘4.9’ and not ‘WP 4.9’. 
From https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/
However, for Premium and the addons that depend on the …

Update WP tested up to version

---

js/src/components/modals/SeoAnalysisModal.js

* In https://github.com/Yoast/wordpress-seo/pull/15368 it was intented to add the icon to the modal. However, this Icon was explicitly not set in our modal rewrite https://github.com/Yoast/wordpress-seo/pull/15876 
* Fixes a bug where the Yoast icon got removed from the Add synonyms/related keyphrase modals.
*
* Create/edit a post
* Scroll down to the metabox or open the sidebar and open the SEO analysis tab
* Click on + Add synonyms / + Add related keyphrase
* Verify that the modals now have an icon: 
Fixes https://yoast.atlassian.net/browse/P1-201

P1-201 Add Yoast icon to SEO modals

---

js/src/components/SEMrushRelatedKeyphrasesModal.js
js/src/components/modals/SEMrushCountrySelector.js
js/src/indexation.js
js/tests/components/SEMrushCountrySelector.test.js

* The team that is releasing is experiencing a lot of bugs due to faulty imports:
Our developers want to use the new button, but they cannot because it is similarly named to the old button.
So naturally, they try a direct import
```javascript
import { Button } from "@yoast/components/src/button/Button.js";
```
but that does not work when you do not have a linked monorepo.
A quick fix would be to just export the button/Button under an alias. At a later point, we should replace the older buttons by the new ones.
* Allows importing of the new React Button via the NewButton alias.
* See context
* Test in premium: https://github.com/Yoast/wordpress-seo-premium/pull/3021
Fixes P1-202

Use new alias imports for the new Buttons

---

js/src/components/AdvancedSettings.js
js/src/components/CollapsibleCornerstone.js
js/src/components/SchemaTab.js
js/src/components/contexts/location.js
js/src/components/modals/editorModals/FacebookPreviewModal.js
js/src/components/modals/editorModals/TwitterPreviewModal.js
js/src/components/social/FacebookWrapper.js
js/src/components/social/SocialForm.js
js/src/components/social/TwitterWrapper.js
js/src/containers/CollapsibleCornerstone.js
js/src/containers/FacebookEditor.js
js/src/containers/SchemaTab.js
js/src/containers/SnippetEditor.js
js/src/containers/TwitterEditor.js
js/src/helpers/withLocation.js
js/src/redux/selectors/cornerstoneContent.js
js/src/redux/selectors/index.js

*
* Refactors IDs to use location.
* Removed the unique ID because we can not reliably know what it will be. We should ensure the ID to be unique ourselves.
* See test instructions on premium: https://github.com/Yoast/wordpress-seo-premium/pull/3022
* Only the social previews would need to be checked separately in free, as those are different.
Fixes https://yoast.atlassian.net/browse/P1-190

P1-190 add ids

---

admin/views/class-yoast-feature-toggles.php
admin/views/class-yoast-integration-toggles.php

* Moves the Ryte feature toggle to the Integrations tab.
* Moves the Ryte feature toggle to the Integrations tab.
*
* Navigate to SEO -> General.
* Go to the Features tab. Notice that the Ryte integration toggle is gone.
* Go to the Integrations tab. Notice that the Ryte integration toggle is there.
* Change the value of the toggle and save.
* In your database, check the `wp_options` table and search for the `wpseo` option name.
* In the value of this option, search for the `ryte_indexability` property and make sure it has the proper value (i.e. `b:0;` if you've turned Ryte off)
Fixes [P3-189]

Moved Ryte feature toggle to the integrations tab

---

js/src/components/Indexation.js
js/src/indexation.js
js/tests/indexation.test.js

*
* Unit test for Indexation component.
* Moved component to separate file.
*
Fixes #

Added unit-tests for Indexation component

---

admin/views/tabs/network/general.php
package.json
wp-seo-main.php
wp-seo.php

* The SEO → General tab in the network admin is missing a top margin. See attached image.
* Fixes styling of the General tab in the Network admin dashboard
*
build, visit the Network admin dahboard, then SEO → General and observe the result:
Fixes [P3-195]

P3-195 Add margins to content in network admin SEO general tab

---

composer.json
phpcs.xml.dist
src/conditionals/the-events-calendar-conditional.php
src/generators/schema/third-party/events-calendar-schema.php
src/integrations/third-party/the-events-calendar.php

Replaces https://github.com/Yoast/wordpress-seo/pull/15893
This plugin adds a the business logic of this plugin: https://de.wordpress.org/plugins/wpmyte/
The purpose of the code added is to provide a tighter integration of the schema code by 'The Events Calendar'. It transforms the schema code generated by TEC and puts it into a Schema_Piece.
* Added Open Graph integration for `The Events Calendar`.
* Install `The Events Calendar`
* Create a custom event
* Watch the month view for that event
* The Open Graph json object should now have a representation for that event
* Watch the single view for that event
* The Open Graph json object should now have a representation for that event

Luehrsenheinrich integration/wpm the events calendar

---

src/integrations/admin/indexing-indexables-integration.php
src/integrations/admin/indexing-integration.php
src/integrations/indexing-interface.php
tests/unit/integrations/admin/indexing-indexables-integration-test.php
tests/unit/integrations/admin/indexing-integration-test.php

* When integrating with the current indexing algorithm some things went wrong. For example when there are prominent words but no indexable the code had logic to calculate them in the background when the total amount of it is less than 25. 
* N/A - Makes the indexation more robust.
* Introduces a new indexation interface
* 🚨   **Is needed for** https://github.com/Yoast/wordpress-seo-premium/pull/3025
* Reset the indexables (with the test helper) and make sure everything still get indexed.
Fixes #

Have a main class to attach the indexations to.

---

tests/unit/integrations/admin/indexing-notification-integration-test.php

*
* N/A - Fixes two failing unit tests on the release branch.
*
* Check that Travis passes.
Fixes #

Fix two failing unit tests on the release branch

---

admin/tracking/class-tracking-settings-data.php
admin/views/class-yoast-feature-toggles.php
inc/options/class-wpseo-option-wpseo.php

* We want to add an option (to be tracked) + the related feature toggle fot the upcoming "Enhanced Slack sharing" feature.
* Adds a toggle for the "Enhanced Slack sharing" feature
*
* build
* visit SEO→General, "Feature" tab, and see that there is a new toggle at the bottom of the list:
* inspect the `wpseo` array of options in the DB: since the option has just been added, there is no value set for `enable_enhanced_slack_sharing` so it will be taken from the default in the code (value `true`)
* to test this, edit `/admin/class-admin.php`, and at the end of the constructor (should be line 121) add the following lines:
```
echo …
```

P3-206 add settings toggle for enhanced slack sharing

---

src/integrations/admin/indexing-tool-integration.php

*
* Fixes a bug where the wrong endpoint was called.
*
* On the release branch
*  Reset everything
* Run the indexing of the seo data one the tools page
* Refresh the page
* The indexing button will remain visible
* Index the data
* Refresh page and see that the button is hidden.
Fixes #

Also index the links for terms

---

src/actions/indexing/post-link-indexing-action.php
tests/unit/actions/indexation/post-link-indexing-action-test.php
tests/unit/integrations/admin/indexing-integration-test.php

P2-435 Treat old SEO links as unindexed

---

release-info.json

*
* add release notification
*
*
Fixes #

add notification

---

js/src/initializers/admin.js

* We want to avoid a JS error related to ClipboardJS.
* Fixes a bug where ClipboardJS is undefined on the Free plugin.
- for the Zapier integration we added the ClipboardJS script that is used in the Integrations tab
- the relevant JS is in the admin.js file because there are no suitable files in the premium directory where to add this script
- however, the Zapier integration is a Premium only feature so the ClipboardJS is enqueued only on Premium (and only when the feature flag is set to true)
- this PR avoids a JS error due to ClipboardJS being undefined by just checking for it in the JS part
- moved the code to a separate function to make ESLint happy (it was ranting for too many statements within the document ready anonymous …

P3-227 Check whether ClipboardJS is defined before using it.

---

css/src/modal.css

* The replacement variable drop-down for the descriptions in all previews was hidden.
* Fixes a bug where the replacement variable dropdown menu was hidden for the description fields in all preview modals.
* Added the flex-grow to the container so that it stretches with the modal, and removed duplicate CSS that was likely introduced due to a faulty merge.
* Test the preview modals (Google Preview, Twitter Preview, Facebook Preview) and verify that the replacement variable dropdown is fully visible in all input fields.
* Pay some extra attention to the padding and top border of the modal content (see code comments below). They are expected to be unchanged.
* Verify that the SEMrush …

Fix hidden replacement variable drop-down

---

src/commands/index-command.php
tests/unit/commands/index-command-test.php

* Clear specific transients to make sure `--reindex` via the commandline works as intended.
* Fixes a bug where reindexing via WP-CLI did not always repopulate the indexables tables.
* I will still need confirmation if calling the transient names like this is the correct way to move forward.
1. Install Yoast 14.9
1. Run the WP-CLI command `wp yoast index --reindex` once, see it will probably correctly reindex.
1. Run it again and see it will not run properly.
Install this fix and perform the same steps. Notice it should now properly run again.
Fixes https://yoast.atlassian.net/browse/QAK-2265

Fix wp-cli --reindex not repopulating the tables

---

inc/class-upgrade.php
src/helpers/indexing-helper.php
src/integrations/admin/background-indexing-integration.php
src/integrations/admin/indexing-notification-integration.php
src/integrations/admin/indexing-tool-integration.php
tests/unit/helpers/indexing-helper-test.php
tests/unit/integrations/admin/background-indexing-integration-test.php
tests/unit/integrations/admin/cron-integration-test.php
tests/unit/integrations/admin/indexing-notification-integration-test.php
tests/unit/integrations/admin/indexing-tool-integration-test.php

* We want to have one method that does the calculation.
* Optimizes the code to have one method for retrieving the unindexed count.
*
* Reset everything (indexables + prominent words)
* Verify that the notification for indexing SEO data is given.
* Verify that the indexing process still works
* Now remove between the 5 and 20 indexables and verify that these are calculated in the background.
* In the test helper set the plugin version to something below 14.5 and verify that the update routine works / won't give errors.
* Merge this pull request in a temporary premium branch 
* It should also work for the prominent words
* A notification should be visible
* A button to index in the …

P2 423 extract method to helper

---

src/presenters/slack/enhanced-data-presenter.php

*
* Renames the enhanced Slack data filter and adds documentation to it.
*
* refer to https://github.com/Yoast/wordpress-seo/pull/16183 for testing
Fixes #

Rename filter and add documentation

---

readme.txt

* Iris, Jessie and Jono improved the readme.txt text.
* Updates the readme.txt text
*
* N/A
Fixes #

Update readme.txt text

---

.github/PULL_REQUEST_TEMPLATE.md

* Sometimes there is a difference between the steps the acceptance tester needs to take, and the steps QA needs to take during RC testing. Until now, there was no clear way to indicate that.
* Sometimes PRs have a bigger impact than is suggested in the user-facing changes. In such cases,
additional (regression) testing might be necessary. Until now, there was no clear way to indicate that.
* Update PR template
* N/A
* N/A
Fixes #

Add QA specific steps and impact check to PR template

---

admin/class-admin-asset-manager.php
css/src/elementor.css
js/src/initializers/elementor-editor-integration.js
src/integrations/third-party/elementor.php

* On the prototype branch we've put our integration next to the "Elements" and "Global" tabs. Elementor has requested we put our integration in a Tab on the page settings panel (when you click the lower-left gear icon).
* Adds the Yoast SEO sidebar in Elementor's post-settings panel.
* Elementor has requested us to add our plugin on the post-settings panel, in stead of hacking it into the main view. We have followed the example set out in their `elementor/elementor-hello-world` plugin. However, the Elementor controls API is a bit too narrow for our purposes, so we overwrite the `yoast-tab` route to show our React root.
* Checkout branch and build all the things.
* In an Elementor …

Move Elementor integration to settings tab area

---

package.json
yarn.lock

*
* Bump yoast-components
*
*
*
*
Fixes #

Bump yoast-components

---

config/grunt/task-config/notify-slack.js

* [This commit](https://github.com/Yoast/wordpress-seo/pull/16237/files) didn't yet have the desired effect.
* Fixes the ping to the plugin testers and the product team when an RC is announced in the #test channel.
* See https://api.slack.com/reference/surfaces/formatting#mentioning-groups.
via the user / group browser the team Ids can be retrieved; S014S9W185T and S01CRBFCFAS.
* Create an RC through the automatization, see that the pings work as expected.
* N/A this change only has any effect when creating RC's. 
*
Fixes #

Provide the group ID to ping the testers and the product team

---

js/src/helpers/ajaxHelper.js

*
* Adds an ajax helper for performing ajax-requests using promises.
*
* Test in conjunction with https://github.com/Yoast/wordpress-seo-premium/pull/3070.
*
*
Fixes #

Added ajax helper to aid in testing.

---

wp-seo.php

*
* Update WC tested up to version to 4.7
*
* Don't see warnings about not tested versions
*
*
Fixes #

Update WC tested up to version to 4.7

---

js/src/components/Indexation.js
js/tests/indexation.test.js
src/integrations/watchers/indexable-post-watcher.php
tests/unit/integrations/watchers/indexable-post-watcher-test.php

*
* Fixes a bug where the SEO optimization process sometimes had to be run twice before everything was correctly indexed.
* Refactored the `Indexation` component.
* Made the state of the tool (idle, in progress, errored , completed) more apparent and how the tool looks based on this state.
* Simplified the `render` method of the component by splitting it into multiple methods.
* The indexing process itself is now considered the 'source of truth' for when the 'Indexing completed' message is shown.
* This makes sure that it is only shown when the 'complete' endpoint has been called.
* Reset the indexable tables and migrations using the test helper.
* Run the SEO …

P2 510 seo optimization runs several times on clean install

---

css/src/elementor.css
js/src/initializers/elementor-editor-integration.js

Draft status due to styling on the menu item still needing to be done, it currently has no icon.
* Make Yoast SEO more easily findable in the elementor integration
* Adds a Yoast SEO option to the elementor menu to easily navigate to the Yoast SEO sidebar.
* Open a post in elementor.
* Open the hamburger menu in the top left corner.
* There should be a Yoast SEO option.
* Click on it.
* You should navigate to the Yoast sidebar.
* The initialization of th elementor integration. No console errors should occur on load or when clicking the menu item.
Fixes …

P1 231 add elementor menu item

---

js/src/components/SettingsReplacementVariableEditors.js
js/src/elementor/components/fills/ElementorFill.js
js/src/elementor/containers/ElementorFill.js
js/src/elementor/containers/SnippetEditor.js
js/tests/redux/actions/cornerstoneContent.test.js
js/tests/redux/reducers/analysisData.test.js
js/tests/redux/reducers/cornerstoneContent.test.js
js/tests/redux/reducers/snippetEditor.test.js

* Some unfixed errors snuck onto feature branch which makes Travis checks on new branches useless. This remedies that.
* Codestyle fixes.
* Disabled complexity for reducers. I know at some point we want to clean these up, but the switch/case nature of reducers causes them to grow in complexity quickly, without that complexity being... complex. So I just disabled the rule for the new files.
* Run `yarn test` and `grunt eslint`.
Can't test in RC, the errors that are fixed are at build time.
* N/A
Fixes P1-229

Fix errors that snuck onto feature branch

---

js/src/helpers/fields/AnalysisFields.js
src/integrations/third-party/elementor.php

* Advanced Fields were not saving
* Fixes an unreleased bug where the Advanced settings were not saved in Elementor.
* N/A
* Load a post in Elementor
* Change some settings in the Advanced collapsible and remember them.
* Reload.
* Verify that the settings are the ones you set.
* Do the same for the social tab.
*
*
Fixes P1-234

Fix saving advanced and social fields

---

config/dependency-injection/interface-injection-pass.php
config/dependency-injection/util/constructor-details.php
src/actions/semrush/semrush-options-action.php
src/builders/indexable-post-builder.php
src/deprecated/src/actions/indexing/indexable-prepare-indexation-action.php
src/generators/schema/third-party/events-calendar-schema.php
src/integrations/admin/link-count-columns-integration.php
src/integrations/schema-blocks.php
src/presenters/admin/meta-fields-presenter.php
tests/unit/config/semrush-client-test.php
tests/unit/generators/schema-generator-test.php
tests/unit/inc/sitemaps/sitemaps-admin-test.php
tests/unit/integrations/admin/indexing-notification-integration-test.php
tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
tests/unit/integrations/watchers/indexable-post-watcher-test.php
tests/unit/presentations/presentation-instance-dependencies-trait.php
tests/unit/presenters/slack/enhanced-data-presenter-test.php

* Always import classes  with a `use` statement in namespaced files.
* _N/A_ This PR does not contain functional changes.

QA: always import classes

---

src/integrations/third-party/elementor.php

* Article Type dropdown in the Schema Tab/Collapsible should not be shown on Pages.
* Fixes an unreleased bug where the Article Type dropdown was erroneously visible on Pages in the Elementor editor.
* Type defaulted to "post" because it was not passed.
* Edit a Page in Elementor. Open the Schema collapsible. There should only be a Page Type dropdown.
Fixes P1-246

Fix Article schema being shown on Pages

---

composer.json
tests/unit/database/migration-status-test.php
tests/unit/doubles/builders/indexable-post-builder-double.php
tests/unit/doubles/builders/indexable-term-builder-double.php
tests/unit/doubles/builders/primary-term-builder-double.php
tests/unit/doubles/context/meta-tags-context-mock.php
tests/unit/doubles/database/migration-double.php
tests/unit/doubles/generators/schema/article-double.php
tests/unit/doubles/generators/schema/author-mock.php
tests/unit/doubles/integrations/watchers/indexable-post-watcher-double.php
tests/unit/doubles/models/indexable-double.php
tests/unit/doubles/presentations/abstract-presentation-mock.php
tests/unit/helpers/image-helper-test.php
tests/unit/helpers/open-graph/image-helper-test.php
tests/unit/helpers/options-helper-test.php
tests/unit/helpers/product-helper-test.php
tests/unit/helpers/schema/id-helper-test.php
tests/unit/helpers/taxonomy-helper-test.php
tests/unit/helpers/user-helper-test.php

* More quality, less CS errors
* It just adds docs to tests
* 
* N/A - It just adds docs.
*
*
Fixes #

Added docs

---

composer.json
src/repositories/primary-term-repository.php
src/routes/indexables-head-route.php
src/routes/yoast-head-rest-field.php
src/surfaces/meta-surface.php
src/surfaces/values/meta.php
src/values/open-graph/images.php
tests/unit/actions/indexables/indexable-head-action-test.php
tests/unit/actions/indexing/indexable-general-indexation-action-test.php
tests/unit/actions/indexing/indexable-post-indexation-action-test.php
tests/unit/actions/indexing/indexable-term-indexation-action-test.php
tests/unit/builders/indexable-author-builder-test.php
tests/unit/builders/indexable-home-page-builder-test.php
tests/unit/builders/primary-term-builder-test.php
tests/unit/conditionals/yoast-admin-and-dashboard-conditional-test.php
tests/unit/conditionals/yoast-tools-page-conditional-test.php

*
* Adds missing docs.
*
* N/A.
*
*
Fixes #

Fix CS docs in free

---

composer.json
config/composer/actions.php
config/composer/unit-test-generator.php
tests/unit/helpers/indexable-helper-test.php

*
* Introduces a composer command to generate a unit test.
*
* Pick a class in the `src` folder for which a unit test already exists.
* Note down its fully qualified class name (e.g. `Yoast\WP\SEO\Integrations\Admin\Background_Indexing_Integration`).
* Run `composer generate-unit-test 'Fully\Qualified\ClassName'` in the root folder of the plugin.
* Note the quotation marks around the fully qualified class name, they are necessary.
* You should see an error saying that a unit test already exists for this class.
* Remove that unit test (only for testing).
* Run the unit test generation command again.
* A new unit test should have been created.
* Check if this unit test...
* …

Unit test creator

---

js/src/structured-data-blocks/faq/components/FAQ.js
js/src/structured-data-blocks/faq/components/Question.js
js/src/structured-data-blocks/how-to/components/HowTo.js
js/src/structured-data-blocks/how-to/components/HowToStep.js

* We want our structured data blocks (How-to and FAQ) to work properly in latest Gutenberg version that will be released with WordPress 5.6. 
* Fixes a bug where the How-to and FAQ blocks didn't display the formatting controls in their toolbars and didn't set focus on their input fields.
*
Note: although the issues QAK-2361 and QAK-2362 refer to Premium, the How-to and FAQ blocks are on Free and need to be fixed on Free.
- **test on both WordPress 5.6 trunk and WordPress 5.5**
- create a post in Gutenberg
- add a How-to block
- when the block is added, observe that focus goes to the How-to description
- click the step title and check focus is actually set on the step …

QAK-2361 QAK-2362 Fix How to and FAQ blocks focus

---

src/presentations/indexable-post-type-presentation.php
src/presenters/slack/enhanced-data-presenter.php
tests/unit/presentations/indexable-post-type-presentation/open-graph-article-author-test.php
tests/unit/presentations/indexable-post-type-presentation/twitter-creator-test.php
tests/unit/presenters/slack/enhanced-data-presenter-test.php

* On pages and other non-post post types you might not want the author shown in the metadata, so we're removing it.
* Check the twitter:creator, article:author and enhanced slack integration meta data, see that on pages there is no author shown, on posts there is.
*
*
Fixes QAK-2266

Don't output author on non post post-types

---

release-info.json

* Add release notification
* Add release notification
* 
*
*
*
Fixes #

Add release notification

---

tests/unit/helpers/language-helper-test.php

* Adds missing languages with function word and morphology support to the unit tests of the language helper which checks whether a given language has morphology/function word support.
* Adds missing languages with word form and function word support to the language helper unit tests.
*
*
* This PR only makes changes to unit tests, so it does not need to be tested.
*
Fixes #

Add missing languages to the language helper tests

---

inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-option-wpseo.php

* It should be possible to disable the Enhanced Slack Sharing feature at network level on multisite
* Allows network disabling of the Enhanced Slack Sharing feature.
*
* Build and network-activate the plugin on multisite 
* visit the network Dashboard
* visit SEO → General and observe the Enhanced Slack Sharing feature toggle is set to "Allow control"
* visit SEO → General in a couple of subsites and set the toggle to "On"
* visit single posts in the front end for both the subsites, view the source and see the you can find the tags for the Enhanced Slack Sharing like these ones:
```
<meta name="twitter:label1" value="Written by">
<meta name="twitter:data1" value="Agatha …
```

P3-272 Allow network disabling of Enhanced Slack Sharing

---

tests/unit/inc/addon-manager-test.php
wp-seo-main.php
wp-seo.php

* We only support the last 2 versions of WordPress
* Set minimum WP version to 5.5 and tested up to to 5.6
*
*
*
*
Partially fixes https://yoast.atlassian.net/browse/QAK-2524

Set minimum WP version to 5.5 and tested up to to 5.6

---

package.json
yarn.lock

Bump monorepo versions for 15.5

---

css/src/schema-blocks.css

*
* Replaces the CSS for the schema blocks with an CSS-import from the schema-blocks monorepo package. 
*
* Follow the test instructions on https://github.com/Yoast/javascript/pull/975
* No need to test this PR. The schema blocks will be tested as a whole when they are ready.
*
Fixes #

P2-576 Moved schema-blocks CSS to the monorepo.

---

admin/class-plugin-conflict.php

*
* Extends the plugin conflict list.
*
*
*
*
Fixes #

Add Rank Math to the plugin conflict list

---

inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-option-wpseo.php
lib/orm.php

* Several changes to free code have been made in premium. This ports relevant changes back to free.
* Adds a fix for NULL queries to the ORM and two options to our options framework.
* All code has already been active in premium for several months.
* A basic safety check that no crashes occur on the main pages ( post-edit, our settings page and the frontend at least ).
* All code has already been running in premium for several months.
* The ported changes come only into effect when running premium where they've already been running for several months.

Port changes made to free code in premium back to free

---

css/src/modal.css

* Adds two columns to the modal
* Adds two columns to be used in the modal
*
* See test-instructions for [the PR on premium](https://github.com/Yoast/wordpress-seo-premium/pull/3121)
*
*
Fixes P1-228

Add columns to modal

---

composer.json
tests/unit/database/migration-runner-test.php
tests/unit/integrations/watchers/indexable-author-watcher-test.php
tests/unit/integrations/watchers/indexable-date-archive-watcher-test.php
tests/unit/integrations/watchers/indexable-home-page-watcher-test.php
tests/unit/integrations/watchers/indexable-post-type-archive-watcher-test.php
tests/unit/integrations/watchers/indexable-system-page-watcher-test.php
tests/unit/integrations/watchers/indexable-term-watcher-test.php
tests/unit/integrations/watchers/option-titles-watcher-test.php

* More quality, less CS errors
* It just adds docs to tests
*
* N/A - It just adds docs and set annotations in the tests right.
*
*
Fixes #

Fixes a couple of CS errors in the tests

---

admin/class-admin-asset-manager.php
config/webpack/paths.js
js/src/editor-modules.js

* Extension of #16479, missed three modules and added them here.
* Exposes three more editor modules which are relied on by Yoast SEO premium in a separate script.
* enqueue the script. Notice no new JS errors.
* This PR adds to a script which isn't used in Yoast SEO free. There is nothing to test in Yoast SEO free for QA. When we start using this in Yoast SEO Premium, this should be properly tested.
* NA

Add three more editorModules.

---

js/src/editor-modules.js

* Extension of #16479, a new module import was added to premium so I added them here.
* Exposes one more editor module which are relied on by Yoast SEO premium in a separate script.
* enqueue the script. Notice no new JS errors.
* This PR adds to a script which isn't used in Yoast SEO free. There is nothing to test in Yoast SEO free for QA. When we start using this in Yoast SEO Premium, this should be properly tested.
* NA

Add the editor modal to the editor modules

---

js/src/editor-modules.js

* This PR replaces the import for the ajaxHelper used in the plugin.
* Replaces the import for the ajaxHelper.
*
* Build the plugin the way you're used to and see if it builds correctly without errors.
*
*
Fixes #

Change import ajaxHelper

---

package.json
yarn.lock

* Bump monorepo versions for 15.6.
* Bump monorepo versions for 15.6.

Bump monorepo versions for 15.6

---

package.json
yarn.lock

* This version bump is necessary for the Free and Premium RCs tomorrow. 
* Bumps the `schema-blocks` package to 1.1.0-RC1.
*
* See that Travis passes.
*
*
Fixes #

Bumps the `schema-blocks` package to 1.1.0-RC1

---

src/integrations/watchers/indexable-ancestor-watcher.php
src/integrations/watchers/indexable-author-watcher.php
src/integrations/watchers/indexable-date-archive-watcher.php
src/integrations/watchers/indexable-home-page-watcher.php
src/integrations/watchers/indexable-homeurl-watcher.php
src/integrations/watchers/indexable-permalink-watcher.php
src/integrations/watchers/indexable-post-meta-watcher.php
src/integrations/watchers/indexable-post-type-archive-watcher.php
src/integrations/watchers/indexable-post-watcher.php
src/integrations/watchers/indexable-static-home-page-watcher.php
src/integrations/watchers/indexable-system-page-watcher.php
src/integrations/watchers/indexable-term-watcher.php
src/integrations/watchers/option-titles-watcher.php
src/integrations/watchers/primary-term-watcher.php
src/loadable-interface.php
tests/unit/integrations/watchers/indexable-static-home-page-watcher-test.php
tests/unit/integrations/watchers/primary-term-watcher-test.php

* Part of the WPSEO CS Cleanup.
* Improves the documentation for the indexable watchers and their tests.
*
* No test needed, this is just documentation and has no impact on the functionality.
*
*
Fixes #

Fix docs in watchers

---

admin/class-admin-asset-manager.php
composer.json
config/webpack/paths.js
js/src/dynamic-blocks.js
src/context/meta-tags-context.php
src/integrations/blocks/abstract-dynamic-block.php
src/integrations/blocks/breadcrumbs-block.php

* Adds a breadcrumbs block which renders the Yoast SEO breadcrumbs for a particular post or page.
* Adds a breadcrumbs block which renders the Yoast SEO breadcrumbs for a particular post or page.
* somehow loading the breadcrumbs block
* Add the breadcrumbs block. Notice the breadcrumbs showing in the block editor.
* Save
* Look at the page on the frontend. Notice the breadcrumbs showing in the page.
* Inspect the source. Notice the breadcrumbs schema added to the graph.
* Nothing in particular. It's a new block.

Breadcrumbs block

---

tests/unit/helpers/blocks-helper-test.php
tests/unit/helpers/pagination-helper-test.php
tests/unit/helpers/primary-term-helper-test.php
tests/unit/helpers/schema/html-helper-test.php
tests/unit/helpers/twitter/image-helper-test.php

* Adding some missing doc to `tests/unit/helpers` files
* Adds missing docs to unit test files for helpers.
*
* N/A - It just adds docs.
*
*
Fixes #

Add missing docs to tests for helpers

---

tests/unit/inc/health-check-ryte-test.php

* CS fixes.
* Adds descriptions to the health ryte check test docs.
*
* In a terminal, in the `wordpress-seo` root, run:
`vendor/squizlabs/php_codesniffer/bin/phpcs ~/yoast/plugin-development-docker/plugins/wordpress-seo/tests/unit/inc/health-check-ryte-test.php`. Verify that the description errors are no longer there.
* Not applicable: doc changes only.
*

Add descriptions to health-ryte-check-test

---

tests/unit/repositories/indexable-repository-test.php

* Fix CS warning in docs for Indexable Repository Test
* Fixes documentation for Indexable Repository Test
*
*
*
*
Fixes #

Fix CS warning in docs for Indexable Repository Test

---

admin/class-product-upsell-notice.php
inc/health-check-curl-version.php
inc/health-check-links-table-not-accessible.php
inc/health-check-ryte.php
readme.txt

Change "kb.yoast.com" to "yoast.com/help/" and "Knowledge Base" to "Yoast help center"

Help Center naming changes

---

.travis.yml

*
* Replaces the php vulnerability checker package.
*
*
*
*
Fixes #

Replace the security checker

---

src/builders/indexable-link-builder.php
tests/unit/builders/indexable-link-builder-test.php

* When you're linking to `/tag/seo-basics/` instead of writing the URL out in full, we don't properly detect the target indexable. This fixes that. 
* When you're linking to `/tag/seo-basics` (without the trailing slash) instead of writing the URL out in full, we don't properly detect the target indexable if the site does have a trailing slash in its permalink structure. This fixes that as well. 
* Fix the tests
* ~Trigger a reindex of all relative links on all sites.~ 
* Properly detect the target indexable for relative links.
*
* Make sure your permalink settings have a trailing slash.
* Add, to a post or page, a relative link, without a trailing slash, to an existing …

Fix relative link detection

---

src/presenters/title-presenter.php

* Improve performance of the post overview page in the admin.
I noticed a loading time decrease of the posts overview page (52 posts) of 30%. Going from
`Time per request:       814.375 [ms] (mean)`
to
`Time per request:       524.596 [ms] (mean)`
* Improved loading time of the posts overview page in the WordPress backend (props to [@Rahe](https://github.com/Rahe)).
* The `remove_filter()` priority needs to match the priority of the `add_filter()`, otherwise it won't be removed.
* Make sure post title in the post overview are as expected. They should be the same before and after this change.
* Make sure post titles on the frontend are as expected as well. 
* The …

Add matching priority to pre_get_document_title filter removal

---

src/builders/indexable-link-builder.php
src/helpers/request-helper.php
src/integrations/blocks/breadcrumbs-block.php
tests/unit/builders/indexable-link-builder-test.php

* Fixes an issue where indexable without an ID would be created from the breadcrumbs block.
* Fixes an error in the indexing process that occurred as a results of the breadcrumbs block.
* Create a post with a breadcrumb block.
* Save it.
* There shouldn't be any indexables with an object_type of post and no object id.
* Rendering of the breadcrumbs block, both in the frontend as well as in the editor.
Fixes https://yoast.atlassian.net/browse/QAK-2629

[QAK-2629] Fix broken indexable for breadcrumb

---

css/src/schema-blocks.css

*
* Added extra CSS for the schema template blocks.
*
* Test this PR in tandem with [this PR in Premium](https://github.com/Yoast/wordpress-seo-premium/pull/3169), use its test instructions.
* 
* N/A, only touches schema blocks functionality, which is behind a feature flag.
Fixes #

Added extra CSS for schema blocks.

---

readme.txt
src/context/meta-tags-context.php
src/generators/schema/breadcrumb.php
src/generators/schema/webpage.php
src/surfaces/values/meta.php
tests/unit/doubles/context/meta-tags-context-mock.php
tests/unit/generators/schema-generator-test.php
tests/unit/generators/schema/breadcrumb-test.php
tests/unit/generators/schema/webpage-test.php

* Makes sure the breadcrumbs schema is always present, except on static page homepages, system pages or 404 pages.
* Makes sure the breadcrumbs schema is always present, except on 404 pages.
* Please verify the changelog item is valid.
* The schema of any frontend request.

Always enable bc schema

---

js/src/help-scout-beacon.js

*
* Fixes a bug where the HelpScout beacon would throw a console error.
* The JSON is already parsed on line 47. Parsing parsed JSON doesn't work 😅.
* See https://yoast.atlassian.net/browse/QAK-2647
*
*
Fixes https://yoast.atlassian.net/browse/QAK-2647

[QAK-2647] Don't parse already parsed JSON

---

js/src/schema-blocks.js

* We do not want to expose debug logging to end users. We do want to use logging for our own purposes. We do not want to have to add / remove logging every time.
* Hides debug logging behind an abstraction; default to logging only errors.
* this allows us to hide console.logs behind an abstraction in the schema-blocks package. 
changing the call to `initialize( )` will allow you to log more or less detailed information. Given this is a fairly new product, we expect logging is helpful for the next few weeks.
* 
* open the developer console; no console.logs coming from schema blocks should be visible.
* to change the loglevel, …

P2-560 Replace console.logs with logger, initialize at ERROR level

---

js/src/redux/reducers/editorContext.js
js/src/redux/selectors/editorContext.js
src/integrations/third-party/elementor.php

* We need an extra filter to apply the hidden hields from addons to the Elementor integration
* Adds filter to apply hidden fields from addons to Elementor integration
* 
* See test instructions on [Video](https://github.com/Yoast/wpseo-video/pull/872)
*
*
Fixes #

Implement Video in Elementor editor

---

package.json
readme.txt
wp-seo-main.php
wp-seo.php

* Needed to do a hotfix 15.8.2 release for Premium without having to do it for Free.
* Updates the plugin version to 15.8.2.
*
*
*
*
Fixes #

Update the version to 15.8.2

---

package.json
yarn.lock

*
* Bumps `@yoast/schema-blocks` to `1.4.0-rc2`.
*
*
*
*
Fixes #

Bump monorepo packages for 15.9-RC3

---

admin/class-admin-asset-manager.php

* Fixes a console error on the settings page due to a missing script dependency.
* Go to the Yoast SEO settings page.
* There shouldn't be any console errors.
* Only the settings page.

[QAK-2725] Fix missing dependency in settings script

---

src/helpers/schema/image-helper.php
tests/unit/helpers/schema/image-helper-test.php

* Adds `contentUrl` to the schema image output to more precisely say what the URL _is_.
*
* Image output in Schema should have a `contentUrl` attribute that matches the `url` attribute.
*
*
Fixes PRODUCT-202

Add contentUrl to schema image output

---

src/context/meta-tags-context.php
src/generators/schema/faq.php
src/generators/schema/webpage.php
tests/unit/generators/schema-generator-test.php
tests/unit/generators/schema/faq-test.php

*
* Schema: removes `mainEntityOfPage` from our FAQ Schema block output and moves it to `mainEntity` on the `WebPage` output, fixing a Google parse issue with those FAQ blocks.
* Added a `$main_entity_of_page` to the context, so that can be changed from within `is_needed` functions of piece generators.
* See old / current FAQ schema output in RRT / SDTT and see that it errors.
* Switch to this branch, test output, see that it doesn't error and creates the correct previews in the RRT.
*
*
Fixes PRODUCT-275

Fix FAQ schema to prevent Google error

---

.travis.yml
readme.txt
tests/unit/bootstrap.php
wp-seo-main.php
wp-seo.php

* On March 9th, WordPress 5.7 will be released. We always support the 2 latest versions.
* For 15.9.1, the `tested up to` changes in readme.txt and wp-seo.php were already made on SVN.
* Sets the WordPress tested up to version to 5.7 and minimum supported WordPress version to 5.6.
*
* N/A
*
* N/A
Fixes #

Set tested up to to WP 5.7 and minimum to 5.6

---

js/tests/components/SEMrushCountrySelector.test.js
js/tests/setupTests.js

* We want to remove React as a dependency
* Removes React import from tests.
*
* Run `yarn test` and see if tests still pass
*
*
Fixes [AR-66](https://yoast.atlassian.net/browse/AR-66)

Remove React import from tests

---

src/generators/schema/main-image.php
tests/unit/generators/schema/main-image-test.php

⚠️  no tests broke when I built this, but I also didn't add any yet and we should ⚠️ 
* The idea of this change is that the social image is meant for a sharing context, and is thus most suitable to be the main image.
* Adds your OpenGraph or Twitter image as the main image in Schema when they're set.
*
* Set a social image on a post that already has a featured image, see that this featured image is replaced by the social image in the Schema.
Fixes PRODUCT-266

Make social images eligible to be the primaryImageOfPage

---

js/src/analysis-worker.js
js/src/initializers/post-scraper.js
js/src/initializers/term-scraper.js
js/tests/Pluggable.test.js
js/tests/components/contentAnalysis/mapResults.test.js

*
* Adds eslint-disable-next-line for some errors, adds missing semicolon, and fixes a helper path in `mapResults.test.js`
*
* Run `yarn test` and make sure that all tests pass
* Run `grunt check` and make sure that no error is found
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-701

Add eslint-disable-next-line for some errors

---

.env.example
config/grunt/task-config/notify-slack.js

*
* Changes the channel in which is announced that a beta has been created from #test to #beta
*
*
*
*
Fixes #

Send slack message about betas in the beta channel

---

src/generators/schema/article.php
tests/unit/generators/schema/article-test.php

* Changed the output of the `articleSection` and `keywords` attributes of the Article schema to an array instead of comma separated values.
* Test on any article by setting two categories and two tags and seeing the output change. 
*
*
Fixes PRODUCT-259

Un-implode tags and categories

---

composer.json
wp-seo-main.php

* Fixes an issue where rewrite rules could be set as if the strip category base feature was enabled during plugin activation.
* Activate and install premium 15.9.
* Upgrade to 16.0.3
* Visit any category archive.
* It should work as normal.
* The activation routine.
Fixes https://yoast.atlassian.net/browse/QAK-2823
Fixes #16808

[QAK-2823] Do not instantiate WPSEO_Rewrite unless stripcategorybase is set to true

---

src/helpers/schema/image-helper.php

* In #16690 I added `contentUrl` for most imageObject schema output, this fixes the cases that I omitted.
* None needed.
* The logo output within `Organization` schema should now have a `contentUrl` as well.

add contentUrl for image objects based on attachment metadata too

---

admin/class-admin-asset-manager.php
admin/metabox/class-metabox.php
admin/taxonomy/class-taxonomy.php
src/integrations/third-party/elementor.php

*
* Fixes some code style errors.
*
*
*
* No functional changes, just fixes some CS errors.
Fixes #

Fix CS errors

---

src/schema-templates/ingredients.block.php

*
* Sets default header of the ingredients block to h3.
*
* Make sure you have the schema-blocks feature flag enabled.
* Link the latest version of the monorepo to your dev environment before building.
* Create a new post with a recipe block and fill it in.
* Inspect the ingredients title and check if it set to h3.
* Save the post and check on the front-end if the ingredients title is set to h3.
*
*
Fixes #

Set default header of ingredients title to h3

---

src/builders/indexable-home-page-builder.php
tests/unit/builders/indexable-home-page-builder-test.php

*
* Fixes an unreleased bug where the homepage OG image would not reset properly.
*
* Open the settings: SEO > Social > Facebook > Frontpage settings.
* Set an image.
* Save.
* Check the source code of the front page and ensure that you see the line: <meta property="og:image" content="yourImageURL.jpg" />.
* Return to Social > Facebook > Frontpage settings. 
* Remove the image.
* Save.
* Check the source code of the front page, the `og:image` meta tag should no longer be present.
*
* 
Fixes https://yoast.atlassian.net/browse/P1-476

Reset homepage indexable's image source and meta

---

config/grunt/task-config/copy.js

* Not all files in the css/dist directory were copied
* Make sure all css files in the dist directory are copied to the artifact
*
* Run `grunt artifact`
* Open the artifact folder and verify that all css files are present. Also the ones in the select2 directory needs to be copied
*
*
Fixes #

Copies all files in the css directory instead of the ones in the root

---

css/src/metabox.css
css/src/search-appearance.css
package.json
yarn.lock

* The draft-js upgrade has an unexpected side-effect when building for production: backspace/removing no longer works. We could not determine why this is failing in a reasonable timeframe. In development it does work. And in our `merge-monorepo` branch it also works with production. Therefor the pragmatical solution for now is to revert the `draft-js` upgrade for now. And reintroduce it later when the `merge-monorepo` has landed.
* The unfortunate side-effect is that we regress back to our tabbing issue / keyboard trap in the metabox.
* Fixes an unreleased bug where the backspace in the replacement variable editors would no longer work when building for production.
*
* …

P1-475 revert draft js upgrade

---

js/src/help-scout-beacon.js

* When using identify, the user's email address will be sent to HelpScout. We don't want that.
* Use prefill for the HelpScout Beacon instead of identify
*
On trunk:
* Have premium trunk active as well.
* Make sure you have a name and email address set in your user profile.
* Clear your local cookies: 
* Open the network tab in your terminal.
* Refresh the page, log in again (because you will be logged out), go to an options page where the HelpScout beacon is present, for example Yoast > General.
* Filter the requests on `beacon`. See a PUT request called `customers`, containing your email address:
On this branch:
* (still have premium active as well)
* Clear your local …

Use prefill for the HelpScout Beacon instead of identify

---

config/grunt/task-config/aliases.yaml
config/grunt/task-config/clean.js

* Zip size is over 6 MB, we need to reduce the artifact size.
*
* Prevent the schema blocks translations from ending up in the release artifact.
* after generating the languages files, clean all schema blocks files.
* `grunt artifact` will create a zip file; this file should not contain schema blocks translations.
*
Fixes #

P2-895 block schema blocks translations from shipping

---

Gruntfile.js
config/grunt/task-config/aliases.yaml
config/grunt/task-config/clean.js
config/grunt/task-config/copy.js
config/grunt/task-config/shell.js
package.json

* Undo the logic made in #16647 to prevent large zip files.
* Removes the logic that catches schema translations which will cause a large zip file.
*
* Run `grunt build:artifact`
* Verify that the size of the zip is decreased below the 5 mb.
*
*
Fixes #

P2-897 - Remove all schema translations logic

---

js/src/redux/selectors/fallbacks.js

* Social previews were broken since 16.1. See example:
* [wordpress-seo-premium] Fixes a bug where the protocol instead of the domain was displayed in the social previews.
* Chose to rely on script data instead of a piece of state that seems unreliable.
* Notice the issue. Install the fix. Notice it fixes the bug.
* Facebook preview and Twitter preview in Yoast SEO Premium should reflect the domain.
Fixes #

Fix broken domain name in the social previews.

---

js/src/structured-data-blocks/faq/block.js

* Many people like to segment their FAQ pages using multiple FAQ blocks. We didn't allow for that yet, but we simply could, as we conflate all the questions in a single FAQ page anyway in the schema.
* Allows adding multiple FAQ blocks to a post or page.
* Note you can now add multiple FAQ blocks
* Note they are combined nicely in the FAQ schema.
* FAQ schema
Fixes #

Allow multiple FAQ blocks

---

src/integrations/third-party/elementor.php
src/integrations/third-party/wpml-wpseo-notification.php

CS: class constants before properties

---

admin/class-yoast-form.php
admin/class-yoast-network-admin.php
inc/class-wpseo-replace-vars.php
inc/sitemaps/class-sitemap-cache-data.php
lib/orm.php
src/builders/indexable-hierarchy-builder.php
src/generators/schema/faq.php
src/presentations/indexable-presentation.php
tests/integration/doubles/wpseo-wp-rest-server-mock.php
tests/integration/inc/test-class-wpseo-upgrade.php
tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-data.php

* Code quality
* Code quality
No functional changes.
The result from the condition will already be `true` or `false`, no need for the ternary.
For anyone not entirely clear on how post-decrement works, this code was doing some inscrutinable magic.
The minor tweak now applied makes it clearer what is happening for the next person.
... except when used in HTML templating.
* _N/A_

CS/QA: various small fixes

---

tests/unit/bootstrap.php

Modernize: use __DIR__

---

config/composer/unit-test-generator.php
config/dependency-injection/inject-from-registry-pass.php
config/dependency-injection/interface-injection-pass.php
src/actions/semrush/semrush-phrases-action.php
src/builders/indexable-post-builder.php
src/config/semrush-client.php
src/exceptions/indexable/indexable-exception.php
src/exceptions/oauth/authentication-failed-exception.php
src/exceptions/semrush/tokens/empty-property-exception.php
src/exceptions/semrush/tokens/empty-token-exception.php
src/exceptions/semrush/tokens/failed-storage-exception.php
src/helpers/date-helper.php
src/integrations/schema-blocks.php
src/integrations/third-party/elementor.php
src/routes/indexing-route.php
tests/unit/actions/alert-dismissal-action-test.php
tests/unit/doubles/admin/admin-gutenberg-compatibility-notification-double.php
tests/unit/doubles/builders/indexable-post-builder-double.php
tests/unit/doubles/integrations/watchers/indexable-post-watcher-double.php
tests/unit/helpers/schema/replace-vars-helper-test.php
tests/unit/presenters/admin/badge-presenter-test.php
tests/unit/routes/alert-dismissal-route-test.php
tests/unit/routes/indexing-route-test.php

QA: import all classes in namespaced files

---

src/generators/open-graph-image-generator.php
src/generators/twitter-image-generator.php
src/integrations/admin/helpscout-beacon.php
src/presenters/debug/marker-open-presenter.php
tests/unit/admin/metabox/metabox-collapsibles-section-test.php
tests/unit/admin/paper-presenter-test.php
tests/unit/admin/views/integration-toggles-test.php
tests/unit/builders/indexable-term-builder-test.php
tests/unit/doubles/models/indexable-double.php
tests/unit/generators/schema/main-image-test.php
tests/unit/inc/options/option-social-test.php
tests/unit/integrations/exclude-oembed-cache-post-type-test.php
tests/unit/integrations/third-party/elementor-exclude-post-types-test.php

No functional changes.
* _N/A_

QA: remove redundant use statements

---

src/deprecated/admin/add-keyword-modal.php
src/deprecated/admin/keyword-synonyms-modal.php
src/deprecated/admin/multiple-keywords-modal.php
src/deprecated/frontend/breadcrumbs.php
src/deprecated/frontend/frontend.php
src/deprecated/frontend/schema/class-schema-howto.php
src/deprecated/frontend/schema/class-schema-main-image.php
src/deprecated/frontend/schema/class-schema-person.php
tests/integration/admin/test-class-yoast-network-admin.php
tests/integration/formatter/test-metabox-formatter.php

QA: no FQN in non-namespaced files

---

config/composer/unit-test-generator.php
src/conditionals/admin/estimated-reading-time-conditional.php
src/conditionals/third-party/elementor-edit-conditional.php
src/helpers/date-helper.php
src/helpers/input-helper.php
src/helpers/request-helper.php
src/integrations/admin/helpscout-beacon.php
src/integrations/front-end/wp-robots-integration.php
src/integrations/third-party/elementor.php
src/repositories/indexable-repository.php
tests/unit/conditionals/estimated-reading-time-conditional-test.php
tests/unit/helpers/input-helper-test.php
tests/unit/integrations/schema-blocks-test.php

QA: use FQN global constants in namespaced files

---

admin/class-premium-popup.php
admin/formatter/class-post-metabox-formatter.php
admin/formatter/class-term-metabox-formatter.php
admin/taxonomy/class-taxonomy.php
config/dependency-injection/custom-loader.php
src/builders/indexable-link-builder.php
src/generators/breadcrumbs-generator.php
src/integrations/admin/admin-columns-cache-integration.php
src/models/seo-links.php
tests/unit/conditionals/no-tool-selected-conditional-test.php
tests/unit/conditionals/yoast-tools-page-conditional-test.php
tests/unit/generators/schema-generator-test.php
tests/unit/helpers/url-helper-test.php
tests/unit/integrations/watchers/primary-term-watcher-test.php

Docs: various type fixes

---

admin/class-yoast-form.php
inc/class-addon-manager.php
inc/class-wpseo-replace-vars.php
inc/options/class-wpseo-option.php
inc/options/class-wpseo-options.php
src/deprecated/frontend/class-twitter.php

Docs: improve types in `@var` tags

---

inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-taxonomy-meta.php

* Code clean up
* Code clean up
* _N/A_

QA: remove commented out code

---

admin/class-admin.php
src/deprecated/frontend/schema/class-schema-howto.php
tests/integration/admin/test-class-admin-asset-dev-server-location.php

Docs: remove various tags

---

tests/unit/dependency-injection/schema-templates-loader-test.php
tests/unit/dependency-injection/schema-templates-pass-test.php

QA/Tests: fix two incorrect namespaces

---

admin/class-yoast-form.php
config/dependency-injection/inject-from-registry-pass.php
src/commands/index-command.php
src/generators/schema-generator.php
src/integrations/admin/helpscout-beacon.php
src/integrations/third-party/web-stories.php
src/integrations/watchers/primary-category-quick-edit-watcher.php
tests/integration/notifications/test-class-yoast-notification-center.php
tests/unit/doubles/admin/admin-gutenberg-compatibility-notification-double.php

Docs: fix parameter doc alignment

---

src/presenters/admin/meta-fields-presenter.php

Docs: use full docblock format for properties

---

composer.json

* _N/A_
This is a threshold-only change and should have no effect on the functionality. If the build passes (linting, test runs), we're good.

Composer: update CS thresholds

---

src/deprecated/admin/onpage/class-onpage-option.php
src/integrations/front-end-integration.php

*
*Added phpcs:ignore comments for 2 lines that do not need explicit escaping.
*
*
*
*
Fixes #

P2-953 Fixed CS issues to match the threshold.

---

src/generators/schema/faq.php

* After enabling multiple FAQ blocks it turned out the position of a Question starts counting from 1 again in schema when using multiple FAQ blocks. This needs to count up.
* Makes sure the schema question positions are correct when using multiple FAQ blocks.
* Note how the bug is fixed
* Schema on the frontpage when using one or multiple FAQ blocks should work as expected.

P1-512 Make sure FAQ question positions count up

---

inc/class-upgrade.php
js/src/initializers/admin.js
src/builders/indexable-home-page-builder.php
tests/unit/builders/indexable-home-page-builder-test.php

* Global Social Templates feature was removed, therefore we need to remove the upgrade routine from the 16.3 release branch.
* Removes the upgrade routine for the Global Social Templates.
* Please note that the team agreed to keep some changes e.g. the new options. They will just be unused, for now. This won't impact in any way the existing functionalities.
* Not sure there's a way to test this PR, as the upgrade routine won't run.
No need to test this PR, as it just removes an upgrade routine.
*
*
Fixes [P3-593]

Remove the Global Social Templates upgrade routine.

---

packages/js/package.json
packages/schema-blocks/tests/functions/blocks/getParentSidebar.test.ts

* The `getparentSidebar.test.ts` file is failing after we merged `develop` branch in `javascript` to `feature/language-split` in `wordpress-seo`. This test is passing in `javascript`. We skip this test for now.
* Skip the`getparentSidebar.test.ts` test
*  Delete the empty `premium-configuration` branch with the same name after this PR is merged
* Run `yarn`
* Run `yarn test` and make sure that everything passes except the failing tests related to `premium-configuration`
*
*
Fixes #

skip the getParentSidebar test

---

README.md

* Removes outdated instructions (associated to linking the monorepo) from README.md file.
*
*
* This PR affects the following parts of the plugin, which may require extra testing:
*
Fixes https://yoast.atlassian.net/secure/RapidBoard.jspa?rapidView=99&modal=detail&selectedIssue=LINGO-804 (step 4)

Update readme file: remove leftovers from linking the monorepo

---

package.json
yarn.lock

* @noud-github published version 2.1.1 of `@yoast/grunt-plugin-tasks` on NPM. Our plugin should use that version.
* This PR contains the same solution as https://github.com/Yoast/wordpress-seo/pull/17042. I closed it and created a new PR because that was easier than resolving the merge conflicts on that PR.
* Bumps `@yoast/grunt-plugin-tasks` to version `^2.1.1`.
*
* The automatic changelog creation should work as expected.
* No QA test needed.
*
Fixes #

Bump @yoast/grunt-plugin-tasks to version ^2.1.1

---

apps/content-analysis/src/utils/getMorphologyData.js
packages/yoastseo/spec/specHelpers/getMorphologyData.js

*
* Updates paths to Hungarian morphology data after the version had been changed.
*
*
*
*
Fixes #

Update Hungarian morphology data version

---

packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper2.js
packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper4.js
packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper3.js
packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper2.js
packages/yoastseo/spec/scoring/assessments/seo/IntroductionKeywordAssessmentSpec.js
packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js

*
* Adds a missing space to the feedback text in he keyphrase in introduction assessment.
* [yoastseo] Adds a missing space to the feedback text in he keyphrase in introduction assessment.
*
* Open a new post.
* Add the keyphrase `cat dog`.
* In the first paragraph of the post, add the text `A cat. And a dog`.
* You should get the feedback text `Keyphrase in introduction: Your keyphrase or its synonyms appear in the first paragraph of the copy, but not within one sentence. Fix that!`. Confirm that there is a space after the `:`.
*
*
Fixes …

Add missing space in feedback text

---

admin/class-admin-asset-manager.php

* Adds a missing dependency to the editor scripts.
* Fixes a bug where new feature notification couldn't be dismissed.
* Adds missing api dependencies to all scripts that were using it.
1. Install and activate News SEO 12.7 alongside this PR
2. Create a new post and navigate to the News tab
3. With the console open try to dismiss the News notification
4. See that the News notification doesn't close and a console error appears
* Dismissing alerts.
Fixes https://yoast.atlassian.net/browse/QAK-2923

[QAK-2923] Add missing api-client dependency to editor scripts

---

packages/yoastseo/README.md

*
* Updates the yoastseo package readme file.
*
*
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-720

Update yoastseo package readme

---

packages/yoastseo/src/languageProcessing/languages/nb/config/functionWords.js

Reverts Yoast/wordpress-seo#17131

Revert "Expand list of Norwegian function words"

---

src/generators/schema/website.php
tests/unit/generators/schema-generator-test.php
tests/unit/generators/schema/website-test.php

* Google has updated [their documentation](https://developers.google.com/search/docs/data-types/sitelinks-searchbox) on how sitelinks search box schema should be structured. This pull updates our implementation to match the new spec.
The new approach expands the value of the target property into an EntryPoint object, with a urlTemplate property.
Before
```json
"potentialAction":[
{
"@type":"SearchAction",
"target":"https://www.example.com/?s={search_term_string}",
"query-input":"required name=search_term_string"
}
]
```
After
```json
"potentialAction": [
{
"@type": "SearchAction",
"target": {
"@type": "EntryPoint",
"urlTemplate": "https://www.example.com/?s={search_term_string}"
},
"query-input": "required name=search_term_string"
}
]
```
This PR can be summarized in the following …

Fix PRODUCT-339

---

src/repositories/indexable-repository.php

* Adds methods to the indexable repository for the workouts.
* These are added here to the `ensure_permalink` method can be used.
* Use `wp shell` to execute these methods, they should return the correct indexables.
* Should not be tested on it's own but rather via https://github.com/Yoast/wordpress-seo-premium/pull/3363
* Used in the workouts premium feature.

Add methods to indexable repository for the workouts integration

---

packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts

*
* Renames the Job closing date block to Job application closing date.
* Accompanies this Premium PR: https://github.com/Yoast/wordpress-seo-premium/pull/3355
* See that the new name is "Job application closing date" everywhere.
*
*
Fixes #

Rename the Job closing date block to Job application closing date

---

src/generators/schema-generator.php

*
* Improves documentation for the `wpseo_schema_{identifier/type}` filter.
* After discussion with @herregroen in the architecture half hour, this is the solution we chose for P2-1045.
* No test is needed, this is just a documentation change.
*
*
Fixes #

Improve documentation for the 'wpseo_schema_{identifier/type}' filter

---

packages/yoastseo/src/languageProcessing/index.js

*
* [yoastseo] Adds `stripHTMLTags` helper to `languageProcessing` index.js file.
* [wpseo-woocommerce] Fixes a bug where an error occurred in the `YoastWooCommerce-productTitle` assessment.
*
* Build the plugin from this branch
* Install and activate [Yoast SEO WooCommerce 14.1](https://github.com/Yoast/wpseo-woocommerce/releases/tag/14.1)
* Install and activate  Woocommerce 5.4.1.
* Go to Products > Add New
* Check SEO analysis and confirm that the woocommerce specific assessment is loaded and that it doesn't look like this:
* Confirm that there is no error in the console
* …

Add stripHTMLtags helper to languageProcessing index

---

packages/yoastseo/README.md

*
* Updates the yoastseo package readme file (adds language support for Slovak).
*
*
*
*
Fixes https://yoast.atlassian.net/secure/RapidBoard.jspa?rapidView=99&modal=detail&selectedIssue=LINGO-879

Add Slovak to README.md in yoastseo package

---

readme.txt
tests/unit/bootstrap.php
wp-seo-main.php

* On July 20th, WP 5.8 will be released.
* Set tested up to version to WP 5.8
*
*
*
*
Fixes #

Set tested up to version to WP 5.8

---

wp-seo.php

* On July 13th, WC 5.5 will be released.
* Bump WC tested up to to 5.5.
*
*
*
*
Fixes #

Set WC tested up to to 5.5

---

package.json
yarn.lock

* bump plugin-grunt-tasks to 2.1.2
* bump plugin-grunt-tasks to 2.1.2
* 
* 
* This bumps a dev dependency; no test is needed.
*
Fixes #

bump grunt-plugin-tasks to 2.1.2

---

packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
packages/yoastseo/spec/scoring/assessments/readability/transitionWordsAssessmentSpec.js
packages/yoastseo/spec/scoring/contentAssessorSpec.js
packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js

*
* [yoastseo] Makes `transitionWordsAssessment` not applicable when the text has less than 200 words.
*
* Create a post and add a text with less than 200 words
* Confirm that the transition words assessment doesn't appear in the metabox
* Add more words to the text so it's more than 200 words
* Confirm that the transition words assessment appear in the metabox
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-948

Adjust transition words assessment applicability

---

packages/yoastseo/spec/scoring/assessments/seo/ImageAltTagsAssessmentSpec.js
packages/yoastseo/src/scoring/assessments/index.js
packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js
packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
packages/yoastseo/src/scoring/productPages/seoAssessor.js

*
* [yoastseo] Creates `ImageAltTagsAssessment` for product pages
* This new assessment checks if all images in the text has alt attributes or not
* In `apps/content-analysis/src/App.js` on the line before `worker.initialize( config )`, please add this (don't commit):
```
config.customAnalysisType = "productPage";
```
Perform the steps below for both normal content and cornerstone content:
* Create a post without any images
* Confirm that `Image alt tags` assessment doesn't appear in the metabox
* Add three images without alt attributes to the text:
```
```
* Confirm that the feedback says `Image alt tags: None of the images has alt tags. Add alt attributes to your …

Create image alt tags assessment for product pages

---

packages/js/src/components/Indexation.js
src/builders/indexable-link-builder.php

* P2-1106 intends to expose errors that happen during the indexing process; we'd like to capture those errors but not break the entire indexing procedure.
* Prevents an error during the indexing process
* log an error instead of throwing it
* create two posts, add an image to each
* link post 1 to post 2
* 
*
*
Fixes #

P2-1177 prevent error during indexing

---

packages/yoastseo/src/worker/AnalysisWebWorker.js

*
* [yoastseo] Registers the whole web worker with the scope.
*
* This PR should be tested together with https://github.com/Yoast/wpseo-woocommerce/pull/709
*
*
Fixes #

Register the web worker to allow setting custom assessors in addons

---

composer.json
tests/unit/integrations/front-end-integration-test.php
tests/unit/surfaces/meta-surface-test.php

*
* Fixes a couple of PHPCS issues on docs in tests
*
* Once it passes Code Review, it can be accepted. No changes in the code itself, just in commenting
*
*
Fixes #

P2-1225 Add short descriptions in doc comments

---

packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js

*
* [yoastseo] Adjusts the English papers in full text tests for product pages.
*
* Run `yarn test` and make sure everything passes.
*
*
Fixes #

adjust english papers

---

apps/content-analysis/src/utils/getMorphologyData.js
packages/yoastseo/spec/specHelpers/getMorphologyData.js

*
* Updates Italian morphology data version.
*
*
*
*
Fixes #

LINGO-1014 Update Italian morphology data version to v10

---

packages/yoastseo/README.md

*
* [yoastseo] Updates `README.md` for Farsi support.
*
*
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-935

Update Readme for farsi support

---

packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper1.js
packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper2.js
packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper3.js
packages/yoastseo/spec/fullTextTests/testTexts/index.js

*
* [yoastseo] Adjusts Farsi full text tests papers.
*
* run `yarn test` and make sure everything passes.
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-934

Adjust Farsi full text tests papers

---

.adr-dir
docs/.adr-dir
docs/project-decisions/0001-record-architecture-decisions.md

* We will record architecture decisions in the source repository.
* Adds Architecture Decision Records to document project decisions.
*
* install [adr-tools ](https://github.com/npryce/adr-tools)
* open a terminal to the repository folder
* type `adr new blabla` 
* run `git status` which should prove that a new file was generated in the `docs\project-decisions` folder named `0002 blabla`
*
*
Fixes #

AR-238 record architecture decisions

---

apps/content-analysis/src/utils/getMorphologyData.js
packages/yoastseo/spec/specHelpers/getMorphologyData.js

*
* Updates Russian morphology data version.
This PR should be tested together with [this premium PR](https://github.com/Yoast/wordpress-seo-premium/pull/3444).
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-1027

Update Russian morphology data version

---

admin/metabox/class-metabox.php

*
* Fixes a bug where the placement variables Category, Name and Tag would not show up in the snippet preview.
*
* Set a display name for your user.
* Do the following steps for the block editor, the classic editor and elementor:
1. Create a new post, add tags and categories and use the `Category`, `Name` and `Tag` replace vars in the snippet editor.
2. *Note:* The tags and categories will only be updated in the previews when the page is refreshed.
3. Save the post and verify that the tags work on the front-end.
Verify that the `Category`,  `Name` and `Tag` replacement variable can be used in the search appearance pages.
* …

Fixed labels for replacevars name and tag

---

admin/class-admin-asset-manager.php
admin/class-admin-asset-seo-location.php
admin/class-yoast-notification-center.php
config/composer/unit-test-generator.php
config/dependency-injection/renamed-classes.php
lib/orm.php
src/actions/indexing/indexable-post-indexation-action.php
src/actions/indexing/indexable-term-indexation-action.php
src/builders/indexable-builder.php
src/builders/indexable-link-builder.php
src/config/researcher-languages.php
src/generators/schema/breadcrumb.php
src/helpers/current-page-helper.php
src/integrations/admin/social-templates-integration.php
src/integrations/cleanup-integration.php
src/presenters/admin/indexing-failed-notification-presenter.php
src/schema-templates/cooking-time.block.php
src/schema-templates/preparation-time.block.php
src/schema-templates/recipe-ingredients.block.php
src/schema-templates/recipe-instructions.block.php
src/services/indexables/indexable-version-manager.php
tests/unit/builders/indexable-builder-test.php
tests/unit/integrations/feature-flag-integration-test.php
tests/unit/presenters/admin/indexing-error-presenter-test.php
wp-seo-main.php

CS: various fixes

---

src/schema-templates/cooking-time.block.php
src/schema-templates/preparation-time.block.php
src/schema-templates/recipe-description.block.php
src/schema-templates/recipe-ingredients.block.php
src/schema-templates/recipe-instructions.block.php
src/schema-templates/recipe.block.php

* Code quality
* Code quality
* _N/A_

QA: don't use FQN in non-namespaced files

---

tests/unit/actions/indexing/indexable-term-indexation-action-test.php
tests/unit/admin/import/plugins/import-aioseo-v4-test.php
tests/unit/config/indexable-builder-versions-test.php
tests/unit/generators/schema/main-image-test.php
tests/unit/main-test.php

QA; fix incorrect `@covers` tags

---

admin/class-admin-asset-manager.php
config/webpack/paths.js
packages/js/src/admin-modules.js
packages/js/src/editor-modules.js
packages/js/src/workouts.js
packages/js/src/workouts/components/CornerstoneWorkoutCard.js
packages/js/src/workouts/components/OrphanedWorkoutCard.js
packages/js/src/workouts/components/WorkoutCard.js
packages/js/src/workouts/components/WorkoutsPage.js
packages/js/src/workouts/redux/reducer.js
packages/js/src/workouts/redux/selectors.js
src/integrations/admin/workouts-integration.php
src/routes/workouts-route.php

*
* Register premium Cornerstone and Orphaned content workouts in free. 
*
*
*
*
Fixes #

Dupp 7 register premium workouts

---

packages/seo-store/src/analysis/slice/config.js

- Refactor the config slice to not use constants.
- Refactor the config slice to not use reducer & selector helpers.
- Refactor the config slice to not use constants.
- Refactor the config slice to not use reducer & selector helpers.
*
*
*
*
Fixes P1-997

Create Redux reducer for managing analysis configuration state

---

packages/replacement-variables/.eslintrc
packages/replacement-variables/package.json
packages/replacement-variables/src/index.js
packages/seo-store/gists/interfaces.js
packages/seo-store/src/analysis/hooks.js
packages/seo-store/src/analysis/slice/index.js
yarn.lock

*
* Add JSDocs to the replacement variable factory function.
* Accept `regexp` as part of the configuration, for flexibility.
* Add eslint scripts: `yarn lint` and `yarn lint:watch`.
* Add clean script `yarn clean` and apply them before build & watch.
* The flexibility part of `regexp`.
* Applied two (currently unmerged) commits to be able to see the replacevars still working in the `seo-integration` app (the `seo-store` ones).
* Run the `seo-integration` app
* Verify the `%%title%%` in the content still gets replaced by whatever you input in the title (check in console).
* N/A …

P1-1028 replacement variable factory

---

packages/replacement-variables/__tests__/index.test.js
packages/replacement-variables/package.json
yarn.lock

* Setup jest so we can test our code
* Wrote first small test
* Setup jest so we can test our code
*
- `cd` into the project folder
- run `yarn test`
- Verify that the (apply function)test suite passes
*
*
Fixes P1-1029

P1-1029 - Setup Jest

---

admin/ajax.php

*
* Changes parameter name for the wpseo_upsert_new() method to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions when clicking **Save** or **Save all** for Yoast SEO titles in the bulk editor
*
Fixes #

Rename parameters with reserved names admin/ajax.php

---

inc/class-wpseo-utils.php

*
* Changes parameter names in the `WPSEO_Utils` class to avoid breaking changes in PHP 8+
*
* N/A
* No regression testing needed, we are changing only functions that are deprecated and not used in our codebase anymore
*
Fixes #

Rename parameters with reserved names class-wpseo-utils.php

---

apps/seo-integration/package.json
apps/seo-integration/src/app.css
apps/seo-integration/src/app.js
apps/seo-integration/src/index.js
apps/seo-integration/src/replacement-variables.js
apps/seo-integration/src/seo-title-width.js

*
* Adds the editor fields in the `seo-integration` app.
* Adds the Google preview data in the `seo-integration` app.
* Adds the replacement variables in the `seo-integration` app.
* Refactor the app setup:
- move replacement variables to own file
- move seo title width to own file
- move registering to index: this makes the app a component without import side-effects
* Fire up the `seo-integration` app (needs built and symlinked packages: `seo-store` and `replacement-variables`.
* Try the redux layer of the new inputs: editor and Google preview in the sidebar
* Try the replacement variables, see the console for which should be available. …

P1-1056 dummy editor

---

packages/replacement-variables/__tests__/index.test.js

*
* Adds tests for the `replacement-variables` package.
*
* CR the tests
* Install deps
* Go to `replacement-variables` package and run the tests: `yarn test`
* N/A
*
Fixes https://yoast.atlassian.net/browse/P1-1030

Replacement-variables: add tests

---

packages/seo-store/package.json
packages/seo-store/src/analysis/slice/config.js
packages/seo-store/src/analysis/tests.js
yarn.lock

* Setup jest to test our code
* Setup jest to test our code
* Place the tests inside of the applicable folders (ducky pattern; [ref](https://www.freecodecamp.org/news/scaling-your-redux-app-with-ducks-6115955638be/#enter-re-ducks))
*
* `cd` into the project folder
* run `yarn test`
* Verify that the (config slice)test suite passes
*
Fixes P1-1007

P1-1007 - Setup Jest

---

packages/seo-store/src/analysis/tests.js
packages/seo-store/src/editor/tests.js
packages/seo-store/src/form/tests.js

-
* Created tests for the `seo` and `editor` reducers
* 
* CR the tests
* Install deps `yarn`
* Go to `seo-store` package and run the tests: `yarn test`
*
*
Fixes #

Test the analysis data reducer

---

packages/seo-store/src/analysis/slice/config.js
packages/seo-store/src/analysis/tests.js

*
* Adds tests for the `analysis` slice.
* Fixes an unreleased bug where the analysis config research actions would not work.
* Use `isBoolean` naming for selectors whenever the values are booleans.
* Code review the tests
* Install deps: `yarn`
* Go to `seo-store` package and run the tests: `yarn test`
* The tests should all pass
* N/A
*
Fixes [P1-1005](https://yoast.atlassian.net/browse/P1-1005)

P1-1005 test analysis config slice

---

admin/class-admin.php

* We want to prevent a visit to the conf. wizard by direct URL
* Disables the registration of the configuration wizard page
* 
* visit `{your_site}/wp-admin/admin.php?page=wpseo_configurator` and check that you get a `Sorry, you are not allowed to access this page.` message.
*
*
Fixes [DUPP-101]
[DUPP-101]: https://yoast.atlassian.net/browse/DUPP-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DUPP-101 hide conf wizard direct URL

---

packages/yoastseo/src/worker/bootstrapAnalysis.js
packages/yoastseo/webpack/bootstrapAnalysis.webpack.config.js
packages/yoastseo/webpack/languages.webpack.config.js
packages/yoastseo/webpack/main.webpack.config.js
packages/yoastseo/webpack/webpack.config.js

*
* [yoastseo] Adds webpack configuration to build a script that bootstraps the analysis within a web worker.
* Decided to change the target of the main and languages webpack configuration to `self` instead of `window`.
* `self` refers to the global scope in web workers as well as in browsers (e.g. `self` refers to `window` in browser contexts).
* This makes sure that the scripts always work when loaded within web workers.
* Run `grunt build:js` within `packages/yoastseo`.
* A new file should be built called `bootstrap-analysis.js`, located within the `packages/yoastseo/dist/build` folder.
* The file's contents should be a minified version of the code found in …

P1-1073 web worker bootstrap script

---

apps/seo-integration/package.json
apps/seo-integration/public/worker-mock.js
apps/seo-integration/src/index.js
apps/seo-integration/src/replacement-variables.js
apps/seo-integration/yarn.lock
packages/replacement-variables/src/index.js
packages/seo-integration/package.json
packages/seo-integration/src/analysis.js
packages/seo-integration/src/index.js
packages/seo-integration/src/replacement-variables.js
packages/seo-store/src/analysis/slice/results.js
yarn.lock

*
* Enhances the SEO integration factory function.
* Mocked the analysis web worker in the app. We don't have an actual one, and this makes it so we can test the `seo-integration` package.
* Use `create` as default prefix for the factory functions, mostly after Nolle's remark.
* Expanded the JSDoc a bit, using `@typedef` sometimes. Calling certain ones `...Interface`, not sure if that is the way to go, but couldn't think of a better name, suggestions welcome.
* The analysis configuration is using a filter `yoast.seoIntegration.analysis.configuration`. This might turn out to not work fine in add-ons, due to it only being run once. They might still need access to `worker.initialize` or at least a wrapper to change the configuration …

P1-1035 create seo integration factory function

---

admin/views/sidebar.php
css/src/admin-global.css

* Removes Black Friday sale badge from sidebar
* Removes Black Friday sale badge from sidebar
*
* Pull this branch and build assets
* Navigate to `/wp-admin/admin.php?page=wpseo_dashboard`
* Check if the '30% off' badge is gone in the sidebar:
*
*
Fixes #

P1 1053 remove black friday sale badge

---

package.json
yarn.lock

* Bump plugin-grunt-tasks to 2.2.1 This fixes a changelog issue during hotfix creation
* Bump plugin-grunt-tasks to 2.2.1 This fixes a changelog issue during hotfix creation
*
*
*
*
Fixes #

Bump plugin-grunt-tasks to 2.2.1

---

tests/unit/surfaces/meta-surface-test.php

* 
* _N/A_ This change only involves the tests. If the build passes, we're good.

Meta_Surface_Test::for_url_provider(): use named data sets

---

css/src/installation-success.css
packages/js/src/installation-success.js

Note: when zooming out (<100%) the thickness of the border of the right circle might be incorrect (i.e. thinner than expected).
* Adds the stepper and title to the free installation success screen.
*
* Enable the feature flag: add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* Navigate to `{admin-url}/admin.php?page=wpseo_installation_successful_free`.
* See the title and stepper match the [design](https://www.sketch.com/s/d8601833-a14f-4dff-bee0-426acfa4a2c8/a/098oodO/play).
* N/A
*
*
Fixes #

DUPP-139 add stepper and title

---

src/config/schema-types.php

* Adds "Blog Post" / `BlogPosting` as a potential Schema `Article` type.
* See that `Blog Post` is available as an option in the Article type schema dropdown and actually shows on the frontend when selected.
Fixes PRODUCT-632

Add blog posting type

---

src/builders/indexable-link-builder.php
src/repositories/seo-links-repository.php

* This PR aims to fix the incoming link counts of posts never being set to zero.
* Fixes a bug where the incoming link count of a post would not return to zero if all incoming links are removed.
* The query in `get_incoming_link_counts_for_indexable_ids()` is bugged in that it will not return the IDs of indexables that have 0 incoming links, therefore they would never get updated. After some discussion and deliberation, I opted to fix this in PHP, rather than expanding the query to account for this, and potentially become very bloated.
* Create 2 posts (A and B)
* Make sure the SEO indexables optimization is completed so that you can see the incoming and outgoing link …

IM-1614 Fix incoming link count of 0

---

packages/js/src/components/WincherPerformanceReport.js
packages/js/src/dashboard-widget.js

* Takes care of a few problems that caused React to log warnings when rendering the dashboard widget.
* Fixes some React warnings.
*
* Enable Wincher integration and track a few keywords.
* Go to dashboard, ensure that there are no React warnings in console.
*
*
Fixes #

QA-2609 Wincher: Fix React warnings in the dashboard widget

---

packages/yoastseo/README.md

*
* [yoastseo] Updates `README.md` for Japanese support.
*
*
*
*
Fixes #

Update readme for Japanese support

---

tests/unit/integrations/admin/installation-success-integration-test.php

* We want to avoid tests to fail because of critical race conditions with `time()` returning different values.
* Avoids using `time()` in tests for the installation success integration.
*
* Check that the tests are passing.
* NA it's only related to unit tests
*
Fixes [DUPP-172]
[DUPP-172]: https://yoast.atlassian.net/browse/DUPP-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DUPP-172 Fix installation success integration tests

---

packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js

* We've cleaned up some spec descriptions for assessing text and paragraph length. We've also added some corner cases (for texts with zero and one word/character). 
* [yoastseo] Cleaned up spec descriptions for assessing text and paragraph length
* None
* Run the specs (`yarn test` in `packages/yoastseo`) and confirm they all pass. 
* None.
Fixes https://yoast.atlassian.net/browse/LINGO-1201

Cleaned up spec descriptions for assessing text and paragraph length

---

packages/js/tests/components/WincherKeyphrasesTable.test.js

* Fix failing tests
*
*
*
*
*
Fixes #

Fix failing Wincher JS tests

---

admin/class-admin-asset-manager.php

* Fixes the workouts not loading.
* See https://yoast.atlassian.net/browse/QA-2720
* Loading JavaScript for the workouts and installation success page.
Fixes https://yoast.atlassian.net/browse/QA-2720

[QA-2720] Fix loading JS on workouts pages

---

docs/project-decisions/0002-single-responsibility-per-file.md

* AR-122 caused architecture decisions that need to be recorded.
* We want clean code. Part of that is to limit a code file to a single responsibility.
* We want clean code. Part of that is to limit a code file to a single responsibility.
* n/a
*
*
Fixes #

AR-122 Single Responsibility Per File

---

packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js

* The Japanese full text test was failing because of the recently merged adaptation for metadata description length (https://github.com/Yoast/wordpress-seo/pull/17907), that was initially pushed to the release branch, while the full text test (https://github.com/Yoast/wordpress-seo/pull/17877) was pushed to trunk. 
* [yoastseo] Fixes the Japanese full text test.
*
* Run `yarn test` in `packages/yoastseo` and confirm all tests pass.
* No further impact.
Fixes the build of the trunk branch.

Fixes the failing Japanese full text test

---

packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper1.js
packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
packages/yoastseo/spec/languageProcessing/helpers/sanitize/sanitizeLineBreakTagSpec.js
packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeLineBreakTag.js
packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
packages/yoastseo/src/worker/AnalysisWebWorker.js

* The plain `<br>` tags without any attributes is converted to paragraph tags using [WordPress `autop` function](https://developer.wordpress.org/reference/functions/wpautop/). However, this function doesn't convert `<br>` tags with attributes. As the result, the paragraph is not tagged properly and the highlight doesn't work for those paragraph.
* Fixes a bug where the `<br>` tags with attribute(s) in the text would not be converted to paragraph tags. As a result some long paragraph(s) in the text failed to be highlighted.
* The further sanitation of `<br>` tag with attributes is done inside `getParagraphLength` research file instead of inside the `AnalysisWebWorker.js`. This is done to minimize the scope if impact of this …

Lingo 1210 fix paragraph highlighting bug

---

packages/seo-integration/readme.md

* Provide minimal documentation for the `@yoast/seo-integration` package.
*
*
* Review the docs [here](https://github.com/Yoast/wordpress-seo/tree/p1-987-analysis-integration-docs/packages/seo-integration).
*
*
Fixes #

P1 987 seo-integration docs

---

packages/js/src/classic-editor.js
packages/js/src/classic-editor/plugins/featured-image.js
packages/js/src/classic-editor/plugins/index.js
packages/js/src/classic-editor/plugins/markdown.js
packages/js/src/classic-editor/plugins/shortcodes.js

* Refactor the Markdown plugin to use WordPress filter instead of `registerModification` to modify paper data.
* Refactors the Markdown plugin to new analysis paper data modification API.
* Refactored `featuredImagePlugin` and `shortcodesPlugin` for consistancy.
* Added `plugins/index.js` to `classic-editor` duck for named plugin imports.
First, enable analysis worker debugging like so:
1. Open the `plugin-development-docker/config/basic-wordpress-config.php` file.
2. In the `yoastdebug` conditional, add the `define( 'YOAST_SEO_DEBUG_ANALYSIS_WORKER', 'TRACE' );` like so:
3. Now you can add the `yoastdebug` param to the URL you're testing and see analysis worker logs. …

P1 1109 markdown plugin

---

packages/js/src/classic-editor/helpers/dom.js

*
* Fixes an unreleased bug where the post date helper would not support the use of a named timezone.
* Using moment, since it is already on the window in WP. I only know of `toLocaleString` to provide a timezone, but that requires parsing again. This seems easier.
* Set a named timezone in your WP install, e.g. `Europe/Amsterdam`
* Create a new post in the classic editor
* Look at the editor's date in the `@yoast/seo` store
* Verify it is in UTC correctly
* Set a manual offset timezone, e.g. `+8:45`
* Create a new post in the classic editor (or change the publish date and save)
* Look at the editor's date in the `@yoast/seo` store
* Verify it is in UTC correctly
* Play …

P1-1152 Fix post date timezone in name format

---

readme.txt
tests/unit/bootstrap.php
wp-seo-main.php

* WP 5.9 will be released on Jan 25, the same day as the 18.0 release.
* Sets the WordPress tested up to version to 5.9.
*
*
*
*
Fixes #

Set WP tested up to to 5.9

---

wp-seo.php

* WooCommerce 6.1 has been released.
* Sets WooCommerce tested up to version to 6.1.
*
*
*
*
Fixes #

Set tested up to WC to 6.1

---

src/integrations/front-end-integration.php

* Fixes an infinite loop involving the new document title filter.
* Fixes an infinite loop involving the new document title filter.
* See https://yoast.atlassian.net/browse/QA-2801
* The front-end as well as potentially any place using `wp_get_document_title`
Fixes https://yoast.atlassian.net/browse/QA-2801

[QA-2801] Fix infinite loop involving the document title

---

packages/js/src/redux/selectors/WincherSEOPerformance.js

* Fixes a bug where keyphrases using capital letters were duplicated in the SEO performance table.
* Lowercase Wincher keyphrases to prevent duplicates in table. 
*
* Enable Wincher integration
* Create post and add a focus keyphrase that uses capital letters.
* Open SEO Performance modal
* Ensure keyphrase is only displayed once in the Table and that it's in lowercase. 
*
* Wincher integration
Fixes IM-1662

IM-1662 Lowercase keyphrases in getWincherTrackableKeyphrases

---

packages/js/package.json
packages/js/src/workouts/components/Stepper.js
yarn.lock

* Adds animations to the stepper as shown in the [Axure prototype](https://er5tbk.axshare.com/) to visually emphasize what happens: one step collapses and another step expands.
* Adds transition animations to the stepper.
* We created a new component `TailwindStep` (since `Step` already exists) to remove duplicate code for the three versions (statuses) of the steps. 
* We moved away from using statuses ("complete", "current", "upcoming"), since a step is either `saved` or not, and on top of that it can be active. 
* Dealing with the active step is handled outside of the `Stepper` component, it just receives an `activeStepIndex`. 
* Since animations with heights are extremely tricky, we added a package to deal with this …

Dupp 196 add stepper button animations

---

packages/helpers/src/index.js
packages/helpers/src/replacement-variables/extractExcerptFromContent.js
packages/seo-integration/babel.config.json
packages/seo-integration/package.json
packages/seo-integration/src/replacement-variables/configurations.js
packages/seo-integration/tests/replacement-variables/configurations.test.js
yarn.lock

* Jest was already installed inside `seo-integration` package. However, the unit tests were not yet working. This PR is to adjust the Jest configuration so the unit tests work.
* [seo-integration] Adjusts the unit test framework configuration and adds a test file.
* [helpers] Adds a new helper to extract excerpt from the content.
* See my comments below.
* Run `yarn test` and make sure everything passes
* N/A: this only impacts the JavaScript unit tests.
*
Fixes #

Fix the jest configuration for seo integration package

---

config/grunt/task-config/shell.js
yarn.lock

*
* Adds back build commands for `seo-integration` package after they were accidentally removed.
*
* Run `grunt build` command in the branch and confirm that there is no error in the terminal.
* NA
*
Fixes https://yoast.atlassian.net/browse/LINGO-1299

Add back build commands for seo-integration package after they were accidentally removed

---

src/services/options/site-options-service.php
src/validators/boolean-validator.php
tests/unit/validators/boolean-validator-test.php

*
* Adds the boolean validator.
*
```php
/** @var \Yoast\WP\SEO\Validators\Boolean_Validator:: $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Boolean_Validator::class );
try {
}
echo '<br>';
}
_test_validate( null );
```
* Part of …

P1-1191 create boolean validator

---

src/services/options/site-options-service.php
src/validators/text-field-validator.php
tests/unit/validators/text-field-validator-test.php

*
* Adds the text field validator.
*
* You can run this somewhere and play around with feeding it different input:
```php
function _print_characters( $string ) {
$array = str_split( $string );
foreach ( $array as $character ) {
echo wp_json_encode( $character ), ' ';
}
}
/** @var \Yoast\WP\SEO\Validators\Text_Field_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Text_Field_Validator::class );
_print_characters( $value );
try {
_print_characters( $validator->validate( $value ) );
} catch ( …
```

P1-1197 create text validator

---

src/integrations/blocks/structured-data-blocks.php

* Ensures images in structured data blocks maintain their aspect ratio when larger than the page.
* See https://yoast.atlassian.net/browse/QA-2900
* Images in structured data blocks.
Fixes https://yoast.atlassian.net/browse/QA-2900

[QA-2900] Add height auto to structured data imgaes

---

css/src/tailwind.css
packages/js/src/workouts/components/ConfigurationWorkout.js
packages/js/src/workouts/tailwind-components/ConfigurationIndexation.js
packages/js/src/workouts/tailwind-components/Indexation.js
packages/js/src/workouts/tailwind-components/indexation-step.js

* Some features/minor updates were left out of the initial iteration of the indexing step _tailwindification_
* Update the first time configuration indexation step to include some UI/UX additional requirements
* I tried to isolate each change into single commits
* Install and activate wpseo free
* Activate Yoast Test plugin
* Navigate to _SEO_ -> _Workouts_ -> start the _Configure Yoast SEO_ workout
* Check the link _check out the benefits of the indexables squad_ is displayed as a link 
* Click on `Start SEO data optimization` in the first step and make sure the italic text _"SEO data optimization is running… You can safely move on to the next steps of this …

Dupp 272 leftovers indexation step

---

packages/ui-library/.gitignore
packages/ui-library/.storybook/main.js
packages/ui-library/.storybook/preview.js
packages/ui-library/.storybook/style.css
packages/ui-library/package.json
packages/ui-library/scripts/css.copy.js
packages/ui-library/src/base.css
packages/ui-library/src/elements/index.ts
packages/ui-library/src/elements/link/index.js
packages/ui-library/src/elements/link/link.css
packages/ui-library/src/elements/link/stories.js
packages/ui-library/src/introduction.stories.mdx

* Create a Link element that styles "whatever" as a Link.
* Adds the `Link` element.
[Change styles setup plan](https://github.com/Yoast/wordpress-seo/commit/7ec91a197e06aa6d7d285dfff1f5c58f7d452875) 
The UI library should provide unprocessed CSS files to be able to:
* purge tailwind styles correctly
* control what you want to import as user of the UI library
This makes it so the user of the library should import Tailwind in the style. Similar to the `.storybook/style.css`.
And process/build the styles.
* Wrote Link in JS, since we're going that way
* Found a way to use markdown file as a story with @nolledgeable 
* Found a way to input source of a story component: `parameters.docs.transformSource: () => "const foo = "bar";"` …

P1-1232 create link element

---

packages/ui-library/src/components/select-field/index.js
packages/ui-library/src/components/select-field/stories.js
packages/ui-library/src/components/select-field/style.css
packages/ui-library/src/elements/select/index.js
packages/ui-library/src/elements/select/stories.js
packages/ui-library/src/elements/select/style.css

* Adds select element and select field component to UI library
* Adds select element and select field component to UI library
*
* Run Storybook with `yarn storybook`
* Verify that the `Select` and `Select Field` stories work and look as expected.
*
*
Fixes #

P1-1240: create select element

---

inc/class-upgrade.php

*
* Triggers an upgrade routine for yoast-staging, so we can test https://github.com/Yoast/wordpress-seo/pull/18113/files there
*
*
*
*
Fixes #

Trigger update routine for 18.3-RC3

---

src/models/indexable.php

* Fixes #18132 
* Fixes a potential error related to the `has_ancestors` column of our indexables table. Props to @junaidbhura.
* N/A
1. Install HyperDB
2. Update a post
3. The post should save correctly and show no errors
*
*
Fixes #18132

Add `has_ancestors` to the list of boolean columns in the Indexable model

---

src/integrations/front-end/print-qrcode-embed.php
src/integrations/front-end/print-qrcode-render.php

* We want to apply what was done in https://github.com/Yoast/wordpress-seo/pull/18121 for the code that existed in the 18.3 release branch at the time of that PR
*
* N/A, if Travis is green, merge
* Test https://yoast.atlassian.net/browse/DUPP-301 to ensure no regressions
* The impact check of https://yoast.atlassian.net/browse/DUPP-301
Fixes #

Backslash stuff

---

packages/ui-library/.storybook/style.css
packages/ui-library/src/components/text-field/index.js
packages/ui-library/src/components/text-field/style.css
packages/ui-library/src/components/textarea-field/index.js
packages/ui-library/src/components/textarea-field/stories.js
packages/ui-library/src/components/textarea-field/style.css
packages/ui-library/src/elements/text-input/style.css
packages/ui-library/src/elements/textarea/index.js
packages/ui-library/src/elements/textarea/stories.js
packages/ui-library/src/elements/textarea/style.css

*
* Adds the `Textarea` element.
* Adds the `TextareaField` component.
* Made the `TextareaField` like the `TextField` with label, description and error. Even though the design only shows a label.
*
*
*
Fixes [P1-1241](https://yoast.atlassian.net/browse/P1-1241)

Add textarea element

---

packages/ui-library/.storybook/style.css
packages/ui-library/src/components/modal/index.js
packages/ui-library/src/components/modal/stories.js
packages/ui-library/src/components/modal/style.css

*
* Adds the `Modal` component.
*
*
*
*
Fixes [P1-1243](https://yoast.atlassian.net/browse/P1-1243)

Add modal component

---

admin/views/tabs/network/integrations.php
src/actions/configuration/configuration-workout-action.php
src/actions/importing/aioseo/aioseo-general-settings-importing-action.php
src/actions/wincher/wincher-account-action.php
src/helpers/wordproof-helper.php
src/integrations/admin/helpscout-beacon.php
src/integrations/third-party/wordproof.php
src/routes/workouts-route.php
src/services/importing/conflicting-plugins-service.php
tests/unit/actions/importing/aioseo-posts-importing-action-test.php
tests/unit/builders/indexable-post-builder-test.php
tests/unit/doubles/services/importing/importable-detector-service-double.php
tests/unit/helpers/indexable-helper-test.php
tests/unit/services/importing/aioseo-social-images-provider-service-test.php

* Code documentation consistency 
* Code quality
* Code documentation consistency 
* Code quality
The second time the key is declared will just overwrite the first.
... and are not allowed to `return` anything.

CS/QA: various minor fixes

---

admin/views/tabs/dashboard/integrations.php
src/actions/importing/aioseo/aioseo-general-settings-importing-action.php
src/helpers/import-cursor-helper.php
src/helpers/wordproof-helper.php
src/integrations/admin/helpscout-beacon.php
src/integrations/third-party/wordproof-integration-toggle.php
src/services/importing/aioseo/aioseo-robots-transformer-service.php

* Code quality
* Code quality
* CS/QA: remove unused import use statements [1]
* CS/QA: remove unused import use statements [2]
The class being imported is in the same namespace.
* CS/QA: alphabetically sorted import use statements
* CS/QA: always import all used classes
* _N/A_

QA: improve import use statements

---

composer.json
src/integrations/watchers/indexable-post-type-archive-watcher.php
src/services/health-check/default-tagline-report-builder.php
tests/unit/helpers/import-cursor-helper-test.php
tests/unit/helpers/import-helper-test.php
tests/unit/integrations/watchers/indexable-post-type-archive-watcher-test.php

* Code quality
* Code quality
* CS: remove duplicate ignore annotations
The class docblock already contains the same annotation.
* CS: move select ignore annotations into the class docblock.
* Composer: update CS thresholds
* _N/A_ If the (CS) build passes, we're good.

CS: update ignores and thresholds

---

README.md

* Improve build status reporting
* Improve build status reporting
*
* _N/A

README: add badge for the new CheckJS workflow

---

src/services/health-check/default-tagline-report-builder.php

* `esc_attr` is being used but it should be `esc_url`
* Fixes an incorrect escaping function in our health checks. Props to [BronsonQuick](https://github.com/BronsonQuick).
* Make sure you have the default WordPress tagline.
* Go to the health checks.
* The link in the health check about the tagline should still work.
* The tagline health check.
Fixes #

Change to esc_url

---

src/conditionals/third-party/wordproof-plugin-inactive-conditional.php
src/config/wordproof-app-config.php
src/config/wordproof-translations.php
src/helpers/wordproof-helper.php
src/integrations/third-party/wordproof-integration-toggle.php
src/integrations/third-party/wordproof.php
src/integrations/watchers/option-wpseo-watcher.php
tests/unit/integrations/watchers/option-wpseo-watcher-test.php

* Travis error
* Remove the capital P from php class names.
* Travis build failed
* Travis build not failing
*
Fixes #

remove capital p

---

.github/PULL_REQUEST_TEMPLATE.md

Add definition of done to PR template

---

admin/class-admin-asset-manager.php
config/grunt/task-config/copy.js
packages/components/src/select/select.html
packages/js/package.json
yarn.lock

* The styling and some of the drag and drop functionality of the select2 fields were broken.
* Fixes a bug where a version mismatch caused broken styling in WooCommerce select fields when linking products.
*
* Install & activate WooCommerce
* Add two products
* Edit one of the two products and navigate to 'Product Data > Linked Products'
* Search for and select the second product
* Verify that the style of the selected product is off  ![image](https://user-images.githubusercontent.com/20287474/159907865-28e39141-5344-4b01-abaa-969b044c0ea2.png)
* Checkout this PR
* Reload the product page
* Verify the style of the selected product looks appropriately …

Yoast SEO 17.6 breaks ACF "Select" fields.

---

src/helpers/import-cursor-helper.php
src/helpers/import-helper.php
tests/integration/doubles/class-yoast-form-double.php
tests/unit/routes/importing-route-test.php

*
* Changes parameter names in import classes to comply with PHP 8+.
*
* Quickly smoke test importing AIOSEO settings
Fixes #

Fix reserved parameter names in import classes

---

packages/replacement-variables/package.json
packages/seo-integration/package.json
packages/seo-integration/src/analysis-result-containers/seo.js
packages/seo-store/package.json

* Changed `main` property of the agnostic analysis packages to `src/index.js`, as a quick fix for the unit tests to run before the agnostic analysis packages are released.
* Fixes the `feature/agnostic-analysis` branch build.
*
* Check to see that the build is fixed 👇 .
* N/A: This PR is meant to fix the feature branch build.
* N/A: This PR is meant to fix the feature branch build.
Fixes #https://yoast.atlassian.net/jira/software/c/projects/LINGO/boards/99?modal=detail&selectedIssue=LINGO-1386

Fixed agnostic analysis feature branch

---

yarn.lock

*
* Cherry picks https://github.com/Yoast/wordpress-seo/commit/528786306bdf43e770096dbc26b61ae3e2e9d6a8
*
*
*
*
Fixes #

Merge normalizing several @babel dependencies

---

packages/seo-store/src/form/slice/index.js
packages/seo-store/src/form/slice/social/facebook.js
packages/seo-store/src/form/slice/social/index.js
packages/seo-store/tests/form/slice/social/facebook.test.js
packages/seo-store/tests/form/slice/social/index.test.js

* This PR adds functionality to save Facebook-specific data to the seo store.
* [seo-store] Adds Facebook-specific data to the seo store.
* None
* Run `yarn test` inside `packages/seo-store` and make sure that everything passes.
* NA
* No further impact.
Fixes https://yoast.atlassian.net/browse/LINGO-1358

LINGO-1358 Adds Facebook-specific data to the seo store

---

src/integrations/admin/ryte-integration.php

* Fixes a bug where a fatal error would occur on the site health page if WordFence was installed and active.
* Make sure you are in an environment were `WP_DEBUG` is false.
* Have WordFence installed and active.
* Visit the site health checks.
* There should not be a fatal error.
* The Ryte health check.
Fixes #18309
Fixes https://yoast.atlassian.net/browse/IM-1815

[IM-1815] Correctly use the wfConfig class

---

css/src/tailwind.css
css/src/workouts.css
packages/js/src/workouts/components/ConfigurationWorkout.js
packages/js/src/workouts/tailwind-components/ConfigurationStepperButtons.js
packages/js/src/workouts/tailwind-components/Stepper.js
packages/js/src/workouts/tailwind-components/base/alert.js
packages/js/src/workouts/tailwind-components/base/radio-group.js
packages/js/src/workouts/tailwind-components/base/text-input.js
packages/js/src/workouts/tailwind-components/steps/personal-preferences/newsletter-signup.js
packages/js/src/workouts/tailwind-components/steps/personal-preferences/personal-preferences-step.js
packages/js/src/workouts/tailwind-components/steps/social-profiles/social-field-array.js
packages/js/src/workouts/tailwind-components/steps/social-profiles/social-input-person-section.js
packages/js/src/workouts/tailwind-components/steps/social-profiles/social-input-section.js
packages/js/src/workouts/tailwind-components/steps/social-profiles/social-profiles-step.js
tailwind.config.js
yarn.lock

* Tailwindify the configuration workout
* Adds the Personal Preferences step according to a new Tailwind design.
* Copied the element from the ui-library rather than importing it, to prevent scope creep.
* Verify that the personal preferences step looks (enough) like the design 
* Verify that with premium and free the value for tracking is always set.
*
*
Fixes DUPP-247

Add personal preferences step

---

packages/js/tests/classic-editor/watcher.test.js

*
* Adds a unit test for the `classic-editor/watcher.js` file that tests the behavior of the post title watcher.
*
* Run the JavaScript unit tests of the plugin.
* Go to the `packages/js` folder and run `yarn test`.
* See all the tests pass.  
* N/A: this adds a unit test to the code, which does not influence any user facing code.
* N/A: this adds a unit test to the code, which does not influence any user facing code.
Fixes #

Added basic unit test for watcher.js file.

---

packages/tailwindcss-preset/index.js
packages/tailwindcss-preset/readme.md
packages/ui-library/package.json
packages/ui-library/readme.md
packages/ui-library/scripts/build-css.js

* Simplifies the CSS build structure & improves documentation of the UI library package.
* Improves documentation of the Tailwind preset package.
* Simplifies the CSS structure & improves documentation of the UI library package.
* Improves documentation of the Tailwind preset package.
* Move `@wordpress/element` dependency to be a peer dependency, because we want to implementor to manage the `react` and `react-dom` versions. Multiple versions of these packages [can cause errors](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).
* In the UI library package, run the `yarn build:css` command to check if CSS is correctly being built. The …

UI library improvements

---

admin/class-yoast-input-validation.php
admin/views/tabs/metas/paper-content/post_type/woocommerce-shop-page.php
admin/views/tabs/social/twitterbox.php
src/services/health-check/ryte-reports.php

* Fixes typos several types in brand names and the word metadata. Props to [NekoJonez](https://github.com/NekoJonez).
* On the settings page it should spell `LinkedIn` and `YouTube` as opposed to `Linkedin` and `Youtube`.
* In the metabox it should spell `metadata` as opposed to `meta data`.
* When editing a WooCommerce shop page it should spell `metadata` as opposed to `meta-data`.
* The spelling of several words in the admin.
Fixes #18326

Typo fixes

---

.github/workflows/jstest.yml

*
* Adds `replacement-variables`, `seo-integration` and `seo-store` packages to the list of packages to be tested by GitHub actions.
*
* Make sure that in the PR's GitHub actions, `TestJS` jobs for these packages: `replacement-variables`, `seo-integration` and `seo-store`, are triggered.
* NA
*
Fixes #

Add new packages for Github action

---

packages/seo-store/src/form/slice/social/index.js
packages/seo-store/src/form/slice/social/twitter.js
packages/seo-store/tests/form/slice/social/index.test.js
packages/seo-store/tests/form/slice/social/twitter.test.js

* This PR adds functionality to save Twitter-specific data to the seo store.
* [seo-store] Adds Twitter-specific data to the seo store.
* None
* Run `yarn test` inside `packages/seo-store` and make sure that everything passes.
* NA
* No further impact.
Fixes https://yoast.atlassian.net/browse/LINGO-1359

Add Twitter data to the seo store

---

inc/options/class-wpseo-option-wpseo.php
src/actions/configuration/first-time-configuration-action.php
src/routes/configuration-workout-route.php
src/routes/first-time-configuration-route.php
tests/unit/actions/configuration/first-time-configuration-action-test.php
tests/unit/routes/configuration-workout-route-test.php
tests/unit/routes/first-time-configuration-route-test.php

This reverts commit f1c6582.
* See https://github.com/Yoast/wordpress-seo/pull/18333
* Reapplies https://github.com/Yoast/wordpress-seo/pull/18333 see there for test instructions

Revert the reverting of DUPP-366 PR

---

packages/README.md

* This PR adds documentation for our JavaScript packages related to agnostic analysis.
* Adds information about `@yoast/replacement-variables`, `@yoast/seo-store` and `@yoast/seo-integration` packages to `packages/README.md`.
* NA
* Go to [this page](https://github.com/Yoast/wordpress-seo/tree/LINGO-1407-update-readme-md-inside-packages-directory/packages) and make sure that the newly added links of the agnostic analysis packages work and lead to the correct pages.
* NA, just documentation.
* NA
Fixes …

LINGO-1407 Add info of agnostic analysis packages to the packages readme file

---

admin/views/tabs/dashboard/first-time-configuration.php
config/grunt/task-config/postcss.js
css/src/tailwind.css
packages/js/src/first-time-configuration/tailwind-components/tailwind-modal.js
tailwind.config.js

Tailwind usually applies something they call a "preflight" to the styles on a page. This is a way to reset and override most interfering styles, and get all browsers on the same "blank slate". However, in WordPress, we don't want to reset and override interfering styles, we want to surgically apply our styles to areas we want.
But we ALSO want to use TailwindUI classes and examples, and they expect a preflight to have been done.
The solution here is to disable preflight, but apply all the resetting and overriding to a root class, and everything inside of that class will work as if Tailwind had done a preflight.
* Disables the standard Tailwind preflight, and applies the base layer to a yst-root element instead.
* This is a …

Scope tailwind preflight

---

admin/menu/class-admin-menu.php
admin/menu/class-network-admin-menu.php

* Renamed the main admin menu item to "Yoast SEO" instead of "SEO".
* See that the main admin menu item changes name.
* This affects almost every screenshot ever taken of the admin.

Rename admin menu

---

packages/js/src/structured-data-blocks/faq/components/FAQ.js
packages/js/src/structured-data-blocks/faq/components/Question.js
packages/js/src/structured-data-blocks/how-to/components/HowTo.js
packages/js/src/structured-data-blocks/how-to/components/HowToStep.js

* Fixing linting error caused by [18390](https://github.com/Yoast/wordpress-seo/pull/18390)
* Fixes an unreleased linting error caused by not removing a variable that was only used in a prop that was removed in [2aedab7](https://github.com/Yoast/wordpress-seo/commit/2aedab756323fff34fddd16270f10d822042dfcd).
*
* Do a safety check that the How-To and FAQ blocks still work.
*
*
Fixes #

Remove unused vars from blocks

---

readme.txt
tests/unit/bootstrap.php
wp-seo-main.php

* We want to update the supported version of WP to 6.0 (out on May 24th)
* Sets the WordPress tested up to version to 6.0.
*
* N/A
*
* N/A
Fixes #

Set tested up to to WP 6.0

---

admin/tracking/class-tracking-settings-data.php
admin/views/tabs/dashboard/crawl-settings.php
admin/views/tabs/network/crawl-settings.php
inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-option-wpseo.php
src/integrations/front-end/crawl-cleanup-rss.php
tests/unit/integrations/front-end/crawl-cleanup-rss-test.php

Reverts Yoast/wordpress-seo#18492

Revert "DUPP-547 Remove global feed"

---

admin/tracking/class-tracking-settings-data.php
admin/views/tabs/dashboard/crawl-settings.php
admin/views/tabs/network/crawl-settings.php
inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-option-wpseo.php
src/integrations/front-end/crawl-cleanup-rss.php

Reverts Yoast/wordpress-seo#18490

Revert "DUPP-541 - DUPP-541-disable-atom-rdf-feeds"

---

packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js

* Return the initial behavior for premium users in first time configuration
* Return initial behavior for premium users in the first time configuration
*
* Have a clean environment & activate the plugin
* Go to the first time configuration and click on continue until you're at the final step
* Verify you'll see the webinar promo content
* Dismiss the webinar promo alert at the top of the page
* Verify the the last step has non webinar promo related content
* Have a clean environment & activate premium
* Go to the first time configuration and click on continue until you're at the final step
* Verify the the last step has non webinar promo related content
Fixes P1-1416

Return initial behavior for premium users in first time configuration

---

packages/helpers/src/social-preview-image-validation/facebookValidation.js
packages/helpers/tests/social-preview-image-validation/facebookValidationTest.js
src/helpers/image-helper.php

* Make sure we support webp for OpenGraph.
* Added support for `webp` images for OpenGraph output.
* Add a `webp` image to a post, see you get an error and when you save it, we don't output the `og:image`.
* Apply patch, see the error is gone.
Fixes IM-1857

Fix webp support

---

src/generators/schema/article.php
tests/unit/generators/schema/article-test.php

* By adding the name of the article author to the `author` section of the `Article` schema piece, we make Pinterest detect as it doesn't traverse the graph properly.
* Try an article with a current version of Yoast SEO in the [Pinterest URL debugger](https://developers.pinterest.com/tools/url-debugger/).
* See that it doesn't detect the author.
* Switch to this patch, try again, see that it now does.

Fix author detection on Pinterest Rich Article pins

---

composer.json
composer.lock

* We want to update Guzzle to 6.5.7 following a security report
* Bumps Guzzle version to 6.5.7.
*
* Note: Guzzle is a dependency of the OAuth client we use (from League). I.e. it is the authentication that should be tested.
* Test that you can authenticate with Semrush
* Test that you can authenticate with Wincher
* **NOTE**: it's important to test the **authentication**, so if your site is already connected to the two services above, please disable the Wincher and Semrush integrations, save, and then re-enable them.
*
*
Fixes #

Require Guzzle 6.5.7

---

src/config/schema-ids.php
src/context/meta-tags-context.php
src/deprecated/frontend/schema/class-schema-howto.php
src/deprecated/frontend/schema/class-schema-ids.php
src/generators/schema/article.php
src/generators/schema/author.php
src/generators/schema/howto.php
src/generators/schema/third-party/events-calendar-schema.php
src/generators/schema/webpage.php
src/helpers/schema/replace-vars-helper.php
src/integrations/third-party/woocommerce.php
src/presentations/archive-adjacent-trait.php
src/presentations/indexable-author-archive-presentation.php
src/presentations/indexable-home-page-presentation.php
src/presentations/indexable-post-type-archive-presentation.php
src/presentations/indexable-post-type-presentation.php
src/presentations/indexable-presentation.php
src/presentations/indexable-static-posts-page-presentation.php
src/presentations/indexable-term-archive-presentation.php
tests/unit/doubles/context/meta-tags-context-mock.php
tests/unit/generators/schema-generator-test.php
tests/unit/generators/schema/article-test.php
tests/unit/generators/schema/author-test.php
tests/unit/generators/schema/webpage-test.php
tests/unit/helpers/schema/replace-vars-helper-test.php
tests/unit/integrations/third-party/woocommerce-test.php
tests/unit/presentations/indexable-presentation/permalink-test.php

* Switch our main schema ID for interoperability with other plugins and systems.
* We've changed the `@id` of the main schema `WebPage` node to be just the permalink for the current page, for interoperability with other plugins.
* Exposed `permalink` on both the `Meta_Tags_Context` and the `Indexable_Presentation`.
* Deprecation notices say 18.8 now, please set to correct version before merge.
* Test every page type, the `@id` in the `WebPage` block should match the (unaltered) canonical for the current page. On search pages, this would include the search term.
* list of page types:
- home page
- post
- page
- custom post type item
- custom post type archive
- category …

Change the main schema ID

---

yarn.lock

* We always want to target the latest browsers when building our JavaScript. This PR makes sure that the list/db on what is considered the "latest browsers" is up to date and consistent across our JavaScript packages.
* Updates the list of the latest browsers to make sure that we target the latest browsers when building the JavaScript of the plugin.
* I executed this command to update the `caniuse-lite` database, as described in the warning message as seen below:
```
npx browserslist@latest --update-db
```
* During building, you should **not** see any messages like this:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest …
```

Updated caniuse-lite database for browserslist.

---

css/src/admin-global.css

* We want to add a class to change opacity of some settings
* Adds a CSS rule to lower opacity of some settings in the Clean Permalinks feature.
*
* Test with https://github.com/Yoast/wordpress-seo-premium/pull/3588
*
*
Fixes [PC-70]
[PC-70]: https://yoast.atlassian.net/browse/PC-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PC-70 clean permalinks disabled opacity

---

admin/class-config.php
packages/js/src/components/SchemaSettings.js

* We want to include the https://yoast.atlassian.net/browse/PC-83 task to the 19.3 release
* Moves PC-83 to the 19.3 release branch and RCs
*
* Test instructions from https://github.com/Yoast/wordpress-seo/pull/18605/files
*
*
Fixes #

Move PC 83 to release/19.3

---

tests/unit/presenters/meta-author-presenter-test.php

* Fixes an incompatibility between the [Frontend inspector resources](https://github.com/Yoast/wordpress-seo/pull/18621) and the [bugfix](https://github.com/Yoast/wordpress-seo/pull/18634)
* Fix meta author presenter test, trunk build was failing.
*
* CI tests should pass.
*
*
Fixes https://yoast.atlassian.net/browse/PC-45

Fix meta author presenter test

---

packages/analysis-report/src/AnalysisList.js
packages/analysis-report/src/AnalysisResult.js
packages/analysis-report/tests/AnalysisResultTest.js
packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
packages/components/src/beta-badge/BetaBadge.js
packages/components/src/beta-badge/beta-badge.css
packages/components/src/beta-badge/index.js
packages/components/src/index.js
packages/js/src/components/contentAnalysis/mapResults.js
packages/js/tests/components/contentAnalysis/mapResults.test.js
packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
packages/yoastseo/spec/values/AssessmentResultSpec.js
packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
packages/yoastseo/src/values/AssessmentResult.js

* This PR adds a beta badge to the word complexity assessment. 
* [wordpress-seo-premium] Adds a beta badge to the word complexity assessment.
* [wpseo-woocommerce] Adds a beta badge to the word complexity assessment.
* [analysis-report] Adds an optional beta badge to assessment results.
* [yoast-components] Adds a beta badge component.
* We added a new BetaBadge component that is only used in an AnalysisResult. This limits the scope of this issue. 
* Activate Yoast SEO Premium. 
* Add at least 50 characters of content.
* Confirm that in front of the word complexity assessment, a beta badge is shown. 
* Repeat the above steps with all other supported …

PC-135 Add beta badge to the word complexity assessment

---

packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
packages/yoastseo/spec/worker/transporter/serializeSpec.js

* In [this PR](https://github.com/Yoast/wordpress-seo/pull/18609), unit tests were added for the Product identifiers assessment. However, the assessment is disabled for now which causes some unit tests to fail. In this PR, these tests are being commented out. They will be uncommented out again once the assessment is enabled.
* Comments out unit tests that are failing due to the product identifiers assessment being currently disabled.
* Adjusts a failing unit test.
* [yoastseo] Adjusts a failing unit test and comments out unit tests that are temporarily failing.
*
* Make sure that all unit tests pass.
* No QA testing is needed as the PR only touches unit tests.
This PR …

Fix failing unit tests

---

packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js

*
* [yoastseo] Fixes a failing unit test.
*
* N/A
* N/A
*
Fixes #

Fix a failing unit test

---

packages/analysis-report/tests/__mocks__/@wordpress/i18n.js
packages/js/src/initializers/search-appearance.js
packages/replacement-variable-editor/src/ReplacementVariableEditor.js
packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
packages/replacement-variable-editor/src/helpers/serialization.js
packages/search-metadata-previews/tests/__mocks__/@wordpress/i18n.js
packages/social-metadata-forms/jest/__mocks__/@wordpress/i18n.js

* Support for additional Draft.js plugins
* Adds support for additional Draft.js plugins
* Add a slotprovider to the search-appearance component to add support for slot/fill components.
* N/A
*
Fixes PC-47

PC-47 - Adds support for additional Draft.js plugins

---

packages/yoastseo/spec/helpers/getLanguagesWithWordComplexitySpec.js
packages/yoastseo/src/helpers/getLanguagesWithWordComplexity.js

*
* Add upsell for Spanish and German word complexity
*
*
*
*
Fixes #

Add upsell for Spanish and German word complexity

---

inc/options/class-wpseo-option-ms.php

* The Algolia Integration can not be controlled at network level: we want to implement it.
* Fixes a bug where the Algolia integration could not be controlled at network level.
*
* Setup a multisite environment.
* Install and network activate Yoast SEO and Yoast SEO Premium.
* Go to `My Sites` -> `Network admin` -> `Dashboard`.
* Open `Yoast SEO` -> `General` and go to the `Integrations` tab.
* Disable `Algolia integration`.
* Now go to `My sites`, select one of the multisites and go to `Dashboard`.
* Open `Yoast SEO` -> `Integrations`.
* Check that the Algolia Plugin Integration has a `Network Disabled` badge in the header.
* Also check that you can not enable the …

Add network level management for Algolia

---

admin/class-admin-asset-manager.php
inc/class-wpseo-admin-bar-menu.php
packages/js/src/indexables-page/components/indexables-table.js
packages/js/src/indexables-page/indexables-page.js
src/context/meta-tags-context.php
src/integrations/admin/indexables-page-integration.php
src/routes/indexables-route.php

*
* Adds most and least linked posts in the indexable page
*
*
*
*
Fixes #

Add least and most linked posts in the page

---

packages/js/src/indexables-page/components/indexables-table.js

*
* Alter Edit button `href` to point to the post edit screen.
*
* Activate Yoast SEO on [this](https://github.com/Yoast/wordpress-seo/pull/18660) branch.
* Go to `Yoast SEO` -> `General` on the admin screen of WordPress.
* Click on `Indexables`.
* Click the `Edit` button for some Indexable. This should open a new tab with the post edit screen of the Indexable you clicked on.
*
*

Alter Edit button URL for indexables page

---

packages/js/src/indexables-page/components/indexables-table.js
packages/js/src/indexables-page/indexables-page.js
src/helpers/indexables-page-helper.php
src/integrations/admin/indexables-page-integration.php
src/routes/indexables-route.php

*
* Re-populates lists when ignoring and undoing indexables
*
* Have at least 8 posts with content and keyphrase.
* Add this filter2 in your site:
```
add_filter( 'wpseo_indexables_list_size', 'custom_indexables_list_size', 1 );
function custom_indexables_list_size() {
return 2;
}
add_filter( 'wpseo_indexables_buffer_size', 'custom_indexables_buffer_size', 1 );
function custom_indexables_buffer_size() {
return 3;
}
```
* Your lists will now include 2 posts each (and it will locally store 2*3=6 indexables upon page load).
* In the SEO score list, ignore 3 posts. Make sure that the indexable that comes into the list still makes sense. For example, if you ignored the last …

Repopulate lists when ignoring and undoing

---

.github/PULL_REQUEST_TEMPLATE.md

*
* Edits the PR template to guide authors to highlist relevant test cases
*
* NA
* NA
*
Fixes #

Add five checkboxes about relevant testing scenarios

---

packages/js/src/indexables-page.js
packages/js/src/indexables-page/components/indexables-table.js
packages/js/src/indexables-page/indexables-page.js
tailwind.config.js

* Add animation
* Add grid
* Add list styling
*
*
*
*
*
Fixes #

Restyle Indexables Page

---

packages/js/src/ui/publishBox.js

*
* Fixes a bug in the Classic Editor where clicking on the SEO link inside of the Publish box would not scroll the SEO analysis into view when the SEO tab inside of the Yoast metabox was not already open.
*
* Install and activate the Classic Editor plugin.
* Create a post or open an existing one.
* Within the Yoast metabox, select a tab that's not the SEO tab (e.g. the Readability or Schema tab).
* Inside of the Publish metabox (in the top right of the editor), click on the link labeled _SEO_.
* The SEO analysis should be selected and scrolled into view.
* Please test this for custom post types and pages. Taxonomies do not have the Publish box.  …

PC-318 - Fixes a bug where clicking on the SEO link inside of the Publish box in classic editor did not always scroll the SEO analysis into view

---

admin/metabox/class-metabox.php
admin/taxonomy/class-taxonomy.php
packages/js/src/containers/SnippetEditor.js
packages/js/src/elementor/initializers/editor-store.js
packages/js/src/initializers/editor-store.js
packages/js/src/redux/actions/index.js
packages/js/src/redux/actions/postId.js
packages/js/src/redux/reducers/index.js
packages/js/src/redux/reducers/postId.js
packages/js/src/redux/selectors/index.js
packages/js/src/redux/selectors/postId.js

* A performance optimisation for the replacement variable search in the snippet preview caused a JavaScript error in Classic Editor.
* Fixes an unreleased bug where replacement variable search for snippet editor caused a JavaScript error in Classic Editor.
* Add current post ID to our own `yoast-seo/editor` store, instead of selecting from the WP `core/editor` store.
**Test in Classic editor, Gutenberg & term editor**
* Follow test instructions in [this QA issue](https://yoast.atlassian.net/browse/PC-344).
* Follow test instructions in [original PR](https://github.com/Yoast/wordpress-seo/pull/18687).
* …

Pc 344 fix type error classic editor replacement variables search

---

inc/sitemaps/class-post-type-sitemap-provider.php
src/integrations/admin/link-count-columns-integration.php

* Code quality
* Code quality
* 
* _N/A_ Functionally, there should be no noticeable difference

QA: use `add_action()` when hooking into actions

---

src/actions/configuration/first-time-configuration-action.php
src/integrations/admin/integrations-page.php
src/integrations/admin/redirects-integration.php
src/integrations/third-party/wordproof.php
src/services/health-check/links-table-runner.php
tests/unit/services/health-check/links-table-runner-test.php

CS/QA: use fully qualified global constants in namespaced files

---

composer.json
packages/analysis-report/package.json
packages/components/package.json
packages/yoast-components/package.json

PHPCS/ESlint: update thresholds

---

packages/js/src/integrations-page/integrations-grid.js

* We want to update the copy of the integrations page
* Updates the copy in the Integrations page.
*
* Visit the integrations page and check that the copu of the card (titles and descriptions) match the expected ones in the issue.
*
*
Fixes [PC-368]
[PC-368]: https://yoast.atlassian.net/browse/PC-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PC-368 Update copy in the integrations page.

---

admin/class-admin-init.php
admin/class-expose-shortlinks.php
admin/class-inclusive-language-notice.php
admin/class-yoast-notification.php
admin/views/tabs/network/features.php
packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
packages/js/src/analysis/PostDataCollector.js
packages/js/src/analysis/isKeywordAnalysisActive.js
packages/js/src/components/SidebarCollapsible.js
packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
packages/js/src/initializers/post-scraper.js
packages/js/src/ui/publishBox.js
packages/yoast-components/composites/Plugin/ContentAnalysis/reducers/contentAnalysis/inclusiveLanguageResultsReducer.js
packages/yoast-components/composites/Plugin/ContentAnalysis/reducers/tests/contentAnalysisReducerTest.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
tests/unit/admin/views/feature-toggles-test.php

*
* Cherrypicks the main inclusive language PR (https://github.com/Yoast/wordpress-seo/pull/18729) to the release branch.
* Cherrypicks https://github.com/Yoast/wordpress-seo/pull/18781 to the release branch.
*
*
*
*
Fixes #

Inclusive language cherry picked

---

admin/views/class-yoast-feature-toggle.php
admin/views/class-yoast-feature-toggles.php
admin/views/tabs/dashboard/features.php
admin/views/tabs/network/features.php

*
* Fixes a bug where the Inclusive language feature toggle was shown when the installed version of Premium does not support Inclusive language.
*
* Spin up a single site testing environment.
* Install and activate a Yoast SEO Premium version before 19.2-RC1.
* Go to the Yoast SEO features admin page (_Yoast_ > _General_ > _Features_).
* The Inclusive language feature toggle should not be shown.
* Install and activate a Yoast SEO Premium version after 19.2-RC1.
* Go to the Yoast SEO features admin page (_Yoast_ > _General_ > _Features_).
* The Inclusive language feature toggle should be shown.
* Spin up a multisite testing environment.
* Install and activate a Yoast SEO …

Do not add feature toggle if current installed Premium version does not support feature.

---

src/integrations/admin/installation-success-integration.php

* Fixes a bug where a redirect to our installation success page could happen on admin ajax calls.
* Install but do not activate the plugin.
* Open the post editor, open the network tab and wait a little bit for a request to `admin-ajax.php` to occur, most likely the hearbeat request.
* Right click this request, go to copy and select "Copy as cURL".
* Make sure the `should_redirect_after_install_free` is set to `true` and `activation_redirect_timestamp_free` is set to `0`.
* Activate the plugin without visiting the admin by, for example, using WP CLI: `wp plugin activate wordpress-seo`
* Send an admin ajax request by pasting the above copied into your terminal.
* It should …

Do not redirect to the installation success pages on admin ajax calls

---

admin/views/class-yoast-feature-toggles.php

*
* Adds missing shortlinks for inclusive language on the features page.
*
* Activate Yoast SEO Free
* Go to the Features tab in the General settings
* Hover over the`Unlock with Premium!` button next to the inclusive language feature and confirm that the link starts with `https://yoa.st/get-inclusive-language`
* Click on the question mark next to the feature
* Hover over the link in the text that appears `Discover why inclusive language is important for SEO.` , and confirm that it starts with `https://yoa.st/inclusive-language-features-premium`
* Activate Yoast SEO Premium
* Go back to the Features tab in the General settings
* Click on the question mark next to the …

Add missing shortlinks on inclusive language feature page

---

packages/js/src/settings/helpers/search.js
packages/js/src/settings/helpers/validation.js
packages/js/src/settings/store/schema.js
packages/js/src/settings/utils/index.js

* Adds validation to homepage social image field in new settings UI.
* Adds validation to homepage social image field in new settings UI.
*
* Upload a PDF to the homepage social image field in the new settings UI.
* Verify that an error message is shown because media type is invalid.
* Try to save the form with error and verify that the general validation notification pops up.
* Move to another page, but keep general validation notification open. Verify that clicking the link in the notification takes you to the invalid field.
*
*
Fixes #

Pc 443 fix homepage social image validation

---

inc/options/class-wpseo-option-ms.php

*
* [wordpress-seo-premium] Makes the inclusive language feature enabled by default in Multisite Network admin.
*
* Run a fresh multisite environment
* Tips: run `./clean.sh` if you're testing in Docker before running the multisite container
* Refer to [this documentation](https://github.com/Yoast/plugin-development-docker/#running-alternate-or-multiple-containers) on how to start a multisite using subdirectories or subdomains
* Install and activate Yoast SEO 19.6-RC5 and Yoast SEO Premium on your main site
* Network activate Yoast SEO and Yoast SEO Premium in Network admin: Network admin > Dashboard > Go to Plugins in the sidebar
* Go to Yoast SEO in the sidebar > …

Make inclusive language feature enabled by default in Network admin 

---

css/src/toggle-switch.css

*
* Fixes a bug where the feature toggle label was broken when it was too long to fit.
* As a quick fix I decided to update the width of the element. We may need to revisit the CSS / HTML markup of the feature toggles in the future to prevent this happening again for even longer labels.
* Activate Free and Premium
* Go to the feature toggle page (_Yoast SEO_ > _General_ > _Features_).
* Check that the labels of the feature toggles are not broken:
* E.g. the text and question mark icon are on one line, for each feature toggle.
* Check that all question marks expand a text
* …

PC-456 - Increase width of feature toggle labels.

---

admin/tracking/class-tracking-settings-data.php
inc/options/class-wpseo-option-wpseo.php
src/actions/indexables-page-action.php
tests/unit/actions/indexables-page-action-test.php

*
* Allows to track the state of the indexables overview process
*
*
Fixes #

Pc 461 track state

---

packages/js/images/icon-adjustments.svg
packages/js/src/indexables-page/components/all-features-disabled.js
packages/js/src/indexables-page/indexables-page.js
packages/js/src/indexables-page/landing-page.js

*
* Bypass Not Enough (Analyzed) Content screens when features are disabled
*
*
*
*
Fixes #

Bypass Not Enough (Analyzed) Content screens when features are disabled

---

admin/views/tabs/dashboard/dashboard.php
css/src/notifications.css
packages/js/src/indexables-page.js
packages/js/src/indexables-page/components/indexation-view.js
packages/js/src/indexables-page/components/not-enough-analysed-content.js
packages/js/src/indexables-page/components/not-enough-content.js
packages/js/src/indexables-page/indexables-page.js
src/integrations/admin/indexables-page-integration.php

* Move indexables page to dashboard, restyle, and remove indexables tab.
* Moves indexables overview to Yoast SEO `General` tab.
* Decided to restyle the notifications so that the difference didn't look too big with the Indexables tables.
* Did not use tailwind here because the new setting's UI is coming up anyways, and it felt like  a waste of time to refactor it perfectly now.
*
*
*
Fixes PC-434

Move indexables page to dashboard, restyle, and remove indexables tab.

---

css/src/admin-global.css
packages/js/src/indexables-page/components/indexation.js
packages/js/src/indexables-page/components/indexing-error.js
src/integrations/admin/indexables-page-integration.php

* We want to show the error state of the indexing process when it occurs
* Shows the error state of the indexing process when it occurs
*
* Add a `throw new Exception( 'This went wrong' );` line in the `protected function run_indexation_action` of the `Indexing_Route` class to simulate an error in the SEO optimization
*
*
Fixes [PC-484](https://yoast.atlassian.net/browse/PC-484)

PC 484 manage indexing errors

---

src/integrations/third-party/woocommerce.php
tests/unit/integrations/third-party/woocommerce-test.php

* Set out to fix PC-189, but encountered a lot of duplicated code that needed fixing first. Shouldn't have any meaningful impact other than less code.
* Removes duplicated code in the WooCommerce integration.
* On the WooCommerce Shop Page the title and meta description should remain the same with and without this PR.
Fixes #

Removed duplicated WooCommerce code

---

packages/js/src/indexables-page/components/indexable-title-link.js
packages/js/src/indexables-page/components/indexables-table.js
packages/js/src/indexables-page/components/not-enough-analysed-content.js
packages/js/src/indexables-page/components/suggested-links-modal.js
packages/js/src/indexables-page/indexables-page.js

*
* Implements UX feedback
*
*
*
*
Fixes #

Pc 496 implement UI feedbacks

---

packages/js/src/indexables-page/components/not-enough-content.js
packages/js/src/indexables-page/components/suggested-links-modal.js
packages/js/src/indexables-page/indexables-page.js
src/integrations/admin/indexables-page-integration.php

*
* Adds shortlinks in the indexable page
* 
* Learn more about orphaned content. - `yoa.st/indexables-orphaned-content`
* Learn more about cornerstone content. - `yoa.st/indexables-cornerstone-content`
**Recommended reading list**
* Blogging: The ultimate guide - `yoa.st/indexables-ultimate-guide-blogging`
* 10 tips for an awesome and SEO-friendly blog post - `yoa.st/indexables-seo-friendly-blog-post`
* How to optimize a blog post for search engines: a checklist! - `yoa.st/indexables-optimize-blog-post-checklist`
* Why the purpose of your text is important for SEO  - `yoa.st/indexables-purpose-text-seo`
* How to write an SEO-friendly introduction for a blog post - …

Add shortlinks

---

packages/js/src/analysis/classicEditorData.js

* We want to fix SEO/Readability analysis in the Classic Editor following #18758
* Fixes an unreleased bug where adding an image to content in Classic Editor would trigger console errors and break SEO/Readability assessment.
* Activate Classic editor
* keep the console open
* create a new post 
* add an image to content
* see that you don't get any console errors
* check that SEO and Readability assessments are working
* edit the post several times and see that the improvement introduced by #18758 is OK
* after having added the image, do several edits to the post and check that the image is not continuously loaded
* publish the post
* check that everything is still working after a reload …

PC-505 fix SEO/Readability when image is added to content in Classic Editor

---

inc/wpseo-functions-deprecated.php
wp-seo-main.php

* We want to move the initialization of WP CLI redirect commands to Premium
* Moves the initialization of WP CLI redirect commands to Premium.
*
* Test the matching [Premium PR](https://github.com/Yoast/wordpress-seo-premium/pull/3668): WP CLI redirect commands are not available in Free so this PR doesn't change anything visible to users.
*
*
Fixes [PC-525]
[PC-525]: https://yoast.atlassian.net/browse/PC-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PC-525 move WP-CLI redirect commands init to Premium

---

packages/js/src/indexables-page/components/indexables-table.js

*
* Fixes an intermittent issue with Chrome
*
* Repeat test instructions from https://github.com/Yoast/wordpress-seo/pull/18660 (only the **Ignore and Undo** section) in Chrome
*
*
Fixes #

Remove removing the loading state of the ignore button when clicked

---

inc/sitemaps/class-sitemap-image-parser.php

*
* Fixes a bug where the query parameters from an image URL would be omitted in the sitemap.xml
*
Test with normal posts:
* Activate the classic editor and Yoast SEO.
* Head on over to a post and open it with the classic editor.
* Add an image to the post.
* Go to the `Text` visualisation of the post (at the top right side of the classic editor).
* Scroll to the image you just added and add some query parameters to the `src` attribute of the image (such as `?bla=bla&cats=cool`).
* Save the post and head on over to the post sitemap (`/post-sitemap.xml`), inspect the page source to see the entire sitemap.
* Scroll down to the post you just edited within the sitemap and …

Add query parameters when image URL is fetched from ID

---

config/dependency-injection/services.php
css/src/admin-global.css
inc/options/class-wpseo-option-ms.php
inc/options/class-wpseo-option-wpseo.php
src/helpers/robots-txt-helper.php
src/integrations/admin/crawl-settings-integration.php
src/integrations/front-end/robots-txt-integration.php
src/presenters/robots-txt-presenter.php
src/values/robots/directive.php
src/values/robots/user-agent-list.php
src/values/robots/user-agent.php
tests/unit/helpers/robots-txt-helper-test.php
tests/unit/integrations/front-end/robots-txt-integration-test.php
tests/unit/presenters/robots-txt-presenter-test.php

*
* Adds a helper to help with adding content to the robots.txt file.
* Adds options to support the changes in the premium plugin.
*
*
*
*
Fixes #

PC-12 PC-13 port to release branch

---

css/src/tailwind.css

* We want a nice white checkmark instead of a blue one overlapping our one
* Fixes a non released layout issue where two checkmarks were overlapping each other.
* None.
* Open /wp-admin/admin.php?page=wpseo_dashboard. Make sure you see the reading tips. If you don't see them make sure you have less than 20 posts/pages or set `Minimum threshold for the amount of posts needed:` really high in the test helper.
* Check one of the checkboxes and verify it looks the same as https://ui-library.yoast.com/?path=/docs/1-elements-checkbox--factory
*
* …

Add yst-content-none to remove default checkmark from wp.

---

wp-seo-main.php

*
* Fixes a bug where a fatal error would be thrown in connection with plugins changing the standard WP login page.
*
*
*
*
Fixes #

Manually revert PR 18836

---

inc/options/class-wpseo-option-titles.php
packages/js/src/settings/routes/breadcrumbs.js
src/integrations/settings-integration.php

*
* Fixes an unreleased bug where wrong text was displayed on the Breadcrumbs page.
* Fixes an unreleased bug where the user would get to see the breadcrumbs separator as encoded HTML.
*
* Test is [PC-653](https://yoast.atlassian.net/browse/PC-653) is no longer reproduced.
* Test is [PC-654](https://yoast.atlassian.net/browse/PC-654) is no longer reproduced.
*
*
Fixes #

Settings UI phase 4 feedback

---

packages/yoastseo/index.js

* This PR is closely related with [the PR on re-applying the unit-tests for inclusive language in premium](https://github.com/Yoast/wordpress-seo-premium/pull/3687).
* This PR exposes the Factory class to be used in Premium for mocking researchers.
* When Inclusive language was moved to Premium, the specs were not moved yet. 
* This PR needs to be merged before [the free PR on re-applying the unit-tests for inclusive language in premium](https://github.com/Yoast/wordpress-seo-premium/pull/3687). Otherwise the travis tests on the latter won't pass. 
* Exposes the Factory class for it to be used in Inclusive language tests in Premium
* 
* All relevant test instructions are …

PC-528 Exposes Factory class for running Inclusive language tests in Premium

---

.eslintrc
packages/analysis-report/package.json
packages/analysis-report/src/AnalysisList.js
packages/components/package.json
packages/components/src/Collapsible.js
packages/components/src/ErrorBoundary.js
packages/components/src/HelpText.js
packages/components/src/IconButtonToggle.js
packages/components/src/ScoreAssessments.js
packages/components/src/Textarea.js
packages/components/src/Textfield.js
packages/components/src/Toggle.js
packages/components/src/a11y/ScreenReaderShortcut.js
packages/components/src/input/Input.js
packages/components/src/select/Select.js
packages/components/src/table/ListTable.js
packages/configuration-wizard/package.json
packages/configuration-wizard/src/ConfigurationWizard.js
packages/configuration-wizard/src/Step.js
packages/configuration-wizard/tests/wizardTest.js
packages/js/package.json
packages/js/src/components/PrimaryTaxonomyFilter.js
packages/js/src/reindex-links.js
packages/search-metadata-previews/package.json
packages/search-metadata-previews/src/helpers/animations.js
packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
packages/search-metadata-previews/src/snippet-preview/HelpTextWrapper.js
packages/yoast-components/package.json
packages/yoastseo/src/app.js
packages/yoastseo/src/scoring/assessments/readability/TextPresenceAssessment.js

* Fixes ESLint errors showing up in every PR.
* Fixes ESLint errors in the CI build
*
* This build should have no visible ESLint errors when looking at the files changes.
* All the changed components should remain the same:
* Collapsible: visible in the metabox.
* ErrorBoundary: used in the SEMRush country selector.
* IconButtonToggle: used for the eye icon after assessment results.
* ScoreAssessments: used in the dashboard widget.
* Textarea: Used for multiline inputs in the configuration wizard.
* Toggle: Used for the cornerstone toggle, to toggle Wincher keyphrase tracking and to toggle WordProof timestamps.
* AnalysisList: …

Fix eslint errors

---

packages/yoastseo/src/helpers/index.js

* Exposes `createAnchorOpeningTag` to be used in [this PR](https://github.com/Yoast/wordpress-seo-premium/pull/3695) for adding tracking parameters to shortlinks of inclusive language analysis.
* Exposes the `createAnchorOpeningTag` for adding tracking parameters to shortlinks in premium.
*
* Test together with https://github.com/Yoast/wordpress-seo-premium/pull/3695
*
*
Fixes #

PC-527-exposes-function-to-add-tracking-parameters

---

src/conditionals/primary-category-conditional.php

* Adds the possibility to use primary category in post URL at additional admin pages using filter.
`changelog: enhancement`
* Adds the possibility to use primary category in post URL at additional admin pages using filter.
* Adds a `wpseo_primary_category_admin_pages` filter to enabled the Primary Category feature in additional admin pages beside the default ones. Props to @ssvet.
* NA: we don't use the primary category in other admin pages except the default ones, so we just need to check that the feature still works as expected.
*
*
Fixes # …

Adds the possibility to use primary category at additional admin pages

---

.github/workflows/cs.yml
.github/workflows/integrationtest.yml
.github/workflows/jslint.yml
.github/workflows/jstest.yml
.github/workflows/lint.yml
.github/workflows/unittest.yml
config/grunt/custom-tasks/ensure-pre-release-branch.js
packages/ui-library/scripts/publish-storybook.sh

* Prepare the wordpress-seo repo for a switch from a `master` repo to a `main` repo.
***This is a work in progress*** ⚠️ 
* Prepares the repository for a rename of the master to  the main branch.
*
*
*
*
Fixes #

Add master to main replacements

---

src/helpers/indexing-helper.php
src/repositories/indexable-repository.php

*
* Adds two helpers to decide whether the indexables button should show.
* These helper methods are needed for the other SEO optimization issues (PC-68, PC-683 and PC693) to function.
* These helper methods are not yet used in the code.
* N/A: This PR adds two helper methods that are not yet used in the code, but are needed for three other issues (see technical choices above).
*
*
Fixes #

Add helpers for indexables button

---

admin/tracking/class-tracking-default-data.php

To determine the size of the sites we're optimizing for.
* To determine the size of the sites we're optimizing for.
* Adds posts and page counts to tracked data.
* Not sure how we test tracking honestly. Tracking data should contain `countPosts` and `countPages` variables.
None.
Fixes [PC-732]
[PC-732]: https://yoast.atlassian.net/browse/PC-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add the number of posts and pages to tracking

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/integrationtest.yml
.github/workflows/jslint.yml
.github/workflows/jstest.yml
.github/workflows/lint.yml
.github/workflows/unittest.yml
config/grunt/custom-tasks/ensure-pre-release-branch.js
packages/ui-library/scripts/publish-storybook.sh

* Change all necessary master references related to the Github repository to main
* Change all necessary `master` references related to the Github repository to `main`
*
* N/A
*
*
Fixes #

preparie rename master 2 main

---

readme.txt

*
* Add 'What happens to my data if I enable usage tracking?' to the readme FAQ
*
* Look in the readme.txt in the FAQ section for 'What happens to my data if I enable usage tracking?'
* Proofread for phrasing and grammar.
* The first shortlink should go to https://yoast.com/help/yoast-seo-usage-tracking/ and the second one to https://yoast.com/privacy-policy/.
*
* N/A
Fixes #

Add 'What happens to my data if I enable usage tracking?' to the readme FAQ

---

packages/yoastseo/src/scoring/assessments/SCORING SEO.md

*
* [yoastseo] Updates the documentation for _single title_ assessment.
*
* CR - Make sure that the documentation table for single title assessment looks good.
*  N/A - this PR is only updating documentation. No test is required for this PR
* N/A - this PR is only updating documentation. No test is required for this PR
*
*
Fixes #

PC-876 update single title assessment documentation in the readme file

---

packages/yoastseo/README.md
packages/yoastseo/src/scoring/README.md
packages/yoastseo/src/scoring/assessments/README.md
packages/yoastseo/src/scoring/assessments/SCORING INCLUSIVE LANGUAGE.md
packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md

*
* Adds documentation about the inclusive language analysis.
* Updates the documentation that said that only English had morphological support.
* The list of supported languages in the `yoastseo` README file was divided into readability, SEO, and inclusive language
* Checks whether the added documentation appears without issues on Github
* Confirm that all the added links work (exception: the links to the supported languages overview will not point to the right headings yet, since these headings are not yet on `trunk`).
*
*
Fixes #

Adds documentation for the inclusive language analysis

---

packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md

*
* [yoastseo] Updates the analysis documentation for transition words assessment.
*
* NA -> this PR is only updating a documentation
* N/A - this PR is only updating a documentation 
*
*
Fixes #

Update transition words documentation

---

admin/views/tabs/dashboard/webmaster-tools.php

The Baidu Webmaster tools link on line 50 directs to a 403 forbidden page. This PR fixes this and resolves issue: https://github.com/Yoast/wordpress-seo/issues/19108
*
* Update the link to Baidu Webmaster Tools, props [@SavPhill](https://github.com/SavPhill).
*
*
*
*
Fixes #

Fix broken url

---

tests/unit/helpers/robots-txt-helper-test.php

* Improve tests
* Improve tests
*
* _N/A_

Tests: fix three loose comparisons

---

admin/formatter/class-post-metabox-formatter.php
admin/tracking/class-tracking-plugin-data.php
config/dependency-injection/deprecated-classes.php
inc/class-wpseo-admin-bar-menu.php
src/actions/indexables-page-action.php
src/deprecated/src/integrations/admin/ryte-integration.php
src/deprecated/src/services/health-check/curl-check.php
src/deprecated/src/services/health-check/curl-reports.php
src/deprecated/src/services/health-check/ryte-check.php
src/deprecated/src/services/health-check/ryte-reports.php
src/helpers/post-helper.php
src/helpers/robots-txt-helper.php
src/integrations/admin/health-check-integration.php
src/integrations/front-end/robots-txt-integration.php
src/services/health-check/default-tagline-check.php
src/services/health-check/default-tagline-reports.php
src/services/health-check/links-table-check.php
src/services/health-check/links-table-reports.php
src/services/health-check/page-comments-check.php
src/services/health-check/postname-permalink-check.php
src/values/robots/directive.php
src/values/robots/user-agent-list.php
src/values/robots/user-agent.php
tests/unit/helpers/robots-txt-helper-test.php
tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
tests/unit/presenters/robots-txt-presenter-test.php
tests/unit/routes/indexables-page-route-test.php

* Documentation consistency
* Documentation consistency
*
* _N/A_

CS: various doc fixes

---

config/grunt/task-config/update-changelog-to-latest.js
readme.txt

* Update changlog format (both in file and creation settings)
* Update changlog format (both in file and creation settings)
*
* read the new changelog, test of the grunt task was done with a Jenkins test setup.
*
*
Fixes #

Update changlog format (both in file and creation settings)

---

tests/unit/doubles/models/seo-links-mock.php

* SEO_Links_Mock: sync the list of declared properties with the properties listed in the class docblock of the `Yoast\WP\SEO\Models\SEO_Links` class.
* _N/A_ This is a test only change, if the build passes, we're good.

Tests/SEO_Links_Mock: sync the list of declared properties

---

css/src/new-settings.css
packages/js/src/settings/app.js
packages/js/src/settings/components/fieldset-layout.js
packages/js/src/settings/components/search.js
packages/js/src/settings/components/sidebar-recommendations.js
packages/js/src/settings/routes/site-basics.js
packages/js/src/settings/routes/site-features.js
packages/postcss-preset/package.json
packages/tailwindcss-preset/package.json
packages/ui-library/package.json
packages/ui-library/src/components/sidebar-navigation/index.js
packages/ui-library/src/components/sidebar-navigation/style.css
tailwind.config.js
yarn.lock

* Improve responsive behaviour of new settings UI.
* Improves the responsive behaviour of new settings UI.
*
* Verify that the mobile menu appears at the same breakpoint the WP mobile menu appears.
* With Premium disabled: on `Site features`, verify that the breakpoints are set so that the Premium upsell buttons and toggles in card footers never break lines (in English language).
* With Premium disabled: on a post type or taxonomy, verify that section titles/descriptions are placed above the fields they describe from 1536px downward.
* With Premium enabled: on `Site features`, verify that the breakpoints are set so that the toggles in card footers never break lines (in …

Dupp 683 new settings UI responsive improvements

---

packages/ui-library/src/elements/file-input/index.js
packages/ui-library/src/elements/file-input/stories.js

* Rename all `isDisabled` props for form field components to `disabled`.
* Rename `isDisabled` props to `disabled` in the files related to file input component. That includes the index file of that component and it's story file.
*
* Open story book and test file input component disable functionality. 
*
*
Fixes #

refactor: rename is Disable to disable

---

packages/js/src/integrations-page/plugin-integrations.js
packages/js/src/integrations-page/seo-tools-integrations.js

*
*  Change the claim messages and the logo shortlinks on the integrations page.
* Semrush already had a different shortlink for the logo so we're not touching it
* The copy for TEC will be provided in issue DUPP-781
* visit the integrations page
* check that all the logos (except Semrush) have shortlink following this format: `https://yoa.st/integrations-logo-[NAME-OF-THE-INTEGRATION]`
* Check that they are different from the "Learn more" links, which we didn't touch in this PR and have the format `https://yoa.st/integrations-about-[NAME-OF-THE-INTEGRATION]`
* check that all the integrations claims display the new copy from https://yoast.atlassian.net/browse/PC-794 (note …

DUPP-777 Change claim messages and logo links for integrations 

---

css/src/new-settings.css

* Fixes minor CSS issues in new settings UI.
* Fixes minor CSS issues in new settings UI.
*
* Verify that a triple click in a replacement variable editor field **that contains variables** correctly selects all content in that field. So text **and** variables are all selected after triple click.
* Verify that the emoji picker opens to the right under the emoji button on RTL languages.
* Verify that the `Thanks for creating with WordPress` tagline is neatly aligned with our content.
*
*
Fixes #

Fix minor CSS issues in new settings UI

---

README.md
packages/js/jest.config.js
packages/js/package.json
packages/js/tests/settings/__snapshots__/search.test.js.snap
packages/js/tests/settings/search.test.js

* Connected to issue [CR & acceptance testing of new settings UI phase 6 branch](https://yoast.atlassian.net/browse/DUPP-672) 
* Created 6 unit tests and 1 snapshot test for search functionality
* Created 6 unit test and 1 snapshot test for search functionality
*
*
*
*
Fixes #

DUPP-710-unit-test-for-search-functionality-in-feature-new-settings-ui_clean

---

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js

* While generating the Inclusive Language database I noticed some spec files were failing. The cause was that recently a new key was added to the `Mark` function but was missing from the expected result in the spec file.
* Adds a new key to the assessor properties to fix failing test files for Inclusive language.
*
* Inside `packages/yoastseo`, run the inclusive language unit tests through `yarn test inclusiveLanguage`
* Make sure that all tests pass
*
*
Fixes #https://yoast.atlassian.net/browse/PC-980

Edit spec file to fix failing tests for Inclusive Language

---

packages/ui-library/src/elements/file-input/stories.js

* Add stories for FileInput regarding description, disabled and icon prop.
* Add stories for FileInput regarding description, disabled and icon prop.
*
* Open storybook and go to FileInput, check if the stories are there and are clear.
*
*
Fixes #

Dupp 736 create better file input stories

---

css/src/new-settings.css
packages/js/package.json
packages/js/src/first-time-configuration/first-time-configuration-steps.js
packages/js/src/settings/app.js
packages/js/src/settings/components/error-fallback.js
packages/js/src/settings/components/search.js
packages/js/src/settings/components/sidebar-recommendations.js
packages/js/src/settings/routes/site-features.js
packages/ui-library/src/components/modal/style.css
packages/ui-library/src/elements/select/index.js
yarn.lock

* Fixes various minor issues found during QA testing of new settings UI `alpha`.
* Fixes various minor issues found during QA testing of new settings UI `alpha`.
* Downgraded `react-hotkeys-hook` package for now due to an issue with [Chrome autocomplete](https://yoast.atlassian.net/browse/QA-4086).
* Verify that [this QA issue](https://yoast.atlassian.net/browse/QA-4086) is no longer reproducible.
* Verify that [this QA issue](https://yoast.atlassian.net/browse/QA-4087?atlOrigin=eyJpIjoiNTI3YzRmYmZiZTJjNDJhMTliODI4MmQyYzY2OWEzNTQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) is no longer reproducible.
* Verify that the `Discard changes` modal (make a change, then click `Discard …

Dupp 808 settings UI bugs found in alpha test

---

packages/ui-library/src/elements/radio/stories.js

* Separated isLabelDangerousHtml prop example from variants story. Refactor docs.
* Separated isLabelDangerousHtml prop example from variants story. Refactor docs.
*
*
*
*
Fixes #

Dupp 737 improve radio element stories for is label dangerous html prop

---

packages/ui-library/src/elements/table/stories.js

* Add stories to Table element.
* Adds stories to Table element.
*
* Open storybook and check Table element stories
*
*
Fixes https://yoast.atlassian.net/browse/DUPP-752

UI library: docs: table element stories

---

packages/ui-library/src/components/card/index.js
packages/ui-library/src/components/card/stories.js

* Add story to Card component and fixed className props.
* Add story to Card component and fixed className props.
*
* Open storybook and go to Card component, check story and story props.
*
*
Fixes #

Dupp 731 create card stories

---

packages/ui-library/src/elements/tag-input/index.js
packages/ui-library/src/elements/tag-input/stories.js
packages/ui-library/src/elements/tag-input/style.css

* Use of Badge component in TagInput.
* Match the styling to the given reference.
* Fix story functionality.
* Use of Badge component in TagInput.
* Match the styling to the given reference.
* Fix story functionality.
*
* Open storybook and test TagInput Element.
*
*
Fixes #

fix: used Badge component in TagInput and style it.

---

packages/ui-library/src/components/checkbox-group/index.js
packages/ui-library/src/components/checkbox-group/stories.js
packages/ui-library/src/components/checkbox-group/style.css
packages/ui-library/src/components/radio-group/stories.js
packages/ui-library/src/components/radio-group/style.css
packages/ui-library/src/elements/checkbox/index.js
packages/ui-library/src/elements/checkbox/stories.js
packages/ui-library/src/elements/checkbox/style.css

* Add documentation/story about `CheckboxGroup`  children prop.
*Add documentation/story about `CheckboxGroup`  children prop.
*
* Open storybook and go to "CheckGroup" component and find `children` prop documentation and story.
*
*
Fixes #

DUPP-732-revisit-checbox-group-stories-based-on-changes

---

packages/ui-library/src/elements/spinner/index.js
packages/ui-library/src/elements/spinner/stories.js

* Add stories to Spinner element
* Add stories to Spinner element
*
* Open storybook and test spinner element stories.
*
*
Fixes [DUPP-784](https://yoast.atlassian.net/browse/DUPP-854)

UI library: docs: add stories to spinner element

---

packages/ui-library/.storybook/preview.js
packages/ui-library/src/hooks/hooks.stories.mdx
packages/ui-library/src/hooks/readme.md
packages/ui-library/src/hooks/use-svg-aria.js
packages/ui-library/src/introduction.stories.mdx

**This PR is a cleaned up copy of https://github.com/Yoast/wordpress-seo/pull/19369**
* Add documentation for the hooks. 
* Add documentation for the hooks. 
*
* Open story book and look in the end of the menu for `Other exports/Hooks`. Check if the documentation are clear to understand and are true to the hooks functionality.
*
*
Fixes [DUPP-753](https://yoast.atlassian.net/browse/DUPP-753)

UI library: Dupp 753 document other exports in storybook 2

---

css/src/new-settings.css
packages/js/src/indexables-page/indexables-page.js
packages/js/src/settings/components/form-layout.js
packages/js/src/settings/components/search.js
packages/ui-library/src/components/modal/index.js
packages/ui-library/src/components/modal/stories.js
packages/ui-library/src/components/modal/style.css

* Add story to Modal component regarding the `initialFocus` prop.
* Add story to Modal component regarding the `initialFocus` prop.
*
* Open storybook on Modal and test the story for initialFocus. Is it clear enough?
*
*
Fixes [DUPP-720](https://yoast.atlassian.net/browse/DUPP-720)

UI library: DUPP-720 after cherrypick: prepare modal component for release

---

.gitignore
gulpfile.js
package.json
yarn.lock

Hackaton: Artifacts Copy + Compress + Clean

---

packages/js/package.json
packages/js/src/settings/components/search.js
yarn.lock

* Bumps `react-hotkeys-hook` dependency to newest version.
* Bumps `react-hotkeys-hook` dependency to newest version.
*
* Visit the new settings UI.
* Verify that [the QA issue](https://yoast.atlassian.net/browse/DUPP-838) is no longer reproducible.
* Verify that `cmd+k` or `ctrl+k` (depending on OS) opens the search and focuses the search field.
* Verify that `cmd+k` or `ctrl+k` (depending on OS) opens the search and focuses the search field **while you're focused in a text field.**
*
* No impact outside new settings UI.
Fixes # …

Settings UI: Update react-hotkeys-hook dep to 4.0.5 version

---

.github/CODEOWNERS

* This introduces a CODEOWNERS file to define individuals or teams that are responsible for code in a repository. Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. If a file has a code owner, you can see who the code owner is before you open a pull request. In the repository, you can browse to the file and hover over.
* The CODEOWNERS file will be used to keep @Yoast/team-ui-library aware of changes in the `packages/ui-library` directory.
* Introduces a CODEOWNERS file to defined the Yoast UI library team as owner of the @yoast/ui-library NPM package.
* 
* This file will probably go into effect *after* …

Introduce the CODEOWNERS file for the UI library

---

packages/js/src/settings/components/form-layout.js

* Removes the blank area from settings pages that do not have much content.
* Removes the blank area from settings pages that do not have much content.
*
* Go to Settings > Advanced > Special pages
* Verify you no longer see the blank area under the form fields
* Screenshot with blank area ![image](https://user-images.githubusercontent.com/35524806/209646706-e09463aa-e593-4eb9-8403-a1454cf90509.png)
* Screenshot without blank area ![image](https://user-images.githubusercontent.com/35524806/209646572-dae68261-8d94-4e2a-a932-3396a9749ac6.png)
*
* …

Settings: Remove the minimum form height

---

packages/js/src/settings/routes/crawl-optimization.js

* Improves description for  `Additional URL parameters to allow` in settings.
* Improves description for  `Additional URL parameters to allow` in settings.
*
When Premium is enabled:
* Open `YoastSEO`->`Settings`->`Advanced`->`Crawl optimization`
* Scroll to the bottom of the page
* Enable the `Remove unregistered URL parameters` setting toggle
* Add extra parameters using either a comma or pressing enter
* Check description to match:
*
*
Fixes [Minor: Improve description for 'Additional URL parameters to allow' …

Settings-UI: #317 improve description for additional url parameters to allow

---

readme.txt

* update date format in readme.txt
* update date format in readme.txt
*
* verify readme.txt
*
*
Fixes #

update date format in readme.txt

---

package.json
yarn.lock

* Updates the `plugin-grunt-tasks` dependency to 2.4 ( this will change the initial date format to yyyy-mm-dd when creating a new RC).
* Updates a dependency from `master` to `main`.
* Updates the `plugin-grunt-tasks` dependency to 2.4 ( this will change the initial date format to yyyy-mm-dd when creating a new RC).
* Updates a dependency from `master` to `main`.
*
* none
*
*
* [] This PR falls under an innovation project. I have attached the `innovation` label and noted the work hours.
Fixes #

update plugin-grunt-tasks to 2.4

---

packages/ui-library/src/elements/toggle/style.css

*
* [@yoast/ui-library] Increases the contrast of the `Toggle`.
* Increases the contrast of the Settings toggles.
*
* Go to Settings > Site features
* Verify the feature toggles are a bit darker when turned off
* Compared to before (from issue):
This also influences all other places the Toggle is used:
* Throughout the Settings
* Integrations page
But since this is just the style, I don't think much checking is needed here.
*
* Anywhere the UI library Toggle (or ToggleField) is used.
Fixes https://github.com/Yoast/wordpress-seo/issues/19522

Settings / UI library: increase the Toggle contrast a little

---

packages/js/src/settings/components/introduction.js
packages/js/tests/settings/__snapshots__/search.test.js.snap
packages/ui-library/src/components/modal/index.js

Reverts Yoast/wordpress-seo#19650

Revert "Dupp 900 introduction modal dialog accessibility"

---

packages/js/src/settings/components/search.js
packages/js/src/settings/hooks/use-router-scroll-restore.js

* Fixes scroll to result when searching for a value more than once.
* Fixes scroll to result when searching for a value more than once.
* The result area is targeted via `id` (for example when searching `map`) and via `data-id` (for example when searching `pretty`). I targeted both scenarios. 
* Open `YoastSEO`->`Settings`
* Click on `Search` and when the dialog opens search for the `pretty`.
* When you reach the result, scroll to the top of the page and search again for `pretty` and click the result. 
* Check you are directed to the result area in the same way you were before (smooth scroll to the result).
* Start a new search for `map`
* Click on the result and see you …

Settings ui: 337 minor issue with inconsistent search behavior

---

admin/formatter/class-metabox-formatter.php
packages/js/src/containers/SnippetEditor.js
packages/js/tests/containers/SnippetEditor.test.js
packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js

⚠️ Accidental merge in `release/20.0`. This is just a revert, will merge into `trunk` later.
* Reverts Yoast/wordpress-seo#19406.
* N/A
Fixes

Revert "DUPP-822-update-mobile-previews-to-account-for-site-name"

---

packages/js/src/settings/readme.md

* Document primary libraries and concepts used in new settings UI.
* Document primary libraries and concepts used in new settings UI.
* None.
* Verify that the documentation makes sense. Please feel free to add documentation if needed.
* This is a documentation PR, so **no QA testing needed**.
* This is a documentation PR, so **no QA testing needed**.
* No impact, documentation only.
Fixes #
https://yoast.atlassian.net/browse/DUPP-699

Document primary libraries and concepts used in new settings UI

---

src/integrations/settings-integration.php

* We want to make sure all characters are allowed when setting permalinks for posttypes/taxonomies.
* Fixes a bug where the settings page of a post type would not load when a special character like ט was added as permalink.
*
* Add /טסט/ to your Product permalink structure under Settings → Permalinks → Product permalinks → "Custom base" and also under Product categories and Product tags.
*Go to SEO > Settings > Content Types > Products
* You should now the settings for this content type.
Same goes when you put it in Product tags/categories permalinks - see screencast below.
* …

Add url encode voor special characters in routes.

---

packages/js/src/settings/components/introduction.js

* Add lazy loading attributes the images in introduction modal.
* Adds lazy loading attributes to images in the introduction modal.
* Enable the settings Introduction modal
* Go to `YoastSEO`->`Settings`
* Open console and inspect images and check they have `loading="lazy"` and `decoding="async"` attributes.
*
*
*
Fixes [Trivial: Images in the "welcome" modal should lazy load](https://github.com/Yoast/plugins-automated-testing/issues/377)

settings-UI: Added lazy loading attributes to introduction modal images.

---

src/presenters/admin/sidebar-presenter.php

* Fix typo at the rating stars image fetch priority attribute.
* Fixes a typo at the rating stars image `fetchpriority` attribute. Props to [@fellyph](https://github.com/fellyph).
* Make sure premium plugin is disable.
* Inspect Sidebar rating stars and check they have attribute `fetchpriority` and not `fetchpriorty`.
* 
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/19505
https://github.com/Yoast/wordpress-seo/pull/19509

adding typo fixes

---

src/integrations/third-party/elementor.php

* We want to remove all calls to `filter_input` in our codebase.
* We want to remove `FILTER_SANITIZE_STRING` because it is deprecated.
* Prevents a deprecation notice that was thrown in PHP 8.1 when saving a post in Elementor.
*
* Install and activate Yoast SEO and Elementor.
* Go to a post editor and open the Elementor editor.
* Click on the hamburger menu on the top left and click on Yoast SEO.
* Verify that the Yoast SEO metabox loads as expected.
* Now click on Google preview and change the slug of the post.
* Save the post and refresh the page, verify that the slug changed correctly.
*
This PR affects the following parts …

DUPP-670 Refactor filter_input and FILTER_SANITIZE_STRING in Elementor integration

---

packages/js/src/structured-data-blocks/convertValueToStringRichText.js

* We want to revert [Yoast/wordpress-seo#19835](https://github.com/Yoast/wordpress-seo/pull/19835).
* Reverts [Yoast/wordpress-seo#19835](https://github.com/Yoast/wordpress-seo/pull/19835).
*
*
*
Fixes [19835](https://github.com/Yoast/wordpress-seo/pull/19835)

Revert "escaped quotes in alt of images in how-to and faq blocks"

---

packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js

* Fix google preview in Elementor
* Fixes line-height and color of google preview in Elementor.
*
* Install and activate Elementor
* Create a post with Elementor and save.
* Create a post without Elementor and save.
* Compare google preview in both posts and check:
* Line height of description is the same in mobile preview.
* Color of description text is the same in Desktop Preview.
*
*
Fixes [#19905](https://github.com/Yoast/wordpress-seo/issues/19905)

19905 elementor styles on google preview are broken

---

packages/analysis-report/src/AnalysisResult.js

* There is warning in the console when start to edit post
* [analysis-report] Fixes console warning about the invalid prop **marker** when editing a post.
* [shopify-seo] Fixes console warning about the invalid prop **marker** when editing a post.
*
* Open developer console
* Start to edit any post
* Click on the Readability analysis collapsible
* Confirm that no message "Warning: Failed prop type: Invalid prop `marker` of type `function` supplied to `AnalysisResult`, expected `array`" in the console or  "Warning: Failed prop type: Invalid prop `marker` of type `array` supplied to `AnalysisResult`, expected `function`"
* …

Warning: Failed prop type: Invalid prop marker of type function supplied to AnalysisResult, expected array#19895

---

packages/yoastseo/spec/fullTextTests/runFullTextTests.js
packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
packages/yoastseo/spec/scoring/assessments/seo/TextTitleAssessmentSpec.js
packages/yoastseo/src/scoring/assessments/index.js
packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js

* Puts the code of textTitleAssessment inside the `yoastseo` package and register it in Premium.
* In the code the assessment is called TextTitleAssessment yet towards users it is called the Title assessment.
* Should be merged and tested together with https://github.com/Yoast/wordpress-seo-premium/pull/3856
* [yoastseo] Adds the _title assessment_ to the yoastseo package.
* No FullTextTests were created for product pages and collection pages as Text Title assessment is not available for shopify.
* Test Text Title Assessment: Perform [section 1.3.1 from the atp](https://docs.google.com/document/d/1fWX_8YkvSqcsqmwan_gwJjYqGOKIcTBTv0FbLKz47ig/edit#heading=h.cy2egg76v5is)
* …

17 restructuring yoastseo correctly bundle the title assessment

---

packages/js/src/settings/components/formik-tag-field.js

* Add type check to formik tag value to avoid error `split is not a function`.
* Adds type check to formik tag value to avoid error `split is not a function` after importing custom fields to page analysis.
* 
* Have Premium activated
* Go to `Yoast SEO`->`Settings` > `Content types`> `Pages`
* Scroll to the bottom and add a tag to the `Add custom fields to page analysis`
* Save
* Go to `Yoast SEO`->`Tools`->`Import and export`
* Go to `Export settings` tab, export, copy data.
* Go to `Import settings` tab and paste the data.
* Go to `Yoast SEO`->`Settings` > `Content types`> `Pages`
* Check no error appears
* …

Add type check

---

tests/unit/integrations/admin/crawl-settings-integration-test.php

* Add unit tests to the `crawl settings integration` class.
* Adds unit tests to the `crawl settings integration` class.
* 
* The tests are already executed and checked in the CI process.
*
*
Fixes [Crawl cleanup: enhance test coverage for crawl-cleanup related integrations](https://github.com/Yoast/wordpress-seo/issues/19988)

19988 crawl settings integration unit tests

---

packages/js/src/bulk-editor.js

* Updates a js file.
* Changes to the bulk editor.
*
* Go to /wp-admin/admin.php?page=wpseo_tools&tool=bulk-editor and add a value in the `New Yoast SEO Title`. Open the post in the post editor and make sure you see the same value there.
*
*
Fixes #

update bulk editor js.

---

packages/js/src/initializers/admin.js

* This is part of some code cleaning.
* Removes an unused `wpseoDetectWrongVariables` function.
*
* This should have no impact at all. Just make sure there are no console errors while in the admin.
*
* Open a post and add a replacement variable to see if that triggers any console errors.
Fixes #

Remove old unused function.

---

packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js

* We want to fix how we display the vertical dots in the Google Snippets preview.
* Handles long breadcrumbs and site name to accomodate the vertical dots in Google Snippets previews.
* [shopify-seo] Handles long breadcrumbs and site name to accomodate the vertical dots in Google Snippets previews.
* N/A
* Edit or create a post 
* In the right sidebar, edit the post's permalink to be very long
* Verify that both the mobile and desktop previews display the three dots correctly and truncates the breadcrumbs with a final `...`
* Go to `Yoast SEO`-> `Settings` -> `Site Basics`
* Enter  a very long string in `Website name`
* Edit a post and verify for both for mobile and …

Fix vertical dots in preview for long breadcrumbs

---

packages/ui-library/src/elements/alert/docs/component.md
packages/ui-library/src/elements/alert/docs/index.js
packages/ui-library/src/elements/alert/docs/variants.md
packages/ui-library/src/elements/alert/stories.js
packages/ui-library/src/elements/badge/docs/component.md
packages/ui-library/src/elements/badge/docs/index.js
packages/ui-library/src/elements/badge/docs/sizes.md
packages/ui-library/src/elements/badge/docs/variants.md
packages/ui-library/src/elements/badge/stories.js
packages/ui-library/src/elements/button/docs/component.md
packages/ui-library/src/elements/button/docs/index.js
packages/ui-library/src/elements/button/docs/sizes.md
packages/ui-library/src/elements/button/docs/states.md
packages/ui-library/src/elements/button/docs/variants.md
packages/ui-library/src/elements/button/stories.js
packages/ui-library/src/elements/button/variants.md
packages/ui-library/src/elements/checkbox/docs/component.md
packages/ui-library/src/elements/checkbox/docs/disabled.md
packages/ui-library/src/elements/checkbox/docs/index.js
packages/ui-library/src/elements/checkbox/stories.js
packages/ui-library/src/elements/radio/docs/component.md
packages/ui-library/src/elements/radio/docs/dangerous-label.md
packages/ui-library/src/elements/radio/docs/index.js
packages/ui-library/src/elements/radio/docs/variants.md
packages/ui-library/src/elements/radio/stories.js
packages/ui-library/src/elements/toggle/docs/component.md
packages/ui-library/src/elements/toggle/docs/index.js
packages/ui-library/src/elements/toggle/stories.js

*
* [@yoast/ui-library 0.1.0] Adds documentation to the elements: `Alert`, `Badge`, `Button`, `Checkbox`, `Radio` and `Toggle`.
*
* Start Storybook and check the element pages:
* Alert
* Badge
* Button
* Checkbox
* Radio
* Toggle
* For each of the above, verify if the documentation makes sense:
* Is it clear in which context the element should be used?
* Is it consistent?
* Is there redundant information?
*
* Only UI library Storybook.
Fixes #

UI library: Add documentation to certain elements

---

wp-seo.php

*
* Sets the minimum supported WooCommerce version to 7.1.
* Note: the `WC tested up to:` is expected to be upgraded by the RC creation script from now on, so I'm keeping it as it is even if it's not consistent.
* NA
* NA
*
Fixes #

Set the minimum supported WooCommerce version to 7.1.

---

readme.txt

* Since we're deprecating the Zapier integration, we shouldn't market it anymore.
* Remove Zapier marketing from readme.txt
*
* N/A
* N/A

Remove Zapier integration from readme

---

packages/js/src/settings/app.js

* Add key to SidebarNavigation.SubmenuItem in the taxonomy menu.
* Fixes a bug where a warning about a missing key in a component would be thrown in the console in the Yoast SEO Settings page.
*
* Add few taxonomies.
* Go to `Yoast SEO`->`Settings`
* Inspect page and check no errors are in the console regarding missing keys in SidebarNavigation.SubmenuItem components.
*
*
Fixes [19863](https://github.com/Yoast/wordpress-seo/issues/19863)

Added key to taxonomy submenu items

---

composer.lock

* Update dev dependencies
* Update dev dependencies
Refs:
* https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.0.5
* https://github.com/sebastianbergmann/diff/blob/3.0.4/ChangeLog.md
* _N/A_ If the tests run & pass, we're good.

Composer: update test dependencies

---

config/scripts/install-wp-tests.sh

Re-synced with the script from the WP-CLI scaffold-command repo.
Ref: https://github.com/wp-cli/scaffold-command/blob/eb8d71618de1e34264991109f91a8d8247601fb2/templates/install-wp-tests.sh
* _N/A_ If the integration tests still run and pass, we're good.

Integration tests: update script to install WP

---

.github/workflows/cs.yml

GH Actions: fix minor spelling snafu

---

tests/unit/builders/indexable-link-builder/abstract-indexable-link-builder-testcase.php

Tests: `TestCase` classes should be abstract

---

src/analytics/domain/missing-indexable-bucket.php
src/analytics/domain/to-be-cleaned-indexable-bucket.php
src/generators/breadcrumbs-generator.php
src/repositories/indexable-cleanup-repository.php
tests/integration/test-wpseo-functions.php

CS/QA: static closures should be declared as static

---

config/dependency-injection/loader-pass.php
src/analytics/application/missing-indexables-collector.php
src/commands/cleanup-command.php
src/deprecated/i18n/i18n-v3.php
src/deprecated/src/integrations/admin/social-templates-integration.php
src/generators/schema/howto.php
src/helpers/redirect-helper.php
src/helpers/short-link-helper.php
src/integrations/admin/activation-cleanup-integration.php
src/integrations/admin/crawl-settings-integration.php
src/integrations/admin/integrations-page.php
src/integrations/blocks/structured-data-blocks.php
src/integrations/front-end/open-graph-oembed.php
src/integrations/third-party/wincher.php
src/integrations/third-party/wordproof-integration-toggle.php
src/integrations/watchers/indexable-attachment-watcher.php
src/repositories/indexable-cleanup-repository.php
tests/integration/admin/watchers/test-class-indexable-post-watcher.php
tests/unit/helpers/short-link-helper-test.php
tests/unit/integrations/admin/activation-cleanup-integration-test.php
tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
tests/unit/repositories/indexable-cleanup-repository-test.php
wp-seo-main.php

* CS/QA: don't use FQN function calls in non-namespaced files
* CS/QA: use FQN constants in namespaced files
* CS/QA: use FQN function calls in namespaced files 
* _N/A_

CS/QA: use fully qualified function calls/constants in the right places

---

composer.json
packages/yoastseo/grunt/config/eslint.js

* QA
* QA
Lower thresholds to match the current reality to prevent new issues coming in.

CS/QA: lower thresholds

---

packages/js/src/decorator/helpers/markTinyMCE.js
packages/js/tests/decorator/helpers/markTinyMCE.test.js

* In #20073 a mistake was made that caused highlighting not being removed after undoing the highlight button. This pr fixes this bug.
* Fixes an unreleased bug where highlighting would not be removed when the highlighting was switched off in the classic editor.
* [shopify-seo] Fixes an unreleased bug where highlighting would not be removed when the highlighting was switched off in the classic editor.
* As part of  #20073 I implemented an early exit. This early exit was undone, because it caused problems. Therefore, also the spec testing if there was an early exit was removed.
* Install and activate classic editor.
* Install and activate yoastseo free (with the current fix …

fix mistake where it was impossible to undo highlighting.

---

packages/js/src/support/app.js

* Change the upsell shortlinks in support page sidebar.
* Changes the upsell shortlinks in support page sidebar.
*
* Go to `Yoast SEO`->`Support`
* Check sidebar link for `Get Yoast SEO Premium` is [https://yoa.st/jj](https://yoa.st/jj) (without the params)
* Check links for academy are [https://yoa.st/3t6](https://yoa.st/3t6) (without the params)
*
*
Fixes [Increase visibility of (premium) support](https://github.com/Yoast/roadmap/issues/153)

Changed upsell links for academy and premium in support page

---

apps/content-analysis/package.json
apps/content-analysis/src/index.js
apps/content-analysis/yarn.lock
packages/yoastseo/spec/specHelpers/getResearcher.js

* There was an unvalidated dynamic method call in one of our spec helpers, which is used in the content analysis app. This PR adds validation to this call.
* Removes an unvalidated dynamic method call in the content analysis app.
* Fixes a bug where the content analysis app did not work because yoastseo could not be imported.
* We followed the suggestion in https://github.com/Yoast/wordpress-seo/security/code-scanning/45
* This PR also fixes the content analysis app by adding `yoastseo` as a (local) dependency.
* Open the content analysis app:
* Navigate to `apps/content-analysis`.
* Run `yarn install`.
* Run `npm start`, which will open up the content analysis app in …

Removes an unvalidated dynamic method call

---

css/src/tailwind.css
packages/tailwindcss-preset/index.js

Reverts Yoast/wordpress-seo#20420

Revert "added default color for placeholder text"

---

packages/js/src/components/WebinarPromoNotification.js

* We want to change the copy for the webinar notification.
* Updates copy of our free webinar notification. 
*
* Create a new SEO manager user.
* Login as this user and go to YoastSEO -> General
* Make sure the notification has the same copy as the issue.
*
*
Fixes #

Update copy for webinar notification

---

packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js

* We want to align our messaging in the FTC with the content of the link.
* Changes the copy in the final step of the first time configuration.
*
* Open the FTC and go to the final step. 
* Confirm the copy is the same as in the issue.
*
*
Fixes #

Updates FTC copy.

---

src/integrations/settings-integration.php

*  We want to check if the post is published.
* Fixes a non released bug where pages would still show up when they were no longer published.
*
* The test instructions for this live in : https://github.com/Yoast/wordpress-seo-premium/pull/3998
*
*
Fixes #

Add check if the post is published.

---

packages/ui-library/src/elements/autocomplete/style.css

* We want to fix inconsistency of box shadow for the autocomplete field in ui library. 
* [@yoast/ui-library 0.1.0]Fixes a bug where box shadow would be missing when using autocomplete field.
*
* Go to `Yoast SEO`->`Settings`->`Site basics`
* Check the policies autocomplete fields have box shadow
*
*
Fixes #

Fixes box shadow for autocomplete field

---

readme.txt
tests/unit/bootstrap.php
wp-seo-main.php

*
* Sets the WordPress tested up to version to 6.3.
*
* NA
*
*
Fixes #

Sets the WordPress tested up to version to 6.3.

---

packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js

*
* Changes the AI generate title & description upsell' Premium badge to a Beta badge.
*
* Verify the Premium badge is now a Beta badge: color and text are different
* This happens on:
* The upsell modal in the editors
* The upsell modal in the Yoast admin pages
* To see the introduction again: reset the value in the database back to `0` (or delete the DB row). It is located in the user meta under the `_yoast_wpseo_introductions` key as `ai-generate-titles-and-descriptions-upsell`.
*
*
Fixes #

Change badge from premium to beta

---

packages/js/src/shared-admin/components/video-flow.js

* Fix for a PR that was recently merged [#20560](https://github.com/Yoast/wordpress-seo/pull/20560)
* Change AI introduction video background to white.
*
* Deactivate Yoast SEO Premium.
* Edit a post
* Scroll to the metabox or click on `Yoast SEO` tab in sidebar
* Click on `Use AI` in the Google preview above title or description fields. 
* Check you see the introduction modal 
* Clicking on the thumbnail leads to a permission question:
* Clicking allow
* Check video automatically plays
* Check there is no black frame in the video
*
*
Fixes …

change video background to white

---

css/src/first-time-configuration.css

*
* Changes unreleased visited button css.
*
- Go through the First Time Configuration stepper.
- On the last step, click the primary button.
- Go back to the FTC and make sure the button link color is still readable.
*
*
Fixes #

Removes purple visited color in FTC final step

---

inc/options/class-wpseo-option-wpseo.php
packages/js/src/settings/routes/site-features.js

* We want to have ai feature off by default, and show the beta label on the features page.
* Changes unreleased default on to default off of the ai feature
* Changes the unreleased new label to beta on the ai features card.
*
* Make sure that the feature card on /wp-admin/admin.php?page=wpseo_page_settings#/site-features show a `beta` label
* To test the default off/on behaviour refer to the premium pr: 
*
*
Fixes #

Change option and change label.

---

packages/js/src/settings/routes/site-features.js

* Add option to hide premium badge but show the premium upsell.
* Adds beta badge to site features and hides premium badge.
*
* Go to /wp-admin/admin.php?page=wpseo_page_settings#/site-features and make sure the ai card only has the beta badge with premium disabled and enabled. And that the other premium cards still have their badges.
*
*
Fixes #

Adds option to hide premium badge but show the premium upsell.

---

packages/js/src/components/social/SocialUpsell.js

Implemented
* Updating upsell copy for Social appearance previews
* Updates upsell copy for Social appearance previews.
* Check if social is not Twitter and replace it with "social"
**In the Sidebar**
* Click Improve your post with Yoast SEO.
* Open **Facebook preview**.
* In the opened modal make user that on top the message is 'Want to see how your content will look when it's shared on social media?'.
* Close modal.
* Click **Twitter preview**.
* In the opened modal make user that on top message is remain the same 'Want to see how your content will look when it’s shared on Twitter?'.
**In the metabox**
* Open **Social** tab.
* Check *Facebook preview* panel.
* On top …

Update upsell copy for Social appearance previews #20551

---

inc/options/class-wpseo-option-wpseo.php

*
* Fixes a bug where the multisite control of the `enable_ai_generator` option was disabled.
*
* Create multisite
* Install and activate Free & Premium
* Enable feature for a subsite
* Verify that the feature setting is turned on
* Verify that the feature is there in the editor
* Go to Network Admin and disable 'AI title & description generator' feature
* Go to subsite
* Verify that the feature setting is turned off and unable to turn back on due to `Network disabled`
* Verify that the feature is missing in the editor
*
*
Fixes …

Fix multisite control of the AI generator feature

---

packages/yoastseo/src/scoring/assessments/SCORING SEO.md

*
* [yoastseo] Updates documentation on scoring for the _keyphrase in image assessment_.
*
*
*
*
Fixes #https://github.com/orgs/Yoast/projects/51/views/1?pane=issue&itemId=23851083

Update documentation for keyphrase in image assessment

---

admin/class-expose-shortlinks.php
packages/js/src/components/social/SocialUpsell.js
packages/social-metadata-forms/src/SocialMetadataPreviewForm.js

* Improving upsell for social previews.
* Improves the upsell for social previews.
* FeatureUpsell component used to show upsell button.
* Make sure that Yoast SEO Premium deactivated.
* Open Social appearance tab
* Make use that Social Appearance and Twitter Appearance are fit the design
* Thumbnail image size should be 130px wide
* Make sure that Yoast SEO Premium deactivated.
* Open Social appearance tab
* Make use that Social Appearance and Twitter Appearance are fit the design
* Thumbnail image size should be 130px wide
* …

123 improve upsell for social previews

---

composer.json
composer.lock
config/php-scoper/deprecation-contracts.inc.php
config/php-scoper/guzzlehttp.inc.php
config/php-scoper/psr.inc.php
src/functions.php
tests/unit/bootstrap.php
wp-seo-main.php

* Update various non-dev dependencies which can use more recent versions now PHP 7.2 is the minimum supported PHP version.
* Updates external dependencies.
This is a first PR related to the plan to update the PHP dependencies as prepared by @diedexx @enricobattocchi and me during our office days end of May.
... with dependencies.
Includes:
* Adding the new `psr/http-client` and `psr/http-factory` dependencies to the PHP-Scoper configuration.
* Making a tweak to the PHP-Scoper configuration for the Guzzle dependencies.
* Removing the file inclusions for Guzzle Promises and Guzzle PSR7 related `functions` files from the test bootstrap file and the `src/functions.php` file.
For both Promises as well as PSR7, this file was removed in …

Composer: update select dependencies

---

packages/js/package.json
packages/ui-library/changelog.md
packages/ui-library/package.json

* Release `@yoast/ui-library:3.2.1`
* Bumps `@yoast/ui-library` to version 3.2.1.
*
*
*
*
Fixes #

Update UI library to release version 3.2.1

---

yarn.lock

* We always want to target the latest browsers when building our JavaScript. This PR makes sure that the list/db on what is considered the "latest browsers" is up to date and consistent across our JavaScript packages.
* Updates the list of the latest browsers to make sure that we target the latest browsers when building the JavaScript of the plugin.
* I executed this command to update the `caniuse-lite` database, as described in the warning message as seen below:
```sh
npx browserslist@latest --update-db
```
* During building, you should **not** see any messages like this:
```
Browserslist: caniuse-lite is outdated. Please run:
npx …
```

Updated caniuse-lite database for browserslist

---

packages/js/src/components/Indexation.js
packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation.js
packages/js/tests/indexation.test.js

*
* Migrates the tests in `packages/js/tests/indexation.test.js` to use the Testing library.
* Fixes a bug where the Indexation components would not be compatible with React 18 state batching.
* Wrap the `setState` calls in the `doIndexing` while loop with a `flushSync` to prevent batching.
* Did this also for the First-time configuration copy, even though that one has no tests.
* Have a site with a decent amount of content so the indexation actually has to loop a bit
* Reset the indexable tables (via the Yoast test helper)
* Go to Yoast SEO > Tools
* Run and verify the indexation still functions like before
* Reset the indexable tables (via the Yoast test helper)
* Go to …

Migrate indexation tests

---

packages/js/tests/components/PrePublish.test.js

*
* Migrates the PrePublish tests to use the Testing library.
*
* Does the CI pass?
* Do the tests still verify the things they did before? (compared to `trunk`)
* Just tests. No actual code change.
*
Fixes https://github.com/Yoast/wordpress-seo/issues/20670

Migrate PrePublish tests

---

packages/js/tests/components/AnalysisCheckList.test.js

*
* Migrates the AnalysisCheckList tests to use the Testing library.
*
* Does the CI pass?
* Do the tests still verify the things they did before? (compared to `trunk`)
* Just tests. No actual code change.
*
Fixes https://github.com/Yoast/wordpress-seo/issues/20669

Migrate AnalysisCheckList tests

---

phpunit-integration.xml.dist
phpunit.xml.dist

* Dev-file update
* Dev-file update
PHPUnit config: update schema reference to the minimum PHPUnit version which is currently in use.
The configuration has also been validates against the schema and where needed, updated.
* _N/A_

PHPUnit config: update schema reference

---

.eslintrc
packages/replacement-variable-editor/.eslintrc.js
packages/replacement-variable-editor/package.json
packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
packages/replacement-variable-editor/tests/ReplacementVariableEditorTest.js
packages/replacement-variable-editor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
packages/replacement-variable-editor/tests/test-utils.js

* Following the issue for upgrading to react 18 and migrating all enzyme tests to react testing library.
* [@yoast/replacement-variable-editor 0.0.1] Migrate replacement variable editor tests to react testing library.
* Changed the name of lifecycle hook componentWillReceiveProps to UNSAFE_componentWillReceiveProps to remove warning that the name has changed.
* Moved eslint rules to the package from root.
*
*
*
Fixes [#20675 ](https://github.com/Yoast/wordpress-seo/issues/20675)

20675 replacement variable editor replacement variable editortestsreplacementvariableeditortestjs

---

inc/class-wpseo-primary-term.php

Improve primary term performance.
* Improves performance in getting the primary term. Props to [nlemoine](https://github.com/nlemoine).
* Bails early when no meta is there, no need to get all post terms if we no have no term id to check against
* Make sure you have more than 1 category in your post's categories.
* Edit a post (while console is open)
* Check you do not get console errors related to the TaxonomyPicker component prop type.
* Add more than one category
* Check you see the select input box to select the primary category.
* Select a different Primary category and save.
* Refresh and check your selection was saved.
* …

Improve primary term helper performance

---

packages/js/src/integrations-page/acf-integration.js
packages/js/src/integrations-page/algolia-integration.js
packages/js/src/integrations-page/integrations-grid.js
packages/js/src/integrations-page/mastodon-integration.js
packages/js/src/integrations-page/plugin-integration.js
packages/js/src/integrations-page/schema-api-integrations.js
packages/js/src/integrations-page/simple-integration.js
packages/js/src/integrations-page/toggleable-integration.js
packages/js/src/integrations-page/woocommerce-integration.js

* We want to get rid of some warnings related to the mismatch between the expected and the actual type of some props. 
*  Specifies the correct prop type for props that can contain an interpolated string.
* N/A
* Open your browser's console
* Go to `Yoast SEO` -> `Integrations`
* Verify that:
* no warnings like `Warning: Failed prop type: Invalid prop 'integration.claim' of type 'object' supplied to 'ToggleableIntegration', expected 'string'.` are shown
* the following warnings are not shown
* `Warning: Failed prop type: The prop 'id' is marked as required in 'ForwardRef', but its value is 'undefined'.` 
* `Warning: Each child in a list should have a unique "key" prop.`
* …

Address integrations page warnings

---

admin/class-premium-upsell-admin-block.php
css/src/yst_plugin_tools.css

*
* Fixes Black Friday banner on first time configuration page.
*
* Make sure premium is not installed or activated
* Replace the following line in `src/promotions/domain/black-friday-promotion.php` line 18:
```php
new Time_Interval( \gmmktime( 11, 00, 00, 11, 23, 2022 ), \gmmktime( 11, 00, 00, 11, 28, 2023 ) )
```
* Check the space the upsell block has the Black Friday banner:
* Go to first time configuration and check the same upsell block appear like so:
* Restore `src/promotions/domain/black-friday-promotion.php` line 18
* Check the upsell block looks as expected
* …

1090 trivial black friday ad looks weird on first time configuration

---

packages/js/tests/components/contentAnalysis/KeywordInput.test.js

* Following the issue for upgrading to react 18 and migrating all enzyme tests to react testing library.
* Migrate KeywordInput tests to the React testing library.
* Settings the global `wpseoAdminL10n` variable before and deleting after (any/all the tests in the file). This side-effect in the component is unfortunate.
* I tried doing our `mockWindow` approach we have for `AnalysisField`, but that got me a strange error I didn't know how to solve.
* Does the CI pass?
* Do the tests still verify the things they did before? (compared to `trunk`)
* Just tests. No actual code change. …

Migrate KeywordInput tests

---

packages/js/src/components/UpsellBox.js
packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js

* We want to update some copy.
* Updates copy of the Premium SEO Analysis upsell.
*
* Disable premium.
* Edit a post and open the `Premium SEO analysis` upsell via the sidebar.
* Make sure it looks the same as this [sketch](https://www.sketch.com/s/f4295b89-a2ae-4a4d-a717-89e738dff74c/prototype/AC14CF6D-B79F-4C2C-A742-34C29B1AF332/a/AC14CF6D-B79F-4C2C-A742-34C29B1AF332) 
* Enable the black friday sale by editing /promotions/domain/black-friday-promotion.php and make sure the upsell looks like this [sketch](https://www.sketch.com/s/f4295b89-a2ae-4a4d-a717-89e738dff74c/prototype/EE25C771-5B59-41FB-8371-B579E9614911/a/EE25C771-5B59-41FB-8371-B579E9614911).
QA can test this …

Fix inconsistent copy

---

readme.txt
tests/unit/bootstrap.php
wp-seo-main.php

*
* Sets the WordPress tested up to version to 6.4.
*
*
*
*
Fixes #

Sets the WordPress tested up to version to 6.4

---

inc/options/class-wpseo-option-wpseo.php

* We want to enable the AI feature for new installs.
* Sets the ai feature to default on when using premium.
*
* This PR needs to be tested with a premium counterpart. The test instructions are in that [PR](https://github.com/Yoast/wordpress-seo-premium/pull/4107).
*
*
Fixes #

Changes the default value for the ai option and introduces a new option.

---

css/src/modal.css

* Fix header border bottom in product page upsell modal
* Add more configuration to upsell modal bottom border.
*
* Create a product
* Open one of the upsell modals
* Check header has border bottom.
*
*
Fixes [#1129](https://github.com/Yoast/plugins-automated-testing/issues/1129)

fix header border bottom in product page upsell modal

---

packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js

*
* Removes deprecated life cycle method `componentWillReceiveProps`.
*
* Edit a post or a page
* Go to the Google preview 
* Edit title, description and slug, add and remove variables.
* Open the console and check no errors appear.
* Check the preview is updated
* Save and refresh and check changes are saved.
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/19867

19867 replacing componentwillreceiveprops

---

packages/js/tests/components/WincherKeyphrasesTable.test.js
packages/js/tests/components/WincherTableRow.test.js

*
* Migrate Wincher table tests 
*
*
*
*
Fixes [Wincher feature: js/tests/components/WincherKeyphrasesTable.test.js and js/tests/components/WincherTableRow.test.js](https://github.com/Yoast/wordpress-seo/issues/20672)

20672 wincher tests

---

packages/yoastseo/spec/parse/build/private/parseBlocksSpec.js

* Add unit tests for parseBlocks.js inside yoastseo.
* Adds unit tests for parseBlocks.js inside yoastseo.
*
* cd into `packages/yoastseo` directory
* run `yarn test`
* make sure that all test are green
*
* This is unit tests for existing code so should not impact anything.
Fixes [#191](https://github.com/Yoast/lingo-other-tasks/issues/191)

Add unit tests for parseBlocks.js inside yoastseo#191

---

packages/js/src/initializers/admin.js

* Remove distractions during the FTC.
* Removes notices and upsell ads in the first time configuration.
*
* Check you see notices as expected and the upsell ads, sidebar and block.
* Go to `First time configuration` tab
* Check the notices and ads are hidden.
* Go back to `Dashboard` tab
* Check the notices and ads are restored.
*
*
Fixes [Remove disctractions during the FTC#55](https://github.com/Yoast/growth/issues/55)

Toggle notices and upsell ads in FTC

---

packages/js/src/components/WincherSEOPerformanceModal.js

*
* Fixes the `Track SEO performance` icon in the metabox.
* Using the same components as the new upsells.
* Using the same icon as in the sidebar (though slightly bigger).
* Edit a post
* Verify the icon next to `Track SEO performance` is looking good and is the same as in the sidebar
* Verify that clicking on it and opening the modal does not result in the icon changing (it would change to collapsible' chevron up)
*
* Metabox Wincher modal only
Fixes https://github.com/Yoast/wordpress-seo/issues/20826

Replace metabox open modal button

---

packages/js/src/components/MetaboxButton.js
packages/js/src/components/WincherSEOPerformanceModal.js

* We want to fix the `Track SEO performance` title misalignment in the Yoast metabox
* Fixes the alignment of the `Track SEO performance` title in Yoast metabox.
* N/A
* Activate Yoast SEO Premium
* Edit a post
* Verify `Track SEO performance` is left-aligned correctly
* disable Premium
* re-check that the alignment is still correct
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/1183

Fix title alignment

---

packages/js/src/components/WincherSEOPerformance.js
packages/js/src/components/WincherTableRow.js

- Display the ranking period select during the ranking days limit request with a default select options i.e. display it just after connecting.
- Fix the view button height on the classic editor.
- Classis editor:
- Block editor:
- Elementor editor:
*
*
* Add new post and a focus keyphrase
* Open "Track SEO Performance" modal
* Connect to Wincher
* Make sure the period select is displayed instantly after connecting to Wincher
* Make sure that the view button in the classic editor has the correct height.
* Make sure there is no regression regarding the view button height in both the block and the elementor editors
* 
This PR …

Wincher modal fixes

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/test.yml

* QA
* QA
Update a few links in inline comments as the old URLs are no longer valid.
* _N/A_

GH Actions: update a few links in inline comments

---

packages/js/src/first-time-configuration/first-time-configuration-steps.js
packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
packages/js/src/first-time-configuration/tailwind-components/steps/indexation/configuration-indexation.js
packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation-step.js
packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/personal-preferences-step.js
packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-profiles-step.js

* We want to improve the indication we give to users while using the First-time configuration
* Improves the indication given to the users in the First-time configuration.
* N/A
* Reset your indexable with the Yoast Test helper
* go to `Tools` -> `Yoast test` and click on `Reset indexables tables & migrations` 
* Go to `Yoast SEO` -> `General` -> `First-time configuration tab
* go through each step of the First-time configuration and check the copy against this [doc](https://docs.google.com/document/d/1Z_aJpe_3q1l3PUSzySp-ucTzp5QNbfWOsNUerrHc-RE/edit) 
* No functional changes are …

Various copy improvements in the FTC

---

packages/replacement-variable-editor/src/Mention.js

* We want to align the post replacement variable editor with the settings.
* [@yoast/replacement-variable-editor 0.0.1] Update styling to match settings styling.
*
* Make sure the metabox en sidebar replacement variable editor for classic, gutenberg and Elementor look the same as in the settings and the screenshot below:
* 
*
*
Fixes #

Update styling of replacement variable editor content.

---

inc/sitemaps/class-post-type-sitemap-provider.php
inc/sitemaps/class-sitemap-image-parser.php

*
* Adds a filter to add images to front page in sitemaps.
*
* Go to `Settings`->`Readings`
* Go to `Your homepage displays` and select `Your latest posts` 
* Go to `Yoast SEO`->`XML Sitemaps`
* View the sitemaps-> Page sitemap,  and check you see the front page there with 0 images. 
* Install `Code Snippets` plugin
* Add the following PHP snippet:
```php
function add_sitemap_front_page_url_images( $images ) {
return [ [ 'src' => 'http://wordpress.test/wp-content/uploads/2023/11/khtaxncwxuc.jpg' ] ];
};
add_filter( 'wpseo_sitemap_urlimages_front_page', 'add_sitemap_front_page_url_images', 10, 1 );
```
* View the sitemaps-> Page sitemap,  and check you see the frontpage …

Add filter for adding image to front page sitemap

---

.eslintrc
packages/feature-flag/package.json
packages/helpers/package.json
packages/js/package.json
packages/replacement-variable-editor/package.json
packages/yoastseo/package.json
yarn.lock

* Make some progress in fixing more of our phantom dependencies.
* Fixes the `a11y-speak` dependency to use the `main` branch, which was previously named `master`.
* Adds `root: true` to the root ESLint configuration, to ensure ESLint does not look outside the project.
* [@yoast/feature-flag 0.0.1] Adds missing development dependency on `@yoast/browserslist-config`.
* [@yoast/helpers 0.0.1] Adds missing development dependency on `@yoast/browserslist-config`.
* [@yoast/replacement-variable-editor 0.0.1] Adds missing development dependency on `@yoast/browserslist-config`.
* [yoastseo 0.0.1] Adds missing development dependency on `eslint-config-yoast`.
*
These are not any …

Phantom dependencies

---

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js

* In [another PR](https://github.com/Yoast/wordpress-seo/pull/20903), the feedback for phrases with 'normal' and 'abnormal' was adapted. We got additional feedback on those changes after the PR was merged, which are implemented in this PR.
* [See Slack thread with the feedback](https://yoast.slack.com/archives/C03PRESAXMJ/p1701766647321619)
* Improves feedback for the phrases 'normal person/people', 'abnormal person/people', 'mentally normal', and 'mentally abnormal'.
*
* Open a new post and add the following phrase to the text: `normal person`
* Confirm that the inclusive language analysis returns a **red** traffic light with the following feedback: `Avoid using normal …

Inclusive language: Improve feedback for 'normal/abnormal people' and 'mentally normal/abnormal'

---

config/composer/actions.php
phpcs.xml.dist

* CI/Composer scripts improvement
* CI/Composer scripts improvement
Update CS menu functions to be in line with the same in other plugins.
* _N/A_ No functional changes

Composer: update CS menu functions

---

admin/class-plugin-conflict.php
admin/class-yoast-notifications.php
admin/class-yoast-plugin-conflict.php
inc/class-wpseo-meta.php
inc/class-wpseo-replace-vars.php
inc/class-wpseo-utils.php
inc/class-yoast-dynamic-rewrites.php
inc/sitemaps/class-sitemaps-cache.php
lib/model.php
src/actions/importing/abstract-aioseo-importing-action.php
src/services/health-check/health-check.php
tests/Unit/Routes/Importing_Route_Test.php
tests/Unit/Routes/Indexables_Head_Route_Test.php

Modernize: use magic `::class` keyword for name resolution

---

admin/views/tabs/network/crawl-settings.php
admin/views/tabs/network/features.php
admin/views/tabs/network/integrations.php
src/integrations/admin/crawl-settings-integration.php

CS/QA: use `printf()`, not `echo sprintf()`

---

src/integrations/third-party/wordproof.php
tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php

CS/QA: static closures should be static

---

config/dependency-injection/loader-pass.php
lib/abstract-main.php
lib/migrations/adapter.php
lib/orm.php
src/builders/indexable-link-builder.php
src/conditionals/wp-cron-enabled-conditional.php
src/content-type-visibility/application/content-type-visibility-dismiss-notifications.php
src/content-type-visibility/user-interface/content-type-visibility-dismiss-new-route.php
src/helpers/current-page-helper.php
src/integrations/admin/background-indexing-integration.php
src/integrations/blocks/structured-data-blocks.php
src/integrations/front-end-integration.php
src/integrations/settings-integration.php
src/integrations/support-integration.php
src/integrations/third-party/wordproof.php
src/integrations/watchers/indexable-post-type-change-watcher.php
src/integrations/watchers/indexable-taxonomy-change-watcher.php
src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
src/presentations/indexable-term-archive-presentation.php
src/presenters/admin/sidebar-presenter.php
tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
tests/Unit/Doubles/Introductions/Introduction_Mock.php
tests/Unit/Inc/Sitemaps/WPSEO_Sitemaps_Router.php
tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php
tests/WP/Builders/Indexable_Author_Builder_Test.php
tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
tests/WP/Builders/Indexable_Post_Type_Archive_Builder_Test.php
tests/WP/Builders/Indexable_Term_Builder_Test.php

CS/QA: use fully qualified global functions and constants in namespaced files

---

admin/class-bulk-editor-list-table.php
admin/class-meta-columns.php
admin/class-premium-upsell-admin-block.php
admin/class-yoast-form.php
admin/metabox/class-metabox.php
admin/taxonomy/class-taxonomy-columns.php
admin/taxonomy/class-taxonomy-fields-presenter.php
config/composer/actions.php
inc/class-addon-manager.php
src/integrations/admin/addon-installation/dialog-integration.php
src/integrations/admin/menu-badge-integration.php
src/presenters/meta-description-presenter.php
tests/Unit/Integrations/Admin/Indexing_Tool_Integration_Test.php
tests/Unit/Integrations/Blocks/Structured_Data_Blocks_Test.php
tests/Unit/Presenters/Admin/Indexing_Error_Presenter_Test.php
tests/Unit/Presenters/Admin/Indexing_Failed_Notification_Presenter_Test.php

* Consistently have concat operator at start of line when concatenating across multiple lines.

CS: consistently have concat operator at start of line

---

tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php

* Remove unnecessary unused parameters in some function mocks.

CS/QA: remove unnecessary unused parameters

---

tests/Unit/Admin/MyYoast_Proxy_Test.php
tests/Unit/Repositories/SEO_Links_Repository_Test.php
tests/WP/Admin/Asset_Manager_Test.php
tests/WP/Admin/Editor_Specific_Replace_Vars_Test.php
tests/WP/Admin/Gutenberg_Compatibility_Test.php
tests/WP/Admin/Import/AIOSEO_Test.php
tests/WP/Admin/Import/Premium_SEO_Pack_Test.php
tests/WP/Admin/Import/Smartcrawl_SEO_Test.php
tests/WP/Admin/Import/Squirrly_Test.php
tests/WP/Admin/Meta_Columns_Test.php
tests/WP/Admin/Metabox/Metabox_Test.php
tests/WP/Admin/Network_Admin_Test.php
tests/WP/Admin/Primary_Term_Admin_Test.php
tests/WP/Admin/Services/File_Size_Service_Test.php
tests/WP/Inc/Admin_Bar_Menu_Test.php
tests/WP/Inc/MyYoast_Api_Request_Test.php
tests/WP/Notifiers/Dismissible_Notification_Test.php
tests/WP/Sitemaps/Image_Parser_Test.php

Tests: use `willReturn()`

---

tests/WP/Builders/Indexable_Author_Builder_Test.php
tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
tests/WP/Builders/Indexable_Post_Type_Archive_Builder_Test.php
tests/WP/Builders/Indexable_Term_Builder_Test.php
tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php
tests/WP/Frontend/Front_End_Integration_Test.php
tests/WP/Helpers/First_Time_Configuration_Notice_Helper_Test.php
tests/WP/Repositories/SEO_Links_Repository_Test.php

* WP tests should use snake case fixture methods as otherwise the WP setup/teardown may not be called correctly.

Tests: WP tests should use snake case fixture methods

---

tests/Unit/Builders/Indexable_Home_Page_Builder_Test.php
tests/Unit/Builders/Indexable_Post_Type_Archive_Builder_Test.php

Tests: fix some `@covers`

---

tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
tests/WP/Builders/Indexable_Term_Builder_Test.php

QA: more modern class references

---

admin/class-export.php
admin/class-yoast-form.php
admin/import/plugins/class-abstract-plugin-importer.php
admin/taxonomy/class-taxonomy-fields-presenter.php
inc/class-addon-manager.php
inc/class-upgrade.php
inc/options/class-wpseo-option-titles.php
inc/options/class-wpseo-taxonomy-meta.php
lib/orm.php
src/actions/wincher/wincher-account-action.php
src/config/oauth-client.php
src/generators/schema/person.php
src/integrations/front-end/wp-robots-integration.php

Modernize: use null coalesce

---

admin/views/licenses.php
inc/sitemaps/class-post-type-sitemap-provider.php
src/helpers/crawl-cleanup-helper.php
src/integrations/settings-integration.php
src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
src/introductions/application/version-trait.php
tests/Unit/Admin/Import/Import_Settings_Test.php
tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
tests/Unit/Helpers/Short_Link_Helper_Test.php
tests/Unit/Inc/Yoast_Dynamic_Rewrites_Test.php
tests/WP/Builders/Indexable_Author_Builder_Test.php
tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
tests/WP/Builders/Indexable_Post_Type_Archive_Builder_Test.php
tests/WP/Builders/Indexable_Term_Builder_Test.php
tests/WP/Inc/Yoast_Dynamic_Rewrites_Test.php

CS: various minor tweaks

---

tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php

* Remove redundant global variable import which is never used.

QA: remove redundant global variable import

---

inc/sitemaps/class-post-type-sitemap-provider.php
src/content-type-visibility/application/content-type-visibility-dismiss-notifications.php
src/content-type-visibility/application/content-type-visibility-watcher-actions.php
src/introductions/infrastructure/introductions-seen-repository.php
src/introductions/infrastructure/wistia-embed-permission-repository.php
tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Dismiss_Notifications_Test.php
tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php

* Docs: more formatting fixes
* Docs: consistent tag order 

Docs: more fixes

---

tests/Unit/Analytics/Domain/Missing_Indexable_Bucket_Test.php
tests/Unit/Analytics/Domain/Missing_Indexable_Count_Test.php
tests/Unit/Analytics/Domain/To_Be_Cleaned_Indexable_Bucket_Test.php
tests/Unit/Analytics/Domain/To_Be_Cleaned_Indexable_Count_Test.php
tests/Unit/Analytics/User_Interface/Last_Completed_Indexation_Integration_Test.php
tests/Unit/Helpers/Post_Type_Helper_Test.php
tests/Unit/Repositories/SEO_Links_Repository_Test.php

* Unit tests should use snake case fixture methods as otherwise the Mockery setup/teardown may not be called correctly.

Tests: unit tests should use snake case fixture methods

---

.github/workflows/test.yml
tests/Unit/Inc/Addon_Manager_Test.php
tests/Unit/bootstrap.php
wp-seo-main.php
wp-seo.php

*
* Sets the minimum supported WordPress version to 6.3.
*
* NA
*
*
Fixes #

Set the minimum supported WordPress version to 6.3.

---

composer.json
composer.lock

* Update select dependencies
* Update select dependencies
Selectively update test dependencies.
Refs:
* https://github.com/antecedent/patchwork/releases/tag/2.1.27
* https://github.com/sebastianbergmann/phpunit/blob/8.5.36/ChangeLog-8.5.md
Selectively update Guzzle and dependencies.
Refs:
* https://github.com/guzzle/guzzle/releases/tag/7.8.1

Composer: update dependencies

---

.github/workflows/finish-coveralls.yml

When a PR doesn't change anything in the yoastseo package the tests for it aren't run and coverage of that package isn't measured. To prevent sudden coverage drops, Coveralls allows to carry forward coverage from previous runs if there is no new coverage report for a package.
* Fixes a bug where total reported coverage would drop below 40% on PRs when the PR did not change anything in the yoastseo package.
* n/a
* Merge to `trunk` 
* Wait for the finish-coveralls workflow to finish.
* Rebase https://github.com/Yoast/wordpress-seo/pull/20923. Its coveralls report should include coverage for the yoastseo package with a "⏩ carried forward" label next to it.
QA can test this …

Carryforward yoastseo test results

---

inc/class-wpseo-content-images.php
src/actions/configuration/first-time-configuration-action.php
src/builders/indexable-builder.php
src/generators/schema-generator.php
src/helpers/schema/language-helper.php
src/integrations/front-end-integration.php
src/presenters/schema-presenter.php

Docs: fix some filter docblocks

---

.github/workflows/deprecation-check.yml
packages/components/README.md

* We are moving away from `@yoast/components` in favor of `@yoast/ui-library`. Granted this is not a drop in replacement at all.
* [@yoast/components] Deprecates this package.
* Adding folder to the deprecation check workflow (GH-actions)
* You can check what all we changed in this folder since the last release: `git log 12520ef960f8c1f7789c337354f160a3fc3ac98c...trunk --oneline -- packages/components`
* Does the readme change make sense?
* Any PR with changes inside the `packages/components` folder will now get a comment similar to https://github.com/Yoast/wordpress-seo/pull/21045#issuecomment-1893722784
* Meant to inform the creator that changing this package is not …

Deprecate @yoast/components

---

yarn.lock

* 
* Fixes a bug where the Babel versions in `yarn.lock` would break the `yarn add` command.
* This seems to solve a Babel loop we run into when adding any dependency via `yarn add`:
* remove: all @babel/* dependencies from yarn.lock
* run: yarn install
* commit: result
* We haven't tested if we can make these removals more precise.
* However, it sort of makes sense that these Babel versions are made to work together?
* Do a smoke test
* Try to use Yarn to add dependencies somewhere (please don't commit them 😄 )
* Only the smoke test is needed here. …

Fix yarn add

---

.github/PULL_REQUEST_TEMPLATE.md

*
* Adapts GitHub PR template to include Gutenberg to the list of editors a PR should be tested on and adds examples of documentation.
*
*
*
*
Fixes #

335 add gutenberg to the list of editors a pr should be tested on

---

src/context/meta-tags-context.php
tests/Unit/Context/Meta_Tags_Context_Test.php

* When performing a REST request for a post, the schema generated doesn't include the primary image: we want to fix this.
* Fixes a bug where the schema of a post requested through a REST request doesn't include the primary image.
* In both `generate_main_image_id` and `generate_main_image_url` methods I now call a new method specific for the REST request case.
* `get_main_image_id_for_rest_request` can be extended to cover the `categories`, `tags` and `taxonomies` cases in the future
* Create a post 
* select a featured image for it
* take note of the post id
* Perform a REST request as follows: `YOUR_BLOG_URL/wp-json/wp/v2/posts/POST_ID` where
* `YOUR_BLOG_URL` is your …

Add reference to primary image in posts schema generated by a REST request

---

packages/js/src/shared-admin/components/premium-upsell-card.js
src/presenters/admin/sidebar-presenter.php

* We want to update the sidebar ad text.
* Updates sidebar ad text.
* N/A
* Go to `Yoast SEO` -> `General`
* Go to `Yoast SEO` -> `Settings`
* N/A
Fixes [#21130](https://github.com/Yoast/wordpress-seo/issues/21130)

Update ad text

---

src/helpers/social-profiles-helper.php

* We want to also allow X.com in the FTC 
* Adds `x.com` as a possible domain for the Twitter validation in our FTC social profiles settings.
*
- Go to the social profiles step in the FTC.
- Enter a Twitter profile with x.com, like https://x.com/yoast
- Verify you do not get a validation warning and can save
- Enter a Twitter profile with twitter.com, like https://twitter.com/yoast
- Verify you do not get a validation warning and can save
- Enter another domain and verify you get a validation warning
- Try it with just `yoast` as a user Id.
*
* …

Allow X.com in ftc

---

.github/workflows/jstest.yml

* Only build yoastseo when needed. Missed an if statement in https://github.com/Yoast/wordpress-seo/pull/20874
* Fixes the Fix GH actions' JS tests when not needing to run `yoastseo` tests.
*
* GH actions should pass; The `TestJS - yoastseo` in particular
* No need
*
Fixes #

Fix GH actions' JS tests when not needing to run yoastseo tests

---

inc/class-upgrade.php
inc/sitemaps/class-sitemaps-cache-validator.php
tests/WP/Doubles/Inc/Upgrade_Double.php
tests/WP/Inc/Upgrade_Test.php

* We want to add integration tests covering the queries in the upgrade routine that will be rewritten with placeholders.
* Adds integration tests covering the queries in the upgrade routine that will be rewritten with placeholders.
*
*
*
*
Fixes [#21058](https://github.com/Yoast/wordpress-seo/issues/21058)

Add upgrade routine integration tests

---

readme.txt
tests/Unit/bootstrap.php
wp-seo-main.php

*
* Sets the WordPress tested up to version to 6.5.
Relevant technical choices:
*
*
*
*
Fixes #

Sets the WordPress tested up to version to 6.5

---

.github/workflows/test.yml
composer.json
composer.lock

*
* Fixes the failing unit tests by preventing Mockery from being updated to the buggy 1.6.10 version.
*
* NA, the tests should just pass
*
*
Fixes #

Prevent Mockery from being updated to the buggy 1.6.10 version

---

packages/js/src/ai-generator/components/modal-content.js
packages/js/src/introductions/components/content.js

* The yoa.st and yoast.com domains do not use `www`. Using this for hyperlinks causes unnecessary redirects.
* Fix hyperlinks to our documentation.
* N/A
* Make sure this link still works:
*
*
Fixes #

Prevent unnecessary redirects by not using the wrong URLs in hyperlinks

---

inc/class-wpseo-admin-bar-menu.php

* Google retired the Mobile Usability report, Mobile-Friendly Test tool, and Mobile-Friendly Test API on December 4, 2023. However, we are still showing the "Mobile-Friendly Test" sub-menu for the "Analyze this page" on the admin menu bar when viewing the pages. Google also redirected the link https://www.google.com/webmasters/tools/mobile-friendly/ to the lighthouse page, so customers unaware of this may get confused.
* Removes the link to the now-retired Google Mobile-Friendly Test from the admin bar menu.
*
* View any page, and confirm that the "Mobile-Friendly Test" sub-menu is not showing for the menu "Analyze this page" …

Removed the Mobile-Friendly test link from the admin menu bar

---

packages/js/src/settings/helpers/validation.js

* We want to Introduce a type check for allowed MIME types for social templates images.
* Introduces a check for allowed MIME types when uploading social templates images.
* N/A
* Make sure you have Premium installed and activated
* Go to https://www.simpleimageresizer.com/image-converter 
* Upload an image and convert it to `TIFF` format
* Go to `Yoast SEO` -> `Settings` -> `Content type` -> `Posts`
* In the `Social media appearance` section, click on `Select image`
* upload the TIFF image and select it 
* verify you get the following error: `The selected media type is not valid. Supported types are: JPG, PNG, WEBP and GIF.`
* upload a file which is not an image (e.g. …

Introduce allowed MIME type check for social templates images

---

composer.json

* To comply with the newest YoastCS release, we need to make sure the number of errors is exactly the threshold, not more or less
* Decrease the threshold for PHPCS errors.
*
* N/A
*
*
Fixes #

Decrease threshold for PHPCS errors

---

packages/ui-library/src/components/autocomplete-field/index.js
packages/ui-library/src/patterns/forms.stories.mdx
packages/ui-library/tailwind.config.js

* Introduce a page to the Storybook explaining how forms are usually constructed.
* Introduce a page to the Storybook showcasing how forms fields can be aligned next to each other.
* [@yoast/ui-library] Introduces a page in the storybook showcasing how to construct a form.
* This is the first pattern in the Storybook. It's based on the introduction, explaining there to be elements, components and patterns.
* The file itself uses our own elements to render nice titles, texts and a `<code>` piece.
* Spin up the Storybook.
* Visit the "Forms" pattern that now appears in the left-hand menu.
* …

Introduce form patterns in Storybook

---

packages/ui-library/src/elements/button/index.js

I needed it for `MyYoast Client` form case and it is one of three types according to HTML spec.
*
* [@yoast/ui-library 0.1.0] Added `reset` as valid value of `type`, in the `Button` element.
*
* Make sure that you see `reset` on button component's page in storybook. Make sure as well that, if "reset" radio selected, that it reflects in components code.
*
*
Fixes #

Add type reset to button - UI Library

---

.github/workflows/test.yml
tests/Unit/Inc/Addon_Manager_Test.php
tests/Unit/bootstrap.php
wp-seo-main.php
wp-seo.php

*
* Sets the minimum supported WordPress version to 6.4.
*
* NA
*
*
Fixes #

Set the minimum supported WordPress version to 6.4.

---

packages/js/src/structured-data-blocks/faq/block.json
packages/js/src/structured-data-blocks/how-to/block.json
src/integrations/blocks/structured-data-blocks.php

* Improvement to https://github.com/Yoast/wordpress-seo/pull/21329
* Fixes wrong version numbers in block declaration and when deprecating a method.
*
* NA
*
* It's related to https://github.com/Yoast/wordpress-seo/pull/21329 but I assume it should not have any impact
Fixes #

Fixes wrong version numbers in block declaration and when deprecating a method

---

packages/js/src/dynamic-blocks.js
packages/js/src/dynamic-blocks/breadcrumbs/block.json
src/integrations/blocks/abstract-dynamic-block-v3.php
src/integrations/blocks/breadcrumbs-block.php

*
* Convert the Breadcrumbs block to the Blocks V3 API .
* We are introducing a new class for the dynamic blocks that will be used also by some Premium blocks. I have decided to create a new class instead of adapting the old one: the old class is staying for the moment and will be deprecated when the transition is complete.
* while the FAQ and the How-To block were named `yoast/faq` and `yoast/how-to`, this block is called `yoast- seo/breadcrumbs`, which is inconsistent, but it cannot be renamed since it would be breaking compatibility
* **Important:** test using an artifact instead of just building from the source since there is an integral part of this PR that is …

Convert the Breadcrumbs block to the Blocks V3 API 

---

admin/menu/class-base-menu.php
src/integrations/admin/menu-badge-integration.php

* We want to change some copy.
* Changes the copy in the admin sitebar from `Premium` to `Upgrades`
*
* Go to /wp-admin and make sure that in the Yoast SEO sidebar it says `Upgrades` and it leads to `?page=wpseo_licenses`
* In the admin bar menu (both in the front end and in the back end) make sure that under `SEO Settings` it also says `Upgrades` and leads to `?page=wpseo_licenses`
*
*
Fixes #

Updates copy from Premium to Upgrades.

---

tests/WP/Builders/Indexable_Date_Archive_Builder_Test.php

*
* Adds integration tests to the date archive indexable builder.
*
* N/A
*
*
Fixes #

Adds integration test for date archive builder.

---

packages/ui-library/src/elements/toast/index.js

* We want to allow users to add additional CSS classes to the Toast's close button 
* Allows users to add additional CSS classes to the Toast's close button. 
* N/A
* Please follow the test instructions in [Add skeleton loader to toast #4327 ](https://github.com/Yoast/wordpress-seo-premium/pull/4327)
* N/A
Fixes [#1577](https://github.com/Yoast/plugins-automated-testing/issues/1577)

Allow users to add additional CSS classes to the Toast's close button

---

src/integrations/admin/menu-badge-integration.php

*
* Fixes an unreleased bug where the `Premium` badge was reading `Upgrades`.
*
* Check that the following badges read `Premium` instead of  `Upgrades`:
- in the sidebar, next to `Yoast SEO` > `Workouts`
- in the sidebar, next to `Yoast SEO` > `Redirects`
- in the admin bar menu, under `SEO Settings`, next to `Workouts`
- in the admin bar menu, under `SEO Settings`, next to `Redirects`
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/1615

Fix the `Premium` badge

---

packages/js/src/settings/routes/site-features.js
packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js
packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap

* We want to finalize the copies for the new AI feature
* Updates copies in the AI upsell modal and the AI feature card
* Go to the Yoast->Settings page and check the AI feature card. Confirm it looks like this:
* Also, deactivate Premium and delete any `_yoast_wpseo_introductions` usermeta, so that when you refresh the settings page, you see this modal:
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/228

Update copies to cover the new AI features in the card and the upsell

---

admin/formatter/class-post-metabox-formatter.php

*
* Bumps the post metabox formatter' `use_social_templates` deprecation version to 23.1.
*
*
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/229

Bump deprecation version to 23.1

---

readme.txt
tests/Unit/bootstrap.php
wp-seo-main.php

*
* Sets the "WordPress tested up to" version to 6.6.
*
* NA
*
*
Fixes #

Sets the WordPress tested up to version to 6.6

---

css/src/introductions.css
packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js

* We want to use the introduction gradient class in a contained way also in the ai title and description introduction modal.
* Fix gradient background for AI title and description generator introduction modal.
* I removed the `yst-introduction-modal-panel` class because we want to use the gradient inside elements in the modal.
* We want more flexibility when using the gradient.
* Either clean the user meta `_yoast_wpseo_introductions` or create a new site.
* Go to one of Yoast admin pages and check the introduction modal has a gradient of 50% only on the upper part of the modal.
* Edit a post and click on the Use AI button and check the upsell modal for the AI title and …

Fix introduction gradient.

---

src/helpers/indexing-helper.php
src/integrations/admin/background-indexing-integration.php
tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php

* We want to leverage our DI system to inject all indexation actions so that if we ever add one we don't need to touch this code.
* Refactors the way we handle the DI container injection in our background indexing systems.
*
* Disable the plugin
* Create 100 new posts. by running `wp post generate --count=100 --post_author=admin`
* Add some links from one post to another post
* Enable the plugin and run the following CLI command `wp cron event run "wpseo_indexable_index_batch"`
* Make sure indexable and internal link database records are created.
* …

Add auto inject with variadic operator

---

admin/class-plugin-availability.php
admin/metabox/class-metabox.php
src/integrations/admin/integrations-page.php
src/integrations/settings-integration.php
tests/Unit/Admin/Plugin_Availability_Test.php
tests/Unit/Integrations/Admin/Integrations_Page_Integration_Test.php
tests/WP/Admin/Plugin_Availability_Test.php
tests/WP/Doubles/Admin/Plugin_Availability_Double.php

* We want to deprecate some unused functions and change the way we check some dependencies.
* Streamlines checking for dependencies on admin pages.
*
* Make sure you have WOO and our WOO seo plugin enabled.
* Go to /admin.php?page=wpseo_integrations and make sure the integration is enabled.
* Disable WooSeo and make sure the integration is now disabled.
* Edit a product and make sure you don't see our additional settings in Woo in the Product data editor.
* Enable WooSeo and make sure you see our settings.
* Go to /admin.php?page=wpseo_page_settings#/post-type/product and make sure the `Schema` field is grayed out with a message that you have WooSeo enabled.
* Disable it …

Refactor plugin availability.

---

packages/js/src/decorator/helpers/getAnnotationsHelpers.js

* Fixes a "something went wrong" error when removing an image caption.
* Fixes a bug where the content analysis would error when removing an image caption in the default editor.
* If caption removed `block.attributes` for caption returns `undefined` so this case is processed.
* Activate only Free version.
* Open development console.
* Create post in the default editor.
* Add image first then more than 300 words make sure to add the keyphrase in the first paragraph and don't add the keyphrase anywhere else.
* Set a keyphrase.
* Click the highlight button next to the keyphrase density assessment to highlight the keyphrase (only one keyphrase occurrence will be highlighted). …

Fixes "something went wrong" error when removing image caption

---

inc/class-wpseo-utils.php
packages/js/src/components/contentAnalysis/SeoAnalysis.js
packages/js/src/redux/reducers/preferences.js

*
* Refactor check if AI feature is active property.
* Moved a check for premium feature to premium.
* No need for premium check is SeoAnalysis.js since er are using premium store for the AiFeature status. The prop is optional and the default is false.
* Test together with https://github.com/Yoast/wordpress-seo-premium/pull/4479.
* Edit a post and check you see the AI button in the search appearance
* Check you get the upsell modal when clicking on it.
* Check you don't get any console error.
* Continue with the test instructions in the premium PR. 
* …

21632 refactor is ai feature active property

---

packages/js/src/dashboard/app.js
packages/js/src/dashboard/components/route-layout.js
packages/js/src/dashboard/routes/first-time-configuration.js
packages/js/src/dashboard/routes/index.js
packages/js/src/first-time-configuration.js
packages/js/src/first-time-configuration/first-time-configuration-app-container.js
packages/js/src/first-time-configuration/first-time-configuration-steps.js
packages/js/tests/dashboard/components/__snapshots__/route-layout.test.js.snap
packages/js/tests/dashboard/components/route-layout.test.js

* We want to make sure the FTC works with the new dashboard.
* Integrates the FTC into the new dashboard
*
* Add the following code:
`define( 'YOAST_SEO_NEW_DASHBOARD_UI', true );`
* Make sure the FTC looks the same as the design as seen here https://github.com/Yoast/reserved-tasks/issues/268 and you can save your values.
* Smoke test the existing FTC so to make sure that still works as expected.
*
*
Fixes #

Extract FTC stept to own component to be reused in new dashboard.

---

.github/workflows/test.yml
tests/Unit/Inc/Addon_Manager_Test.php
tests/Unit/bootstrap.php
wp-seo-main.php
wp-seo.php

*
* Sets the minimum supported WordPress version to 6.5.
*
*
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21664

Set the minimum supported WordPress version to 6.5

---

src/promotions/domain/black-friday-promotion.php

*
* Fixes a bug where the Black Friday sale start and end times were incorrect.
*
* Change either your system time or your PHP server time to: 28th of November 2024, just a little bit before 11:00 CET
* Go to the Yoast general page
* Wait a little bit until it is 11:00
* Change either your system time or your PHP server time to: 3rd of December 2024, just a little bit before 11:00 CET
* Go to the Yoast general page
* Wait a little bit until it is 11:00
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/286

Fix Black Friday start and end time

---

inc/class-wpseo-utils.php
packages/js/src/components/contentAnalysis/SeoAnalysis.js
packages/js/src/redux/reducers/preferences.js

* Reverts #21633 
* Reverts Yoast/wordpress-seo#21633, Not backwards compatible.
* Test together with https://github.com/Yoast/wordpress-seo-premium/pull/4479.
* Edit a post and check you see the AI button in the search appearance
* Check you get the upsell modal when clicking on it.
* Check you don't get any console error.
* Continue with the test instructions in the premium PR. 
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21632

Revert "21632 refactor is ai feature active property"

---

.github/workflows/test.yml

* Ubuntu latest 24.0 does not contain SVN, so we manually add a step to the wp-test workflow to install SVN.
* Update testing workflow to install SVN
*
*
*
*
Fixes #

Adding step in wp-test flow to install SVN

---

packages/yoastseo/.gitignore
packages/yoastseo/package.json
packages/yoastseo/src/pluggable.js
packages/yoastseo/tsconfig.json
yarn.lock

* We want to add a TypeScript compiler in the `yoastseo` package, adding TypeScript bindings.
* [yoastseo] Adds TypeScript bindings.
* Adds a command to create TypeScript bindings to `package.json` and add typescript configuration.
* Make sure that **packages/yoastseo/types** folder is created.
* Do a small smoke test that it works as expected.
*
* Should not impact anything but just in case please do small smoke test.
Fixes [#389](https://github.com/Yoast/lingo-other-tasks/issues/389)

Enable typescript in the yoastseo package

---

admin/class-config.php
src/dashboard/user-interface/new-dashboard-page-integration.php
tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php

*
* Fixes an unreleased bug where the general page of the network admin would be broken
*
* Install Yoast SEO in a multisite
* Visit the network's Yoast SEO general page (`/wp-admin/network/admin.php?page=wpseo_dashboard`)
* Confirm that it looks as it should
* Visit the Yoast SEO general page in a subsite or in a single site installation
* Confirm that it looks as it should and smoke test it a bit
* Do the same with the new dashboard feature flag both enabled and disabled
*
Fixes https://github.com/Yoast/reserved-tasks/issues/303

Fix network page of dashboard

---

changelog.md
config/grunt/task-config/update-changelog-to-latest.js
readme.txt

*
* Moves the changelog to a separate changelog.md file.
*
* NA, a RC creation needs to run to check whether it's fine.
*
*
Fixes #

Move changelog to new file

---

packages/js/src/general/components/notifications.js
packages/js/src/general/components/problems.js

* We want to cap the max length of the paper content so it looks good on all screens.
* Adds a maximum width to the problems and notifications in the dashboard.
*
* Build the PR and compare it to the design in te original issue.
* Also make sure the size is 600px and does not get bigger also not on big screens.
*
*
Fixes #

Set max width for Paper content.

---

admin/metabox/class-metabox.php

Reverts Yoast/wordpress-seo#21734

Revert "Fix metabox assets enqueuing"

---

admin/metabox/class-metabox.php

Revert enqueuing fixes

---

readme.txt
tests/Unit/bootstrap.php
wp-seo-main.php

*
* Sets the _WordPress tested up to_ version to 6.7
*
*
*
*
Fixes #

Sets the WordPress tested up to version to 6.7

---

admin/class-admin-asset-manager.php
css/src/modal.css
css/src/tailwind.css
package.json
packages/js/.eslintrc.js
packages/js/package.json
packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
packages/js/src/containers/SEMrushRelatedKeyphrases.js
packages/js/src/redux/reducers/preferences.js
packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/index.js
packages/ui-library/.storybook/style.css
packages/ui-library/src/elements/table/index.js
packages/ui-library/src/elements/table/style.css
tailwind.config.js

*
* Adds new columns and design to the related key phrase suggestions table.
* [@yoast/ui-library 0.1.0] Improves the border radius of the Table element. 
*
* Create a post and add focus key phrase
* Click on "Get related keyphrases"
* Login to SEMrush about and check you are getting the loading table:
https://github.com/user-attachments/assets/e4fd7a8d-c01b-476f-97eb-f12f4dd5f84f
* Then you should get a table like that:
* Check you are getting in the table two extra columns, one for the intent and one for the keyphrase difficulty %.
* Check the Difficulty index and search volume are aligned to the right.
* Hover the badges in intent and check you get a tooltip with …

implementation of the related keyphrase suggestions package

---

packages/js/src/redux/reducers/preferences.js

*
* Fixes unreleased bug of isRtl type not being boolean.
*
* Edit a post with focus key phrase.
* Click on `Get related keyphrases` 
* Open the devtools console and check you don't get the error for wrong type for isRtl:
* Go to user profile and change the language an rtl one like arabic and repeat the tests.
*
*
Fixes #

fix isRtl preference

---

package.json
packages/js/package.json
packages/related-keyphrase-suggestions/package.json
packages/ui-library/changelog.md
packages/ui-library/package.json

> [!IMPORTANT]
> Do not rebase this PR. The "Version increase" commit 6c11d5d7c04162a4ee16af5c9644bd8947ac8166 is the exact version that has been published to NPM. Orphaning this commit will make it impossible to properly determine changes since the published version.
* Release our Yoast UI library:
- @yoast/ui-library:4.1.0
* Release new package versions.
* n/a
* n/a: only manifest updates. all actual code changes have already been made.
* n/a
* n/a
Fixes #

Version increase

---

packages/js/src/dashboard/components/dashboard.js
packages/js/src/dashboard/components/page-title.js
packages/js/src/dashboard/index.js
packages/js/src/dashboard/scores/score-meta.js
packages/js/src/general/initialize.js

*
* Improves copy in the dashboard
*
See [the design](https://www.figma.com/design/DXKVj4tji7M65FYCYwBFUl/General-page?node-id=2316-1358&node-type=frame&t=DwmnyxOfX8TFKaWY-0) for the wanted copy.
See the issue for the notes on what changed.
* Go to the dashboard
* Verify the score descriptions. They depend on what score the largest amount has.
* Verify the page description. There are 2 variants, plus an info alert.
* The default
* `Welcome to your dashboard! Check your content's SEO performance, readability, and overall strengths and opportunities. Learn more on how to improve your content with our content analysis tool.`
* The last sentence should link and open in a new …

Dashboard: move to final copy

---

tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php

*
* Fixes integration tests when Black Friday sale is on.
*
* N/A
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/344

Fix integration tests when black friday sale is on

---

packages/js/src/dashboard/components/page-title.js
packages/js/src/dashboard/scores/score-meta.js

* Copy changes.
* Changes some copy for disabled analyses.
* Changes some copy for when there are a lot of not analyzed posts.
*
* Make sure you disable both analyses and make sure the copy matches up with the design mentioned in https://github.com/Yoast/reserved-tasks/issues/345
* Make sure you have more `not analyzed` posts than any other type for a `content type` and make sure the copy matches the design.
*
*
Fixes #

copy adjustments for not analyzed disabled analyses

---

packages/js/src/dashboard/scores/components/content-type-filter.js
packages/js/src/dashboard/scores/components/term-filter.js

* Make sure encoding/decoding works.
* Makes sure content types and taxonomy labels are properly decoded.
*
* Active the CPT UI plugin and create a post type with the main label as `test !@#$%^&*()<>'"`
* Create a category for the normal `post` post type with the name `test !@#$%^&*()<>'"`
* Open the dashboard and make sure they show up correctly in the UI.
*
*
Fixes #

Use proper character decoding

---

packages/js/src/installation-success.js
packages/js/tests/InstallationSuccessPage.test.js
packages/js/tests/__snapshots__/InstallationSuccessPage.test.js.snap

*
* Change the copy in the Free installation success page.
* Took the opportunity to replace the renderReactRoot. I needed that to write the tests.
* Reset Free installation success page in the Yoast helper and reactive the plugin or reinstall.
* Check the text for the first square title is "Your site is now easier for search engines to find."
* Open the devtools console and check there are no console errors (error related to renderReactRoot).
*
*
Fixes [Improve copy in FTC](https://github.com/Yoast/reserved-tasks/issues/349)

349 improve copy in fti

---

tests/WP/Dashboard/Application/Endpoints/Endpoints_Repository_Test.php

* We want to add integration tests.
* Adds an integration test to make sure the endpoints repository returns the needed data.
*
* N/A
*
*
Fixes #

Creates integration test for the Endpoints_Repository.

---

.github/workflows/cs.yml
.github/workflows/deploy.yml

* Improve CI
* Improve CI
This job checks the GH Actions workflows against syntax errors and other problems.
Includes minor fixes to pre-existing workflows to allow the build to pass.
* _N/A_ This PR is the test.

GH Actions: add actionlint job

---

src/conditionals/sitekit-feature-conditional.php

*
* Adds a feature flag for the sitekit integration, without doing much else.
*
* N/A
*
Fixes #

Add feature flag for the sitekit integration

---

src/conditionals/google-site-kit-feature-conditional.php
src/conditionals/site-kit-feature-conditional.php

*
* Rename the feature flag for the sitekit integration
*
* N/A
*
*
Fixes #

Rename feature flag

---

apps/content-analysis-api/helpers/get-researcher.js
packages/yoastseo/spec/specHelpers/getMorphologyData.js

*
* Bumps the morphology data version for German.
* 
* Follow the test instructions in the accompanying [Premium PR](update-english-morphology-data-version).
*
*
Fixes #

Updates the morphology data version number for German

---

.github/workflows/test.yml
tests/Unit/Inc/Addon_Manager_Test.php
tests/Unit/bootstrap.php
wp-seo-main.php
wp-seo.php

*
* Sets the minimum supported WordPress version to 6.6.
*
* NA
*
*
Fixes #

Set the minimum supported WordPress version to 6.6

---

packages/js/src/dashboard/index.js
packages/js/src/dashboard/services/remote-data-provider.js
packages/js/src/dashboard/widgets/top-pages-widget.js
packages/js/src/general/initialize.js

*
* Refactors endpoint fetching for time based seo metrix for the site kit integration.
*
* Have the site kit feature flag enabled and site kit configured with real data on a development or real envirnment.
* Check you get data for the "Top 5 most popular content" table.
*
*
Fixes [Adjust frontend in line with new API contract](https://github.com/Yoast/reserved-tasks/issues/440)

440 adjust frontend in line with new api contract

---

packages/js/src/dashboard/components/dashboard.js
packages/js/src/dashboard/widgets/score-widget.js
packages/js/src/dashboard/widgets/site-kit-setup-widget.js
packages/js/src/dashboard/widgets/top-pages-widget.js

*
* Changes the layout of the widgets in the dashboard.
* I created a 4 column grid for future one column widget.
* Enable google site feature flag
```
define( 'YOAST_SEO_GOOGLE_SITE_KIT_FEATURE', true );
```
* Make sure you are not connected to the site kit integration and the set up widget is on the dashboard. Check the widgets are taking the size of half of the dashboard and on mobile view will take the full width of the dashboard.
* Dismiss the set up widget until next visit and check the scores widget are parallel:
* Connect to the site kit and check the "Top 5 most popular content" widget is always the full width of dashboard:  …

fix dashboard layout with grid

---

.github/workflows/pr-validation.yml

* This is a follow-up to #22038. After internal discussion we want to remove the PR validation for the milestone, as that prevents us from getting an overall green check in the code review phase.
* Removes the PR validation for milestone.
*
* Open a PR.
* Do add a proper changelog label.
* Do **not** add a milestone.
* Confirm you do not get a warning. 
* No QA required.
* None.

Removes the PR validation for milestone

---

packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js

* This is a small follow-up to #22044: no translator comments were present for two strings, and that was detected by #22042.
* Adds translator comments for subheading distribution assessment feedback.
*
* This just adds translator comments, no additional testing required on top of #22044.
*
*

Adds translator comments for subheading distribution assessment feedback

---

admin/tracking/class-tracking-settings-data.php

*
* Tracks sites that have connected Site Kit.
*
* N/A
*
Fixes https://github.com/Yoast/reserved-tasks/issues/465

Track sites that have connected Site Kit

---

packages/js/src/dashboard/widgets/organic-sessions/daily.js

*
* Fixes an unreleased bug where the Dashboard would show an error related to our organic sessions widget.
*
* Have Site Kit set-up and connected, including analytics
* Disable Premium
* Without this PR: error
* With this PR: no error
*
*
Fixes #

Register more/missing chart plugins

---

src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php
tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Abstract_Time_Based_SEO_Metrics_Route_Test.php
tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Check_Capabilities_Test.php
tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Constructor_Test.php
tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Conditionals_Test.php
tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Metrics_Test.php
tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Register_Routes_Test.php

*
* Adds unit tests for the site kit integration endpoints.
*
* A small impact check on the number of results for the `Top 5 most popular content` and `Top 5 search queries` being still 5.
* A small impact check on the capability check of the REST routes:
* Do a GET request to any of our new endpoints, eg. to `/wp-json/yoast/v1/time_based_seo_metrics?options[widget]=organicSessionsDaily` as an admin. Confirm you get a 200 response
* Repeat the same as an SEO manager. Again confirm you get a 200 response.
* Repeat the same as an editor. Confirm you know get a 403 response.
* …

Adds unit tests for the site kit integration endpoints

---

src/dashboard/infrastructure/score-groups/score-group-link-collector.php
tests/Unit/Dashboard/Infrastructure/Score_Groups/Get_View_Link_Score_Group_Link_Collector_Test.php

*
* Adds unit tests for the score group link collector class.
*
* Smoke test if the links in the SEO and readability dashboard widgets still work.
*
*
Fixes #

Unit tests for the score group link collector.

---

tests/Unit/Dashboard/Infrastructure/Endpoints/Readability_Scores_Endpoint_Test.php
tests/Unit/Dashboard/Infrastructure/Endpoints/SEO_Scores_Endpoint_Test.php
tests/Unit/Dashboard/Infrastructure/Endpoints/Site_Kit_Configuration_Dismissal_Endpoint_Test.php
tests/Unit/Dashboard/Infrastructure/Endpoints/Site_Kit_Consent_Management_Endpoint_Test.php
tests/Unit/Dashboard/Infrastructure/Endpoints/Time_Based_SEO_Metrics_Endpoint_Test.php

*
* Adds unit tests for our Endpoint objects.
*
*
*
*
Fixes #

479 add unit test for endpoint container classes

---

composer.json
composer.lock
src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php
tests/WP/Dashboard/Infrastructure/Search_Console/Abstract_Search_Console_Adapter_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Construct.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Failed_Request_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Unexpected_Response_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Failed_Request_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Unexpected_Response_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Validate_Comparison_Response_Test.php
tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Validate_Response_Test.php
tests/WP/Doubles/Dashboard/Infrastructure/Search_Console/Search_Console_Module_Mock.php
tests/WP/TestCase.php

*
* Adds integration tests for the search console adapter
* A significant change of this PR is that it sets the Site Kit plugin as a dev dependency, so that it can be activated and used during integration tests.
* Added the `Site_Kit_Search_Console_Adapter::set_search_console_module()` function to facilitate testing - it shouldnt have an impact in the normal behavior of the classs. 
* Check that in the RC (or create an artifact if you're a dev), there's no `google-site-kit` folder in the vendor folder
* Quickly Smoke test the top 5 pages/queries widget
* …

Add integration tests for the search console adapter

---

packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md

* Flesch reading ease was moved to Insights so it shouldn't be included in the assessment documentation in the `yoastseo` package.
* Removes Flesch reading ease from the assessments documentation.
* [yoast-seo] Removes Flesch reading ease from the assessments documentation.
*
*  Check whether the changes are formatted correctly here: [SCORING_READABILITY.md ](https://github.com/Yoast/wordpress-seo/blob/remove-flesch-reading-ease-from-assessments-documentation/packages/yoastseo/src/scoring/assessments/SCORING%20READABILITY.md)
* No QA testing needed, only documentation is affected. …

Remove Flesch reading ease from the assessments documentation

---

packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js

* Besides the issue, there are some more tweaks made here to get the copy more consistent
* Improves the copy in the Search Ranking Compare widget.
* change the names to be translated too, provide context to be sure it is clear to translators they are SEO terms
* use a single source, for DRY and ease of potential changes later
* Enable the Site Kit feature flag
* Have Site Kit installed and set up for our Dashboard
* Go to the Dashboard
* Verify the copy of the widget' tooltips by comparing them to [the design](https://www.figma.com/design/DXKVj4tji7M65FYCYwBFUl/Dashboard?node-id=4137-15827&m=dev):
* …

Update copy in search ranking compare

---

packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js
packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap
packages/js/tests/shared-admin/components/__snapshots__/ai-generate-titles-and-descriptions-upsell.test.js.snap

* We want to add CTB codes to all upsell buttons.
* Adds data attributes to upsell buttons.
*
* Disable premium.
* Go to the post editor and click on the `use ai` button in the metabox for both `SEO title` and `Meta description`.
* In the modal make sure that the `Unlock with Yoast SEO Premium` button has the following two data attributes: 
```
data-action="load-nfd-ctb"
data-ctb-id="f6a84663-465f-4cb5-8ba5-f7a6d72224b2"
```
* Do the same for the  ✨ button in the readability analysis.
* Do the same for the initial upsell popup after first installing the plugin. (This is the same popup as the ✨ one).
* …

Add two CTB button codes

---

composer.json
composer.lock

* Updated dev dependencies
* Updated dev dependencies
Including updating the YoastCS dependencies.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/3.2.0
* https://github.com/PHPCSStandards/PHP_CodeSniffer/releases
* https://github.com/PHPCSStandards/phpcsutils/releases
* https://github.com/PHPCompatibility/PHPCompatibilityWP/releases
* https://github.com/automattic/VIP-Coding-Standards/releases
* https://github.com/sirbrillig/phpcs-variable-analysis/releases
* _N/A_

Composer: update to YoastCS 3.2.0

---

admin/class-my-yoast-proxy.php
admin/services/class-file-size.php
config/composer/actions.php
inc/class-my-yoast-api-request.php
inc/options/class-wpseo-option.php
lib/abstract-main.php
src/actions/indexing/indexable-post-type-archive-indexation-action.php
src/builders/indexable-builder.php
src/dashboard/infrastructure/taxonomies/taxonomies-collector.php
src/editors/framework/readability-analysis.php
src/editors/framework/seo/terms/description-data-provider.php
src/editors/framework/seo/terms/title-data-provider.php
src/integrations/admin/unsupported-php-version-notice.php
src/presenters/url-list-presenter.php
tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
tests/Unit/Images/Application/Image_Content_Extractor_Test.php
tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php

CS: various minor whitespace fixes

---

src/dashboard/infrastructure/taxonomies/taxonomy-validator.php
tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Constructor_Test.php

CS/QA: remove unused import use statements

---

admin/class-plugin-availability.php
admin/class-yoast-form.php
admin/class-yoast-input-validation.php
admin/import/plugins/class-import-aioseo-v4.php
admin/menu/class-replacevar-editor.php
config/composer/actions.php
src/actions/importing/aioseo/abstract-aioseo-settings-importing-action.php
src/actions/importing/aioseo/aioseo-taxonomy-settings-importing-action.php
src/dashboard/application/search-rankings/top-page-repository.php
src/dashboard/application/search-rankings/top-query-repository.php
src/dashboard/infrastructure/endpoints/readability-scores-endpoint.php
src/dashboard/infrastructure/endpoints/seo-scores-endpoint.php
src/dashboard/infrastructure/endpoints/site-kit-configuration-dismissal-endpoint.php
src/dashboard/infrastructure/endpoints/site-kit-consent-management-endpoint.php
src/dashboard/infrastructure/score-results/readability-score-results/cached-readability-score-results-collector.php
src/dashboard/infrastructure/score-results/seo-score-results/cached-seo-score-results-collector.php
src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php
src/deprecated/admin/class-customizer.php
src/deprecated/src/helpers/request-helper.php
src/deprecated/src/integrations/admin/disable-concatenate-scripts-integration.php
src/editors/framework/site/base-site-information.php
src/helpers/notification-helper.php
src/integrations/third-party/wincher-publish.php
src/services/importing/aioseo/aioseo-replacevar-service.php

* Improve code documentation
* Improve code documentation
* _N/A_

Docs: fix unconventional tag order

---

packages/js/tests/dashboard/services/widget-factory.test.js

Removed duplication of tests.
*
* Adds and refactor tests to the widget factory class.
* I removed tests because I added them as cases in existing tests.
* Navigate to `packages/js`.
* Generate coverage report by executing the command `yarn test --coverage`.
* Search for the `widget-factory.js`.
* Check you have full coverage.
*
*
Fixes [Add tests to widget factory for site kit supported version check](https://github.com/Yoast/reserved-tasks/issues/494)

refactor and added tests for widget factory

---

packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md

* The paragraph length assessment strings were changed in https://github.com/Yoast/wordpress-seo/pull/21824 . We should update the documentation to reflect that.
* Updates the _paragraph length_ assessment feedback strings in the assessment scoring documentation.
* [yoastseo] Updates the assessment scoring documentation for the _paragraph length_ assessment.
*
* Check that the formatting of the paragraph length assessment documentation looks correct: [Paragraph length documentation](https://github.com/Yoast/wordpress-seo/blob/update-assessments-scoring-documentation/packages/yoastseo/src/scoring/assessments/SCORING%20READABILITY.md#2-paragraph-length) …

Update the paragraph length feedback strings

---

packages/dashboard-frontend/.gitignore
packages/dashboard-frontend/eslint.config.mjs
packages/dashboard-frontend/jest.config.js
packages/dashboard-frontend/package.json
packages/dashboard-frontend/src/components/widget.js
packages/dashboard-frontend/src/scores/components/scores.js
packages/dashboard-frontend/src/scores/components/term-filter.js
packages/dashboard-frontend/src/widgets/organic-sessions/compare.js
packages/dashboard-frontend/src/widgets/organic-sessions/daily.js
packages/dashboard-frontend/tests/__mocks__/data-provider.js

* While finalizing the [dashboard-frontend PR](https://github.com/Yoast/wordpress-seo/pull/22152) together with Vraja, I forgot to push the latest commits. But I did create the artifact locally. So these commits were checked by Natalia, just not Thijs.
* Adds some tooling polish to the dashboard frontend package.
*
* Run the linting
* Run the tests
* Already tested through the artifact before.
*
Fixes #

Add missing commits from dashboard frontend setup

---

readme.txt
tests/Unit/bootstrap.php
wp-seo-main.php

*
* Sets the _WordPress tested up to_ version to 6.8.
*
*
*
*
Fixes #

Sets the WordPress tested up to version to 6.8

---

packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js
packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap
packages/js/tests/shared-admin/components/__snapshots__/ai-generate-titles-and-descriptions-upsell.test.js.snap

*
* Reverts #22113.
*
* NA
*
*
Fixes #

Reverts #22113

---

packages/js/package.json
packages/search-metadata-previews/package.json
packages/yoastseo/CHANGELOG.md
packages/yoastseo/package.json

> [!IMPORTANT]
> Do not rebase this PR. The "Version increase" commit 36873df2d6a05be2ad34b91842eb278a07c9f0a7 is the exact version that has been published to NPM. Orphaning this commit will make it impossible to properly determine changes since the published version.
* We want to release the following JS packages:
- yoastseo:3.1.0
* Releases a new version of the JavaScript package `yoastseo`.
* The focus here was on releasing `yoastseo`.
* NA, just package releases, no code changes.
*
*

Release of yoastseo 3.1.0

---

packages/dashboard-frontend/src/scores/components/score-content.js
packages/dashboard-frontend/src/scores/components/score-list.js
packages/dashboard-frontend/src/scores/components/scores.js
packages/dashboard-frontend/src/scores/score-meta.js

* We want to differentiate the tooltip related to not analyzed objects on the basis of the analysis type.
*  Differentiates the tooltip string related to not analyzed objects on the basis of the analysis type.
* N/A
* Make sure you have both `SEO Analysis` and `Readability Analysis` activated in `Yoast SEO` -> `Settings`
* Make sure you have some content which has not been analyzed
* Go to `Yoast SEO` -> `General`
* Hover the mouse on the `Not analyzed` label of both SEO scores and Readability scores widgets
* Verify the tooltip copy is the same as in the [design](https://www.figma.com/proto/DXKVj4tji7M65FYCYwBFUl/Dashboard?page-id=1593%3A2352&node-id=1593-2356&node-type=f …

Update tooltip text for not analyzed content in readability scores

---

packages/dashboard-frontend/src/components/trend.js
packages/dashboard-frontend/src/services/comparison-metrics-data-formatter.js
packages/dashboard-frontend/src/widgets/organic-sessions/compare.js
packages/dashboard-frontend/src/widgets/search-ranking-compare/search-ranking-compare-metric.js
packages/dashboard-frontend/src/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
packages/dashboard-frontend/src/widgets/search-ranking-compare/use-search-ranking-compare.js
packages/dashboard-frontend/tests/components/trend.test.js

* We want the show a green number when your avg position goes down, because that is good.
* Changes the color displayed for some features.
*
* Make sure you have positive numbers in the sessions compare widget but a `negative` number for the `Average position`. All these values should be green.
* If you have negative numbers for the values and a `positive` number for the `Average position` they should be red.
* Also make sure the chart widget behaves the same.
Also compare it to the design https://www.figma.com/proto/DXKVj4tji7M65FYCYwBFUl/Dashboard?page-id=1599%3A2169&node-id=2666-3831&viewport=84%2C94%2C0.3&t=JPbkyJ0il6p99AX3-8&scaling=min-zoom&content-scaling=fixed&star …

Make sure  that the correct color is shown.

---

packages/dashboard-frontend/src/services/plain-metrics-data-formatter.js
packages/dashboard-frontend/tests/widgets/top-pages-widget.test.js

*
* Decodes the url in the "Top 5 most popular content" widget on the dashboard. 
*
* Install Yoast SEO with site kit feature flag enable, you can do that by returning true in the site kit feature conditional.
* Have popular content url in other languages
* Check the url in the widget are rendered correctly without encoding symbols (%%)
* Check nothing has changed for sites in English.
* 
*
Fixes [Site kit widget Top 5 most popular landing page url in other languages](https://github.com/Yoast/reserved-tasks/issues/518)

518 site kit widget top 5 most popular landing page url in other languages

---

packages/yoastseo/src/scoring/assessors/ASSESSORS OVERVIEW.md

* In [another PR](https://github.com/Yoast/wordpress-seo/pull/22197), the links in the `ASSESSORS OVERVIEW.md` were changed incorrectly.
* Fixes broken links in the assessors documentation.
* [yoastseo] Fixes broken links in the assessors documentation.
*
* Check whether all links in this file work: [ASSESSORS OVERVIEW.md](https://github.com/Yoast/wordpress-seo/blob/fix-links-in-assessors-documentation/packages/yoastseo/src/scoring/assessors/ASSESSORS%20OVERVIEW.md)
No QA testing needed as the change is only in documentation.
*
*

Fix broken links in assessors documentation

---

packages/js/package.json
packages/search-metadata-previews/package.json
packages/yoastseo/CHANGELOG.md
packages/yoastseo/package.json

> [!IMPORTANT]
> Do not rebase this PR. The "Version increase" commit 175fde778fe9b62c3c780e8f848b69084882e71f is the exact version that has been published to NPM. Orphaning this commit will make it impossible to properly determine changes since the published version.
* We want to release the following JS packages:
- yoastseo:3.2.0
* Releases a new version of the JavaScript package `yoastseo`.
* The focus here was on releasing `yoastseo`.
* NA, just package releases, no code changes.
*
*
Fixes …

Release of yoastseo 3.2.0

---

packages/dashboard-frontend/src/widgets/organic-sessions/daily.js

* We want to avoid showing an horizontal scroller when the Organic session widget is displayed.
* Fixes the width of the table used in the screenreader text of the Organic sessions widget.
* [@yoast/dashboard-frontend 0.0.1 bugfix] Fixes a bug where the screen reader only table in the Organic Sessions widget was influencing the width on the page.
* N/A
* Use the Google Chrome browser
* Make sure you have Google Analytics set up
* Go to `Yoast` -> `General`
* Toggle the device toolbar in the Chrome Devtools and select a device with a small display (e.g. iPhone 14)
* Verify no horizontal scrollbar is shown  …

Fix eccessive width for the Organic session widget

---

src/dashboard/user-interface/setup/setup-flow-interceptor.php
tests/Unit/Dashboard/User_Interface/Setup/Abstract_Setup_Flow_Interceptor_Test.php
tests/Unit/Dashboard/User_Interface/Setup/Setup_Flow_Interceptor_Intercept_Test.php

* This improves the GA connection fix.
* Improves the bugfix about also intercepting the GA connection.
*
* Create a fresh site with tastewp (not locally)
* Install this RC/PR and the newest test helper.
* Enabled the site kit integration.
* Install Site Kit from our dashboard and start the setup.
* Select the also connect GA checkbox.
* Complete the setup and make sure you end up on our dashboard.
---
* Reset the Site Kit install.
* Start the setup from our dashboard.
* Select the also connect GA checkbox.
* At some point you get prompted this screen:
* Click on the account select box scroll all the way down and select new account.
* Complete the setup and make sure you …

Fix GA loading

---

packages/js/package.json
packages/search-metadata-previews/package.json
packages/yoastseo/CHANGELOG.md
packages/yoastseo/package.json

> [!IMPORTANT]
> Do not rebase this PR. The "Version increase" commit eef922875137731c9bd7b93323e5a49361c84198 is the exact version that has been published to NPM. Orphaning this commit will make it impossible to properly determine changes since the published version.
* We want to release the following JS packages:
- yoastseo:3.3.0
* Releases a new version of the JavaScript package `yoastseo`.
* The focus here was on releasing `yoastseo`.
* NA, just package releases, no code changes.
*
*
Fixes

Release yoastseo 3.3.0

---

packages/js/package.json
packages/js/src/ai-generator/components/errors/bad-wp-request-alert.js
packages/js/src/ai-generator/components/errors/subscription-error.js
packages/js/src/ai-generator/components/feature-error.js
packages/js/src/ai-generator/components/length-progress-bar.js
packages/js/src/ai-generator/components/suggestion-error.js
packages/js/src/ai-generator/components/suggestions-list-skeleton.js
packages/js/src/ai-generator/store/product-subscriptions.js

*
* Fixes a couple default prop warnings so we don't go over our limit.
* Refactors the `selectProductSubscriptions` fallback to be a valid object.
*
*
*
*
Fixes #

AI generator: fix default props

---

inc/class-upgrade.php

* We don't want an upgrade routine since the feature changed to op-in instead of out.
* Removes non released upgrade routine.
*
* Smoke test https://github.com/Yoast/wordpress-seo/pull/22253 to make sure this did not change anything it should not have.
*
*
Fixes #

Begone upgrade routine.

---

packages/js/tests/ai-generator/helpers/apply-pluggable-replacement-variables.test.js
packages/js/tests/ai-generator/helpers/enforce-title-variable.test.js
packages/js/tests/ai-generator/helpers/fetch-suggestions.test.js
packages/js/tests/ai-generator/helpers/focus-focus-keyphrase-input.test.js
packages/js/tests/ai-generator/helpers/is-considered-empty.test.js
packages/js/tests/ai-generator/helpers/prepare-prompt-content.test.js
packages/js/tests/ai-generator/store/applied-suggestions.test.js
packages/js/tests/ai-generator/store/product-subscriptions.test.js
packages/js/tests/ai-generator/store/prompt-content.test.js

* 
* Adds tests to AI generator from premium.
*
*
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/593

Adds tests from premium

---

packages/js/src/settings/routes/site-features.js

*
* Updates copy on llms.txt feature card.
*
* Confirm that you see the following copy in the feature card:
> Generate a file that points to your website's most relevant content. Designed to help AI Assistants understand your website better.
*
Fixes https://github.com/Yoast/reserved-tasks/issues/612

Update copy on llmstxt feature card

---

packages/related-keyphrase-suggestions/package.json
packages/related-keyphrase-suggestions/src/components/CountrySelector/index.js
packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
packages/related-keyphrase-suggestions/src/components/Modal/index.js
packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/index.js
packages/related-keyphrase-suggestions/src/elements/TableButton/index.js
packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestLimitReached.js
packages/related-keyphrase-suggestions/src/elements/UserMessage/index.js

> [!IMPORTANT]
> Based of https://github.com/Yoast/wordpress-seo/pull/22256
> The merge base should be updated to trunk automatically if that is merged first
* [@yoast/related-keyphrase-suggestions 0.0.1 bugfix] Fixes a bug where the CountrySelector would have invalid default values.
* [@yoast/related-keyphrase-suggestions 0.1.0] Refactors the `defaultProps` to be `defaultArguments` instead.
* See commits and their descriptions
* Start the storybook and smoke test the components
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/571

Related Keyphrase Suggestions: Refactor defaultProps to be defaultArguments

---

packages/ui-library/.storybook/interactive-docs-page.js
packages/ui-library/package.json
packages/ui-library/src/components/checkbox-group/index.js
packages/ui-library/src/components/dropdown-menu/index.js
packages/ui-library/src/components/file-import/index.js
packages/ui-library/src/components/modal/stories.js
packages/ui-library/src/components/notifications/index.js
packages/ui-library/src/components/pagination/button.js
packages/ui-library/src/components/pagination/index.js
packages/ui-library/src/components/popover/index.js
packages/ui-library/src/components/radio-group/index.js
packages/ui-library/src/components/sidebar-navigation/collapsible.js
packages/ui-library/src/components/sidebar-navigation/icon.js
packages/ui-library/src/components/sidebar-navigation/item.js
packages/ui-library/src/components/sidebar-navigation/link.js
packages/ui-library/src/components/sidebar-navigation/list.js
packages/ui-library/src/components/sidebar-navigation/mobile.js
packages/ui-library/src/components/tooltip-container/index.js
packages/ui-library/src/elements/autocomplete/index.js
packages/ui-library/src/elements/paper/content.js
packages/ui-library/src/elements/paper/header.js
packages/ui-library/src/elements/skeleton-loader/index.js
packages/ui-library/src/elements/toast/index.js
packages/ui-library/src/elements/toast/stories.js

> [!IMPORTANT]
> Based of https://github.com/Yoast/wordpress-seo/pull/22256
> The merge base should be updated to trunk automatically if that is merged first
* [@yoast/@yoast/ui-library 0.1.0] Refactors the `defaultProps` to be `defaultArguments` instead.
*
* Start the storybook: `yarn workspace @yoast/ui-library storybook`
* Smoke test the touched components (see commits)
* Noneed
*
Fixes https://github.com/Yoast/reserved-tasks/issues/576

UI library: Solve react/require-default-props warnings

---

packages/js/src/ai-generator/components/modal-content.js

*
* Disables "Generate 5 more" button only when limit reached and premium enabled.
*
* Edit a post and use this patch on local environment: 
[fake-api.patch](https://github.com/user-attachments/files/20724288/fake-api.patch)
* Enable Premium.
* Click on "Use AI" and get to the point you can generate title/description.
* Check you reach the 10 spark limit.
* Check you can still click on the "Generate 5 more" button
*
*
Fixes #

Disable "Generate 5 more" button only when limit reached and premium enabled.

---

packages/js/src/ai-generator/components/errors/not-enough-content-alert.js
packages/js/src/ai-generator/components/errors/rate-limit-alert.js
packages/js/src/ai-generator/components/errors/seo-analysis-inactive-error.js
packages/js/src/ai-generator/components/errors/site-unreachable-alert.js
packages/js/src/ai-generator/components/errors/subscription-error.js
packages/js/src/ai-generator/components/errors/timeout-alert.js
packages/js/src/ai-generator/components/errors/unethical-request-alert.js
packages/js/src/ai-generator/components/tip-notification.js
packages/js/src/shared-admin/components/ai-consent.js

*
* Removes premium text domain from the AI generator feature.
*
* Smoke test translation on:
* Tip notification
* Consent modal
* Errors:
*  Subscription error
* Not enough content error
* SEO analysis inactive error
* Site unreachable error
* Timeout error
* Unethical request alert error
*
*
Fixes [Change text-domain to Free](https://github.com/Yoast/reserved-tasks/issues/598)

Change text-domain to Free

---

packages/js/package.json
packages/js/src/ai-generator/components/app.js
yarn.lock

*
* Without Premium, in the AI generator modal's tooltip: Don't mention unlimited sparks.
*
* Devs: use the fake API
* Edit a post and use AI
* Verify the tooltip does not mention unlimited sparks
* Activate Premium
* Edit a post and use AI
* Verify the tooltip mentions unlimited sparks
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/630

Update the tooltip of the usage counter

---

packages/js/src/components/UpsellBox.js
packages/js/src/shared-admin/components/premium-upsell-card.js
src/presenters/admin/sidebar-presenter.php

* We want to remove some things from the upsells.
* Changes copy of the upsells.
*
* Open a post. in the metabox click on `Premium SEO analysis` and make sure the upsell does not show a price.
* Go to the dashboard and make sure the upsell does not show a price.
* Go to the tools page and make sure the upsell does not show a price.
*
*
Fixes #

Remove the price from different upsells.

---

packages/social-metadata-previews/package.json
packages/social-metadata-previews/src/shared/SocialImage.js

> [!IMPORTANT]
> Based of https://github.com/Yoast/wordpress-seo/pull/22256
> The merge base should be updated to trunk automatically if that is merged first
* [@yoast/social-metadata-previews 0.1.0] Refactors the `defaultProps` to be `defaultArguments` instead.
* See commits and their descriptions
* Just devs: link this Free to the Premium vendor folder
* Enable Premium
* Smoke test the social previews in the editor
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/575

Social Metadata Previews: Solve react/require-default-props warnings

---

tests/Unit/Llms_Txt/Application/Configuration/Abstract_Llms_Txt_Configuration_Test.php
tests/Unit/Llms_Txt/Application/Configuration/Llms_Txt_Configuration_Constructor_Test.php
tests/Unit/Llms_Txt/Application/Configuration/Llms_Txt_Configuration_Get_Configuration_Test.php

*
* Adds unit tests for the llms-txt configuration
*
* N/A
* N/A
* None
Fixes #

Add unit tests for the llms-txt configuration

---

tests/WP/Llms_Txt/Application/Available_Posts/Available_Posts_Repository_Test.php

*
* Adds integration tests for the available posts repository
*
* N/A
*
*
Fixes #

Add integration tests for the available posts repository

---

packages/js/src/ai-generator/components/app.js
packages/js/src/ai-generator/store/usage-count.js
src/ai-generator/user-interface/get-usage-route.php

*
* Fixes the limit for free sparks in the usage count for a WooCommerce product.
*
* Install and activate Woocommerce + Yoast SEO Free + Yoast SEO Premium
* Use Yoast Test Helper and switch to staging API
* Have an active Premium subscription
* Use AI on Product more then 10 times
* Check the limit is always 10 in the usage counter.
* Enable woo license and check the limit is now 100.
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/2426

2426 critical 256 rate limit on product instead of subscription required

---

packages/js/src/ai-generator/components/app.js

*
* Fixes the link in the AI generator error modal.
*
* Enable Premium without subscription.
* Edit a post and click on "Use AI".
* Check you are getting a subscription error.
* Click on the question mark and check you are redirected to the help link `https://yoast.com/help/faq-ai-in-yoast-seo` with parameters in the url like:
`https://yoast.com/help/faq-ai-in-yoast-seo/#utm_medium=software&utm_source=yoast-seo&utm_term=ai-support&utm_content=support-link&php_version=8.2&platform=wordpress&platform_version=6.8.2&software=premium&software_version=25.6-RC7&days_active=20297&shortlink=ai-generator-help-button-modal`
* Enable the subscription or disable premium
* Edit a post …

Fix main modal help link prop

---

tests/Unit/AI_Authorization/Infrastructure/Access_Token_User_Meta_Repository/Abstract_Access_Token_User_Meta_Repository_Test.php
tests/Unit/AI_Authorization/Infrastructure/Access_Token_User_Meta_Repository/Constructor_Test.php
tests/Unit/AI_Authorization/Infrastructure/Access_Token_User_Meta_Repository/Delete_Token_Test.php
tests/Unit/AI_Authorization/Infrastructure/Access_Token_User_Meta_Repository/Get_Token_Test.php
tests/Unit/AI_Authorization/Infrastructure/Access_Token_User_Meta_Repository/Store_Token_Test.php
tests/Unit/AI_Authorization/Infrastructure/Code_Verifier_User_Meta_Repository/Abstract_Code_Verifier_User_Meta_Repository_Test.php
tests/Unit/AI_Authorization/Infrastructure/Code_Verifier_User_Meta_Repository/Constructor_Test.php
tests/Unit/AI_Authorization/Infrastructure/Code_Verifier_User_Meta_Repository/Delete_Code_Verifier_Test.php
tests/Unit/AI_Authorization/Infrastructure/Code_Verifier_User_Meta_Repository/Get_Code_Verifier_Test.php
tests/Unit/AI_Authorization/Infrastructure/Code_Verifier_User_Meta_Repository/Store_Code_Verifier_Test.php
tests/Unit/AI_Authorization/Infrastructure/Refresh_Token_User_Meta_Repository/Abstract_Refresh_Token_User_Meta_Repository_Test.php
tests/Unit/AI_Authorization/Infrastructure/Refresh_Token_User_Meta_Repository/Constructor_Test.php
tests/Unit/AI_Authorization/Infrastructure/Refresh_Token_User_Meta_Repository/Delete_Token_Test.php
tests/Unit/AI_Authorization/Infrastructure/Refresh_Token_User_Meta_Repository/Get_Token_Test.php
tests/Unit/AI_Authorization/Infrastructure/Refresh_Token_User_Meta_Repository/Store_Token_Test.php

*
* Adds tests to ai authorization infrastructure section.
*
*
*
*
Fixes [Add tests to ai authorization infrustructure](https://github.com/Yoast/reserved-tasks/issues/695)

695 add tests to ai authorization infrustructure

---

tests/Unit/Llms_Txt/User_Interface/Available_Posts/Abstract_Available_Posts_Route_Test.php
tests/Unit/Llms_Txt/User_Interface/Available_Posts/Available_Posts_Route_Check_Capabilities_Test.php
tests/Unit/Llms_Txt/User_Interface/Available_Posts/Available_Posts_Route_Constructor_Test.php
tests/Unit/Llms_Txt/User_Interface/Available_Posts/Available_Posts_Route_Get_Conditionals_Test.php
tests/Unit/Llms_Txt/User_Interface/Available_Posts/Available_Posts_Route_Get_Posts_Test.php
tests/Unit/Llms_Txt/User_Interface/Available_Posts/Available_Posts_Route_Register_Routes_Test.php

*
* Adds tests for the available posts endpoint
*
*
*
*
Fixes #

Add tests for the available posts endpoint

---

css/src/ai-generator.css
packages/js/src/ai-generator/components/app.js

*
* Changes the AI generator button label and design.
*
* Edit a post and:
* Check the label of the AI generator button for Search appearance title is: Generate SEO title.
* Check the label of the AI generator button for Search appearance description is: Generate meta description.
* Check for Social appearance for facebook and x title AI generator button label is: Generate social title.
*  Check for Social appearance for facebook and x description AI generator button label is: Generate social description.
* Check the colors and border of the button match the [design](https://www.figma.com/design/X7AcWgsjZXP4cuR1y2K5dk/AI-button?node-id=2-2183&t=Bs5ICYei6qTgNVma-0).
* …

Change `Use AI` button to be more prominent

---

.github/PULL_REQUEST_TEMPLATE.md

* We don't use the label so it is ready to remove it.
* Removes a label from the PR template.
*
* N/A
*
*
Fixes #

Update the pull request template to no longer include the unused ui change label checkbox.

---

src/promotions/domain/black-friday-promotion.php

* We want to make sure the timing is right.
* Updates the timing to the correct 2025 timings.
*
* N/A just make sure that on this pr there is no sudden black friday sale on your site.
*
*
Fixes #

Set correct timing.

---

packages/js/src/components/BlackFridayPromotion.js

*
* Fixes margin for the Black Friday ad in elementor.
*
* Check the Black Friday ad in elementor editor is aligned:
*
*
Fixes #

fix BF ad margin on elementor

---

src/ai-authorization/user-interface/abstract-callback-route.php
tests/Unit/AI_Authorization/User_Interface/Callback_Route/Abstract_Callback_Route_Test.php
tests/Unit/AI_Authorization/User_Interface/Callback_Route/Callback_Test.php
tests/Unit/AI_Authorization/User_Interface/Callback_Route/Conditional_Test.php
tests/Unit/AI_Authorization/User_Interface/Callback_Route/Constructor_Test.php
tests/Unit/AI_Authorization/User_Interface/Callback_Route/Register_Routes_Test.php
tests/Unit/AI_Authorization/User_Interface/Refresh_Callback_Route/Abstract_Refresh_Callback_Route_Test.php
tests/Unit/AI_Authorization/User_Interface/Refresh_Callback_Route/Register_Routes_Test.php

*
*
*
*
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/696.

Add `ai-authorization` user interface tests

---

config/grunt/custom-tasks/verify-zip-size.js

*
* Removes the Slack webhook from verify-zip-size task to avoid a failure when creating a RC bigger than 5 MB.
*
*
* NA, only related to RC creation
*
Fixes #

Remove Slack webhook from verify-zip-size task

---

src/alerts/application/default-seo-data/default-seo-data-alert.php

* Follows https://github.com/Yoast/wordpress-seo/pull/22608 and opens the links in the notifications in new tabs.
* Opens the links in the AI generate notifications in new tabs.
*
* Use the instructions of https://github.com/Yoast/wordpress-seo/pull/22608 to display the new notifications both for Free and Premium
* Click the `Try it for free`  and `Learn how to use it.` links and confirm that they open in a new tab.
*
Fixes #

Open links for the AI generate feature in new tabs

---

admin/class-admin-asset-manager.php
css/src/installation-success.css
packages/js/src/installation-success.js
packages/js/tests/InstallationSuccessPage.test.js
packages/js/tests/__snapshots__/InstallationSuccessPage.test.js.snap
src/integrations/admin/installation-success-integration.php
tests/Unit/Integrations/Admin/Installation_Success_Integration_Test.php

* 
* Improves the Installation success page
*
* The look and feel of the page has been already approved by @uxkai, so only a general regression check is needed (the page loads, the styles are working, the links are working)
*
*
Fixes https://github.com/Yoast/ux/issues/317

Redesign the installation success page
