- js/src/components/MailchimpSignup.js
* When you enter an email address of someone else, you can see whether that person is subscribed. Due to privacy reasons, we should not show if a particular email address is added to our list. 
* For privacy reasons, no longer shows whether an email address is already subscribed to the newsletter.
* It feels very hacky, but this is the only way I could think of to get the desired result. The problem is that there is no difference between the MailChimp response you get when the email address is already on the list and when something else is wrong, except for the message (see below). If you know a better solution, please let me know 😄 
```
{ msg: "[email address] is already subscribed to list Yoast Newsletter. <a …
```
> Don't show it when an email address is already on the mailing list

- src/helpers/author-archive-helper.php
* On sites with large posts, we are seeing 503s occur from this query which scans a large number of rows:
```
SELECT COUNT(*) AS `count` FROM `wp_yoast_indexable` WHERE `object_type` = 'post' AND `object_sub_type` IN ('post') AND `author_id` = 'x' AND `is_public` = '1' LIMIT 1
```
This PR can be summarized in the following changelog entry: 
* Improves performance by selecting the first ID, rather than getting the total count in query of author_has_a_post_with_is_public_null and author_has_a_public_post.
Fixes #15389.
> Remove COUNT(*) from query in author_has_a_public_post() and author_has_a_post_with_is_public_null()

- src/commands/index-command.php
* To enable users to run the `wp yoast index --reindex` command with an extra argument, `--skip-confirmation`. This prevents confirmation prompts and allows automated scripts to use this command.
⚠️  There is a test in `tests/commands/index-command-test.php` for the `--reindex` command and the prompt. However, I am not sure if and how this should be modified. If this needs changes, please let me know as I'd like to know how to do this.
* Introduces the `--skip-confirmation` argument to run our wp-cli reindex command without confirmation prompt.
* N/A
1. Run the following command: `wp yoast index --reindex` and see the confirmation prompt.
1. Now run: `wp yoast index --reindex …
> Introduce skip confirmation to the Yoast reindex CLI

- src/helpers/author-archive-helper.php
* Per #15450, this is an expensive query and for authors that have no posts, the query will end up scanning all the rows.  We should add some caching around it to ensure the expensive query isn't called consistently if a false value is expected.
* Improves performance by adding caching around false values for authors with no posts in author_has_a_post_with_is_public_null and author_has_a_public_post. Props rebeccahum.
Fixes #15389.
> Add caching for authors with no posts to prevent full table scanning in author_has_a_public_post and author_has_a_post_with_is_public_null 

- js/src/components/WordPressUserSelectorSearchAppearance.js
* As parsing a string (like "false") to an integer, this will result in `0`.
This keeps the current functionality intact, but avoids the `state.value` being read as not set, though it is just set to no user.
* Prevents a console error when no user is selected in the Company or Person selector
*
*
Fixes #15461
> Simplify value parsing for userID

- admin/views/tabs/metas/paper-content/general/homepage.php
- admin/views/tabs/metas/paper-content/general/title-separator.php
* Add spacing around the knowledge graph container.
* Add spacing around the knowledge graph container.
*
* Pull the `develop` branch of the javascript repo
* Link the monorepo
* Check if there is enough spacing around the `Knowledge graph` block in the `Search Appearance` page
Fixes #
> FRO-120 Add spacing around the knowledge graph container

- src/conditionals/yoast-admin-page-conditional.php
- src/integrations/admin/dismissable-notification-integration.php
- src/integrations/admin/redesign-notification-integration.php
- src/presenters/admin/dismissable-notification-presenter.php
* We want to make sure people are not scared that the redesign/new visuals have any impact on their settings.
* Added a notification on all Yoast SEO admin-pages for installations done before this release explaining that the redesign is only visual, not functional.
* Created a new conditional to check for Yoast SEO-admin page
* Created a generic dismissable-notification-presenter
* Have an install that is activated before July 7th 2020
* Go to any Yoast SEO-admin page
* See the message being displayed at the top of the page
* Use the "Hide this notice" button to dismiss the notification and don't see it again
* Log in as a different user and see the notification
To restore the …
> Redesign notification (dismissable)

- lib/orm.php
The `and` and `or` have a different operator precedence (much lower) than `&&` and `||`, which can lead to hard to debug bugs.
* _N/A_
> CS: use boolean and/or operators

- js/src/edit.js
Got the error above when on term edit and classic editor, because `blockEditor` was not present. Lodash `get` searches more gracefully.
* Fixes an unreleased bug where an error would occur when on edit pages without a block editor.
> Use get to test for experimentalLinkControl presence

- inc/class-addon-manager.php
* Fixes the fact that we sometimes did multiple calls to my.yoast.com if you had multiple Yoast products running, when we could do it in one call.
* Added a quick cache, which caches the result for 1 minute, so we don't do the same call twice on a pageload.
*
Fixes https://github.com/Yoast/bugreports/issues/754
> Cache MyYoast requests differently

- css/src/metabox.css
- grunt/config/aliases.yaml
- js/src/components/MetaboxCollapsible.js
- js/tests/__snapshots__/advancedSettings.test.js.snap
- package.json
* The styling of the tabs did not match the design. This PR aims to improve the styling so that it better reflects the new design.
I think it looks sweeeeet :sparkles: 
* Improve the styling of the metabox tabs.
* Adds a `grunt` and `yarn` command to only build the CSS and JS while developing.
* Compare (the design)[https://www.sketch.com/s/accd731d-dfb3-493e-bb2f-d4df01c8f1e8/a/dnAmKb] with the version of the metabox in this branch. See that they match.
Fixes P1-25
> Improve the styling of the tabs

- grunt/config/eslint.js
- js/src/components/RelatedKeyPhrasesModal.js
- js/src/components/modals/SemRushLimitReached.js
- js/src/components/modals/SemRushLoading.js
- js/src/components/modals/SemRushUpsellAlert.js
* Users of the free plugin can use the SEMrush integration to look for related keyphrases but they can't add them to the Yoast SEO analysis. They should switch to Yoast SEO Premium to be able to do this.
* Add an Yoast SEO Premium upsell info alert on top of the SEMrush modal 
* Introduce a simple SemRushUpsellAlert component in the components/modals directory
* Edit a post
* Enter some focus keyphrase in the Yoast sidebar or in the Yoast metabox
* Click the button to open the modal dialog
* Observe the upsell info alert box
* Verify the link is working
Fixes [P3-46]
> P3-46 Create Upsell info Alert content for the modal

- admin/taxonomy/class-taxonomy-fields-presenter.php
* In [this commit](https://github.com/Yoast/wordpress-seo/commit/a0034a53d3c07c29af748abb22940f121f70cd66#diff-4a28d28b5c9cf861ebe0a4e82231f591R64) a help link was added to all fields. Unfortunately, it also adds that link to all hidden fields, which causes problems (styling issues and lots of duplicate links):
This fix will only render links for non-hidden fields. 
But besides fixing the bug, I wonder why we always add that specific URL to our input fields on taxonomies.
* Fixes an unreleased bug where too many links to help articles would render in the metabox.
* I've only disabled the help button for hidden fields.
* I am not sure we should hard-code the URL introduced in [this …
> Only add link buttons for non-hidden fields

- js/src/components/RelatedKeyPhrasesModal.js
- js/src/components/modals/SemRushRequestFailed.js
*
* Adds content for the SEMrush modal dialog for the scenario where the request to get related keyphrases from SEMrush fails. 
* Introduces a simple `SemRushRequestFailed` component in the `components/modals` directory
* The component is added to the `RelatedKeyPhrasesModal` for testing purposes.
* In `wordpress-seo/js/src/components/RelatedKeyPhrasesModal.js`, in `ModalContainer`, comment out all but `<SemRushRequestFailed />`
* Run `grunt build:js`
* In the backend, go to `Posts` and edit a post
* In the Yoast sidebar or metabox, click "Get related keyphrases"
* Verify the content follows the design as shown below:
Fixes [P3-38]
> Add SEMrush "request failed" content

- admin/views/tabs/metas/paper-content/post_type/post-type.php
- admin/views/tabs/metas/paper-content/taxonomy-content.php
* Removes the unnecessary `strong` tag in the `Content Types` tabs
* Removes the unnecessary `strong` tag in the `Content Types` tabs
*
* Pull the `developer` branch of the `javascript` repo
* Link the `monorepo`
* In the `Content Types` tab in the `Search Appearance` page check if the `strong` tag isn't visible anymore in the `Show SEO settings for Posts` text
Fixes https://yoast.atlassian.net/browse/FRO-126
> FRO-126 Remove strong tag in Content types

- js/src/components/RelatedKeyPhrasesModal.js
- js/src/components/modals/SemRushMaxRelatedKeyphrases.js
* Users of the premium plugin can use the SEMrush integration to look for related keyphrases and add them to the Yoast SEO analysis. A maximum number of 4 related keyphrases (whether they've been added via SEM rush or not) can be added.
* Add a alert box to be displayed conditionally in the SEMrush modal for Premium, if user can't add any new related keyphrase.
* Introduce a simple SemRushMaxRelatedKeyphrases in the `modals` directory.
* The alert will be conditionally displayed based of what we get from the Redux store about the number of related keyphrases.
* It shouldn't be rendered at all on the free plugin.
* build the JS with `grunt build:js`
* Edit a post
* Enter some focus …
> P3-3 Create "Max number related keyphrases entered" content

- js/src/inline-links/edit-link.js
- js/src/inline-links/inline.js
* This fixes a bug where a block in the block editor would crash because some React components could not be loaded from `window.wp.blockEditor`.
* Fixes a bug where certain React components could not be loaded in the block editor, leading to blocks crashing when they were selected.
* We need to import them in the render functions, since we can only know for sure that we are in the block editor when rendering the components.
* We can't tell WordPress that `wp-block-editor` script is a dependency when loading this JavaScript, since we cannot tell if the edit page is using the classic or block editor before loading the JavaScript files.
* Checkout `trunk`.
* Go to a post edit page.
* …
> Moved the import of window.wp.blockEditor components to the render funtions where they are used.

- inc/class-addon-manager.php
* Fixes `get_plugins()` undefined error if there is already `plugin.php` loaded via `init` hook by some other plugin. (e.g. [Stylekits for Elementor](https://wordpress.org/plugins/analogwp-templates))
This PR can be tested by following these steps: 
- Install  [Stylekits for Elementor](https://wordpress.org/plugins/analogwp-templates) plugin with Yoast or Yoast-Premium.
- After you activate both, a error will trigger at Yoast's `class-addon-manager.php` for `get_plugins()` undefined.
> Fix undefined `get_plugins()` error in some conditions

- .cache/.gitkeep
- .gitattributes
- .gitignore
- .travis.yml
* Dev environment improvement
* Enable PHPCS caching (Premium)
Since PHPCS 3.0.0, PHPCS has a caching feature available. While this feature cannot be used for the Free repo yet, it will be enabled for the Premium repo and to do so, certain changes are needed to shared files.
This commit makes those changes.
Note: this is a sister-PR to the PR in the Premium repo which adds the caching configuration to the PHPCS ruleset. This PR **has** to be merged first!!
`/.cache/` directory:
* Create the directory and place a `.gitkeep` file in it to allow it to be committed.
`.gitignore`:
* Prevent committing of cache files (already in place), but allow committing of the `.cache` directory.
`.gitattributes`:
* Do not include the `.cache` …
> PHPCS: enable caching between runs (Premium)

- admin/class-yoast-form.php
* Aligns input fields to one line in html code for automated tests.
* Aligns input fields to one line in html code for automated tests.
*
* Pull the javascript repo develop branch and link the monorepo
* Check in the source code if on the `Social` page the `Linkedin` field is one row
Fixes https://yoast.atlassian.net/browse/FRO-129
> Aligns input field to one line in html code

- src/generators/schema/article.php
- tests/generators/schema/article-test.php
* Only if the page is open for comments -or- closed for comments, but there are comments present, show the number of comments in the schema output.
* Props to https://github.com/gr8shivam for pulling this in https://github.com/Yoast/wordpress-seo/pull/13588
* The original file was deleted, so I was unable to move the commit in the way that would keep the committer name in it, sorry.
* Fixes a bug where the comment count would be output for Articles that did not accept comments. Props to [gr8shivam](https://github.com/gr8shivam).
* N/A
* Create a page which comments are not open for; see the comment count not output
* Create a page with an approved comment, close the comments; see …
> Output comment count in Article schema when relevant

- webpack/webpack.config.js
* Not really sure when this broke. But the `build` and `webpack-analyze-bundle` scripts are broken (due to missing `env` variable). 
* Fixes a bug where the webpack config would error when running the `build` or `webpack-analyze-bundle` scripts.
* We seem to mostly use the webpack config via the grunt task. There the env is created (see `grunt/config/webpack.js`. Which is why we did not notice.
* Switch to the release branch.
* Run `yarn build` and/or `yarn webpack-analyze-bundle`.
* Both should stop with an error similar to this:
```
wordpress-seo/node_modules/webpack-cli/bin/cli.js:244
throw err;
^
TypeError: Cannot read property 'environment' of undefined
at module.exports …
```
> P2-57 Fixes a bug where the webpack config env would not exist

- js/src/containers/MetaboxFill.js
* Terms now have a collapsible for the setting of cornerstone content. This is due to a misinterpretation of `isCornerstoneActive`, which is the general setting. But irrespective of that setting, cornerstone content does not apply to terms.
* Thanks @andizer for spotting.
* Fixes a bug where the cornerstone content collapsible was visible when editing taxonomies, while taxonomies cannot be cornerstone content.
* In the metabox fill, I've added a check that firsts tests whether we are on a post, so the isCornerstoneActive should return false for term metaboxes.
* Initially I adjusted the preferences selector `isCornerstoneContentActive()` in `isCornerstoneContentActive.js` to include the check, but I figured that selector should …
> Make cornerstone visibility depend on both general setting AND post/term

- inc/class-wpseo-replace-vars.php
Props to [jchristopher](https://github.com/jchristopher).
I wrote a page that documents a `\Namespaced\Class` and that has a Title `\Namespaced\Class` and when viewing the front end the `<title>` ends up as `NamespacedClass` instead of `\Namespaced\Class`
`esc_html()` is fired in `wp_get_document_title()` after this return and a call to `stripslashes()` prevents titles with backslashes e.g. when documenting a namespaced PHP class.
* Fixes a bug where slashes in titles were removed before they were used as a replacement variable.
* Removes `stripslashes` from `retrieve_title()`
1. On `trunk`, enter a title with `\` in it, for example: `\Nice\Namespace`. Save the post.
2. On the front-end, check that the `\` is stripped.
3. …
> Removes stripslashes from retrieve_title()

- css/src/editor/metabox.css
* This very simple PR will allow removing the CSS file that `wpseo-news` has.
* Add `.wpseo-meta-section-content` class with 16px padding to use in add-ons within their specific metabox tabs.
*
Fixes #
> Add a generic class to allow styling inside of metabox tab section

- css/src/components/headings.css
- integration-tests/notifiers/test-class-configuration-notifier.php
* Changes specificity so that headings css only affect our headings.
* Changes specificity so that headings css only affect our headings.
*
* Pull the develop branch of the javascript repo
* Link the monorepo and build the plugin
* Go to `SEO` -> `Social` -> `Facebook` and click on `Upload image`
* Check if the headings are the standard WordPress headings
Fixes https://yoast.atlassian.net/browse/FRO-136
> FRO-136 upload image styling

- inc/sitemaps/class-sitemaps.php
CC @enricobattocchi 
* We changed the `readfile` function to `get_contents()` from `wp_filesystem` to fix the cs error in `class-sitemaps.php`
* CS fix
* Chose for WP_Filesystem because this was recommended by wordpress and the error message
* On trunk: build and activate the plugin
* Go to http://basic.wordpress.test/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl
* Make sure the sitemap gets downloaded and looks fine
* Repeat the steps on this branch
> Changed readfile to get_contents from wp_filesystem

- js/src/initializers/admin.js
And simplify the JavaScript to match the other changes to the light switches.
* See issue, make sure the toggle is usable again
* N/A (regression)
* Simplify JavaScript according to surrounding code
* Settings page: Yoast -> Archives -> Author
* Toggle the "Show author archives in search results?" to and make sure the "Show archives for authors without posts in search results?" option appears
Fixes FRO-149
> Missing no posts no index toggle

- admin/views/tabs/metas/paper-content/media-content.php
- js/src/initializers/admin.js
* Inverses the functionality of the Disable Attachment toggle, this is a "disabled"-option which needed to be flipped visually.
* N/A (regression)
* N/A
* Settings: Yoast -> Search Appearance -> Media
* Toggle the "Redirect attachment to itself" and have the other options show when it is set to "No"
* This should match the "disable-attachment" setting (you can search in the source and see its value) - "true" = redirect to itself
Fixes FRO-172
> Redirect attachment toggle fix

- admin/views/tabs/metas/breadcrumbs.php
- admin/views/tabs/metas/paper-content/breadcrumbs-content.php
* Removes the breadcrumbs paper styling and adds extra header.
* Removes the breadcrumbs paper styling and adds extra header.
*
* Pull the release/14.5 branch from the wordpress-seo repo
* Link the monorepo and build the plugin
* Check if the paper is remove in `SEO` -> `Search Appearance` -> `Breadcrumbs` and check if there is an extra heading
Fixes https://yoast.atlassian.net/browse/FRO-170
> Remove paper style breadcrumbs and add extra header

- admin/class-yoast-form.php
* Updates the radio input and legend to the new styling
* Updates the radio input and legend to the new styling
*
* Pull the javascript repo
* Pull this premium branch FRO-132-premium-import-export-pages
* Link the monorepo to the premium branch
* Merge this branch with a `--no-commit`
* Check under `SEO` -> `Tools` -> `Import/export` under the `Import redirects` if the radio's are correct.
Fixes https://yoast.atlassian.net/browse/FRO-132
> FRO-132 Updates radio and legend to new styling

- src/integrations/admin/indexation-integration.php
- src/presenters/admin/indexation-list-item-presenter.php
- tests/integrations/admin/indexation-integration-test.php
- tests/presenters/admin/indexation-list-item-presenter-test.php
* Reintroduces the checkmark when the sites is successfully indexed on the tools page.
* Reintroduces the checkmark when the sites is successfully indexed on the tools page.
*
* Check if the green checkmark show left beside the text "Great, your site has been optimized!" if you've indexed your site.
Fixes https://yoast.atlassian.net/browse/FRO-152
> FRO-152 Update check mark to new class and update tests

- admin/views/tabs/network/features.php
This was breaking all the toggles in the feature tab of the network admin since relies on the toggles having as allow_enable_admin_bar_menu.
The prefix was probably removed by accident by Team Frontend during the redesign of the network pages
* Make sure that the feature toggles work on the network tab.
* Fixes a bug where saving features in the network admin would disable all features for all sites.
* Set-up a multisite (does not need to be a fresh install)
* Go to the General->Features tab in the network admin
* Toggle some features and save
* Reload the page
* See that the values are persisted
> Add the ALLOW_KEY_PREFIX back to the toggles

- admin/class-yoast-notification.php
- admin/watchers/class-slug-change-watcher.php
- css/src/components/headings.css
- css/src/editor/post-overview-global.css
* Fix the styling of the deleting content notification
* N/A
* N/A
* Delete a post/page on the overview page and check if the styling of the notification is okay.
Fixes https://yoast.atlassian.net/browse/FRO-174
> FRO-174 Style delete content notification

- src/integrations/disable-core-sitemaps.php
- tests/integrations/disable-core-sitemaps-test.php
* Disables the WP Core sitemaps as introduced in WordPress 5.5.
* Ours are better.
* Check out 5.5, see that the core sitemaps are disabled.
Fixes PROD-190
> Disable WP core sitemaps

- admin/views/partial-notifications-template.php
- css/src/components/buttons.css
- css/src/components/paper.css
- js/src/admin-global.js
Not fixed:
- Restore button styling
- Using "restore" has unwanted nesting of papers
*
*
*
*
Fixes FRO-131
> Restore button functionality in notifications

- css/src/editor/metabox.css
- css/src/gutenberg-modal.css
- js/src/components/contentAnalysis/SeoAnalysis.js
*
* Restores basic styling for the Related keyphrases modal dialog after trunk merge.
* deleted `gutenberg-modal.css` and moved its _two CSS rules_ to `metabox.css`: I'd think this is fine because it's just a very few lines of CSS cc @JoseeWouters 
* Also restores a line break that was introduced in https://github.com/Yoast/wordpress-seo/pull/15368 
- go to the Meta box > open SEO analysis 
- verify the two links `+ Add synonyms` and `+ Add related keyphrase` are on separate lines 
- observe the "Get related keyphrases" button in both the meta box and the sidebar 
- verify there's some spacing between the input field and the button e.g.:
- enter a focus keyphrase 
- click "Get …
> Restore Related keyphrases modal basic styling.

- js/src/components/RelatedKeyPhrasesModal.js
- js/src/components/modals/SemRushLimitReached.js
* The limit-reached content of the SEMrush related keyphrases modal (created in #15369) used a `yoast-upsell-button`, which is not used anymore due to (admin) redesign changes. 
This caused the limit-reached content to look like this:
* Fixes a bug where the wrong css class was used for the SEMrush limit-reached upsell button. 
* As suggested by Rolf: the button now uses the `yoast-button yoast-button--buy class`, and the `yoast-button-upsell__caret` is replaced with `yoast-button--buy__caret`. 
* The `yoast` class is added to the `ModalContainer` in the `RelatedKeyphrasesModal` to enable it to work 
* Checkout this branch and build
* In the backend, go to Posts and edit a post
* In …
> P3-62 Fix SEMrush limit-reached upsell button css

- admin/tracking/class-tracking-settings-data.php
- inc/class-upgrade.php
- inc/options/class-wpseo-option-wpseo.php
- src/actions/indexables/indexable-complete-indexation-action.php
- src/commands/index-command.php
- src/integrations/admin/indexation-integration.php
- src/routes/indexable-indexation-route.php
- tests/actions/indexables/indexable-complete-indexation-action-test.php
- tests/commands/index-command-test.php
- tests/integrations/admin/indexation-integration-test.php
- tests/routes/indexable-indexation-route-test.php
* We want to set a flag to indicate that the indexation process is completed. This makes it easy to tell when it is.
* Sets an `indexable_indexation_completed` flag in the `wpseo` option when the indexable indexation process has been completed.
*
* Visit a Yoast SEO admin page (for example the SEO tools page: _SEO_ > _Tools_)
* If you have currently more then 25 unindexed indexable, you should see a notification saying you should index your site.
* If not, reset the indexables tables (e.g. by using the Yoast Test Helper plugin).
* In your database, check the `wpseo` option in the `wp_options` table.
* It should have an entry for …
> P2 22 Introduce indexables indexation completed option

- js/src/helpers/replacementVariableHelpers.js
This ensures that they do not show up as a replacement variable in the replacement variable editor
* `contentImage` and `snippetPreviewImageUrl` are not sensible variables, they also do not have any value when they are used.
* Add contentImage and snippetPreviewImageUrl to the list of nonReplaceVars.
1. Verify the bug on trunk
1. Go to a replacement variable editor
2. Enter `%co`
3. See that `contentImage` show up as a replacement variable
7. Enter `%snippet`
8. See that `snippetPreviewImageUrl` is a suggestion
2. Checkout this branch
3. Build the JS
4. Go to a replacement variable editor
5. Enter `%co`
6. See that `contentImage` is no longer a suggestion
7. Enter `%snippet`
8. See …
> Add contentImage and snippetPreviewImageUrl variables to nonReplaceVars

- package.json
- yarn.lock
*
* Upgrades plugin-grunt-tasks, gets rid of the sass dependency.
* Cherry-picked the appropriate commit from #15545, since the original PR became outdated and rebasing it would be less efficient.
* Pull, run yarn, check that all grunt tasks still work.
Fixes #
> Bump plugin-grunt-tasks, drops sass dependency

- admin/import/plugins/class-abstract-plugin-importer.php
- admin/import/plugins/class-import-squirrly.php
- inc/class-upgrade.php
- src/actions/indexation/indexable-post-indexation-action.php
- src/actions/indexation/indexable-term-indexation-action.php
- src/integrations/watchers/option-titles-watcher.php
- tests/actions/indexation/indexable-post-indexation-action-test.php
- tests/actions/indexation/indexable-term-indexation-action-test.php
- tests/integrations/watchers/option-titles-watcher-test.php
[1] Placing the placeholder creation for `WHERE ... IN ()` type clauses in the `$wpdb->prepare()` function call, allows for static analysis tools to verify these type of clauses are set up correctly.
Includes updating the expectations in the unit tests to match.
[2] Small tweak: Passing the DB query replacements as an array allows to bypass an "Incorrect number of replacements passed" notice.
* _N/A_
> QA: tweak some prepared SQL statements

- src/config/migrations/20200702141921_CreateIndexableSubpagesIndex.php
- src/integrations/blocks/abstract-dynamic-block.php
- src/repositories/indexable-repository.php
This PR does the following:
- Adds an index for the queries made by siblings and child blocks
- Ensures siblings and child blocks don't crash when a custom class name is entered.
- Ensures siblings and child blocks only display published posts.
To test:
- Checkout the branch in premium with the same name.
- Create a page that has two children, one of which isn't published.
- Add a subpages block to this page.
- It should only display the published subpage.
- Add a custom class name to this block in the sidebar under advanced.
- The block shouldn't crash.
> Siblings and subpages block fixes

- src/conditionals/xmlrpc-conditional.php
- src/integrations/xmlrpc.php
- tests/integrations/xmlrpc-test.php
* The `xmlrpc.php` file and all possible ways to request it are now automatically `noindex`'d, removing them from Google's search results.
* Didn't unittest the header output as that's proving impossible.
* Open example.com/xmlrpc.php, see the HTTP header output contains an `X-Robots-Tag: noindex, follow` header.
Fixes PROD-191
> XMLRPC noindexing

- js/src/inline-links/edit-link.js
- js/src/inline-links/utils.js
* As we added our own inline link format `yoast-seo/link` we remove the `core/link` format. This can cause problems with Richtext implementations which rely on the presence of the `core/link` format. This PR changes our own format from `yoast-seo/link` to `core/link` which means we now officially take ownership of `core/link` when Yoast SEO is active.
* Fixes a bug where inline link functionality in custom blocks could be missing.
* As we added our own inline link format `yoast-seo/link` we remove the `core/link` format. This can cause problems with Richtext implementations which rely on the presence of the `core/link` format. This PR changes our own format from `yoast-seo/link` to `core/link` which means we now officially take …
> Fixes a bug where core/link format isn't available anymore

- admin/metabox/class-metabox.php
- css/src/metabox.css
- inc/class-wpseo-meta.php
- inc/class-wpseo-utils.php
- js/src/components/SchemaTab.js
- js/src/components/fills/MetaboxFill.js
- js/src/components/fills/SidebarFill.js
- js/src/containers/SchemaTab.js
* This is the rebased version of https://github.com/Yoast/wordpress-seo/pull/15323
* We are adding a Schema tab to provide more insights into what Yoast SEO does with schema in the back-end.
* Adds the JS side for the new schema tab.
* Check that the Schema tab renders on Posts and Pages
* In Pages: Only the page type select box should be visible.
* In Posts: The article and page type select boxes should be visible.
* Check that values are set and fetched from the hidden input fields:
* Setting:
1. Change a value in schema tab
2. Check that the corresponding hidden input is changed
1. This can be done in the browser's console with the following selector: …
> P1-17 Create the schema tab component

- src/presentations/indexable-presentation.php
* In the sharing metadata used for Facebook, Twitter, Pinterest, LinkedIn and many other sites, we now output the post title instead of the SEO title. This prevents the brand name from being added in most cases, which is better on those platforms. You can still set a specific sharing title on the Social tab of the Yoast SEO post settings.
* Used the `breadcrumbs_title` to prevent an extra query.
* See a post, page or other URL, see the `og:title` in the output no longer has the site name added to it.
Fixes #9408 
Fixes PROD-193
> Use the post title instead of the SEO title for OpenGraph

- css/src/metabox.css
- js/tests/__snapshots__/advancedSettings.test.js.snap
This ensures that a border bottom will be displayed for the metabox container.
* No border on tabs without collapsibles. See:
* Fixes a bug where there is no border on the bottom of metabox tabs without any collapsible sections.
* Because the border is added to the metabox container, it is no longer necessary to add a border on the collapsibles.
* Test together with https://github.com/Yoast/javascript/pull/764
* Build everything :wrench: 
* Checkout the metabox
* See that the readability tab has a border bottom
* See that the SEO tab still looks good (ie. there is a border between the collapsed collapsibles).
Fixes P1-54
> Show a bottom border for the metabox container

- src/initializers/disable-core-sitemaps.php
- tests/initializers/disable-core-sitemaps-test.php
Turns the disable core sitemaps integration into an initializer so it is loaded before WordPress redirects to the sitemap.
Fixes https://yoast.atlassian.net/browse/QAK-2011
Test instructions:
- run `./wp.sh core update --version=nightly` to update to WordPress 5.5
- Visit basic.wordpress.test/sitemap.xml
- You should be redirect to the Yoast sitemap and not see a 404.
> Turns disable core sitemaps into an initializer

- admin/pages/dashboard.php
- admin/tracking/class-tracking-settings-data.php
- admin/views/class-yoast-integration-toggles.php
- admin/views/tabs/dashboard/integrations.php
- inc/options/class-wpseo-option-ms.php
- inc/options/class-wpseo-option-wpseo.php
- integration-tests/inc/options/test-class-wpseo-option-wpseo.php
* We want to have an “Integrations” tab in the general settings of Yoast SEO, where people can disable the SEMrush integration in its totality.
* Adds an "Integrations" tab in the Yoast SEO General Settings, showing the toggle to enable/disable SEMrush integration.
* Added a `Yoast_Integration_Toggles` class which manages the array of integration toggles.
* Uses `Yoast_Feature_Toggle` class as it is generic enough to be used for integrations as well as features.
* ~Enabling/Disabling the toggle currently *does not set* the option (called `semrush_enable`). The option must probably be declared somewhere else in the tree.~
* Added an option called `semrush_integration_active` in the `wpseo[]` options array. It's also added to the …
> P3-73 Create an "Integrations" tab in the General settings of Yoast SEO

- admin/formatter/class-metabox-formatter.php
This change was made originally in https://github.com/Yoast/wordpress-seo-premium/pull/2868 - but I had to be done in wordpress-seo 
* The "Yoast didn't recognize my keyphrase" link had disappeared.
* Restores the "Yoast didn't recognize my keyphrase" link.
* `isPremium` was moved to `class-wpseo-utils` in this [commit](https://github.com/Yoast/wordpress-seo-premium/commit/6f7457b958f4dd65302a98b725d242180ff730cd). It seems that this broke the "Yoast didn't recognize my keyphrase" link functionality. @andizer and I created a quick fix by reintroducing `isPremium` in `class-wpseo-utils`, so that this is fixed before the 14.6 release.
* In the mean time, I will ask team components about a possible better solution.
This PR can be …
> P2-84-yoast-didnt-recognize-my-keyphrase-not-shown

- admin/class-admin-asset-manager.php
- admin/class-asset.php
- integration-tests/test-class-admin-asset.php
* Optimize script loading by removing `ver` parameters from scripts and styles when they're not needed.
* We use the `$flat_version` in filenames everywhere when registering our assets, so we don't need the `?ver` parameter for cache busting. Removing this makes sure the web worker uses the same scripts as the browser.
* Everything should basically keep working, this impacts the script that runs the analysis. If that works, this should be OK.
Fixes QAK-2035
> Optimize script and style loading

- admin/class-yoast-form.php
- js/tests/__snapshots__/advancedSettings.test.js.snap
* Updates the checkboxes to the new Yoast styling in the plugin.
* Updates the checkboxes to the new Yoast styling in the plugin.
*
* Build the plugin and get the `https://github.com/Yoast/wpseo-woocommerce/tree/FRO-211-woocommerse-styling-update branch` from the wpseo-woocommerce repo.
* Install and activate Woocommerce
* Go the the Woocommerce page under SEO
* Check if the checkboxes uses the new styling
Fixes https://yoast.atlassian.net/browse/FRO-211
> Update checkbox to new styling

- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- js/src/components/WordPressUserSelectorSearchAppearance.js
* The message that we show when no user is selected is ugly and does not match the style for when a company is not selected.
* Also moves the "company" header slightly higher, to have this placed the same way when switching between person and company.
* Improves the styling of the warning when no person is selected in the Person/Company schema selector.
* Used the Alert from Yoast-components
* Toggle between company/person on the Yoast SEO -> Search Appearance settings page
* See the alert being much more pretty
**Before**
**After**
> Convert person selection warning to Alert

- src/conditionals/web-stories-conditional.php
- src/integrations/third-party/web-stories.php
- tests/conditionals/web-stories-conditional-test.php
- tests/integrations/third-party/web-stories-test.php
* This is a follow-up to #13446
* Adds support for the upcoming [Web Stories](https://github.com/google/web-stories-wp) WordPress plugin by Google, which uses a `web-story` post type
*  Add support for adding metadata to Web Stories (the `web-story` post type) from the [Web Stories](https://github.com/google/web-stories-wp) plugin.
* Unhooks `web_stories_story_head` actions added by the Web Stories plugin itself
* Uses `wp_dequeue_script` and `wp_dequeue_style` to remove Yoast assets that are not relevant for the stories editor and dashboard, since those are custom React apps and not Gutenberg.
1. Install current nightly build of the Web Stories plugin  
1. Visit https://github.com/google/web-stories-wp/actions?query=workflow%3A%2 …
> Add Web Stories integration

- js/src/components/MetaboxCollapsible.js
* Remove scrollbar from overflow in metabox titles.
* Remove scrollbar from overflow in metabox titles.
* Also checkout the same branch from javascript.
* Check in Windows in the metabox of a post/page if the title are fully visible and don't scroll.
Fixes https://yoast.atlassian.net/browse/FRO-217
> FRO-217 title scrollbar windows fix

- js/src/analysis/isWordFormRecognitionActive.js
* In the `window.wpseoScriptData` the `wordFormRecognitionActive` was changed to an actual boolean instead of a string `0` and `1`, which caused this bug.
* Fixes a bug where the word form upsell would not be shown anymore.
*
* Verify the upsell is back in the SEO analysis collapsible of the metabox and sidebar (see issue screenshot).
* Check this branch in premium, the upsells should not be there.
Fixes https://yoast.atlassian.net/browse/P1-56
> P1-56 Fix word form recognition check

- src/presentations/indexable-post-type-presentation.php
- src/presentations/indexable-presentation.php
- src/presentations/indexable-term-archive-presentation.php
* Restrict the `og:title` change introduced in [this pull](https://github.com/Yoast/wordpress-seo/pull/15622) to single posts and single terms.
* See QAK-2042
Fixes QAK-2042
> QAK-2042 Restrict og:title change to single URLs

- css/src/metabox.css
- js/src/components/MetaboxCollapsible.js
- js/src/components/social/SocialMetadata.js
- js/src/components/social/SocialUpsell.js
* Because the admin redesign was reverted, we also have to revert part of the styling updates we have made in the metabox.
* There was a bug which caused the "separator" (border top on collapsible_content) to not appear, now fixed. Thijs signed off on the separator being ok to ship.
* The `FacebookPreview` had `hasSeparator={ true }`, which it should not have, because it is the top component. Fixed.
* [non-user-facing] Metabox collapsible colouring has been reverted from purple to its original colour, to fall in line with delays in new designs elsewhere in the plugin.
* [non-user-facing] There was an unreleased bug causing a border to appear at the top of the social tab where there should be none.
* There is now a small separator …
> Metabox styling reverts and fixes

- src/generators/schema-generator.php
* When we output an `Author`, we output a Schema piece of `@type` `Person`, if you want to filter _all_ instances of `Person`, we didn't have a filter for that. Now we do.
* Adds the option to filter our Schema by `@type`.
> Add a filter for the graph piece's type

- js/src/redux/selectors/fallbacks.js
- js/tests/redux/selectors/fallbackSelectors.test.js
- readme.txt
* See https://github.com/Yoast/wordpress-seo/pull/15622 
* Changes the Facebook preview title fallback to be the indexable title instead of the SEO title.
* Used the title replacement variable in the store instead of adding it again to a value that might make more sense.
* Build this branch in premium.
* Create a post, edit the title.
* Check the facebook preview, it should have the post title.
Fixes https://yoast.atlassian.net/browse/P1-69
> Use title as facebook title fallback

- admin/taxonomy/class-taxonomy-content-fields.php
- inc/options/class-wpseo-taxonomy-meta.php
- js/src/containers/MetaboxFill.js
- js/src/initializers/term-scraper.js
- src/builders/indexable-term-builder.php
*
* Enables the cornerstone content toggle for taxonomies.
*
* Create a new category, save it, look it up in the indexables table and make sure `is_cornerstone` is `0`.
* Set the Is cornerstone content toggle to true and save it again, and make sure the toggle is set to true.
* Look it up in the indexables table and make sure `is_cornerstone` is `1`.
* Redo these steps for a custom taxonomy as well.
Fixes #
> Add cornerstone toggle to terms

- js/src/inline-links/utils.js
* Fixes a bug where an inline link that opens in a new window would render `undefined` in the aria-label
* Fixes a bug where an inline link that opens in a new window would render `undefined` in the aria-label.
* Omit the aria-label entirely until Gutenberg comes up with a better solution.
- create a post 
- add a paragraph
- select some text in the paragraph and add an external link
- check "Open in new tab" in the add link UI
- save the post
- see the post preview
- inspect the link source and confirm there is no longer an aria label value.
Fixes https://yoast.atlassian.net/browse/P1-71
> Inline link aria-label fix

- admin/config-ui/class-configuration-storage.php
- admin/config-ui/class-configuration-structure.php
- admin/config-ui/fields/class-field-tracking-intro.php
- admin/config-ui/fields/class-field-tracking.php
- admin/tracking/class-tracking.php
- admin/views/class-yoast-feature-toggles.php
- inc/options/class-wpseo-option-wpseo.php
- integration-tests/config-ui/test-class-configuration-structure.php
* Allow people to opt in to or out of tracking.
The following use cases:
- Only Yoast SEO free:
- tracking off by default
- Only premium:	
- tracking on by default
- Free + add-on:
- tracking on by default
The feature toggle and the config wizard option will always default to off when they've not been specifically set to on.
* We've added the option for users to opt-in to allow Yoast to track some data about their site.
* [wordpress-seo-premium] We've added the option to opt-out of our usage tracking.
* The `tracking` option defaults to `null`, which means that it can be overridden by the filter in premium and add-ons.
Two spots:
* See step 7 of the config wizard. Note that this …
> Add tracking opt-in

- js/src/redux/selectors/fallbacks.js
- js/tests/redux/selectors/fallbackSelectors.test.js
* Show term title as fallback for Social Previews. An oversight in https://github.com/Yoast/wordpress-seo/pull/15664/files was that "title" is only filled out in posts. For terms the relevant replacevar is "term_title"
* [wordpress-seo-premium] Fixes an unreleased bug where social previews did not correctly fall back to the title of a term if the social title fields were empty.
*
* Create a new term, have empty social fields. Enter a title for the term. Preview fields should fall back to that title.
Fixes QAK-2062
> Use term_title as fallback for terms rather than empty replacevar title

- js/src/indexation.js
* At the moment, when an indexation process finishes (either with success or with a fail), feedback is shown to the user as plain text. This isn't very eye-catching. Therefore, these messages should be shown as an alert in the top of the screen.
* Adds an alert to signal whether an indexation process succeeded / failed.
* 
* Check out `feature/internal-linking-phase-2` in Premium and merge this branch into it. Build.
* Use the Yoast Test Helper to reset the indexables and the prominent words.
* Go to the Yoast Tools page.
_Test indexable indexation success when the notice wasn't hidden_
* In the top of the screen, you should see a green alert that signals that you should run the …
> Fix indexation alerts

- src/presentations/indexable-post-type-presentation.php
- src/presentations/indexable-term-archive-presentation.php
- tests/presentations/indexable-post-type-presentation/twitter-title-test.php
- tests/presentations/indexable-term-archive-presentation/twitter-title-test.php
*
* The user changelog item is already covered in the item from https://github.com/Yoast/wordpress-seo/pull/15622.
* Internal changelog item: Fixes a bug where the SEO title instead of the post/term title would still be shown as twitter:title.
* Like [the changes before](https://github.com/Yoast/wordpress-seo/pull/15662), I’ve limited the changes to single posts and single terms.
* Disable Open Graph in the Yoast Settings so that the twitter:title is output.
* Write a post with a title.
* Don't manually set a twitter title in the social previews.
* Publish the post.
* Go to the frontend and see that only the post title is output as `twitter:title`, without the `[separator] [site …
> Show post/term title instead of SEO title as twitter:title

- js/src/structured-data-blocks/faq/block.js
- js/src/structured-data-blocks/how-to/block.js
* For WP 5.5 and the block directory, we need to add “Yoast” to our block names, because if people have the “most used blocks” option enabled, they’ll lose the context that the blocks are ours.
* Prefixed the FAQ and HowTo block names with Yoast.
*
* Use the `Add block` functionality.
* See FAQ and HowTo being prefixed by Yoast.
Fixes https://yoast.atlassian.net/browse/P1-67
> P1-67 Prefix block names with Yoast

- Gruntfile.js
- composer.json
- config/composer/actions.php
- grunt/config/aliases.yaml
- grunt/config/clean.js
- grunt/config/eslint.js
- grunt/config/postcss.js
- grunt/config/shell.js
- grunt/config/watch.js
- js/tests/data.test.js
- js/tests/edit.test.js
- js/tests/helpers/factory.js
Current situation: because the plugin-grunt-tasks has a "CSS" section which tries to load a "sass" configuration which does not exist; the `grunt watch` command fails to do anything.
- Defining a `watch:css` config specifically combats this problem.
- Optimized PHPCS to only check for branch-changed files
- Optimized Lint to only check for branch-changed files
- Added the `src` directory to PHP checks
- Added the `JavaScript tests` to the checks (linting)
- Reduced the execution time significantly
- Parallel linting
- Only lint & check CS for changed files
- Added new directories and files to the scope (`src`-folder, `JavaScript tests`)
- Not having to have a `make it work` / `build assets` command in your bash aliases anymore - `grunt build-watch` will do the work for you
- Having a tool …
> Fix `grunt watch`

- js/src/structured-data-blocks/faq/block.js
- js/src/structured-data-blocks/how-to/block.js
* Compatibility with WordPress 5.5: makes sure Yoast structured data blocks are found on more keywords and have examples in the block inserter.
* Compatibility with WordPress 5.5: makes sure Yoast structured data blocks are found on more keywords and have examples in the block inserter.
* Nothing special, just a few extra attributes.
* Confirm this works as expected. 
Part of https://yoast.atlassian.net/browse/P1-66 and https://yoast.atlassian.net/browse/P1-65
> P1-65 Add example and extra keywords to structured data blocks

- admin/class-admin-asset-manager.php
- js/src/components/PluginIcon.js
- js/src/initializers/edit.js
* Adds the Yoast logo to the Yoast block categories.
* Adds the Yoast logo to the Yoast block categories.
* Reused the plugin icon and made it useful for multiple usecases.
* Notice the Yoast logo in the block inserter next to our block categories.
Fixes https://yoast.atlassian.net/browse/P1-63
> P1-63 Add logo to our block categories

- lib/migrations/adapter.php
No need for a closure when there is a PHP native function which does exactly the same.
Ref: https://www.php.net/manual/en/function.array-column.php
POC: http://sandbox.onlinephpfunctions.com/code/b3e5374a8e4340dac407e85498c30eb2c1a9c8ae
* _N/A_
> QA: no need for a closure when there is a native PHP function

- js/src/initializers/edit.js
* Removes the color from the yoast icon next to block categories.
* Removes the color from the yoast icon next to block categories.
* Confirm the color has in fact been removed.
> Remove the color of the block category icon.

- src/routes/indexables-head-route.php
- tests/routes/indexables-head-route-test.php
WordPress 5.5 introduces a new notice when the `permission_callback` is not set.
`register_rest_route was called incorrectly. The REST API route definition for yoast/v1/get_head is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.)`
* n/a
* n/a
* Make sure the `get_head` rest endpoint still works as expected.
Fixes P2-152
> Set permissions callback on get_head rest registration

- inc/sitemaps/class-sitemaps.php
This reverts commit c2a9a9d43e7bb806416199d478d82b8f38965000.
* For some reason, only a part of https://github.com/Yoast/wordpress-seo/pull/15549/ was reverted, which means https://yoast.atlassian.net/browse/QAK-2043 was not fixed at all. This PR reverts the part of https://github.com/Yoast/wordpress-seo/pull/15549/ which was not reverted before 
* Fixes a bug where a fatal error would occur in sitemaps on sites where the home URL and site URL were different. Because the cause of this was a missing style sheet, the content of the sitemaps was still there, which means Google and other search engines could still reach the sitemaps and no SEO harm was done.
*
* See Jannes' comment …
> Revert "Changed readfile to get_contents from wp_filesystem"

- inc/class-wpseo-utils.php
The cognitive complexity of a double negative is high, while there is no need for it. Casting to a boolean has the same effect.
* _N/A_
> QA: don't use double negatives

- grunt/custom/convert-pot-to-wp.js
* We want to copy the translator comments from JS.
* N/A - Improved the script to copy the translator comments as well.
*
* Run `grunt build:i18n`
* Open the file `languages/wordpress-seojs.php`
* For strings containing `%s` there is no translator comment
* Checkout this branch do the build step
* Now the file should contain translator comments
Fixes https://yoast.atlassian.net/browse/QAK-2083
> Make sure to copy the translator comments

- js/src/post-edit.js
* Fixes a bug where wpseoShortcodePluginL10n was not defined. See: https://wordpress.org/support/topic/conflict-with-yoast-seo-14-6-1/
* Fixes a bug where wpseoShortcodePluginL10n was not defined.
* Add the global back for backwards compatibility
* Try to reproduce the bug in the forums and notice it's fixed.
> Fixes a bug where wpseoShortcodePluginL10n was not defined.

- js/src/indexation.js
* When the indexables process is run on the tools page and fails for some reason, the process cannot be started again without a page reload. This PR fixes this by resetting a flag when an error is encountered.
* Fixes a bug where the indexable indexation process could not be started again on the tools page if it failed without a page reload.
* 
**Note**: It is best to test this in Premium, where we also have an indexation process for internal linking suggestions. The testing instructions below are for Premium.
* Checkout `release/14.7`.
* Let the indexable indexation process deliberately fail.
* For example by throwing an exception in the `index` method of the …
> Reset the indexation process when it fails so that it can be start again.

- src/initializers/disable-core-sitemaps.php
- tests/initializers/disable-core-sitemaps-test.php
* This PR is [a copy of this one](https://github.com/Yoast/wordpress-seo/pull/15718), but based on the release branch, rather than `trunk`.
* I did replace the code with the appropriate `do_safe_redirect` method on the `Redirect_Helper`, which does the same.
* Fixes a (not yet released) bug where visiting the WordPress users sitemap would trigger a 404 error, instead of redirecting to its respective Yoast SEO sitemap.
* https://developer.wordpress.org/reference/functions/wp_safe_redirect calls for an `exit()` after a `wp_safe_redirect()`.
* See that visiting `domain/wp-sitemap-users-1.xml` successfully redirects instead of generating a 404.
Fixes #
> Exit after a successful safe redirect from the core sitemaps

- wp-seo-main.php
* When a user has used Premium and goes back to Free, we want to have tracking disabled by default.
* n/a
* Only set this if we are not in premium
* Only set this on plugin activation
Scenario 1:
* Activate Premium
* See tracking being enabled
* You can check this by looking at the `wpseo` option in the `wp_options` table in your DB. The serialized object should have a `tracking` parameter which is set to 1 / `true`.
* Activate Free
* See tracking being disabled
Scenario 2:
* Activate Free
* Go to the configuration wizard - enable tracking
* Deactivate Free
* Activate Free
* See tracking being disabled
Fixes P2-166
> If we are not premium; disable tracking on plugin activation

- admin/tracking/class-tracking-settings-data.php
- inc/options/class-wpseo-option-wpseo.php
- src/actions/semrush/semrush-options-action.php
- src/routes/semrush-route.php
- tests/routes/semrush-route-test.php
* The SEMrush modal has a country selector to choose the country database against which the request for related keyphrases must be performed. We want to store in an option the last country code that's been used, so we need a REST API endpoint to access with a POST request.
* Added a `/semrush/country_code` REST endpoint to store the last country database queried by the SEMrush integration.
* Multisite is not supported at the moment since the `semrush_tokens` options do not currently support it (to be discussed).
* The endpoint has currently been created only to store the value via POST: querying via GET hasn't been implemented since the country selector will probably read the value when the Edit page is accessed to avoid problems …
> P3-81 Add REST endpoint to set country code option for SEMrush

- grunt/config/eslint.js
- js/src/components/fills/MetaboxFill.js
- js/src/components/fills/SidebarFill.js
*
* Fixes schema tab trying to be rendered on term pages.
*
* Visit an edit term page. There is no longer a JS error and the metabox is usable again.
* Quick smoke test on a post edit page to see if the schema tab is still there and "usable" (current state is just seeing changed values reflected in the hidden input fields).
Fixes https://yoast.atlassian.net/browse/P1-81
> P1-81 Fix schema tab error on term pages

- js/src/components/RelatedKeyphrasesModal.js
- js/src/components/contentAnalysis/KeywordInput.js
- js/src/containers/SEMrush.js
- js/src/redux/actions/SEMrushModal.js
- js/src/redux/reducers/SEMrushModal.js
- js/src/redux/reducers/SEMrushRequest.js
- js/src/redux/selectors/SEMrushModal.js
- js/src/redux/selectors/SEMrushRequest.js
* 
* Displays an error message when attempting to open the SEMrush modal with an empty keyphrase.
- adds a new `displayNoKeyphraseMessage` property to the redux state
- adjusts actions, reducers, selectors accordingly
- this PR needs to be tested together with the related JS repo PR https://github.com/Yoast/javascript/pull/805
- switch the JS repo to the branch `P3-63-error-message-empty-keyphrase`
- of course, switch Yoast SEO to this branch `P3-63-error-message-empty-keyphrase`
- run `yarn link-monorepo` and then build the plugin
- edit a post
- test both in the metabox and in the sidebar 
- empty the Focus keyphrase field
- click "Get related keyphrases"
- observe the SEMrush …
> P3-63 Add error message when attempting to open the SEMrush modal with an empty keyphrase

- js/src/components/contentAnalysis/KeywordInput.js
* Needed for https://github.com/Yoast/wordpress-seo-premium/pull/2921
* [non-user-facing] Puts different slot names after the KeywordInput in the metabox and the sidebar.
*
*
Fixes #
> Differentiate between sidebar and metabox for language feedback

- js/src/ui/publishBox.js
* Fixes a bug where the SEO and Readability scores were no longer shown in the publishbox.
* Fixes a bug where the SEO and Readability scores were no longer shown in the publishbox.
* Nothing specific.
* Notice the publishbox scores are back in the classic editor.
Fixes https://github.com/Yoast/wordpress-seo/issues/15711
> Fixes scores in classic editor publish box.

- src/config/migrations/20200728095334_AddIndexesForProminentWordsOnIndexables.php
* We want to be able to quickly identify how many indexables need to be indexed for prominent words / internal linking suggestions.
* Adds indexes to the indexables table in the database, such that it is quicker and more efficient to retrieve the number of unindexed indexables for prominent words.
* Decided to add this in Free on advice from Herre. Since it is best to keep all migrations for one table in one plugin.
* Visit a Yoast page in the admin of your WordPress site to trigger the database migrations.
* Check the structure of the `wp_yoast_indexable` table in your database. 
* It should have a new index called `prominent_words`.
* The index should be on four columns: 
* …
> Added migration to add indexes for prominent words to the indexables table.

- src/integrations/watchers/indexable-permalink-watcher.php
* We use transients as cache to prevent count queries all the time. But when everything is calculated and permalinks are reset the transients should removed as well.
* N/A - Not released yet. Fixes a bug where the transients keeps state also when that state has changed
*
* On the release branch
* Have all indexables calculated
* Change the permalink structure (WordPress permalink settings) or reset the category base (under search appearence)
* Make sure that the amount of indexables affected by the change is bigger than 25. Since 25 indexables are re-indexed on every request and you would not get the notice either way.
* Visit the tools page: no notice is given and there is no …
> Remove transients when permalinks are reset

- inc/options/class-wpseo-option-ms.php
* Adds the tracking option to the network overrides so it can be disabled from the network tab.
* Fixes disabling tracking from the network tab not working.
* Go to the network SEO settings of a multisite WordPress.
* E.g. _Yoast_ > _General_ > _Features_ tab off the network admin.
* Usage tracking should be on allow control by default.
* Disable tracking.
* Refresh the page, it should stay disabled.
* Go to the SEO settings of a specific site.
* The toggle should be disabled with a notice that it's been disabled in the network.
Fixes https://yoast.atlassian.net/browse/QAK-2127
> Add the tracking option to the network overrides

- src/config/migrations/20200728095334_AddIndexesForProminentWordsOnIndexables.php
*
* Fixes a (not yet released) bug where a specific database migration would be done only for premium, and not free.
* I moved the migration from premium too free, but forgot to change the `plugin` parameter from `premium` to `free`.
* See the (adapted) test instructions of the original PR: #15745
Fixes #
> Migration for indexes on prominent words version columns should be in free.

- js/src/containers/RelatedKeyphrasesModal.js
* Re-adds a missing method to the RelatedKeyphrases container.
* Re-adds a missing method to the RelatedKeyphrases container.
*
* Check out and build the `feature/semrush` branch.
* Edit a post, open console and notice the following error:
```
Warning: Failed prop type: The prop `onOpenWithNoKeyphrase` is marked as required in `RelatedKeyphrasesModal`, but its value is `undefined`.
in RelatedKeyphrasesModal (created by WithDispatch(RelatedKeyphrasesModal))
in WithDispatch(RelatedKeyphrasesModal)
in Unknown (created by WithSelect(WithDispatch(RelatedKeyphrasesModal)))
in WithSelect(WithDispatch(RelatedKeyphrasesModal)) (created by Context.Consumer)
in div (created by …
```
> Add missing method to RelatedKeyphrases container

- js/src/ui/publishBox.js
* The Readability score link should navigate to the correct section instead of throwing an error.
* Fixes a bug where clicking the readability score link in the classic editor would trigger an error.
* The readability section was moved to a separate tab some time ago. Make sure that the tab is active before navigating towards the readability section.
* Click on the readability score link (see issue if you have no clue)
* Click it
* See that the page "scrolls" to the correct section in the metabox
Fixes P1-98
> P1-98 Readability score link in the publish box triggers an error

- css/src/metabox.css
* We want to display active tabs in black.
* Change the schema-tab icon based on whether the tab is active.
* I tried used the `fill` CSS property, this does not seem to have any effect on the icon (probably because it is set as `background-image`).
* I tried to inline the image directly in the metabox definition. This removes the icon (probably because we espace raw HTMl).
* I tried to set the image as `content` on the `::before` property. This removes the possibility to resize the image.
In the end, I decided to stick with this ugly, but working, solution.
* Test with JS PR
* Open the metabox
* Go to the schema tab
* See that the color of the icon changes
Fixes P1-99
> Change the background-image when the schema-tab is selected

- src/integrations/admin/indexation-integration.php
- src/presenters/admin/indexation-warning-presenter.php
- tests/integrations/admin/indexation-integration-test.php
- tests/presenters/admin/indexation-warning-presenter-test.php
* When you clicked on "Hide this notice" for the indexable indexation, it only worked if you were on the tools page.
* Fixes a bug where the indexable indexation warning would not be hidden if you were on a page other than the Tools page.
* We changed the `Hide this notice` button into a link on all pages other than the Tools page. The indexation integration now checks whether there is a `yoast_seo_hide` query parameter in the URL, and if so, it hides the notification.
* Reset the indexables in the Test Helper.
* Go to the Yoast dashboard.
* Hoover over "Hide this notice", and see it is a URL.
* Click "Hide this notice", and see the notice disappear.
* Reset the indexables in the …
> Hide notice from other pages than the tools page

- .travis.yml
- readme.txt
- wp-seo.php
* On August 11, WordPress 5.5 will be released. Because we always support the 2 latest versions, the minimum supported version needs to be updated to 5.4.
* Sets minimum WP version to 5.4
*I've remove 'tested up to' from the readme because it's already in the plugin file, and the plugin file takes precedence. See https://core.trac.wordpress.org/ticket/46938
*
Fixes #
> Set minimum WP version to 5.4

- src/presenters/admin/indexation-permalink-warning-presenter.php
- src/presenters/admin/indexation-warning-presenter.php
* This PR is a follow-up to https://github.com/Yoast/wordpress-seo/pull/15776. There, we only fixed the `indexation-warning-presenter`, while we should have fixed the `indexation-permalink-warning-presenter` as well.
* Fixes a bug where the indexable permalink warning would not be hidden if you were on a page other than the Tools page.
*
_Test the Category URLs setting_
* Reset the indexables in the Test Helper.
* Run the indexable indexation.
* Go to Search appearance --> Taxonomies and click the Category URLs toggle.
* The warning should appear. 
* Hoover over "Hide this notice", and see it is a URL.
* Click "Hide this notice", and see the notice disappear.
_Test the Permalinks …
> P2-205 Hide the permalink warning also when you're not on the tools page

- admin/formatter/class-metabox-formatter.php
- js/src/initializers/edit.js
- js/src/redux/selectors/twitterEditor.js
* [This PR on premium](https://github.com/Yoast/wordpress-seo-premium/pull/2774) contains only changes in Free code. This gives some problems. Therefore, the code should also be merged into free. This PR does exactly that ^.
* Passes the twitterCardType to the JavaScript and loads it in the store.
*
1. Change the Default Twitter card type in the settings (see original issue)
1. See that this changes the Twitter Preview in the Social React tab.
> Load TwitterCardType in store and update the selector

- js/src/components/RelatedKeyphrasesModal.js
* The SEMrush modal contains some components which need a parent container with a `yoast` class.
* Add `yoast` class to SEMrush modal
*
* The PR can't be tested (one can just check that the class is present) since the components affected will be merged later or are visible just in the Premium plugin. The PR will be directly merged.
Fixes P3-98
> P3-98 Add `yoast` class to SEMrush modal

- js/tests/setupTests.js
*
* Fixes a bug where the `yoast-components` text domain was missing in the JS tests.
*
* You should not longer get errors about the `yoast-components` text-domain when running the JS tests (`yarn test`).
* The error would look like:
```
console.error node_modules/memize/index.js:74
Jed localization error: 
Error: Domain `yoast-components` was not found.
```
Fixes #
> Add missing text domain in JS tests

- grunt/custom/convert-pot-to-wp.js
* We can't push to WordPress trunk because of `,` without value.
* N/A - Deployment code only.
*
* Run `grunt build:i18n` and verify that the `.php` files in the languages directory doesn't contain any unexpected values.
Fixes #
> Check if there is a language string before adding translator comment

- js/src/components/SchemaTab.js
* In the Schema tab when you click on `Search Appearance Settings` it opens in the same window. Users can loose their unsaved content/changes. It is better to open it in a new window
* Makes sure the Search Appearance settings are opened in a new tab
*
* Go to the schema tab
* Click the link
* See that it's opened in a new tab
Fixes #
> [QAK-2135] Open Search Appearance settings in a new tab

- Gruntfile.js
* We want to commit the svn assets as well.
* N/A - This is for deployment and will include the svn-assets directory.
*
* This can only be tested when releasing the plugin because the value is used for the deploy:master, see https://github.com/Yoast/plugin-grunt-tasks/blob/develop/config/wp_deploy.js#L23
* After deploying the images should be updated.
Fixes #
> Sets the assets directory for svn

- admin/views/tool-file-editor.php
* To add checks if the path to home is writable, so that the robots.txt file can be edited on WordPress.com Business sites
On Business Plan sites hosted on WordPress.com, it is not possible to edit the robots.txt file in Tools > File Editor.
When I access this tool, I see the message "If you had a robots.txt file and it was editable, you could edit it from here."
This is due to the fact that `get_home_path()` points to a non-writable folder in WordPress.com where the core WordPress files are located.
`/wordpress/core/5.4.2/`
This PR adds checks on whether `get_home_path()` is writable.  If so, it sticks to `get_home_path()`, if not, it goes to `$_SERVER['DOCUMENT_ROOT']`.
#15675 
* Fixes a bug where the `robots.txt` and …
> Adds writable check to robots.txt file editor to comply with WordPress.com

- admin/views/licenses.php
* 
* Make the titles of the addon upsell cards on the Premium page translatable.
*
* As long as there are no translations, you'll keep seeing the English string. I visited the Premium page to double-check I didn't completely break the title.
Fixes #
> Make addon display titles translatable

- admin/views/tool-file-editor.php
* Follow-up on community patch https://github.com/Yoast/wordpress-seo/pull/15697 I reviewed.
* Fixes a bug where `DOCUMENT_ROOT` could be used even when empty.
* Fixes a bug where `DIRECTORY_SEPARATOR` would not be used when it should.
* The PHP global `DOCUMENT_ROOT` can be empty. This is now checked.
* The `/` can be `\` on Windows, using the constant.
* Go to the SEO -> Tools -> File editor page.
* Verify you can view/edit robots.txt and .htaccess (if on apache) as usual.
* To fake the `is_writable` check to return false, edit the code to:
* `if ( ! false && ! empty( $_SERVER['DOCUMENT_ROOT'] ) ) {` -- this will make it use the `DOCUMENT_ROOT`.
* Verify viewing/editing again.
* …
> P1-121 Add safety check to the tool file editor

- js/src/components/RelatedKeyphrasesModalContent.js
After decision from product, the request-failed design was updated (from - to)
* Updates request-failed content.
* 
* Ensure you have a valid SEMrush token present in your database before testing (see https://github.com/Yoast/wordpress-seo/pull/15607 for more information on how to do this).
* Ensure you've run `composer install`, `yarn` and `grunt build`.
* Navigate to a new or pre-existing post in the admin.
* Add a keyphrase (suggestion: `yoast`) and click the 'Get related keyphrases' button.
* See that the modal pops up and contains the upsell message, country selector with button and debug information.
* Select a country code, hit the 'Change Country' button.
* See that the …
> Show Country Selector with request failed message

- js/src/components/modals/KeyphrasesTable.js
Correct styling: 
* Fixes the button styling in the KeyphrasesTable.
* As discussed with Rolf, a parent `yoast` class was missing and the `td` containing the buttons needed the `yoast-table--nobreak` class.
**Testing on Free:**
- Switch to this branch and build
- Edit a post, add a keyphrase and open the SEMrush modal
- Check there are no errors
- Check the column with the buttons is _not_ displayed
**Testing on Premium**
* on Premium, make a new branch, branching out from `feature/semrush` and switch to that branch
* Add the Free repo as additional remote on the Premium repo, if you didn't add it already
* Run `git fetch --all` and `git pull free P3-106-fix-premium-button-styling` …
> Fix premium button styling in keyphrases table

- src/helpers/post-helper.php
- src/surfaces/meta-surface.php
Should be merged and rebased to trunk, after https://github.com/Yoast/wordpress-seo/pull/15609 has been merged.
*
* Improves SQL performance by not performing unnecessary update queries when updating a post's public status.
* A bug that was present before is still there. https://yoast.atlassian.net/jira/software/c/projects/P2/issues/P2-227
* Create a new post, add a new attachment (*so upload a new attachment*) and publish it.
* Search for the attachment in the `wp_yoast_indexables` table and make sure `has_public_posts` is set to `NULL`.
* Now set the post status to private and update it.
* Search for the attachment in the `wp_yoast_indexables` table and make sure …
> Improved sql performance

- js/src/components/modals/KeyphrasesTable.js
- src/actions/semrush/semrush-phrases-action.php
* Refactors the API request slightly so we don't request unnecessary data.
* Refactors request to only get the three required columns: Keyphrase, Volume and Trend.
*
* Ensure you have a valid SEMrush token present in your database before testing (see https://github.com/Yoast/wordpress-seo/pull/15607 for more information on how to do this).
* Navigate to a new or existing post
* Fill in a keyphrase and click 'Get related keyphrases'.
* Select the desired country and hit 'Change Country'
* Ensure you get a proper response back and all the data is displayed as it should.
Fixes #
> Refactored the API call slightly to return less columns

- src/helpers/language-helper.php
* Let the Free users see an upsell notification that promotes Premium wordform functionality.
* Activate upsell notification for Polish users.
*
* Set the languages of your website to Polish.
* Check that you are seeing a morphology upsell. (See [this PR](https://github.com/Yoast/wordpress-seo/pull/15322) for what the upsell looks like.)
Fixes https://yoast.atlassian.net/browse/LIN-554
> Add Polish to the list of morphology-supported languages

- js/src/components/contentAnalysis/KeywordInput.js
* Adds centralized keyphrase validation to the `KeywordInput` component which utilizes the unordered list introduced in P3-90.
* Adds centralized keyphrase validation to the `KeywordInput` component.
*
* Check out this PR, make sure you have the `feature/semrush` branch checked out for the Javascript monorepo and have it linked.
* Make sure you've run `composer install`, `yarn` and `grunt build`.
* Edit a post or create a new one
* Hit the 'Get related keyphrases' button without filling in a keyphrase. Note the error pops up above the input field. No modal pops up.
* Start typing a keyphrase and note that the error disappears.
* Hit the 'Get related keyphrases' button again. Note …
> Added validation for the keyphrase input

- src/generators/schema-generator.php
- tests/unit/generators/schema-generator-test.php
* In https://yoast.atlassian.net/browse/P1-110 I noticed adding the same page type to what is added already added in SEO Woo would result into duplicate output. Instead of fixing that in the filter everywhere this adds a check after the filter.
* Adds validation for schema type array: unique values only and single value inside an array removes the array wrapping.
* When the type is an array:
- Ensure the values are unique.
- Only 1 value? Use that value without the array wrapping.
* What do you think of the changelog entry? Too technical? Suggestion welcome 😉 
* Go to the frontend of a post (default post, create a new one if you changed the schema settings).
* Check the schema …
> P1-123 Add schema type validation

- js/src/components/contentAnalysis/KeywordInput.js
* The `KeywordInput` component from `yoast-components` has been recently refactored (see: https://github.com/Yoast/javascript/pull/814) to be a stateless component accepting error messages as props, instead of performing cheks internally (namely, the check for a comma in the keyphrase).
We are adding back the check for a comma (issue P3-101), and refactor the check for maximum length of the keyphrase to use the new component API (issue P3-95)
* Refactor checks for comma in keyphrase and max keyphrase length to adapt them to the new implementation of component
* 
* make sure you are on the `feature/semrush` branch of monorepo
* build as usual
* start writing a new post, see there are …
> P3-101 - P3-95 Refactor checks for comma in keyphrase and max keyphrase length

- js/src/components/RelatedKeyphrasesModal.js
- js/src/components/RelatedKeyphrasesModalContent.js
* Adds the maximum related keyphrases warning to the modal, if applicable.
* Only shows the 'upsell to Premium' message, if the user is not using Premium.
* Adds the maximum related keyphrases warning to the modal (if applicable) and only shows the 'upsell to Premium' message if the user is not using Premium.
* I've added the logic for displaying the maximum related keyphrases warning to Free, despite it being something we only show in Premium. The thought behind this is that we only have the one modal and based on the existence of related keyphrases, we can then show/hide the message. By default, `relatedKeyphrases` is an empty array in Free and thus will never trigger the message. …
> Show maximum related keyphrase warning

- admin/class-admin-init.php
- admin/class-yoast-notification-center.php
- release-info.json
* We want to show notifications in WordPress after a user has manually or automatically updated Yoast SEO (Premium) or one of the add-ons. This should happen for all users, and not just the ones that have automatic updates enabled. The reason for that is that not all of our users are subscribed to our newsletter or follow us on social media. This way they can still find some more detailed information on the version they’ve just upgraded to.
* Adds an update notification for major and minor releases.
* The last version in which the user has dismissed the notification is stored in the usual user option. Normally this is set to `seen` in the database, but the functions have a parameter for that which was unused. The Notification …
> P3 84 update notifications

- admin/formatter/class-metabox-formatter.php
- admin/metabox/class-metabox.php
- admin/views/class-yoast-feature-toggles.php
- inc/class-wpseo-meta.php
- js/src/components/SchemaTab.js
- js/src/components/fills/MetaboxFill.js
- js/src/components/fills/SidebarFill.js
- js/src/containers/MetaboxFill.js
- js/src/containers/SchemaTab.js
- js/src/redux/reducers/preferences.js
- tests/unit/admin/metabox/metabox-test.php
* We do not want every user to be presented with the schema settings of an indexable. Now coupled to the advanced section and adapted the help text for that option.
* Apply the advanced section's capability and option checks to the schema settings.
* Fixes a bug where a user could be presented with a link without having access to that page.
* The MetaboxFill container had some specific props (compared to the SidebarFill). I cleaned that up.
* I added the variables to the preferences reducer. This should probably have its own (schema) reducer in the end. But I know we have a cleanup coming and this is the quick version for the release branch.
* Go to SEO -> General -> Features and …
> P1-119 Apply advanced section capability and option to the schema tab

- src/generators/breadcrumbs-generator.php
- src/generators/schema/breadcrumb.php
- src/helpers/pagination-helper.php
- tests/unit/generators/breadcrumbs-generator-test.php
- tests/unit/generators/schema/breadcrumb-test.php
- tests/unit/helpers/pagination-helper-test.php
* Page numbers in the breadcrumbs are useful, as they let users know where they are on the site.
* Fixes a bug where the page number was not shown in the breadcrumb for paginated series.
* Because date archives don't have an indexable permalink, only for this archive type we constructed the URL's from scratch. Since a "Page ..." breadcrumb was added, these URL's are now needed to turn the breadcrumb before the Page breadcrumb into a URL.
* The `is_paged` method doesn't detect pagination in the case of a paginated post. Therefore, we now also look at the `number_of_pages` in the indexables table. We do this for the last indexable in the `$indexables` array, because that is the indexable of the current page (the first indexable in …
> Fix breadcrumb page numbers in paginated series

- js/src/components/SchemaSettings.js
* In order to alert users to what their Search Appearance Schema setting will do upon saving, we show an alert. We currently show this onBlur of the setting's input field. Sometimes users click the save button immediately after selecting an option, and thus the "onBlur" event coincides with saving, and thus the alert is too late. We now fix this by decoupling saving and showing the alert.
* Fixes unreleased suboptimal user experience whereby a cautionary alert (that should be shown before saving schema settings) could be shown on the exact moment a user clicked save.
* Because of a11y concerns, developers should not introduce [context changes](https://www.w3.org/TR/WCAG21/#dfn-change-of-context) in functions listening to onInput …
> Show SchemaSettings change alert before onBlur

- lib/orm.php
* This was a task in the `WPSEO CS Cleanup` sheet, which aims at improving coding standards in our code base.
* Removes prefixed underscores from protected method names in the ORM.
*
* The indexables should still work as before.
Fixes #
> Remove underscore prefixes from method names

- admin/formatter/class-term-metabox-formatter.php
- admin/metabox/class-metabox.php
*
* Disables the SEMrush integration on the edit terms and edit attachment pages.
* Uses the existing `semrushIntegrationActive` value and sets it to `0` to disable SEMrush. I think this is the simplest way to do it. Do let me know if a separate value is preferred.
- make sure the SEMrush integration is enabled under SEO > General > Integrations
- edit a category
- observe there's no "Get related keyphrases" button in the metabox and there are no errors
- edit a tag
- observe there's no "Get related keyphrases" button in the metabox and there are no errors
- install and activate a plugin that adds custom taxonomies e.g.:
- activate the Yoast Test Helper plugin (it should already be …
> P3-103 disable SEMrush on terms edit pages and edit attachment page

- src/models/indexable.php
* Port numbers can be part of a URL and should therefore be taken into account when building permalinks
* Fixes missing port numbers in the indexables (when applicable)
*
1. Run a WordPress site on a server that uses a different port than 80 or 443
1. Install Yoast SEO without this patch
1. Visit a post and check the source of the page. See that the canonical metadata does not contain the port number.
1. Install this patch and reset the indexables
1. Re-visit the post and see the port included in the canonical URL
Fixes https://github.com/Yoast/wordpress-seo/issues/15397
> Add port to indeaxble permalink when available

- js/src/analysis/PostDataCollector.js
* Fixes a bug where the slug would not be shown in the snippet editor.
* Fixes a bug where the slug would not be shown in the snippet editor.
*
* Refresh the editor page and make sure the slug is filled in in the snippet editor.
* Update the slug through the snippet editor and see that the slug is updated in the document settings.
* Update the slug through the document settings and see that the slug is updated in the snippet editor.
* Repeat these steps in the classic editor.
Fixes #P2-250
> Initialize slug from the store when in block editor

- js/src/components/RelatedKeyphrasesModalContent.js
- js/src/components/modals/SEMrushCountrySelector.js
* In this PR we want to fire a request when the SEMrush modal is first opened, so the user immediately gets SEMrush related keyphrases.
* When the modal is first opened and rendered, `relatedKeyphrasesRequest()` is called which fetches data from semrush.
* I have chosen to call `relatedKeyphrasesRequest()` within the `componentDidMount()` function since this was the safest place to call it since it only triggers when everything has rendered correctly. This allows for a clean SEMrush request which can be handled by the correctly rendered components.
* Checkout this branch and build
* Make sure you have a (non expired) SEMrush token. If not, run the steps here #15607 
* Go to a post
* …
> P3 109 send request on open modal

- admin/class-admin-asset-manager.php
* Adds `wp-api-fetch` to the classic-editor asset loading configuration.
* Adds `wp-api-fetch` to the classic-editor asset loading configuration.
*
* Checkout this branch and build it.
* Ensure you have the Classic Editor plugin installed and activated.
* Ensure you have a valid SEMrush token.
* Create a new post (or edit an existing one).
* Add a keyphrase and hit the 'Get related keyphrases' button. A request should automatically be sent and succeed.
* Alter the database from the dropdown and click 'Change Country'
* A new request should be successfully sent.
* Check the console and ensure there are no errors.
[P3-111]
> P3-111 Adds wp-api-fetch to the classic-editor asset loading configuration

- admin/class-license-page-manager.php
- inc/class-upgrade.php
- inc/options/class-wpseo-option-wpseo.php
* Performance optimization: move the `wpseo_license_server_version` option to the options framework. Prevents regular DB queries.
Not sure how to test this... @herregroen / @andizer do you know?
> Move license_server_version to Options framework

- admin/class-meta-columns.php
- src/repositories/indexable-repository.php
- tests/unit/admin/meta-columns-test.php
* We don't want to do any queries that result in invalid SQL.
* Fixes an error that occurred when viewing the overview of posts, pages or custom post types while there were no entries.
* See https://yoast.atlassian.net/browse/P2-272 for the original steps to reproduce.
* This issue should also occur on the overview of any custom post types that has no posts.
Fixes https://yoast.atlassian.net/browse/P2-272
> [P2-272] Don't do queries when there are no post IDs

- config/grunt/task-config/webpack.js
* Using the `<%= %>` variable notation makes sure the variable is read on run-time instead of initialization. This prevents the problem of not having the correct version after doing a version bump in the same grunt-sequence (alias progression).
* N/A
*
* Use the `create RC`-flow
* Bump the RC version
* See the JavaScript and CSS files having the correct (bumped) version in their filename after they have been build.
Fixes P2-256
> WebPack RC build version fix - P2-256

- .github/SECURITY.md
Adding the security policy to the repo to let security researchers know about our security bug bounty program. As advised [here](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) and agreed upon in the security meetings. I added the file to the `.github` dir to keep the root as clean as possible.
This PR is not related to the plugins' code or workings, hence no test instructions are provided. 
Awaiting review from security team leads.
> Add SECURITY.md to the repository

- js/src/components/RelatedKeyphrasesModal.js
* Changes the SEMrush modal to the custom Yoast modal instead of the default Gutenberg one.
* Changes the SEMrush modal to the custom Yoast modal instead of the default Gutenberg one.
*
* Checkout this branch and build it.
* Create a new (or open an existing) post
* Enter a keyphrase and hit the 'Get related keyphrases' button.
* Determine that the modal looks and works the same as it did previously.
Fixes #
> Changes the SEMrush modal to the custom Yoast modal one

- js/src/initializers/editor-store.js
* #15832 introduced a regression about the retrieval of the country code from the database.
When user edits a post and opens the SEMrush modal, the country database is set on `us` (the default value) regardless of the value stored in the database.
Changing the value in the country selector and sending a new request changes the value correctly in the database, but if you reload the page the selector will be reset to `us` again. 
Also, opening the modal for the first time sends a request immediately, so the value in the database is set to `us` after the modal has been opened.
* Fix problem with country code not initialized with value from database
* 
* Build as usual
* Edit a post and …
> P3-118 Fix problem with country code not initialized with value from database

- phpcs.xml.dist
* Apply an earlier CS fix for the sitemaps resulted in the need for a patch release because using `WP_Filesystem` broke websites. Therefore the decision (during the architecture meeting) has been made to disable the sniffs that are related to the `WP_Filesystem`. Just to prevent more broken websites.
* See https://github.com/Yoast/wordpress-seo/pull/15713
* N/A - Disables the sniffs.
*
* I hope I have disabled the sniffs the right way. 
Fixes #
> Exclude the file_system specific sniffs

- src/actions/indexation/indexable-post-type-archive-indexation-action.php
More information is in issue: #15082 Basically, there are shown errors after updating plugins.
Due to the code documentation `find_array` method can returns `array|false`, but here we putting result of this method directly to `array_map`. This code is the way how to fix this warnings.
```
print_r(false ?: []); // array()
print_r([5,10] ?: []); // array(5, 10)
print_r([] ?: []); / array()
```
* Fixes a warning that occurs when a query is unsuccessful while indexing post type archives. 
Should be compatible with PHP >= 5.4
Fixes #15082
> Issue #15082 - Expected parameter 2 to be an array, bool given

- js/src/components/RelatedKeyphrasesModal.js
- js/src/components/contentAnalysis/KeywordInput.js
* We want to allow the user to open the SEMrush modal only if the focus keyphrase is not completely blank.
* Show error message when trying to get related keyphrases for a blank focus keyword
* The original issue asked to prevent to fire the content analysis for blank keyphrase too, but it's a bit harder and out of the scope of the SEMrush integration. It will be the focus of another issue.
* The commit also fixes two warnings about import that could be shortened.
* Build as usual
* Edit a new or an existing post
* insert a focus keyphrase of only spaces, or tabs
* Click the "Get related keyphrases" button
* See the error message "Please enter a focus keyphrase first to get related …
> Check trimmed keyphrase before opening the modal

- js/src/components/AdvancedSettings.js
- js/src/components/modals/PostSettingsModal.js
* The modal currently closes after selecting an image in or closing the media library. This gives a very bad user experience since the user has to open the modal again. This PR prevents the modal from closing when the media library opens.
* Prevents the Metabox Modal from closing when the media library opens.
* I check whether the media library opens by looking for the `blur` eventType and whether the related target (the media library) has a `className` of `media-modal wp-core-ui`. I think this covers all our current cases in the modal and might even cover future cases where the media library is needed.
* Note: the media library dialog does not have an ID. Therefore, I have decided to match based on the `className`.
This PR can …
> P1-134 Prevent modal from closing when the media library opens

- js/src/components/SnippetPreviewModal.js
* We want to notify users that the SnippetPreviewModal will be removed in the future.
* Add an info alert to the SnippetPreviewModal that points to the new location.
* Copy has been created by Thijs.
* Open the `SnippetPreviewModal`
* See the Alert.
Fixes P1-136
> Add postSettingsModal actions

- admin/class-gutenberg-compatibility.php
* Gutenberg 8.8.0 was released on August 20, 2020. We only support the latest Gutenberg version.
* Set Gutenberg version to 8.8.0
*
* Have a Gutenberg version < 8.8.0. 
* See a notification to update to 8.8.0.
Fixes #
> Set gutenberg version to 8.8.0

- inc/options/class-wpseo-option-titles.php
- src/helpers/schema/article-helper.php
* See https://github.com/Yoast/wordpress-seo/issues/15865 and https://yoast.atlassian.net/browse/P2-296.
* Makes it possible to change the default Schema Article type for custom post types.
* We already had a filter available to change the default Schema Article type (`wpseo_schema_article_post_types`), but it wasn't called anywhere. Now it is.
* Use the Test Helper to `Enable post types & taxonomies.` See that you have Books and Movies available as custom post types.
* In your database, in `wp_options` go to `wpseo_titles`.
* See that `schema-article-type-movie` is set to `None`. (If it isn't, manually change the value so that you can continue testing).
* Add the following filter …
> Call the article helper to determine the Schema article type

- src/context/meta-tags-context.php
*
* Passes the indexable as context to the `wpseo_schema_article_type` filter.
*
* In your theme's `functions.php`, add the following code:
```
add_filter( 'wpseo_schema_article_type', function( $context, $indexable ) {
print_r($indexable); die;
}, 10, 2 );
```
* Open a post on the frontend.
* See that the indexable is printed on your screen (and therefore, is available in the filter).
Fixes https://yoast.atlassian.net/browse/P2-297
> Pass the indexable to the wpseo_schema_article_type filter

- inc/sitemaps/class-sitemaps.php
We want to allow users of the plugin to dynamically add/remove/change links to the individual sitemaps in the sitemaps index.
* Add sitemap_index_links filter
* Naming of the filter: `wpseo_sitemap_index_links`
* Argument to the filter: I chose to pass the entire `$links` array because it solves the most use cases with just one filter.
* Register a handler for the `wpseo_sitemap_index_links`
* Check the value of the passed argument
* Modify and return the array
* Check `sitemap_index.xml` to see if it reflects the changes to the array 
* None
* None besides docblock
Fixes #15796, fixes #14240
> Add wpseo_sitemap_index_links filter

- inc/class-wpseo-utils.php
- js/src/components/AdvancedSettings.js
- js/src/components/fills/MetaboxFill.js
- js/src/components/modals/PostSettingsModal.js
- js/src/containers/AdvancedSettings.js
- js/src/containers/PostSettingsModal.js
- js/src/helpers/fields/AdvancedFields.js
- js/src/redux/actions/advancedSettings.js
- js/src/redux/actions/index.js
- js/src/redux/reducers/advancedSettings.js
- js/src/redux/reducers/editorContext.js
- js/src/redux/reducers/index.js
- js/src/redux/reducers/preferences.js
- js/src/redux/selectors/advancedSettings.js
- js/src/redux/selectors/editorContext.js
- js/src/redux/selectors/index.js
- js/tests/redux/actions/advancedSetings.test.js
- js/tests/redux/reducers/advancedSettings.test.js
* We need Redux to be the source of truth for the Advanced tab, because there will be a period of time where the Advanced Settings are both visible in the metabox and in the modal. It is not yet clear how long this period will be.
* Data source of truth for Advanced Tab is now our Redux store. Persistence still flows via hidden fields.
* NOTE that the select2 fix we have implemented will be undone in a follow-up PR that is coming soon. We will switch to `react-select` soon, but decided to split that out to a new issue to keep the scope small. 
* Test together with sibling PR on javascript: https://github.com/Yoast/javascript/pull/838
* Verify that the Advanced Tabs settings are …
> Route data via Redux for Advanced Tab

- admin/formatter/class-metabox-formatter.php
- config/grunt/task-config/eslint.js
- css/src/modal.css
- js/src/components/SEMrushRelatedKeyphrasesModal.js
- js/src/containers/SEMrushRelatedKeyphrasesModal.js
- js/src/initializers/editor-store.js
- js/src/redux/actions/SEMrushRequest.js
- js/src/redux/reducers/SEMrushRequest.js
- js/src/redux/selectors/SEMrushRequest.js
* When the user is not logged in in SEMrush, instead of the SEMrush modal we want to show a popup where the user can log in or register.
* Adds a link to the SEMrush login/register form in a popup window
* This PR just shows conditionally a link opening a popup to login/register to SEMrush. **It does not** manage the steps after the authorization by SEMrush has been granted.
* The user is considered "logged out" when no token is stored in the DB, or if it's expired and cannot be refreshed. The check is performed "at runtime" on the server and the result is stored in the Redux store (where it could be updated following a successful login — not covered by this PR)
* The "button" to open the popup is actually a `<a>` tag as it …
> Add SEMrush login popup

- src/presentations/indexable-post-type-presentation.php
- src/presentations/indexable-presentation.php
- tests/unit/presentations/indexable-author-archive-presentation/robots-test.php
- tests/unit/presentations/indexable-date-archive-presentation/robots-test.php
- tests/unit/presentations/indexable-post-type-archive-presentation/robots-test.php
- tests/unit/presentations/indexable-post-type-presentation/robots-test.php
- tests/unit/presentations/indexable-presentation/robots-test.php
- tests/unit/presentations/indexable-term-archive-presentation/robots-test.php
* This was missed in https://github.com/Yoast/wordpress-seo/pull/15880
* Fixes a bug where the `archive`, `imageindex` and `snippet` robot values where output when set to no index.
* The removing is done before the filtering, just like the `max-` values. So when filtering, they can be still be forced to appear.
* Removed the `no` part from the keys for `noimageindex`, `noarchive` and `nosnippet` to make it consistent with `noindex` and `nofollow`. There was a mismatch with the robots array before the string filter and after. As the string to array removes the `no` part from the key.
* Fixed the robots string to array part by removing any `:value` parts from the key. E.g. `max-snippet:-1` in the string will convert to `max-snippet …
> Strip extra robot values

- js/src/components/SchemaTab.js
- js/src/components/social/FacebookWrapper.js
- js/src/components/social/TwitterWrapper.js
- js/src/containers/FacebookEditor.js
- js/src/containers/SchemaTab.js
- js/src/containers/TwitterEditor.js
- js/src/helpers/fields/SchemaFields.js
- js/src/redux/actions/index.js
- js/src/redux/actions/schemaTab.js
- js/src/redux/reducers/facebookEditor.js
- js/src/redux/reducers/index.js
- js/src/redux/reducers/schemaTab.js
- js/src/redux/reducers/twitterEditor.js
- js/src/redux/selectors/facebookEditor.js
- js/src/redux/selectors/index.js
- js/src/redux/selectors/schemaTab.js
- js/src/redux/selectors/twitterEditor.js
* Part of the reason why the schema tab does not up-date, is because it is not using Redux for state management.
This PR changes the Schema tab component so that it uses the Redux store.
* Add Redux to the Schema tab component.
* Fix small issue where Twitter and Facebook data was loaded from the store multiple times.
* The data does not actually sync atm. This is an issue with the underlying `MultiSelect` elements. This will be fixed in a separate PR on the monorepo.
* Until the fix for the Select has been merged, this PR can only be tested using the [Redux developer tools](https://github.com/zalmoxisus/redux-devtools-extension).
* Check that the data in the schema tab is …
> Add redux to the Schema-tab.

- src/context/meta-tags-context.php
* Prevent `null` to be part of `@ type` in our schema.
* Fixes a bug where `null` could be part of `@ type` in our schema.
*
* Install Yoast 14.8.1 and follow the steps in https://github.com/Yoast/wordpress-seo/issues/15936
* You will see that `null` is a part of the `@ type` in the schema.
* apply this patch and null will not be output anymore.
Fixes #
> Prevent ATtype of null to end up in our schema

- src/config/migrations/20200617122511_CreateSEOLinksTable.php
* Database errors would show up when trying to add (attachment) URLs to the `yoast_seo_links` table. This happened because the primary key of the table was not set to auto-increment with each entry and the entries themselves did not define a unique ID either.
* Fixes the SEO Links table on new installs not having auto-incrementing IDs.
* Make sure you have a clean install that doesn't have any existing Yoast tables.
* Activate the plugin.
* The SEO Links table should have auto-incrementing IDs.
* Create a post with links in it.
* The links should show up in the SEO Links table.
Fixes `WordPress database error Duplicate entry '0' for key 'PRIMARY' for query INSERT INTO …
> Fix id column options in SEO Links migration

- admin/views/tabs/dashboard/features.php
- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- admin/views/tabs/network/features.php
- config/dependency-injection/services.php
- inc/class-upgrade.php
* Fix CS errors with a newer version of `yoastcs` to eventually be able to upgrade without breaking the development flow.
* Fixes some docs for the future yoastcs version.
*
* Temporarily add the following `composer.json` scripts:
```json
"before-premium-cs": [
"composer require --dev yoast/yoastcs:~2.0.0 --update-with-dependencies --no-suggest --no-interaction  --no-scripts",
"Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin::run"
],
"after-premium-cs": [
"composer require --dev yoast/yoastcs:~0.4.3 --update-with-dependencies --no-suggest --no-interaction --no-scripts",
"@php ./config/composer/scripts/maybe-restore-composer-lock.php",
"composer config-yoastcs"
] …
```
> Fix PHPCS: docs

- inc/wpseo-functions.php
* We want to have `wp_get_environment_type()` available in all the WP versions supported by Yoast SEO, which includes WP 5.4.
* Backfill `wp_get_environment_type()` for WordPress 5.4.
* I opted to put the backfilled function in the `inc/wpseo-functions.php` as it seems the most logical place
* Since the core PHP coding standards are different from the plugin ones, ~I had to disable some PHPCS rules (Short array syntax and Yoda conditions) to keep the original `wp_get_environment_type()` code unchanged. Alternatively we could just update the function code to our standards but I think the first option is preferable.~ I changed the function code to meet the Yoast coding standards.
- …
> P3-127 Backfill wp_get_environment_type for WP 5.4

- js/src/components/modals/PostSettingsModal.js
- js/src/components/social/FacebookWrapper.js
- js/src/components/social/TwitterWrapper.js
- js/src/containers/FacebookEditor.js
- js/src/containers/TwitterEditor.js
* See https://github.com/Yoast/wordpress-seo-premium/pull/2979 for information
* [wordpress-seo-premium] Fixes an unreleased bug where Social Previews would be empty when the post settings modal was opened.
* In the future we should investigate adding a modal location via locationproviders, so that there is no hassle with explicitly passing the props
* Test in premium https://github.com/Yoast/wordpress-seo-premium/pull/2979
* Also test in free, should build without errors.
Fixes P1-158
> Add modal location to social slots

- tests/unit/builders/indexable-social-image-trait-test.php
- tests/unit/generators/schema/organization-test.php
- tests/unit/helpers/site-helper-test.php
- tests/unit/repositories/indexable-repository-test.php
* Add some missing `@covers` tags and fix an incorrect one
* _N/A_. This is a test doc only change and has no effect on functionality.
> Tests: add missing `@covers` and fix an incorrect one

- admin/class-admin-init.php
- admin/class-premium-upsell-admin-block.php
- admin/config-ui/class-configuration-structure.php
- admin/import/plugins/class-abstract-plugin-importer.php
- admin/views/tabs/dashboard/webmaster-tools.php
- inc/class-addon-manager.php
- src/config/migrations/20200617122511_CreateSEOLinksTable.php
- src/context/meta-tags-context.php
- src/repositories/seo-meta-repository.php
- src/values/open-graph/images.php
- tests/integration/doubles/wpseo-capability-manager-double.php
- tests/unit/helpers/language-helper-test.php
- tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
- tests/unit/integrations/xmlrpc-test.php
- tests/unit/repositories/indexable-hierarchy-repository-test.php
Follow up on #15950 and #15951, fixing yet more (mostly) recently introduced violations against the coding standards.
Includes a few fixes which couldn't be pulled until the switch over to YoastCS 2.0.
* _N/A_. This is a code only change and has no effect on functionality.
> CS: more minor fixes

- composer.json
- phpcs.xml.dist
Update the ruleset for YoastCS 2.0, WPCS 2.x and PHPCS 3.x.
Includes:
* Enabling parallel scanning and caching of the scan results between scans.
* Enabling PHPCS for all Yoast code in the repo.
* Adding appropriate configuration for a number of sniffs.
* Making selective allowances for exceptions to the rules for, for instance, deprecated code and tests.
* For the time being - temporarily!! - disabling the `PrefixAllGlobals` and `FileName` rules for the "old" code.
* Adding substantial inline documentation to the ruleset.
Please see the individual commits for full detail.
* _N/A_. This is a PHPCS ruleset only change and has no effect on …
> Build/PHPCS: fix the ruleset to work with YoastCS 2.0

- config/grunt/task-config/webpack.js
- config/webpack/webpack.config.js
* Create an easier way to work with javascript without `YOAST_SEO_DEV_SERVER`.
* Adds a `grunt webpack:watch` task that quickly rebuilds javascript when changing a js file without having to run `grunt build:js` again.
*
* Run `grunt webpack:watch`.
* Make a change to a JS file which you can easily see (like adding a `console.log` to admin-global.js), and save it.
* See that `grunt webpack:watch` almost instantly rebuilds the javascript.
* Reload the browser to see the change you made.
Fixes #
> Added grunt webpack:watch task

- css/src/modal.css
- js/src/components/modals/SEMrushCountrySelector.js
- js/tests/components/SEMrushCountrySelector.test.js
After some issues arose due to refactoring of the css, it was decided that the select2 implementation in the `SEMrushCountrySelector` component should be replaced with a react-select component from the monorepo (see [javascript#851](https://github.com/Yoast/javascript/pull/851) for the adjustments made in the monorepo). 
IMPORTANT: the styling of the `SEMrushCountrySelector` component is not completely correct yet (i.e., the placement of the button next to the Select, it is currently still below the Select). An issue has already been added to the board of Team Frontend. 
* Uses react-select instead of select2 for the SEMrushCountrySelector component.
* 
* Checkout …
> Use SingleSelect

- config/grunt/task-config/eslint.js
- js/src/initializers/term-scraper.js
*
* Fixes a bug where the Yoast replacement variables plugin was not available on edit terms page for usage by other plugins.
* Followed the pattern used on the post scraper, where the YoastReplaceVarPlugin class prototype is made available on the window object for usage by other plugins.
* removed the YoastSEO global usage to make the coding pattern in term scraper consistent with the one in post scraper
* lowered the ESLint maxwarnings limit to 123
- install and activate Yoast SEO trunk, Advanced Custom Fields 5.9.0, and ACF Content Analysis for Yoast SEO 2.7 (cloning and building the develop repo is fine: https://github.com/Yoast/yoast-acf-analysis )
- create an Advanced Custom …
> P3-146 Make the Yoast replace var plugin available on edit terms page

- css/src/modal.css
- js/src/components/modals/SEMrushCountrySelector.js
After the refactoring of select2 to react-select, the css had to be adjusted in order to place the button next to the select. 
* Places the button next to the select in the SEMrushCountrySelector component.
*
* Make pulled `feature/semrush` on the monorepo and you've linked it
* Checkout this branch and build
* Open the related keyphrases modal
* See the button is placed next to the select as shown in the image below
Fixes #
> Use new css to place button next to select in SEMrushCountrySelector

- .travis.yml
- config/yarn/link_monorepo_to_plugin.js
* When creating a PR for a feature branch of the Free plugin, job #1 in Travis should check out the matching feature branch of the javascript monorepo to perform `yarn link-monorepo` with it.
As we can see [in this log](https://travis-ci.org/github/Yoast/wordpress-seo/jobs/721664027)  we expected to see the feature/semrush branch of monorepo checked out, but instead we got (lines 947-948)
```
Already on 'develop'
Checking out develop on the monorepo.
```
thus triggering an error since the plugin feature branch relied on code in the monorepo feature branch that was different from the `develop` branch.
* Make sure that the matching monorepo feature branch is checked out when Travis runs on a pull request based on a feature branch
* …
> P3 142 fix travis monorepo feature branches

- release-info.json
We don't use the modal anymore, so we can't mention it here.
*
* We still mentioned the modal in the notification, but we don't have a modal anymore. That's fixed now.
*
*
Fixes #
> Replace mention of modal

- src/generators/schema-generator.php
- tests/unit/generators/schema-generator-test.php
*
* Restricts Schema output on posts that are password-protected.
* In `schema-generator.php`, I [changed](https://github.com/Yoast/wordpress-seo/pull/16015/commits/979747672f36c5b9b70b45741df6b5ed761ef819) an `isset` to an `array_key_exists`. The aim of this check was/is to evaluate whether a graph piece consists of a single graph piece (in the form of `[ '@type' = 'aa', 'name' = 'bb' ]`), or multiple pieces (in the form of `[ [ '@type' = 'aa', 'name' = 'bb' ], [ '@type' = 'cc, 'name' = 'dd' ] ]`). However, a single graph piece in the form of `[ '@type' = NULL, 'name' = 'bb' ]` would not have been recognized as being a single piece, because `isset` evaluates to false when the `@type` is `NULL`. In the same scenario, …
> Restrict Schema output on password-protected pages

- admin/views/class-yoast-feature-toggle.php
- admin/views/class-yoast-feature-toggles.php
- admin/views/tabs/dashboard/features.php
- js/src/initializers/admin.js
- src/initializers/disable-core-sitemaps.php
- tests/unit/initializers/disable-core-sitemaps-test.php
*
* Disabling the Yoast SEO sitemap feature does not automatically disable WordPress' own sitemap anymore.
* Go to the _Features_ tab on the Yoast SEO admin dashboard.
* Toggle the XML sitemap feature to 'Off'.
* You should see a warning below the XML sitemap feature toggle, with the following text:
```
Disabling Yoast SEO’s XML sitemaps will not disable WordPress’ core sitemaps. In some cases, this may result in SEO errors on your site. These may be reported in Google Search Console and other tools.
```
* Toggle the XML sitemap feature to 'On'.
* The warning should disappear.
* Toggle the XML sitemap feature to 'Off'.
* The warning should appear again. 
* Save the changes you made …
> Use core sitemaps when yoast seo sitemaps are disabled

- src/generators/schema/person.php
- tests/unit/generators/schema/author-test.php
* If a user has a `website` set in their WordPress profile, use it in their `SameAs` array in the Schema output.
* Go into your WordPress profile, add a URL to your `website` field.
* Go to a post you authored, check the schema.
* See the website as part of the `sameAs` for your `author` section.
Fixes PROD-231
> Add website field from a user's WordPress profile SameAs array

- composer.json
- composer.lock
- config/php-scoper/polyfill-intl-idn.inc.php
- src/functions.php
* When creating ZIP for Premium, we encountered a problem since a newer version of guzzlehttp/guzzle is used instead of a older one in Free. The new version relies on constants and functions from the php-intl package which is not a standard one included in most server configurations.
One possible solution that was explored was to force the use of the earlier version in Premium, but it has obvious maintenance issues.
While investigating on why the problem didn't occur when running from the repo instead of from the ZIP, we found that in that case there is a symfony/polyfill-intl-idn package in vendor that provides the missing constants and functions.
We have to vendor_prefix it and make sure it's autoloaded correctly.
* …
> P3-166 Vendor prefix symphony/polyfill-intl-idn

- js/src/components/AdvancedSettings.js
* 
* Adds an id to the meta robots advanced's input field.
*
* Check out and build this branch along with the monorepo one https://github.com/Yoast/javascript/pull/863
* Go to a post/page
* Ensure the `Advanced -> Meta robots advanced` still works and saves as before (I wouldn't know why not).
* Check that underlying input now has the id:
* `yoast_wpseo_meta-robots-adv-input` in the metabox.
* `yoast_wpseo_meta-robots-adv-input_sidebar` in the sidebar.
Fixes #
> P1-181 Add id to the multiselect

- js/src/components/AdvancedSettings.js
- js/src/components/TopLevelProviders.js
- js/src/components/fills/MetaboxFill.js
- js/src/components/fills/SidebarFill.js
- js/src/components/modals/editorModals/EditorModal.js
- js/src/components/portals/MetaboxPortal.js
- js/src/components/slots/MetaboxSlot.js
- js/src/components/slots/SidebarSlot.js
- js/src/components/social/FacebookWrapper.js
- js/src/components/social/TwitterWrapper.js
- js/src/initializers/block-editor-integration.js
* I wanted to use the context providers for context rather than passing props to the containers. AdvancedSettings and FacebookEditor/TwitterEditor had such flow, to avoid conflicts when rendering both in the modal and in the metabox.
I then figured that we call `TopLevelProviders` a lot in `MetaboxFill` and `SidebarFill`, and I thought that that could be refactored. I think I was correct in that, but I want to have some extra eyes on this.
* The MetaboxFill was refactored to not call TopLevelProviders around each item. Rather, TopLevelProviders is now around the MetaboxSlot.
* The SidebarFill was refactored to not call TopLevelProviders around each item. Rather, TopLevelProviders is now around the SidebarSlot.
* The …
> Refactor TopLevelProviders and provide modal location

- inc/class-upgrade.php
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/watchers/indexable-permalink-watcher.php
- tests/unit/integrations/watchers/indexable-category-permalink-watcher-test.php
- tests/unit/integrations/watchers/indexable-permalink-watcher-test.php
* We want to make sure any change to the `permalink_structure` option triggers a re-generation of the permalinks stored in the indexables.
* Monitors changes to the `permalink_structure` option to flush and regenerate the posts permalinks in the Indexable.
- Uses a daily WP-Cron job to monitor changes
- Uses an upgrade routine currently set to version 15.1
- Uses `sanitize_option()` to validate `permalink_structure` as that's WordPress uses to validate this option as well. **Important:** please double check this as `sanitize_option()` also sets a WordPress global "settings error" via `add_settings_error()` to print out an admin notice. Alternatively, we should build our own validation function.
This PR can be tested by following …
> P3-150 monitor permalink structure flush indexable permalinks

- lib/orm.php
- src/builders/indexable-builder.php
- src/builders/indexable-hierarchy-builder.php
- src/repositories/indexable-hierarchy-repository.php
- tests/integration/test-class-wpseo-breadcrumbs.php
- tests/unit/builders/indexable-hierarchy-builder-test.php
Move the save above the hook to make sure the indexable is saved already
* When the indexables aren't indexed, there can be an infinated loop in some cases: on the frontend, post overview in the admin and post edit.
* N/A - It fixes a bug that is introduced in the same branch :)
* moved the save function before the hook to ensure the event is triggered with a saved indexable.
* added an int cast in the orm layer to force inserted id's to int instead of string (this was already in place in selects, but now in inserts too.) this reduces a bunch of duplicate key errors because int keys were being compared to string keys.
* added a method to prevent indexables being added to the hierarchy more than once. …
> Fix indefinite loop

- inc/class-upgrade.php
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/watchers/indexable-homeurl-watcher.php
- tests/unit/integrations/watchers/indexable-homeurl-watcher-test.php
* Registers a cron job that checks whether the `home_url` was changed manually and resets the permalinks accordingly.
* Registers a cron job that checks whether the `home_url` was changed manually and resets the permalinks accordingly.
*
* Ensure you've checked out this branch and have built everything.
* Ensure you've installed the Yoast Test helper.
* To trigger the the upgrade routine, first bump the version in the test helper to something like `15.1-RC0` and then downgrade it again to `15.0-RC6`.
* Check your database and ensure the `home_url` property exists for the `wpseo` key and isn't empty.
* In your terminal, navigate to your Docker environment and run `./wp.sh cron event …
> Flush permalink home url changes

- src/models/indexable.php
* In some case the ancestors has a `null` value cause wrong argument type errors. This is the case when calculating the breadcrumbs on a page add. The indexable object differs from the other ones. 
* N/A - Fixes a bug where an error is given when creating a page.
*
* Checkout this branch 
* Add a page and see no errors occur.
Fixes #
> Set default value for ancestors to an empty array

- js/src/components/SEMrushRelatedKeyphrasesModalContent.js
- js/src/components/modals/SEMrushCountrySelector.js
- js/src/containers/SEMrushRelatedKeyphrases.js
* **Problem**:
Currently, we only fire a request the first time the SEMrush modal is opened since the page has last refreshed. The cached data is stored for a day with `set_transient` (see `src/actions/semrush/semrush-phrases-action.php` line 71). When a SEMrush token is unexpectedly changed and is not valid anymore (manual database changes for instance) the cached results are still shown, even when the keyword is changed. When a new request is fired, an error will be displayed that something went wrong because your token is not valid.
**Solution**: 
We want to always fire a request when the modal is opened if the requested keyphrase has been changed since the last request. If not, the cached data should be presented. This way the token will be checked since the only way to validate the …
> Compare the current focus keyword with the last SEMrush request on modal open

- Gruntfile.js
- config/grunt/custom-tasks/bump-rc-version.js
* If the release branch doesn't yet exist upstream (and is created locally in the `create-rc` task), it fails with a fatal error when pushing to GitHub. While the error message (see the screenshot in the issue) suggests that this is due to a missing `--set-upstream`, it was [explained on Slack](https://yoast.slack.com/archives/CUXBV0FR6/p1601024595013100?thread_ts=1601021983.010200&cid=CUXBV0FR6) that the error message is wrong and that actually the branch that you want to push to, is undefined. This PR fixes that.
* Fixes a bug in the RC automatization where the upstream branch was not defined.
* I also specified that we want to use `grunt-git` for the `gitpush` command (it is unclear why this was missing from the code, although …
> Add the upstream branch to push to

- .travis.yml
* QA
* QA
Travis only takes the exit code of the LAST command into account and as a number of the scripts related to Premium now contain `cd` commands, the `cd` command was the one from which the exit code was being taken.
In reality, the Premium builds should have been failing for quite a while now, but due to the above, the failures weren't being reported.
* _N/A_ This won't show any significant difference in the Travis output until it is merged back to Premium and I've been fixing a number of the errors already, though there may still be some which will cause the builds to fail once the merge back is done.
Seeing those failures is the whole point of this PR.
> Travis: fix Premium builds not reporting failures

- js/src/indexation.js
* The previous code caused the `webpack:buildProd` task to fail when building RC's.
* Replaces a React `Button` with an HTML button to fix an import problem when the monorepo is unlinked.
* Direct imports from the node modules don't work, because they don't have an `src` folder. The reason we had a direct import in the code is because we wanted to have the newly styled React Buttons, and due to a naming conflict with the old buttons we can only have them via direct imports (which only works well with linked monorepo, but for RC building the monorepo has to be unlinked).
* Therefore, in this PR I am replacing the React `Button` with an HTML button, so we don't need the import anymore. …
> Use HTML button to fix broken import of new `Button` component

- js/src/components/SEMrushRelatedKeyphrasesModalContent.js
This is a quick PR to fix a prop type.
* Fixes a bug where a JS warning is thrown in the console when opening the "Get related keyphrases" modal dialog.
* See related PR https://github.com/Yoast/wordpress-seo/pull/16098
I'm not sure why but, for me, the warning is visible in the console only on **Premium trunk**. However, the root cause of the warning is also on Free and in the release/15.1 branch.
- test on Premium trunk
- edit a post
- add a keyphrase and click "Get related keyphrases" to open the modal
- see the warning in your browser's dev tools console
`Warning: Failed prop type: Invalid prop `lastRequestKeyphrase` of type `string` supplied to `RelatedKeyphraseModalContent`, expected `object`. in …
> Fix lastRequestKeyphrase prop type.

- admin/pages/network.php
- admin/views/tabs/dashboard/integrations.php
- admin/views/tabs/network/integrations.php
* The integrations tab is missing in Network admin for multisite, so SEMrush can't be enabled/disabled network-wide (this also measn that subsites may not be able to enable/disable the SEMrush integration for themselves)
* Fixes integrations tab non-existence for network admin 
* The copy for the integrations tab message was adapted from the one in the features tab. This should be reviewed by Product afterwards, we're going on anyway with fixing the bug since it's blocking
* On a multisite installation with the plugin installed and active network-wide, visit the network Dashboard
* visit SEO → General and observe the integration tab is now present
* visit SEO → General in a subsite …
> P3-190 Add Integrations tab for Network admin

- admin/views/tabs/network/integrations.php
* Fixes the naming of the SEMrush switch as network admin from 'on' and 'off' to 'Allow Control' and 'Disable'.
* Changes the naming
* N/A
*
Fixes #
> Fix SEMrush network switch naming

- admin/class-gutenberg-compatibility.php
- wp-seo.php
* WooCommerce is planning on releasing 4.6 on October 13.
* Gutenberg 9.1 has been released on September 30th.
* Bump the Gutenberg version to 9.1 and WooCommerce version to 4.6
*
*
Fixes #
> Bump Gutenberg and WooCommerce version

- package.json
- yarn.lock
*
* Fixes a bug where the `@yoast/helpers` is set to an RC while the latest is a release.
*
*
Fixes #
> Fix wrong helpers version

- js/src/components/SEMrushRelatedKeyphrasesModal.js
- js/tests/components/SEMrushRelatedKeyphrasesModal.test.js
- release-info.json
* The "Get related keyphrases" button uses the old `Button` component which does not match the expected styling. We can't use the `NewButton` component since it's not present (as such) in the `release/15.1` branch of the monorepo.
* Use plain HTML for "Get related keyphrases" button while the new component is unaccessible
* The style that's displayed is just the one calculated by using the classes `yoast-button yoast-button--secondary`. It seems that there is a little mismatch between the expected value for `box-shadow`:
```
box-shadow: inset 0 -2px 0 rgba(0, 0, 0, 0.1);
```
and the actual one from the `yoast-button` class:
```
box-shadow: inset 0 -2px 0 rgba(0, 0, 0, 0.3);
```
This should be addressed either by having the style …
> P3-197 temporarily fix get related keyphrases button styling

- admin/class-admin.php
* [wordpress-seo-premium] On the plugins overview page, we'll always show a link to the FAQ.
* [wordpress-seo-premium] On the plugins overview page, if your plugin is not activated in MyYoast, we'll show an activation link.
* Did this in free because adding a filter to do this in premium would be overkill.
* Have an activated Yoast SEO premium install in WP admin, check the plugins page.
Fixes #
> Show MyYoast activation link on plugins page

- js/src/components/SEMrushRelatedKeyphrasesModal.js
- js/src/components/modals/SEMrushCountrySelector.js
- js/src/indexation.js
- js/tests/components/SEMrushCountrySelector.test.js
* A fix for an import issue with new Buttons has been deployed to trunk and develop, but is actually needed on release/15.1. This PR cherrypicks the needed fixes.
* Allows importing of the new React Button via the NewButton alias.
* See https://github.com/Yoast/wordpress-seo/pull/16123
* See the free PR https://github.com/Yoast/wordpress-seo/pull/16123 and the premium PR https://github.com/Yoast/wordpress-seo-premium/pull/3021 only substitute all mentions of P1-202-use-temporary-alias-for-newer-button-component with P3-138-fix-border-and-use-new-button.
Fixes P3-138
> Use NewButton alias on release/15.1

- src/integrations/watchers/option-wpseo-watcher.php
- tests/unit/integrations/watchers/option-wpseo-watcher-test.php
* Currently there is no way to reset the SEMrush auth tokens without direct manipulation of the DB. If the SEMrush integration is disabled via the toggle, the tokens should be purged.
* Purges the SEMrush auth tokens if the integration is disabled.
* A watcher for the `wpseo` options array has been added, currently used only to check the `semrush_integration_active` flag but it will be triggered anytime an option in the array changes.
* This is also one of the reasons why we don't check for changes but only check if the integration is currently disabled: the checks are reduced to what is strictly needed to minimize the overhead on option changes.
* Also, if the SEMrush integration flag is set to false in any other way than by …
> P3-186 purge SEMrush tokens when integration is disabled

- composer.json
- js/src/indexation.js
- release-info.json
- src/helpers/notification-helper.php
- src/integrations/admin/indexing-notification-integration.php
- src/presenters/admin/indexing-notification-presenter.php
- src/surfaces/helpers-surface.php
- tests/unit/integrations/admin/indexing-notification-integration-test.php
Fixes https://yoast.atlassian.net/browse/P2-390
Fixes https://yoast.atlassian.net/browse/P2-393
*
* Fixes a bug where indexation wouldn't start automatically after being redirected to the tools page from the SEO dashboard notification.
* Made small change to `register_hooks` where I call `create_notification` on `admin_init` instead of relying on wp-cron, because it was more reliable in my experience. 
* Clear the indexables using the Yoast test helper.
* Make sure the notification is shown by running `\wp_clear_scheduled_hook( self::NOTIFICATION_ID );` before `if ( ! \wp_next_scheduled( self::NOTIFICATION_ID ) ) {` in `indexing-notification-integration::register_hooks`.
* Go to the …
> Start indexation if redirected from notification

- js/src/indexation.js
*
* N/A - Improves the copy of the alert that is shown when indexing is disabled for non-production environments.
*
* Set your WordPress environment to anything but production (for example `staging`).
* You can do this by adding or replacing this line in your `wordpress-config.php`:
```php
define( 'WP_ENVIRONMENT_TYPE', 'staging' );
```
* Note: for the `basic.wordpress.test` development environment, this file is `config/basic-wordpress-config.php`.
* Go to the Yoast SEO tools page (e.g. `http://basic.wordpress.test/wp-admin/admin.php?page=wpseo_tools`).
* The button labeled _Start SEO optimization_ should be disabled and the info alert below it should read:
> SEO data optimization …
> P2-409 Improve warning copy for disabled data optimization

- admin/ajax.php
- inc/class-upgrade.php
- inc/options/class-wpseo-option-wpseo.php
- js/src/indexation.js
- src/actions/indexation/indexable-complete-indexation-action.php
- src/helpers/indexable-helper.php
- src/integrations/admin/indexing-notification-integration.php
- src/routes/indexable-indexation-route.php
- src/routes/link-indexing-route.php
- tests/unit/actions/indexation/indexable-complete-indexation-action-test.php
- tests/unit/integrations/admin/indexing-notification-integration-test.php
- tests/unit/routes/indexable-indexation-route-test.php
- tests/unit/routes/link-indexing-route-test.php
* We want an error alert to be shown on the tools page when a request to the indexing endpoint fails. Right now this error is not handled, leading to the indexing tool on the tools page to disappear instead of showing an error alert.
* Fixes a bug where the indexing progress bar and button would disappear from the tools page if a request to one of the indexing endpoints would fail during the indexing process.
* Refactors the way errors are thrown inside the indexing flow.
*
* We need to simulate a failure in one of the endpoints to be able to test this PR.
* Replace the `respond_with` method in `abstract-indexation-route.php` with this:
```php
protected function respond_with( …
```
> P2-391 correctly handle failed indexing requests

- src/routes/semrush-route.php
- tests/unit/routes/semrush-route-test.php
* The SEMrush authorization currently must be performed by a user that has `manage_options` capability (usually, just the admins). Once that the tokens stored, as long as they are valid (or can be refreshed) the SEMrush integration can be used by any user.
if non-admin users try to use SEMrush without valid tokens, they see the popup, clciking on "approve" closes it but then they get a 403 Forbidden error to their AJAX call to store the tokens, and they stay unauthorised.
It has been decided to address this issue by allowing every user that can use SEMrush to perform authorization with it.
* Adjust capability checks for using and authenticating with SEMrush
* I've added a check on the `edit_pages` capability since there could be …
> P3-199 Allow non admins to authorize with SEMrush

- inc/options/class-wpseo-option-wpseo.php
- js/src/indexation.js
- src/actions/indexation/indexable-prepare-indexation-action.php
- src/helpers/notification-helper.php
- src/integrations/admin/indexing-indexables-integration.php
- src/integrations/admin/indexing-integration.php
- tests/unit/actions/indexation/indexable-prepare-indexation-action-test.php
- tests/unit/integrations/admin/indexing-integration-test.php
* Show an alert to tell the user we have combine the different analyzing buttons.
* N/A - Shows a notice to clarify that the difference indexing buttons are combined to one.
* Moved the logic for the limit (the hook) to a separate method.
* Used that method for the `get_total_unindexed` - when there are items being calculated in the background we can assume that there is nothing to index. This prevents showing the button and showing a notification. 
* Reset the indexables
* Visit the tools page and see a notice above the indexing button
* Run the indexing
* The alert is gone. 
* Have some indexables that needs to be indexed and remove the transients. Or use the test helper to reset …
> Add first time indexing alert

- src/config/semrush-client.php
* During testing of 15.1-RC3 on a Windows installation we noticed that the authentication with SEMrush couldn't be performed due to a `401 Unauthorized` error.
Actually it was due to cURL (used by the Guzzle library which in turn is a dependency of the OAuth2 library we are using) that couldn't find the CA certificates to verify the server-to-server connections. It's a know issue that has been experienced by many projects using the Guzzle library.
Since WordPress, to prevent similar issues with its own HTTP client, ships a CA cert bundle, we can use it to prevent the error from happening.
* Fixes a bug on some hosting configurations where the SEMrush authentication would fail
* To set the path of the CA cert bundle, we can use …
> P3-200 Prevent authorization errors when CA cert files are not configured in the server

- src/integrations/admin/indexing-integration.php
- tests/unit/integrations/admin/indexing-integration-test.php
* Did a rename without thinking about the reasons for its original name.
* N/A - Just reverted a name change.
* I think `Indexable_Helper` isn't the best class for such function, but I have no idea what should the alternative. Just keeping it this way. Perhaps `Indexing_Helper` might be a good place, but we should discuss that.
This PR does not change any behavior, but the disabling / enabling of the SEO button based on the environment type should still work as expected.
* Set your WordPress environment type to non-production, for example `staging`.
* You can do this by adding or replacing this line in your `wp-config.php` file:
```
define( 'WP_ENVIRONMENT_TYPE', 'staging' );
```
* …
> Revert rename. Just use the indexable helper for this

- admin/tracking/class-tracking-settings-data.php
* The tracking of the SEMrush-related settings has some mistakes that we need to fix:
* `semrush_integration_active` is tracked as anonymous even though it's just a flag
* `semrush_country_code` is listed as anonymous though it's actually not tracked: we should make sure it's tracked non-anonymously (it contains just the country code for the database used to query SEMrush).
* Fixes a bug where the SEMrush setting where not properly tracked.
*
* build
* edit `/admin/class-admin.php`, and at the end of the constructor (should be line 121) add the following lines:
```
if ( filter_input( INPUT_GET, 'action' ) === 'collect' ) { …
```
> Fix tracking of SEMrush settings

- src/helpers/language-helper.php
*  Let Free users see an upsell notification that promotes Premium word form recognition.
* Activate word form recognition upsell banner for Swedish users.
*
* Set the languages of your website to Swedish.
* Check that you are seeing a morphology upsell. (See [this PR](https://github.com/Yoast/wordpress-seo/pull/15322) for what the upsell looks like.)
Fixes https://yoast.atlassian.net/browse/LIN-585
> Add Swedish to list of languages with morphology support

- inc/class-wpseo-replace-vars.php
- inc/class-wpseo-utils.php
- src/helpers/string-helper.php
- tests/unit/helpers/string-helper-test.php
* Some utils are used in one class only. These should be moved to that classes.
* N/A - It just moved some methods from the utils to the replace vars class.
*
* It is a code move change only and it should work as before.
* Verify that the replacement variables in the templates are replaced correctly. You can set/manage the templates in the search appareance settings. You can also use these in social previews which can you find in the post edit. 
Fixes #
> Move the utils to the class that is using them

- js/src/components/SEMrushRelatedKeyphrasesModal.js
* Reported by @ma0sm:
* With SEMrush unauthenticated, select Get related keyphrases when adding a new post.
* The SEMrush authenticator pops up, you select approve, it disappears.
* Select Get related keyphrases again straight after, and the authenticator appears again.
* Wait a few seconds and the results will appear in the main window, while the authenticator popup just stays there useless.
This can occur because the authentication can took a bit on some systems, and it can happen that the user clicks again on the link to open the popup in the meantime
* Fixes a bug where the SEMrush popup could stay opened even after authorization has been performed successfully
* I decided to just call `close()` on the popup again after the …
> P3-213 Prevent the SEMrush popup to stay open if auth is gone OK

- src/integrations/admin/indexing-notification-integration.php
- tests/unit/integrations/admin/indexing-notification-integration-test.php
* 
* Fixes a bug where the notification to re-index your indexable does not immediately appear when the permalinks, home url or category base is changed.
* 
* Checkout the release branch (`release/15.1`).
* Change your permalink settings.
* E.g. go to _Settings_ > _Permalinks_ and change your permalink structure.
* Notice that you do not immediately get a new notification to re-index your site.
* Checkout this branch (`fix-notification-not-being-shown-when-permalink-changes`).
* Change your permalink settings.
* E.g. go to _Settings_ > _Permalinks_ and change your permalink structure.
* Notice that you do get a new notification to re-index your site.
Fixes #
> Fixed the notification not being shown immediately when permalink settings change

- inc/class-wpseo-admin-bar-menu.php
Do I need to change the ID?
changelog: bugfix
* changes structured data test which is being deprecated to rich results test.
* Fixes a bug where we linked to Google's Structured Data Test, which is deprecated. We now link to Google's Rich Results Test. Props to [wormeyman](https://github.com/wormeyman).
*
* Make sure you are an editor (and NOT an admin)
* Open a blog post while logged in and the admin bar active
* Hover over the yoast icon
* scroll down to analyze this page
* click Structured Data Test
Fixes #16105
> Swap Structured Data tool with Rich Results.

- src/integrations/admin/indexing-indexables-integration.php
- tests/unit/integrations/admin/indexing-indexables-integration-test.php
* We have a routine that calculates indexables on the background. This routine makes sure there are only small groups of indexables being indexed. This prevents showing the 'you have things to index' notification more than needed. 
* N/A - Fixes a bug where the indexables aren't calculated in the background when visiting the yoast seo pages.
*
* On the release branch of 15.1
* Remove 5 indexables from the indexables table. 
* Remove all transients from `wp_options` to prevent cached count values
* Visit a yoast seo page, excepts the tools page.
* See no indexables begin calculated
* Visit the tools page and see the indexables being calculated.
* Checkout out this branch and see that …
> Use the right conditional

- src/integrations/admin/indexing-notification-integration.php
- wp-seo-main.php
*
* Fixes a bug where the notification to index your site wasn't shown when installing Yoast SEO for the first time.
* As advised by @herregroen, we are setting an indexing reason when the plugin gets activated. `$this->options_helper->get( 'indexing_reason' )` will then evaluate to `true`, and as a result the notification will be created.
* Reset your WordPress environment (in `plugin-development-docker`: `./clean.sh`, `./make.sh`, `./start.sh`).
* See that the indexing notification immediately pops up with the following text: "'You can speed up your site and get insight into your internal linking structure by letting us perform a few optimizations …
> Show indexing notification on clean install of Yoast SEO

- src/builders/indexable-link-builder.php
- src/builders/indexable-post-builder.php
- src/builders/indexable-term-builder.php
- src/integrations/admin/admin-columns-cache-integration.php
- src/integrations/admin/indexing-links-integration.php
- src/integrations/watchers/indexable-post-watcher.php
- src/integrations/watchers/indexable-term-watcher.php
- tests/unit/builders/indexable-link-builder-test.php
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/builders/indexable-term-builder-test.php
- tests/unit/doubles/models/indexable-mock.php
- tests/unit/doubles/models/seo-links-mock.php
- tests/unit/integrations/admin/admin-columns-cache-integration-test.php
- tests/unit/integrations/admin/indexing-integration-test.php
- tests/unit/integrations/watchers/indexable-post-watcher-test.php
- tests/unit/integrations/watchers/indexable-term-watcher-test.php
*
* Fixes a bug where the incoming link counts, as shown on the post overview page, was incorrect.
*
* Reset the indexables so you start of with a clean indexable table in your database. 
* E.g. by using the Yoast Test Helper.
* Open a post.
* Add a link to another post on your website.
* Go to the post overview page. 
* Check the incoming link count in its column, it should be off by one.
* In other words: the link you added should be counted to its target post's incoming link count.
* Reset the indexables so you start of with a clean indexable table in your database. 
* E.g. by using the Yoast Test Helper.
* Open a post.
* Add a link to another post on your website.
* Go to the …
> P2-367 Wrong incoming links count on initial indexation

- inc/class-wpseo-image-utils.php
* Add a filter to `WPSEO_Image_Utils` class, to allow highjacking of image meta data. 
This filter is specially useful for those using a plugin that loads image from a third party source like S3 or Unsplash. It is a workaround for #15437 
* Adds a filter to `WPSEO_Image_Utils` class to allow changes to image meta data. Props to [Jonny Harris](https://github.com/spacedmonkey)
*
*
Fixes #16119 #15437
> Add wpseo_image_get_data filter.

- src/conditionals/get-request-conditional.php
- src/integrations/admin/background-indexing-integration.php
- tests/unit/conditionals/get-request-conditional-test.php
- tests/unit/integrations/admin/background-indexing-integration-test.php
* When changing category or taxonomy base, `Background_Indexing_Integration` runs immediately so it starts to fill again the indexable tables with permalink for the terms. Unfortunately, `get_term_link` will return wrong results at this stage as that's based directly on the rewrite rules which are only set at the start of a request.
* Make sure the background indexation is run only on `GET` requests.
*
* checkout and build from `release/15.1` without these commits
* have more than 25 categories and/or more than 25 tags
* start from empty indexable table, perform SEO optimization, see the table is OK
* change category and/or tag base in Settings->Permalinks, perform SEO optimization …
> P3-220 Fix background indexation on taxonomy base change

- admin/ajax.php
- inc/class-upgrade.php
- src/actions/indexing/indexable-prepare-indexation-action.php
- src/actions/indexing/indexing-complete-action.php
- src/integrations/admin/cron-integration.php
- src/integrations/admin/indexing-notification-integration.php
- src/presenters/admin/indexing-notification-presenter.php
- tests/unit/actions/indexation/indexable-prepare-indexation-action-test.php
- tests/unit/actions/indexation/indexing-complete-test.php
- tests/unit/integrations/admin/indexing-integration-test.php
- tests/unit/integrations/admin/indexing-notification-integration-test.php
- tests/unit/presenters/admin/indexing-notification-presenter-test.php
- wp-seo-main.php
*
* Make sure you have more than 25 categories.
* Change the category base in the permalink settings.
* You should get a notification.
* Start the indexing process and close that browser window.
* There should not be a notification ( it assumes you're still in the indexing process ).
* Change your permalink settings again.
* You should get another notification.
*
*
Fixes #
> P2-436 Cleanup indexing notification integration

- src/integrations/third-party/woocommerce-permalinks.php
*
* Fixes a bug where the woocommerce product permalinks were not updated after a permalink structure change.
*
1. Activate Woocommerce.
2. Create 1 product.
3. Change permalinks for products in _Settings_ > _Permalinks_.
4. Save the change.
5. Visit any SEO Admin page
6. It is now expected that product would receive updated permalink in indexables table. But if I check DB it is not changed.
7. Checkout this branch.
8. Step 6 should be solved now.
Fixes #
> Fix woocommerce permalink reset

- readme.txt
- src/actions/indexing/abstract-link-indexing-action.php
- src/actions/indexing/post-link-indexing-action.php
- tests/unit/actions/indexation/post-link-indexing-action-test.php
- tests/unit/actions/indexation/term-link-indexing-action-test.php
* Fixes the indexing tool on the tools page always showing more work to be done.
* Fixes a bug where the indexing button on the Tools page would keep showing up because certain objects would be detected as requiring indexing but would not actually be indexed during the indexing process.
* Have a site that has a few internal links.
* Make sure at least one SEO link does have a target_post_id and does not have a target_indexable_id.
* Run the indexing process.
* It should keep showing as completed after a reload.
Fixes https://yoast.atlassian.net/browse/QAK-2331
> Always index links to account for partially filled legacy SEO links

- js/src/components/Indexation.js
*
* Fixes a bug that wouldn't allow users to stop the indexation by pressing the `Stop SEO Data optimization` button.
*
* Reset the indexables.
* Go to `Yoast` > `Tools` page.
* Start the indexation, let it index a few indexables.
* Stop the indexation and restart it.
Fixes #
> Fix stop indexation

- admin/taxonomy/class-taxonomy.php
* We received warnings from concerned users about unfiltered HTML in taxonomy descriptions. While this was only possible for users with `unfiltered_html` capabilities, it wasn't optimal. WordPress itself normally does not allow this, so we should at least filter the "dangerous" stuff.
* Fixes a bug where unfiltered HTML could be inserted in taxonomy descriptions by administrators and editors.
* Rewritten the function to remove unused filters:
* The pre_link_* filters are for outdated WordPress functionality (blogroll) and no longer needed.
* There was / is no reason to remove kses from user descriptions.
* The description filters have their hard kses filters removed and replaced with post_kses filters to allow for HTML tags that …
> Fix sanitization in term descriptions and remove unused filters

- css/src/modal.css
* First fixed on `trunk` in https://github.com/Yoast/wordpress-seo/pull/16219, but we'll introduce the flex-grow fix as a fix-before-release here as well. Because the bug was quite ugly. The `trunk` fix also has css deduplication.
* Fixes a bug where the replacement variable dropdown menu was partially hidden for the description inputs in all preview modals.
* See https://github.com/Yoast/wordpress-seo/pull/16219
* Test the preview modals (Google Preview, Twitter Preview, Facebook Preview) and verify that the replacement variable dropdown is fully visible in all input fields.
Pay some extra attention to the padding and top border of the modal content (see code comments below). They …
> Add flex-grow to fix the replacevar dropdown being hidden on release branch

- src/integrations/admin/indexing-notification-integration.php
* Fixes a bug where we check against a value that the option will never have. It only can contain `null` or a timestamp (like 123456789). 
* Fixes a regression where the notification always show up when indexing is started and aborted during the process
*
* Reset indexing data
* Deactivate/activate the plugin to have a reason
* Start indexing and press the button to stop it.
* Verify that the notification isn't visible when visiting the dashboard. 
Fixes #
> P2-466 The option never will have a '0' value

- Gruntfile.js
- config/grunt/custom-tasks/update-readme.js
* When there are no changes in the user-facing change log, the automated RC script should not fail when trying to commit the absent changes in the change log to the Git repository.
* Fixes a bug in the automated RC process where an unchanged user-facing change log would crash the RC script.
* I could not directly compare the old and new change log, due to the asynchronous nature of editing the change log during the RC script.
* Instead, and to make it more robust, I decided to check the status of the Git index for any uncommitted changes.
* If there are any uncommitted changes in the `readme.txt`, it commits them.
* Run `grunt update-readme --plugin-version=15.2`.
* An editor should …
> P2 145 rc automization fails on unchanged changelog

- inc/class-wpseo-utils.php
- inc/options/class-wpseo-taxonomy-meta.php
- src/conditionals/third-party/w3-total-cache-conditional.php
- src/integrations/third-party/w3-total-cache.php
* Replace the static util and implementation for a separate third-party integration.
* Moves the flushing logic for w3tc to its own integration. This integration resets the cache when taxonomy data has been changed.
*
* Install W3 Total cache
* Open a term page for example a category. Make some changes in the settings: things like meta description, cornerstone value and some advanced settings
* Save it, refresh the page and verify the values are still saved.
Fixes #
> Moves the logic to its own integration.

- inc/options/class-wpseo-option-wpseo.php
* Adds the `zapier_subscription` option to the `wpseo` option stack.
* Adds the `zapier_subscription` option to the `wpseo` option stack.
* As per CR by @afercia, this code has been moved to here from https://github.com/Yoast/wordpress-seo-premium/pull/3050
*
> Adds the Zapier subscription option (moved from Premium PR)

- inc/wpseo-functions.php
* We potentially redeclare the `ctype_digit()` function due to a conditional error, this should fix that.
* Fixes a bug where the `ctype_digit()` function would be redeclared.
* N/A
* Have a PHP environment without the ctype extension enabled and have the `ctype_digit()` function polyfilled before our plugin is initialized. With this PR, this should not throw a redeclare error.
Note: I have not been able to test this myself, as I was unable to unload the ctype extension during runtime.
Fixes https://github.com/Yoast/wordpress-seo/issues/15925
> Fix possible redeclare error of the ctype_digit function

- config/grunt/task-config/notify-slack.js
*
* Adds a handle to notify the plugin testers when an RC has been created automatically.
*
* Run the automatic RC script.
* See that the plugin testers are pinged.
Fixes #
> Notify the plugin testers on Slack when an RC has been created

- src/helpers/indexable-helper.php
* We want to show the reindex notification whenever the permalinks are reset.
* Fixes a bug where no notification to reindex your site was shown when changing the permalink structure, category base or home URL multiple times in a row and hiding the notification in between.
*
* Change the permalink structure of your website.
* Hide the reindex notification that is shown on the Yoast SEO Dashboard.
* Change the permalink structure again.
* The notification should be unhidden again.
Fixes #
> Always show a notification when resetting the permalinks.

- src/config/indexing-reasons.php
- src/helpers/indexable-helper.php
- src/integrations/admin/indexing-notification-integration.php
- src/integrations/watchers/indexable-category-permalink-watcher.php
- src/integrations/watchers/indexable-homeurl-watcher.php
- src/integrations/watchers/indexable-permalink-watcher.php
- src/presenters/admin/indexing-notification-presenter.php
- src/routes/indexing-route.php
- tests/unit/integrations/admin/indexing-notification-integration-test.php
- tests/unit/integrations/watchers/indexable-category-permalink-watcher-test.php
- tests/unit/integrations/watchers/indexable-homeurl-watcher-test.php
- tests/unit/integrations/watchers/indexable-permalink-watcher-test.php
- tests/unit/routes/indexing-route-test.php
* We want to separate the reasons from the integration
* It just moves the constants to another class
* I point the old constants to the new ones, just for BC
* Reset the permalink structure - A notice wil be given
* Do the same for the category base
Fixes #
> Move notification reasons into standalone class

- inc/class-wpseo-image-utils.php
* The filter name wpseo_image_get_data filter was not logical and not consistent with the name structure of other filters. The filter was introduced in https://github.com/Yoast/wordpress-seo/pull/16177 and is not released yet.
* Renames the unreleased wpseo_image_get_data filter to wpseo_image_data.
* N/A
*
Fixes #
> Rename unreleased wpseo_image_get_data filter to wpseo_image_data

- .travis.yml
* Composer has updated to 2.0 (.2 by now). Travis installs the latest composer version automatically. This breaks our current Travis builds. We should fix this properly, but for now move to the situation where we were before the update.
* Downgrades composer to `1.10.16` on Travis.
* Added to every `before_install`, as that is the first entry point in Travis.
* Travis build should pass.
Fixes #
> Travis: downgrade composer to `1.10.16`

- admin/tracking/class-tracking-settings-data.php
- inc/options/class-wpseo-option-wpseo.php
* We need to add the Zapier API key to the options
* Adds the Zapier api key to the WPSEO options.
*
* Needs to be tested with https://github.com/Yoast/wordpress-seo-premium/pull/3061
Fixes #
> Add Zapier API key to options

- inc/class-wpseo-meta.php
- src/helpers/meta-helper.php
* Adds extra post meta field for the Zapier trigger call.
* Adds meta helper method to easily set values.
* Adds extra post meta field for the Zapier trigger call.
* Adds meta helper method to easily set values.
* This PR is necessary to ensure we don't trigger calls to Zapier when a post has already been published.
* Please test this with https://github.com/Yoast/wordpress-seo-premium/pull/3062
> Add extra post meta field and meta helper method to easily set values

- src/presenters/slack/enhanced-data-presenter.php
- tests/unit/presenters/slack/enhanced-data-presenter-test.php
* Our code breaks AMP and W3C validation, and more broadly is 'invalid' (at least, in terms of W3C validation). It's also inconsistent with the rest of our (correct) meta tags. There is also a potential marketing risk.
* Fixes a bug where AMP and W3C validation would break because Twitter meta tags would contain 'value' attributes instead of 'content' attributes.
* As far as I could see, no changes were needed on WooCommerce SEO, because that doesn't output twitter tags.
* Look on the frontend of the site at the meta tags. See 'content' attributes instead of 'value' attributes in the Twitter meta tags.
Fixes https://yoast.atlassian.net/browse/QAK-2373
> Rename 'value' to 'content' in twitter meta tags

- admin/class-admin-init.php
- admin/formatter/class-metabox-formatter.php
- js/src/analysis/isZapierConnected.js
- js/src/analysis/isZapierIntegrationActive.js
- js/src/initializers/block-editor-integration.js
- js/src/redux/reducers/preferences.js
- js/src/ui/publishBox.js
* This is a companion PR for the related PR on Premium. For the test instructions, please refer to the Premium PR: https://github.com/Yoast/wordpress-seo-premium/pull/3063
* Adds configuration and layout for the Zapier text to be displayed in the Classic Editor publish box and the block editor pre-publish panel.
- adds custom hook into the Classic Editor publish box to make sure the scores _and_ the Zapier text will always be displayed close each other (other plugins may add content here, via the WP hook and with non-predictable priority)
- adds flags for when the Zapier integration is active and connected, and makes these values available for JS (this part needs to be on Free since the related options are on Free)
- adds a Slot …
> P3-168 Add configuration and Slot for the Zapier text

- src/integrations/third-party/woocommerce-permalinks.php
- tests/unit/integrations/third-party/woocommerce-permalinks-test.php
Moved from the WooCommerce SEO plugin
* There aren't any tests for the WooCommerce permalink integration. I moved them from https://github.com/Yoast/wpseo-woocommerce/pull/644 to this repository.
* It just adds unit tests
*
* If travis is happy, we are happy and can press the merge button.
Fixes #
> Add unit tests for the WooCommerce permalinks integration

- src/helpers/language-helper.php
*  Let Free users see an upsell notification that promotes Premium word form recognition.
* Activate word form recognition upsell banner for Hebrew users.
*
* Set the languages of your website to Hebrew.
* Check that you are seeing a morphology upsell. (See [this PR](https://github.com/Yoast/wordpress-seo/pull/15322) for what the upsell looks like.)
Fixes https://yoast.atlassian.net/browse/LINGO-328
> Add Hebrew to list of languages with morphology support

- composer.json
- src/helpers/indexing-helper.php
- src/routes/indexing-route.php
- tests/unit/helpers/indexing-helper-test.php
- tests/unit/routes/indexing-route-test.php
If the start time would still be set to the time when indexing started, the notification is not shown
*
* Fixes a bug where no notification to reindex your site would be shown when the indexing process failed.
* In the `indexing-notifation-integration`, in `should-show-notification`, it is checked whether the `indexing_started` option has a value `> 0`. If so, we never show a notification.
* However, when the indexing reason changes, we do want to always show a notification.
* Therefore, the `indexing_started` option needs to be set to `null`.
* We were only setting `indexing_started` to `null` in the `finish` method, but if the indexing process fails, we never make it to the finish method. We always want to set …
> Set the start time to null when changing the notification reason

- admin/class-admin-asset-manager.php
*
* Fixes a bug where the Yoast metabox could not be loaded in the post editor when the configuration-wizard-1520.js JavaScript file is blocked from loading.
*
* Open the network tab of your browser's developer tools.
* Open the post editor.
* See that the `configuration-wizard-1520.js` is **not** loaded.
* The Yoast metabox should load and there should be no console errors related to `OnboardingWizard`, `LoadingIndicator` and `MessageBox`.
*
* Classic editor, block editor, term editor, configuration wizard.
Fixes #
> Remove the configuration wizard as a dependency from the legacy yoast-components package.

- admin/class-admin-asset-manager.php
- composer.json
*
* Fixes a bug where the configuration wizard would not load.
* Lowered the PHPCS error threshold, since the amount of errors has been reduced to 773 in the mean time.
* Open the configuration wizard.
* The configuration wizard should be shown.
*
* It should only impact the configuration wizard, no other parts.
Fixes #
> P2 502 configuration wizard not shown

- admin/class-yoast-columns.php
- composer.json
- composer.lock
- config/dependency-injection/interface-injection-pass.php
- src/context/meta-tags-context.php
- src/deprecated/src/integrations/admin/indexation-integration.php
- src/exceptions/oauth/authentication-failed-exception.php
- src/integrations/admin/indexing-notification-integration.php
- tests/unit/actions/indexing/indexable-post-type-archive-indexation-action-test.php
- tests/unit/actions/semrush/semrush-options-action-test.php
- tests/unit/helpers/schema/html-helper-test.php
- tests/unit/inc/health-check-ryte-test.php
- tests/unit/integrations/admin/cron-integration-test.php
- tests/unit/presenters/admin/indexing-failed-notification-presenter-test.php
- tests/unit/presenters/admin/indexing-list-item-presenter-test.php
* Updated dev dependencies
* Updated dev dependencies
* Updated YoastCS from `2.0.2` to `2.1.0`.
* Updated PHP_CodeSniffer from `3.5.5` to `3.5.8`.
* Updated the DealerDirect Composer plugin from `0.6.2` to `0.7.0` (which is  compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Relevant changes in PHPCS:
* PHPCS will now _run_ without problems on PHP 8.
Note: it will not necessarily handle all code using PHP 8 syntax correctly  yet, though it does contain preliminary support for various syntaxes.
* Lots of bugfixes.
Refs:
* …
> Composer: update YoastCS + Composer Installers

- css/src/elementor.css
- js/src/initializers/elementor-editor-integration.js
* Replacement variables preview styling was broken in the Elementor implementation.
* Replacement variables styling in the Elementor integration is now the same as in the Block editor and Metabox.
* Styled components stylesheets moved from head to end of body.
* Merge
* Check whether the styling of the replacement variables in the snippet editors is the same as in the 'normal' plugin
* Check that other styling isn't changed compared to P1-193
* Check whether all styling of the Elementor integration is the same as in the Block editor sidebar. Except from link hover color. …
> P1 210 replacement variables styling

- .travis.yml
- composer.json
- composer.lock
- src/routes/semrush-route.php
- tests/unit/routes/semrush-route-test.php
* Update build dependency for compatibility with Composer 2.0.
* Update build dependency for compatibility with Composer 2.0.
_**Note: not sure whether or not this should be mentioned in "Changelog: Other", but it _may_ solve issues (or not).**_
Update the `humbug/php-scoper` dependency from version `0.12.4` to `0.13.8`.
Based on the changelog, this should not make a significant difference for the task for which PHP Scoper is used by YoastSEO, aside from some bugfixes.
However, it does allow us to also update the underlying dependencies, getting rid of the last dependency which was blocking YoastSEO from being installed using Composer 2.x.
Ref:
* https://github.com/humbug/php-scoper/releases
This reverts commit 525272c. The …
> Composer: update PHP Scoper dependency

- admin/class-admin-init.php
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/duplicate-post-integration.php
- src/integrations/duplicate-post.php
- tests/integration/inc/options/test-class-wpseo-option-wpseo.php
- tests/unit/integrations/duplicate-post-integration-test.php
**Note that the branch has a wrong issue number**
* We need to restrict the Zapier integration to supported post types, disable it by default and make sure it's compatible with Yoast Duplicate Post. We need to apply some changes in the Free plugin even if the Zapier integration is a Premium feature.
* Disables the Zapier integration by default, and adds a Duplicate Post integration to filter out meta fields while copying.
* The Duplicate Post integration has been added in Free so it can be used in the future for any other need.
* This needs to be tested together with the companion Premium RC :https://github.com/Yoast/wordpress-seo-premium/pull/3072. refer to that for the …
> P3-248 hide zapier in non public post types

- src/integrations/watchers/indexable-homeurl-watcher.php
- src/integrations/watchers/indexable-permalink-watcher.php
- tests/unit/integrations/watchers/indexable-homeurl-watcher-test.php
* Cleans up some of the code that exists for the watchers related to permalinks by removing unnecessary complexity.
* Introduces a new method called `unschedule_cron` that gets called when the plugin is deactivated to ensure the cron is deactivated.
* Cleans up some of the code that exists for the watchers related to permalinks by removing unnecessary complexity.
* Introduces a new method called `unschedule_cron` that gets called when the plugin is deactivated to ensure the cron is deactivated.
*
* Prior to checking out this branch, run the steps described in https://github.com/Yoast/wordpress-seo/pull/16078 and/or https://github.com/Yoast/wordpress-seo/pull/16079. **Please note …
> Clean up permalink code

- js/src/elementor/components/fills/ElementorFill.js
* We missed copying the SEMrush integration to the ElementorFill.
* Fixes an unreleased bug where the SEMrush button was missing below the Keyphrase input.
* N/A
* Verify that the Add related keyphrases button is present in the Elementor sidebar, and that the modal is present and works.
*
*
Fixes P1-204
> Reintroduce SEMrush modal

- inc/sitemaps/class-post-type-sitemap-provider.php
* To improve compatibility with [get_permalink](https://developer.wordpress.org/reference/functions/get_permalink/).
* Fixes a bug where post-sitemap.xml causes a fatal error when the filter post_link requires WP_Post object.
* Use [sanitize_post](https://developer.wordpress.org/reference/functions/sanitize_post/) instead of casting to int and enforce [WP_Post](https://developer.wordpress.org/reference/classes/wp_post/) object instead of default stdClass.
*
1. Add following PHP code:
```php
add_filter( 'post_link', function( $permalink, WP_Post $post ){ 
return $permalink;
}, 10, 2 );
```
2. Check _post-sitemap.xml_. It should work without PHP fatal error. …
> Enforce post objects to WP_Post in class WPSEO_Post_Type_Sitemap_Provider

- inc/class-wpseo-replace-vars.php
- inc/class-wpseo-utils.php
- src/helpers/options-helper.php
* I didn't realise that the deprecated method was used by other plugins.
* Provides an alternative for a deprecated method
* Moved it to the options_helper, because it relies on `Options`
* Verify that the separator replacement variable still works.
*
* The metabox on post edit / term edit
* The search Appearance admin page
* Front-end: `<title>` and all metavalues where templates can be added. For example the metadescription.
Fixes #
> P2-509 Move method for getting the title separator to a helper

- js/src/components/Indexation.js
- js/src/helpers/urlHelpers.js
- js/tests/helpers/urlHelpers.test.js
* When the indexing is started we don't want to start it again after page reload. If a user refreshes the page he has to press the index button again.
* Prevents the indexing to restart automatically when the page is reloaded during indexing.
* Decided to push the url state instead of replacing it, this allows the user to go back (also to the case where the indexation is started automatically). 
* Reset the indexables with the test helper.
* Go the the yoast dashboard and press the index button in the notification you get about the indexing.
* During indexing refresh the page. Indexing shouldn't start again.
* You can verify this also by checking if the url is altered …
> Remove query parameter

- css/src/elementor.css
* Modal close button hover/active tooltip was broken within the Elementor integration. Also :focus styling of the modal wasn't the same as in Gutenberg. At last radio button styling was off in the Google preview modal.
* Fixes styling of modals within the Elementor integration.
*
* Check whether modals' close buttons tooltips look the same as in the Block editor
* Check whether the radio-button in the Google preview modal looks the same as in the Block editor
* Check whether the :active state of all elements looks the same as in the Block editor
* …
> P1 209 upsell modals styling

- js/src/analysis/PostDataCollector.js
- js/src/analysis/getIndicatorForScore.js
*
* Fixes the analysis bullets reflecting the score again in Elementor.
* Since we do not have the yoastseo app anymore in Elementor, I pulled the indicator translations out of yoastseo into the helper.
* **Positive**:
* One more step away from the old app.
* Less usage of Jed, in favor of `@wordpress/i18n`.
* **Cost**:
* Influences all the score indication being done, requiring more testing.
* The translations are now moved to the `wordpress-seo` domain, requiring it to be translated again.
* Edit a post/page in Elementor.
* Open our sidebar (settings bottom-left -> Yoast SEO tab at the top).
* Verify the readability and SEO analysis collapsible have icons.
* Adapt the …
> P1-221 Fix analysis bullets reflecting score

- js/src/elementor.js
- js/src/elementor/initializers/used-keywords-assessment.js
- js/src/watchers/elementorWatcher.js
- src/integrations/third-party/elementor.php
* We want the used keywords assessment to run in the Elementor integration too.
* The Used Keyword assessment is now initialized in our Elementor integration.
* Added our new refresh analysis function and passed it to the used-keywords-assessment.
* Removed references to the old store, and use `subscribe`, `dispatch` and `select` from `@wordpress/data` instead.
* We get the focusKeyphrase via a selector now.
* Had to add an id to the post_id hidden field (`usedKeywords.js` uses a jQuery search to find the post id hidden field, in order to pass it on in an AJAX request).
* Open three posts in Elementor.
* Add `&yoastdebug` to the URL (make sure this bit is in your …
> P1 212 used keywords assessment elementor

- js/src/initializers/elementor-editor-integration.js
* The update button should be disabled if no changes have been made. With Yoast SEO it's enabled immediately if your SEO score is negative.
* Fixes the update button being enabled in Elementor even if no changes have been made.
* Linkdex values below 0 aren't saved by the plugin. So when watching for changes we treat values below 0 as the default ( which is 0 ).
* Open a post in elementor.
* The update button should be disabled.
* Make a change in the post.
* The button should enable.
* Save your post.
* The button should be disabled again.
* Change any SEO setting
* The button should enable. …
> Fix the save button being enabled on page load

- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/shell.js
* Ensure the deploy to dist runs successfully.
* N/A only build scripts are changed.
*
* Make sure you have not built `@yoast/schema-blocks`, if you have delete the `dist` directory in it.
* Run `grunt artifact`.
* You should have a working zip.
* This does not need to be tested by QA, it only changes build scripts
* The schema blocks JavaScript is touched by this. As this is still behind a feature flag a simple check for no console errors on the post edit screen should be sufficient to ensure no undue changes have been made.
Fixes the Travis trunk build failing.
> Build typescript before building JS in artifact task

- src/integrations/third-party/elementor.php
* When a user disables the SEO settings for a post type, we should not display our sidebar.
* Fixes the SEO setting for post type in Elementor.
* Copied the `display_metabox` from `class-metabox.php` and added the check in register hooks. Had to pass the post-type as the `get_post_type` does not work in that moment of time.
* Disable the SEO settings for posts: SEO -> Search appearance -> Content types -> post type -> Show SEO settings for Posts -> Hide
* Edit a post in Elementor.
* Verify our Elementor integration is not active for that post.
* Edit a page in Elementor.
* Verify our Elementor integration is still active for that page.
* Feel free to play around with …
> P1-233 Fix SEO setting for post type

- composer.json
- composer.lock
* Updated test dependencies
* Updated test dependencies
Updated:
* BrainMonkey from v 2.4.0 to 2.5.0.
Note: this explicitly sets the minimum version. The actual update (without updating the dependencies) appears to already silently have been done in #16067.
* Mockery from v 1.3.0 to 1.3.3.
Improved support for PHP 8.
* Hamcrest-php from v 2.0.0 to 2.0.1
... which claims compatibility with PHP 8.
* Patchwork from v 2.1.11 to 2.1.12
This resolves two issues which _might_ be relevant for us.
Refs:
* https://github.com/Brain-WP/BrainMonkey/releases
* https://github.com/mockery/mockery/releases
* https://github.com/hamcrest/hamcrest-php/releases
* https://github.com/antecedent/patchwork/releases
- Notably: …
> Composer: update BrainMonkey with dependencies

- js/src/initializers/elementor-editor-integration.js
* Authors don't see the "settings" part of the hamburger menu due to Elementor's restrictions. We now register the button under "more".
* The location of the Yoast SEO button in Elementor has shifted from "settings" to "more".
* N/A
* Have the Yoast test helper (or log in as a user with the author role).
* Follow the steps to reproduce in issue [P1-237](https://yoast.atlassian.net/browse/P1-237).
* Switch to an author, and verify that you can still access Yoast SEO via the hamburger menu (top left three horizontal stripes).
* Be logged in as an author (not admin).
* Verify that you can still access the Yoast SEO sidebar via …
> Moved Yoast SEO button location in hamburger menu from "style" to "more"

- lib/orm.php
Properties should use visibility modifiers to indicate their access and should not be named using the PHP 4 "_underscore prefix for protected and private properties_" practice.
This commit renames all properties in the `Lib\ORM` class to comply.
*_N/A_ This is covered by the integration tests (verified) If those pass, we're good.
* External classes which extend the `Lib\ORM` class and access these properties will need adjusting.
> CS: Lib\ORM: rename properties (no underscore prefix)

- .travis.yml
* Fix broken CI check
* Fix broken CI check
The `composer install` within the `premium` subdirectory was not being run for PHP 8, which was the reason the PHP `nightly` builds were failing on Premium as the linting tooling could not be found.
* _N/A_
Once Free has been merged back into Premium, check the output of the Travis build for `nightly`. It should be passing and running the PHP linting correctly, while previously it was failing.
> Travis: fix `lint` command for Premium on PHP 8

- admin/formatter/class-metabox-formatter.php
- js/src/initializers/used-keywords-assessment.js
* We want the duplicate posts for Rewrite & Republish to skip the Previously Used Keyword analysis assessment so that they can share the same keyphrase without affecting the analysis. These posts are temporary copies and will be deleted when "Republishing" so the assessment result would be misleading.
Note: this is a companion PR for the main PR on Duplicate Post, see https://github.com/Yoast/duplicate-post/pull/56
* Adds a filter to deactivate the Previously Used Keyword analysis assessment.
*
- this PR needs to be tested together with the main PR on Duplicate Post, please refer to the test instructions there.
-N/A as it was …
> P3-235 Add filter to deactivate the PreviouslyUsedKeyword assessment.

- admin/class-meta-columns.php
- tests/integration/test-class-wpseo-meta-columns.php
* To hide some of our columns by default, we hijack a user options call. This essentially disables the core filter `default_hidden_columns`. The [original PR](https://github.com/Yoast/wordpress-seo/pull/8191) was outdated so I reapplied the same fix in our current codebase. 
* Fixes a bug where we break the core `default_hidden_columns` filter. Props [thomasmb](https://github.com/thomasmb).
* N/A
1. Visit any public post overview screen in the backend
1. Play around with the screen options, hide and unhide different columns. The behavior should not have changed.
Fixes https://github.com/Yoast/wordpress-seo/issues/8189
> Use a filter for default hidden columns

- admin/class-admin-editor-specific-replace-vars.php
* Improved compatibility with PHP 8.0
* Improved compatibility with PHP 8.0
`array_merge()` expects to be passed one or more arrays to be merged. As the `$arrays` parameter is variadic, PHP 8.0 named parameters is not supported.
`call_user_func_array()` expects a function name and an array of parameters to be unpacked and passed on to the function.
In PHP 8, when `call_user_func_array()` receives an array of parameters with string keys, the keys will be interpreted as parameter names.
Refs:
* https://www.php.net/manual/en/function.array-merge.php
* https://www.php.net/manual/en/function.call-user-func-array
* https://wiki.php.net/rfc/named_params#call_user_func_and_friends
The base `$replacement_variables` array has string keys …
> PHP 8.0: fix fatal ArgumentCountError

- css/src/elementor.css
- js/src/elementor/containers/SnippetEditor.js
QA discovered some issues with styling of the Elementor integration. Especially with the overflow of modals. This PR fixes those issues.
*
* Nothing special
* Check whether modals show a vertical scrollbar when the content doesn't fit the screen instead of content overflowing
* Check whether styling of the Elementor integration looks the same as that of the Block editor sidebar apart from link hover color and the radio buttons in the Google Preview. Those are delibaretely different as decided together with Kai.
* Check that styling is the same as in te Block editor sidebar apart from link hover color and the radio buttons in the Google Preview. Those are delibaretely different as …
> P1 238 elementor modal styling issues

- composer.json
- phpcs.xml.dist
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/builders/indexable-social-image-trait-test.php
- tests/unit/builders/indexable-term-builder-test.php
* Ignore overwriting WordPress global variables for the unit tests, as for those, the WordPress environment is not loaded, so it won't influence other tests.
* Exclude the `lib` directory from select naming conventions sniffs as the intention is to move this code to a separate package.
* Exclude the `src/deprecated` directory from select naming conventions sniffs as renaming classes and such would be a BC-break, while these files remain in place to _prevent_ BC-breaks.
... to take these changes and the other changes of today into account.
* _N/A_ If the Travis build passes, we're good.
> PHPCS: ruleset update and add select ignore annotations

- js/src/components/SEMrushRelatedKeyphrasesModal.js
- js/src/components/modals/editorModals/EditorModal.js
- js/src/initializers/elementor-editor-integration.js
* SEMRush modal was not accessible when our sidebar was closed and then opened again.
* Fixes an unreleased bug in the Elementor integration where the SEMrush modal was closing immediately upon opening, after the Yoast SEO sidebar had been closed an opened again.
* Moved the stylesheet from the bottom of the body to our own integration, because it kept duplicating on every close and open. Now it is removed on close, and added again on open.
* Filter the blur event to check whether it is caused by clicking outside of the modal (not all blur events should lead to a close).
* Go to the SEO sidebar in Elementor. Open the Semrush modal. It should open.
* Go to any other …
> Fix semrush modal closing immediately

- js/src/initializers/elementor-editor-integration.js
*
* Fixes a bug where the Elementor update button would be active on page load right away.
The prominent words are not loaded in the hidden field correctly. This always starts as an empty string (not only in the Elementor editor). The actual values are then calculated in JS.
In Elementor this is a problem because we rely on the hidden input values for the "dirty" check.
But since the prominent words are based on the content, title and description (ty Marijn 😄  and Herre for confirming) I felt it is save to ignore changes in that data.
* This is a free change that impacts premium only. So developers: create a branch (from release/15.4 on premium and merge this into it).
* …
> Elementor: ignore prominent words change

- config/grunt/custom-tasks/update-readme.js
- tests/unit/integrations/schema-blocks-test.php
* The pop-up that lets you enter the new changelog entries already fills in the version number for the new release. However, it currently always fills in a number like `15.4.0`, even though we never use the `0` in our versioning. I added a check that only adds the patch number if it is unequal to zero.
* Improves the RC automatization by checking whether the plugin version number should contain a patch number.
*
**To reproduce**
* Create a new test branch from `trunk` (because the test will add a commit to your branch).
* In the terminal, run `grunt update-readme --plugin-version=15.5` (the version number should be higher than what we currently have in `readme.txt`).
* …
> Only add the patch number in the readme if we're actually doing a patch

- admin/formatter/class-post-metabox-formatter.php
- inc/class-wpseo-replace-vars.php
- inc/class-wpseo-utils.php
- inc/date-helper.php
- inc/sitemaps/class-author-sitemap-provider.php
- inc/sitemaps/class-sitemaps-renderer.php
- inc/sitemaps/class-sitemaps.php
- src/deprecated/inc/sitemaps/class-sitemap-timezone.php
- src/helpers/date-helper.php
- tests/unit/helpers/date-helper-test.php
* We want to use modern helpers instead of the old ones.
* No functional change, it just inverses the dependencies.
* I just removed the `WPSEO_Date_Helper` dependency on the date helper in the `src` directory. And just called the 'modern' date helper in the old `WPSEO_Date_Helper`. All locations where we have `WPSEO_Date_Helper` as dependency are replaced by calling methods from `YoastSEO()->helpers->date`
* I would suggest to do a smoke test by:
* visiting the sitemaps and see if the dates are rendered right
* make sure the `%%date%%` replacevar is still correct.
* make sure the `%%modified%%` replace var is still right.
* And the date that is shown in the preview is …
> Inverses the dependency

- config/dependency-injection/custom-loader.php
* Fixed Dependency Injection Compile command on Windows
* Fixed Dependency Injection Compile command on Windows
Both the returned value from `glob` as well as the classmap generated by Composer contain file paths with a mix of forward and backward slashes when run on Windows.
This was breaking the `compile-di` command.
Previously it was _silently_ broken - it wouldn't work, but without throwing an error.
Since the addition of the `Schema_Blocks` it would fail with an exception.
This commit fixes this by:
1. Adding a `normalize_slashes()` method.
2. Calling that method in the relevant places in the script to make sure that paths are normalized before they are compared based on their string value.
The …
> Dependency Injection: fix custom loader on Windows

- admin/class-yoast-plugin-conflict.php
- admin/menu/class-admin-menu.php
- admin/menu/class-base-menu.php
- admin/menu/class-network-admin-menu.php
- composer.json
- inc/class-wpseo-utils.php
- tests/integration/test-class-wpseo-utils.php
Replaces #16272
I've deprecated some methods, when you are merging this and the next release is higher than `15.4` please change the version numbers instead of pushing it back to me, otherwise it would take up some time where I keep increasing the version number. Thanks!
* We want to replace the static utils by helper methods. 
* It just replaces, deprecates and moves existing logic.
* I did a search for all methods and couldn't find any occurrences of them. This makes it safe enough for me to move / deprecate the functionality.
* The methods `grant_access`,`traffic_light_svg`, `schema_tag` and `schema_output` aren't used anymore. Safe enough to remove them.
* I moved the methods `has_access_token_support` and `get_roles` to the …
> More utils cleanup 2

- js/src/dashboard-widget.js
* When a user chooses to hide the Yoast SEO dashboard widget by unchecking the corresponding box in the screen options on the dashboard, we want to prevent this widget from still fetching data.
* Fixes a bug where the Yoast SEO dashboard widget would still fetch data even when it was hidden.
* We only want to fetch the data when the box is checked.
* We only want to fetch the data once. If a user keeps checking and unchecking the box, the data don't need to be fetched every time. Therefore, we introduced `isDataFetched` in the state.
* Please note that this PR tackles the situation where the widget is _hidden_. It's also possible to completely [remove the widget with a filter](https://yoast.com/help/how-to-hide-the-seo-dashboard-w …
> Don't fire HTTP requests when the Yoast dashboard widget has been hidden

- js/src/elementor/initializers/editor-store.js
* An error occurred in Elementor when opening the sidebar without having `opengraph` enabled. Or `twitter`.
* Fixes an unreleased bug where the Yoast SEO sidebar would crash in Elementor if "opengraph" or "twitter" were disabled.
* Only initialize data we actually have on the page.
* Disable `opengraph`, go to an Elementor page and open our sidebar. No crashing should occur. Twitter should be visible populated with the right data.
* Disable `opengraph` and `twitter`, go to an Elementor page and open our sidebar. No crashing should occur. No social fields should be visible.
* Disable `twitter` (enable `opengraph`), go to an Elementor page and open our sidebar. No crashing …
> Only attempt loading Social data if the platform is enabled

- js/src/elementor/redux/actions/snippetEditor.js
- js/src/elementor/redux/selectors/analysis.js
- js/src/redux/selectors/snippetEditor.js
* We don't want to change the way the snippet editor fields behave simultaneously with the new integration, because it is slightly confusing. For MVP, we will revert back to the old behavior.
* Also fixes incorrect Keyword in Title and metadescription assessments.
* Fixes the confusing cases where the title input field was empty, yet the title length bar showed a non-zero length.
* Fixes an unreleased bug where the meta description and keyword in title assessments were not getting accurate data.
* I had a hard time restoring old functionality in a nice way, so I went with a pragmatic way.
The SnippetEditor selectors need some work, since they don't play nicely with the templates. It's hard to select whether you want:
• whether …
> Restore old Snippet Editor fields functionality

- js/src/elementor/redux/selectors/analysis.js
*
* Fixes a bug where links were not picked up correctly by the analysis in the Elementor editor.
* The base URL prefix is needed in the URL comparison. As the analysis does not remove this for the links in the content. Could be a possible improvement in the future?
The update event is not always being triggered when working with a dynamic Button link in Elementor. I created a bug on their repo for this. If this is the case, please ignore and change the text of the button or something to trigger the event: https://github.com/elementor/elementor/issues/13136
* Edit a post/page without any links in the Elementor editor.
* Verify the SEO analysis has the problems with …
> P1-261 Fix links

- admin/class-admin-asset-manager.php
- composer.json
- src/integrations/schema-blocks.php
- tests/unit/TestCase.php
- tests/unit/integrations/schema-blocks-test.php
* The templated are shown before the `<html>`-tag which resulted in wrong parsed templates. 
* Fixes a bug where the templates aren't parsed correctly
* Added a wrapper for `is_script_enqueued` to the `WPSEO_Admin_Asset_Manger` to check if a script is enqueued.
* Passed the `WPSEO_Admin_Asset_Manger` as dependency to the constructor
* Added an `expectEmptyOutput` to the testcase just to have a proper assertion when testing early returns
* Check this together with https://github.com/Yoast/javascript/pull/944
*  
*
Fixes #
> Output schema templates later

- js/src/helpers/elementorHook.js
- js/src/initializers/elementor-editor-integration.js
- js/src/watchers/elementorWatcher.js
* This PR should fix the `Document is not editable` error when saving a published post as a draft in Elementor.
This is an error triggered by Elementor while checking if there are any changes on the document (and if the status is not draft). We artificially tell Elementor something changed when our data changes.
This PR does not fix this completely, see the `Unable to fix` section below.
* This PR should make it so that we do not save Yoast SEO data when saving a draft on an already published post.
* Fixes a bug where Elementor save as draft would save the Yoast SEO data to the published post.
Elementor keeps the `update` button active after saving as a draft. When you reload the page and save as a draft right away, you still …
> P1-251 save draft on published post

- js/src/initializers/elementor-editor-integration.js
- src/integrations/third-party/elementor.php
* Saving takes place in free code in Elementor via an Ajax request, but in Premium we need to check the headers for whether a redirect has taken place.
* Adds an action to hook into the save functionality of our Elementor integration.
* Needed for https://github.com/Yoast/wordpress-seo-premium/pull/3097
* See https://github.com/Yoast/wordpress-seo-premium/pull/3097
Fixes P1-258
> Do action for premium elementor to get access to redirect headers

- admin/class-admin-asset-manager.php
- js/src/elementor.js
- js/src/initializers/elementor-editor-integration.js
* The goal is to speed up the Elementor editor loading, or rather the interactivity. Keep in mind this PR is written with a time constraint too.
* Loads our Elementor JS at a later time, making the interactivity earlier.
*
* Go to an Elementor edit page.
* Compare the moment of interactivity of this version and a previous version (previous RC?).
* To get some more measurements you can open the network tab in the inspector.
* The elementor JS script is loaded in later.
* The initialize in that script is run later, which results in the analysis-worker script to be loaded in later.
* Verify the action works by testing the Premium PR that uses it: …
> P1-269 Delay loading our Elementor JS

- js/src/watchers/elementorWatcher.js
*
* Fixes an unreleased bug where a console error would appear when switching to site settings in Elementor.
* Chose to skip analysis dispatches entirely when the document is not a "wp-post" or "wp-page".
* On release/15.4, the bug would occur if you go to site settings (hamburger menu > site settings).
* With this branch checked out and built, open a post, a custom post, and a page.
* On each, make some changes and verify that the analysis runs (for example remove your focus keyphrase from the title) and verify that that assessment changes. Or check the logs / redux if you have access.
* Then switch to site settings on each, and verify that there is no console error, and …
> Fix console error .find of undefined on document switching

- css/src/elementor.css
* Headings in our sidebar in Elementor where mimicing the color scheme our plugin has in the Block editor on WP5.3. That needed to be updated to look just like in the Block editor on WP5.5.3 
* Colors of our headings in the Elementor sidebar are now universal in color and mostly slightly darker, like in the newest Block editor
*
* Open our Elementor integration and verify that the headings look comparable to our sidebar in the Block editor on WP5.5.3. Please be aware that color-codes can sligthly differ, as the Elementor integration uses the Yoast color scheme instead of the WP color scheme. But the general look should be the same. …
> updates headings in sidebar to wp5.5 colorscheme

- js/src/initializers/elementor-editor-integration.js
- js/src/redux/actions/index.js
*
* Adds a warning when there are SEO setting changes on a non-draft post.
*
* Create a new post/page and switch to the Elementor editor.
* Verify there is no warning at the top of our sidebar.
* Change some SEO settings.
* This should never make the warning appear.
* Publish the post/page.
* Verify there is no warning (yet).
* Change an SEO setting.
* Verify the warning appeared at the top of our sidebar:
* Check the text is the same as in the issue.
* Change the post status back to draft (Settings (the tab next to the Yoast SEO tab) -> General Settings -> Status).
* Verify the warning disappears.
* Play around with this 😄 
* …
> P1-272 add warning

- src/helpers/language-helper.php
* Let Free users see an upsell notification that promotes Premium word form recognition. Reduce the limit of prominent words that are saved so that it matches the limit of other languages with function word support (languages with no function words get a higher limit to increase the chances of content words showing up in the prominent words).
* Activate word form recognition upsell banner for Hungarian users, and reduce the maximum number of prominent words that are saved for Hungarian users to match that of other languages with function word support.
*
* Set the language of your website to Hungarian.
* Check that you are seeing a morphology upsell in Free. (See [this …
> Add Hungarian to lists of languages with morphology and function words

- admin/class-admin-asset-manager.php
- admin/class-config.php
* This PR replaces https://github.com/Yoast/wordpress-seo/pull/16400/commits/b9b1cd86f3ee41000b448ad3f26f50533b9cbf3d. That PR was created off of a wrong branch (i.e., not `trunk`), taking along with it the commits of that wrong branch.
* In this PR, I cherry-picked the only commit from https://github.com/Yoast/wordpress-seo/pull/16400/commits/b9b1cd86f3ee41000b448ad3f26f50533b9cbf3d which was actually meant to be present in the PR.
* Fixes a bug where the translations on Search Appearance pages would be broken.
* Removed the declaration of the `search-appearence` script
* Localized `settings` because that script will be loaded on that page.
* On trunk
* Set your site in …
> Localize an existing script

- js/src/elementor/components/fills/ElementorFill.js
- js/src/elementor/containers/Alert.js
- js/src/initializers/elementor-editor-integration.js
- js/src/redux/selectors/index.js
- js/src/redux/selectors/warning.js
* Fix a console error that appeared in some cases, mostly around the draft warning in Elementor.
* Fixes an unreleased bug where a console error would appear when the draft warning rendered.
* Changes the draft warning to a draft info box which is less threatening.
* Using a more applicable component, `Alert.js` which accepts strings rather than an array of html. Had to create a quick container to translate [] => string though.
* Shifted to using an "info" alert rather than a "warning" alert, as per the spec.
* Moved the StyleSheetManager up one level, because it was misbehaving.
* `yarn unlink-monorepo`!!!!! Build all the things, and finally run `grunt webpack:buildProd` …
> Trying with a new component

- config/grunt/task-config/notify-slack.js
* We don't want to ping the whole product team when an RC has been created, but a subset of those people.
* Changes the ping when an RC has been created from `@team-product` to `@product-rc`.
* 
* For CR: look up the ID for the `@product-rc` handle [here](https://app.slack.com/client/T0258FPMJ/browse-user-groups/user_groups). When you click the handle, you will see the ID in the address bar.
* If the ID is correct, no test should be needed.
* No need for testing.
*
Fixes #
> Change ping to product-rc

- inc/options/class-wpseo-option-wpseo.php
* Reflect the right option value in feature management
* Fixes a bug where the tracking was disabled network-wide but was sending tracking data on a single site.
*
* On a multisite:
* Disable the tracking network-wide
* Go to a site in the network and see the toggle for the tracking is disabled
* In class `WPSEO_Tracking` add in method `tracking_enabled` the following code: `die( 'Hi!' );` under:
```php
// Check if we're allowing tracking.
$tracking = WPSEO_Options::get( 'tracking' );
if ( $tracking === false ) {
return false;
}
```
* On the site where the feature was enabled for the single site it should print `Hi!`
* Checkout this branch and see it now adapts the …
> Add tracking to ms feature disable

- admin/tracking/class-tracking.php
* We don't want to send tracking data when on the network admin
* Fixes a bug where tracking would send partial data
*
* Enable tracking data on the first site of your admin (this is the main site)
* In class `WPSEO_Tracking` add this in method `should_send_tracking` on line 152:
```
die('Sending data');
```
* Go the first site of your network and see there is printed `Sending data`
* Go the a second site and see there is nothing printed
* Go to you network admin site and see there is printed `Sending data`
* And see that only the first site will print `Sending data` and the network admin + second site won't print something. …
> Do early return on network admin

- .travis.yml
- js/src/elementor.js
- package.json
* Initialize our JS translations in our Elementor integration.
* Initializes our JS translations in our Elementor integration.
*
* Switch site language to something other than English.
* Edit a post in Elementor.
* Open the Yoast sidebar.
* Verify the text is translated.
* Note: Some (like the new info) might not be, due to it not actually being translated yet. You can check the sidebar in the block editor to see what should be translated.
*
* Initializes l10n in our Elementor integration.
Fixes #
> Add l10n initialization

- js/src/components/AreaChart.js
* We want to avoid an error in the SEMrush modal when the trend values are all zero and also display a horizontal blue line when that's the case.
* Fixes a bug where the SEMrush modal triggers errors and doesn't display a chart when all the Trend values are zero.
- the AreaChart component used in the SEMrush modal works in a way that needs to get the maximum value for the X and y coordinates used for the chart
- in some edge cases, SEMrush may return a value of zero for all the previous 12 months displayed in the modal for a given keyphrase suggestion
- when this happens, the data returned for X and Y are like the ones in the screenshot below, where `y` is always `0`:
- this triggers a division by zero later in the AreaChart code …
> P3-241 Ensure the AreaChart max values are at least 1 to avoid a division by zero

- inc/sitemaps/class-taxonomy-sitemap-provider.php
Hi folks!  👋 
`get_terms` in `wordpress-seo/inc/sitemaps/class-taxonomy-sitemap-provider.php` can be very taxing on a site with thousands of terms.  I'm adding some arguments here so that we don’t have to grab all the terms every time each single taxonomy sitemap is built.
* I've noticed degraded performance for some sites on WordPress VIP when taxonomy sitemaps are active.   We would like to help customers be able to keep these while not significantly degrading their applications.
* The main issues are in **when** the sitemap generation happens and **how** the links are built for taxonomies
* This PR hopes to address a small first step which is improving the performance of the `get_terms()` called
* Related issue: https://github.com/Yoast/wordpress-seo/issues/6761
I think there are more …
> Improve performance for taxonomy sitemaps

- composer.json
- inc/class-wpseo-replace-vars.php
- src/generators/schema-generator.php
- src/integrations/schema-blocks.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/integrations/schema-blocks-test.php
* The `generate` code in the schema blocks generator is called multiple times, which means that we tried to register some replacement variables multiple times, leading to a PHP warning in the post editor.
* Fixes a bug where warnings about replacement variables were shown in the post editor.
* Decided to move the registration of the replacement variables to the `Schema_Blocks_Integration`, 
* To make sure that it is only called when the schema blocks feature flag is enabled.
* Hooked into the `wpseo_json_ld` action for registering the replace vars.
* Since we need the replace vars to be registered before the schema output, and this hook triggers right before generating and outputting the schema, it seemed like the most …
> P2-558 Register replacevars in the schema-blocks integration.

- js/src/components/social/SocialUpsell.js
- js/src/containers/FacebookEditor.js
- js/src/containers/TwitterEditor.js
* We had some mistakes with translations. There are more mistakes, but this covers the social previews placeholders and info text only. The social preview labels for example should be covered by this issue: https://yoast.atlassian.net/browse/QAK-2529
* Fixes a bug where the social preview placeholders and info text where not translated.
1. Use the correct text domain in the plugin itself: `wordpress-seo`.
1. If a file is imported before we pass the translations to `@wordpress/i18n` (see the i18n helpers), the translations won't work. This is now prevented by moving them to the function in which they are used.
* Switch the site language to non-English
* Edit a post
* Open …
> P1-286 Fix socials translations

- js/src/dashboard-widget.js
* This prevents a console warning.
* Fixes an unreleased bug where a console warning would be output on the WordPress dashboard when the Yoast SEO widget was enabled.
* Because the warning said that `setState` cannot be called on a component that is not yet mounted, I'm now first checking whether the DOM is ready.
* Please make sure that https://github.com/Yoast/wordpress-seo/pull/16383 still works as expected.
* In addition, you should _not_ see a console warning about the Yoast dashboard widget when you're on the WordPress dashboard and have the Yoast dashboard widget enabled.
* …
> Only set the state after the component has mounted

- admin/class-yoast-form.php
* Subsites in a multisite network never send tracking data. Therefore, we don't want to confuse the user by showing a toggle for this feature, suggesting that they have control over it. In this PR, the toggle for the tracking feature is always disabled on multisite subsites.
* Fixes a bug where subsites in a multisite network could have an enabled feature toggle for the `Usage tracking` feature, even though subsites never send tracking data.
* I couldn't find a specific function to check if a site is a subsite, therefore I used `! is_network_admin() && ! is_main_site()`.
* Get a multisite environment running (in Docker, you can use `./start.sh multisite-wordpress`).
* …
> Disable the Usage tracking feature toggle on multisite subsites

- inc/class-wpseo-admin-bar-menu.php
Before:
After:
* Remove the admin bar menu on block editor pages. This only shows on mobile anyway, and there it's annoying when there's too much stuff in the admin bar as it blocks access to the block editor's toolbars.
* Open a page in the block editor, switch to mobile view, see there's no Yoast admin bar menu + score. See screenshots above.
> [P3-266] Remove the admin bar on block editor pages

- js/src/elementor/replaceVars/elementor-replacevar-plugin.js
- js/src/elementor/replaceVars/general/excerpt.js
- js/src/elementor/replaceVars/general/index.js
- js/src/elementor/replaceVars/general/modified.js
- js/src/elementor/replaceVars/general/name.js
- js/src/elementor/replaceVars/general/pageNumber.js
- js/src/elementor/replaceVars/general/pageTotal.js
- js/src/elementor/replaceVars/general/postTypeNamePlural.js
- js/src/elementor/replaceVars/general/postTypeNameSingular.js
- js/src/elementor/replaceVars/general/term404.js
- js/src/elementor/replaceVars/general/userDescription.js
- src/integrations/third-party/elementor.php
*
* Adds advanced snippet variables in the Google preview of our Elementor integration.
* Use all added replacement variables, except term404,  on posts and pages
* Use wpseoScriptData to pass the replacement value from PHP to JS
* Only in the Google preview until https://yoast.atlassian.net/browse/P1-242 is done. Then also in the social previews.
* Translation of the labels not working. There is a separate issue for this: https://yoast.atlassian.net/browse/QAK-2530
* Edit a post in the Elementor editor.
* Open the Google preview.
* Try the replacement variables in the title or description:
* Post type (singular) / `%%pt_single%%`: Replaced with the content type single …
> P1-223 Add advanced replacement variables in Elementor

- README.md
This PR simply replaces the URL that is used for the Travis badge that is displayed in the README.md file. I noticed that it is pointing to travis-ci.org and it seems that you migrated to travis-ci.com.
> Update README.md to use badge from travis-ci.com instead of travis-ci.org

- tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
- tests/unit/TestCase.php
- tests/unit/admin/metabox/metabox-collapsibles-section-test.php
- tests/unit/admin/metabox/metabox-section-additional-test.php
- tests/unit/admin/myyoast-proxy-test.php
- tests/unit/integrations/admin/indexing-tool-integration-test.php
- tests/unit/integrations/admin/migration-error-integration-test.php
- tests/unit/integrations/front-end-integration-test.php
- tests/unit/integrations/front-end/force-rewrite-title-test.php
- tests/unit/integrations/schema-blocks-test.php
* Improve unit tests
* Improve unit tests
Order fixture methods in the order they will executed fo lower cognitive load.
PHPUnit contains a native `expectOutputString()` method to set expectations for generated output.
If needs be, this can be combined with a call to `setOutputCallback()` method to adjust the actual generated output before the expectation is tested, for instance, to normalize line endings.
With that in mind, there is no need for a custom `expectOutput()` or `expectEmptyOutput()` methods in the `WPSEO_UnitTestCase` class.
So, this commit switches out the custom code in this test suite in favour of using the PHPUnit native `expectOutputString()` method.
WP Test Utils 0.2.0 introduces a new `expectOutputContains()` …
> Unit tests: remove custom expectOutput*() methods and other improvements

- admin/class-admin.php
- admin/pages/dashboard.php
* Picked up from the WPSEO CS Cleanup spreadsheet. This tiny PR seeks to remove remnants related to the old "about" page.
* Removes unused code related to the old About page.
- Yoast SEO used to have an "About" page accessible at the URL `wp-admin/admin.php?page=wpseo_dashboard&intro=1`
- That page was removed starting from #5504 and following changes.
- Right now, trying to access that URL (which users might have bookmarked, for example), makes WordPress print out the following error message on the page: "There has been a critical error on your website. Please check your site admin email inbox for instructions."
- This PR removes the unused code related to the About page.
- It does _not_ remove the user meta …
> Remove about page remnants.

- package.json
- src/integrations/third-party/web-stories.php
- yarn.lock
In order for Web Stories to be discoverable, it makes sense to always have a meta description.
Since Web Stories for WordPress does not _yet_ have support for the Yoast meta boxes, this seems like the easiest way to ensure meta descriptions being present, without the user having to change the Search Appearance settings.
If there's a better suited filter for this, please let me know.
* Web Stories: ensure that there’s always a meta description. Props to [swissspidy](https://github.com/swissspidy)
* Uses the `wpseo_metadesc` filter to fall back to displaying the post excerpt if there's no meta description present.
1. Create a new web story
1. Add some excerpt in the document panel
1. …
> Web Stories: ensure that there’s always a meta description

- src/helpers/language-helper.php
- tests/unit/helpers/language-helper-test.php
* Let Free users see an upsell notification that promotes Premium word form recognition. Reduce the limit of prominent words that are saved so that it matches the limit of other languages with function word support (languages with no function words get a higher limit to increase the chances of content words showing up in the prominent words).
* Activate word form recognition upsell banner for Norwegian users, and reduce the maximum number of prominent words that are saved for Norwegian users to match that of other languages with function word support.
*
* Set the language of your website to Norwegian Bokmål.
* Check that you are seeing a morphology upsell. (See [this …
> Add Norwegian to languages with morphology and function words

- admin/metabox/class-metabox.php
- js/src/elementor.js
- js/src/helpers/fields/EstimatedReadingTimeFields.js
- js/src/initializers/estimated-reading-time.js
- js/src/post-edit.js
- js/src/redux/actions/estimatedReadingTime.js
- js/src/redux/actions/index.js
- js/src/redux/reducers/estimatedReadingTime.js
- js/src/redux/reducers/index.js
- js/src/redux/selectors/estimatedReadingTime.js
- js/src/redux/selectors/index.js
- src/conditionals/admin/estimated-reading-time-conditional.php
- src/integrations/estimated-reading-time.php
- src/integrations/third-party/elementor.php
- tests/unit/conditionals/estimated-reading-time-conditional-test.php
- tests/unit/integrations/estimated-reading-time-test.php
* In https://github.com/Yoast/wordpress-seo-premium/pull/3094 we added Estimated Reading Time to premium. But there are free features that also need the value. That's why the changes in Premium were removed in https://github.com/Yoast/wordpress-seo-premium/pull/3122, and added here.
* Adds estimated reading time to the yoast-seo/editor store and relevant actions and selectors.
* Adds an estimated reading time hidden field, so the reading time can be persisted in post metadata.
*
* The easiest way to make sure everything in P1-288 went well, is to test in premium, with a `--no-commit` of this branch. Therefor, follow the test instructions here …
> Move Estimated Reading Time calculation and data flow to free

- admin/class-admin-asset-manager.php
- config/webpack/paths.js
- js/src/editor-modules.js
* Yoast SEO Premium is currently still a fork of Yoast SEO free. It relies directly on JavaScript modules in the free part of the code. This PR makes sure all Yoast editor modules which Premium relies on are exposed in a separate file, which can be depended on by Yoast SEO Premium, or any other plugin for that matter.
* Exposes all Yoast editor modules which are relied on by Yoast SEO premium in a separate script.
* Simply decided to expose all the modules in one big ugly object. The alternative would be to reorganize all of the JavaScript in Yoast SEO. That seemed like an easy trade off. 
* enqueue the script. Notice no new JS errors. …
> Expose the Yoast editormodules which are used outside of Yoast SEO.

- src/integrations/third-party/web-stories.php
- tests/unit/integrations/third-party/web-stories-test.php
* Simplifies the way default metadata output of Web Stories for WordPress is removed.
In the Web Stories plugin we recently simplified how the plugin's default metadata output can be remove by plugins like Yoast SEO. There are now a few dedicated filters, see https://github.com/google/web-stories-wp/blob/0994fd1808777a2907e3369c5f93f85438cedb3a/includes/Discovery.php
* Make integration with Web Stories for WordPress more robust
* Uses more appropriate filters to filter metadata output
1. Create a new web story
2. View story on frontend
3. Ensure Yoast SEO metadata is present
4. Ensure default metadata added by Web Stories is present (i.e. there are no duplicates). 
QA can …
> Web Stories: Update metadata filters

- src/config/migrations/20201216124002_ExpandIndexableIDColumnLengths.php
- src/config/migrations/20201216141134_ExpandPrimaryTermIDColumnLengths.php
* On large WordPress installations, IDs like post IDs and author IDs can be large. Larger than our database tables (e.g. `wp_yoast_indexable` and `wp_yoast_primary_term`) currently allows. This PR migrates those columns to `bigint`s, such that they allow higher ID values.
* Fixes a bug where the plugin would break on very large WordPress installations.
* Decided to split the new database migrations into two, one for each database table.
* This makes each migration responsible for one table, which makes it easier to read.
* Check the `indexable` table structure in your WordPress database.
* The `object_id`, `author_id` and `post_parent` columns should have a datatype of …
> Added migration to transform ID columns in the indexable table to bigint.

- css/src/modal.css
* In https://github.com/Yoast/wordpress-seo/pull/16484 we accidentally merged Estimated Reading Time changes to trunk, but they also have to be in release/15.6. Thus, this is a copy of that branch, rebased to release/15.6. For all further information, see the original PR.
* Adds two columns to be used in the modal
> Add CSS for two columns in modal

- src/helpers/schema/replace-vars-helper.php
- tests/unit/helpers/schema/replace-vars-helper-test.php
*
* Fixes an unreleased bug where a PHP notice was shown on non-post pages.
*
1. Make sure that you have Query Monitor plugin installed.
2. Visit to a non-post page, like an author archive or term archive page. 
3. See the following PHP notice when you open the Query Monitor debug bar:
```
Trying to get property 'post_date' of non-object
```
1. Make sure that you have Query Monitor plugin installed.
2. Visit to a non-post page, like an author archive or term archive page.
3. You should not see any PHP notices.
*
*
Fixes #
> Fixed PHP notice on non-post pages.

- .gitignore
- config/composer/actions.php
- config/dependency-injection/container-compiler.php
- config/dependency-injection/inject-from-registry-pass.php
- config/dependency-injection/schema-templates-pass.php
- config/dependency-injection/services.php
- lib/abstract-main.php
- lib/dependency-injection/container-registry.php
- src/main.php
- tests/unit/dependency-injection/schema-templates-pass-test.php
* Creates the basic DI framework that can be used and expanded by our add-ons so they can implement their own DI containers that can inject classes from the free container.
* N/A
There are no effective changes, this only introduces framework to be used by add-ons. Functionally free stays identical.
*
* Delete your generated container in `src/generated/container.php` as well as the meta file next to it.
* Run `composer compile-di`
* It should work
* Run the plugin, meta output should appear as normal on the front-end without warnings or errors.
* Meta output should appear as normal on the front-end without warnings or errors. …
> Create DI framework to be used by add-ons

- inc/language-utils.php
- src/integrations/third-party/elementor.php
* Don't use deprecated methods. `WPSEO_Language_Utils::get_user_locale()` got deprecated in https://github.com/Yoast/wordpress-seo/pull/15905 for 15.6
* Fixes an unreleased bug where a deprecated function was not adapted to the alternative in the Elementor integration.
* Fix the version in the deprecation comment to the actual 15.6
* Deactivate the plugins `Debug bar` and `Query monitor`. They don't fully work in the Elementor editor (due to scripts not being enqueued there) and hide the deprecation warning.
* Edit a post in the Elementor editor.
* The deprecation notice should no longer be present in the HTML; starts with `Deprecated: …
> P1-311 Fix usage of deprecated get_user_locale

- js/src/elementor/components/fills/ElementorFill.js
- js/src/elementor/components/modals/editorModals/FacebookPreviewModal.js
- js/src/elementor/components/modals/editorModals/TwitterPreviewModal.js
- js/src/elementor/containers/FacebookEditor.js
- js/src/elementor/containers/TwitterEditor.js
* A newer implementation of replacevars was used for the Google preview in Elementor. For consistency and future implementations this needs to be applied to the Social previews as well.
* Adds advanced snippet variables in the Social previews of our Elementor integration.
* Copied some files like done for the Google Preview modal. These copies can be removed whenever the new kind of Replacevar implementation is adapted to the Block and Classic editor as well.
* Edit a post in the Elementor editor.
* Open the Facebook preview.
* Try the replacement variables in the title or description:
* Post type (singular) / `%%pt_single%%`: Replaced with the content type single label
* …
> P1 242 elementor social replacevars update

- src/presentations/indexable-author-archive-presentation.php
- tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/indexable-author-archive-presentation/robots-test.php
* Set noindex for empty author pages if user is owner of CPT which isn't shown on author page. 
* Fixes a bug where empty author archive pages could be indexed when the author had published a custom post-type that was not shown on his/her author archive page. Props to [stodorovic](https://github.com/stodorovic).
* Re apply the logic from PR #13570. Only post_types from the filter _wpseo_author_archive_post_types_ should be counted as user's posts.
1. Create public CPT
```php
// Listing type.
$args = [
'labels'       => [
'name'               => 'Directory',
'singular_name'      => 'Listing',
'add_new'            => 'Add New Listing', …
```
> Correctly implemented count_posts call in indexable-author-archive-presentation.php

- composer.json
- tests/unit/generators/breadcrumbs-generator-test.php
- tests/unit/generators/open-graph-image-generator-test.php
- tests/unit/generators/schema/article-test.php
- tests/unit/generators/schema/faq-test.php
- tests/unit/generators/schema/howto-test.php
- tests/unit/generators/twitter-image-generator-test.php
*
* Adds doc blocks to methods in the generator unit tests.
* Fixes an incorrect `@covers` annotation in a unit test.
*
* Check that Travis passes.
* N/A, only applies documentation blocks to some unit tests.
* N/A, only applies documentation blocks to some unit tests.
Fixes #
> Fixes CS warnings on docs in the generator unit tests.

- src/helpers/language-helper.php
- tests/unit/helpers/language-helper-test.php
* Let Free users see an upsell notification that promotes Premium word form recognition. Reduce the limit of prominent words that are saved so that it matches the limit of other languages with function word support (languages with no function words get a higher limit to increase the chances of content words showing up in the prominent words).
* Activate word form recognition upsell banner for Turkish users, and reduce the maximum number of prominent words that are saved for Turkish users to match that of other languages with function word support.
*
* Set the language of your website to Turkish.
* Check that you are seeing a morphology upsell. (See [this …
> Add Turkish to languages with morphology and function words

- config/composer/actions.php
- config/dependency-injection/container-compiler.php
- config/dependency-injection/custom-loader.php
- src/main.php
* This is preparation for using premium as an addon, a hardcoded class map path doesn't work when free is in the vendor directory itself.
* Makes the class map path of the custom DI loader dynamic instead of hardcoded.
* Run `composer compile-di`. Your `src/generated/container.php` shouldn't change.
* Delete `src/generated/container.php` and load any page, it should automatically be regenerated.
* Load any page which has Yoast SEO meta in the head. The fields should be present and unchanged.
* This affects building the DI container. If it …
> Make the class map path dynamic in the custom loader

- config/grunt/custom-tasks/sync-gutenberg-version.js
* When creating the RC per grunt script, a change in the Gutenberg compatibility version is not pushed to the remote.
* Fixes a bug where the `sync-gutenberg-version` Grunt task would not push the changes.
* Making use of https://github.com/rubenv/grunt-git as in the `bump-rc-version` task.
* Switch to this branch.
* Run yarn install to ensure grunt dependencies are there.
* Open `admin/class-gutenberg-compatibility.php` and lower the version.
* Create a new branch (e.g. `test-sync-gutenberg`) and push it to the remote (so you can remove it instead of having to force push later).
* Commit this change (push does not matter).
* Run the grunt task: `grunt …
> Add push after gutenberg compatibility version change

- src/presentations/indexable-presentation.php
- src/surfaces/values/meta.php
* Enhanced Slack Integration did not have access to Estimated Reading Time any longer, unless a post was recently saved/updated.
* Fixes a bug where the Enhanced Slack sharing integration did not show Estimated Reading Time for posts that were not recently created or updated.
* Added the old estimated reading time to the generator in case the reading time is not set yet.
* Clear the estimated_reading_time_minutes from the indexable for a post, or find one where the estimated_reading_time_minutes is NULL.
* Then view that post on the frontend (don't go to the editor for that post). Before this fix, enhanced slack integration would not display estimated reading time.
* Now …
> Fix enhanced slack sharing bug when reading time is null

- admin/class-yoast-notification-center.php
- admin/tracking/class-tracking-server-data.php
* FILTER_INPUT doesn't work for INPUT_SERVER when using fastcgi ( see https://stackoverflow.com/questions/25232975/php-filter-inputinput-server-request-method-returns-null )
* Fixes the update notification not being dismissable.
* Have a server with FastCGI enabled.
* Attempt to dismiss the update notification.
* It should work.
* The notification center and the tracking data send.
> Replace filter_input( INPUT_SERVER, ... ) with  for fastcgi compat

- config/webpack/externals.js
* We want to be able to use the `@wordpress/date` package inside of the editor, which is set on the window under `window.wp.date`.
* Adds the `@wordpress/date` package as an external JS dependency to the plugin's WebPack configuration.
* Fixed the code style of the `externals.js` config file to be in line with the JS code style. 
* Only a regression test is needed, see the test instruction under "Impact check".
* 
* Test whether the block editor still works as expected, no new JavaScript errors are introduced.
Fixes #
> P2-252 - Added `@wordpress/date` as an external WP JavaScript package in WebPack.

- admin/class-yoast-notification.php
- tests/integration/notifications/test-class-yoast-notification-center.php
This change allows the Wordpress to avoid a race condition caused by a [call to `WP_User->get_role_caps()`](https://github.com/Yoast/wordpress-seo/blob/23d97720eeefbc604a73703b180072a01366f8d1/admin/class-yoast-notification.php#L285) which momentarily [resets the `allcaps` property](https://github.com/WordPress/WordPress/blob/bf83c368fdfcee2b879d00b193f505038e1681f0/wp-includes/class-wp-user.php#L513), causing custom capabilites on the site to malfunction.
* Fixes a bug where custom capabilities could be reset due to our code. Props to [Jerome Charaoui](https://github.com/jcharaoui).
* This replaces a WP core function `get_role_caps` with another, `user_can`, which also serves to simplifiy the `has_capabilities` function.
This PR …
> Avoid race condition in get_role_caps(), fixes #16108

- admin/class-helpscout.php
- composer.json
- src/deprecated/frontend/class-opengraph-oembed.php
- src/integrations/admin/cron-integration.php
- src/integrations/admin/link-count-columns-integration.php
- src/integrations/admin/migration-error-integration.php
- src/integrations/blocks/abstract-dynamic-block.php
- src/integrations/blocks/block-categories.php
- src/integrations/blocks/structured-data-blocks.php
- src/main.php
- tests/unit/presentations/abstract-presentation-test.php
- tests/unit/repositories/indexable-hierarchy-repository-test.php
- tests/unit/routes/indexables-head-route-test.php
Coding Standards will recognize `{@inheritDoc}` as a valid inheritance declaration.
This is resolving a couple of CS errors.
Seems this was possible all along: https://github.com/squizlabs/PHP_CodeSniffer/pull/214
* N/A
* None
* None, only documentation change in code.
*
* None
Fixes P2-609
> Replace `@inheritDoc` with `{@inheritDoc}`

- admin/class-admin-init.php
- admin/class-yoast-notification-center.php
- config/grunt/task-config/copy.js
- inc/class-upgrade.php
- release-info.json
* Removes the release notification as the added benefit of having it, is minimal and seems to result in more questions from users.
* Removes the release notification as the added benefit of having it, is minimal.
*
* First, ensure that you have the 15.6 release notification present in the notification center:
* Switch to the `rebased-release/15.6` branch
* Install and activate the Yoast Test Helper plugin
* Go to Tools > Yoast Test, and set the Yoast SEO DB Version to 15.6
* Navigate to the notification center (SEO -> General)
* See that the notification is present.
* Checkout this branch and build everything accordingly.
* Refresh the notification center. See that the …
> Removed the release notification

- src/integrations/blocks/breadcrumbs-block.php
* Temporarily disables the breadcrumbs block for 15.7
* Disables the breadcrumbs block until it can be finalized.
* Don't register the block.
* Notice the breadcrumbs block does no longer show up
> Temporarily disable the breadcrumbs block.

- tests/unit/config/semrush-client-test.php
* Fixes a occasion where travis fails on differing timestamps in two tests.
* Fixes a bug where 2 tests unrightfully fail by differing timestamps due to travis running slower then the tests expect.
* Defined the time at the beginning of the tests, and uses that value instead of getting it seperately
* N/A, this is a travis only thing
Fixes #
> P3 318 fix semrush timestamp tests

- config/dependency-injection/inject-from-registry-pass.php
*
* Fixes a not released bug where WordPress SEO Premium would show deprecation warnings when visiting a page.
*
**Note**: Though this code is in free, the deprecation warnings only occur in Premium, so this should be tested in Premium.
On `release/15.7` / previous RC:
* Make sure you use Premium.
* E.g. merge this branch into the Premium release branch. 
* Make sure that you have the Query Monitor plugin installed and activated.
* Visit any admin page.
* See deprecation warnings like these inside of the Query Monitor logs:
```
Deprecated (Suppressed)	The "Yoast\WP\SEO\Conditionals\Admin_Conditional" service is private, getting it from the container is deprecated since …
```
> Made type definitions added to the container automatically public

- src/actions/alert-dismissal-action.php
- src/helpers/user-helper.php
- src/routes/alert-dismissal-route.php
- tests/unit/actions/alert-dismissal-action-test.php
- tests/unit/helpers/user-helper-test.php
- tests/unit/routes/alert-dismissal-route-test.php
* When adding dismissable alerts (not to be confused with the Yoast Notification Center notifications) we do not want to have to reinvent the wheel every time. This PR implements an action that handles that alert per user. Plus an endpoint that calls the dismiss action with a given key (for when the user dismisses an alert in JS).
* Adds generic alert dismissal functionality.
* Using the `edit_posts` permission as per feedback from Herre. Subscribers shouldn't be able to save data to the database. https://yoast.slack.com/archives/C01FYN1QGB1/p1610458141008200?thread_ts=1610457905.008100&cid=C01FYN1QGB1
* Not too sure about the return data of the route. But looked at the SEMRush and there we have an object that includes `success` …
> P1-314 add alert dismissal

- src/helpers/url-helper.php
- tests/unit/helpers/url-helper-test.php
The link classifier was erroneously parsing scheme relative links as internal. So this link:
```html
<a href="//d33v4339jhl8k0.cloudfront.net/docs/assets/5375d691e4b0d833740d56cc/images/54ab21d7e4b047ebb774ac27/file-gOxSkpNUXo.jpg">image</a>
```
Would be parsed as internal, even though it's only scheme relative.
* Correctly classify scheme relative links.
* Should be tested properly by the new unit tests, but can also be tested by running this code:
```php
$url = parse_url( '//d33v4339jhl8k0.cloudfront.net/docs/assets/5375d691e4b0d833740d56cc/images/54ab21d7e4b047ebb774ac27/file-gOxSkpNUXo.jpg' );
echo '<pre>' . print_r( $url, 1 ) . '</pre>';
echo …
```
> Fix link classifier

- admin/metabox/class-metabox-section-additional.php
- css/src/metabox.css
- js/src/components/SidebarButton.js
- js/src/components/modals/editorModals/EditorModal.js
- js/src/components/modals/editorModals/FacebookPreviewModal.js
- js/src/components/modals/editorModals/GooglePreviewModal.js
- js/src/components/modals/editorModals/TwitterPreviewModal.js
- js/src/elementor/components/modals/editorModals/FacebookPreviewModal.js
- js/src/elementor/components/modals/editorModals/GooglePreviewModal.js
- js/src/elementor/components/modals/editorModals/TwitterPreviewModal.js
* [We want to "reactify" the Video metabox](https://github.com/Yoast/wpseo-video/pull/860), and this required some changes in Free and the monorepo.
* Adds the option to adjust the additional metabox section classnames.
* Adds ids to the Modal buttons in the sidebar.
*
* Test together with the [Video PR](https://github.com/Yoast/wpseo-video/pull/860). Follow test instructions there.
* Test without the Video PR, but with the monorepo PR. All should work as normal.
*
*
Fixes N/A
> Make wpseo-form class output optional and add ids to Modal buttons

- admin/class-config.php
- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- admin/views/tabs/social/facebook.php
- js/src/components/ImageSelectComponent.js
- js/src/components/portals/ImageSelectPortal.js
- js/src/containers/FacebookEditor.js
- js/src/containers/TwitterEditor.js
- js/src/editor-modules.js
- js/src/helpers/selectMedia.js
- js/src/initializers/search-appearance.js
- js/src/initializers/social-settings.js
- js/src/settings.js
* The ImageSelect component features a preview and this PR replaces the old image upload in the metabox and settings pages with the new ImageSelect
* Replaces the image uploads with the new ImageSelect component.
*
ImageSelect should look like this:
* Test this PR together with the same [branch on the monorepo](https://github.com/Yoast/javascript/pull/1023)
* Check the following pages to see if the new ImageSelect renders like it should 
* Search Appearance > General > organization image
* Search Appearance > General > person image
* Social Settings > Facebook > frontpage
* Social Settings > Facebook > default image
* Metabox > Social > Facebook
* Metabox > Social > …
> Replace image uploads with new ImageSelect component

- admin/class-bulk-editor-list-table.php
- admin/filters/class-cornerstone-filter.php
* `&&` and `||` are SQL operators that should be avoided due to double usage (in the case of `||`) and [deprecation](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_and).
* Improves interoperability and consistency in database queries.
* Simply replaced SQL `&&` operators with `AND`. This should cause no issues.
* Inspired by https://yoast.atlassian.net/browse/QAK-1440, but that needs fixing in Premium.
* In the posts overview; make sure the cornerstoned articles are the same before and after this change.
* In SEO -> Tools -> Bulk editor; make sure that any saved changes are reflected correctly on page reload.
This PR affects the following parts of …
> Replace deprecated SQL && operators with AND

- src/integrations/third-party/woocommerce.php
- tests/unit/inc/sitemaps/sitemaps-admin-test.php
- tests/unit/integrations/third-party/woocommerce-test.php
*
* Fixes a bug where paginated WooCommerce shop pages did not have the right canonical.
* 
* Make sure that you have a WooCommerce shop with more than 12 products.
* This ensures that you have a paginated shop.	
* Go to page 2 (or higher) of your paginated shop.
* E.g. https://woocommerce.wordpress.test/shop/page/2
* Inspect the page's source code.
* The source code should contain a canonical link with the same link as the page.
* E.g.    
```html
<link rel="canonical" href="http://woocommerce.wordpress.test/shop/page/2/">
```	
*
*
Fixes #
> Added pagination support for WooCommerce shop pages.

- css/src/toggle-switch.css
* We need to fix the disabled style for the switch toggles.
* Fixes a bug where the disabled style of the switch toggles didn't look right.
* Note: this emerged in the ongoing work on Local SEO where some toggles may be disabled even when the underlying option is set to "enabled"
* activate Yoast SEO switched to this branch (build it, of course)
* activate Local SEO switched to the `P3-329-new-toggle-shared-opening-hours` branch (build it, of course)
* go to SEO > Local SEO > Opening hours
* set "Locations inherit shared opening hours" to Yes
* set "Open 24/7" to No
* set "I have two sets of opening hours per day" to Yes
* set "Locations inherit shared opening hours" back …
> P3-349 Fix light switch toggle disabled style.

- config/dependency-injection/custom-loader.php
* If two containers are compiled in the same request, such as when an addon is deactivated or activates during development then the second compile will fail due to the class map being static and thus reused between both compilations.
* Fixes a fatal that would occur in development versions of the plugin when activating or deactivating one of our addons.
* Make sure you're running a git clone of the repo.
* Deactivate an addon.
* There should be no fatals.
* This does not affect production builds.
* Development versions of the plugin.
> Fix static class map in custom loader

- css/src/metabox.css
- js/src/components/modals/editorModals/EditorModal.js
- js/src/containers/EditorModal.js
- js/src/redux/actions/editorModals.js
- js/src/redux/actions/index.js
- js/src/redux/reducers/editorContext.js
- js/src/redux/reducers/editorModals.js
- js/src/redux/reducers/index.js
- js/src/redux/selectors/editorContext.js
- js/src/redux/selectors/editorModals.js
- js/src/redux/selectors/index.js
* Needed for [P1-361 in Video](https://github.com/Yoast/wpseo-video/pull/867).
* Adds actions and selectors that can be used to open and close the editor modals.
* Needed for [P1-361 in Video](https://github.com/Yoast/wpseo-video/pull/867).
* Should be mainly tested together with the [Video PR](https://github.com/Yoast/wpseo-video/pull/867), but on it's own, these are the changes you should test.
* *In the block-editor:*
* Make sure all modals in the Sidebar can still be opened and closed. Without new console errors.
*
*
Fixes P1-361
> P1-361 Add redux flow and self-contained implementation for the modals

- admin/class-yoast-form.php
- composer.json
- src/presenters/admin/light-switch-presenter.php
* We want to make the "light switch" toggle more flexible so that it can be used also with post meta. We need this in Local SEO, see P3-333.
* Refactors the light switch toggle by introducing a presenter class.
* also lowers the PHPCS threshold to 348.
* activate Yoast SEO switched to this branch and build
* test a "light switch" toggle: for example, the one under SEO > Search Appearance > Taxonomies > Remove the categories prefix
* check the toggle styling looks okay 
* check the "?" help button works as expected and reveals the inline help when clicked
* set the toggle to "Keep" and save
* got to Posts > Categories and click the "View" link of one of the categories
* …
> P3-353 Refactor the light switch toggle by introducing a presenter

- src/actions/alert-dismissal-action.php
- src/builders/indexable-post-builder.php
- src/integrations/alerts/abstract-dismissable-alert.php
- src/routes/alert-dismissal-route.php
- tests/unit/actions/alert-dismissal-action-test.php
- tests/unit/routes/alert-dismissal-route-test.php
* To increase security, use an allow list for the dismissable alerts. Original PR for dismissable alerts: https://github.com/Yoast/wordpress-seo/pull/16544
* Adds an allowed dismissable alerts interface (to an unreleased feature).
* The allow list is checked in the route. Meaning that a key has to be registered in PHP in order for the route to be able to dismiss it.
* Added public `is_allowed` to the action that is used in the `dismiss`, `reset` and `is_dismissed` functions and in the route for validation.
* Added an Abstract_Dismissable_Alert class to use as a higher level integration.
* Includes tiny unrelated documentation codescout.
* To check a working alert see the …
> P1-360 add allowed dismissable alerts

- src/builders/indexable-hierarchy-builder.php
- src/repositories/indexable-hierarchy-repository.php
- src/repositories/indexable-repository.php
- tests/unit/builders/indexable-hierarchy-builder-test.php
* Since the homepage isn't really going to change and we need it on every page load, shortly caching the request for that should save a query per pageload.
* Performance: prevents database queries for the homepage indexable.
*
* When visiting the homepage:
* There should be only one query for the home page indexable.
* There should not be any delete queries for the ancestors table apart from the very first query with this PR active.
* All metadata, including the breadcrumb, should be unchanged.
*
Fixes #
> Cache (shortly) retrieving the home-page indexable

- Gruntfile.js
- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/copy.js
- config/grunt/task-config/shell.js
- package.json
* 
* Get the translatable strings from the schema blocks package
*
* Do the yarn magic
* Run `grunt build:i18n:potFiles`
* Verify that you have the `languages/yoast-schema-blocks.pot` file
* Also make sure that `languages/wordpress-seo.pot` contains `No, please undo this`
* This is a string from the schema blocks package and should be in wordpress-seo which will be read by WordPress to fill load in the translator site.
*
*
Fixes #
> Setup the tasks for building the translations for schema-blocks

- config/dependency-injection/schema-templates-loader.php
- config/dependency-injection/schema-templates-pass.php
- src/integrations/schema-blocks.php
- tests/unit/dependency-injection/schema-templates-loader-test.php
- tests/unit/integrations/schema-blocks-test.php
* We don't want to release the recipe schema block already
* Puts the recipe schema blocks behind a feature flag.
* Used the feature check in an `if-condition` in the integration that loads the templates. I've located it here because the dependency container isn't aware of any feature flag that is set on the user's site.
* Also made the path build by the dependency container (machine) relative. 
* Run `composer compile-di` and verify that the path in the calls to the `$instance->register_template` method are relative in `src/generated/container.php`
* Disable the feature flag and see that no templates are loaded
* Enable the feature flag and see the templates are loaded. …
> Put recipe schema behind feature flag

- src/builders/indexable-hierarchy-builder.php
* The function `is_invalid_ancestor()` may be passed a non-Indexable object which would cause a fatal error due to type declaration. We want to prevent this but still check for the object type.
* Fixes a fatal error when a post ancestor is not an indexable.
* The function checks if an ancestor is invalid. If the argument is not an indexable object, it is also invalid, so the function should be able to expect a non-Indexable as an argument.
* Create and save a page
* Create another page and set the previous page as parent, save this page.
* Both pages should save normally.
* Indexables should be created for both pages as usual. …
> Prevent fatal error due to type declaration

- src/generators/schema/breadcrumb.php
* When we check for broken schema breadcrumbs, we assume the passed variable is an array. If it is not, the array checks will throw warnings. This can be prevented by checking for an array first, as a non-array breadcrumb is broken anyways.
* Fixes a bug where invalid breadcrumbs may show PHP warnings. 
* A non-array breadcrumb is broken either way, so no need to check it for array values.
* Make sure breadcrumbs keep working the way they do. This fix covers theoretical edge-cases which I have not yet reproduced myself.
* N/A
*
Fixes #
> Introduce broken breadcrumb array check

- admin/views/class-yoast-feature-toggle.php
- admin/views/tabs/dashboard/integrations.php
* Code used by the Zapier integration toggle was adeed to the Free files in the Premium repo by mistake, so it was not present anymore since Free was imported as a dependency. We should fix that
* Fixes a bug where integrations toggles wouldn't display following content.
* The PR which added to Premium code meant to Free is: https://github.com/Yoast/wordpress-seo-premium/pull/3035
Only the changes for the first two files are needed.
* this needs to be tested on Premium: check out the `hotfix/15.8.1` branch there
* run `composer require --dev yoast/wordpress-seo:dev-P3-368-fix-missing-info-after-integration-toggles@dev`
* build
* visit SEO->General, Integrations tab
* …
> P3-368 Reinstate code added to Free files in Premium repo by mistake

- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
- admin/taxonomy/class-taxonomy.php
- src/helpers/product-helper.php
- tests/unit/helpers/product-helper-test.php
The path no longer works since Premium became an add-on
* Because Premium is becoming an add-on, the `/premium` path no longer exists.
* Fixes an unreleased bug where we were using a path to check whether we are in the Premium plugin. This path no longer exists when Premium becomes an add-on.
* Adds a helper function to retrieve the plugin name, and simplifies the code in several places by calling this function.
* I wanted to [remove the partial mock from the test](https://yoast.atlassian.net/wiki/spaces/DEV/pages/1081770041/Architecture+decision+log#Partial-mocks-are-discouraged-and-should-never-be-used-for-dependencies.), but then had the problem of having to mock a static method (`WPSEO_Utils:is_yoast_seo_premium`). Therefore, …
> P2-668 Use the helper to get the product name

- src/commands/index-command.php
- src/deprecated/src/actions/indexing/indexable-prepare-indexation-action.php
- src/routes/indexing-route.php
- tests/unit/commands/index-command-test.php
- tests/unit/routes/indexing-route-test.php
* We do not want to use our own deprecated classes.
* Fixes a bug where a deprecation notice would be shown when in a WordPress development environment and visiting a page.
*
* Make sure that the Query Monitor plugin is installed and activated.
* Run `composer compile-di`.
* Go to any webpage on your website.
* Click on the Query Monitor bar in the admin bar at the top of the page.
* You should see this deprecation warning:
```
Deprecated (Suppressed) | Relying on service auto-registration for type 
"Yoast\WP\SEO\Actions\Indexing\Indexable_Prepare_Indexation_Action" is deprecated since Symfony 3.4 
and won't be supported in 4.0. Create a service named …
```
> Replaces the deprecated indexable_prepare_indexation_action in the indexing command with the appropriate replacement.

- src/integrations/schema-blocks.php
- tests/unit/integrations/schema-blocks-test.php
* We don't want to load assets when the feature flag is disabled.
* Puts the schema blocks integration behind a feature flag.
* 
* Add a post
* No schema-blocks related assets (js and css) should be loaded
* Enable the feature flag
* Add this `define('YOAST_SEO_SCHEMA_BLOCKS', true);`  somewhere (e.g `wp-config.php`) on your test domain.
* The assets should be loaded
* You can add a recipe to your post.
*
*
Fixes #
> P2-693 Prevent assets from being loaded when feature flag is disabled

- src/config/migration-status.php
- src/initializers/migration-runner.php
- tests/unit/database/migration-runner-test.php
- tests/unit/database/migration-status-test.php
* Allows using the migration runner with other versions than `WPSEO_VERSION`. This is preparation for premium as an addon.
* The Migration_Runner class now accepts an optional `$version` argument to the `run_migrations` function allowing it to be used in addons.
* When installing the plugin on a clean database migrations should be run as they normally are.
* Can also be tested by simply clearing the indexable tables from the test helper plugin.
* Running DB migrations.
> Add custom versions to the migration runner

- js/src/containers/PersistentDismissableAlert.js
- js/src/editor-modules.js
- js/src/initializers/settings-store.js
- js/src/settings.js
* The PersistentDismissableAlert Container wasn't useable on settings pages and not useable in add-ons. This PR adds functionality for this uses.
* Enhances the Dismissible Alert, so that it can be used in more places.
* Exposed the PersistentDismissableAlert Container via Editor Modules
* Introduced a little store to the Settings pages
* Using an optional prop to connect the Persistent Dismissable Alert to another store when needed
* Check that the PersistentDismissableAlert Container still functions like before in the Editor. You can follow the test instructions from [P1-341](https://github.com/Yoast/wordpress-seo/pull/16643) for that.
* Check that there is a Settings …
> P1 332 persistent dismissable alert for addon settings

- src/builders/indexable-link-builder.php
Some of our customers reported that they can't create anymore translations of variable product.
Indeed a fatal error is triggered and breaks the variable product translation creation:
```
[22-Feb-2021 07:52:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_taxonomy() on string in C:\wamp64\www\wordpress-support\wp-content\plugins\woocommerce-5.0.0\includes\admin\meta-boxes\views\html-product-data-attributes.php:40
Stack trace:
#0 C:\wamp64\www\wordpress-support\wp-content\plugins\woocommerce-5.0.0\includes\admin\meta-boxes\class-wc-meta-box-product-data.php(46): include()
#1 C:\wamp64\www\wordpress-support\wp-content\plugins\woocommerce-5.0.0\includes\admin\meta-boxes\views\html-product-data-panel.php(51): WC_Meta_Box_Product_Data::output_tabs()
#2 …
```
> Fix conflict between Yoast Seo and Polylang For WooCommerce

- admin/views/class-yoast-feature-toggles.php
- tests/unit/admin/views/feature-toggles-test.php
* Improved PHP 8.0 compatibility
* Fixes a warning when running the plugin on PHP 8.0
Related to: https://yoast.atlassian.net/browse/QAK-2609
As there appeared to be no tests for the class at all, adding a minimal test function to test the basic functionality, as well as a specific test covering the PHP 8 sorting issue.
The `u*sort()` functions in PHP have always been expected to return an integer: a negative integer for when A should be considered "less than" B, a `0` when they should be considered as equal and positive integer for when B should be considered "more than" A.
The `Yoast_Feature_Toggles::sort_toggles_callback()` did not comply with this and returned a boolean value instead.
As of PHP 8.0, PHP checks more strictly …
> PHP 8: prevent warning in Yoast_Feature_Toggles

- admin/views/class-yoast-integration-toggles.php
- tests/unit/admin/views/integration-toggles-test.php
* Improved PHP 8.0 compatibility
* Fixes a warning when running the plugin on PHP 8.0
Related to: https://yoast.atlassian.net/browse/QAK-2609
As there appeared to be no tests for the class at all, adding a minimal test function testing the basic functionality, as well as a specific test covering the PHP 8 sorting issue.
The `u*sort()` functions in PHP have always been expected to return an integer: a negative integer for when A should be considered "less than" B, a `0` when they should be considered as equal and positive integer for when B should be considered "more than" A.
The `Yoast_Integration_Toggles::sort_toggles_callback()` did not comply with this and returned a boolean value instead.
As of PHP 8.0, PHP checks more …
> PHP 8: prevent warning in Yoast_Integration_Toggles

- composer.json
- src/conditionals/wp-robots-conditional.php
- src/integrations/front-end-integration.php
- src/integrations/front-end/wp-robots-integration.php
- tests/unit/conditionals/wp-robots-conditional-test.php
- tests/unit/integrations/front-end-integration-test.php
- tests/unit/integrations/front-end/wp-robots-integration-test.php
*
* Integrates with `wp_robots` by hooking into it and using our settings there. 
* I decided to filter out the values that aren't relevant when noindex is set. We are doing the same at the moment, but WordPress is adding some values again. This will keep the behaviour the same.
* You can install WordPress 5.7 by installing this plugin https://nl.wordpress.org/plugins/wordpress-beta-tester/
* Make a new a post
* Set robot meta values by using the advanced panel (it's in the metabox).
* Save the post
* View the source of your post and verify that the robots metatag is outside the Yoast SEO metatags block.
* Check if the set values are correctly shown.   …
> Integrate with wp_robots

- src/integrations/third-party/elementor.php
* Our Elementor integration aborted loading because it didn't detect a correct post type. Adjust the load order to give plugins a chance to register custom post types on init.
* Fixes an unreleased bug where CPT would not have our Elementor integration due to a load order problem.
*
* Install and activate Yoast SEO plugin 16.0-RC4 (or later / this branch) in combination with Elementor and Elementor pro Version 3.1.1.
* Install and activate Yoast Test Helper
* Navigate to Tools > Yoast Test > enable Post Types and Taxonomies
* Navigate to Elementor > Settings > General > Tick Books and Movies
* Create a CPT, then click Edit in Elementor
* Notice that Yoast SEO is no longer …
> Delay Elementor load

- js/src/helpers/addCheckToChecklist.js
- js/tests/containers/DocumentSidebar.test.js
- js/tests/containers/PrePublish.test.js
*
* Fixes a bug where no schema analysis was shown when no block schema was generated yet.
* The code now checks specifically for blocks with the `is-yoast-schema-block` attribute, rather than looking at whether or not the `yoast-schema` attribute is defined.
* Reasoning: it is better to be explicit than to deduce it implicitly. 	
* Companion PR of https://github.com/Yoast/wordpress-seo-premium/pull/3196. Please follow its test instructions.
* 
*
Fixes #
> Only show schema validation result when block has an 'is-yoast-schema-block' attribute that is set to 'true'.

- src/actions/indexing/indexable-post-indexation-action.php
- tests/unit/actions/indexing/indexable-post-indexation-action-test.php
* Addresses a slow query  related to posts indexing, details can be found in this ticket https://github.com/Yoast/wordpress-seo/issues/16645
* phpunit tests have been also modified to comply with the new query
* Improves the performance of the post indexing. Props to [Ovidiu Liuta](https://github.com/ovidiul).
* the NOT IN SQL check is not performance and can lead to performance issues for sites with a large number of posts, instead, a LEFT JOIN should be considered as a better alternative
* Install and activate Yoast Test Helper
* Switch to Yoast SEO 16.0
* Reset the indexable tables: Tools -> Yoast Test -> Reset indexables tables & migrations
* Run the indexation, …
> #16645 fixing the posts indexation get_query method by adding a LEFT JOIN

- js/src/elementor/initializers/editor-store.js
* Currently, we disable the mark (eye icon) button on Elementor. This leads to confusion with users. Let's remove the mark button on Elementor.
* Fixes a bug where the analysis highlight button would be visible in our Elementor integration even though we don't support it.
*
* Install & activate
* Yoast SEO 16.1-RC1 (or higher / this branch)
* Elementor 3.1.1 (or higher) (Elementor pro is optional)
* Edit it in Elementor
* Add some text and use a transition word. I used:
```txt
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo. Furthermore, lorem ipsum dolor sit amet, consectetur …
```
> Hide mark buttons in Elementor

- admin/class-admin.php
* Premium has become an addon. When Premium is active, we don't want users to deactivate Free.
* [wordpress-seo-premium] Hides the 'deactivate' button for Yoast SEO on the Plugins page, as long as Yoast SEO Premium is active, because Yoast SEO Premium cannot function properly without Yoast SEO. When Yoast SEO Premium is deactivated, the 'deactivate' button for Yoast SEO will reappear.
*
* Have both Premium and (this branch of) Free installed and activated:
* See no deactivate button for Free, but 'Deactivate Yoast SEO Premium first'.
* Deactivate Premium but keep it installed, have (this branch of) Free still installed and activated.
* See a deactivate button for Free.
* …
> Hide the free deactivate button when premium is active

- inc/class-addon-manager.php
* We want to convert subscriptions, even if no updates are available.
* Fixes an unreleased bug where the auto-update toggle for Yoast SEO Premium was not shown when no update was available.
* 
* Go to the plugins page.
* See that the auto-update toggle for Yoast SEO Premium is available.
* (Even though you are on the latest version and no update for Premium is available) 
*
*
Fixes #
> Still convert subscription when no update is available.

- src/builders/indexable-post-builder.php
- src/helpers/post-helper.php
- src/integrations/watchers/indexable-post-watcher.php
- src/routes/yoast-head-rest-field.php
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/integrations/watchers/indexable-post-watcher-test.php
- tests/unit/routes/yoast-head-rest-field-test.php
⚠️ Take care: travis tests are failing because the tests that touch the changes in this PR have not been changed yet!
* Prevent indexable creation on `auto-draft` posts.
* Prevent link building on drafts
* Prevent indexable creation on the yoast_head route for non-indexable objects.
This PR can be summarized in the following changelog entries:
[Bugfix]
* Fixes a bug where indexable creation caused compatibility problems with code that would hook in to new post creation.
[Enhancement]
* Performance enhancements in the post indexable builder by skipping link creation on drafts.
* Initial creation of a post does not trigger `wp_is_post_revision()` or `wp_is_post_autosave()`, so we needed another method. Posts with status `auto-save` do not merit the resources of an indexable creation.
* If …
> Filter posts with status 'auto-draft' from the post watcher indexable builder

- js/src/initializers/post-scraper.js
- js/src/initializers/term-scraper.js
- js/tests/Pluggable.test.js
* Adapt plugin-side code to changes made in the accompanying [yoastseo PR](https://github.com/Yoast/javascript/pull/1095).
* n/a
* This PR makes sure that the researcher is also passed when an app is constructed in the `post-scraper.js` and `term-scraper.js` legacy code. We don't use this legacy code anymore, since we run the analysis in the web worker, but some integrations might. So we want to keep that code working as long as we haven't properly deprecated it.
* This branch refers to an incorrect issue number, so I added the correct issue number in the PR title. 
* See associated javascript PR.
* …
> LINGO-685 Make researcher argument of assessor

- composer.json
- composer.lock
* 3 days ago, [a new version of psr/container was released](https://github.com/php-fig/container/releases/tag/1.1.1) in which there are changes related to `ContainerInterface` that are incompatible with our code. psr/container was an indirect dependency until this commit. In the Travis build, the `travis_retry composer remove humbug/php-scoper --dev --ignore-platform-reqs` command would update `psr/container` from 1.0.0 to 1.1.1, which would cause the Travis build to fail.
* Set psr/container 1.0.0 as a direct dependency to prevent updating to 1.1.1 (which would cause failing Travis builds).
* N/A
* See a passing Travis build. 
* See no `  - Updating psr/container (1.0.0 …
> Set psr/container 1.0.0 as a direct dependency

- admin/class-yoast-notification-center.php
- src/integrations/watchers/auto-update-watcher.php
- tests/unit/integrations/watchers/auto-update-watcher-test.php
* If the auto update message is serialized then the class will be serialized which causes errors. Instead pass along the string.
* Fixes a fatal error when upgrading from 15.9.1 to 16.0.
* See https://yoast.atlassian.net/browse/QAK-2748
* Upgrading from 15.9.1 to 16.0 while the auto update notification is in the notification center.
Fixes https://yoast.atlassian.net/browse/QAK-2748
> [QAK-2748] Fix auto update notification serialization

- src/models/settings/global-settings-model.php
- src/models/settings/object-settings-model.php
- tests/unit/models/settings/object-settings-model-test.php
* We want an abstract class for global and object specific settings.
* Adds abstract classes for the global and object setting models 
*
* It adds code that isn't implemented yet.
*
*
Fixes [AR-75]
[AR-75]: https://yoast.atlassian.net/browse/AR-75
> AR-74 AR-75 Adds global and object settings model

- admin/class-admin.php
* Makes the network admin plugins overview consistent with the normal plugins overview.
* Adds missing links to the network plugins overview for Yoast SEO.
* Disables the option to network deactivate Yoast SEO while Premium is also active.
* It should not be possible to network deactivate Yoast SEO while Premium is active.
* Note that cases where free is network active while premium is active on only a certain site are not currently supported.
* The plugins network overview
* The normal plugins overview ( this should be unchanged ).
* The settings link in particular has changes to ensure …
> [QAK-2754] Fix network plugin links

- src/integrations/front-end/wp-robots-integration.php
* Correctly sorts the robots tags.
* Makes sure the robots values are sorted in the optimal order when running WordPress 5.7.
* See https://yoast.atlassian.net/browse/QAK-2758
* All robots values but only on WordPress 5.7.
Fixes https://yoast.atlassian.net/browse/QAK-2758
> [QAK-2758] Sort robots

- src/models/settings-model.php
- src/models/settings/object-settings-model.php
- src/repositories/settings-repository.php
- tests/unit/doubles/models/settings-model-double.php
- tests/unit/models/settings-model-test.php
- tests/unit/models/settings/object-settings-model-test.php
- tests/unit/models/settings/open-graph-settings-test.php
- tests/unit/models/settings/search-engine-verify-settings-test.php
- tests/unit/models/settings/social-settings-test.php
- tests/unit/repositories/settings-repository-test.php
* Retrieving, saving and merging all values into our one option through an easy to use interface
* Preparation to allow easy management of the settings values
* The Settings_Repository can be easily extended by add-ons by letting them add additional initializers.
* n/a. code is not yet in use.
*
*
> AR-64 AR-89 Creates Settings_Repository to save all the combined options

- js/src/initializers/admin.js
- js/src/initializers/featured-image.js
- js/src/network-admin.js
- js/src/reindex-links.js
- package.json
- yarn.lock
* Replaces and removes a11y-speak as a dependency
* Replaces and removes a11y-speak as a dependency
*
* Functionally nothing should change, so just do a smoketest for example with VoiceOver on your Mac to see if speak still works the same. Test for example the featured image warning.
* Go to Safari and open a post in the classic editor
* Activate VoiceOver on your Mac with cmd + F5 (your Mac will now read out loud everything you do)
* Set an image smaller than 200x200 pixels as featured image
* Your Mac will now read aloud: "SEO issue: The featured image should be at least 200 by 200 pixels to be picked up by Facebook and other social media sites." …
> Replace a11y-speak with @wordpress/a11y

- admin/class-admin.php
- admin/formatter/class-metabox-formatter.php
- admin/formatter/class-term-metabox-formatter.php
- admin/metabox/class-metabox.php
- js/src/analysis/isContentAnalysisActive.js
- js/src/analysis/isCornerstoneContentActive.js
- js/src/analysis/isKeywordAnalysisActive.js
- js/src/analysis/isSEMrushIntegrationActive.js
- js/src/analysis/isZapierConnected.js
- js/src/analysis/isZapierIntegrationActive.js
* We want to ensure consistency in the JS code base. 
* Uses booleans everywhere instead of 0|1 in localized data.
Localised variables that were changed:
* `'contentAnalysisActive'`
* `'keywordAnalysisActive'`
* `'cornerstoneActive'`
* `'semrushIntegrationActive'`
* `'zapierIntegrationActive'`
* `'zapierConnectedStatus'`
* Go to this branch and build with `composer install && yarn install && grunt build:dev`.
* Create a new post or edit an existing one.
* Make sure all features of the Yoast metabox / sidebar are there.
* Smoke test the metabox / sidebar. 
* Pay special attention to the content analysis, keyword analysis, cornerstone content and SEMrush integration.
QA can …
> AR-69 use boolean values for instead of 0|1 for localized variables

- config/dependency-injection/services.php
- src/validators/search-engine-verify/baidu-verify-validator.php
- src/validators/search-engine-verify/bing-verify-validator.php
- src/validators/search-engine-verify/google-verify-validator.php
- src/validators/search-engine-verify/pinterest-verify-validator.php
- src/validators/search-engine-verify/search-engine-verify-validator.php
- src/validators/search-engine-verify/yandex-verify-validator.php
- src/validators/url-validator.php
- src/validators/validator-interface.php
- src/values/validation-error.php
- tests/unit/validators/search-engine-verify/baidu-verify-validator-test.php
- tests/unit/validators/search-engine-verify/bing-verify-validator-test.php
- tests/unit/validators/search-engine-verify/google-verify-validator-test.php
- tests/unit/validators/search-engine-verify/pinterest-verify-validator-test.php
- tests/unit/validators/search-engine-verify/search-engine-verify-validator-test.php
- tests/unit/validators/search-engine-verify/yandex-verify-validator-test.php
- tests/unit/validators/url-validator-test.php
- tests/unit/values/validation-error-test.php
* Create the Validators that can make sure that instances of the Settings_Model contain valid data
* Validators that can validate the new Settings_Model data to store options.
*
* n/a. this code is not yet used anywhere.
*
*
> AR-77 AR-78 AR-91 Create validators to validate the settings

- src/helpers/language-helper.php
- tests/unit/helpers/language-helper-test.php
* Let Free users see an upsell notification that promotes Premium word form recognition. Reduce the limit of prominent words that are saved so that it matches the limit of other languages with function word support (languages with no function words get a higher limit to increase the chances of content words showing up in the prominent words).
* Activate word form recognition upsell banner for Czech users, and reduce the maximum number of prominent words that are saved for Czech users to match that of other languages with function word support.
*
* Set the language of your website to Czech.
* Check that you are seeing a morphology upsell. (See [this …
> Add Czech to languages with morphology and function words

- tests/unit/actions/indexing/post-link-indexing-action-test.php
* Quick follow up to https://github.com/Yoast/wordpress-seo/commit/248a7fcedd5061ffe28e40b161550be4c6e40b92 to add 
a missing quote to the indexing queries used in the tests. See https://github.com/Yoast/wordpress-seo/pull/16764 
* Fixes failing tests due to missing quote in sql statements.
*
* See the tests pass.
*
*
Fixes #
> Add missing quote to indexing queries in the tests.

- src/integrations/front-end-integration.php
- src/integrations/front-end/wp-robots-integration.php
- tests/unit/integrations/front-end/wp-robots-integration-test.php
* We reset the global Query before running wpseo_head, however with WordPress 5.7 the indexable is fetched before that in the `wp_robots` filter. This ensures the query is also reset before fetching the indexable.
* Fixes an issue where usage of WP_Query without properly resetting globals could lead to incorrect SEO data.
* Add an action to `template_redirect` in which you construct a new `WP_Query` and call `the_post` on it. ie:
```php
function do_something_with_query() {
global $wp_query;
if ( $wp_query->post->ID === 2 ) {
$need_some_data = new WP_Query( ['page_id' => 1] );
$data_from_the_post = $need_some_data->the_post();
}
}
add_action( 'template_redirect', …
```
> Ensure the query is reset before fetching the indexable

- css/src/metabox.css
- js/src/components/PostPublish.js
* Improve the accessibility for the social sharing links in the post publish panel
* Improves accessibility for the social sharing links in the post publish panel
* I decided not to use `makeOutboundLink` from `@yoast/helpers`, because it did not allow the the `rel` attribute to be configured as it was.
* I used flexbox to implement the design of the link, which could need extra support for IE11 but falls back to an acceptable layout with the text next to the icon: 
* Checkout this branch and build accordingly (`$ composer install; yarn; grunt build`).
* Add a new post with a title and publish it
* On the post publish confirmation panel, check the Facebook and Twitter …
> P3-387 Improve social links accessibility in the post publish panel

- inc/options/class-wpseo-option-titles.php
* We want to avoid a PHP notice while saving the organization / person settings and have properly saved options.
* Fixes a PHP notice while saving the Organization or Person name and logo.
*
**Note:**  right now there's an sql error that originates from current trunk and may be printed out on some pages. It's unrelated to this PR. It's tracked [on another Jira issue](https://yoast.atlassian.net/browse/P3-445), so please ignore it while testing this PR>
- First, test on latest trunk. 
- Disable all plugins, including Query Monitor.
- Keep only Yoast SEO activated.
- Go to SEO > Search appearance.
- Set "Choose whether the site represents an organization or a person" to …
> P3-443 Fix saving of company and person logo meta options.

- src/actions/indexing/post-link-indexing-action.php
- src/actions/indexing/term-link-indexing-action.php
- tests/unit/actions/indexing/post-link-indexing-action-test.php
- tests/unit/actions/indexing/term-link-indexing-action-test.php
* The reindexing action for post links should not throw exceptions from SQL queries.
* Fixes a bug where reindexing the post links would not succeed.
* I've prefixed all other fields in the query as well to prevent future issues from arising in case any of the other tables being joined change.
* Build the environment (`$ composer; yarn; grunt install`)
* Make sure not to have any plugin activated like Debug Bar or Query Monitor
* Go to any of the Yoast SEO admin pages
* Verify that no Database error is reported at the top of the screen
* Now go to SEO > Tools and click "Start SEO data optimization" button
* Verify that the success message is shown …
> P3-445 Resolved ambiguous fields in SQL query

- admin/class-admin.php
* Support emails indicate that some people interpret 'Deactivate Yoast SEO Premium first' as us telling them to deactivate plugins, instead of explaining the reason why the `Deactive` link is hidden.
* Changes the deactivation prevention text on the Plugins page from 'Deactivate Yoast SEO Premium first' to 'Required by Yoast SEO Premium' to avoid confusion.
*
*
*
*
Fixes #
> Change deactivation prevention text

- composer.json
- inc/class-addon-manager.php
- src/integrations/watchers/addon-update-watcher.php
- tests/unit/integrations/watchers/addon-update-watcher-test.php
*
* Enables/disables auto-updates for the `ACF Content Analysis for Yoast SEO` plugin when auto-updates for Yoast SEO are enabled/disabled.
* The [issue](https://yoast.atlassian.net/browse/P2-744) said that "the `update_supported` setting of the ACF plugin is never set to true" in `class-addon-manager`. But this is not the right solution, because the `class-addon-manager` revolves around our paid add-ons that have a subscription, this is not the case for ACF for Yoast. 
* I will now explain in some more detail why we don't have to set `update_supported` for ACF for Yoast.
* The `class-addon-manager` uses the filter `_site_transient_update_plugins` to add plugin information to the `_site_transient_update_plugins` option.
* …
> Bring auto-updates for Yoast ACF Analysis in sync with Yoast SEO

- admin/class-admin-asset-manager.php
*
* Fixes the problem that the analysis didn't work for unsupported languages.
* When registering available language scripts, we only used the list of supported languages. But we also need to register the default language script.
*
* Set your environment to an unsupported langauge, e.g. Afrikaans.
* Open a post and confirm that the analysis loads.
*
Fixes https://yoast.atlassian.net/browse/LINGO-738
> Fix analysis not working with default languages

- admin/tracking/class-tracking-default-data.php
*
* Adds gmt_offset and timezone_string to tracking data
*
* In `class-tracking.php`, add `return true;` at the top of `should_send_tracking` (line 145).
* In `class-collector.php`, add `var_dump( $data );` before the return statement in `collect` (line 40). 
* Visit Settings > General, and see `gmt_offset` and `timezoneString` in the tracking data:
* `gmt_offset` contains a numeral offset.
* `timezoneString` contains the name of the time zone. NB: when an numerical offset (like `UTC-12`) is selected, the value of this will be an empty string. If a location (like `Amsterdam`) is selected, it will contain the name of the timezone. 
* NB: You might need to remove the …
> Add gmt_offset and timezoneString to tracking data

- src/generators/schema/breadcrumb.php
- tests/unit/generators/schema/breadcrumb-test.php
⚠️ Tests still need fixing, as this changes some logic and the tests were annoying to fix :) ⚠️ 
* Correctly reference the current webpage in breadcrumb schema output.
* See that the last bit of the breadcrumbs schema output is always a reference to the `#webpage` by `@id`.
*
*
Fixes PRODUCT-208
> Correctly reference the current webpage in breadcrumb schema

- inc/class-wpseo-utils.php
Allow overriding of if the Yoast SEO metabox should show on a post type.
Useful when you need Yoast functionality on non-public post types.
I wrote this code so that in collaboration with the existing `wpseo_accessible_post_types` filter I can have the "Primary Category" functionality work on a non-public post type (I am using it with Sensei Question post type). 
* Adds a filter that allows for showing the Yoast SEO metabox on non-public post types if these are accessible. Props to [jondcampbell](https://github.com/jondcampbell).
*
* Add a new filter using `wpseo_display_metabox_{post_type}` that returns true or false to show or hide the box. …
> Add filter for display_post_type_metabox

- src/helpers/url-helper.php
* Make sure that there are no errors when saving a post with protocol agnostic URLs.
* Fixes a bug where saving posts with URLs without protocol would fail or trigger warnings.
* 
I could only get this to fail hard in the classic editor, but there are cases where it could fail in the block editor as well.
You should deactivate Query Monitor if active, that hides the warnings.
1. Create new post
2. Fill the title and content
3. Add any image and delete protocol from its URL (this can be done by switching to the code editor instead of the visual one).
4. Save the post. With this fix, no errors should appear. …
> Check for key existence before comparing it.

- src/helpers/site-helper.php
- src/integrations/watchers/auto-update-watcher.php
- src/presenters/admin/auto-update-notification-presenter.php
- tests/unit/helpers/site-helper-test.php
- tests/unit/integrations/watchers/auto-update-watcher-test.php
- tests/unit/presenters/admin/auto-update-notification-presenter-test.php
* Sites in an network don't have the ability to enable/disable auto updates. This has to be done on network admin level.
* Changes the message in the notification for sites in a network to tell them to contact there network admin to enable automatic updates for Yoast SEO. 
* It added unit tests for `Site_Helper::test_is_multisite_and_switched` because I implemented a method there that I removed later because it felt useless to have a wrapper method for `is_multisite`. Because I added also a test for the existing method I decided to keep this test.
* Have auto updates for WordPress enabled
* Have the auto updates for Yoast SEO disabled
* Visit the admin of a site in your …
> Show auto update notification on multisite subsites

- config/webpack/externals.js
- js/src/externals/analysis.js
- package.json
* Within the separate language bundles, there are duplicate files `buffer` and `htmlparser2/lib` which contribute to the large zip size. This can be fixed by changing the files to externals.
* Changes `buffer` and `htmlparser2/lib` to externals.
*
* Check out the `language-split-2` branch in javascript and link the wordpress-seo branch to the monorepo.
* Run `BUNDLE_ANALYZER=true grunt build:dev`
* This should open files in the browser, the last of these files should show the language bundles.
* Make sure that you do not see `buffer` and `htmlParser2` in the language bundles.
* Build the plugin, open the post editor, and make sure there are no (new) console errors.
QA can …
> Add buffer and htmlparser as externals

- composer.json
- inc/class-upgrade.php
- src/integrations/watchers/addon-update-watcher.php
- src/presenters/admin/auto-update-notification-presenter.php
- tests/unit/integrations/watchers/addon-update-watcher-test.php
- tests/unit/presenters/admin/auto-update-notification-presenter-test.php
* On multisite, when enabling auto-updates for Yoast SEO the auto-updates were not automatically enabled for the add-ons (as it works on single site).
* Fixes a bug where, on a multisite installation, enabling/disabling auto-updates for Yoast SEO would not automatically enable/disable auto-updates for Yoast SEO Premium and the other Yoast add-ons.
*
**Preparations**
* Make sure that your site has (at least one of) the following Yoast add-ons:
* Video SEO.
* News SEO.
* WooCommerce SEO.
* Install the ACF add-on through WordPress (in other words, using a released zip, not a GitHub clone).
* Add `'acf-content-analysis-for-yoast-seo/yoast-acf-analysis.php'` to the array of …
> Make the addon-update-watcher work for multisite

- js/src/containers/SnippetEditor.js
- js/tests/containers/SnippetEditor.test.js
* Thank you automated tests 🎉 
* Fixes an unreleased bug where editing the slug in the snippet editor would no longer work in the block editor.
*
* Create a new post using the block editor
* Add a title like `test-slug`
* Publish the post
* View the post and verify the slug is what you expected: `test-slug`
* Edit the slug in the Google preview: `test-slug123`
* Update the post
* View the post and verify the slug changed to `test-slug123`
*
* You could verify the slug changing still works in the classic and elementor editors. They have …
> Fix slug changing in block editor

- js/src/elementor/initializers/editor-store.js
* Needed for https://github.com/Yoast/wpseo-video/pull/876
* Implements the recently added control for dismissible alerts to our Elementor store, from which it was accidentally omitted.
* N/A
* Test with these Video PR https://github.com/Yoast/wpseo-video/pull/876 test instructions, on the correct branch.
* Make sure there are no errors in the Elementor store.
* On a fresh install or a new user, dismiss the Alert in the Video section in Elementor. Reload the page. The alert should not reappear. This should only work after https://github.com/Yoast/wpseo-video/pull/876 has been merged and released. …
> Add DismissAlert control to Elementor store

- admin/menu/class-replacevar-editor.php
- js/src/components/SettingsReplacementVariableEditor.js
- js/src/components/SettingsReplacementVariableEditors.js
- js/src/components/portals/SettingsEditorPortal.js
* Adds the possibility to pass along custom labels for the SEO title field label, Meta description field label and the Meta description field placeholder text.
* Adds the possibility to pass along custom labels for the SEO title field label, Meta description field label and the Meta description field placeholder text.
*
* In case https://github.com/Yoast/javascript/pull/1114 hasn't been merged yet, ensure your local version of the JavaScript monorepo uses the branch from that PR.
* Run `composer install`, followed by `yarn link-monorepo` and `grunt build`.
* Navigate to SEO -> Search Appearance -> Content Types.
* See that nothing has changed in the forms and the usual …
> Adapt settings replacement form to support custom field labels and placeholder

- admin/tracking/class-tracking-settings-data.php
- inc/options/class-wpseo-option-wpseo.php
* Fixes a bug where the metabox insights and linking suggestions options from Premium would reset after Premium and Free were deactivated and reactivated again. 
* Fixes a bug where the metabox insights and linking suggestions options from Premium would reset after Premium and Free were deactivated and reactivated again. 
* Opted to also include these option in the tracking class, as this seems to be commonplace for most options.
* Checkout this branch and build accordingly (`composer install`, `yarn`, `grunt build`)
* Use your preferred database software and inspect the `wpseo` entry in the `wp_options` table.
* See that `enable_metabox_insights` and …
> Moved options regarding enabling of metabox insights and linking suggestions

- src/conditionals/admin/doing-post-quick-edit-save-conditional.php
- tests/unit/conditionals/admin/doing-post-quick-edit-save-conditional-test.php
* The Media Library (inserting an image into a post by browsing the available attachments) is currently broken. `git bisect` helped revealt that the problem was the implied `die()` raised by a call to `check_admin_referer()` introduced by [this commit](https://github.com/Yoast/wordpress-seo/commit/3b971b2edd012b856451ccb6cd08709f6f9b0b3c)
* Fixes a bug where inserting an image from the Media Library was broken.
* 
* Edit a post
* insert an image block and click on the "Media Library" button
* see that the popup is populated with the thumbnails
* check that you don't get any `403` error as a response to a call to `admin-ajax.php` …
> P2-797 Avoid `check_admin_referer` to die

- src/integrations/schema-blocks.php
- tests/unit/integrations/schema-blocks-test.php
* We want to show a warning message with a link that navigates the user to additional info about required en recommended blocks.
* Exposes two shortlinks by using localize script
*
* Test this against https://github.com/Yoast/javascript/pull/1117
*
*
P2-690
> P2 690 expose shortlinks

- src/schema-templates/recipe.block.php
* Move the recipe schema block to the correct category in the blocks overview.
* Fixes a bug where the Recipe schema block turns up under the `text` blocks category in the blocks overview, instead of the Yoast SEO blocks.
*
* Make sure the `YOAST_SEO_SCHEMA_BLOCKS` feature flag is active.
* Click the `Add block` (+) in the top left of the editor.
* See that the Recipe block is under the `Yoast Structured Data Blocks` category, instead of the `Text` category.
*
*
Fixes #
> Moved recipe block to Yoast category instead of default

- src/conditionals/admin/doing-post-quick-edit-save-conditional.php
- tests/unit/conditionals/admin/doing-post-quick-edit-save-conditional-test.php
* When the nonce is valid we shouldn't early return from the method.
* Fixes a bug where a valid nonce causes the logic to stop further execution. 
*
Please keep in mind that this fixes https://github.com/Yoast/wordpress-seo/pull/16820 which was a fix one https://github.com/Yoast/wordpress-seo/pull/16817
* Create 2 categories for posts
* Create a post and assign it to category A
* Set the breadcrumbs of Yoast to use categories.
* Check the breadcrumbs of the created post (either in schema or HTML) and note the category
*. Go to the posts overview and use "quick-edit" on the created post. Set the category to B and update.
*. Check the breadcrumbs of the post again, the …
> Prevent valid nonce to stop further execution of code

- wp-seo-main.php
* Fixes an issue where rewrite rules would not always be flushed on plugin activation.
* See https://yoast.atlassian.net/browse/QAK-2823
* Plugin activation.
Fixes https://yoast.atlassian.net/browse/QAK-2823
> [P3-470] Always flush rewrite rules on activation

- js/src/initializers/search-appearance.js
* After #16807 allows dynamic fields to be added, this allows an unlimited number of instances of the `ImageSelectPortal` to be added to the search appearance admin pages. This is just a preparation for subsequent changes that will combine both features (the hooks + the image select portal).
* Adds support for dynamically added image select portals to the search appearance admin pages.
* There's no direct dependency on #16807, but the new hooks added there allow for the addition of new `ImageSelectPortal` instances
* Checkout this PR together with #16807, build the plugin (`$ composer install; yarn; grunt build`)
* Add a callback for one of the hooks introduced in #16807 …
> P3-380 Allow dynamic ImageSelectPortal on the Search Appearance pages

- src/generators/twitter-image-generator.php
- src/values/images.php
* After merging [https://github.com/Yoast/wordpress-seo/pull/16644](this community patch) a set `og:image` for a specific post was always replaced by the default fallback. That needed fixing.
* Also above PR changed the OG Twitter image to the Facebook (fallback) image, which wasn't in line with the Twitter Tags Functional specifcation. So we decided to fix that as well.
* Fixes an unreleased bug in which the `og:image` tags for Facebook and Twitter didn't reflect the correct images.
* Decided to revive the old somewhat less performant functionality for Twitter, since the new functionality was faulty.
* Set a default image on the Facebook Settings Admin page
* Create a …
> P1 464 og image fix

- admin/class-yoast-form.php
- css/src/yst_plugin_tools.css
* We want an input field with extra content to the right of the label to match the design for the Global social templates.
* Adds a new method to generate an input field with the new styling and help link.
*
* build 
* use the new method somewhere, for example in `admin/views/tabs/metas/paper-content/author-archive-settings.php`
* add `use Yoast\WP\SEO\Presenters\Admin\Help_Link_Presenter;` at the top of the file, after the file block comment
* add the following snippet fo code after `$editor->render();`
```
$breadcrumbs_title_help_link = new Help_Link_Presenter(
WPSEO_Shortlinker::get( 'https://yoa.st/4cf' ),
__( 'Learn more about the breadcrumbs title', 'wordpress-seo' …
```
> P3-501 Add new yost form method and related CSS.

- admin/class-primary-term-admin.php
For sites that have a lot of terms, there is a slowdown happening at the `map_taxonomies_for_js()` level since `update_term_meta_cache` is set to `true` by default and we are grabbing all fields which calls `update_term_cache()`. Since we are just grabbing the terms and using the ID and name for return, we don't need to prime the term meta caches each time.  We can avoid all of that by only requesting for the `id=>name` fields in the term query and setting `update_term_meta_cache` to false: https://developer.wordpress.org/reference/classes/wp_term_query/get_terms/.
* Skip priming term cache when map_taxonomies_for_js is called
> map_taxonomies_for_js() - speed up get_terms call by avoiding priming term meta caches

- src/schema-templates/recipe-name.block.php
- src/schema-templates/recipe-name.schema.php
- src/schema-templates/recipe.block.php
- src/schema-templates/recipe.schema.php
- tests/unit/dependency-injection/schema-templates-loader-test.php
* Add a recipe name block and accompanying schema template for the recipe block.
* Adds the recipe-name block to the recipe block.
* Also did some refactoring so the implementation of the recipe block lines up with the implementation of the jobs-posting block in premium.
* Add a recipe block
* Give the post a title, give the recipe a name, image, at least one step and at least one ingredient.
* Save the post
* On the front-end inspect the schema output and make sure the recipe schema is present and the name property is the same as the value you filled in as your recipe's name.
* …
> P2-224 Add recipe name block and schema templates

- src/builders/indexable-post-builder.php
- src/helpers/post-type-helper.php
- src/integrations/watchers/indexable-ancestor-watcher.php
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
* 
* Fixes a bug where a fatal error would be thrown when creating a new Elementor template or editing an existing one.
*
* Create a new Elementor template.
* No fatal PHP error should be shown.
*
*
Fixes https://yoast.atlassian.net/browse/QAK-2844
> Excluded post types are now not build anymore in the build_post_hierarchy method.

- admin/class-admin-asset-manager.php
- admin/class-admin-asset-seo-location.php
* Preserves backwards compatibility for the asset location class by adding a new optional constructor argument.
* See https://yoast.atlassian.net/browse/LINGO-770
* Asset loading. A quick test on our most important pages to scan for 404s on assets should be enough.
Fixes https://yoast.atlassian.net/browse/LINGO-770
> Asset location backward compatibility

- src/config/researcher-languages.php
- src/helpers/language-helper.php
- tests/unit/helpers/language-helper-test.php
* [wordpress-seo] Adds Czech to the supported languages list.
*
* This PR can be acceptance tested by following these steps:
Test a post in Czech in following environment:
- A normal post
- Taxonomy page
Steps to test:
- Confirm that the SEO and readability analysis load
- Set a keyphrase, add it to the text and see that it's recognized
- Change some readability metrics (e.g., add transition words) and confirm that the analysis updates accordingly
- Check that you are seeing a morphology upsell. (See [this PR](https://github.com/Yoast/wordpress-seo/pull/15322) for what the upsell looks like).
* …
> Add Czech to language lists

- src/conditionals/news-conditional.php
- src/integrations/admin/fix-news-dependencies-integration.php
*
* Fixes a News dependency issue that was causing an error with the Classic editor in News SEO.
*
* Install and activate Classic editor.
* Go to create new post in Classic editor.
* Make sure there are no console errors.
*
Fixes https://yoast.atlassian.net/browse/LINGO-771
> Fix news dependencies

- src/integrations/front-end/wp-robots-integration.php
* Allow for other plugins to override the core robots meta tag after Yoast.
* [non-user-facing] Lower the priority of the `wp_robots` hook so that other plugins can hook in after us.
* N/A
* Have a post on your website that is allowing indexing.
* Add the following filter to a functions.php:
```php
add_filter( 'wp_robots', 'override_yoast', PHP_INT_MAX );
function override_yoast( ){
return [ 'noindex' => true, 'nofollow' => true ];
}
```
* Without this PR: 
* the content in `<meta name='robots' content='{{}}' />` will either not change or conflict with itself.
* With this PR: 
* the content in `<meta name='robots' content='{{}}' />` will always be `noindex, nofollow`. …
> Allow lower priority hooks to wp_robots

- admin/views/tabs/metas/paper-content/post-type-content.php
- admin/views/tabs/metas/paper-content/taxonomy-content.php
* We need to revert in Free 16.2 the hook renaming that was done by  #16807 because there won't be a matching Premium release and a deprecation warning will be displayed to users.
* Reverts the changes in `post-type-content.php` and `taxonomy-content.php` introduced by #16807
* While #16807 introduced hooks in other files, we need just to revert the renaming so only the `post-type-content.php`  and  `taxonomy-content.php` file are touched by this PR.
* the hook formerly known as `wpseo_admin_page_meta_taxonomies` isn't used by our code at all so it can't be tested. It was decided to revert the renaming as well so both deprecation go live in 16.3 which is more consistent 
. …
> P3-522 Revert renaming of `wpseo_admin_page_meta_post_types` hook

- inc/class-wpseo-replacement-variable.php
- inc/options/class-wpseo-option-wpseo.php
- inc/options/class-wpseo-option.php
- lib/migrations/column.php
- lib/migrations/migration.php
- lib/migrations/table.php
* Since constructors do not explicitly return anything, a CS error was thrown for six constructors which included an `@return` statement in their documentation.
* I removed these return statements to fix Travis, which was failing on this (although locally the tests didn't fail).
* Removes `@return` statements from the documentation of some constructors, since they do not return anything.
*
* No test is needed, since this change only concerns documentation.
*
*
Fixes #
> Remove return documentation from constructors

- config/grunt/task-config/copy.js
* We are shipping the `css/src` directory but we don't use these files.
* Fixes a bug where we accidentally ship the `css/src` directory.
* Situation before:
* Situation after:
* Run `grunt artifact` in the terminal
* Open the artifact folder and see that there is no `css/src` directory anymore
Some sanity checks:
* You can unpack the artifact.zip file to verify the same, but that is just the compressed `artifact` folder.
* You can also install the zipfile to check if the styling is still loaded the right way.
*
* 
Fixes …
> Prevent the css/src folder from being shipped

- admin/views/tabs/metas/paper-content/author-archive-settings.php
- admin/views/tabs/metas/paper-content/date-archives-settings.php
- admin/views/tabs/metas/paper-content/post-type-content.php
- admin/views/tabs/metas/paper-content/post_type/post-type.php
- admin/views/tabs/metas/paper-content/taxonomy-content.php
* The changes in the hooks by #16807 are not enough to add the new social templates fields for post type archives
* We also want to have distinct sections in distinct container to apply the expected spacing, and move all the toggles in the Taxonomies collapsibles to the top.
* Deprecates the `wpseo_admin_page_meta_post_types` hook in favor of a new hook `Yoast\WP\SEO\admin_post_types_beforearchive`.
* Deprecates the `wpseo_admin_page_meta_taxonomies` hook in favor of a new jook `Yoast\WP\SEO\admin_taxonomies_meta`.
* Introduces a new `Yoast\WP\SEO\admin_post_types_beforearchive` hook.
* Adds a new hook `Yoast\WP\SEO\admin_post_types_archive` at the end of the archive section of the custom post types in Search Appearance.
* …
> P3-507 Add hook inside the post type archive section of the Search appearance

- Gruntfile.js
- admin/class-admin-asset-yoast-components-l10n.php
- config/grunt/custom-tasks/i18n-clean-json.js
- config/grunt/task-config/clean.js
- config/grunt/task-config/convert-pot-to-wp.js
- config/grunt/task-config/copy.js
- config/grunt/task-config/makepot.js
- config/grunt/task-config/po2json.js
- config/grunt/task-config/shell.js
- js/src/schema-blocks.js
- src/integrations/schema-blocks.php
* The setup wasn't completed the right way. This pull makes sure that the right translations are loaded.
* Fixes a bug where the schema-blocks translations aren't loaded well.
* In short how it works:
* The potfile builder will look to all the strings with the text domain `yoast-schema-package`
* All these strings are extracted and put in the `yoast-schema-blocks.php` file. Here it will get the `wordpress-seo` text domain. This allows translators to translate the strings in `translate.wordpress.org`
* The next step is to get all translated values and put them in separate `yoast-schema-blocks-{language}.json` files for each language. 
* All strings not present in the main file `yoast-schema-blocks.json` will be filtered out of the …
> Make sure translations for the schema-blocks are working

- config/grunt/custom-tasks/github-pre-release.js
* QA wants the complete changelog when it's RC1, not just the changes to the last beta.
* Prompts the dev to enter the full QA changelog for RC1 rather than just the changes to the last beta.
* Fixes a bug where the QA changelog did not contain the correct initial content.
* I think the code for `beta1` also contained a bug, which I fixed here. 
* If the version number is "16.1-beta1", the old code `pluginVersion.substr( pluginVersion.length - 3 )` would yield `ta1`, and would therefore never match to `beta1`. 
* When you inspect the 16.1-beta1 [on GitHub releases](https://github.com/Yoast/wordpress-seo/releases/tag/16.1-beta1), it says "Changes compared to 16.0", which suggests the conditional wasn't entered at that time (while …
> For RC1, as well as for beta1, ask the user to enter the full QA changelog

- src/wrappers/wp-remote-handler.php
* Removes call to `$raw_response->get_error_code()` in the `WP_Remote_Handler` class as `Exception` expects an integer, but would sometimes receive a string instead.
* Removes call to `$raw_response->get_error_code()` in the `WP_Remote_Handler` class as `Exception` expects an integer, but would sometimes receive a string instead.
*
* Ensure you've correctly built this branch (`composer install`, `yarn`, `grunt build`).
* Create a new post and add a keyphrase.
* Click the 'Get related keyphrases' button and see the Semrush window pop up.
* Log in with your account, if prompted to do so.
* Add the following line to the hosts file (can be found as `/etc/hosts` and make sure …
> Removed call to error code in remote handler class as we can't be sure it's an integer

- admin/class-primary-term-admin.php
- src/integrations/watchers/primary-term-watcher.php
- tests/unit/integrations/watchers/primary-term-watcher-test.php
* We want to save the primary term the right way.
* Fixes a bug where the primary term isn't saved at the right moment resulting in having an unexpected term for the breadcrumbs.
* I used `\PHP_INT_MAX - 1000` and `\PHP_INT_MAX - 500` to make sure the sequence of executing the hooks is right. We want to do the hook in `WPSEO_Primary_Term_Admin` and then Yoast\WP\SEO\Integrations\Watchers\Primary_Term_Watcher and afterwards the one implemented in #16817
* Create a post and select a category. For example: Cat A
* Save the post and see that Cat A is in the breadcrumbs
* Now choose Cat B and deselect Cat A and save.
* Cat B is now the one reflected in the breadcrumbs
* Select …
> P2 857 Save primary term right

- inc/class-upgrade.php
- src/integrations/watchers/addon-update-watcher.php
- tests/unit/integrations/watchers/addon-update-watcher-test.php
* The `update_site_option_auto_update_plugins` hook would not fire if the `auto_update_plugins` option did not yet exist. This would be the case when a user would have never enabled auto-updates for a plugin before.
* In this case, where Yoast SEO would be a user's first ever plugin for which auto-updates were enabled, all the add-ons would not be added to the list of plugins to auto-update.
* Fixes a bug where our add-ons would not automatically be updated if Yoast SEO was the first plugin for which the user ever enabled auto-updates.
* I added the `add_site_option_auto_update_plugins` hook, which fires when an option is created for the first time.
* I wrote an upgrade routine to fix the situation where users only have working …
> Handle the situation where the auto_update_plugins option did not previously exist

- admin/views/tabs/metas/paper-content/author-archive-settings.php
- admin/views/tabs/metas/paper-content/date-archives-settings.php
- admin/views/tabs/metas/paper-content/post-type-content.php
- admin/views/tabs/metas/paper-content/taxonomy-content.php
- admin/views/tabs/metas/post-types.php
- css/src/yst_plugin_tools.css
* We want to avoid to introduce in trunk some extra vertical spacing displayed in the settings pages, between titles and settings. These changes were introduced as part of the preparation for the Global Social Templates feature. See https://github.com/Yoast/wordpress-seo/pull/16858 and https://github.com/Yoast/wordpress-seo/pull/16872. At the same time, we want to introduce some spacing between sections of settings, in preparation for the Global Social Templates.
* Improves spacing between settings sections.
*
* install and activate Yoast SEO (switched to this branch and built)
* make sure you don't have the `YOAST_SEO_SOCIAL_TEMPLATES` feature flag enabled
* on a …
> Fix additional space between setting titles and settings.

- admin/class-admin-gutenberg-compatibility-notification.php
- tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
- tests/unit/doubles/admin/admin-gutenberg-compatibility-notification-double.php
- tests/unit/doubles/admin/class-admin-gutenberg-compatibility-notification-double.php
A notification is displayed on the Yoast dashboard when an incompatible version of the Gutenberg plugin is installed. In some environments, such as multisites, the user can not update the Gutenberg plugin. It would be nice to allow the Gutenberg compatibility notification to be disabled in these types of environments.
* Adds a filter that allows the Gutenberg compatibility notification to be disabled.
* Note that I changed the visibility of two properties and a method in the `WPSEO_Admin_Gutenberg_Compatibility_Notification` class from 'private' to 'protected'. I made these changes to accommodate unit testing. Please carefully evaluate whether these changes are acceptable or if a different approach should be used.
1. Install and …
> Add a filter which allows the Gutenberg compatibility notification to be disabled

- packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
- packages/yoastseo/src/languageProcessing/index.js
- packages/yoastseo/src/worker/AnalysisWebWorker.js
*
* Removes the codes for reassigning `yoast.analysis` with a new value in `AnalysisWebWorker`, and adds `stripHTMLTags` helper in `languageProcessing/index.js` file.
*
* Make sure that woo specific assessment (the short description assessment) is loaded and there is no error in the console
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-772
> Fix woo assessment error

- admin/views/class-yoast-integration-toggles.php
- js/src/components/modals/SEMrushKeyphrasesTable.js
- js/src/components/modals/SEMrushLimitReached.js
- js/src/components/modals/SEMrushLoading.js
- tests/unit/admin/views/integration-toggles-test.php
* SEMrush changed the spelling of their name to Semrush
* Replace all occurrences of 'SEMrush' by 'Semrush' to reflect Semrush's spelling change.
* I only changed the userfacing occurrences to prevent possible bugs caused by incomplete replacements in function, action, namespace and class names.
Check the spelling of 'Semrush' in the following places (but please think if you can think of more places!): 
* Yoast SEO > General > Integrations (also click the question mark behind the heading)
* In the post editor:
* Enter a focus keyphrase, click the 'get related keyphrases' button, scroll down in the modal. See 'Get more insights at Semrush'. 
* Enter a new focus keyphrase, …
> Replace SEMrush by Semrush in user-facing strings

- src/schema-templates/ingredients.block.php
- src/schema-templates/recipe-name.block.php
- src/schema-templates/steps.block.php
The name of the instruction has changed## Context
*
* Changes the way the heading level is chosen for headings inside of the recipe block. You can now change the heading level using the block's block controls instead of using a select element in the block's sidebar.
*
* Companion PR of https://github.com/Yoast/wordpress-seo-premium/pull/3288, please follow its test instructions instead.
* **Note**: these steps should only be followed once in Premium. Do not test this in Free.
*
*
Fixes #
> Rename variable-tag-rich-text to heading

- .travis.yml
- composer.json
- composer.lock
* Improve stability of CI runs
* Improve stability of CI runs
As discussed in Slack this updates the Travis script to run the CS check in its own workflow.
Includes minor other tweaks and clean up.
For the record: this was the PHPCS PR which caused the difference in reported issues: https://github.com/squizlabs/PHP_CodeSniffer/pull/2925
.. to get rid of the `The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies.` warning.
Remove ENV variable declaration and conditions which are no longer necessary since the Premium plugin has been split off and now has its own script.
... with its own simplified build steps.
* …
> Travis: run CS in separate workflow & other minor tweaks

- src/integrations/schema-blocks.php
- tests/unit/integrations/schema-blocks-test.php
* We need to enable the schema blocks feature for upcoming WordPress SEO Premium functionality to work.
* Enables the Schema blocks feature feature for upcoming WordPress SEO Premium functionality to work.
*
* Companion PR of https://github.com/Yoast/wordpress-seo-premium/pull/3283.
* You only have to test this once in WordPress SEO Premium!  
* Use the steps as described in that PR. 
* **Note**: This PR may impact some functionality in Free. See the _Impact check_ below.
* 
* Please test whether the recipe block is still behind the Schema …
> P2-818 Removed Schema blocks feature flag conditional from Schema blocks integration.

- src/integrations/front-end-integration.php
- tests/unit/integrations/front-end-integration-test.php
* [This commit](https://github.com/Yoast/wordpress-seo/commit/11693de48bfd95ab13746ed3f807d1d1dcf4b713) broke a unit test on the 16.2 release branch.
* This PR fixes that.
* Loads the Request helper through dependency injection rather than using the Helpers surface.
*
* Follow the steps to reproduce in https://yoast.atlassian.net/browse/P2-893.
* Using this branch / an RC which contains this code, see the problem is fixed.
*
*
Fixes #
> P2-896 Load the Request helper through dependency injection

- admin/capabilities/class-capability-manager-factory.php
* We want to fix the creation _and removal_ of the Premium-specific capabilities.
* Improves the creation and deletion of Yoast SEO user capabilities.
* Adds a parameter to the `WPSEO_Capability_Manager_Factory::get` method so that Free and Premium can have separate instances of the class and thus add/remove their own capabilities independently.
* Please refer to the test instructions on the companion Premium PR https://github.com/Yoast/wordpress-seo-premium/pull/3293
* This PR doesn't impact Free features.
*
*
Fixes [P3-552]
> Allow Free and Premium to use separate instances of the Capability Manager

- Gruntfile.js
- config/grunt/custom-tasks/i18n-clean-json.js
- config/grunt/task-config/clean.js
- config/grunt/task-config/convert-pot-to-wp.js
- config/grunt/task-config/copy.js
- config/grunt/task-config/makepot.js
- config/grunt/task-config/po2json.js
* All the translation configurations for the `schema-blocks` package were removed from the `release/16.2` branch in https://github.com/Yoast/wordpress-seo/pull/16928, because we needed a quick solution to bring the zip size down (the Job Posting block will not yet be released in 16.2).
* There was already more configuration present in `trunk`, but this wasn't removed in https://github.com/Yoast/wordpress-seo/pull/16928.
* After part of the configuration was removed in https://github.com/Yoast/wordpress-seo/pull/16928, the remaining configuration in `trunk` broke the `i18n` build script.
* Removes all the configuration regarding the `schema-blocks` translations.
* I did a search in `wordpress-seo/config/grunt` on the word `schema` …
> Remove all the configuration regarding the `schema-blocks` translations

- src/helpers/schema/replace-vars-helper.php
- tests/unit/helpers/schema/replace-vars-helper-test.php
* The `datePosted` property of the Job posting block should be in ISO 8601 format.
* [wordpress-seo-premium] Fixes a bug where the Job posting block would show an invalidly formatted `datePosted` date.
* I used the `"2017-01-24T19:33:17+00:00"` format, since that is the same format we use for the other Schema pieces in the graph.
* E.g. for the `datePublished` and `dateModified` properties of the `WebSite` and `Article` pieces.
* It is also valid [according to Google's documentation](https://developers.google.com/search/docs/data-types/job-posting#job-posting-definition):
> The original date that employer posted the job in ISO 8601 format. For example, "2017-01-24" or "2017-01-24T19:33:17+00:00".
This PR can be acceptance tested …
> Formatted post date correctly in schema replace vars helper.

- .gitignore
- Gruntfile.js
- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/build-qa-changelog.js
- config/grunt/task-config/download-qa-changelog.js
- config/grunt/task-config/update-changelog-with-latest-pr-texts.js
- package.json
- yarn.lock
* This PR as needed for the automation of RC/beta release process, this add changelog update taks, without the need for input during the RC/beta creation task
* Added config for RC/beta creation
*
* run grunt update-changelog:file --plugin-version=XX.X-RCX (where the X represent numbers for instance: 16.3-RC2" this should update the changlog.md file with new changelog items from the "wiki" yoast-cli create:changelog command specific to this RC number and version
* run grunt update-changelog:qa --plugin-version=XX.X-betaX this should create/overwrite a file .tmp/qachangelog.md for a beta1 it will contain all entry's from the "wiki" yoast-cli create:changelog command, for a …
> Add Grunt changelog tasks from plugin-grunt-tasks

- package.json
- yarn.lock
*
* Bumps the monorepo package versions to the latest RC version (16.3-RC1).
> Bump monorepo packages for 16.3-RC

- src/generators/schema/author.php
- src/helpers/user-helper.php
- tests/unit/generators/schema/author-test.php
on a post with author archives enabled
* To improve the author schema piece by adding the url property when possible.
* Adds url property to author schema on a post when author archives are enabled.
* On a post:
* With author archives enabled:
* Test the author archive url is added as a url property on the person schema piece.
* With author archives disabled:
* Test the url property is not added to the person schema piece.
* On anything else than a post that has a person schema piece:
* Test the url property is not added on the person schema piece. 
* Schema, especially for posts. Only …
> Add url property to author schema

- src/integrations/schema-blocks.php
- tests/unit/integrations/schema-blocks-test.php
*
* Reinstates the schema blocks feature flag.
* Used `assertEquals` instead of the less strict `assertSame` in the unit tests.
* Please test this once in Premium, using the test instructions in the companion PR in Premium.
*
* Please make sure that the recipe block is also (still) behind the feature flag.
Fixes #
> P2-923 - Reintroduce job posting feature flag

- admin/menu/class-replacevar-editor.php
- admin/views/tabs/metas/paper-content/front-page-content.php
- js/src/initializers/search-appearance.js
- src/config/badge-group-names.php
- src/presenters/admin/badge-presenter.php
- tests/unit/config/badge-group-names-test.php
- tests/unit/presenters/admin/badge-presenter-test.php
* When we introduce new features and place 'New' badges next to them, we want the badges to disappear after a certain version (usually the one after the next one). For example, a badge next to features introduced in `16.3` should disappear from `16.5` on (actually from `16.5-beta1`, see below)
* Adds a framework to make 'New' badges disappear after upgrading to a chosen version.
* The version number in the `Badge_Group_Names` class has to be set as (e.g.) `16.5-beta0`. This way the badges will disappear as soon as the version is bumped to `16.5-beta1`, so it can be tested in beta and RC stages. This is because `version_compare()` treats `16.5-beta*` and `16.5-RC*` as coming before `16.5` (and rightly so).
This PR can be …
> P3-472 Disappearing 'New' badges

- src/context/meta-tags-context.php
- tests/unit/context/meta-tags-context-test.php
* Yoast SEO only supports JPG, PNG and GIF images to be correctly displayed as logo in the Organization schema piece. We should avoid to output a badly formed piece if another image type is used.
* Fixes a bug where a malformed Organization piece is added to the Schema if the company logo is an unsupported image.
* This only prevents a faulty Schema output, but it doesn't address the uploading/use of unsupported images in the Image selector component.
* edit your theme's `functions.php` file and add this snippet to the bottom:
```
function my_custom_mime_types( $mimes ) {
// New allowed mime types.
$mimes['svg'] = 'image/svg+xml';
$mimes['svgz'] = 'image/svg+xml'; …
```
> Prevent the displaying of an Organization schema piece if the logo is an unsupported image

- admin/class-plugin-availability.php
* Code quality
* Code quality
Performance tweak: Use `isset()` instead of the slow combination of `in_array()` with `array_keys()`.
* _N/A_
> Performance: use isset()

- lib/migrations/adapter.php
- lib/migrations/table.php
- lib/orm.php
* Code quality
* Code quality
`join()` is an alias for `implode()`. Use the canonical function name instead.
* _N/A_
> QA: don't use `join()`

- tests/unit/doubles/inc/options/option-social-double.php
- tests/unit/routes/yoast-head-rest-field-test.php
No functional changes.
A constructor cannot `return`.
These tests do not use a data provider and do not allow for parameters to be passed in, so the `@dataProvider` tag is incorrect.
* _N/A_
> Tests: minor tweaks

- admin/views/licenses.php
* Security hardening
* Security hardening
URLs should be escaped with `esc_url()`
* _N/A_
> QA: fix incorrect escaping

- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
For hooks docblocks, there is no directly related variable name for the parameters being passed, but they should still be given a "name", if only in the docblock to help describe what the user will receive in their hooked-in function.
* _N/A_
> Docs: `@param` tags should contain variable name

- admin/class-admin-asset-yoast-components-l10n.php
- admin/class-admin-init.php
- admin/class-asset.php
- admin/class-product-upsell-notice.php
- admin/class-yoast-input-validation.php
- admin/class-yoast-notification-center.php
- admin/config-ui/components/class-component-mailchimp-signup.php
- admin/filters/class-cornerstone-filter.php
- admin/metabox/class-metabox-null-tab.php
- admin/ryte/class-ryte.php
- inc/class-addon-manager.php
- inc/class-wpseo-shortlinker.php
- lib/dependency-injection/container-registry.php
- lib/migrations/adapter.php
- lib/migrations/migration.php
- lib/model.php
- src/actions/alert-dismissal-action.php
- src/actions/indexing/abstract-link-indexing-action.php
- src/builders/indexable-author-builder.php
- src/deprecated/admin/class-social-admin.php
- src/deprecated/admin/links/class-link-compatibility-notifier.php
- src/deprecated/admin/links/class-link-table-accessible-notifier.php
- src/deprecated/admin/notifiers/class-post-type-archive-notification-handler.php
- src/deprecated/frontend/class-twitter.php
- src/helpers/author-archive-helper.php
- src/presentations/indexable-presentation.php
- src/routes/yoast-head-rest-field.php
All types which can be returned should be listed in the `@return` tag.
* _N/A_
> Docs: fix missing/incorrect types in `@return` tags

- admin/class-database-proxy.php
- admin/config-ui/class-configuration-page.php
- admin/formatter/class-metabox-formatter.php
- admin/import/plugins/class-import-jetpack.php
- admin/views/tabs/dashboard/webmaster-tools.php
- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- config/dependency-injection/interface-injection-pass.php
- inc/class-upgrade.php
- inc/class-wpseo-replace-vars.php
- inc/class-wpseo-utils.php
- inc/options/class-wpseo-option-titles.php
- inc/options/class-wpseo-option.php
- inc/sitemaps/class-sitemap-image-parser.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
- src/conditionals/admin/doing-post-quick-edit-save-conditional.php
- src/deprecated/admin/extension.php
- src/integrations/third-party/elementor.php
- src/integrations/watchers/primary-category-quick-edit-watcher.php
- src/presenters/breadcrumbs-presenter.php
- src/presenters/meta-description-presenter.php
- src/presenters/title-presenter.php
- src/values/open-graph/images.php
- tests/unit/conditionals/admin/doing-post-quick-edit-save-conditional-test.php
- tests/unit/conditionals/estimated-reading-time-conditional-test.php
- tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
- wp-seo-main.php
* Move a function description for a `void` function to the "description" part of the docblock. The `void` return type cannot have a description attached to it.
... picked up along the way.
* _N/A_
> Docs: various minor tweaks

- src/presenters/slack/enhanced-data-presenter.php
- tests/unit/presenters/slack/enhanced-data-presenter-test.php
* All our meta tags are self-closing (`<meta ... />`). Our `twitter:label` and `twitter:data` are not. For consistencies' sake and to allow pages to pass some validations, we should add the self-closing indicator.
* [Enhancement] Makes all twitter meta tags self-closing.
* More information here: https://www.w3.org/TR/html52/syntax.html#start-tags . It isn't strictly necessary to mark the tags as self closing, but it doesn't hurt either and it allows for consistency and, according to [this issue](https://github.com/Yoast/wordpress-seo/issues/16949), ADA compliance. 
* Check if the source-code of an article has the following meta tags:
```
<meta name="twitter:card" …
```
> Consistently self-close enhanced twitter meta tags

- css/src/adminbar.css
* Remove the background color override of our adminbar notification to adhere to the new colors of WP 5.7
* Changed the radius of the notification background to an absolute instead of percentage to prevent oval warping.
* [enhancement] Changes the notification in the adminbar to closer match the sidebar.
* I wanted to change a bit more to have the notification account for different scenarios, But WordPress overrides some settings. So I chose to leave it at the background color change and radius change. 
The notification in the admin bar should have gone from this:
To this:
* Make sure the notification shows correctly on …
> Change color and radius of adminbar notification

- admin/ryte/class-ryte-request.php
* Decrease the likelyhood of a site-check by Ryte to end in a timeout.
* [non-user-facing] Increase the timeout for the site-health check to Ryte from 5 to 10 seconds.
* When Ryte is particularly busy, responses may exceed several seconds. Combine this with WordPress / host / networking overhead may cause the Ryte check to timeout and show an `cURL 28 error`.
* Have Query Monitor installed
* Go to Tools -> Site Health
* Check the HTTP API calls in Query Monitor
* See that the call to `https://indexability.yoast.onpage.org/` now has a timeout of 10 seconds (instead of the default 5)
*
Fixes …
> Increase Ryte sitecheck timeout

- src/context/meta-tags-context.php
- src/generators/schema/organization.php
- src/helpers/image-helper.php
- tests/unit/context/meta-tags-context-test.php
- tests/unit/generators/schema/organization-test.php
* The fix in #16936  merely prevented to trigger notice in the frontend + put out a malformed `Organization` Schema piece, but at the cost of forbidding the usage of images for which we couldn't get an array of metadatas.
We should restore that, while avoiding to save the full `option_titles` array each time there is a new frontend request (which can raise race conditions if the options are filtered)
* Fixes a bug where the complete options array could be re-saved in the database at each frontend request.
*
* edit your theme's `functions.php` file and add this snippet to the bottom:
```
function my_custom_mime_types( $mimes ) {
// New allowed mime types.
$mimes['svg'] = …
```
> P3-584 do not restrict image types but avoid race condition

- admin/class-premium-popup.php
- admin/class-yoast-notification.php
- css/src/dashboard.css
- css/src/yst_plugin_tools.css
- css/src/yst_plugin_tools.scss
- inc/health-check.php
- tests/unit/inc/health-check-test.php
* The `Yoast_SEO_Icon` image was moved from the root `images` directory to `packages/js/images`, but the path in the files where this image is used has not been changed.
* Fixes an incorrect path that caused the Yoast SEO Icon to not be found.
*
Make sure there are no console errors when:
* Clicking on the Dashboard
* Clicking on an SEO suggestion under Tools -> Site Health, e.g.
* Additionally, the Yoast icon should be visible under the Site Health tabs as shown in the screenshot above.
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-808
> Fix path of the Yoast SEO icon image

- config/grunt/task-config/copy.js
* The `Yoast_SEO_Icon` image was moved from the root images directory to `packages/js/images`, but the path in the files where this image is used has not been changed. [This PR ](https://github.com/Yoast/wordpress-seo/pull/16994) fixes the problem in the development version. However, it doesn't fix the issue in the production version.
* Adds an extra path inside `copy.js` file for images inside the js package.
* Delete the empty `premium-configuration` branch with the same name after this PR is merged
* The development version can be tested via docker.
* The production version can be tested by making a zip first.
Make sure there are no console errors both in the …
> Add extra path in grunt-task config for images inside the js package

- src/conditionals/Addon_Installation_Conditional.php
- src/conditionals/addon-installation-conditional.php
- src/routes/supported-features-route.php
- tests/unit/routes/supported-features-route-test.php
* We need to know whether we can install an addon from outside.
* Adds a rest route which gives information about the features which are supported by the plugin.
* We've kept it simple. The rest route returns the needed information immediately.
use the `basic.wordpress.test` local setup to follow along these test instructions.
* Checkout this pr's branch;
* Set the `YOAST_SEO_ADDON_INSTALLATION` feature flag to true.
* Go to your plugin development docker environment.
* go to `config/basic-wordpress-config.php` for example. line 40;
* add `define( 'YOAST_SEO_ADDON_INSTALLATION', true );`
* Run `composer install`. ( for the DI. )
* Go to …
> Add a feature flag for the addon installation project

- packages/schema-blocks/tests/functions/blocks/getParentSidebar.test.ts
- packages/schema-blocks/tests/functions/presenters/BlockSuggestionsPresenter.test.ts
* After merging `develop` in `javascript` to `feature/language-split` in `wordpress-seo`, there are two `schema-blocks` test that are failing. 
* Adds `matchMedia.mock` to ` BlockSuggestionsPresenter` and `getParentSidebar` test files, and unskips `getParentSidebar` test.
* `getParentSidebar` test was skipped in [this PR](https://github.com/Yoast/wordpress-seo/pull/17017) and it's unskipped in this PR.
* The empty `premium-configuration` branch with the same name should be deleted after this PR is merged.
* Run `yarn test` and make sure that all tests pass.
* …
> LINGO-819 Fix failing schema blocks tests

- packages/configuration-wizard/src/Choice.js
* The prop type for the `choices` component was changed from object to array in this [commit](https://github.com/Yoast/javascript/commit/737d588e7f8c6742e7806c7e58e65ee95782c3f9). This wasn't causing any errors in the previous plugin versions, but in this version we get an error saying that an array was expected but received an object. Changing the prop type back to Object fixes the error, and seems more logical as the function in `Choice.js` uses object-specific methods such as `Object.keys`. 
* Changes prop type for `choices` from array to object.
*
* Open the configuration wizard and make sure this error does not appear:
* …
> Change prop type that was causing a console error in the configuration wizard

- src/integrations/front-end/wp-robots-integration.php
- tests/unit/integrations/front-end/wp-robots-integration-test.php
* In a very limited set of cases it was possible that WordPress pages (WP 5.7+) in combination with our plugin would show combinations of `index, noindex` or `follow, nofollow` as robots meta values. While noindex / nofollow directives generally take precedence over their index / follow counterparts, this is of course highly unwanted behavior. This PR ensures that this could never happen again. 
* Fixes a bug where both noindex and index values could be added to the robots meta tag on the WP login screen. 
* Enforces that `index` is always removed from robots if `noindex` is included.
* Enforces that `follow` is always removed from robots meta if `nofollow` is included.
* …
> QAK-2892 Ensure robots values are always congruent if noindex and or nofollow is set

- src/presentations/indexable-post-type-presentation.php
- src/presentations/indexable-presentation.php
- src/presentations/indexable-term-archive-presentation.php
- tests/unit/presentations/indexable-post-type-presentation/open-graph-description-test.php
- tests/unit/presentations/indexable-post-type-presentation/twitter-description-test.php
- tests/unit/presentations/indexable-presentation/open-graph-description-test.php
- tests/unit/presentations/indexable-presentation/open-graph-title-test.php
- tests/unit/presentations/indexable-presentation/twitter-description-test.php
- tests/unit/presentations/indexable-presentation/twitter-image-test.php
- tests/unit/presentations/indexable-presentation/twitter-title-test.php
- tests/unit/presentations/indexable-term-archive-presentation/open-graph-description-test.php
- tests/unit/presentations/indexable-term-archive-presentation/twitter-description-test.php
* We want the changes in #16850 to be more clear and readable, by reducing the changes from the current state in `master` and following the hierarchy fallback order.
* We want also to address the changes in the Twitter hierarchy, where social templates should take precedence over the fallback to OG tags.
* Improves the presentations classes for readability and adherence to the current behaviour.
* Updates the presentations classes to add the Social Template in the hierarchy for the Twitter tags.
* The tests have also improved to check more carefully the complete fallback mechanism.
Basically we need to test against regressions to make sure that the code changes are not …
> P3-582 improve presentations classes

- src/integrations/front-end/wp-robots-integration.php
- src/memoizers/meta-tags-context-memoizer.php
- tests/unit/integrations/front-end/wp-robots-integration-test.php
- tests/unit/memoizers/meta-tags-context-memoizer-test.php
* Flows were possible where the current page context was fetched without first resetting the query, possibly leading to situation where the wrong object would be set as the current page leading to, among other things, incorrect schema.
* Fixes a rare issue where the name property would be missing in the breadcrumb schema due to plugin conflicts.
* The query is always reset when creating the current page context, this ensures the main query is always used and whether or not the loop is active no longer has any impact on what is seen as the current page.
* Add the following code somewhere ( functions.php or wp-seo-main.php ): `add_action( 'init', 'wp_title' );`
* This will …
> Always reset the query before retrieving the current page context

- inc/class-upgrade.php
- inc/options/class-wpseo-option-titles.php
* We want the defaults for the social templates do be distinct from the ones used for the SEO templates
* Sets the default values for the Social Title templates.
* Removes the upgrade routine that copied the SEO templates defaults into the Social templates defaults.
*
* activate Yoast SEO switched to this branch and built
* use the Yoast Test Helper plugin to register the `Book` and `Movie` custom post types
* manually inspect the database by using your tool of choice (e.g. Sequel Pro on macOS)
* in the `wp_options` table, delete the option with name `wpseo_titles`
* _To test the following bullet point, install and activate Premium from `trunk` and enable the Social …
> P3-590 Change defaults for social title templates

- inc/options/class-wpseo-option-titles.php
* We want the default value for the home social title to be the site title instead of an empty string (which fallbacks to the SEO title).
* Sets the homepage social title default value to the site title.
*
* activate Free, switched to this branch and build it as usual
* activate Premium
* make sure that under Settings > Reading, the "Your homepage displays" setting is set to "Your latest posts"
* go to SEO > Search Appearance > General > Homepage
* check the Social title input field contains the "Site title" variable as its default value
* if you previously set a custom value for this field, empty the field and save: after the page reloads, check the default value is the …
> Set the home social title default to the site title.

- css/src/schema-blocks.css
- packages/schema-blocks/css/schema-blocks.css
- packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
- packages/schema-blocks/src/instructions/blocks/Duration.tsx
- packages/schema-blocks/src/instructions/blocks/index.ts
- src/schema-templates/assets/icons.php
- src/schema-templates/cooking-time.block.php
- src/schema-templates/cooking-time.schema.php
- src/schema-templates/recipe.block.php
- src/schema-templates/recipe.schema.php
- tests/unit/dependency-injection/schema-templates-loader-test.php
- yarn.lock
*
* Adds a cooking time block for the recipe block.
* Moved Icons to free from premium, along with some general CSS rules that apply to certain elements that are shared between free and premium.
* Make sure the `YOAST_SEO_SCHEMA_BLOCK` feature flag is enabled.
* Add a new recipe block.
* Inside the recipe block add a `Cooking Time` block.
* Fill in a number of minutes.
* Save the post.
* On the front-end inspect the schema output. In the recipe schema block, the cooking time attribute should be formatted as a ISO 8601 duration string. https://en.wikipedia.org/wiki/ISO_8601
* Also check out `P2-223-move-schema-assets-for-free` in premium. Activate …
> Added cooking time instruction

- inc/class-my-yoast-api-request.php
* By default wp_remote_get doesn't set an `Expect` header, this means that the underlying Curl will add that header with a `100-Continue`  value. This causes there to actually be two responses, one with a 100 status header indicating the server will respond and after that the normal response.
* Optimizes license checks made by premium addons.
* Have the premium addon active alongside this PR.
* Visit the premium page in the SEO settings.
* Premium should show as activated ( provided you have an active MyYoast subscription ).
*
*
> Add expect header to the MyYoast API requests

- src/helpers/current-page-helper.php
- src/memoizers/meta-tags-context-memoizer.php
- tests/unit/helpers/current-page-helper-test.php
* Ensures we no longer trigger the static posts page on any object with the same ID.
* Fixes a bug where the schema output could be incorrect on terms with the same ID as the static posts page.
* Uses the built in `is_page` function of `WP_Query`.
To reproduce the issue:
1. Install Yoast free 16.3
2. Go to the WordPress Reading settings, and set your Sample page as the `Posts page` (in my case, the sample page has the ID of 2, this is important).
3. Go to your post categories and create categories until you create one with the same ID as the page in the previous step, so in this case ID 2.
4. Create a post and assign the category from the previous step (ID 2)
5. Go to the …
> A page is only a static posts page if it is a page

- src/helpers/redirect-helper.php
- src/integrations/front-end/redirects.php
- tests/unit/integrations/front-end/redirects-test.php
* Using `wp_safe_redirect()` instead of `wp_redirect()`, along with the allowed_redirect_hosts filter if needed, can help avoid any chances of malicious redirects within code.
*  Improve unsafe redirects in Redirect_Helper.
* The `do_redirect` function (in  Redirect_Helper) has been renamed to `do_unsafe_redirect`, to keep the option, but make it more clear that someone is consciously choosing the unsafer option (instead of the `do_safe_redirect` function).
* The unsafe redirect in the `page_redirect` has been changed to a safe redirect.
* It still needs to be discussed whether the unsafe redirect in `attachment_redirect` can also safely be replaced with a safe redirect. **-- Please update this comment with the decisions made …
> P3 622 fix unsafe redirect in redirect helper

- admin/menu/class-replacevar-editor.php
- packages/components/src/Label.js
- packages/components/src/badges/badge.css
- packages/components/src/field-group/FieldGroup.js
- packages/components/src/image-select/ImageSelect.js
- packages/components/src/index.js
- packages/components/src/new-badge/NewBadge.js
- packages/components/src/new-badge/index.js
- packages/components/src/new-badge/new-badge.css
- packages/components/src/premium-badge/PremiumBadge.js
- packages/components/src/premium-badge/index.js
- packages/components/src/premium-badge/premium-badge.css
- packages/js/src/components/ImageSelectComponent.js
- packages/js/src/components/SettingsReplacementVariableEditor.js
- packages/js/src/components/SettingsReplacementVariableEditors.js
- packages/js/src/components/portals/ImageSelectPortal.js
- packages/js/src/components/portals/SettingsEditorPortal.js
- packages/js/src/initializers/search-appearance.js
- packages/replacement-variable-editor/src/ReplacementVariableEditor.js
- packages/replacement-variable-editor/src/SettingsSnippetEditor.js
- packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
- packages/replacement-variable-editor/src/shared.js
- packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
- src/integrations/admin/social-templates-integration.php
* We want to display a "Premium" badge for the social templates forms, only when Premium is activated.
* Adds a "Premium" badge to the social templates forms.
* For consistency, the ability to display the "Premium" badge is added to all the places where the "New" badge was added.
- activate Yoast SEO Free, switched to this branch and build it as usual 
- activate Yoast SEO Premium and SEO Local 
- go to SEO > Search Appearance > Content Types and check _all_ the Social image, Social Title, and Social description display a "Premium" badge before the "New" badge (check also the Locations and Locations archive)
- check the "Premium" badge matches the design …
> P3-623 Add Premium badge to social templates forms

- packages/replacement-variable-editor/src/Mention.js
- packages/replacement-variable-editor/src/ReplacementVariableEditor.js
* Since the `replacement-variable-editor` package is used in a range of products. To allow for different styling of the `ReplacementVariableEditor` in differing implementations, CSS-classes are needed.
* [@yoast/replacement-variable-editor] Adds classes to the main elements of the `ReplacementVariableEditor` and `Mention` components to allow for individual styling.
* Prefixed with `yst-` like we do in the Settings UI App
* In a page or post editor, get to the replacement variable editors
* Verify that the replacement variable editors function and look the same as before
* Inspect the HTML and verify that the following classes are added to various parts of the replacement …
> Add classes for styling in other implementations

- src/models/indexable.php
This fixes an issue where multibyte characters can be truncated part-way through a character in the `primary_focus_keyword` field on an Indexable. The potential knock-on effect is invalid characters in a mysql insert/update, which then fails.
* Improved the truncation of the `primary_focus_keyword` field to handle multibyte characters.
* Changed the string truncation method to use `mb_substr()` instead of `substr()`
Use some strings (longer than 191 characters) containing multibyte characters in the keywords field of a page or post - check that they are saved correctly to `wp_yoast_indexables`.
This is the exact keywords string where we first spotted the issue, with some Malayalam characters toward the end:-
```
kuldeep yadav, …
```
> Use mb_substr instead of substr to avoid multibyte character truncation

- inc/options/class-wpseo-option-titles.php
* We want the Homepage Social title to fallback to the SEO title (when the Social title is emptied) so that we have a fallback mechanism that is consistent with the other social titles. 
* Improves the Homepage Social title implementation by allowing a fallback to the Homepage SEO title.
* Changed validation method for the `open_graph_frontpage_title` setting in `WPSEO_Option_Titles` so that it's now possible to save an empty string.
* activate Yoast Free, switched to this branch, and build it as usual
* use a clean database, or empty the value of the `wpseo_titles` option in the database table `wp_options`
* go to SEO > Search appearance > General > Homepage
* check the …
> P3-639 Allow to save an empty Homepage Social title and trigger the fallback.

- admin/views/tabs/metas/general.php
- admin/views/tabs/metas/paper-content/front-page-content.php
- admin/views/tabs/metas/paper-content/post_type/post-type.php
- composer.json
* We want to fix the feature branch crossing the CS error threshold
* Fixes some CS errors by escaping attributes in Search Appearance tabs
*
* N/A
*
*
Fixes #
> Escape attributes in Search Appearance tabs

- admin/views/tabs/metas/paper-content/front-page-content.php
- admin/views/tabs/social/facebook.php
- packages/components/src/image-select/ImageSelect.js
- packages/components/src/image-select/image-select.css
- packages/js/src/components/ImageSelectComponent.js
- packages/js/src/components/portals/ImageSelectPortal.js
- packages/js/src/initializers/search-appearance.js
- packages/js/src/initializers/social-settings.js
- packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
- src/integrations/admin/social-templates-integration.php
* We want to show validation warnings for the images set in the Social Templates, for consistency with the validation that is in place in the Yoast meta box for Facebook and Twitter images.
- Adds image validation warnings to the Social templates images.
- [@yoast/components] Improves the accessibility of the Select Image validation warnings.
*
- activate Yoast SEO Free, switched to this branch and build it as usual 
- activate Yoast SEO Premium 
- upload the attached image to the WordPress media library (unzip it first)
[bmp-image-small.bmp.zip](https://github.com/Yoast/wordpress-seo/files/6561323/bmp-image-small.bmp.zip)
- when using this image for the social image, it …
> P3-638 Add image validation warnings for social templates

- packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
- packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
* We want to release Norwegian readability assessments (i.e. Passive Voice, Sentence Beginning, and Transition Words Assessments) under feature flag.
* [yoastseo] Adds a check in Passive Voice, Sentence Beginning, and Transition Words Assessments whether `norwegian-readability` feature is enabled, and returns the default result if it's disabled.
* The empty `premium-configuration` branch with the same name should be deleted after this PR is merged.
* Currently, when we enable the feature, there are going to be errors in the console related to the fact that at this point we haven't added the necessary configs and helpers for the assessments in the Norwegian Researcher. These errors will be fixed when we implement the the related …
> LINGO-748 implement norwegian readability feature flag

- src/conditionals/addon-installation-conditional.php
- src/integrations/admin/addon-installation/dialog-integration.php
- src/integrations/admin/addon-installation/installation-integration.php
- src/routes/supported-features-route.php
- tests/unit/routes/supported-features-route-test.php
Reverts Yoast/wordpress-seo#17046
Reintroduces the addon installation flow feature flag.
> Revert "Remove the Addon installation feature flag"

- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/shell.js
* The Core team regularly gets questions from other devs about their builds breaking due to the `schema-blocks` package. It isn't common knowledge that `yarn build` should be run every time the TypeScript code in the `schema-blocks` package has changed.
* Introduces the Grunt `build:ts` command to compile the TypeScript in our `schema-blocks` package.
* I changed the `install-schema-blocks` shell command to run `yarn build` in `packages/schema-blocks` rather than in `node_modules/@yoast/schema-blocks`. I believe this should have happened after we merged the monorepo, but was forgotten.
* I also removed the conditional from the `install-schema-blocks` shell command. The TypeScript in the plugin should be recompiled every time it …
> Add Grunt `build:ts` command for compiling TypeScript in the plugin

- admin/views/tabs/metas/paper-content/post-type-content.php
- admin/views/tabs/metas/paper-content/post_type/post-type.php
- src/config/badge-group-names.php
- src/integrations/admin/social-templates-integration.php
- tests/unit/config/badge-group-names-test.php
* We want to move the Social templates forms at the end of the expandable panels in the settings pages so that they're displayed as last thing within the panels.
* We want to fix a bug that prevented the "New" badges from being displayed.
* Moves the Social templates forms at the end of the settings sections.
* Fixes a bug where the "New" badges were not displayed for the Social templates forms.
- Removes the `Yoast\WP\SEO\admin_post_types_meta` since it's now unused
- Note: This PR is a UI-change compared to the PR that merged the Global Social Templates feature https://github.com/Yoast/wordpress-seo/pull/17095 as now the Social template forms will be displayed in a different position in the settings pages 
This PR can be …
> Move social settings below schema settings and restore New badges

- admin/class-admin-init.php
- admin/class-premium-upsell-admin-block.php
- admin/views/sidebar.php
- src/integrations/admin/social-templates-integration.php
* With adding more contextual upsells, we become less dependant on our ads. In this PR I'm removing about half the ads that were listed in the sidebar of the Yoast SEO admin screens. Also, we've removed the ad box at the bottom on the search appearance settings. 
* Less is more: removes a whole bunch of ads from the Yoast SEO admin screens.
* On every Yoast SEO admin/settings screen the following ads should be gone:
* "Extend Yoast SEO"
* "Remove these ads?"
* On the search appearance settings screen the following ad should be gone:
* The upgrade box at the bottom
* On every admin screen, the links in the ads should now have a `screen` parameter which resembles the `page` …
> P3-666 Remove ads

- admin/views/tabs/social/facebook.php
To avoid confusion for the user, we should add  'social' before the 'homepage settings'.
See slack thread for reference: https://yoast.slack.com/archives/C027BFR5L/p1622636034237200
* Improves copy of the moved-homepage-settings alert.
*
* Navigate to SEO > Social > Facebook.
* Make sure the alert matches [the design](https://www.sketch.com/s/6b4efaeb-fcab-4e48-8314-0d532488e164/a/l1RrVGv/play).
* Navigate to SEO > Social > Facebook.
* Make sure the alert matches [the design](https://www.sketch.com/s/6b4efaeb-fcab-4e48-8314-0d532488e164/a/l1RrVGv/play).
This PR affects the following parts of …
> P3-668 Improve copy of the moved-homepage-settings alert

- admin/views/tabs/metas/general.php
- admin/views/tabs/metas/paper-content/general/force-rewrite-title.php
- admin/views/tabs/metas/paper-content/general/title-separator.php
When the `Force rewrite titles` setting is present, we need to make sure it appears in a paper at the top of the Search Appearance > General tab.
* Moves the 'Force rewrite titles' toggle into a separate paper in the General Search Appearance settings.
*
* Make sure the theme does not register support for title-tag. To do this, remove or comment out the `add_theme_support( 'title-tag' );` line from your theme's functions.php file and click `Update file`.. 
* Navigate to SEO > Search Appearance > General and see there is a separate 'Rewrite titles' paper with the 'Force rewrite titles' toggle. Make sure it matches [the …
> P3-671 Move rewrite titles to separate paper

- inc/class-wpseo-utils.php
Patch to expand test for Apache to also check for the Apache-compatible web server LiteSpeed and return same result
* Add support for the only [unofficially supported but officially recognized](https://make.wordpress.org/hosting/handbook/handbook/server-environment/#web-server) web server, LiteSpeed. Without this then changes to redirects via wordpress-seo-premium are not actually applied to `.htaccess` and the Settings tab under Redirects only shows PHP & Web server instead of PHP & `.htaccess` along with a secondary option of with being able to select a separate redirect file.
* Add increased compatibility for LiteSpeed web servers
* Easiest to just implement this patch but would be _better to change the logic in all plugins …
> Add support for LiteSpeed web servers

- src/presentations/indexable-presentation.php
- tests/unit/presentations/indexable-presentation/twitter-description-test.php
- tests/unit/presentations/indexable-presentation/twitter-title-test.php
* We don't want to output `twitter:` tags if a matching `og:` tag is being output from the Social Templates
* Fixes a bug where a `twitter:title` and `twitter:description` tag were sent to the output even if matching `og:` tags from the Social Templates were already in place.
* We still need to send out a `twitter:` tag with the value from the social template if the indexable has a different value for the open graph tag
* activate Premium
* visit `SEO` > `Search appearance` and set values for `Social title` and `Social description` for a single post
* eg: "Template %%title%%" and "Template %%excerpt%%"
* create a new post, add a title and some content (or an excerpt) to …
> P3-674 do not output Twitter tag if OG tag already existing

- packages/components/src/image-select/image-select.css
* We want the Social image buttons which display an image to support a ~16:9 aspect ratio, to avoid white bars above and below when an image with the right size for social sharing has been loaded.
* [@yoast/components] Improves the support for 16:9 images by the ImageSelect component.
* 
* For each one of the following instances of the ImageSelect component, check that:
* the size when empty is 300x165px
* if you upload a 16:9 image, you don't see any white padding bars above and below the image
* The list of the instances:
* `SEO` > `Social`, `Facebook` tab
* `SEO` > `Search Appearance`:
* `General` tab (for the Homepage social settings and for the Schema settings)
* …
> P3-676 Improve ImageSelect support for 16:9 images

- packages/yoastseo/spec/languageProcessing/languages/nb/ResearcherSpec.js
- packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/nb/config/firstWordExceptions.js
*
* Adds the consecutive sentences assessment for Norwegian.
* [yoastseo] Activates the consecutive sentences assessment for Norwegian and adds a list of exception words to exclude from the assessment.
*
* Set your site to Norwegian (Norsk bokmål)
* Open a new post and add the following sentence 4 times in the editor: `Katter er søte.`
* Make sure the consecutive sentences assessment returns a red bullet and that the sentences are highlighted.
* Remove the sentences and add the following text: `En katt. En hund. En hest. En enhjørning.`.
* Make sure the consecutive sentences assessment returns a green bullet.
* …
> LINGO-728 Add Norwegian consecutive sentences assessment

- packages/yoastseo/spec/languageProcessing/languages/nb/ResearcherSpec.js
- packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/nb/config/transitionWords.js
- packages/yoastseo/src/languageProcessing/languages/nb/config/twoPartTransitionWords.js
*
* Adds the transition words assessment for Norwegian
* [yoastseo] Adds Norwegian transition words and activates the transition words assessment
*
* Set your site to Norwegian (Norsk bokmål)
* Open a new post and paste the following text: `Da jeg var liten, bodde jeg i India. Jeg elsker katter.`
* Make sure that the transition words assessment returns a green bullet.
* Check that the first sentence, but not the second sentence is highlighted.
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-721
> Add Norwegian transition words assessment

- admin/formatter/class-post-metabox-formatter.php
- admin/formatter/class-term-metabox-formatter.php
* We don't want to prefill the social tab of the metabox with values from the social templates if Premium is disabled or if Opengraph is (and thus the social templates are) disabled.
* Prevents the values from Social Templates to be used to prefill the fields in the Social tab of the Yoast Metabox
*
* install and activate Premium
* fill the social templates (image, title and desc) for a single post, and for a term archive, then save
* choose easily distinguishable values
* disable Premium
* edit a new post, visit the metabox, go to the social tab and check that the "title" and "description" fields are empty, for both Twitter and Facebook
* edit a new term, visit the …
> P3-678 do not prefill form with social templates on Free

- admin/views/tabs/metas/paper-content/front-page-content.php
- admin/views/tabs/metas/paper-content/post-type-content.php
- css/src/badge.css
- css/src/search-appearance.css
- css/src/yst_plugin_tools.css
- src/integrations/admin/social-templates-integration.php
- src/presenters/admin/premium-badge-presenter.php
* We want to introduce a new "Social settings" headings before the social forms and display the "Premium" and "New" badges there instead of close to the social settings fields.
* Adds a "Social settings" heading in the Search appearance settings to better distinguish the social settings.
* Introduces a new Presenter class for the "Premium" badge.
- activate Yaost SEO Free, switched to this branch, and build it as usual
- activate Yoast SEO Premium 
- activate Local SEO (to test the settings for CPTs)
- go to Search appearance > General > Homepage 
- check there's a new heading "Social settings" with only a "New" badge 
- check that Social image, Social title, and Social …
> Add social settings heading.

- packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
- packages/yoastseo/src/languageProcessing/researches/getSentenceBeginnings.js
* We don't want to count sentences that are inside tables or table captions for the consecutive sentences assessment.
* Excludes sentences inside tables and table captions from the consecutive sentences assessment.
* [yoastseo] Filter out table block content from the getSentenceBeginnings research.
*
* Do the following steps in default editor, classic editor, and Elementor.
* Open a new post and add some text.
* Create a table with 4 cells. Paste the following sentence in each cell: `Cats are cute.`
* Make sure that the consecutive sentence assessment returns a green bullet. 
* Add the following table caption: `Unicorns are cute`. Add the same sentence two times in the …
> Exclude tables from consecutive sentences assessment

- inc/class-upgrade.php
* The social titles options have been introduced since 16.3 with outdated defaults so users upgrading to 16.5 won't see the new default values. We want to reset those options.
* Adds an upgrade routine to reset the social title options to the new default values.
*  We had to hook the method to copy social options for the home page to `init` action to make sure that integrations are loaded by then and the `Indexable_Home_Page_Watcher` can trigger the rebuilding of the home page indexable.
* some of the values will be localized so it would be better to have WP in a different language from the default English (US)
* change the language in `Settings` > `General`
* visit …
> P3-681 Reset existing Social titles options to the new defaults via upgrade routine

- inc/class-upgrade.php
* We need to add checks to the upgrade routing added by #17127 to avoid setting values to previously non-existing options
* Adds some checks to the upgrade routine for the Social Templates
* we don't filter out attachments because 16.4 created options for them (they will be removed when the user edits the Search Appearance form)
* Follow the test instruction from #17127 and check that at the end there are no `social-titlept-archive-post` and `social-titlept-archive-page` options.
* [] QA should use the same steps as above.
* Not sure it's relevant since it's about database values, not seen by the users …
> P3-681 addendum: Add checks to upgrade routine

- packages/yoastseo/src/languageProcessing/languages/nb/config/functionWords.js
* 
* Improves keyword detection for Norwegian by expanding the list of function words.
*
* Test the following in WP SEO Free:
- Set the site language to Norwegian
- Create a new post and add a text with at least 300 words. To create a text you can use e.g., a [text generator](https://www.lipsum.com/feed/html) or use the [Norwegian Wikipedia](https://no.wikipedia.org/wiki/Portal:Forside)
- Set your keyphrase to `fjerde katt`
- Add the word `katt` to the text
- Make sure that the keyphrase density assessment shows the keyphrase is found once.
*
* …
> Expand list of Norwegian function words

- admin/formatter/class-post-metabox-formatter.php
- admin/formatter/class-term-metabox-formatter.php
- src/integrations/admin/social-templates-integration.php
- tests/unit/doubles/admin/formatter/post-metabox-formatter-double.php
- tests/unit/doubles/admin/formatter/term-metabox-formatter-double.php
* Premium should have version >= 16.5 for the social templates to work
* Disables the Social Templates feature in unsupported Premium versions.
*
* run without Premium active:
* you should see the Social Templates forms disabled, with the upsell "Unlock with Premium"
* if you edit a new post, the fields in the social tab should not load the social template values
* run with Premium 16.5 active:
* you should see the Social Templates forms enabled
* if you edit a new post, the fields in the social tab should load the social template values
* run with Premium 16.4 or lower active:
* you should see the Social Templates forms disabled, with a message advising to update Premium …
> P3-685 require Premium 16.5 for social templates

- css/src/search-appearance.css
- src/integrations/admin/social-templates-integration.php
Follow-up to P3-685 / https://github.com/Yoast/wordpress-seo/pull/17135
* We want to improve the message shown to users who are on Premium 16.4 or less by changing it to an alert.
* Improve the message to invite users to unlock the Social Templates features by updating to latest Premium version.
*
- install and activate Yoast SEO Free, switched to this branch, and build it as usual
- install and activate Premium **16.4**
- note: if you're testing with the cloned repos of the plugin you can switch Premium to the 16.4 tag: `git checkout tags/16.4`  and then build it
- go to Search appearance > Content types > Posts
- check the social forms are disabled and there's a …
> GST: change unlock by updating message to an alert

- css/src/search-appearance.css
- src/integrations/admin/social-templates-integration.php
Follow-up to https://github.com/Yoast/wordpress-seo/pull/17139
* We want to avoid passive voice for the copy used for the GST "unlock by updating" alert.
* Further Improve the message to invite users to unlock the Social Templates features by updating to latest Premium version.
* Changes the alert text to "To unlock this feature please update Yoast SEO Premium to the latest version."
* Males sure the English text stays in one line. Translated, longer, text may go in two lines.
* This PR changes only the copy of the alert and slightly adjusts left/right margins via CSS. This alert has already been tested and accepted in https://github.com/Yoast/wordpress-seo/pull/17139 
* …
> GST: Change update to Premium alert text

- apps/content-analysis/config/paths.js
- apps/content-analysis/config/webpack.config.js
- apps/content-analysis/config/webpackDevServer.config.js
* After Content-anlaysis app was moved to `wordpress-seo` from `javascript` repo, it stopped working. 
* Adjusts the content-analysis app config after the merging of `javascript` monorepo to `wordpress-seo`.
*
* In `content-analysis` app, run `yarn`
* Run `yarn start`
* Confirm that the app is running and that there are no errors
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-851
> Adjust content-analysis app configs

- src/generators/schema/breadcrumb.php
- tests/unit/generators/schema/breadcrumb-test.php
* Changes the breadcrumbs schema output so Google can understand it better.
* Our previous implementation was technically correct but Google failed to parse it correctly.
* See https://yoast.atlassian.net/browse/P3-508
*
Fixes #P3-508
> Fix breadcrumb name attribute

- src/integrations/admin/social-templates-integration.php
* We want to load the Social Templates integration only on Admin, and instatiate objects triggering queries only on demand
* Fixes a bug where unnecessary queries were triggered by the Social Templates integration
*
* visit SEO > Search Appearance and check that the Social Templates forms are there
* activate Premium 16.5
* visit SEO > Search Appearance and check that the variables work in the Social templates form.
* install and activate Query Monitor
* install the 16.5 release branch
* visit the home page and take note of the number of the DB queries
* filter by component `wordpress-seo` and see there is a query called by `WPSEO_Custom_Fields::get_custom_fields()`
* …
> P3-696 Optimize loading of Social Templates Integration

- src/generators/schema-generator.php
* In https://github.com/Yoast/wordpress-seo/pull/16943 a situation has been introduced where a filter function receiving 4 arguments would only receive 2 arguments resulting in a fatal error. This PR will introduce a temporary fix until the root problem (https://yoast.atlassian.net/browse/P2-1045) is solved.
* Fixes a bug that if you used the `wpseo_schema_{@type}` filter you would get a fatal error.
*
* Make sure you get schema output on the front-end, if not make sure you have everything configured correctly.
* Add the following filter:
```
add_filter( 'wpseo_schema_person', 'change_webpage_schema', 10, 4);
function change_webpage_schema($schema, $context, …
```
> Make sure wpseo_schema_* filters receive the same number of arguments

- src/integrations/admin/helpscout-beacon.php
* Show a different beacon to people who have tracking enabled so we can send them surveys.
* None needed.
*
Fixes #
> Show different HelpScout beacon to users with tracking on

- admin/pages/dashboard.php
- admin/pages/metas.php
- admin/pages/network.php
- admin/pages/social.php
* Fixing the same CS error that occurred in several admin pages:
```
FOUND 1 ERROR AFFECTING 1 LINE
--
--------------------------------------------------------------------------------
35 | ERROR | Overriding WordPress globals is prohibited. Found assignment to $tabs
```
* Cleans up some code that caused an override of the global variable $tabs.
* There should still be tabs on the Yoast SEO admin pages:
* dashboard (general)
* metas (search appearance)
* network
* social
Fixes N/A
> Rename  to avoid conflict with the global var

- packages/js/src/components/SchemaTab.js
- packages/js/src/containers/SchemaTab.js
- packages/js/src/helpers/classicEditor.js
- packages/schema-blocks/package.json
- packages/schema-blocks/src/functions/initialize.tsx
- packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
- yarn.lock
*
* Fixes a non-released bug where the classic editor would crash if the schema blocks feature flag is active.
* Makes sure the schema-blocks package javascript is not loaded when the classic editor plugin is active. To achieve this we had to make sure that the schema blocks package is no longer a dependency of the classic-editor script. Because the Gutenberg and classic-editor script share the same metabox fills, I resorted to using Slot/Fill, so the schema-blocks package can inject itself into the metabox when the schema-blocks script is loaded.
* Install and activate the classic-editor plugin.
* Enable the feature flag (`define( 'YOAST_SEO_SCHEMA_BLOCKS', true );`).
* …
> Fixes the metabox for classic editor when schema blocks are active

- packages/schema-blocks/src/core/validation/BlockValidation.ts
- packages/schema-blocks/src/core/validation/RequiredBlock.ts
- packages/schema-blocks/src/core/validation/RequiredBlockOption.ts
- packages/schema-blocks/src/core/validation/index.ts
- packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
- packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
- packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
- packages/schema-blocks/tests/functions/process.test.ts
- packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
* checking against redundantblocks is unnecessary; wordpress prohibits adding more than one block if the blocks are configured correctly. We do not need to validate that. The validation logic is a bit complicated, and removing the code reduces the complexity of our code.
* Removes unnecessary validation logic and constants.
* removed the findRedundantBlocks function, its usage and its tests; this meant other tests needed less setup and validation, and some enums/enum values were no longer needed. [P2-816](https://yoast.atlassian.net/browse/P2-816)
* since the removed function validated against a situation that was impossible to achieve in real life, it only needs …
> P2-816 remove redundantblocks validation

- src/generators/schema/breadcrumb.php
- tests/unit/generators/schema/breadcrumb-test.php
* Prevents stripping the final breadcrumb for the static posts page as this page does not have a page crumb.
* Fixes a bug where the last breadcrumb item is stripped in breadcrumb schema on subsequent pages of a static posts page.
* Set a static posts page.
* Go to the second page of it.
* The breadcrumb schema should not have an empty text.
* Breadcrumbs schema generation.
Fixes #
> Fix breadcrumb for static posts page

- src/generators/schema-generator.php
* In https://github.com/Yoast/wordpress-seo/pull/16943 we introduced 2 new arguments  to the `wpseo_schema_{identifier}` filter. This filter could overlap with the `wpseo_schema_{type}` filter, and when requesting 4 arguments from the `wpseo_schema_{type}` filter, a fatal error would occur because the called filter-function would receive only 2 arguments.
Initially, this was fixed by adding the 2 additional arguments to the `wpseo_schema_{type}` filter as well in https://github.com/Yoast/wordpress-seo/pull/17158. Due to type-hinting with would also lead to fatals because some addons still used the deprecated `WPSEO_Graph_Piece` interface instead of the new `Abstract_Graph_Piece` abstract class. The `type_filter` function expected a `Abstract_Graph_Piece`, but got a `WPSEO_Graph_Piece` …
> Remove abstract schema piece type hint from Schema_Generator::type_filter.

- packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
- src/conditionals/slovak-support-conditional.php
- src/helpers/language-helper.php
- tests/unit/helpers/language-helper-test.php
* 
* Adds a feature-flag for Slovak support.
* This PR is accompanied by [another PR in Premium](https://github.com/Yoast/wordpress-seo-premium/pull/3364/files).
* In PHPStorm/your preferred IDE, navigate to `packages/yoastseo/languageProcessing/languages/_default` and copy the contents
* Inside the `languages` folder, create an `sk` folder and paste the contents from `_default` (don't commit any changes)
* Build the free plugin
* Enable the `SLOVAK_SUPPORT` feature by adding `define( 'YOAST_SEO_SLOVAK_SUPPORT', true );` in `basic-wordpress-config.php` file
* Set your site to Slovak
* Create/open a post
* In the console, enter `window.yoast.Researcher` and confirm that it …
> Implement feature flag for Slovak support

- packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
- packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
- packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
- packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
*
* Renames `Job Posting` to `JobPosting` in the context of Schema.
* Also renames the `yoast/job-expiration` template to `yoast/job-closing-date`. This accompanies the rename of this template in Premium. https://github.com/Yoast/wordpress-seo-premium/pull/3355
* We want to get rid of these hard-coded template names in Free at some point (this is a to-do in P2-971).
* Test together with https://github.com/Yoast/wordpress-seo-premium/pull/3355.
* See that we use the name `'JobPosting'` when we refer to Schema analysis, and `'Job Posting'` when we refer to the blocks or block patterns in general.
* In the Schema tab, see that there is a 'Job closing date' block listed under …
> P2-1042 A few small renames regarding JobPosting

- config/dependency-injection/services.php
- css/src/admin-global.css
- packages/js/src/components/CollapsibleCornerstone.js
- src/repositories/indexable-repository.php
- src/wordpress/wrapper.php
* Includes a few improvements needed in Premium.
* Makes sure the badge styling can also be used in the admin bar menu.
* Adds a Slot below the cornerstone toggle
* Fixes https://yoast.atlassian.net/browse/QAK-2961
> QAK-2961 Workouts improvements

- admin/menu/class-admin-menu.php
- admin/menu/class-base-menu.php
* Allows the admin menu to display submenus with different capabilities such as the workouts.
* 
* Have a user that only has permission to see the workouts.
* The workouts should be under the SEO menu.
* Have a user that only has permission to manage redirects and workouts.
* Both should be under the SEO menu.
* The display of Yoast SEO submenu items if the user can not access the SEO dashboard.
Fixes https://yoast.atlassian.net/browse/QAK-2956
> [QAK-2956] Allow the admin menu to display submenus with different capabilities

- composer.json
- src/builders/indexable-builder.php
- src/generators/schema-generator.php
- src/models/indexable.php
- src/repositories/indexable-repository.php
- tests/unit/models/indexable-test.php
- tests/unit/repositories/indexable-repository-test.php
*
* Fixes a bug where the SEO optimization could run indefinitely when the database contained at least 25 faulty indexables without a permalink.
*
I've been able to reliably test this on a clean WordPress installation. *Warning:* While will empty your database:
* Pull the latest version of the `plugin-development-docker`.
* Run `./clean.sh && ./make && ./start`, and stop the development environment after.
* Run `docker exec -it --user www-data basic-wordpress wp db reset`.
* Run `./start` again.
* When you navigate to your `wp-admin` you will have to initialize your WordPress installation.
* Install the Yoast Test Helper and the FakerWordPress plugin.
* Using FakerPress …
> When creating unindexed indexables ensure that they have a permalink

- src/integrations/admin/menu-badge-integration.php
* Adds custom CSS which adds the "Premium" content to the Premium badge in admin and adminbar menus
* Adds custom CSS which adds the "Premium" content to the Premium badge in admin and adminbar menus
* This fixes a bug where the word "Premium" ended up in the title of the redirects manager in Yoast SEO Premium. Test this with the newest RC of Premium.
> Add custom css for premium badges in admin / adminbar menu

- src/conditionals/addon-installation-conditional.php
- src/conditionals/feature-flag-conditional.php
- src/conditionals/schema-blocks-conditional.php
- src/integrations/feature-flag-integration.php
- tests/unit/integrations/feature-flag-integration-test.php
*
* Fixes a bug where WordPress would crash with a fatal error when Yoast SEO would be used in tandem with Yoast SEO Premium <= 16.4.
* It broke because the `get_feature_flag` method's visibility was changed from `protected` to `public`: a change that broke backwards compatibility.
* Install WordPress SEO Premium 16.4.
* Install this version of the WordPress SEO plugin
* Either by checking out this branch or using the appropriate RC-zip.
* WordPress should **not** crash because of this fatal error:
*
*
Fixes #
> Changed get_feature_flag method from public to protected again.

- packages/js/src/components/SchemaTab.js
- packages/schema-blocks/src/functions/initialize.tsx
*
* Fixes a bug where the schema blocks analysis is shown in either the sidebar or the metabox, not both.
*
* Make sure the `YOAST_SEO_SCHEMA_BLOCKS` feature flag is active.
* Create a new post in the block editor.
* Open the schema analysis in both the metabox and the sidebar.
*
*
Fixes #
> Make sure the schema blocks analysis is rendered in both the metabox and the sidebar

- src/presenters/abstract-indexable-presenter.php
- src/presenters/abstract-indexable-tag-presenter.php
- src/surfaces/values/meta.php
* In https://github.com/Yoast/wordpress-seo/pull/17162/files#diff-e0fbc64494e81172a60a7095550fda610afe7ac055178800a81c773c3c1930a1R39 we broke BC because add-ons that extended the class would not have a key property, but instead they output the meta-tag property directly in `$this->tag_format`. Instead of throwing an exception this PR makes sure that the tag is still output.
* Fixes a bug where fatal errors would occur in add-ons.
*
* Activate Yoast SEO Video.
* Create a post containing a video.
* Open the post on the front page.
* Inspect that the Video SEO meta tags are output as expected.
* …
> Dont throw exception when no key is provided in abstract indexable tag presenter

- packages/feature-flag/src/index.js
- src/integrations/feature-flag-integration.php
- tests/unit/integrations/feature-flag-integration-test.php
* Fixes a bug where many Premium editor features would not work if Yoast SEO was updated to version 16.6 while Yoast SEO Premium was still on version 16.5 or lower.
* Install Yoast SEO Premium 16.5 and Yoast SEO 16.6.1
* The related keyphrases feature should be working.
* Feature flags in JavaScript.
Fixes https://yoast.atlassian.net/browse/IM-456
> [IM-456] Fix backwards compatibility of feature-flags

- config/jenkins/Jenkinsfile_artifact
* The Branch names contains slashes which does not play nicely with path names, changed the zip creation to replace "/" with "-" to fix broken zip building in release branches
* Changed the zip creation to replace "/" with "-" in branch name
*
*
*
*
Fixes #
> replace / with - in branch names during zip creation

- src/integrations/front-end-integration.php
- src/routes/yoast-head-rest-field.php
- tests/unit/integrations/front-end-integration-test.php
*
* Adds Meta_Tags_Context to `wpseo_frontend_presenters` filter.
*
* The changes in this PR can be tested in the following add-on PR's, which rely on the changes in this PR:
* https://github.com/Yoast/wpseo-video/pull/889
* https://github.com/Yoast/wpseo-woocommerce/pull/698
* https://github.com/Yoast/wpseo-news/pull/703
* [Local SEO PR to be added]
* To test this PR on its own: visit the front-end and see no notices about undefined variables.
* FYI, this tests if `$this->context_memoizer->for_current_page()` can be found, which is the only code change that was made to this PR (apart from documentation changes). 
*
This PR …
> Added Meta_Tags_Context to wpseo_frontend_presenters filter

- packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
- packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/sk/config/firstWordExceptions.js
*
* [yoastseo] Adds the sentence beginnings assessment for Slovak.
* Implements the consecutive sentence beginnings assessment for Slovak to ensure variety in a text.
*
**Test in Free**
* Enable the `SLOVAK_SUPPORT` feature by adding `define( 'YOAST_SEO_SLOVAK_SUPPORT', true );` in `basic-wordpress-config.php` file
* Set your website to Slovak.
* Create a new post and add three or more Slovak sentences:
> that all begin with the same written-out number, like `jeden` ("one" in masc. form)
E.g. `Jeden pisateľ o meditácii povedal: "Aby sme mohli vidieť veci jasne, naša myseľ musí byť prázdna.". Jeden prevádzkovateľ smie podať pri každej časti na každý základný výrobok len …
> Add sentence beginning assessment for Slovak

- src/presenters/slack/enhanced-data-presenter.php
- tests/unit/presenters/slack/enhanced-data-presenter-test.php
* The presenter checked for post type in the wrong way, which broke json head output
* Fixes a bug where the post type was verified incorrectly
* replaced an `\is_singular` check with `model->obj_sub_type === 'post'`
* check the json head output according to test instructions in [P2-925 / PR 17162](https://github.com/Yoast/wordpress-seo/pull/17162)
* for posts, the written by AND est reading time fields should be together in a JSON object in the json head output, under the twitter_misc key. e.g.
` twitter_misc: { "Est. reading time": "4 minutes", "Written by": "Henk" }`
* …
> replace is_singular check with post type check

- src/generators/schema-generator.php
- tests/unit/generators/schema-generator-test.php
* Fixes a check that attempted to use the global post for checking if a post is password protected.
* Create a password protected post.
* View that post using the REST API.
* It should only have Website, WebPage and, if filled out, Organization schema. Nothing else.
* Schema generation.
> Fix protection of password protected posts in schema generation

- src/routes/indexables-head-route.php
- tests/unit/routes/indexables-head-route-test.php
* Fixes the Yoast head API route when used with URLs including unicode characters.
* Call a route such as: http://basic.wordpress.test/wp-json/yoast/v1/get_head?url=http://basic.wordpress.test/%d0%b4
* If you do not have a page by that URL you should get a 404 response.
* If you create a page with that slug you should get a 200 response with the SEO data of your page.
* The `/wp-json/yoast/v1/get_head?url=` route.
> Fix urls being decoded by WP API

- packages/yoastseo/spec/fullTextTests/runFullTextTests.js
- packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
- src/conditionals/norwegian-readability-conditional.php
*
* Fixes the Norwegian readability feature flag.
*
* Add the statement `define( 'YOAST_SEO_NORWEGIAN_READABILITY', true );` in your `basic-wordpress.config.php` file. 
* Build the Free plugin and set your site to Norwegian.
* Open a post, add some text, and make sure that the sentence beginnings, transition words, and passive voice assessments show up.
* Try to get different results for the assessments, e.g. by adding a transition word or a passive sentence, and confirm that the assessment feedback changes accordingly.
* Remove the statement `define( 'YOAST_SEO_NORWEGIAN_READABILITY', true );` from your `basic-wordpress.config.php` file and rebuild the plugin.
* Make …
> Add conditional for the Norwegian readability feature flag

- inc/class-wpseo-replace-vars.php
* Fixes the `cf_`, `ct_`, `ct_desc`, `tag`, `category` and `parent_title` replacement variables in the REST API.
* Create a custom taxonomy for posts.
* Create a term in that taxonomy that has a description.
* Create a tag
* Create a category
* Create a post and add all your created taxonomies to it.
* Set it's meta description to `%%tag%% %%category%% %%ct_{YOUR_CUSTOM_TAXONOMY_NAME}%%` %%ct_desc_{YOUR_CUSTOM_TAXONOMY_NAME}%%`
* View your post in the REST API. It's meta description should include all names of your taxonomies and the description of your custom taxonomy.
* Create a page
* Give that page a parent
* Set it's meta description to `%%parent_title%%`
* View it …
> Fix replacevars for rest api

- config/dependency-injection/renamed-classes.php
- config/dependency-injection/services.php
- src/deprecated/src/integrations/third-party/elementor.php
* The class Elementor_Exclude_Post_Types has been renamed to Exclude_Elementor_Post_Types. This PR allows us to safely rename classes and deprecate the old ones in favor of the new classes.
* Enhances code deprecation by safely redirecting to the new version of a class.
* applied the same mechanism as [Premium already has in place](https://github.com/Yoast/wordpress-seo-premium/blob/0997ce62fce8b77a8b97647b6596f7d713893816/config/dependency-injection/renamed-classes.php)
create an instance of the old class anywhere in php code that's being used. for instance, add this line:
`$deprecated = new \Yoast\WP\SEO\Integrations\Third_Party\Elementor_Exclude_Post_Types();`
to the …
> P2 1105 correctly deprecate elementor exclusions

- src/integrations/front-end-integration.php
- src/surfaces/values/meta.php
- tests/unit/integrations/front-end-integration-test.php
* Fixes passing the context correctly to the presenters filter.
* This is tested with https://github.com/Yoast/wordpress-seo-local/pull/2294/files
* SEO data from addons when viewed in the REST API.
> [P2-1109] Fix passing context to get presenters

- src/helpers/wordpress-helper.php
- src/integrations/blocks/block-categories.php
- src/surfaces/helpers-surface.php
- tests/unit/helpers/wordpress-helper-test.php
* 
* Fixes an unreleased bug where a deprecation warning was shown when calling the WordPress helper using the `YoastSEO()->helpers->wordpress` helpers surface.
*
* Make sure that you have Local SEO 14.0-RC1 or later installed.
* Although it is a fix in WordPress SEO, this bugfix can best be tested using Local SEO, since we use the `wordpress` helper surface in its code. 
* Make sure that you have the Query monitor plugin installed.
* Go to any page on your website (on the frontend of your website).
* You should get this PHP deprecation warning in Query monitor.
```
Service identifiers will be made case sensitive in Symfony 4.0. 
Using …
```
> Rename WordPress_Helper to Wordpress_Helper.

- packages/components/src/image-select/ImageSelect.js
- packages/components/tests/ImageSelectTest.js
- packages/components/tests/__snapshots__/ImageSelectTest.js.snap
* The ImageSelect missed a button text for screenreaders. 
* [@yoast/components] Fixes a bug where the ImageSelect did not a have a screen reader text.
* The ImageSelect component is ready to receive an alt text for the image, but this has to be provided at the places of implementation.
* Checkout this branch and go to one of the places where the ImageSelect component is used, e.g. the Facebook preview.
* Inspect the image preview in the dev tools or use Voice Over on Mac and make sure the image preview has focus. 
* When there's no image selected, the screen reader should say: "select image". 
* When an image is selected, the screen reader should say: "replace image".
QA …
> Add screen reader text to image select button

- src/generators/schema/breadcrumb.php
* Prevent removing the last breadcrumb if there is only one.
* Fixes a bug where paginated static frontpages would fail to output a valid breadcrumb.
* Some plugins / themes will allow a static frontpage to be paginated. Our code did not account for that and we would strip the breadcrumbs on such paginated frontpages.
* This fix is a bandaid and extended an already fairly complex logic check. I feel this should be rewritten at some point.
Follow these steps with and without this fix and check the breadcrumbs in the schema on the frontpage.
* Set your frontpage to be a static page in Settings -> Reading
* Navigate to `http://basic.wordpress.test/page/2` and make sure it …
> IM-465 Prevent an empty breadcrumbs array on a paginated static frontpage

- packages/yoastseo/spec/fullTextTests/runFullTextTests.js
- packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
- src/deprecated/src/conditionals/norwegian-readability-conditional.php
*
* Removes the Norwegian readability feature flag.
* [yoastseo] Removes the Norwegian readability feature flag and deprecates the Norwegian readability feature flag conditional.
*
* Set your site to Norwegian (Norsk Bokmål).
* Open/create a post and add a text of at least 300 words.
* Make sure that the transition words, passive voice, and consecutive sentences assessments show up.
* Add the word `eansett` to the text. Make sure that it's detected by the transition word assessment.
* Add the sentence 'Oppgaven vil bli gjort.`. Make sure that it's detected by the passive voice assessment.
* Remove all of your text and add the sentences `En katt. En hund. En hest.`. Make …
> Remove Norwegian readability feature flag

- packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
- packages/schema-blocks/src/core/blocks/BlockLeaf.ts
- packages/schema-blocks/src/leaves/blocks/BlockElementLeaf.ts
- packages/schema-blocks/src/leaves/blocks/BlockRootLeaf.ts
*
* Fixes React's unique keys in the console (in development builds).
* Instead of fixing this for each instruction individually, I have chosen to surround all child elements of instructions with a Fragment to which I can assign a key. Since instructions are static, it doesn't really matter that I used the index as keys (something you should normally never do), because the order of blocks within instructions never change during runtime.
* Make sure premium is active.
* Add all jobs-blocks.
* Add a recipe block and add all possible child-blocks.
* Make sure there are no `Each child in a list should have a unique "key" prop` errors. …
> Added key props to all schema block instruction components

- src/integrations/admin/admin-columns-cache-integration.php
- tests/unit/integrations/admin/admin-columns-cache-integration-test.php
* Fixes https://github.com/Yoast/wordpress-seo/issues/16812
* Fixes https://yoast.atlassian.net/browse/QAK-2911
* Prevents indexable caching on every ajax call
* Prevents building of seemingly random indexable caches
* Fixes a bug where unrelated post queries were being done on ajax calls.
* Improves performance if the main query does not return posts.
In the current behavior, you can observe that an ajax heartbeat request will enter the `fill_cache()` method without any posts in the main query. And because of `$wp_query->get_posts` we will query for the 10 most recent posts and put them in the indexable cache. This seems useless on heartbeat requests as that cache is not used at all.
This behavior would be fixed by any of the …
> P2-1115 Improve some performance for AJAX calls and empty WP_Queries

- packages/js/src/containers/DocumentSidebar.js
- packages/js/src/containers/PrePublish.js
- packages/js/src/decorator/gutenberg.js
- packages/js/src/helpers/addCheckToChecklist.js
- packages/js/tests/containers/mockSelectors.js
* This PR removes the following console warning:
> wp.data.select( 'core/editor' ).getBlocks` is deprecated. Please use `wp.data.select( 'core/block-editor' ).getBlocks` instead.
* Use the new block editor store to get Blocks, instead of the deprecated core editor store.
* replaced core/editor with core/block-editor where getBlocks was used.
* renamed variables to follow suit
* updated unit tests
No errors or console warnings should be visible when using these features:
* Regression test for Document Sidebar
* Regression test for PrePublish checks
* Regression test for annotations
* Regression test for schema blocks (behind feature toggle) …
> P2-1133 update core/editor getBlocks deprecation

- src/integrations/front-end/wp-robots-integration.php
- tests/unit/integrations/front-end/wp-robots-integration-test.php
*
* Fixes a bug where the `robots` meta tag could have incorrect values if users called the `wp_robots` filter to set certain values to `false`. Props to [Roy-Orbison](https://github.com/Roy-Orbison).
**Copied from the issue**: 
* The `wp_robots` filter is applied in WP core's `wp-includes/robots-template.php` and it ignores falsey values in the array that aren't strings. 
* This means that a filter added to this hook that sets the `index` key to `true` and `noindex` to `false` gets broken by `Yoast\WP\SEO\Integrations\Front_End\WP_Robots_Integration::enforce_robots_congruence` because [it (incorrectly) assumes](https://github.com/Yoast/wordpress-seo/blob/595e98bd530d24fc327b44d993df5b0cd11ed87e/src/integrations/front-end/wp-robot …
> Fix incorrect robots tag generation

- src/config/researcher-languages.php
- src/helpers/language-helper.php
- tests/unit/helpers/language-helper-test.php
*
* Fixes a bug where the keyphrase assessments would not load when the site language is set to Slovak.
* [yoastseo] Fixes the Slovak feature flag not working correctly, by only adding 'sk' to array of languages with word form support, function word support and researcher support if the Slovak feature flag is enabled.
*
* Set your site to Slovak (Slovenčina).
* Open a post with some text.
* Set a keyphrases.
* You shouldn't see any errors in the keyphrase analyses.
*
*
Fixes #
> Fix Slovak feature flag

- src/actions/indexing/indexable-general-indexation-action.php
- tests/unit/actions/indexing/indexable-general-indexation-action-test.php
* We want to avoid duplicate database queries wherever possible. To do this we can store the result in a transient. We already do this for the unindexed counts for the other indexing actions. This PR adds it for the general indexing action as well.
* Prevents some superfluous database queries for our indexables, preventing some unnecessary load on the database.
*
* Checkout `trunk` or use a previous version of the plugin.
* Make sure that you have the Query Monitor plugin installed and activated.
* Go to the SEO tools page (_SEO_ > _Tools_ in your WP admin).
* Query Monitor should report duplicate queries.
* Checkout this branch or use the RC in which you should test this …
> Store the result count of the general indexing action in a transient.

- composer.json
- src/actions/indexing/abstract-indexing-action.php
- src/actions/indexing/abstract-link-indexing-action.php
- src/actions/indexing/indexable-general-indexation-action.php
- src/actions/indexing/indexable-post-indexation-action.php
- src/actions/indexing/indexable-post-type-archive-indexation-action.php
- src/actions/indexing/indexable-term-indexation-action.php
- src/actions/indexing/indexation-action-interface.php
- src/actions/indexing/limited-count-trait.php
- src/actions/indexing/post-link-indexing-action.php
- src/actions/indexing/term-link-indexing-action.php
- src/commands/index-command.php
- src/helpers/indexable-helper.php
- src/helpers/indexing-helper.php
- src/integrations/admin/background-indexing-integration.php
- tests/unit/actions/indexing/indexable-post-indexation-action-test.php
- tests/unit/actions/indexing/indexable-term-indexation-action-test.php
- tests/unit/actions/indexing/post-link-indexing-action-test.php
- tests/unit/actions/indexing/term-link-indexing-action-test.php
- tests/unit/helpers/indexing-helper-test.php
- tests/unit/integrations/admin/background-indexing-integration-test.php
*
* Partially fixes a bug where queries due to the background indexation would put a lot of strain on the database.
* In step 3 on the issue we say: "Move `if ( $total > 0 && $total < $this->get_shutdown_limit() )` to the indexing helper and call it something like: `should_index_on_shutdown()`." We decided to not this function, but create it in the background indexing integration instead, because it has all logic regarding the indexing on shutdown.
* Added an `Abstract_Indexing_Action` class to reduce duplicate code in relation to counting unindexed objects.
* Split up `get_query` in indexing actions in `get_select_query` and `get_count_query` for better eadability.
* Count queries will now set the transient to 0 before counting …
> Refactored logic for background indexation to reduce count queries

- src/actions/indexing/indexable-post-indexation-action.php
- tests/unit/actions/indexing/indexable-post-indexation-action-test.php
* 
* Improves performance of an SQL query used to find the number of unindexed posts in the indexable table.
* This improvement really concerns the `COUNT` query. It hardly has an impact on the `SELECT` query when you pass a (default) limit of 25, but for code consistency I decided to keep the two queries the same.
**Preparations**
* Test on a big site with +- 10.000 posts.
* To generate posts in Docker, you can run the following commands:
* `docker exec  -ti basic-wordpress /bin/bash -c 'php -d memory_limit=512M "$(which wp)" package install git@github.com:Yoast/wp-cli-faker.git --allow-root'`
* `docker exec -it basic-wordpress wp faker core content --posts=10000 …
> Improve performance for the query to find unindexed posts

- packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
- packages/yoastseo/src/scoring/productPages/contentAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/productPages/seoAssessor.js
*
* [yoastseo] Adds assessors for product pages.
* [yoastseo] Removes the outbound links and internal links assessments from the SEO analysis on product pages. Removes the Flesch Reading Ease assessment and the consecutive sentences assessment from the readability analysis on product pages.
The assessors are not exported via the index so that they don't get bundled for use in the Yoast SEO plugin. This is important because we will not use these assessors in the plugin itself, but only in extensions and other integrations.
I've combined LINGO-961 with LINGO-911 (removing assessments) because having some visible differences in the product page assessors makes testing easier. …
> Add product assessors

- packages/js/src/initializers/estimated-reading-time.js
* Improve (typing) performance in all supported editors, especially the block editor.
* Introduces a `debounce` on getting content from the store, this may or may not improve typing performance in all supported editors, especially the block editor
* The `subscribe()` function triggers as soon as a user even looks at their monitor. This would cause multiple `select( "" ).getEditedPostAttribute( "" )` per second and these were more expensive than the eventual reading time calculations. So for the Elementor and Block editors (that use the `subscribe()` function) I moved all logic into a debounce.
* I used a debounce of 1.5 seconds with a forced execution after 3 seconds. This means that as long as `subscribe()` is firing, the …
> P2-1129 Improve editor performance by reducing estimated reading time calculations

- src/actions/indexing/indexable-general-indexation-action.php
- tests/unit/actions/indexing/indexable-general-indexation-action-test.php
* Because the general indexing count transient is not deleted on indexation, the total unindexed count would return a small number, meaning that on each admin request the background indexation would be run, and this would clear out all count transients for the individual indexation actions, causing expensive count queries to be run on each request.
* This bug was introduced in https://github.com/Yoast/wordpress-seo/pull/17264 because we forgot the delete the transient upon indexing the general indexation.
* Fixes a bug where the background indexing would keep running on each request because a wrong number of general pages was returned in the count. 
*
* Make sure Query …
> P2-1155 Fixes a bug where the incorrect amount of unindexed general pages was returned

- src/commands/index-command.php
- tests/unit/commands/index-command-test.php
*
* Adds post link indexing and term link indexing to the `wp yoast index` WP-CLI command.
*
* Run the `wp yoast index` cli command.
* For docker that is `docker exec -it -u www-data basic-wordpress wp yoast index`
*  Make sure the post- and term-links are indexed.
*
*
Fixes #
> P2-1153 Added post- and term-link indexing to the index cli command

- packages/yoastseo/spec/scoring/assessments/seo/PageTitleWidthAssessmentSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/productPages/seoAssessor.js
*
* [yoastseo] Adds custom config for `TitleWidth` assessment for product pages and adds extra feedback string in the assessment file for when short title width is not penalized with a bad score.
*
**Note: Currently this PR cannot be tested in Product pages since the assessors for the product pages haven't been used anywhere yet. Hence, for now we can test this PR in normal pages by adding product pages configuration in `seoAssessor.js` for normal analysis**
* Set the `allowShortTitle` to true in `scoring/seoAssessor.js` file for `TitleWidth` assessment and add this config `{ scores { widthTooShort: 9 } }` (don't commit anything): 
* Create a post and …
> Add product pages config for SEO title width assessment

- packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/productPages/seoAssessor.js
*
* Lowers the minimum recommended text length for product pages.
* [yoastseo] Adds text length score boundaries config for product pages to the product page SEO assessors.
*
* For now, the changes can only be tested by temporarily adding the config of the product config to the non-product assessors. 
* Add the following as a parameter to `TextLength` in `yoastseo/src/scoring/seoAssessor.js`: `{
recommendedMinimum: 200,
slightlyBelowMinimum: 150,
belowMinimum: 100,
veryFarBelowMinimum: 50,
}` 
* Build the plugin and add a text of less than 100 words. The assessment should return a red bullet and the following feedback: `Text length: the text contains X words. This is far …
> Adapt config for product pages text length assessment

- packages/yoastseo/spec/scoring/assessments/readability/subheadingDistributionTooLongAssessmentSpec.js
- packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
- packages/yoastseo/src/scoring/assessments/readability/subheadingDistributionTooLongAssessment.js
- packages/yoastseo/src/scoring/productPages/contentAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
*
* [yoastseo] Adds an extra check in the `SubheadingsDistributionTooLong` assessment's applicability where we can adjust whether the assessment should appear in a short text analysis or not.
*
**Note: Currently this PR cannot be tested in Product pages since the assessors for the product pages haven't been used anywhere yet. Hence, for now we can test this PR in normal pages by adding product pages configuration in `seoAssessor.js` for normal analysis**
* Set the `shouldNotAppearInShortText` to true in `scoring/contentAssessor.js` and `scoring/cornerstone/contentAssessor.js` file for `SubheadingDistributionTooLong` assessment by adding this config `{ …
> Add extra check for subheading distribution assessment's applicability

- src/actions/indexing/abstract-indexing-action.php
- src/actions/indexing/indexable-general-indexation-action.php
- src/actions/indexing/indexable-post-type-archive-indexation-action.php
- src/actions/indexing/indexation-action-interface.php
- src/actions/indexing/limited-indexing-action-interface.php
- src/helpers/indexing-helper.php
* We can't add methods or arguments to interfaces that are used in other plugins, since that can lead to backwards compatibility problems. E.g. older versions of plugins that do not implement this new interface leading to fatal errors. In this case a method was added to the `Indexation_Action_Interface`, which is also used in WordPress SEO Premium.
* [wordpress-seo-premium] Fixes an unreleased bug where updating WordPress SEO before WordPress SEO Premium lead to a fatal error.
* We can't change the `Indexation_Action_Interface` without backwards compatibility issues. However, we can add a new interface.
* Make sure that you have WordPress SEO Premium, version 16.8 or …
> Moves limited indexation count to new interface to avoid complication with backwards compatibility.

- packages/yoastseo/spec/scoring/cornerstone/relatedKeywordAssessorSpec.js
- packages/yoastseo/spec/scoring/relatedKeywordAssessorSpec.js
- packages/yoastseo/src/scoring/cornerstone/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/relatedKeywordAssessor.js
*
* Removes image count assessment from related keyphrase assessment.
* [yoastseo] Removes image count assessment from related keyphrase assessment.
*
* Build the free plugin
* Run `composer require yoast/wordpress-seo:dev-LINGO-978-delete-unnecessary-assessment-from-assessors@dev`
* Build the premium plugin
* Create a post and add some text
* Set a keyphrase and a related keyphrase
* Confirm that in the metabox for related keyphrase analysis, `Images` assessment doesn't appear
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-978
> Delete image count assessment from related keyphrase assessors

- src/actions/indexing/abstract-link-indexing-action.php
- tests/unit/actions/indexing/post-link-indexing-action-test.php
- tests/unit/actions/indexing/term-link-indexing-action-test.php
*
* Reverts to using the total count for post-links and term-links in background-indexing, instead of a limited select, because it was actually was harmful to the performance.
*
* Make sure Query monitor is installed.
* Delete all transients.
```
DELETE FROM wp_options
WHERE option_name LIKE '%_transient_%'
```
* Visit the WordPress dashboard.
* The following queries should have run on that request:
```
SELECT COUNT(T.term_id)
FROM wp_term_taxonomy AS T
LEFT JOIN wp_yoast_indexable AS I
ON T.term_id = I.object_id
AND I.object_type = 'term'
AND I.permalink_hash IS NOT NULL
WHERE I.object_id IS NULL
AND taxonomy IN ('category', 'post_tag', 'post_format')
```
```
SELECT …
```
> Use total counts for unindexed links

- packages/yoastseo/spec/scoring/storeBlog/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/storeBlog/seoAssessorSpec.js
- packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/storeBlog/seoAssessor.js
The store blog assessors were using product page values for the title width assessment. They should use regular values.
*
* n/a
* Fixes incorrect assessors values. The store blog assessor was using values for product pages for the title width assessments. It should use regular values.
* In `apps/content-analysis/src/App.js` on the line before `worker.initialize( config )`, please add this:
```
config.customAnalysisType = "storeBlog";
```
* Confirm that the title width assessment behaves as specified here (both regular & cornerstone): https://github.com/Yoast/javascript/wiki/Scoring-SEO-analysis#16-title-width
* …
> Use non-product-page values on store blog assessors

- packages/js/src/analysis/blockEditorData.js
- packages/js/src/components/SettingsReplacementVariableField.js
- packages/js/src/initializers/estimated-reading-time.js
- packages/js/src/post-edit.js
- packages/js/src/redux/selectors/results.js
- packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
- packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
* Improves overall performance and responsiveness in Gutenberg.
This PR makes 3 main changes to improve overall performance in Gutenberg
1. The anonymous callback functions in the replacement variable editor were changed to methods to avoid unnecessary rerenders and garbage collection of previously created functions.
2. The gutenberg data collector class was changed to only call `getEditedPostContent` once as this is the most expensive call, once gotten this data is then reused in every other function.
3. The estimated reading time analysis is changed to first check if the record is changed before getting the edited post content ( see above ) and loading is delayed by 500ms to avoid blocking the initial render of Gutenberg …
> Gutenberg performance improvements

- packages/js/src/components/fills/MetaboxFill.js
- packages/js/src/components/fills/SidebarFill.js
*
* Fixes duplicate key errors in the console.
*
* Install and activate:
* Yoast SEO Premium (Branch: P2-1178-add-keys-to-sidebar-items)
* Yoast SEO News (Branch: P2-1178-add-key-to-sidebar-item)
* Yoast SEO Woocommerce (Latest trunk)
* Yoast SEO Local (Latest trunk)
* Yoast SEO Video (Branch: P2-1178-add-key-to-sidebar-item)
* Woocommerce
* Open the editor, make sure there are no duplicate key errors and each sidebar-item is only displayed once.
* Install and activate:
* Yoast SEO Premium (Latest RC)
* Yoast SEO News (Latest RC)
* Yoast SEO Woocommerce (Latest version)
* Yoast SEO Local (Latest version)
* Yoast SEO Video …
> Added keys to sidebar items

- packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
- packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
*
* Removes `Images` assessment from related keyphrase analysis.
*
**Test in Shopify**
This PR can be tested together with this PR https://github.com/Yoast/shopify-seo/pull/145
* Make sure that `Images` assessment doesn't show in the side bar for related keyphrase analysis both in normal and cornerstone content
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-980
> Delete images assessment from related keyphrase assessors

- packages/yoastseo/spec/scoring/assessments/readability/ListAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
*
* [yoastseo] Adds shortlinks to the feedback text of the Lists assessment.
*
* In apps/content-analysis/src/App.js on the line before `worker.initialize( config )`, please add this (don't commit):
```
config.customAnalysisType = "productPage";
```
* Run the content analysis app and add some text
* The Lists assessment should show up with a red bullet
* However over the links in the feedback text and make sure that the first link is `https://yoa.st/shopify38` and the second one is `https://yoa.st/shopify39`
*
*
Fixes …
> Add shortlinks to the Lists assessment

- src/actions/indexing/abstract-link-indexing-action.php
- src/actions/indexing/indexable-post-indexation-action.php
- src/actions/indexing/indexable-post-type-archive-indexation-action.php
- src/actions/indexing/indexable-term-indexation-action.php
- src/actions/indexing/post-link-indexing-action.php
- src/actions/indexing/term-link-indexing-action.php
- tests/unit/actions/indexing/indexable-post-indexation-action-test.php
- tests/unit/actions/indexing/indexable-post-type-archive-indexation-action-test.php
- tests/unit/actions/indexing/indexable-term-indexation-action-test.php
- tests/unit/actions/indexing/post-link-indexing-action-test.php
- tests/unit/actions/indexing/term-link-indexing-action-test.php
*
* Speeds up load times of admin pages by preventing unnecessary counts of unindexed objects.
*
* Make sure query monitor is enabled.
* Make sure your entire site is indexed.
* Clear all transients in the database.
```sql
DELETE FROM wp_options
WHERE option_name LIKE '%_transient_%'
```
* Visit the Wordpress Dashboard.
* Now you have 15 minutes to do the following steps to test it reliably, because of the duration of the limited unindexed objects transients.
* De-activate Yoast SEO and Yoast SEO Premium.
* Create a new category.
* Enable Yoast SEO and Yoast SEO Premium.
* Make sure the background-indexing is run by deleting the …
> Don't delete transients when no indexables have been created

- admin/class-yoast-notification-center.php
* While logging SQL queries I noticed that the Yoast user notifications get stored on every shutdown with a SQL UPDATE statement, even if there were no changes. This PR checks if there are any new or resolved notifications before allowing the updates to happen. 
* Non-user-facing: prevents updating the user notifications if there were no changes.
* We use the `$new` array and `$resolved` int to keep track of changes to the notifications in the current request. So I used those to determine if an update needs to be done.
* Dismissals are stored in separate calls.
* Because the notification updates only happened on shutdown calls, Query Monitor would never notice them unless persistent logging was enabled.
This PR can be acceptance …
> Check if there are changes to Yoast notifications before updating

- packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
- packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
*
* [yoastseo] Adjust recommended text length values for non-cornerstone collections pages so that they are lower than the cornerstone ones.
*
* In apps/content-analysis/src/App.js on the line before worker.initialize( config ), please add this (don't commit):
```
config.customAnalysisType = "collectionPage";
```
* Make sure the cornerstone toggle is off
* Add a text of 80 words, e.g. `Figure out what you want to write. The large field of creative writing splits into subcategories (fiction, poetry, creative nonfiction) and there are even specialized genres (sci-fi, mysteries, experimental… the list goes on). Figure out what you want to write. Write what you would want to …
> Adjust recommended text length values for non-cornerstone collections pages

- admin/class-admin-init.php
- admin/class-suggested-plugins.php
*
* Updated the message that recommends you to install WooCommerce SEO when WooCommerce is installed.
* Removed `yoast_plugin_suggestions_notification` and  `get_yoast_seo_suggested_plugins_notification` from `WPSEO_Admin_Init`, because the coee is never executed. [This function](https://github.com/Yoast/wordpress-seo/pull/17313/files#diff-12ee615e5fe8e5cae1aa9d83ab002c96743a69001694a8c86639744193a4d042L91) will always return an empty array, therefore the following loop does nothing. The reason `get_plugins_with_dependencies` will always return an empty array is because `register()` is never called on `$checker`, which is necessary to instatiate the class' functionality. These functions are meant to register notifications …
> Updated message for recommended addons with dependencies

- inc/class-upgrade.php
- src/integrations/cleanup-integration.php
- tests/unit/integrations/cleanup-integration-test.php
* With this PR we want to add a cron job that will gradually clean in chunks every orphaned entry from the seo_links and indexable_hierarchy and prominent_words tables. Those orphaned entries can be orphaned because the respective entries from the indexable table have been previously cleaned with https://github.com/Yoast/wordpress-seo/pull/17234
* That cron job will unregister itself when there's no deletion in those tables, which means that when the cleanup is complete, we no longer query for orphaned entries
* Although the original task at hand talked about orphaned entries due to cleanup of the shop_order indexables, this PR cleans up EVERY orphaned entry in those table, not specifically shop_order indexables.
* Cleans up …
> Delete orphaned entries from Yoast tables with a scheduled action

- packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
- packages/yoastseo/src/worker/AnalysisWebWorker.js
*
* [yoastseo] Adds functionality for the webworker to also set custom options when loading the custom assessors for the SEO analysis (regular/cornerstone), the SEO analysis for related keyphrases (regular/cornerstone), and the readability analysis (regular/cornerstone).
*
* Run `yarn test` and make sure everything is passing.
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-990
> Also set custom options when setting the custom assessors

- admin/class-bulk-editor-list-table.php
* The `Save all` button(s) in the bulk editor have been broken for a while. This PR fixes this problem, and accidentally also fixes the updating of the `Existing Yoast SEO <type>` column.
* Fixes a bug where the `Save all` button in the bulk editor did not work.
* Fixes a bug where the `Existing` column in the bulk editor did not update after save.
* The order of type & id was wrong in the PHP output, so JavaScript was not able to identify the needed fields.
* Verify that the bulk save of both titles and descriptions works.
* It is currently [expected](https://github.com/Yoast/wordpress-seo/issues/7829) that the `Existing` column does not show the default value if it was …
> Fix bulk editor `Save all` button and column update

- packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
- packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
- packages/yoastseo/src/scoring/productPages/contentAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/productPages/seoAssessor.js
* We want the possibility to pass different shortlinks to the options of the assessor.
* [yoastseo] Replaces assessment shortlinks that are passed to the assessment constructors in the product assessors with variables.
*
*
*
*
Fixes #
> Replace assessment shortlinks in product assessors with variables

- packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
*
* Fixes an unreleased bug where a post's slug could not be updated in the Google preview.
* 
* Try to update the slug.
* The slug should have changed too `[object Object]`.
* Check the developer console, it should have the following error:
```
analysis-170-RC1.js:344 Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': function () {
return null;
} could not be cloned.
```
* Edit the post in Elementor.
* Try to update the slug.
* The slug should not update.
* Check the developer console, it should have the following error:
```
Uncaught TypeError: r.trim is not a function
```
* Edit the post in the block editor.
* Try to update the slug.
* …
> Use the event's target value instead of the event itself when the slug has changed.

- admin/class-yoast-notification-center.php
* In https://github.com/Yoast/wordpress-seo/pull/17297 we attempted to make notifications a bit more efficient, but it turns out this breaks notifications on the posts overview page (and other pages as well).
* Fixes a bug where the redirect-notification/upsell would not be shown when deleting/trashing a post/term.
*
* On the posts overview page, trash a post, make sure you get the upsell notification for premium.
* Repeat the same process with premium active and make sure you get the notification to create a redirect or serve a 410 header.
*
* …
> P2-1212 Revert 17297

- packages/yoastseo/spec/scoring/cornerstone/relatedKeywordAssessorSpec.js
- packages/yoastseo/src/scoring/cornerstone/relatedKeywordAssessor.js
*
* Sets `isRelatedKeyphrase` to `true` for keyphrase length assesment in related keyword assessor in cornerstone.
*
* Build the free plugin from this branch
* In `wordpress-seo-premium`, run this command `composer require yoast/wordpress-seo:dev-LINGO-983-adjust-keyphrase-length-config-in-related-keyword-assessor@dev` and build the premium plugin
* Make sure that the Free and Premium plugins are activated.
* Set the `Cornerstone content` toggle on.
* Set a related keyphrase with one word.
* Make sure the feedback is `Keyphrase length: Good job!`
* Delete the related keyphrase.
* Confirm that the feedback is `Keyphrase length: Set a keyphrase in order to calculate your …
> Set isRelatedKeyphrase to true in related keyword assessor for keyphrase length assesment

- wp-seo-main.php
* Both Yoast SEO and our addons register their autoloaders immediately when loaded. Since many of our addons now include Yoast SEO as a dev-dependency this can cause free classes to be loaded from the vendor directory of one of our addons as opposed to it's own files if the autoloader from that addon was loaded last.
* Fixes an autoloading problem when using a development version of any Yoast addon.
* After all plugins are loaded the Yoast SEO autoloader unregisters and reregisters itself with the `true` argument to ensure it takes priority.
* Load this branch and, for example, Yoast SEO WooCommerce from GitHub. It should not cause any fatal errors. …
> Fix autoloading priority in development builds

- tests/unit/helpers/open-graph/image-helper-test.php
- tests/unit/helpers/twitter/image-helper-test.php
- tests/unit/inc/sitemaps/sitemaps-admin-test.php
- tests/unit/presentations/indexable-presentation/open-graph-locale-test.php
* Correctly uses the appropriate methods for testing filters rather than mocking `apply_filters` directly.
* Fixes several unit tests to use the correct methods.
* The unit tests should pass.
* There should be no unit tests that mock `apply_filters`.
* None, this only impacts unit tests.
* Unit tests.
> Test filters correctly and get rid of a few partial mocks along the way

- lib/orm.php
* Because inserting multiple rows with a single query instead of using multiple INSERT queries is much more performant in most cases, we needed an ORM function that will enable our classes to perform those batch INSERT queries. This PR creates that function, called `insert_many()`.
* Adds a function in our ORM model that enables using a batch INSERT query
* The new `insert_many()` function takes an array of model instances as params
* If one of those model instances is not new (so, it's to be **updated** instead of **inserted**), throw an exception as this function should be used only for INSERT queries.
* The reason we made it into a pure INSERT function is that if things went wrong somewhere we wouldnt be able to identify if it …
> Create insert_many() function for bulked INSERT INTO queries

- packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
- packages/yoastseo/src/languageProcessing/languages/es/config/functionWords.js
- packages/yoastseo/src/languageProcessing/languages/id/config/functionWords.js
- packages/yoastseo/src/languageProcessing/languages/nl/config/functionWords.js
- packages/yoastseo/src/languageProcessing/languages/ru/config/functionWords.js
*
* [yoastseo] Adds a missing array entry that caused time-related words in Dutch, English, Indonesian, Russian, and Spanish to not be counted as function words.
* Improves the filtering out of function words in Dutch, English, Indonesian, Russian, and Spanish by including time-related words like 'minute'.
*
* Set your site to English, open a post and set `minute` as your keyphrase. Make sure that the Function words in keyphrase assessment gets triggered.
* Set your site to Dutch, open a post and set `minuut` as your keyphrase. Make sure that the Function words in keyphrase assessment gets triggered.
* Set your site to Indonesian, open a post and set `detik` as your …
> Adds time-related words to English, Dutch, Indonesian, Russian and Spanish function words

- lib/orm.php
- tests/unit/doubles/lib/orm-double.php
- tests/unit/repositories/orm-test.php
* We want to fix insert_many() to cover cases where model instances are having different set of dirty_values among them, as per Herre's input on https://github.com/Yoast/wordpress-seo/pull/17353
* We also improve exception handling as per Hans Christiaan's input on https://github.com/Yoast/wordpress-seo/pull/17360
* Enhances our database access layer to allow batch inserts.
* The new `insert_many()` function takes an array of model instances as params
* If one of those model instances is not new (so, it's to be **updated** instead of **inserted**), throw an `InvalidArgumentException` as this function should be used only for INSERT queries.
* The reason we made it into a pure INSERT function is that if things went wrong somewhere …
> P2 1229 insert many dirty fields

- src/builders/indexable-link-builder.php
- src/repositories/seo-links-repository.php
- tests/unit/builders/indexable-link-builder-test.php
*
* Improves the performance of saving posts, especially on posts with a lot of links.
* [Added `delete_all_by_post_id_where_indexable_id_null` function. ](https://github.com/Yoast/wordpress-seo/pull/17357/files#diff-3b3c3fe90f75b2e93fe8ed4d29c14aebd7f0924f5b198c9cea29f9ccbce90b86R375) The seo links column did not have a reference to an indexable before, now that we only save new links and delete old ones, we do not want to delete all links by post id, because it would delete the seo links that properly link to an indexable as well.
* I moved the function call to the start of the function, so all old seo links are removed before we retrieve the seo links for the post so we save all seo-links in the new format (with an indexable …
> P2-1131 Only update necessary links

- src/integrations/admin/indexing-notification-integration.php
- tests/unit/integrations/admin/indexing-notification-integration-test.php
* We don't want to show the SEO optimization notification when we're not on a production site.
* Stops showing the SEO Optimization notification on non-production sites.
* Added a `Environment_Helper` param in the `Indexing_Notification_Integration` constructor, to be able to use the helper's method in the latter's `should_show_notification()` function 
* Checked that we don't construct the `Indexing_Notification_Integration` anywhere in the code that would break by the above addition. Also checked Premium and the add-ons
With trunk/last plugin version:
* Go to Tools->Yoast Test and **Reset Indexables tables & migrations**
* Add `define( 'WP_ENVIRONMENT_TYPE', 'staging' …
> Hide SEO Optimization notification on non-prod sites

- packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
⚠️ Please rebase this PR to the `release/17.1` branch before merging it ⚠️ 
* Google changed the look of their search results, so we update our preview to closer resemble that current look.
* [@yoast/search-metadata-preview] Updates the styling of our Google preview to reflect the updated styling of the Google search results.
*  Updates the styling of our Google preview to reflect the updated styling of the Google search results.
* Couldn't find the exact separator for mobile, so picked the closest looking one for now.
* Compare our Google preview to both the desktop an mobile results from Google
* The color and font size of the Title on mobile should now be the same
* …
> P1-535 Update text colors, sizes and separators on Google preview

- packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
*
* [yoastseo] Adds a missing plural variant of a feedback string for the keyphrase length assessment in product pages.
*
* Activate the Free plugin and WooCommerce SEO
* Create a product page
* Add the keyphrase `cat`. The keyphrase length assessment should return the following feedback: `Keyphrase length: The keyphrase is 1 word long. That's shorter than the recommended minimum of 4 words. Make it longer!`
* Change the keyphrase to `small cat`. The keyphrase length assessment should return the following feedback: `Keyphrase length: The keyphrase is 2 words long. That's shorter than the recommended minimum of 4 words. Make it longer!` (make sure that it says `words` …
> Fix an incorrect feedback string for the keyphrase length assessment

- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/productPages/seoAssessor.js
*
* [yoastseo] Replaces Images assessment `countVideos` value that is passed to the assessment constructor in the product assessors with a variable. 
*
* This PR should be tested with [this accompanying PR](https://github.com/Yoast/wpseo-woocommerce/pull/716).
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-1011
> Replace images assessment `countVideos` value in product assessors with a variable

- packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper1.js
- packages/yoastseo/spec/languageProcessing/languages/fa/ResearcherSpec.js
- packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/fa/config/sentenceLength.js
*
* Improves the sentence length assessment for Farsi by increasing the maximum recommended sentence length to 25 words.
* [yoastseo] Changes the maximum recommended sentence length in Farsi to 25 words.
*
* Enable the FARSI_SUPPORT feature by adding define( 'YOAST_SEO_FARSI_SUPPORT', true ); in basic-wordpress-config.php file
* Change the site language to Farsi (فارسى)
* Create a new post and paste this sentence: .سگ گربه اسب گاو خرگوش همستر خوک مرغ جغد موش خوکچه هندی پروانه تک شاخ خرس اردک جوجه تیغی پشه موش روباه شیر گوزن
* The sentence length assessment should return a green bullet 
* Change the sentence to: .گربه سگ اسب گاو خرگوش همستر خوک مرغ جغد موش خوکچه هندی …
> Change recommended maximum sentence length for Farsi to 25 words

- packages/yoastseo/spec/fullTextTests/testTexts/index.js
- packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
- packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
*
* [yoastseo] Makes Consecutive sentence, Passive voice and Transition words assessments available for Farsi when the Feature flag is enabled.
* The Farsi papers for full text tests are skipped for now. This is because they will fail for Transition words, Consecutive sentences and passive voice assessments since we still don't have the necessary configs and helpers for those assessments in Farsi. 
* The Farsi papers should be added back when the Transition words, Consecutive sentences and passive voice assessments are already implemented. I add the step to check for this in [this issue to remove the feature flag](https://yoast.atlassian.net/browse/LINGO-1010).
* Currently, when we enable the feature, there are going to be errors …
> Make Consecutive sentence, Passive voice and Transition words assessments available for Farsi

- packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
* The mobile title in the snippet preview was increased in font size and line height recently. However the space for this title was limited. This resulted in a title that never spanned two lines, while it should. So that needed to be fixed.
*
* Stayed with pixels since Google is using pixels as well
* Add a long SEO title in our snippet editor
* Verify that it spans two lines now
*
*
Fixes QA-2101
> Let mobile title span two lines again

- inc/class-upgrade.php
- inc/options/class-wpseo-option-titles.php
* Removes the `|` and `~` separators.
* Install Yoast SEO 17.0.
* Set your separator to either `|` or `~`.
* Upgrade to Yoast SEO 17.1
* Your separator should now be set to `-`.
* Visit the frontend
* There should be no `|` or `~` in your `<title>` element.
* Visit the separator settings
* You should not be able to select either `|` or `~`.
* The separator settings
* The 17.1 upgrade routine.
* Check if the separator replacement variable still works in the previews (Google, Facebook (Premium), Twitter (Premium)).
Fixes https://yoast.atlassian.net/browse/P2-1254
> Remove pipe and tilde separators

- packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
- packages/yoastseo/spec/scoring/collectionPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/storeBlog/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/storeBlog/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/storePostsAndPages/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/taxonomyAssessorSpec.js
- packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
- packages/yoastseo/src/scoring/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/seoAssessor.js
- packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/storeBlog/seoAssessor.js
- packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
- packages/yoastseo/src/scoring/taxonomyAssessor.js
*
* [yoastseo] Adds custom config for TitleWidth assessment in all SEO assessors so that short title is not penalized with a bad score.
* [search-metadata-previews] Adds custom config for `PageTitleWidthAssessment` so that the bar indicator under SEO title field shows green when short SEO title is set.
* Gives short SEO title width a green bullet in all content types.
*
**In regular analysis and taxonomy analysis:**
* Set two-word long title in SEO title field
* Make sure that SEO title width assessment returns with green bullet and gives feedback: `SEO title width: Good job!`
* Confirm that the indicator bar under the SEO title field also shows green …
> Do not penalize short title

- src/helpers/options-helper.php
* The default of the separator is `sc-dash`, which needs to be translated to `-` by doing a lookup in the separator options.
* If the real value wasn't present in the separator options then instead of doing a lookup for the default the default was immediately returned.
* Fixes "sc-dash" being used literally in cases where the chosen separator no longer exists.
* A second fallback has been added to use the first separator in cases where `sc-dash` has also been removed from the separator options. This could occur if that value is filtered out.
* See https://yoast.atlassian.net/browse/P2-1259 …
> P2-1259 fix default fallback of separator

- admin/class-yoast-notification-center.php
* Another attempt at reducing the UPDATE queries on every shutdown. Previous attempt was https://github.com/Yoast/wordpress-seo/pull/17297 and this failed because it did not account for live notifications like the premium redirects.
* Non-user-facing: prevents updating the user notifications if there were no changes.
* I chose another approach than the `$new` array and `$resolved` int checks. Instead, every method that updates notifications will now set `$notifications_need_storage` to true, which is used to check if storage needs updating.
Because the update happens on shutdown, it isn't easily tested with plugins like query monitor. So this is a small workaround.
* In …
> Reduce update queries on shutdown

- packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
- packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/contentAssessorSpec.js
- packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
- packages/yoastseo/src/scoring/cornerstone/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js
- packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessor.js
- packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js
* The parent class of the `Assessor` has three parameters, where the second one is the researcher. However, when we created the specific assessors based on the parent class, we didn't pass researcher in the parameter. So far we didn't have any bug reported in relation to this. But in principle we should also pass the researcher as the second parameter in all of the child classes.
* [yoastseo] Adds missing researcher parameter in assessors.
*
**In Free and Premium:**
* Turn on the cornerstone content toggle
* Smoke test some of the assessments (two or three) in SEO and Readability analysis
* Make sure there is no error in the console and that the assessments are working as …
> Add missing researcher parameter in assessors

- inc/class-upgrade.php
- src/integrations/cleanup-integration.php
- tests/unit/integrations/cleanup-integration-test.php
*
* Cleans up indexables for posts with `auto-draft` post-status.
* Refactored the way that indexables are cleaned up, all responsibility for cleaning up the indexable now lies with the `Cleanup_integration`.
* Make sure you have the yoast test helper installed and activated.
* Make sure you have `wordpress-seo-premium`'s `P2-1140-add-cleanup-tasks` branch checked out, built and activated.
* Check-out this branch and build the plugin, and make sure you visit an admin-page.
* Run the following query to add some invalid entries into the database that should be cleaned up by this PR (You should be able to the run the entire query at once):
```sql
INSERT INTO …
```
> P2 1140 cleanup auto draft indexibles

- lib/abstract-main.php
- src/integrations/third-party/elementor.php
- tests/unit/doubles/main-double.php
- tests/unit/main-test.php
*
* Added unit-tests for the surface API.
* Moved the initialization of `$social_is_enabled` and `$is_advanced_metadata_enabled` in the elementor integration to `init` instead of the constructor.
* Run `composer test`.
* Now add an exception to the constructor of a random helper to see it fail.
```
public function __construct() { throw new \Exception( "nope" ); }
```
* Run `composer test` and make sure it fails.
*
*
Fixes #
> Added unit test for surface api

- packages/yoastseo/spec/languageProcessing/languages/ru/helpers/internal/stemSpec.js
* [yoastseo] Expands Russian irregular nouns exception list.
* [Yoast SEO premium] Introduces word form support for more Russian irregular nouns.
*
* Run `yarn test` and make sure that everything passes.
**In Content-analysis app:**
* Set your website to Russian (ru)
* Add a text of min 300 words in the text field
* Turn the `Use morphology` on
* Set `мать` as the focus keyphrase
* Add these other forms of the word in the text: _матери, матерями, матерью_ and make sure that all 3 forms are recognised.
* Set `щенок` as the focus keyphrase
* Add these other forms of the word in the text: _щенята, щенка, щенке, щенятами_ and make sure that all 4 forms are recognised.
* Set …
> Expand list of irregular plurals for Russian

- src/integrations/admin/helpscout-beacon.php
* Add the HelpScout beacon to the workouts page.
* Load our help beacon on the workouts page.
* With this change, the beacon should show on the workouts page. 
* When premium is enabled, it should still show a beacon on the workouts page, this time the premium one.
Fixes #P2-1289
> P2-1289 - Add HelpScout beacon to workouts page

- packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper1.js
- packages/yoastseo/spec/languageProcessing/researches/keywordCountInUrlSpec.js
- packages/yoastseo/src/languageProcessing/researches/keywordCountInUrl.js
* The changes in this PR are adapted from this PR: https://github.com/Yoast/javascript/pull/19. 
* [yoastseo] Removes hyphens from a keyphrase for the Keyphrase in slug assessment. Also removes the functionality that would look for the keyphrase in the unparsed slug if it was not found in the parsed slug, as it is made redundant by the new functionality.
* Improves the accuracy of the Keyphrase in slug assessment by correctly detecting multi-word keyphrases with at least one hyphenated word in the slug.
* The functionality for searching for a keyphrase in the unparsed slug was removed because it is made redundant by the dehyphenating functionality.
* The function for dehyphenating keyphrases from the original PR was adapted so …
> Removes hyphens from the keyphrase before checking if slug contains keyphrase

- src/repositories/indexable-repository.php
*
* Fixes a bug where calling a removed method would cause errors.
* 
see https://github.com/Yoast/wordpress-seo-premium/blame/95056ecc0b5030ac7ea54297a78cf1d1a35278f8/src/integrations/admin/workouts-integration.php#L193
* run premium workouts; they use the method that was removed.
*
* any code using `ensure_permalinks` will now get a deprecation warning.
This is an internal method used by _far too much_ external code, but with the deprecation added in this PR, the correct (new) behavior of upgrading the requested indexable (p2-1161) is …
> P2-1299 deprecate ensure_permalink method

- admin/class-premium-upsell-admin-block.php
- src/actions/indexing/indexable-post-indexation-action.php
- src/builders/indexable-post-builder.php
- src/helpers/post-helper.php
- src/integrations/watchers/indexable-post-watcher.php
- tests/unit/actions/indexing/indexable-post-indexation-action-test.php
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/integrations/watchers/indexable-post-watcher-test.php
… ensure posts that shouldn't be indexed are never indexed
*
* Fixes a bug where indexables would be created for `auto-draft` indexables when the SEO optimization is run.
*
* Make sure you have auto-draft posts in your posts table. (Create a new post, add some content, DO NOT save it and refresh te page). If you get the message to revert to a back-up the auto-draft was succesfully created.
* Check the database that no indexable was created for the auto-draft post.
* Reset the indexables tables using the Yoast Test Helper.
* Run the SEO Optimization.
* Check the database that no indexables were created for auto-draft posts.
* …
> P2 1308 dont index autodraft posts

- admin/import/plugins/class-import-aioseo-v4.php
*
* Fixed a bug where custom post types with a hyphen were not imported properly.
*
* Make sure the custom post types and custom taxonomies in the Yoast Test Helper are active.
* Make sure AIOSEO is activated and Yoast SEO is deactivated.
* Create a new Book, add a replacement variable "Taxonomy Name" with value `book-genre` to the meta title or description.
* Activate Yoast SEO.
* Import AIOSEO data.
* Save the post.
* Check the front-end if it has the right value.
*
* Import custom fields from AIOSEO
Fixes #
> P2-1324 - Fix import of custom post types with a hyphen

- wp-seo-main.php
* Premium shows a warning in the changelog screen that the plugin isn't tested for the current WordPress version (= 5.8.1):
* For Free, we are using WP's infrastructure about tested up to versions. In that context, minor version releases don't need any action from our side. However, for the addons (incl. Premium) we had to create our own infrastructure, in which the `YOAST_SEO_WP_TESTED` constant is used and minor releases do matter.
* Sets YOAST_SEO_WP_TESTED to 5.8.1
*
* Without this PR, clicking `View details` on Yoast Premium in the plugins overview shows a warning:
* With this PR, the warning should be gone and the `compatible up to` should mention 5.8.1 
QA can test …
> Set YOAST_SEO_WP_TESTED to 5.8.1

- src/integrations/third-party/web-stories.php
- tests/unit/integrations/third-party/web-stories-test.php
* There's an issue with duplicate canonical tags for web stories.
* Duplicates https://github.com/Yoast/wordpress-seo/pull/17435 to make sure that the Travis build is able to pass.
* Fixes a bug where a duplicate canonical tag was output for web stories created with the Web Stories plugin. Props to [swissspidey](https://github.com/swissspidy).
* Move hook (un)registration to a later stage
* Install the Web Stories plugin
* Publish a story
* View the story
* Verify that there's only one canonical tag
*
* 
Fixes #17419
> Fix duplicate canonical tags for web stories

- admin/import/plugins/class-importers.php
- tests/integration/admin/import/test-class-importers.php
* It was decided that we're not releasing the AiOSEO v4 importer in 17.3.
* Disables the AiOSEO v4 importer.
* Just commenting out the class that is responsible for the import functionality seems to be all there is to this.
* Activate AiOSEO.
* Make sure you have at least one post with some data filled in in the AiOSEO metabox.
* Without this PR / without this code in the RC, on the `Import from other SEO plugins` page in `Tools` you should see the option to import.
* With this PR / with this code in the RC, you should see the message "Yoast SEO did not detect any plugin data from plugins it can import from.".
*
This PR …
> Disable the AiOSEO v4 import functionality

- src/integrations/blocks/breadcrumbs-block.php
*
* Fixes a fatal error in the breadcrumbs block for auto-draft posts.
* If no indexable exists a minimal indexable is created.
* No breadcrumb title is generated, as that would just show `Auto Draft` (or the translated equivalent). It was decided that that would be less user friendly than showing no title.
Method 1:
* Add the breadcrumbs block to a newly created post that has never been saved.
* There should be no fatals.
Method 2:
* Add the breadcrumbs block to a post and publish the post
* Refresh the page
* The block should show the correct breadcrumbs
* Add some text to the post and open the network tab of your dev tools window
* Wait for the `/autosave` request 
* …
> [IM-1350] Fix breadcrumb block if no indexable exists

- inc/class-rewrite.php
- tests/integration/test-class-rewrite.php
* There's a known race condition with `delete_option` and `all_options` in combination with persistent caches that would cause Yoast SEO to keep flushing rewrite rules on every single page load. (see https://github.com/woocommerce/woocommerce/pull/27696 and https://github.com/Automattic/jetpack/pull/19229) 
* Fixes a bug where a race condition may occur that causes the rewrite rules to be flushed on every page request when using a persistent cache like Redis.
* I chose to schedule the rewrite flush on shutdown on the same request instead of on init on the next request. This way, it doesn't impact the next request, doesn't rely on db/cache storage and is a bit more predictable.  …
> Flush rewrite rules on shutdown without using options

- tests/integration/admin/test-class-admin-asset-dev-server-location.php
- tests/integration/admin/test-class-admin-asset-seo-location.php
- tests/integration/capabilities/test-class-capability-manager-factory.php
- tests/integration/capabilities/test-class-capability-manager.php
- tests/integration/capabilities/test-class-register-capabilities.php
- tests/integration/config-ui/test-class-configuration-components.php
- tests/integration/notifications/test-class-yoast-notification.php
- tests/integration/sitemaps/test-class-wpseo-author-sitemap-provider.php
- tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
Test classes should be suffixed with `Test`. Not `Tests`, not prefixed.
* _N/A_
> QA: fix incorrectly named test classes

- composer.json
- composer.lock
- phpcs.xml.dist
- src/integrations/third-party/wpml.php
- src/integrations/xmlrpc.php
* Update dev tools
* Update dev tools
... which includes PHP Parallel Lint by design, so no need to require it separately anymore.
Refs:
* https://github.com/Yoast/yoastcs/releases
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases
* https://github.com/PHPCompatibility/PHPCompatibilityWP/releases
* _N/A_
This is a tooling-only change and should have no effect on the functionality. If the build passes (linting, test runs), we're good.
> Composer: update to YoastCS 2.2.0

- src/presenters/open-graph/image-presenter.php
- tests/unit/presenters/open-graph/image-presenter-test.php
* Fixes the `path` of images being output in the open graph images of the JSON head.
* See https://yoast.atlassian.net/browse/IM-1356
* The following pieces are not shown anymore for posts with OG image in `yoast_head_json` 
"path"
"size"
"id"
"alt"
"pixels"
* The open graph image presenter, used in both the JSON output and the meta tags on the frontend.
Fixes https://yoast.atlassian.net/browse/IM-1356
> [IM-1356] Fix the open graph presenter to sanitize and display types

- src/generators/schema/webpage.php
- tests/unit/generators/schema-generator-test.php
* Fixes a bug where the `url` property in the search page schema would be empty.
* Go to a search URL, see the `url` property in the schema on the `WebPage` piece is no longer empty.
> Fix bug in search page schema

- admin/import/plugins/class-importers.php
- src/conditionals/aioseo-v4-importer-conditional.php
- tests/unit/admin/import/plugins/importers-test.php
* We want to set the new AiOSEO importer behind a feature flag.
* Puts the new AiOSEO V4 importer behind the `YOAST_SEO_AIOSEO_V4_IMPORTER` feature flag.
* Added unit tests for the `WPSEO_Plugin_Importers` class.
* Install and activate the All-in-One SEO plugin.
* Create or open a post.
* Add All-in-One SEO metadata in their metabox (e.g. title, meta description).
* Save the post.
* Disable the All-in-One SEO plugin.
* Install and activate the Yoast SEO plugin.
* In the WordPress admin, go to the _Import from other SEO plugins_ tab in the import and export tool.
* Located in _Yoast_ > _Tools_ > _Import and Export_ > _Import from other SEO plugins_.
* You should see the …
> Added AiOSEO V4 feature flag.

- inc/class-wpseo-meta.php
- src/config/schema-types.php
- src/context/meta-tags-context.php
* Add filtering for schema article types.
* Please test in conjunction with https://github.com/Yoast/wpseo-news/pull/718
Relates to PRODUCT-166
> Add filtering for schema article types

- admin/views/sidebar.php
- css/src/admin-global.css
* We want to show a badge in our upsells at certain times.
* Adds a sale badge to the upsell on our main settings page, that is temporarily shown.
* All times in UTC for certainty
* Either change the time of you php (dev) server, or change the date and time in the code
* _Please be aware that all times are in UTC / GMT, so you should add one hour for Western European time_
* When that time is within the set time window, there should be a badge visible on our main settings page / dashboard
* This badge should look like the design
*
*
Fixes …
> Add temporary badge to upsell

- admin/views/tabs/metas/paper-content/post_type/post-type.php
- inc/class-wpseo-meta.php
- inc/options/class-wpseo-option-titles.php
- src/helpers/schema/article-helper.php
- src/integrations/third-party/web-stories.php
- tests/unit/helpers/schema/article-helper-test.php
- tests/unit/integrations/third-party/web-stories-test.php
* Fixes a bug where the `page` post type wasn't allowed to display an `Article` piece in the Schema.
* Makes sure that the Schema Article type is enabled for any post type supporting authors.
* Deprecates `wpseo_schema_article_post_types` filter.
* The default `Article` type is `Article` for posts, `None` (→ no `Article` piece is in the Schema output) for any other post type.
notes by @enricobattocchi:
* I decided to make `is_article_post_type()` synonym to `is_author_supported()`  to avoid major changes + adding deprecations to the API, and allow for an easy refactoring, should the requirements for an `Article` type change in the future.
* I've also removed an unnecessary use of the deprecated filter in our Web Stories …
> Make sure we allow for article schema on pages and any post type supporting `author`

- src/helpers/schema/article-helper.php
* Fix a fatal error that occurs when the `wpseo_schema_article_post_types` filter would be used.
* Add a message to the deprecation filter, stating the reason for deprecation.
* Fixes an unreleased bug where the filter deprecation of `wpseo_schema_article_post_types` would cause fatal errors.
*
* Use the filter `wpseo_schema_article_post_types`, something like this:
```php
add_filter( 'wpseo_schema_article_post_types', 'add_spanish_blog', 10, 1 );
function add_spanish_blog( $posttype ) {
$posttype[] = 'book';
return $posttype;
}
```
* Visit `SEO -> Search appearance`. 
* Without this PR, content would not be loaded and a fatal error is thrown.
* With this PR, no fatal …
> apply_filters_deprecated expects original arguments in an array

- packages/social-metadata-previews/src/facebook/FacebookImage.js
- packages/social-metadata-previews/src/shared/SocialImage.js
- packages/social-metadata-previews/src/twitter/TwitterImage.js
* 
* Applies the aspect ratio fix from https://github.com/Yoast/wordpress-seo/pull/17544 only when in landscape mode.
*
* In your terminal cd into: `packages/social-metadata-previews/`
* Enter `yarn link`
* Open the `wordpress-seo-premium` repo
* Open the terminal and enter `yarn link "@yoast/social-metadata-previews"`
* Execute the grunt build command `grunt build:js`
* Change the Twitter card type to `Summary`: Yoast SEO -> Social -> Twitter
* Add/edit a post
* Open the Yoast SEO `social` tab
* Add a Facebook and Twitter image that has a bigger width than height
* Verify the Facebook image looks the same as before (17.6-RC1): centered and proper …
> P1-1063 undo aspect ratio for non landscape social previews

- packages/js/src/initializers/term-scraper.js
*
* Fixes a bug where the SEO and readability analyses wouldn't load on taxonomy pages.
* In a [recent PR,](https://github.com/Yoast/wordpress-seo/pull/17526) jed was removed. Before that `i18n` used to be the first argument of all assessors. This was changed for all essors and also for (almost) all places wher the assessors were instantiated.
* In the current PR, I change once instance in which the taxonomy assessor was still called with the `i18n` object as the first parameter. When the assessors was instantiated like that, the fact that the parameters had changed on the taxonomy assessor class itself meant that it couldn't be correctly instantiated anymore.
* I didn't dive into it, but I think that the piece of code affected …
> Remove i18n argument when initializing taxonomy assessor

- packages/js/src/workouts/redux/container.js
- packages/js/src/workouts/redux/reducer.js
* In the Cornerstone workout, it was possible to get the same indexable in the addLinks step multiple times, leading to weird looking UI and console errors (duplicate keys).
* Test together with https://github.com/Yoast/wordpress-seo-premium/pull/3495
* [wordpress-seo-premium] Fixes a bug where the same indexable could be added to the same workout step multiple times.
* Replaced `typeof indexable.purge === "undefined"` by `! indexable.purge` in order to also be able to set `indexable.purge` to `false`.
* Test together with premium https://github.com/Yoast/wordpress-seo-premium/pull/3495
* For all the below tests, note that if you refresh very quickly after …
> Fix duplicate indexables in step

- packages/yoastseo/spec/languageProcessing/researches/getSubheadingTextLengthSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
- packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
- packages/yoastseo/src/languageProcessing/researches/getSubheadingTextLengths.js
- packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
*
* [yoastseo] Adapts `getSubheadingTextLengths` for Japanese.
* I've changed the naming of the `countCharacters` helper, importing it in the researcher as `customCountLength`. That's to keep the language-independent side of the analysis independent in a more straightforward way: I think it makes more sense to formulate a general rule like "custom count length overwrites count words" than a specific rule such as "character count overwrites count words". The fact that a custom method can overwrite a default method is relatively self-explanatory, whereas you need to know more context to understand why character count would overwrite word count.
* Check if the specs run …
> Adapt getSubheadingTextLengths for Japanese

- packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
- packages/yoastseo/spec/specHelpers/factory.js
- packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/ja/config/topicLength.js
- packages/yoastseo/src/languageProcessing/researches/keyphraseDistribution.js
*
* [yoastseo] Adapts `keyphraseDistribution` research for Japanese and adds Japanese topic length criteria config.
* The highlighting is still not yet working for this research since `markWordsInSentences` is not yet adapted for Japanese. Hence the current unit tests for `sentencesToHighlight` is always an empty array. [An issue](https://yoast.atlassian.net/browse/LINGO-1138) to adjust the highlighting functionality was already created in Jira.
* I also add a new method to get the config in `buildMockResearcher` so that we can pass more than one configs when we create a mock researcher.
* The criteria for determining whether a topic is long or short is passed through the Japanese researcher. In Japanese, a topic is short if it’s …
> Adapt keyphrase distribution research for Japanese

- apps/seo-integration/craco.config.js
- apps/seo-integration/package.json
- apps/seo-integration/src/app.js
- apps/seo-integration/src/helpers.js
- packages/seo-store/gists/interfaces.js
- packages/seo-store/package.json
- packages/seo-store/src/analysis/hooks.js
- packages/seo-store/src/analysis/slice/index.js
- packages/seo-store/src/analysis/slice/results.js
- packages/seo-store/src/index.js
*
* Introduces the `yoast.seoStore.analysis.preparePaper` filter to change the paper before the analysis.
* Introduces the `yoast.seoStore.analysis.processResults` filter to change the results before storing them.
* Removes the `preparePaper` and `processedResults` initialize functions.
* Fixes a bug where the analyze hook would not work.
* Fixes a bug where the paper data was not as designed: `title` -> `seoTitle` and `description` -> `metaDescription.
* Adds `seoTitleWidth` to the paper in the `seo-integration` app, via the `preparePaper` filter.
* Discussed the possibilities for the `seoTitleWidth`. We would really like to prevent the element creation part in the `seo-store` package.
* Solution 1, as done now: use the filter …
> P1-1000 add hooks around analysis

- src/actions/importing/aioseo-posts-importing-action.php
- src/routes/abstract-action-route.php
- src/routes/abstract-indexation-route.php
- src/routes/importing-route.php
- tests/unit/routes/importing-route-test.php
*
* Adds an abstract import route, that can be expanded with new routes in the near future.
The code calls the `yoast/v1/import/aioseo/posts` wp rest api end-point. Each API call to `yoast/v1/import` shoud refer to a class that extends the Importing interface. 
Each import function should return an object with an `objects` property and a `next_url` property. The `next_url` property is used to determine whether the next endpoint should be called when the current endpoint is finished importing all entities.
* Make sure you are logged in as an admin.
* On the WordPress dashboard page run the following code in the JS command-line:
```js
( async function() {
const a = await …
```
> Abstract plugin import route

- config/composer/unit-test-generator.php
*
* Renames function parameters that use reserved keywords in the unit test generator.
*
*
* NA it has to do with the unit test generator which is used by devs.
*
Fixes #
> Change parameter names to not use reserved keywords unit-test-generator.php

- inc/class-wpseo-replace-vars.php
*
* Changes parameter names in the `WPSEO_Replace_Vars` class to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions with replace vars
*  
Fixes #
> Rename parameters with reserved names class-wpseo-replace-vars.php

- admin/class-option-tab.php
*
* Changes parameter names in the `WPSEO_Option_Tab` class to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions in the tabs of the Yoast pages
*
Fixes #
> Rename parameters with reserved names class-option-tab.php

- admin/class-yoast-network-settings-api.php
*
* Changes parameter names in the `Yoast_Network_Settings_API` class to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions in multisite's settings
*
Fixes #
> Rename parameters with reserved names class-yoast-network-settings-api.php

- admin/class-yoast-form.php
- config/dependency-injection/container-compiler.php
- config/dependency-injection/custom-loader.php
* PHP8 has broken Backward Compatibility, and changing reserved keywords is part of preventing trouble. 
* Renamed some parameters to avoid issues with reserved keywords and named parameters.
* 
* Code review only.
* N/A
*
Fixes #
> Rename reserved variables in various classes

- inc/options/class-wpseo-options.php
*
* Renamed function parameters that use reserved keywords.
*
*
*
*
Fixes #
> Change parameter names to not use reserved keywords

- composer.json
- config/composer/actions.php
* Update dev tools
* Update dev tools
As of YoastCS 2.2.0, the Yoast standard contains a custom `Threshold` report.
This switches out the custom logic for comparing the PHPCS run results against thresholds in the `Yoast\WP\SEO\Composer\Actions` class to use this new report instead.
The report will now also respect the error code returned by PHPCS if the threshold is not met.
Notes:
* The `-m` parameter directs PHPCS to not record the error messages, which saves a lot of memory usage during this run.
* The -q parameter makes it so no progress is being shown during this run.
* The `exec()` function has been switched out in favour of the `passthru()` to allow for the report to be displayed directly.
The downside of this is that the …
> Composer/actions: simplify the PHPCS threshold check

- inc/sitemaps/class-sitemap-image-parser.php
*
* Changes parameter names in the `WPSEO_Sitemap_Image_Parser` class to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions in the post sitemap. More specfically test if a post created with the post editor that has a gallery in its content gets its number of images (including its feature image) calculated correctly in the sitemap
*
Fixes #
> Rename parameters with reserved names class-sitemap-image-parser.php

- admin/views/partial-notifications-template.php
*
* Changes parameter name for the `_yoast_display_notifications()` method to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions in notifications in the SEO->General page
*
Fixes #
> Rename parameters with reserved names partial-notifications-template.php

- inc/sitemaps/class-sitemaps.php
*
* Changes parameter names in the `WPSEO_Sitemaps` class to avoid breaking changes in PHP 8+
*
* N/A
* Check for regressions when registering sitemaps in the /sitemap_index.xml page
* Check for regressions when handling xsl files
* Check for regressions when handling bad sitemaps (404 when requesting empty sitemaps)
*
Fixes #
> Rename parameters with reserved names class-sitemaps.php

- src/surfaces/meta-surface.php
- tests/unit/surfaces/meta-surface-test.php
When `page_on_front` is 0 in database (which happens if you check `show_on_front`, select a `page_for_posts` but no `page_on_front`), `get_option('page_on_front')` will return 0 **as a string**.
The following condition (see next line after `get_option('page_on_front')`) will then be evaluated to true (it shouldn't) causing `$indexable = $this->repository->find_by_id_and_type( $front_page_id, 'post' );` to be called with `$front_page_id` to 0 and finally resulting in upgrading some random post in the indexable table with a 0 object_id.
There may be a related issue with `Indexable_Repository::find_by_id_and_type()` because it will call `upgrade_indexable` to be called with an $object_id set to 0 corrupting a post indexable.
* Fixes a bug where the meta surface could return the wrong result …
> Fix Meta_Surface::for_home_page()

- admin/metabox/class-metabox.php
* Prevent an array loop on a non-array variable, preventing warnings on certain post edit screens.
* Fixes a bug where some post types would cause a PHP warning about custom fields.
* `get_post_custom()` is described to return an array, however, it is also capable of returning an empty string. Therefore we should check for an array before we use it as an array.
* Try the reproduction steps from https://yoast.atlassian.net/browse/IM-1597 :
1. Install WordPress
2. Install Yoast SEO / Yoast SEO Premium
3. Install GiveWP and configure
4. Click on Add Form in Give WP, make sure there is no warning.
* Make sure that custom field variables keep working in the metabox. For …
> IM-1597 - Verify array before looping

- admin/class-yoast-form.php
- admin/views/tabs/metas/paper-content/post-type-content.php
* https://github.com/Yoast/wordpress-seo/pull/17174
* Adds a link to the archive page for the content types in the search appearance settings. Props to [felipelousantos](https://github.com/felipelousantos).
*
*
*
*
Fixes #
> Add link to archive search appearance

- src/integrations/admin/configuration-workout-integration.php
* The indexation in the conf. workout is broken, we have to update the endpoint name
* Fixes an unreleased bug where the indexation in the configuration workout was failing.
* [this is the commit](https://github.com/Yoast/wordpress-seo/commit/7f7a0bbede785397e8ebde37907961deec416cbd) where the endpoint names changed
* change your permalinks settings so indexation can be restarted
* Visit the conf. workout and start the indexation, check it works
* change your permalinks settings so indexation can be restarted
* Visit SEO > Tools  and start the indexation, check it works (it shouldn't be affected but let's check)
*
This PR …
> DUPP-81 Fix indexation in configuration workout

- patchwork.json
- src/commands/index-command.php
- tests/unit/commands/index-command-test.php
This is a basic effort to get indexing working without crashing or maxing out CPU usage for large sites.
Ideally what is needed is the ability to do bulk inserts / updates as well as periodically clearing object cache memory.
* Indexing posts on a large site via CLI slows down and can crash
* CPU usage spikes to 100% during indexing
* Each post can trigger 4 db inserts / updates during indexing so indexing 10k posts can theoretically result in up to 40k db queries
* Added a usleep interval to the WP CLI index command to limit server load while this command is running. Props to [roborourke](https://github.com/roborourke)
* `usleep` allows for intervals less than a second for more powerful servers while also allowing for times …
> Improve indexing performance

- packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
- packages/yoastseo/spec/languageProcessing/languages/ja/helpers/getStemmerSpec.js
- packages/yoastseo/spec/languageProcessing/languages/ja/helpers/internal/createWordFormsSpec.js
- packages/yoastseo/spec/specHelpers/getMorphologyData.js
*
* [yoastseo] Disables tests that use Japanese language data when the feature flag for the Japanese language is disabled.
* Uses `require` instead of `import` to be able to conditionally import the Japanese language data.
* Make sure that the Travis build succeeds.
* N/A: The changes only concerns unit tests.
* N/A: The changes only concerns unit tests.
Fixes #
> Only import Japanese morphology data when the feature flag is turned on.

- packages/seo-store/package.json
- packages/seo-store/src/analysis/tests.js
*
* Adds tests for the analysis hooks: `useAnalyze`.
* Using Jest fake timers to get around the debounce. Thanks Nolle 😄    -- Context: we can not know when the analyze is done, the only way to know would be to listen to the success or error action, which is out of the scope of this hook.
* Code review the tests
* Install deps: `yarn`
* Go to `seo-store` package and run the tests: `yarn test`
* The tests should all pass
* N/A
*
Fixes [P1-1006](https://yoast.atlassian.net/browse/P1-1006)
> P1-1006 test analysis hook

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/WorkoutIndexation.js
* We want to run the indexing actions added by Premium when indexing in the conf. workout
* Fixes an unreleased bug where indexing from inside the conf. workout resulted in an endless loop with Premium
*
* test with https://github.com/Yoast/wordpress-seo-premium/pull/3499
* then, disable premium
* reset indexables, link count and prominent words in the Test helper
* visit the conf. workout and start the optimization, see it finishes
* reset indexables, link count and prominent words in the Test helper
* visit SEO > Tools and start the indexation from there, see it works (it's not been touched)
* …
> DUPP-87 Allow registering of indexing actions in the Workout indexation

- packages/seo-store/src/analysis/tests.js
*
* Adds tests for the `analysis` slice: the index/combine part.
* Tested the structure part, i.e. if it has config and results. The actions and selectors are complete right now. For the future I think it would be fine to not have to include new ones in there every time. It should be fine as a "random" select few to ensure some of both got in.
* Code review the tests
* Install deps: `yarn`
* Go to `seo-store` package and run the tests: `yarn test`
* The tests should all pass
* N/A
*
Fixes [P1-1068](https://yoast.atlassian.net/browse/P1-1068)
> Seo-store: add tests for the analysis slice

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/Steps.js
* Disable finishing of the workout before indexation is finished.
* Update notification for when indexation hasn't even started.
* Disables finish workout button when indexation has not yet finished.
* Adjusts notification about finishing the workout before Indexation is finished to reflect whether the indexation has started or not. 
*
* Use yoast-test-helper or change permalink settings to reset indexation states.
* Before indexation has started:
* Finish workout button should be disabled
* Notification reads: `Before you finish this workout, please start the SEO data optimization in step 1 and wait until it is completed...`
* When indexation has started:
* Finish …
> Disable button for not started and unfinished indexation

- css/src/workouts.css
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/NewsletterSignup.js
- packages/js/src/workouts/components/ValidatedTextInput.js
* Add a way to display validation results near our TextInput components.
* Validate email client-side
* Fixes an unreleased bug where the newsletter signup in the configuration workout would always return a success message, despite inputs being invalid or even absent.
* Fixes an unreleased bug where the continue button in the indexation step was misaligned.
* Decided to keep the wrapped TextInput inside the workouts/components despite potential wider use cases, since we are on the clock with this feature.
* Also, the TextInput here may be superseded at some point by the TextInput in admin-ui.
* In the newsletter configuration workout, go to the newsletter signup at the …
> Validate email and give feedback in newsletter signup

- packages/js/src/workouts.js
- src/integrations/admin/workouts-integration.php
* Only those who can actually do the configuration workout should be bothered with notifications and see the workout.
* Fixes an unreleased bug where users without the wpseo_manage_options capability saw the Configurtion Workout and accompanying notification.
* Hides the configuration workout notification in the workouts page.
* Exposed the variable to JS via the localized object rather than creating a separate integration for the configuration workout.
* Use the user-switching plugin and switch to an editor/author/seo_editor if you can. Else, log in as an editor/author/seo_editor. Anyone without the `wpseo_manage_options` capability should do.
* Use the test helper to …
> [DUPP-94][DUPP-93][DUPP-100] dont show configuration workout and notice without wpseo manage options
