- packages/js/src/initializers/term-scraper.js
Reverts Yoast/wordpress-seo#17600
> Revert "Remove i18n argument when initializing taxonomy assessor"

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/SocialInput.js
- packages/js/src/workouts/components/SocialInputSection.js
- src/actions/configuration/configuration-workout-action.php
- tests/unit/actions/configuration/configuration-workout-action-test.php
* We need to signal to users when some social profiles values are not saved.
* 
* Valid URLs are always saved
* Invalid URLs are never saved
* Feedback is server side (so there is a request to save at least the valid URLs)
* Step can only be finished if there are no invalid fields
* Use these parameters and see if all the cases are caught.
* Valid URLs are always saved
* Invalid URLs are never saved
* Feedback is server side (so there is a request to save at least the valid URLs)
* Step can only be finished if there are no invalid fields
*
* …
> Signal social profile validation

- src/actions/importing/deactivate-conflicting-plugins-action.php
* We want to hide some more code behind a feature flag, to prevent people working on trunk from seeing errors.
* Disables a feature that's still in progress.
* hide the action behind the feature flag. 
* Run SEO Optimization. It should complete normally now.
* set the YOAST_SEO_AIOSEO_V4_IMPORTER feature to true.
* rerun optimization.
* it should cause a PHP error instantly.
*
*
Fixes #
> Hides the deactivation import action behind the feature flag

- src/actions/importing/abstract-importing-action.php
- src/actions/importing/aioseo-posts-importing-action.php
- src/actions/importing/deactivate-conflicting-plugins-action.php
- tests/unit/actions/importing/abstract-importing-action-test.php
- tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
- tests/unit/doubles/actions/importing/abstract-importing-action-double.php
* Fixes an error where a subclass would not properly initialize its parent
* Fixes an error where a subclass would not properly initialize its parent
* Fixes an error where a subclass would not properly initialize its parent
* Run SEO Optimization. It should complete normally.
* enable the YOAST_SEO_AIOSEO_V4_IMPORTER flag , set it to true
* Run SEO Optimization. It should complete normally.
*
* Acceptance test https://github.com/Yoast/wordpress-seo/pull/17639 again
* Acceptance test https://github.com/Yoast/wordpress-seo/pull/17578 again
Fixes …
> inject parent dependencies through child's constructor

- packages/js/src/workouts/components/ConfigurationWorkout.js
- src/integrations/admin/configuration-workout-integration.php
* We want to disable the "Organization or person" select when the step is finished or when Local SEO forces the choice.
* Disables the "Organization or person" select in the configuration workout when the step is complete or when Local SEO is active.
* Also moves the definition of the choices in the PHP side to make them translatable.
* visit the configuration workout
* in the second step, choose "Organization" and fill the other stuff, then click "Save and continue"
* check that the step is greyed out, and the select becomes a readonly textbox with the Option you selected
* reload, or visit SEO > Search Appearance, to check that your choice was saved
* un-grey the step …
> DUPP-96 Change select with textinput when company or person choice is disabled

- apps/seo-integration/src/replacement-variables.js
- packages/replacement-variables/__tests__/index.test.js
- packages/replacement-variables/readme.md
- packages/replacement-variables/src/index.js
* Adds documentation for the `@yoast/replacement-variables` JavaScript package.
* Adds documentation for the `@yoast/replacement-variables` JavaScript package.
* Adds documentation for the `@yoast/replacement-variables` JavaScript package.
* Replace support for multiple args for `getReplacement` functions with a single `context` args to be able to pass multiple variables (as props of `context`) to the `getReplacement` functions in the configured set of replacement variables.
* Read the documentation and check if that makes sense.
* You could try the the example for real for fun I guess (I haven't).
* …
> P1-1032 document replacement variables package

- src/integrations/admin/workouts-integration.php
* 
* Removes configuration notice when site representation name and logo have been set and the indexing has been done.
* I moved some checks into their own private functions to improve readability of the `should_display_configuration_workout_notice` method, since it depends on quite a lot of factors. 
* Make sure you are an admin.
* Make sure you have not completed the Configuration Workout (the number of finished steps should be less than 5).
* Activate Yoast SEO and the Yoast Test Helper.
* Navigate to Tools > Yoast Test, and click the `Reset Indexables tables & migrations`, or make sure you need to re-run the indexation in some other way. 
* Do NOT run the indexation …
> DUPP-109 change conditions configuration workout notice

- src/surfaces/values/meta.php
* This code is fully functional, because `indexable` exists on the `Meta_Tags_Context`, but isn't tab-completed by the IDE because the comment in this pull is missing:
```php
YoastSEO()->meta->for_current_page()->indexable->primary_focus_keyword
```
* None needed.
> Expand indexable on the meta surface

- packages/js/src/initializers/estimated-reading-time.js
* The reading time functionality doesn't work for languages other than English. The research was never working for languages other than English because we run the research with the default config/attribute with `en_US` as the locale, and the locale was never overridden by the correct locale.
* Fixes a bug where the reading time functionality was not working for languages other than English.
* The locale is passed as part of the configuration when running the research in `estimated-reading-time.js`. 
* There are three different functions to get the estimated reading time for the three editors (i.e. Elementor, Block/Default, and Classic editor) where the functions for Block and Classic editors have their own editor-specific classes …
> Fix reading time functionality for languages other than English

- packages/js/src/workouts.js
- packages/js/src/workouts/components/ConfigurationWorkoutCard.js
- packages/js/src/workouts/components/CornerstoneWorkoutCard.js
- packages/js/src/workouts/components/OrphanedWorkoutCard.js
* Absence of correct Redux store on <5.7 caused workouts not to load.
* Incorrect function call on Redux useSelect <5.8 caused workouts not to load.
* Fixes an unreleased bug where workouts did not load on WordPress 5.6 due to errors with the Redux store.
* * Fixes an unreleased bug where workouts did not load on WordPress 5.7 due to errors with the Redux selectors.
* Decided to prevent the createReduxStore call if the function is not present, and call an older function instead. That function is now deprecated though, so we should remove the code once we go to 5.6 (as well as upgrade our code in other places where we use the deprecated function).
* If needed, use the WP …
> Catch non existence of createReduxStore and provide alternative

- css/src/notifications.css
- packages/js/src/workouts/components/CornerstoneWorkoutCard.js
- packages/js/src/workouts/components/OrphanedWorkoutCard.js
- packages/js/src/workouts/components/WorkoutCard.js
- packages/js/src/workouts/components/WorkoutsPage.js
- src/integrations/admin/workouts-integration.php
- src/presenters/admin/notice-presenter.php
- tests/unit/presenters/admin/notice-presenter-test.php
* We want the notification to update Premium to be more meaningful depending on whether the user can upgrade or not based on their site's subscription status
* Changes the notice to update Premium to see the new workouts, depending on the status of the subscription
* Also solves an issue (DUPP-106) where the image in the notification was displayed as big as the screen for an instant.
**Note**: there are some slight changes in the copy of the notifications (namely, adding the required version number) that are not yet in the design but were agreed to [here](https://yoast.slack.com/archives/C025T9L6B1R/p1637667934146400?thread_ts=1637334850.125600&cid=C025T9L6B1R)
**also …
> DUPP-66 DUPP-106 Add different notifications for expired and unactivated Premium

- src/integrations/front-end-integration.php
Backports changes from https://github.com/WordPress/gutenberg/pull/36133
Removes the `_block_template_render_title_tag` hook 
Steps to reproduce the issue available on https://github.com/WordPress/gutenberg/issues/34106
* Create a new page. Add some content and save.
* On the sidebar of the post, select to create a new template for the post. 
* Save the template
* Visit the frontend and check the page source
There should only be a single `<title>` element in the `<head>` of the document. Needs to be tested both with Gutenberg active, and inactive.
Fixes #
> Avoid double-title elements when using a custom single-page block template

- src/integrations/watchers/indexable-ancestor-watcher.php
- src/integrations/watchers/indexable-post-watcher.php
- tests/unit/integrations/watchers/indexable-post-watcher-test.php
* Prevents updating related indexables when an indexable is saved, instead it only updates them when the source object has changed.
* Fixes a bug where memory issues could occur when indexing a site with large amounts of terms assigned to many posts.
* Indexing your site after resetting permalinks should not lead to any OOM issues.
* Updating a post should still lead to the timestamps of it's terms being updated.
* Changing the slug of a page should still lead to the permalinks of child pages being updated.
* Updating timestamps of related indexables.
* Updating the breadcrumb hierarchy of …
> [IM-1616] Fix updating relations on index

- packages/js/src/workouts/components/ConfigurationWorkout.js
- src/integrations/admin/configuration-workout-integration.php
New behaviour surrounding Step 4 tracking:
* When step 4 tracking has no selected value, the “Finish this workout” button is disabled
* So: the “Finish this workout” button can only be used, when step 1 data optimization has finished and a user has selected a tracking value 
* Step 4 tracking has a disabled “Save and continue” button and an alert when no value has been selected. 
* For premium users the tracking value from the database will be used. 
* For Free users, the tracking value is not selected when you start the workout. It will be saved when you finish the step. When the step is not finished, and you reload the page, the value will be set back to null.
* Displays empty radiobuttons for the tracking step of the …
> Pass a third state for the tracking option on selected condition

- css/src/workouts.css
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/FinishButton.js
- packages/js/src/workouts/components/Steps.js
- packages/js/src/workouts/components/WorkoutsPage.js
- packages/js/src/workouts/helpers.js
- packages/js/src/workouts/redux/actions.js
- packages/js/src/workouts/redux/reducer.js
* Adds 1px border around cards in overview and workouts.
* Adds scrolling to next step on clicking (save and) continue.
* Adds green saved checkmarks behind the save and continue buttons when step has been saved.
* When a step is finished,  “Save and continue” is changed to “Revise this step”.
* When “Finish this workout” is used, the copy changes to “Do workout again”.
* Saves all the settings when “Finish this workout” is used.
* Adds a “Congratulations” section when “Finish this workout” is used.
* Step 1 is only be completed when indexation is done, not on clicking continue.
* Saves all steps of the configuration workout when using the “Finish this workout” button.
* Adds some UI improvements to the configuration workout.
* …
> Configuration workout - Improve user flow and small design tweaks

- inc/options/class-wpseo-option-wpseo.php
- packages/js/src/workouts/components/ConfigurationWorkout.js
- src/integrations/admin/configuration-workout-integration.php
* We want to avoid a critical race when finishing all the steps in a workout together.
* Changes the default behaviour of the tracking radiobuttons in the configuration workout to display the actual value from the database.
* Fixes an unreleased bug where the tracking option would be overwritten by the previous value when finishing the full configuration workout.
* Adds the link to step one "Learn more about the benefits of optimized SEO data.".
*
* Visit the configuration workout and look at the tracking radiobuttons in step 4
* it should always display the current value from the database (so "no" by default on a new Free installation, "yes" by default on a new Premium …
> DUPP-115 tracking option not saved

- inc/wpseo-functions.php
*
* Renamed function parameters that use reserved keywords to prevent unnecessarily high cognitive load with named parameters.
* `wpseo_replace_vars()`: Rename $string parameter to $text.
* `wpseo_register_var_replacement()`: Rename $var parameter to $replacevar_name.
* `ctype_digit()`: Rename $string parameter to $text.
* General smoke testing.
*
*
Fixes #
> replace function arguments in wpseo-functions.php

- lib/migrations/adapter.php
*
* Renamed function parameters that use reserved keywords to prevent unnecessarily high cognitive load with named parameters.
* `Adapter::quote_string()`: Rename $string parameter to $text.
* `Adapter::identifier()`: Rename $string parameter to $text.
* `Adapter::quote_table()`: Rename $string parameter to $text.
* General smoke testing.
*
*
Fixes #
> replace function arguments in adapter.php

- src/integrations/admin/workouts-integration.php
* Premium redirects submenu page coming it at priority 9 in the sibling PR in premium. This can put it above workouts, which is not what we want.
* Context https://yoast.slack.com/archives/C027BFR5L/p1637576075263300
* Fixes an unreleased bug where the workouts menu item could be below premium menu items.
*
* Test with the [sibling PR](https://github.com/Yoast/wordpress-seo-premium/pull/3503) in premium, and News SEO.
* the order should be: Workouts, Redirects, News SEO
* check the behaviour with previous versions of Premium:
* install Premium 17.6
* you shouldn't see **two** Workouts pages
* the order should be: Workouts, Redirects, News SEO
* visiting the Workouts page …
> Increase priority of workouts to be above the priority of premium

- css/src/workouts.css
- packages/js/src/helpers/stringHelpers.js
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/NewsletterSignup.js
- packages/js/src/workouts/components/OrganizationSection.js
- packages/js/src/workouts/components/PersonSection.js
- packages/js/src/workouts/components/SocialInputSection.js
- packages/js/src/workouts/components/Steps.js
- packages/js/src/workouts/components/WorkoutsPage.js
* We want to add ids for automated testing.
Update: @mrcuc360 has approved. 
* Adds ids to the elements of the configuration workout.
* As a result, clicking the labels of the social input fields now focusses on the corresponding input field.
* Do a smoke test of the Configuration workout.
* See the ids have been added.
* For the input fields: check that clicking the label focusses on the corresponding input field.
* Do a smoke test of the Configuration workout.
* For the input fields: check that clicking the label focusses on the corresponding input field. …
> DUPP-114 add ids to configuration workout

- css/src/workouts.css
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/Steps.js
- packages/js/src/workouts/components/WorkoutIndexation.js
- src/integrations/admin/workouts-integration.php
* On Premium <17.7 indexation cannot be run from the workout.
* To prevent issues, we usher the user towards the Tools section and disable step 1.
New case: Indexation needed, Premium outdated
New case: Indexation done, Premium outdated
Fixed this bug too: Premium oudated, styling and step number issues:
* Fixes an unreleased bug where users who had updated Free to 17.7 but had Premium at an older version got caught in an indexation loop on the Configuration Workout.
* Bug is prevented by not offering indexation in the workouts for users with an outdated premium. In stead, we send them to the tools page and ask them to refresh afterwards. Completion of the workout should be as in other cases. …
> Fix compatibility indexation with premium <17.7

- apps/seo-integration/src/app.js
- apps/seo-integration/src/index.js
- apps/seo-integration/src/replacement-variables.js
- packages/seo-integration/src/index.js
- packages/seo-store/src/analysis/slice/config.js
- packages/seo-store/src/analysis/slice/index.js
- packages/seo-store/src/analysis/slice/results.js
- packages/seo-store/src/editor/slice.js
- packages/seo-store/src/form/slice/index.js
- packages/seo-store/src/form/slice/keyphrases.js
- packages/seo-store/src/form/slice/seo.js
- packages/seo-store/src/index.js
* Adds support for setting initial SEO store state via `seo-integration` package.
* [@yoast/seo-integration] Adds support for setting initial SEO store state via seo-integration package.
* Combine all slice `defaultStates` into a general `defaultState` which will be merged with `initialState` from factory args to ensure entire state shape.
* Should we only support initial editor state?
* Re-export `SEO_STORE_NAME` and `useAnalyse` from `seo-store` in `seo-integration` package so that implementor only has to use imports from `seo-integration` package.
* Fire up the example `seo-integration` app using `yarn start`.
* Immediately after render, check if the initial `title` …
> P1 1036 support initial SEO store state

- src/actions/importing/deactivate-conflicting-plugins-action.php
- tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
*
* Fixes a bug where having any plugin from the conflcting plugins list as active would break all the other importing endpoints
*
* Have AIOSEO active
* Create a couple of posts. That way, we have AIOSEO post data to import to Yoast
* In the console, run
```
( async function() {
const a = await fetch( "/wp-json/yoast/v1/import/aioseo/posts" ,
{
method: "POST",
headers: { "X-WP-Nonce": wpApiSettings.nonce }
}
);
console.log( await a.json() );
} )();
```
* This is a call in order to import AIOSEO post data, so it should have returned some imported data.
* Instead, it throws 404
Now, with this PR:
* Have AIOSEO active
* Create a couple of posts. That way, …
> Remove is_compatible() method of the deactivating plugins action class

- Gruntfile.js
- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/copy.js
- config/grunt/task-config/shell.js
- package.json
- packages/replacement-variable-editor/src/shared.js
- packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
* Goal: all strings are translated.
* Fixes a bug where certain text in the Google, Facebook and Twitter previews would not be translated.
*
* For developers: build this branch, including the translations (will be done if you use `grunt build`, or run `grunt build:i18n` on top of your normal steps)
* Set your site language to something other than `English (United State)` (I tested with Dutch): Settings -> General -> Site Language
* Download the latest translations: Dashboard -> Updates -> Download translations
* Edit a post
* Verify the strings are now translated
* Check the Facebook preview
* `Facebook image` label
* `Facebook title` label
* `Facebook description` label …
> P1-991 fix social untranslatables

- css/src/elementor.css
* Elementor [changed the styling of their dialogs](https://github.com/elementor/elementor/blob/35887cb30964386cb9eaba449afb28e223ad5423/assets/dev/scss/editor/_introduction.scss) which has broken our introduction message dialog. To have a proper introduction message again we had to fix the styling.
* Currently it looks like this:
* Fixes a bug where the styling of our Introduction dialog in Elementor was broken due to changes in Elementor.
* Had to overrule inline styled positioning using `!important`
* As we now have to style the button ourselves as well I took the liberty to make it slightly more Yoastie
* Install and activate this branch or 17.8RC
* Install and …
> Update Elementor introduction dialog styling

- packages/js/src/workouts/components/ConfigurationWorkout.js
- src/actions/configuration/configuration-workout-action.php
- src/integrations/admin/workouts-integration.php
- tests/unit/actions/configuration/configuration-workout-action-test.php
* We want to prevent the SEO managers to change the site tagline in the conf. workout
* Prevents SEO managers from changing the site description in the configuration workout.
*
* log in as a SEO Manager
* open the configuration workout
* see that you can't see the "tagline" input field in the second step
* when saving the step, inspect the payload of the AJAX call to the `/site_representation` endpoint and see that it doesn't contain a `description` field.
* now login as admin
* open the configuration workout
* see that now you can see the "tagline" input field in the second step
* change the value and save the step
* reload or visit `Settings` > `General` to check that …
> DUPP-104 Prevent SEO managers to change the site tagline

- apps/seo-integration/package.json
- apps/seo-integration/public/worker-mock.js
- apps/seo-integration/src/app.js
- apps/seo-integration/src/index.js
- apps/seo-integration/yarn.lock
- packages/seo-integration/src/analysis-result-containers/hooks.js
- packages/seo-integration/src/analysis-result-containers/index.js
- packages/seo-integration/src/analysis-result-containers/readability.js
- packages/seo-integration/src/analysis-result-containers/seo.js
- packages/seo-integration/src/analysis-result-containers/transformers.js
- packages/seo-integration/src/index.js
- packages/seo-store/src/analysis/slice/config.js
- packages/seo-store/src/analysis/tests.js
*
* Adds a `ReadabilityResultsContainer`.
* Adds a `SeoResultsContainer`.
* Renamed the configuration selectors to start with `select` too.
* Added a transform for the analysis results, this is temporary (the grouping is there to stay though). As discussed, this will be removed in favor of doing this in the `yoastseo` in between layer directly. Resulting in the Redux store having the results as objects already.
* Not sure about:
* the folder name
* the non-hook-ness of the transform
* the double action of the transformer. I.e. grouping and transforming
* the secret different defaults for the `headingLevel` and `marksButtonClassName`
* Install dependencies in the monorepo …
> P1-1042 analysis results containers

- packages/components/src/radiobutton/radiobutton.css
*
* Fixes a bug where on small screens the advanced setting's search engine follow checkbox would have a misplaced center.
* Override the block editor style where this was coming from, effectively removing it. We have our own center style.
* Go to a post
* Put the browser screen width to say 375 pixels
* Go to advanced
* Verify the radio button of the search engine follow links is no longer showing a misaligned blue circle. It was:
*
* Check in multiple browsers? I checked in Chrome and Safari.
Fixes https://yoast.atlassian.net/browse/P1-140
> Override block editor style for the yoast radio button

- admin/tracking/class-tracking-settings-data.php
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/admin/workouts-integration.php
- src/routes/workouts-route.php
- wp-seo-main.php
Slack thread for reference: https://yoast.slack.com/archives/C027BFR5L/p1638353248381200
The desired behaviour should be: when a user activates the plugin the `first_time_install` option is set to `true`, which means we are assuming we are looking at a first-time user. When the configuration workout is finished, then this value is set to `false`. 
The notification should only be shown to users when they have this `first_time_install` value set to `true` in combination with the existing requirements. So as soon as the configuration workout has been finished once, the notice should never be shown again (unless the free plugin is deactivated and activated again - and the value is set back to `true`). 
* Fixes a bug where the …
> Only show First-time configuration notice to first-install users

- src/actions/wincher/wincher-keyphrases-action.php
- tests/unit/actions/wincher/wincher-keyphrases-action-test.php
* Don't collect keyphrases from taxonomies when using the "Add existing keyphrases" functionality.
* Fixes a bug where the "Add existing keyphrases" functionality of the Wincher integration would collect and add keyphrases from taxonomies as well.
*
* Change the focus keyphrase of a taxonomy
* Use the "Add existing keyphrases" button
* Ensure that the focus keyphrase you set on the taxonomy was not added to Wincher.
*
*
Fixes #
> Wincher: ensure that collect_all_keyphrases does not collect from taxonomies

- admin/class-admin-asset-manager.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy.php
- packages/js/package.json
- packages/js/src/classic-editor.js
- packages/js/src/watchers/classicEditorWatcher.js
- yarn.lock
* Implement our SEO integration within the classic editor as a first target. This PR is giving a JS entry point to start the SEO integration from, it is not yet functional (and actually produces errors).
* Replaces the classic editor integration with a sketch of our SEO integration setup.
*
The classic editor should now load in our integration. Both for posts and for taxonomies.
But it does not function and produces errors in this PR. The Main thing to see is that the old metabox is gone
* N/A for this specific PR
* Other editor should be …
> Sketch initial classic editor setup

- css/src/workouts.css
*
* [wordpress-seo-premium] Fixes an unreleased bug where the steps in the premium workouts would not be greyed out on finishing a step.
* Fixes an unreleased bug where there was too much whitespace between the title and the workflow within the workouts.
*
* Install and activate Free and Premium.
* Open the configuration workout. See the spacing between the title and the subtitle is correct (see screenshots below).
* Finish all steps for the configuration workout. Make sure none of the steps are greyed out when finished.
* Open the cornerstone workout. See the spacing between the title and the subtitle is correct (see screenshots below).
* Finish all the steps for the …
> DUPP-124 small styling fixes workouts

- packages/js/src/workouts/components/ConfigurationWorkout.js
* Fix a bug with indexing state not updating within the workoutspage.
* Fixes a bug where the state of indexation was not persisted when switching between workouts and the workouts page.
* 
* Verify that the following does NOT happen anylonger:
1. reset indexables with the yoast test helper if you haven't done so
2. go to the configuration workout
3. complete step 1 by running the indexation
4. click go back to workouts
5. click on the configuration workout again
6. step 1 now says you should still do indexation, but when you click it it completes VERY quickly
7. repeat going back to workouts by clicking back to workouts, and go to configuration again
8. it's again not …
> Persist indexation state when moving back and forth between workouts

- packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/languages/ca/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/es/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/fa/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/he/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/it/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/ja/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/pt/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/ru/config/sentenceLength.js
- packages/yoastseo/src/languageProcessing/languages/tr/config/sentenceLength.js
- packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
* Adapts the sentence length assessment for Japanese: the recommended sentence length is set to 40 characters (rather than 20 words in the default assessor)
* [yoastseo] Adapts the sentence length assessment for Japanese.
* Changed the config item `recommendedWordCount` to `recommendedLength` to reflect that the length of a sentence need not necessarily be measured in number of words.
Note: you can use a [Japanese lorem ipsum generator](https://generator.lorem-ipsum.info/_japanese) in combination with a [character counter](https://wordcounter.net/character-count) to create texts for testing.
* Enable the …
> Adapt sentence length assessment for Japanese

- src/actions/wincher/wincher-keyphrases-action.php
- tests/unit/actions/wincher/wincher-keyphrases-action-test.php
- wp-seo-main.php
Keywords of trashed posts should not  be included when using "Add existing keyphrases" because they're no longer relevant.
* Fixes an unreleased bug where trashed keyphrases where included when using the "Add existing keyphrases" of the Wincher integration.
*
1. Have less than 5 posts with a keyphrase set (and no term)
2. Trash one of those posts
3. Visit SEO > General > Integrations and click on "Add existing keyphrases to Wincher"
* 
*
Fixes #
> Wincher: do not include trashed posts when using "Add existing keyphrases" 

- packages/js/src/workouts/components/ConfigurationWorkoutCard.js
- packages/js/src/workouts/components/CornerstoneWorkoutCard.js
- packages/js/src/workouts/components/OrphanedWorkoutCard.js
- packages/js/src/workouts/components/WorkoutCard.js
* Dario requested more defined and specific ids per workout card to help with automated testing.
* Adds specific id's to several elements on the workout cards.
* Verify that the workout cards, usps (green checkmark thingies), buttons (also check with and without premium active), and locked sections (when you have not done the configuration workout yet) have specific ID's.
* You can do so by opening the element inspector, clicking the "highlighting arrow" and hover over the elements. Id's are recognisable by looking like so: `div#my-specific-id` when you hover, or as `id="my-specific-id"`
*
This PR affects the following parts …
> Allow passing of id to card and add more ids to its contents

- inc/options/class-wpseo-option-wpseo.php
- src/conditionals/installation-success-conditional.php
- src/integrations/admin/installation-success-integration.php
- src/integrations/admin/workouts-integration.php
- tests/unit/integrations/admin/installation-success-integration-test.php
- wp-seo-main.php
* We want to redirect to a new installation successful page after the first activation
* Introduces the integration and the feature flag for the "installation successful" page.
*
* deactivate Yoast SEO Free
* add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* reactivate Yoast SEO Free
* You should be redirect to a blank page with URL `{admin_path}/admin.php?page=wpseo_installation_successful_free`
* deactivate Yoast SEO Free
* reactivate Yoast SEO Free
* you shouldn't be redirected anymore
* deactivate Yoast SEO Free
* comment out `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` in your `wp-config.php` file
* reactivate Yoast SEO …
> DUPP-136 installation success integration

- packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
- packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getKeyphraseLengthSpec.js
- packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getKeyphraseLength.js
*
* [yoastseo] Adds custom `keyphraseLength` research for Japanese.
* I named the custom research inside Japanese folder `getKeyphraseLength` instead of just `keyphraseLength`. This is to avoid confusion later when the `keyphraseLength` config is also added in the researcher.
**Note**: This PR cannot be tested on Docker yet since the Keyphrase length assessment is not yet adjusted.
* Run `yarn test` and make sure there is no failing tests.
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-1099
> Adapt keyphrase length research for Japanese

- admin/views/tabs/metas/paper-content/integrations/wincher.php
* Fix typo
* Fix typo in limit reached message of the Wincher integration.
*
*
*
*
Fixes #
> QA-2602 Wincher: remove extra dot from limit reached message

- packages/js/src/workouts/components/CornerstoneWorkoutCard.js
- packages/js/src/workouts/components/OrphanedWorkoutCard.js
* Reverts #17729
* Removes the configuration workout as a prerequisite for the Premium workouts.
* We just remove the variables on which the condition is triggered, but the overaly is still there for future use if needed.
* Install and activate Premium > 17.7
* visit SEO > Workouts
* if the Configuration workout is already completed, restart it and then navigate back to the workouts overview
* check that the premium workouts are still accessible even with the conf. workout not completed, and you don't see the "required" overlay hiding the buttons
* disable premium and check that you can see the upsell buttons for the premium workouts …
> DUPP-145 Revert conf. workout prerequisite

- packages/yoastseo/spec/fullTextTests/runFullTextTests.js
- packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/UrlKeywordAssessmentSpec.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/runFullTextTests.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
- packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
- packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
* In Japanese, URLs are often written in Latin characters. Due to potential encoding errors, this is actually the preferential way of writing them. Therefore it doesn't make sense to ask for the Japanese keyphrase to be included in the slug.
* [yoastseo] Disables the keyphrase in slug assessment for Japanese.
*
* Enable the JAPANESE_SUPPORT feature by adding `define( 'YOAST_SEO_JAPANESE_SUPPORT', true );` in `basic-wordpress-config.php`.
* Change the site language to Japanese (`日本語`).
* Open a new post.
* Set a keyphrase.
* Make sure the slug is filled in and doesn't contain your keyphrase.
* You **should not** see the assessment feedback with an orange bullet and the …
> Disable keyword in slug assessment for Japanese

- tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
1. The `Mockery::close()` is already handled by the parent `tear_down()`, or rather, the `Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration` trait used by the parent class handles this, so the `tear_down()` method is redundant.
2. The Mockery `allows()` method allows for passing an array of functions with their return value, so let's use that instead of calling the method multiple times.
Ref: http://docs.mockery.io/en/latest/reference/alternative_should_receive_syntax.html?highlight=allows#allows
3. The if/else to return a boolean value is unnecessary. Returning the result of the condition does the same.
* _N/A_ This change only involves the …
> WPSEO_Admin_Gutenberg_Compatibility_Notification_Test: minor fixes/simplification

- tests/unit/helpers/schema/html-helper-test.php
This refactors both the `test_sanitize()` and `test_smart_strip_tags()`  tests to use data providers.
This:
1. Makes it easier to debug the test as the data provider will show a descriptive name for the failing test case and the test method itself now only contains one assertion instead of multiple.
2. Auto-documents the test cases by using named data providers.
3. Allows for more easily adding additional test cases.
Note: The actual test cases themselves have not been changed by this refactor, though the order in which they are run has (to more closely match the logic order in the method under test).
Includes changing the used assertion from `assertEquals()` (loose type check) to …
> HTML_Helper_Test: improve tests

- tests/unit/helpers/date-helper-test.php
1. Use type strict assertions in the tests (`assertSame()` instead of `assertEquals()`.
2. Use named data sets and remove the redundant `$message` parameter.
The `$message` parameter for assertions is (mostly) intended to be used when there are multiple assertions within one test.
When there is just one assertion and the test uses a data provider, naming the data sets is the better way to allow for identifying which test case failed.
Includes fixing one test case "Test formatting the date to a timestamp" in the `format_provider()` method where the "expected" value was set as an integer, while the function returns a string.
... to document the behaviour when an integer is passed.
... to …
> Date_Helper_Test: improve tests

- tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
The `unregister_taxonomy()` function call may not be executed when the tests fails before reaching that point. In this case, that's unlikely as the tests don't contain assertions, but only expectations.
Still, as a matter of best practice and example, I'm moving the `register_taxonomy()` and `unregister_taxonomy()` function calls to the `set_up()` and `tear_down()` fixture methods.
* _N/A_ This change only involves the tests. If the build passes, we're good.
> WPSEO_Sitemap_Provider_Overlap_Test: stabilize the tests

- css/src/installation-success.css
- packages/js/src/installation-success.js
*
* Adds the skip link to free the installation success page.
*
* Enable the feature flag: add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* Navigate to `{admin-url}/admin.php?page=wpseo_installation_successful_free`.
* See the Skip link matches the [design](https://www.sketch.com/s/d8601833-a14f-4dff-bee0-426acfa4a2c8/a/098oodO/play).
* See the skip link navigates you to the SEO Dashboard.
* N/A
*
*
Fixes [DUPP-132](https://yoast.atlassian.net/browse/DUPP-132)
> Add skip link to free installation success page

- tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-data.php
* Use `assertSame()` instead of `assertEquals()` where applicable
* Change one test to use a data provider instead of having multiple test cases within the test method.
* _N/A_ This change only involves the tests. If the build passes, we're good.
> WPSEO_Sitemaps_Cache_Data_Test: improve tests

- css/src/alerts.css
- packages/components/src/Alert.js
- packages/components/tests/__snapshots__/AlertTest.js.snap
- packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
*
* Changes the font size of the alerts from 14px to 13px.
*
* Navigate to SEO > Social > Facebook.
* Set `Add Open Graph meta data` to `Enabled`.
* Check the font-size of the alert is 13px.
* Navigate to SEO > Search Appearance.
* Remove your Organization / Person name or logo.
* Check the font-size of the alert is 13px. 
*
*
Fixes [DUPP-119](https://yoast.atlassian.net/browse/DUPP-119)
> Change font size alerts from 14px to 13px

- admin/formatter/class-metabox-formatter.php
- packages/js/src/initializers/block-editor-integration.js
* We want to fix the Wincher's integration feature flag
* Fixes the Wincher integration's feature flag
* We also put the post-publish panel under the right condition since it was displayed even with the Wincher integration non active
* set the wincher feature flag **ON**
* make sure Wincher is enabled
* set the wincher feature flag **OFF**
* edit a new post (in Block editor, Classic Editor and Elementor) and check that the "Track SEO performance" section is not there in the metabox
* add a keyphrase
* in the block editor, publish the post
* see that in the sidebar there is no "SEO Performance" section mentioning Wincher.
* set the wincher feature flag **ON**
* edit a new …
> Fix wincher feature flag

- tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
- tests/unit/actions/wincher/wincher-keyphrases-action-test.php
* Improves test suite
* Improves test suite
* _N/A_
> Tests: fix some incorrect `@covers` tags

- src/presenters/open-graph/image-presenter.php
* The `og:image:type` meta was likely never output since the introduction of the indexables, because this code exists like this since the beginning of the indexables.
* Fixes a bug where the `og:image:type` meta was not output correctly. Props to [dodomorandi](https://github.com/dodomorandi).
* Maybe the value of this array item needs to me `meta-type` as a sort of description. But I could not find this being used anywhere so I chose not to change anything else.
* Set an image as the Facebook image for a post
* Without this PR, no `og:image:type` is output in the metatags of the post on the frontend.
* With this PR, the `og:image:type` is correctly output. …
> 17727 Fix `og:image:type` meta output.

- packages/js/src/analysis/refreshAnalysis.js
* One of the artifact size optimisations accidentally broke the readability analysis for terms pages. This PR fixes that.
* Fixes an unreleased bug where the readability analysis was broken on terms pages only.
* Directly import `setOverallReadabilityScore` and `setOverallSeoScore` from `yoast-components`, because the **wrapped version** from `packages/js/src/redux/actions/index.js` breaks for terms pages due to a bad DOM element sync in `packages/js/src/helpers/fields/AnalysisFields.js`
* Go to a terms page, ie. categories or tags.
* Check if the readability analysis works as expected.
*
This PR affects the following parts of …
> Fix readability analysis for terms

- src/integrations/admin/installation-success-integration.php
- tests/unit/integrations/admin/installation-success-integration-test.php
* We want to prevent the installation success page to be displayed when the plugin is activated as part of a bulk activation.
* Prevents the installation success page to be displayed when the plugin is activated in bulk.
* Also added a unit test that was missing from #17767 
* add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* deactivate Yoast SEO Free
* make sure that `activation_redirect_timestamp_free` in `wpseo` is set to 0;
* select Yoast SEO Free and another inactive plugin (e.g. Yoast Test Helper - not Premium!)
* select `Activate` in the bulk actions menu and apply
* You **should NOT** be redirected to a blank page with URL …
> DUPP-137 install success bulk action

- src/integrations/admin/installation-success-integration.php
- tests/unit/integrations/admin/installation-success-integration-test.php
*
* Only shows the Premium installation success screen when Free and Premium are activated simultaneously. 
*
* Enable the feature flag: add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* Clean and restart your docker.
* Activate Premium (this should automatically activate Free as well).
* You should be redirected to the Premium installation success screen (and not the free one).
* In the database check `activation_redirect_timestamp` in `wpseo_premium` has a value (other than 0), and check `activation_redirect_timestamp_free` in `wpseo` has a value (other than 0).
* It should behave the same way. …
> Don't redirect to free success page when also activating Premium

- src/routes/importing-route.php
* We want to prevent editors from being able to use the new `import/conflicting-plugins/deactivation` endpoint to deactivate plugins
* We also want to stop adding the new endpoints unless the feature flag is enabled.
* Fixes a bug where an editor would be able to deactivate plugins using a newly introduced endpoint
* Use the `AIOSEO_V4_Importer_Conditional` conditional before registering the new importing route, so that the new endpoints won't be available without the feature flag.
* Have the `activate_plugins` capability as `permission_callback` for the new importing endpoints (instead of `edit_posts` that used to be there)
Notes:
* You should have the AIOSEO plugin …
> Only allow admins to use the deactivating plugins endpoint

- wp-seo-main.php
* We want to avoid displaying the installation success screen when the plugin is activated using WP CLI
* Prevents the installation success page to be displayed when the plugin is activated using WP CLI
*
* add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* deactivate Yoast SEO Free
* make sure that `activation_redirect_timestamp_free` in `wpseo` is set to 0;
* use WP CLI to activate the plugin: open a terminal, cd to the WP folder and `wp plugin activate wordpress-seo`
* if you are using our docker env, you can use `./wp.sh plugin activate wordpress-seo` from the docker env folder
* visit any page in the backend
* You **should NOT** be …
> DUPP-135 Prevent installation success to be displayed when activating with WP CLI

- css/src/installation-success.css
- packages/js/src/installation-success.js
* We want to improve the looke of the installation success page on mobile screens
* Improves the look of the installation success page on mobile screens.
*
* add `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` to your `wp-config.php` file
* visit the installation success page (URL: `{domain}/wp-admin/admin.php?page=wpseo_installation_successful_free`)
* check that the look hasn't changed from the expected design
* switch to mobile view and shrink the width of the screen until it becomes less than 768px
* you should now see the mobile version of the screen:
* the stepped is to the left side and it's vertical
* the cards are on the right side and they are in a column
* …
> DUPP-144 Improve style of the installation success page on mobile screens

- src/integrations/admin/installation-success-integration.php
- tests/unit/integrations/admin/installation-success-integration-test.php
*
* Avoids redirecting to the installation succes page when  Yoast SEO is activated in the network admin. 
*
_Network activation_
* Make sure you have the `YOAST_SEO_INSTALLATION_SUCCESS` feature flag enabled.
* Use a fresh environment, or make sure Yoast SEO is not activated for any of the subsites and the `activation_redirect_timestamp_free` timestamp is set to `0` for all subsites.
* Visit the Network admin of a multisite.
* Network activate Yoast SEO and see you are not redirected to the installation success page.
* Visit the admin of one of the subsites (make sure you check one of the other subsites than the main one!) and see you are not redirected to the …
> DUPP-167 Deal with showing installation success for network activation of the plugin

- admin/class-admin.php
- inc/sitemaps/class-author-sitemap-provider.php
* WP 5.9 [deprecates](https://core.trac.wordpress.org/ticket/16841#comment:80) the `'who'` parameter in `get_users()`. We want to avoid a warning to be displayed.
* Fixes a bug where a deprecation notice would be displayed when using WordPress 5.9.
* Also removes an outdated `use` statement for a non-existing `Wincher_Links` class.
* make sure you have `WP_DEBUG` set to `true`
* disable Debug Bar and Query Monitor to make sure you can see the warning
* install and activate the WordPress Beta Tester plugin
* make sure you have at least:
* a user with role `Contributor` or higher who *doesn't* have any published post (call it A)
* a user with role `Subscriber` who *does* …
> DUPP-164 Use `capability` instead of deprecated `who` param in WP 5.9

- packages/js/src/classic-editor/components/advanced-settings.js
- packages/js/src/classic-editor/components/cornerstone-content.js
- packages/js/src/classic-editor/components/google-preview.js
- packages/js/src/classic-editor/components/metabox/index.js
* Setup the 'Cornerstone content' component
* Made components for `AdvancedSettings` and `GooglePreview` to be consistent and increase the readability of the `metabox` component
* Setup the 'Cornerstone content' component
*
* Verify the cornerstone content toggle toggles the `isCornerstone` value in our Seo store
*
*
Fixes P1-1115
> P1-1115 Setup cornerstone component

- src/actions/wincher/wincher-account-action.php
- src/routes/wincher-route.php
* Sending requests to the Wincher endpoints without having connected first caused some endpoints to throw exceptions. This fixes that.
* Improve error handling for certain Wincher routes. 
*
* Enable Wincher integration but do not actually Connect
* Send authenticated requests to Wincher endpoints and make sure that they do not throw an exception:
- `GET` request to `http://basic.wordpress.test/wp-json/yoast/v1/wincher/limits`
- `POST` request to `http://basic.wordpress.test/wp-json/yoast/v1/wincher/keyphrases/track` with body `{ "keyphrases": []  }`
- `POST` request to `http://basic.wordpress.test/wp-json/yoast/v1/wincher/keyphrases/track/all` with no body
QA can test …
> QA-2601 Wincher: Fatal error on routes if no token is present

- lib/model.php
As of PHP 8.1 get_class_vars doesn't return the _current_
value of any static property anymore. The function was never intended
to do so. Instead, it returns the initial value of the property,
which is `null` in the case of our models.
* Fixes a bug where using the plugin would throw a fatal error ("Table yoast_wp_seo_models_indexable doesn't exist") when using PHP 8.1.
*
* 
* Use PHP 8.1
* Update any post
* See that you don't get an error
* See that your changes were saved
*
> Fix 8.1 compatibility: Table yoast_wp_seo_models_indexable doesn't exist

- admin/class-yoast-dashboard-widget.php
- admin/formatter/class-metabox-formatter.php
- src/helpers/wincher-helper.php
- src/routes/wincher-route.php
* Disallow contributors from using the Wincher integration.
* Fixes a bug where contributors still had access to the Wincher integration.
* Moved wincher active check to a shared helper function in Wincher_Helper.
* Enable the Wincher integration and Connect to Wincher
* Log in as Contributor
* Go to Dashboard, verify that there is no trace of Wincher in the Dashboard widget
* Edit a post
* Verify that there is no "Track SEO Performance" in the metabox or side bar.
*
*
Fixes #
> QA-2612 Disallow contributors from using the Wincher integration

- src/generators/schema/organization.php
- src/generators/schema/person.php
- tests/unit/generators/schema/organization-test.php
- tests/unit/generators/schema/person-test.php
* Makes sure we don't output the same `sameAs` URL twice on `Person` and `Organization`.
- in SEO > Search Appearance, set "Organization" and add name and logo
- in SEO > Social, add a Twitter nickname and some social URLs, making sure that some of them are duplicated
- visit the home page in the front end and inspect the Schema
- check that the `Organization` piece doesn't display duplicated URLs in `sameAs`
- pick a user which is the author of some posts
- add a Twitter nickname and some social URLs, making sure that some of them are duplicated
- visit in the front end one of the user's posts and inspect the Schema
- check that the `Persone` piece doesn't display …
> Schema sameAs URLs should be unique

- packages/components/src/Toggle.js
- packages/js/src/components/WincherKeyphrasesTable.js
- packages/js/src/components/WincherPerformanceReport.js
* Fixes a bug where the metabox UI was broken on mobile when the Track SEO Performance dialog was open.
* Fixes a bug where the metabox UI was broken on mobile when the Track SEO Performance dialog was open.
* Had to add `position: relative;` to the Toggle container. I don't think this should impact anything else.
* Load post editor with a mobile viewport
* Ensure that layout is not broken when opening the "Track SEO Performance" box.
*
*
Fixes #
> QA-2610 Wincher: Use horizontal scroll for table on mobile

- composer.json
- config/dependency-injection/services.php
- src/deprecated/frontend/frontend.php
* Reverts https://github.com/Yoast/wordpress-seo/pull/17671
* Reverts the removal of the deprecated `WPSEO_Frontend` class.
*
* NA the class is not used anymore so it shouldn't have any effect. Just do a smoke test to check the plugin is working (open a post, and one of the admin pages).
*
*
Fixes [DUPP-175]
[DUPP-175]: https://yoast.atlassian.net/browse/DUPP-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DUPP-175 Revert the removal of WPSEO_Frontend

- packages/js/src/components/WincherPerformanceReport.js
* Add more context about the keyphrases listed in the overview on the dashboard.
* Add explanation to the Wincher keyphrases table on the dashboard. 
*
* Enable Wincher integration and connect
* Track one or more keyphrases
* Visit the WordPress Dashboard
* Ensure that there's a text at the keyphrases table like this "This overview only shows you keyphrases added to Yoast SEO. There may be other keyphrases added to your <link>Wincher account</link>."
*
*
Fixes #
> QA-2616 Wincher: add explanation to table on the Dashboard

- src/integrations/third-party/elementor.php
* Slugs were not initialized for draft posts in elementor because they generally don't have a saved `post_name`, leading to unexpected behavior such as the Wincher modal not working and the permalink field of the Google Preview modal being empty.
* Fixes a bug where slugs were not loaded for draft posts in Elementor. 
* 
* Add a new draft post and edit it with Elementor.
* Ensure that the permalink field of the "Google preview" modal is set correctly.
* Ensure that the "Track SEO Performance" modal does not display an error message like this: "Before you can track your SEO performance make sure to set either the post’s title and save it as a draft or manually set the …
> QA-2596 Fix loading of slugs for drafts in Elementor

- css/src/workouts.css
*
* Improves the Workouts overview for mobile screens.
*
* Navigate to the Workouts overview
* Check that the look hasn't changed from the expected design
* Switch to mobile view
* See the description width now fits the page better
*
*
Fixes DUPP-121
> Decrease max-width of description workouts overview for mobile screens

- src/conditionals/wincher-conditional.php
* Disable Wincher for multisite environments.
* Disables the Wincher integration for multisite environments.
* Decided to add this to the same conditional to not duplicate logic since the integration should be completely and fully hidden for multisite installs.
* Setup a multisite environment
* Add `define('YOAST_SEO_WINCHER_INTEGRATION', true);` to your wp-config.php
* Navigate to SEO > General > Integrations and see that there is no Wincher integration toggle.
* Edit a post, and see there is no Wincher item to Track SEO performance in (1) the sidebar and (2) the metabox.
* Navigate to the WordPress Dashboard and make sure you don't see any Wincher information in the …
> QA-2606 Disable Wincher integration for multisite environments

- lib/model.php
- lib/orm.php
* Preparation for PHP 8.1 compatibility.
* prevents many deprecation warnings in preparation for PHP 8.1 compatibility. Thanks @jrfnl ! 
As of PHP 8.1, PHP will start throwing deprecation warnings along the lines of:
```
Deprecated:  Return type of [CLASS]::[METHOD]() should either be compatible with [PHP NATIVE INTERFACE]::[METHOD](): [TYPE], or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```
These type of deprecation notices relate to the [Return types for internal methods RFC](https://wiki.php.net/rfc/internal_method_return_types) in PHP 8.1.
Basically, as of PHP 8.1, these methods in classes which implement PHP native interfaces are expected to have a return type declared.
The …
> PHP 8.1: fix "missing return type" deprecation warnings

- inc/sitemaps/class-sitemap-cache-data.php
- inc/sitemaps/class-sitemaps-cache.php
- tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-data.php
- tests/integration/sitemaps/test-class-wpseo-sitemaps-cache.php
* Prepares for compatibility with PHP 8.1 by implementing magic methods used by PHP7.4 and up.
PHP 7.4 introduced the magic `__serialize()` and `__unserialize()` methods as an improved way to handle object serialization compared to the `Serializable` interface and/or the magic `__sleep()` and __wakeup()` methods.
As of PHP 8.1, implementing the `Serializable` interface is deprecated, unless the class also implements the new magic methods.
The `WPSEO_Sitemap_Cache_Data` class implements the `Serializable` interface and would throw the following deprecation notice on PHP 8.1:
```
Deprecated: WPSEO_Sitemap_Cache_Data implements the Serializable interface, which is deprecated. Implement …
```
> PHP 8.1 | WPSEO_Sitemap_Cache_Data: implement magic serialization methods

- tests/unit/actions/addon-installation/addon-activate-action-test.php
- tests/unit/actions/addon-installation/addon-install-action-test.php
Both the `Addon_Activate_Action_Test::test_activate_addon_activation_result_is_null()`, as well as the `Addon_Install_Action_Test::test_install_addon_thows_when_install_fails()` test would throw a `"Exception::__construct(): Passing null to parameter #1 ($message) of type string is deprecated"` deprecation notice on PHP 8.1 due to the mock for WP_Error not being complete (not returning a value for `WP_Error::get_error_message()`).
Fixed now.
Includes renaming two tests in the `Addon_Activate_Action_Test` class to be more descriptive.
* This is a test-only change. This change should have no effect …
> PHP 8.1 | Tests: fix two incomplete mocks

- admin/class-gutenberg-compatibility.php
In PHP 8.1, the `test_manage_notification_gutenberg_show_notification()` test throws a `version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated` notification causing the test to error out.
Let's unpack this one:
The `version_compare()` function is called from the `WPSEO_Admin_Gutenberg_Compatibility_Notification::is_below_minimum()` method and expects the `$current_version` property to be set.
The default state of the `$current_version` property is "uninitialized", however, in "real" life, the property will always have a value as the constructor of the `WPSEO_Admin_Gutenberg_Compatibility_Notification()` will always set …
> PHP 8.1 | WPSEO_Admin_Gutenberg_Compatibility_Notification: fix null to non-nullable notice

- src/surfaces/meta-surface.php
- tests/unit/surfaces/meta-surface-test.php
* Improves compatibility with PHP 8.1 by preventing the use of null values.
As the `Meta_Surface::for_url()` method contains a diverging path specifically for date archives, a test needs to be added covering that path.
As the expectation setting in the test function needs changing to accommodate for data archives, we may as well also adjust the "Home page" test cases to be more realistic, i.e. set these to use a `$url` without path component.
This way, the changes being made to accommodate the date archive test, will not hide a PHP 8.1 deprecation notice which is triggered on a `$url` without path component being passed to the `Meta_Surface::is_date_archive_url()` method.
Previously, all test …
> PHP 8.1 | Meta_Surface::is_date_archive_url(): prevent null to non-nullable deprecation notice

- src/helpers/schema/html-helper.php
- tests/unit/doubles/stringable-object-mock.php
- tests/unit/helpers/schema/html-helper-test.php
* Improves compatibility with PHP 8.1 by validating input types
This adds a data provider to both test methods which sets the tests up with unexpected data types and sets expectations on how those should be handled.
As things are, a select number of these tests will fail/error out:
* `true` would currently return `1` instead of an empty string.
* Both array and object would currently throw a warning in PHP 7.4 and a type error on PHP 8.0+.
* `null` would throw a deprecation on PHP 8.1.
As of PHP 8.1, passing `null` to not explicitly nullable scalar parameters for PHP native functions is deprecated.
In the tests, a number of errors could be seen along the lines of:
```
preg_replace(): Passing …
```
> PHP 8.1 | HTML_Helper: add input validation

- src/generators/schema-generator.php
* Improves compatibility with PHP 8.1 by filtering invalid values.
The `Schema_Generator::get_type_from_piece()` method _does_ check that the `$piece['@type']` is set, but doesn't check if every value within an array set as `$piece['@type']` is actually set.
This is exposed by the existing test case for the FAQPage in the `Schema_Generator_Test::get_expected_schema()` method, where the `@type` is deliberately set as `[ null, 'FAQPage' ]`.
This in turn on PHP 8.1, leads to "passing null to non-nullable" deprecation notices for the `strtolower()` function call in the `Schema_Generator::type_filter()` method.
As `null` as a type is not useful anyway and is (was) ignored/discarded in the …
> PHP 8.1 | Schema_Generator::get_type_from_piece(): prevent null to non-nullable deprecation notice

- src/helpers/current-page-helper.php
As per the documentation, the PHP native `filter_input()` function will return the value of a variable, `false` if the filter fails or `null` if the variable is not set.
While it will be rare for the `page` variable to not be set for an active request to WP, it is common in test situations (and I believe also possible in non-test situations), which would result in `filter_input()` returning `null`.
As of PHP 8.1, passing `null` to a non-nullable PHP native function will generate a deprecation notice, which is what will happen when the `$_GET['page']` is not set and is subsequently passed to the PHP native `strpos()` function.
Verifying that the returned …
> PHP 8.1 | Current_Page_Helper::is_yoast_seo_page() prevent null to non-nullable deprecation notice

- src/models/indexable.php
- tests/unit/models/indexable-test.php
* Improves handling of multi-byte languages
* Improves handling of multi-byte languages
The `$primary_focus_keyword` property is a (dynamic/managed via magic methods) property on the `ORM` class. This property may or may not be set at the time of a save.
As of PHP 8.1, passing `null` to a non-nullable PHP native function will generate a deprecation notice, which is what will happen when the `$primary_focus_keyword` property has not been set (yet) and is subsequently passed to the PHP native `strlen()` function.
Verifying that the property is a string before passing it to `strlen()` prevents the notice without BC-break.
Note: I've elected to verify the …
> PHP 8.1 | Indexable::save() prevent null to non-nullable deprecation notice + multi-byte language fix

- src/helpers/date-helper.php
- tests/unit/helpers/date-helper-test.php
As of PHP 8.1, passing `null` to not explicitly nullable scalar parameters for PHP native functions is deprecated.
In the tests, a number of errors could be seen along the lines of:
```
date_create_immutable_from_format(): Passing null to parameter #2 ($datetime) of type string is deprecated
```
In this case, both methods in the `Date_Helper` class expect a `string` as input, but it is not verified that they actually receive a `string` and the received parameter is blindly passed on to PHP native functions.
As running `date_create_immutable_from_format()` is useless when no valid date/timestamp is passed, we can short circuit both functions by doing a …
> PHP 8.1 | Date_Helper: add input validation (x2)

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/NewsletterSignup.js
- src/integrations/admin/configuration-workout-integration.php
*
* Adds system tracking parameters to the shortlinks in the configuration workout. 
*
* Navigate to the configuration workout.
* Check that all links contain (at least) the PHP version.
*
*
Fixes #
> Pass tracking params to shortlinks configuration workout

- inc/sitemaps/class-sitemaps-renderer.php
* Improves compatibility with PHP 8.1 by filtering invalid values.
This fixes an issue with a call to the PHP native `http_build_query()` function, the second parameter of which is the _optional_ `$numeric_prefix` parameter which expects a `string`.
A parameter being optional, however, does not automatically make it nullable.
As of PHP 8.1, passing `null` to a non-nullable PHP native function will generate a deprecation notice.
In this case, this function call yielded a `http_build_query(): Passing null to parameter composer#2 ($numeric_prefix) of type string is deprecated` notice.
Changing the `null` to an empty string fixes this without BC-break.
Note: the tests which are being added in …
> PHP 8.1: fix deprecation warning / http_build_query()

- admin/class-yoast-dashboard-widget.php
- admin/formatter/class-metabox-formatter.php
- admin/views/class-yoast-integration-toggles.php
- admin/views/tabs/metas/paper-content/integrations/wincher.php
- packages/js/src/components/WincherSEOPerformanceModal.js
- src/actions/wincher/wincher-account-action.php
- src/conditionals/non-multisite-conditional.php
- src/conditionals/wincher-conditional.php
- src/helpers/wincher-helper.php
- src/integrations/third-party/wincher.php
- tests/unit/admin/views/integration-toggles-test.php
- tests/unit/conditionals/non-multisite-conditional-test.php
- tests/unit/conditionals/wincher-conditional-test.php
- tests/unit/integrations/third-party/wincher-publish-test.php
- tests/unit/integrations/third-party/wincher-test.php
* We want to enable the Wincher integration, currently behind a feature flag.
* Introduces a keyphrase position tracking tool that gives insight into how your content ranks in the search results. Powered by Wincher. 
* The `Wincher_Conditional` implementing the feature flag has been re-worked into a "standard" conditional extending a new `Non_Multisite_Conditional`. This makes it easier to refactor the `Wincher_Conditional` to add/change conditions.
* A new Wincher integration has been added to nicely use conditionals to add the integration toggle in SEO > Integrations.
* remove `define( 'YOAST_SEO_WINCHER_INTEGRATION', true );` from `wp-config.php`
* check that the …
> Change the Wincher feature flag into a regular conditional based on a new Non_Multisite conditional

- inc/class-wpseo-utils.php
* Make the schema output more friendly to non-alphanumeric languages.
* There have been comments that the unicode escaping was hurting SEO performance. I could not find any evidence for this.
* Not escaping the unicode characters may reduce the overall character count / size of the schema by quite a bit, which is preferable.
* It makes debugging in other languages more user-friendly.
* Enhances schema presentation for languages that are not alphanumeric. Props to [sous-studio](https://github.com/sous-studio)
* Did some additional investigation into the security-side of enabling this flag. I was unable to find anything that could seriously go wrong with this flag enabled. …
> Add JSON_UNESCAPED_UNICODE flag for schema output

- src/actions/importing/abstract-aioseo-settings-importing-action.php
- src/actions/importing/aioseo-posttype-defaults-settings-importing-action.php
* We want to import the `Show Meta Box` setting when importing AIOSEO settings
* Enhances the importing of settings from AIOSEO by importing wether or not we should show meta boxes for each post type.
* Added a new key/value pair in the aioseo_to_yoast map array to cover this setting
* Have Books and Movies custom post types enabled
* Have AIOSEO and Yoast activated
* Have the `YOAST_SEO_AIOSEO_V4_IMPORTER` feature flag enabled (defined to `true`). If it's disabled, the POST call mentioned below will return 404.
* Go to the AIOSEO->Search Appearance page in the Content Types tab
* In the Advanced tab of every post type there, set the `Show AIOSEO Meta Box` setting
* Do …
> Import showMetaBox setting when importing posttype settings

- css/src/installation-success.css
- src/integrations/admin/installation-success-integration.php
* We want the installation success page to display translations
* Fixes a bug where the installation success page would not display the translations.
* Also fixes a small issue in CSS building step where `flex-start` was suggested to be used instead of `start`
* make sure you have the feature flag `YOAST_SEO_INSTALLATION_SUCCESS` set to `true`
* build the branch
* check that on `grunt build` you don't see this:
```
Running "postcss:build" (postcss) task
>> autoprefixer: /home/lopo/src/Yoast/plugin-development-docker/plugins/wordpress-seo/css/dist/installation-success-1780.css:5:2: start value has mixed support, consider using flex-start instead
>> 27 processed stylesheets …
```
> DUPP-185 fix translations in the installation success page

- packages/js/src/components/WincherKeyphrasesTable.js
- src/actions/wincher/wincher-keyphrases-action.php
- tests/unit/actions/wincher/wincher-keyphrases-action-test.php
* Keyphrase limit message was not being shown correctly when trying to add multiple keyphrases at once.
* Fixes bug causing keyphrase limit message not to be shown correctly. 
*
1. Connect Wincher free account with several keyphrases (for instance, 2 keyphrases)
2. Create a post and add 5 keyphrases to it (1 focus keyphrase and 4 related) that aren't already tracked
3. Publish the post
4. On the post publish screen click "Track all keyphrases on this page"
5. Ensure limit reached message is shown
*
*
Fixes QA-2712
> QA-2712 Wincher: fix keyphrase limit message not being shown

- packages/js/src/components/modals/editorModals/EditorModal.js
*
* Fixes a bug where clicking outside of a Yoast modal in the block editor would not close the modal.
It is likely something has changed in WordPress, where presumably a `tabindex=-1` was added to the Modal Screen Overlay (the background that covers the rest of the page while the modal content is displayed). 
Why did that change break our modals?In the past we had a PostSettingsModal where there were some dropdown selects. Because a click on such a dropdown caused the modal to close (as the modal was "blurred), we made a check to see whether at least the background overlay was clicked by checking the `event.relatedTarget`. However, if an item has no tabindex, there is no relatedTarget. Therefore this check has started to always …
> Allow all blur events except media library clicks to close editormodals

- packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getWordFormsSpec.js
- packages/yoastseo/spec/languageProcessing/researches/functionWordsInKeyphraseSpec.js
- packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getWordForms.js
* Adding a related keyphrase that contains only function words triggered 'NaN' and 'Infinity' in feedback strings.
* [yoastseo] Fixes a bug where Japanese keyphrase that contains spaces would give `NaN` or `Infinity` result when matching the keyphrase in the text.
* Removing spaces before processing Japanese keyphrase prevent `NaN`/`Infinity` result when matching the keyphrase in the text.
* This approach also makes more sense, otherwise no forms are outputted at all in `ja/getWordsForms` when the keyphrase contains spaces.
* Build and activate Free and Premium (run `composer require yoast/wordpress-seo:dev-LINGO-1207-fix-counting-related-keyphrase@dev` on the Premium …
> Remove spaces before processing keyphrase in Japanese

- packages/js/src/components/WincherPostPublish.js
- packages/js/src/components/WincherSEOPerformanceModal.js
- packages/js/src/containers/WincherPostPublish.js
* The SEO Performance modal would not be shown after clicking on the "Track all keyphrases" button in the post publish flow if the Yoast side bar was disabled.
* Fixes bug where Track SEO Performance modal would not be shown in post publish.
*
* Connect Wincher account
* Disable Yoast sidebar panel 
* Publish the post
* On the post publish screen click “Track all keyphrases on this page”
* Ensure modal is shown
*
*
Fixes QA-2713
> QA-2713 Wincher: fix modal not shown if Yoast sidebar panel was disabled

- packages/js/src/components/WincherPostPublish.js
*
* Fixes an unreleased bug where the link for the Wincher help icon in the post publish sidebar redirected to google.com.
*
* Create a new post and publish.
* Make sure the Wincher help icon in the post publish sidebar leads to the same Wincher help icon as in the Yoast metabox.
*
*
Fixes #
> Use correct shortlink for wincher help icon in the post publish sidebar

- packages/js/src/redux/selectors/WincherSEOPerformance.js
* Keep tracked keyphrases in the Wincher table even if they are removed as focus or related keyphrase from Yoast. They should be visible until page reload or that they are untracked from Wincher via the table. 
* Improve handling of keyphrases in Wincher so that removed keyphrases are kept in the Table until reload.
*
* Connect Wincher
* Create post and add a focus keyphrase and a related keyphrase
* Open Wincher modal and track both keyphrase
* Close modal and remove the related keyphrase
* Open modal again and ensure that the related keyphrase is still visible in the Table and marked as tracked (green toggle)
* Untrack keyphrase
* Ensure that keyphrase is removed from …
> [QA-2716] Keep tracked keyphrases in Wincher table until untrack/reload

- packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/languages/ja/config/assessmentApplicabilityCharacterCount.js
- packages/yoastseo/src/languageProcessing/languages/ja/config/subheadingsTooLong.js
- packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
- packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
- packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
* Short cornerstone content was erroneously given a red bullet, because the parameter `applicableIfTextLongerThan` was not set. This parameter was introduced during development for Japanese support, but was only set for regular Japanese content. This PR sets the parameter `applicableIfTextLongerThan` for default cornerstone content, product cornerstone content, and Japanese cornerstone content. 
* [yoastseo] Fixes the assessment of short cornerstone content.
* We have removed the parameter`subheadingDistribution` from `packages/yoastseo/src/languageProcessing/languages/ja/config/assessmentApplicabilityCharacterCount.js`, as that had the same function as the parameter `applicableIfTextLongerThan`. By doing so, we create a single …
> Fixes the assessment of short cornerstone content

- composer.json
- composer.lock
- config/php-scoper/oauth2-client.inc.php
* Updates external dependencies
* Updates external dependencies to improve PHP 8.1 compatibility
The `league/oauth2-client` package has released a new version, which includes a PHP 8.1 fix we need.
This commit just updates that package, without updating the underlying dependencies.
Based on the changelog, this should be a safe update.
Ref: https://github.com/thephpleague/oauth2-client/releases
PHP Scoper is prefixing the attribute use statement that will need to be pulled into the TheLeague OAuth Client implementation of the `JSONSerializable` interface.
See thephpleague/oauth2-client#919
This change removes the prefix from the use statement.
PHP Scoper was updated to 0.15.0 during investigation of this issue and it still does …
> PHP 8.1 | Composer: update OAuth2-Client  + underlying dependencies

- packages/js/src/components/WincherKeyphrasesTable.js
* Bug causing request spam to Wincher endpoints.
* Fixes bug that caused spamming to Wincher API endpoints.
* Kept "leading: true" - this will lead to one additional request when typing, but also faster loading when opening the metabox/modal. Think this is preferable for now.
1. Connect to Wincher
2. Open a post and open the Wincher tab in the metabox
3. Open the network tab of the development tools of your browser.
4. Start typing in the keyphrase field of the metabox.
5. Ensure that there is not a spam of POST requests as you're typing. There should be one request initially and then one when you're finished typing.
*
This PR …
> QA-2722 Wincher: fix debounce not working in WincherKeyphrasesTable

- packages/js/src/components/WincherSEOPerformanceModal.js
* Auto focus the focus keyphrase input when trying to open the "Track SEO Performance" modal without any keyphrases. 
* Auto focus the focus keyphrase input when trying to open the "Track SEO Performance" modal without any keyphrases. 
*
* Create new post without a focus keyphrase/related keyphrases
* Resize browser window so that there's a scroll bar in the side bar.
* Scroll the side bar so that the focus keyphrase input isn't in view.
* Click "Track SEO Performance"
* Ensure that you are scrolled up to the focus keyphrase input and that it's focused.
* …
> Wincher: auto focus the focus keyphrase input on no keyphrases

- .travis.yml
* Simplify CI
* Simplify CI
This reverts commit b3999428193d5cdcdd0758dcb7dc060e6992c507.
Composer 2.2.3 has been released which contains a fix for the overly greedy optimization pass which was introduced in Composer 2.2.0.
With this fix in place, the previously introduced work-around for Composer 2.2 is no longer needed.
Refs:
* https://github.com/composer/composer/releases/tag/2.2.3
* https://github.com/composer/composer/issues/10394
> Travis: remove "Fix PHP 8.0 build after composer update"

- inc/class-wpseo-replace-vars.php
- packages/js/src/analysis/blockEditorData.js
- packages/js/src/analysis/classicEditorData.js
- packages/js/src/containers/SnippetEditor.js
- packages/js/src/elementor/containers/SnippetEditor.js
- packages/js/src/redux/selectors/editorData.js
- packages/js/tests/containers/SnippetEditor.test.js
- packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
- packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionLengthAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/ja/config/metaDescriptionLength.js
- packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
* 
* Adapts the recommended meta description length and meta description preview limit for Japanese.
* [search-metadata-preview] Adds locale as one of the props in `SnippetEditor.js` to be used to determine which configuration to use in meta description length progress bar.
* [yoastseo] Adds Japanese configuration for meta description length.
*
Requirements:
* Build the Free plugin
* Install and activate Elementor
* Set the site language to Japanese
Note that the meta description length is calculated *including* the date and the separator. The length of the date is language-specific. The date and separator count for 12 characters in Japanese. 
**Test in regular content** …
> Adapt the recommended meta description length for Japanese

- packages/js/src/classic-editor.js
- packages/seo-integration/src/analyze.js
* We want our add-ons to still work with the new classic editor integration.
* Adds back support for `window.YoastSEO.analysis` and `window.YoastSEO.app.refresh` within the new classic editor integration for compatibility with add-ons.
* Fixes a bug where the permalink and slug would not be passed to the analysis correctly.
* Wrapped the call to `analyze` in a `debounce`, as was the case in the original implementation of `window.YoastSEO.app.refresh`.
* Install the latest version of Local SEO.
* Install the latest version of WooCommerce SEO.
* Activate Local SEO.
* Set Local SEO to use multiple locations within the Local SEO settings.
* Create a new Location.
* In the SEO …
> Added support for global YoastSEO api's in the classic editor for compatibility with add-ons.

- admin/class-config.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy.php
- packages/js/src/classic-editor.js
- packages/js/src/classic-editor/helpers/dom.js
- packages/js/src/classic-editor/initial-state.js
- packages/js/src/classic-editor/shortcodes.js
- packages/js/src/classic-editor/watcher.js
- packages/js/src/initializers/tiny-mce.js
- packages/js/src/ui/publishBox.js
- packages/seo-integration/src/replacement-variables/configurations.js
- src/integrations/third-party/elementor.php
* Split logic between post and term and handle branching at the root level.
* This split is needed because post and terms are too different to try to handle with the same logic. Primarily the differences in DOM elements used by WordPress and our own hidden inputs between post and term pages. By trying to support both post and term DOM, a lot of functions got messy and responsible for multiple things (branching between post/term in a lot of places) and I didn't like that.
* Splits post and term logic in favour of structuring.
* Split logic between post and term at the highest level in `classic-editor.js` entrypoint. Removed this split from some other places, like the `shortcodes` plugin.
* Added support for legacy UI functions: …
> make a hard split between post and term logic

- packages/js/src/classic-editor/components/google-preview.js
* Let the 'Google preview container' determine which image it should use as featured image.
* Let the 'Google preview container' determine which image it should use as featured image.
*
* Create and edit a new post using the Classic Editor
* Add a featured image and verify the image will be set in the google preview
* Remove the featured image
* Add multiple images in the `content`
* Verify the google preview will pick the first image
*
*
Fixes P1-1128
> P1-1128 - Fix featured image with first image in content fallback in Google Preview container

- packages/components/src/image-select/ImageSelectButtons.js
* Focus loss is confusing to visually impaired users.
* Clicking outside of one of our EditorModals after removing an image will not close the modal (you have to click the modal first and then click outside of it) because focus is elsewhere and the blur event does not get handled by the modal.
* Fixes a bug where removing an image from our Facebook Preview and Twitter Preview modals could lead to a confusing accessibility experience due to focus loss.
*
* Before this change, (so on `trunk`) in our editor modals clicking the "remove image" button would cause a loss of focus.
* This was for example evident when removing an image, and clicking outside of the modal: it would …
> Handle focus loss by disappearing button in ImageSelect

- inc/class-upgrade.php
* Wincher options already existed behind a feature flag in 17.8. This can cause issues when users save the deactivated value, and then upgrade to 17.9. An upgrade routine was created to set the Wincher integration to active in 17.9, as it emerges from behind the feature flag.
* Fixes an unreleased bug where saving the integrations form in 17.8 and upgrading to 17.9 would set the Wincher integration to "off".
* N/A
* If you have it enabled, disable the `YOAST_SEO_WINCHER_INTEGRATION` feature flag in your wp-config.
* Go to Yoast>general>integrations, change something (i.e. turn ryte off) and press save.
* Get the yoast-test-helper plugin.
* Go to tools>yoast-test-helper
* …
> Add upgrade 17.9 routine to set wincher active to true

- .travis.yml
- admin/class-admin-asset-manager.php
- config/webpack/webpack.config.js
- yarn.lock
* Fixes issues that caused our JS files to not be fully parsed by translate.wordpress.org.
* Reverts the change renaming our `.js` files to `.min.js`, `.min.js` files are not parsed by translate.wordpress.org.
* Updates a sub-dependency causing our analysis library to not be fully parsed.
* There should be no JS errors in the metabox/sidebar, the workouts and our settings pages.
* Script loading errors in our metabox/sidebar, workouts and our settings pages.
> Fix wordpress.org translation parsing

- packages/yoastseo/src/scoring/assessments/seo/TitleKeywordAssessment.js
*
* [yoastseo] Encloses a feedback string for the Keyphrase in title assessment in the WordPress translation function so that it can be translated to other languages.
*
* Create a new post and add a keyphrase, e.g. `cats and dogs`
* Add a title that doesn't contain all words from the keyphrase, e.g. `cats`
* Confirm that the Keyphrase in title assessment returns the following feedback: `Keyphrase in title: Not all the words from your keyphrase X appear in the SEO title. For the best SEO results write the exact match of your keyphrase in the SEO title, and put the keyphrase at the beginning of the title.`
* Switch site language to Japanese
* Go back to the post and confirm …
> Fix untranslated string for the Keyphrase in title assessment

- admin/class-primary-term-admin.php
- packages/js/src/classic-editor.js
- packages/js/src/classic-editor/plugins/seo-title-width.js
- src/integrations/admin/fix-news-dependencies-integration.php
*
* Adds SEO title width plugin.
* Fixes a bug where the primary category plugin would not be loaded due to the L10n not being available.
* Fixes a bug where the news add-on would not have the free scripts loaded due to the script handle being wrong.
* Searched for the `post-edit-classic` script handle and changed the implementations to use `classic-editor` when not on the block editor.
* Added the SEO title width as preparePaper filter. Using the `measureTextWidth` from our `yoastseo` package.
* Check out the `analysis-integration` branch before this PR
* Activate News SEO
* Open the classic editor
* Verify the news tab in the metabox does not have any content and there …
> P1-1140 Fix title width and primary category plugins

- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/shell.js
- packages/replacement-variables/package.json
- packages/seo-integration/package.json
- packages/seo-store/package.json
* Running yarn build in wordpress-seo should also build the new SEO integration packages. 
* Build the seo-integration packages alongside free 
- Codescout:
- Removed unused grunt shell command
- Refactored shell commands to use our yarn script commands 
- Added sourcemaps to our packages `build` command
- Run `grunt build`
- Verify the three seo-integration packages are built.
- verify that these packages have sourcemaps 
- Run `grunt release`
- Verify the three seo-integration packages are built.
- verify that these packages **do not** have sourcemaps 
* This is tooling so this does not have to be tested by QA.
This PR …
> P1-1139 - Create build script in wordpress-seo

- Gruntfile.js
- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/copy.js
- config/grunt/task-config/shell.js
- package.json
- yarn.lock
* Have translations for the new JS package
* Adds the `seo-integration` package to the translations pipeline.
* Tried to put the i18n command in the package itself (since we also build there), but then the translator comments are relative to that package, which is confusing I think. So I put it along the other ones, inside the root.
* Run `grunt build:i18n`
* Ensure you have the translations from `seo-integration` in the pot file:
* Search for `Something went wrong with loading the analysis, please refresh the page to try again.` in the `languages` folder. You should get a hit in the `yoast-components.php` file (the packages get merged into that one). …
> P1-1149 seo integration translations pipeline

- packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getWordFormsSpec.js
- packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getWordForms.js
* Keyphrases with only function words (= do not contain content words) yielded NaN/Infinity results for the keyword density and keyword in meta description assessments. This PR fixes that by adding a guard, returning an empty list in the same format as when there are content words in the keyphrase.
* [yoastseo] Fixes incorrect assessments for keyphrases only consisting of function words in Japanese.
* Currently Japanese keyphrase/synonym containing only function words is not recognised in the text even if there is a match. This will be addressed in a separate issue.
* Build and activate Free.
* Build and activate Premium:
* Check-out the `trunk` branch.
* Run `composer …
> LINGO-1253 Fixes incorrect assessments for keyphrases only consisting of function words

- package.json
- yarn.lock
* The `colors` NPM package [has recently been the subject of updates](https://snyk.io/blog/open-source-npm-packages-colors-faker/) that may be breaking it. We should stick to the latest safe version.
* Sets the version of the `colors` dev dependency to 1.4.0 to avoid problems from updates.
*
* `composer install && yarn && grunt build`
* quick smoke test (edit a post) to check components are not broken
* the package is used during automatic RC creation so let's see if we have problems with that
* N/A
*
Fixes #
> Pin `colors` package to safe version 1.4.0

- composer.json
- src/repositories/seo-links-repository.php
* A database query may fail and return a false boolean which would be used as an array and cause a fatal. This PR fixes that.
* Fixes a bug where the internal link update might cause a fatal error.
* It should be noted that if the query fails, the related indexables are not retrieved and therefore not updated. This would not happen regardless of if we would throw a fatal error. So this PR just fixes the fatal, but the underlying problem still persists (whatever that may be).
* In `get_incoming_link_counts_for_indexable_ids()` set `$indexable_counts` to `false` immediately after the query.
* Without this PR, any post update where links in the post are changed will cause a …
> Account for a failed query and return early.

- admin/class-meta-columns.php
- css/src/score_icon.css
* The overall score icon used to be grey when no keyphrase was set. This PR changes the color to red.
* Changes the overall SEO score color on the posts/pages/movies/books overview page to red when no keyphrase is set.
* The color for when no keyphrase is set is not changed centrally in `score_icon.css` file.
* In `parse_column_score()` in `class-meta-columns.php`, the rank for when no focus keyphrase is set is changed from "No_FOCUS" to "BAD".
* This way, this change only affects the overall SEO score icon and not the readability icon. This means that for old posts that were created before installing the plugin, the readability icon on the overview page should still stay grey. …
> Change the overall SEO score on the posts/pages/movies/books overview page to red when no keyphrase is set

- src/integrations/front-end-integration.php
It was reported that in block-based themes, the Yoast title does not work (https://twitter.com/bgardner/status/1482898902336557056?s=20)
Using the latest build of WP 5.9 and the default 2022 theme I was able to replicate the issue.
FSE (block-based) themes use a different method to add the title, and this PR adds compatibility with that.
* Use the latest nightly build of WP Core (the easiest method to do that is using the plugin from https://wordpress.org/plugins/wordpress-beta-tester/)
* Make sure you're using the default twentytwentytwo theme
* Create a new post and change the Yoast title tag for that post
* Visit the frontend on that post and make sure that there's only 1 `<title>` tag in the page's source, and it's the one that was manually entered instead of the default one.
Fixes #
> title-tag: compatibility with block-based themes

- src/actions/wincher/wincher-keyphrases-action.php
- tests/unit/actions/wincher/wincher-keyphrases-action-test.php
* The plugin was sending API requests to Wincher with no keyphrases. This always results in an API error, so this is unnecessary. Instead return an empty response immediately.
* Prevents sending a request to the Wincher API with no keyphrases.
*
* No good way to verify this behavior, but just make sure that the Wincher integration still works correctly.
*
* Wincher integration, primarily on the Dashboard.
Fixes #
> Wincher: don't send API request when no keyphrases

- src/config/oauth-client.php
- src/config/semrush-client.php
- src/config/wincher-client.php
* The plugin was sending Wincher access tokens in the GET params of requests (unnecessarily, since it's read from the headers by our API). This is a (very minor) security concern and also clogs up our logs. 
* Avoids sending OAuth access tokens in GET parameters when doing requests against the Wincher API.
* Make sending access token in the headers the default, since this is what most APIs would expect.
* There are no good steps to verify this behavior, but simply make sure that both the Wincher and SEMRush integrations still work as expected. 
* 
* Wincher integration
* SEMRush integration
Fixes #
> Wincher: don't send access token in GET parameters

- packages/js/src/import.js
- src/integrations/admin/import-integration.php
- tests/unit/integrations/admin/import-integration-test.php
* We want to improve the UX for the new import, by tweaking it considering that AIOSEO should not be available for import once its import is completed.
* Improves the old import UX for the new importing actions
*
(Designs are as per meeting with @uxkai )
**With the `YOAST_SEO_AIOSEO_V4_IMPORTER` enabled: **
* **When having no other SEO plugins to import from, only AIOSEO**:
* When entering this Import from other SEO plugins tab for the first time, the input field at step 2 should show a default state: `Select SEO plugin`. The Import button should be disabled until the user selects `All In One SEO Pack` from the dropdown
* While the import is running:
* When finishing the …
> Improve import UX

- inc/class-addon-manager.php
* We were calling `get_plugins()` in our own plugin initialization loop, instead of after all plugins were loaded. Because `get_plugins()` gets cached, we would potentially cache plugin information before all plugins were fully initialized.
* Fixes a bug where plugins that would initialize after our plugin would be unable to register certain plugin information or utilize certain hooks.
* Moved the call of `get_plugins()` to the `plugins_loaded` action hook.
* Make sure Yoast Free is active.
* Create a php file in the plugins directory and name it `z.php`. Add the following content:
```php
<?php
/*
* Plugin Name:       Yoast Bug Example
* Version:           1
*/ …
```
> Delay a call to `get_plugins()` until after all plugins are loaded

- inc/sitemaps/abstract-class-indexable-sitemap-provider.php
- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
- src/builders/indexable-author-builder.php
- src/config/migrations/20211108133106_AddIsPubliclyViewableToIndexables.php
- src/integrations/watchers/indexable-author-watcher.php
- src/repositories/indexable-repository.php
- tests/integration/sitemaps/test-class-wpseo-author-sitemap-provider.php
- tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
- tests/unit/builders/indexable-author-builder-test.php
- tests/unit/integrations/watchers/indexable-static-home-page-watcher-test.php
- tests/unit/repositories/indexable-repository-test.php
* Make indexable sitemaps more consistent with the current generation sitemaps
* Don't require existing sites to do a full reindex before getting valid sitemaps.
* Deduplicate code
* Make indexable sitemaps more consistent with the current generation sitemaps
* Don't require existing sites to do a full reindex before getting valid sitemaps.
* I've derived the is_publicly_viewable value for authors off of the number of publicly viewable posts. There is another condition that determines if author archives are viewable, but that is a global wpseo setting that would require us to reindex _all_ authors when that setting is changed. This operation will be too heavy for some sites, so it isn't included in the expression.
This PR can be …
> Indexable sitemaps improvements

- inc/sitemaps/class-author-sitemap-provider.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
- src/integrations/watchers/indexable-post-watcher.php
- tests/integration/framework/class-wpseo-unit-test-case.php
- tests/integration/frontend/test-class-wpseo-image-utils.php
👉 I've set the base branch to [sitemap-feedback](https://github.com/Yoast/wordpress-seo/pull/17912). Once that branch is merged, the base branch can be updated to feature/indexable-sitemaps.
* Integration tests were failing, some on every supported version of WP, some just on versions other than trunk.
* Improve stability in integration tests
* Instead of creating an attachment in the WPSEO_Image_Utils_Test dataProvider, it now uses the setupBeforeClass and teardownAfterClass methods. The dataproviders are called _before_ any tests are executed to determine the number of tests to run. Any changes to the DB during that period, are not cleaned up or reverted. That's why we need to use the setup/teardown methods for it instead.
* If …
> Fix Integration tests

- src/helpers/string-helper.php
*
* Changes parameter names in the `String_Helper` class to avoid breaking changes in PHP 8+
*
* N/A
Check for regressions with the string helper likeso:
* Add the following code in your functions.php or in a mu-plugin:
```
add_filter( 'wpseo_title', 'custom_wpseo_title', 10, 2 );
function custom_wpseo_title( $title, $presentation ) {
return "bla bla <tag>";
}
```
* Go to the frontend of a post and confirm that the tag has been stripped and that the title tag is `bla bla`.
* For that post, tweak its indexable in the db, and add `bla  bla` in the description column (have a double space between the words, GitHub doesn't allow me …
> Rename parameters with reserved names in String_Helper

- src/helpers/options-helper.php
*
* Changes parameter names in the `Options_Helper` class to avoid breaking changes in PHP 8+
*
* N/A
A nice way to regression test this change is to test options. For example the separator:
* Check for regressions with the separator option. Go to the frontend of the site and check if the separator is shown as expected depending the one you have selected in Search Appearance settings.
*
Fixes #
> Rename parameters with reserved names in Options_Helper

- src/actions/importing/abstract-importing-action.php
- src/actions/importing/aioseo-posts-importing-action.php
- src/helpers/indexable-to-postmeta-helper.php
- src/helpers/utils-helper.php
- tests/unit/actions/importing/aioseo-posts-importing-action-test.php
- tests/unit/helpers/indexable-to-postmeta-helper-test.php
* We want to include the `Focus Keyphrase` and the `Canonical URL` settings in the post import from AIOSEO
* Imports the Canonical URL and the Focus Keyphrase settings for posts from AIOSEO
* We do a `sanitize_url` before importing the Canonical URL in our db
* We do a `sanitize_text_field` before importing the Focus Keyphrase in our db
Note:
* Without the `YOAST_SEO_AIOSEO_V4_IMPORTER` feature flag, you won't be able to see the AIOSEO import as available.
* Create a post while having AIOSEO active
* Add a `Focus Keyphrase` and a `Canonical URL` in the AIOSEO meta box
* Go to the frontend of the post and take a note of the `canonical` link tag.
* Activate Yoast and …
> Import canonical url

- inc/sitemaps/abstract-class-indexable-sitemap-provider.php
- src/helpers/xml-sitemap-helper.php
* Featured images were missing from the indexable sitemaps.
* Add featured images to the indexable-based sitemaps.
* There's a PR open that adds the featured image to the links table. It doesn't however, specify that it's a featured image. So the only way to be sure the featured image isn't already in the result of the links query, is to fetch the featured image and compare the urls.
* Create a post without a featured image and without any images
* When viewing the sitemaps the "images" column should say 0 for your post.
* When viewing the sitemap page source, there should be no `<image:image>` entry for your post
* Add an external image to your post (e.g. …
> Add featured images to indexable sitemaps

- packages/js/src/structured-data-blocks/faq/components/Question.js
- packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
* When using TwentyTwentyTwo and other Full Site Editing / Block Themes, images added in our FAQ and HowTo blocks spanned more width than their container. This PR corrects that, so that our blocks look the same with regular and block themes.
* Fixes a bug where images inserted into our FAQ or HowTo blocks would be rendered wider then their respective container when using a Block Theme.
* Using a nasty inline style, since we don't enqueue any frontend stylesheets.
1. Install WordPress 5.9 RC2 or newer with the beta tester plugin (Activate Twenty Twenty-Two).
2. Install Yoast SEO 18.0 RC6.
3. Create a new post or page.
4. Add one How-to and one FAQ block with one image …
> Add a max-width to our FAQ and HowTo Block IMG's

- src/helpers/post-helper.php
*
* Changes parameter names in the `Post_Helper` class to avoid breaking changes in PHP 8+
*
* N/A
Check for regressions with the post helper likeso:
* Have a post with empty meta description and Facebook/Twitter description.
* Have empty meta description in the Content Types->Posts in Search Appearance settings
* Load the post in the frontend
* Verify that the og:description is having the excerpt as value there
*
Fixes #
> Rename parameters with reserved names in Post_Helper

- src/surfaces/helpers-surface.php
- src/surfaces/open-graph-helpers-surface.php
- src/surfaces/schema-helpers-surface.php
- src/surfaces/twitter-helpers-surface.php
Magic isset method provides a convenient way to check if a helper exists without the need to use a try catch syntax
While working with Yoast API and since all surfaces rely on properties access, I found that checking on a helper existence quite tedious:
```php
try {
$helper = $yoast->helpers->some_helper;
} catch(\Exception $e} {
// The helper doesn't exists or is incorrectly named
}
```
Because the container will throw if some service isn't found.
Adding a magic isset method provides an easier error handling.
```php
if(!isset($yoast->helpers->some_helper)) {
return;
}
```
* Add an isset magic method to ease working with helper surfaces. Props to @nlemoine.
* See example …
> Add helper magic isset method

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/Stepper.js
* When we open a page that contains a Stepper, we want to expand the first unsaved step. If the stepper has been finished, we want to open the last step.
* Expands the first unsaved step when entering a page with the stepper.
* Reasoning behind the method: Whether steps are saved or not, should be handled by the parent of the stepper, e.g. the `ConfigurationWorkout`. However, which index should be expanded on first render, given this information, should be handled by the `Stepper`, as this should be the same for all steppers and avoids duplicated code.
* When we have moved the stepper and configuration code (outside of the workouts folder), it might be a good idea to move this method into its own helper class. Also depending on …
> Expand the first incomplete step on entering the workout

- src/helpers/xml-sitemap-helper.php
* Yoast SEO Premium, returns `false` in the `wpseo_sitemap_entry` filter to filter out sitemap entries for posts that are redirected. Other plugins can return similar values to prevent sitemap output.
* Allow for filtering items from the sitemap.
* I check if the `loc` key exists, as that's the only required key for the sitemap.
* add the following code block to your functions.php or wp-config.php: it randomly removes around half of your posts from the sitemap.
```php
add_filter( 'wpseo_sitemap_entry', function ( $url ) {
if ( (bool) random_int( 0, 1 ) ) {
return false;
}
return $url;
} );
```
* Visit your sitemap and see that around half of your content is not in the …
> Prevent filtered links from showing up in the sitemap

- inc/sitemaps/abstract-class-indexable-sitemap-provider.php
- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
* Some sitemap links in the index resulted in 404s because the post-type or taxonomy was no-indexed globally.
* Prevent links for no-indexed posttypes/taxonomies on the sitemap index
* N/A
* In the search appearance settings, set "Show `posttype` in search results?" to "Off" for a posttype and for a taxonomy
* go to the sitemap index: /sitemap_index.xml
* See that there are no links to the no-indexed posttype/taxonomy
* Switch the options back to "On"
* See that there are links to the no-indexed posttype/taxonomy 
* Click the links and see the indexed posts or terms.
* …
> Prevent links for no-indexed posttypes/taxonomies on the sitemap index

- inc/sitemaps/abstract-class-indexable-sitemap-provider.php
- inc/sitemaps/class-author-sitemap-provider.php
* There's a bug with indexable sitemaps that shows the _first_ last modified date for every page instead of the most recent.
*  Fixes an unreleased bug where the the sitemap index would show the oldest last modified date of a page instead of the most recent.
* Ideally, reversing the sort of the `object_last_modified` column would fix the issue, but that causes a new problem: once a post is updated, _all_ sitemap pages rotate 1 post, which makes them have a new last_modified date.
* Open the sitemap index of your site
* See that, for every link in the sitemap index, the date that is shown next to it is the most recent date of all dates that are listed in the sitemap that …
> Display the most recent last-modified date for every page in the sitemap

- inc/sitemaps/class-sitemaps-cache.php
* The news SEO plugin (among others) throws fatal errors with the feature/indexable-sitemaps branch because we removed the caching file.
* Deprecate the WPSEO_Sitemaps_Cache class.
* I kept the return type consistent with the phpdoc return type to prevent potential breakage.
* Install and activate version 13.1 of News SEO.
* Create and publish a new post
* This should not throw a fatal error. Instead you get deprecation warnings depending on your server config
* the post you updated is now visible in the sitemaps.
*
* -
> Restore WPSEO_Sitemaps_Cache to prevent fatal errors

- packages/js/src/structured-data-blocks/faq/components/Question.js
* Provides a fix for a deprecation message from WordPress 5.8
* Fixes a bug where a (debug) deprecation message would show in the widget editor on WordPress 5.8 and above.
*
* Install and activate Yoast Free on WordPress 5.8 or above.
* Make sure debugging is active (add to wp-config.php: `define( 'WP_DEBUG', true );` and `define( 'SCRIPT_DEBUG', true );`)
* Navigate to `Appearance -> Widgets`
* Notice the PHP Notice: `wp_enqueue_script() ...`
* With this PR, that message won't show.
* Make sure the FAQ block keeps functioning as expected on posts and pages. …
> Fix structured data blocks deprecation warning

- packages/js/src/analysis-worker.js
- packages/js/src/analysis/worker.js
* Translations should be available in the context of the analysis worker.
* Fixes an unreleased bug where the content analysis would not be translated.
* The translations are made available by wp-scripts, but they are in a ready-to-be-called function. We don't have access to this function from the worker, as it resides on the window. So, we parse the json translation data and extract the domain from the function on the window and send that to the worker.
* Set your site language to something other than english
* Edit a post and see that the content analysis is translated.
* Edit a term and see that the content analysis is translated.  …
> Also load translations in the web worker

- packages/js/src/classic-editor/helpers/dom.js
- packages/js/src/classic-editor/watcher.js
- packages/js/tests/classic-editor/helpers/dom.test.js
- packages/js/tests/classic-editor/initial-state.test.js
* In [this PR](https://github.com/Yoast/wordpress-seo/pull/17973), we added categories to the watcher, so that it updates the "Category" replacement variable on selection of a category. However, the watcher only considered the categories in the "All Categories" section. This PR adds the category checkboxes in the "Most Used" section to the watcher.
* Adds categories from the "Most Used" section to the watcher. As a result, the "Category" replacement variable is synced with the selected categories.
* We only need to watch the "Most Used" section for changes, but we don't need to use that for fetching the current selected categories (as that would create duplicates with the "All Categories" section), nor do we need to watch it for …
> LINGO-1287 Update category replacement variable when selecting from most used categories

- .travis.yml
* Fix CI
* As of WP 5.9 we need to use PHPUnit 9 for our integrationtests. If we use 7.5 we get a deprecation warning.
* Fix CI: PHP 8.0 integration tests
* changed reference from master to trunk: [WP-develop changed their main branch](https://make.wordpress.org/core/2021/11/10/default-git-branch-for-wordpress-wordpress-develop/).
* Use PHPUnit 9 as per https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/
* See that the builds succeed
*
*
> Use the best suiting version for PHPUnit with WP 5.9

- packages/js/src/classic-editor/replacement-variables/configurations.js
- packages/js/tests/classic-editor/replacement-variables/configurations.test.js
*
* Supports primary category replacement variable.
* See my comments below.
Requirement:
* Install and activate classic editor
* Create three categories from Posts > Categories > Add new category
**Test with categories created via Posts > Categories > Add new category**
* Use the `Primary category` replacement variable both in SEO title and meta description field
* Check all the categories that you just created for the post
* Make the category that is not on top of the list the primary category
* Confirm that the correct primary category is previewed in Google preview both in SEO title and in meta description
* Uncheck the current primary category
* …
> Lingo 1250 support primary category pluggable replacement variable

- src/integrations/admin/installation-success-integration.php
* #17915 has introduced a deprecation for a translation-related class that we're still using in the installation success page. We should remove that reference.
* Removes a reference to a deprecated class in the installation success page.
*
* make sure you have `define( 'WP_DEBUG', true );` in your `wp-config.php`
* make sure you have `define( 'YOAST_SEO_INSTALLATION_SUCCESS', true );` in your `wp-config.php`
* visit the installation success page (e.g. http://basic.wordpress.test/wp-admin/admin.php?page=wpseo_installation_successful_free) and check that you don't get any deprecation warning such as: `The called constructor method for WPSEO_Admin_Asset_Yoast_Components_L10n …
> DUPP-248 Remove reference to `WPSEO_Admin_Asset_Yoast_Components_L10n`

- packages/yoastseo/spec/languageProcessing/helpers/url/urlSpec.js
- packages/yoastseo/src/languageProcessing/helpers/link/getLinkType.js
- packages/yoastseo/src/languageProcessing/helpers/url/url.js
* This change fixes a Shopify bug where the internal linking assessment didn't recognise links using the primary domain, if the domain was different than the Shopify domain
* See the two other PRs that are part of this fix: https://github.com/Yoast/admin-ui/pull/230 https://github.com/Yoast/shopify-seo/pull/572
* In Wordpress, we compare the links in the text against the site url. However, in Shopify this causes a problem because the place where we retrieve the site url from uses the url with a `myshopify` domain. But many users have set a different primary domain, so we want to make sure we always compare the links against a url with the primary domain. As far as I know, in `shopify-seo` we don't have easy access to the url with the primary domain, but we do have access to the primary …
> Recognise internal link if link host is same as the user's site domain

- composer.json
- inc/sitemaps/class-post-type-sitemap-provider.php
* When you set a posttype to no-index in the search appearance settings, you should not get a link for it on the sitemap index.
* Fixes an unreleased bug where posttypes that were set to no-index in the search appearance settings got a link on the sitemap index which pointed to a 404.
*
* Pick a posttype that is publicly accessible and has an archive
* Go into the SEO > search appearance > Content Type settings and set the value for "Show Testimonials in search results?" to "Off" for your posttype.
* Visit the sitemap index and see that there is no link to your posttype.
* …
> FIX-61 Hide non empty excluded posttypes

- src/validators/array-validator.php
- src/validators/news-sitemap-content-type-validator.php
- tests/unit/validators/news-sitemap-content-type-validator-test.php
* Two options(in `Local SEO`) their array values are sanitized to 'on' if the keys are strings.
* Adds the news sitemap content type validator .
* The 'Array validator' throws an exception instead of returning a boolean.
* Tests should cover and pass.
* You can test the validator via:
```php
function _test_validate_news_sitemap_content_type( $value ) {
/** @var \Yoast\WP\SEO\Validators\News_Sitemap_Content_Type_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\News_Sitemap_Content_Type_Validator::class );
try {
} catch ( …
```
> P1 1189 create array of type validator

- inc/sitemaps/abstract-class-indexable-sitemap-provider.php
- inc/sitemaps/class-author-sitemap-provider.php
- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
* Posts that have a canonical url set, shouldn't end up in the sitemaps.
* Fixes an unreleased bug where posts would still be in the sitemaps even though they have a canonical url set to another url.
* I still include an entry if the sitemap if the canonical url matches the post permalink _exactly_. If the post is `/something` and the canonical is `/something/` it still is removed from the sitemap. This behaviour is now the same as in `trunk`.
* Open the posts sitemaps
* Click a single entry in the sitemap and edit that post: under the Advanced section in the metabox, give it a canonical url. This can be any besides the url of the post.
* Save the post and visit the …
> Hide canonical posts from sitemaps

- packages/js/src/containers/FacebookEditor.js
- packages/js/src/containers/TwitterEditor.js
- packages/js/src/helpers/selectMedia.js
- packages/social-metadata-previews/src/index.js
- packages/social-metadata-previews/src/shared/SocialImage.js
* Using a background image causes numerous performance issues / limitations, and should therefore be changed (e.g., an inability to use native lazy loading)
* Use a smaller image size if available
* [wordpress-seo-premium] The Facebook and Twitter Preview now uses an image instead of a background image.
* [shopify-seo] The Facebook and Twitter Preview now uses image instead of a background image.
* [@yoast/social-metadata-previews] The Facebook and Twitter Preview now uses image instead of a background image.
* [@yoast/social-metadata-previews] Export the variables TWITTER_IMAGE_SIZES, FACEBOOK_IMAGE_SIZES and  determineFacebookImageMode.
* Google preview uses an \<img> and object-fit approach, so we have precedent for this.
* …
> Facebook and Twitter preview images should use images, not backgrounds

- admin/import/plugins/class-import-aioseo-v4.php
- packages/js/src/import.js
- src/actions/importing/aioseo-cleanup-action.php
- src/actions/importing/aioseo-posts-importing-action.php
- src/integrations/admin/import-integration.php
- src/integrations/admin/indexing-tool-integration.php
- src/services/importing/importable-detector.php
- tests/unit/actions/importing/aioseo-cleanup-action-test.php
- tests/unit/integrations/admin/import-integration-test.php
- tests/unit/integrations/admin/indexing-tool-integration-test.php
- tests/unit/services/importing/importable-detector-test.php
* We want to cleanup AIOSEO data, when the user clicks the Clean button
* Adds the Data Cleanup functionality for AIOSEO 
* When we perform the cleanup, we truncate the AIOSEO post indexable table and we delete any postmeta that contain AIOSEO data that we import in posts.
* The cleanups is not performed in chunks but rather in one go.
* We dont queue the cleanup action with the rest of the import actions but rather have it triggered solely by the Clean button
**With the `YOAST_SEO_AIOSEO_V4_IMPORTER` feature flag both enabled and disabled**:
* Running `yoastImportData.restApi.cleanup_endpoints` in the Tools page's console, should return a `Uncaught ReferenceError: …
> Cleanup AIOSEO data

- src/actions/importing/aioseo-posts-importing-action.php
- src/helpers/indexable-helper.php
- src/models/indexable.php
- tests/unit/actions/importing/aioseo-posts-importing-action-test.php
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/helpers/indexable-helper-test.php
- tests/unit/services/importing/importable-detector-test.php
- tests/unit/services/importing/importer-action-filter-trait-test.php
* We want to skip importing post data from AIOSEO when there's already Yoast data in even 1 meta setting for that post
* The settings we check if there are already Yoast data are **Meta Title**, **Meta Description**, **OG Title**, **OG Description**, **Twitter Title**, **Twitter Description**, **Canonical URL**, **Focus Keyphrase** and **Robots Settings**
* Checks if the Yoast indexable contains default values before importing AISOEO data to avoid overwriting Yoast data
* We added a unit test in the Post Indexable Builder that checks for the current default values of the fields we check. If/when one of those default values changes in the future, that unit test will start failing 
This PR can be acceptance tested by following …
> Check if default values in indexable fields before importing

- admin/pages/tools.php
- admin/views/tabs/tool/import-seo.php
- packages/js/src/import.js
- src/integrations/admin/import-integration.php
- tests/unit/integrations/admin/import-integration-test.php
* We want to change the wording of the import page, depending on whether the feature flag is enabled or not.
* Impove texts in import pages
* Added the `yoast-import-explanation` and `yoast-cleanup-explanation` classes in the import-seo.php file to be able to safely show the new copies or not depending on the feature flag.
**With the feature flag either enabled or disabled:**
* Changed the copy in the tools page from `Import settings from other SEO plugins and export your settings for re-use on (another) blog` to `Import settings from other SEO plugins and export your settings for re-use on (another) site`:
**With the feature flag enabled:**
* Step 2 should look like …
> Plugin 1439 import wording changes

- css/src/admin-global.css
* CSS update to prevent the "Save changes" button from overlapping the admin sidebar menu on WordPress.com, by allowing for differing admin menu widths. See issue #17008.
**Before**
**After**
* Fixes bug where the "Save changes" button overlaps the admin sidebar on WordPress.com
* CSS update does not specify a specific `left` or `right` attachment in an effort to allow for variable admin sidebar widths.
* Increase the size of the admin sidebar menu for testing purposes.
* Go to the "Search Appearance" section.
* The "Save changes" button that is fixed on the bottom of the screen, should not overlap (or be overlapped) by the admin sidebar, regardless of view-port size …
> Issue #17008 WPCOM CSS update to allow differing admin menu widths.

- src/actions/importing/abstract-importing-action.php
- src/actions/importing/aioseo-posts-importing-action.php
- tests/unit/actions/importing/aioseo-posts-importing-action-test.php
* We want to fix the case when the user has selected to `Use Data from Facebook Tab` for the Twitter data
* Fixes an unreleased bug where twitter data from AIOSEO wouldn't get correctly imported when the user had enabled to retrieve those from the respective fb data
*
Notes:
* Without the feature flag, you won't be able to perform the Import as it won't be available in the Tools->Import/Export page
* Create a post while having AIOSEO enabled
* In the Social->Twitter tab, enable the `Use Data from Facebook Tab` setting
* Activate Yoast, go to Tools->Import/Export page and perform the import
* Go to the frontend of the post and compare the twitter title, description and …
> Plugin 1441 use fb data for twitter

- admin/tracking/class-tracking-default-data.php
- packages/js/src/structured-data-blocks/faq/components/Question.js
- packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
- src/integrations/blocks/structured-data-blocks.php
* Optimizes the image output of FAQ and How To blocks.
* Optimizes the images in FAQ and How To blocks to be more responsive and load faster.
* A new filter `wpseo_structured_data_blocks_image_size` is added to allow adjusting attachment sizes.
* Create a FAQ and How To block before updating to this PR.
* Update to this PR.
* The output of images in the FAQ and How To blocks should be lazily loaded and include a `srcset` attribute.
* Do the same for new FAQ and How To blocks.
* The output of FAQ and How To blocks.
> Optimize faq and how to images

- admin/tracking/class-tracking-settings-data.php
- inc/options/class-wpseo-option-wpseo.php
- patchwork.json
- src/conditionals/wp-cron-conditional.php
- src/conditionals/wp-cron-enabled-conditional.php
- src/helpers/indexing-helper.php
- src/integrations/admin/background-indexing-integration.php
- src/values/indexables/indexable-builder-versions.php
- tests/unit/generators/schema/webpage-test.php
- tests/unit/helpers/indexing-helper-test.php
- tests/unit/integrations/admin/background-indexing-integration-test.php
* Users shouldn't have to click the optimize site button every time they install our plugin or every time we release a new version that modifies the indexable model, which needs a full reindex.
* Replaces indexing at the end of admin requests with WP-Cron if WP-Cron is not disabled on the site.
* In the unittests, [we added our own shutdown hook](https://github.com/Yoast/wordpress-seo/pull/17989/files#diff-cde93b4be417fc1864763094db41de5978a285c6b621790af85a92643b5c714cL193-L198) with assertions to get around testing if the shutdown hook was used as expected. The assertions in that [`shutdown_indexation_expectations` callback](https://github.com/Yoast/wordpress-seo/pull/17989/files#diff-cde93b4be417fc1864763094db41de5978a285c6b621 …
> wp-cron indexing

- src/exceptions/validation/invalid-email-exception.php
- src/validators/email-validator.php
- tests/unit/validators/email-validator-test.php
*
* Adds the email validator.
*
* You can run this somewhere and play around with feeding it different input:
```php
/** @var \Yoast\WP\SEO\Validators\Email_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Email_Validator::class );
try {
}
echo '<br>';
}
_test_validate( 'info@example!.org' );
``` …
> Add email validator

- packages/js/src/classic-editor/helpers/dom.js
- packages/js/src/classic-editor/initial-state.js
- packages/js/tests/classic-editor/helpers/dom.test.js
- packages/js/tests/classic-editor/initial-state.test.js
- packages/seo-integration/src/replacement-variables/configurations.js
- packages/seo-integration/tests/replacement-variables/configurations.test.js
- packages/seo-store/src/editor/slice.js
- packages/seo-store/src/editor/tests.js
* In [this PR](https://github.com/Yoast/wordpress-seo/pull/17958), we added fallbacks for the excerpt when that is empty. This PR changes the functionality to adhere to the changes in [this PR](https://github.com/Yoast/wordpress-seo/pull/17907), where we adapted the recommended meta description length (and meta description preview limit) for Japanese. 
* Sets the recommended meta description length for Japanese to 80 characters.
* We retrieve the locale not from the DOM (as that shows the user's locale, and not the site-wide locale), but from the `l10nObject` (in `packages/js/src/analysis/getContentLocale.js`). 
* The behaviour of live-updating the generated excerpt differs between new and existing posts. For new posts, the …
> LINGO-1267 Adjusts the meta description length limit for Japanese

- src/exceptions/option/missing-configuration-key-exception.php
- src/exceptions/option/unknown-exception.php
- src/services/options/site-options-service.php
- src/validators/integer-validator.php
- tests/unit/validators/empty-string-validator-test.php
- tests/unit/validators/integer-validator-test.php
- tests/unit/validators/string-validator-test.php
- tests/unit/validators/url-validator-test.php
*
* Adds the integer validator.
* Snuck in some more validator tests.
* Tests should cover and pass.
* You can test the validator via:
```php
function _test_validate_int( $value ) {
/** @var \Yoast\WP\SEO\Validators\Integer_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Integer_Validator::class );
try {
}
echo '<br>';
}
_test_validate_int( true );
_test_validate_int( false );
```
* Play around with it!
QA can …
> P1-1193 create integer validator

- css/src/tailwind.css
- css/src/workouts.css
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/components/StepHeader.js
- packages/js/src/workouts/components/Stepper.js
* Once a user finishes the workout, each step should be individually editable by means of an _Edit_ button which appears aside the step's title
* Adds edit buttons and logic to a finished stepper's (editable) steps
* Stepper `saveAndContinue` function has been split into `saveEditedStep` and `continueToNextStep` to enhance reuse
* `StepHeader` component has been derived by `TailwindStep` component in order to better isolate state variables
* Edit button transitions uses the Tailwind classes declared in `stepperTimingClasses` object in order to (try to) b synchronised with the other steps transitions
* Start the configuration workout from scratch
* Verify there are no …
> Dupp 216 add edit buttons and logic

- src/integrations/front-end-integration.php
- tests/unit/integrations/front-end-integration-test.php
* We strip the title presenter when a theme does not support the `title-tag` and we don't force a rewrite of the title. This is correct behavior for the frontend, but the title should always get included in a get_head route via REST.
* Fixes a bug where the title of a page would not get included in our `get_head` REST route.
* 
* Install WordPress 5.9 with a FSE theme (like twenty twentytwo) or a theme without `title-tags` support.
* Install wordpress-seo 18.1
* Check the output of a `get_head` rest route. My example is on `http://standalone.wordpress.test/wp-json/yoast/v1/get_head?url=http://standalone.wordpress.test/hello-world/`
* Without this PR, it will not include a …
> Never filter the title presenter on a REST request

- patchwork.json
- src/integrations/admin/background-indexing-integration.php
- tests/unit/integrations/admin/background-indexing-integration-test.php
* When you redefine mockable internals with Patchwork, it will change the way mocks are handled. There's a known bug there, which will make all functions that take references instead of values on a (partially) mocked class result in failing tests.
* Fixes unittests with partial mocks in our addons.
* Since we can't `expect` calls of `register_shutdown_function` I created a wrapper which I then mock. That's the only way I could think of that would allow us to test the class as close to 100% as possible. I considered creating a scheduler class, but that can still not be tested because of the fact that we can't mock php internals while this bug is in place. 
* I also removed some `time` mocks, which weren't needed for the tests. …
> Fix failing tests with partial mocks with functions that take reference args

- src/helpers/indexable-helper.php
* This introduces a filter to enable/disable indexing globally. Currently, we only have `wpseo_should_save_indexable` which is only used in the Indexable Builders.
* Adds a filter to enable/disable creating indexables: `Yoast\WP\SEO\should_index_indexables`
* I considered moving the existing filter from the Indexable_Builder to the `Indexable_Helper::should_index_indexables` function, but the existing filter accepts a single indexable object to determine whether it should index or not. Since the `should_index_indexables` function globally determines whether we should index it can't have a single indexable to pass to the filter.
* Add define( 'WP_ENVIRONMENT_TYPE', …
> Should index filter

- src/integrations/blocks/structured-data-blocks.php
* Fixes an unreleased bug where an error would prevent saving the widget editor with our structured data blocks.
* If there is no post to cache on then don't optimize images.
* See https://yoast.atlassian.net/browse/QA-2893
*
Fixes https://yoast.atlassian.net/browse/QA-2893
> [QA-2893] Do not optimize images if no post

- packages/js/src/structured-data-blocks/faq/components/Question.js
- packages/js/src/structured-data-blocks/how-to/components/HowTo.js
- packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
https://github.com/WordPress/gutenberg/pull/30393 Removed this property and made it the default.
* Fixes a bug where a console warning would be thrown when adding a structured data block in the block editor, FSE editor or widget editor.
* Add structured data blocks in Gutenberg ( post editor, FSE editor and widget editor ).
* There should be no console warnings.
* Our structured data blocks.
Fixes [IM-1620]
> Remove keepPlaceholderOnFocus as it's now default behavior

- src/exceptions/validation/invalid-value-exception.php
- src/services/options/site-options-service.php
- src/validators/array-validator.php
- src/validators/boolean-validator.php
- src/validators/email-validator.php
- src/validators/empty-string-validator.php
- src/validators/integer-validator.php
- src/validators/is-equal-validator.php
- src/validators/news-sitemap-content-type-validator.php
- src/validators/string-validator.php
- src/validators/url-validator.php
- src/validators/validator-interface.php
- tests/unit/helpers/validation-helper-test.php
- tests/unit/validators/is-equal-validator-test.php
*
* Adds the is equal validator.
* Added settings parameter to validate (helper already passed it). It should be an (object) array. This means the other validators need adjusting (and open PRs will still need to be adjusted).
* I left the exception intentionally vague. If the value would be output in the message, it should be able to handle things like array to string conversion errors in the exceptions. I didn't want to do that 😉 
* Only implementation for free
```php
function _test_validate( $value, $equals ) {
/** @var …
```
> P1-1195 create is equal validator

- src/integrations/blocks/structured-data-blocks.php
* https://github.com/Yoast/wordpress-seo/pull/18030 added a form of caching that ensures that the lookup from block attributes to an image id is only done once. This had a bug where the lookup in the block attributes for a attachment id didn't store its result, automatically causing the more expensive src->attachment_id fallback to be used.
* Fixes an unreleased bug where attachment_ids weren't used if they were already present in the FAQ/HowTo block attributes.
* added an Isset check to make sure that we don't merge null with a list of images.
* Activate the query monitor plugin.
* Edit a post
* Add an FAQ block and insert an image. Be sure to _not edit the block any …
> Add missing assignment and type check

- packages/js/package.json
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/tailwind-components/ConfigurationStepperButtons.js
- packages/js/src/workouts/tailwind-components/StepCircle.js
- packages/js/src/workouts/tailwind-components/StepHeader.js
- packages/js/src/workouts/tailwind-components/Stepper.js
* In the initial implementation of the Stepper we tried to encapsulate all its behaviours via the props resulting in excessive prop threading throughout various components, and a massive API to use the Stepper.
* Refactor the Tailwind Stepper component to use a compound component pattern.
* After lots of headaches we read some articles ( https://kentcdodds.com/blog/compound-components-with-react-hooks%20https://kentcdodds.com/blog/inversion-of-control ) and realised that we tried to control everything on the definition side, whereas actually we should be giving control to the implementation side.
* The solution we choose is a Compound Component pattern using React `useContext`.
* The resulting code on the implementation side can …
> Refactor Stepper to use a Compound Component pattern

- src/integrations/blocks/structured-data-blocks.php
* In the block editor, if you add to the footer both the Yoast FAQ and Yoast How-to blocks, a PHP notice is displayed in the frontend footer of the site.
* Fixes an unreleased  bug  where a PHP notice would displayed in the frontend when using a FAQ or How-To block in the FSE.
* An extra existence condition has been added to avoid accessing a non-existent array element
1. Set up clean local env (WP 5.9, Twenty Twenty Two theme)
2. Install and activate Yoast Free 18.2
3. Go to `Appearance` -> `Editor`
4. Click on the Footer block to highlight it
5. Click it again to highligh the group inside the Footer block and click the `+` sign in the lower right corner
6. In the search …
> Add extra check to prevent accessing non-existent array element

- packages/js/src/classic-editor/replacement-variables/configurations.js
- packages/js/tests/classic-editor/replacement-variables/configurations.test.js
* When creating a post without assigning any category, `Uncategorized` will be automatically assigned as the category. Upon reopening the post, `Uncategorized` is also expected to be assigned as the primary category as well, which wan't the case. This PR fix this problem.
* Selects the only checked category as the primary category in Classic editor.
*
Requirements:
* Create a post without assigning any category
* Save the post and go to the posts overview page
**Test if `Uncategorized` is also assigned as `primary category`**
* Reopen the post that you just created
* Confirm that `Uncategorized` is checked as the category
* Use …
> Add a fallback value when no primary category is explicitly selected

- src/integrations/blocks/structured-data-blocks.php
* Fixes an issue where images in structured data blocks could become much larger
* See https://yoast.atlassian.net/browse/QA-2898
* Images in structured data blocks.
Fixes https://yoast.atlassian.net/browse/QA-2898
> [QA-2898] Add max-width: 100% to images in structured data blocks

- src/actions/importing/aioseo-posts-importing-action.php
- src/helpers/indexable-to-postmeta-helper.php
- tests/unit/actions/importing/aioseo-posts-importing-action-test.php
- tests/unit/helpers/indexable-to-postmeta-helper-test.php
* We want to keep the dynamic behavior when a user has set `featured-image` as a og or twitter image. That is, if after the import, the user changes the featured-image, the og/twitter image should be updated to the new featured image (only when og/twiter image source is `featured image` ofc)
* Improves the import of og and twitter image to retain the dynamic behavior when featured image is selected for social images
* When for a post `featured image` is selected as the source of og/twitter image in AIOSEO, we don't import anything and we let the Yoast's inherent calculation of og/twitter images when the indexable is built, to set the og/twitter image from the featured image
* In order for that to work, we had to adjust the …
> Don't import social image url if featured image is selected

- packages/components/src/image-select/ImageSelect.js
- packages/js/package.json
- packages/js/src/components/ImageSelectComponent.js
- packages/js/src/components/social/SocialForm.js
- packages/js/src/containers/FacebookEditor.js
- packages/js/src/containers/TwitterEditor.js
- packages/js/src/elementor/containers/FacebookEditor.js
- packages/js/src/elementor/containers/TwitterEditor.js
- packages/js/src/helpers/selectMedia.js
- packages/js/src/redux/reducers/facebookEditor.js
- packages/js/src/redux/reducers/twitterEditor.js
- packages/js/src/redux/selectors/facebookEditor.js
- packages/js/src/redux/selectors/twitterEditor.js
- packages/js/src/settings.js
- packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
* Fix up the alt texts for our image selector a bit.
* Not quite done, creating more issues for:
* Editor: no alt text on page load
* Editor: Twitter fallback does not have an alt text
* Fixes a bug where a warning would be thrown on pages with our image selector.
* Uses the alt texts from WordPress attachments when selecting images in the editor or in the settings.
* [shopify-seo] Fixes a bug where a warning would be thrown on pages with our image selector.
* [@yoast/components] Changes the `imageAltText` prop from the `ImageSelect` component to no longer be required.
* [@yoast/social-metadata-forms] Adds an `imageAltText` prop to the `SocialMetadataPreviewForm` component.
* Alt text is no longer required. The URL is not …
> P1-1058 console warning image alt text is undefined

- src/actions/importing/aioseo/aioseo-taxonomy-settings-importing-action.php
- src/services/importing/aioseo/aioseo-replacevar-service.php
- tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
- tests/unit/services/importing/aioseo-replacevar-service-test.php
* AIOSEO has a bug with the default replacevar tags of custom taxonomies where it adds some irrelevant tags which are always being translated into empty strings. This PR manages to transform those into empty strings while importing to Yoast SEO.
* Fixes an unreleased bug where some broken replacevar tags from AIOSEO in custom taxonomies would be transformed into Yoast tags
* While still using partial mocks for testing the settings import actions, the unit tests for the new code should be improved with https://yoast.atlassian.net/browse/PLUGIN-1449
* Activate AIOSEO and WooCommerce
* Go to AIOSEO->Search Appearance page, in the Taxonomies tab and add the following in the …
> Fix more broken replacevars in taxonomies

- src/helpers/taxonomy-helper.php
*
* Changes parameter names in the `Taxonomy_Helper` class to avoid breaking changes in PHP 8+
*
* N/A
Check for regressions with the taxonomy helper likeso:
* Go to Search Appearance settings in the Taxonomies tab and save an empty meta description for categories. 
* Go to a category's edit page and in the `Yoast SEO` metabox, confirm that the description there is empty.
* Add in the native WP Description of that category, some text, eg. `This is the description`. 
* Load the category in the frontend
* Verify that the og:description is having the `This is the description` value
* Ensure that no PHP notices/warnings/errors are …
> Rename parameters with reserved names in Taxonomy_Helper

- src/actions/importing/aioseo/abstract-aioseo-settings-importing-action.php
- src/actions/importing/aioseo/aioseo-custom-archive-settings-importing-action.php
- src/helpers/import-helper.php
- tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
- tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
- tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
- tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
- tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
- tests/unit/doubles/actions/importing/aioseo-custom-archive-settings-importing-action-double.php
- tests/unit/doubles/actions/importing/aioseo-default-archive-settings-importing-action-double.php
- tests/unit/doubles/actions/importing/aioseo-general-settings-importing-action-double.php
- tests/unit/doubles/actions/importing/aioseo-posttype-defaults-settings-importing-action-double.php
- tests/unit/doubles/actions/importing/aioseo-taxonomy-settings-importing-action-double.php
- tests/unit/helpers/import-helper-test.php
* We want to get closer to removing partial mocks in the new import framework
* Creates import helper to facilitate removing partial mocks from the new import framework in the future
* Created the Import_Helper to contain the flatten_settings() method, so that importing actions can use it from there.
* Added the Import_Helper as a dependency for Importing AIOSEO Settings actions via `@required`
* Follow the steps from the **For removing the import-cursor-manager-trait** section of the https://github.com/Yoast/wordpress-seo/pull/18047 PR
* The above instructions are basically regression …
> Facilitate removing partial mocks from the new import framework

- .travis.yml
- inc/class-upgrade.php
- src/helpers/image-helper.php
* Fixes an issue where HowTo images would not be optimized if they did not start with the site URL.
* Have a site URL that's different from your Home URL ( such as on yoast.com )
* Create a HowTo block, add an image to it and change the image's width.
* View that image on the frontend.
* It should be optimized with, among other things, the `loading="lazy"` attribute.
* Images in structured data blocks when the site URL is different from the home URL.
> Fix detecting images as external when they are not

- src/integrations/front-end/print-qrcode-embed.php
* Fixes the QR code not being removed after the print dialog is closed.
* Fixes a fatal error when attempting to display the QR code on pages that have no canonical.
* Go to any page.
* Open the print dialog.
* You should see a QR code at the bottom.
* Close the dialog.
* You should not see a QR code at the bottom of the normal page.
* Go to a page which is noindexed.
* Open the print dialog.
* You should not see a QR code.
* There should be no errors in your console.
* Printing QR codes at the bottom of the page.
Fixes https://github.com/Yoast/wordpress-seo/pull/18089#issuecomment-10468065 …
> Remove QR code after print and only display if there is a URL

- src/integrations/blocks/structured-data-blocks.php
* We want to fix a bug in the Twenty Twenty-One theme, where setting a custom width in a HowTo image wouldn't be applied in the frontend
* Fixes a bug where HowTo images with custom width would lose their custom width in the Twenty Twenty-One theme.
*
* Have the Twenty Twenty-One theme active and create a new post
* In the post add a HowTo block with an image in one of the steps.
* After adding the image, click on it and add a custom width that's lower than the width of the image.
* Go to the frontend
* The image would be shown in its original width, ignoring the width we set in the edit post page
With this PR:
* The image would be shown in the width we …
> Dupp 297 fix how to images custom width

- src/exceptions/validation/missing-settings-key-exception.php
- src/exceptions/validation/no-regex-groups-exception.php
- src/exceptions/validation/no-regex-match-exception.php
- src/services/options/site-options-service.php
- src/validators/regex-validator.php
- tests/unit/validators/regex-validator-test.php
*
* Adds the regex validator.
The solution, while I think it turned out ok. Feels overkill for what we do with it.
Perhaps we should consider rewriting over extending this to the perfect verify validators we do want. If not for the exception message alone.
Other than that:
* The original implementation split this up into 2 regexes, and calling `sanitize_text_field`. The latter is still missing now. Created [an issue](https://yoast.atlassian.net/browse/P1-1204) to fix that.
* You can run this somewhere and play around with feeding it different input:
```php
function _test_validate( $value, $pattern ) {
/** @var …
```
> P1-1196 create regex validator

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/tailwind-components/Stepper.js
- packages/js/src/workouts/tailwind-components/steps/indexation/ConfigurationIndexation.js
- packages/js/src/workouts/tailwind-components/steps/indexation/Indexation.js
- packages/js/src/workouts/tailwind-components/steps/indexation/indexation-step.js
* If indexation is already done, but the stepper has not yet been finished, the copy needed to be different.
* Changed the copy of the success alert when indexation had already been done and the configuration was not yet finished.
* Introduced a fourth state to distinguish between "just finished" ( `completed` ) and "already done" ( `already_done` )
* Have Yoast Test Helper active, reset indexation
* Run indexation in the configuration stepper
* When it completes, the text should read: We’ve succesfully analyzed your site
* Refresh the page (as if you got here with indexation already done), text should be: We've already successfully analyzed your site. You can move on to …
> Change Indexation step success alert copy

- src/integrations/front-end/print-qrcode-embed.php
- src/integrations/front-end/print-qrcode-render.php
* We want to catch exceptions coming from the QR code lib and show a `400 - error message` instead
* We also want to show a QR code for the homepage if the URL is too long
* Enhances the QR code feature by catching fatal errors from the QR code lib and gracefully showing the error in the frontend.
*
* Go to a page in the frontend, check it's page source and find the `yoast_seo_print_qrcode_script` script
* In the `<img src="http://basic.wordpress.test/?nonce=e7707d3e54&yoast_qr_code=http%3A%2F%2Fbasic.wordpress.test%2F\"` tag there, copy that url and open it in a different tab
* Confirm that you'll see a QR code there
* Now take the part in that url, after the …
> DUPP-301 Catch exceptions from the QR code lib

- src/config/schema-types.php
- src/config/separator-options.php
- src/exceptions/validation/invalid-settings-exception.php
- src/exceptions/validation/missing-settings-key-exception.php
- src/exceptions/validation/not-in-array-exception.php
- src/helpers/taxonomy-helper.php
- src/services/options/site-options-service.php
- src/validators/in-array-keys-validator.php
- src/validators/in-array-provider-validator.php
- src/validators/in-array-validator.php
- tests/unit/helpers/taxonomy-helper-test.php
- tests/unit/validators/in-array-keys-validator-test.php
- tests/unit/validators/in-array-provider-validator-test.php
- tests/unit/validators/in-array-validator-test.php
*
* Adds the in array validator.
* Adds the in array key validator.
* Adds the in array provider validator. Where you can configure a method in class to give back the allow list (array).
* Left the `In_Array` name we decided upon earlier. Even though our name length sniff gave some protest there. Was pondering about:
* `Contains` -- but that could also indicate a string? Which is not what it does.
*  `Allow_List` -- that isn't shorter! But does convey some more meaning maybe.
* Added key and provider variants to have a slightly broader default range we can use them for. But still there will have to be some very specific validators that are almost these. 
* Copied over (instead of removing right away) some code to put in classes …
> P1-1192 create in array validator

- packages/js/src/settings.js
* Fixes an unreleased bug where the News Addon settings page would break because of the settings Redux store being unavailable.
* Bug was caused by changes to settings entrypoint in [this PR](https://github.com/Yoast/wordpress-seo/pull/18071/files?file-filters%5B%5D=.js&show-viewed-files=true#diff-72fe1c8bb99ec64963d955519e9fa74bb74b25bf6708dfcf4d45c013dd5d9482R2).
* Fixes an unreleased bug where the News Addon settings page would break because of the settings Redux store being unavailable.
* Reverted changes to settings entry point from [this PR](https://github.com/Yoast/wordpress-seo/pull/18071/files?file-filters%5B%5D=.js&show-viewed-files=true#diff-72fe1c8bb99ec64963d955519e9fa74bb74b25bf6708dfcf4d45c013dd5d9482R2).
This PR …
> [QA-2937] Restore load order of settings Redux store in settings entry point

- src/actions/importing/aioseo/aioseo-general-settings-importing-action.php
- tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
* We want to fix cases where the user has already set an organization or person logo in their schema general settings
* To do so, we need to initialize again the logo id and meta in the db, before importing the AIOSEO organization or person logo
* We also produce the id and meta after we import the logo url
* Fixes an unreleased bug where organization and person logos in the Knowledge Graph wouldn't be updated if there were already there before AIOSEO import
*
* Have Yoast active and set an Organization logo in Search Appearance->General
* Activate AIOSEO and in their Appearance->General set a Organization Name but leave the Organization Logo empty
* Import AIOSEO to …
> DUPP-302 Fix case when organization logo exists before import

- inc/options/class-wpseo-option-wpseo.php
- src/integrations/front-end/print-qrcode-embed.php
- src/integrations/front-end/print-qrcode-render.php
* Replaces the QR code nonce with a salted code. This has several advantages:
* It can be cached for more than one day.
* It can be cached for one user and server to another.
* The endpoint can only be used with the specific URL we generate rather than any URL ( including vastly more computationally expensive ones ).
* Fixes the QR code not working when a page is cached for user A but served to user B.
* Fixes the QR code not working if it's served from a cache with an expired nonce.
* Fixes the QR code endpoint being usable with any URL.
* The QR code endpoint should always work on yoast.com, even when logging in as different users.
* The QR code endpoint shouldn't …
> Replace QR code nonce with salted code

- packages/js/src/classic-editor/helpers/dom.js
- packages/js/src/classic-editor/watcher.js
- packages/js/tests/classic-editor/helpers/dom.test.js
- packages/seo-integration/src/google-preview-container.js
* There were some problems related to slug, url and permalink preview that are fixed in this PR:
* the slug in url preview was previewed twice after the base url
* when a post doesn't have a title, the path name in url preview shows `undefined`
* any changes made in the slug field inside snippet editor is not saved even after clicking `Save` or `Update` button
* any changes made in the slug field inside snippet editor is not immediately reflected in the permalink field and in the WordPress `Slug` field
* the title will be assigned as the slug, overwriting the slug value that was saved inside the snippet editor
* Sets an empty string as the fallback value for Post slug.
* Excludes slug from the base URL that is previewed in Google …
> Fix URL and permalink preview

- packages/js/src/initializers/elementor-editor-integration.js
- src/integrations/third-party/elementor.php
* In Elementor 3.6.0, our way of rendering React in the Elementor Yoast tab is broken. This PR fixes that by changing the place React is rendered.
* The problem is caused by the `run:after` event not being triggered on the `$e.routes` API anymore since [a major Elementor JS refactor](https://github.com/elementor/elementor/commit/9badffae32291ed567412dae9c85cd524cbcc67b#diff-76c13bdd5dc28b8e7fd6da876614f16a39bd59a9ce5f2eaf8701966b77d87c61R475).
* Fixes an incompatibility with Elementor 3.6.0 where the React contents of the Yoast tab in Elementor are not rendered.
* Move rendering of React in Yoast tab from `run:after` event callback to [menu item callback](https://github.com/Yoast/wordpress-seo/pull/18146/files#diff-0d2d7e68459adaf …
> Fix rendering of React in Elementor Yoast tab

- packages/js/src/initializers/elementor-editor-integration.js
- src/integrations/third-party/elementor.php
* Cherry picked from https://github.com/Yoast/wordpress-seo/pull/18146 - which was merged to `trunk`, we want it out sooner.
* In Elementor 3.6.0, our way of rendering React in the Elementor Yoast tab is broken. This PR fixes that by changing the place React is rendered.
* The problem is caused by the `run:after` event not being triggered on the `$e.routes` API anymore since [a major Elementor JS refactor](https://github.com/elementor/elementor/commit/9badffae32291ed567412dae9c85cd524cbcc67b#diff-76c13bdd5dc28b8e7fd6da876614f16a39bd59a9ce5f2eaf8701966b77d87c61R475).
* Fixes an incompatibility with Elementor 3.6.0 where the React contents of the Yoast tab in Elementor are not rendered.
* Move rendering of React in Yoast tab from …
> P1-1260 fix elementor react rendering 183 release

- src/initializers/migration-runner.php
- src/loader.php
- src/surfaces/classes-surface.php
- wp-seo-main.php
* For php8 compatibility we should avoid using reserved parameter names.
* Avoids usage of the reserved parameter name "$class".
*
* These changes should all be internal to methods, so no behaviour should be affected. For clarity, the areas touched are:
* Migration (so migrating the database from version to version should still work)
* Loader (so autoloading should still work)
* wp-seo-main (so _everything_ should still work - but loading specifically)
* classes_surface (this is a helper function used throughout the plugin, so falls in the category "everything should still work").
* …
> Don't use $class as parameter name in free

- src/integrations/admin/admin-columns-cache-integration.php
- src/integrations/third-party/woocommerce-permalinks.php
- src/integrations/watchers/indexable-permalink-watcher.php
- tests/unit/integrations/third-party/woocommerce-permalinks-test.php
* For php8 compatibility we should avoid using reserved parameter names.
* Avoids usage of the reserved parameter name "$parent".
* Avoids usage of the reserved parameter name "$new".
*
* These changes should all be internal to methods, so no behaviour should be affected. For clarity, the areas touched are:
* admin_columns_cache_integration -> so areas where we add tables in the admin (e.g. internal link count in post overview) should still work.
* woocommerce-permalinks -> a function that runs on this action `update_option_woocommerce_permalinks` was affected, so likely changing permalinks in woocommerce should still work.
* permalink-watcher -> Handles updates to the …
> Fix a few reserved parameters in the integrations folder

- inc/sitemaps/class-sitemap-cache-data.php
* We want to use the same param names in WPSEO_Sitemap_Cache_Data and its interface.
* Changes the name of the parameter in WPSEO_Sitemap_Cache_Data::set_status.
*
* This change should not affect anything outside the method. Possible impact would be in **Sitemap cache**.
*
*
Fixes [DUPP-312]
[DUPP-312]: https://yoast.atlassian.net/browse/DUPP-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DUPP-312 Use parameter name from interface in WPSEO_Sitemap_Cache_Data

- src/integrations/admin/helpscout-beacon.php
* The session details that we send to HelpScout when a user uses our beacon were outdated. This PR aims to:
* Remove all HTML tags for a cleaner look (they were not parsed anymore)
* Remove unused details (like host OS and name)
* Remove the version of our own separate plugin fields, as it was not working correctly
* Add PHP Memory information
* Add information about mu-plugins and dropins (count)
* Add information about indexables and migrations status
* Add information about the site and user locale settings
* Add transient caching for 5 minutes to prevent having to request all this information on every backend pageload
* Updates and caches the session details that our HelpScout beacon sends to our support team.
* To prevent …
> Update helpscout beacon session details

- .travis.yml
- tests/unit/bootstrap.php
- wp-seo-main.php
- wp-seo.php
* On January 25, 2022, WordPress 5.9 was released. We've decided to go back to supporting only the latest 2 WP versions.
* Sets minimum required WordPress version to 5.8.
*
*
*
*
Fixes #
> Set minimum WP version to 5.8

- tests/integration/admin/import/test-class-import-aioseo.php
- tests/integration/admin/import/test-class-import-greg-high-performance-seo.php
- tests/integration/admin/import/test-class-import-headspace.php
- tests/integration/admin/import/test-class-import-jetpack.php
- tests/integration/admin/import/test-class-import-platinum-seo-pack.php
- tests/integration/admin/import/test-class-import-premium-seo-pack.php
- tests/integration/admin/import/test-class-import-rankmath.php
- tests/integration/admin/import/test-class-import-seo-framework.php
- tests/integration/admin/import/test-class-import-seopressor.php
- tests/integration/admin/import/test-class-import-smartcrawl.php
- tests/integration/admin/import/test-class-import-squirrly.php
- tests/integration/admin/import/test-class-import-ultimate-seo.php
- tests/integration/admin/import/test-class-import-woothemes-seo.php
- tests/integration/admin/import/test-class-import-wp-meta-seo.php
- tests/integration/admin/import/test-class-import-wpseo.php
* For php8 compatibility we should avoid using reserved parameter names.
* Avoids usage of the reserved parameter name "$bool" in the integration tests.
* 
*
* These changes should all be internal to methods, so no behaviour should be affected. For clarity, the areas touched are:
* integration tests
All of these are integration tests and all changes are self-contained. So testing is done by running the tests anyways, just mentioned the areas in case something breaks.
*
*
Fixes DUPP-314
> Don't use $bool as a parameter name in integration tests function

- src/presenters/abstract-indexable-presenter.php
- src/presenters/admin/light-switch-presenter.php
- tests/unit/builders/indexable-link-builder-test.php
- tests/unit/helpers/pagination-helper-test.php
- tests/unit/helpers/schema/replace-vars-helper-test.php
- tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
- tests/unit/presenters/meta-description-presenter-test.php
- tests/unit/presenters/open-graph/description-presenter-test.php
- tests/unit/presenters/open-graph/title-presenter-test.php
- tests/unit/presenters/title-presenter-test.php
* For php8 compatibility we should avoid using reserved parameter names.
* Avoids usage of the reserved parameter name "$default" in the unit tests.
* Avoids usage of the reserved parameter name "$string" in the unit tests and abstract indexable presenter.
* Avoids usage of the reserved parameter name "$array" in the unit tests.
* Avoids usage of the reserved parameter name "$var" in the light switch presenter.
*
* These changes should all be internal to methods, so no behaviour should be affected. For clarity, the areas touched are:
* unit tests
* presenters (light switch and abstract indexable presenter)
Most of these are unit tests and all changes are self-contained. …
> Dont use $string in replacevar function

- src/services/options/site-options-service.php
- src/validators/sanitize-option-validator.php
- tests/unit/validators/sanitize-option-validator-test.php
*
* Adds the sanitize option validator.
*
```php
function _test_validate( $value, $option ) {
/** @var \Yoast\WP\SEO\Validators\Sanitize_Option_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Sanitize_Option_Validator::class );
try {
var_dump( $validator->validate( $value, [ 'option' => $option ] ) );
}
echo '<br>';
}
_test_validate( 'category', …
```
> P1-1198 create sanitize option validator

- src/services/options/site-options-service.php
- src/validators/wp-kses-post-validator.php
- tests/unit/validators/wp-kses-post-validator-test.php
*
* Adds the wp kses post validator.
*
```php
/** @var \Yoast\WP\SEO\Validators\Wp_Kses_Post_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Wp_Kses_Post_Validator::class );
try {
}
echo '<br>';
}
_test_validate( 123 );
```
* You can play with the setting (see [this …
> P1-1200 create wp kses post validator

- .github/workflows/codeql-analysis.yml
* Improves CI
* Improves CI
As this workflow is currently only being run via a cron job, the `pull_request` condition will never be met.
Additionally, this step triggers the following warning on GH Actions:
```
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
This commit:
* …
> GH Actions/CodeQL: various improvements

- .github/workflows/cs.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .travis.yml
- README.md
- composer.json
- config/composer/actions.php
* CI/QA is now run via GitHub Actions for the PHP code style, PHP linting and the Composer dependency security check
* CI/QA is now run via GitHub Actions for the PHP code style, PHP linting and the Composer dependency security check
👉🏻 This PR will be easiest to review by reviewing each commit individually.
This commit:
* Adds a GH Actions workflow for the CI code style check and to validate the `composer.json` file.
* Removes those actions from the `.travis.yml` configuration.
* Adds a few tweaks to the CS related functions in the `Yoast\WP\SEO\Composer\Actions` class.
* Adds a "Build Status" badge in the Readme to use the results from this particular GH Actions run.
Notes:
1. Builds will run on all pushes and on pull requests, …
> CI: switch to GitHub Actions - step1 to 3

- src/helpers/url-helper.php
- tests/unit/helpers/url-helper-test.php
* Workshop PHP 8.1 compatibility 2022-02-24
* Adds a check and unit test for the Url_Helper, to cover when wp_parse_url returns null
*
* Tests should run and pass.
*
*
Fixes #
> Url_Helper check for wp_parse_url returning null

- src/services/options/site-options-service.php
- src/validators/verification-validator.php
- tests/unit/validators/verification-validator-test.php
* Fixes a leftover issue from https://github.com/Yoast/wordpress-seo/pull/18023 where the verification options did not sanitize the input like the original (running `sanitize_text_field`).
* Adds the verification validator.
*
* You can run this somewhere and play around with feeding it different input:
```php
function _test_validate( $value, $settings ) {
/** @var \Yoast\WP\SEO\Validators\Verification_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Verification_Validator::class );
try {
var_dump( $validator->validate( $value, …
```
> P1-1204 fix regex validator to sanitize like text instead of string

- admin/pages/social.php
- admin/views/tabs/social/accounts.php
* Organizations currently specify information related to their social profiles in the _Accounts_ tab of the _Social_ page in the admin menu sidebar. With the introduction of the _First time configuration_ workout users will specify this information in the _Social profiles_ step instead, so the form in the _Accounts_ tab of the _Social_ page must be removed. 
*  Remove social accounts form for Organization and update both Person and Organization text
* N/A
* Click on on _Search Appearance_ in the _SEO_ submenu of the admin menu sidebar
* Make sure that in the _Knowledge Graph & Schema.org_ section _Organization_ is selected from the first drop-down menu
* Click on _Social_ …
> Dupp 290 remove social profiles controls

- admin/tracking/class-tracking-settings-data.php
- inc/class-upgrade.php
- inc/options/class-wpseo-option-social.php
- tests/unit/inc/options/option-social-test.php
* We want to switch to a different structure for the social profiles options in preparation for the changes in the First-time configuration and the new Settings UI. 
* Changes the structure of the Social options to accept an unlimited array of URLs beside the Facebook and Twitter profiles.
* The validation just check if data is an array, without any check about elements being URLs.  This has been done to unblock this PR and make the change available for an upcoming PR that will provide changes to the API route.
* The PR includes an upgrade routine that will need to be adapted with the actual version number. The routine does not delete outdated social options, allowing user to downgrade without losses of data (as long as they …
> DUPP-289 Switch other social URLs to array

- packages/js/package.json
- packages/js/src/analysis/plugins/reusable-blocks-plugin.js
- packages/js/src/initializers/post-scraper.js
- yarn.lock
* Pick up reusable block changes in the analysis.
* Fixes a bug where reusable block content would not be updated in our analysis when changed in the editor.
* Note that this gets all the content of all the blocks on every store change... far from optimal. I failed to find a better ways to fix this.
* Added the `@wordpress/blocks` dependency at the version that should be in WP now (`11.9` according to https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/).
* Create/edit a post in the block editor
* Add some blocks
* Convert/add a couple of reusable blocks
* Verify the analysis text gets the correct content. I use debug output: e.g. put `define( …
> Add reusable block change listener

- admin/class-yoast-form.php
- admin/views/tabs/dashboard/integrations.php
- admin/views/tabs/network/integrations.php
- inc/options/class-wpseo-option-ms.php
- src/helpers/wordproof-helper.php
- src/integrations/third-party/wordproof-integration-toggle.php
- src/integrations/third-party/wordproof.php
* This PR removes multisite compatibility for the WordProof integration
* Adds logic to display this to the user.
* This PR removes multisite compatibility for the WordProof integration
* Adds attribute that is checked to hide the disabled_note for subsites
* Adds variable to wordproof_helper to return the conditional that is unmet to display proper message for the network admin
* added 'admin_network_integration_after' action, just like how it's used in integrations.php 
1. Activate plugin on a multisite
2. The wordproof integration should be disabled
3. Text underneath the integration should display this to the user on subsites and on the site network integrations page. …
> Wordproof remove multisite compatibility

- package.json
- packages/js/package.json
- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/tailwind-components/base/alert.js
- packages/js/src/workouts/tailwind-components/base/combo-box.js
- packages/js/src/workouts/tailwind-components/base/single-select.js
- packages/js/src/workouts/tailwind-components/helpers/index.js
- packages/js/src/workouts/tailwind-components/steps/indexation/ConfigurationIndexation.js
- packages/js/src/workouts/tailwind-components/steps/site-representation/person-section.js
- packages/js/src/workouts/tailwind-components/steps/site-representation/site-representation-step.js
- packages/js/src/workouts/tailwind-components/steps/site-representation/user-selector.js
- src/integrations/admin/configuration-workout-integration.php
- tailwind.config.js
- yarn.lock
* HeadlessUI / TailwindUI released a nicely styled combobox that ALMOST covers the use cases we have with our wordpress user select. So let's use it!
* The exception is that the Combobox opens slightly differently (yet accessible), and that it is not async, like our current implementation (which is an async react-select from a package)
* Uses a HeadlessUI combobox instead of an async react-select component for the first time configuration's user select.
* Created an async wrapper for the base combobox component
* ~Implemented additional UX requirements with the exception of opening on click input, since that gave me some issues with aria-expanded booleans that were not within my control. Should pick up in a separate issue (DUPP …
> Use tailwind combobox as user-select dropdown

- .github/workflows/js.yml
- .travis.yml
- config/grunt/task-config/eslint.js
- packages/search-metadata-previews/package.json
- packages/yoastseo/grunt/config/shell.js
* CI/QA is now run via GitHub Actions for the JS linting and testing checks
* CI/QA is now run via GitHub Actions for the JS linting and testing checks
This commit:
* Adds a GH Actions workflow for the Javascript related CI checks.
* Removes all references to that check from the `.travis.yml` configuration.
* Updates the warning thresholds in a couple of configuration files to reflect the current reality.
Notes:
1. Builds will run on:
- Select pushes using branch filtering similar to before.
- All pull requests.
- When manually triggered.
Note: manual triggering of builds has to be [explicitly allowed](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/). This is not a feature which is …
> CI: switch to GitHub Actions - step 4: javascript checks

- admin/views/class-yoast-feature-toggle.php
- admin/views/tabs/dashboard/integrations.php
- admin/views/tabs/network/integrations.php
- src/integrations/third-party/wordproof-integration-toggle.php
* Add a new badge to integration toggles
* Add a new badge to the WordProof integration toggle
* Adding to the Yoast_Feature_Toggle class
- go to the integrations tab
- WordProof should have the new badge
- go to the integrations tab
- WordProof should have the new badge
*
* The integration toggles
Fixes #
> Add new badge to integration toggle

- lib/orm.php
* We want to use the same param names as in the ArrayAccess interface in ORM.
* Changes the name of the parameter in ORM methods overloaded from ArrayAccess.
*
* This change should not affect anything outside the method. Possible impact would be in **Indexables**.
*
*
Fixes [DUPP-337]
[DUPP-337]: https://yoast.atlassian.net/browse/DUPP-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DUPP-337 Use parameter name from ArrayAccess interface in orm.php

- tests/unit/main-test.php
* Improve tests
* Improve tests
The fixture methods should **never** contain expectations or assertions. Those belong in the actual tests.
* _N/A_ This is a test-code only change. If the build passes, we're good.
> Main_Test: set expectations in the test itself, not in the `set_up()` fixture method

- src/config/wordproof-translations.php
- src/helpers/current-page-helper.php
- src/helpers/woocommerce-helper.php
- src/helpers/wordproof-helper.php
- src/integrations/admin/helpscout-beacon.php
- src/integrations/third-party/wordproof-integration-toggle.php
- src/integrations/third-party/wordproof.php
* CS/QA: use fully qualified global function calls
* CS/QA: use fully qualified global constants
* _N/A_
> CS/QA: use fully qualified globals

- src/helpers/wincher-helper.php
* Code quality
* Code quality
Do not use double negatives to type cast a value. Use a proper type cast instead.
This improves readability and makes the code less bug-prone.
* _N/A_
> CS/QA: do not use double negatives

- src/config/wincher-pkce-provider.php
The `@codingStandardsIgnoreStart` tag should never be used and I see no reason why this file (which mostly complies with the YoastCS requirements) should be exempt.
This commit fixes up the complete file and makes very select allowance for a few exceptions to the rules.
* _N/A_ This is a code-only change and should have no effect on functionality.
> Wincher_PKCE_Provider: file is not exempt from CS

- tests/integration/admin/test-class-yoast-network-admin.php
* Improve tests
* Improve tests
These assertions should have been updated when the PHPUnit Polyfills were introduced, but they have clearly fallen through the cracks as the tests were not run against WP Multisite previously (which they soon will be, which is how this was discovered).
> Tests: fix a few assertions

- src/validators/news-sitemap-content-type-validator.php
- src/validators/url-validator.php
- tests/unit/validators/boolean-validator-test.php
- tests/unit/validators/empty-string-validator-test.php
- tests/unit/validators/url-validator-test.php
- tests/unit/validators/verification-validator-test.php
* Since the tests are mocked they are not producing the same results as in the integration tests. This is the easy fix.
* Removes failing URL validator test cases.
* The tests results were different between local and Travis. It was either the mocked WP or the PHP 5.6 doing it. Most likely the first. But because our tests do not have to test the WP functions, it is okay to remove the tests here.
* Fix some (unrelated) PHP CS errors on the feature branch.
*
* No need to test the tests, especially removal of said tests
*
Fixes …
> Remove failing validator test cases

- composer.lock
* Removes the unpkg CDN link for '@wordproof/uikit' and uses locally stored scripts.
* Removes the unpkg CDN link for `@wordproof/uikit` and uses locally stored scripts.
* modules are lazy-loaded to only load relevant data.
* Go to your timestamped page
* Open the network tab in DevTools
* Make sure the uikit scripts are loaded from 'wordpress-sdk' vendor and no unpkg origin is used.
* Make sure the certificate link and modal are still loading and functioning correctly 
* [ x] QA should use the same steps as above.
*
* Pages with a timestamp
* [x ] I have tested this code to the best of my abilities …
> wordproof/wordpress-sdk 1.2.11

- src/exceptions/validation/invalid-twitter-username-exception.php
- src/services/options/site-options-service.php
- src/validators/twitter-username-validator.php
- tests/unit/validators/twitter-username-validator-test.php
* Adds the Twitter username validator.
* Adds the Twitter username validator.
*
```php
/** @var \Yoast\WP\SEO\Validators\Twitter_Username_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Twitter_Username_Validator::class );
try {
}
echo '<br>';
}
_test_validate( …
```
> P1-1205 - Create Twitter site validator

- src/builders/indexable-post-builder.php
- tests/unit/builders/indexable-post-builder-test.php
* When building post indexables on PHP 8.1 a deprecation is thrown when`meta-robots-adv` doesn't have a value. This is because `null` is passed to `explode`. This PR prevents that by removing the transformation from an empty string to null and leaving that behaviour intact for values that expect a null value.
* Fixes a deprecation warning in building post indexables when leaving "Meta robots advanced" empty and while using PHP 8.1 or higher.
* I used the newer Meta_Helper instead of the static call to WPSEO_Meta.
* There are still `'' -> null` conversions being done because the indexable model expects null values and not empty strings in those cases. I'd like to get rid of that eventually, but it's out of scope for this PR.
* I …
> PHP 8.1 compatibility: build post indexable without advanced robots settings

- composer.lock
https://yoast.slack.com/files/U01763ZA8NA/F036QNNM6HL/screencast_2022-03-10_11-12-43.mp4
* When updating your privacy policy within 4 seconds after the last save, a transient is returned. This causes a fatal error and the pages’ timestamp changes, but not the blockchain entry.
* Fix thrown error when saving a page that should be timestamped
* Within the debounce period, an error was thrown as the data from a transient was returned instead of a WP_Rest_Response. When a transient is returned, it is now returned as a WP_Rest_Response.
1. Enable the WordProof integration on your privacy policy.
1. Make a change to the page and update twice within 4 seconds.
1. The error log …
> Fix error on timestamp

- src/actions/importing/aioseo/aioseo-cleanup-action.php
* We want to avoid throwing a database error, when the user tries to cleanup a setup where the AIOSEO indexable table has already been cleaned up manually.
* Fixes a bug where in certain edge cases a database error would show during AIOSEO clean up
This method is supposed to return a string (based on the docblock) and the return value is passed on to `WPDB::query()`, which expects a string as well, so probably better to return an empty string than to return boolean `true`.
Alternatively, if there is a good reason to return `true` here, `bool` should be added to the return type and the reason for returning `true` should be documented inline.
@leonidasmi And this is another one where I'd like to ask you for a review as a sanity …
> DUPP-349 CS/QA: fix inconsistent/incorrect return statement

- .github/workflows/unittest.yml
- .travis.yml
- README.md
- tests/unit/conditionals/estimated-reading-time-conditional-test.php
- tests/unit/helpers/input-helper-test.php
- tests/unit/main-test.php
* CI/QA is now run via GitHub Actions for the PHP unit tests
* CI/QA is now run via GitHub Actions for the PHP unit tests
This commit:
* Adds a GH Actions workflow for the PHPUnit CI check.
* Removes all references to that check from the `.travis.yml` configuration.
* Adds a "Unit Tests" badge in the Readme using the results from the GH `Unit Test` Action runs.
Notes:
1. Builds will run on:
- Select pushes using branch filtering similar to before.
- All pull requests.
- When manually triggered.
Note: manual triggering of builds has to be [explicitly allowed](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/). This is not a feature which is enabled by default.
2. If a previous GH …
> Switch to GH Actions - step 5: unit tests

- .github/workflows/jslint.yml
- .github/workflows/jstest.yml
- packages/yoastseo/grunt/config/eslint.js
- packages/yoastseo/package.json
* Make CI faster
* Make CI faster
The JS workflow was the slowest workflow, with a runtime of easily 10 minutes.
This commit fixes that by making the runs more modular.
* The JS lint task will now be run in a separate workflow. No other changes were made to the lint job.
* The JS test task has now been split into two different jobs:
1. One job for small packages.
2. One job for "big" packages.
The "small" packages job will:
* Run on select push events, PRs and on demand.
* NOT run via the cron job.
* Run the full test suite for each package, always.
* Run the tests for each package via a matrix, resulting in a separate build for each package.
* Runs with `fail-fast: false` as these runs are all unique so we don't want to job to …
> GH Actions/JS: split the workflow into two + separate test builds per package

- src/generators/schema/organization.php
- tests/unit/generators/schema/organization-test.php
* We want to make sure that the `sameAs` property in the `Organization` Schema piece is built using the new format options introduced in #18174 
* Updates the Schema generation to fetch social profiles in the new array format for the `sameAs` property
*
* make sure you have set "Organization" (with a name and a logo) in Search Appearance
* inspect `wpseo_social` in the DB options table
* if you tested DUPP-329, you should already see the options in the right format
* otherwise, or for a more comprehensive test, you can set the value to the following. Note that the old options are empty, and the `other_social_urls` has some duplicated and empty fields that should not …
> DUPP-331 Update sameAs generation

- admin/tracking/class-tracking-default-data.php
* I was just updating Yoast SEO on a client's site hosted on WordPress VIP and the sniffs detected this issue.
* Fixes a bug where `date()` could return the incorrect date. Props to [BronsonQuick](https://github.com/BronsonQuick).
* When inspecting the data send to our tracking server ( make sure tracking is enabled ) it should contain the correct ( current ) date.
* On line 124 in `admin/tracking/class-tracking.php` put `var_dump( $collector->get_as_json() ); exit;` to output the data before the request is sent.
* The data in our tracking request
> Bug: date() is affected by runtime timezone changes

- inc/class-wpseo-content-images.php
- tests/unit/inc/content-images-test.php
`WPSEO_Content_Images::get_img_tag_source` now checks if the found source url for an image is an URL. This should avoid an issue where data uri's where being duplicated into the Schema.org part of a page when no featured image is set.
This PR can be summarized in the following changelog entry: changelog: bugfix
* Fixes a bug where data uri's would be considered for Schema.org content when no featured image is set. Props to [NielsdeBlaauw](https://github.com/NielsdeBlaauw).
* Adjusted test to return a URI scheme, as `get_home_url` does in WordPress.
* See reproduction in issue #18176
Fixes #18176
> Fixes #18176. Adds url validation for images from content.

- src/config/wordproof-app-config.php
* Change WordProof environment to production
* Removes the environment override in the WordProof app config
* Removes the environment override in the WordProof app config
**Please remove `wordproof_source_id` and `wordproof_access_token` from your database manually before trying to use the integration**
1. Try and timestamp your privacy page
2. Make sure the authentication flows is handled by 'my.wordproof.com'
3. Make the the authentication works correctly (note you probably need a new account due to the move to a new server)
4. Try to timestamp the page.
* The WordProof integration …
> WordProof: use production environment

- packages/js/src/classic-editor/helpers/dom.js
- packages/js/src/classic-editor/initial-state.js
- packages/js/src/classic-editor/replacement-variables/configurations.js
- packages/js/src/classic-editor/watcher.js
- packages/js/tests/classic-editor/helpers/dom.test.js
- packages/js/tests/classic-editor/initial-state.test.js
- packages/js/tests/classic-editor/replacement-variables/configurations.test.js
- packages/seo-store/src/editor/slice.js
*
* Fixes a bug where non-hierarchical custom taxonomies variables didn't return the correct replacement in Classic editor.
* This PR also introduces non-user facing changes in order to make the custom taxonomies replacement variable work in the new Classic editor integration. [Here](https://yoast.atlassian.net/wiki/spaces/LIN/pages/2378104851/Classic+editor+functionality+comparison+on+trunk+and+on+the+feature+branch) is the overview of which parts of custom taxonomies which this PR fixes (see the `Agnostic analysis` column).
* I added `/* eslint-disable camelcase */` to disable the camelcase warnings inside `configurations.tests.js` and `dom.tests.js`. I think it's okay to do this in a test file, otherwise the number of the …
> Adds support for custom taxonomies as replacement variables

- .github/workflows/integrationtest.yml
- .travis.yml
- README.md
- config/scripts/install-wp-tests.sh
- tests/integration/admin/test-class-yoast-network-admin.php
- tests/integration/bootstrap.php
* CI/QA is now run via GitHub Actions for the PHP integration tests
* CI/QA is now run via GitHub Actions for the PHP integration tests
This commit:
* Adds a GH Actions workflow for the PHPUnit Integration test CI check.
* Removes all references to that check from the `.travis.yml` configuration.
* Replaces the "Build Status" badge in the Readme with a badge using the results from the GH `IntegrationTest` Action runs.
All other workflows have their own status badges, so the Travis badge can now be safely removed.
Notes:
1. Builds will run on:
- Select pushes using branch filtering similar to before.
- All pull requests.
- When manually triggered.
Note: manual triggering of builds has to be [explicitly …
> Switch to GH Actions - step 6: integration tests

- packages/ui-library/src/components/checkbox-group/index.js
- packages/ui-library/src/components/checkbox-group/stories.js
- packages/ui-library/src/components/radio-group/index.js
- packages/ui-library/src/components/radio-group/stories.js
- packages/ui-library/src/components/select-field/index.js
- packages/ui-library/src/components/select-field/stories.js
- packages/ui-library/src/components/text-field/index.js
- packages/ui-library/src/components/text-field/stories.js
- packages/ui-library/src/components/textarea-field/index.js
- packages/ui-library/src/components/textarea-field/stories.js
- packages/ui-library/src/components/toggle-field/index.js
- packages/ui-library/src/components/toggle-field/stories.js
- packages/ui-library/src/elements/checkbox/index.js
- packages/ui-library/src/elements/radio/index.js
* [UI-Library] Makes sure that users of a screenreader don't potentially miss context on certain Input elements
All Form field elements should have a Label for screen reader users. This PR ensures that by making the Label required on those Components.
* [@yoast/ui-library] All Form field elements should have a label for screen reader users. The `label` prop is now required.
*
* Open the UI Library Storybook
* Verify the following for all Form elements
* The Label is required (red asterisk in the Factory)
* Alle examples have a Label
*
*
Fixes …
> P1 1270 no label formfield a11y

- src/actions/importing/aioseo/aioseo-posts-importing-action.php
- src/services/importing/aioseo/aioseo-social-images-provider-service.php
* As per discussion with @jrfnl , dynamic properties are being deprecated in PHP 8.2, so we want to fix two of those within the AIOSEO importer.
* Fixes a deprecation warning in PHP 8.2 that would be shown on AIOSEO imports
* Have AIOSEO active and Yoast deactivated
* Go to create a new post.
* For the new post, upload an image in its content and also go to the AIOSEO metabox->Social->Facebook->Image Source and select `Attached Image`. Also add a featured image.
* Save the post
* Go to Yoast SEO tools->Import/Export and perform an AIOSEO import
* Check the created post and confirm that the FB image got imported successfully. That is, the FB image for Yoast is the attached image, *not* the featured image
* Go to the db, in the …
> DUPP-348 AIOSEO Importer: bug fix - typo in property name

- composer.lock
* A one-line WordProof SDK change to remove a leftover log function.
* Removes a log function that would prevent the saving of WordProof settings in some cases.
* Update the SDK
* Authenticate with WordProof
* Timestamp a page
* The certificate link should only contain the shield.
* Update the certificate link text (WordProof Settings -> Go to My WordProof -> Change the text and press save)
* Check if this text is used on the timestamped privacy page for the certificate link.
* Setting WordProof settings
Fixes #
> WordProof: removes unnecessary log function

- config/dependency-injection/custom-loader.php
* To be ready for PHP 8, we need to make sure overloaded child methods have the same signature as parent methods.
* Changes parameters names of overloaded methods in the dependency injection folder to match the parent class.
* Needed for PHP 8 compatibility.
* Since this is a very vital piece of code for the plugin it may be best to have someone knowledgeable about the dependency injection container check this code.
* As far as I can tell the way to test this is by simply running composer install and seeing whether the plugin builds properly.
* QA cannot test this, as I am pretty sure an RC cannot be build when these classes …
> Use identical method parameters as parent in dependency injection folder

- packages/js/src/workouts/tailwind-components/base/combo-box.js
- packages/js/src/workouts/tailwind-components/base/spinner.js
- packages/js/src/workouts/tailwind-components/helpers/index.js
- packages/js/src/workouts/tailwind-components/steps/site-representation/user-selector.js
* User selection is actually async, so a loading state is a good way to signal that data is being fetched
* Adds a loading state to the combobox to display a spinner while data is being fetched.
* N/A
* Go to the site representation step.
* Set representation to person.
* Open the Name combobox.
* Start typing in the Name combobox.
* Notice the loading spinner.
* Try to break?
*
*
Fixes DUPP-332
> Add loading state to the ComboBox

- inc/class-wpseo-shortlinker.php
- inc/options/class-wpseo-options.php
- src/helpers/options-helper.php
- src/services/options/abstract-options-service.php
- src/services/options/site-options-service.php
- tests/integration/inc/options/test-class-wpseo-options.php
- tests/integration/ryte/test-class-ryte.php
- tests/unit/TestCase.php
- tests/unit/admin/admin-features-test.php
- tests/unit/admin/metabox/metabox-test.php
- tests/unit/admin/tracking/tracking-test.php
- tests/unit/admin/views/feature-toggles-test.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/helpers/options-helper-test.php
- tests/unit/inc/language-utils-test.php
- tests/unit/inc/options/options-test.php
- tests/unit/inc/sitemaps/sitemaps-admin-test.php
- tests/unit/integrations/admin/migration-error-integration-test.php
- tests/unit/presenters/admin/migration-error-presenter-test.php
- tests/unit/services/options/site-options-service-test.php
* Use the options service in our `WPSEO_Options` class.
* Calls the options service via the options helper.
*
*
* Please test the whole feature instead of only this PR.
*
Fixes https://yoast.atlassian.net/browse/P1-1157
> P1-1157 create options helper class on top of single site and multisite options classes

- inc/sitemaps/class-author-sitemap-provider.php
- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-sitemaps.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
- tests/integration/sitemaps/test-class-wpseo-author-sitemap-provider.php
- tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
- tests/integration/sitemaps/test-class-wpseo-taxonomy-sitemap-provider.php
* Makes our sitemap numbering consistent.
* Fixes an issue where sitemap locations would change once the number of entries exceeded that of the first page.
* Set your number of posts for your sitemap suitably low using the `wpseo_sitemap_entries_per_page` filter:
```
add_filter( 'wpseo_sitemap_entries_per_page', function () { return 10; } );
```
* Go to your sitemap index.
* The first sitemap entry for each content type should not have a number.
* If you visit, for example, /post-sitemap1.xml, you should be redirect to the sitemap without a number.
* See the issue for full details.
* …
> Fix sitemap numbering and redirect wrongly numbered sitemaps

- src/config/wincher-pkce-provider.php
* Prevent a fatal error that could occur on PHP8 when the Wincher API:s returns unexpected responses.
* Fixes a bug where array_key_exists could throw a fatal error on PHP8.  
* 
Testing this is a bit convoluted because you need to trigger a non-json error response. An example of how to do this:
* Install WordPress and Yoast on PHP8
* Enable Wincher integration and connect
* Apply this diff:
```diff
diff --git a/src/actions/wincher/wincher-keyphrases-action.php b/src/actions/wincher/wincher-keyphrases-action.php
index 3345e25e3a..ccafe4ff70 100644
--- a/src/actions/wincher/wincher-keyphrases-action.php
+++ b/src/actions/wincher/wincher-keyphrases-action.php
@@ -207,17 …
```
> Fix potential fatal error from array_key_exists on PHP8

- src/surfaces/meta-surface.php
- tests/unit/surfaces/meta-surface-test.php
* Workshop PHP 8.1 compatibility 2022-02-24
* Written together with @jrfnl 
* Avoids array key warnings in empty array and non-array returns from wp_parse_url.
* Technically this is not the issue with null return values being passed on (since here wp_parse_url will only ever return an array or "false", however, I think the mixed return type of wp_parse_url warrants some defensive coding.
* Tests should run.
* I couldn't find an implementation for this for_url function, I guess because it is split up with call_user_func. It is potentially used in the indexables get_head function, so that should still work as expected.
*
This PR …
> PHP >= 8 Avoid array key warnings in meta-surface and add test

- packages/js/src/redux/selectors/WincherSEOPerformance.js
* Since the Wincher API canonicalizes keyphrases before it stores them, we could sometimes get into a situation where a keyphrase would show up twice in the table if it contained certain special characters. This aims to fix that problem.
* Fixes a bug where keyphrases could show up multiple times in Wincher table.
*
1. Activate Wincher integration.
2. Create new post with focus keyphrase `test: """"keyphrase""""          `.
3. Activate tracking for the keyphrase
4. Ensure that keyphrase only shows up once.
*
*
Fixes #
> Wincher: canonicalize keyphrases to prevent duplicates in table

- src/config/wincher-client.php
Currently the connection flow relies on setting a cookie in order to store the PKCE-code needed to exchange the code for a token. This seems to fail on certain installation that are behind a misconfigured cache (for instance Cloudflare). Cloudflare seems to strip the Set-Cookie header and cache the response to /authorization-url if the caching settings are too aggressive.
This PR aims to fix this problem by storing the PKCE  code as a transient in the DB instead.
* Fixes a bug where the Wincher connection flow would fail on certain installations.
* Use set_transient instead of setcookie.
* Make sure you have deleted all the cookies for the test website
* Ensure that …
> Wincher: store PKCE code as transient instead of cookie

- packages/js/src/classic-editor/replacement-variables/configurations.js
- packages/js/tests/classic-editor/replacement-variables/configurations.test.js
* When all tags are removed from a post, they are still shown in the snippet editor preview. This was caused by the fact that the tag replacement variable is retrieved from `wpseoScriptData` object when the tags value in `@yoast/seo` store is empty. 
* Removes unnecessary fallback value for the tag replacement variable.
* It turns out that assigning a fallback value for when the data for tags in `@yoast/seo` is empty is unnecessary. The store already reflect the correct situation of when the tags are assigned or removed in the post.
* Create a post and save it
**Test with tags created from inside the Post**
* Add `%tag%` variable in …
> Remove the unnecessary fallback value for tag replace var

- src/services/health-check/curl-runner.php
- src/services/health-check/myyoast-api-request-factory.php
- tests/unit/services/health-check/curl-runner-test.php
- tests/unit/services/health-check/myyoast-api-request-factory-test.php
* This prevents a deprecation warning of Symfony that mentions case sensitive services coming up.
* Fixes an unreleased deprecation warning trigger by renaming `MyYoast_API_Request_Factory` to `MyYoast_Api_Request_Factory` (as well as the test), notice the capitalization of `API`.
*
* Have a development build of this PR (or `release/18.5` branch after merge)
* Ensure you have Query Monitor active
* Go to the plugins page
* Deactivate Yoast SEO
* Activate Yoast SEO
* Notice the following PHP Error in Query Monitor is no longer present:
```
Service identifiers will be made case sensitive in Symfony 4.0. Using "Yoast\WP\SEO\Services\Health_Check\MyYoast_Api_Request_Factory" …
```
> Rename MyYoast_API_Request_Factory to MyYoast_Api_Request_Factory

- packages/yoastseo/src/helpers/shortlinker/singleton.js
* When using WooCommerce SEO we load in the `packages/yoastseo/src/helpers/shortlinker/singleton.js` file twice, once in WordPress SEO and once in WooCommerce SEO. This currently resets the globally defined shortlinker to `null` on the second file load. This PR prevents this reset when the global shortlinker is already defined.
* [wpseo-woocommerce] Fixes a bug where no telemetry parameters were added to the links in the SEO and Readability analysis results on product pages. 
*
* Within WooCommerce SEO, go to `trunk` and require this branch of WordPress SEO using Composer: 
```
composer require --dev yoast/wordpress-seo …
```
> Make sure that the global shortlinker is not overwritten if it has already been defined.

- src/generators/schema/third-party/events-calendar-schema.php
* We want the Schema piece for a single Event (with Events Calendar) to reference the already existing `ImageObject` for the featured image.
* Fixes an unreleased bug where the Schema piece for a single Event when using The Events Calendar would not reference the ImageObject for featured image in the correct way.
*
* Install and activate The Events Calendar
* create an event and set a featured image for it
* inspect the Schema:
* without this patch, the `Event` piece would have a `image` property with `@id` set to e.g. `http://basic.wordpress.test/event/altro-evento/#primaryimage`, without any hash
* with this patch, the `Event` piece would have a `image` property with …
> Add the URL hash to the primary image ID in the schema piece for a single event

- src/context/meta-tags-context.php
- src/generators/schema/article.php
- src/generators/schema/main-image.php
- src/generators/schema/webpage.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/generators/schema/article-test.php
- tests/unit/generators/schema/webpage-test.php
* Reverts https://github.com/Yoast/wordpress-seo/pull/18286
* Reverts the no-feature-image-in-post bug fix for https://github.com/Yoast/wordpress-seo/pull/18286
*
* N/A
* We will perform Acceptance Test when the last revert of the CoAuthor Plus integration is to be merged
*
* 
* [] I have tested this code to the best of my abilities
Fixes #
> Revert "Issues with new Image schema, when post has no featured image but has a resized image in its content"

- composer.json
- inc/class-upgrade.php
- inc/options/class-wpseo-option-ms.php
- src/helpers/wincher-helper.php
- src/integrations/third-party/wincher.php
- tests/unit/helpers/wincher-helper-test.php
- tests/unit/integrations/third-party/wincher-test.php
* The Wincher integration is not available on multisite. The integrations (tab) on Yoast SEO didn’t show the Wincher toggle and that made it very confusing.
* Adds a disabled Wincher integration toggle to the Network admin/Multisite `integrations` tab.
* Added a `upgrade routine` to set the Wincher toggle to 'Disable/Off' on Multisites/Network admin
* Else it was possible that the toggle was disabled and still showed 'Allow Control/On'
* Testing using a multisite:
* Click on `SEO -> General`  in the WordPress sidebar
* Navigate to the `Integrations` tab
* Verify the `Wincher integration` toggle is disabled and has the value 'Off'
* Verify the copy reads: `Currently, the …
> P1-1282 - improve wincher integration on multisite

- packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
*
* Adds a spec file for `getLanguagesWithWordFormSupport.js`.
*
* Run yarn test inside the `yoastseo` package and make sure that everything passes
*
Fixes [#LINGO-744](https://yoast.atlassian.net/browse/LINGO-744?atlOrigin=eyJpIjoiNTAwMTliOGIxN2Y3NGZjNzgwYTc5YjhhZDNlYTdiMjYiLCJwIjoiaiJ9)
> Add a spec file for getLanguagesWithWordFormSupport

- inc/options/class-wpseo-taxonomy-meta.php
- src/exceptions/option/delete-failed-exception.php
- src/exceptions/option/method-unimplemented-exception.php
- src/exceptions/option/save-failed-exception.php
- src/exceptions/option/term-not-found-exception.php
- src/exceptions/option/unknown-exception.php
- src/helpers/options-helper.php
- src/services/options/abstract-options-service.php
- src/services/options/site-options-service.php
- src/services/options/taxonomy-metadata-service.php
- tests/unit/actions/importing/aioseo-cleanup-action-test.php
- tests/unit/exceptions/importing/aioseo-validation-exception-test.php
- tests/unit/helpers/options-helper-test.php
- tests/unit/services/options/site-options-service-test.php
- tests/unit/services/options/taxonomy-metadata-service-test.php
* Support taxonomy metadata.
* Adds Taxonomy_Metadata_Service, which replaces the WPSEO_Taxonomy_Meta options class.
* Have a separate service for the taxonomy metadata. This one won't be going through the options helper because the interface requires the term and taxonomy to be passed too. And the old one was called directly already anyway, so no loss there.
* Only changed the functions in the old class that are used in our plugins:
* get_term_meta -> get
* set_values -> set_options
* set_value -> set
* inside get_keyword_usage: get_tax_meta -> get_options
* I did not deprecate the other methods of the WPSEO_Taxonomy_Meta class. Should I? 
* Both the old class and the …
> P1-1207 support taxonomy metadata

- inc/options/class-wpseo-option-wpseo.php
- src/actions/configuration/first-time-configuration-action.php
- src/routes/first-time-configuration-route.php
- tests/unit/actions/configuration/first-time-configuration-action-test.php
- tests/unit/routes/first-time-configuration-route-test.php
* The first time configuration stepper needs to be moved outside the workouts tab, so routes need to be updated
* Updates routes for the first time configuration and adds actions to save/retrieve configuration state
*
* Install (if you don't have it installed already) and activate [JSON API Auth](https://wordpress.org/plugins/json-api-auth/) plugin
* Send a REST request as follows: 
`http://basic.wordpress.test/wp-json/yoast/v1/configuration/save_configuration_state`
With JSON body:
```
{
"finishedSteps": ["step1", "step2"],
"indexablesBySteps": [],
"priority": 10
}
```
* Verify the response body is as follows:
```
{
"success": true,
"status": 200
}
```
* In the database, …
> Dupp 366 update create routes

- admin/views/tabs/tool/import-seo.php
* Minor copy change to accommodate for the moving of the first time configuration from `Workouts` to `General` page
* Changed copy in step 4 of the importer to reflect the moving of the first time configuration form `Workouts` to `General` page 
*
* Install and activate another SEO plug-in (for which we have foreseen an importing procedure, e.g. AIOSEO).
* Visit `Tools` -> `Import and Export` and click on `Import from other SEO plugins` tab.
* Verify Step 4 copy is as follows:
* Verify the link opens on the `First time configuration` tab in the `General` page.
* …
> Dupp 271 change copy in step 4 of the importer

- src/integrations/third-party/wincher.php
- tests/unit/integrations/third-party/wincher-test.php
* This PR removes the Wincher output from the unit test summary.
* Removes unwanted output from the test summary.
*
* Run `composer test -- --filter Wincher_Test`
* Verify no unwanted output is visible in the test summary
Before:
After:
*
*
Fixes #
> Removes Wincher output from unit test summary

- packages/js/src/classic-editor/components/google-preview.js
* The Google preview snippet was not opened by default in the agnostic analysis feature branch, while it is opened automatically on `trunk`. This issue was found when running the automated tests.
* Opens the Google preview snippet by default.
* None
* Activate the Classic Editor plug-in.
* Confirm that the Google preview snippet is open by default (there is no "Edit snippet" button as shown in the first screenshot of [LINGO-1430](https://yoast.atlassian.net/browse/LINGO-1430), but there is rather an editing pane as shown in the second screenshot)
* Repeat above two steps for a page and a category. …
> LINGO-1430 Google preview snippet should open by default

- packages/ui-library/package.json
- packages/ui-library/src/components/checkbox-group/index.js
- packages/ui-library/src/components/checkbox-group/stories.js
- packages/ui-library/src/components/radio-group/index.js
- packages/ui-library/src/components/radio-group/stories.js
- packages/ui-library/src/components/select-field/index.js
- packages/ui-library/src/components/select-field/stories.js
- packages/ui-library/src/components/text-field/index.js
- packages/ui-library/src/components/text-field/stories.js
- packages/ui-library/src/components/textarea-field/index.js
- packages/ui-library/src/components/textarea-field/stories.js
- packages/ui-library/src/components/toggle-field/index.js
- packages/ui-library/src/components/toggle-field/stories.js
- packages/ui-library/src/elements/checkbox/index.js
- packages/ui-library/src/elements/checkbox/stories.js
- packages/ui-library/src/elements/label/index.js
- packages/ui-library/src/elements/label/stories.js
- packages/ui-library/src/elements/radio/index.js
- packages/ui-library/src/elements/radio/stories.js
- packages/ui-library/src/elements/radio/style.css
- yarn.lock
* For a11y, the labels should _only_ contain text.
* [@yoast/ui-library] Refactors Label to be a string, instead of a node, for a11y.
* Any extra elements within a label should be moved outside the label for a11y
* To enforce this this commit changes the types to string and makes it a prop (instead of children in the label itself). I think this reduces the risk of people adding more than a string in their labels, which would then result in React warnings.
* The Radio element' check has moved outside of the label now
* Start the storybook: `cd package/ui-library && yarn storybook`
* Verify the stories look correct still. Specifically the elements: label, checkbox and …
> Refactor labels be strings

- packages/js/src/classic-editor/components/google-preview.js
- packages/js/tests/classic-editor/components/google-preview.test.js
*
* Adds the `"metabox"` suffix to the IDs of the Google Preview elements for the classic editor agnostic analysis integration.
*
* Create a new post or open an existing one in the classic editor.
* In the classic editor, open the page source.
* E.g. open the developer tools.
* The source code should contain an HTML-element with an id of `"yoast-google-preview-description-metabox".
*
* 
Fixes #
> Id of the google preview should be yoast google preview description metabox

- packages/seo-integration/src/index.js
- packages/seo-integration/src/social/containers/twitter-container.js
- packages/seo-integration/tests/social/containers/facebook-container.test.js
- packages/seo-integration/tests/social/containers/twitter-container.test.js
* This PR provides a Container for the Twitter editor. It will be used in a later PR to connect the Twitter data (title, image, description) from the agnostic analysis SEO store, to the Twitter editor form in the metabox.
* [seo-integration] Adds Twitter editor container.
* None
**Note**: This container is not used yet in the code, so it cannot yet be acceptance tested. It will be tested in the PR that implements [LINGO-1389](https://yoast.atlassian.net/browse/LINGO-1389), since that combines this code and other code into a feature that can be tested.
What you can do:
* Check that the unit tests pass.
* Check that the unit tests cover 100% of the lines of the newly added …
> LINGO-1362 add a twitter editor container to the seo-integration package

- src/integrations/third-party/coauthors-plus.php
* We don't want to add a `Person` object in the schema, unless we're in a post that is an Article Type
* Fixes an unreleased bug where a `Person` object would be added in the schema in posts that are not `Article`s
* At present time, if the article type is set to `None`, no author is inserted into the schema. As per [specifications](https://developer.yoast.com/features/schema/pieces/article/#failure-scenarios), this behaviour should be corrected to add authors to the `WebPage` piece instead.
* Install and activate The Events Calendar plugin
* Install and activate Co-Authors Plus plugin 
* Set site to represent the Organisation (set name and logo)
* Create an event with …
> Don't add a person object if the post is not an article type

- packages/js/src/workouts/components/ConfigurationWorkout.js
- packages/js/src/workouts/tailwind-components/base/single-select.js
- packages/js/src/workouts/tailwind-components/steps/site-representation/site-representation-step.js
* When Local SEO is activated, we want to force-select `Organization` as entity the site represents
* Forces `Organization` in the Social Representation step of the first time configuration when Local SEO is activated
* N/A
* Install and activate WPSEO Local
* Go to the first time configuration and navigate to the `Site representation` step
* Verify that:
* An alert is shown as follows:
*  The select below `Does your site represent an Organization or Person?` is greyed-out and disabled
* The pre-selected value in the select is `organization`
* `Organization name` and `Organization logo` are editable
* Deactivate WPSEO Local
* Go to the first time configuration and …
> Dupp 403 if local seo then organization selected

- inc/class-wpseo-utils.php
- wp-seo-main.php
* Automattic is experiencing  timeout issues related to how we empty the `rewrite_rules` option, which causes a race condition when using persistence object caching
* Fixes a bug that would lead to race conditions when using persistent object caching.
* Instead of deleting the `rewrite_rules` option and then recreate and fill it, we use `update_option` and pass an empty string as value. 
*  There are 3 scenarios where `rewrite_rules` option is being emptied:
1. In a multisite wp installation, when network-activating wpseo
2. In a multisite wp installation, when network-deactivating wpseo
3. Every time an option is being updated
_Scenario 1_
* Start with a fresh wp …
> Dupp 413 fix rewrite_rules performance problem

- src/helpers/options-helper.php
- src/integrations/admin/social-profiles-helper.php
- tests/unit/integrations/admin/social-profiles-helper-test.php
* We want to allow the user to save an empty string in some of the Other Social URLs and when that happens we delete those entries/fields in the back-end.
* We also want to allow users to delete their previously saved Facebook and Twitter values, as we didn't before
* Allow the user to save an empty string in some of the Other Social URLs
* Fix an unreleased bug, where deleting a previously saved Facebook or Twitter value would not be saved in the db.
*
For the `Allow the user to save an empty string in some of the Other Social URLs`  part:
* Set Organization and move to the SOCIAL PROFILES step
* Add a couple of `Other social profile` fields
* If even one of them fields …
> Let empty Other Social URLs pass validation and dont save them

- inc/class-upgrade.php
*
* Performs the upgrade routine on 18.8 to transfer the Social URLs in the format that the new First Time Configuration expects
*
* With trunk (or the 18.7 version if you're in QA), set up Organization and go to SEO->Social
* Add a couple of URLs there.
* Checkout this branch (or install the 18.8 RC if you're in QA)
* Via the Test Helper, perform the 18.8. upgrade by going to Tools->Yoast test, set as DB version for Yoast SEO, a version lower than what the current RC/PR is on. So, if we're on 18.7, set 18.6 there.
* Go to SEO->General->First-Time configuration
* Confirm that the URLs you added while on trunk (or the 18.7 version if you're in QA) have been transferred and …
> Dupp 326 correct version in upgrade routine

- src/conditionals/third-party/coauthors-plus-flag-conditional.php
- src/integrations/third-party/coauthors-plus.php
* We want to put the CoAuthors Plus integration behind a feature flag.
**NOTE: when and if this is merged, please update #18331 to make it non-user-facing. **
* Adds a feature flag for the CoAuthors Plus integration.
*
* add `define( 'YOAST_SEO_COAUTHORS_PLUS', true );` to your `wp-config.php`
* enable the CoAuthors Plus plugin
* repeat all the tests from https://github.com/Yoast/wordpress-seo/pull/18331, nothing should behave differently
* remove `define( 'YOAST_SEO_COAUTHORS_PLUS', true );` to your `wp-config.php`
* enable the CoAuthors Plus plugin
* repeat tests from https://github.com/Yoast/wordpress-seo/pull/18331:
* Test 2 and 4 should still be valid
* In Tests 1 …
> Add feature flag for the CoAuthors Plus integration.

- packages/js/src/classic-editor/initial-state.js
- packages/js/tests/classic-editor/initial-state.test.js
* On trunk, the term keyphrase is automatically set to the term title before another keyphrase is set.
* Sets the term keyphrase to the term title if no other keyphrase has been set.
* The fallback value was not included in the test in in `initial-state-test.js` because the test mocks what `getTermFocusKeyphrase` returns 
* Make sure you have the Classic Editor enabled
* Create a new tag
* Open the editor to edit the tag
* Confirm that the focus keyphrase is set to the name of the tag
* Set another keyphrase, save and exit the editor
* Open the tag again and confirm that the keyphrase is set to the one that you had entered
* Repeat the same steps for a category and a …
> Set term keyphrase to its title if no keyphrase is set

- packages/js/src/first-time-configuration/tailwind-components/helpers/index.js
- packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-field-array.js
- packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-input-person-section.js
- packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-input-section.js
* After QA preliminary testing, a series of enhancements and bug fixes are being made to the first time configuration before shipping it
* Adds placeholders to social URLs input fields
* N/A
* Navigate to the first time configuration and reach the `Personal Preferences` step
* Select your site to represent a person, then click `Save and continue`
* Verify that each input field has a placeholder accordingly to the social medium it represents
* * Navigate back to the `Personal Preferences` step
* Select your site to represent an organization, then click `Save and continue`
* Verify that both the Facebook and Twitter input fields have a placeholder accordingly to the social …
> Dupp 416 ftc there are no placeholders for social profile fields and other social profiles

- inc/sitemaps/class-sitemap-image-parser.php
- inc/sitemaps/class-sitemaps-renderer.php
- tests/integration/sitemaps/test-class-wpseo-sitemap-image-parser.php
- tests/integration/sitemaps/test-class-wpseo-sitemaps-renderer.php
* Remove XML sitemap image properties `title` and `caption` as Google has deprecated them.
* Create a post with a thumbnail image, an image gallery, and a single image in the post content. Make sure all have an alt text and/or a title.
* Open the xml sitemap source (cmd+option+U in chrome) and find your post.
* See that `<image:title>` and `<image:caption>` no longer appear in XML sitemaps.
* Install WooCommerce SEO 14.7 or trunk
* Create a product with a product image gallery with images with an alt text and title.
* Open the products sitemaps and see that the product images.
* See that the `<image:title>` and `<image:caption>` no longer appear in XML sitemaps for all …
> Remove deprecated properties and attributes

- packages/js/src/structured-data-blocks/faq/components/Question.js
- packages/js/src/structured-data-blocks/how-to/components/HowTo.js
- packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
*
* Fixes a bug where our How To and FAQ blocks would not handle focus correctly when using WordPress 6.0.
*
* Set up a clean environment with WP 6.0 Beta version (Default editor)
* To change to WP 6.0, change the update channel to Bleeding edge / Nightlies (under Tools -> Beta testing) and update WP
* Install and activate the code of this PR
* Add How-To or FAQ block
* At How-To block add a description
* By mouse-click try to navigate to Enter a step title or Enter a step description (see issue)
*
*
Fixes …
> Change RichText to use onFocus instead of unstableOnFocus

- packages/js/src/structured-data-blocks/faq/components/Question.js
- packages/js/src/structured-data-blocks/how-to/components/HowTo.js
- packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
* Fix https://github.com/Yoast/wordpress-seo/pull/18386
* Fixes an unreleased bug where the controls of the How-To and FAQ blocks were not showing.
* Gutenberg forces a focus event when a RichText is unfocused. By removing the `isSelected` this no longer happens. Most likely this is due to our focus state being out of sync with those events.
* Set up a clean environment with WP 6.0 Beta version (Default editor)
* To change to WP 6.0, change the update channel to Bleeding edge / Nightlies (under Tools -> Beta testing) and update WP
* Install and activate the code of this PR
* Add How-To block and add a description
* By mouse-click try to navigate to …
> P1-1359 fix faq and how to block controls

- admin/class-config.php
- admin/views/tabs/social/accounts.php
- css/src/tailwind.css
- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/base/combo-box.js
- packages/js/src/first-time-configuration/tailwind-components/base/image-select.js
- packages/js/src/first-time-configuration/tailwind-components/base/single-select.js
- packages/js/src/first-time-configuration/tailwind-components/base/text-input.js
- packages/js/src/first-time-configuration/tailwind-components/step-header.js
- packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-input-section.js
- packages/js/src/initializers/social-settings.js
*
* Updates the look of the Accounts tab in the Social menu.
* Also fixes various (unreleased) bugs and debts:
* Submitting with Enter in the _other_ tabs of "general" and "social" is available again.
* Submitting e.g. the Pinterest field would delete the facebook_site, twitter_username and other_social_urls values. ⚠️ this could have been a serious bug, but we caught it on time.
*	* Submitting e.g. the Pinterest field when person was selected would still delete the facebook_site, twitter_username and other_social_urls values for organization. ⚠️ this could have been a serious bug, but we caught it on time.
* Text and placeholder color now conforms with the design everywhere.
* If you set Site representation to person, but dont …
> Add component, styling, and rudimentary state

- src/integrations/admin/social-profiles-helper.php
* 
* Adds extra sanitization in the Social Profiles endpoint
*
* Go to the FTC
* Select Person 
* Add `https://dfd.dsf</script><script>alert(document.domain)</script><script>` in one of the Social Profiles there and Save
* Refresh the page and go to the Social Profiles step again, to check what has been saved in the db.
With this PR/RC:
* The malicious part of the url has been stripped and only `https://dfd.dsf` has been left there.
With the previous RC:
* The malicious part would not have been stripped and `https://dfd.dsf</script><script>alert(document.domain)</script><script>` would have been inserted in the db
We also improved the UX for when saving malicious urls in …
> Adds extra sanitization in the Social Profiles endpoint

- inc/class-upgrade.php
- src/actions/configuration/first-time-configuration-action.php
- tests/unit/actions/configuration/first-time-configuration-action-test.php
* We want to show the FTC as completed if the user had completed the 2 first steps of the Configuration Workout (SEO optimization and Site Representation)
* Transfers progress from the old configuration workout upon upgrading to the new plugin version
*
* Checkout master (or use the 18.8 version if on RC)
* Complete the first 2 steps of the Configuration Workout
* Checkout this PR (or install the current RC)
* [Run the upgrade routine by going into the Test Helper and putting 18.8 in the DB version and hitting Save] _(note by @enricobattocchi: I don't think it's needed, the upgrade routine should already run by itself)_
* Go to the dashboard and confirm that you don't get …
> Run upgrade routine to transfer progress of the configuration workout

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/initializers/admin.js
* We use javascript to dynamically change values, but the PHP values in other tabs did not get refreshed. This is hard to do without a reload, but we can at least change the enable tracking and remove the notice. Also, we still reload when swapping tabs after the stepper is finished.
* Fixes an unreleased bug where the First-time Configuration notification would still be shown after finished the configuration.
* Fixes an unreleased bug where the Usage tracking radio button on the features tab would not be updated after editing  the tracking in the First-time configuration.
* Fixes a bug where pressing back and forward in the browser after switching tabs on the General page would not change tabs.
* These changes are suboptimal, …
> Keep PHP and JavaScript data aligned as much as possible

- packages/babel-preset/package.json
- packages/jest-preset/package.json
- packages/postcss-preset/package.json
* Move `devDependencies` to `dependencies` for tooling preset packages so that they get installed when installing the preset packages.
* [@yoast/babel-preset] Move `devDependencies` to `dependencies`.
* [@yoast/jest-preset] Move `devDependencies` to `dependencies`.
* [@yoast/postcss-preset] Move `devDependencies` to `dependencies`.
*
* Create a dummy NPM module locally (run `mkdir test && cd test && yarn init`) and complete the setup wizard.
* Install `@yoast/babel-preset`, `@yoast/jest-preset` and `@yoast/postcss-preset` and verify that all dependencies of these packages are also installed in the `node_modules` folder.
*
This …
> Move dev deps to deps for tooling packages

- css/src/tailwind.css
- packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation.js
- packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/personal-preferences-step.js
- packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-field-array.js
- packages/js/src/initializers/social-settings.js
* Some minor UX changes were needed, we bundled them in this PR
* Performs minor UX enhancements to the unreleased First time configuration
*
* Confirm that:
* Heading is now dark gray in Accounts tab (for Person and Organization)
* Button label becomes “Add another profile” in Accounts tab and FTC
* “This feature includes and replaces the Text Link Counter and Internal Linking Analysis” Alert moved to bottom of step
* Non-production environment Alert gets a top margin (this one is visible in Local by Flywheel, not in Rancher afaik - or you can add `define('WP_ENVIRONMENT_TYPE', 'development');` in the wp-config.php file of your setup and re-start it)
* If the the …
> Dupp 486 ux fixes to ftc

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/personal-preferences-step.js
* Some of the values that can be edited in the first-time configuration can be edited also in another parts of the plug-in: we want to keep the values of those variable aligned
* Fixes an unreleased bug which prevents keeping aligned the `Usage tracking` option value between the first-time configuration and the Features tab
* N/A
* Start with a freshly-installed Yoast SEO instance
* Navigate to `General` -> `First-time configuration tab` -> `Personal preferences` step
* Toggle the radio button to `Yes, you can track my site data` and click on `Save and Continue`
* Switch to the `Features` tab and verify the `Usage tracking` radio button is set to `on`
* Toggle it to `off` …
> Dupp 487 ftc usage tracking not aligned between ftc tab and features tab

- admin/class-config.php
- packages/js/src/initializers/social-settings.js
*
* Hides the `Site represents an Organization` text in the Social page when Local SEO is enabled
*
* When Local is not installed, and the site represents an Organization, going into the Yoast SEO->Social page, the `Your website is currently configured to represent an Organization, .... ` text should appear likeso:
* When Local is installed, the `Your website is currently configured to represent an Organization, .... ` text should NOT appear there, likeso:
* When Local is not installed, and the site represents a person, going into the Yoast SEO->Social page, the `Your website is currently configured to represent a Person, .... ` text should appear likeso: …
> When local is enabled, hide text in Social page

- packages/js/src/first-time-configuration.js
- src/integrations/admin/first-time-configuration-integration.php
* We want to avoid throwing a console error in the SEO dashboard page when on the network admin
* Fixes an unreleased bug where a console error would appear in the network admin.
*
* Go to the http://multisite.wordpress.test/wp-admin/network/admin.php?page=wpseo_dashboard page of a multisite setup
* We would have gotten a `Uncaught Error: Target container is not a DOM element` console error
With this PR:
* We dont get that console error
* Go to the SEO->Dashboard page of a subsite in a multisite setup and smoke test that the FTC tab appears there with the normal UX
* Go to …
> Dupp 490 error in network admin

- packages/js/src/installation-success.js
* The mobile version of the _installation successful_ page does not render correctly the `Skip` anchor
* Fixes the placement of the `Skip` anchor in mobile view
*
* Install and activate Yoast SEO: you will be redirected to the _Installation successful_ page (if you have it already installed and activated visit the  page directly, e.g. http://basic.wordpress.test/wp-admin/admin.php?page=wpseo_installation_successful_free
* In the browser's developer tools switch to the mobile view and verify the `Skip` anchor is right below the purple block:
*
* …
> Fix 'Skip' anchor placement in mobile view

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/helpers/index.js
- packages/js/src/initializers/social-settings.js
* Fixes an unreleased bug where error feedback in the social profiles step and social accounts tab would be misplaced upon deletion of another input.
*
* In the FTC have organization set and go to social profiles. Add 5 or so empty other social profiles, and in the 3rd and the last one enter a bad value (e.g. "bla"). Also enter bad values for facebook and twitter.
* Press save and continue.
* Errors should appear at all bad values.
* Edit Facebook. Only facebook error should disappear.
* Edit Twitter. Only Twitter error should disappear.
* Remove some of the empty other urls. The erroring inputs should have its error move along with it.
* Edit the last erroring other url. …
> Update error fields upon input actions

- inc/class-upgrade.php
* We want every user that upgrades into 18.9, to not be shown the new Installation Success page.
* We also want any old users that potentially deactivate/re-activate 18.9 to also not get the new Installation Success page.
* For that, we're adding two db entries upon upgrade to 18.9, that we check before the Installation Success page is shown.
* Hides the installation success page for old users upgrading into 18.9
* We're adding a hardcoded timestamp for `activation_redirect_timestamp_free` for users upgrading to 18.9.
* That way we will be able to know in the future if a user saw that Installation Success page or not. Maybe it won't ever be useful but maybe it will be.
* …
> Add an upgrade routine to help indentifying old users so that we don't show the Installation Success page then

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/initializers/admin.js
* Moving the First-time configuration inside a tab of the `General` section introduced the need to manage tabs switching when the current step is being edited. 
* Shows a confirmation modal pup-up when the user tries to switch tab and there are unsaved changes in the current step
* Please note the First-time configuration notice could keep popping up when you switch tabs until the page is refreshed. This is expected and will be fixed [in another PR](https://github.com/Yoast/wordpress-seo/pull/18419).
* Start with a freshly-installed Yoast SEO instance
* Navigate to `General` -> `First-time configuration` tab
* Click on Start SEO data optimization and switch tab before the …
> Dupp 465 modify modal pop up behaviour related to general panel tabs switching

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation-step.js
- src/integrations/admin/first-time-configuration-integration.php
*
* Updates links in the FTC SEO data optimization step
*
* In the 1st step of the FTC, check the link of the `Yoast SEO indexables squad` text. It should be `http://yoa.st/config-indexables?` plus the information about your setup:
* In the 1st step of the FTC, check the link of the `check out the benefits of the indexables squad` text. It should be `http://yoa.st/config-indexables-benefits?` plus the information about your setup:
* In the PERSONAL PREFERENCES step of the FTC, check the link of the `our privacy policy` text. It should be `https://yoa.st/gdpr-config-workout?` plus the …
> Updates shortlinks in the FTC SEO data optimization step

- packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/personal-preferences-step.js
- src/integrations/admin/first-time-configuration-integration.php
* We want to gray out the usage tracking step in the FTC when it's not allowed at network level, as it happens already in the features tab.
* Disables the usage tracking step in the FTC when it's not allowed at network level
* Note that _the "sending" part of the step is not disabled_. Prior to this PR, saving the step to set a choice of "yes" in a network where tracking is disabled would have resulted in a `500` error. In this case, instead, the value is always forced to be `No`, the request is sent but gets a `200`. I don't think it would worth the hassle to prevent that request, adding complexity.
* install on a multisite environment
* network activate the plugin
* …
> DUPP-496 Disable the usage tracking step in the FTC when it's not allowed at network level

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
* Removes an unreleased feature that would cause a reload upon finishing the First-time Configuration in order to refresh form data and implements an alternative.
* The reloading solution could not quickly be implemented in an elegant way, so instead we opted to manipulate the DOM using JS to fire corollary effects for the points of contact (covered by both FTC and general tab).
* The points of contact are:
* First Time Configuration notice
* SEO Optimization notification
* Usage tracking radio button.
* Using the test helper, reset indexables tables, and Configuration progress, and notifications.
* Go to Plugins and deactivate Yoast SEO. Then reactivate Yoast SEO.
* Go …
> Implement alternative to reloading for form-data refresh

- packages/js/src/initializers/admin.js
*
* Fixes an unreleased bug where a modal would show twice when switching tabs from the First-time Configuration, and would break the page on pressing cancel.
* Without this branch (or on master) replicate the bug:
* On FTC on Site representation step do some changes and navigate to Webmaster  Tools
* Click Cancel in the popup
Result: popup is shown one more time and is user clicks one more time Webmaster Tools tab is opened
and the page is broken:
• With this branch or RC: 
• verify that replication is no longer possible.
*
*
Fixes DUPP-501
> Prevent tab switch when clicking cancel

- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/user-selector.js
* in the `Site representation` step of the First-time configuration, toggling back and forth the select combobox outputs an error in the browser console
* Fixes an unreleased bug where switching back and forth the combobox in the Site representation steps causes an error to be displayed in the browser console
*
* Navigate to `General` -> `First-time configuration tab` -> `Site representation` step
* Open the browser's  console
* Toggle back and forth the select combobox labelled `Does your site represent an Organization or Person?`, selecting `Person` and `Organization` alternatively
* Verify no error appears in the console
* …
> Make sure component state is not accessed after unmounting

- packages/seo-store/src/analysis/slice/results.js
- packages/seo-store/tests/analysis/slice/results.test.js
*
* Fixes a bug in the classic editor agnostic analysis integration where the focus keyphrase forms were not highlighted inside of the Google preview desktop result.
* Since the results of a research are always set on the `result` key, I decided to add this path to the `getResearchResults` selector.
* Set a focus keyphrase.
* Add a meta description and add your focus keyphrase in the description.
* Inside Google Preview, preview the meta description in “Desktop result”.
* Confirm that the focus keyphrase is in bold in the preview.
* …
> LINGO 1459 - focus keyphrase is not previewed in bold in meta description preview desktop result

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
* We want to update sidebar notification count after indexation in the FTC
* Updates sidebar notification count after indexation in the FTC.
*
* Follow the instructions from https://github.com/Yoast/wordpress-seo/pull/18419 (namely the ones about the notification count) and check the the sidebar count is updated as well, not just the admin bar one.
*
*
Fixes [DUPP-498]
[DUPP-498]: https://yoast.atlassian.net/browse/DUPP-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DUPP-498 Update sidebar notification count after indexation in the FTC

- src/integrations/admin/workouts-integration.php
* Since there is no Free workout now, we want to add a `Premium` badge to the Workouts menu item.
* Adds a `Premium` badge to the Workout menu item.
*
* Check that you can see a `Premium` badge next to the Workouts menu item, both with just Free and Free+Premium
*
*
Fixes  [DUPP-504]
[DUPP-504]: https://yoast.atlassian.net/browse/DUPP-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DUPP-504 Add a `Premium` badge to the Workout menu item

- packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
- packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
- packages/yoastseo/spec/languageProcessing/helpers/sanitize/sanitizeStringSpec.js
- packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
- packages/yoastseo/spec/languageProcessing/helpers/word/getWordsSpec.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeString.js
- packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
- packages/yoastseo/src/languageProcessing/helpers/word/getWords.js
- packages/yoastseo/src/values/Paper.js
* Editing an existing post (created in Block editor) in Elementor, will lead to an analysis result discrepancy when exiting the Elementor editor.
* One of the reasons of the result discrepancy is the fact that in the above case, additional paragraph tags were added when exiting the Elementor editor. The tags were not properly sanitized inside the Paper at this point.
* Another potential problem is the fact that in some cases an `&nbsp;` tag is also added when editing in Elementor editor. The tag is sanitized when retrieving the sentences from the text, but not when retrieving the words.
* [yoastseo] Adds a step to unify all whitespaces and non-breaking spaces in `sanitizeString.js` helper.
* [yoastseo] Adds a step to unify …
> LINGO-1448 decrease analysis result discrepancy of Block and Elementor editor

- src/integrations/admin/old-configuration-integration.php
* We want to make sure that no 403 is thrown when a user tries to go to the old configuration wizard
* Fixes a bug where a 403 error page would be thrown when a user tried to access the old configuration wizard.
*
* Go to the http://basic.wordpress.test/wp-admin/?page=wpseo_configurator page (or http://multisite.wordpress.test/site2/wp-admin/admin.php?page=wpseo_dashboard#top#first-time-configuration for a subsite)
* Confirm that you are redirected to that site's new FTC
* Install and activate 17.6
* Open wizard but do nothing
* Install and activate 18.8 or 18.9-RC2
* Message regarding configuration wizard is displayed on the …
> Dupp 502 redirect to ftc

- packages/js/src/initializers/admin.js
* The modal pop-up related to tabs switching needs to be adjusted for more clarity
* Changes the copy of the modal pop-up shown when users want to change tab from the First-time configuration
*
* Navigate to `General` -> `First-time configuration tab` -> `Site representation` step
* Make some changes, don't save and try to switch to another tab
* Verify a modal pop-up is shown which reads: `There are unsaved changes in one or more steps. Leaving means that those changes may not be saved. Are you sure you want to leave?`
*
*
Fixes …
> Change tabs popup copy

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
* Translator comment malplacement.
* [non-user-facing] Fixed translator comment placement
* n/a
* n/a
* Nothing
> Fix translator comment placement

- packages/yoastseo/spec/languageProcessing/researches/altTagCountSpec.js
- packages/yoastseo/spec/languageProcessing/researches/countSentencesFromTextSpec.js
- packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
- packages/yoastseo/spec/languageProcessing/researches/findTransitionWordsSpec.js
- packages/yoastseo/spec/languageProcessing/researches/functionWordsInKeyphraseSpec.js
- packages/yoastseo/spec/languageProcessing/researches/getFleschReadingScoreSpec.js
- packages/yoastseo/spec/languageProcessing/researches/getKeywordDensitySpec.js
- packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
- packages/yoastseo/spec/languageProcessing/researches/getWordFormsSpec.js
- packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
- packages/yoastseo/spec/languageProcessing/researches/keyphraseLengthSpec.js
- packages/yoastseo/spec/languageProcessing/researches/keywordCountInUrlSpec.js
- packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
- packages/yoastseo/spec/languageProcessing/researches/matchKeywordInSubheadingsSpec.js
- packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
- packages/yoastseo/spec/languageProcessing/researches/metaDescriptionLengthSpec.js
- packages/yoastseo/spec/languageProcessing/researches/readingTimeSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/SentenceBeginningsAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/fleschReadingEaseAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/IntroductionKeywordAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInImageTextAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionKeywordAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/SubHeadingsKeywordAssessmentSpec.js
* We have a lot of language-specific unit tests for researches and assessments that are not necessary for unit-testing purposes. In this PR, we remove the tests that are deemed unnecessary. Additionally, there are tests that are unnecessary but nice to have, for the general purpose of having good test coverage for many languages. We want to move those tests to separate language-specific files. This will be done in a separate PR, but in this PR we mark those tests by commenting them out.
* [yoastseo] Removes unnecessary language-specific tests for assessments and researchers, and comments out unnecessary-but-nice-to-have language-specific tests (they will be moved to separate files in a separate PR).
*  Guidelines that were used …
> Remove unnecessary language specific tests

- packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
- packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
- packages/yoastseo/src/languageProcessing/researches/getSentenceBeginnings.js
* We want to exclude list items from the assessment that checks whether consecutive sentences begin with the same word(s), since items in lists often do (they enumerate things, for example).
* Fixes a bug where items in lists were not excluded for the readability assessment that checks whether consecutive sentences do not begin with the same words.
* [shopify-seo] Fixes a bug where items in lists were not excluded for the readability assessment that checks whether consecutive sentences do not begin with the same words in Collections, Posts and Pages.
*
* Add a list.
* Add items that start with the same words to the list.
* Check the results of the …
> LINGO-1487 - Exclude list items in the sentence beginnings assessment.

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
* In the First-time configuration the titles of the steps are not localized
* Add localization to the First-time configuration steps' titles
* N/A
* Navigate to `General` -> `First-time configuration tab`
* Verify each steps' title is properly localized (or displayed in english if the string is not translated to the current locale)
*
Fixes [DUPP-513](https://yoast.atlassian.net/browse/DUPP-513)
> Adds localization to steps titles

- src/actions/configuration/first-time-configuration-action.php
- tests/unit/actions/configuration/first-time-configuration-action-test.php
*
* Fixes a bug where the schema would not be updated with the new logo when the user changed it via the First Time Configuration
* We now deleted the cached `company_logo_meta` and `person_logo_meta` db entries that take precedent when on the frontend, whenever we save the Site Represents step in the First Time Configuratio.
* Which means that every time the Site Representation step is saved in the FTC, the next page load of the frontend will also produce again the cached `company_logo_meta` and `person_logo_meta` values.
* Go to the First Time Configuration's Site Representation step
* Select Organization and set a Organization Logo
* Visit the frontend
* Now go again …
> Delete cached logos from the db when Site Representation is stored

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/configuration-stepper-buttons.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
* When a network error (or another generic error) occurs when the user is in the Site Representation step of the First-time configuration, no notice is given to the user and s/he is still be able to advance to the next step
* Fixes a bug where an error in saving the Site representation step of the First-time configuration would not block the advancement to the next step.
* The management of this error exploits the already-existing _setErrorFields_ function by creating an array in which the first element is the string "site_representation", and the second element is the actual error message. This is sub-optimal and should be addressed by swapping the _setErrorFields_ function to a more general function allowing to manage all the …
> DUPP-510 - DUPP-510-handle-network-failure-in-ftc-site-representation-step

- admin/pages/redirects.php
- admin/views/redirects.php
- src/integrations/admin/redirects-integration.php
- tests/unit/integrations/admin/redirects-integration-test.php
* We want to add a Redirects page in Free with an Upsell to Premium
* Adds a Redirects page with an upsell to Premium.
* 
* install & activate this PR or the RC containing it
* make sure Premium is not active
* check that there is a `Redirects` menu item in the sidebar and it has a `Premium` badge
* visit the page and check it's according to this screenshot:
* Check that navigating with the `TAB` key skips all the form elements in the background
* Check that different screen sizes are handled well.
* Look at the upsell button link destination and see it contains the expected info (version number, etc.)
* Click on the button and see a new tab opens on the same page as the …
> DUPP-436 Add a Redirects with an upsell to Premium

- packages/js/package.json
- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/organization-section.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
*
* Fixes a bug in the First-time Configuration where saving an invalid organization name would fail without feedback.
*
* In the FTC, go to Site representation, select organization, and enter an invalid name (e.g. `<script>blablabla</script>`
* Press save.
* You should see error feedback in the company name field.
*
*
Fixes DUPP-514
> Also validate company_name failure

- packages/js/src/first-time-configuration/tailwind-components/base/combo-box.js
- packages/js/src/first-time-configuration/tailwind-components/base/single-select.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/user-selector.js
* QA can always do with specific id's, as they provide better means of targeting UI. Unfortunately, headless-ui does not provide a way to override their semi-random internal id's. Therefore, I decided to at least make sure the wrapping div has an id.
* Adds an id to the single-select and combo-box components to make automated tests easier.
*  Unfortunately, headless-ui does not provide a way to override their semi-random internal id's. Therefore, I decided to at least make sure the wrapping div has an id.
* Inspect the First-time configuration. Notice that the organisation-person-select and, after selecting person, the user-select, have a wrapping div with an id.
QA can …
> Small improvements to single-select and combo-box id's

- inc/class-wpseo-admin-bar-menu.php
‘Check links to this URL’ option on admin bar menu should take current home URL ’home’ instead of the WordPress installation directory URL ‘siteurl’. In subdirectory WP setup, it is taking to unreachable Google Search Console page. This pull request will fix this case by passing the Site Address (URL) instead of WordPress Address (URL). 
* Fixes a bug where the "Check links to this URL" option on admin bar menu would lead to an error page on setups with home URL different from the site URL. Props to @suascat.
*
* Login to your WP setup which should be either subdirectory or subdomain install. Assuming the **WordPress Address (URL)** setting is `http://example.com/wp` …
> Fixing site URL instead of WordPress URL within ‘Check links to this URL’ option of Yoast admin bar menu.

- packages/yoastseo/src/languageProcessing/languages/es/config/transitionWords.js
*
* Fixes a bug which caused the Spanish transition word `para ilustrar` to not be recognized by the transition words assessment.
* [yoastseo] Fixes a typo in the list of Spanish transition words.
* [shopify-seo] Fixes a bug which caused the Spanish transition word `para ilustrar` to not be recognized transition words assessment.
*
* Set your site language to Spanish
* Create a post and add a text with at least 200 words
* Add the phrase `para ilustrar` to the text
* Confirm that the transition words assessment recognizes it as a transition word.
* Repeat the same steps in Shopify with a new product ([here are instructions on how to change analysis language in …
> LR-3 Fix typo in Spanish transition words list

- src/integrations/front-end/robots-txt-integration.php
- tests/unit/integrations/front-end/robots-txt-integration-test.php
* Each site on a subdirectory multisite install has its own sitemap index. Therefore the robots.txt should have all sitemaps.
* Add support for subdirectory XML sitemaps in robots.txt.
* Have a `Subdirectory` multisite installation and have not activated the plugin yet
* Verify that a `robots.txt` file exists; e.g. `http://multisite.wordpress.test/robots.txt`
* Verify it contains:
```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
Sitemap: http://multisite.wordpress.test/wp-sitemap.xml
```
- Activate the plugin
- Reload the `robots.txt`; e.g. `http://multisite.wordpress.test/robots.txt`
- * Verify it contains:
```
User-agent: *
Disallow:
Sitemap: …
```
> Add support for subdirectory XML sitemaps in robots.txt

- src/conditionals/robots-txt-conditional.php
- tests/unit/conditionals/robots-txt-conditional-test.php
*
* Fixes an unreleased bug where the robots txt integration was not active in the multisite file editor, resulting in the contents being the same as before our filters: no sitemap(s) and other allow/disallow.
*
* Set up clean multisite subdomain env (or remove the `robots.txt` file from your WP root)
* Install and Network activate this branch
* Check `robots.txt` file (it shows the link to sitemaps)
* Go to Yoast SEO>Edit files> click create `robots.txt` file
* Check `robots.txt` file, it should have something like:
```
User-agent: *
Disallow:
Sitemap: http://multisite.wordpress.test/sitemap_index.xml
```
* Note that if you created the `robots.txt` as active file, the …
> Add multisite file editor location to robots conditional

- admin/views/tabs/dashboard/crawl-settings.php
- admin/views/tabs/network/crawl-settings.php
*
* Adds an info link in the Crawl settings.
*
* Go to Yoast SEO->General in the Crawl settings tab
* Confirm that an info link was added there likeso:
* Confirm that the link directs to https://yoa.st/crawl-settings in a new tab and that the shortlink args are added in the url, eg. `?php_version=7.4&platform=wordpress&platform_version=5.9.3` etc.
For multisites:
* Go to Yoast SEO->General in the Crawl settings tab of the network admin
* Confirm that an info link was added there likeso:
* Confirm that the link directs to https://yoa.st/crawl-settings in a new tab and that the shortlink args are added in the url, eg. …
> Add info link

- src/integrations/admin/redirects-integration.php
- tests/unit/integrations/admin/redirects-integration-test.php
*
* Fixes an unreleased bug where the `Redirects` upsell wouldn't be displayed to the roles that access the same page on Premium.
* in Premium the target capability for `Redirects` is `wpseo_manage_redirects` which is not present at all in Free. We want to avoid conflicts so we're not introducing that cap, targeting `edit_others_posts` instead.
* Install and activate without Premium
* Make sure you have at least a user with `Editor` role and a user with `SEO Editor` role.
* Switch to the Editor user
* Check that you can see only 2 subpages under `Yoast SEO` in the sidebar (both with `Premium` badge)
* Workouts
* Redirects
* visit the Redirects page and check it looks as …
> DUPP-533 show redirects upsell to editors

- src/integrations/admin/crawl-settings-integration.php
- tests/unit/integrations/admin/crawl-settings-integration-test.php
* We want to clean some leftovers in the Crawl settings integration.
* Improves technical debt in the Crawl settings integration.
*
* Smoke test the crawl settings tab: it should still be there and be working.
* The feed removal should be unaffected 
*
*
Fixes [DUPP-540]
[DUPP-540]: https://yoast.atlassian.net/browse/DUPP-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DUPP-540 clean crawl settings integration

- admin/views/tabs/dashboard/crawl-settings.php
- admin/views/tabs/network/crawl-settings.php
* We want to clean some leftovers in the Crawl tab
* Improves technical debt in the Crawl tab
*
* In a multisite, install SEO Free
* Go to a subsite and `Remove` the **Post comment feeds**
* Confirm in a post of that subsite that the feed have been removed
* Go to the network site and toggle the **Post comment feeds** from `Allow Control` to `Disable`
* Refresh the subsite settings and confirm that the setting has been disabled:
* Confirm in the post of that subsite that the feed have returned.
*
Fixes #
> Remove obsolete code

- packages/yoastseo/spec/languageProcessing/helpers/morphology/getAllWordsFromPaperSpec.js
- packages/yoastseo/spec/languageProcessing/researches/keywordCountInUrlSpec.js
- packages/yoastseo/src/languageProcessing/helpers/morphology/getAllWordsFromPaper.js
- packages/yoastseo/src/languageProcessing/researches/keywordCountInUrl.js
* In other assessments, we recognize word forms of hyphenated keyphrases (e.g. `two-year-old` and `two-year-olds`) but we do not filter out function words (e.g. `two`, `year`, and `old` are all function words but they don't get filtered out from the phrase `two-year-old`). We want to achieve the same behavior for the Keyphrase in slug assessment. Before implementing the change in this PR, both morphology and function words weren't working in the Keyphrase in slug assessment for hyphenated keyphrases.
* [wordpress-seo-premium] Improves the accuracy of the Keyphrase in slug assessment by recognizing different word forms of hyphenated keyphrases in the slug (e.g. if keyphrase is `ex-husband` and slug is `ex-husbands`). 
* …
> LR-6 Make morphology work for hyphenated keyphrases in Keyphrase in slug assessment

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/helpers/index.js
- packages/js/src/first-time-configuration/tailwind-components/stepper.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
* To add errors on a step-saving level (so unrelated to specific input fields).
* Adds an informative error message to the steps of the First-time configuration should an error occur.
* Only added errors to steps with advancing criteria that can fail (e.g. they have `.then().catch()` statements upon saving.
* Only showing the error alert if there was a message field in the server error response.
* In the stepper, go to either the site representation, social profiles, or personal preferences step.
* In the network tab in Chrome, under the `throttling` drop down, set throttling to "offline".
* Press save. An error should appear about you being offline.
* Set throttling to …
> Handle step level errors

- packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
- packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-input-person-section.js
- packages/js/src/workouts/components/SocialInputPersonSection.js
- src/integrations/admin/first-time-configuration-integration.php
- src/routes/first-time-configuration-route.php
* In the `Site representation` step, if a user chooses _Person_ but doesn’t select the user the site represents, in the following `Social profiles` step a text paragraph is shown with outdated information and an alert is displayed with wrong styling
* Fixes a bug where outdated information is shown in the First-time configuration Social profiles step
* N/A
* Start with a fresh installation of  Yoast SEO 
* Navigate to `General` -> `First-time configuration` tab
* In the `Site Representation`step, choose the site to represent a person from the drop-down but leave the _Name_ input field empty. Press `Save and Continue` and advance to the next step
* Verify the content of …
> Dupp 542 ftc adjust copy and alert in Social profiles step

- admin/tracking/class-tracking-settings-data.php
- admin/views/tabs/dashboard/crawl-settings.php
- admin/views/tabs/network/crawl-settings.php
- inc/options/class-wpseo-option-ms.php
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/front-end/crawl-cleanup-rss.php
* We want to add a new toggle switch to the `Crawl settings` tab to let users disable Atom/RDF URLs access by redirecting the request to their site homepage
* Adds a feature to redirect all the Atom/RDF feeds requests to the site homepage
* N/A
* Check that you can access the Atom and RDF feeds of the site, e.g.:
* http://basic.wordpress.test/feed/atom
* http://basic.wordpress.test/feed/rdf
* http://basic.wordpress.test/comments/feed/atom
* http://basic.wordpress.test/comments/feed/rdf
* http://basic.wordpress.test/hello-world/feed/atom
* http://basic.wordpress.test/hello-world/feed/rdf  
* etc.
* Go to the admin area of your site, `Yoast SEO` -> `General` -> `Crawl …
> DUPP-541 - DUPP-541-disable-atom-rdf-feeds

- admin/tracking/class-tracking-settings-data.php
- admin/views/tabs/dashboard/crawl-settings.php
- admin/views/tabs/network/crawl-settings.php
- inc/options/class-wpseo-option-ms.php
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/front-end/crawl-cleanup-rss.php
- tests/unit/integrations/front-end/crawl-cleanup-rss-test.php
* We want to add a new toggle switch to the `Crawl settings` tab to let users disable the global feed by redirecting the request to their site homepage
* Adds a feature to disable the global RSS feed.
* Disabling the RSS global feed doesn't disable the Atom and the RDF version of it: so http://basic.wordpress.test/feed/atom and http://basic.wordpress.test/feed/rdf will still be accessible until you disable the Atom/RDF feeds.
* inspect any page and see that you can see a  tag linking to the global feed, e,g,
`<link rel="alternate" type="application/rss+xml" title="Basic &raquo; Feed" href="http://basic.wordpress.test/feed/" />`
* Check that you can access the global feed …
> DUPP-547 Remove global feed

- composer.json
- composer.lock
*
* Bumps Guzzle version to `6.5.6`.
* Guzzle now uses Symfony polyfills. However, those are not compatible with PHP 5.6. Therefor we are require the latest PHP 5.6 compatible versions of those polyfill packages.
* Note: Guzzle is a dependency of the OAuth client we use (from League). I.e. it is the authentication that should be tested.
* Test that you can authenticate with Semrush
* Test that you can authenticate with Wincher
*
* Check with PHP 5.6
Fixes #
> Bump guzzle to 6.5.6

- admin/pages/network.php
- src/integrations/admin/crawl-settings-integration.php
- tests/unit/integrations/admin/crawl-settings-integration-test.php
*
* Show different button when Premium is not upgraded
*
* When Premium is not installed, we should get this in the Yoast SEO-General for single sites and the network subsite respectively:
* When Premium is installed but lower than 18.6, we should get these: 
* When Premium is installed and 18.6, we should get these: 
and the feature should be working as expected
*
*
Fixes #
> Show different button when Premium is not upgraded

- admin/tracking/class-tracking-theme-data.php
* Adds block template support to tracking
* Adds block template support to our tracking data.
* Make sure tracking is enabled.
* Delete the `wpseo_tracking_last_request` option.
* Visit the WordPress Admin.
* The tracking data send should include `blockTemplateSupport` in the theme tracking data.
* I recommend setting a breakpoint in the `WPSEO_Tracking::send` method to validate this.
* Make sure tracking is enabled.
* Delete the `wpseo_tracking_last_request` option.
* Visit the WordPress Admin.
* The `wpseo_tracking_last_request` should be filled with a timestamp near the current time.
* There should have been no fatals.
This …
> Add block template support to tracking

- packages/js/src/components/WincherPerformanceReport.js
- packages/js/src/components/WincherSEOPerformance.js
- packages/js/src/components/modals/WincherReconnectAlert.js
- packages/js/src/dashboard-widget.js
- src/config/oauth-client.php
- src/values/oauth/oauth-token.php
- tests/unit/config/oauth-client-test.php
- tests/unit/values/oauth/oauth-token-test.php
Wincher is currently getting about 500-800 requests per minute from Yoast installations that have somehow ended up with a corrupt / invalid refresh token. 
It's unclear exactly how the installations have ended up in this state, but it could be because of:
* Storage errors when saving the new token.
* Response errors, like network errors after our server has already processed the request.
* Race conditions and refresh token rotation (on our end).
This problem also has negative consequences for the performance of WordPress on installations caught in this state, since on every single admin page load they'll have to wait for the refresh request to Wincher as well. It also likely also affects the SEMRush integration.
* Improves …
> Wincher: improve refresh token handling

- packages/js/src/classic-editor/components/cornerstone-content.js
- packages/js/src/classic-editor/initial-state.js
- packages/js/src/classic-editor/watcher.js
- packages/js/tests/classic-editor/initial-state.test.js
- packages/seo-integration/src/analysis/analysis.js
- packages/seo-integration/src/analysis/analyze.js
- packages/seo-integration/src/analysis/createAnalysisConfiguration.js
- packages/seo-integration/src/google-preview/containers/google-preview-container.js
- packages/seo-store/src/analysis/slice/config.js
- packages/seo-store/src/form/slice/seo.js
- packages/seo-store/tests/analysis/hooks.test.js
- packages/seo-store/tests/analysis/slice/config.test.js
- packages/seo-store/tests/analysis/slice/results.test.js
- packages/seo-store/tests/form/slice/seo.test.js
*
* Fixes a bug where marking a post as cornerstone content did not influence the SEO or readability analysis.
* Moved the `isCornerstone` state to the analysis configuration state, since we treat it as analysis configuration in the analysis (and thus need it to re-initialize the analysis).
* Make sure that the Classic Editor plugin is installed and activated.
* Add a focus keyphrase.
* Check the results of the SEO analysis, it should have a red bullet for the _Text length_ assessment saying:
> [Text length](https://yoa.st/34n?php_version=7.4&platform=wordpress&platform_version=6.0&software=free&software_version=19.0&days_active=6-30&user_language=en_US): …
> LINGO-1462 - Marking a post as cornerstone content does not change the readability analysis

- src/integrations/admin/crawl-settings-integration.php
* The upsell should match the look of "installed premium"
* Fixes an unreleased bug where in the crawl settings upsell the state of the toggles would not match the default premium state.
* Only cosmetically fixed this for now, added a comment for future readers.
* Go to the multisite network dashboard, go to general > crawl settings
* Note all sides are disabled and on "allow control".
* Try to save other forms on the general page, note that nothing happens to the toggles on the crawl settings tab.
(you can also inspect the `admin-ajax.php` request in the inspector's network tab, and verify that nothing related to crawl-settings is in the saved form). …
> Set disabled upsell crawl settings toggle to "allow_control"

- inc/class-upgrade.php
* This is a follow-up fix for the https://github.com/Yoast/wordpress-seo/pull/18520 fix
* With this PR we want to ensure that users with no Premium when on 19.0, will get their `Post Comment Feed` setting set to `Allow Control` when the eventually install Premium
* Doing so requires setting `Post Comment Feed` to `Allow Control` upon upgrade to 19.0, even for people that have already set that setting to `Disable`
* We expect the users affected by the above point to be very few, if any.
* Fixes a bug where users on 19.0 and with no Premium would get the non-default value for `Post Comment Feeds` when eventually they install Premium
*
* Use clean docker multisite env
* …
> Revert to Allow Control for Post Comment feeds upon upgrade to 19.1

- packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
* Keep the webinar promo on the final step of the first time configuration for free users
* Return initial behavior for free users in first time configuration
* Have a clean environment & activate the plugin
* Go to the first time configuration and click on continue until you’re at the final step
* Verify you’ll see the webinar promo content
* Have a clean environment & activate premium
* Go to the first time configuration and click on continue until you're at the final step
* Verify the the last step has non webinar promo related content
Fixes P1-1416
> Return initial behavior for free users in first time configuration

- src/integrations/admin/ryte-integration.php
* Adds a new filter `wpseo_change_home_url` that allows changing the URL the Ryte integration checks, to allow for more versatile hosting setups.
* If you're on a test environment like the Yoast's docker one, you have to add this filter in a mu-plugin (or in the functions.php file of your active theme:
```
add_filter( 'yoast_seo_development_mode', 'yoast_seo_development_mode_change', 1 );
function yoast_seo_development_mode_change() {
return false;
}
```
so that the Ryte integration can be active and running when checking the Site Health tool
* If you're on a local environment, the site should not be able to be indexed, so if you go to the Site Health tool, you should see …
> DUPP-573 Allow changing the check url for the Ryte integration

- admin/class-meta-columns.php
- composer.json
- css/src/admin-global.css
*
* Enables sorting on the SEO and readability score columns on the post overview page.
*
* Go to the post overview page
* Verify the SEO score & readability score columns can now be sorted (first click should sort descending, from green to red)
* Note an unchanged "quirk": the posts without a saved score will be filtered out. Unchanged because this works the same way for the meta description and keyphrase columns
*
*
Fixes P1-1370
> Post overview: sortable SEO and readability score columns

- src/exceptions/validation/invalid-blog-id-exception.php
- src/services/options/network-admin-options-service.php
- src/validators/blog-id-validator.php
- tests/unit/validators/blog-id-validator-test.php
* Adds the blog ID validator.
* Have a multisite wordpress installation running
```php
/** @var \Yoast\WP\SEO\Validators\Blog_ID_Validator $validator */
$validator = YoastSEO()->classes->get( \Yoast\WP\SEO\Validators\Blog_ID_Validator::class );
try {
}
echo '<br>';
}
_test_validate( 1 );
_test_validate( 0 …
```
> Create defaultblog option validator for network admin 

- packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
* This PR resolves [issue 640](https://github.com/Yoast/YoastSEO.js/issues/640) where initials in the sentence caused the sentence tokenizer to split up the sentence because the tokenizer thought that a fullstop followed by a space and a capitalized letter was a sentence break.
* Note that this PR is to a large extend a copy of https://github.com/Yoast/wordpress-seo/pull/18477. This I closed because it was too cluttered.
* Improves the sentence recognition by disregarding initials as potential sentence boundaries.
* [yoastseo] Improves the sentence recognition by disregarding initials as potential sentence boundaries.
* [shopify-seo] Improves the sentence recognition by disregarding initials as potential sentence boundaries.
* …
> LR-7 Improves sentence detection for sentences with initials

- admin/class-config.php
- admin/metabox/class-metabox.php
- composer.json
- packages/js/src/components/WebinarPromoNotification.js
- packages/js/src/components/fills/SidebarFill.js
- packages/js/src/elementor/components/fills/ElementorFill.js
- packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
- packages/js/src/initializers/settings-header.js
- src/integrations/third-party/elementor.php
* Add the shortlinks to the webinar promo banner and notifications
* Add the shortlinks to the webinar promo banner and notifications
* Header banner notifications
* Visit the 'General' admin page(`Yoast SEO -> General`)
* You'll see the webinar promo notification
* Inspect the `Register now!` link and verify the url: `https://yoa.st/webinar-intro-settings` with added query parameters 
* Final step of the FTC
* Visit `Yoast SEO -> General -> First-time configuration(tab)`
* Make it to the last step
* Inspect the `Register now!` button and verify the added query parameters 
* Add a new post
* You'll see the webinar promo notification in the sidebar
* Inspect the `Register …
> Add the shortlinks to the webinar promo banner and notification

- src/presenters/abstract-indexable-tag-presenter.php
- src/presenters/open-graph/image-presenter.php
- src/presenters/twitter/image-presenter.php
* Fixed a bug where filtering the OpenGraph and Twitter image to a URL containing ampersands would lead to encoding issues.
* Made sure we don't use the `display` escaping for URLs.
* Create a small plugin like so:
```php
<?php
/**
* Plugin Name: test plugin
*/
add_filter( 'wpseo_opengraph_image', 'return_wrong_image' );
add_filter( 'wpseo_twitter_image', 'return_wrong_image' );
function return_wrong_image() {
return 'https://www.example.com/path/?query=value&cats=cool';
}
```
* See that with the patch this gets displayed properly in the Twitter and `og:` meta-tags with the `&` unencoded.
Fixes P1-1414
> Don't encode ampersands in URLs

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
*
* Fixes a bug that would cause the First-time configuration to crash when completing indexation with the Yoast admin bar menu hidden.
*
* Have indexation set to not completed (using the Test helper => reset indexables tables and migations). Also reset notifications.
* Go to SEO-> General-> Feature and set Admin bar menu to Off
* Note the red notifaction in the sidebar.
* Go to SEO-> General-> FTC and Start SEO Data Optimization
* Wait until Start SEO Data Optimization is finished
* Note the count in the sidebar has gone down (or the red bubble is gone, if it was at 1 before).
* No errors in the console, FTC did not crash.
* …
> Update notifications counters only when present

- src/integrations/front-end-integration.php
- src/presenters/meta-author-presenter.php
- tests/unit/integrations/front-end-integration-test.php
- tests/unit/presenters/meta-author-presenter-test.php
* By adding a `meta author` tag we're making sure LinkedIn picks up the name of a post author properly.
* This uses `get_userdata`, which [this pull](https://github.com/Yoast/wordpress-seo/pull/18542) introduces in another place. Should we move this to the `Meta_Tags_Context` ? @herregroen what do you think?
* install and activate latest Premium RC
* in SEO > General > Crawl settings, disable oEmbed links
* set up `ngrok` to make your site visible outside:
* run `ngrok http 127.0.0.1 --host-header="basic.wordpress.test"` in a console
* pick the https:// URL and use it as "Site URL" in the WP settings
* pick a post whose author is not `admin`, copy its URL
* Put the URL in …
> Introduce new meta author presenter

- admin/class-meta-columns.php
* Bob R mentioned that this would make more sense to him during the sprint review, due to the red score posts requiring action from the user.
* [Sort implementation PR](https://github.com/Yoast/wordpress-seo/pull/18533)
* Changes the unreleased first sort of the score columns on the post overview page to go from red to green instead of green to red.
*
* Go to the post overview page
* Verify the SEO score & readability score columns can now be sorted: the first click should sort ascending, from red to green.
*
*
Fixes #
> Change the first sort of the post score columns from red to green

- css/src/admin-global.css
- src/integrations/admin/crawl-settings-integration.php
* Minor UX tweaks, as per @uxkai 's feedback
* To be tested alongside https://github.com/Yoast/wordpress-seo-premium/pull/3576
* Improves UX for the unreleased feature of the additional Crawl Cleanup settings
*
* When Premium is not enabled, the Crawl Cleanup tab should look like this:
* When Premium is enabled, follow Test Instructions of https://github.com/Yoast/wordpress-seo-premium/pull/3576
*
Fixes #
> Improve UX

- css/src/admin-global.css
- src/integrations/admin/crawl-settings-integration.php
* We want to use a generic class to style help text in the Crawl settings tab. 
* Uses a generic CSS class to style help text in the Crawl settings tab.
*
* Disable Premium
* Check that the help line `By removing Global comments feed, Post comments feeds will be removed too.` is visible and styled correctly (in _italic_ and 50% opacity)
* Enable Premium
* Check that the help line `By removing Global comments feed, Post comments feeds will be removed too.` is styled correctly (in _italic_)
* also check the matching Premium PR https://github.com/Yoast/wordpress-seo-premium/pull/3578
* …
> DUPP-593 Use generic class for help text

- packages/js/src/components/WincherKeyphrasesTable.js
- packages/js/tests/components/WincherKeyphrasesTable.test.js
*
* Fixes a bug in the Wincher integration table on posts and terms where the focus keyphrase was not marked with an asterisk.
* Also fixes a minor error inside of the Wincher table unit tests:
```js
console.error
fn is not a function
```
Note: this should be tested in the block editor, classic editor and Elementor.
* Install and activate the latest version of Yoast SEO Premium.
* Enter a focus keyphrase that includes capital letters (for example _Yoast SEO_).
* Enter a related keyphrase.
* Look in the Wincher integration table inside of the metabox (In the collapsible labeled _Track SEO performance_). The focus keyphrase should have an asterisk next to …
> Fixes a bug where the focus keyphrase was not recognized in the Wincher table (and thus did not get marked with an asterisk).

- packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
- packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
- packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
* LR-7 and LR-9 where both merged, but caused an issue when combined. This pr fixes this.
* [non-user-facing] Fixes a bug where two PRs on the sentence tokenizer clashed, which broke the fix of initials.
* The `wordBoundariesForRegex` in `sentenceTokenizer.js` was expanded to also increase string boundaries.
1. Create a new post. And fill in a title. For example "Frank Mercer"
2. Paste the text from [LR_7_test_text.txt](https://github.com/Yoast/wordpress-seo/files/8762162/LR_7_test_text.txt) in the post.
3. Expand readability analysis and toggle button to highlight the results of the passive voice analysis in the text (see arrow in the screenshot)
4. The result should …
> Lr 45 sentence tokenizer clash between initials and quotes

- admin/views/class-yoast-feature-toggles.php
*
* Fixes an unreleased bug where the shortlink of the Help text of the IndexNow feature toggle would be broken.
* Improves the unrleased copy of the IndexNow feature toggle.
*
* Have Free enabled and Premium disabled.
* Go to a single site's or a subsite's Yoast SEO->General page in the Features tab
* The IndexNow toggle should have the following copy:
**Automatically ping search engines like Bing and Yandex whenever you publish, update or delete a post.**
* The `Find out how IndexNow can help your site.` link should point to the https://yoa.st/index-now-feature shortlink
* Go to the network site in the SEO->General page in the Features tab
* The IndexNow toggle should …
> Fix help link and copy of the IndexNow feature toggle

- src/helpers/url-helper.php
- src/integrations/front-end/indexing-controls.php
- src/integrations/front-end/redirects.php
- tests/unit/integrations/front-end/redirects-test.php
* If you disable date archives in Yoast SEO, `/2022/` would redirect to your homepage, but a post, say `/hello-world/` with the parameter `?year=2022`, so `https://example.com/hello-world/?year=2022` would still show the 2022 archives. Yoast SEO now redirects those parameters away, so you'd be redirected to `https://example.com/hello-world/`.
* Moved `recreate_current_url`, introduced in premium in the crawl cleanup clean permalinks changes, to the `Url_Helper` for easier access.
* Try `https://example.com/hello-world/?year=2022` or something similar, and for the other variables touched too.
Fixes PRODUCT-288
> Remove date parameters from URLs when date archives are disabled

- inc/options/class-wpseo-option-wpseo.php
- inc/sitemaps/class-sitemaps-admin.php
- inc/sitemaps/class-sitemaps.php
- tests/unit/inc/sitemaps/sitemaps-admin-test.php
- tests/unit/integrations/front-end/category-term-description-test.php
- tests/unit/integrations/front-end/comment-link-fixer-test.php
- tests/unit/integrations/front-end/indexing-controls-test.php
- tests/unit/integrations/front-end/redirects-test.php
- tests/unit/integrations/front-end/robots-txt-integration-test.php
- tests/unit/integrations/front-end/rss-footer-embed-test.php
- tests/unit/integrations/front-end/theme-titles-test.php
- tests/unit/integrations/third-party/amp-test.php
- tests/unit/integrations/third-party/bbpress-test.php
- tests/unit/integrations/third-party/jetpack-test.php
- tests/unit/integrations/third-party/wpml-test.php
- tests/unit/loader-test.php
* Set IndexNow to on by default (in premium);
* Simplify XML sitemap ping towards Google
* Remove Bing XML sitemap ping
* Ensures the Bing XML sitemap ping is only made if IndexNow is disabled.
* Prevents XML sitemap pings for blogs that aren't public.
*
* Place a breakpoint in the ping search engines function.
* It should be called when you publish a post.
* Publish a post.
* There should be no errors in the network tab or console ( compared to before clicking publish ).
* Pinging search engines after a post has been published or otherwise …
> Changes to IndexNow and pinging search engines

- composer.json
- composer.lock
- src/conditionals/third-party/wordproof-integration-active-conditional.php
- src/integrations/third-party/wordproof.php
* Fix for [QA-3346](https://yoast.atlassian.net/browse/QA-3346)
* WordProof endpoint security vulnerability fix
* Added a Wordproof_integration_active conditional to the main WordProof integration file that prevents registering the hooks. With the integration disabled, none of the hooks in `integrations/third-party/wordproof.php` are registered. This includes the init of the SDK which in turn registers webhooks.
* Webhooks are only accepted when the site is authenticated preventing others to access webhook endpoints.
* Go to /wp-json
* wordproof/v1 should not be listed in the namespaces
* enable the WordProof integration
* wordproof/v1 should be listed in the namespaces …
> WordProof endpoint fix

- src/integrations/front-end/feed-improvements.php
* Brings some of the RSS feed enhancements we've long done on yoast.com to Yoast SEO.
* Adds canonical HTTP headers from RSS feeds to their parent URLs (for instance your homepage, or specific categories or tags), so the feeds themselves don't show up in search results.
* Makes sure the title separator chosen in Yoast SEO is used for RSS feed titles too.
* Makes sure the `link` tag in the RSS feeds' `channel` section links to the most specific URL possible (for instance the category or tag the RSS feed is for) instead of the homepage.
* Make sure that feeds are enabled
* Repeat the checks below for all these types of feeds:
* category feeds e.g. …
> Bring several small improvements to WordPress RSS feeds

- package.json
- yarn.lock
* Fixes small bug in the WordProof certificate
* Fix small bug in the WordProof certificate
* New version of @wordproof/uikit.
* Timestamp a page
* Open the certificate
* Click on "Compare Versions"
* Make sure the line breaks are not as funky as in the image below.
* The WordProof certificate
Fixes #
> Fix small bug in the WordProof certificate

- src/context/meta-tags-context.php
* When a site has not set a logo in the Yoast SEO settings, but has set a site logo in the customizer, we will now use that logo in our Schema `Organization` output.
* Set your site to represent an organization
* Set also the organization name and logo
* Visit a site's page, e.g. the front page, and copy the schema
* Inspect the schema (e.g. with [this](https://classyschema.org/Visualisation) tool)
* Look for the `Organization` schema piece and verify:
*  The `name` attribute is the one you specified
*   In the `Logo` sub-element, The URL is the one corresponding to the image you picked as logo
* Now go to `Appearance` -> `Customize` -> `Site Identity`
* Specify both the …
> Default to site logo for org and person logo, and site name for org name

- composer.json
- composer.lock
* We want to update Guzzle to 6.5.8 following a security report
* Bumps Guzzle version to 6.5.8.
*
* Note: Guzzle is a dependency of the OAuth client we use (from League). I.e. it is the authentication that should be tested.
* Test that you can authenticate with Semrush
* Test that you can authenticate with Wincher
* **NOTE**: it's important to test the **authentication**, so if your site is already connected to the two services above, please disable the Wincher and Semrush integrations, save, and then re-enable them.
*
*
Fixes [PC-78]
[PC-78]: …
> PC-78 Require Guzzle 6.5.8

- admin/capabilities/class-register-capabilities.php
* add add_manage_privacy_options capability to seo manager so this role can edit the privacy page
* SEO Managers are now allowed to edit the privacy page. But not on multisites.
* we use map_meta_cap to dynamically add the capability
* Create a privacy page as an admin.
* Login as an SEO manager.
* Make sure you can edit the privacy page.
* Above should not be the case for multisites.
* The `manage_privacy_options` capability for the SEO manager.
Fixes #
> add add_manage_privacy_options capability to seo manager

- composer.json
- composer.lock
- src/integrations/third-party/wordproof.php
* Prevent Yoast timestamping posts that contain the default WordProof timestamp meta or 'selected_post_types' from authenticating with the WordProof timestamp plugin.
* Fixes an unreleased bug where all previously timestamped pages through the WordProof Timestamp plugin would continue to be timestamped through the Yoast SEO WordProof integration with the WordProof Timestamp plugin deactivated.
* We only return the Yoast meta key and return an empty array for the auto timestamping feature.
- Activate WordProof Timestamp plugin, authenticate (or logout and authenticate again) and timestamp a few pages
- Activate Yoast SEO plugin with WordProof integration
- Deactivate …
> only return the yoast meta key to be timestamped

- css/src/admin-global.css
- inc/options/class-wpseo-option-wpseo.php
- src/integrations/admin/deactivated-premium-integration.php
- tests/unit/integrations/admin/deactivated-premium-integration-test.php
* Adds a notice if premium is installed but not activated.
* This notice is shown on all admin pages if and only if the current user has the capability to activate plugins.
* Adds a notice that displays when Yoast SEO Premium is installed but not activated prompting the user to activate it.
* Have Yoast SEO Premium installed but not activated.
* You should see a notice if and only if you have permission to activate plugins.
* The notice should be present on all admin pages.
* The notice should look like this:
* Click the link in the notice.
* Premium should be activated.
* Deactivate premium again
* Uninstall Premium and reload any admin page.
* The notice should not be …
> [PC-73] Add notice for premium deactivated

- src/integrations/admin/deactivated-premium-integration.php
- tests/unit/integrations/admin/deactivated-premium-integration-test.php
* Prevents showing the premium deactivated notice on upgrade pages.
* Prevents showing the premium deactivated notice on upgrade pages.
* See https://yoast.atlassian.net/browse/PC-87
* The premium deactivated notice on upgrade pages.
Fixes https://yoast.atlassian.net/browse/PC-87
> [PC-87] Do not show premium deactivated notice on upload plugin pages

- src/integrations/third-party/wordproof.php
* Fixes a misnamed filter causing a fatal error.
* Fixes a misnamed filter causing a fatal error.
* See https://yoast.atlassian.net/browse/PC-92
* Which posts are being timestamped by WordProof.
Fixes https://yoast.atlassian.net/browse/PC-92
> [PC-92] Fix the name of the filter function for wordproof_timestamp_post_types

- css/src/admin-global.css
* When in the `Settings` -> `Privacy` WordPress page,  Yoast SEO notices are shown without padding
* Adds padding around Yoast SEO notices when in WordPress Privacy page.
* N/A
* Install Yoast SEO
* Install but do not activate Yoast SEO Premium
* Go to `Settings` -> `Privacy` 
* Without this PR, the notice is shown as follows:
* With this PR, it is shown as follows, instead:
*
Fixes [PC-93](https://yoast.atlassian.net/browse/PC-93)
> Fix yoast-premium-deactivated-notice when shown in privacy page

- packages/js/src/insights/components/insights-collapsible.js
- packages/js/src/insights/components/insights-modal.js
- packages/js/src/insights/initializer.js
- packages/js/src/insights/redux/reducer.js
- packages/js/src/insights/redux/selectors.js
- packages/js/tests/insights/components/insights-collapsible.test.js
- packages/js/tests/insights/components/insights-modal.test.js
- packages/js/tests/insights/redux/selectors.test.js
* For some languages, like Japanese, we do not support the Flesch reading ease calculation. When it is not available, we do not want to show it in the insights.
* Fixes a bug where the Flesch reading ease insight was shown in the insights, even if the user's language does not support Flesch reading ease score calculation.
* Created a new selector to check whether the Flesch reading ease score and difficulty are available.
* Set your site language to Japanese.
* Add some content.
* Check the insights tab inside of the metabox.
* **Note**: Even though the site's language is set to Japanese, the insights tab will still be in English since the insights …
> PC-90 - Do not show Flesch reading ease inside of the insights tab when it is not available.

- src/presentations/indexable-presentation.php
- tests/unit/presentations/archive-adjacent-test.php
- tests/unit/presentations/indexable-author-archive-presentation/canonical-test.php
- tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/indexable-home-page-presentation/canonical-test.php
- tests/unit/presentations/indexable-post-type-archive-presentation/canonical-test.php
- tests/unit/presentations/indexable-post-type-archive-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/indexable-post-type-presentation/canonical-test.php
- tests/unit/presentations/indexable-presentation/canonical-test.php
- tests/unit/presentations/indexable-presentation/open-graph-url-test.php
- tests/unit/presentations/indexable-presentation/permalink-test.php
- tests/unit/presentations/indexable-static-home-page-presentation/canonical-test.php
- tests/unit/presentations/indexable-static-posts-page-presentation/canonical-test.php
- tests/unit/presentations/indexable-static-posts-page-presentation/open-graph-url-test.php
- tests/unit/presentations/indexable-term-archive-presentation/canonical-test.php
* We want to fix the `main_schema_id` for date archives after https://github.com/Yoast/wordpress-seo/pull/18558
* Fixes an unreleased bug where the `WebPage` piece would get a blank ID for date archives.
* 
* Visit a date archive page, e.g.:
* http://basic.wordpress.test/2022/06/23/
* http://basic.wordpress.test/2022/06/
* http://basic.wordpress.test/2022/
* Inspect the schema (e.g. with [this](https://classyschema.org/Visualisation) tool)
* Look for the `CollectionPage` schema piece:
*  Without this PR, the `@id` is set to `null`
*  With this PR, the `@id` is set to the page's permalink
* Now go to `Settings` -> `Permalinks` and choose `Numeric` from the `Common …
> PC-94 Fix permalink generation for date archives

- packages/js/src/insights/components/insights-collapsible.js
- packages/js/src/insights/components/insights-modal.js
- packages/js/src/insights/components/text-length.js
- packages/js/src/insights/components/word-count.js
- packages/js/src/insights/initializer.js
- packages/js/src/insights/redux/actions.js
- packages/js/src/insights/redux/reducer.js
- packages/js/src/insights/redux/selectors.js
- packages/js/tests/insights/components/insights-collapsible.test.js
- packages/js/tests/insights/components/insights-modal.test.js
- packages/js/tests/insights/components/text-length.test.js
- packages/js/tests/insights/redux/reducer.test.js
- packages/js/tests/insights/redux/selectors.test.js
- packages/yoastseo/spec/languageProcessing/AbstractResearcherSpec.js
- packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/textLengthSpec.js
- packages/yoastseo/spec/languageProcessing/researches/wordCountInTextSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/taxonomyTextLengthSpec.js
- packages/yoastseo/src/languageProcessing/helpers/word/countWords.js
- packages/yoastseo/src/languageProcessing/languages/ja/customResearches/textLength.js
- packages/yoastseo/src/languageProcessing/languages/ja/helpers/countCharacters.js
- packages/yoastseo/src/languageProcessing/researches/readingTime.js
- packages/yoastseo/src/languageProcessing/researches/wordCountInText.js
- packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
- packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
* For certain languages, e.g. Japanese, we do not count the text length in words, but in characters. This PR fixes a bug where the insights mistakenly showed "words" instead of "characters" when talking about the text length for these languages.
* Displays "character/characters" string instead of "word/words" string inside Insights tab for languages that use character as the unit measurement for text length calculation.
* Changed mentions of "word count" to "text length" inside of the insights, since text length can also be counted in number of characters, instead of words.
* We decided not to rename `wordCountInText` research in this PR to avoid scope creep.
**Note**: …
> PC-91 Output character counts for languages that use character count for text length calculation

- admin/class-admin-asset-manager.php
* Fix bug caused by https://github.com/Yoast/wordpress-seo/pull/18620
* Fixes an unreleased bug where the assets of the first time configuration where incomplete, causing a JavaScript error on the general settings page.
*
* Have a fresh environment
* Verify that before this change you get an `uncaught ReferenceError: wpApiSettings is not defined` error in Yoast SEO > General
* Verify that with this change you get the first time configuration working!
*
*
Fixes https://yoast.atlassian.net/browse/PC-98
> Add undetected first time configuration assets

- packages/js/src/components/fills/MetaboxFill.js
*
* Fixes an unreleased bug where the order of the SEO analysis and Premium SEO analysis in the Yoast metabox would be wrong in Firefox
*
* In Firefox, go to create a new post (while Premium is not active)
* In both the Block Editor and the classic editor, SEO analysis and Premium SEO analysis should be at the top of the metabox (but below the Google preview). (with the previous RC the SEO analysis and Premium SEO analysis were at the bottom of the metabox)
* Which means that the order of the sidebar items in that metabox should be `1. SEO analysis 2. Premium SEO analysis 3. Add related Keyphrases, etc.`
* Confirm that clicking on the `Premium SEO Analysis` opens the …
> Fix order of the metabox in Firefox

- packages/components/src/insights-card/InsightsCard.js
- packages/js/src/insights/components/flesch-reading-ease.js
- packages/yoastseo/spec/languageProcessing/researches/getFleschReadingScoreSpec.js
- packages/yoastseo/src/languageProcessing/researches/getFleschReadingScore.js
* If the Flesch reading ease does not make sense (e.g. in cases where there is very little text (10 words or less), previously we would display 100: very easy to read. This PR chages this to a ? and the encouragement to write more text before watching the FRE.
* Changes the feedback of Flesch reading ease in the insights tab when there is not enough text.
* [yoastseo] Changes the feedback of Flesch reading ease in the insights tab when there is not enough text.
* [@yoast/components] Changes the allowed proptype of `amount` in the `InsightCard.js` to also allow the '?' as a value.
* In `packages/components/src/insights-card/InsightsCard.js` we changed the allowed proptypes of "amount" in order for it to also allow a question mark. …
> Pc 110 only show flesch reading ease score when there is enough content

- admin/formatter/class-post-metabox-formatter.php
- packages/yoastseo/src/scoring/assessments/SCORING SEO.md
- src/integrations/third-party/woocommerce-post-edit.php
- tests/unit/integrations/third-party/woocommerce-post-edit-test.php
* Google does not show dates in the search results for products, so we should do the same in the Google preview for WooCommerce products.
* Removes the date from the meta description for WooCommerce products.
*
* In the Google Preview section, confirm that the date is shown.
* Confirm that the meta description length assessment and the color bar base their feedback on the meta description text with the date.
* Repeat these steps for pages and custom post types.
* Repeat the above steps for the Elementor, Gutenberg, and the Classic Editor plug-ins.
* Activate the WooCommerce plug-in
* Create a new product.
* In the Google Preview section, confirm that …
> PC-27 - don't show date in meta description in certain shopify content types and woo product pages

- src/presenters/meta-author-presenter.php
- tests/unit/presenters/meta-author-presenter-test.php
* We want to prevent warning if no user data is available
* Fixes a bug where a warning would be triggered when author data wasn't available for a post.
*
* install and activate BBPress
* in the BBPress settings, enable `Allow guest users without accounts to create topics and replies`
* switch to the Twenty Twenty-One theme
* create a new Forum
* visit the forum in the frontend in an incognito window, so you appear unlogged 
* use the form at the bottom to create a new topic. **Note**: you may get an error because of some problem not related to our plugin. If so, just visit the forum once more
* visit the topic you just created:
* without this patch, you'll get a …
> PC-122 Prevent warning if no user data is available

- src/context/meta-tags-context.php
- src/generators/schema/main-image.php
- src/generators/schema/webpage.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/generators/schema/main-image-test.php
- tests/unit/generators/schema/webpage-test.php
* Improves Schema for archive pages by using the featured image of the first post as `primaryImageOfPage` and removing `potentialAction`.
* Improves Schema for attachment pages by setting the proper `primaryImage` attribute.
_Tip: to verify the results of this PR, I found the [diffchecker](https://www.diffchecker.com/diff) tool to be very effective. You can use it to compare the schema produced by Yoast SEO before and after applying the PR.
However, you should still use a schema validator tool s.a. [this](https://classyschema.org/Visualisation) to ensure a valid schema is produced._
* Go to `Yoast SEO` -> `Search Appearance` -> `Media` tab and verify that the `Redirect …
> Improve archive template / CollectionPage schema properties

- packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
- packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
* When a text containing backslash before the quotation mark, for example `It is a \"calico\" cat` entering the Paper (an object that collects data for the analysis), the paper adds (two) extra backslash: `It is a \\\"calico\\\" cat`. The backslash is not removed when the text is split into words. When we add word boundary using regex to these words with backslash, the regex is invalid. This invalid regex is the cause of the error in Word complexity assessment:
* [wpseo-woocommerce] Fixes a bug where words preceded by or followed by `\` were causing an error in the Word Complexity assessment.
* [worpress-seo-premium] Fixes a bug where words preceded by or followed by `\` were causing an error in the Word Complexity assessment.
* …
> An error occurred in the word complexity assessment in product pages in Woo

- inc/class-wpseo-utils.php
- packages/js/src/redux/reducers/preferences.js
*
* Fixes an unreleased bug where the News SEO upsell would show in the editor for content types for which News SEO was disabled despite being active. 
*
* Enable news SEO.
* In Yoast SEO > News SEO (settings) disable News SEO for e.g. pages, but enable it for posts.
* Visit the search appearance settings try to select news article for some content types. No Upsell should appear.
* For block, classic, and elementor editors:
* Visit a post and a page in all three editors (Tip: use separate tabs). Edit the Schema Article Type to be "News Article".
* No Upsell should be visible in any of the cases.
* 	The bug was that previously, now you would see an upsell for pages despite …
> Dont show news seo upsell when news seo is active

- admin/class-yoast-form.php
- admin/views/tabs/dashboard/features.php
- admin/views/tabs/dashboard/integrations.php
- css/src/admin-global.css
- inc/class-upgrade.php
- src/integrations/admin/crawl-settings-integration.php
* We want to fix a bug where disabled setting toggles would set to `false` when the form in the General page would get saved, instead of persisting their current value.
* That bug would affect users with no Premium, where when they eventually install Premium, they would have their otherwise-enabled-by-default settings set to disabled
* We also want to remedy this bug for current users that might have already performed a form save in the General page. For those, we check upon Free upgrade whether they have never installed Premium before, and if they hadn't, we set enabled-by-default Premium settings to `On`.
* Fixes a bug where disabled settings in the General page would be set to `Off` upon saving the settings form
*
This PR can …
> Fix inactive setting toggles get a false value upon saving the settings form

- admin/class-admin-asset-manager.php
- admin/metabox/class-metabox-editor.php
- packages/js/src/analysis/getApplyMarks.js
* In the Gutenberg editor, our eye markers were unable to highlight content in so-called classic blocks (blocks that use the TinyMCE editor). This PR fixes this issue. 
* Allows marking inside of Classic editor blocks in the Block/Gutenberg editor.
* We have chosen to register the `inside-editor` script globally. 
* Enter a focus keyphrase.
* Add content, including multiple classic editor blocks. Make sure that you use the focus keyphrase multiple times in multiple blocks.
* Within the SEO analysis, click on the marker next to the _Keyphrase density_ assessment.
* All of the occurrences of the focus keyphrase should be highlighted in the post. Including …
> PC-62 Applies marks to Classic editor blocks inside the Block/Gutenberg editor

- packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
- packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
- packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
* This PR fixes a small grammatical error in the word complexity feedback string. (X% of the words in your text **is** considered complex --> X% of the words in your text **are** considered complex)
* [yoastseo] Fixes a small grammatical error in the feedback string.
*
* Create a post/page/CPT with block/elementor/gutenberg/classic editor and add enough text to get the word complexity feedback. Also make sure to include at least 5% complex words to get an orange (or red with cornerstone) bullet. For example use this text: `pandemic simple simple simple simple simple simple simple simple simple simple simple simple simple `
* Make sure that the feedback string for word …
> Pc 133 incorrect singular in feedback string for word complexity assessment v2

- src/presenters/meta-author-presenter.php
- tests/unit/presenters/meta-author-presenter-test.php
* Improves the meta author presenter
* Improves the author meta tag to be displayed only on posts.
* Adds a `wpseo_meta_author` hook to filter the content of the author meta tag.
*
* Visit a _page_ in the front-end, check that you *can't* see a tag such as `<meta name="author" content="Kathlyn Rodriguez" />`
* Visit a _custom post type item_ in the front-end, check that you *can't* see a tag such as `<meta name="author" content="Kathlyn Rodriguez" />`
* Visit a _WooCommerce product page_ in the front-end, check that you *can't* see a tag such as `<meta name="author" content="Kathlyn Rodriguez" />`
* Visit a _post_ in the front-end, check that you *can* see a tag such as …
> PC-88 PC-142 Improve meta author presenter

- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
- packages/js/src/components/contentAnalysis/SeoAnalysis.js
- packages/js/src/components/fills/MetaboxFill.js
- packages/js/src/components/fills/SidebarFill.js
- packages/js/src/elementor/components/fills/ElementorFill.js
- packages/js/src/redux/reducers/preferences.js
* When a user activated Yoast SEO and WooCommerce plugins, the premium upsell of Word complexity and Keyphrase distribution assessments are not loaded in the metabox of a product page. This PR makes sure that the upsell is loaded in the aforementioned case.
* The keyphrase distribution assessment only appears when there are at least 15 sentences and a keyphrase is added to the metabox.
* [wpseo-woocommerce] Loads word complexity and keyphrase distribution premium upsell for products when Yoast SEO WooCommerce plugin is not activated.
* We don't show the upsell in WooCommerce product pages when Yoast SEO WooCommerce plugin is activated. This is because the premium assessments of the upsell are already loaded even when the Premium …
> PC-148 Make word complexity and keyphrase distribution premium upsell is available for products

- packages/yoastseo/spec/markers/addMarkSpec.js
- packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
- packages/yoastseo/src/markers/addMarkSingleWord.js
*
* Fixes a bug where the keyphrase density assessment errors, or fails to mark the found keyphrases in the text, when using keyphrases that include some regular expression control characters, for example brackets.
* [wordpress-seo-premium] Fixes a bug where the keyphrase distribution assessment errors, or fails to mark the found keyphrases in the text, when using keyphrases that include some regular expression control characters, for example brackets.
* [shopify-seo] Fixes a bug where the keyphrase density and keyphrase distribution assessments error, or fails to mark the found keyphrases in the text, when using keyphrases that include some regular expression control characters, for example brackets.
*
This PR can be acceptance …
> PC-160 - Fixes marking words in text for strings that contain regex control characters

- packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
- packages/yoastseo/spec/languageProcessing/languages/en/ResearcherSpec.js
- packages/yoastseo/spec/languageProcessing/languages/en/helpers/checkIfWordIsComplexSpec.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
- packages/yoastseo/src/languageProcessing/languages/en/config/internal/wordComplexity.js
- packages/yoastseo/src/languageProcessing/languages/en/helpers/checkIfWordIsComplex.js
- packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
*
* [wordpress-seo-premium] Excludes the plural version of frequent words in English from being marked as complex.
* [wpseo-woocommerce] Excludes the plural version of frequent words in English from being marked as complex.
* [shopify-seo] Excludes the plural version of frequent words in English from being marked as complex.
* In this PR, we also move the helper to check if a word is complex to the language folder. This is because the way we check for a complex word might differ between languages.
* In this PR, we only address the regular plural forms with -s suffix.
Requirement:
* Set the site language to English (currently Word complexity assessment is only available …
> PC-154 exclude plurals of non complex nouns from the word complexity assessment

- packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
- packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
- packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
- packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
- packages/yoastseo/spec/languageProcessing/helpers/sanitize/quotesSpec.js
- packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
- packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
- packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/src/languageProcessing/helpers/sanitize/quotes.js
- packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
- packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
* There were different results for some readability assessments (such as passive voice) between editors. The reason was that not all different quotation marks were supported by the SentenceTokenizer, and that the ampersand (&) was processed differently between different editors. This issue resolves this by adding support for more quotation marks and removing all versions of the ampersand from the text.
* Improves the text analysis by adding curly (“”) and angular quotation marks («»).
* Improves the text analysis by filtering out all versions of the ampersand (&).
* [yoastseo] Improves the SentenceTokenizer performance by adding curly (“”) and angular quotation marks («»).
* [yoastseo] Adds the html code (&amp) for the ampersand …
> Pc 43 fix discrepancies between elementor classic editor v2

- packages/js/src/components/contentAnalysis/SeoAnalysis.js
- packages/js/src/helpers/addCheckToChecklist.js
* We want to change the label `SEO Analysis` to `Premium SEO Analysis` both in the post sidebar and in the metabox when Yoast SEO Premium is activated.
* Changes `SEO Analysis` label to `Premium SEO Analysis` when Yoast SEO Premium is activated.
*
* Be sure to have Yoast SEO Premium installed but *not* activated
* Edit a post, and check that:
* in the block editor sidebar, `SEO Analysis` label is present
* in the Yoast metabox and Yoast sidebar, both `SEO Analysis` and `Premium SEO Analysis` sections are present (the second one being an upsell):
* Now Activate Yoast SEO Premium
* Edit a post, and check that:
* in the block editor sidebar,  `Premium SEO Analysis` label is …
> Rename SEO Analysis to Premium SEO Analysis when Premium is active

- packages/analysis-report/src/AnalysisResult.js
- packages/components/src/insights-card/InsightsCard.js
- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
- packages/js/src/insights/components/estimated-reading-time.js
- packages/js/src/insights/components/flesch-reading-ease.js
- packages/js/src/insights/components/text-length.js
*
* Adds a note to the readability analysis that tells users that the Flesch reading ease score has moved to the insights section.
*
* Open the readability analysis in the metabox.
* Confirm that below the assessments, a paragraph with the following text is shown: `Curious to see the [Flesch reading ease] score of your text? We’ve moved it to our [Insights] section.`
* Confirm that the first link leads to the page on Flesch reading ease on [yoast.com](http://yoast.com/), including the tracking parameters.
* Confirm that clicking on the second link scrolls to the Flesch reading ease score in the Insights section.
* Repeat the above steps for the …
> Added note to the readability analysis that tells users that the Flesch reading ease score has moved to the insights section.

- admin/class-expose-shortlinks.php
- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
*
* Fixes a bug where the link to the insights section inside of the "Flesch reading ease has moved" notification inside of the sidebar would not link to the insights modal in the sidebar, but to the insights section in the metabox instead.
* Splits up the shortlinks used in the "Flesch reading ease has moved" notification to one used in the metabox and one used in the sidebar.
* Changes the copy of the "Flesch reading ease has moved" notification when insights are disabled.
*
* Create a post (in the default block editor).
* Open the readability analysis results in the Yoast sidebar.
* Click on the "Insights" link inside of the "Flesch reading ease has moved" …
> Fix insights link in sidebar

- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
- packages/js/src/helpers/assessmentUpsellHelpers.js
- packages/yoastseo/spec/helpers/getLanguagesWithWordComplexitySpec.js
- packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
- packages/yoastseo/src/helpers/getLanguagesWithWordComplexity.js
- packages/yoastseo/src/helpers/index.js
- packages/yoastseo/src/languageProcessing/index.js
*
* [yoastseo] Adds a helper to return the supported languages for Word complexity assessment.
* [wpseo-woocommerce] Makes the Word complexity assessment upsell not show in product pages and taxonomies for unsupported languages.
* [wordpress-seo-premium] Makes the Word complexity assessment upsell not show in all content types for unsupported languages.
* Makes the Word complexity assessment upsell not show in all content types for unsupported languages.
*
* Set the site language to any language other than English
* Create a post with at least 50 characters
* Go to Readability analysis and confirm that the greyed out upsell for Word …
> PC-198 only show word complexity upsell for languages that support word complexity

- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
*
* Fixes a bug where the insights link does not work in the Elementor editor.
*
* Create or open a post in the Elementor editor.
* Navigate to the readability analysis results.
* in the "Flesch reading ease has moved" notification, click in the link labeled "Insights".
* The Insights modal should open.
* Also test the link in the classic editor, block editor, Gutenberg. 
* Test the link found in the sidebar as well as the metabox where applicable.
*
*
Fixes https://yoast.atlassian.net/browse/PC-203
> Fixed insights link in Elementor editor.

- packages/js/src/integrations-page.js
- packages/js/src/integrations-page/integrations-grid.js
- packages/js/src/integrations-page/tailwind-components/card.js
- packages/js/src/integrations-page/tailwind-components/integrations-grid.js
- src/actions/integrations-action.php
- src/integrations/admin/integrations-page.php
- src/routes/integrations-route.php
* We want to improve the UX of the integrations page.
* Fixes some UX issues for the Integrations page.
* Also removes an unused `check_capability` route
* Also uses Heroicons components instead of inline SVGs
* Also moves the IntegrationsGrid (and related components) outside the `tailwind-components` folder since they're not candidates to be included in the UI library anytime soon (while Card might be)
* An empty div with `wp-header-end` class has been added on top of the integrations page to let the notifications attach to it, instead of attaching to the `<h1>` title messing up the layout.
* Check https://yoast.atlassian.net/browse/PC-218 and see all the remaks have …
> PC- 218 Integrations page UX improvements

- src/generators/schema-generator.php
- tests/unit/generators/schema-generator-test.php
* Currently, running [this article](https://yoast.com/trusted-web-timestamping-content/) through the Schema validator shows several different pieces, when it should be parsing as one piece. Outputting the most important thing first (`Article`, if applicable, otherwise `WebPage`) fixes that.
* Change the order in which Schema nodes are output from `Organization / Person > WebSite > WebPage > Article` to `Article > WebPage > WebSite > Organization / Person`. This fixes validation issues for the Schema validator and puts the most important Schema content first.
* See that the output order of Schema pieces changes, and nothing else.
> Change order of schema pieces to ensure parsing as one graph

- admin/metabox/class-metabox.php
- inc/class-wpseo-custom-fields.php
- packages/js/src/containers/SnippetEditor.js
- packages/js/src/redux/actions/snippetEditor.js
- packages/js/src/redux/controls/dismissedAlerts.js
- packages/js/src/redux/controls/index.js
- packages/js/src/redux/controls/snippetEditor.js
- packages/js/src/redux/reducers/snippetEditor.js
- packages/js/tests/containers/SnippetEditor.test.js
- packages/replacement-variable-editor/src/ReplacementVariableEditor.js
- packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
- packages/replacement-variable-editor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
- packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
- src/integrations/third-party/elementor.php
- src/routes/meta-search-route.php
* Instead of loading all custom fields at once dynamically load them when searching for replacement variables.
* Fixes a performance issue in the meta description editor that would occur when very large amounts of custom fields were used.
* Create a very large amount of custom fields:
```
$post_id = YOUR_POST_ID;
for ( $i = 0; $i < 99999; $i++ ) {
add_post_meta( $post_id, wp_generate_password(), wp_generate_password() );
} 
```
* Open that post in your editor.
* Editing the meta description field should not be laggy.
* You should find all sorts of different custom fields if you start typing after using `%` to create a replacement variable.
* Note that custom field …
> [PC-214] Dynamically load custom fields instead of loading all at once

- packages/yoastseo/spec/languageProcessing/languages/de/helpers/checkIfWordIsComplexSpec.js
- packages/yoastseo/src/languageProcessing/languages/fr/helpers/checkIfWordIsComplex.js
*
* Fixes a bug where the word complexity assessment for French gave inconsistent results when the text contains words of length 8 with contractions, like _l'histoire_.
* Single quotes are normalized before trying to remove contractions.
* Set your site's language to French.
* Create a post in either the block editor or the classic editor.
* Add a text to the post that contains one or multiple words of 8 characters with a contraction (for example _l'histoire_ -> where _histoire_ = 8 characters).
* Check and note down the result of the word complexity assessment.
* Save the post.
* Install and activate the Elementor plugin.
* Open the post you just created in the Elementor …
> Normalize single quotes before removing contractions in the French word complexity assessment.

- src/helpers/url-helper.php
- src/integrations/front-end/redirects.php
- tests/unit/helpers/url-helper-test.php
- tests/unit/integrations/front-end/redirects-test.php
* We want to prevent the `Url_Helper::recreate_current_url` method to trigger warnings.
* Fixes a bug where an `Undefined index: SERVER_NAME` warning would be triggered in cronjobs or WP CLI commands.
* Moved the date redirect method to the `template_redirect` instead of `pre_get_posts` to avoid affecting all the queries.
* in Search Appearance, disable the Date Archives.
* execute `wp post get 1` in a command line
* if you're using Rancher/Docker environment:
* in the terminal, go to the plugins development environment base dir (`plugin-development-docker`)
* run `docker ps` and copy the name of the container running WordPress ( e.g. `basic-wordpress` ) from the `NAMES` …
> PC-221 fix SERVER_NAME warning

- packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
Replace action with a filter to add additional draft-js-plugins to the plugin list.
*
* Adds support for providing additional draft js plugins via a filter.
* N/A
* N/A
*
*
Fixes #
> Replace action with a filter to add additional draft-js-plugins

- packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
- packages/yoastseo/src/languageProcessing/researches/getProductIdentifierData.js
- packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
* The assessment was partially implemented in this [PR](https://github.com/Yoast/wordpress-seo/pull/18609). In this PR, we enable the assessment for WooCommerce as well as add a grey bullet condition to the assessment. In the accompanying [WooCommerce PR](https://github.com/Yoast/wpseo-woocommerce/pull/789), the data used for scoring on this assessment is retrieved and passed to the Paper.
* [wpseo-woocommerce] Adds a new assessment which checks whether products (or product variants) have an identifier.
* [yoastseo] Enables the Product identifiers assessment in WooCommerce.
* [yoastseo] Adds a condition to the assessment that returns a grey bullet when the product variant data is not valid.
* …
> Enable the product identifiers assessment in WooCommerce

- inc/class-wpseo-admin-bar-menu.php
- src/conditionals/front-end-inspector-conditional.php
* Put the front-end inspector behind a feature flag.
* Puts the front-end inspector behind a feature flag.
*
* Test with [this Premium PR](https://github.com/Yoast/wordpress-seo-premium/pull/3618).
*
*
Fixes https://yoast.atlassian.net/browse/PC-278
> Put front-end inspector behind feature flag.

- css/src/toggle-switch.css
- css/src/yst_plugin_tools.css
*  Fixes alignment issues of elements on pages with a switch-container.
* Fixes alignment issues of elements on pages with a switch-container.
* Hides the 'clear' div only when its an upsell 'switch-container'.
* Adds word-wrap to 'label.select' else the text would go underneath the select field if the label was too long.
* SEO - Search Appearance:
* Verify the 'description' of 'Force rewrite titles' is on a new line.
* Breadcrumbs:
* The select label is now word wrapping instead of going underneath the select field if the label is too long.
* Social - Facebook & Twitter
* Verify the 'description' is on a new line.
* Local SEO:
* Visit Local SEO and verify the alignment …
> PC-273 - 19.4 Yoast SEO: styling issues

- packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
* Replacement variable application in the Google preview or `SnipperEditor` component needs to be more flexible to fit the needs of different products.
* [@yoast/search-metadata-previews] Adds a prop to the `SnippetEditor` for overriding default replacement variable application.
* Implemented the most flexible solution possible: either leave it to the component to handle replacement variable application based on the `replacementVariables` prop or take over the functionality completely using the new `applyReplacementVariables` prop.
* In `packages/js/src/containers/SnippetEditor.js`, in the `SnippetEditorWrapper` component, add a dummy `applyReplacementVariables` prop like …
> Add apply replacement variables prop to google preview

- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- composer.json
- inc/language-utils.php
- packages/components/src/image-select/ImageSelect.js
- packages/js/src/components/CompanyInfoMissing.js
- packages/js/src/components/ImageSelectComponent.js
- packages/js/src/components/PersonImageFallbackInfoMissing.js
- packages/js/src/components/portals/ImageSelectPortal.js
- packages/js/src/components/portals/PersonImageFallbackInfoPortal.js
- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/base/image-select.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/organization-section.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/person-section.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
- packages/js/src/initializers/search-appearance.js
- src/context/meta-tags-context.php
- src/integrations/admin/first-time-configuration-integration.php
- tests/unit/inc/language-utils-test.php
This adds functionality to display the site logo and name in the search appearance and first time configuration.
These values are already represented in the schema.
*
* Adds the site logo and name as default values in the first time configuration and search appearance.
* Added 'fallback images' to the image components to make sure you cannot remove these.
*  In search appearance with organization selected, `without` a logo set in the customizer:
*  	You should see no placeholder image. and in the front-end there should not be any schema for `"@type": "Organization",`
* 	You should see a placeholder text in the organization name
*   Select a logo and save. The logo should …
> PC-59 Adds support for organization / person fallback image.

- admin/pages/dashboard.php
* We want to hide "Save changes" button in the integrations tab
* Hides the "Save changes" button in the "Integrations" tab in the "Yoast SEO  > General" page.
*
* Visit Yoast SEO > General
* navigate to the Integrations tab and check that the "Save changes" button is not visible
*
* check the Integrations page to see which Integrations are active (among the toggleable ones)
* go back to the General Page and click on Save changes
* check once again the Integrations page and see that the same integrations are enabled.
Fixes [PC-297]
[PC-297]: …
> PC-297 Hide submit button in integrations tab

- packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeEstimatedReadingTimeSpec.js
- packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
- packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeEstimatedReadingTime.js
- packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeString.js
- packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
- packages/yoastseo/src/languageProcessing/researches/findKeywordInFirstParagraph.js
- packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
* The text from the estimated reading time block was taken into account during the analysis, which led to a bug (for example, in Keyphrase in Introduction). This PR fixes that bug by excluding the estimated reading time block from the analysis.
* [yoastseo] Excludes Table of Contents from the analysis.
* [wordpress-seo-premium] Excludes the Table of Contents block from the SEO and readability analysis.
* A helper to exclude the Estimated Reading time is created.
1. Run yarn test and make sure that all tests pass
2. Build the Free and Premium plugin (run `composer require yoast/wordpress-seo:dev-PC-162-exlude-estimated-reading-time-new@dev` in Premium before building) …
> PC 162 Exclude estimated reading time from the analysis

- packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
* This PR fixes a small change done by [this one](https://github.com/Yoast/wordpress-seo/pull/18689).
* [yoastseo] Restores the `unifyNonBreakingSpace` santization step in `getSentences.js`.
* Removing `unifyNonBreakingSpace` from `getSentences.js` caused a unit test to fail. So it was deemed better to return it back. 
* The test instructions are the same as in the other PR for [fixing eye highlighter not highlighting text that includes the &nbsp; character](https://github.com/Yoast/wordpress-seo/pull/18689).
*
*
Fixes #
> Fix eye highlighter not working for text containing the &nbsp; character 2nd edition

- admin/metabox/class-metabox.php
* Handles the initial load of custom field replace vars when no indexable exists.
* Fixes a bug where a PHP notice is thrown when creating a new post in the classic editor.
* See https://yoast.atlassian.net/browse/QA-3588
* The initial load of custom field replace vars.
Fixes https://yoast.atlassian.net/browse/QA-3588
> Handle getting custom fields replace vars when no indexable exists

- inc/options/class-wpseo-option-wpseo.php
* Algolia should be disabled when disallowed at network level
* Fixes an unreleased bug where the Algolia integration would be enabled even if not allowed at network level.
*
* Activate Free and Premium on multisite
* install the Algolia plugin
* visit the network admin and disable the Algolia integration at network level
* visit the Integrations page in one of the subsites and check that the Algolia integration looks disabled (with a toggle that you can't act on)
*
*
Fixes [PC-314]
[PC-314]: …
> PC-314 Set Algolia as disabled when not allowed at network level

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
* The behaviour of the site presentation select box had different behaviour in the search appearance and FTC.
* Aligns behaviour in First time configuration with search appearance.
* N/A
* Create a clean install. Enable free and enter the FTC. On the site representation step the `organization` select should be preselected.
* Select `person` and save. Reload. Person should still be active.
* Go to search appearance. Change it back to `organization`. Go to the FTC and check if `organization` is selected
*
*
Fixes #
PC-320
> PC-320 Aligns behaviour in FTC with search appearance

- src/integrations/settings-integration.php
* Revert settings UI from requesting user data on page load because it will fail on sites with a lot of users.
* Fix an unreleased bug where the new settings UI would request user data on page load, which can fail on sites with a lot of users.
*
* Visit the new settings UI with JS console open.
* Verify in JS console that `wpseoScriptData.users` does not exist anymore.
* Verify on site with a lot of users that page loads normally.
*
*
Fixes #
> Remove user data request from settings integration

- .github/workflows/integrationtest.yml
- tests/unit/bootstrap.php
- tests/unit/inc/addon-manager-test.php
- wp-seo-main.php
- wp-seo.php
*
*  Sets the minimum supported WordPress version to 5.9.
* 
* N/A
* N/A
*
Fixes [PC-340]
[PC-340]: https://yoast.atlassian.net/browse/PC-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set minimum WP version to 5.9

- packages/js/src/analysis/blockEditorData.js
- packages/js/src/analysis/classicEditorData.js
* Prevents images from being loaded every time the content changes even if it's from cache.
* Fixes an issue where image elements would lead to repeated requests for that image source while editing content.
* `jQuery.parseHTML` is used as this does not instantiate an image element in the same way that `jQuery` directly does ( at least based on my testing, please validate during your own testing ).
* Add an image.
* Open the network tab of your browser console.
* Edit the content of your posts with small breaks in between edits for the debounce to trigger.
* You should not see repeated requests for the image you've added in the network tab. …
> Do not continually load images when the content changes

- packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
- src/routes/meta-search-route.php
* Custom replacement variables suggestions not showing in the Yoast metabox description.
* Fixes an unreleased bug where custom replacement variables suggestions are not shown in the Yoast metabox description field.
* The number of suggestions displayed has been raised to 25.
* Add some custom replacement variables to a post:
```$post_id = YOUR_POST_ID;
for ( $i = 0; $i < 30; $i++ ) {
add_post_meta( $post_id, "my_custom_" . $i, "my_custom_" . $i );
} 
```
This snippet of code creates 30 meta fields named `my_custom_0` - `my_custom_29`
(use the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin to conveniently execute the code snippet once)
* Open that …
> Pc 339 replacement fields suggestions not showing in metabox description field

- admin/class-admin-init.php
- packages/js/src/admin-global.js
- src/integrations/watchers/search-engines-discouraged-watcher.php
- src/presenters/admin/search-engines-discouraged-presenter.php
- tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
- tests/unit/presenters/admin/search-engines-discouraged-presenter-test.php
* The search engines notice that is shown when indexability is disabled in the WordPress settings is not yet shown in the Problems section of the Yoast SEO dashboard.
* Adds a "Search engines discouraged" notification in the Yoast SEO dashboard when indexability is turned off in WordPress settings.
* Rewritten `wpseoSetIgnore` to not use a jQuery.post but instead use a fetch in order to be able to return the `Promise` and add an action after this `Promise` has been resolved.
* Install and activate Yoast SEO and the Yoast SEO Test Helper.
* Go to the administration dashboard.
* Go to `Settings` -> `Reading`.
* Enable `Discourage search engines from indexing this site`.
In …
> PC-46 Add the search engines discouraged notice to the notification dashboard

- inc/sitemaps/class-post-type-sitemap-provider.php
https://github.com/Yoast/wordpress-seo/pull/16630
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlwpseo-143
Allow to filter the first links of the post type sitemap provider. The first link is either for the home page or the CPT archive page.
This is needed for WPML in order to pass the related secondary languages page.
Ex:
-> https://domain.com/
-> https://domain.com/fr/
-> https://domain.com/de/
Or:
-> https://domain.com/city/
-> https://domain.com/fr/ville/
-> https://domain.com/de/stadt/
* Introduces a new filter `wpseo_sitemap_post_type_first_links` that can be used to add 
Currently, WPML is adding some output at the end of the rendered sitemap, but this was done a long time ago. Now we would like to enhance the …
> Introduce the filter `wpseo_sitemap_post_type_first_links`

- admin/class-meta-columns.php
- admin/taxonomy/class-taxonomy-columns.php
- css/src/adminbar.css
- inc/class-wpseo-admin-bar-menu.php
- inc/class-wpseo-utils.php
- packages/js/src/components/contentAnalysis/mapResults.js
- packages/js/src/ui/adminBar.js
- src/helpers/robots-helper.php
- src/helpers/score-icon-helper.php
- src/presenters/score-icon-presenter.php
- tests/integration/test-class-wpseo-utils.php
- tests/unit/helpers/robots-helper-test.php
- tests/unit/helpers/score-icon-helper-test.php
- tests/unit/presenters/score-icon-presenter-test.php
* Fixes an unreleased bug where the Frontend Inspector score indicators were not matching up with the admin bar' and the overview' score indicators. This highlighted some more inconsistencies which are now (mostly) addressed. Key thing to note is that within the editor, the indicators all show the outcome of the analysis that just ran. Meaning mostly: no `noindex` indication.
* Fixes a bug where the score indicators of the overview pages and admin bar where inconsistent. The taxonomy overview and admin bar score indicators now uses red to indicate `Focus keyphrase not set`. The admin bar score indicator now shows blue when set to `noindex`.
* Fixes a bug where the score indicator in the classic editor would not update the …
> Frontend inspector: fix inconsistent color indicators

- lib/model.php
* Stabilize code for use in tests
* Stabilize code for use in tests
When the `Model` class is mocked, the `__debugInfo()` magic method is not mocked. This can (and will) lead to fatal errors along the lines of:
```
Warning: Uncaught Error: Call to a member function as_array() on null in path/to/wpseo-premium/vendor/yoast/wordpress-seo/lib/model.php:574
Fatal error: __debuginfo() must return an array in path/to/wpseo-premium/vendor/yoast/wordpress-seo/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 933
```
While maybe not needed during "normal" run-time, this small tweak prevents these errors and allows the tests to run properly on higher PHP/higher PHPUnit combinations.
This PR can be …
> Lib\Model::__debugInfo(): work-around for Mockery

- packages/js/src/containers/SnippetEditor.js
- packages/js/tests/containers/SnippetEditor.test.js
* Ensures that finding custom fields is only done after a user finishes typing.
* Fixes an unreleased performance issue where requests to find custom fields would be sent for every keystroke.
* Edit a post
* Open the Yoast metabox.
* In the meta description editor open a replacement variable by typing `%` and then type very fast.
* In the network tab you should only see a single request half a second after you finish typing.
* This should be tested in Gutenberg and classic editor.
* Finding custom fields in replacement variable editors in the post edit ( classic & Gutenberg ).
> Memoize the find custom fields function to prevent duplicate requests

- packages/js/src/components/contentAnalysis/mapResults.js
*
* Fixes an unreleased bug where the score indicators in the editor would be gray instead of red.
*
* Create a post with several sentences
* Check SEO/Readability scores indicators
*
*
Fixes https://yoast.atlassian.net/browse/PC-363
> Fix the wrong color of SEO/Readability scores indicators on post edit screen

- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
* We want to have different feedback strings for 'Third World' and 'Third World country'. However, 'Third World country' would trigger both of the feedbacks strings. This PR fixes it so that only the specific string for 'Third World country' is shown in those cases.
* Fixes an unreleased bug where to inclusive language feedback strings would be shown for 'Third World country' instead of one.
* [yoastseo] Adds a rule to the inclusive language feedback string for 'Third World' so that it's not shown when 'Third World' is followed by 'country.
*
* Enable Yoast SEO Free and Premium
* Enable the Inclusive language feature
* Create a post and add 'I live in a Third World …
> Inclusive language: show only one feedback string for 'Third World country'

- packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
- packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
* Inside `SentenceTokenizer.js`, we have a check whether the previous token is a period when the current token is a quotation mark:
> `if ( this.isQuotation( token.src ) && previousToken.src !== "." ) {`
* However, it's possible that the quotation mark occurs at the beginning of a text/block, hence the `previousToken` would be undefined.
* Fixes a bug where a text starting with a double quotation mark followed by a space(s) broke the analysis.
* [shopify-seo] Fixes a bug where a text starting with a double quotation mark followed by a space(s) broke the analysis.
* I added an extra check for previousToken in this line:
`if ( this.isQuotation( token.src ) && previousToken && previousToken.src !== "." ) {`
* The extra check is …
> PC-362 fix tokenizing quotation

- packages/js/src/components/contentAnalysis/Results.js
*
* Fixes SEO title, meta description or slug field not being focused when the Google Preview collapsible in the metabox is closed and a user clicks on an respective edit button next to an assessment.
*
* Create or open a post.
* Enter a focus keyphrase.
* Leave or make the SEO title and meta description empty, and make sure that the post's slug does not contain the focus keyphrase.
* Close the Google Preview collapsible inside of the metabox.
* In the SEO analysis results inside of the metabox, click on edit button next to the result of the _Keyphrase in SEO title_ assessment.
* This should open the previously closed Google Preview collapsible and focus the SEO title …
> PC-375 - When the google preview tab is closed a console error appears and the actionable buttons dont work

- inc/class-addon-manager.php
- src/schema-templates/cooking-time.block.php
- src/schema-templates/preparation-time.block.php
* Minor security improvement
* Minor security improvement
HTML attributes should be escaped using `esc_attr*()` functions, not `esc_html*()`.
URLs in HTML attributes should be escaped using `esc_url()` functions, not `esc_attr()`.
* _N/A_ Functionally, there should be no noticeable difference
> QA: fix incorrect output escaping

- admin/class-yoast-form.php
* Security hardening
* Security hardening
Always escape the complete value of an attribute in one go.
* _N/A_ Functionally, there should be no noticeable difference
> QA: fix some incorrect output escaping

- src/builders/indexable-post-builder.php
- src/integrations/front-end/robots-txt-integration.php
- src/integrations/third-party/wordproof.php
- src/presenters/score-icon-presenter.php
- tests/unit/presenters/score-icon-presenter-test.php
* Improves compatibility with PHP 8.0
* Improves compatibility with PHP 8.0
Follow up on the previously addressed list of reserved keywords being used as param names.
This fixes a number of newly introduced issues.
* _N/A_
> QA: no reserved keyword as function parameter names

- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
* We previously returned a red bullet when the text contained 'disabled parking' and 'disabled toilet' and suggested 'accessible parking/toilet' as the alternative. While that is a slightly more inclusive alternative, it was found during using testing that 'disabled parking' and 'disabled toilet' are widely used within the disability community. For that reason, we decided to not target these phrases anymore.
* We target the word 'handicap', as well as the phrases 'handicap parking', 'handicap toilet', 'handicap bathroom', 'handicap stall'. The phrases previously also triggered the feedback for 'handicap'. This PR fixes it so that the string for 'handicap' doesn't appear for those phrases.
* Since 'sociopath' can be used informally in a medical sense, we add to the feedback string that it …
> Fixes and improvements for inclusive language feedback

- packages/js/src/components/contentAnalysis/Results.js
*
* Fixes a bug where the Google preview collapsible was closed when clicking on an edit button when the collapsible was open.
*
* Create or open a post.
* Enter a focus keyphrase.
* Leave or make the SEO title and meta description empty, and make sure that there is a slug that does not contain the focus keyphrase.
* Open the Google Preview collapsible inside of the metabox, or leave it open if it already is.
* In the SEO analysis results inside of the metabox, click on edit button next to the result of the _Keyphrase in SEO title_ assessment.
* This should focus the SEO title field.
* Close the Google preview collapsible.
* In the SEO analysis results inside of the …
> Check if Google preview collapsible is closed before clicking on it.

- src/deprecated/src/integrations/third-party/elementor.php
`parent::method_name`-like callbacks are only partially supported by PHP. With this mind, they will be deprecated in PHP 8.2, with support being completely removed in PHP 9.0.
Fixed by changing it to a fully supported syntax.
Note: while this issue is not covered by tests, as this is a deprecated class, I'm not going to bother with adding tests.
Refs:
* https://wiki.php.net/rfc/deprecate_partially_supported_callables
* _N/A_
> PHP 8.2 | Elementor_Exclude_Post_Types: fix for partially supported callback

- admin/class-yoast-notification-center.php
As things were, the callback which was being created would have the following form:
```
["Yoast_Notification_Center", "Yoast_Notification_Center::add_notification"]
```
Take note of the class name also being prepended to the method name.
This is due to the use of the `__METHOD__` magic constant, which includes the class name already. By changing this to `__FUNCTION__`, the method name _without_ the class name is returned.
As this type of callback is only partially supported by PHP, will be deprecated in PHP 8.2, with support being completely removed in PHP 9.0, fixing this seems prudent.
The integration test suite runs into this issue in the test …
> PHP 8.2 | Yoast_Notification_Center: bugfix for partially supported callback

- tests/unit/builders/indexable-home-page-builder-test.php
- tests/unit/conditionals/estimated-reading-time-conditional-test.php
- tests/unit/helpers/wpdb-helper-test.php
- tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
- tests/unit/presenters/meta-author-presenter-test.php
- tests/unit/services/importing/importable-detector-service-test.php
> PHP 8.2 | Various Tests: explicitly declare all properties

- src/surfaces/classes-surface.php
> PHP 8.2 | Classes_Surface: explicitly declare all properties

- src/helpers/import-cursor-helper.php
> PHP 8.2 | Import_Cursor_Helper: explicitly declare all properties

- tests/unit/presentations/indexable-static-posts-page-presentation/presentation-instance-builder-trait.php
- tests/unit/services/importing/aioseo-robots-transformer-service-test.php
> PHP 8.2 | Tests: bug fix - typo in property name x 2

- config/dependency-injection/deprecated-classes.php
- config/dependency-injection/renamed-classes.php
- config/dependency-injection/services.php
- src/deprecated/src/conditionals/front-end-inspector-conditional.php
* Adds the deprecated front end conditional to the DI container so it can still be used by old versions of premium.
* Fixes a fatal error when the Yoast SEO 19.5 was used with an older version of Yoast SEO Premium.
* Adds the `deprecated-classes.php` to easily do the same for future deprecated classes.
* Install Yoast SEO 19.5.1 and Yoast SEO Premium 19.0. There should be no fatals.
* Running Yoast SEO with an older version of Yoast SEO Premium.
> Add the deprecated front end inspector conditional to the DI container

- packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
- packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
*
* The SKU and Product identifier assessments are now shown for simple products only when they have a price set.
*
**Note for acceptance testers**: Test this PR together with https://github.com/Yoast/wpseo-woocommerce/pull/806 in WooCommerce SEO. Link the WooCommerce SEO branch with this branch by running this command in WooCommerce SEO and building the WooCommerce SEO plugin as normal:
```
composer require yoast/wordpress-seo dev-PC-385-do-not-show-sku-or-product-identifier-assessments-when-a-simple-product-does-not-have-a-regular-price@dev
```
* Create a product in WooCommerce
* Confirm that the SKU and Product identifier assessments do not show up in the SEO analysis …
> PC-385 - Do not show SKU or product identifier assessments when a simple product does not have a regular price

- src/presentations/archive-adjacent-trait.php
- src/presentations/indexable-author-archive-presentation.php
- src/presentations/indexable-home-page-presentation.php
- src/presentations/indexable-post-type-archive-presentation.php
- src/presentations/indexable-term-archive-presentation.php
- tests/unit/presentations/archive-adjacent-test.php
- tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/indexable-date-archive-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/indexable-home-page-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/indexable-static-posts-page-presentation/presentation-instance-builder-trait.php
- tests/unit/presentations/presentation-instance-dependencies-trait.php
> PHP 8.2 | Indexable_*_Presentation: explicitly declare all properties

- packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
- packages/yoastseo/spec/languageProcessing/researches/getProductSKUDataSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
- packages/yoastseo/src/languageProcessing/researches/getProductIdentifierData.js
- packages/yoastseo/src/languageProcessing/researches/getProductSKUData.js
- packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
* When a variable product had no variants, the analysis treated the product as a simple product. 
* Fixes a bug where variable products were treated as simple products if they had no variants.
* [wpseo-woocommerce] Fixes a bug where variable products were treated as simple products if they had no variants.
* We added checks for `product type` and decide if (and which) feedback to show based on it. Note that Shopify might have different/no product types. 
* This PR also required changes in woocommerce. These changes are in [this pr](https://github.com/Yoast/wpseo-woocommerce/pull/811)
**NOTE:** make sure to pull and build both yoastse-woocommerce and yoastseo-free.
* …
> PC-395-wpseo-variable-products-show-wrong-feedback-when-variants-are-deleted-in-woo

- packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
*
* [wordpress-seo-premium] Makes the inclusive language green bullet feedback link open in new tab.
*
* Activate Premium 
* Activate the Inclusive language feature
* Open a new post that receives a green bullet for Inclusive language
* Go to the inclusive language tab
* Click on the link behind `Inclusive language` in the feedback text
* Confirm that the link opens in a new tab
*
*
Fixes #https://yoast.atlassian.net/jira/software/c/projects/PC/boards/138?modal=detail&selectedIssue=PC-399
> Make the inclusive language green bullet feedback link open in new tab

- packages/js/src/components/fills/SidebarFill.js
- packages/js/src/elementor/components/fills/ElementorFill.js
When the inclusive language tab was added, the position of the ‘Track SEO performance’ tab in the sidebar and in Elementor was changed. This PR puts it back to where it originally was. 
* Fixes the wrong position of the ‘Track SEO performance’ tab in the sidebar and in Elementor.
* There is an accompanying Premium PR: https://github.com/Yoast/wordpress-seo-premium/pull/3650 
* Open a post in Default editor
* Confirm that the order of tabs in the Yoast SEO sidebar is the same as in the screenshot:
* Activate Gutenberg plugin and confirm that the order of tabs is still the same
* Activate Elementor and open a post in Elementor. 
* Confirm that the order of the tabs is still …
> Fix the wrong position of the ‘Track SEO performance’ tab

- packages/js/src/helpers/firstImageUrlInContent.js
* This prepares our elementor integration for if ever tinymce changes the way the handle the content. If that happens we don't want to start loading every image.
* Changes the way the elementor data collection handles images
*
*  Add an image to a post and check if the `Image Keyphrase` assessment shows up
* Add an alt tag to the image and check if the `Image Keyphrase` assessment shows Images on this page have alt attributes, but you have not set your keyphrase. or another version of the assessment where alt tags are available
*
*
Fixes #
> PC-335 Fix image requests in elementor

- admin/class-inclusive-language-notice.php
*
* Changes the Inclusive language notification such that it is only shown when Premium version 19.2-RC1 or above is installed.
* Changes the text of the Inclusive language notification to emphasize that this is a beta feature that is disabled by default.
Note: this notification [will be removed in the next release again](https://yoast.atlassian.net/browse/PC-424).
* 
* Install and activate a Premium version before 19.2-RC1 (e.g. 19.1 or earlier).
* Go to the Yoast SEO notification center.
* You should not see the Inclusive language notification.
* Install and activate a Premium version after 19.2-RC1.
* Go to the Yoast SEO notification center.
* You should see the …
> PC-426 - Only show notification when Premium 19.2-RC1 or above is installed.

- packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
* Fixes an issue where starting to type a custom field that had a lot of matches in the replacement variable editors would cause scrolling behavior.
* See https://yoast.atlassian.net/browse/PC-421
*
Fixes https://yoast.atlassian.net/browse/PC-421
> Fix scrolling issue when many custom fields exist in the replacementvariable editor

- packages/js/src/initializers/post-scraper.js
* Since words in square brackets get removed from the analysis as shortcodes, there were false negatives in the Inclusive language assessment. This issue adds an improvement that make sure non-inclusive words get targeted even if they are in square brackets.
* Note that this PR is to a large part a duplicated of: https://github.com/Yoast/wordpress-seo/pull/18845 . It was created because the previous PR was based on the wrong branch.
* Includes words in square brackets to the analysis for multiple assessments in the block editor.
* [wordpress-seo-premium] Includes words in square brackets to the Inclusive language analysis in block editor.
* There will be a new issue created to cover words in less common brackets ( `<>` and `{}` ) …
> Include words in square brackets to the Inclusive language analysis for Block editor (release branch based)

- packages/js/src/indexables-page/components/indexables-links-card.js
- packages/js/src/indexables-page/components/indexables-score-card.js
- packages/js/src/indexables-page/indexables-page.js
- packages/js/src/indexables-page/landing-page.js
- src/actions/indexables-page-action.php
*
* Informs user of deactivated features in the indexables page
*
*
*
*
Fixes #
> Show alert informing user of disabled features

- packages/js/src/indexables-page/components/indexables-links-card.js
- packages/js/src/indexables-page/components/indexables-score-card.js
- packages/js/src/indexables-page/components/indexables-table.js
- packages/js/src/indexables-page/indexables-page.js
- packages/js/src/indexables-page/landing-page.js
- packages/ui-library/src/hooks/index.js
- packages/ui-library/src/hooks/use-media-query.js
- src/helpers/indexables-page-helper.php
- tests/unit/actions/indexables-page-action-test.php
* 2 column and single column view need different orders
* [ui-library] Adds a useMediaQuery hook that returns an object with a matches key.
* Changes the layout of the indexables page to a two-column layout if space permits, keeping the order logical. 
*
* Make the screen narrow and wide.
* On the indexables page, the order of elements should be
* in single column:
* seo score
* readability score
* least linked
* most linked
* in double column
* seo score * readability score
* links linked *most linked
> Add useMediaQuery hook to ui-library, use it to define single and double column view

- src/actions/indexables-page-action.php
- tests/unit/actions/indexables-page-action-test.php
*
* Only allow posts and pages in the indexables lists.
*
*
*
*
Fixes #
> Only posts and pages in the indexables lists

- src/presenters/admin/sidebar-presenter.php
*
* Fixes a bug where the `$url` variable in the `sidebar-presenter.php` was undefined.
*
* Activate Yoast SEO.
* Go to the administration dashboard and click on "Yoast SEO".
* Check that the premium upsell banner is still there (and uses the new styling).
*
*
Fixes #
> Fix undefined url variable and translation of h3 title

- inc/sitemaps/class-post-type-sitemap-provider.php
- tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
* Empty sitemaps should be excluded from the sitemap index (`/sitemap_index.xml`).
* Exclude empty custom post type sitemaps from `sitemap_index.xml`.
*
* Install and activate Yoast SEO and Custom Post Type UI.
* Add a custom post type by going to the WordPress administrator dashboard -> CPT UI -> Add/Edit Post Types.
* Add a custom taxonomy for the custom post type by going to CPT UI -> Add/Edit Taxonomies (make sure to add the taxonomy to the custom post type).
* Add a couple of posts, pages, categories, tags (and connect these to posts and pages), instances of the custom post type. and instances of the custom taxonomy to your WordPress installation.
* Check …
> Add ignore for sitemaps of a custom post type that have no posts

- admin/class-inclusive-language-notice.php
*
* [wordpress-seo-premium] Adds an accurate inclusive language notification for subsites with the Inclusive language feature disabled by admin
*
**On single site**
* Build free and premium
* Enter the main site
* Go to yoastseo > general > features and check that the Inclusive language feature is disabled by the admin
* Go yoastseo > general > dashboard
* Find the notification on Inclusive language, and confirm that it says `New in Yoast SEO Premium 19.2: Did you know that you can now get feedback on the use of inclusive language? This feature is disabled by default. [Learn more about this feature]`
**On multisite**
_Using subdirectories_
* Build a multisite installation …
> PC-413 Adapt inclusive language notification for subsites with feature disabled by admin

- admin/views/tabs/network/features.php
*
* Fixes an issue where the incorrect "read more" link was used in feature toggles for Premium features.
* 
* Startup a multisite WordPress environment.
* Go to the Network Admin.
* Make sure that Yoast SEO is installed and active.
* Go to the Yoast SEO feature toggle page (_Yoast SEO_ > _General_ > _Features_).
* Navigate to the Inclusive language feature toggle 
* Open the help description by clicking on the question mark next to the label.
* Hover over the link that is shown in the text `Discover why inclusive language is important for SEO.` in the description
* The link should point to https://yoa.st/inclusive-language-features-premium …
> PC-460 - Overwrite network feature toggle read more link with its premium version if it is a premium feature.

- packages/js/src/indexables-page/components/not-enough-analysed-content.js
- src/actions/indexables-page-action.php
*
* Adds a filter to specify which post types needs to be shown in the four tables
* Updates copy on `not-enough-analysed-content` page
*
*
*
*
Fixes #
> Pc 457 add a filter on post sub types

- .github/workflows/integrationtest.yml
- .github/workflows/lint.yml
- .github/workflows/unittest.yml
- composer.json
- composer.lock
Provide support for [`composer/installers`](https://github.com/composer/installers) versions 1 and 2, for peer dependencies that might require the latter.
* Provide support for `composer/installers` versions 1 and 2. Props to @mcaskill.
* Update version constraint on `composer/installers` dependency to support:
* `>=1.12.0 <2.0.0-0` or
* `>=2.0.0 <3.0.0-0`
1. Install WordPress plugin using Composer versions 1.10, 2.1, 2.2, 2.3, or later.
2. Validate that the plugin is installed in the expected directory as defined by the [install path](https://github.com/composer/installers#custom-install-paths) for the `wordpress-plugin` type. …
> Add support for composer/installers v1 and v2

- admin/class-yoast-form.php
*
* Fixes an unreleased bug that would cause escaped html instead of help buttons in the Yoast form.
* Quick fix for local.
* Have local and trunk, both built.
* Go to local settings.
* Buttons should not look like this:
* 
*
*
Fixes #
> Revert label encoding on yoast form

- packages/js/src/settings/initialize.js
* Fix typo for preloading homepage social image.
* Fixes a bug where the homepage social image would not be preloaded, causing its validation to fail.
*
* Check if you are unable to reproduce issue [PC-459](https://yoast.atlassian.net/browse/PC-458)
*
*
Fixes #
> Fix typo in homepage social image preload

- admin/class-inclusive-language-notice.php
*
* Fixes a bug where the "Learn more about this feature" link in the Inclusive language notification did not open in a new tab.
*
* Install and active Yoast SEO Premium.
* Make sure that the Inclusive language feature is off and your site language is set to English.
* You should see a notification in the Yoast SEO dashboard (_Yoast SEO_ > _General_ in the admin sidebar) that looks like this:
* Clicking on the second link ("Learn more about this feature") should open a new tab leading to yoast.com.
*
*
Fixes …
> PC-468 - Link in inclusive language notification now opens in a new tab.

- admin/formatter/class-metabox-formatter.php
- admin/metabox/class-metabox-analysis-inclusive-language.php
*
* [wordpress-seo-premium] Fixes a bug where the Inclusive language feature tab was shown when the installed version of Premium does not support Inclusive language.
*
* Install and activate Yoast SEO 19.6-RC9 and Premium 19.2-RC10
* Enable Inclusive language feature
* Confirm that the Inclusive language feature tab is shown
* Downgrade the Yoast SEO Premium version to 19.1
* Tips: If building a premium plugin, build it from `master` 
* Go to a post
* Confirm that the Inclusive language feature tab is still shown
* Install and activate Yoast SEO and Premium
* Tips: If building a premium plugin, run `composer require …
> PC-467 inclusive language tab is shown after downgrade

- inc/class-wpseo-image-utils.php
* Use the new core function wp_filesize (see https://github.com/WordPress/wordpress-develop/commit/7fc225aa87c80680df01a0a82e6bb94b7773a34c)
* Use the new WordPress `wp_filesize` function.
* Removed the warning and the `@todo`.
* Have an image larger than 2MB set as the Facebook image for a post.
* In the open graph data of that post the image used should be the same before and after this PR.
* Change the image to another one.
* This should also raise no fatal errors and the image shown afterwards in the meta data should be the same.
* Used to determine which image to use for open graph …
> Use wp_filesize instead of filesize

- packages/js/src/components/WordProofTimestampToggle.js
* we released the WordProof integration a while ago already, it’s time to remove the `new` label.
* Removes the `new` annotation from the WordProof toggle.
* None
* Enable the WordProof integration
* Go to /wp-admin/options-privacy.php and set a page to be your privacy policy page.
* Edit the page.
* Open the Advanced tab of the Yoast SEO metabox
* See that there is no `new` badge after `Timestamp with WordProof`
*
* The option exists in the metaboxes of all editors
Fixes #
> Remove 'new' badge from all wordproof toggles.

- src/actions/indexables-page-action.php
- tests/unit/actions/indexables-page-action-test.php
*
* Select only columns that are used for indexables
*
*
*
*
Fixes #
> Select only columns that are used for indexables

- src/loader.php
- tests/unit/loader-test.php
* This PR ensures that, if for some reason such as plugin incompatibility, a class requested from the container does not exist when requested by the loader that no exception is thrown in production but loading is failed gracefully.
* Ensures that the loader class fails gracefully in production when classes do not exist.
* Open the `src/conditionals/front-end-conditional.php` file
* Remove all the lines except the first one (`<?php`) and save
* Make sure your `YOAST_ENVIRONMENT` is set to `development`. This should be the case if you are building the plugin from the repo, otherwise if you are using a zip this may mean adding `define( 'YOAST_ENVIRONMENT', 'development' );` …
> Make di container more robust

- packages/js/src/indexables-page/indexables-page.js
- src/actions/indexables-page-action.php
- src/helpers/indexables-page-helper.php
- src/routes/indexables-page-route.php
- tests/unit/actions/indexables-page-action-test.php
- tests/unit/routes/indexables-page-route-test.php
* A version of the undo hiding of all items that "un-ignores" all indexables for all lists at once.
* Adds a button to undo the hiding of all indexables on the Indexables Page.
* This is a version where there is only one button. If there is time to spare we will implement a version where there is an ignore option _per list_.
Fixes PC-342
> Indexables page: add undo hide for all indexables

- packages/js/src/indexables-page/assessment-functions.js
- packages/js/src/indexables-page/indexables-page.js
* Use the star symbol instead of coloured bullets for the `Highest number of incoming links` card.
* Uses the star symbol instead of coloured bullets for the `Highest number of incoming links` card.
*
*
*
*
Fixes [PC-478](https://yoast.atlassian.net/browse/PC-478)
> Pc 478 use stars in mostly linked table

- css/src/notifications.css
- packages/js/src/indexables-page/components/indexable-title-link.js
- packages/js/src/indexables-page/components/indexables-card-options.js
- packages/js/src/indexables-page/components/indexables-card.js
- packages/js/src/indexables-page/indexables-page.js
* Improved UX.
*
*
* Hide one row in a certain list (List A). Then hide a row in another list (List B).
* Observe the button appearing at the bottom to undo the hiding.
* Now in List B, click the three-dot-menu, and click "restore hidden items". The aforementioned button should disappear and the row you've hidden should come back. List A should be unaffected.
* Now, again, hide a row in List A. Then hide a row in List B.
* Observe the button appearing at the bottom to undo the hiding.
* Now, in List A, click the three dot menu and click restore hidden items. The button should not disappear. Clicking it should still work. The row you've hidden in List A should be back.
* Hide various rows in all lists.
* Click the  "Restore all …
> Enhance User Experience with separate restoring per indexables card

- packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
* Before, we wouldn't show the SKU or product identifiers assessment results for products/variants without a price. We don't want to have this preconditions for showing the assessment results anymore. Also, when a variable product has no variants we decided to show the same assessment results that we show for simple products.
* Shows the SKU and product identifiers assessment results also when the product or variants don't have a price.
* There is an accompanying WooCommerce PR https://github.com/Yoast/wpseo-woocommerce/pull/819
* Activate Yoast SEO Free, WooCommerce, and Yoast SEO: WooCommerce plugins
*  Make sure to link the Free branch before building Woo (composer …
> PC 500 Make SKU and product identifier assessments price independent

- inc/options/class-wpseo-option-wpseo.php
- src/integrations/admin/crawl-settings-integration.php
* Internal site search URLs (eg., example.com/?s=example or example.com/search/example) are often the target of large-scale spam link attacks, which can result in them being aggressively crawled.
* Note that [this PR](https://github.com/Yoast/wordpress-seo/pull/18854) needs to be merged first!
* Add a setting for disabling crawling of search URLs.
*
Test changes on basic (wordpress basic):
* Activate Yoast SEO.
* Go to the WordPress administration and click on Yoast SEO.
* Click on `Crawl settings (beta)`.
* Scroll down and check whether you see a blurred toggle `Prevent search engines from crawling site search URLs`.
Test changes on multisite (wordpress multisite):
* …
> Pc 13 add support for blocking site search via robots txt

- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
* The WooCommerce Yoast SEO analysis was not working and there was a console error when the Product SKU Generator for WooCommerce plugin was used on products without variants.
* Does not show the SKU assessment when we cannot detect a SKU on products without variants. This prevents the analysis from breaking when using the Product SKU Generator for WooCommerce plugin (and possibly other plugins that touch the SKU).
* [yoastseo] Makes the SKU assessment not applicable when we cannot detect the SKU on products without variants.
* There is an accompanying Woo PR https://github.com/Yoast/wpseo-woocommerce/pull/820 
* Using the Product SKU Generator for WooCommerce plugin on products with variants does not cause problems. However, it …
> Do not show SKU assessment when we cannot retrieve SKU

- wp-seo-main.php
* Don't load Yoast SEO on login.
* Improves handling of fatal errors in the front-end by preventing Yoast SEO to run in the login page, allowing users to access their dashboard.
*
* The purpose of the tests is to check that an error affecting the front-end of a website doesn't affect the login screen anymore, so users can access their backend and e.g. disable/downgrade Yoast SEO (or the addons). So we need to mimic this case by creating front-end errors; we could easily trigger any fatal error but that might affect the backend as well.
* We need to check Premium to test that preventing Free to run in the login page shields the site from errors caused by the Premium as …
> Don't load Yoast SEO on the login screen

- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
* In a previous [PR](https://github.com/Yoast/wordpress-seo/pull/18905), the SKU assessment was disabled when we couldn't detect the SKU field. This would happen when the Product SKU generator plugin was used, which would override the input field. While that plugin didn't cause the same issue for the SKU fields of variants, there may be other plugins that do that. So to be on the safe side, in this PR we disable the SKU assessment if the SKU of a variant is not accessible.
* Disables the SKU assessment for products with variants when the SKU of at least one variant cannot be detected.
* There is an accompanying Woo PR: https://github.com/Yoast/wpseo-woocommerce/pull/821 …
> Disable SKU assessment when variant SKU cannot be detected

- inc/class-wpseo-admin-bar-menu.php
- inc/class-wpseo-meta.php
*
* Remove Premium code regarding the Frontend Inspector, the additional focus keyphrases and the wincher analysis of additional focus keyphrases
*
* Follow Test Instructions in https://github.com/Yoast/wordpress-seo-premium/pull/3663
*
*
Fixes #
> Allow adding submenu items in the admin bar via action

- admin/formatter/class-post-metabox-formatter.php
- admin/formatter/class-term-metabox-formatter.php
* We want to allow Premium to filter the social template values in the metabox
* Adds `wpseo_social_template_post_type` and `wpseo_social_template_taxonomy` filters for the social templates in the metabox.
*
* Install without Premium
* Create a new post, move to the Social tab of the metabox
* Check that the Facebook and Twitter boxes work as expected
* Create a new term in a taxonomy, move to the Social tab of the metabox
* Check that the Facebook and Twitter boxes work as expected 
* Install and activate Premium < 19.2.1
* in Search Appearance, add social templates  (image, title, description) for the post type and the taxonomy
* Create a new post, move to the Social …
> PC-516 Add filters for the social templates in the metabox

- src/actions/wincher/wincher-keyphrases-action.php
- tests/unit/actions/wincher/wincher-keyphrases-action-test.php
* We want to allow Premium to filter the keyphrases collected by the Wincher integration
* Adds `wpseo_wincher_keyphrases_from_post` and `wpseo_wincher_all_keyphrases` filters to enhance the collected keyphrases arrays
* **Note:** one of the part that have been touched is used by code which is currently not working, because it's behind a conditional related to the automated tracking feature which cannot be turned on. There is no way to test it then at the moment.
* Install without Premium active
* Check that Wincher is working as expected (adding/removing keyphrases in post edit screen, checking the tracked keyphrases in the dashboard widget)
* activate Premium < 19.2.1
* …
> PC-518  Add filters for the keyphrases collected by Wincher

- admin/formatter/class-post-metabox-formatter.php
- inc/class-wpseo-meta.php
*
* Remove Premium code regarding the related keyphrases' assessment
*
* Follow Test Instructions of https://github.com/Yoast/wordpress-seo-premium/pull/3667
*
*
Fixes #
> Add filter for related keyphrases

- src/integrations/front-end/robots-txt-integration.php
* Some users don't want all multisite XML links visible in the robots.txt this PR provides a way to filter them.
* Adds a filter to remove subdirectory sites from the robots.txt
* The choice was made to only make a turn on or off feature, instead of a filter to actually filter the list of subsites.
* Start the multisite docker (not multidomain)
* Open https://multisitedomain.wordpress.test/robots.txt you should see 3 entries
* Sitemap: http://multisitedomain.wordpress.test/sitemap_index.xml
Sitemap: https://multisitedomain.wordpress.test/sitemap_index.xml
Sitemap: https://multisitedomain.wordpress.test/site2/sitemap_index.xml
* add `add_filter( …
> Adds filter to disable including multisite xml sitemaps in robots txt

- src/routes/indexables-page-route.php
* Enforce security by casting REST request parameters to booleans
* Converts the `set_reading_state` REST request parameter to the expected type
*
* Make sure you have less than 20 public posts/pages or use the filters described in [this PR](https://github.com/Yoast/wordpress-seo/pull/18660) to adjust the threshold as needed to get to the `Start writing content!` page
* Once in the `Start writing content!` page, check/uncheck some of the checkboxes in the reading list
* Refresh the page and verify the state of the reading list is kept
*
*
Fixes …
> Pc 534 harden security on set reading list

- packages/js/src/indexables-page/components/indexables-card.js
- packages/js/src/indexables-page/indexables-page.js
*
* Add loading state in the cards' titles when loading.
*
* Quickly smoke test that when the lists are loading, the titles of the lists are also in a loading state:
*
*
Fixes #
> Pc 513 show title in loading state

- packages/js/src/indexables-page/components/not-enough-analysed-content.js
* The card displayed in the `Posts and pages without a focus keyphrase/Posts and pages that haven't been analyzed` page is misaligned
* Correctly aligns the card in the `Posts and pages without a focus keyphrase/Posts and pages that haven't been analyzed` page
*
* Make sure you have more than 20 public posts/pages but less that 50% of them analysed; alternatively use the filters described in [this PR](https://github.com/Yoast/wordpress-seo/pull/18660) to adjust the threshold as needed to get to the `Posts and pages without a focus keyphrase/Posts and pages that haven't been analyzed` page
* Without this PR, the card is displayed as follows:
* With this PR, the card is …
> Pc 537 layout of the new indexables page is off

- packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
- packages/js/src/indexables-page/components/indexation-view.js
- packages/js/src/indexables-page/components/indexation.js
- packages/js/src/indexables-page/indexables-page.js
*
* Improve the relation between the Indexables Overview and the FTC, in regards to the SEO optimization
*
**For the copy change:**
* Visit the Indexables page with Indexables cleaned out. Verify the copy is like below:
* When that button is clicked, it should then change its copy to this:
**For the reloading of the page from the FTC:**
* Make sure that the SEO optimization in the first step of the FTC, is complete.
* When visiting the last step of the FTC, click on the `Go to your SEO dashboard` button
* Do that for Premium both active and inactive
**For the small part of adding quotes around the post title in the restore button** (no need for separate PR, tiny change): …
> Pc 536 seo optimization flow improvement

- src/integrations/settings-integration.php
* Ignore new indexables page related options in the new settings UI since they can't be altered there.
* Fixes an unreleased bug where the new settings UI would save new indexables page option as string values instead of boolean values.
*
* Verify that [PC-540](https://yoast.atlassian.net/browse/PC-540) is no longer reproducable.
*
*
Fixes #
> Pc 540 ignore new indexables page options

- packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
* It is possible to remove the product identifier input fields, see https://yoast.atlassian.net/browse/PC-511. This breaks the analysis. As a solution, we want to disable the Product identifier assessment when the identifiers cannot be retrieved.
* Does not show the Product identifier assessment when the identifiers cannot be retrieved.
* When you change a variable product with variants to a simple or external product, the variants disappear. However, the hasVariants variable doesn't get updated correctly - it remains `true`. That's why in the applicability check, to check whether a product has variants just checking the hasVariants is not enough. Instead, we also have to check whether the product is a simple or grouped product, …
> Do not show Product identifier assessment when the identifiers cannot be retrieved

- packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation.js
- packages/js/src/indexables-page/components/indexation.js
* To be able to correctly target the right button they need an ID.
* Adds separate IDs to the indexation buttons in the General page, for automation tests.
* None.
* Open https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard#top#first-time-configuration inspect the 'Start SEO data optimization' button to see if there is an ID with the value `indexation-data-optimization`
* Reset the indexables table with the test helper and go to https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard. See if the 'Start site analysis' button has an ID with the value `indexation-site-analysis`
* Verify that both buttons start the SEO optimization process as …
> Adds id to relevant button

- inc/sitemaps/class-taxonomy-sitemap-provider.php
* Revert #17442 
*
*
*
* Regular regression test for the taxonomy sitemaps. In particular, taxonomies marked as `noindex` should never be in the sitemaps, even if they have some `index` terms. This means that https://yoast.atlassian.net/browse/QA-3730 should not happen anymore.
*
Fixes [PC-548]
[PC-548]: https://yoast.atlassian.net/browse/PC-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert PR #17442

- packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
- packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
- packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
- packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
- packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
- packages/yoastseo/src/scoring/productPages/seoAssessor.js
*
* Makes the feedback strings for the Product Identifier and SKU assessment more explicit and actionable.
*
* Build and activate the Free plugin/ the branch in Free
* Build and activate the Woo plugin
* For Developers: use [the branch in Woo](https://github.com/Yoast/wpseo-woocommerce/pull/828), and then require the branch in this PR (by running `composer require yoast/wordpress-seo:dev-PC-552-make-SKU-and-PI-feedback-more-explicit@dev --dev`)
* Open or create a new product 
**Product without variants:**
* Confirm that the product identifier assessment bullet is orange and reads as follows: `Your product is missing an identifier (like a GTIN code). …
> edit feedback strings for SKU and PI assessment and test files

- admin/class-admin-asset-manager.php
- admin/class-yoast-notifications.php
- admin/views/tabs/dashboard/dashboard.php
- composer.json
- css/src/notifications-new.css
- src/conditionals/indexables-page-conditional.php
- src/integrations/admin/indexables-page-integration.php
- src/presenters/admin/notice-presenter.php
- src/routes/indexables-page-route.php
- tests/unit/integrations/admin/deactivated-premium-integration-test.php
- tests/unit/presenters/admin/notice-presenter-test.php
*
* Puts the Indexable Overview behind a feature flag.
*
Note: You can add the following line in your wp-config.php to enabled the feature flag:
`define('YOAST_SEO_INDEXABLES_PAGE', true );`
Without the Feature Flag:
* Visit Yoast SEO->Dashboard and confirm that the Indexables Overview is not shown under the Notifications
* Do a GET request via Postman to http://basic.wordpress.test/wp-json/yoast/v1/get_reading_list and confirm that you get a 404 response ([Helping article](https://www.oasisworkflow.com/how-to-authenticate-wp-rest-apis-with-postman) on doing WP REST API requests via Postman)
* Confirm that the Notifications look like this:
With the Feature Flag:
* Visit …
> Put Indexable Overview behind a feature flag

- src/presenters/admin/sidebar-presenter.php
* We want the layout to be the same as yoast.com
* Adds more styling to the upsell sidebar.
* None.
* Make sure premium is not activated.
* Go to https://yoast.com/carbon-footprint-of-website/ and https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard
* compare the sidebars without the price. And make sure they are the same visually.
* Make sure the buy button and review links work.
*
*
Fixes #
> Update layout to add bold text

- admin/tracking/class-tracking-plugin-data.php
- admin/tracking/class-tracking.php
* We want to know if users have auto updating on for plugins.
* Adds additional key to tracking data with auto updating information
* None.
* Make sure tacking is enabled on /admin.php?page=wpseo_dashboard#top#first-time-configuration in the personal preferences step.
* Disable all auto updating plugins and make sure query monitor is running
* Open https://basic.wordpress.test/wp-admin/options.php and look for the option wpseo_tracking_last_request
* Set the value of this option to 1600000000 and save.
* On the page that is loaded after saving open query monitor look in the HTTP API calls section and see if https://tracking.yoast.com/stats was sent.
* Enable auto updating …
> PC-418 Adds which plugins have auto updating enabled.

- packages/js/src/indexables-page/components/indexables-card.js
* Hide overflow on indexables card to prevent horizontal scrollbar when hiding animation.
* Fixes an unreleased bug where a horizontal scrollbar would appear when hiding an indexables from the indexables table on the new indexables page.
*
* Visit the indexables page.
* Decrease viewport width until one of the indexables tables is most right element.
* In one of the indexable tables, hide one of the listed indexables using the eye icon and verify that no horizontal scrollbar appears on window during the animation.
*
*
Fixes #
> Hide overflow on indexables cards

- admin/formatter/class-metabox-formatter.php
- admin/views/tabs/social/twitterbox.php
- inc/options/class-wpseo-option-social.php
- packages/js/src/initializers/admin.js
- src/context/meta-tags-context.php
- src/presenters/twitter/card-presenter.php
* We want to force the `summary_large_image` type of card, being the only one supported by Twitter now.
* Forces the use of the large card, which is the only supported format by Twitter.
* Deprecates the `wpseo_twitter_card_type` filter.
I decided to have a "light" approach about the removal, to keep the scope and impact low instead of erasing all the mechanisms triggered by the former choice between a small and a large image card:
* I've remove the select2 from the Social settings: this is a page that's going to be replaces soon anyway by the new UI, but it's still one occurrence of a library that we want to get rid of soon. No hidden field has been placed in the page, so saving the options will force the value of …
> PC-445 Remove Twitter small preview

- src/generators/schema/breadcrumb.php
- tests/unit/generators/schema/breadcrumb-test.php
* We check each ListItem in a breadcrump object whether it has valid Text value and if not we remove it from schema.
* Fixes a bug where `ListItem` entries would be output in a `BreadcrumbList` even if their text was empty, resulting in Schema validation errors.
* This fix "masks" the underlying issues, but it does introduce graceful failure when a breadcrumb item has an empty text to avoid GSC errors
* Have the Twenty Nineteen theme enabled (that way, you're able to have empty title for a page)
* Create a page, lets call it Page1
* Now create a second page, lets call it Page2 and make it as children of Page1. Add a Yoast's breadcrumb block there.
* Now, go to Page1's …
> Remove list item in breadcrumps schema if it has an empty text

- src/generators/schema-generator.php
- tests/unit/generators/schema-generator-test.php
* With [PC-190](https://yoast.atlassian.net/browse/PC-190) we addresses a range of edge-cases where our breadcrumb schema contains empty or invalid ‘levels’ (by filtering them out). As a side-effect, we may now find many such scenarios misrepresent a page as only having the homepage in the breadcrumb structure.
* With this PR, we address those scenarios by omitting the breadcrumb schema if it contains only the homepage and we're not on the homepage.
* We also remove the reference of the breadcrumb node from the WebPage node.
* Removes empty breadcrumb schemas if not on homepage.
* The removal of the empty breadcrumb schema happens late in the process of generating the schema, so that it is performed after all the filtering.
This …
> Remove empty breadcrumb schema if not on homepage

- src/integrations/front-end/feed-improvements.php
We should automatically noindex all comment feeds.
This will reduce duplicate content and index bloat, and improve crawl quotas for sites which do not disable comments feeds.
* Adds a `X-Robots-Tag: noindex, follow` header to all comment feeds to prevent them to be indexed, reducing duplicate content.
* I removed the canonical links from the comments feed because in https://yoast.atlassian.net/browse/PC-14 it is mentioned that this should only be added on non-comment feeds, this was not the case.
Mainly taken from https://yoast.atlassian.net/browse/PC-14
- Make sure that all feeds are enabled in the crawl settings
- Open a comment feed e.q. …
> Adds robots tag for comments feed.

- src/presenters/robots-txt-presenter.php
- tests/unit/integrations/front-end/robots-txt-integration-test.php
- tests/unit/presenters/robots-txt-presenter-test.php
* We want to fix the comments for the Yoast SEO block in `robots.txt`, since it's not limited to internal search
* Fixes a bug where the block of directives introduced by Yoast SEO in `robots.txt` would display a wrong comment.
*
* visit your site's `robots.txt` and see that the opening and closing comments are fixed, e.g:
```
User-agent: *
Disallow:
Sitemap: http://basic.wordpress.test/sitemap_index.xml
```
is now
```
User-agent: *
Disallow:
Sitemap: http://basic.wordpress.test/sitemap_index.xml
```
* install the lates Premium, play with `robots.txt`-related toggles ("Prevent search engines from crawling site search URLs", "Prevent search engines from crawling …
> PC-645 Fix the block comments in `robots.txt`

- admin/tracking/class-tracking-server-data.php
* There are many web hosting providers that disable a number of built-in PHP functions due to security reasons. When the `php_uname()` function is disabled on a web host, activating Yoast SEO causes a fatal error when the tracking is enabled. The PR checks whether the relevant function exists and if it does, it adds the OS information to the tracking data. If the relevant function is disabled, the `PHP_OS` constant is being used as a fallback as the relevant constant will work even when the relevant function is disabled by the web hosting provider.
* Prevent PHP fatal error when `php_uname()` function is disabled by the web hosting provider.
* Used an additional `if()` condition to check whether the `php_uname()` function is …
> Prevent fatal error when `php_uname()` is disabled

- wpml-config.xml
It's quite very common to see that someone wants to set `noindex` to the translated content while the main content remains `index`. However, it wasn't possible at all due to the two-way robots meta synchronization. Setting up the `noindex` to the translated content will set the `noindex` to the parent content as well and vice-versa.
The PR resolves the two-way robots meta synchronization between the multilingual contents by applying the `copy_once` instead of `copy`. `wpml-config.xml` file is popular and used by various themes and plugins (i.e., Polylang) to make everything compatible with each other, and it offers the relevant action.
According to the [WPML documentation](https://wpml.org/documentation/support/language-configuration-files/#custom-fields):
> when using the `copy-once`, …
> Avoid syncing robots meta between multilingual contents

- admin/formatter/class-term-metabox-formatter.php
* When the rewrite rule is set to false for a custom post type or taxonomy, a PHP notice `Trying to access array offset on value of type bool` occurs. The relevant PHP notice is expected since there are no values for `rewrite` key that we use without checking. This PR adds a condition before using the `rewrite` key to prevent the relevant PHP notice.
* Prevent a PHP notice when editing a custom post type or taxonomy where `rewrite` is set to `false`.
* When `rewrite` is set to `false`, there's no slug that we need to show in the snippet preview. Otherwise, we could have either used the following two possible solutions to get the slug from the labels:
**Possible solution 1**
```php
$base_url = trailingslashit( $base_url . …
```
> Get slug only when `rewrite` is `true`

- src/presentations/indexable-presentation.php
- tests/unit/presentations/indexable-presentation/robots-test.php
* When `add_filter( 'wpseo_robots', '__false' );` is set, `noindex, nofllow` isn't shown but only `max-image-preview:large` is being shown, which is wrong. When the relevant filter is set to `false`, it shall output `noindex, nofollow` to discourage search engine crawling the entire site.
* Fixes a bug where `noindex, nofollow` would not be displayed when `wpseo_robots` filter is set to `false`.
* Set `add_filter('wpseo_robots', '__return_false');` on `functions.php` file.
* Check the robots meta output on the front-end of the website to look for `noindex, nofllow`.
Fixes #18483
> Return `noindex, nofollow` when `wpseo_robots` is `false`

- packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
* **Note**: This fix applies when the user opens the post in the editor. The SEO score as shown in the post overview page (and the Indexable overview page) only gets updated after the post is opened and resaved.
* Fixes a bug where changes in the replacement variables (e.g. the value of the `%%title%%` replacement variable when the post title changes) would not be reflected in the Meta description length, the SEO title width, and the Keyphrase in SEO title assessments.
* 
* Open a post in the editor.
* Make sure that the `%%title%%` replace var is in the SEO title.
* Make sure that the `%%title%%` replace var is in the meta description.
* Add just enough extra text to the …
> Update the title, description and slug on the store whenever the replacement variables have changed

- packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
* This PR was originally intended for RC1 but was merged at a later point without rebasing to the release branch.
* Reverts Yoast/wordpress-seo#18975.
* 
*
*
Fixes #
> Revert "Update the title, description and slug on the store whenever the replacement variables have changed"

- src/integrations/front-end-integration.php
- src/integrations/third-party/web-stories.php
- src/presenters/title-presenter.php
- tests/unit/integrations/front-end-integration-test.php
- tests/unit/integrations/third-party/web-stories-test.php
* No `<title>` attribute is outputted when viewing a Web Stories post type with Yoast SEO enabled.
* Alter web stories metadata filter when Yoast title is disabled.
* We disable the Web Stories metadata when Yoast SEO is disabled but when the theme used does not have the `title-tag` theme support we also disable the Yoast SEO title resulting in a page without a title. In this PR the metadata is only disabled when we are sure that the Yoast title is outputted.
* Install and activate both Yoast SEO and Web stories.
* Activate the Twenty-Twenty-Two theme.
* Go to the administration dashboard -> `Web Stories`.
* Click on `Create New Story`.
* Add some content to the story and …
> Alter web stories metadata filter when Yoast title is disabled

- packages/js/src/first-time-configuration/tailwind-components/base/combo-box.js
- packages/js/src/first-time-configuration/tailwind-components/base/single-select.js
* Add `data-id` props to Headless UI components that don't accept `id` props in FTC to use as selectors in automated tests.
* Adds `data-id` props to Headless UI components that don't accept `id` props in FTC.
*
* Visit the first-time configuration.
* Verify that the organization/person select `button` now contains unique `data-id` prop next to the auto-generated `id` prop.
* Verify that the person user select `button` (rendered as `div` with `role="button"`) and `input` now contain unique `data-id` prop
*
*
Fixes # …
> Add data id props to headless ui components in FTC

- src/generators/breadcrumbs-generator.php
* If `wpseo_breadcrumb_links` is used wrongly, it may cause fatal errors on PHP 8.0+ since our code expects it to return an array.
* Fixes a bug where a fatal error would be thrown when using the `wpseo_breadcrumb_links` filter in the wrong way on PHP 8.0+
* First usage of the `_doing_it_wrong` method in our plugin. This prints a PHP notice to the PHP error logs when `WP_DEBUG` is enabled.
* Take care to change the version number in the code of this PR if this is not released in 18.5
You will need to keep an eye on your logs (this can be done with Query Monitor)
- on PHP 8.0+, add the following to your functions.php:
```php
add_filter('wpseo_breadcrumb_links', …
```
> Make sure the wpseo_breadcrumb_links filter returns an array

- tests/unit/helpers/url-helper-test.php
* We do not want to test partial mocks of classes, since they may lead to false negatives in the unit tests (e.g. a test passes, but it does not actually test the thing it should be testing, since it is mocked).
* Replaces a partial mock in the URL helper unit tests.
* Replaced some home URLs with actual URLs (e.g. `'home_url'` with `'https://example.com'`) for better tests.
* Unit tests should pass.
* N/A: this PR only changes some unit tests.
* N/A: this PR only changes some unit tests.
Fixes #
> Replaces partial mock in URL helper tests.

- src/presenters/admin/sidebar-presenter.php
*
* Fixes the shortlink in the Yoast sidebar ad
*
* Check the Yoast sidebar ad and make sure the destination link is  http://yoa.st/jj instead of http://yoa.st/17h
*
*
Fixes #
> Fix sidebar ad shortlink

- admin/tracking/class-tracking-settings-data.php
* We added new options to change the robots txt output, but we did not add them to our tracking.
* Adds two options to the tracking data.
* None.
* edit `/admin/class-admin.php`, and at the end of the constructor (should be line 115) add the following lines:
```
$collector->add_collection( new WPSEO_Tracking_Settings_Data() );
echo '<pre>';
print_r( $collector->collect() );
echo '</pre>';
}
die;
```
* test the tracking of the setting: visit http://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard&action=test and see that among the lines in the array there is: ` …
> PC-638 Add options to tracking

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/configuration-stepper-buttons.js
- packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
* Add more `id` props to buttons in FTC for easy selecting in automated tests.
* Adds `id` props to back and continue buttons for each step in FTC.
* Adds `id` props to finish step buttons in FTC.
*
* Visit the FTC.
* Verify that in each step the `Back` and `Continue` buttons have unique `id` attributes based on the step identifier, ie. `button-siteRepresentation-continue`.
* Verify that in the finish step buttons have unique `id` attributes based on Premium active state, ie. `button-seo-dashboard` on Premium active and `button-webinar-seo-dashboard` on Premium inactive.
* …
> Pc 661 id props ftc

- packages/js/src/settings/components/formik-user-select-field.js
- packages/js/src/settings/store/users.js
- packages/ui-library/src/elements/autocomplete/index.js
*
* Improves the user select component in the new settings UI.
*
* Verify [PC-658](https://yoast.atlassian.net/browse/PC-658) is no longer reproducible.
* Also verify that the `Select a user...` placeholder when the field is empty disappears when you focus the field and start typing. So you don't have to manually delete the placeholder before typing.
*
*
Fixes #
> Improve user select component

- packages/js/src/insights/components/insights-collapsible.js
- packages/js/src/insights/components/insights-modal.js
- packages/js/tests/insights/components/insights-collapsible.test.js
- packages/js/tests/insights/components/insights-modal.test.js
- src/conditionals/text-formality-conditional.php
*
* Puts Text formality feature behind a flag.
*
* Disable the feature by adding `define( 'YOAST_SEO_TEXT_FORMALITY', false );` in `wp-config.php` file of your site
* If using Rancher, you can find the config file in `plugin-development-docker/config/basic/wp-config.php` 
* Open a post and confirm that the Formality upsell is not shown when opening `Insights` tab
* Repeat this step in **all other content types** and confirm that you get the same result
* Repeat this step in **Classic, Block, and Elementor** and confirm that you get the same result
* Install and activate Yoast SEO Premium
* The premium PR: …
> PC-660 remove formality

- inc/class-wpseo-utils.php
- tests/integration/test-class-wpseo-utils.php
* According [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986), prevent encoding at sign (`@`) in an URL path.
* Fixes a bug where social or canonical URLs containing `@` would lead to encoding issues. Props to @stodorovic.
*
* Save a Tiktok user URL into the Organization's social profiles field. Refresh the page and view the saved URL.
* Save a canonical URL (which contains `@`) into a page and view the saved URL.
*
Fixes #18764, #17099
> Don't encode '@' in URL path

- src/generators/breadcrumbs-generator.php
Improves the possibility to filter the term crumbs in a breadcrumb with "wpseo_breadcrumb_links".
* I want to be able to get the proper taxonomy from my term, while filtering the term crumbs. This is not possible without the actual taxonomy value. For example to get taxonomy data with: https://developer.wordpress.org/reference/functions/get_term_by/
* Adds taxonomy information to crumbs of type "term" to be able to filter them better with `wpseo_breadcrumb_links`. Props to @svenvonarx.
* Extends the crumb array with one entry called taxonomy. There should be no negative consequences by that.
* Nothing to test really. Other then checking the values, since its not used by …
> Add the taxonomy name to term crumb.

- admin/roles/class-role-manager-factory.php
- admin/roles/class-role-manager-vip.php
Fixes https://github.com/Yoast/wordpress-seo/issues/16993 by deprecating the special code paths that were made specifically for WP VIP.
Usage of VIP-specific role functions is no longer necessary, as they are effectively just wrappers around the same core methods now. So rather than fixing the bug/incorrect usage of `wpcom_vip_add_role()`, I think it will be best to just remove the edge case altogether.
Ideally we remove the whole `WPSEO_Role_Manager_VIP` class eventually, but I figure deprecating first is safer just in case something is calling the code directly.
Should I also add a constructor to the class w/ a deprecation notice inside to help catch if something is instantiating but not using a method directly for some reason? I didn't see this pattern used elsewhere, so opted to not …
> Deprecate WPSEO_Role_Manager_VIP

- src/conditionals/yoast-admin-and-dashboard-conditional.php
- tests/unit/conditionals/yoast-admin-and-dashboard-conditional-test.php
* We want to fix the `Yoast_Admin_And_Dashboard_Conditional` so it doesn't run on the front-end's home page
* Fixes the `Yoast_Admin_And_Dashboard_Conditional` to work only on the back Props to @mweimerskirch.
* this is in place of #18088 because removing `index.php` would not target the site's dashboard anymore
* Put a breakpoint in the `Yoast_Admin_And_Dashboard_Conditional::is_met()`, or something similar, and check it doesn't return `true` in the site's home page but it does on the site's dashboard
* [] QA should use the same steps as above.
* NA just a change that has no effect outside
This PR affects the following parts …
> PC-669 Fixes the Yoast_Admin_And_Dashboard_Conditional

- packages/js/src/settings/components/formik-user-select-field.js
* 
* Fixes an unreleased bug where the `username` fallback for users missing a `display_name` field wouldn't show in the users select on site representation route.
*
* Verify that [PC-658](https://yoast.atlassian.net/browse/PC-658) is no longer reproducible.
*
*
Fixes #
> Fix request context in users select

- packages/js/src/ui/publishBox.js
* We want to stop a console error from appearing when working with Elementor's containers
* Fixes a bug where Yoast would conflict with Elementor, when Yoast Premium or Yoast News or Yoast Video is active, throwing console errors.
* Some unused code was removed in the `packages\js\src\ui\publishBox.js` file
* That file got referenced in the Editor Modules with https://github.com/Yoast/wordpress-seo/pull/18922
* Any add-on that uses the Editor Modules in the Elementor editor, aka Premium, News, Video, caused a console error in Elementor editor's when active
* Activate Free and either one of Premium, News, Video
* Have Elementor active and enable the Containers feature like …
> Remove unused code that breaks the Elementor container feature

- src/integrations/watchers/search-engines-discouraged-watcher.php
- tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
* Some tests created in [PC-46](https://github.com/Yoast/wordpress-seo/pull/18744) used a mocked version of the `Search_Engines_Discouraged_Watcher`.
* Changes tests for `Search_Engines_Discouraged_Watcher` to not use a mocked version of the class.
*
* re-check the notification introduced by https://github.com/Yoast/wordpress-seo/pull/18744 to make sure its look is unchanged.
*
*
Fixes [PC-347](https://yoast.atlassian.net/browse/PC-347)
> Refactor tests to not use mocked class

- packages/js/src/settings/components/formik-user-select-field.js
*
* Improves the `username` fallback for users with whitespace as a `display_name` field in the users select on site representation route.
*
* Go to the Site representation route in the new settings UI and select the person entity.
* Verify that when a user has whitespace as `display_name`, the `username` is shown instead as option label in the user select.
*
*
Fixes #
> Improve empty option fallback in user select

- src/wrappers/wp-remote-handler.php
* 
* Fixes a bug where a fatal error would be thrown on WordPress.com using PHP 8.0 in connection with the Debug Bar.
* [`wp_remote_request`](https://developer.wordpress.org/reference/functions/wp_remote_request/) expects a string as its first parameter but we were passing a `UriInterface`. This was breaking
* Check that the Semrush integration flow is working as expected.
*
*
Fixes [PC-688]
[PC-688]: https://yoast.atlassian.net/browse/PC-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PC-688 Cast `Uri` to `string` to for PHP 8 compatibility

- inc/class-wpseo-admin-bar-menu.php
- packages/js/src/admin-global.js
* We want to avoid mismatches between the issue counters in the adminbar and the sidebar, so we're forcing the latter get the value of the former on page load.
* Fixes a bug where the sidebar issue counter would show a wrong number of issues, on the first page load after an issue was resolved.
* Because of timing issues, the sidebar issue counter gets the old issue count on the first page load after an issue gets resolved.
* In order to fix that properly, it would require a radical transformation of the whole notification system, which doesnt make much sense, considering that we're probably going to scrap it soon.
* Which meant that I could just resort in jQuery to make the value of the sidebar issue counter same with the value …
> Improves the relation between the sidebar and the adminbar notifications

- src/services/health-check/curl-runner.php
- tests/unit/services/health-check/curl-check-test.php
- tests/unit/services/health-check/curl-runner-test.php
* We don't want to complain about a too old curl version in the health Check when the API call is succeeding. Enhances https://github.com/Yoast/wordpress-seo/pull/18824 to fix the unit tests.
* Relaxes the requirement about cURL version if MyYoast API can be successfully reached. Props to @tomsommer.
* 
It's not so easy to test the actual condition with an outdated but patched cURL version, so most importanto of all is to make sure that successful API checks are still working:
* visit Tools > Site Health 
* expand the "Passed tests"
* look for this section:
* if you could see it without the patch, you should still be able to see it with this patch. …
> Do not complain about curl version

- packages/js/src/settings/components/formik-user-select-field.js
* Fix selected user name fallback in user select.
* Fixes an unreleased bug where no username fallback would be shown for selected user in new settings UI.
*
* Visit the new settings UI -> Site representation and select the Person entity.
* In the user select, select a user without a proper name and verify that the selected user name fallback is correctly showing in the select.
* If test instructions unclear, please ping me @nolledgeable.
*
*
Fixes #
> Fix selected user name fallback in user select

- src/context/meta-tags-context.php
Allow WP Queries where the parameter "fields" is set to "ids".
Otherwise ID is not a property of $GLOBALS['wp_query']->posts[0].
I was getting a PHP notice in one of my personal projects.
So I tried to resolve it.
* Fixes a bug where a warning would be thrown on archive and search pages when the main query is set to return IDs instead of post objects. Props to @mathiasdb.
The line `return $this->get_singular_post_image( $GLOBALS['wp_query']->posts[0]->ID );` is guesswork. You don't know if $posts[0] is null, false, "", an object.
* Add this code at the end of your theme's `functions.php`:
```
function use_ids_in_archive( $query ) {
if ( ! is_admin() && ( is_archive() || is_search() ) && $query->is_main_query() ) {
$query->set( "fields", "ids" );
}
}
add_action( 'pre_get_posts', …
```
> Fixes a bug where ID is not a property of $GLOBALS['wp_query']->posts[0]

- src/deprecated/admin/ryte/class-ryte-option.php
- src/deprecated/admin/ryte/class-ryte-request.php
- src/deprecated/src/integrations/admin/ryte-integration.php
- src/deprecated/src/services/health-check/ryte-check.php
- src/deprecated/src/services/health-check/ryte-reports.php
- src/deprecated/src/services/health-check/ryte-runner.php
* To make extra sure that there is no chance of the integration still being used, we want to also remove the code
* Emptys deprecated Ryte classes
* None.
* NA we're removing code that has not purpose currently.
*
*
Fixes [PC-747]
[PC-747]: https://yoast.atlassian.net/browse/PC-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove all deprecated ryte code.

- css/src/structured-data-blocks.css
* We want to make sure that buttons for the FAQ and the How-To blocks are still visible when using a dark theme.
* Fixes a bug where the buttons in the FAQ and in the How-To block would be hardly visible when using a dark theme.
*
* install and activate any dark theme
* if you have WP 6.1 with Twenty Twenty Three, set a dark style instead
* please test both cases!
* open a post in the Block editor
* add a FAQ block or a How-To block
* **without this fix** the buttons to add/delete a question or an image will be hardly visible because they're black on black/dark background
* **with this fix** the buttons to add/delete a question or an image should be visible because …
> PC-733 Use light color for button in structured data blocks when using a dark theme

- packages/js/src/components/WincherSEOPerformance.js
- packages/js/src/containers/WincherSEOPerformance.js
* When someone connects to Wincher we wat to start tracking their keyphrases.
* Adds immediate key phrase tracking after connecting to Wincher
* None.
* Make sure Wincher is enabled.
* Make sure you do not have Wincher connected. If this is the case toggle the integration in the integration page.
* Create a fresh post and add a keyword for example `wincher intregration example` Add a title and save the post.
* Hit connect with Wincher in the meta box in the track SEO performance tab and complete all the steps
* Make sure your keyphrase is present in the Wincher dashboard.
* Make sure your keyphrase is 'on' in the metabox.
---
* Slightly change your keyphrase and save. for …
> Adds immediate key phrase tracking after connecting to Wincher.

- packages/js/src/components/fills/MetaboxFill.js
- packages/js/src/components/fills/SidebarFill.js
- packages/js/src/components/link-suggestion.js
- packages/js/src/components/link-suggestions.js
- packages/js/src/editor-modules.js
- packages/js/src/elementor/components/fills/ElementorFill.js
* We want to add an upsell for the `Internal linking suggestions functionality` both in the sidebar and in the metabox
* Adds an upsell for the `Internal linking suggestions` in metabox and sidebar.
* This PR must be tested and merged together with its [Yoast SEO Premium accompanying one](https://github.com/Yoast/wordpress-seo-premium/pull/3703)
* Make sure you don't have Yoast SEO Premium activated
* Open a post for edit
* Check that in the sidebar you have an `Internal linking suggestions` collapsible, and click it: it should display as in picture:
* Make sure the upsell button takes you to the right page, that is: …
> PC-6-add-internal-linking-suggestions-in-post-editor-in-free

- src/integrations/third-party/elementor.php
*  If a site is configured to use basic access authentication through `.htaccess`, users which don't have the `manage_options` capability will be prompt to insert their credentials when trying to save a post in Elementor. Moreover, the meta options related to that post will not be saved. 
* Fixes a bug where users with site-wide basic access authentication are prompted to insert their credentials when saving a post in Elementor if they don't have the `manage_options` capability.
* Fixes a bug where Yoast SEO-related post meta data is not saved if a user without the `manage_options` capability saves a post in Elementor.
* Be sure your dev env (Rancher/Docker) is already …
> PC-717-401-unauthorized-when-editing-a-page-with-elementor

- src/presenters/twitter/card-presenter.php
* 
* Reinstates the `wpseo_twitter_card_type` filter that was wrongly deprecated in 19.8.
*
* Add the following filter in your functions.php (or in a mu-plugin):
```
add_filter( 'wpseo_twitter_card_type', 'twitter_card_type' );
function twitter_card_type( $type ) {
return 'whatever';
}
```
* Visit the frontend of any post and regardless of the social settings, confirm that the `twitter:card` tag has a value of `whatever`
* Also confirm that you don't get a deprecation message: `PHP Deprecated: Hook wpseo_twitter_card_type is <strong>deprecated</strong> since version WPSEO 19.8 with no alternative available. The only supported value is summary_large_image`
QA can test this …
> PC-795 Reinstates `wpseo_twitter_card_type` filter that was wrongly deprecated

- admin/tracking/class-tracking-addon-data.php
- admin/tracking/class-tracking.php
* We want to add some addon options to the tracking.
* Adds tracking for multiple options from the local addon.
* I also implemented the option tracking for the other addons (if they are enabled)
* make sure local is enabled.
*  edit `/admin/class-admin.php`, and at the end of the constructor (should be line 115) add the following lines:
```
$collector->add_collection( new WPSEO_Tracking_Addon_Data() );
echo '<pre>';
print_r( $collector->collect() );
echo '</pre>';
}
die;
```
* test the tracking of the setting: visit http://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboar …
> Adds local seo tracking and prepares file for all other addon tracking.

- packages/js/src/insights/components/flesch-reading-ease.js
- packages/js/tests/insights/components/flesch-reading-ease.test.js
* The call-to-action feedback string for Flesch Reading Ease (FRE) analysis when the text is recognized as "fairly difficult" is not representative of how the FRE score is being calculated. 
* The string: `Try to make shorter sentences to improve readability` 
* NOTE: a text is fairly difficult if the score is between 50 - 60 (see [this doc](https://yoast.atlassian.net/wiki/spaces/LIN/pages/1627324605/Flesch+Reading+Ease+Score+General+Overview#Scale))
* This is because the FRE score is influenced by both sentence length, as well as the use of complex (i.e., long) words. 
* In this PR, we want to return the same call-to-action feedback string for Flesch Reading Ease analysis when the text is recognized as "fairly difficult", "difficult", or "very difficult".
* The string: `Try to make …
> PC-389 Improve FRE call to action feedback

- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessmentSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/includesConsecutiveWordsSpec.js
- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/includesWordsAtPositionSpec.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/index.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/scores.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesConsecutiveWords.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesWordsAtPosition.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isPrecededByException.js
- packages/yoastseo/src/scoring/assessments/index.js
- packages/yoastseo/src/scoring/inclusiveLanguageAssessor.js
* This PR is part of the issue to move inclusive language from Premium to Free.
* Moves the inclusive language assessment and assessor from Premium to Free.
*
* Confirm that all unit tests pass.
*
*
Fixes https://yoast.atlassian.net/browse/PC-766
> Move inclusive language assessment and assessor from Premium to Free

- css/src/structured-data-blocks.css
*
* Fixes a bug where the mover buttons in the FAQ and in the How-To block would be hardly visible when using a dark theme.
* retest https://github.com/Yoast/wordpress-seo/pull/19035 adding more that one FAQ/HowTo step and check that the buttons to move the step up or down have a light color when using a dark theme.
*
*
* [z] I have tested this code to the best of my abilities
Fixes [PC-820]
[PC-820]: https://yoast.atlassian.net/browse/PC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PC-820 Fix color of mover buttons for FAQ and HowTo block with dark themes

- admin/tracking/class-tracking-settings-data.php
- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- inc/options/class-wpseo-option-titles.php
- src/context/meta-tags-context.php
- src/generators/schema/organization.php
- src/generators/schema/website.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/generators/schema/organization-test.php
- tests/unit/generators/schema/website-test.php
* Cherry-picked from the original https://github.com/Yoast/wordpress-seo/pull/19060 PR, that is now closed because of inadvertently merging trunk in that one 
* Given Google's new support for [site names in Google Search](https://developers.google.com/search/blog/2022/10/introducing-site-names-on-search), we want to increase the control site owners have over this value.
Output:
Input fields:
* Google introduced new support for [site names in Google Search](https://developers.google.com/search/blog/2022/10/introducing-site-names-on-search). Yoast SEO already outputs this value correctly, using the WordPress site name. With this change we have increased the control site owners have over this value by adding input fields to …
> Pc 822 add company alternate name

- src/context/meta-tags-context.php
*
* Removes filter introduced in previous RC for alternate company name
*
* Smoke test giving an Alternate organization name and checking the homepage's frontend if it shows in the schema
*
*
Fixes #
> Remove filter for alternate company name

- packages/js/src/analysis-worker.js
* We want to prevent the `wp-inert-polyfill` script from Gutenberg to be loaded as a dependency of the analysis worker, which would trigger a JS error.
* Fixes a JS error that would be triggered by the `wp-inert-polyfill` script from Gutenberg when loaded as a dependency of the analysis worker.
* We just prevent the worker to load the offending script as a dependency. This doesn't prevent future issues, should the dependencies start using the Web API (or require the `wp-inert-polyfill` to be working)
* install the latest Gutenberg `trunk`
* edit a post and see that the readability tab works without any issue
* see that you don't get any `Uncaught ReferenceError: Element …
> PC-824 Prevent wp-inert-polyfill to be loaded as a dependency of the analysis worker

- src/builders/indexable-link-builder.php
* When saving a post (or optimising a post within the SEO optimisation routine) we look through its contents for internal and external links (to other webpages or to images) and save information about it in the database.
* When we would encounter a link to an image, we try to retrieve its file size and save it. However, if this failed, PHP would give a warning.
* When WordPress debugging is on, this warning was output in the response to a REST-request in the SEO optimisation.
* Since this response was expected to be JSON, but now included a warning in HTML, the SEO optimisation gave an error.
* Fixes a bug where the SEO optimization routine would give an error when an image file of an image linked in a post could not be …
> PC-829 - SEO Optimisation errors when trying to get the file size of an non-existing image

- css/src/yst_plugin_tools.css
- src/presenters/admin/sidebar-presenter.php
* We want to show a banner in our up sale sidebar at certain times.
* Adds a sale badge to the upsell on our main settings page, that is temporarily shown.
* The function used to calculate the time is `gmmktime` and it says it is in GMT so the time is 2 hours before CET.
* Either change the time of you php (dev) server, or change the date and time in the code
* You can use the https://www.epochconverter.com/ site to get timestamps from Human Dates and then put them in the `$time` variable.
* When the time is within the set time window, the sidebar should change to the design in the issue.
**For 22 Nov 12.00 CET - 27 Nov 12.00 CET** - we should show `Black Friday`
**For 27 …
> Adds BF banner

- src/builders/indexable-builder.php
- tests/unit/builders/indexable-builder-test.php
* When building an indexable fails, we insert a new indexable record with the "unindexed" status. This, however, doens't take into account any existing records for that object. Saving an object for which the building step fails over and over results in multiple records of the same indexable object in the database.
* Prevent duplicate indexable records for the same object
* Instead of querying the db for any existing indexables, I rely on the caller to provide the existing indexable, as we already do.
* If the indexable already exists, but rebuilding the indexable fails, I mark it as "unindexed". The indexable should have changed, but that failed, so we cannot reliably determine the validity of the indexable contents.
This PR can …
> Prevent duplicate indexable records for the same object

- src/actions/indexing/post-link-indexing-action.php
- tests/unit/actions/indexing/post-link-indexing-action-test.php
* When the `wpseo_indexable_excluded_post_types` filter is used to exclude a post type from indexables, a fatal error occurs when the SEO data optimization is run. 
* Fixes a bug where the SEO optimization would error out when a post type is manually excluded via a filter.
* None.
Do the following in trunk or the previous RC
* Add the following code snippet to run on every page
```
add_filter( 'wpseo_indexable_excluded_post_types', 'yoast_exclude_some_custom_post_types' );
function yoast_exclude_some_custom_post_types( $excluded_post_types ) {
$excluded_post_types[] = 'page';
return $excluded_post_types;
}
```
* Make sure you have published pages.
* Clear your indexables …
> PC-871 fixes fatal error call when running seo optimization

- inc/class-upgrade.php
- src/helpers/author-archive-helper.php
- src/helpers/post-type-helper.php
- src/integrations/cleanup-integration.php
- tests/unit/integrations/cleanup-integration-test.php
The indexable table has grown a lot since it was introduced. We're reducing the size by limiting what objects end up in the indexables table. We remove indexables for:
* Posts and taxonomy objects that are not publicly viewable
* Users that do not have an archive. Either because the archives are disabled, or the user doesn't have any publicly viewable posts that would end up in their archives.
* Duplicated indexable rows for the same object with the "unindexed status".
* Reduces the amount of data that is stored in the yoast_indexables table.
* I chose to do part of the upgrade routine on shutdown. post_types and taxonomies are to be registered on or after the `init` hook. Especially since not all post types may be available at …
> Cleanup indexables when updating the plugin

- src/initializers/woocommerce.php
- tests/unit/initializers/woocommerce-test.php
* We want to declare compatibility with High Performance Order Storage feature in WooCommerce 7.1+. Yoast SEO doesn't perform any operation on WC orders, so it's not affected by the switch to custom tables.
* Ensures compatibility with the High Performance Order Storage feature in WooCommerce 7.1+.
*
* Install the WooCommerce zip from the [HPOS feature release page](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table) and install it.
* make sure you have only Free with this branch active (no other addons)
* create one or more orders under WooCommerce > Orders
* visit WooCommerce > Settings > Advanced > Features
* under Experimental features, …
> PC-868 Declare compatibility with the HPOS feature (WooCommerce 7.1+)

- packages/analysis-report/src/AnalysisList.js
- packages/analysis-report/src/AnalysisResult.js
- packages/analysis-report/src/ContentAnalysis.js
- packages/js/src/components/contentAnalysis/Results.js
* This bug affects the assessments that:
* have highlighting functionality, AND
* it's possible to update the assessment feedback without making any changes in the highlighted text area. For example:
* Keyphrase distribution assessment
* Subheading distribution assessment
* Keyword density assessment
* Fixes a bug where highlighting would not be removed from the text after the analysis is updated and the present highlighting has become irrelevant.
*
NOTE: This assessment is not available for related keyphrase. It is only available for focus keyphrase.
* Install and activate Yoast SEO Premium
* If building the plugin: run  `composer require …
> PC-870 Fix highlight issue

- inc/class-upgrade.php
* We want to change the version number from `19.10` to `19.11` for this upgrade routine.
*  Change the version number from `19.10` to `19.11`.
*
* Please follow the test instructions here: https://github.com/Yoast/wordpress-seo/pull/19087 
*
*
Fixes [PC-875](https://yoast.atassian.net/browse/PC-875)
> Change version number in the upgrade routine

- inc/sitemaps/class-author-sitemap-provider.php
- src/builders/indexable-author-builder.php
- src/builders/indexable-builder.php
- src/exceptions/indexable/author-not-built-exception.php
- src/exceptions/indexable/not-built-exception.php
- src/helpers/author-archive-helper.php
- src/integrations/watchers/indexable-author-archive-watcher.php
- src/integrations/watchers/indexable-post-watcher.php
- tests/unit/builders/indexable-author-builder-test.php
- tests/unit/integrations/watchers/indexable-post-watcher-test.php
* We do not want to create indexables for users when:
* Author archives are disabled.
* An author/user does not have public facing posts or pages.
* We want to schedule a cleanup of the indexables table when:
* Author archives are disabled. (The cleanup should remove the author indexables again).
* A post gets updated in such a way that its author does not have any public facing posts anymore.
* E.g. gets set to be a private post or the last post of an author gets deleted. 
* Fixes a bug where indexables were created for users when author archives were disabled.
* Fixes a bug where indexables were created for users who did not have any publicly viewable posts.
* Fixes a bug where indexables for users did not get removed when …
> PC-853 When author archives are disabled we should not store indexables for author pages

- composer.json
- src/actions/indexing/indexable-post-indexation-action.php
- src/actions/indexing/indexable-term-indexation-action.php
- src/actions/indexing/post-link-indexing-action.php
- src/actions/indexing/term-link-indexing-action.php
- src/builders/indexable-builder.php
- src/builders/indexable-post-builder.php
- src/builders/indexable-term-builder.php
- src/exceptions/indexable/not-built-exception.php
- src/exceptions/indexable/post-not-built-exception.php
- src/exceptions/indexable/term-not-built-exception.php
- src/generators/schema/breadcrumb.php
- src/generators/schema/webpage.php
- src/helpers/post-helper.php
- src/helpers/post-type-helper.php
- src/helpers/taxonomy-helper.php
- src/integrations/admin/indexables-exclude-taxonomy-integration.php
- src/presentations/indexable-term-archive-presentation.php
- src/routes/yoast-head-rest-field.php
- tests/unit/actions/indexing/indexable-post-indexation-action-test.php
- tests/unit/actions/indexing/indexable-term-indexation-action-test.php
- tests/unit/actions/indexing/post-link-indexing-action-test.php
- tests/unit/actions/indexing/term-link-indexing-action-test.php
- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/builders/indexable-term-builder-test.php
- tests/unit/helpers/post-helper-test.php
- tests/unit/routes/yoast-head-rest-field-test.php
* We don't want to store indexables for non public pages/tax types
* Fixes a bug where an entry to the indexable DB table would be added when saving, or updating or accessing a post (or term) for a non-public post type (or taxonomy).
* Introduces the `wpseo_indexable_excluded_taxonomies` filter, to allow manually excluding taxonomies from being indexed. 
* None.
**_Note: Pay special attention to Query Monitor for PHP errors_**
**Post type both non-public AND non-publicly queryable - Create/Update (not included in our production version)**
* Enable a custom post type creator
* Add a custom post type with the properties `public` and `Publicly Queryable` set to false.
* Add …
> Don't store indexables for non-public post/tax types

- packages/js/src/settings/components/sidebar-recommendations.js
- src/presenters/admin/sidebar-presenter.php
*
* Put 'get' in sidebar upsell ad outside of `<strong>` tags.
*
* Make sure that Yoast SEO premium is **not** active.
* Go to the Yoast SEO settings page.
* Verify that `get` in `get new features & tools` in the Premium upsell on the right of the page is **not** bold.
*
*
Fixes [PC-919](https://yoast.atlassian.net/browse/PC-919)
> Change bold 'get' in sidebar ad

- admin/tracking/class-tracking-addon-data.php
* When `Locations inherit shared business info` is set to `off` in Local SEO, the `business_type` should not get added to the addon data but it is.
* Remove `business_type` from addon tracking data when `Locations inherit shared business info` is turned off.
*
* Activate Yoast SEO and Yoast Local SEO.
* Go to Yoast SEO -> Local SEO
* Set `My business has multiple locations` to `on`.
* Set `All locations are part of the same business` to `on`.
* Set `Locations inherit shared business info` to `on`
* Set `Business type` to `Preschool` (for example).
* Add the following piece of code to `admin/class-admin.php` in Yoast SEO at the end of the constructor:
```
if ( …
```
> Filter admin tracking data for Local SEO

- inc/class-upgrade.php
- src/integrations/cleanup-integration.php
- tests/unit/integrations/cleanup-integration-test.php
* Since the cleanup and upgrade routine have been introduced, a new helper functions were added. They are a better fit for what we're trying to do.
* Fixes an unreleased bug where the post_format indexable would not be removed when updating the plugin while post_format archives are disabled. 
* n/a
👉 Start testing without having this branch checkedout yet
1. In the search appearance settings, make sure post_format archives are disabled.
2. Perform a full reindex on the latest release (wp yoast index --reindex --skip-confirmation).
3. Verify that there are post_format indexables in the indexables table the database `*`.
4. checkout this branch.
5. Refresh any page. This …
> Improve consistency with indexable builders

- admin/tracking/class-tracking.php
* The localSEO data tracking has more complexity than we first thought, so we want to remove the collection for now.
* Removes unreleased addon tracking from the data collection.
*
* This is not really testable because the data tracking happens in the background.
* 
*
*
Fixes #
> Removes addon data tracking.

- .github/workflows/cs.yml
- .github/workflows/deploy.yml
- .github/workflows/integrationtest.yml
- .github/workflows/lint.yml
- .github/workflows/unittest.yml
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Caches used in GH Actions …
> GH Actions: various tweaks

- admin/class-my-yoast-proxy.php
- admin/class-yoast-network-admin.php
- src/conditionals/admin/estimated-reading-time-conditional.php
- src/conditionals/third-party/elementor-edit-conditional.php
- src/integrations/admin/helpscout-beacon.php
- src/integrations/settings-integration.php
- src/integrations/third-party/elementor.php
- tests/integration/admin/test-class-yoast-network-admin.php
- tests/unit/conditionals/estimated-reading-time-conditional-test.php
- tests/unit/main-test.php
* Reduce noise from PHP 8.1 deprecations
* Reduce noise from PHP 8.1 deprecations
The deprecation of the `FILTER_SANITIZE_STRING` constant will be addressed at a later point, but is causing undue confusion for users, so for now, we'll be silencing the deprecation notices.
Includes updating a few test expectations to no longer expect the deprecation notice.
* _N/A_ This just works - see: https://3v4l.org/9QiUq
> CS/QA: silence a few deprecations

- src/builders/indexable-builder.php
* After a recent change the author_id was overwitten with the indexable_id of the author. This is incorrect
* Fixes and unreleased bug where post indexables would get the incorrect author_id when the author has an archive.
* n/a
1. have a publicly viewable posttype (posts will do just fine).
2. Have author archives enabled.
3. Create a new user and give them the admin role (or something else that can publish posts, but it doesn't matter)
4. While still logged in with your user, create a new post, and before publishing, change the author of the post to your new user.
5. Publish the post
6. Check the database: the indexable record for the new post now has an author_id of the wrong user (it equals the id of the _indexable_ of the …
> Don't overwrite author_id with indexable id

- admin/class-admin-init.php
* We want to have fewer notifications
* Removes a notification that prompts users to help with translating the plugin in the language of the site.
* None.
* Disable premium
* Switch to a different language then english for example dutch. Go to https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard and make sure there is no notification with the text
`You're using WordPress in Dutch. While Yoast SEO has been translated to Dutch for 94%, it's not been shipped with the plugin yet. You can help! Register at [Translating WordPress](https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/) to help complete the translation to Dutch!` …
> Remove notification from free

- packages/js/src/first-time-configuration/first-time-configuration-steps.js
- packages/js/src/first-time-configuration/tailwind-components/helpers/index.js
- packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
- src/actions/configuration/first-time-configuration-action.php
- src/integrations/admin/first-time-configuration-integration.php
* We want to add a new `Website name` text field in the `Site Representation` step of the `First-time configuration`
* Adds a new `Website name` text field in the `Site Representation` step of the `First-time configuration`.
*
* Go to `Yoast SEO` -> `General` -> `First-time Configuration` tab
* Advance to the `Site Representation step`
* Notice the `Website name` text field is pre-filled with your blog's name
* Change the value in `Website name` and click `Save and continue`
---
* Go to `Yoast SEO` -> `Search Appearance`
* Under `Knowledge Graph & Schema.org` you'll find the `Website name` text field with the value you have specified previously
* Change it and press `Save …
> PC-848-add-support-for-website-name-to-first-time-configuration

- admin/class-admin-asset-dev-server-location.php
- admin/class-admin-asset-manager.php
- admin/class-config.php
- admin/metabox/class-metabox.php
- config/grunt/task-config/aliases.yaml
- config/grunt/task-config/clean.js
- config/grunt/task-config/copy.js
- config/webpack/paths.js
- css/src/admin-global.css
- css/src/metabox.css
- css/src/yst_plugin_tools.css
- packages/js/package.json
- packages/js/src/initializers/admin.js
- packages/js/tests/components/SEMrushCountrySelector.test.js
- src/integrations/third-party/elementor.php
- tests/integration/admin/test-class-admin-asset-dev-server-location.php
- yarn.lock
*  We want to stop using select2, since it's bad for accessibility and maintenance of our code.
* Stops using select2 to render the selects in Search Appearance > Breadcrumbs.
* Remove select2 from the dependencies.
* **Important**: this can only be released after, or in connection with, https://github.com/Yoast/wordpress-seo-premium/pull/3700 and https://github.com/Yoast/wordpress-seo-local/pull/2361
* The breadcrumbs settings are slated to be included in the new settings UI so it might just happen that the Search Appearance page is completely removed before this is merged. This is an even stronger reason to remove a dependency that's going to be useless.
* visit Search …
> PC-715 Do not use select2 for the breadcrumbs select and remove the library from the bundle

- src/builders/indexable-author-builder.php
- src/helpers/author-archive-helper.php
- tests/unit/builders/indexable-author-builder-test.php
* When SEO optimization is not run, querying the indexables table to figure out whether an author has authored public posts will fail.
* As a result, author archives will be no-indexed when SEO optimization is not run 
* Fixes an unreleased bug where author archives would get no-indexed if SEO optimization hasn't been ran.
* We no longer query indexables when assessing whether an author has authored public posts, upon page load of author archives. We now use `WP_Query` instead.
* NOT have Yoast SEO active
* create xyz author
* create a post with the xyz author
* THEN activate Yoast SEO
* Visit `/author/xyz` archive page and confirm it's no-indexed with the previous RC (or …
> Calculate posts of authors via the WP way

- inc/class-upgrade.php
* Changes a couple of queries to make sure they don't create a notice.
* Fixes a bug where the upgrade routine would throw a notice when certain queries were executed.
* None.
* Run the upgrade routine and confirm that there are no PHP notices in the debug.log file afterwards.
Taken from [the original cleanup PR](https://github.com/Yoast/wordpress-seo/pull/19087):
👉 _Start testing with our production version installed_
1. In the search appearance settings, make sure author archives are _enabled_.
1. Perform a full reindex on the latest release (`wp yoast index --reindex …
> Change prepare to query to mitigate wp notices.

- packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
- packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
*
* [wordpress-seo-premium] Removes the beta badge from the _word complexity_ assessment.
* [wpseo-woocommerce] Removes the beta badge from the _word complexity_ assessment.
* [shopify-seo] Removes the beta badge from the _word complexity_ assessment.
* [yoastseo] Removes the beta badge from the result of the WordComplexityAssessment.
*
* Install and activate the previous version of Yoast SEO (19.10)
* Install and activate the previous version of Yoast SEO Premium (19.5)
* Add at least 50 characters of content.
* Confirm that in front of the word complexity assessment, a beta badge is shown.
* Install and activate Yoast SEO with the badge removed
* …
> PC-962 Remove beta badge from word complexity assessment

- admin/ajax.php
* Improve PHP 8.1 compatibility for `wpseo_set_ignore` function.
*
* Activate Yoast SEO and go to `Settings` -> `Reading`.
* Enable `Discourage search engines from indexing this site`.
* Go to the WordPress dashboard and click on `I don't want this site to show in the search results.` in the error notification that pops up.
* Reload the page and verify that the notification does not appear anymore.
*
*
Fixes #
> DUPP-670 Fix filter_var for wpseo_set_ignore function

- config/dependency-injection/services.php
- src/integrations/front-end/robots-txt-integration.php
- src/presenters/robots-txt-presenter.php
- tests/unit/integrations/front-end/robots-txt-integration-test.php
- tests/unit/presenters/robots-txt-presenter-test.php
* Improved line ending handling for robots.txt contents.
* Improved line ending handling for robots.txt contents.
* Move the data provider up to be directly below the test using it.
* Rename the index key for the parameter in the datasets to match the parameter name as used by the test method (to prevent issues with PHP 8.0 named parameters).
* Remove the unused `'sitemap'` sub array key.
As things were, the `Robots_Txt_Helper` was mixing the use of `"\n"` (Linux new lines) and `PHP_EOL` (OS-based new lines).
This could (on non-Linux machines) result in the text string being generated for `robots.txt` having mixed line endings, which is never a good idea.
The [RFC regarding `robots.txt`](https://datatracker.ietf.org/doc/rfc9309/) …
> Robots_Txt_[Helper|Integration]: fix line ending handling robots.txt

- src/commands/cleanup-command.php
- src/integrations/cleanup-integration.php
* Not all sites can rely on WP-CRON for the cleanup or want the cleanup to be done faster and want more control over it.
* Adds a WP-CLI command to cleanup unused data from our custom database tables:`wp yoast cleanup`
* To reduce the impact of this change, I directly depend on the Cleanup_Integration. This is a bit nasty. I would've split up the responsibilities of cleaning up the tables from the Cron-specific implementation if test-scope wasn't a concern.
* When the cleanup is done for a site, I unschedule the CRON, because that wouldn't have anything left to cleanup.
* Use a plugin like _Custom Post Type UI_ to register a new post type that has `public` = `true`.
* …
> Add a CLI command to run a cleanup of our custom tables

- admin/class-admin-init.php
* We want to be compatible with PHP 8.1
* Improves PHP 8.1 compatibility for `load_admin_page_class` function.
*
*
* Activate Yoast SEO and head over to any of the following Yoast SEO admin pages (General, Social Tools).
* Verify whether the following upsell block appears:
Fixes #
> DUPP-670 Fix filter_input call for load_admin_page_class function

- admin/ajax/class-yoast-plugin-conflict-ajax.php
* Improve PHP 8.1 compatibility for `dismiss_notice` function.
*
* The class seems to be not used so there are no test instructions for this PR.
*
*
Fixes #
> DUPP-670 Fix filter_var call for dismiss_notice

- src/integrations/watchers/indexable-post-type-change-watcher.php
- src/integrations/watchers/indexable-taxonomy-change-watcher.php
* Both the check for a cleanup cron job already scheduled and the actual scheduling of a new cron job were wrongly doubled. 
* Removes unnecessary duplicated checks
* Sets correct delay in seconds for post types watcher
*
**Note:** these are basically part of the instructions of the [original PR](https://yoast.atlassian.net/browse/DUPP-618) except for some temp things that were there while other PRs were in the process
**Prerequisite**
* install and activate [CPT UI](https://wordpress.org/plugins/custom-post-type-ui/)
* install and activate [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/)
* Add the following code to your WordPress theme:
```
add_filter( …
```
> Remove unneeded repetitions

- packages/analysis-report/src/AnalysisResult.js
- packages/components/src/insights-card/InsightsCard.js
- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
- packages/js/src/insights/components/estimated-reading-time.js
- packages/js/src/insights/components/flesch-reading-ease.js
- packages/js/src/insights/components/text-length.js
* After moving the Flesch reading ease assessment to Insights, we [added a notice in the Readability analysis metabox](https://github.com/Yoast/wordpress-seo/pull/18677) to inform the users. This notice can now be removed.
* Removes the note in the readability analysis results that tells users that the Flesch reading ease score has moved to the insights section.
*
* Open the readability analysis in the metabox.
* Confirm that below the assessments no notice on the Flesch reading ease assessment is shown.
* Repeat the above steps for the readability analysis in the sidebar.
* Repeat the above steps, but given that there is no sidebar, you only have to …
> Remove Flesch reading ease move notice

- packages/yoastseo/spec/worker/createWorkerSpec.js
- packages/yoastseo/src/worker/createWorker.js
- src/integrations/third-party/web-stories-post-edit.php
- tests/unit/integrations/third-party/web-stories-post-edit-test.php
* Our `analysis-worker.js` file was not being loaded when creating a Web Story through the Google Web Stories plug-in, breaking the Yoast metabox, and not allowing analysis. 
* After some research, we found that this was due to strict CORS headers from the Web Stories plug-in. With the introduction of the "Video Optimization" setting in the Web Stories plug-in, these strict headers were introduced, and as a result, the analysis broke. 
* Fixes a bug where the content analysis would not load when editing web stories in the Web Stories plug-in. 
* With this PR, we add an integration that is only loaded when the Web Stories plug-in is activated and we are creating/editing a post. 
* When this post is of the `web-story` type, we add …
> PC-343 Fixes loading of the webworker while editing posts with the Web Stories plug-in

- src/integrations/admin/installation-success-integration.php
- src/integrations/admin/old-configuration-integration.php
- src/integrations/settings-integration.php
- tests/unit/integrations/admin/installation-success-integration-test.php
- tests/unit/integrations/admin/old-configuration-integration-test.php
- tests/unit/integrations/settings-integration-test.php
* This PR continues on the work made in https://github.com/Yoast/wordpress-seo/pull/19125
* Fixes deprecated warning generation when executing under PHP 8.1. Props to [@davefx](https://github.com/davefx).
*
* To test the `old-configuration-integration` go to https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_configurator and make sure you get redirected to https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard#top#first-time-configuration
* To test the `settings-integration` open https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_settings#/site-basics and change a setting. Save the setting and make sure you get the `Great! Your settings were …
> Adds community patch PHP 8.1 improvements and adds unit tests

- composer.json
- composer.lock
* Remove our Yoast i18n composer dependency. As we were already not using it anywhere in the code, this should not have any impact.
* Removed the Yoast_i18n package.
* No user impact.
> Remove our Yoast i18n composer dependency

- admin/tracking/class-tracking-addon-data.php
- admin/tracking/class-tracking.php
* Add local SEO data to the tracking
*  Adds addon tracking to our tracking data set.
*
* This PR can be acceptance tested by following these steps:
* Activate Yoast SEO and Yoast Local SEO and Woocommerce.
* Go to Yoast SEO -> Local SEO
* Set `My business has multiple locations` to `on`.
* Set `All locations are part of the same business` to `on`.
* Set `Locations inherit shared business info` to `on`
* Set `Business type` to `Preschool` (for example).
* Add the following piece of code to `admin/class-admin.php` in Yoast SEO at the end of the constructor:
``` …
```
> Enable tracking and add woocommerce check

- packages/js/src/settings/routes/site-representation.js
* Implemented the suggested quick win from Luc (in the issue comments)
* Finetunes the site representation user profile alerts in the Settings UI for when a user does not have the capabilities to alter the profiles.
*
* Log in as a user with the SEO manager role (or something else that does not allowed editing of random users?)
* Open the Settings UI
* Go to site representation
* Switch to represent a user and change the user to someone that is not your current user
* Verify the alert changes:
* Removed the alert at the top of the other profiles section
* Added a sentance at the end of the alert under the user select:
*
This …
> Settings UI: change site representation user rights notifications

- src/helpers/indexables-page-helper.php
* Improved PHP 8.2 compatibility
* Improved PHP 8.2 compatibility
* This property is assigned to from within the class constructor, so is a known property which should be declared.
* _N/A_
> PHP 8.2 | Indexables_Page_Helper: declare a missing property

- tests/unit/builders/indexable-post-builder-test.php
- tests/unit/doubles/models/indexable-mock.php
- tests/unit/integrations/watchers/indexable-post-watcher-test.php
... with the properties listed in the class docblock of the `Yoast\WP\SEO\Models\Indexable` class.
Includes a minor fix to one tests to prevent having to _also_ mock the ORM class, while still making sure the test tests what it should be testing.
* _N/A_ This is a test only change, if the build passes, we're good.
> PHP 8.2 | Tests: improve Indexable_Mock & use in more places

- src/context/meta-tags-context.php
- tests/unit/doubles/context/meta-tags-context-mock.php
- tests/unit/helpers/schema/id-helper-test.php
- tests/unit/integrations/front-end-integration-test.php
Take note of the addition of `$schema_article_type` to the properties list.
This property is referenced in the `Yoast\WP\SEO\Generators\Schema\Person::site_represents_current_author()` method on line 274.
> PHP 8.2 | Tests: improve Meta_Tags_Context_Mock & use in more places

- tests/unit/doubles/models/primary-term-mock.php
- tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
... with the properties listed in the class docblock of the `Yoast\WP\SEO\Models\Primary_Term` class.
* _N/A_ This is a test only change, if the build passes, we're good.
> PHP 8.2 | Tests: improve Primary_Term_Mock & use in more places

- packages/js/src/settings/app.js
- packages/js/src/settings/components/route-layout.js
* ⚠️ This PR is branched of from `feature/new-settings-ui-phase-6` and requested to be merged in there ⚠️ -- this seems like the best solution until that is merged
* UX has not looked at this in detail yet.
* Adds a transition around the `routes` to make it more obvious when you switch pages.
* Nice `key` prop to force React to rerender whenever the route changes. Which makes it always appear.
* Go to the Settings UI
* Switch routes.
* Notice the effect.
* Specifically when switching between Posts and Pages for example. There was not to notify the page did in fact change before this PR.
* Ensure there is no effect on initial page load. …
> Add a transition when a route changes

- src/presentations/indexable-presentation.php
- tests/unit/doubles/presentations/indexable-presentation-mock.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/generators/schema/breadcrumb-test.php
- tests/unit/helpers/schema/replace-vars-helper-test.php
- tests/unit/integrations/breadcrumbs-integration-test.php
- tests/unit/integrations/third-party/woocommerce-test.php
... and implement the use of this new `Indexable_Presentation_Mock` class in select test classes.
Includes adding some missing properties to the docs for the `Indexable_Presentation` class.
> PHP 8.2 | Indexable_Presentation: work around dynamic properties

- tests/unit/doubles/models/indexable-hierarchy-mock.php
- tests/unit/repositories/indexable-hierarchy-repository-test.php
... and implement the use of this new `Indexable_Hierarchy_Mock` class in select test classes.
> PHP 8.2 | Indexable_Hierarchy: work around dynamic properties

- tests/unit/presenters/open-graph/description-presenter-test.php
This property is being set in the test `set_up()` and should be declared.
> Description_Presenter_Test: declare known property

- tests/unit/generators/schema/webpage-test.php
The `website_hash` property is set on the `ID_Helper` class at the end of the `WebPage_Test::set_up()` method.
However, in the whole of the YoastSEO code base, no `$website_hash` property exists, nor any references to a `->website_hash` property, only to a class constant by the same name.
I suspect this is a "stray"/copy-paste test-only bug and that the property assignment should just be removed.
The `primary_image_hash` and `breadcrumb_hash` properties are set on the `ID_Helper` class from within the `test_generate_with_provider()` test method.
However, in the whole of the YoastSEO code base, no `$primary_image_hash` nor …
> WebPage_Test: remove stray property assignments

- tests/unit/actions/indexables/indexable-head-action-test.php
- tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
- tests/unit/builders/indexable-link-builder-test.php
- tests/unit/builders/primary-term-builder-test.php
- tests/unit/dependency-injection/schema-templates-pass-test.php
- tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
- tests/unit/integrations/watchers/primary-term-watcher-test.php
- tests/unit/models/indexable-test.php
- tests/unit/repositories/indexable-hierarchy-repository-test.php
- tests/unit/repositories/indexable-repository-test.php
Including for YoastSEO native dependency classes.
> Tests: use named mocks for YoastSEO native classes

- src/generators/schema-generator.php
- src/generators/schema/abstract-schema-piece.php
* Improved PHP 8.2 compatibility
* Improved PHP 8.2 compatibility
The `Schema_Generator::filter_graph_pieces_to_generate()` method would previously check using `property_exists()` whether a non-declared, dynamic property `$identifier` has been added to the graph piece.
As dynamic properties are deprecated and this is a "known" (non-variable name) property, we may as well declare the `$identifier` property on the `Abstract_Schema_Piece` class, which all schema pieces extend.
By changing the function call in the `Schema_Generator::filter_graph_pieces_to_generate()` method from `property_exists()` to `isset()`, we maintain the same behaviour, but the code is now compatible with PHP 8.2.
This PR can be acceptance tested by following …
> Schema_Generator/Abstract_Schema_Piece: improve handling of optional identifiers

- tests/unit/commands/index-command-test.php
* Add class name into the call to Mockery if the name was missing.
* Add import `use` statement if it was missing.
* Use class name resolution via the `::class` constant
Note: no "double" is added as the class uses `Mockery:mock()` with `overload:`.
See: http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#overloading
* Add class name into the call to Mockery if the name was missing.
* Add import `use` statement if it was missing.
* Use class name resolution via the `::class` constant
Note: no "double" is added as no properties are being set on the class either by the tests or by the code under test.
This PR can be …
> Tests: use named mocks for WP_CLI native classes

- admin/tracking/class-tracking.php
* We want to fix a compatibility problem with PHP 8.1 when we schedule a job to send tracking data after a core upgrade.
* Fixes a bug that would affect users managing the cron jobs with a plugin on PHP 8.1 after they have performed a core upgrade.
* The problem has been reported with PHP 8.0, but it gives just a warning in that case that can be easily suppressed. In PHP 8.1 the problem triggers a fatal error, that's why we are treating it as a PHP 8.1 compatibility issue.
* if the cron job is scheduled in the wrong way as it happens currently, it will stay this way until it runs. For the sake of simplicity, **we're not introducing an upgrade routine** to remove the offending cron job, because it will run anyway and will thus be …
> DUPP-755 - PHP 8.1 compat: Use array to pass parameters to schedule a cron job to send tracking data after core update

- src/integrations/third-party/web-stories.php
- tests/unit/integrations/third-party/web-stories-test.php
* #18977
The above PR is not really correct. It disables the wrong filter in the Web Stories plugin (the correct one would be `web_stories_enable_document_title`) and it also wrongly depends on the type of theme being used (block theme vs classic).
Yoast SEO should always override the Web Stories plugin's default behavior and use its own presenters to add things like title tags and meta descriptions, regardless of theme support.
Please note that at the same time we're also making some changes to the Web Stories plugin itself to ensure there are never duplicate title tags, and never missing title tags.
I would appreciate being contacted before making changes to the Web Stories integration class in the future so that we can better coordinate such fixes.
This PR can be summarized in the …
> Enforce displaying title tags for web stories

- lib/abstract-main.php
- src/exceptions/forbidden-property-mutation-exception.php
- src/surfaces/helpers-surface.php
- src/surfaces/open-graph-helpers-surface.php
- src/surfaces/schema-helpers-surface.php
- src/surfaces/twitter-helpers-surface.php
- tests/unit/TestCase.php
- tests/unit/admin/admin-features-test.php
- tests/unit/admin/tracking/tracking-test.php
- tests/unit/admin/views/feature-toggles-test.php
- tests/unit/generators/schema-generator-test.php
- tests/unit/helpers/wincher-helper-test.php
- tests/unit/inc/addon-manager-test.php
- tests/unit/inc/language-utils-test.php
- tests/unit/inc/sitemaps/sitemaps-admin-test.php
- tests/unit/integrations/admin/deactivated-premium-integration-test.php
- tests/unit/integrations/admin/migration-error-integration-test.php
- tests/unit/integrations/watchers/option-wpseo-watcher-test.php
- tests/unit/main-test.php
- tests/unit/presenters/admin/migration-error-presenter-test.php
- tests/unit/presenters/admin/notice-presenter-test.php
- tests/unit/surfaces/classes-surface-test.php
- tests/unit/surfaces/helpers-surface-test.php
- tests/unit/surfaces/meta-surface-test.php
- tests/unit/surfaces/open-graph-helpers-surface-test.php
- tests/unit/surfaces/schema-helpers-surface-test.php
- tests/unit/surfaces/twitter-helpers-surface-test.php
PHP 8.2 deprecates the use of dynamic properties.
* Improve compatibility with PHP 8.2
* Disallow setting or unsetting any dynamic properties on Abstract_Main.
* The isset implemenation used to call the magic __get as part of its implementation. This is not how it is intended.
* To further prevent any dynamic properties being set, the __set and __unset will always throw an exception, because there is no reason to set any dynamic properties anymore.
* When mocking away our surfaces_helper, we often combine it with setting dynamic properties. This is deprecated since PHP 8.2 and will fail tests on PHP >= 8.2. Also, when we mock away our internals, we hide potential issues in our own code. So, with these helpers in the testCase, we …
> PHP 8.2 | Abstract_Main and surface helpers: Fix use of dynamic properties 

- packages/js/src/settings/hocs/with-disabled-message-support.js
- packages/js/src/settings/routes/crawl-optimization.js
- src/integrations/settings-integration.php
*
* Fixes the Crawl optimization page' support for disabled options. Both disallowed by the network admin and unavailable on multisite.
* In the current/old options UI, the disabling of the multisite is determined in the specific views. Here I created a list in the settings integration instead. We should keep this in mind for the cleanup. The "normal" disabled is controlled via the options framework. Not sure why this is not, but out of scope for now I think.
* Switch to a multisite environment.
* Disable some crawl optimization settings in the network admin.
* Go to a sub site and verify in the Settings UI' Crawl optimization that those options are disabled with the …
> Settings UI: crawl cleanup robots txt modification rules should be disabled on multisite

- packages/js/src/settings/app.js
- packages/js/src/settings/components/sidebar-recommendations.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/crawl-optimization.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/site-features.js
- packages/js/src/settings/routes/templates/post-type.js
- packages/js/src/settings/routes/templates/taxonomy.js
- packages/js/src/settings/store/default-settings.js
- packages/ui-library/src/components/feature-upsell/index.js
- src/integrations/settings-integration.php
We want to add some configuration options to our buy buttons.
* Adds upsell data attributes to the new settings ui
* I added the data to the default settings store so we have one source of truth.
* Open the following pages and make sure all the buttons have `data-action` with value `load-nfd-ctb` and `data-ctb-id` with value `57d6a568-783c-45e2-a388-847cff155897`. Also make sure that when you hit a button or link it still sends you to the url attached to the button.
https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_settings#/site-features
https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_settings#/crawl-optimization …
> Add upsell configuration to buy buttons

- packages/yoastseo/src/worker/createWorker.js
* In this PR #19170 we made it possible to load the worker in a web story, by creating a worker blob when editing in a web story in `createWorker.js`
* This requires us to check `wpseoAdminL10n` whether the post type is indeed a web story:
````
if ( ! isSameOrigin( window.location, url ) || window.wpseoAdminL10n.isWebStoriesIntegrationActive === "1" ) {
return createWorkerFallback( url );
}
```` 
* However, when `createWorker` is used `shopify-seo`, we don't have access to `wpseoAdminL10n`. This will return undefined and trying to access a key of an undefined object will cause an error (in this case, it was a silent error without warning at all)
* As a result, in Shopify, we cannot load the worker since we failed to create one.
* In this PR, we add a safeguard to check if `wpseoAdminL10n` …
> PC-989 Add a safeguard to check if wpseoAdminL10n is defined in the worker

- src/surfaces/values/meta.php
- tests/unit/surfaces/values/meta-test.php
* Improve PHP 8.2 compatibility
* Improve PHP 8.2 compatibility
The magic `Surfaces\Values\Meta::__get()` method was creating dynamic properties on the class, where dynamic properties are properties not declared on the class which subsequently created on the fly as `public` properties.
As of PHP 8.2, creating dynamic properties is deprecated.
This commit fixes this by:
* Declaring a `private` `$properties_bin` array property to the class.
* Adjusting the magic `__get()` method to save the values for the properties in the `$properties_bin` instead of dynamically creating properties.
* Adjusting the magic `__get()` method to take values previously saved to the `$properties_bin` into account.
* Adjusting the magic `__isset()` method …
> Surfaces\Values\Meta: fix dynamic property setting in magic methods

- packages/js/src/settings/helpers/submit.js
- src/integrations/settings-integration.php
- tests/unit/integrations/settings-integration-test.php
* New settings UI page id conflicts with admin bar settings submenu id.
* Fixes an unreleased bug where `SEO Settings` admin bar submenu would not show when new settings UI is enabled.
*
* Test with [this Premium PR](https://github.com/Yoast/wordpress-seo-premium/pull/3756).
* On `trunk` branch (before merge) with the new settings UI enabled, verify that the `SEO Settings` submenu is not showing in our admin bar menu.
* On this branch, verify that above issue is fixed.
* On this branch, verify that you can still correctly save your settings in the new UI.
* …
> Change new settings UI page id

- admin/metabox/class-metabox-analysis-inclusive-language.php
* Previously, in [this PR](https://github.com/Yoast/wordpress-seo/pull/19115), we decided on the following:
* With Premium 19.2, we use the inclusive language as defined in Free.
* With Premium 19.2.1 - 19.6 activated, we use the inclusive language analysis as defined in Premium.
* With Premium >= 19.7 activated, we use the inclusive language analysis as defined in Free.
* However, in the upcoming Free 19.11 release cycle, we will **not** release Premium. Therefore, we need our to change our approach to the following:
* With Premium 19.2, we use the inclusive language as defined in Free.
* With Premium 19.2.1 - 19.5 activated, we use the inclusive language analysis as defined in Premium.
* With Premium >= 19.6 activated, we use the inclusive language analysis as defined in Free.
* …
> PC-961 inclusive language analysis is not loaded when premium is activated

- inc/class-wpseo-replace-vars.php
- tests/integration/test-wpseo-functions.php
* utf8_decode is deprecated since PHP 8.2.
* Improve PHP 8.2 compatibility.
* We used utf8_decode before to transform multibyte characters like Japanese to singlebyte `?` characters so we could count them. PHP already has a function to count mb strings, which is also [polyfilled by WordPress core](https://github.com/WordPress/WordPress/blob/f3b087164dcb42eb18bd7fa1e66e6ea116ccb0c2/wp-includes/compat.php#L151).
* This PR brings _no_ functionality change. This is a regression test.
* Change the site language to Japanese.
* Create a post and insert the `excerpt` replace var in the meta description.
* In the post content, paste this:
* …
> PHP 8.2 | utf8_decode deprecation

- src/presentations/abstract-presentation.php
* Improve PHP 8.2 compatibility
* Improve PHP 8.2 compatibility
... for now.
Realistically, the magic methods should be fixed, but even more realistically, we should probably have a look at injecting the `Presentation` objects into the `Presenter` classes using the `Abstract_Presentation::of()` method.
This is, however, out of scope for the current task at hand. An issue will be opened to address this at a later date.
In the mean time, we'll hide the PHP 8.2 "Creation of dynamic properties is deprecated" notices by applying the `#[AllowDynamicProperties]` attribute to the `Abstract_Presentation` class.
As this attribute is inherited by child classes, this also fixes the remaining issues with the `Meta_Tags_Context` class, the …
> Abstract_Presentation: brute force allow dynamic properties

- .github/workflows/integrationtest.yml
- .github/workflows/unittest.yml
* Safeguard PHP 8.2 compatibility via CI
* Safeguard PHP 8.2 compatibility via CI
... and as the tests currently pass without issue, don't allow the build to fail.
> GH Actions: run the tests against PHP 8.2

- packages/js/src/settings/app.js
- packages/js/src/settings/components/sidebar-recommendations.js
- packages/js/src/settings/hocs/with-disabled-message-support.js
- packages/js/src/settings/hooks/index.js
- packages/js/src/settings/hooks/use-disabled-message.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/crawl-optimization.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/site-features.js
- packages/js/src/settings/routes/templates/post-type.js
- packages/js/src/settings/routes/templates/taxonomy.js
- packages/js/src/settings/store/default-settings.js
- packages/js/src/settings/store/preferences.js
- packages/ui-library/src/components/card/style.css
- packages/ui-library/src/components/feature-upsell/index.js
- packages/ui-library/src/elements/badge/style.css
- src/integrations/settings-integration.php
* Fix the site features cards to make it more inline with the integrations page.
* Changes the site features' cards in the Settings UI to match the integrations design more. Specifically the badges and the disabled header image.
* Moved the logic out of the higher order component and into a hook so we can re-use it in the site features specific component.
* Made a `FeatureCard` to handle all the specific logic of a site features card. (note: I wish Inverse of Control would be able to make this neater, but I see that making it more complicated in this case.)
* Bit of a scope creep with the [Change the CTB data code](https://github.com/Yoast/wordpress-seo/pull/19237/commits/b8dce67e3f8aa16616c10c0555360b31de0cb5bb) commit. …
> Settings UI: site features on network admin

- packages/js/src/settings/helpers/submit.js
* Fixes a settings save on fresh installs. Before this fix it would try to save the user' social profiles when the user id would be `false`.
* Fixes a bug where the settings would error on the user' social profiles because no user was selected.
* Check if the user ID is a number and if it is higher than `0` before we try to submit them.
* Have a fresh install, or remove the `company_or_person_user_id` from the `wpseo_titles` options row.
* Go to the Settings UI
* Verify that the site representation user is not set to a user (Site representation > Organization/person > Person > Select a user)
* Change some other option to be able to save and save
* Verify you can save …
> Settings UI: only save the user profiles when allowed and when the user ID is a number of 1 or higher

- src/integrations/watchers/indexable-post-type-change-watcher.php
- tests/unit/integrations/watchers/indexable-post-type-change-watcher-test.php
- tests/unit/integrations/watchers/indexable-taxonomy-change-watcher-test.php
* In https://github.com/Yoast/wordpress-seo/pull/19095 we added two watchers to detect when post types or taxonomies switch from being public to private and vice-versa. With this PR we add unit tests for those watchers.
* Adds unit tests for the post type/taxonomy viewability watchers
*
* N/A (no changes in public code)
*
* No impact check
Fixes #
> Unit tests for the viewability watchers

- composer.json
- composer.lock
- src/integrations/admin/unsupported-php-version.php
* We want to throw a notice to admins to notify we're dropping compatibility with PHP < 7.2 starting March 1st, 2023
* Introduces a notice on the WordPress dashboard and the Yoast SEO dashboard to let users know we're dropping support for PHP < 7.2 starting March 1st, 2023.
* `yoast/whip` is not vendor prefixed because it's not namespaced. Also, it takes care of version differences by itself (on a version bump method names should change)
* Run `grunt artifact` to create a zip. This makes it way easier to test on different envs.
* Find a way to have WP running on PHP 5.6, 7.0 and 7.1.
* e.g. I was able to have a Local by Flywheel site on PHP 5.6. I'm on Linux, I know other …
> DUPP-668 Use WHIP to deprecate PHP < 7.2

- packages/js/src/settings/helpers/search.js
- packages/js/src/settings/helpers/submit.js
- packages/js/src/settings/routes/site-basics.js
- packages/js/src/settings/routes/site-representation.js
- src/integrations/settings-integration.php
* Adding the same [support that was done for our existing settings](https://github.com/Yoast/wordpress-seo/pull/19066) to the Settings UI.
* Adds support for website name, alternate website name and alternate organization name in the new settings.
*
* Go to the Settings UI > Site basics
* Verify the Site title is gone
* Verify that Website name and Alternate website name took its place
* Verify that changing the values of the above will get reflected in the old settings
* Go to the Settings UI > Site representation
* Ensure you are representing an organization
* Verify that Alternate organization name is now below the Organization name
* Verify that changing the values of …
> Settings UI: add support for website name and alternate name for both website and organization

- src/helpers/blocks-helper.php
Fixes Issue #19173 where performance issues happen due to whitespace blocks with a NULL value as the blockName
* Fix performance issues as outlined in Issue #19173
* Fixes a bug where blocks with a NULL `blockName` would trigger deprecation errors with PHP 8.1 and cause performance issues. Props to [@dustyf](https://github.com/dustyf).
*
* Set up an environment on PHP 8.1
* make sure you have WP_DEBUG set to `true`, Debug Bar and Query Monitor installed and active
* create and publish a post with several blocks (they can just be multiple paragraphs)
* visit the Frontend and check the PHP Errors in Query Monitor:
* without this patch: you should get a "Deprecated" error …
> Performance issues happen due to whitespace blocks with NULL value as blockName

- src/conditionals/third-party/elementor-edit-conditional.php
- tests/unit/conditionals/third-party/elementor-edit-conditional-test.php
* Fix PHP 8.1 compatibility for `elementor-edit-conditional` class.
*
* Install and activate Yoast SEO and Elementor.
* Edit a post with Elementor and verify whether the Yoast SEO tool shows up and works as expected.
*
*
Fixes #
> DUPP-670 Fix PHP 8.1 compatibility for elementor-edit-conditional class

- css/src/new-settings.css
- packages/js/src/settings/components/search.js
- packages/js/src/settings/helpers/search.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/breadcrumbs.js
- packages/js/src/settings/routes/crawl-optimization.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/media.js
- packages/js/src/settings/routes/rss.js
- packages/js/src/settings/routes/site-basics.js
- packages/js/src/settings/routes/site-features.js
- packages/js/src/settings/routes/site-representation.js
- packages/js/src/settings/routes/templates/post-type.js
- packages/js/src/settings/routes/templates/taxonomy.js
- packages/js/tests/settings/__snapshots__/search.test.js.snap
- packages/js/tests/settings/search.test.js
- packages/ui-library/src/components/toggle-field/style.css
- packages/ui-library/src/elements/autocomplete/style.css
- packages/ui-library/src/elements/code/style.css
- packages/ui-library/src/elements/select/style.css
- packages/ui-library/src/elements/table/index.js
* Fixes various small UX feedback points on new settings UI.
* Fixes various small UX feedback points on new settings UI.
*
* Verify that the `OpenGraph` feature card now contains `Keep this feature enabled to optimize your site for social media.` copy.
* Verify that the `XML sitemaps` feature card now contains a `View XML sitemap` **button** when enabled.
* Verify that the remove social profile icon on `Site representation` organization entity is now a button with a trash icon instead of just a trash icon.
* Verify that the copy+toggles on `Crawl optimization` are now wider than all the others, see a post type for instance.
* Verify that when you disable the `Show author …
> Dupp 793 settings UI last run ux feedback

- packages/js/src/settings/components/formik-media-select-field.js
- packages/js/src/settings/components/formik-replacement-variable-editor-field.js
- packages/js/src/settings/hocs/with-formik-dummy-field.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/crawl-optimization.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/media.js
- packages/js/src/settings/routes/templates/post-type.js
- packages/js/src/settings/routes/templates/taxonomy.js
- packages/ui-library/src/components/feature-upsell/index.js
- packages/ui-library/src/components/select-field/index.js
- packages/ui-library/src/components/select-field/style.css
- packages/ui-library/src/elements/select/index.js
- packages/ui-library/src/elements/select/style.css
* Disable fields instead hiding based on `enable` toggles for archive and media routes.
* Disable fields instead of sections based on Premium state for crawl optimization route.
* Improves the new settings UI by disabling fields instead of completely hiding them or blurring out entire sections.
* Adds `disabled` support to `Select` element and `SelectField` component in UI library.
* Go to the new settings UI.
* For the `Author archives`, `Date archives`, `Format archives` and `Media pages` routes:
* Verify that the main `enable` toggle on top of the route now disabled all fields for that route instead of hiding them completely.
* with Premium disabled, verify that …
> Dupp 684 revisit disabled fields and sections

- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/breadcrumbs.js
- packages/js/src/settings/routes/crawl-optimization.js
- packages/ui-library/src/elements/code/style.css
- packages/ui-library/src/elements/label/style.css
* Improve toggle dependencies when overarching toggle is set to disabled.
* Adds taxonomy `name` to taxonomy breadcrumb selects on `Breadcrumbs` route.
* Improve toggle dependencies when overarching toggle is set to disabled.
* Adds taxonomy `name` to taxonomy breadcrumb selects on `Breadcrumbs` route.
* Flipped toggles need negating when setting the `checked` prop manually.
* Improve the line-height of `Code` element a bit.
* On the `Crawl optimization` route:
* Verify that when the `Filter search terms` is toggled ON, you are able to change the `Filter searches with emojis and other special characters` and `Filter searches with common spam patterns` toggles freely and …
> Implement toggle deps for author archives and crawl optimization

- packages/js/src/settings/components/search.js
- packages/js/src/settings/helpers/search.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/breadcrumbs.js
- packages/js/src/settings/routes/crawl-optimization.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/media.js
- packages/js/src/settings/routes/site-basics.js
- packages/js/src/settings/routes/site-features.js
- packages/js/src/settings/routes/templates/post-type.js
- packages/js/src/settings/routes/templates/taxonomy.js
- packages/js/src/settings/store/breadcrumbs.js
- packages/ui-library/src/elements/autocomplete/index.js
- packages/ui-library/src/elements/select/index.js
- packages/ui-library/src/elements/toggle/index.js
* Improves the search index in the new settings UI.
* Improves the search index in the new settings UI.
* Move rewrite of `id` prop to `data-id` prop to UI library for `Select` and `Autocomplete` components. Allows us to always write `id` props on implementation level.
* Verify that typing a very long search term results in text overflow in the search field in sidebar:
* Verify that select labels on the breadcrumbs route now contain code blocks containing post type or taxonomy name. This should also be the case for these fields in the search results.
* Verify you can now search and find the `Add custom fields to page analysis` fields for post types.
* Verify you can now …
> Dupp 806 improve search index

- css/src/new-settings.css
- packages/js/src/settings/components/search.js
- packages/js/tests/settings/__snapshots__/search.test.js.snap
- packages/js/tests/settings/search.test.js
- packages/ui-library/src/components/modal/style.css
*
* Refactors the Search modal in the Settings UI. Uses the Headless UI combobox and sticks it to the top to prevent jumping around depending on how many search results there are.
*
* Go to Settings UI > Search
* Type something with a longer list like `open g` for `open graph`
* Verify you can now use the up & down arrows
* Verify the top of the search modal stays at the same spot
*
*
Fixes https://yoast.atlassian.net/browse/DUPP-775
Fixes https://yoast.atlassian.net/browse/DUPP-805
> Settings UI: allow using arrow up down to navigate through search results with keyboard command palette

- packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
- packages/js/src/components/contentAnalysis/SeoAnalysis.js
- packages/js/src/components/modals/MultipleKeywords.js
- packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
- packages/js/src/components/social/SocialUpsell.js
- packages/js/src/externals/contexts.js
- packages/js/src/helpers/classicEditor.js
- packages/js/src/initializers/block-editor-integration.js
- packages/js/src/initializers/elementor-editor-integration.js
- packages/js/src/insights/components/prominent-words.js
* We want to add some more parameters to our upsell buttons
* Adds a context parameter to upsell button links to add more context on where the button lives in the plugin.
* Disable premium
* Do the following in the block editor, classic and elementor.
* For the meta box, elementor and the sidebar open the following tabs and and make sure all the buttons and links that lead to a [RTU page](https://yoast.com/rtu-premium-analysis/) and with a context variable. and they start with the editor you are using and then location so for example `elementor-sidebar`
* Also make sure that when you hit a button or link it still sends you to the url attached to the button.
SEO analysis tab
Premium SEO analysis
Add related keyphrase
Readability …
> Add context parameter to upsell buttons

- packages/js/src/settings/routes/site-representation.js
- src/integrations/settings-integration.php
*
* Fixes a bug where the social profiles of a user would not be loaded in when switching from representing an organization to representing a person.
* Moved and renamed the `supportedPersonSocialProfiles` for clarity and preventing side effects (window variable) in the component.
* Had to move the sync out of PersonSocialProfiles and into SiteRepresentation due to it now needing the current and previous value of the `companyOrPerson` to check if it changed.
* Used an "overkill" `useCallback` to keep the `useEffect` dependencies a bit cleaner.
* In Settings > Site representation
* Configure person to "admin"
* Configure representation (back) to organization
* Save
* Go to …
> Settings UI: Load in the person social profiles when the switching to represent a person

- admin/class-admin-init.php
* Improvement to #19134
* Fixes an unreleased bug where pre-existing notifications about incomplete translations would be persisting in the Notification Center even after we stopped triggering them.
* Can't use an upgrade routine since notifications are per-user.
It's probably more reliable  to address this using zip instead of swithcing branches.
* Install Free 19.11
* Switch WP to a language with incomplete translations, such as Spanish for Argentina or Colombia 
* See that you get a notification suggesting to help with translations.
* Install an artifact create from this branch
* See that the notification is now gone.
* …
> Removes any persisting notification about incomplete translations

- packages/js/package.json
- packages/js/src/settings/app.js
- packages/js/src/settings/components/formik-replacement-variable-editor-field.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/homepage.js
- packages/js/src/settings/routes/index.js
- packages/js/src/settings/routes/media-pages.js
* When globally disabling an archive type, uncheck show in search results toggle. This looks like the following in author archives:
* We do this to visually show to the user the other archives are not shown in the search results either. 
* Improves the Settings UI archives and media pages under advanced by showing the "show in search results" as off when the whole feature is disabled.
* Renames the "Formats" page title to "Format archives", for consistency.
* Solved with a ternary as override `checked` prop. Checked means it is only visual (not the value). Ternary to only impact it when the overal value is disabled.
* Renamed the `media` route to `media-pages` for consistency. …
> Settings UI: when globally disabling an archive type, uncheck show in search results toggle

- css/src/yst_plugin_tools.css
* #19022 has also removed some CSS rules which Local doesn't have a replacement for. We need to reinstate them to fix the UI
* Fixes an unreleased bug where Local SEO selects in the settings page would be displayed with the wrong bottom margin.
*
* Install Local SEO
* visit the Local SEO settings page and check that the style of the selects are OK. refer to the original [bug report](https://yoast.atlassian.net/browse/DUPP-821) to see which places to check.
*
*
Fixes [DUPP-821]
[DUPP-821]: …
> Reinstate some CSS rules to fix wrong styling in Local SEO

- inc/class-wpseo-admin-bar-menu.php
* We want to add tracking parameters to the `Get Yoast SEO Premium` link in Yoast Admin Bar.
* Adds tracking parameters to the `Get Yoast SEO Premium` link in Yoast Admin Bar.
*
* Open any page in the frontend
* Go to the Yoast Admin Bar menu and inspect the link `Get Yoast SEO Premium`:
* Without this PR the link is: `https://yoa.st/admin-bar-get-premium`
* With this PR the link should be something like (parameters' values may vary): `https://yoa.st/admin-bar-get-premium?php_version=7.4&platform=wordpress&platform_version=6.1.1&software=free&software_version=19.12-RC5&days_active=6-30&user_language=en_US` 
* Perform the same inspection …
> Add tracking parameters to URL

- admin/views/licenses.php
*
* Hides the new "all the Yoast plugins" card if the user has already all the relevant plugins active.
*
* Visit the Yoast SEO > Premium page
* make sure you are on basic.wordpress.test so activation state can be tested
* try different combinations of addons: if even one of them is not activated, you should be able to see the "Buy all the Yoast plugins" card. If **all** the plugins look activated, the card should disappear
* don't forget to install and activate WooCommerce to trigger the WooSEO card, test with that as well.
*
*
Fixes …
> Hide the "all the Yoast plugins" card if the user already has all the plugins active

- packages/js/src/integrations-page/integrations-grid.js
- packages/js/src/integrations-page/seo-tools-integrations.js
*
* Hides the Semrush and Wincher cards from the last section of the Integrations page
* Renames the "SEO Tools Integrations" to "Other Integrations"
*
* Visually check the page
*
*
Fixes [DUPP-825]
[DUPP-825]: https://yoast.atlassian.net/browse/DUPP-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove duplicated integration cards

- packages/ui-library/src/components/children-limiter/stories.js
* Add unique key to eliminate warning.
* Add unique key to eliminate warning.
*
*
*
*
Fixes #
> UI library: fix unique key prop warning

- admin/class-admin.php
- inc/class-wpseo-admin-bar-menu.php
*
* Adds data attributes to the admin bar and plugins page premium links.
* Circumvent an issue in the WP admin bar API in order to pass `data` attributes. See https://core.trac.wordpress.org/ticket/38636 and https://yoast.slack.com/archives/C03KU0EHCNQ/p1670233645950939 and https://yoast.slack.com/archives/C03KU0EHCNQ/p1670245043987409
The correct data attributes to are (see issue):
* `data-action` => `load-nfd-ctb`
* `data-ctb-id` => `57d6a568-783c-45e2-a388-847cff155897`
Steps:
* Disable premium
* Go to the plugins page
* Verify the `Get premium` link under Yoast SEO has the correct data attributes.
* Check the admin bar
* Verify the `Get Yoast SEO Premium »` link has …
> Upsell: add upsell data attributes to admin bar and plugins page

- inc/class-wpseo-admin-bar-menu.php
* We want to change the way we use the `WPSEO_Shortlinker` class in the `WPSEO_Admin_Bar_Menu` class to a cleaner implementation.
* Refactors `WPSEO_Admin_Bar_Menu`  to accept `WPSEO_Shortlinker` as a constructor parameter.
* N/A
* Open a post in the front-end
* When Premium is not enabled, the Frontend Inspector link should:
* Still points to `https://yoa.st/admin-bar-frontend-inspector`
* It now adds parameters like `?php_version=8.0&platform=wordpress&platform_version=6.1.1&software=free&software_version=19.12-RC6&days_active=6-30&user_language=en_US`
* See the **Impact check** section for regression testing …
> Pass the shortlinker as a parameter to the constructor

- src/deprecated/i18n/i18n-v3.php
* By removing the I18n package dependancy in free we introduce a fatal error in premium 19.15 and below.
* Fixes a non released bug where premium would give a fatal error on the redirect page when the version was lower than 19.16.
* We chose to add a deprecation class instead of reintroducing the package to keep the impact as low as possible.
* Install and activate Free 19.12-rc6 + Premium 19.5
* Go to the redirects page. You should get a fatal error (make sure you run composer install in both)
* Activate this pr/RC and run composer again (not needed in the RC) and refresh the page. The error should be gone.
* …
> Add deprecated class to prevent fatal error from removing the I18n package.

- packages/js/src/settings/components/search.js
- packages/js/src/settings/helpers/i18n.js
- packages/js/src/settings/helpers/index.js
- packages/js/src/settings/helpers/search.js
- packages/js/src/settings/routes/author-archives.js
- packages/js/src/settings/routes/date-archives.js
- packages/js/src/settings/routes/format-archives.js
- packages/js/src/settings/routes/media-pages.js
- packages/js/src/settings/routes/site-basics.js
- packages/js/src/settings/routes/templates/post-type.js
- packages/js/src/settings/routes/templates/taxonomy.js
- packages/js/src/settings/store/search.js
- src/integrations/settings-integration.php
* Makes the search in new settings UI case insensitive.
* Makes the search in new settings UI case insensitive.
* Move from Lodash `toLower` to `string.toLocaleLowerCase` for locale specific lowercasing.
* Added a `safeToLocaleLower` helper that doesn't throw breaking errors when `locale` is invalid.
* Added a max width to the `Force rewrite titles` toggle.
* Open the search in the new settings UI.
* Verify that `SEO` and `seo` give you the same search results.
* Verify that `XML` and `xml` give you the same search results.
* Verify that section descriptions for post types and taxonomies still contain lowercase post type or taxonomy name:
* Verify that the `Force rewrite …
> Lowercase query before searching in new settings UI

- packages/ui-library/src/components/autocomplete-field/stories.js
- packages/ui-library/src/elements/autocomplete/stories.js
* Add stories for Autocomplete and AutocompleteFields
* Adds stories for Autocomplete and AutocompleteFields.
* Autocomplete stories: With label, With error, with selected label, with placeholder.
* AutocompleteField stories: With error message, with description, with selected label, with placeholder.
*
* Open storybook and check stories for Autocomplete and AutocompleteField
*
*
Fixes https://yoast.atlassian.net/browse/DUPP-723
> UI library: prepare autocomplete autocomplete field components for release

- packages/ui-library/src/components/autocomplete-field/stories.js
- packages/ui-library/src/components/checkbox-group/stories.js
- packages/ui-library/src/components/radio-group/stories.js
* Add stories for `children` prop story in `CheckboxGroup`,`RadioGroup` and `AutocompleteField` components. 
* `SelectField` has the `children` story from [DUPP-717 Revisit stories for Select element and SelectField component ](https://yoast.atlassian.net/browse/DUPP-718)
* Adds stories for `children` prop story in `CheckboxGroup`,`RadioGroup` and `AutocompleteField` components. 
*
* Open storybook and check `CheckboxGroup`,`RadioGroup` and `AutocompleteField` components for `children` prop stories.
*
*
Fixes …
> UI library: improve stories for form field components that render options as children checkbox group radio group select autocomplete

- src/builders/indexable-builder.php
- tests/integration/admin/watchers/test-class-indexable-post-watcher.php
- tests/unit/builders/indexable-builder-test.php
When performing a full reindex, I noticed that indexable hierarchy is not created. This is due to a problem where we rely on the indexable being saved to the database (and thus having an indexable id) when we generate hierarchy, but when we index a post we:
1. Create the indexable
2. Generate hierarchy (for indexableId = null)
3. Save the indexable to the database, giving it an indexable id.
* Fixes a bug where indexable hierarchy wasn't built when the Indexable is built for the first time.
* I've added some (very basic) integration tests to prove that my solution works and to pinpoint the origin of the problem. There's still a lot of tests that need to be added, which I've described in a comment.
* I've added an early return in …
> Bugfix: Create indexable hierarchy the first time an indexable is created

- .github/workflows/integrationtest.yml
- tests/unit/bootstrap.php
- tests/unit/inc/addon-manager-test.php
- wp-seo-main.php
- wp-seo.php
*
* Sets the minimum supported WordPress version to 6.0.
* N/A
* N/A
*
*
Fixes #
> Set minimal compatibility to wp 6.0

- packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
- packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
* Like 'dumb', 'stupid' is [ableist language](http://deareverybody.hollandbloorview.ca/wp-content/uploads/2018/08/DearEverybodyTipsonAbleistLanguage2018-19.pdf) and its use should be avoided. This PR adds 'stupid' as a target to our inclusive language analysis, with the same inclusive alternatives as for 'dumb'.
* Adds 'stupid' as a non-inclusive phrase in the inclusive language analysis.
* None.
* Enable the Inclusive language analysis feature in Yoast SEO > General > Features
* Add the word 'stupid' to the post
* Confirm that the inclusive language analysis assessment gives the following …
> PC-981 Adds 'stupid' to non-inclusive phrases

- src/generators/breadcrumbs-generator.php
- src/integrations/third-party/woocommerce.php
- tests/unit/integrations/third-party/woocommerce-test.php
*
* Fixes a bug where a fatal error would be thrown when trying to create breadcrumbs from unindexable items.
* Add this filter in your functions.php:
```
add_filter( 'wpseo_indexable_excluded_post_types', function( $post_types ) { 
$post_types[] = 'page'; 
return $post_types;
} );
```
* Activate Yoast SEO (or if you had it active before, clean up indexables)
* Create a product and visit its frontend
_Without this PR:_
* You would get this Fatal Error:
```
PHP Fatal error:  Uncaught TypeError: Yoast\WP\SEO\Generators\Breadcrumbs_Generator::Yoast\WP\SEO\Generators\{closure}(): Argument #1 ($ancestor) must be of type Yoast\WP\SEO\Models\Indexable, …
```
> Fix Fatal Error when trying to create breadcrumbs with unindexable items

- packages/yoastseo/src/worker/AnalysisWebWorker.js
* We need to be able to override the shortlinks within the Inclusive language analysis from within Shopify SEO so we can determine from which platform the traffic to the website is coming from. This PR adds a method to do that.
* [yoastseo] Adds the possibility to change the links to the "learn more" URLs in the Inclusive language assessments.
* **Do NOT merge `trunk` into this branch**. This branch has been created based on the release branch, will be used in Shopify, and should not contain any unstable changes.
* **Do NOT remove this branch after merging**. This branch will be used in Shopify.
* For Shopify SEO, please follow [the steps described in this …
> Adds the possibility to add options to the Inclusive language assessor.

- packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
- packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
* Fixes an unreleased bug where _keyword density_, _keyphrase distribution_ and _word complexity_ (which are all assessments that use `packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js` for highlighting.) broke when there was an hyperlink on an item between square brackets. (`<a ...>[1]</a>`).
* The bug was introduced in this PR: https://github.com/Yoast/wordpress-seo/pull/19162
* In more detail: the bug was caused because, in classic editor, all items between square brackets are removed before the analysis as they are potential[ wordpress shortcodes](https://kinsta.com/blog/wordpress-shortcodes/).
* NOTE: There is still an issue: not all occurrences of `bread` are highlighted. This is due to a known issue regarding square brackets. This could not be solved …
> PC-1029-anchors-containing-square-brackets-in-content-lead-to-errors-with-classic-editor

- inc/class-upgrade.php
- src/integrations/watchers/indexable-author-watcher.php
- src/integrations/watchers/indexable-post-watcher.php
- src/integrations/watchers/indexable-term-watcher.php
* This is needed to be able to hook into the removal of an indexable.
* Adds a new `wpseo_indexable_deleted` action that triggers whenever an indexable is removed.
* Registers a run of the cleanup routine.
* No prominent words are being generated for terms. This PR adds the hook to the deletion of terms to keep it consistent  and when/if we add prominent words for terms it will just work.
* Same goes for authors, I added the code their since there is a removal of an indexable and I want that to be consistent.
* With this PR if you remove an indexable by hand the action is triggered and it is gone, also the cleanup cron is triggered in an upgrade routine, that removes all orphaned prominent words at the end of the cleanup. So …
> Remove prominent words when its indexable gets deleted

- packages/js/src/initializers/block-editor-integration.js
* The next release of Gutenberg block editor will introduce a functionality to let users remove any unknown formatting tag to a rich-text snippent. It does so by adding a new `core/unknown` default formatting style which would break the `Link` functionality in the visual editor, making impossible for users to insert links through the GUI. 
We want to avoid this by updating in advance our code.
* Avoids a future incompatibility with Gutenberg rich-formatting `core/unknown` formatting style.
*
* Build Gutenberg trunk as plugin and activate it
* Open a post in the block editor
* Without this PR:
* The `Link` functionality is missing when editing a text:
* If you try to …
> Block editor: DUPP-850 fix error with gutenberg trunk

- packages/js/src/components/contentAnalysis/SeoAnalysis.js
* We missed one upsell link where want to add a context variable to the url.
* Fixes a not released bug where the context get parameter was not added to two upsell links.
*
* Disable premium and build this RC/pr for free.
* Make sure every upsell link still works and ends up on: https://yoast.com/reasons-to-upgrade-keywords
* Open a post in the Gutenberg editor. 
* In the metabox open the `SEO analysis` tab and click on the `+ Add synonyms` button. In the modal make sure the `Yoast SEO Premium` link and the buy button both have a context parameter that is `block-metabox`.
* Do the same for the sidebar and make sure the context parameter is `block-sidebar`.
*Open a post in …
> Add location context to synonyms upsell.

- config/composer/actions.php
All the repos in the Yoast organisation contain a `<arg name="cache" value="./.cache/phpcs.cache"/>` directive in the PHPCS ruleset. This directive makes running PHPCS faster by caching the run results in a file and only scanning changed files when running PHPCS again.
However, when there is no cache available, running with the `cache` option enabled will make PHPCS _slower_ as the cache needs to be created and the file read/write actions slow PHPCS down.
In GH Actions, we are not caching the PHPCS `cache` file, which means that there is cache file available and running with `cache` will be slower.
By adding the `--no-cache` option, the `cache` directive in the ruleset is ignored, which should …
> GH Actions: improve performance of the CS step
