inc/class-wpseo-replace-vars.php
=> Clear retrieved replacement before going to next iteration

.travis.yml, readme.txt
* Move to WP 4.0 and 4.1
* Add PHP 5.6 (fixes #1881)
* Change order of builds to execute PHPLint build first
=> Several updates to Travis config

admin/pages/social.php, frontend/class-frontend.php
=> Added wpseo_replace_vars for metadescription [Finishes #83392882]

admin/class-opengraph-admin.php
=> Add isset check if value exists in $_POST [Finishes #83667902]

admin/class-admin.php, inc/class-wpseo-options.php, inc/wpseo-functions.php
This fixes #1859
Delete entire XML sitemap cache on plugin upgrade. Old method kept timeout transients. Original issue #1266
=> Delete entire XML sitemap cache when XML sitemaps settings are changed

.editorconfig
:) Unifying the coding style for different editors and IDEs using `.editorconfig` file.
=> Editorconfig for Coding Standard

inc/class-sitemaps.php
When wpseo_typecount_join and wpseo_typecount_where filters in build_post_type_map() function is used, the resulting root sitemap index and individual post type maps become incompatible as the number of posts included in the sitemap changes.
Changed build_root_map() function to use same query and filters used in build_post_type_map().
Note: build_post_type_map uses different join and where filters (wpseo_typecount_join and wpseo_posts_join / wpseo_typecount_where and wpseo_posts_where) for counting the number of posts and building the map. I think these filters should be same to ensure consistent results but I did not propose a change as I'm not sure if there may be other use cases utilizing different filter names.
=> build_root_map() / post count query updated for consistency.

inc/class-wpseo-utils.php, inc/wpseo-functions.php
Add the sitemap delete function again to WP SEO.
=> Add my sitemap function again [References #82491766]

frontend/class-googleplus.php, frontend/class-twitter.php
=> Forgot two files with defined check

readme.txt, wp-seo-main.php, wp-seo.php
=> release notes and version bump 1.8-beta

admin/TextStatistics.php, admin/class-bulk-editor-list-table.php, admin/class-bulk-title-editor-list-table.php, admin/class-config.php, admin/class-metabox.php, admin/class-opengraph-admin.php, admin/class-pointers.php, admin/class-sitemaps-admin.php, admin/class-snippet-preview.php, admin/class-taxonomy.php, admin/class-tracking.php, admin/class-yoast-plugin-conflict.php, admin/pages/import.php, frontend/class-breadcrumbs.php, frontend/class-frontend.php, inc/class-rewrite.php, inc/class-sitemaps.php, inc/class-wpseo-meta.php, inc/class-wpseo-options.php, inc/class-wpseo-replace-vars.php, inc/class-wpseo-utils.php, inc/wpseo-functions.php
For Travis tests. Mostly array keys rule (raised to error recently).
=> Cleaned up coding style

inc/class-wpseo-utils.php, tests/test-class-wpseo-utils.php
Some extra fixes in the remove nbsp from string function, and added a PHPUnit test to make sure we have a correct functioning function.
=> Final fix for keyword density 0% problem

admin/class-admin-init.php, frontend/class-frontend.php
=> Stories/am/show %%page%% in keywords [Delivers #82543810]

.travis.yml, composer.json, composer.lock
Fixes conflict with latest Composer.
Run `composer selfupdate` to get current version.
See #1890
=> Raised composer-php52 version

readme.txt, wp-seo-main.php, wp-seo.php
@jdevalk please review. I would like to release this tomorrow (tuesday) morning.
Release would contain everything that was in the beta plus a few extra small fixes.
Since we haven't had any negative feedback on the beta and haven't experienced any issues ourselves, I reckon the current state of things is ready to be shipped.
After release we can review al open PR's and start merging things in again.
=> release notes and version bump 1.7.2

readme.txt, wp-seo-main.php, wp-seo.php
=> release notes and version bump 1.7.3.1

.travis.yml
If I understand right PHP 5.2 should be working in Travis again. Opening PR to see if it really does. :)
Fixes #1967
=> Restored PHP 5.2 in Travis

admin/ajax.php
=> Fix to replace custom (cf_...) fields in the metabox [Delivers #83392878]

README.md, composer.json
=> Improved bug reporting section in readme

inc/class-wpseo-utils.php, tests/test-class-wpseo-utils.php
Merge with Pull https://github.com/Yoast/wpseo-video/pull/150
=> Add date time util check

frontend/class-frontend.php
=> Prevented overwrite of post global

inc/class-wpseo-options.php
=> Adding google plus url to the option class to get it saved [Delivers #89914378]

frontend/class-opengraph.php
=> Running replace_vars on the OG:description for frontpage [Delivers #89912490]

admin/views/tab-breadcrumbs.php
=> Open link in new window [Delivers #89922008]

admin/ajax.php, admin/class-bulk-editor-list-table.php, inc/wpseo-functions.php, readme.txt, wp-seo-main.php, wp-seo.php
@jdevalk please review. Can you confirm I haven't restricted the "orderable" columns too heavily?
=> Sanitize orderby and order params

admin/class-yoast-form.php
=> When there is a left label and a normal label show them both [Delivers #89920572]

admin/class-config.php
=> checkbox should be backwards compatible [Delivers #90100316]

admin/views/about.php
=> Textual suggestions for update page [Finishes #89920564] [Fixes #2084]

frontend/class-frontend.php, tests/framework/class-wpseo-unit-test-case.php
Normalized line endings for consistent behavior and unit tests passing on Windows.
=> Fixed tests on Windows

admin/class-bulk-editor-list-table.php, admin/class-config.php, admin/class-yoast-form.php
Several fixes in class bulk editor to use `filter_input`
=> Code style and documentation changes

frontend/class-frontend.php, phpunit.xml, tests/test-class-opengraph.php
=> Defaulted home meta description to blog description

inc/class-sitemaps.php
=> Hide post-types without any posts [Delivers #91080218]

readme.txt, wp-seo-main.php, wp-seo.php
Let's wait for @tacoverdo to give his final blessings from an acceptance testing point of view.
@jdevalk could you please review?
=> Release notes and version bump 2.0

frontend/class-breadcrumbs.php
@omarreiss @andizer please review. It's simple enough so we might want to ship with 2.0.1?
=> Fixes #1926

frontend/class-breadcrumbs.php
Reverts Yoast/wordpress-seo#2197
@jdevalk Revert merge and then merge back in later?
=> Revert "Fixes #1926"

admin/views/about.php, readme.txt
Minor change to release notes.
=> Give 2.0.1 its own tab on the about page.

admin/pages/social.php, inc/class-wpseo-options.php
Remove warning about verification, as that's no longer true.
=> Enable Twitter by default, fixes #2220

frontend/class-breadcrumbs.php
Fixes #1926
It was decided this fix should be in 2.1, not in 2.0.1
=> Reintroduce Breadcrumbs Fix

frontend/class-twitter.php, tests/framework/class-expose-wpseo-twitter.php, tests/test-class-twitter.php
=> Remove twitter:url as it's no longer used by Twitter.

frontend/class-breadcrumbs.php
=> Made post type determination in breadcrumb more robust

tests/test-class-opengraph.php
- updated for code style
- fixed multiple copies of lines in output
- fixed creating feaured images attachments
- prevented leftover files
- updated expected image URLs
=> Fixed opengraph tests

wp-seo-main.php
=> Implemented check for mu-plugins path when loading textdomain

frontend/class-frontend.php
@omarreiss @andizer please review.
=> Fixes #2286, duplicate output of JSON+LD

frontend/class-opengraph.php
=> Adding fallback for image_output

admin/class-admin-init.php
=> Changing the way we call redirect_to_about_page

readme.txt, wp-seo-main.php, wp-seo.php
=> release notes and version bump 2.1.1

admin/class-admin-init.php, composer.lock
Updating links to translate.yoast.com to https
Fixes #1932
=> Fixing issue #2294

inc/wpseo-non-ajax-functions.php
Fixes broken reference to `$wpseo_front` global, replacing it with a proper instance call.
=> Contains changes by @bhubbard, fixes #2311

composer.json, composer.lock
=> Switched to stable library versions

.travis.yml
As per http://docs.travis-ci.com/user/caching/
=> Added cache directives for Composer folders to Travis configuration

frontend/class-opengraph.php, tests/test-class-opengraph.php
Fixes #2354 
OpenGraph array documentation: http://ogp.me/#array
=> Display multiple article tag tags

inc/class-sitemaps.php
=> Made request match for sitemap to be more specific

inc/class-sitemaps.php
This will allow wp-cli to create partial sitemaps.
Closes #2332.
=> Add setter method for $n in class WPSEO_Sitemaps.

frontend/class-frontend.php
=> Adds filter for inclusion of RSS footer embed

frontend/class-json-ld.php
=> Added twitter profile to JSON LD output

inc/class-sitemaps.php
=> Fixed date conversion in sitemaps

admin/class-import.php
=> Fixed multisite settings import

frontend/class-frontend.php, frontend/class-opengraph.php, frontend/class-twitter.php, tests/test-class-opengraph.php, tests/test-class-twitter.php
- OpenGraph & Twitter Card tests for static front and posts pages
- proper title and description handling for static posts page (Social before SEO before generic)
Fixes #2421
=> Fixed posts pages titles and descriptions

inc/class-wpseo-replace-vars.php
=> Giving the arguments a number.

admin/pages/dashboard.php
=> Change the value of the GWT field and don't made this one translatable

admin/views/about.php, readme.txt, wp-seo-main.php, wp-seo.php
=> Changelog and version bump 2.2-RC

admin/class-social-facebook.php, admin/pages/social.php
Fixes #2453 by:
* Moving FB Insights to bottom of FB tab
* Adding inline documentation
* Adding links to newly created documentation on the knowledge base
* Several small interface changes
@omarreiss @tacoverdo please review.
=> Fixes #2453

inc/class-wpseo-options.php
=> Implemented accepting Twitter URL and extracting handle from it

admin/class-social-facebook.php, inc/class-wpseo-options.php
References #2460 
@jdevalk please review
=> Make sure Facebook admin ID gets fetched when the full meta tag was given

admin/pages/metas.php
Fixes #2449 
@tacoverdo please review
=> Fix grammar and make html more expressive

admin/pages/dashboard.php
=> Add link to about page to general tab of wpseo dashboard

admin/pages/metas.php
=> Using code tags to mark noindex, follow.

admin/pages/social.php
=> Moved the description under the title.

admin/ajax.php, admin/class-admin-init.php, admin/class-pointers.php
=> Make from ignore tour a page request instead of an AJAX request

readme.txt
=> Fix a typo in the word "typos"

inc/class-wpseo-options.php
=> Added validation logic for separator import

composer.lock
Closes #2478
Dev dependency only, no code changes to review.
=> Updated YoastCS with added PHPMD

admin/class-admin-user-profile.php, admin/views/user-profile.php
- fixed exclude from sitemap not saving
- fixed erased text fields not saving
- fixed conditional checked status
- updated deprecated method call
Fixes #2323
=> Fixed user profile save of WP SEO settings

frontend/class-json-ld.php, tests/test-class-wpseo-json-ld.php
Because of changes in [API docs](https://developers.google.com/structured-data/slsb-overview).
=> Change `search_term` to `search_term_string`

inc/class-upgrade.php, inc/class-wpseo-meta.php
=> Remove redirect functionality

admin/class-pointers.php, admin/views/tab-permalinks.php
Fixes #2474 
@tacoverdo please review
=> String improvements

admin/class-pointers.php
=> Fixed newsletter link in tour

admin/class-export.php, admin/google_search_console/views/gsc-display.php, admin/pages/metas.php
@tacoverdo Please review
This will also fixes #2649
=> Some text string replacements

admin/google_search_console/class-gsc-table.php, admin/google_search_console/views/gsc-create-redirect.php
Change how thickbox is called, so we can use the title of the thickbox. Also add extra error headings.
=> Improvements to redirect thickbox

admin/class-admin.php, admin/google_search_console/class-gsc-platform-tabs.php, admin/google_search_console/class-gsc.php, admin/google_search_console/views/gsc-display.php
=> rename 'Webmaster Tools' submenu item to 'Search Console'

admin/google_search_console/class-gsc-platform-tabs.php, admin/google_search_console/class-gsc.php, admin/google_search_console/views/gsc-display.php
=> Redirect to settings

admin/class-admin-init.php
=> Show a notice when GA by Yoast 5.4.3 is installed

admin/google_search_console/class-gsc-service.php
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/298
=> Show notice

inc/class-wpseo-meta.php
=> Prevent advanced metadata getting posted if not permitted

inc/class-upgrade.php
Simply push this specific bit of the upgrade routine to `wp`, leave the rest where it is.
=> Upgrade fix

readme.txt, wp-seo-main.php, wp-seo.php
=> Release notes and version bump 2.3.2

phpcs.xml, readme.txt, tests/test-class-opengraph.php, tests/test-class-wpseo-frontend.php
=> Plugin name change cleanup

admin/class-taxonomy.php
=> Fixed closing h3 tag

.travis.yml, js/wp-seo-admin-global.js, js/wp-seo-admin-gsc.js, package.json
`grunt:checki18n` is omitted for now until stephenharris/grunt-checktextdomain#8 is fixed.
@omarreiss Do you want me to look into `grunt-checktextdomain` to see if I can write a PR that fixes the issue there?
Fixes #2687
=> Adds grunt:checkjs to .travis.yml

frontend/class-frontend.php
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/301
=> Hide version in premium

admin/google_search_console/class-gsc-issue.php
=> Moving to format method, since 5.2 cannot do getTimeStamp.

frontend/class-opengraph.php, tests/test-class-opengraph.php
=> Implemented check for article OG type to output publisher

admin/class-metabox.php
=> Reformatted message code and encoded for possible spaces in URL

admin/class-yoast-dashboard-widget.php, admin/views/dashboard-widget.php, inc/class-wpseo-statistics.php
=> Show posts counts on dashboard per user level [Fixes #2727]

readme.txt, wp-seo-main.php, wp-seo.php
=> Version bump and change log 2.3.3

js/wp-seo-wordpress-scraper.js
Checks if the excerpt is available on page, prevents it from breaking the analyzer
Fixes #1505
=> Check if excerpt is available on page

frontend/class-opengraph.php
=> Implemented check for array data in featured image handling

admin/class-admin-init.php, admin/google_search_console/class-gsc.php
=> Moved init logic from direct run on load

admin/class-metabox.php
=> Fixed display of template-based meta descriptions in posts list

admin/class-admin-user-profile.php
=> Fixed nonce fail for alternate user updates

admin/class-metabox.php
=> Detect Premium and show in metabox [Fixes #2804]

inc/class-sitemaps.php
This fixes the use of %author% in post permalinks. Today a permalink such as `/%author%/%postname%/` will output `//%postname%/` in the sitemap xml...
=> sitemap: support use of %author% in permalinks

readme.txt, wp-seo-main.php, wp-seo.php
=> Changelog and version bump 2.3.5

inc/class-upgrade.php
=> Adding update method to version 2.4.

frontend/class-opengraph.php
=> Corrected Facebook admins to output as multiple Open Graph tags

admin/class-config.php, admin/class-yoast-form.php, admin/pages/licenses.php
=> Updated admin heading tags

admin/class-admin-init.php, wp-seo-main.php
=> Enabled admin metabox code to load in ajax inline save context

admin/class-admin.php
=> Restricted blog public warning to admins

.travis.yml, composer.json, composer.lock
- updated 5.2 autoloader version
- reverted explicit Composer version in Travis
- fixed up whitespace in composer.json (replaces #2884 props @austinpray)
=> Updated 5.2 autoloader dependency

admin/class-metabox.php
Fixes #2241 
Issue also suggest removing Focus Keyword under these conditions, but it seems separate enough feature?
=> Removed Page Analysis metabox tab, when disabled by filter

tests/framework/class-expose-wpseo-twitter.php
Travis was complaining, but not enough to fail the tests.
=> Made test method signature consistent with parent to fix strict notice

.travis.yml
It suddenly got chatty and annoying lately. Build status is available on pull requests anyway.
=> Disabled email notifications in Travis configuration

frontend/class-frontend.php
=> Getting the keywords for a static posts page.

admin/class-sitemaps-admin.php, inc/wpseo-functions.php
=> 2961: Adding option to disable pinging of search engines

admin/class-admin.php
=> Applied filtered user capability to main settings page for consistency

admin/ajax.php, admin/ajax/class-yoast-wptitle-ajax.php, admin/class-admin-init.php, admin/pages/metas.php, frontend/class-frontend.php
Deprecate the wp_title and show a notice to the site admin.
Fixes #3023
=> Deprecate wp title

frontend/class-frontend.php
=> Adds noodp to meta robots if the content is written. 

admin/class-admin.php, tests/test-class-wpseo-slug-stopwords.php
=> Fixed check for draft post status when removing stopwords from slug

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-content-fields.php
This is displayed in the tooltip
=> Add a description about the page analysis

admin/views/tool-file-editor.php
=> Hide htaccess title if needed

admin/class-recalculate-scores.php, admin/pages/dashboard.php, admin/pages/tools.php
=> Move the recalculate button

admin/class-admin-init.php, admin/class-yoast-notification-center.php, admin/class-yoast-notification.php
Fixes #3012 
Probably helps in unconfirmed cases like #2938
=> Deduplicated notifications

admin/onpage/class-onpage.php
=> Make activation hook public

tests/onpage/test-class-onpage-email-presenter.php
Because we shouldn't merge when tests are failing!
=> Fix failing onpage tests

admin/class-plugin-conflict.php
=> Check if plugin is a string.

admin/class-admin-init.php, admin/google_search_console/class-gsc.php, admin/onpage/class-onpage.php, inc/class-wpseo-utils.php
Add some checks to reduce the amount of notices being shown to the user.
Fixes #3190
=> Reduce the amount of notices

admin/metabox/class-metabox.php, tests/test-class-wpseo-metabox.php
=> Don't show metabox on attachment edit page

admin/class-admin-init.php
=> Return false when running ajax.

inc/wpseo-non-ajax-functions.php
Fixes https://github.com/Yoast/wordpress-seo/issues/3221
=> Fix edit link

admin/onpage/class-onpage-option.php, tests/onpage/test-class-onpage-option.php
=> Set the fetch limit to 15 seconds.

inc/class-wpseo-meta.php
=> Exclude current post correctly in keyword usage

admin/class-yoast-dashboard-widget.php, admin/onpage/class-onpage-option.php, admin/onpage/class-onpage.php, admin/views/dashboard-widget.php
=> Change the way for handling a request failure.

admin/views/dashboard-widget.php
=> Fix onpage shortlinks to be without dashes

readme.txt, wp-seo-main.php, wp-seo.php
=> change log and version bump 3.0.1 (OnPage.org integration issues)

admin/onpage/class-onpage-notifier.php, admin/onpage/class-onpage-option.php, admin/views/about.php, admin/views/dashboard-widget.php, tests/onpage/test-class-onpage-option.php, tests/onpage/test-class-onpage.php
Deprecated `WPSEO_OnPage_Option::is_indexable`. I am not sure what the return value should be though...
Also fixed the broken onpage tests.
=> Fix tests and deprecate is_indexable function

admin/class-admin.php, admin/pages/xml-sitemaps.php, frontend/class-frontend.php, inc/class-upgrade.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-option-xml.php, inc/sitemaps/class-author-sitemap-provider.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps-admin.php, inc/sitemaps/class-sitemaps-cache.php, inc/sitemaps/class-sitemaps-router.php, inc/sitemaps/class-sitemaps.php, inc/sitemaps/class-taxonomy-sitemap-provider.php, inc/wpseo-functions-deprecated.php, inc/wpseo-functions.php, tests/functions/test-wpseo-xml-sitemaps-base-url.php
=> Finished up sitemaps code organization pass

inc/class-wpseo-replace-vars.php
=> Strip tags from term description when called via ct_desc_ tag

admin/class-yoast-dashboard-widget.php, admin/onpage/class-onpage-option.php, admin/onpage/class-onpage.php, admin/pages/dashboard.php, admin/views/dashboard-widget.php, inc/options/class-wpseo-option-wpseo.php
=> Opt out onpage

frontend/class-frontend.php
=> Made canonical filter apply to all cases without override exclusion

admin/pages/xml-sitemaps.php, inc/sitemaps/class-author-sitemap-provider.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemap-image-parser.php, inc/sitemaps/class-sitemaps-cache.php, inc/sitemaps/class-sitemaps-renderer.php, inc/sitemaps/class-sitemaps-router.php, inc/sitemaps/class-sitemaps.php, inc/sitemaps/class-taxonomy-sitemap-provider.php
Inline documentation only, no code changes.
See #2787
=> Added inline documentation for all sitemap hooks

admin/class-recalculate-scores.php
Instead of custom query, this time using `’fields’ => ‘ids’` method for
a fix which @Rarst suggested.
=> Fix for "Out of Memory" issue - #3359

.travis.yml
=> Updated Travis matrix for WP 4.4 and PHP 7.0 stable

admin/pages/metas.php
Fixes #2923, wraps each title/meta section in a div.
=> Fixes #2923

admin/class-sitemaps-admin.php, admin/google_search_console/class-gsc-issue.php, inc/wpseo-functions.php
=> Adjusted method to produce localized date output for search console issues

frontend/class-opengraph.php
Data update only, no code changes.
See #2567
=> Updated list of locales supported by Facebook.

admin/metabox/class-metabox.php
Moved the if check of the attachment post type so it doesn't get executed too early.
Fixes https://github.com/Yoast/wordpress-seo/issues/3770
=> Fixed issue where JS is loaded on media page

admin/pages/metas.php
=> Remove duplicate options.

wp-seo-main.php
wp_installing() is now the correct way to check if WordPress is
installing.
See https://core.trac.wordpress.org/changeset/34828
=> Use wp_installing

admin/metabox/class-metabox.php
=> Don't make robots meta values translateable

admin/class-admin.php
This pull request fixes #3530 by checking for multisite and the current site state.
=> Prevent manipulation of remote posts's slugs

admin/pages/dashboard.php, admin/pages/metas.php
=> Moved the OnPage.org options

admin/class-import-external.php, admin/metabox/class-metabox.php, admin/pages/metas.php, frontend/class-frontend.php, inc/class-wpseo-meta.php, inc/options/class-wpseo-option-titles.php, tests/test-class-wpseo-frontend.php
Fixes #3942 
Removes noydir from admin pages, admin meta box, frontend generation and tests.
=> remove noydir completely

frontend/class-breadcrumbs.php
Fixes #3964, see that issue for more info.
=> Don't add PT archive link for posts

admin/pages/metas.php, admin/pages/xml-sitemaps.php
=> Hide internal taxonomies from XML sitemap page

admin/class-admin.php
The class we check for doesn't exist. This result in buy premium links in the plugin overview.
=> Change classname to verify it's existence for.

admin/pages/xml-sitemaps.php
=> Split explanation.

admin/metabox/class-metabox.php
=> Give post id to the get_sample_permalink to prevent errors.

frontend/class-frontend.php, tests/test-class-wpseo-frontend.php
=> added no index,nofollow for 404 pages + unit tests

admin/class-admin-init.php, admin/class-plugin-conflict.php, admin/onpage/class-onpage.php
=> Disable notices.

tests/sitemaps/test-class-author-sitemap-provider.php
=> Added tests that were removed in the merge from 3.1 to trunk

admin/pages/metas.php
=> Make "Subpages of archives" description clearer

admin/class-yoast-notification.php, tests/notifications/test-class-yoast-notification.php
Notifications are spiked with more options to facilitate new functionality needed for notifier implementation.
Provided tests to test new functionalities.
=> Prepare Notification for Notifiers

inc/sitemaps/class-author-sitemap-provider.php
Replaces #4139
Props @stodorovic
=> Made author query in sitemaps order consistently between pages

admin/class-admin-asset-manager.php, admin/google_search_console/class-gsc.php, css/xml-sitemap-xsl.php, tests/test-class-primary-term-admin.php
=> Fixed lingering script paths issues after sources moved

admin/views/tab-permalinks.php
=> restored permalink/?replytocom description

admin/onpage/class-onpage-request.php, admin/onpage/class-onpage.php, tests/onpage/test-class-onpage-request.php
This makes it possible for OnPage to more knowledgeable about saying if
the site is indexable or not.
Fixes #4180 
Fixes #4181
=> Send extra parameters to OnPage

frontend/class-breadcrumbs.php, frontend/class-frontend.php
Fixes #4030 
Reverts #73 (after internal discussion for code simplification and it being edge case with low SEO value).
=> Removed special handling of titles and breadcrumbs on 404 for date-related queries

admin/taxonomy/class-taxonomy-metabox.php, admin/taxonomy/class-taxonomy.php
Fixes #4167 
Might also take care of #3863
=> Moved handling of taxonomy assets to admin init to improve their sync with metabox

admin/pages/metas.php
Fixes #3353 
String update only, no code changes.
=> Clarified noodp setting description

admin/taxonomy/class-taxonomy-metabox.php
=> Taxonomy metabox title consistency

inc/sitemaps/class-sitemaps-cache.php
=> Added explicit string check to prevent strpos() error on object input

admin/class-social-admin.php, admin/taxonomy/class-taxonomy-social-fields.php
=> Updated Facebook image size and changed typography to use dimensions sign

wp-seo-main.php
This patch fixes activation/deactivation on a multinetwork setup of WordPress.
Fixes #3988
=> fix activation/deactivation on multi-network setup

inc/sitemaps/class-taxonomy-sitemap-provider.php
Fixes #4140 
Replaces #4139 
Props @stodorovic
=> Prevented generating sitemap links for private taxonomies

tests/admin/test-class-yoast-input-select.php
=> Normalized select input test to pass on Windows

inc/sitemaps/class-sitemaps-cache-validator.php, inc/sitemaps/class-sitemaps-cache.php, inc/sitemaps/class-sitemaps.php, tests/sitemaps/test-class-wpseo-sitemaps-cache-validator.php, tests/sitemaps/test-class-wpseo-sitemaps-cache.php
=> Split sitemap validator logic into a separate class

wp-seo.php
Load the files from the DEFINE instead of the `__FILE__` variable.
=> Allow activation of Premium when Free is active

inc/wpseo-functions.php
Fixes https://github.com/Yoast/wordpress-seo/issues/4038
=> Introduce functions to retrieve primary term information

admin/class-primary-term-admin.php
=> Remove filtering of non-category taxonomies for primary category

admin/class-admin.php, admin/pages/tutorial-videos.php, wp-seo.php
Fixes https://github.com/Yoast/wordpress-seo/issues/4245
=> Introduce the Tutorial Videos admin page

admin/google_search_console/views/gsc-create-redirect.php, admin/onpage/class-onpage.php, admin/views/about.php, admin/views/dashboard-widget.php, admin/views/tab-breadcrumbs.php
Change all link to `yoa.st` to be https.
=> SSL on yoa.st

inc/sitemaps/class-post-type-sitemap-provider.php
=> Made column names explicit to table in sitemap queries

frontend/class-frontend.php
=> Disabled canonical and added noindex for term archives with multiple terms

admin/ajax.php, admin/ajax/class-recalculate-scores-ajax.php, admin/class-export.php, admin/class-pointers.php, admin/class-social-facebook.php, admin/class-yoast-notification-center.php, admin/class-yoast-notification.php, frontend/class-json-ld.php, inc/class-wpseo-utils.php, tests/notifications/test-class-yoast-notification-center.php, tests/test-class-wpseo-json-ld.php
=> Deprecated json_encode wrapper, unnecessary for supported core versions

.travis.yml
=> Updated travis matrix for WP core 4.5 release

admin/class-admin-init.php
No code changes.
It seems for some reason URLs where set _back_ to http from https in #3740, but https seems to work fine?..
Fixes #4346
=> Updated glotpress URLs to https.

inc/sitemaps/class-sitemap-image-parser.php
=> Fixed parsing image HTML with quotes inside attributes

admin/class-admin-asset-manager.php
=> Removed faulty dependency check.

admin/class-admin.php, admin/class-pointers.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-content-fields.php, admin/views/tabs/metas/archives.php
I need to be able to change the URLs we point to, so changed these URLs to short links.
=> Link changes

.travis.yml, composer.json, composer.lock
Fixes autoload generation failing on latest Composer versions.
=> Updated composer-php52 dependency

admin/class-yoast-form.php
Fixes #4262 
Note: do we care about American / UK English differences? E.g. `optimize` vs. `optimise`.
=> Improve the sidebar banners alt attributes.

admin/pages/advanced.php, readme.txt, wp-seo-main.php, wp-seo.php
Options werent saved because of invalid opt_group in settings due to refactor.
Fixes #4430
=> Advanced tabs "permalinks" and "rss" were not saveable

inc/options/class-wpseo-option-xml.php
=> Implemented max 50k limit on sitemap page size for Google requirements.

css/xml-sitemap-xsl.php
=> Added time zone to displayed sitemap data

inc/class-wpseo-utils.php, inc/sitemaps/class-sitemap-timezone.php
=> Simplified DateTime related functions after audit

admin/class-meta-columns.php
=> Removed sort by SEO score in admin list tables

admin/class-option-tabs-formatter.php, admin/views/partial-settings-tab-video.php
=> Remove unnecessary aria-hidden.

inc/sitemaps/class-post-type-sitemap-provider.php
=> Fixed SQL to exclude attachments with unpublished parents

css/xml-sitemap-xsl.php
Was prep work for making stuff translatable in #4425 which didn't happen.
Doesn't quite fix anything, but makes working with output there less of a mess and more IDE-friendly.
=> Converted XSL from string to inline output

admin/class-meta-columns.php
=> Add missing label for the SEO filter select.

frontend/class-opengraph.php
=> Don't shortcircuit Frontend logic (inc. filters) Fixes #4298

inc/sitemaps/class-sitemaps-cache-validator.php
=> Disabled autoload of sitemap validator options

inc/sitemaps/class-post-type-sitemap-provider.php
=> Removed invalid sort by ID from posts sitemap query

inc/sitemaps/class-sitemap-image-parser.php, inc/sitemaps/class-taxonomy-sitemap-provider.php
=> Implemented sitemap images for attachments and terms

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-metabox.php
=> Put the social tab above the advanced one

composer.lock
Because of a bugfix in the i18n module.
=> Update the i18n module to latest release.

admin/metabox/class-metabox.php
=> Fix Metabox form table HTML.

admin/class-bulk-editor-list-table.php
Related https://github.com/Yoast/wordpress-seo/issues/4650
=> Bulk Editor: Use Yoast Notification constant for Notification Type

inc/sitemaps/class-sitemaps-cache.php, tests/sitemaps/test-class-wpseo-sitemaps-cache.php
=> Implemented delayed queued cache clear.

js/src/wp-seo-post-scraper.js, js/src/wp-seo-term-scraper.js, js/src/wp-seo-tinymce.js
=> TinyMCE improvements

admin/ajax/class-yoast-onpage-ajax.php, admin/class-social-facebook.php, admin/taxonomy/class-taxonomy-fields-presenter.php, admin/views/tabs/metas/general.php, changelog.txt, frontend/class-frontend.php, js/dist/wp-seo-post-scraper-324.js, js/dist/wp-seo-term-scraper-324.js, js/src/analysis/tabManager.js
Fixes #4693 
Spotted somE repeated "the the" and "in in". Haven't run `build:i18n` to not create conflicts. Can do that, just let me know :)
=> Fix some dittography.

admin/class-yoast-notification-center.php
Fixes https://github.com/Yoast/wordpress-seo/issues/4720
=> Revert code to keep it better readable.

inc/class-upgrade.php, inc/options/class-wpseo-options.php
Fixed upgrade version to 3.3 instead of 3.4
Fixes #4731
=> Removed deprecated function call on upgrade

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-content-fields.php, tests/taxonomy/test-class-taxonomy-content-fields.php
=> Change metabox labels

admin/views/tabs/tool/import-seo.php
This action is needed by premium to add an import option for redirection.
=> Add action for premium to hook into

admin/views/about.php
=> 3.3 about page

admin/class-admin-init.php, admin/class-plugin-availability.php, admin/class-plugin-compatibility.php, tests/admin/test-class-plugin-availability.php, tests/admin/test-class-plugin-compatibility.php, tests/admin/test-class-wpseo-plugin-availability-double.php
This will add notifications to the notification center and will set the severity based on whether or not a incompatible plugin is active.
Fixes #4817
=> Added checks for installed plugins and compatibility

admin/class-yoast-notification-center.php
We are doing a very hard check anyway.
This was breaking the dismissal of notifications for certain users.
=> Notification dismissal problem fix

frontend/class-primary-category.php
fix get_permalink() not using $post parameter to get primary category
Fixes #4328
=> fix get_permalink() not using $post parameter to get primary category

admin/google_search_console/views/gsc-display.php
Added the video on how to connect Google Search Console
Fixes #4866
=> Add video on how to connect to Google Search Console

admin/pages/dashboard.php
Fixes #4880 
Replaces https://github.com/Yoast/wordpress-seo/pull/4893
=> Add video to notification center

admin/class-admin-init.php
=> Avoid click here links.

css/src/admin-global.scss, css/src/adminbar.scss, css/src/alerts.scss, css/src/dashboard.scss, css/src/edit-page.scss, css/src/featured-image.scss, css/src/metabox-primary-category.scss, css/src/snippet.scss, css/src/taxonomy-meta.scss, css/src/toggle-switch.scss, css/src/wpseo-dismissible.scss, css/src/wpseo-rtl.scss, css/src/yst_plugin_tools.scss, css/src/yst_seo_score.scss, grunt/config/browserify.js, grunt/config/sass.js
This makes it easier later to delete all src files and makes it easier
to reuse code among different files.
=> Build all CSS files from SCSS files

inc/sitemaps/class-sitemaps-renderer.php, inc/sitemaps/class-sitemaps.php
=> Implemented conversion of sitemap to UTF-8 if necessary and possible

admin/views/dashboard-widget.php
First accessibility improvement for the Dashboard widget. See #4930 
Further improvements to discuss.
=> Fix dashboard widget heading level

admin/views/user-profile.php
=> Better heading hierarchy in the User Profile page

admin/views/tabs/advanced/breadcrumbs.php, admin/views/tabs/advanced/permalinks.php, admin/views/tabs/advanced/rss.php
=> Advanced settings better headings hierarchy.

admin/class-social-facebook.php, admin/views/tabs/social/accounts.php, admin/views/tabs/social/facebook.php, admin/views/tabs/social/google.php, admin/views/tabs/social/pinterest.php, admin/views/tabs/social/twitterbox.php
=> Social settings better headings hieararchy.

admin/views/tabs/dashboard/general.php, admin/views/tabs/dashboard/knowledge-graph.php, admin/views/tabs/dashboard/security.php, admin/views/tabs/dashboard/webmaster-tools.php
=> General settings better headings hierarchy.

admin/views/tabs/social/accounts.php
New string:
`To let search engines know which social profiles are associated to this site, enter them below:`
Please do feel free to further improve the wording.
Fixes #4964
=> Social tabs better intro text

admin/class-social-facebook.php, admin/views/tabs/sitemaps/exclude-post.php, admin/views/tabs/sitemaps/general.php, admin/views/tabs/sitemaps/post-types.php, admin/views/tabs/sitemaps/taxonomies.php, admin/views/tabs/sitemaps/user-sitemap.php, admin/views/tabs/social/accounts.php, admin/views/tabs/social/facebook.php, admin/views/tabs/social/google.php, admin/views/tabs/social/pinterest.php, admin/views/tabs/social/twitterbox.php
=> XML sitemap settings better headings

admin/class-pointers.php, admin/class-premium-popup.php, admin/class-social-facebook.php, admin/class-yoast-plugin-conflict.php, admin/google_search_console/views/gsc-display.php, admin/pages/licenses.php, admin/pages/network.php, admin/views/tabs/dashboard/general.php, admin/views/tabs/sitemaps/general.php, admin/views/tabs/tool/import-seo.php, admin/views/tabs/tool/wpseo-export.php, admin/views/tabs/tool/wpseo-import.php
=> Always use the buttons base CSS class.

admin/class-admin.php
=> Update FAQ link

admin/views/about.php
=> Add a title attribute on the release video iframe

admin/views/about.php
Fixes #5032.
Not sure about Yoast best practices for long lines. It's just a bit longer than the original one but definitely not so readable. Suggestions welcome :)
=> Improve the credits screen contributors links

admin/ajax.php, grunt/config/browserify.js, js/src/wp-seo-post-scraper.js, tests/formatter/test-metabox-formatter.php
=> Restores the focus keyword on pageload - release

admin/class-admin-asset-manager.php, admin/class-config.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, inc/class-wpseo-utils.php, tests/test-class-wpseo-utils.php
=> Don't throw a 404 when there is an empty locale

admin/class-meta-columns.php, admin/taxonomy/class-taxonomy-columns.php, inc/options/class-wpseo-taxonomy-meta.php
=> Add readability score to term overview

admin/views/about.php
=> Fixed minor typo in about page

admin/views/tabs/advanced/permalinks.php
=> Simplified wording of stop words setting.

inc/wpseo-non-ajax-functions.php
This makes it more clear what the number in the admin bar is about.
Fixes #4769
=> Add notification menu item to admin bar

changelog.txt, readme.txt
=> Changelog for 3.4

admin/class-yoast-dashboard-widget.php
=> Hide posts overview

admin/taxonomy/class-taxonomy-columns.php
=> Fixed the check to display the readability score in taxonomy overviews

js/src/wp-seo-term-scraper.js
Requires https://github.com/Yoast/YoastSEO.js/pull/818
Fixes #5218
=> Added a check to disable markers on term pages

admin/class-admin-init.php, admin/class-admin.php, admin/class-primary-term-admin.php, admin/metabox/class-metabox.php, inc/wpseo-non-ajax-functions.php
This makes it easier to see what is happening and to change it if
necessary for some reason.
=> Abstract functions to detect post overview/edit

admin/metabox/class-metabox.php
=> Added handling for invalid return of tax names from core for attachments

.travis.yml
This makes the .travis.yml more clear.
=> Move installing dependencies to install step

Gruntfile.js, grunt/config/aliases.yaml, js/src/analysis/genericTab.js, js/src/analysis/getDescriptionPlaceholder.js, js/src/analysis/getI18n.js, js/src/analysis/getIndicatorForScore.js, js/src/analysis/getL10nObject.js, js/src/analysis/getTitlePlaceholder.js, js/src/analysis/getTranslations.js, js/src/analysis/isContentAnalysisActive.js, js/src/analysis/isKeywordAnalysisActive.js, js/src/analysis/keywordTab.js, js/src/analysis/snippetPreview.js, js/src/analysis/tabManager.js, js/src/analysis/usedKeywords.js, js/src/assessors/taxonomyAssessor.js, js/src/decorator/tinyMCE.js, js/src/ui/adminBar.js, js/src/ui/publishBox.js, js/src/ui/trafficLight.js, js/src/values/replaceVar.js, js/src/wp-seo-admin-global.js, js/src/wp-seo-bulk-editor.js, js/src/wp-seo-post-scraper.js, js/src/wp-seo-recalculate.js, js/src/wp-seo-shortcode-plugin.js, js/src/wp-seo-tinymce.js
Also remove JSHint & JSCS in favor of ESLint
=> Include and fix child JavaScript files

grunt/config/aliases.yaml, grunt/config/browserify.js
This enables us to start integrating React components
=> Enable ES6 for all JavaScript

.travis.yml
Updated Travis matrix for WP 4.6 release
* recalculated matrix in `.travis.yml`.
* observe Travis having dedicated entries for WP 4.6 tests.
=> Updated Travis matrix for WP 4.6 release

admin/class-admin.php, inc/wpseo-non-ajax-functions.php
=> Add missing text domain to the notifications count bubbles.

admin/class-yoast-form.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-fields-presenter.php
=> Make translatable and properly escape all the Upload Image buttons.

inc/class-wpseo-meta.php
=> Prevented keyword usage meta query for invalid keyword

inc/wpseo-non-ajax-functions.php
=> Improve the admin bar top level menu item.

frontend/class-frontend.php
Fixes #2094 (or at least more of).
=> Added check for invalid search query from page permalink

frontend/class-opengraph.php, frontend/class-twitter.php, tests/test-class-opengraph.php, tests/test-class-twitter.php
=> Implemented posts page images handling in Open Graph and Twitter Cards

admin/taxonomy/class-taxonomy-fields-presenter.php, tests/taxonomy/test-class-taxonomy-presenter.php
=> Fixed missing descriptions in taxonomy settings fields

frontend/class-frontend.php
=> Added custom canonical handling for posts page

css/xml-sitemap-xsl.php, inc/sitemaps/class-author-sitemap-provider.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps-renderer.php, inc/sitemaps/class-sitemaps.php, inc/sitemaps/class-taxonomy-sitemap-provider.php
=> Deprecated change frequency and priority in sitemaps

inc/wpseo-non-ajax-functions.php
=> Fixed up analyze entries in toolbar

frontend/class-twitter.php
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/718
=> Twitter replace vars

changelog.txt, readme.txt
=> Changelog 3.5

js/src/analysis/PostDataCollector.js, js/src/analysis/TermDataCollector.js, js/src/analysis/genericTab.js, js/src/analysis/getDescriptionPlaceholder.js, js/src/analysis/getI18n.js, js/src/analysis/getTitlePlaceholder.js, js/src/analysis/getTranslations.js, js/src/analysis/isKeywordAnalysisActive.js, js/src/analysis/keywordTab.js, js/src/analysis/snippetPreview.js, js/src/analysis/tabManager.js, js/src/analysis/usedKeywords.js, js/src/decorator/tinyMCE.js, js/src/kb-search/wp-seo-kb-search.js, js/src/ui/adminBar.js, js/src/ui/publishBox.js, js/src/ui/trafficLight.js, js/src/values/replaceVar.js, js/src/wp-seo-admin-global.js, js/src/wp-seo-featured-image.js, js/src/wp-seo-metabox-category.js, js/src/wp-seo-post-scraper.js, js/src/wp-seo-recalculate.js, js/src/wp-seo-replacevar-plugin.js, js/src/wp-seo-shortcode-plugin.js, js/src/wp-seo-term-scraper.js, js/src/wp-seo-tinymce.js
There were a lot of codestyle issues for the JS. This pull request is solving some of them.
=> Fix js codestyle

admin/config-ui/class-configuration-page.php, admin/config-ui/components/class-component-mailchimp-signup.php, admin/config-ui/fields/class-field-mailchimp-signup.php, admin/views/about.php, admin/views/tabs/dashboard/general.php, js/src/components/MailchimpSignup.js
Added a button to start the wizard.
* Go to the dashboard page, open the general tab and see I the button appears.
Fixes #5517
=> Adds a button for opening the onboarding page.

composer.lock
Updated code coverage dependencies
* updated dependencies used for code coverage reporting
* `composer.lock` change only, as long as CI runs everything is good
=> Updated code coverage dependencies

admin/class-plugin-availability.php
see issue #5492 
Accedentally merged that one into trunk, this one should've gone into the release branch.
see issue #5492 
see issue #5492 
see issue #5492 
*
Fixes #5486
=> Refactored plugin status check for performance.

admin/class-admin.php, admin/config-ui/class-configuration-page.php
Removes the notification when the wizard has been completed.
=> Removes the notice after installation

grunt/config/eslint.js, js/src/components/ConnectGoogleSearchConsole.js, js/src/components/MediaUpload.js
Fixed the ESLint warnings for the GSC and MediaUpload component.
=> Reduce the amount of warnings.

admin/config-ui/fields/class-field-success-message.php
=> Onboarding wizard: add title attribute on the video iframe

admin/config-ui/class-configuration-options-adapter.php
* n/a
* Exceptions shouldn't be translatable as they aren't user facing.
=> Don't translate thrown exception

js/src/components/MailchimpSignup.js
=> Mailchimp Signup fix doubled label and other improvements.

changelog.txt, readme.txt
=> Adds changelog for 3.6

admin/views/tabs/tool/wpseo-import.php
Fixes #5746 
See https://github.com/Yoast/wordpress-seo-premium/pull/781
=> Tools Import page: add missing label

js/src/wp-seo-admin.js
=> Facebook add admin popup: properly insert the notices.

admin/metabox/class-metabox-form-tab.php, admin/metabox/class-metabox.php, css/src/metabox.scss
Fixes #5727 
Note: the additional tabs in the Premium version need to be addressed in a separate issue.
=> Meta box single tabs shouldn't be links

admin/class-bulk-editor-list-table.php
=> Bulk editor table: Use a fallback title for posts with no title

admin/class-bulk-editor-list-table.php, admin/class-premium-popup.php, admin/class-recalculate-scores.php, admin/class-social-facebook.php, admin/google_search_console/views/gsc-create-redirect.php, admin/google_search_console/views/gsc-display.php, admin/metabox/class-metabox.php, admin/views/tabs/social/facebook.php, admin/views/tool-file-editor.php, admin/views/tool-import-export.php, css/src/admin-global.scss, css/src/yst_plugin_tools.scss
Fixes #5760 
See #5629
Some inline styles come from modules/components, probably we should have a look at those too.
=> Remove a bunch of inline styles.

admin/views/tabs/dashboard/features.php, inc/options/class-wpseo-option-wpseo.php
Add the necessary filters to allow adding feature toggles.
* Feature toggles need to be a general option, so that option needs to be filterable to be able to add new ones dynamically.
* The actual output should be filterable as well.
* Use both filters to add an extra feature toggle.
=> Add the necessary filters to allow adding feature toggles

admin/views/partial-alerts-warnings.php
On the dashboard the improvements heading is changed in to `notifications`. And there is no explaining paragraph.
=> Change improvements header

readme.txt
Should be `3.7.0` instead of `3.6.0`.
=> Fixes version number in changelog

admin/class-admin.php, admin/class-product-upsell-notice.php, inc/class-upgrade.php, inc/class-wpseo-features.php, inc/class-wpseo-installation.php, inc/options/class-wpseo-option-wpseo.php
Adds a notice to inform the user about premium and the configuration service.
Fixes #5815
=> Inform about yoast products

admin/formatter/class-metabox-formatter.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-metabox.php
Fixes #5744 
Pending decisions and feedback on the Premium PR https://github.com/Yoast/wordpress-seo-premium/pull/778
=> Change the remove keyword links in buttons

admin/class-social-admin.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-metabox.php
=> Metabox social tabs should not be links when there's only one.

admin/views/tabs/sitemaps/general.php
Fixes #5981 
Removes the `button` CSS class
Add translators comment
Better indentation
=> Make the XML Sitemap link look like a link

admin/class-product-upsell-notice.php
* Concat the language string to prevent tabs in the string.
=> Fix the tabs in the string.

changelog.txt, readme.txt
=> Adds changelog for 3.8

js/src/wp-seo-tinymce.js
This is a duplicate of https://github.com/Yoast/wordpress-seo/pull/6049 so that it can be merged in the 3.9 release.
=> Adds check for tinyMCE required iframe

composer.json, composer.lock
* When making the changelog, include all changelog entries from the license manager if they are relevant to users.
* See the changelog of the license manager.
=> Update the license manager to 1.4

admin/banner/class-admin-banner-sidebar.php, admin/class-yoast-form.php
Fixed banner wording
* string only change
Fixes #6136
Fixes #6137
=> Fixed banner wording

admin/banner/class-admin-banner-sidebar.php, admin/class-yoast-form.php
=> Add missing textdomains

changelog.txt, readme.txt
=> Adds changelog 3.9

admin/taxonomy/class-taxonomy-content-fields.php, admin/taxonomy/class-taxonomy-settings-fields.php
=> Merge and standardize a few translatable strings.

admin/views/about.php
Since Rens isn't working for Yoast anymore, he shouldn't be one the credits page.
=> Updated the credits page

admin/pages/dashboard.php, admin/views/tabs/dashboard/site-analysis.php
n/a
* This is completely transparent in that it adds nothing without additional code.
* See the PR on premium.
=> Add hooks to add a site wide analysis tab

admin/banner/class-admin-banner-sidebar.php
With feedback from @Annelieke and Marieke
=> Improve banner copy

readme.txt
Improves punctuation and sentence structure in Read Me. 
This is a sting-only change.
=> Improve punctuation and sentence structure in Read Me

admin/class-help-center.php
Fixes #6190 
Depends on https://github.com/Yoast/wordpress-seo/pull/6215
=> Use WPSEO_Utils::get_user_locale to set the wpseoAdminL10n locale

admin/google_search_console/class-gsc-table.php
=> Add labels to the search console checkboxes.

admin/banner/class-admin-banner-sidebar.php
=> Removes review banner from plugin admin

tests/admin/test-class-option-tab.php, tests/config-ui/test-class-configuration-service.php
Added tests for the option tab. This can be tested by looking if the tests are passing in travis.
=> Add test for option tab

inc/class-wpseo-utils.php, inc/options/class-wpseo-options.php
Added a function that allows retrieving an option only when it's been autoloader.
* Need this in a Video SEO patch but think it's worthwhile having available here.
=> Add autoloaded option function

admin/class-admin-init.php
=> I18n: Fix indentation of translators comment.

admin/views/tool-bulk-editor.php
_N/A_
Make a text string translatable.
_N/A_
=> I18n: Add missing I18n function call to make a string translatable

admin/metabox/class-metabox-analysis-seo.php, admin/metabox/class-metabox.php, admin/views/tabs/dashboard/site-analysis.php
=> Fix various minor code style issues.

admin/config-ui/components/interface-component.php, inc/sitemaps/interface-sitemap-provider.php
_N/A_
* Add two missing class (interface) doc blocks
_N/A_
=> Add missing interface documentation blocks

admin/banner/class-admin-banner-sidebar.php, admin/class-product-upsell-notice.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-fields-presenter.php, inc/sitemaps/class-sitemap-image-parser.php, inc/wpseo-non-ajax-functions.php
_N/A_
* No functional changes. Compliance with the `Squiz.Strings.ConcatenationSpacing` sniff as included in WPCS 0.10.0.
_N/A_
=> Fix concatenation spacing issues.

admin/class-admin-init.php, admin/class-help-center.php, admin/google_search_console/class-gsc.php, admin/import/class-import-aioseo-hooks.php, admin/import/class-import-wpseo-hooks.php, admin/views/about.php
_N/A_
* No functional changes. Compliance with the WP I18n guidelines.
_N/A_
=> I18n: Add some missing /* translators: */ comments.

changelog.txt, readme.txt
=> Adds changelog 4.1

admin/taxonomy/class-taxonomy-settings-fields.php, tests/admin/test-class-plugin-compatibility.php, tests/taxonomy/test-class-taxonomy-fields.php, tests/taxonomy/test-class-taxonomy-settings-fields.php
=> Add some unit tests

changelog.txt, readme.txt
=> Add changelog

frontend/class-opengraph.php
* Added a filter to add images to the opengraph
* Check if the filter works.
Is implemented for https://github.com/Yoast/wpseo-woocommerce/issues/71
=> Add filter to extend og images

inc/class-wpseo-replace-vars.php
This changes 'more unique' to 'unique'.  This is a string only change. 
Fixes #6578
=> Fix string

admin/google_search_console/views/gsc-display.php
- Added link to our knowledge base article about connecting your website to Google Search Console.
Fixes #6090
=> Added link to KB article about connecting your website to Google Search Console

admin/metabox/class-metabox.php
Use same strings for translation as in other files.
=> Equalize strings

admin/views/dashboard-widget.php
=> span closing tag is wrong

changelog.txt, readme.txt
Adds changelog 4.3
BEFORE merging, please change the base branch to the current release branch!
=> Adds changelog 4.3

changelog.txt, readme.txt
=> Added changelog for 4.4

admin/class-help-center.php, admin/class-premium-popup.php, admin/class-social-facebook.php, admin/pages/licenses.php
* Changes the links into shortlinks for the extensions page. 
*open the extensions page. The links should be shortcodes (like documented in the issue). 
Fixes #6673
*When merging, please update the changelog
=> Add shortlinks.

admin/class-admin.php
Changed confusing comments for WPSEO_Admin::temporarily_enable_page
Fixes #6748
props @vittala
=> Changes comments for WPSEO_Admin::temporarily_enable_page

admin/ajax.php
=> CS compliance: variable names should be lowercase [1]

admin/metabox/class-metabox-add-keyword-tab.php
Or was this intended to be a localizable url ? or a dynamic url ?
=> CS compliance: remove unnecessary concatenation

admin/ajax.php
=> CS compliance: variable names should be lowercase [2]

admin/class-admin.php
=> CS compliance: variable names should be lowercase [3]

admin/class-plugin-availability.php
=> CS compliance: variable names should be lowercase [4]

admin/class-primary-term-admin.php
=> CS compliance: variable names should be lowercase [5]

admin/class-primary-term-admin.php
=> CS compliance: variable names should be lowercase [6]

admin/class-primary-term-admin.php
=> CS compliance: variable names should be lowercase [7]

admin/class-primary-term-admin.php
=> CS compliance: variable names should be lowercase [8]

admin/config-ui/fields/class-field-choice-post-type.php
=> CS compliance: variable names should be lowercase [11]

admin/google_search_console/views/gsc-display.php
=> CS compliance: variable names should be lowercase [12]

admin/metabox/class-metabox.php
=> CS compliance: variable names should be lowercase [13]

admin/metabox/class-metabox.php
=> CS compliance: variable names should be lowercase [14]

admin/pages/licenses.php
=> CS compliance: variable names should be lowercase [15]

admin/banner/class-admin-banner-sidebar.php, admin/banner/class-admin-banner-spot.php, admin/class-product-upsell-notice.php, admin/metabox/class-metabox-add-keyword-tab.php, admin/views/tabs/advanced/breadcrumbs.php, inc/class-wpseo-advanced-settings.php
=> CS compliance: few minor whitespace fixes.

admin/metabox/class-metabox-add-keyword-tab.php
=> I18n: Fix text strings missing text domain

admin/class-bulk-editor-list-table.php
=> Cleanup: no need for variable assignment

admin/banner/class-admin-banner-sidebar.php
=> CS compliance: Fix comment style for commented out code.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md
Created together with @benvaassen and @thulshof.
This is a rewrite of the contribution guidelines and a new setup for the issues to provide better feedback to our users. When this is approved and proven to be successful, we can also implement this on the other repositories.
@atimmer and @omarreiss, can one of you take a look at this?
=> Rewrite of the contributing.md and issue template.md for GitHub

admin/links/class-link-columns.php, admin/links/class-link-notifier.php, admin/links/class-link-reindex-dashboard.php
Added the copy given in #7294
Fixes #7294
=> Change copy link index

admin/class-admin.php
In Yoast SEO 5.0 we want to show the PHP version message to users of PHP 5.3
=> Show Whip on PHP 5.3

admin/class-admin.php, admin/class-meta-storage.php, admin/links/class-link-compatibility-notifier.php, inc/interface-wpseo-wordpress-integration.php
=> Abstract registering hooks to a single foreach

admin/class-meta-storage.php, admin/links/class-link-column-count.php, admin/links/class-link-columns.php, admin/links/class-link-content-processor.php, tests/admin/links/test-class-link-columns-count.php
Counting how much external links you have isn't that useful. It is
better to count how much internal links you have.
=> Change link count to internal link count

admin/links/class-link-reindex-post-service.php, admin/links/class-link-type-classifier.php, tests/admin/links/test-class-link-type-classifier.php
* Compare the host to match protocols https and http
* Mark every url with an protocol different like http or https as an external link
* Check for path to match domain with an subdirectory. If the subdirectory differs from the one in the base url it is an external one.
=> Recognise all schemes

admin/class-admin.php, admin/class-yoast-columns.php
We only have to change the shortlinks to the relevant ones.
=> Add help center content

admin/class-premium-popup.php, inc/class-wpseo-shortlinker.php
Updates the link.
Also, fixes a double space in `class  WPSEO_Shortlinker`. Just because I was searching through the codebase for `class WPSEO_Shortlinker` and got no results :)
Fixes #6918
=> Update "Add keyword popup" go premium link.

admin/views/partial-alerts-errors.php, admin/views/partial-alerts-template.php, admin/views/partial-alerts-warnings.php, css/src/alerts.scss
* Change the padding of the notice container on the dashboard
* Add some contextual copy above the muted notices.
* Do `grunt build:css`
* See the changes matches the screenshot in the issue #7359 
Fixes #7359
=> Apply seo dashboard tweaks

admin/views/tabs/metas/post-types.php, admin/views/tabs/metas/taxonomies.php
* Show the posttype name and the taxonomy name for a better identification in the titles and metas configuration.
* Go to the titles and metas configuration and see it being visibile on the post types and taxonomies tab.
Fixes #6968
=> Show slugs

admin/links/class-link-notifier.php, inc/class-upgrade.php
* Fixed code formatting issues
Fixes #7484
=> Fixed code formatting issues

admin/class-collector.php, admin/class-remote-request.php, admin/interface-collection.php, admin/tracking/class-tracking-default-data.php, admin/tracking/class-tracking-plugin-data.php, admin/tracking/class-tracking-server-data.php, admin/tracking/class-tracking-theme-data.php, admin/tracking/class-tracking.php, admin/tracking/interface-tracking-collection.php
I've added some code to generate tracking data.
* Add this code the WPSEO Admin class.
```php
if ( filter_input( INPUT_GET, 'action' ) === 'collect' ) {
$collector->add_collection( new WPSEO_Tracking_Default_Data() );
$collector->add_collection( new WPSEO_Tracking_Server_Data() );
$collector->add_collection( new WPSEO_Tracking_Theme_Data() );
$collector->add_collection( new WPSEO_Tracking_Plugin_Data() );
echo $collector->get_as_json();
}
```
* Go to an admin page with `?action=collect` in the URL. There is JSON visibile.
* You can can do `print_r( $collector->collect() ); ` to have a 'nicer' print of it.
Fixes #7546
=> Implement tracking data collector

admin/pages/licenses.php
Fixes https://github.com/Yoast/wordpress-seo/issues/7562
Fixes https://github.com/Yoast/wordpress-seo/issues/7134
=> Change from get to show

admin/banner/class-admin-banner-sidebar.php, admin/config-ui/components/class-component-configuration-choices.php, admin/config-ui/components/class-component-suggestions.php, admin/config-ui/fields/class-field-success-message.php, admin/google_search_console/views/gsc-display.php, admin/metabox/class-metabox-add-keyword-tab.php, admin/metabox/class-metabox.php, admin/pages/advanced.php, admin/pages/dashboard.php, admin/pages/licenses.php, admin/pages/metas.php, admin/pages/social.php, admin/pages/xml-sitemaps.php, admin/taxonomy/class-taxonomy-metabox.php, admin/views/about.php, admin/views/dashboard-widget.php, admin/views/partial-help-center-video.php, admin/views/tool-bulk-editor.php, admin/views/tool-file-editor.php, admin/views/tool-import-export.php
Removes the keyword research training banner as we don't currently sell it.
=> Remove keyword research banner

admin/tracking/class-tracking-server-data.php
Added `xml` and `pcre` to the extensions.
=> Added two extensions

admin/google_search_console/class-gsc-table.php, admin/views/tool-bulk-editor.php, grunt/config/eslint.js, js/src/components/ConnectGoogleSearchConsole.js, js/src/wp-seo-admin-global.js, js/src/wp-seo-admin-gsc.js, js/src/wp-seo-admin-media.js, js/src/wp-seo-admin.js, js/src/wp-seo-bulk-editor.js, js/src/wp-seo-metabox.js, js/src/wp-seo-post-scraper.js, js/src/wp-seo-recalculate.js, js/src/wp-seo-replacevar-plugin.js, js/src/wp-seo-shortcode-plugin.js, js/src/wp-seo-tinymce.js
I've fixed a lot of `camelcase` issues in the JS-files to please eslint. 
Just build the js files `grunt build:js` and go to every Yoast SEO window to make sure nothing is broken.
=> Eslint fix camelcase

admin/class-yoast-form.php
* Add missing I18n function call to make a string translatable
*
*
Fixes #
=> Add missing I18n function

readme.txt
It changed, see https://meta.trac.wordpress.org/ticket/2952#comment:5
=> Change keyword for requiring PHP version

admin/class-admin.php
* Added the public access modifier for method that don't have an access modifier.
=> Added some access modifiers

admin/views/about.php
* Fixes wrong urls on the credits page
* See issue #7487 for the steps to reproduce
Fixes #7487
=> Fix incorrect urls on credits page

inc/wpseo-non-ajax-functions.php
* Add configuration wizard to admin bar menu
* Checkout this branch and check if the link is in the adminbar
Fixes #7748
=> Add configuration wizard to the admin bar menu

admin/tracking/class-tracking-default-data.php
Removes email address from tracking.
=> Remove email address from tracking

admin/config-ui/fields/class-field-site-name.php
=> CS compliance: fix funky function layout

admin/config-ui/fields/class-field-success-message.php
* Make title in WPSEO_Config_Field_Success_Message translatable.
*
*
Fixes #
=> I18N: Make title translatable

inc/wpseo-non-ajax-functions.php
* Replace adwords url with https version
Fixes  #7602
=> Use HTTPS for adwords url

admin/class-help-center.php
*  Correct *plug-in* spelling and merge with similar string
* Avoid duplicate strings and improve i18n consistency
Fixes #7865
=> Change string to merge with similar.

tests/test-class-wpseo-frontend.php
=> CS compliance: minor code restructuring (1)

admin/filters/class-abstract-post-filter.php, admin/filters/class-cornerstone-filter.php
=> Check if post type object is null

tests/framework/index.php, tests/index.php
_N/A_
The tests are not shipped with the plugin - as per the `.gitattributes` file -, so no need for empty `index.php` files.
_N/A_
=> CS/cleanup: empty index files are not needed for directories not shipped

admin/class-admin-asset-manager.php, admin/class-bulk-description-editor-list-table.php, admin/class-bulk-title-editor-list-table.php, frontend/class-frontend.php, frontend/class-opengraph.php, frontend/class-twitter.php, inc/options/class-wpseo-taxonomy-meta.php, inc/sitemaps/class-author-sitemap-provider.php, inc/sitemaps/class-sitemaps.php, tests/test-class-opengraph.php, tests/test-class-rewrite.php, tests/test-class-wpseo-breadcrumbs.php, tests/test-class-wpseo-frontend.php, tests/test-class-wpseo-meta.php, tests/test-wpseo-functions.php
_N/A_
Whether these comments should actually be in the code or be turned into issues and tracked that way is another matter, but at the very least they should be made more easy to pick up on with automated tooling which is what using the proper doc tags allows for.
_N/A_
=> Documentation: fix non-tagged @todo comment(s)

inc/options/class-wpseo-option-wpseo.php
=> Documentation: use PSR-5 compliant styling for @internal tags

admin/views/tool-bulk-editor.php
Fixes the codestyle in the `tool-bulk-editor.php`
=> Two small CS fixes.

admin/ajax.php, admin/class-bulk-editor-list-table.php, admin/class-cornerstone-field.php, admin/class-export.php, admin/class-import.php, admin/class-license-page-manager.php, admin/class-premium-upsell-admin-block.php, admin/class-social-admin.php, admin/class-social-facebook.php, admin/class-yoast-form.php, admin/config-ui/fields/class-field-google-search-console-intro.php, admin/metabox/class-metabox.php, admin/pages/network.php, admin/views/about.php, admin/views/tabs/dashboard/features.php, admin/views/tabs/metas/general.php, admin/views/tabs/sitemaps/general.php, frontend/class-frontend.php, inc/class-wpseo-replace-vars.php, inc/options/class-wpseo-option-internallinks.php, inc/options/class-wpseo-option-ms.php, inc/options/class-wpseo-option-social.php, inc/options/class-wpseo-option-titles.php, inc/options/class-wpseo-option-xml.php, inc/options/class-wpseo-option.php, tests/onpage/test-class-onpage.php
_N/A_
* WPCS I18N compliance.
This PR addresses a number of issues surrounding internationalization and localization.
* Use of the correct text domain for WPSEO and use `default` when a WP core translation is the intention.
* Make sure that all PO generators can pick up on the translators comments.
* Make sure all gettext calls with placeholders have a translators comment.
**Review note**: the PR will be easiest to review by looking at the individual commits.
_N/A_
=> I18n: various improvements

admin/config-ui/class-configuration-page.php
=> Capital P Dangit!

admin/ajax.php, admin/class-license-page-manager.php, admin/class-meta-columns.php, admin/class-plugin-availability.php, admin/class-product-upsell-notice.php, admin/class-remote-request.php, admin/config-ui/fields/class-field-environment.php, admin/google_search_console/class-gsc-ajax.php, admin/google_search_console/class-gsc-category-filters.php, admin/google_search_console/views/gsc-display.php, admin/menu/class-admin-menu.php, admin/pages/tools.php, admin/tracking/class-tracking-server-data.php, admin/views/tabs/metas/general.php, frontend/class-opengraph.php, frontend/class-primary-category.php, inc/wpseo-non-ajax-functions.php, tests/admin/links/test-class-link-factory.php, tests/formatter/test-metabox-formatter.php, tests/formatter/test-post-metabox-formatter.php, tests/onpage/test-class-onpage.php, tests/taxonomy/test-class-taxonomy-fields.php, tests/test-class-rewrite.php
See #7987, things which appear to have slipped in again in the mean time.
When viewing the changes, adding ?w=1 to the URL shows the changes while ignoring whitespace differences making it easy to verify that the commits only contain whitespace changes.
=> CS compliance: more whitespace fixes

admin/class-bulk-editor-list-table.php, admin/google_search_console/views/gsc-display.php, admin/google_search_console/views/gsc-redirect-nopremium.php, admin/views/tabs/metas/post-types.php
_N/A_
No need to `echo sprintf` if you can just `printf` ;-)
_N/A_
=> CS/QA: minor simplification

inc/sitemaps/class-post-type-sitemap-provider.php
* Changes a quoted replacement variable to be not quoted.
*
As the issue is already closed, just using a related to reference the original issue:
Related #7911
=> Remaining quoted string replacement

frontend/class-twitter.php
=> Add action to allow developers to add images to the Twitter tags

admin/class-plugin-availability.php
=> 8146 add woocommerce seo suggestion 2

.travis.yml
=> Also run travis on release branches and hotfixes

admin/config-ui/class-configuration-page.php
_N/A_
No variable replacement taking place. Translators comment also not needed.
_N/A_
=> CS/QA: replace an unnecessary printf()

admin/google_search_console/class-gsc-bulk-action.php
_N/A_
Minor function refactor. Part of the "remove assignments in conditions" effort, but in this case, there was some duplicate code as well, so it seemed simpler to just refactor the method.
_N/A_
=> CS/cleanup: minor function refactoring

package.json, yarn.lock
Version bump components (2.11.1) and yoastSEO.js (1.23.1)
=> Version bump components and yoastseojs

admin/class-admin.php
I have moved a deprecated method to the bottom of the class. This is the location where other deprecated methods are placed as well.
=> Moved the deprecated method to the bottom of the class.

admin/google_search_console/class-gsc-platform-tabs.php
* Adds better HTML escaping to the Search Console tabs.
* Connect to a Search Console profile
* Use the tabs
Fixes #8249
=> escape tab html output

readme.txt
Improves the changelog descriptions.
=> Update changelog descriptions

admin/class-admin-init.php, admin/class-admin.php, admin/config-ui/fields/class-field-success-message.php, admin/links/class-link-notifier.php, admin/onpage/class-ryte-service.php, frontend/class-breadcrumbs.php, tests/admin/links/test-class-link-watcher.php, tests/admin/test-class-plugin-suggestions.php, tests/test-class-wpseo-breadcrumbs.php, tests/test-class-wpseo-frontend.php
_N/A_
* Code style compliance. 
Variety of whitespace / code layout fixes.
_N/A_
=> CS/QA: Clean up after latest merges

frontend/class-frontend.php, tests/doubles/frontend-double.php, tests/test-class-wpseo-frontend.php
=> Make unhooking html comment easier

readme.txt
Adds changelog items from yoast-components
=> Changelog items from yoast components 

package.json, readme.txt
Update yoast-components to 2.11.4
=> Update yoast-components to 2.11.4

package.json, yarn.lock
Update yoast-components to 2.11.5
=> Update components version

package.json, yarn.lock
* Changes the feedback string for a good meta description length from `The length of the meta description is sufficient.` to `The meta description has a nice length.` https://github.com/Yoast/YoastSEO.js/pull/1307
=> Change yoastseo.js version

package.json, readme.txt, yarn.lock
Bump yoast-components version and add addition to changelog
=> Bump yoast-components version and add addition to changelog

admin/class-help-center.php, admin/formatter/class-metabox-formatter.php
* Introduce sprintf for strings with react-intl variables
* Build this branch.
* Check whether no strings are broken. NB. the foundResultsText is a screenreader text.
Fixes #8406
=> Introduce sprintf for strings with react-intl variables

admin/class-export.php
_N/A_
This hard-coded string is only referenced once a few lines down, so no need to assign it to a variable.
_N/A_
=> CS/QA: remove unnecessary variable setting

admin/views/tabs/social/google.php
=> CS/XSS: always escape output - 19

admin/views/tabs/social/pinterest.php
=> CS/XSS: always escape output - 20

composer.lock, yarn.lock
=> Upgrade dependencies

admin/metabox/class-metabox-add-keyword-tab.php, admin/metabox/class-metabox.php
_N/A_
* Code style compliance. Classes should be prefixed with a plugin specific prefix.
Yes, please!
=> CS: rename non-prefixed class

js/src/edit.js
* Fixes a bug where the collapsible headings in the content analysis were not translated. 
* Set your site language to a language that is not English, but is translated. 
* Check whether the new headings in the content analysis are translated (good, bad, need improvement, considerations).
=> Fix intl provider for content analysis

inc/class-wpseo-replace-vars.php
=> When post is password protected don't replace var excerpt.

grunt/config/eslint.js, js/src/edit.js, js/src/wp-seo-help-center.js
*
Fixes the following errors: 
* Build this branch.
* Go to the post page and open the help center. 
* Check your console.
=> Fix React Intl errors and fix propType

grunt/config/eslint.js, js/src/edit.js, js/src/wp-seo-help-center.js
Reverts Yoast/wordpress-seo#8504
=> Revert "Fix React Intl errors"

admin/class-help-center.php
* Adds translation for the Help center's "Need help?" button.
* You can change line 220 in `class-help-center.php` and see the new translations be applied to the button.
Fixes #8520
=> Added translation for need help button

readme.txt
=> Update readme copy

frontend/class-json-ld.php
** Use late escaping and remove an unnecessary variable setting.
Test this by opening a relevant admin page in a browser and checking that things still work as expected.
=> CS/XSS: always escape JS output - 2

changelog.txt, readme.txt
=> Added changelogs

.github/PULL_REQUEST_TEMPLATE.md
Making it concrete that this is a focus and not just a vocal intention.
=> Add testing focus to PR template

frontend/class-breadcrumbs.php, frontend/class-json-ld.php
_N/A_
More docblock punctuation fixes. Similar to #8194.
Not claiming completeness, just another step in the right direction.
_N/A_
=> Documentation: more docblock punctuation

admin/class-import-aioseo.php, admin/class-import-jetpack.php, admin/class-import-woothemes-seo.php, admin/class-import-wpseo.php
* Make sure old meta values are properly deleted during imports.
* Properly pass on class constructor variables.
=> Make sure $replace is passed on properly

admin/views/tabs/dashboard/features.php
Someone needs to look at the tests for this and fix them :) 
* Changed the explanation of features on the features tab and linked to explanatory articles where needed.
* Added an `order` attribute to the objects to make adding features halfway easier.
* Go to features tab, note state.
* Apply this PR, see the difference.
Fixes #8739
=> Changes labels for features

inc/sitemaps/class-sitemaps-renderer.php, inc/sitemaps/class-sitemaps.php
This pull contains two improvements for #8521
=> Improve use of xsl

admin/config-ui/fields/class-field-advanced-settings.php
* Go to the advanced setting step in the configuration wizard and verify that the content is changed.
=> Configuration wizard change copy

admin/class-admin-asset-seo-location.php, admin/class-help-center.php, admin/class-import-seopressor.php, admin/config-ui/fields/class-field-advanced-settings.php, admin/formatter/class-metabox-formatter.php, admin/metabox/class-metabox-editor.php, admin/views/tabs/dashboard/features.php, frontend/class-frontend.php, tests/admin/test-class-admin-asset-dev-server-location.php, tests/admin/test-class-extension-manager.php, tests/bootstrap.php, tests/doubles/class-wpseo-post-type-sitemap-provider-double.php, tests/frontend/test-class-wpseo-frontend-title.php, tests/frontend/test-class-wpseo-frontend-woocommerce-shop.php, tests/frontend/test-class-wpseo-frontend.php, tests/inc/test-class-post-type.php, tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php, tests/test-class-admin-asset.php
_N/A_
* Code style compliance. 
Variety of whitespace / code layout fixes.
_N/A_
=> CS: Clean up after the latest merges

admin/views/class-view-utils.php, inc/sitemaps/class-sitemaps-admin.php
Found some code that was leftover from the XML sitemaps merge, removed it. "Boyscouted" the options usage.
* XML sitemaps should still work as intended, not all that much to test.
=> Remove leftover post exclusion code

.travis.yml
Instead of doing separate lines, which belong together, use the multiline statements.
If the build works as before and passes this works.
=> Use multiline format for statements

admin/pages/metas.php
Must have gone missing in a merge somewhere.
* Go to Search Appearance, see Breadcrumbs tab.
=> Bring back breadcrumbs

admin/ajax.php, admin/class-yoast-dashboard-widget.php
See https://github.com/Yoast/wordpress-seo/pull/8903
=> Only load dashboard on admin_init

inc/options/class-wpseo-option-wpseo.php
Alexa verification was removed 2 years ago, this single line was a leftover from that removal. Props @iamazik 
Fixes #8965
=> Remove stray alexaverify option

.travis.yml
Adds folding groups as described in https://github.com/travis-ci/travis-ci/issues/2158
This should make the Travis build a lot more comprehensible.
All completed sub-tasks will be collapsed if they passed successfully.
If a tasks fails, it will not be collapsed.
=> Add folding to travis parts

admin/config-ui/fields/class-field-social-profiles-intro.php
* None
* Go to the 5th tab in the configuration wizard.
Fixes #8945
=> Rename Advanced settings reference to `Social`

admin/banner/class-admin-banner-sidebar.php, admin/views/licenses.php
Fixes #9010
Fixes #9013
Fixes #9046
=> Ad changes

tests/onpage/test-class-onpage-request.php, tests/test-class-wpseo-meta-columns.php, tests/test-class-wpseo-metabox.php
The coverage build errors over some wrong `@covers` comments, fixed them.
=> Fix coverage build

.travis.yml
This will help us when debugging problems in Travis, by providing information about the specific loaded versions.
=> Add version number information to Travis builds

admin/class-meta-columns.php
Fixes a typo in the documentation
=> Fixes typo

admin/ajax.php, admin/class-bulk-editor-list-table.php, admin/views/tabs/metas/post-types.php, inc/class-wpseo-replace-vars.php
* Replace the word post type to content type in all places
* Please, check the Search Appearance -> Content Types (tab) -> Archives section.
* Please, check the Tools -> Bulk Editor -> Content Types filter and column.
Fixes #9172 
Fixes #9032
=> Replace Post Type to Content Type

tests/onpage/test-class-onpage.php
* (N/A)
* Run the tests and see them pass.
Fixes #9291
=> Fix OnPage unit test

admin/views/tabs/dashboard/features.php
* Changed the wording for the Ryte indexability check on the features tab.
* See features tab.
Fixes #8954
=> Change wording of Ryte integration

admin/formatter/class-metabox-formatter.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-fields-presenter.php, js/src/analysis/tabManager.js, js/src/components/contentAnalysis/AnalysisSection.js, js/src/edit.js, js/src/redux/actions/activeTab.js, js/src/redux/reducers/activeTab.js, js/src/wp-seo-metabox.js, js/src/wp-seo-post-scraper.js, js/src/wp-seo-term-scraper.js
Reverts Yoast/wordpress-seo#9265
And apply fix for PR https://github.com/Yoast/wordpress-seo/pull/9216
Fixes https://github.com/Yoast/wordpress-seo/issues/8784
=> Fix "Use StyledSection for analyses"

js/src/edit.js, js/src/redux/actions/keywords.js, js/src/redux/reducers/keywords.js, js/tests/redux/actions/keywords.test.js, js/tests/redux/reducers/keywords.test.js
* Add keywords to redux layer
Implements 3 actions:
* setKeywords( array )
* addKeyword( string, index )
* removeKeyword( string )
* Normal development steps: `(composer install & yarn install) && grunt build`
* Run `yarn test`
Fixes #9306
=> Add keywords to redux layer

admin/class-help-center.php, inc/class-wpseo-shortlinker.php, tests/inc/test-class-wpseo-shortlinker.php
* _Not applicable_
Replaces #9383 
Fixes #9376
=> Change parameters yoa.st links

admin/metabox/class-metabox.php, admin/views/licenses.php, admin/views/tabs/tool/import-seo.php, admin/views/tool-import-export.php, admin/views/user-profile.php, frontend/class-frontend.php, inc/class-upgrade.php, inc/class-wpseo-meta.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-option-titles.php, inc/options/class-wpseo-options-backfill.php, inc/sitemaps/class-sitemaps.php, tests/admin/import/test-class-import-status.php, tests/frontend/test-class-wpseo-frontend.php, tests/inc/options/test-class-wpseo-options-backfill.php, tests/test-class-wpseo-upgrade.php
* _N/A_
Various whitespace fixes and comma's after last item in arrays.
This PR will be easiest to review by using the `?w=1` trick: https://github.com/Yoast/wordpress-seo/pull/9345/files?w=1
* _N/A_
=> CS: clean up after latest merges - whitespace fixes

.codeclimate.yml, README.md, phpmd.xml
=> Configure some CodeClimate sniffs to be less annoying

admin/config-ui/fields/class-field-google-search-console-intro.php, admin/views/tabs/dashboard/features.php, admin/views/tabs/tool/import-seo.php
* _Security hardening_
* Includes layout changes for some long function calls to multi-line.
* Verify that the visual presentation of the pages affected has not been changed.
=> CS: clean up after latest merges - escape output

.babelrc, js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap, webpack/webpack.config.default.js
* This makes it much easier to see which styled components are and
aren't used.
=> Use babel-plugin-styled-components

tests/admin/import/test-class-import-premium-seo-pack.php, tests/admin/import/test-class-import-squirrly.php
* _N/A_
* Part of clean up after merges. No functional changes and as these are function local variables, no BC-break.
* _N/A_
=> CS/QA: rename some local variables to snake_case

admin/class-add-keyword-modal.php, admin/class-bulk-editor-list-table.php, admin/class-premium-benefits-list.php, admin/class-unsupported-php-message.php, admin/class-yoast-modal.php, admin/google_search_console/views/gsc-display.php, admin/import/plugins/class-import-seo-framework.php, admin/import/plugins/class-import-squirrly.php, admin/metabox/class-metabox-add-keyword-tab.php, admin/metabox/class-metabox-addon-section.php, admin/metabox/class-metabox.php, admin/services/class-indexable-post-provider.php, admin/services/class-indexable.php, admin/views/licenses.php, frontend/class-opengraph-image.php, inc/options/class-wpseo-option-social.php, tests/admin/import/test-class-import-premium-seo-pack.php, tests/admin/import/test-class-import-smartcrawl.php, tests/admin/import/test-class-import-squirrly.php, tests/admin/test-class-database-proxy.php, tests/frontend/test-class-wpseo-image-utils.php, tests/frontend/test-class-wpseo-opengraph-image.php, tests/inc/test-class-post-type.php, tests/onpage/test-class-onpage.php, tests/services/test-class-indexable-post-provider.php, tests/services/test-class-indexable-term-provider.php, tests/sitemaps/test-class-wpseo-sitemaps-renderer.php
* _N/A_
Mostly whitespace fixes, some missing parenthesis on class instantiation, one docblock format fix.
This PR will be easiest to review using the `?w=1` trick on the files tab.
*_N/A_
=> CS: clean up after latest merges

frontend/class-opengraph-image.php, inc/class-wpseo-image-utils.php, tests/frontend/test-class-wpseo-image-utils.php, tests/frontend/test-class-wpseo-opengraph-image.php
* N/A
*
* The unit test should pass.
* You might consider instantiating the class somewhere (`function.php`):
```php
add_action( 'init', function() {  
$instance = new WPSEO_Opengraph_Image();
$instance->add_image( array( 'no_url_key' => 'present' ) ); 
} );
``` 
Related #9609
Fixes #9676
=> Check if url key exists in given argument

js/src/values/defaultReplaceVariables.js
* N/A
* Add missing replace variables default
* Check for typos
=> Add missing replace variables default

js/src/redux/reducers/activeKeyword.js
* This makes sure code that relies on the string being there just works.
=> Default active keyword to empty string

js/src/components/SnippetPreviewSection.js
* N/A
* Decided to pass a placeholder as a prop to the snippet editor. PR in yoast components
* Checkout yoast-components branch: https://github.com/Yoast/yoast-components/pull/536
* Link yoast-components.
* Follow testing steps mentioned in: https://github.com/Yoast/yoast-components/pull/536
Fixes #9736
=> Implement meta description placeholder

admin/config-ui/fields/class-field-mailchimp-signup.php
* N/A
*
* Open configuration wizard and go to the email signup.
Fixes #9741
=> Update privacy policy string

package.json, yarn.lock
* Updated yoast components version to 4.0.2.
* Check if everything still works
=> bumped the version of yoast components to version 4.0.2

admin/class-admin-media-purge-notification.php
To avoid losing the data being filtered elsewhere
*
*
*
Fixes #
=> Return the input

.gitignore, Gruntfile.js, grunt/config/wp_deploy.js
* Introduces a new location for the the SVN repository to be checked out in.
* Creating a new variable in the gruntfile.
* Using it in production.
Fixes #9792
=> Grunt Deploy: Change SVN checkout directory

readme.txt
n/a
* Adds a missing item to the change log.
=> Add missing change log item

inc/class-upgrade.php, inc/class-wpseo-content-images.php
* N/A
The version in the upgrade routing should be set to 7.7 instead of 7.6 (#9715)
=> Change version number in update routine

admin/class-admin-media-purge-notification.php
* N/A
*
*
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/1802
=> Forcibly removes the attachment URL notification

admin/watchers/class-slug-change-watcher.php
Discusse the copy change with @jdevalk 
* n/a
*
* See https://github.com/Yoast/wordpress-seo/pull/10089
=> Update notification copy

readme.txt
* N/A
* I've moved ```* Fixes a bug where the analysis results were being hidden while updating.``` to the premium changelog.
=> Update 7.7 changelog

package.json, yarn.lock
* N/A
* Test whether these changes are working: https://github.com/Yoast/wordpress-seo/pull/10224
* Test whether nothing else breaks.
=> Bump components to 4.6

css/src/search-appearance.scss
I added the build CSS files, but forgot the scss file
=> Add missing scss file

admin/taxonomy/class-taxonomy.php, frontend/class-frontend.php
* N/A
* N/A
* Verify the correct milestone is set in the code because the PR this PR fixes was merged on a incorrect milestone.
Fixes #10072
=> Set the correct milestone for the deprication warnings of 10072

js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap, package.json, yarn.lock
* N/A
* Need the latest version of Jest to have more specific matcher assertions available for testing.
* `Yarn install`, then `yarn test`.
* Verify that the tests still work.
~* [ ] I have added unittests to verify the code works as intended~
=> Upgrade Jest to latest version

admin/menu/class-replacevar-editor.php, admin/views/class-view-utils.php, admin/views/tabs/metas/archives.php, admin/views/tabs/metas/general/homepage.php, admin/views/tabs/metas/post-types.php, admin/views/tabs/metas/taxonomies.php
* n/a
*
* Checkout this branch and verify if everything related to replacement variables on the search appearance settings page is still working.
Fixes #
=> Pass the arguments as array instead of class properties.

admin/views/paper-collapsible.php, admin/views/tabs/metas/paper-content/general/homepage.php, admin/views/tabs/metas/paper-content/taxonomy-content.php
* n/a
*
* Check if the template editors in search appearance do not have paper style.
=> Fix the paper styling for in-paper replace var editors.

js/src/components/Sidebar.js, js/src/containers/Sidebar.js, js/src/edit.js, js/src/redux/reducers/index.js, js/src/redux/reducers/preferences.js, yarn.lock
* Adds a container deal with the displaying of the SEO and Readability analysis based on user preferences.
* @atimmer and I decided to use the current implementation to determine the user preferences based on localized scripts as this is a proven solution and the quickest way to move forward.
* Checkout this branch and ensure you've properly run `yarn upgrade yoast-components`.
* Ensure you have all the necessary flags set to enable Gutenberg and sidebar support.
* Run `yarn start`.
* Add a new post and enable the Yoast Sidebar. See that the labels 'Readability analysis' and 'SEO analysis' show up.
* Go to SEO -> General -> Features  and disable SEO analysis.
* Go back to your post …
=> Implemented Sidebar container

admin/metabox/class-metabox-section-react.php
* _N/A_
* Refrain from trying to replace the entire content.
* Use `%s` in an SEO title on a post edit page.
=> Only use `printf` on the part that needs a variable

readme.txt
=> Modify 8.0 changelog

js/src/wp-seo-term-scraper.js
* N/A
* Create a new term (tag or category) and edit it.
* See that the focus keyword is prefilled with the name of the term.
Fixes #10544
=> Use termscraper to fetch keyword for initial keyword value

admin/class-admin.php, admin/class-paper-presenter.php, admin/config-ui/fields/class-field-success-message.php, admin/formatter/class-metabox-formatter.php, admin/google_search_console/class-gsc-modal.php, admin/import/class-import-settings.php, admin/links/class-link-installer.php, admin/links/class-link-reindex-dashboard.php, admin/metabox/class-metabox-section-react.php, admin/notifiers/class-post-type-archive-notification-handler.php, admin/onpage/class-ryte-service.php, admin/views/sidebar.php, admin/views/tabs/metas/paper-content/breadcrumbs-content.php, admin/views/tool-file-editor.php, frontend/class-breadcrumbs.php, inc/class-wpseo-admin-bar-menu.php, inc/class-wpseo-custom-taxonomies.php, inc/sitemaps/class-sitemap-image-parser.php, inc/wpseo-non-ajax-functions.php, tests/admin/test-class-admin-editor-specific-replace-vars.php, tests/frontend/test-class-opengraph.php, tests/test-class-wpseo-meta.php
_N/A_
Mostly whitespace fixes, a missing comma after last array item and a missing semi-colon in embedded PHP.
_N/A_
=> CS: clean up after merges

.travis.yml
* N/A
This is a hotfix for a small mistake in #10548
=> Place the add key code in the correct entry and fix the travis build

admin/class-gutenberg-compatibility.php, css/src/structured-data-blocks.scss, inc/class-structured-data-blocks.php, inc/structured-data-blocks/class-faq-block.php, inc/structured-data-blocks/class-how-to-block.php, js/src/structured-data-blocks/faq/block.js, js/src/structured-data-blocks/faq/components/FAQ.js, js/src/structured-data-blocks/faq/components/Question.js, js/src/structured-data-blocks/how-to/block.js, js/src/structured-data-blocks/how-to/components/HowTo.js, js/src/structured-data-blocks/how-to/components/HowToStep.js, js/src/wp-seo-structured-data-blocks.js
* Added a Yoast Structured Data block for creating FAQ pages.
* The code has swollen slightly for this implementation, and could definitely use a cleaning-pass, but it works and it needs to be in 8.1
* Make sure you have the feature flag set to true:
```define('YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS', true );```
* Add the FAQ block in a post in the Gutenberg editor.
* Verify that everything functions as you expect: Editing title and questions/answers, inserting, removing, moving, etc.
* Verify that editting triggers autosaving correctly (there are no "Update failed" warnings).
* Use the Ordered/Unordered list toggle in the sidebar, and verify that the block switches out …
=> Create Structured Data Block - FAQ Page

webpack/webpack.config.js
=> Use the default external name in the worker scripts as well.

js/src/analysis/collectAnalysisData.js, js/src/analysis/refreshAnalysis.js
* N.A.
* Sends the paper to the worker as it's automatically parsed with https://github.com/Yoast/YoastSEO.js/pull/1731.
* When combined with https://github.com/Yoast/YoastSEO.js/pull/1731 it should work.
Fixes #
=> Send paper to worker.

js/src/analysis/refreshAnalysis.js
Remove unused import of 'Paper'
=> Remove unused import of 'Paper'

package.json, yarn.lock
=> Bump components version

js/src/components/SnippetPreviewModal.js
=> Make the modal close button translatable

package.json, yarn.lock
* Adds readability analysis for 
* Change the language of your WordPress site to Polish (you can set your profile language to English to keep your interface in English).
* Add a Polish text and check whether the following assessments work for Polish:
* Transition word assessment
* Sentence length limit for Polish
* Sentence beginnings assessment
* Passive voice assessment for Polish
=> Bump YoastSEO.js to 1.39.0

package.json, yarn.lock
=> Set components version to develop branch

admin/class-admin-asset-manager.php
* Fixes incorrect dependencies for search appearance js and css.
*
* Install `Query Monitor` plugin.
* Load search appearance page, make sure `Query Monitor` doesn't show any errors regarding script and css dependencies.
Fixes #10879
=> Fix search appearance dependencies

css/src/structured-data-blocks.scss, js/src/structured-data-blocks/faq/components/FAQ.js, js/src/structured-data-blocks/faq/components/Question.js
* N/A
* Renamed HTML elements (see issue).
* Changed the`<strong>` title to a `<h2>`.
````html
<script type="application/ld+json">{"@context":"http:\/\/schema.org","@graph":[{"@type":"FAQPage","name":"This is a title"},{"@type":"Question","name":"Question 1","answerCount":1,"acceptedAnswer":{"@type":"Answer","text":"Answer 1"}},{"@type":"Question","name":"Question 2","answerCount":1,"acceptedAnswer":{"@type":"Answer","text":"Answer 2"}}]}</script>
<div class="schema-faq wp-block-yoast-faq-block">
<strong class="schema-faq-title" id="this-is-a-title">This is a title</strong>
<div class="schema-faq-question"><strong class="schema-faq-question-question">Question 1</strong>
<p class="schema-faq-question-answer">Answer 1</p>
</div> …
```
=> Fix FAQ title and element names

js/src/structured-data-blocks/how-to/components/HowTo.js
Fixes an error in the How To block when the `release/8.2` branch was merged into trunk.
It seems https://github.com/Yoast/wordpress-seo/pull/10910/files was largely undone when these branches were merged.
* N/A
*
* 
* [x I have tested this code to the best of my abilities
=> Fixed error that was introduced when merging release/8.2 into trunk

js/src/structured-data-blocks/how-to/block.js, js/src/structured-data-blocks/how-to/legacy/8.2.js, js/src/structured-data-blocks/how-to/legacy/index.js
=> 10995 added 8.2 deprecated save

admin/notifiers/class-post-type-archive-notification-handler.php
=> PHPUnit: fix two typos in ignore annotations

inc/indexables/class-indexable.php
* _N/A_
Method modifiers should be in the following order:
`[abstract|final] [visibility, i.e. public|protected|private] [static] function function_name() {}`
* _N/A_
=> CS: method modifier/visibility order

package.json, yarn.lock
* N/A.
* Bumps Yoast Components to v. 4.13
=> Bump Yoast Components to 4.13.0.

readme.txt
=> Improve 9.0 changelog

inc/options/class-wpseo-taxonomy-meta.php
This way it is actually saved.
*
*
*
Fixes #
=> Add Twitter image ID to term options

grunt/config/shell.js, package.json, yarn.lock
* _N/A_
* This was breaking the Windows build.
*
=> Fix `build:i18n` on Windows

admin/class-admin-asset-manager.php, js/src/wp-seo-recalculate.js
* Fixes a bug where a dependency wasn't loaded for the SEO -> Tools page.
* Fixes a faulty reference to the old SEOAssessor class. 
*
* While on the `trunk` branch, visit the SEO -> Tools page.
* Open the Inspector and see three errors being logged in the console.
* Checkout this branch, reload the page.
* Check the console again and determine that no errors are being logged anymore.
Fixes #11228
=> Fix JavaScript dependencies in asset manager

js/src/components/PrimaryTaxonomyPicker.js, js/src/wp-seo-wp-globals-backport.js, package.json, webpack/webpack.config.js, yarn.lock
* N/A
*
* Checkout trunk with the latest Gutenberg RC
* Open a post and see an error in the console (See #11394)
* You will also notice that it is impossible to set a primary category
* Checkout this branch and do `yarn` and all the grunt building magic
* It should be fixed now.
Fixes #11394
=> Make the primary category picker work with latest Gutenberg RC.

README.md
* Improves the `README.md` to use the more generic Markdown style and adds proper contributing documentation.
*
* Read the `README.md` file and ensure there are no weird English sentences.
=> Improved the README by adding proper contribution instructions

admin/class-admin.php
Fixes #9014
* N/A
* N/A
*
Fixes #9014
=> Emphasize Premium Support Link

inc/class-post-type.php
* N/A
*
* Should be tested in combination with Yoast/wordpress-seo-premium#2098. Check this PR for test instructions.
Fixes Yoast/wordpress-seo-premium#1936
Fixed Yoast/wordpress-seo-premium#1710
=> Added has_metabox_enabled function to class-post-type.php

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, inc/class-wpseo-utils.php, js/src/analysis/worker.js, js/src/edit.js
* N/A
* Added the environment variable `YOAST_SEO_DEBUG`. Which is a higher debug toggle that enable the next environment variable. To function as sort of a master switch for when we start adding more debug logs.
* Added the environment variable `YOAST_SEO_DEBUG_ANALYSIS_WORKER`. Which gives the possibility to set a specific Analysis Worker log level.
* Changed `global` to `window` for all gets of `wpseoAnalysisWorkerL10n`. To make it the same as other l10n objects.
Not to sure about the decisions I made here. Very open to feedback proposed changes!
- Is the global flag overkill?
- Piling onto `wpseoAnalysisWorkerL10n` that is almost the same in the metabox and taxonomy files. Could DRY it up a bit. …
=> Yoastseo.js/1792 add loglevel for worker

js/src/wp-seo-term-scraper.js
* N/A
* 
* Check if #11552 is fixed.
Fixes #11552
=> Fixes crashing metabox on term page.

admin/class-recalibration-beta.php
* N/A
* N/A
* Look at the recalibration toggle in the features tab. Check if there is a link, and it has gone through the shortlinker. NB. The link currently goes to the yoast.com homepage, because the article has not been written yet.
Fixes #11617  (only first part)
=> Add link to recalibration toggle explanation text

src/models/indexable-meta.php, src/models/indexable.php
* Minor I18n improvements
* Add translation comments to newly introduced text strings...
* _N/A_
=> QA: add some missing translators comments

js/src/analysis/handleWorkerError.js, js/src/analysis/refreshAnalysis.js, js/src/analysis/worker.js, js/src/components/Metabox.js, js/src/components/Sidebar.js, js/src/containers/Warning.js, js/src/redux/actions/warning.js, js/src/redux/reducers/index.js, js/src/redux/reducers/warning.js, js/src/wp-seo-post-scraper.js, js/src/wp-seo-term-scraper.js, js/tests/analysis/handleWorkerError.test.js, js/tests/redux/actions/warning.test.js, js/tests/redux/reducers/warning.test.js
* Adds a warning message at the top of the metabox and sidebar for when the web worker initialization or analysis fail when using the recalibrated analysis beta.
* An analogous error for non-recalibrated analysis will be implemented in https://github.com/Yoast/wordpress-seo/issues/11736
* Link this branch with `11700-handle-worker-error` on YoastSEO.js and with `11700-add-yoast-warning-component` on yoast-components
* If you have an old FlyWheel that throws the original error, don't do update it! Make sure you have the plugin in the FlyWheel location. Tip for a developer: https://github.com/getflywheel/local-addon-volumes -- that way you can symlink your existing plugins directory …
=> Add warning component to the sidebar and metabox for catching recalibration errors

tests/frontend/test-class-wpseo-frontend.php, tests/test-class-rewrite.php
* Cleanup in  WPSEO_Rewrite_Test::test_category_rewrite_rules
* https://core.trac.wordpress.org/changeset/38654
=> Fixes WPSEO_Rewrite_Test::test_category_rewrite_rules

grunt/config/eslint.js, js/src/structured-data-blocks/how-to/components/HowTo.js, js/src/structured-data-blocks/how-to/components/HowToStep.js
Implemented shouldComponentUpdate in HowToStep and removed function declarations from render functions
* Improves HowToBlock block performance.
* Implemented `shouldComponentUpdate` in `HowToStep` component, and used a shallow compare to prevent all steps from re-rendering when a single step is touched.
* Replaced all anonymous function declarations in the render functions with class member functions (this improves performance overall and was also necessary to make the shallow compare work in `HowToStep`).
* Keep your console open to catch potential errors.
* Create a How To block with multiple steps.
* Make sure you can still switch steps with the up and down buttons.
* Make sure …
=> Improved HowTo block performance.

admin/config-ui/class-configuration-structure.php
* _N/A_
As the "fields" arrays don't change, there is no need to declare them in the function itself.
Declaring them in a class property improves the readability and maintainability of the code.
* _N/A_
=> CS: Move static arrays to a class property [1]

readme.txt
This needs to be merged on the branch which enables the recalibration notification and feature toggle.
At this moment it has not been determined if this will be a separate release or will be included in 9.4.
Related: https://github.com/Yoast/wordpress-seo-premium/pull/2162
=> Re-adds the recalibration changelog entries

src/watchers/primary-term-watcher.php
=> Fixed PHPCS warnings in primary-term-watcher.php

js/src/analysis/PostDataCollector.js, js/src/analysis/TermDataCollector.js, js/src/analysis/getI18n.js, js/src/analysis/usedKeywords.js, js/src/edit.js, js/src/wp-seo-markdown-plugin.js, js/src/wp-seo-post-scraper.js, js/src/wp-seo-term-scraper.js, js/src/wp-seo-tinymce.js
* [not user-facing] Removed App usages in preparation of being able to remove it fully.
* Refactored used keywords to use the refresh function directly instead of via `App`.
* Refactored edit to use the refresh function directly instead of via `App`.
* Refactored `PostDataCollector` to use the refresh function directly instead of via `App`.
* Refactored `TermDataCollector` to use the refresh function directly instead of via `App`.
* Refactored `TinyMCE` bind events to use the refresh function directly instead of via `App`.
* Refactored `PostDataCollector` to use the getI18n helper instead of from `App`.
* Refactored the post scraper's `handleStoreChange` to use the refresh function directly instead of via `App`.
* Refactored the …
=> Yoastseo.js/1741 deprecate app

tests/src/doubles/database-migration.php, tests/src/doubles/indexable-author-formatter-double.php, tests/src/doubles/indexable-post-formatter-double.php, tests/src/doubles/indexable-term-formatter-double.php, tests/src/doubles/plugin.php
* _N/A_
Add perfunctory class docblocks where these were missing. Descriptions can do with improvement, but this is a step in the right direction.
* _N/A_
=> Documentation: add missing class docblocks

admin/class-social-admin.php
* N/A - Fix input CS issues in `admin/class-social-admin.php`
* Fixes the following errors:
```
FILE: admin\class-social-admin.php
--
FOUND 3 ERRORS AFFECTING 2 LINES
212 \| ERROR \| Processing form data without nonce verification.
\|       \| (WordPress.Security.NonceVerification.NoNonceVerification)
213 \| ERROR \| Processing form data without nonce verification.
\|       \| (WordPress.Security.NonceVerification.NoNonceVerification)
213 \| ERROR \| Processing form data without nonce verification.
\|       \| …
```
=> YoastCS: Add nonce verification social admin

admin/metabox/class-metabox.php
* N/A 
* Fixes the following issues:
```
FILE: admin\metabox\class-metabox.php
--
FOUND 7 ERRORS AFFECTING 4 LINES
713 \| ERROR \| Processing form data without nonce verification.
\|       \| (WordPress.Security.NonceVerification.NoNonceVerification)
713 \| ERROR \| Processing form data without nonce verification.
\|       \| (WordPress.Security.NonceVerification.NoNonceVerification)
740 \| ERROR \| Processing form data without nonce verification.
\|       \| (WordPress.Security.NonceVerification.NoNonceVerification)
743 \| ERROR …
```
=> Yoastcs: Fix input issues for class-metabox.php

admin/pages/dashboard.php
* N/A
* Fixes the following issue:
```
FILE: admin\pages\dashboard.php
--
FOUND 1 ERROR AFFECTING 1 LINE
25 \| ERROR \| Missing wp_unslash() before sanitization.
\|       \| (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
```
* No functional change.
Fixes #
=> Unslash the value

admin/class-social-admin.php, frontend/class-frontend.php, inc/class-wpseo-meta.php, tests/test-class-wpseo-meta.php
* N/A
* I moved the content of a method to the location where this method has been called, because it the only usage of this method.
* This pull should fix the following issues:
```
FILE: inc\class-wpseo-meta.php
--
FOUND 6 ERRORS AND 1 WARNING AFFECTING 3 LINES
358 \| WARNING \| Processing form data without nonce verification.
\|         \| (WordPress.Security.NonceVerification.Recommended)
359 \| ERROR   \| Missing wp_unslash() before sanitization.
\|         \| (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
994 \| …
```
=> YoastCS: Fix cs issues in inc\class-wpseo-meta.php

admin/class-plugin-conflict.php, admin/google_search_console/views/gsc-display.php
* Fixes couple typos. Also, it fixes PHPCS error.
Fixes #
=> Fixes couple typos

.travis.yml
=> Skip test step on tag builds

readme.txt
* n/a
* Removes a YoastSEO.js changelog item that is only applicable in Premium.
=> Remove changelog items that's only applicable to premium

admin/class-admin.php
* N/A
* Remove left-over method call
* N/A
=> Remove call to deprecated method

admin/class-bulk-editor-list-table.php, admin/config-ui/fields/class-field-company-logo.php, admin/config-ui/fields/class-field-company-name.php, admin/config-ui/fields/class-field-company-or-person.php, admin/config-ui/fields/class-field-person-name.php, tests/src/unit-tests/exceptions/no-indexable-found-test.php, tests/src/unit-tests/watchers/indexable-post-watcher-test.php
* _N/A_
Just adding some missing function docblocks and short descriptions. (Lots more to go)
* _N/A_
=> Documentation: add some missing function docblocks and descriptions

inc/class-myyoast-api-request.php, inc/class-wpseo-utils.php, inc/exceptions/class-myyoast-authentication-exception.php, inc/exceptions/class-myyoast-bad-request-exception.php, inc/exceptions/class-myyoast-invalid-json-exception.php, phpcs.xml.dist, src/loaders/oauth.php, tests/inc/test-class-myyoast-api-request.php
* N/A - This is for the My Yoast integration.
*
* If the code looks good and the tests are passing you can merge. There is no functional change.
Fixes #12151
=> Introduces a MyYoast api request class

frontend/class-json-ld.php
Implements theme-support check for BreadcrumbList structured data
Closes #11989
=> fix: breadcrumbs structured data enabled with theme support

admin/class-my-yoast-route.php, inc/class-myyoast-api-request.php, tests/admin/test-class-my-yoast-route.php, tests/doubles/class-my-yoast-route-double.php
* N/A - Adds the authorize route.
*
* N/A - There are unit tests. We will connect everything together in a later stadium.
Fixes #12132
=> Add authorize route

admin/class-my-yoast-route.php, tests/admin/test-class-my-yoast-route.php, tests/doubles/class-my-yoast-route-double.php
* N/A - Adds the complete route.
*
* N/A - There are unit tests. We will connect everything together in a later stadium.
Fixes #12135
=> Adds the oAuth complete route

admin/class-my-yoast-route.php, composer.json, config/php-scoper/oauth2-client.inc.php, config/php-scoper/psr.inc.php, inc/class-myyoast-api-request.php, src/loaders/oauth.php, tests/admin/test-class-my-yoast-route.php
* N/A - Makes some change to connect the oAuth flow
* Extended the `prefix-oauth2-client` config in composer with some new configuration and commands to prefix missing `psr` dependencies.
* This can be best tested later on, when the flow can be done visually. I've done this work with @herregroen to set the first steps in this oAuth flow. 
Fixes #
=> Makes some improvements for the oAuth flow

.travis.yml
* [not-user-facing] Bump the tested WordPress versions in Travis to the latest and before-latest.
* See Travis pass.
=> Update WordPress version to test against

tests/bootstrap.php
* [not-userfacing] Updates the `bootstrap.php` file so that PHPUnit will also work correctly in the new VVV installations.
* This code was developed by @moorscode from my computer. Please ask him about technical choices.
* Check whether PHPUnit can perform a unit test without causing any unexpected errors.
* Check whether the unit test still works as expected.
Fixes #
=> Updated bootstrap.php so that PHPUnit works in newer VVV installations

package.json, yarn.lock
* Bumped marked to version 0.6.1
*
* Install jetpack and set it to development mode by setting `define( 'JETPACK_DEV_DEBUG', true);` in `wp-config.php`.
* Under `Jetpack`> `Settings` > `Writing`, enable `Write posts or pages in plain-text Markdown syntax`.
* Now write a page or post in markdown (use the **text editor** and not the visual editor) and make sure the analyses update accordingly.
In the following text for exxample the following analyses are present:
* Subheading distribution: Great job!
* Outbound links: Good job!
* Keyphrase in subheading: Your subheading reflects the topic of your copy. Good job!
```
Test. [Link](https://example.com).
Some data about subheadings.
A new …
```
=> Bumped marked to 0.6.1

yarn.lock
* Updated deep-extend to 0.6.0
*
*
Fixes #
=> Updated deep-extend-to-0.6.0

yarn.lock
* [not-userfacing] Updated merge to 1.2.1
*
* Run yarn test
Fixes #
=> Updated merge to 1.2.1

tests/admin/exceptions/test-file-size-exception.php
* N/A Adds a unit test
*
* It are unit tests, if the build passes it can be merged!
Fixes #
=> Adds a testclass for testing file size exception

admin/class-bulk-editor-list-table.php, admin/google_search_console/class-gsc-table.php, admin/import/plugins/class-abstract-plugin-importer.php, admin/views/tabs/dashboard/features.php, admin/views/tabs/network/features.php, admin/views/tabs/network/general.php, frontend/class-frontend.php, inc/class-rewrite.php, inc/class-wpseo-image-utils.php, inc/class-wpseo-meta.php, inc/options/class-wpseo-option.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps-renderer.php, inc/sitemaps/class-sitemaps-router.php, src/yoast-model.php, wp-seo-main.php
=> Documentation: use multi-line comment format for long inline comments

admin/ajax/class-yoast-dismissable-notice.php, admin/google_search_console/class-gsc-table.php, admin/import/plugins/class-importers.php, inc/class-wpseo-primary-term.php
=> Documentation: add some missing property short descriptions

tests/admin/links/test-class-link-watcher.php
=> Test documentation: fix incomplete test short description

admin/config-ui/components/class-component-mailchimp-signup.php, admin/config-ui/fields/class-field-mailchimp-signup.php, admin/google_search_console/class-gsc.php, inc/wpseo-non-ajax-functions.php, js/src/components/MailchimpSignup.js
* N/A In documentation, refer to the user as `him/her`.
* _N/A_
=> Don't assume the user is male

admin/links/class-link-type-classifier.php
=> Documentation: improve a function description

admin/class-yoast-plugin-conflict.php, admin/config-ui/components/class-component-mailchimp-signup.php, admin/config-ui/fields/class-field-mailchimp-signup.php, admin/google_search_console/class-gsc.php, inc/wpseo-non-ajax-functions.php
* _N/A_ Replaces `he or she` by `they`.
* _N/A_
Related to #12497
=> Make gender neutral

inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemaps.php
Reverts Yoast/wordpress-seo#12075
=> Revert "Add filters to handle custom post statuses when generating sitemap"

inc/class-addon-manager.php
These are the Premium 10.1.2 release changes.
_For trunk_
*
*
*
Fixes #
=> Backport transient fix Premium patch

package.json, yarn.lock
* _N/A_ (This was caused during this cycle)
*
*
Fixes #12635
Fixes https://github.com/Yoast/wordpress-seo/issues/12644
=> Fix edit-post metabox

admin/views/tabs/social/accounts.php
* [not user-facing] Changes a mention of 'company' to 'organization'.
* N/A
* See issue
Fixes #12677
=> Changes a mention of 'company' to 'organization'

js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap, js/tests/components/__snapshots__/UpsellBox.test.js.snap, package.json, yarn.lock
* [non-user-facing] Updates the dependencies for 11.1-RC1.
* n/a
* 
Fixes #
=> Update dependencies for 11.1 RC

js/src/components/CollapsibleCornerstone.js
* N/A - Fix wrong import.
*
* Checkout this branch, do `yarn link-monorepo` and the asset building steps
* See the padding is right.
Fixes #12756
=> Reference the right collapsible

inc/class-wpseo-meta.php
=> Documentation: improve property docblock formatting

admin/views/tabs/social/pinterest.php
* Fix wrong Pinterest confirmation URL
*
*
Fixes #
=> Fix wrong Pinterest confirmation URL

package.json, yarn.lock
* [not-user-facing] Updates all Yoast packages to the stable release versions.
* n/a
* Build the files and check whether nothing breaks.
Fixes #
=> Bump package versions to release versions

js/src/wp-seo-metabox.js
* n/a
* Removes an import of the feature flag package that's not used yet.
*
Fixes #
=> Remove feature flag package import

package.json, yarn.lock
* n/a
*
* Build the plugin and check that there are no errors.
* Also confirm that the following user-facing changes are visible: 
YoastSEO:
Improve recognition of German irregular verbs
https://github.com/Yoast/javascript/pull/210
Configuration wizard:
Add focus style to wizard navigation buttons
https://github.com/Yoast/javascript/pull/8
Multiple packages:
Let makeOutboundLink handle rel attribute automatically 
https://github.com/Yoast/javascript/pull/9
Fixes #
=> Bump packages to newest RC version for 11.2-RC1

README.md
Add instructions on js/monorepo development
Fixes https://github.com/Yoast/javascript/issues/235
=> Add instructions on js/monorepo development

tests/config-ui/test-class-configuration-structure.php
* N/A
Removes GSC from the config wizard test.
=> Remove GSC from the config wizard test

admin/class-add-keyword-modal.php, admin/class-keyword-synonyms-modal.php, admin/class-multiple-keywords-modal.php, admin/formatter/class-metabox-formatter.php, js/src/components/modals/MultipleKeywords.js
* i18n: Merge similar translation strings
*
*
Fixes #
=> i18n: Merge similar translation strings

js/src/components/MediaUpload.js
* i18n: Merge similar translation strings in MediaUpload.js
*
*
Fixes #
=> i18n: Merge similar translation strings in MediaUpload.js

package.json, yarn.lock
* [n/a]
* Bumps packages for 11.2-RC2.
* Merge this branch into a temporary test branch on Premium and check that the German morphology data requested is v3 in the network tab.
* Also check that the morphology data request succeeds and you get morphology data in German.
Fixes #
=> Bump packages for 11.2-RC2

package.json, yarn.lock
* [n/a]
* Bumps packages for the next RX of 11.2.
* Build the files and check that nothing breaks.
Fixes #
=> Bump packages for 11.2 next RC

composer.json
* _N/A_
... to deal correctly with the new `tests` directory.
:warning: This PR should only be merged **after** PR https://github.com/Yoast/wordpress-seo-premium/pull/2394 has been merged! :warning:
Note: once actual tests will be added to the directory for the Premium plugin, these commands will need to be updated to include the directory where the tests will live. Similarly, the Premium `.phpcs.xml.dist` file will need to be updated at that time.
* See PR https://github.com/Yoast/wordpress-seo-premium/pull/2394
=> Composer: update the premium CS script

frontend/schema/class-schema-author.php, frontend/schema/class-schema-context.php, frontend/schema/class-schema-person.php
We decided to make the `Person` piece always output `['Person','Organization']` to fix several issues related to that. Unfortunately this caused a nasty side effect as our Author piece was extended from the `Person` class, causing weird references. 
This pull makes sure that when we output an `Author` piece, it's a `Person` only, not a `['Person','Organization']`, which could cause wrong requirements in terms of `logo` attributes.
This fixes #12972 by moving that logic to a better place in the code, because setting the person image from the logo is extracted to its own method.
This pull also fixes some leftovers from #12852, by casting `site_represents_reference` and `site_represents` to `false` explicitly first, so it can't go wrong.
**Note:** I'm not 100% sure whether this fixes the …
=> Site represents Person logo and reference fixes

frontend/schema/class-schema-faq-question-list.php, frontend/schema/class-schema-faq-questions.php, frontend/schema/class-schema-faq.php, frontend/schema/class-schema.php
* Schema FAQ markup: Don't output questions without answers.
* Add an FAQ block with a few questions, one with only a question, see that it doesn't appear in the output.
Fixes #12821
=> If a question has no answer, don't output it

package.json, yarn.lock
* n/a
* Bump the packages for 11.3.
n/a
Fixes #
=> Bump packages for monorepo 11.3 release

package.json, yarn.lock
* n/a
* Bump the packages for 11.4-RC2.
n/a
Fixes #
=> Bump packages for 11.4-RC2

yarn.lock
* I updated webpack-bundle-analyzer to version 3.3.2
* Check if you are on the correct webpack-bundle-analyzer version (run `yarn webpack-bundle-analyzer -v`)
* Run `yarn webpack-bundle-analyzer` and wait for it to load, several tabs will open.
* Check if the bundles are displayed correctly and no errors are being thrown.
Fixes #13018
=> updated webpack-bundle-analyzer to version 3.3.2

src/config/admin.php, src/watchers/indexable-author-watcher.php, src/watchers/indexable-post-watcher.php, src/watchers/indexable-term-watcher.php
* _N/A_
* Order `use` statements alphabetically for the `src` files.
* _N/A_
=> [src] CS: order `use` statements alphabetically

package.json, yarn.lock
* n/a
* Bump the packages for 11.5-RC1.
n/a
Fixes #
=> Bump package versions for 11.5-RC1

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy-metabox.php
* [non-userfacing] Fixes a bug where the metabox would break when opening a taxonomy edit page.
* [non-userfacing] Fixes a bug where an empty readability tab was shown if the readability analysis was disabled in the `SEO` > `General` > `Features` tab.
* [non-userfacing] Fixes a bug where a lot of whitespace was shown left of the `SEO` label in the tab, because the SEO anlaysis score indicator wasn't rendered when the SEO analysis was disabed in the `SEO` > `General` > `Features` tab.
*
* Make sure the metabox is working on the taxonomy pages.
* With readability analysis **disabled** and SEO analysis **enabled** make sure the readability tab is not shown on the post and taxonomy edit …
=> Metabox readability tab fixes

frontend/class-frontend-page-type.php, frontend/class-frontend.php, frontend/class-opengraph-image.php, frontend/class-opengraph.php, frontend/class-twitter.php, frontend/schema/class-schema-webpage.php, integration-tests/frontend/test-class-front-end-page-type.php, tests/frontend/schema/class-schema-webpage-test.php
* Make the page type `CollectionPage` on all blog home pages.
* Made all `WPSEO_Frontend_Page_Type` calls static.
* Needs some testing because there are quite a few calls I've changed.
Fixes #12993
=> Make the page type `CollectionPage` on all blog archive pages.

package.json, yarn.lock
* n/a
* Bump the packages for 11.6-RC1.
n/a
Fixes #
=> Bump package versions for 11.6-RC1

admin/class-admin-asset-dev-server-location.php, admin/class-admin-asset-yoast-components-l10n.php, admin/class-admin-help-panel.php, admin/class-bulk-editor-list-table.php, admin/class-extension.php, admin/class-gutenberg-compatibility.php, admin/class-meta-columns.php, admin/class-plugin-availability.php, admin/class-plugin-compatibility.php, admin/class-remote-request.php, admin/class-suggested-plugins.php, admin/class-yoast-dashboard-widget.php, admin/class-yoast-notification-center.php, admin/config-ui/class-configuration-endpoint.php, wp-seo-main.php
Adds short descriptions for the following files:
admin/class-admin-asset-dev-server-location.php
admin/class-admin-asset-yoast-components-l10n.php
admin/class-admin-help-panel.php
admin/class-bulk-editor-list-table.php
admin/class-extension.php
admin/class-gutenberg-compatibility.php
admin/class-meta-columns.php
admin/class-plugin-availability.php
admin/class-plugin-compatibility.php
admin/class-remote-request.php
admin/class-suggested-plugins.php
admin/class-yoast-dashboard-widget.php
admin/class-yoast-notification-center.php
admin/config-ui/class-configuration-endpoint.php
wp-seo-main.php
=> Adds short descriptions

package.json, yarn.lock
* n/a
* Bump the packages for 11.7-RC1.
n/a
Fixes #
=> Bump package versions for 11.7-RC1

admin/class-admin-init.php
Fix capitalizing of Classic Editor plugin
=> Fix capitalizing of Classic Editor plugin

admin/class-yoast-notification-center.php
* Removes kses_post from $notification because it broke more than it solved. 
* An issue about how to fix this properly is in the making.
* See https://github.com/Yoast/wordpress-seo-premium/issues/2508
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2508
=> Remove kses_post from notification

package.json, yarn.lock
Bumping javascript package versions in preparation of 12.0-RC.
=> bumping versions for 12.0 RC

.github/CODE_OF_CONDUCT.md
Add a code of conduct file to our repo.
* None needed
=> Create a code of conduct file

src/repositories/indexable-repository.php
* Adds `find_by_indexable_id`  method to `indexable` repository.
*
*
Fixes #
=> Add find_by_indexable_id method to indexable repository

admin/views/partial-alerts-template.php, js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
=> Updated snapshots

composer.lock, inc/sitemaps/class-sitemaps-renderer.php, phpcs.xml.dist, wp-seo-main.php
* _N/A_
A new version of PHPCompatibility has been released containing yet more checks to make sure code is compatible with the upcoming PHP 7.4 release.
Ref: https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.3.0
I suspect that this release may find a few new issues. If that's the case, those will need to be fixed first before this PR can be merged.
I've added two new commits to fix the newly found PHP compatibility issues.
One of these actually fixes a I18N issue, so may need to be added to the changelog. Not sure if the issue has been reported before or not.
* _N/A_
=> Composer: update PHPCompatibility

package.json, yarn.lock
Bumping the versions of the javascript monorepo packages
=> bump package versions for 12.1 RC

composer.lock, inc/sitemaps/class-sitemaps-renderer.php, phpcs.xml.dist, wp-seo-main.php
Duplicate of #13420 (copied to have it in the release branch as well)
* _N/A_
A new version of PHPCompatibility has been released containing yet more checks to make sure code is compatible with the upcoming PHP 7.4 release.
Ref: https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.3.0
I suspect that this release may find a few new issues. If that's the case, those will need to be fixed first before this PR can be merged.
I've added two new commits to fix the newly found PHP compatibility issues.
One of these actually fixes a I18N issue, so may need to be added to the changelog. Not sure if the issue has been reported before or not.
* _N/A_
=> Update cs dependencies

package.json, yarn.lock
* Bumps the version numbers of the yoast javascript packages to the newest versions.
*
*
Fixes #
=> Bumped yoast javascript packages to the newest version.

inc/options/class-wpseo-option.php
* n/a
*
* If the code looks good, please merge it!
Fixes #
=> Add function exists wrapper

readme.txt
=> Improve changelog

package.json, yarn.lock
Bumping the versions of the javascript monorepo packages
=> Bump package dependencies for 12.2-RC

src/integrations/front-end-integration.php, src/presenters/abstract-meta-description-presenter.php, src/presenters/fallback/meta-description-presenter.php, src/presenters/post-type/meta-description-presenter.php
* Changed `Default` to `Fallback`, as `Default` is a [reserved keyword](https://www.php.net/manual/en/reserved.keywords.php).
* Implemented the `Fallback` presenter for meta description.
* Moved the `wpseo_metadesc` filter to the abstract class as it needs to run in every instance.
=> Change Default to Fallback, implement fallback presenter

admin/tracking/class-tracking-plugin-data.php, admin/tracking/class-tracking-settings-data.php, admin/tracking/class-tracking.php
* Adds a tracking class for sending anonimized settings + changes output format for plugins to a object instead of array.
*
*
Fixes #
=> Add anonimized settings tracking class

src/helpers/current-page-helper.php, src/integrations/front-end-integration.php, src/repositories/indexable-repository.php
Expands the `Current_Page_Helper` with logic to determine the page type.
And uses this logic in the `Indexable_Repository` to return the correct indexable for terms.
=> Find indexables for terms when on a term archive

admin/class-admin.php, admin/tracking/class-tracking-plugin-data.php, admin/tracking/class-tracking-settings-data.php, admin/tracking/class-tracking.php
Now also on the release branch...
=> Fix tracking

frontend/class-frontend.php
* Add default robots meta settings to opt in to all snippet display features, to prevent affected websites in Europe from having snippet display issues.
=> robots meta fix

package.json, yarn.lock
* [non-user-facing] Updates monorepo packages dependencies for 12.2.
*
*
Fixes #
=> Bump packages for 12.2

package.json, yarn.lock
* [non-user-facing] Updates package dependencies for 12.3 RC.
*
*
Fixes #
=> Bump packages for RCs 12.3

src/helpers/post-type-helper.php, src/helpers/user-helper.php, src/presentations/indexable-author-archive-presentation.php, src/presentations/indexable-post-type-presentation.php, tests/helpers/robots-helper-test.php, tests/helpers/user-helper-test.php, tests/presentations/indexable-author-archive-presentation/presentation-instance-builder.php, tests/presentations/indexable-author-archive-presentation/robots-test.php, tests/presentations/indexable-post-type-archive-presentation/robots-test.php, tests/presentations/indexable-post-type-presentation/robots-test.php, tests/presentations/indexable-presentation/robots-test.php, tests/presentations/indexable-term-archive-presentation/robots-test.php
* Adds author archive with robots output to indexables.
* Fixes some codestyle in other robots files.
* Adds a user helper.
1. Create a new user.
1. On their profile page; Make sure the option `Do not allow search engines to show this author's archives in search results.` is not checked. And save if needed.
1. Go to `Search appearance` > `Archives` > `Author archives settings`.
1. Enable author archives.
1. Enable `Show author archives in search results?`.
1. Enable `Show archives for authors without posts in search results?`.
1. Save the options.
1. Go to the author's archives page.
1. Ensure there is no "robots" meta tag.
1. Go to the author profile page; Check the option `Do not …
=> Add author archive with robots

src/presentations/indexable-date-archive-presentation.php, tests/presentations/indexable-date-archive-presentation/presentation-instance-builder.php, tests/presentations/indexable-date-archive-presentation/robots-test.php, tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
* N/A
*
Make sure `SEO` > `Search Appearance` > `Archives` > `Date archives settings` > `Date archives` is set to `Enabled`.
* Set `SEO` > `Search Appearance` > `Archives` > `Date archives settings` > `Show date archives in search results` to `Yes`.
* Visit a date archive page (for example `http://one.wordpress.test/2019/9`).
* Make sure no robots meta tag is present.
* Set `SEO` > `Search Appearance` > `Archives` > `Date archives settings` > `Show date archives in search results` to `No`.
* Visit a date archive page (for example `http://one.wordpress.test/2019/9`).
* Make sure the robots meta tag is set to `noindex,follow`.
Fixes #
=> Added generate_robots for date archives

src/presentations/indexable-home-page-presentation.php
Added a comment to indexable-home-page-integration regarding generate_robots
* N/A
*
* Set `Setting` > `Reading` > `Your homepage displays` to `Your latest posts`.
* The robots meta tag should be determined by the homepage indexable. You could change the robots directives for the homepage in the database to verify this, but these can't be changed within the plugin.
* The only way to set this page to `noindex` is to check `Setting` > `Reading` > `Search Engine Visibility` > `Discourage search engines from indexing this site`. Or use a `replytocom` URL parameter.
* Set `Setting` > `Reading` > `Your homepage displays` to `A static page`.
* The behaviour should be the same for the home …
=> Presentation home page robots

migrations/20191008131020_WpYoastIndexablesAddImageFields.php, src/builders/indexable-post-builder.php, src/helpers/image-helper.php, src/integrations/watchers/indexable-post-watcher.php, src/models/indexable.php, src/repositories/indexable-repository.php, tests/builders/indexable-post-builder-test.php
=> Add image source to indexable

tests/presentations/indexable-presentation/twitter-creator-test.php, tests/presenters/debug/marker-close-presenter-test.php, tests/presenters/debug/marker-open-presenter-test.php
* N/A
*
* See the tests in the build pass.
Fixes #
=> Add missing presentation and presenter tests

composer.json, composer.lock
* Adds `symfony/config` as a dev dependency.
* This dependency was added to prevent an error occurring because the dependency wasn't found. It was added explicitly so composer doesn't throw it away even though it's already a direct dependency of another dev dependency.
*
Fixes #
=> Add symfony config dev dependency

inc/options/class-wpseo-option.php, tests/TestCase.php, tests/inc/options/option-social-test.php
* _N/A_
(well, unless anyone ever reported a bug about this, but chances of that are small as it would only come into play when using UTF-8 URLs in combination with PHP < 5.4)
Follow up on #13420, addressing one additional PHPCompatibility issue.
From the PHP 5.4 changelogs:
> The default character set for htmlspecialchars() and htmlentities() is now UTF-8, instead of ISO-8859-1.
While _most_ of the WP world uses the WP default `utf-8` character encoding, this can be changed, so to be on the safe side, one should always pass the encoding to functions affected by it.
Refs:
* https://www.php.net/manual/en/migration54.other.php
* https://www.php.net/manual/en/function.htmlentities.php#refsect1-function.htmlentities-changelog
* …
=> PHPCompatibility fix: pass encoding to htmlspecialchars() et al functions

admin/views/tabs/social/twitterbox.php
* Inform Twitter users about enabling OpenGraph
*
*
Fixes #13631
=> Change Twitter settings page

migrations/20191011105120_WpYoastIndexablesAddOGImageMetaField.php, src/builders/indexable-post-builder.php, src/generators/og-image-generator.php, src/generators/twitter-image-generator.php, src/helpers/image-helper.php, src/helpers/twitter/image-helper.php, src/models/indexable.php, tests/_mocks/indexable.php, tests/builders/indexable-post-builder-test.php, tests/generators/og-image-generator-test.php, tests/generators/twitter-image-generator-test.php, tests/values/images-tests.php
=> Save the image url when building the indexable.

src/helpers/post-type-helper.php, src/presentations/indexable-post-type-presentation.php, src/presenters/open-graph/description-presenter.php, tests/presentations/indexable-post-type-presentation/og-description-test.php, tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php, tests/presentations/indexable-post-type-presentation/title-test.php, tests/presentations/indexable-post-type-presentation/twitter-description-test.php, tests/presenters/open-graph/description-presenter-test.php
* Adds OpenGraph meta descriptions for post types.
*
* Create a new post and edit:
* Note that in any of these you could add a replacevar (like `%%title%%`) and a shortcode (`[gallery id="123" size="medium"]`). The replacevar should be replaced. And the shortcode should be stripped.
* The content to be something recognizable like `CONTENT`.
* `Social` > `Facebook` > `Facebook Description` to something recognizable like `FACEBOOK`.
* `SEO` > `Edit snippet` > `Meta description` to something recognizable like `META`.
* `Sidebar` > `Settings` > `Excerpt` to something recognizable like `EXCERPT`.
* Save the post and view it.
* Ensure the `og:description` has the content `FACEBOOK`.
* …
=> OG description presenter with post type presentation

src/builders/indexable-post-builder.php, src/helpers/image-helper.php, src/helpers/open-graph/image-helper.php, src/values/images.php, tests/helpers/image-helper-test.php, tests/helpers/open-graph/image-helper-test.php, tests/helpers/twitter/image-helper-test.php
* N/A
* Combined two methods, because they do almost the same.
* Removed a couple of unused methods.
*
Fixes #
=> Organization of image helpers

src/integrations/front-end-integration.php, src/presenters/debug/marker-close-presenter.php, src/presenters/schema-presenter.php
* Use PHP_EOL instead of \n
*
* Compare the meta tag output (incl. schema) between this branch and the feature branch. See no changes.
Fixes #
=> Use PHP_EOL instead of \n

integration-tests/capabilities/test-class-capability-manager-factory.php, integration-tests/capabilities/test-class-capability-manager.php, integration-tests/doubles/class-admin-bar-menu-double.php, integration-tests/doubles/class-admin-editor-specific-replace-vars-double.php, integration-tests/doubles/class-indexable-double.php, integration-tests/doubles/class-indexable-post-provider-double.php, integration-tests/doubles/class-indexable-term-provider-double.php, integration-tests/doubles/class-my-yoast-api-request-double.php, integration-tests/doubles/class-opengraph-image-double.php, integration-tests/doubles/class-post-type-archive-notification-handler-double.php, integration-tests/doubles/class-sitemap-image-parser-double.php, integration-tests/doubles/class-term-indexable-double.php, integration-tests/doubles/class-upgrade-double.php, integration-tests/doubles/class-wpseo-content-images-double.php, integration-tests/doubles/class-wpseo-post-type-sitemap-provider-double.php, integration-tests/doubles/class_indexable_service_double.php
* Add short descriptions and cover tags for capability-manager-factory and capability-manager
=> Add short descriptions and cover tags

integration-tests/admin/links/test-class-link-utils.php, integration-tests/capabilities/test-class-register-capabilities.php, integration-tests/doubles/wpseo-config-field-double.php, integration-tests/doubles/wpseo-configuration-service-mock.php, integration-tests/doubles/wpseo-meta-columns-double.php, integration-tests/doubles/wpseo-onpage-double.php, integration-tests/doubles/wpseo-wp-rest-server-mock.php
* Adds missing doc comments.
* @inheritDoc was replaced with the parent doc comment.
* This PR should have no effect on functionality.
Fixes #
=> Add doc comments

src/integrations/watchers/indexable-date-archive-watcher.php, src/integrations/watchers/indexable-system-page-watcher.php, tests/integrations/watchers/indexable-date-archive-watcher-test.php, tests/integrations/watchers/indexable-system-page-watcher-test.php
* Removes the indexables feature flag.
*
*
Fixes #
=> Remove the last traces of the indexables feature flag

integration-tests/config-ui/components/test-class-factory-post-type.php, integration-tests/config-ui/fields/test-class-config-field-choice.php, integration-tests/config-ui/fields/test-class-config-field.php, integration-tests/config-ui/test-class-configuration-components.php, integration-tests/config-ui/test-class-configuration-endpoint.php, integration-tests/config-ui/test-class-configuration-options-adapter.php, integration-tests/config-ui/test-class-configuration-storage.php, integration-tests/config-ui/test-class-configuration-structure.php, tests/admin/metabox/metabox-editor-test.php, tests/admin/myyoast-proxy-test.php, tests/admin/roles/register-roles-test.php, tests/admin/roles/role-manager-factory-test.php, tests/admin/roles/role-manager-test.php, tests/database/migration-runner-test.php, tests/frontend/schema/mainimage-test.php, tests/frontend/schema/schema-how-to-test.php, tests/frontend/schema/schema-utils-test.php, tests/frontend/schema/schema-webpage-test.php, tests/oauth/client-test.php
=> Add short descriptions to the tests.

migrations/20191021131550_WpYoastRemoveTwitterCardField.php, src/context/meta-tags-context.php, src/presentations/indexable-presentation.php, src/presenters/twitter/card-presenter.php, tests/presentations/indexable-presentation/twitter-card-test.php, tests/presenters/twitter/card-presenter-test.php
* Adds Twitter card
* Removes the indexable field again (through a migration) in favor of adding it to the context.
* The old frontend code includes override-logic for singular posts that contained a gallery shortcode. This is not included anymore (product decision).
* The old frontend code includes sanitize-logic after the filter. This is not included anymore (product decision).
* Set the default card type: `SEO` > `Social` > `Twitter`.
* Go to a post and verify that it has the output `twitter:card` with the content that you entered above.
* Change the setting.
* Verify that it updated.
* You could repeat this for all the page types.
* In the settings you could disable the Twitter …
=> Add Twitter card

integration-tests/sitemaps/test-class-wpseo-sitemaps-renderer.php, integration-tests/sitemaps/test-class-wpseo-sitemaps-router.php, integration-tests/sitemaps/test-class-wpseo-taxonomy-sitemap-provider.php, integration-tests/statistics/test-class-statistics-service.php, integration-tests/taxonomy/test-class-taxonomy-fields.php, integration-tests/taxonomy/test-class-taxonomy-social-fields.php, src/conditionals/admin-conditional.php, src/conditionals/feature-flag-conditional.php, src/database/database-setup.php, src/database/migration-runner.php, src/database/ruckusing-framework.php, src/loggers/logger.php, src/loggers/migration-logger.php, src/orm/yoast-orm-wrapper.php, tests/admin/admin-features-test.php, tests/admin/myyoast-proxy-test.php
=> Adds missing docs

admin/class-yoast-notification-center.php, integration-tests/framework/class-wpseo-unit-test-case.php, integration-tests/inc/test-class-wpseo-upgrade-history.php, integration-tests/notifications/test-class-yoast-notification-center.php, integration-tests/recalculate/test-class-recalculate-posts.php, tests/inc/addon-manager-test.php
=> Improve doc comments

integration-tests/formatter/test-term-metabox-formatter.php, integration-tests/onpage/test-class-ryte-service.php, integration-tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
=> Fix PHPCS doc comments for 3 files

frontend/class-twitter.php, integration-tests/frontend/test-class-twitter.php
* N/A
*
* Make sure the `twitter:description` tag is no longer rendered in the frontend.
Fixes #
=> Removal of Twitter description

package.json, yarn.lock
* Updates package dependencies for 12.4.
*
*
Fixes #
=> Bump package dependencies for 12.4

package.json, yarn.lock
* Bumps the JavaScript monorepo packages for 12.5-RC1.
*
*
Fixes #
=> Bump package dependencies for 12.5-RC1

readme.txt
* Sets the minimum required WordPress version to 5.2, and the minimum PHP version to 5.6.20.
* N/A
* N/A
Fixes #
=> Set tested up to to 5.3, minimum wp to 5.2 and PHP to 5.6.20

integration-tests/formatter/test-post-metabox-formatter.php, integration-tests/frontend/test-class-front-end-page-type.php, integration-tests/frontend/test-class-woocommerce-shop-page.php, integration-tests/sitemaps/test-class-wpseo-sitemap-image-parser.php, integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-validator.php
=> Added various missing short descriptions to test files

admin/class-admin-help-panel.php, admin/menu/class-replacevar-editor.php, admin/onpage/class-ryte-service.php, frontend/class-frontend.php, inc/class-wpseo-image-utils.php, inc/class-wpseo-meta.php, inc/class-wpseo-replace-vars.php, integration-tests/config-ui/components/test-class-factory-post-type.php, integration-tests/config-ui/fields/test-class-config-field.php, integration-tests/config-ui/test-class-configuration-options-adapter.php, integration-tests/doubles/class-sitemap-image-parser-double.php, src/builders/indexable-term-builder.php, tests/admin/roles/role-manager-test.php
* _N/A_
* Wrap some long description lines.
* Alignment of parameter descriptions.
* _N/A_
=> Documentation: minor formatting tweaks

tests/inc/addon-manager-test.php
* _N/A_
The files in the new `tests` directory should use short arrays.
* _N/A_
=> CS: clean up arrays

tests/admin/metabox/metabox-test.php, tests/admin/roles/register-roles-test.php, tests/admin/roles/role-manager-factory-test.php, tests/admin/roles/role-manager-test.php, tests/admin/watchers/indexable-author-watcher-test.php, tests/admin/watchers/indexable-post-watcher-test.php, tests/admin/watchers/indexable-term-watcher-test.php, tests/inc/class-wpseo-image-utils-test.php
* _N/A_
The namespace name should reflect the directory path to the file.
For more information, see Yoast/yoastcs#141
* _N/A_
=> CS/Tests: fix incorrect namespace names

js/src/analysis/data.js, js/src/components/contentAnalysis/ReadabilityAnalysis.js
* Fixes 6 console errors/warnings
* I've fixed some very easy to fix errors.
* I had 13 console errors when loading Gutenberg.
* When this PR is applied I had 7 console errors, with https://github.com/Yoast/javascript/pull/392 only 6.
=> Fix 6 console errors

src/context/meta-tags-context.php, src/integrations/front-end-integration.php, src/presentations/indexable-presentation.php, src/presenters/open-graph/fb-app-id-presenter.php, tests/presentations/indexable-presentation/og-fb-app-id-test.php, tests/presenters/open-graph/fb-app-id-presenter-test.php
* N/A
* I also fixed a few unrelated documentation things.
* In the backend, set a `Facebook App ID` under `SEO` --> `Social` (for example `246554168145`).
* In the frontend, see that the meta tag `fb:app_id` renders the ID.
Fixes #
=> Port FB app ID to new format

frontend/schema/class-schema-context.php, frontend/schema/class-schema-website.php
* Adds a description property to the WebSite node.
*
* Make sure your website has a Tagline: `http://one.wordpress.test/wp-admin/customize.php`
* Navigate to a page in the frontend
* Look at the page source
* Check whether there is no `description` property for the `WebSite` node
* Check whether there now is a `description` property for the `WebSite` node and this description equals the Tagline of the page
* Remove the Tagline 
* Check whether there is no `description` property for the `WebSite` node 
Fixes #13000
=> Add description property to website node

src/helpers/current-page-helper.php, src/presentations/indexable-date-archive-presentation.php, src/presentations/indexable-home-page-presentation.php, src/presentations/indexable-presentation.php, src/presentations/indexable-search-result-page-presentation.php, src/presentations/indexable-static-posts-page-presentation.php, tests/helpers/current-page-helper-test.php, tests/presentations/indexable-date-archive-presentation/og-url-test.php, tests/presentations/indexable-home-page-presentation/og-url-test.php, tests/presentations/indexable-presentation/og-url-test.php, tests/presentations/indexable-search-result-page-presentation/og-url-test.php, tests/presentations/indexable-static-posts-page-presentation/og-url-test.php
=> Added og:url presentation implementations

package.json, yarn.lock
* Updates package dependencies for 12.5.
*
*
Fixes #
=> Bump yoast package dependencies for 12.5 release

package.json, yarn.lock
* Bumps the monorepo packaged for 12.6-RC1
*
*
Fixes #
=> Bumped monrepo packages for 12.6-RC1.

admin/class-admin.php, admin/class-helpscout.php
* Adds a helpscout beacon to the Yoast SEO admin pages.
*
* Go to a Yoast admin page and verify that there is a helpscout beacon.
Fixes #13864
=> Adds a helpscout beacon class

admin/class-helpscout.php
* N/A
*
* Have a product without a subscription and verify it works/
Fixes #13901
=> Adds a check to verify the subscription has a value

admin/class-helpscout.php
* None needed.
Fixes:
```( ! ) Notice: Undefined index: ip in /plugins/wordpress-seo/admin/class-helpscout.php on line 167```
```( ! ) Notice: Undefined index: Hostname in /plugins/wordpress-seo/admin/class-helpscout.php on line 167```
=> Fix notice in helpscout beacon

package.json, yarn.lock
* Bump monorepo package versions
=> Bump package versions

admin/formatter/class-post-metabox-formatter.php, frontend/class-breadcrumbs.php, frontend/class-opengraph.php, frontend/schema/class-schema-article.php, frontend/schema/class-schema-webpage.php, inc/class-wpseo-replace-vars.php, inc/date-helper.php
* Fixes a bug where a non prefixed class has been introduced.
*
*
Fixes #
=> Prefix the date helper class

package.json, yarn.lock
* Bump monorepo packages for 12.7 RC
=> bump monorepo packages for 12.7 rc

webpack/webpack.config.js
* Improves our internal webpack optimization tool
This makes small files actually small in the overview. That makes it easier to come to good conclusions about relative file sizes.
* Run `BUNDLE_ANALYZER=1 yarn start`
* Your default browser opens a ton of tabs with bundle analysis
* You shouldn't see `sockjs-client` in there anymore.
=> Remove webpack-dev-server modules from analysis

css/src/admin-global.scss
* Fixes a bug where it was difficult to dismiss the Black Friday banner.
* Makes sure the target image is centered on the cursor.
* Try to dismiss the banner when approaching the closing `x` from all angles.
* To get the banner back when you've dismissed it, add `?yst_dismiss_bf=0` after `wp-admin/` in the URL bar and hit enter.
Fixes #
=> Make sure target image is centered on cursor

integration-tests/test-class-wpseo-breadcrumbs.php, integration-tests/test-filters.php
* Adds missing `@covers` tags
*
*
Fixes #
=> Fix missing @cover tags

integration-tests/test-class-admin-asset.php
* N/A
* Adds missing `@covers` tags. 
*
Fixes #
=> Add covers tags

admin/class-helpscout.php
=> CS/QA: Helpscout - use `WPSEO_Utils::format_json_encode()`

admin/views/licenses.php
=> CS: clean up whitespace

package.json, yarn.lock
*
*
* Bumps the Javascript packages to the stable versions for the 12.7 release.
Fixes #
=> Bump monorepo packages for 12.7 release

src/generators/schema-generator.php
* N/A - Apply the changes from #13677 to this branch
*
* See #13677 for test instructions.
Fixes #
=> Check for identifier property to override the class name value.

package.json, yarn.lock
* Bumps the Javascript packages dependencies for the 12.8 RC.
*
*
Fixes #
=> Bump package dependencies for 12.8 RC

src/integrations/watchers/indexable-static-home-page-watcher.php, src/repositories/indexable-repository.php, tests/integrations/watchers/indexable-static-home-page-watcher-test.php
* N/A
* Creates a watcher that triggers on the `page_on_front` option.
* Although it's not used, I also fixed the `find_by_url` function in the indexable repository.
* Create 2 pages.
* Set the first to be the static homepage.
* Check in the database that the corresponding indexable has the root URL as a permalink.
* Set the second to be the static homepage.
* Check in the database that the corresponding indexable has the root URL as a permalink, and the indexable of the previous page has been st back to it's original permalink.
* Set the homepage to `Your latest posts`.
* Check that the indexables of both pages have been set back to their original permalinks.
Fixes #13841
=> 13841 update static page indexable

grunt/config/aliases.yaml, package.json, yarn.lock
Make sure `build` keeps working.
* None needed.
* Use `grunt:build`, make sure it still works.
Fixes #
=> Bump plugin grunt tasks

package.json, yarn.lock
* Bumps the JavaScript monorepo packages to the latest RC versions.
*
*
Fixes #
=> Bump monorepo packages for 12.8 rc

admin/class-admin-asset-manager.php
* N/A - Is not released yet
*
* 
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2650
=> Adds jed as dependency

grunt/config/ensure-pre-release-branch.js
* [non-user-facing] Will send a more informative message if the release branch does not exist remotely.
* N/A
* Tested whilst pairing with @andizer 
Fixes #14039
=> More informative error if remote branch does not exist

Gruntfile.js, grunt/config/update-readme.js
* Makes sure the modified changelog gets committed.
*
* Run `grunt update-readme --plugin-version="12.8.1"`
* You'll get a prompt to add a changelog.
* Exit with CTRL + X + save
* After the script has ended, run `git log` and see a commit called `Add changelog`.
* Run `git diff HEAD^ HEAD` to see the content of the above commit. See that it contains the changelog you just added.
* Don't push the branch, otherwise you'll push the changelog change commit ;)
Fixes #14041
=> Commit the modified changelog

admin/tracking/class-tracking-settings-data.php, config/php-codeshift/remove-vendor-prefixing-array-key-visitor.php, config/php-codeshift/remove-vendor-prefixing-comment-visitor.php, config/php-codeshift/remove-vendor-prefixing-visitor.php, inc/health-check.php
* N/A - Add missing short description.
*
*
Fixes #
=> Add missing short descriptions

.env.example, grunt/config/verify-zip-size.js
* N/A
* 
* Have a zip that is too big or lower the number that indicates the size.
* Run `grunt verify-zip-size` to trigger the message
Fixes #14060
=> Send slack message when max size exceeded

package.json, yarn.lock
* Bumps the monorepo packages
*
* Travis should pass
Fixes #
=> Bump monorepo packages

tests/repositories/indexable-repository-test.php
* Changes the namespace from `Yoast\WP\Free` to `Yoast\WP\SEO` in `indexable-repository-test`.
* Namespace change analogous to the changes in this PR: https://github.com/Yoast/wordpress-seo/pull/14157
Fixes #
=> Apply new namespace convention in indexable repository test

integration-tests/admin/links/test-class-link-columns-count.php, integration-tests/admin/links/test-class-link-columns.php, integration-tests/admin/links/test-class-link-content-processor.php, integration-tests/admin/links/test-class-link-extractor.php, integration-tests/admin/links/test-class-link-factory.php, integration-tests/admin/links/test-class-link-internal-lookup.php, integration-tests/admin/links/test-class-link-storage.php, integration-tests/admin/links/test-class-link-watcher.php, integration-tests/admin/links/test-class-link_reindex_dashboard.php, integration-tests/config-ui/test-class-configuration-service.php, integration-tests/inc/options/test-class-wpseo-options-backfill.php, integration-tests/inc/test-class-myyoast-api-request.php, integration-tests/inc/test-class-post-type.php
* N/A - Add missing `@covers` to the tests
=> Add covers to tests

integration-tests/admin/test-class-yoast-network-admin.php
* Removes a test that tests nothing except whether `implents` does what it should do.
* N/A
* N/A
Fixes #
=> Remove tests that doesn't really test anything

admin/class-admin-asset-dev-server-location.php, admin/class-admin-help-panel.php, admin/class-admin-init.php, admin/class-admin-user-profile.php, admin/class-admin.php, admin/class-bulk-editor-list-table.php, admin/class-config.php, admin/class-customizer.php, admin/class-meta-columns.php, admin/class-meta-table-accessible.php, admin/class-primary-term-admin.php, admin/class-social-admin.php, admin/class-yoast-notification-center.php, admin/class-yoast-notification.php, admin/config-ui/factories/class-factory-post-type.php, admin/formatter/class-post-metabox-formatter.php, admin/links/class-link-columns.php, admin/links/class-link-query.php, admin/links/class-link-table-accessible.php, admin/pages/tools.php, wp-seo-main.php
=> Fix Yoda conditions

admin/recalculate/class-recalculate-posts.php, admin/recalculate/class-recalculate-terms.php, admin/recalculate/class-recalculate.php, admin/taxonomy/class-taxonomy.php, admin/views/tabs/metas/paper-content/general/homepage.php, admin/views/tabs/social/facebook.php, config/dependency-injection/custom-loader.php, frontend/schema/class-schema-context.php, frontend/schema/class-schema-website.php, inc/class-post-type.php, inc/class-rewrite.php, inc/class-upgrade-history.php, inc/class-wpseo-meta.php, inc/class-wpseo-replace-vars.php, inc/class-wpseo-utils.php, inc/options/class-wpseo-option-titles.php, inc/options/class-wpseo-options.php, inc/options/class-wpseo-taxonomy-meta.php, inc/sitemaps/class-post-type-sitemap-provider.php, inc/sitemaps/class-sitemap-image-parser.php, inc/sitemaps/class-sitemaps-admin.php, inc/sitemaps/class-sitemaps-cache.php, inc/sitemaps/class-sitemaps-renderer.php, inc/sitemaps/class-sitemaps.php, inc/sitemaps/class-taxonomy-sitemap-provider.php, integration-tests/bootstrap.php, integration-tests/test-class-rewrite.php, src/orm/yoast-model.php, src/watchers/primary-term-watcher.php
* N/A - Flip statements to get rid of Yoda conditions.
=> Stop using yoda conditions

admin/class-admin-init.php, admin/metabox/class-abstract-sectioned-metabox-tab.php, admin/onpage/class-onpage.php
* Revert yoda conditions
* N/A
* N/A
Fixes #
=> Revert yoda conditions

admin/metabox/class-metabox-editor.php, admin/metabox/class-metabox-form-tab.php, admin/metabox/class-metabox-section-additional.php, admin/metabox/class-metabox.php
Fixes 
<details>
<summary>Fixed the following errors, I have</summary>
FILE: admin\metabox\class-metabox-editor.php
--
-----------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------
37 \| ERROR \| Usage of Yoda conditions is not allowed; switch the expression order
-----------------------------------------------------------------------------------
 
 
FILE: admin\metabox\class-metabox-form-tab.php
------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
------------------------------------------------------------------------------------
114 \| ERROR \| Usage of Yoda conditions is not allowed; …
=> Inverted some conditional statements, I have

src/generators/schema-generator.php, tests/generators/schema-generator-test.php
* N/A
*
* Repeat the steps in #14053 
Fixes #14053
=> Added @context variable

src/loader.php
Changes the documented type hint to the minimal type that is actually required: an interface with `get_conditionals()`
* No user-facing changes
* -
* N/A
Fixes N/A
=> Change type Integration to Loadable

admin/capabilities/class-capability-utils.php, tests/admin/capabilities/capability-utils-test.php
* Fixes a bug where 
*
* Tested by QA
* Add this somewhere in your code base and make sure it returns some user roles.
```
add_action( 'admin_init', function() {
print_r( WPSEO_Capability_Utils::get_applicable_users( 'wpseo_manage_options' ) );
exit;
} );
```
Fixes #14187
=> Fixes a bug where memory got exhausted on sites with a lot of users.

src/presentations/indexable-author-archive-presentation.php, src/presentations/indexable-static-home-page-presentation.php, tests/presentations/indexable-author-archive-presentation/og-type-test.php, tests/presentations/indexable-static-home-page-presentation/og-type-test.php
* N/A
*
* Set a page as a static home page.
* Visit the home page.
* Make sure the `og:type` metatag is `website`.
* Visit an author archive.
* Make sure the `og:type` metatag is `website`.
Fixes #14089 
Fixes #14091
=> Fix og type or author archives and static home pages.

src/presentations/indexable-presentation.php, tests/presentations/indexable-post-type-presentation/twitter-image-test.php, tests/presentations/indexable-presentation/twitter-image-test.php
* N/A - Fixes a regression in the indexables
*
* Follow the steps described in #14115
Fixes #14115
=> Stop using og image as twitter image

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php
* _N/A_
* Add missing translators comments
* _N/A_
=> QA/I18n: add missing translators comments

src/builders/indexable-author-builder.php, src/builders/indexable-post-builder.php, src/builders/indexable-term-builder.php, src/database/ruckusing-framework.php, src/helpers/home-url-helper.php, src/oauth/client.php, tests/admin/capabilities/capability-utils-test.php, tests/helpers/author-archive-helper-test.php, tests/inc/options/options-test.php
* _N/A_
- docblocks
- for calls to global functions
- for use of global constants
Includes adding some (class name based) type declarations to method declarations.
* _N/A_
=> CS/QA: clean up namespaced files

admin/class-asset.php, admin/class-bulk-editor-list-table.php, admin/class-export.php, admin/metabox/class-metabox-form-tab.php, admin/onpage/class-onpage.php, frontend/class-frontend.php
=> Docs: use short form types

src/database/migration-runner.php, src/watchers/indexable-author-watcher.php, src/watchers/indexable-post-watcher.php, src/watchers/indexable-term-watcher.php, src/watchers/primary-term-watcher.php
* _N/A_
Consistent class structure:
* class constants first
* properties second
* methods third
* _N/A_
=> QA: properties before methods

package.json, yarn.lock
* Bumps the monorepo packages for the 12.9 release
*
*
Fixes #
=> Bump monorepo packages for the 12.9 release

package.json, yarn.lock
* Bumps the RC packages for 13.0 release
*
*
Fixes #
=> Bump RC packages for 13.0 release

admin/class-admin-init.php, admin/class-customizer.php, admin/class-yoast-form.php, admin/metabox/class-metabox-section-react.php, inc/health-check-page-comments.php, inc/sitemaps/class-sitemap-image-parser.php
* N/A - Fixes the Yoda conditions.
*
*
Fixes #
=> Fix the yoda style

admin/import/plugins/class-import-rankmath.php, frontend/schema/class-schema-article.php, frontend/schema/class-schema-person.php, inc/class-rewrite.php, inc/class-upgrade.php, inc/class-wpseo-primary-term.php, inc/sitemaps/class-sitemaps-cache.php, integration-tests/admin/exceptions/test-file-size-exception.php, integration-tests/admin/links/test-class-link-storage.php, integration-tests/doubles/class-dismissible-notification-double.php, integration-tests/doubles/frontend-double.php, integration-tests/frontend/test-class-wpseo-opengraph-image.php, integration-tests/inc/test-class-wpseo-primary-term.php, integration-tests/inc/test-class-wpseo-upgrade.php, integration-tests/notifications/test-class-yoast-notification-center.php, src/conditionals/indexables-feature-flag-conditional.php, src/watchers/indexable-author-watcher.php, src/watchers/indexable-post-watcher.php, src/watchers/indexable-term-watcher.php, src/watchers/primary-term-watcher.php, tests/admin/capabilities/capability-utils-test.php, tests/admin/myyoast-proxy-test.php
* N/A Fixes doc comments, cover tags and strict comparisons.
*
*
Fixes #
=> Various codestyle fixes

composer.json
The lock file need to be updated.
=> Duplicate directory in Composer autoload

.github/ISSUE_TEMPLATE/Design_implementation.md
* Adds a GitHub issue template for the transfer of designs to the development team.
*
*
Fixes #
=> Add design implementation issue template

src/helpers/post-helper.php, src/helpers/post-type-helper.php, src/presentations/indexable-post-type-presentation.php, tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php, tests/presentations/indexable-post-type-presentation/og-description-test.php, tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php, tests/presentations/indexable-post-type-presentation/twitter-description-test.php, tests/presentations/indexable-static-home-page-presentation/presentation-instance-builder.php, tests/presentations/indexable-static-posts-page-presentation/presentation-instance-builder.php
* N/A - Just moved a couple of helper methods
* I moved these helpers because they are post specific and I believe the post_type helper is not meant for post specific things.
* The change is just about moving code, all spots were tested and these unit tests should still pass 
Is needed to fix https://github.com/Yoast/wpseo-woocommerce/issues/501
=> Create post helper

src/context/meta-tags-context.php, src/generators/schema/author.php, src/generators/schema/person.php, src/generators/schema/webpage.php, src/helpers/site-helper.php, tests/_mocks/author.php, tests/context/meta-tags-context-test.php, tests/generators/schema/author-test.php, tests/generators/schema/person.php
* Fixes a bug where the `WebPage` Schema node was not double typed as a `ProfilePage` node on author archives.
* Fixes a bug where no Schema node for authors were shown on author archive pages.
* Fixes a bug where the `WebPage` Schema node was output on 404-pages. 
*
* Checkout the `feature/indexable-frontend` branch.
* Go to an author archive page (e.g. http://basic.wordpress.test/author/admin/).
* Check the Schema that is output in the source code.
* It should **not** contain a node with an `@type` property of `[ 'WebPage', 'ProfilePage' ]`.
* Its `Person` node should **not** have a `mainEntityOfPage` property.
* Go to a non-existing page (e.g. …
=> Fixes Schema on author archives and 404-pages

package.json, yarn.lock
* Bumps the monorepo packages for the 13.1 release.
*
*
Fixes #
=> Bump monorepo packages for 13.1

src/builders/indexable-home-page-builder.php, src/builders/indexable-post-builder.php, src/builders/indexable-social-image-trait.php, src/helpers/open-graph/image-helper.php, src/values/open-graph/images.php, tests/builders/indexable-home-page-builder-test.php, tests/helpers/open-graph/image-helper-test.php, tests/values/images-tests.php, tests/values/open-graph/images-test.php
* Fixes a bug where `og:image:width` and `og:image:height` were not saved and output for the homepage. 
* I renamed `get_image_url_by_id` to `get_image_by_id`, since it retrieved and returned the image data entirely instead of only the URL.
* Add a front page image in de YoastSEO settings (e.g. on  http://basic.wordpress.test/wp-admin/admin.php?page=wpseo_social#top#facebook)
* Go to the homepage.
* Check that these two meta tags are output (with the correct image width and heigh):
```html
<meta property="og:image:width" content="width_of_image">
<meta property="og:image:height" content="height_of_image">
```
Fixes #14288
=> `og:image:width`  and `og:image:height` are now output on the homepage

src/generators/schema/article.php, src/generators/schema/webpage.php, tests/generators/schema/article-test.php
* Adds a `potentialAction` entity to the `WebPage` and `Article` Schema pieces.
* This PR ports the changes from #14012 to the `feature/indexables-frontend`, with the necessary adjustments.
As per the original issue requirements:
> - the `potentialAction` piece is intentionally an array (to support multiple potential actions).
> - The `target` value is also intentionally an array (for extensibility purposes).
* Please follow the test instructions from https://github.com/Yoast/wordpress-seo/pull/14341
Fixes https://github.com/Yoast/wordpress-seo/issues/14348
=> Port 14012 to the Indexables branch.

inc/class-wpseo-utils.php
Pull request #14176 get merged because of #14180 that contains a commit that belongs to #14176. Unfortunately a revert #14180 cause the code not in being in the code base. This pull request has a cherry pick of the commit we want. 
@stodorovic Can you confirm this code is still needed?
* Prevents additional sanitation if the URL is already properly encoded. Props to [stodorovic](https://github.com/stodorovic).
* Temporarily remove reserved characters from the value (which are the delimiters between pieces of URI), then [encode](https://www.php.net/manual/en/function.rawurlencode.php)/[decode](https://www.php.net/manual/en/function.rawurldecode.php) this stripped value and check for differences. If it's same then apply only …
=> Don't sanitize  properly encoded URL

admin/config-ui/class-configuration-page.php, inc/class-rewrite.php, inc/sitemaps/class-sitemaps-router.php
Quick CS fix where wp_redirect is changed to wp_safe_redirect
* N/A
* N/A
*
Fixes #
=> Class configuration page cscleanup

package.json, yarn.lock
* Bumps the monorepo packages for 13.3-RC1.
* Bumps the monorepo packages for 13.3-RC1.
*
*
Fixes #
=> Bump monorepo packages for 13.3-RC1

src/helpers/blocks-helper.php, src/helpers/current-page-helper.php, src/helpers/date-helper.php, src/helpers/image-helper.php, src/helpers/meta-helper.php, src/helpers/options-helper.php, src/helpers/post-helper.php, src/helpers/post-type-helper.php, src/helpers/product-helper.php, src/helpers/redirect-helper.php, src/helpers/site-helper.php, src/helpers/string-helper.php, src/helpers/taxonomy-helper.php, src/helpers/url-helper.php, src/helpers/user-helper.php, tests/helpers/blocks-helper-test.php, tests/helpers/current-page-helper-test.php, tests/helpers/home-url-helper-test.php, tests/helpers/options-helper-test.php, tests/helpers/post-helper-test.php, tests/helpers/product-helper-test.php, tests/helpers/taxonomy-helper-test.php, tests/helpers/url-helper-test.php
* N/A - Just adding unit tests
* Some code is extracted to methods just to make testing easier
* The article-post-type-helper isn't tested because it has been moved to the schema directory where test are already written: see #14436 
* Tests for the image helpers is written in #14436 
* Some oneliners are converted to separate if-statements to make sure every scenario is tests.
*
Fixes #
=> Add tests for helpers

admin/metabox/class-metabox.php
* Allow percent-encoding in canonical field.
* Use sanitize_url instead of sanitize_text_field for canonical field.
* Try to save encoded URL as canonical (eg. _https&#58;//domain&#46;com/**%da%af%d8%b1%d9%88%d9%87-%d8%aa%d9%84%da%af%d8%b1%d8%a7%d9%85-%d8%b3%d8%a6%d9%88/**_ )
~~* [ ] I have written documentation for this change.~~
Fixes #14476.
=> Use sanitize_url to sanitize canonical field

integration-tests/test-class-wpseo-metabox.php, integration-tests/test-class-wpseo-utils.php, js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap, js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
* The fix for #14476 isn't covered in unit-test. This pull adds tests for the fix.
* N/A - It just adds unit tests.
* 
* There is no functional change, if the tests are passing, just merge it!
Fixes #14485
=> Add unit tests

package.json, yarn.lock
* We should not use feature branches in the RC
* Fixes a bug where the `@yoast/analysis-report`, `@yoast/components` and `@yoast/configuration-wizard` packages were incorrectly set to a feature release.
*
* Go to create new post.
* Click to open Insights box.
* Verify there is no exception on the page (see issue).
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2716
=> Fix bump versions PR versions

inc/class-wpseo-utils.php
* Related PR #14502.
* Require absolute path in the URL. If scheme/host doesn't exist and path isn't valid then return empty string.
*
*
Fixes #7664.
=> Little fixes for method sanitize_url

integration-tests/test-class-wpseo-utils.php
* This PR adds tests for #14502.
* N/A - It just adds unit tests.
*
*
Fixes #
=> Add more tests for method sanitize

tests/generators/schema/main-image-test.php
* We want full test coverage.
* Adds tests to fully cover the generators' schema main image.
*
* Check that the coverage is indeed 100%.
* Check that the tests pass.
Fixes #
=> Full test coverage for main image

src/generators/breadcrumbs-generator.php, tests/generators/breadcrumbs-generator-test.php
* Tests are missing!
* N/A - Write missing unittests for the breadcrumbs generator
*
* Press merge when Travis is happy
Fixes #
=> Adds unit tests for the breadcrumbs generator.

tests/generators/open-graph-locale-generator-test.php
* Not all code is covered by unit tests. We wanted to have this covered.
* N/A - This pull adds tests.
*
* Travis has to be happy!
Fixes #
=> Add tests for the Open_Graph_Locale_Generator

tests/_mocks/meta-tags-context.php, tests/generators/schema-generator-test.php
* We want to have full test coverage.
* N/A - It just adds tests
* I removed some variables from the meta-tags-context class which are already defined in the context class itself. 
* It only adds test
Fixes #
=> Added additional test for the schema generator.

package.json, yarn.lock
*
* Bumps the monorepo packages in preparation for 13.4-RC1.
*
*
Fixes #
=> Bump monorepo packages for 13.4-RC1

.travis.yml
* We want to test feature branches on staging with the latest monorepo changes, either from `develop` or from a similarly named feature branch on the monorepo.
* To do this we need to link the monorepo when automatically deploying a feature branch to yoast-dist.
* N/A (tooling): Links the monorepo when a feature branch is deployed to yoast-dist.
* I cherry picked the commits that were already present on `feature/internal-linking-phase-2` feature branch.
* See also: https://github.com/Yoast/wordpress-seo/issues/14329#issuecomment-585787505
* 
Fixes #14329
=> Link monorepo when deploying feature branches to yoast-dist

src/integrations/third-party/woocommerce.php, tests/integrations/third-party/woocommerce-test.php
* The fallback didn't correspondent with the one used at the moment. This results in unexpected titles and descriptions
* N/A Fixes a bug where the wrong title and meta description are rendered for a shop page that is based on a singular page in Woocommerce.
* Originally we used the product archive fallback for the shop page. This was discussed earlier, but I can't find the reason why we did it. Now it's decided to move back to the original one. The shop page is a kind of hybrid between a singular and an archive page.
* Install WooCommerce.
* Make sure you have set a page as the shop page. 
* Under: Woocommerce - Settings - Products
* On trunk open the shop page and see the title
* …
=> Use proper fallback for the Woocommerce shop page

package.json, yarn.lock
*
* Bumps the monorepo packages for 13.4.
*
*
Fixes #
=> Bump monorepo packages for 13.4

src/main.php, src/surfaces/helpers-surface.php, src/surfaces/open-graph-helpers-surface.php, src/surfaces/schema-helpers-surface.php, src/surfaces/twitter-helpers-surface.php
* Adds helpers that can be access via `YoastSEO()->helpers->{helper_name}`. For example, `YoastSEO()->helpers->image` gets you an instance of the `Image_Helper`.
* This also works for the nested namespaces so `YoastSEO()->helpers->schema->image` gets you the `Schema\Image_Helper` class.
* N/A
* This makes all our helper classes part of our published API that we'll need to keep backwards compatible.
* Enter `wp shell`, in the docker this can be done with `./wp.sh shell`.
* Call a helper of your choice using `YoastSEO()->helpers`.
* The functions on that helper should work as they currently do.
=> Add helpers surface to easily access helpers externally

src/loggers/database-logger.php
* This should prevent log output on non text/html requests.
Fixes #14651
=> Fix logging for non text/html requests

deprecated/frontend/schema/class-schema-article.php, deprecated/frontend/schema/class-schema-author.php, deprecated/frontend/schema/class-schema-breadcrumb.php, deprecated/frontend/schema/class-schema-faq-question-list.php, deprecated/frontend/schema/class-schema-faq-questions.php, deprecated/frontend/schema/class-schema-faq.php, deprecated/frontend/schema/class-schema-howto.php, deprecated/frontend/schema/class-schema-ids.php, deprecated/frontend/schema/class-schema-image.php, deprecated/frontend/schema/class-schema-main-image.php, deprecated/frontend/schema/class-schema-organization.php, deprecated/frontend/schema/class-schema-person.php, deprecated/frontend/schema/class-schema-utils.php, deprecated/frontend/schema/class-schema-webpage.php, deprecated/frontend/schema/class-schema-website.php, deprecated/frontend/schema/class-schema.php, deprecated/frontend/schema/interface-wpseo-graph-piece.php
* Fixes deprecated schema pieces to be inline with the latest schema changes.
* Adds version numbers to the schema piece deprecation.
* N/A
* The deprecated schema pieces should work as they did previously.
=> Fix deprecated schema pieces

src/config/schema-ids.php, src/context/meta-tags-context.php, src/generators/schema/article.php, src/generators/schema/author.php, src/generators/schema/breadcrumb.php, src/generators/schema/main-image.php, src/generators/schema/organization.php, src/generators/schema/person.php, src/generators/schema/webpage.php, src/generators/schema/website.php, src/helpers/schema/id-helper.php, tests/generators/schema/main-image-test.php, tests/generators/schema/organization-test.php
* We renamed `WPSEO_Schema_IDs` to `Schema_Ids`, uppercasing the last d for consistency in this pull.
* None needed.
=> rename Schema_Ids to Schema_IDs

readme.txt
* Set minimum WP version to 5.3
*
*
*
Fixes #
=> Set minimum WP version to 5.3

tests/context/meta-tags-context-test.php, tests/generators/schema/author-test.php, tests/generators/schema/person-test.php
=> CS: type casts should always be lowercase

admin/class-admin-asset-manager.php, src/initializers/migration-runner.php, src/integrations/watchers/indexable-author-watcher.php, src/integrations/watchers/indexable-date-archive-watcher.php, src/integrations/watchers/indexable-home-page-watcher.php, src/integrations/watchers/indexable-post-type-archive-watcher.php, src/integrations/watchers/indexable-post-watcher.php, src/integrations/watchers/indexable-static-home-page-watcher.php, src/integrations/watchers/indexable-system-page-watcher.php, src/integrations/watchers/indexable-term-watcher.php, src/presentations/indexable-static-posts-page-presentation.php
Classes should be ordered as follows:
* First any trait `use` statements.
* Next class constant declarations.
* Then class property declarations.
* Followed by all method declarations.
* _N/A_
=> CS: fix class ordering
