Yoast/wordpress-seo

inc/options/class-wpseo-option-wpseo.php, src/integrations/admin/old-premium-integration.php, tests/unit/integrations/admin/old-premium-integration-test.php
* We want to display a notification urging to upgrade Premium if it's active and its version is < 20.0 because some settings might be missing from the new UI.
* Displays a notification urging to upgrade Premium if the version is below 20.0, since some settings might be missing from the new user interface.
* The notification is displayed only to users with the `wpseo_manage_options` capability, since other users cannot see the settings.
* Includes a unit test with 100% line coverage.
* Install together  with Premium < 20.0-RC1
* See that on any admin page you can see a notification such as:
* switch to a different user role and check if you can still see the notification: …
=> Settings UI: Introduce a notification urging for upgrade Premium if < 20.0

packages/js/src/settings/routes/site-representation.js
*
* Updates the Twitter field label for Person in the new Settings UI
* visit the new Settings UI under "Site representation"
* set "Person"
* Check that the Twitter field has just "Twitter" as label, instead of the former "Twitter username (without the @)"
* Switch to Organization and see the label is the same, so it's consistent.
*
*
Fixes [DUPP-863]
[DUPP-863]: https://yoast.atlassian.net/browse/DUPP-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Twitter field label in the Person social URLs

inc/options/class-wpseo-option-wpseo.php, packages/js/src/settings/hooks/use-disabled-message.js, packages/js/src/settings/routes/site-features.js, src/helpers/language-helper.php, src/integrations/settings-integration.php, tests/unit/integrations/settings-integration-test.php
* Changed link to the correct link https://yoa.st/inclusive-language-features-free in `Inclusive language analysis` feature.
* Feature available for Free users. No upsell or premium badge.
* Feature is disabled for non-english sites.
* Changes link for the Inclusive Language post to the correct link.
* Removes Premium/Upsell badges for the Inclusive Language setting.
* Disables the Inclusive Language setting for non-english sites.
* Added a function to the `Language_Helper` class which is a wrapper to the function `WPSEO_Language_Utils::get_language( \get_locale() )`.
* Added the `hasInclusiveLanguageSupport` to the global `window.wpseo.ScriptData`. 
* Go to `Settings` -> …
=> Settings-UI: DUPP-864-settings-ui-inclusive-language-issues

packages/js/src/settings/app.js, packages/js/src/settings/components/search.js, packages/js/src/settings/initialize.js
* Disable WordPress `skip links` for `Skip to content` and `Skip to toolbar` to prevent adding hash to url, which results in an empty tab in settings UI.
* Repurpose `Skip to content` link to focus on search button in the settings UI menu.
* Reset `Skip to toolbar` to focus on toolbar without adding hash to url.
* Disable WordPress `skip links` for `Skip to content` and `Skip to toolbar` to prevent adding hash to url, which results in an empty tab in settings UI.
* Repurpose `Skip to content` link to focus on search button in the settings UI menu.
* Reset `Skip to toolbar` to focus on toolbar without adding hash to url.
* Added ID to the search button for targeting.
* Go …
=> DUPP-865-settings-ui-catch-a-11-y-skip-to-links-before-they-break-hash-routing

packages/yoastseo/CHANGELOG.md, packages/yoastseo/package.json
Fixes 
* https://github.com/Yoast/wordpress-seo/issues/19359
* [yoastseo] Fixes a bug where an invalid browser field in package.json would cause Vite to throw an error when building. Props to [peeke](https://github.com/peeke).
* `browser.js` was removed in a previous commit, so the package.json entry no longer has any function.
*
*
*
Fixes #
=> Remove browser field from package.json (packages/yoastseo)

packages/js/src/settings/helpers/search.js, packages/js/src/settings/routes/crawl-optimization.js
* Add missing crawl optimization toggle.
* Fixes an unreleased bug where the crawl optimization in the settings would miss the `Redirect pretty URLs to ‘raw’ formats` toggle. 
*
* Enable Premium, latest 20.0 (at the time of writing RC2)
* Go to Settings
* Search for `redirect`.
* Verify:
* search suggests `Redirect pretty URLs to ‘raw’ formats`
* going there puts focus on: Settings  > Advanced > Crawl optimization > Internal site search cleanup > Redirect pretty URLs to ‘raw’ formats
* Verify the `Redirect pretty URLs to ‘raw’ formats` toggle:
* has the same text as the original issue https://yoast.atlassian.net/browse/PC-390
* looks like (screenshot of implementation): …
=> Settings: Add redirect search pretty URLs

packages/ui-library/src/elements/table/index.js
*
* [@yoast/ui-library] Removes the no wrap style from the `Table.Cell`.
* Fixes an unreleased bug where the RSS table description would not be fully visible.
*
* Go to Settings > Advanced > RSS
* Verify the table descriptions are now visible / wrapping on a new line
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/292
=> UI library: remove no wrap from the table cell

packages/yoastseo/src/languageProcessing/languages/pt/config/transitionWords.js
* We have received user feedback on [missing transition words for Portuguese](https://wordpress.org/support/topic/transition-words/). After reviewing the suggestions (as a native speaker of Portuguese), there are a few which are common enough to be worth adding.
* Improves the  _transition words_ assessment for Portuguese by adding new transition words.
* [shopify-seo] Improves the  _transition words_ assessment for Portuguese by adding new transition words.
* Words added include: `atualmente, ocasionalmente, apesar disso, juntamente com`
* There was an odd entry with `finalmente agora atualmente`. This was corrected to `finalmente`
* Since many of the user suggestions involve ambiguous words (i.e., not always used as transition …
=> Expands list of transition words for Portuguese

packages/js/src/settings/components/search.js
* Improve searching in other locales.
* Fixes an unreleased bug where certain terms would not be searchable in certain locales due to the minimum length of the query.
* Mapping user locale to minimum query lengths to gain more precision.
* Verify the user language is set to site default.
* Switch the site language to Japanese and download the translations.
* Go to the Settings > Content types > Posts (to help with languages: `https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_page_settings#/post-type/posts`)
* Copy the translation of `Posts`, i.e. the title of the page. In Japanese this is `設定`.
* Search for that term
* Verify you get results (where before this …
=> Settings UI: Change minimum query characters depending on the user locale

packages/js/src/settings/app.js
* Adds aria-label to Yoast logo link in `settings UI` with different label for premium.
* Adds focus style to logo's link
* Improves the accessibility of the `Yoast SEO` logo in settings.
* 
* Open `YoastSeo`-> `settings`
* Click on tab key and see if focus is on logo
* Turn off premium and inspect page and check if logo has aria-label and if it is "Yoast SEO".
* Turn on Premium and inspect page and check if logo has aria-label and if it is "Yoast SEO Premium".
* Inspect logo's link and check if it has `aria-label` prop.
* Open in Safari, enable voiceover (cmd+f5) and verify the label gets read.
* …
=> Add ariaLabel to logo and focus style

packages/js/src/settings/components/form-layout.js, packages/js/src/settings/components/introduction.js, packages/js/src/settings/components/search.js, packages/ui-library/src/components/modal/index.js, packages/ui-library/src/components/modal/stories.js, packages/ui-library/src/elements/title/index.js, packages/ui-library/src/elements/title/style.css
* Changes `Modal.Title` tag from `h3` to default `h1`.
* Adds `aria-labelledby` support to `Modal` with `Modal.Title` component in `ui-library`.
* Updates `Modal.Title` in `Discard changes`, 
* Adds `aria-label` to `Indroduction` and `Search` modals.
* Improves modal title accessibility in the `Discard changes`,`Search` and `Introduction` modals.
* Replaces the `Modal.Title` from `Title` (from the `ui-library`) to `Dialog.Title` (from `headless-ui`) to automatically add `aria-labelledby` tag to modal.
* `Modal.Title` component in `ui-library` now has:
* `yst-title` class by default.
* `size` support as `Title` Element.
* `ref` support as in the original component `Dialog.Title`.
* Default `as` is `h1`
* Adding documentation in …
=> DUPP-884-improve-the-discard-all-changes-dialog-a-11-y

css/src/admin-global.css, css/src/new-settings.css, packages/js/src/indexables-page/components/suggested-links-modal.js, packages/js/src/integrations-page/algolia-integration.js, packages/js/src/integrations-page/simple-integration.js, packages/js/src/integrations-page/toggleable-integration.js, packages/js/src/settings/app.js, packages/js/src/settings/components/sidebar-recommendations.js, packages/js/src/settings/routes/site-features.js
* Fixes arrows direction on `rtl` languages in settings ui and integrations.
* Fixes a bug where arrows in settings ui and integration would point to the right when site language direction is `rtl`.
* Added class `yst-icon-rtl` to the `admin-global.css` so it would be applied in the settings ui and the integration page.
* Change site language to one of the `rtl` languages.
* Turn off `Premium`
* Open `Yoast SEO`->`Settings`->`Site features`
* Check the arrow next to `Learn more` is pointing to the left.
* On the sidebar check the recommendation to get premium has arrow that is pointing to the left.
* On the bottom check the recommendation to get premium has arrow that is …
=> Settings UI: mirror arrows in rtl language #295

css/src/new-settings.css, packages/js/package.json, packages/js/src/settings/app.js, packages/js/src/settings/components/search.js, packages/js/src/settings/components/sidebar-navigation.js, packages/js/src/settings/initialize.js, packages/ui-library/package.json, packages/ui-library/src/components/notifications/style.css, packages/ui-library/src/components/sidebar-navigation/index.js, packages/ui-library/src/components/sidebar-navigation/mobile.js, packages/ui-library/src/components/sidebar-navigation/stories.js, packages/ui-library/src/components/sidebar-navigation/submenu-item.js, packages/ui-library/src/index.js, yarn.lock
* Strife to be compatible with a mobile viewport.
* Fixes an unreleased bug where the Settings notifications where would not appear next to the WordPress menu on mobile.
* Fixes an unreleased bug where opening the WordPress menu on mobile would push our content a bit too far to the right.
* Fixes an unreleased bug where the (Settings) notifications could be wider than the screen.
* Fixes an unreleased bug where the mobile menu would not close when navigating to the same page or when going to a search result on the same page.
* Fixes an unreleased bug where the Show more/less icon in the Settings menu would be bigger than designed.
*
* Go to Settings > Site representation …
=> Settings UI: Mobile view: Fix detected mobile view issues

css/src/yst_plugin_tools.css, packages/js/src/settings/components/sidebar-recommendations.js, src/presenters/admin/sidebar-presenter.php
* Fixes `Get Yoast SEO Premium` formatting to be optimal for all languages.
* Fixes `Get Yoast SEO Premium` formatting to be optimal for all languages.
* 
* Turn off premium plugin
* Open `Yoast SEO` -> `General` 
* Check sidebar title `Get Yoast SEO Premium` is centered and `Get` and `Yoast SEO Premium` are in separate lines and centered.
* Open `Yoast SEO` -> `Settings` 
* Check sidebar title `Get Yoast SEO Premium` is centered and `Get` and `Yoast SEO Premium` are in separate lines and centered.
*
*
Fixes [Trivial: "Get Yoast SEO Premium" …
=> #301 get premium title formating

packages/js/src/settings/routes/media-pages.js
*
* Improves the description of the Media page settings' `Enable media pages` toggle.
*
* Go to Settings > Advanced > Media pages
* Verify the copy of the `Enable media pages` toggle now is:
> We recommend keeping media pages disabled. This will cause all attachment URLs to be redirected to the media itself.
*
* Only the copy of that specific toggle in the settings.
Fixes https://github.com/Yoast/plugins-automated-testing/issues/315
=> Settings UI: change description of the media pages toggle

packages/js/src/settings/initialize.js
*  Enforces a minimum height on the WP content that is the height of the WP menu. This prevents it from going into the fixed mode.
*  Enforces a minimum height on the WP content that is the height of the WP menu. This prevents it from going into the fixed mode.
* 
- Set a tall WP menu: you can do this by adding custom post types (via plugin Custom Post Type UI). 
- Set the WP homepage to static pages (to get the Homepage settings to be less tall)
- Switched to Firefox because that seemed to more easily reproduce it than Chrome.
- Go to another page than `Yoast SEO`-> `Settings`-> `Content types`->`Homepage`
- Scroll a tiny bit to trigger WP making the WP menu fixed
- …
=> settings-ui: fix WP content height to match WP menu

packages/js/src/settings/components/introduction.js
* Fixes copy for introduction modal.
* Changes introduction description width.
* Fixes copy for the Settings' introduction modal.
* Changes the Settings' introduction description width.
*
* Login as a new user to have the introduction modal enabled. 
* Open `YoastSEO`->`Settings`
* The modal should open.
* Check if the text in each matches:
Step 1. Title: `Welcome to your new Yoast SEO settings!`  Subtext: `There's a fresh new look, and it's easier than ever to find and manage your site's SEO options.`.
Step 2: Title: `We’ve moved some things around!` Subtex: `Now it’s much easier to find the most important settings, or to dive straight into our advanced options.`
Step 3. …
=> settings-ui: 341 update intro modal copy

packages/js/src/settings/app.js, packages/js/src/settings/components/formik-media-select-field.js, packages/js/src/settings/components/sidebar-recommendations.js, packages/js/src/settings/routes/site-features.js, packages/ui-library/src/components/root/style.css, packages/ui-library/src/components/sidebar-navigation/submenu-item.js, packages/ui-library/src/elements/button/style.css, packages/ui-library/src/elements/link/style.css, packages/ui-library/src/elements/tag-input/index.js, packages/ui-library/src/elements/validation/style.css
* Make sure all links do have a (clear) focus style
* Improves the link focus styles in the first time configuration.
* Fixes an unreleased bug where the focus styles of links in the Settings where non-existent or incorrect.
* [@yoast/ui-library] Improves the focus style of anchors by making it more pronounced. This affects: all anchors within the `yst-root` and `yst-validation-message` classes as well as the `Link` and `SidebarNavigation.SubmenuItem` components. And lastly, the `Button` element, if rendered `as` an anchor.
* [@yoast/ui-library] Removes the `TagInput`' _tabindex_ override.
*
* Enable Premium
* Go to the Settings
* Check the style and specifically the …
=> 19436 make sure all links do have a focus style

packages/js/src/settings/components/search.js, packages/ui-library/src/elements/title/index.js, packages/ui-library/src/elements/title/style.css
* We wanted to align our styling with the tailwind ui component.
* Reduces the font size of the group header in the search results.
*
* Open the new settings
* Click Quick Search... field/button
* Type in a search term like `open` for example.
* You can see the search results with group categories and clickable search results.
* The group category text should be `xs` so .75rem and the font-weight should be semibold `600`.
*
*
Fixes #
[Minor: [Search functionality] Fix the font styles in the search results …
=> Minor: [Search functionality] Fix the font styles in the search results box.

packages/js/src/settings/helpers/validation.js, packages/js/src/settings/routes/crawl-optimization.js
* Adds validation to the `Max number of characters to allow in searches` field.
* Adds validation to the `Max number of characters to allow in searches` field and description of limitation.
*
* Open `YoastSEO`->`Settings`->`Advanced`->`Crawl optimization`
* Go to `Internal site search cleanup`.
* Turn on `Filter search terms`.
* The input that is now enabled should only accept numbers. Check it doesn't accept letters.
* Check is has "Please enter a number between 1 and 50." in the field description.
* Try to insert number greater than 50 or smaller than 1. 
* Check you are getting an error message under input field "The number you've entered is not between 1 and 50."
* …
=> settings ui: 344 minor missing validation in max number of characters to allow in searches

packages/js/src/settings/helpers/validation.js
* We wanted to remove the required validation rule for other social profiles to improve UX.
* Removes the required validation rule for the other social profiles field in the new settings ui.
* N/A
* Open [wordpress.test/wp-admin/admin.php?page=wpseo_page_settings#/site-representation](https://wordpress.test/wp-admin/admin.php?page=wpseo_page_settings#/site-representation)
* Make sure you have selected Organization.
* Scroll down to the social profiles
* Click the `Add another profile` button
* Click Save changes -> The page should now save as normal
* Add just text (not an actual link) and make sure the URL validation still triggers
* Add a valid url for example …
=> Settings: remove required validation rule for other social profiles

packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js, packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js, packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js, packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
* There was a bug in the sentence tokenizer that a closing break tag (`</br>`) was not sanitized. This lead to problems with marking in the classic editor when a text was copied from a third party source (word or other text editors). This would introduce closing break tags. If such break tags were present in a sentence, words in this sentence could not be marked.
* Fixes a bug where self-closing break tags (`</br>`) would not be removed when analyzing content.
* There is still a bug present that a break tag is seen as a sentence delimiter, which is not necessarily true. But for now, this does not lead to visible problems, so a separate issue will be made for this.
* While this PR does touch code that is used in Shopify, it's …
=> Recognize self-closing break tags (</br>)

packages/js/src/settings/components/formik-tag-field.js, packages/ui-library/src/elements/tag-input/index.js, packages/ui-library/src/elements/tag-input/stories.js
* We wanted an easy way to clear an tag input field mostly for automated tests
* Adds the ability to clear a tag input field by using the `ctrl + backspace` keyboard shortcut.
* We decided to go for a combination shortcut, because tripple clicking was technically really complex because the tag field is not just 1 input field it is a combination of inputs. We also did not go for an UI element because all the best places for a X marker are already occupied by validation states.
* Make sure premium is enabled and the new ui library is also build ( can be done with `grunt build:dev`) This is already done in the RC.
* Browse to …
=> Make an ability to clear tags.

packages/js/src/settings/components/form-layout.js, packages/js/src/settings/components/introduction.js, packages/js/src/settings/components/search.js, packages/js/src/settings/routes/site-features.js, packages/ui-library/src/components/card/index.js, packages/ui-library/src/components/modal/index.js, packages/ui-library/src/components/modal/stories.js, packages/ui-library/src/components/toggle-field/index.js, packages/ui-library/src/elements/link/stories.js, packages/ui-library/src/elements/title/index.js, packages/ui-library/src/elements/title/style.css
* Improves accessibility for feature card in `Site features`:
* Adds screen reader support for `Learn more` 
* Adds screen reader support for `Enable feature`    
*  Adds empty alt for feature Image
* Improves accessibility for `Introduction` modal
* Improves accessibility for `Search` modal
*  Improves accessibility for `Discard changes` modal
* Improves accessibility for `Learn more` links and `Enable feature` switches on page `Site features`
* Improves accessibility for features' images.
* Added `aria-label` support for `label` in `ToggleField` component in `Ui library`
* Refactored title in to the `FeatureCard` component
* Refactor `LearnMore` component to accept the title in an `ariaLabel` prop and adds text to it: `Learn …
=> settings ui 19521 improve the feature cards accessibility

packages/js/src/settings/app.js, packages/js/src/settings/components/sidebar-recommendations.js
* Alternate approach to the solution of https://github.com/Yoast/plugins-automated-testing/issues/301
* Improves the sidebar upsell in the settings when viewed in languages that do _not_ need a line break.
* Tweaked the sidebar upsell in the settings styling: logo up a bit more, title is no longer center aligned and the button now has the default horizontal spacing.
* Change the translation to incorporate the tags around _Get_
* Add `white-space: nowrap` around both _Get_ to ensure there can only be a linebreak in there. This happened in Japanese
* The wrapper span in the button is because of the gap, otherwise it would put the gap between _Get_ and _Yoast SEO Premium_ too …
=> 19598 minor update upsell title design in settings

src/helpers/wincher-helper.php
* Fix some links to be shortlinks
* In the Yoast metabox, `Track SEO Performance` collapsible, check that URL of the page opened by the link highlighted in the following picture contains the parameters `referer=yoast&partner=yoast#utm_medium=plugin&utm_source=yoast`
* Track the number of keywords needed to reach the limit for your aubscription plan (5 keywords for free plans)
* Check that the URL of the page opened by clicking on the `upgrade your Wincher plan.`  contains the parameters mentioned above too
=> Use shortlinks for Wincher links in popup

packages/js/package.json, packages/js/src/settings/components/route-layout.js, yarn.lock
* We want to enhance the accessibility of our new `Settings UI` by allowing screen readers to notify users when they change section.
* Allows screen readers to notify the user when s/he navigates to a new section in the `Settings` page.
* The `react-aria-live` package has been favored over `@wordpress/a11y`  `speak` because it is implemented in a way which plays nicer with our `Settings UI` (i.e. by using React context takes care of reading things just once when it's needed). 
* When the screen reader encounters a section containing `info` or `warning` boxes will give precedence to their content before announcing the section. This is foreseen behavior.
* Activate a screen …
=> 19520 improve navigation experience a11y

packages/js/src/settings/components/formik-media-select-field.js, packages/js/src/settings/helpers/validation.js, packages/js/src/settings/store/media.js
* Validates WP media rest error.
* Validates WP media rest error in the Settings.
* Rest api error validation is separate from the general form validation.
* Other fields can be saved except media fields which are disabled.
* Install the [Disable REST API](https://wordpress.org/plugins/disable-json-api/) plugin
* Set a valid image under `Yoast` -> `Settings` -> `Site basics` -> `Site image` and save the settings.
* Go to `Settings` -> `Disable REST API` -> `Rules for Administrator` and deactivate the following 4 routes:
```
/wp/v2/media
/wp/v2/media/(?P[\d]+)
/wp/v2/media/(?P[\d]+)/post-process
/wp/v2/media/(?P[\d]+)/edit
```
* Return to `YoastSEO`-> `Settings` and try to …
=> 310 minor validation rest error may block new settings from saving

inc/class-upgrade.php, src/builders/indexable-builder.php
* We want to protect the indexable creation from needlessly creating `unindexed` entries when invalid IDs are passed for posts and terms
* Improves the indexables creation mechanism by avoiding duplicate `unindexed` entries when multiple invalid posts and terms are being used.
*
**For the improvement**:
* Clean up indexables
* We have to artificially pass invalid terms to create indexables for. One way to do so, is to add some code in src\builders\indexable-builder.php, in the `build()` function. Add the following to the beginning of that function, so that it becomes:
```
public function build( $indexable, $defaults = null ) {
if ( $defaults['object_type'] === 'term' ) { …
```
=> Avoid duplicate unindexed entries in indexable table

packages/js/src/settings/helpers/search.js
* We want to improve the search in the settings by adding keywords.
* Improves the search keywords in the Settings.
*
* Go to Settings
* Search results for:
* `index` and `now` should include Site features > IndexNow
* `search` and `console` should include Site connections > Google
* `schema` and `structured data` should include Site representation > Organization/person
* `image` should include Site representation > Organization logo and Personal logo or avatar
* `divider` and `separator` should include Breadcrumbs > Separator between breadcrumbs
* `facebook` and `share` should include Site features > Open graph data
* Note that `og` was requested here, but we have a …
=> Settings: add search keywords

packages/js/src/settings/routes/site-representation.js
* The Organization / Person choice is one of the most important ones when initially configuring Yoast SEO. To make sure our users will make good choice we linked a help article about this. 
* Adds a link to a help article for Organization / Person choice.
*
* Open `YoastSEO`->`Settings`
* In the sidebar navigation go to `Site representation`->`Organization/person`
* Check that description has a link [Learn more about the differences and choosing between Organization and Person.](https://yoa.st/site-representation-organization-person)\
* The short-link should be yoa.st/site-representation-organization-person (yet to be created) @marijnyoast 
* The short-link should …
=> added link to organisation/person radio button description

packages/js/src/settings/app.js, packages/ui-library/src/components/sidebar-navigation/mobile.js
* Improves accessibility for mobile navigation.
* Improves accessibility for mobile navigation by changing style of menu open and close button, and the default screen reader text of that component.
* `aria-label` prop was added to `SidebarNavigation.Mobile` in `ui-library`.
* Open `YoastSEO`->`Settings`
* Resize the screen to see the sidebar in mobile view.
* Check hamburger has style `yst-text-slate-500`
* Open menu and check `X` has background grey circle and when focus has ring border in the primary colour `primary-500` (The classes that should be there are `focus:yst-ring-2 focus:yst-ring-inset focus:yst-ring-primary-500`) 
* Enable voice over/screen reader and open …
=> settings-ui: 19523 improve mobile navigation a11y

src/integrations/settings-integration.php
* Attachment is something we filter out the Content types in Settings. This went wrong due to us expecting the name as the key. Plus the media pages route could not find the attachment data either.
* Fixes an unreleased issue where the content type `Media` showed up as well as the `Media pages` could not access the data.
*
* Go to Settings
* Verify `Media` is no longer present in the Settings > Content types menu.
* Go to Settings > Advanced settings > Media pages
* Verify the title says `Media pages`
*
* Settings's content types and media …
=> Settings: fix post types data for JS

css/src/yst_plugin_tools.css, src/presenters/admin/sidebar-presenter.php
* Alternate approach to the solution of https://github.com/Yoast/plugins-automated-testing/issues/301 and fix to https://github.com/Yoast/wordpress-seo/pull/19601
* Improves the sidebar upsell in the General page when viewed in languages that do _not_ need a line break.
* Tweaked the sidebar upsell styling in the General page: title is no longer center aligned.
* Change the translation to incorporate the tags around _Get_
* Add `white-space: nowrap` around _Get_ to ensure there can only be a linebreak in there. This happened in Japanese.
* Depending on whether the new translation has already been done or not, you'd need to alter the translations yourself in order to test …
=> fix upsell title on general page

packages/js/src/settings/components/introduction.js, packages/js/tests/settings/__snapshots__/search.test.js.snap, packages/ui-library/src/components/modal/index.js
* Remerge to [Fix Introduction modal dialog a11y.](https://github.com/Yoast/wordpress-seo/pull/19607)
* Relates to [Fix Introduction modal dialog a11y.](https://github.com/Yoast/wordpress-seo/pull/19607)
*
* Relates to [Fix Introduction modal dialog a11y.](https://github.com/Yoast/wordpress-seo/pull/19607)
*
*
Fixes [Fix Introduction modal dialog a11y.](https://github.com/Yoast/wordpress-seo/pull/19607)
=> Dupp 900 introduction modal dialog accessibility

packages/js/src/settings/app.js, packages/js/src/settings/initialize.js, packages/ui-library/src/components/sidebar-navigation/mobile.js
* Fix the `Skip to main content` link. This got reported here: https://github.com/Yoast/wordpress-seo/pull/19472#issuecomment-1372315420
* Fixes an unreleased bug where the `Skip to main content` link was not working.
* [@yoast/ui-library] Adds `openButtonId` and `closeButtonId` props to the _SidebarNavigation.Mobile_ component.
* Added IDs to the Yoast logo link and the mobile sidebar navigation buttons
* Do a not-so-nice outerWidth check to see if we are in the "mobile" view or not
* Go to Settings
* Tab through the page until you get `Skip to main content` (hint: I put my focus in the console of the inspector, then tab)
* …
=> Settings: fix skip to main content

css/src/new-settings.css, packages/ui-library/src/components/notifications/style.css
* Fix notifications content being unreadable.
* Fixes an unreleased bug where the Settings notifications content could be to become unreadable due to it not fitting on the screen, now there will be a vertical scrollbar.
* [@yoast/ui-library] Notifications will now provide vertical scrolling if the content does not fit.
* 
* Go to Settings > General > Site representation
* Set it to organization and start adding way too many other profiles that all have invalid data, e.g. `a`
* You can also try just making your screen height awfully small, and it will scroll the default save notification too. But that is not really real world.
* Click on save and the validation …
=> Settings: optional vertical scroll for notifications

packages/js/src/settings/helpers/validation.js, packages/js/src/settings/routes/crawl-optimization.js
As you can see in the issue, it is not always clear what consequences it can have when you saved an empty field.
_What would happen?_
Empty values would result in a `0` value in the database due to our PHP, which would not be valid (between 1 and 50) in our settings and all the search characters would be stripped (instead of the expected `unlimited`).
_What happens now?_
This PR prevents saving empty values. Only a number between 1 and 50 is allowed to be saved in our settings.
* Requires the search character limit to be a value (between 1 and 50).
* Preventing empty values from being saved. Empty values would result in a `0` value in the database due to our PHP, which would not be valid (between 1 and 50) in our settings and all …
=> Settings: always require a value for the search character limit

src/integrations/admin/old-premium-integration.php, tests/unit/integrations/admin/old-premium-integration-test.php
* Add a link to the plugin overview in the "old Premium" notice. [Original PR](https://github.com/Yoast/wordpress-seo/pull/19401)
* Adds a link to the plugin overview in the "old Premium" notice.
* Added a check to see if not already on the plugins overview, as linking to the same page is a bit unstylish.
* Have a Premium version < 20.0-RC1
* Verify you get the notification:
* <img width="620" alt="image" src="https://user-images.githubusercontent.com/35524806/213152516-8a20d02c-ecf0-4fc5-b90c-e31215462cec.png">
* Verify it includes a link that takes you to your plugins overview page
* Verify that on the plugins overview page, there is no link:
* <img width="628" …
=> 19531 add link to plugin overview to premium update notice

admin/formatter/class-metabox-formatter.php, packages/js/src/containers/SnippetEditor.js, packages/js/tests/containers/SnippetEditor.test.js, packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js, packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
* Add site name to google mobile preview.
* This PR restores the [original PR](https://github.com/Yoast/wordpress-seo/pull/19406)
* Add site name to google mobile preview.
* Change site name in script-data to be generated from the function `generate_site_name` that is being used for the schema snippet. 
* Used `getSiteName` function from the socialPreview settings that was already registered in the Redux store.
* Created 2 style components for new preview `SiteName` and `MobileFaviconContainer`.
For page, posts and taxonomies:
* Edit one of the above.
* Got to `Google preview`
* Check the google mobile preview has site name like in this image:
* Go to `Social` tab and …
=> Revert "Revert "DUPP-822-update-mobile-previews-to-account-for-site-name""

admin/views/tabs/metas/post-types.php, inc/class-post-type.php, src/integrations/settings-integration.php
* Fix an unreleased bug where notifications related to new public post types/taxonomies are never dismissed
* Fixes an unreleased bug where notifications related to new public post types/taxonomies are never dismissed.
* N/A
* Install and activate `Yoast Test Helper`
* If you have it already active, make sure  the `Enable post types & taxonomies` checkbox is not checked **before testing this PR**
* Go to `Tools` -> `Yoast Test`, check  the `Enable post types & taxonomies` checkbox and click `Save`
* Go to `Yoast SEO` -> `General` and verify you have the two notifications in the picture below:
* Click on one of the two `Settings` link
* Verify the `Settings` page opens
* …
=> 19665 new public post types taxonomies notifications cannot be dismissed

admin/class-admin.php, src/helpers/first-time-configuration-notice-helper.php, src/integrations/admin/first-time-configuration-notice-integration.php, src/surfaces/helpers-surface.php
* We want to add a CTA link to finish the SEO configuration in the plugin overview page. This only gets registered when the FTC is not finished yet.
* Adds a link to the first time configuration in the plugin overview when this is not completed yet.
* I extracted some code from the FTC integration into a helper so I could re-use it in the plugin overview class.
* Reset FTC progress and your indexables via the Test helper.
* Go to /wp-admin/plugins.php and make sure `Required by Yoast SEO Premium | [Finish your SEO configuration] | [FAQ] | [Settings]` is shown in the `Yoast SEO` plugin 
* Open the FTC via the link and run the optimization. When completed go back to …
=> Adds Extra link in the plugin overview.

packages/js/src/analysis-worker.js
* Loading the WordPress SEO plugin within the nightly WordPress 6.2 build broke the SEO, Readability and Inclusive language analysis. A WordPress JavaScript library was inadvertently loaded inside of the Analysis Web Worker after it had been renamed from `wp-inert-polyfill` to `wp-polyfill-inert`.
* Fixes a bug where the SEO, Readability and Inclusive language analysis would not load when using WordPress version 6.2-alpha.
* Added a disallow list for dependencies that we do not want to load, to allow for future scripts we want to disallow.
* Install the latest nightly build of WordPress 6.2.
* You can use [the WordPress Beta Tester …
=> Disallow loading wp-polyfill-inert dependency in web worker.

src/helpers/image-helper.php, src/helpers/schema/image-helper.php, tests/unit/helpers/schema/image-helper-test.php
* To be tested together with https://github.com/Yoast/wpseo-woocommerce/pull/874
* It enables Woo to not query the links table in vain for products with placeholder images (that are bound to not be in that table)
* Enables Woo SEO to not perform unnecessary queries
* Adds additional non-required parameters in the `get_attachment_by_url()` & `generate_from_url()` methods to enable not using the SEO Links table from other plugins
For the case of using the SEO link table for the `attachment_src_to_id` change (this also covers the fact that this should have been tested for [the main PR](https://github.com/Yoast/wordpress-seo/pull/19297), but it wasn't):
* With indexables …
=> Make using the SEO Link table as optional, when generating schema for an image based on its URL

packages/yoastseo/src/languageProcessing/languages/es/config/internal/passiveVoiceParticiples.js, packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/getParticiples.js, packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/getParticiples.js, packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js, packages/yoastseo/src/languageProcessing/languages/pt/helpers/internal/getParticiples.js
* The current code for participle detection in Portuguese and Spanish scans the whole text in search for participle forms, but only words of more than 3 characters are possible. Using the same conditional as in [this improvement for Italian](https://github.com/Yoast/wordpress-seo/pull/19610), we can make the scanning for participles more effective.
* Optimizes participle detection for Portuguese and Spanish
* [shopify-seo] Optimizes participle detection for Portuguese and Spanish
* There was one participle stem `id` (_to go_) which was removed from both language directories (in `passiveVoiceParticiples.js`). Intransitive verbs cannot be passivized.
* The conditional with `length > 3` works in all three languages. Although it is …
=> [PT][ES] Optimizes participle detection for Portuguese and Spanish

inc/class-wpseo-image-utils.php
* We want to fix a bug that prevent featured image to appear in og:image when using `wpseo_opengraph_image_size` filter with custom size that is equal to image size. 
* Fixes a bug where `wpseo_opengraph_image_size' is used to set custom size to `og:image` but doesn't work when uploading an image with the same size as the custom size.
* 
* Add the following code to your active theme `functions.php`:
```
// Add custom image size for Yoast SEO socials
add_image_size( 'featured-full', 640, 480 );
add_filter( 'wpseo_opengraph_image_size', 'yoast_seo_opengraph_change_image_size' );
function yoast_seo_opengraph_change_image_size() {
return 'featured-full';
}
```
* Open site …
=> fix og:image for same size as custom size

packages/js/src/structured-data-blocks/faq/components/FAQ.js, packages/js/src/structured-data-blocks/faq/components/Question.js, packages/js/src/structured-data-blocks/how-to/components/HowTo.js, packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
* We want to avoid some WordPress deprecation notices in our `How-to` and `FAQ` blocks
* Stops using deprecated WordPress components\props in `Yoast How-to` and `Yoast FAQ` blocks.
* N/A
**Test the Yoast FAQ block**
* Insert a `Yoast FAQ` block
* Verify that:
* All the buttons are present and function correctly
* You can use the `Italic`, `Link` and `Strike-through` formatting buttons both in the question and in the answer
* You get none of the following notice in the browser's console:
* `wp.components.IconButton is deprecated since version 5.4 and will be removed in version 6.2. Please use wp.components.Button instead`
* `wp.blockEditor.RichText …
=> 19452 fix richtext notices in block editor

src/helpers/post-type-helper.php, src/helpers/taxonomy-helper.php, src/integrations/settings-integration.php
* When you filter the _attachment_ post type out via `wpseo_indexable_excluded_post_types`, the _Media pages_ in Settings was malfunctioning.
* Fixes a bug where the _Media pages_ settings would not work correctly when the _attachment_ post type is filtered out via `wpseo_indexable_excluded_post_types`.
* Change the helpers to key the objects. This makes it so we do not have to loop over them to see if they are included
* Test for the `attachment` post type, and include it if missing
* After some more discussion we skipped showing a notification here. There is not really a text that can explain this properly and the filter itself already has a big warning: https://developer.yoast.com/features/indexables/indexables-filters/#excludi …
=> Settings: fix media pages when not indexing attachments

src/helpers/post-type-helper.php, src/helpers/taxonomy-helper.php, src/integrations/settings-integration.php
* Fix the Settings' Format archives.
* Fixes a bug where the _Format archives_ settings would not work correctly when the `post_format` taxonomy is disabled.
* Fixes a bug where the _Media pages_ settings would not work correctly when the attachment post type is filtered out via `wpseo_indexable_excluded_post_types`.
* Cherry picked the commits from https://github.com/Yoast/wordpress-seo/pull/19696 -- this code makes use of the keys that the taxonomy helper' `get_indexable_taxonomy_objects` got. Plus it is nice to ensure both fixes are present.
* Go to Yoast SEO > Settings > Advanced > Format Archives
* Disable the _Enable format-based archives_ setting
* Save the …
=> Settings: 19699 format archives settings page bug

packages/js/src/settings/components/route-layout.js, packages/js/src/settings/routes/site-connections.js
* We want to properly inform translators about some translatable strings
* We also want to improve the copy of a translatable string
* Improves the translations comments in _Settings > Site connections_ and a translatable string used by screen readers.
*
* visit e.g. Settings > Homepage and see **with the inspector** that in the code you can see  a div like:
```
<div style="border: 0px none; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; white-space: nowrap; padding: 0px; width: 1px; position: absolute;" role="log" aria-live="polite">Homepage Settings - Yoast SEO</div>
```
(the important part is `Homepage Settings - Yoast SEO`)
QA can test …
=> Fix translations settings

packages/js/src/settings/helpers/search.js, packages/js/src/settings/helpers/validation.js
* We want to have the same validation for the Mastodon field as we have for Facebook and Twitter, and we want to improve its discoverability via the Search
* Fixes an unreleased bug  where the Mastodon field doesn't get a validation feedback on error. Also improves discoverability via the Search feature.
*
* test with Premium
* visit the Settings 
* search for "Mastodon" or "Share" or "Social" and see that "Organization Mastodon" is among the results
* visit the field and fill it with a non-valid URL
* see that you get the same feedback you get for e.g. Facebook
* …
=> Add validation and search tags for Mastodon field

packages/js/src/structured-data-blocks/convertValueToStringRichText.js, packages/js/src/structured-data-blocks/faq/components/Question.js, packages/js/src/structured-data-blocks/how-to/block.js, packages/js/src/structured-data-blocks/how-to/components/HowTo.js, packages/js/src/structured-data-blocks/how-to/components/HowToStep.js, src/generators/schema/howto.php, src/integrations/blocks/structured-data-blocks.php
* Fix console notices when editing `FAQ` and `How To` blocks.
* Fixes deprecation notices when editing `FAQ` and `How to` blocks.
* Adds defensive code around php function for images in `FAQ` and `How to`.
* I chose to create custom function `convertValueToStringRichText.js`
* Edit a page or a post with the block editor.
* Add FAQ block ( After you click the blue + on the top left side of the screen, scroll all the way down in the list of the blocks until you reach Yoast blocks)
* Add few questions and answers.
* Change some questions or answers to `bold`,`italic`,`strikethrough`, add a link, image or line break.
* Save changes.
* Open console and see if you are getting …
=> 19453 fix notice in the block editor for faq and how to blocks

packages/yoastseo/spec/scoring/InclusiveLanguageAssessorSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
*
* Fixes an unreleased bug where the potentially non-inclusive phrase 'ex-offenders' was targeted twice by two separate Inclusive Language assessments.
* Fixes an unreleased typo in the feedback text of the 'felon' Inclusive Language assessment. 
* 
1. Install and activate Yoast SEO 20.1-RC1
2. Enable Inclusive language analysis feature in the setting
3. Create a post
4. Add this phrase: ex-offenders
5. You should only see one assessment result for this phrase under the Inclusive language analysis tab
> Avoid using _ex-offenders_ as it is potentially harmful. Consider using an alternative, such as _formerly incarcerated people_.
1. Install and activate Yoast SEO 20.1-RC1 …
=> Non-inclusive phrase "ex-offenders" returns with two feedback strings

packages/js/src/elementor/containers/SnippetEditor.js
* Fix site name missing in mobile preview when using elementor.
* Note: [original PR](https://github.com/Yoast/wordpress-seo/pull/19731) by @vraja-pro, closed because of git shenanigans while rebasing. 
* Fixes site name missing in mobile preview when using elementor.
*
* Edit a post or page with `elementor` and check mobile preview has site name as it appears when editing with the block editor.
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/435
=> fix site name missing in mobile preview in elementor

src/generators/schema/organization.php, src/helpers/social-profiles-helper.php, tests/unit/generators/schema/organization-test.php
*
* Fixes an unreleased bug where a notification would be thrown about missing `facebook_site` and `twitter_site`.
* Also reinstates some unit test cases that were deemed unnecessary in #19679 
* Visit the FTC in a clean environment (actually you just need to have "Facebook" and "Twitter" empty for Organization)
* check that you don't see any notice for missing `facebook_site` and `twitter_site` array elements
* check the impact below
*
* FTC Social Profiles fields for Organization
* check that when you change values (either in the FTC or in …
=> Fix notices about social inputs in FTC

packages/js/src/settings/routes/site-representation.js, src/integrations/admin/old-premium-integration.php
*
* Bumps the minimum Premium version to 20.1-RC0.
* Changes the shortlink in the Mastodon field description.
* Install with Premium < 20.1-RC1 and see you get the "Update to the latest version of Yoast SEO Premium" notification
* Install with Premium >= 20.1-RC1 and see you don't get the notification
* Visit Settings > Site Representation and check that "Read more about how to get your site verified." below the Mastodon field points to http://yoa.st/site-representation-mastodon
*
*
Fixes #19723
=> Mastodon: bump the minimum version in the notification urging to update Premium and update shortlink

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
*
* Improves the feedback strings of some non-inclusive phrases.
* [shopify-seo] Improves the feedback strings of some non-inclusive phrases.
* In this PR, I also removed duplicated unit tests in `disabilityAssessmentsSpec.js`.
* Enable the Inclusive language analysis feature in the setting
* Add this sentence to the post:  This math problem is driving me crazy.
* Confirm that you get the following result in the inclusive language analysis:
* Bullet: red
* Feedback:  "Avoid using _crazy_ as it is potentially harmful. Consider using an alternative, such as _to drive one to their limit, to …
=> Inclusive language: improve feedback string for some non-inclusive phrases

inc/options/class-wpseo-option-wpseo.php, src/integrations/admin/old-premium-integration.php, tests/unit/integrations/admin/old-premium-integration-test.php
*
* Introduces a new option to keep track when a notice to update Premium has been dismissed.
* Removes `dismiss_old_premium_notice` (a boolean) in favor of `dismiss_old_premium_version_notice` (a string storing the minimum Premium version number required)
Test these cases:
* Install with the current Premium RC
* check that you see the notification, dismiss it, and check that it stays dismissed
* Test the upgrade:
* reset the options/use a new environment
* install Free 20.0 + Premium 19.*
* dismiss the notification
* upgrade Free to this RC
* check that the notification is back
* …
=> Introduce and use a new option to keep track when a notice to update Premium has been dismissed

inc/class-wpseo-replace-vars.php, packages/js/src/values/defaultReplaceVariables.js
* We want to uniform replacement variables names across editors.
* Changes replacement variable name from `Page number` to `Page` in the `Settings` page.
* N/A
**Verify the correct insertion of the page-related replacement variables**
* Go to `Yoast SEO` -> `Settings` -> `Content types` -> `Posts`
* In the `SEO title` input field, type `%page`
* Verify that you have three suggestions: `Page`, `Pagetotal` and `Pagenumber`
* Perform the same checks for the `Meta description` text field
---
**Verify the correct rendering of the page-related replacement variable**
* Go to `Settings` and verify that `Blog pages show at most` field has a value of 10
* Edit a category which you …
=> Align naming to the new settings ui

packages/js/src/settings/routes/templates/taxonomy.js, src/integrations/settings-integration.php
* Hides "Enable SEO controls and assessments"  option from `Product shipping classes` in Settings
* Hides "Enable SEO controls and assessments" option from taxonomies that has no standard WP UI.
*
* Go to `WooCommerce`->`Settings`
* Select `Shipping` tab
* Select in the navigation of that tab `Shipping classes`
* Add Shipping class (e.g. testShipping).
* Go back to WP menu and select `Products`->`Add new`
* Add title, price and select `Shipping` tab to add `Shipping class`, select the shipping class you created and save.
* Go to `YoastSEO`->`Settings`->`Categories & tags`->`Product shipping classes`
* Scroll all the way to the end of the page and …
=> Settings UI: hides Enable "SEO controls and assessments" when show_ui is false

inc/class-upgrade.php, src/integrations/watchers/indexable-attachment-watcher.php
* We want to clean up orphaned hierarchies when we automatically clean up attachment indexables upon toggling the **Enable Media pages** setting
* Also, a minor improvement was made in the upgrade routine, where we schedule chunked cleanups *after* we clean up the attachment indexables, instead of *before*, to make sure we clean up orphaned hierarchies as well.
* Schedules cleanup when the `Enable Media pages` setting is turned off
* Moves scheduling of chunked cleanups at the end of the upgrade routine
*
**For the cleanup scheduling after the toggle of the setting**:
* On a brand new site with no images uploaded and the `Enable Media pages` turned on, install this PR/RC …
=> Schedule cleanup when the Enable Media pages setting is turned off

css/src/new-settings.css, packages/js/package.json, packages/js/src/settings/components/search.js, packages/js/tests/settings/__snapshots__/search.test.js.snap, packages/js/tests/settings/search.test.js, packages/ui-library/package.json, yarn.lock
* Address some a11y issues of the Settings' search modal:
* ✅ Visual order and DOM order of the search field and Close button don’t match
* ✅ The search field is unlabelled
* ✅ The search field has no focus style
* ✅ The list of suggestions isn’t read out by VoiceOver
* ✅ The ‘No results found’ message is not announced in any way.
* ✅ Same goes for the amount of results found: there’s no announcement.
* ✅ When there are no results, pressing Enter clears the search field
* ❌ Pressing the Tab key while a suggestions is highlighted selects the suggestion and triggers navigation
* Andrea commented on an existing issue (though closed) upstream: https://github.com/tailwindlabs/headlessui/issues/2017
* Improves the Settings' search …
=> Settings: improve the quick search modal dialog a11y

inc/class-addon-manager.php, tests/unit/inc/addon-manager-test.php
* We do not want to show the `view details` option in the plugin overview for our premium plugins. We want to show `visit plugin site` instead.
* Changes `view details` to `visit plugin site` for all our premium plugins in the plugin overview.
*
* Open the plugin overview page with at least premium installed and maybe with some add-ons. They don't have to be activated, but you will need an active license. 
* `without` this PR. make sure the plugins show `view details` as seen on the screenshot. Besides `Team Yoast` and the version.
* Checkout this PR or the RC.
* Remove all transient cache by running to following query:
`DELETE FROM wp_options WHERE option_name LIKE …
=> Removes including the `slug` key in our own plugin data

admin/class-admin.php, admin/class-premium-upsell-admin-block.php, admin/class-yoast-form.php, admin/views/licenses.php, admin/views/redirects.php, inc/class-wpseo-admin-bar-menu.php, packages/js/src/components/AnalysisUpsell.js, packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js, packages/js/src/components/contentAnalysis/SeoAnalysis.js, packages/js/src/components/modals/KeywordSynonyms.js, packages/js/src/components/modals/MultipleKeywords.js, packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js, packages/js/src/components/social/SocialUpsell.js, packages/js/src/insights/components/prominent-words.js, packages/js/src/integrations-page/simple-integration.js, packages/js/src/integrations-page/toggleable-integration.js, packages/js/src/workouts/components/WorkoutCard.js, src/integrations/admin/crawl-settings-integration.php, src/integrations/admin/social-templates-integration.php, src/integrations/settings-integration.php, src/presenters/admin/sidebar-presenter.php
* The CTB ID needs to be updated from 57d6a568-783c-45e2-a388-847cff155897 to f6a84663-465f-4cb5-8ba5-f7a6d72224b2
* Changes the CTB ID on our Unlock with Premium buttons
*
* Confirm that the upsell buttons now have the CTB ID f6a84663-465f-4cb5-8ba5-f7a6d72224b2 where they had 57d6a568-783c-45e2-a388-847cff155897
* If you happen to have a live BlueHost testing site, also create an zip with this changes and confirm that you get the new CTB popup when clicking one of the buttons with the CTB ID
*
*
Fixes #19792
=> 19792 Change CTB ID

css/src/metabox.css, packages/js/src/components/AnalysisCheck.js
* Fix Zapier publish box styling
* Fixes an unreleased bug where the Zapier section in the post publish would not look right.
* Apply specific styling for the analysis check
* Remove classic editor override to prevent it applying to other divs
* Tweak the margins to make it look right
**Preliminary requirements**
* You need a public site to be able to connect with Zapier. I went with a temporary [instaWP](https://app.instawp.io) one.
* Upload to your live site both  Free 20.1 (with this branch included) and Premium 20.1 zips
* Install the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin
* Go to `Yoast SEO` -> `Settings` -> `Site features` and make …
=> Fix publish box styling

packages/yoastseo/spec/languageProcessing/AbstractResearcherSpec.js, packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js, packages/yoastseo/src/languageProcessing/AbstractResearcher.js, packages/yoastseo/src/worker/AnalysisWebWorker.js
* Adding an infrastructure to register custom helpers will allow us to load helpers that are needed for add-on-specific assessments only when those add-ons are activated.
* [yoastseo] Creates an interface to register helper in the worker, and to add custom helpers to the researcher.
* [yoastseo] Adds type validation to the `registerResearch` method in `AnalysisWebWorker.js` and unit tests to test the method.
* I noticed that the `registerResearch` method didn't have any type validation so I added it in this PR. I also added unit tests for this method in `AnalysisWebWorkerSpec.js`.
* Confirm all unit tests pass.
* None needed …
=> Yoastseo refactor: Create an interface to register helpers in the worker

inc/class-addon-manager.php, tests/unit/inc/addon-manager-test.php
Reverts #19789
* We want to revert #19789
* Reverts #19789 (Changes `view details` to `visit plugin site` for all our premium plugins in the plugin overview.)
Fixes [“Install Now” button is shown for active Yoast add-ons#19454](https://github.com/Yoast/wordpress-seo/issues/19454)
=> Revert "Removes including the `slug` key in our own plugin data"

packages/js/src/inline-links/inline.js
* Remove deprecation notice from console for `anchorRef` prop by changing it to `anchor`. 
* Removes deprecation notice from console for `anchorRef` prop by changing it to `anchor`. 
*
* Edit post or page with block editor.
* Make sure that the view setting are disabled for `Top toolbar` and `Fullscreen mode`
* Add a paragraph block
* Add some text, move cursor to the text and click on the link icon:  
* Check no deprecation notice is triggered in the console regarding the `anchorRef`.
*
*
Fixes [Notice in the block editor: anchorRef prop in …
=> change prop name to anchor due to deprecation notice in console

wp-seo-main.php
* We want to remove all `filter_input` calls from our code base.
* Refactor `filter_input` call in `wp-seo-main` class.
*
The refactored call was only used for loading classes so the test instructions are a bit weird. We just verify that a certain global is set which means the classes loaded correctly.
* Install and activate both Yoast SEO and [Code Snippets](https://wordpress.org/plugins/code-snippets/).
* On the administration dashboard, click on Snippets and add a new snippet with the following content:
```
function check_wpseo_admin_created() {
if ( isset( $_POST['action'] ) && is_string( $_POST['action'] ) && wp_unslash( $_POST['action'] ) === 'inline-save' ) {
if ( …
```
=> DUPP-670 Refactor filter_input call in wp-seo-main

packages/js/src/structured-data-blocks/convertValueToStringRichText.js
* Escape quotes in alt of an image within how-to and faq blocks.
* Fixes an unreleased bug where using double quotes in an alt text of an image inside `Yoast How-to` or `Yoast FAQ` blocks would make the block crash.
*
* Edit a post with the block editor
* Add a `Yoast FAQ` block
* Add a question and an answer
* Add an image to the answer
* When selecting the image, specify an alt text containing  a double quote (`"`)
* Verify the block doesn't crash in the editor
* Visit the post in the frontend and check no error messages appear in console and images are visible as they should
* Repeat the test with the `Yoast How-to` block
* …
=> escaped quotes in alt of images in how-to and faq blocks

src/integrations/watchers/primary-term-watcher.php
* Refactor `filter_input` calls in `primary-term-watcher`.
*
* Go to a post editor screen and make sure to add two or more categories to the post.
* Below the category selector, select a primary category.
* Save and refresh. Verify whether the primary category saved successfully.
*
*
Fixes #
=> DUPP-670 Refactor filter_input in primary-term-watcher

packages/js/src/settings/routes/site-features.js
* Fix headings usage and hierarchy in `Site features`
* Changes headings usage and hierarchy in `Site features` for `Site structure` and `Social sharing` to be of `h2`.
*
* Open `YoastSEO`->`Settings`->`Site features`
* Check `Site structure` and `Social sharing` titles are in `h2` tags.
*
* All section titles should be in `h2` tag. I went over section titles in the general, settings, integration, redirects, workouts pages and couldn't find other section titles with wrong tags. 
Fixes [Improve headings usage and …
=> settings-UI: fix headings usage and hierarchy to h2 in site features

src/services/importing/conflicting-plugins-service.php, tests/unit/services/importing/conflicting-plugins-service-test.php
*
* Refactor calls to `filter_var` in conflicting-plugins-service class.
*
It seems that this class is not being used anymore so I can't write test instructions.
Igor here, I'm not sure this properly tests the path, but at least the code gets run:
* Either add a add & activate a plugin of your own, then add it to [a conflicting plugins list](https://github.com/Yoast/wordpress-seo/blob/trunk/src/config/conflicting-plugins.php), or add & activate one of those conflicting plugins.
* You should get a notification in our notification center about this detected conflict, including a deactivate button
* Click on the deactivate button
* Verify the plugin deactivated
QA can test …
=> DUPP-670 Refactor calls to filter_var in conflicting-plugins-service

src/integrations/admin/addon-installation/installation-integration.php
* Refactor `filter_input` calls in `installation-integration`.
*
* NA the change is in an integration behind a feature flag which we don't have plans to reprise at the moment
*
*
Fixes #
=> DUPP-670 Refactor call to filter_input in installation-integration

src/integrations/admin/helpscout-beacon.php
* Prevent deprecation warning in PHP 8.1 when visiting an admin page.
*
* Go to the Yoast SEO dashboard on the administration screen.
* Verify whether `help-scout-beacon.js` is loaded (by opening the inspect element window and going to the Sources tab).
**Extra step for devs:**
* Repeat the above with this PR and without, on PHP 8.1 and confirm that the deprecation warnings are displayed without the fix and do not display with this fix.
*
*
Fixes #
=> DUPP-670 Prevent deprecation warning by refactoring FILTER_SANITIZE_STRING in helpscout-beacon

packages/js/src/analysis/getApplyMarks.js, packages/js/src/lib/tinymce.js, packages/yoastseo/src/app.js
* After turning on the readability improvement suggestions, when editing text in the classic editor, after a second the editor is blurred and the window is focused instead of the editor field. This makes it impossible to correct the highlighted suggestions.
* Fixes a bug where an attempt on editing the text in Classic editor would result in unfocused text and make the cursor jumps to the beginning of the text when the highlight feature toggle is enabled.
*
* Create a post in Classic editor
* Start editing a post
* Remove everything and put the following text "Even as it is I have not been defeated by this bastard." into the editor
* …
=> [classic editor] Readability improvement highlights unfocus (blur) the editor and make editing difficult

admin/class-helpscout.php, composer.json
* We want to deprecate the unused `WPSEO_HelpScout` class
* Deprecates the `WPSEO_HelpScout` class.
* NA
*
*
Fixes #
=> DUPP-670 Deprecate `WPSEO_HelpScout`

inc/options/class-wpseo-option-social.php, inc/options/class-wpseo-option.php
* Remove `htmlspecialchars` that breaks urls for images that have GET parameters.
* Allows urls with query parameters in some upload fields.
* Props to [federicojacobi](https://github.com/federicojacobi)
*
* Add this snippet to functions.php (or somewhere that will run for sure):
```
/**
* Pseudo set image quality. It just adds get params to image urls. In real life this would be far more complex.
*/
add_filter(
'wp_get_attachment_url',
function ( $attachment_url ) {
$image_url = add_query_arg(
[
'quality' => 90,
'grain'   => 0.5,
],
$attachment_url
);
return $image_url;
}
);
```
* Go to to the `Yoast SEO` -> `General` -> `First-time configuration` 
* Proceed to `Site …
=> Federicojacobi cp

inc/class-addon-manager.php, tests/unit/inc/addon-manager-test.php
* Refactors `class-addon-manager` to not use `filter_input`.
*
* Install and activate Yoast SEO Local.
* Install and activate [Code Snippets](https://wordpress.org/plugins/code-snippets/#:~:text=A%20snippet%20is%20a%20small,to%20your%20active%20theme's%20functions.).
* On the administration dashboard, go to Snippets and add a new snippet.
* In the snippet content, put the following PHP code:
```
add_filter( 'transient_wpseo_site_information_quick', 'set_transient_for_site_information' );
function set_transient_for_site_information($value) {
return (object) [
'url' => …
```
=> DUPP-670 Refactor filter_input calls in class-addon-manager

admin/pages/tools.php
* Refactor `tools` to not use `filter_input`.
*
* On the administration dashboard, go to Yoast SEO -> Tools.
* Open all the administration windows in the tools screen and verify whether they all load correctly.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in tools

src/integrations/front-end/comment-link-fixer.php, tests/unit/integrations/front-end/comment-link-fixer-test.php
* We want to remove all calls to `filter_input` in our codebase.
* Refactor `filter_input` call in `comment-link-fixer` class.
*
* Go to the sites homepage and look at the HTML source, verify that the `<meta name='robots'>` tag has an `index` attribute.
* Now add `?replytocom=true` to the URL and once again go to the HTML source. Verify that the `<meta name='robots'>` tag has an `noindex` attribute.
*
*
Fixes #
=> DUPP-670 Refactor filter_input call in comment-link-fixer

admin/class-yoast-notifications.php
* Refactor `filter_input` calls in `class-yoast-notifications`.
*
* On the administration dashboard, go to Yoast SEO -> General.
* Verify that the styling for the notifications load correctly.
* Hide a notification and verity whether that works as expected.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in class-yoast-notifications

admin/ajax.php
* Improve PHP 8.1 compatibility for `wpseo_set_option` function.
*
* This function is not being used so there are no test instructions for this function.
*
*
Fixes #
=> DUPP-670 Fix filter_var for wpseo_set_option function

admin/class-my-yoast-proxy.php, tests/unit/admin/myyoast-proxy-test.php, tests/unit/doubles/admin/myyoast-proxy-double.php
* We want to be compatible with PHP 8.1
* Refactor all calls to `filter_input` in `class-my-yoast-proxy` class.
* Prevents deprecation warnings in PHP 8.1 to be triggered when a file was requested with the MyYoast proxy.
*
* Go to `/wp-admin/admin.php?page=wpseo_myyoast_proxy&file=research-webworker&plugin_version=19.11` and verify whether you see javascript code.
* Change the `plugin_version` parameter to something else and verify whether the page shows a 501 error.
*
*
Fixes #
=> DUPP-670 Fix PHP 8.1 compatibility for class-my-yoast-proxy class

admin/class-admin.php, composer.json
* Refactor calls to `filter_input` in `class-admin`.
*
* Go to `/wp-admin/admin.php?page=wpseo_licenses` and verify whether the styles load correctly.
*
*
Fixes #
=> DUPP-670 Refactor usage of filter_input in enqueue_assets function

admin/class-option-tabs.php
* Refactor all calls to `filter_input` in class-option-tabs class.
*
* The `tab` GET parameter is not used anymore so this PR can not be tested.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in class-option-tabs

admin/views/tool-import-export.php
* We want to replace all `FILTER_DEFAULT` filters in our codebase.
* Refactor `tool-import-export` class to not use `FILTER_DEFAULT` and `filter_input`.
* This PR removes the first branch because it is not used anywhere else.
* I have specifically not sanitized the `$yoast_seo_class` variable as it is used as a class name but we might need to introduce some better sanitization here (e.g. checking against a restricted set of classes). The code now allows for arbitrary class injection.
* On the administration dashboard, go to Yoast SEO -> Tools.
* Click on `Import and Export`.
* …
=> DUPP-670 Refactor filter_input calls for tool-import-export

admin/ajax.php, admin/taxonomy/class-taxonomy.php, packages/js/src/analysis/usedKeywords.js, packages/js/src/elementor/initializers/used-keywords-assessment.js, packages/js/src/initializers/used-keywords-assessment.js, src/integrations/third-party/elementor.php
* Refactor `filter_input` calls in `ajax_get_keyword_usage` and `ajax_get_term_keyword_usage` functions.
*
* Activate Yoast SEO and go to a post editor.
* Enter a focus keyphrase and verify that the right assessments show up (e.g. that your focus keyphrase is not in post title and not in the beginning of the post content).
* Now add your focus keyphrase to the post title or the beginning of the post content and verify that the assessments disappear.
*
*
Fixes #
=> DUPP-670 Refactor filter_input usage in ajax_get_keyword_usage function

admin/metabox/class-metabox-section-inclusive-language.php, admin/views/class-yoast-feature-toggles.php, packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js, packages/js/src/settings/routes/site-features.js
*
* Removes the beta badge for the _inclusive language_ assessment.
* [yoastseo] Removes the beta badge for the  _inclusive language_ assessment.
*
* Open Yoast SEO->Settings->Site features
* Check that the Beta label is not present for the _inclusive language_ assessment.
* Enable the Inclusive language feature
* Create or open a post
* Check that _inclusive language_ tab doesn't have beta badge
* Disable the Inclusive language feature
* Check that the Beta label is not present for the _inclusive language_ assessment.
* Install and activate Yoast SEO Premium
* Repeat the …
=> Remove beta label from the inclusive language assessment

admin/views/tabs/tool/wpseo-export.php
*Refactor `wpseo-export` to not use `filter_input`.
*
* On the administration dashboard, go to Yoast SEO -> Tools and click on `Import and Export`.
* Go to the `Export settings` tab and click on `Export your Yoast SEO settings`.
* Verify that the export works.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in wpseo-export

inc/class-wpseo-shortlinker.php, tests/integration/inc/test-class-wpseo-shortlinker.php
* Refactors `class-wpseo-shortlinker` to not use `filter_input`.
*
* Go to the Yoast administration dashboard and inspect the link "Get Yoast SEO Premium".
* Verify that the link has a `screen` GET parameter of `wpseo_dashboard`.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in class-wpseo-shortlinker

admin/metabox/class-metabox.php
* Refactor `filter_input` calls in `class-metabox`.
*
* Go to a post editor and verify whether the metabox titles shows up (so the Google title for example).
* Now go to the social tab and set a Facebook image. Upload a new image and select it.
* Verify whether the Facebook image is correctly set in the metabox.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in class-metabox

admin/class-bulk-editor-list-table.php
* Refactor all calls to `filter_input` in `class-bulk-editor-list-table` class.
*
* Head on over to the administration screen and open the bulk editor by going to Yoast SEO -> Tools and clicking on Bulk editor.
* Verify that all the filters and sorting options on the page still work, so test the content type filter, all the sorting options and go to page 2 and verify that all of that works as expected.
*
*
Fixes #
=> DUPP-670 Refactor filter_input call in class-bulk-editor-list-table class

admin/taxonomy/class-taxonomy-columns.php
* Refactor `class-taxonomy-columns` to not use `filter_input`.
*
* Go to the categories overview page (`/wp-admin/edit-tags.php?taxonomy=category`).
* Verify whether the Yoast columns pop up correctly.
* Now go to Yoast SEO -> Search appearance settings.
* Go to the taxonomies tab and disable `Show SEO settings for Categories?`.
* Save and head back to the categories overview page, verify that the Yoast columns are gone.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in class-taxonomy-columns

admin/menu/class-menu.php
* Refactor `filter_input` calls in `class-menu`.
*
* Verify that all admin pages load correctly, more specifically verify that `/wp-admin/admin.php?page=[page]` loads for `page` in `wpseo_tools, wpseo_integrations, wpseo_licences, wpseo_settings, wpseo_dashboard`.
*
*
Fixes #
=> DUPP-670 Refactor filter_input calls in class-menu

admin/filters/class-abstract-post-filter.php
* We want to replace all `FILTER_DEFAULT` filters in our codebase.
* Refactor `class-abstract-post-filter` to not use `FILTER_DEFAULT` or `filter_input`.
*
* Go to the posts list view on the administrator dashboard.
* Edit a post and make it cornerstone content in the yoast metabox.
* Go back to the post list view and verify whether the cornerstone content filter pops up (it will be just below the title of the page "Posts").
* Click on the cornerstone content filter and verify that it works as expected.
* …
=> DUPP-670 Refactor filter_input and FILTER_DEFAULT in class-abstract-post-filter

admin/class-yoast-network-admin.php, tests/integration/admin/test-class-yoast-network-admin.php
* Prevents deprecation warnings in PHP 8.1 to be triggered when visiting the network admin settings of Yoast SEO.
*
* Boot up the multisite testing environment and network activate Yoast SEO.
* Go to the network admin and click on Yoast SEO -> General.
* Change some settings and save them, verify whether the save functions as expected.
**Extra step for devs:**
* Repeat the above with this PR and without, on PHP 8.1 and confirm that the deprecation warnings are displayed without the fix and do not display with this fix.
* …
=> DUPP-670 Fix PHP 8.1 compatibility for class-yoast-network-admin class

src/helpers/current-page-helper.php, tests/unit/helpers/current-page-helper-test.php
* Refactors URL parameters fetching for `current-page-helper` class.
*
* Go to the reading settings of WordPress (`/wp-admin/options-reading.php`) and enable `Discourage search engines from indexing this site`.
* Now go to the Yoast SEO dashboard (`/wp-admin/admin.php?page=wpseo_dashboard`) and verify that the Huge SEO Issue shows up *only* in the problems section.
* Now go to the admin dashboard (`/wp-admin/index.php`) and verify that the Huge SEO Issue shows up in a normal notification.
* Now visit the Yoast SEO > Tools page and verify that the Huge SEO Issue shows up in a …
=> DUPP-670 Refactor filter_input calls in current-page-helper class

packages/yoastseo/spec/languageProcessing/languages/de/ResearcherSpec.js, packages/yoastseo/spec/languageProcessing/languages/de/helpers/checkIfWordIsFunctionSpec.js, packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js, packages/yoastseo/src/languageProcessing/languages/de/Researcher.js, packages/yoastseo/src/languageProcessing/languages/de/helpers/checkIfWordIsFunction.js, packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
* German functional word is not recognised if it's in capitalised.  
* [yoastseo] Adds a helper `checkIfWordIsFunction` for German.
* [wordpress-seo-premium] Fixes an unreleased bug where German function words were not recognized when they were in capital letter(s).
* [shopify-seo] Fixes an unreleased bug where German function words were not recognized when they were in capital letter(s).
*
* Activate Free and Premium
* Set site language to German
* Create a post with the following text:
* Nach der von Erzbischof Hinkmar von Reims gebildeten Legende hat gegen Ende des 5. Jahrhunderts der hl. Remigius als Bischof von Reims den Frankenkönig Chlodwig I. getauft und mit einem …
=> Fix recognition of capitalized function words in German#19860

src/actions/indexables/indexable-head-action.php, tests/unit/actions/indexables/indexable-head-action-test.php
* In case the site has a static page set as homepage, The `get_head` REST endpoint returns wrong values for some meta tags when called with the hompage URL as argument
* Fixes a bug where the `get_head` REST endpoint would return wrong values for some meta tags when called with the hompage URL as argument.
*
* Go to `Settings` -> `Reading`
* Set `Your homepage displays` radio checkbox to `A static page`
* Select a page from the dropdown menu
* Visit your site's homepage in the frontend
* Inspect the page source code and take note of the values of the following meta tags:
* title
* description (if any)
* og:title
* og:description
* Visit …
=> 18055 rest api get head shows incorrect information for front page

admin/metabox/class-metabox.php
* #19154 introduced nonce usage for the AJAX keyword checks, but a nonce wasn't added to the script data for the post metabox, so the AJAX called failed with a 403 error.
* Fixes an unreleased bug where checks against re-using a keyword in posts were broken.
*
* edit a previously existing post or create a new one
* set a focus keyword, e.g. "yoast"
* create a new post
* open the browser tools and keep the Network tab open
* add the same focus keyword as above
* make sure you write it in one go since it will fire the call after a timeout
* check that you see an AJAX call with action `get_focus_keyword_usage` and it get a 200 response instead of a `403` error
* open the …
=> Add nonce to script data for metabox

inc/class-addon-manager.php, tests/unit/inc/addon-manager-test.php
* We want to show the correct values in the `view details` modal in the plugin overview.
* Shows correct buttons in the plugin overview `view details` modal.
*
* Install the latest released versions of premium + all addons together with this PR.
* Make sure all the add-ons show the following information on the `view details` screen.
For example for `news`:
It shows the newest version: in this case 13.1 and it show a button that shows Latest Version Installed. This should be the case for all add-ons and premium.
* Download an older release of a plugin. And make sure it shows the following information.
It shows an upgrade banner that shows the actual newest version. And on …
=> Add correct slug for the modal and add a version to make the buttons behave

packages/yoastseo/spec/scoring/collectionPages/cornerstone/seoAssessorSpec.js, packages/yoastseo/spec/scoring/collectionPages/fullTextTests/runFullTextTests.js, packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js, packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js, packages/yoastseo/spec/scoring/storePostsAndPages/contentAssessorSpec.js, packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/contentAssessorSpec.js, packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/seoAssessorSpec.js, packages/yoastseo/spec/scoring/storePostsAndPages/seoAssessorSpec.js, packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js, packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js, packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/collectionPages/seoAssessor.js, packages/yoastseo/src/scoring/storeBlog/seoAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
*
* [yoastseo] Creates the anchor opening tag after merging the configs in _keyphrase distribution_ and _word complexity_ assessments.
* [yoastseo] Removes _keyphrase distribution_ and _word complexity_ assessments from non-product eCommerce assessors.
* In this PR, we change the way we create the opening anchor tag ONLY in keyphrase distribution and word complexity assessments. This is to limit the impact scope.
* This change is necessary so that the assessment shortlinks passed from shopify side are also processed properly.
* In this PR, the word complexity and keyphrase distribution assessments are also removed from other (non-product) eCommerce assessors. This is because, in Shopify, we register both assessments to ALL …
=> Move the creation of anchor opening tag to after merging the configs

packages/ui-library/.storybook/main.js, packages/ui-library/changelog.md, packages/ui-library/contributing.md, packages/ui-library/readme.md, packages/ui-library/src/changelog.stories.mdx, packages/ui-library/src/contributing.stories.mdx, packages/ui-library/src/installation.md, packages/ui-library/src/installation.stories.mdx, packages/ui-library/src/introduction.md, packages/ui-library/src/introduction.stories.mdx
* The README of the `@yoast/ui-library` should be aimed at a different target audience, then the Storybook is aimed at.
* The README should focus on developers interested on adding to the UI Library or its storybook,
* The Storybook should focus on developers interested on using the UI library or checking the storybook.
* To give more room to certain parts of the introduction, this also splits up the introduction of the Storybook into several smaller pages.
* Improves the documentation of the Storybook for the UI Library.
* I've based this branch on top of a5539ebfb4ff5267cb09c33902d220af3bd342bf. This was the last commit in https://github.com/Yoast/wordpress-seo/pull/19775, which ensures the code of the UI library hasn't changed …
=> Separate `@yoast/ui-library` readme from Storybook introduction

src/helpers/pagination-helper.php, tests/unit/helpers/pagination-helper-test.php
* We want to fix a bug with the canonical/prev/next URLs of paginated pages that have query parameters.
* Fixes a bug where query parameters would be added in the middle of canonical and prev and next links, in paginated pages. Props to @andreas-pa
*
* Add the following filter on your theme's functions.php
```
add_filter( 'term_link', function( $url ) {
$args = [
'foo' => 'bar',
'x' => 'y',
];
return add_query_arg( $args, $url );
} );
```
* To make testing easier, go to Settings->Reading and set `Blog pages show at most` to 2. Then create 8 posts for a category
* Visit the frontend of the 3rd page of that category, eg. …
=> Wrong canonical/prev/next URLs on paginated pages with query params

src/generators/schema/article.php, tests/unit/generators/schema/article-test.php
* We want to avoid showing a php warning by ensuring we're using an instance of `WP_User` when expected.
* Avoids issuing a php warning because of wrong variable type.
*
* Create a new user with an `author` role
* Login with the new user account
* Create and publish a post
* Delete the user you've just created through the database `wp_users` table.
* Visit the post in the frontend and verify no php warnings stating `Attempt to read property "display_name" on bool` are issued
* Inspect the page code and verify:
* the schema is valid 
* the `author` property of the `Article` piece is as follows:
```
"author": {
"name": "",
"@id": ""
}
``` 
* the `Person` piece is as …
=> Add check to ensure author is correctly initialised

src/integrations/front-end/open-graph-oembed.php, tests/unit/integrations/front-end/open-graph-oembed-test.php
* We want to fix the errors from this report: https://wordpress.org/support/topic/fatal-error-with-opengraph-on-20-2/#post-16523301
* Fixes a bug where a fatal error would appear in oEmbed pages for media pages, when those are disabled from Yoast settings.
* A small performance improvement is also included here, by quering for the post's indexable just once in the beginning instead of three times.
* On PHP 8+, make sure you have `Enable Media pages` as disabled
* On the oEmbed link for a media page, eg. for the `http://wordpress.test/small-image-5/` media page:
**Without this PR:**
* We throw a Fatal Error there, so the …
=> Add meta from post indexable only when indexable exists

packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js, packages/yoastseo/src/scoring/collectionPages/cornerstone/relatedKeywordAssessor.js, packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/collectionPages/relatedKeywordAssessor.js, packages/yoastseo/src/scoring/collectionPages/seoAssessor.js, packages/yoastseo/src/scoring/productPages/contentAssessor.js, packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js, packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js, packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js, packages/yoastseo/src/scoring/productPages/seoAssessor.js, packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/storeBlog/seoAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/relatedKeywordAssessor.js, packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
*
* [yoastseo] Imports the e-Commerce assessors' dependencies from `index.js` if applicable.
* [wpseo-woocommerce] Imports the e-Commerce assessors' dependencies from `index.js` if applicable.
* [shopify-seo] Imports the e-Commerce assessors' dependencies from `index.js` if applicable.
* In `packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js`, I changed the class the assessor inherits from. Initially, the class inherits from `Assessor` and duplicates many `ContentAssessor` 's additional methods there. The duplication of those methods is not necessary anymore when `packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js` inherits form `ContentAssessor` (instead of `Assessor`)
This PR can be acceptance …
=> Restructuring yoastseo: improve the js bundle in woocommerce and shopify

packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js, packages/js/src/components/contentAnalysis/SeoAnalysis.js
* All other external links open in new tabs. The upsell links for keyphrase distribution and word complexity should also open in new tabs.
* Make upsell links for the keyphrase distribution and word complexity assessments open in a new tab.
*
* Activate Yoast SEO Free
* Go to the SEO analysis feedback and click the link in the upsell for the keyphrase distribution assessment
* Confirm that the link opens in a new tab
* Go to the readability analysis tab and click the link in the upsell for the word complexity assessment
*
* …
=> Make upsell links for keyphrase distribution and word complexity assessments open in a new tab

admin/class-config.php, admin/class-helpscout.php, admin/google_search_console/views/gsc-redirect-nopremium.php, admin/roles/class-role-manager-vip.php, inc/class-wpseo-utils.php, inc/language-utils.php, inc/sitemaps/class-sitemaps.php, inc/wpseo-functions-deprecated.php, src/config/schema-types.php, src/deprecated/admin/ryte/class-ryte.php, src/deprecated/admin/views/class-view-utils.php, src/deprecated/frontend/frontend.php, src/deprecated/i18n/i18n-v3.php, src/deprecated/src/conditionals/front-end-inspector-conditional.php, src/deprecated/src/conditionals/japanese-support-conditional.php, src/deprecated/src/conditionals/the-events-calendar-conditional.php, src/deprecated/src/conditionals/third-party/coauthors-plus-activated-conditional.php, src/deprecated/src/generators/schema/third-party/coauthor.php, src/deprecated/src/generators/schema/third-party/events-calendar-schema.php, src/deprecated/src/helpers/input-helper.php, src/deprecated/src/integrations/admin/social-templates-integration.php, src/deprecated/src/integrations/third-party/coauthors-plus.php, src/deprecated/src/integrations/third-party/the-events-calendar.php, src/deprecated/src/presenters/admin/auto-update-notification-presenter.php, src/deprecated/src/routes/configuration-workout-route.php, src/integrations/third-party/wincher.php, src/integrations/third-party/wordproof-integration-toggle.php, src/repositories/indexable-repository.php
* We want to be consistent and always use "Yoast SEO" in deprecation messages.
* Changes every `WPSEO` in deprecation messages to `Yoast SEO`.
*
* NA
*
*
Fixes #
=> Change every `WPSEO` in deprecation messages to `Yoast SEO`

packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js, packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js, packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js, packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js, packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js, packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js, packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
*
* Reverts #19399.
* This PR only reverts the user-facing change. In this case, it's the change inside `getSentences.js` where we removed the images from the text.
* Add at least 100 words to the post
* Set a focus keyphrase
* Add an image
* Add a caption to your image and include the focus keyphrase there in the first sentence
* Confirm that the Keyword density assessment detects the focus keyphrase occurrence in the caption
* Click on the eye icon
* Confirm that the focus keyphrase in the image caption is NOT highlighted
* Add a second sentence in …
=> Revert #19399 highlighting support in captions in classic editor

admin/class-export.php
* Remove PHP warnings for undefined array key on exporting settings .
* Fixes a bug where a PHP warning would be thrown when exporting Yoast settings.
*
* Install and activate Yoast SEO 20.3 RC1.
* Install and activate Query Monitor.
* Go to `Yoast SEO` -> `Tools` and click on Import and Export.
* Go to the `Export settings` tab and click on Export your Yoast SEO settings.
* Check you don't get those warnings in the Query Monitor:
* Create a new site and import those setting from the previous site and check you get a message that setting were imported successfully. 
* …
=> fix php warnings undefined array key in export settings

admin/class-admin.php, admin/formatter/class-term-metabox-formatter.php, admin/taxonomy/class-taxonomy.php, inc/sitemaps/class-author-sitemap-provider.php, src/integrations/blocks/block-categories.php, tests/integration/admin/test-class-yoast-network-admin.php, tests/integration/formatter/test-term-metabox-formatter.php, tests/integration/notifications/test-class-yoast-notification-center.php, tests/integration/notifications/test-class-yoast-notification.php, wp-seo-main.php
* Remove dead code related to old WordPress versions that are no longer supported.
* Removes dead code related to old WordPress versions that are no longer supported.
*
* Edit a post with block editor.
* Structured data blocks should still work as expected (FAQ block and the How-to block).
* Also confirm that the block categories still work as expected.
* In a post, click the top left block inserter. See the `Yoast Structured Data Blocks` and `Yoast Internal Linking Blocks` block categories
---
* Check that the author sitemap is correctly being generated.
* Edit a user profile of an admin and save it.
* Repeat the above steps and check all should work again as expected …
=> 19892 check for dead code related to old wp versions

packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
* To accompany platform's https://github.com/Yoast/my-yoast/pull/4254 where the extra information of the `source` is now expected
* Sends a `source` parameter to MyYoast upon newsletter subscription
*
* Have the `Network` tab open and go to the FTC (while you have Premium not active)
* At the last step, `Sign up` for the newsletter
* In the `Network` tab, confirm that the `subscribe` request returned with a 201 response code:
* Also check the payload of that request and confirm that it includes a `source : "free"` parameter
* Go to the last step of the FTC, while having Premium disabled.
* input a valid email address to subscribe to the newsletter ( …
=> Send extra information to the newsletter subscription

src/deprecated/admin/class-helpscout.php
*
* Fixes a bug where a fatal error related to HelpScout would be thrown when using a more-than-2-year-old Yoast addon.
*
* Mimic what addons from before spring '21 did by adding the following snippet to your theme's `functions.php`:
```
add_action( 'admin_init', 'test_helpscout_deprecation' );
function test_helpscout_deprecation() {
$helpscout = new WPSEO_HelpScout(
'4e7489db-f907-41b3-9e86-93a01b4df9b0',
[ 'wpseo_dashboard' ],
[ 'wordpress-seo' ]
);
$helpscout->register_hooks();
}
```
* visit the site's backend
* without this PR: you should get a `Fatal error: Uncaught Error: Call to undefined method WPSEO_HelpScout::is_beacon_page()`
* with this PR: you should not get …
=> Improve deprecation of WPSEO_HelpScout and move it to the deprecated folder

packages/js/src/analysis/blockEditorData.js
* Finetune https://github.com/Yoast/wordpress-seo/pull/18227 a bit
* Fixes a bug where the Google preview would show the post ID in the breadcrumbs when creating a new post with a slug but without a title yet.
* Fixes an unreleased bug where the Google preview would show the `slug` twice in the breadcrumbs if it contains encoded characters.
* Do a case insensitive check on the encoded slug
* Change the `href` to only `origin` and `pathname` so we effectively ignore the `search` and `hash` parts
* Add something non-latin as a slug
* Like `مرحبًا` (which is hello according to Google translate)
* Or `🙂1234567890`
* Verify the breadcrumb in …
=> Remove the encoded slug

packages/replacement-variable-editor/package.json, packages/yoast-components/package.json
* Clean up dependencies a little.
* [@yoast/replacement-variable-editor 0.1.0] Removes unused dependency on `yoastseo`.
* [yoast-components 0.1.0] Removes unused dependency on `yoastseo`.
* Searched for the package name within the respective packages. Nothing else came up.
* Only in tooling, nothing to test
* Only thing to do is do a quick sanity check if it still builds and if the components still work as before:
* Edit a post
* Verify the replacement variable editor works
* Verify the keyphrase input works
*
* Unused dependency cleanup in 2 …
=> Remove unused dependencies on `yoastseo`

packages/js/src/settings/routes/crawl-optimization.js, src/initializers/crawl-cleanup-permalinks.php
*
* Changes the copy and severity level of the _Advanced URL cleanup_ alert in the settings.
* Also adds a link to the `x-redirect-by` header.
* visit Settings > Advanced > Crawl optimization
* scroll to the bottom and verify the copy and alert variant have changed:
* Enable `Remove unregistered URL parameters`
* keep the Network tab of the inspector open 
* visit **while logged out** any front-end page with a bogus param added, e.g. https://basic.wordpress.test/?foo=bar
* see that the `301` redirect header contains `x-redirect-by | Yoast SEO: unregistered URL parameter removed. See https://yoa.st/advanced-crawl-settings`
* …
=> Advanced crawl cleanup improvements

packages/js/src/analysis/blockEditorData.js
* Addendum for https://github.com/Yoast/wordpress-seo/pull/20012 to fix similar problems for custom post types and pages (in the block editor).
* Fixes a bug where the Google preview breadcrumbs in the Block editor would show the slug twice when creating a new page or custom post. This would only happen before (auto-)saving the page or custom post.
* Fixes a bug where the Google preview breadcrumbs in the Block editor would show `auto-draft` when creating a new page or custom post. This would only happen before (auto-)saving the page or custom post.
* When we update the slug in the editor, it triggers this baseUrl refetching, but it does not have the slug yet. In order to prevent a double slug ending up in our chain, we get the …
=> Google preview: custom post type double slug

packages/js/src/integrations-page/jetpack-boost-integration.js, src/integrations/admin/integrations-page.php
*
* Changes icon color and alignment, and  "Learn more" destination URL for the Jetpack Boost integration card.
*
* Install and activate Jetpack Boost, but don't set a premium subscription
* visit the integrations page and look at the Jetpack Boost card
* check that the :warning: icon is vertically centered to the two text lines 
* check that the color is `amber-500` (#f59e0b - rgb(245, 158, 11) ) instead of `orange-400` (#fb923c - rgb(251, 146, 60) )
* set up a premium subscription for Jetpack Boost and re-check the card
* check that the `Learn More` link opens (in a new tab) to `wp-admin/admin.php?page=jetpack-boost`
*
This …
=> Changes to jetpack boost integration card

packages/js/src/components/WebinarPromoNotification.js
* We want to update the copy of the `Get the most out of Yoast SEO` notification
* Updates the copy of the `Get the most out of Yoast SEO` notification.
* Also moved "Yoast SEO" out of the translatable strings
* Open https://basic.wordpress.test/wp-admin/admin.php?page=wpseo_dashboard 
* You should see the following notification
* Make sure the copy is as described in https://github.com/Yoast/growth/issues/13
* If you don't see the notification log in as a new user with at least the seo_manager role.
* create a new post in the block editor
* open the Yoast SEO sidebar
* check that the notification displays the same copy as above. …
=> Updates notification copy.

src/integrations/third-party/elementor.php
* Fixes a bug that was introduced in https://github.com/Yoast/wordpress-seo/pull/19800 . The previously used keyphrase would not work in Elementor. The source of the bug was that the previously used keyphrase analysis was initialized with the old ajax-action (`wpseo-keyword-usage`) instead of the new one (`wpseo-keyword-usage-and-post-types`).
* The old ajax-action is still used in some places of the code. Namely the code for the previously used keyphrase in taxonomies/terms. This analysis is broken and it was decided to solve this in a separate issue: https://github.com/Yoast/wordpress-seo/issues/19808
* Fixes a bug where the _previously used keyphrase analysis_ did not work in Elementor.
* …
=> Fixes a bug where the previously used keyphrase analysis did not work in Elementor.

packages/js/src/analysis/blockEditorData.js, packages/js/tests/blockEditorData.test.js, packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
* Note that some things mentioned in the issue are already fixed in the meantime [20.4 RC] (hence the outdated issue)
* https://github.com/Yoast/wordpress-seo/pull/20012
* https://github.com/Yoast/wordpress-seo/pull/20031
* Fixes a bug where the Google preview would show a duplicate slug in the breadcrumbs when the slug included encoded characters.
* [@yoast/search-metadata-previews 0.1.0] Improves the parsing of the SnippetPreview's breadcrumbs.
* Rewrote the breadcrumb handling in the SnippetPreview
* Use the URL constructor instead of a deprecated `parse`
* Decoding individual URL parts to try and decode as much as possible
* Remove unneeded `replaceSpecialCharactersAndDiacritics` surrounding the url for the breadcrumbs, …
=> Google preview: fix breadcrumb duplicate slug when it includes encoded parts

readme.txt, tests/unit/bootstrap.php, wp-seo-main.php
*
* Sets the WordPress tested up to version to 6.2.
*
* NA
*
*
Fixes #20044
=> Sets the WordPress tested up to version to 6.2

packages/yoastseo/src/scoring/assessments/index.js, packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js, packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js, packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js, packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js, packages/yoastseo/src/scoring/productPages/seoAssessor.js
* Previously, the product-specific assessments `ProductSKUAssessment`, `ProductIdentifiersAssessment`, and `ImageAltTagsAssessment` are included in `assessments/index.js` module. They are the assessments that will be used only on product pages. Loading them together with the other assessments that are available in Yoast SEO (Free) doesn't make sense.
* This PR is to make the aforementioned eCommerce (hence non-Free) assessments not be loaded in Free when Yoast SEO for WooCommerce is not activated.
* [yoastseo] Removes `ProductSKUAssessment`, `ProductIdentifiersAssessment`, and `ImageAltTagsAssessment` from the assessments module.
* The way the assessments' dependencies are loaded is also changed. This is to make sure that those …
=> Restructuring yoastseo: unbundle the ecommerce assessments from the free assessments module

admin/metabox/class-metabox.php, admin/tracking/class-tracking-settings-data.php, inc/class-upgrade.php, inc/options/class-wpseo-option-wpseo.php, packages/js/src/components/JetpackBoost.js, packages/js/src/initializers/block-editor-integration.js
* Jetpack boost ad tweaking
* Changes the non released Jetpack boost ad.
*
*
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/20035
=> Jetpack boost ad tweaking

packages/yoastseo/spec/languageProcessing/AbstractResearcherSpec.js, packages/yoastseo/spec/languageProcessing/helpers/sentence/countSentencesSpec.js, packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js, packages/yoastseo/spec/languageProcessing/helpers/sentence/memoizedSentenceTokenizerSpec.js, packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js, packages/yoastseo/spec/parse/build/buildSpec.js, packages/yoastseo/spec/parse/build/private/filterTreeSpec.js, packages/yoastseo/spec/parse/language/LanguageProcessorSpec.js, packages/yoastseo/spec/parse/structure/NodeSpec.js, packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js, packages/yoastseo/spec/parse/traverse/innerTextSpec.js, packages/yoastseo/src/languageProcessing/AbstractResearcher.js, packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js, packages/yoastseo/src/languageProcessing/helpers/sentence/memoizedSentenceTokenizer.js, packages/yoastseo/src/languageProcessing/languages/de/helpers/memoizedSentenceTokenizer.js, packages/yoastseo/src/languageProcessing/languages/ja/helpers/memoizedSentenceTokenizer.js, packages/yoastseo/src/languageProcessing/researches/getPassiveVoiceResult.js, packages/yoastseo/src/parse/build/private/filterTree.js, packages/yoastseo/src/parse/language/LanguageProcessor.js, packages/yoastseo/src/parse/traverse/innerText.js
*
* [yoastseo] Adds sentences to paragraph and heading nodes.
* The default memoized sentence tokenizer is moved to a separate file and added to the Abstract Researcher. This way, the way we retrieve the tokenizer (through the researcher) is consistent for all languages.
* Filtering out blocks consisting of `<p>` tags is moved out of the tokenizer and into the `getSentences` function. This step is only needed when retrieving sentences through the `getSentences` function (not through the `splitIntoSentences` method of the `LanguageProcessor`) so it makes more sense to have it inside that function. It also helps with not having to repeat the same code in every language-specific tokenizer. …
=> HTML Parser - Add sentences to paragraph and heading nodes

packages/js/src/integrations-page/jetpack-boost-integration.js
* We want to add a `New` badge to the Jetpack Boost integration card
* Adds the `New` badge to the Jetpack Boost card integration
* N/A
* Go to `Yoast SEO` -> `Integrations`
* Verify the Jetpack Boost card displays a `New`badge in the header 
*
Fixes https://github.com/Yoast/wordpress-seo/issues/20047
=> Add the 'New' badge to the integration

admin/class-config.php, packages/js/src/first-time-configuration/first-time-configuration-steps.js, packages/js/src/first-time-configuration/tailwind-components/base/image-select.js, packages/js/src/first-time-configuration/tailwind-components/step-header.js, packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js, packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js, packages/js/src/first-time-configuration/tailwind-components/tailwind-modal.js
* We want to change the last step of the `First-time configuration` to make more clear the flow from it to the free webinar page.
* Changes the last step of the `First-time configuration` to highlight the free webinar availability.
*
* Deactivate Yoast SEO Premium if you have it activated
* Go to `Yoast SEO` -> `General` -> `First-time configuration` tab
* Finish the `First-time configuration` and verify:
* the step looks as follows 
* the `Learn how to get the most out of Yoast SEO!` button has the following shortlink: `https://yoa.st/webinar-intro-first-time-config`
* the link above has the query vars added
* Click on `Or go to your SEO dashboard` and verify you switch …
=> Improve webinar registration button in ftc

css/src/admin-global.css, inc/class-addon-manager.php
* We want to update some copy about our error messages.
* Updates copy of the update notification when there is a new update and you don't have a valid subscription.
* Updates copy of the notification centre message when you don't have a valid subscription. 
*
* Open a site with an active premium subscription and all add-ons installed and activated . 
* Make sure all add-on show `view details` in the plugin overview (this means there was a connection with My-yoast made).
* Add `return true` to `/wordpress-seo/inc/class-addon-manager.php`  on line 517 just above the current return of the function `has_subscription_expired`.
* Open the Yoast seo dashboard and make sure the …
=> Improves copy of notifications.

admin/tracking/class-tracking-addon-data.php
* In certain very rare conditions we might get an unrecoverable fatal error while upgrading Yoast SEO in conjunction with Local SEO (or other addons probably) if it hasn't been able yet to save its options in the DB. 
* Fixes a bug where a fatal error would be thrown when upgrading Yoast SEO while having Local SEO active but never executed.
* Note that the fix will be working when upgrading from this version to a later one, because the problem happens even before the new Yoast SEO version is unzipped and has replaced the old one.
It's not easy to test it live. A possible way could be:
* create an instaWP site  with PHP >= 8.0 or use our docker env (the issue doesn't …
=> Fix fatal on upgrade with Local SEO

src/integrations/cleanup-integration.php, tests/unit/integrations/cleanup-integration-test.php
* We want to be more specific in our cleanup routine delete queyr.
* Fixes a non release bug where to many indexables where deleted when they shared an object_id with another indexable.
*
* Disable Free and make sure `WP Crontrol` is installed
* Run the following query to find a post and term with the same id:
``` select * from wp_posts p where id in (select term_id from wp_terms); ```
* Note down one of the ID's and run the following query to confirm: 
* Run ```select * from wp_yoast_indexable where wp_yoast_indexable.object_id= {your id};``` and make sure there are at least 2 records (one for the post and one for the term) 
* if the above is true, remove to …
=> Update cleanup routine query to take object_type into account.

packages/yoastseo/spec/parse/build/buildSpec.js, packages/yoastseo/spec/parse/build/private/filterTreeSpec.js, packages/yoastseo/src/parse/build/build.js, packages/yoastseo/src/worker/AnalysisWebWorker.js
* It is not necessary to tokenize elements that will always be filtered out. This PR moves the step to filter out the tree so that it's before the tokenization step.
* [yoastseo] Filters out elements that we don't want to analyze before tokenizing them.
* The unit tests in `filterTreeSpec` were adapted to be run on an untokenized tree. Most of the existing unit tests are for elements that should always be filtered out, which is now done before tokenization. In addition, tokenizing shouldn't affect the behavior of `filterTree` as it only adds an extra property (`sentences`) to the node. And it's simpler and more efficient to not tokenize the tree in a unit test.
* Confirm …
=> HTML parser - Don't tokenize elements that should always be filtered out

src/helpers/author-archive-helper.php
* The WP_Query used in the `author_has_public_posts_wp()` function can be improved so as to not run unnecessary queries.
* Improves performance when SEO optimization hasn't been completed. Props to @PypWalters.
*
In order to benchmark the performance improvement of the change:
* To have a website with a lot of posts, run the following command in the WP CLI: `wp post generate --count=100000 --post_author=admin` (it assumes that you have a user with ID=1 - let's say it has the `admin` username)
* Or use [this zip](https://drive.google.com/file/d/1PnqKjeRcjxQ8Oy3qTnDSGUy1eztteS_-/view?usp=sharing) to import in your Local WP.
* If after importing, you get a Database error, …
=> Performance improvement for author_has_public_posts_wp

packages/yoastseo/spec/parse/build/private/getSentencePositionsSpec.js, packages/yoastseo/src/parse/build/private/getSentencePositions.js
* The `getSentencePositions` function was failing for texts that had sentences with HTML tags that don't have a closing tag, such as `<img>`. This is because the function was trying to get each node's end tag which would return `undefined` for nodes without end tags and break the functionality. This is fixed by only getting the end tag if the node has one.
* [yoastseo] Do not try to get a descendant node's end tag in the `getSentencePositions` function if the node doesn't have an end tag.
*
* Make sure all unit tests pass.
*
*
Fixes …
=> HTML parser: Make it possible to get sentences from nodes that have descendant nodes without a closing tag

src/integrations/admin/first-time-configuration-notice-integration.php, tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
* We want to add nonce verification to the dismissal of the first time configuration notice.
* Adds nonce verification to the dismissal of the first time configuration notice.
* Adds unit tests to the `First_Time_Configuration_Notice_Integration` class.
*
* Set a new site and install `Yoast SEO` or reset options and notifications with `Yoast Test` plugin.
* Go to `Yoast SEO` -> `General` 
* Make sure you see the notice to start the first time configuration or to complete it.
* With the browser console open on the `Network` tab, dismiss the notice
* In the browser console select the `POST` request to `admin-ajax.php` and make sure the request contains the `nonce` parameter …
=> 20105 add nonce verification to ftc notice dismissal

packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js, packages/yoastseo/src/scoring/assessments/readability/TextAlignmentAssessment.js, packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js, packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js, packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js, packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js, packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js, packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js
* Now that Premium- and product-specific assessments are properly bundled, we should also update their translation domains. We do so in this PR. 
* Assigns translation strings in Premium- and product-specific assessments to their proper domain.
* None.
* See the [Premium PR](https://github.com/Yoast/wordpress-seo-premium/pull/3927) and [Yoast SEO for WooCommerce PR](https://github.com/Yoast/wpseo-woocommerce/pull/901) for testing instructions.  
*
* Translation strings of Premium- and product-specific assessments.
Fixes …
=> Assigns translation strings in Premium- and product-specific assessments to their proper domain

packages/analysis-report/src/AnalysisResult.js, packages/components/src/ScoreAssessments.js, packages/helpers/src/strings/index.js, packages/helpers/src/strings/stripTagsFromHtmlString.js, packages/helpers/tests/strings/stripTagsFromHtmlStringTest.js, packages/js/src/components/IndexingError.js, packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js, packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexing-error.js, packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
* Prevent usage of dangerouslySetInnerHTML in favor of more precise ways
* [@yoast/helpers 0.1.0] Adds `stripTagsFromHtmlString` to the `strings` export. This helper parses the HTML string and strips any HTML tags that are not specified as allowed.
* [@yoast/analysis-report 0.1.0] Strips HTML tags from the AnalysisResult _text_. Allowed tags are: _a_, _b_, _strong_, _em_ and _i_.
* [@yoast/analysis-report 0.1.0] Strips HTML tags from the ScoreAssessment _html_. Allowed tags are: _a_, _b_, _strong_, _em_, _i_, _span_, _p_, _ul_, _ol_, _li_ and _div_.
* [@yoast/search-metadata-previews 0.1.0] Decodes the `shoppingData.price` instead of allowing HTML.
* Strips HTML tags from the IndexingError _message_ (2 actual components). Allowed …
=> 19957 Review usage of dangerouslySetInnerHTML

.github/workflows/integrationtest.yml, tests/unit/bootstrap.php, tests/unit/inc/addon-manager-test.php, wp-seo-main.php, wp-seo.php
*
* Sets the minimum supported WordPress version to 6.1
* I changed the test for the Addon Manager to use the `YOAST_SEO_WP_REQUIRED` constant and reduce the number of lines to edit manually.
* N/A
* N/A
*
Fixes #
=> Set the minimum supported WordPress version to 6.1

packages/js/src/settings/routes/templates/taxonomy.js, src/integrations/settings-integration.php
* In each page related to a taxonomy without a public post type associated we want to add a link to its edit page. 
* Adds a link to a taxonomy edit page in its settings section when the taxonomy has no public post types associated.
* N/A
* Make sure you have installed and activated [CPT UI](https://wordpress.org/plugins/custom-post-type-ui/)
* Go to `CPT UI` -> `Add/Edit Post Types
* specify the slug, e.g. `my-post-type`
* specify the singular and plural labels, e.g. `My post type` and `My Post Types`
* click `Save Post Type`
*   Go to `CPT UI` -> `Add/Edit Taxonomies`
* specify the slug, e.g. `my-taxonomy`
* specify the singular and plural labels, e.g. `My Taxonomy` and …
=> Add a link to the taxonomy edit page when there are no public post types associated to it

packages/yoastseo/src/worker/AnalysisWebWorker.js
* With this PR, we make it possible to add translations from other domains to the AnalysisWebWorker. This is necessary because we changed the domains for Premium assessments to `wordpress-seo-premium` and for e-commerce assessments to `yoast-woo-seo`. 
* Adds a function to add translations for other domains to the webworker.
*
* Test along with the Premium PR.
*
* Translations inside the AnalysisWebWorker -- so (translations of) feedback for assessments. 
Fixes https://github.com/Yoast/plugins-automated-testing/issues/654
=> Adds a function to add translations for other domains to the webworker

packages/yoastseo/src/worker/AnalysisWebWorker.js
* A console error related to translations appeared when opening a post on a site that's in a language that doesn't have translations, i.e. English.
* This was caused by the change in [this PR](https://github.com/Yoast/wordpress-seo/pull/20204/files) which tries to get the domain from each translation object without checking whether that object is null.
* [wordpress-seo-premium] Fixes a bug where a console error would appear when opening a post on English sites.
* A safeguard was added that checks whether each translation object within the `translations` object is truthy before retrieving the translation.
* An alternative would be to avoid passing an empty translations objects to the worker in the first place. But this would …
=> Fix console error related to translations for English sites

src/integrations/watchers/indexable-attachment-watcher.php, tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
* Add unit test to Indexable attachment watcher class
* adds unit tests to indexable attachment watcher.
* Removed default from original class that couldn't be reached. 
* Generate test coverage report and check `Indexable_Attachment_Watcher` is 100% covered.
*
*
Fixes [Add more unit tests for the #19388 PR](https://github.com/Yoast/wordpress-seo/issues/19747)
=> Indexable attachment watcher unit tests

admin/import/plugins/class-import-seo-framework.php, tests/integration/admin/import/test-class-import-seo-framework.php
* See: https://github.com/sybrew/the-seo-framework/issues/626#issuecomment-1488912270
* Renames "SEO Framework" to "The SEO Framework".
*
* install and activate The SEO Framework plugin
* edit a post and add at least some values in the SEO metabox (e.g. title and description)
* publish the post
* disable The SEO Framework plugin
* enable Yoast SEO
* visit Yoast SEO > Tools > Import and Export, then the last tab "Import from other SEO plugins"
* check that the select displays "The SEO Framework" instead of "SEO Framework"
*
*
Fixes #
=> Make Sybre happy

packages/js/src/academy/app.js
*
* Fixes an unreleased bug where the textual upsell link in the Academy page would be missing the expected params and data attributes. 
*
* Visit the Academy page
* check that the URL for "Maximize your SEO game by purchasing Yoast SEO Premium, which grants you unlimited access to all courses" contains the expected tracking params
* check that the `<a>` tag contains the expected attributes `data-action="load-nfd-ctb" data-ctb-id="f6a84663-465f-4cb5-8ba5-f7a6d72224b2"` as the upsell buttons do.
*
*
Fixes …
=> Add params and data attributes to upsell link in the Academy page

admin/tracking/class-tracking-addon-data.php
* In certain rare conditions we might get a fatal error on the Yoast SEO admin pages in conjunction with WooCommerce SEO if it hasn't been able yet to save its options in the DB.
* Fixes a bug where a fatal error would be thrown when visiting Yoast SEO admin pages while Yoast SEO for WooCommerce is active but never executed.
* very similar to https://github.com/Yoast/wordpress-seo/pull/20090 but that one occurred only on upgrade, so the fix was proactive for the future. In this case, it will already work in the current version.
* create an instaWP site with PHP >= 8.0 or use our docker env (the issue doesn't happen on Local by Flywheel because tracking collection doesn't …
=> Fix fatal error on Yoast admin pages with WooCommerce SEO

css/src/elementor.css, packages/js/src/initializers/elementor-editor-integration.js
* Elementor 3.13 beta 1 changes the markup in their sidebar with [this PR](https://github.com/elementor/elementor/pull/21733), resulting in a broken Yoast SEO tab. It will be reverted in a following beta but it's going to be part of 3.14 so we want to be prepared.
* We also want make sure the Yoast tab can be accessed via keyboard.
* Ensures compatibility with upcoming Elementor accessibility improvements.
* The relevant markup is going to change from `div > a` to `button > span` for a11y reasons. The rendering event used to be attached to the `a` tag. I've decided to target the `button` tag instead, via the `data-tab` attribute, for 2 reasons:
1. backwards compatibility
2. consistency with the other tabs, where the event is …
=> Fix Elementor 3.13 compatibility

config/dependency-injection/services.php
*
* Fixes an unreleased bug in Premium where the dependency injection container would display a deprecation warning about `wpdb`.
*
* NA
* Install and activate Yoast SEO Free RC containing this and the matching Premium RC 
*  Install and activate Query Monitor
* Go to Yoast Settings
* Dismiss Yoast FTC notification
* see that you don't get any PHP error in the AJAX response in the console:
"The "wpdb" service is private, getting it from the…er directly and use dependency injection instead.', file: '/mnt/plugins/wordpress-seo/vendor_prefixed/symfony/dependency-injection/Container.php'" …
=> Set wpdb registration in the container public

tests/integration/repositories/seo-links-repository-test.php, tests/unit/integrations/academy-integration-test.php, tests/unit/repositories/seo-links-repository-test.php
* Add unit tests and integration tests for `SEO_Links_Repository` class.
* Adds unit tests and integration tests for `SEO_Links_Repository` class.
*
* Produce test coverage report and check this class has 100% coverage.
*
*
=> Seo links repository tests

src/integrations/academy-integration.php, tests/unit/integrations/academy-integration-test.php
* Previously we were using the `WPSEO_Plugin_Availability` class to check if Yoast SEO Local is active, but this does not work in production environments. We switched to the `WPSEO_Addon_Manager` class instead.
* Fixes an unreleased bug where the `Local SEO` course in the `Academy` page would not be active when Yoast SEO Local is active.
* N/A
* Please check this PR by uploading an artifact to your WordPress installation (or the latest RC)
* Install `Yoast SEO Local` and don't activate it
* Go to `Yoast SEO` -> `Academy` and verify the `Local SEO` course:
* has no `Premium` badge
* shows the `Start free trial lesson →` link
* shows the `Unlock with Premium` button
* Now …
=> Use the Addon_Manager to check if addons are activated

src/analytics/application/missing-indexables-collector.php, src/analytics/application/to-be-cleaned-indexables-collector.php, tests/unit/analytics/application/missing-indexables-collector-test.php, tests/unit/analytics/application/to-be-cleaned-indexables-collector-test.php
* We need to add a grouping array around the indexable tracking, so we can pick them up in our back-end.
* Adds a grouping array around our new non-released tracking data.
*
* Add the following code to `/wordpress-seo/admin/class-admin.php` at the end of the constructor at around line 118.
* Notice the closing `}` after the admin init this is to close out the constructor.
```
add_action( 'admin_init', [ $this, 'send' ], 1 );
}
public function send() {
$collector->add_collection( new WPSEO_Tracking_Default_Data() );
$collector->add_collection( new WPSEO_Tracking_Server_Data() ); …
```
=> Adds a grouping array around the new indexable tracking info.

admin/tracking/class-tracking.php
* We want to re-enable the indexable tracking.
* Adds tracking for our indexable data.
*
* Smoke test the admin pages to make sure there are no fatals.
*
*
Fixes #
=> Re-enable indexing.

packages/js/package.json, packages/js/src/inline-links/inline.js
* Fix position of the popover box when editing a link in block editor. 
* Fixes a bug where the link popover position in the block editor would be positioned incorrectly when adding or creating links.
* Refactored the component to reduce complexity and remove es lint warnings.
* Open a post or page in the block editor.
* Add a link to the first word in the text.
* A popover would appear for the link.
* Check popover is fully visible when increasing screen resolution to 150%.
How it shouldn't look:
How it should look:
* Toggle `Open in new Tab` add a url and save.
* View page and inspect the link.
* Check it has `target="_blank"` attribute.
* Toggle `Mark as nofollow` and …
=> 20015 difficulty in adding a link in the editor as the box positioning is off

tests/integration/admin/watchers/test-class-indexable-post-watcher.php, tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
Fixes two situations which caused tests to not be run.
* Tests: fix incorrect test class name
* Tests: fix test not running due to duplicate array key in data provider 
* _N/A_
=> Tests: fix some tests which werent being run

tests/unit/helpers/crawl-cleanup-helper-test.php, tests/unit/initializers/crawl-cleanup-permalinks-test.php, tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
`set_up()` fixtures should "set up" the environment for the test. The code in the setup should not be regarded as part of the test itself.
* _N/A_
=> Tests: `set_up()` methods cannot "cover" anything

tests/unit/doubles/inc/addon-manager-double.php, tests/unit/inc/addon-manager-test.php
The `Addon_Manager::convert_subscription_to_plugin()` parent method received a new `$plugin_file` parameter over a year ago and while the parameter _was_ added to the `Addon_Manager_Double::convert_subscription_to_plugin()`, the parameter was not passed to the parent class, nor documented.
This fixes it and updates the associated test expectation.
* _N/A_
=> Tests: sync `Addon_Manager_Double` with parent class

config/dependency-injection/deprecated-classes.php, src/loader.php, tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
* PHP cross-version compatibility
* PHP cross-version compatibility
... to prevent (future) issues with the use of function calls with named parameters.
Ref: https://developer.wordpress.org/reference/functions/_deprecated_function/
* _N/A_
=> QA: various parameter name fixes

inc/class-wpseo-meta.php
No need to use `array_map()` with a closure when there is a PHP (5.5+) native function to do exactly the same.
Ref: https://www.php.net/manual/en/function.array-column.php
* _N/A_
=> CS/QA: use the appropriate PHP native function

src/exceptions/indexable/author-not-built-exception.php, src/exceptions/indexable/not-built-exception.php, src/exceptions/indexable/post-not-built-exception.php, src/exceptions/indexable/post-type-not-built-exception.php, src/exceptions/indexable/term-not-built-exception.php
=> CS/QA: use `self` when refering to current class

admin/import/plugins/class-import-seopressor.php, inc/class-upgrade.php, inc/class-wpseo-meta.php, inc/options/class-wpseo-options.php, inc/sitemaps/class-sitemap-image-parser.php, inc/sitemaps/class-sitemaps-renderer.php, lib/migrations/table.php, lib/model.php, src/actions/wincher/wincher-keyphrases-action.php, src/generators/schema/faq.php, src/presenters/open-graph/image-presenter.php, tests/integration/admin/test-class-database-proxy.php, tests/integration/repositories/seo-links-repository-test.php, tests/integration/test-class-rewrite.php, tests/unit/actions/importing/abstract-aioseo-importing-action-test.php, tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php, tests/unit/admin/admin-features-test.php, tests/unit/builders/indexable-builder/maybe-build-author-indexable-test.php, tests/unit/helpers/crawl-cleanup-helper-test.php, tests/unit/helpers/social-profiles-helper-test.php, tests/unit/repositories/orm-test.php, tests/unit/surfaces/helpers-surface-test.php, tests/unit/surfaces/open-graph-helpers-surface-test.php, tests/unit/surfaces/schema-helpers-surface-test.php, tests/unit/surfaces/twitter-helpers-surface-test.php
* Code quality
* Code quality
Variable is already being imported earlier on in the same function.
The results of a function call do not need to be assigned to a variable, unless that variable will be used later on.
Along the same lines, when looping through an array, the key of the array item does not need to be assigned unless it will be used.
Variables which are not being used have no business existing. All of these are variables which are being assigned a value, but are subsequently never used.
* _N/A_
=> QA: fix various unused/undeclared variable issues

inc/wpseo-functions-deprecated.php, lib/abstract-main.php, src/surfaces/helpers-surface.php, src/surfaces/open-graph-helpers-surface.php, src/surfaces/schema-helpers-surface.php, src/surfaces/twitter-helpers-surface.php, src/surfaces/values/meta.php
... with a reference to the upstream issue which should fix it (after which the annotation should be removed).
* _N/A_
This is a docs-only change and should have no effect on the functionality. If the build passes (linting, test runs), we're good.
=> CS/QA: update some ignore annotations

src/integrations/admin/crawl-settings-integration.php
* Code quality
* Code quality
Commit 47baef5bed4302c4bb76212339d327d462cf82fa removed support for the `$is_network` parameter, but there were still two method calls within the class passing that parameter.
Fixed now.
* _N/A_
=> CS/QA: don't pass parameter which doesn't exist

packages/js/src/settings/routes/crawl-optimization.js, src/integrations/front-end/robots-txt-integration.php, tests/unit/integrations/front-end/robots-txt-integration-test.php
* Add `/page/*/?s=` pattern when preventing crawling of internal site search URLs.
* Tightens crawl optimization site search blocking rules.
*
* Go to `Yoast SEO`->`Settings`->`Advanced`->`Crawl optimisation`
* Toggle `Prevent crawling of internal site search URLs`
* Check description of the toggle contain `/page/*/?s=`
* Go to http://basic.wordpress.test/robots.txt
* Check you see: 
```
Disallow: /?s=
Disallow: /page/*/?s=
Disallow: /search/
```
*
Fixes [Tighten crawl optimization site search blocking rules#20103](https://github.com/Yoast/wordpress-seo/issues/20103)
=> 20103 tighten crawl optimization site search blocking rules

src/commands/index-command.php, src/conditionals/wp-cron-enabled-conditional.php, src/helpers/indexing-helper.php, src/integrations/admin/background-indexing-integration.php, tests/unit/commands/index-command-test.php, tests/unit/conditionals/wp-cron-enabled-conditional-test.php, tests/unit/generators/schema/webpage-test.php, tests/unit/helpers/indexing-helper-test.php, tests/unit/integrations/admin/background-indexing-integration-test.php
This reverts commit 8d8ba3636388905a825a961ca885b657a6838cd6, reversing changes made to b722cce4b8b8d5ad53c5fd312332522f32aad249.
* Re-introduces https://github.com/Yoast/wordpress-seo/pull/20005 that got reverted because we wanted to postpone it by one release.
* Sets up background indexation via WP Cron.
* Fixes a bug where indexables were created when using the wp yoast index WP CLI command on a staging site.
**_Copying over the Relevant technical choices from_** [the original PR](https://github.com/Yoast/wordpress-seo/pull/20005).
* Prominent words need frontend libraries in order to be indexed, so the cron indexation doesn't cover those
* We don't deal with notifications at all, because these look to be related to the manual …
=> Background cron indexation

tests/unit/builders/indexable-term-builder-test.php, tests/unit/repositories/seo-links-repository-test.php
Both the `$expected` variable, as well as the `$actual` variable were unused, which gives me the impression the intention was to test that those are the same.
The `$expected` parameter received from the data provider was unused, which gives me the impression the intention was to also test the function call result.
In each of these tests, an `$expected_result` variable is being set, but subsequently never used, which gives me the impression the intention was to also test the function call result.
* _N/A_
=> Tests: add missing assertions

src/helpers/current-page-helper.php
* Code quality
* Code quality
These functions had a documented return type, which was previously adhered to, but now, they suddenly had an extra return type of `null`.
Fixed now.
@enricobattocchi @vraja-pro Based on the file history, I can see these functions were changed a couple of months back and that those changes were then partially reverted.
I wonder if the changes from then should be completely reverted instead, but at least this fix will make the functions behave according to their specifications again.
* ???
=> CS/QA: fix inconsistent return types

.github/workflows/test.yml, .gitignore, README.md, composer.json, phpunit-integration.xml.dist, phpunit.xml.dist
* Enable test code coverage monitoring.
* Enable test code coverage monitoring.
This commit makes the necessary changes to start recording and uploading code coverage data to Coveralls.
Includes:
* Updating the GH Actions `test` workflow to run the high/low PHP version builds with code coverage and upload the results.
* Updating the PHPUnit config to record coverage and show an inline code coverage summary.
* Ignoring the potentially generated code coverage files in the `build/*` directory to prevent it being committed.
* Adding scripts to the `composer.json` file to run code coverage.
* Adding a code coverage badge to the README.
Notes:
* Coverage will be recorded using `Xdebug` as the code coverage driver.
* Recording code …
=> CI/QA: start recording code coverage

src/presentations/archive-adjacent-trait.php, src/presentations/indexable-author-archive-presentation.php, src/presentations/indexable-home-page-presentation.php, src/presentations/indexable-post-type-archive-presentation.php, src/presentations/indexable-term-archive-presentation.php
This is a follow up PR to PR https://github.com/Yoast/wordpress-seo/pull/18820 in which we found out that this change was not possible until support for PHP 5.6 had been dropped.
As that has now happened, we can clean up the temporary work-around.
=> PHP 8.2 | Indexable_*_Presentation: declare the property in the trait instead

packages/js/src/redux/selectors/WincherSEOPerformance.js
* On certain pathological situations, additional keyphrases can be stored in a wrong way in the DB. This can lead to a fatal error for the Wincher integration which cannot be solved except by editing the DB. We should add defensive coding for it.
* Fixes a bug where the Yoast SEO metabox would crash in conjunction with Yoast SEO Premium when additional keyphrases are stored in the DB in a malformed way.
* It was found while working on https://github.com/Yoast/wordpress-seo-premium/issues/3872
* use Premium with [this fix](https://github.com/Yoast/wordpress-seo-premium/pull/3975)
* create a post
* Set the _yoast_wpseo_focuskeywords field for that post to [""] in the …
=> Prevents metabox crashing when the additional keywords objects are malformed

.github/workflows/cs.yml, .github/workflows/jslint.yml, .github/workflows/jstest.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Only run the workflows when there is a chance that the result of the workflow run will be different from before.
The path selection is set up to cast a wide net to make the risk of the workflows not running when the build could potentially break as small as possible.
This means that, aside from files of the type being checked in the workflow changing, the workflow will also run when:
* The configuration used changes.
* Dependencies used in the workflow may potentially have changed.
* Composer scripts used in the workflow may potentially have changed.
* Shell scripts used in the workflow have changed.
* The workflow itself changes.
* Miscellaneous related files have changed.
Note: the lists of …
=> GH Actions: run workflows more selectively

inc/sitemaps/class-taxonomy-sitemap-provider.php
* Like we do with posts, we should stop adding terms with custom canonical URLs in the taxonomy sitemaps.
* Fixes a bug where terms with custom canonical URLs would get added in the sitemap.
* 
* Create 3 categories (or any other taxonomy tyoe) with posts (or CPT) assigned to them.
* Go to the edit page of the categories
* For categoryA:
* leave the `Canonical URL` field in the Advanced tab of the Yoast metabox, empty.
* For categoryB:
* visit its frontend and copy its URL
* paste the URL in  the `Canonical URL` field in the Advanced tab of the Yoast metabox.
* For categoryC:
* put a completely different URL in  the `Canonical URL` field in the Advanced tab of the Yoast …
=> Don't add terms with custom canonical URLs in the sitemap

packages/js/src/components/WincherPerformanceReport.js
Currently, when there are no tracked keywords, nothing is displayed to the user, and only a blank box is rendered.
Related to issue: https://github.com/Yoast/wordpress-seo/issues/20376
* Fixes an unreleased bug where the Wincher widget in the dashboard would be displayed empty when no keywords were tracked.
- Wincher is connected
- Create a post with keyphrase and track it in Track SEO Performance metabox
- Uncheck tracking toggle in Track SEO Performance metabox and save post
- Make sure that there are no other keyphrases that are tracked by wincher
- Visit dashboard and check Yoast SEO/Wincher widget
- A message should be displayed if user is connected to Wincher, and no keywords are tracked.
Fixes https://github.com/Yoast/wordpress-seo/issues/20376
=> Fix wincher blank box when no keywords are tracked

packages/js/src/settings/routes/crawl-optimization.js
* Continuing from [this PR](https://github.com/Yoast/wordpress-seo/pull/20340), we want to create a new settings section to move our new AdsBot crawling feature, because the existing sections weren't as relevant.
* Adds a new section in the Crawl Optimization settings, so that we move the new AdsBot feature there.
*
Final place/order should be determined as per [this](https://yoast.slack.com/archives/C03KU0EHCNQ/p1686041960101719?thread_ts=1684735243.469229&cid=C03KU0EHCNQ), but for now, the place of the new sections is after the `Remove unused resources` and before the `Internal site search cleanup` sections:
* Confirm that when going to the Crawl Optimization settings …
=> Create new section for the AdsBot feature

src/analytics/application/missing-indexables-collector.php, src/analytics/application/to-be-cleaned-indexables-collector.php, src/analytics/domain/missing-indexable-bucket.php, src/analytics/domain/missing-indexable-count.php, src/analytics/domain/to-be-cleaned-indexable-bucket.php, src/analytics/domain/to-be-cleaned-indexable-count.php
* Fixes an edge case where the tracking would fatal when the query fails to get a result.
* Fixes a bug where a fatal occurs after updating the plugin due to a failed query
*
* Add the following code to `class-admin`: The add_action part should be at the end of the `__construct` method at around line 116.
``` 
add_action( 'admin_init', [ $this, 'send' ], 1 );
}
public function send() {
$collector->add_collection( YoastSEO()->classes->get( Yoast\WP\SEO\Analytics\Application\To_Be_Cleaned_Indexables_Collector::class ) );
echo '<pre>';
print_r( WPSEO_Utils::format_json_encode( …
```
=> Removes typing and adds null check.

src/integrations/front-end-integration.php, tests/unit/integrations/front-end-integration-test.php
* We do not want to show `twitter:label{n}` and their respective `twitter:data{n}`  metatags on static home pages. See also [this thread](https://yoast.slack.com/archives/CGUL0LDQS/p1686238107797379?thread_ts=1686234652.128109&cid=CGUL0LDQS).
* Removes any meta tags for enhanced Slack sharing from static home pages.
*
* Set your WordPress site to display a static page as the home page.
* Go to your WordPress admin.
* Go to _Settings_ > _Reading_ in the sidebar.
* For "Your homepage displays" choose the option "A static page (select below)".
* For "Homepage" select a page in the drop down box that you want to show on the home page.
* Visit the home page of your WordPress …
=> Disables twitter:data meta tags on static home pages.

admin/watchers/class-slug-change-watcher.php
We are actually getting the the term taxonomy id in this method and not the term id. The term id is not always the same as the term_taxonomy_id. Therefore the change is to avoid getting the wrong term in those cases.
* We want to the way we get the term object for `delete_term_taxonomy` action.
* Changes the way we get the term object for `delete_term_taxonomy` action.
*
* Create several tags. for example `apple` and `orange`
* Modify the wp_term_taxonomy table so that the values for term_id and term_taxonomy_id don't match 
* ![image-2022-01-27-10-44-23-926](https://user-images.githubusercontent.com/7323966/235624370-504f10ab-b920-49fa-89b0-54edfd1454a0.png) In this …
=> changed the way we get the term object

packages/js/src/analysis/collectAnalysisData.js, packages/js/src/elementor/containers/SnippetEditor.js, packages/js/src/helpers/replacementVariableHelpers.js, packages/js/tests/containers/mapEditorDataToPreview.test.js, packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js, packages/search-metadata-previews/tests/SnippetEditorTest.js, packages/yoastseo/src/scoring/assessments/SCORING SEO.md, packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
* We want to prepare the 20.10 RC by cherry-picking #20354 into `trunk` from the feature branch `feature/lingo-fixes`. 
* Merges part of the feature branch `feature/lingo-fixes` into trunk. 
* We merge only a part of the feature branch, as we do not want to yet merge other stuff on that branch. 
* See #20354 .
*
*
Fixes --
=> Cherry-picks the PR to exclude separator and site title replacements from title length calculations

packages/js/src/support/app.js
* We want to trigger the help scout beacon also when the tracking is disabled.
* Updates the `contact our support team` button when tracking is disabled.
* 
* Install also Yoast premium and activate
* Got to `Yoast SEO`->`General`->`First time configuration`->`PERSONAL PREFERENCES` and disable tracking:
* Go to `Yoast SEO`->`Support` and check the beacon has a question mark instead of `Need help?`
* Click on `Contact our support team` button
* Check you see a popup and click ok
* Check you see the form in the beacon and it's button is `Need help?`
* …
=> fixing contact our support team button when tracking is disabled

packages/js/src/helpers/replacementVariableHelpers.js
* In this PR, we added an attribute, `filteredSEOTitle`. However, we don't pass this attribute in the social previews, leading to a null-pointer exception when Yoast SEO Premium was activated.
* Fixes an unreleased bug where the Yoast SEO metabox was broken when Yoast SEO Premium was activated.
* Added defensive programming to this variable.
* Activate Premium.
* Make sure that, without this PR, the metabox is not loaded.
* Require this branch and re-build Premium.
* Make sure that, with this PR, the metabox is now loaded.
* 
* The social …
=> Adds defensive programming to the filteredSEOTitle attribute

packages/js/src/components/WincherPerformanceReport.js, packages/js/src/components/WincherSEOPerformance.js
* Remove calls to wincher APIs when wincher integration is active but user is not logged in to a wincher account.
* Removes calls to wincher APIs when wincher integration is active but user is not logged in to a wincher account.
* Go to Yoast SEO->Integration
* Enable Wincher integration if it is disabled.
* Go to Dashboard
* Check in the Wincher block it is not connected to a Wincher account.
* Inspect page
* Check no console errors related to Wincher apis
*
*
Fixes #20424
=> Remove calls to logged-in-only Wincher apis when user is not logged in

css/src/tailwind.css, packages/tailwindcss-preset/index.js
* Fix the default color for placeholder text throughout the plugin.
* [@yoast/tailwindcss-preset 0.1.0]  Fixes the default color for placeholder text throughout the plugin.
*
* Go to `Yoast SEO`->`Settings`->`Site connections`
* Inspect placeholder for `Add verification code` for input fields, you can do that by check the `Show user agent shadow Dom` in the inspect Developer Tools settings in chrome.
* Check the color of the placeholder is `rgb(100 116 139 / var(--tw-placeholder-opacity));`
* Go to `Yoast SEO`->`General`->`First time configuration`->`SOCIAL PROFILES`
* Check the color of the placeholder text in the input fields is `rgb(100 116 139 / …
=> added default color for placeholder text

packages/js/src/support/app.js
* As per [this](https://yoast.slack.com/archives/C03KU0EHCNQ/p1686827839006849), a slight change in the copy of the button in the Github bug report card in the new support page.
* Changes copy of the button in the Github bug report card in the new support page.
*  Visit the new support page
* Verify that the 3rd card in the `Additional resources` section is like this:
* Mainly that the button has the `Write a bug report` copy
*
Fixes #
=> Change CTA copy of bug report card

admin/watchers/class-slug-change-watcher.php
* Fix notice when deleting a term that has `term_taxonomy_id` that is different from `term_id`.
* Fixes a bug where the wrong taxonomy name would appear in the notice when deleting a term.
*
* Make sure `Yoast Premium` is disabled.
* Go to `Posts`->`Tags` and create several tags (for example apple and orange)
* Modify the `wp_term_taxonomy` table so that the values for `term_id` and `term_taxonomy_id` don't match. (Change the `term_taxonomy_id`), check there is no `term_id` that matches the `taxonomy_term_id`.
* Go to `Posts`- > `Tags`, refresh, and delete one of the tags (for example, apple)
* Check no console errors appear
* Check message contain the name of the …
=> 807 minorphp error after term was deleted taxonomy was not specified at notification

packages/js/src/inline-links/inline.js
* Fixes a bug introduced in 20.9 by https://github.com/Yoast/wordpress-seo/pull/20270
* Fixes a bug where adding a link in the block editor would result in displaying the URL instead of the post title.
*
* Try to reproduce #20430 in you setup with 20.10/RC3
* if you can, switch to this fix and see the issue is resolved.
*
*
Fixes #20430
=> Pass the expected object instead of the title string

src/helpers/crawl-cleanup-helper.php, tests/unit/helpers/crawl-cleanup-helper-test.php
* Adds  default allowlist to "Remove unregistered URL parameters" in Advanced: URL cleanup settings.
* Adds utm_source, utm_medium, utm_campaign, utm_term, utm_content, gclid and 
gtm_debug to the default allowlist for the "Remove unregistered URL parameters" setting.
*
* Open Yoast Seo->Settings->Advanced->Crawl optimization 
* Scroll till section Advanced: URL cleanup
* Check "Remove unregistered URL parameters"
* Save settings.
* Logout from current user or open site in incognito mode.
* Append test parameter in site - for example unknown_parameter=yes so you site url will be https://www.example.com/?unknown_parameter=yes
* page should be redirected and the parameter …
=> 20066 add default allowlis to remove unregistered url parameters

packages/js/src/settings/store/pages.js, src/integrations/settings-integration.php
* We want to check if the post is not password protected.
* Fixes a non released bug where pages would still show up when they were password protected.
*
* The test instructions for this live in : https://github.com/Yoast/wordpress-seo-premium/pull/3999
*
*
Fixes #
=> Add password protection check

packages/js/src/settings/routes/crawl-optimization.js
* In [a previous PR](https://github.com/Yoast/wordpress-seo/pull/20452) we added an allowlist for the "Remove unregistered URL parameters" setting. In this PR we forgot to provide information to the user about the defaultly allowed url parameters. In the current PR we add feedback to the user.
* Search team was notified of this change as well as of the change in the previous PR in [this thread](https://yoast.slack.com/archives/C012CJJ46P7/p1688045368543239).
* Adds information to the "Remove unregistered URL parameters" setting in the crawl settings about which URL parameters are always allowed.
*
* Open Yoast SEO -> Settings -> Advanced -> Crawl optimization.
* Scroll …
=> Add information about the allowlist for users.

inc/options/class-wpseo-option-titles.php, packages/js/src/settings/components/formik-page-select-field.js, packages/js/src/settings/store/pages.js, src/integrations/settings-integration.php
*
* Changes the default value for the site policies options to `0` and adds `None`  as a selectable option in the settings.
* Important: this sets the default value to `0` while it used to be `false`. since the feature has not been released yet, no upgrade code has been added. It's very important then to test this PR on a clean environment where the values has not been set yet.
* **install on a clean environment** (see above the technical reason)
* Install and activate the latest Premium RC
* Go to `Yoast SEO` -> `Settings` -> `Site representation`
* Select organisation and add name and logo.
* Visit `Site basics` -> `Site policies` and check they are all set to `None` by …
=> Add `None` option to site policies

packages/js/src/settings/routes/site-connections.js
* The URL of the Google Search Console was updated from `https://www.google.com/webmasters/verification/verification` to `https://search.google.com/search-console/users`. After [the original task](https://github.com/Yoast/wordpress-seo/issues/20404) was created, the old URL started to redirect to the new one, but it was still preferable that our link gets updated.
* This task has a complementary one for Shopify: [here](https://github.com/Yoast/shopify-seo/pull/1237)
* Updates the verification link to the Google Search Console in the Site connections section in Settings.
*
* Activate the currently released version of Free
* On the left-side menu go to Yoast SEO > Settings …
=> Update the google search console verification link

admin/formatter/class-metabox-formatter.php, admin/metabox/class-metabox.php, packages/js/src/components/SchemaTab.js, packages/js/src/components/WooCommerceUpsell.js, packages/js/src/containers/SnippetEditor.js
* Add an ad to metabox schema tab and google preview section on product pages when WooCommerce is active and WooCommerce SEO addon is not active.
* Adds an ad to metabox schema tab and google preview section on product pages when WooCommerce is active and WooCommerce SEO addon is either not installed or not active.
*
* Install Woocommerce
* Create a product
* Go to the meta box and check Google Preview has an upsell add:
* Check the link on the upsell button is yoa.st/product-google-preview-metabox
* Click on the upsell button and check that your are redirected to the upsell page in a new tab and the url contains the platform parameters.
* Go to Schema tab and check the …
=> Add yoast woo ad in google preview on the product pages and in the "schema" tab in the sidebar/metabox 

packages/js/src/settings/components/formik-page-select-field.js, packages/js/src/settings/store/pages.js, packages/ui-library/src/elements/autocomplete/index.js, packages/ui-library/src/elements/autocomplete/stories.js, packages/ui-library/src/elements/autocomplete/style.css
* Add an easer way to reset autocomplete field with an X button.
* [@yoast/ui-library 0.1.0] Add a clear button to nullable autocomplete field.
*
* Install and activate `Yoast Premium`
* Add some sample pages.
* Go to `Yoast SEO`->`Settings`->`Site representation`
* Add logo and name to the organisation.  
* Go to `Site basics`
* Scroll to `Site policies`
* Check you see the default is "None"
* Add some pages to the different policies.
* Check you see an `X` to clear the selection
* Use a screen reader and check the text for the `X` is `Clear selection`.
* Go to home page and check the policy page appears in the schema.
* Go back to `Site policies`
* Click on the `X` of …
=> 4009 improve site policies select menu

config/dependency-injection/loader-pass.php
* Bug fix: building DI container was broken for Windows.
* Fixes a bug where building the DI container would silently fail when running on Windows.
Follow up on #20074, which changed the `Loader_Pass` class to compare paths against (other) paths with hard-coded forward slashes.
This silently broke the Dependency injection layer for anyone compiling on Windows, i.e. the DI container scripts would run without errors, but once the DI container is attempted to be used, everything breaks.
This commit should fix that in a similar way as a previous similar issue was fixed in another part of the DI container setup (PR #16364).
Easiest way to reproduce the original issue is as …
=> Dependency injection: fix `Loader_Pass` being broken on Windows

inc/class-wpseo-utils.php, wp-seo-main.php
* We want to replace our custom way we flush rewrite rules with WP core `flush_rewrite_rules` method.
* The difference is that the WP method updates the `rewrite_rules` and other safeguards while the custom methods deletes the content of the rewrite rules option in the data base.
* Fixes a bug where 404 responses would occur when updating or deactivating the plugin because of incorrect flushing of the rewrite rules.
* WP core function `flush_rewrite_rules` has a lot of safeguards, like:
* Making sure all plugins have registered their rewrites
* Clearing rewrites from the Apache .htaccess if needed
* Actually re-populating the rewrite rules in the same call (and not just leaving it empty for the next call)
* This PR is an …
=> used WP core function to flush rewrite rules

inc/class-addon-manager.php, tests/unit/doubles/inc/addon-manager-double.php, tests/unit/inc/addon-manager-test.php
* We want to fix some translations.
* Fixes some translations
*
* Follow same test instructions from #20014
*
*
Fixes [#20468](https://github.com/Yoast/wordpress-seo/issues/20468)
=> fixed tag in translation for notification from the add-on manager

src/analytics/application/to-be-cleaned-indexables-collector.php, src/integrations/cleanup-integration.php, src/repositories/indexable-cleanup-repository.php, tests/unit/analytics/application/to-be-cleaned-indexables-collector-test.php, tests/unit/integrations/cleanup-integration-test.php, tests/unit/repositories/indexable-cleanup-repository-test.php
* We want our cleanup routine to work also on multisites.
* Fixes a bug where the cleanup routine would throw an error when on multisites.
*
To test if the count query still shows the right amount do the following:
Before testing, install WP control plugin.
* Start up a multisite.
* Do the following in one of the subsites.
* Go to `Yoast SEO`->`Settings`->`Advanced`->`Author archives` and make sure Author archives are enabled.
* Create a new author user, and assign the author to a post. 
* Visit the post to make sure there is a indexable made with object_type `user`
* Go to `My sites`->`Network Admin`->`Users` and remove that author user.
* Add the following code to …
=> Update cleanup to be allow multisites.

src/integrations/admin/admin-columns-cache-integration.php, tests/unit/integrations/admin/admin-columns-cache-integration-test.php
* We want to add some defensive coding in our admin columns cache integration.
* Fixes a bug where an error could occur when an indexable was outdated. Props to @jaimearroyonavia.
*
* Make sure you have ACF, Query monitor and a free version that is not this PR/RC
* Add the following filter to your functions.php
```
add_filter( "wpseo_indexable_forced_included_post_types", function($data) {
$data[] = 'acf-field-group';
return $data;
} );
```
* Create a new ACF field group on /wp-admin/edit.php?post_type=acf-field-group
* After saving remove the filter and run the following query:
`Update wp_yoast_indexable set version=1 where object_sub_type='acf-field-group';
* Go to …
=> Adds defensive coding in the admin columns cache integration.

src/content-type-visibility/application/content-type-visibility-dismiss-notifications.php, src/content-type-visibility/application/content-type-visibility-watcher-actions.php, src/integrations/watchers/indexable-post-type-change-watcher.php, src/integrations/watchers/indexable-taxonomy-change-watcher.php, tests/unit/content-type-visibility/application/content-type-visibility-dismiss-notifications-test.php, tests/unit/integrations/watchers/indexable-post-type-change-watcher-test.php, tests/unit/integrations/watchers/indexable-taxonomy-change-watcher-test.php
* We want to exclude some post types and taxonomies in the indexable watchers.
* Improve the `maybe_dismiss_notification` method to reduce DB queries.
* Fixes a bug where notification for new content type in the notification center would not be dismissed when installing elementor and reviewing the new content types.
* No need for upgrade routine since the watcher is hooked to `admin_init`.
* Install and activate Elementor.
* Check a for notification for new content type appears in the notification center
* Click on the link of that notification to review the new content.
* You will be redirected to the `Yoast SEO`->`Settings` page
* Check for a notification in the bottom …
=> 20505 notification for new content type not excluding

inc/class-wpseo-utils.php, wp-seo-main.php
* Reverts changing the way we flush rewrites.
* Reverts a not released bugfix.
*
*
*
*
Fixes [#](https://github.com/Yoast/plugins-automated-testing/issues/900)
=> Revert "used WP core function to flush rewrite rules"

admin/views/tabs/dashboard/dashboard.php
Applies a fix for the currently open issue [On the Yoast SEO Dashboard, "See who contributed to Yoast SEO" link opens in the same browser tab #20483](https://github.com/Yoast/wordpress-seo/issues/20483).
* Adds an attribute to the link "See who contributed to" to open in a new browser tab, located in the General tab.
* N/A
* Go to Yoast SEO > General > Dashboard page
* Click on "See who contributed to Yoast SEO" link
* The [link](https://yoast.com/about-us/team/) should open within a new browser tab
* N/A
Fixes #20483
=> Add a target="_blank" parameter to the 'See who contributed to' link

admin/class-premium-upsell-admin-block.php, admin/views/licenses.php, packages/js/src/components/modals/KeywordSynonyms.js, packages/js/src/components/modals/MultipleKeywords.js, packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js, packages/js/src/settings/app.js, packages/js/src/shared-admin/components/premium-upsell-card.js, src/presenters/admin/sidebar-presenter.php
* Update copy for premium ads to promote AI feature.
* Updates premium ads copy to promote AI feature.
*
* Install Yoast SEO free plugin and disable Yoast premium or do not install premium.
* Check the ad in the bottom of the page and sidebar have the same copy and design as:
* Sidebar (copy changed): 
`Be more efficient in creating titles and meta descriptions with the help of AI. Get 24/7 support and boost your website’s visibility.`
* Footer ( copy added): 
`Use AI: Quickly create titles & meta descriptions`
* Go to `Yoast SEO`->`Settings` and check the same as above.
* Go to `Yoast SEO`->`Support` and check sidebar has changed the same …
=> 239 update the copy of existing ads so that it mentions ai

inc/options/class-wpseo-option-titles.php
Replace special characters with corresponding html codes to not break rss feeds.
* Fixing bug when adding special characters like " »" as a title separator breaks the RSS feed
* Fixes adding special characters like " »" as a title separator breaks the RSS feed
* Special characters were replaced with corresponding html code.
* Under Yoast SEO > Settings> General > Site Basics, set the Title Separator to ».
* Set the site to use a Static homepage and a Posts page.
* Run the Posts page feed (like example.com/posts/feed/)
* Open https://validator.w3.org/feed/ and use Validate by Direct input and copy content from the previous page there …
=> 20029 special characters as title separator breaks rss feed

admin/metabox/class-metabox.php, packages/js/src/elementor.js, packages/js/src/post-edit.js, src/integrations/third-party/elementor.php
*
* Hides the `Use AI` button for products and attachments.
* The Elementor changes are not really relevant at the moment but they are there for consistency, also in case the disallowed post type list becomes filterable or extendable in some way.
* Install only Free without Premium active
* edit a Product and see that you don't see the Use AI buttons
* make sure you have the media pages enabled in the settings, so editing a media shows the metabox
* edit a media and  see that you don't see the Use AI buttons
* edit posts, pages and custom post items, using block editor, classic editor and elementor, and check the Use AI buttons are there and work as …
=> Hide AI upsells on products and attachments

src/repositories/indexable-cleanup-repository.php
* we want to make sure we don't show a notice.
* Uses correct query logic to not trigger a `doing_it_wrong` notice.
*
* Make sure author archives are enabled and go to a post from an author. (remember this author).
* Also run the SEOO
* Disable Free (and premium).
* Remove the author (not just trash).
* Remove a post.
* Add the following code to `/wordpress-seo/admin/class-admin.php` at the end of the constructor at around line 118.
* Notice the closing `}` after the admin init this is to close out the constructor.
```
add_action( 'admin_init', [ $this, 'send' ], 1 );
}
public function send() {
$collector = new …
```
=> replace not needed prepare for direct query.

packages/js/src/shared-admin/store/wistia-embed-permission.js, packages/js/tests/__mocks__/@wordpress/api-fetch.js, packages/js/tests/components/SEMrushCountrySelector.test.js, packages/js/tests/components/SEMrushRelatedKeyphrasesModal.test.js, packages/js/tests/shared-admin/store/wistia-embed-permission.test.js
* Add JS tests for #4036 
* Adds tests for the Wistia embed permission slice.
* Changing the global mock for WP api-fetch. Let's not return an object by default, moved that to the SemRush test.
* Removed the error log, after looking at it from the perspective of the tests: logging there is a strange side effect of a slice I no longer agree with
* Choose to add some type coercion for the value. Is that better than throwing errors? We should use it proper in the first place. Now testing the expected results either way.
* Verify the tests make sense
* Verify the tests pass
* Verify the tests have 100% coverage
* No need for QA, …
=> Add JS tests for issue 4036

admin/watchers/class-slug-change-watcher.php
Implemented
* Fixing prompt showing "posts" instead of "tags" when tags is deleting.
* Fixes a bug where the redirect notification would mention "posts" when a tag was deleted or trashed.
* 
**Trash post**
* Yoast SEO premium plugin should be switched off.
* Create and publish post with any content.
* Trash the post.
* Make sure that on top the following message is displayed 'You just trashed a Post. Search engines and other websites can still send traffic to your trashed Post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.'.
**Delete …
=> Deleting tags has prompt showing "posts" instead of "tags"#20575

.github/workflows/test.yml, tests/unit/bootstrap.php, tests/unit/inc/addon-manager-test.php, wp-seo-main.php, wp-seo.php
*
* Sets the minimum supported WordPress version to 6.2.
*
* NA
*
*
Fixes #
=> Set the minimum supported WordPress version to 6.2.

config/dependency-injection/services.php, src/promotions/application/promotion-manager-interface.php, src/promotions/application/promotion-manager.php, src/promotions/domain/abstract-promotion.php, src/promotions/domain/black-friday-promotion.php, src/promotions/domain/promotion-interface.php, src/promotions/domain/time-interval.php, tests/unit/promotions/application/fake-expired-promotion.php, tests/unit/promotions/application/fake-promotion.php, tests/unit/promotions/application/promotion-manager-test.php, tests/unit/promotions/domain/time-interval-test.php
* We want to systematize the way we introduce and manage temporary promotions (e.g., the Black Friday ads).
* Introduces the `Promotions_Manager` class and related classes to manage temporary promotions ads.
* The `Promotions_Manager` is instantiated an registered as a service in the DI container. It accepts an array of  `Promotions`. Each Promotion has a unique name and a time frame in which it is considered active.
* A `Black_Friday_Promotion` is also introduced in this PR, which represents the time frame for the sales related to the Black Friday 2023 promotions.
* Start a debugging session by putting a breakpoint, e.g. in …
=> Introduce the promotions helper

admin/class-premium-upsell-admin-block.php, css/src/yst_plugin_tools.css
* Add a banner to a premium upsell when we are in the black friday promotion time.
* Adds upsell below the settings for the black friday promotion.
*
* Change the date in `src/promotions/domain/black-friday-promotion.php` to somewhere starting in 2022.
* Go to `Yoast SEO` -> `Dashboard` tab and make sure the upsell at the bottom looks the same as in the [sketch](https://www.sketch.com/s/5bd8cddb-a2c0-482a-97e5-a8ced2c3acf4).
*
*
Fixes #
=> Add upsell when promotion is on.

src/integrations/front-end-integration.php, tests/integration/doubles/front-end-integration-double.php, tests/integration/frontend/test-front-end-integration.php, tests/unit/integrations/front-end-integration-test.php
*
* Fixes an unreleased bug where the `prev` tag would be not be filled with the home url as expected when using a custom query loop block.
* I moved the test from unit-type to integration-type because we were testing only the legacy code to support WP 6.1 and older, which won't be the case soon anymore
* I changed the visibility of the properties since they were public only for testing purposes.
* I also added a return statment to the method since it's used in a filter so it should ALWAYS return something.
* Perform the acceptance test of https://github.com/Yoast/wordpress-seo/pull/20542 and check that the `prev` meta tag in the second page points to the home url without …
=> Fix prev query loop

css/src/adminbar.css
*
* Fixes a bug where the notifications counter of the admin bar menu would not show with the correct style on the frontend.
* Copied from WP commons' style for `.wp-ui-notification`. That stylesheet is not included on the frontend, and it would cause the whole frontend to look different. This is the quick work-around.
* Noticed the frontend also does not do the Yoast icon color change. Tooks some time to locate this back to WP SVG painter, which is not loaded or set up in the frontend. Leaving me to ignore this.
* Make sure you have a Yoast notification showing. For example, you can add a new content type via the Yoast test helper. Switching the post types & taxonomies …
=> Fix notifications counter style in the admin bar on the frontend

src/builders/indexable-hierarchy-builder.php, src/integrations/watchers/indexable-ancestor-watcher.php, src/integrations/watchers/primary-category-quick-edit-watcher.php, tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
* Add filter to allow building hierarchy when using `wp_set_object_terms` with `wp_insert_post`.  
* Adds filter to allow building hierarchy when using `wp_set_object_terms` with `wp_insert_post`.  
*
* Go to `Yoast SEO`->`Settings`->`Advanced`->`Breadcrumbs`
* Check `Breadcrumbs for post types` has select `Category` in `Posts`.
* Add the following code to the php `header.php`
```php
add_filter( 'wpseo_hierarchy_ignore_already_saved', '__return_true');
$post_id = wp_insert_post([
'post_type' => 'post',
'post_title' => 'Test post',
'post_content' => '',
'post_status' => 'publish'
]);
if ($post_id != 0) {
wp_set_object_terms($post_id, 'test_term', 'category');
}
```
* Visit …
=> add filter to allow building hierarchy

src/integrations/front-end/crawl-cleanup-basic.php
Hi there. 
Issue with method resource_hints_plain_cleanup in file src/integrations/front-end/crawl-cleanup-basic.php
Method resource_hints_plain_cleanup work with array $hints like with array of strings. But according to the documentation [https://developer.wordpress.org/reference/hooks/wp_resource_hints/](https://developer.wordpress.org/reference/hooks/wp_resource_hints/) it can be as array of arrays of resource attributes. If method get array of arrays, we get PHP Fatal error on the site.
We faced with this issue on production sites. When customers tried to activate Sirv plugin and got fatal error.
In PR added check in case if $hint is array.
* Fixes a bug where resource cleanup regarding emojis would cause a fatal error when …
=> Fix for resource_hints_plain_cleanup

packages/js/src/components/BlackFridayProductEditorChecklistPromotion.js, packages/js/src/components/BlackFridayPromotion.js, packages/js/src/components/BlackFridaySidebarChecklistPromotion.js
* We want to follow the best practice of using `useselect` hook inside React components instead of `select`
* Uses `useselect` hook instead of `select` inside React components.
* N/A
* Make sure you have no notifications alredy dismissed
* With a MySQL client edit the `wp_usermeta` table
* search  for the tuple with `user_id` = your user id and `meta_key` = `_yoast_alerts_dismissed`
* set `meta_value` to `a:0:{}`  
* Edit `src/promotions/domain/black-friday-checklist-promotion.php`
* change `\gmmktime( 11, 00, 00, 9, 19, 2023 )` to `\gmmktime( 11, 00, 00, 9, 19, 2022 )`
* Go to `Products` -> `Add new`
* In the Yoast metabox, …
=> Use useselect hook instead of select for invoking selectors

admin/class-admin-asset-manager.php, admin/class-expose-shortlinks.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, packages/js/src/components/KeywordUpsell.js, packages/js/src/components/MetaboxButton.js, packages/js/src/components/contentAnalysis/SeoAnalysis.js, packages/js/src/components/fills/MetaboxFill.js, packages/js/src/components/fills/SidebarFill.js, packages/js/src/components/modals/InternalLinkingSuggestionsUpsell.js, packages/js/src/components/modals/KeywordSynonyms.js, packages/js/src/components/modals/KeywordUpsell.js, packages/js/src/components/modals/MultipleKeywords.js, packages/js/src/components/modals/PremiumSEOAnalysisModal.js, packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js, packages/js/src/elementor/components/fills/ElementorFill.js, tailwind.config.js
*
* Improves the "Premium SEO analysis" upsell.
* Improves the "Add related keyphrase" upsell.
* Improves the "Add synonyms" upsell.
* Adds an "Internal linking suggestions" upsell.
* Added the Tailwind stylesheet as dependency to the metabox stylesheet. This should allow us to use Tailwind classes (as long as we ensure they are nested within a `yst-root`) in the editors.
* I tried to keep it simple here as I _think_ this is a style we eventually want to revamp. For now it is mostly looking like old. So if I had to make new things I did my best to make it look like it does now (without using styled components !!)
* The collapsible there is no way to easily add the badge there instead of the suffix icon. Due to the weird and …
=> Improve upsells

packages/yoastseo/src/languageProcessing/researches/getParagraphs.js
* In Shopify, the _keyphrase in introduction_ assessment did not detect the first paragraph correctly. This turned out to be because the `instanceof` check in the paragraph detection does not seem to work: somewhere in the chain we lose the prototype information. This PR circumvents that issue by doing a string rather than an object type comparison. 
* [shopify-seo] Fixes a bug where the _keyphrase in introduction_ assessment would fail to find the first paragraph.
* We no longer use the `instanceof` check because we lose prototype information when calling the assessment in Shopify. We replace this check with a string comparison which does the same. 
* Tests the steps …
=> Fixes a bug in paragraph detection

packages/js/src/first-time-configuration/tailwind-components/base/image-select.js, packages/js/src/first-time-configuration/tailwind-components/tailwind-modal.js
*
* Fixes a bug where the first-time configuration' site representation logo button would not be translated. Props to @fxbenard.
*
* Switch your site language (or user language) to something that has translations (I tested Dutch). And be sure to pull in the translations (via the WP updates screen)
* Go to Yoast SEO > General and switch to the First-time configuration tab
* Go to the site representation step
* Verify the image upload button's text is now translated (note: this works right away because the translations are the same as used in other places)
* Upload an image
* Verify the image replace button's text is now translated
* Verify the remove image button's text is …
=> Change textdomain

packages/yoastseo/spec/languageProcessing/researches/h1sSpec.js, packages/yoastseo/src/languageProcessing/researches/h1s.js
* Fix crash for Single title assessment in Block editor when one of the H1s doesn't have text.
* Now empty H1s also don't trigger the assessment at all.
* [yoastseo] Don't count empty h1s when looking for h1s in the text in the `h1s.js` research.
* [shopify-seo]  Fixes a bug where an H1 with no text could trigger the Single title assessment.
* Fixes the editor crashing when clicking the highlight button for the Single title assessment in Block editor when one of the H1s doesn't have text.
* h1 filter regex was modified to exclude items with empty content, so that empty h1s also don't trigger the assessment.
* Follow the testing instruction for Single H1 assessment in …
=> Fix crash for Single title assessment when one of the H1s doesn't have text

admin/class-admin-asset-manager.php, admin/class-premium-upsell-admin-block.php, css/src/black-friday-banner.css, css/src/new-settings.css, packages/js/src/settings/components/sidebar-recommendations.js, packages/js/src/shared-admin/components/premium-upsell-card.js, packages/js/src/support/app.js, src/integrations/settings-integration.php, src/integrations/support-integration.php, src/presenters/admin/sidebar-presenter.php, tests/unit/integrations/support-integration-test.php
* Updating Black Friday promotion copy and appearence.
* Adds Black Friday banner in settings page sidebar upsell card.
* Updates copy for sidebar upsell card.
* Updates label for Black Friday upsell sidebar card CTA button.
*
* Make sure you have Yoast premium disabled or not installed.
* Check the sidebar and the upsell block in the bottom of the page, both have the label `Get Yoast SEO Premium`
* Check the text to the upsell sidebar card is: "Use AI to generate titles and meta descriptions, automatically redirect deleted pages, get 24/7 support and much, much more!"
* Check the text is the same in `Yoast SEO`->`Settings` and `Yoast …
=> 73 change the copy on the sticky sidebar and sticky footer bar to claim your 30 off now

packages/js/src/analysis/blockEditorData.js, packages/js/tests/blockEditorData.test.js
* When posts are converted from Classic editor to the default (block/Gutenberg) editor, the posts is displayed using a `core/freeform` block ([docs](https://developer.wordpress.org/block-editor/reference-guides/core-blocks/#classic)). Under the hood, the WordPress `autop` function ([docs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-autop/)) is applied to these blocks (see e.g. [this PR](https://github.com/WordPress/gutenberg/pull/52716) for context). Our new position-based highlighting functionality did not work in that case, because these `<p>` tags were not parts of the HTML that is stored in the database (they are removed on save through `removep` ([docs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-autop/#removep))) …
=> Fixes highlighting behaviour for posts converted from Classic to Gutenberg

composer.json, composer.lock
* Tidy up `composer.json` file and improve usability of scripts
* Tidy up `composer.json` file and improve usability of scripts
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
These descriptions will be used when a list of the available scripts is requested on the command-line using the `composer list` or `composer run -l` commands.
These descriptions also help document the different scripts for the maintainers of the `composer.json` file.
Ref: …
=> Composer: normalize the file, add script descriptions

packages/js/src/analysis/PostDataCollector.js
* When editing a product with WooCommerce v8.2.0-beta.1, the slug would not set in the slug field of the snippet editor after the product is published. This is also the case when WooCommerce v8.1.1 is active accompanied by WordProof plugin. 
* The problem is WooCommerce makes available the "core/editor" store in 8.2.0, in earlier versions it did not do that. When fetching the slug for a saved/published post we first resort to the data from that store — but that’s empty for posts in classic editor (it’s filled only for saved/published posts in block editor).
We could reproduce this same issue also with WordProof — which similarly makes that store available on posts in the classic editor.
* This is [the PR](https://github.com/Yoast/wordpress-seo/pull/15857) that introduced this code, which …
=> Make sure that slug is available before trying to return it

inc/sitemaps/class-post-type-sitemap-provider.php, tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
* We want to make sure that our sitemaps work on mysql 8+ without warnings.
* Fixes a bug where PHP notice would happen when the sitemap index is generated on MySQL 8+.
* The problem here is that in MySQL 8 the use of user defined variables has changed. You now need to use a `select @something into @somethingelse` construction to fill variables. But you cannot do this in a subquery (which we need in this case to get only the Nth row).
* So the solution here was to use the new ROW_NUMBER function introduced in MySQL 8 to get the same result. But to get every Nth row you need to use a modulo of the current row to determine if you are at the Nth row. So, now the query is split in 2 parts. The first to filter the result set to a …
=> Add mysql 8 custom query to make sure it is BC.

packages/js/package.json, packages/js/src/components/PrimaryTaxonomyFilter.js, packages/js/src/components/PrimaryTaxonomyPicker.js, packages/js/src/components/TaxonomyPicker.js
*
* Fixes JS console error when picking primary term in post edit.
* Reduces `eslint` warnings in the Taxonomy Picker files.
* Make sure you have more than 1 category in your post's categories.
* Edit a post (while console is open)
* Check you do not get console errors related to the TaxonomyPicker component prop type.
* Add more than one category
* Check you see the select input box to select the primary category.
* Select a different Primary category and save.
* Refresh and check your selection was saved.
*
*
Fixes …
=> Fix console error and eslint warnings for Primary Taxonomy picker

src/integrations/front-end/rss-footer-embed.php
* Until now, the default for links in the RSS feed was to have a `rel=nofollow` attribute attached to each of them by default.  
* This PR switches the default so that `nofollow` is not added to RSS links, because it is no longer necessary from an SEO perspective. 
* Removes the automatic `rel=nofollow` attribute for links in the RSS feed.
* [yoastseo] Switches the default setting of the `nofollow_rss_links` filter from `true` to `false` in order to disable the `rel=nofollow` attribute for RSS feed links.
* 
* Create and publish new post with any link in content.
* Open RSS feed by adding /feed to the site url. Like https://wordpress.test/feed/ .
* Note: the URL should be …
=> 131 remove automatic rel on rss links

admin/menu/class-base-menu.php, css/src/adminbar.css
* We want to avoid showing the `30% OFF` badge aside the `Premium` menu item when Yoast SEO Premium is activated.
* Avoids showing the `30% OFF` badge aside the `Premium` menu item when Yoast SEO Premium is activated.
* N/A
* Install and activate Yoast SEO Premium
* Edit `src/promotions/domain/black-friday-promotion.php`
* change `\gmmktime( 11, 00, 00, 11, 23, 2023 )` to `\gmmktime( 11, 00, 00, 11, 23, 2022 )`
* Without this PR a `30% OFF` badge is shown aside the `Premium` Yoast SEO menu item
* With this PR, no `30% OFF` badge is shown
* disable Premium
* look at the Yoast menu in the admin bar, both in the backend and in the frontend
* Without this PR, the style for …
=> Fix condition to avoid showing promotion badge when Premium is installed

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, packages/js/src/analysis/collectAnalysisData.js, src/integrations/third-party/elementor.php
* In [this PR](https://github.com/Yoast/wordpress-seo/pull/20528), we changed the way we remove shortcodes from the analysis. However, we relied on a window variable (`wpseo_shortcode_tags`) that was not available in terms. This PR fixes that, and also adds some defensive coding. 
* Fixes an unreleased bug where shortcode removal would not work when editing a term.
* We also remove the unused window variable `wpseo_filter_shortcodes_nonce` as we no longer ship the shortcode plugin.
* Open any Category or Tag (or any other term) and check console
* Confirm that you don't see the following console error:
```
Uncaught TypeError: Cannot read …
```
=> Don't return the shortcodes if it's not available in the window

admin/views/licenses.php, css/src/yoast-extensions.css
*
* Adds the Yoast icon to the Premium page's Premium card.
* Breakpoint of 900px (like other plugins) to: hide the icon and 100% width the card
* Strange "- 8px" width to ensure the width is the same as the other plugins
* Using flex because why float
* Go to Yoast SEO > Premium (`/wp-admin/admin.php?page=wpseo_licenses`)
* Verify the Premium card now has the Yoast icon
* Change the browser screen to be < 900px and verify the Yoast icon is hidden (just like the icons of the other plugins)
* Optional:
* Edit `src/promotions/domain/black-friday-promotion.php` change `\gmmktime( 11, 00, 00, 11, 23, 2023 )` to` \gmmktime( 11, 00, 00, 11, 23, 2022 )`
* Verify the Sale …
=> Add Yoast icon to Premium plugin card

packages/js/src/settings/app.js
*
* Adds Black Friday banner to upsell block in Settings page.
* Adds different upsell label to the button for Black Friday in the Upsell block in Settings page.
*
* Check Yoast Premium is not installed or activated
* Go to `Yoast SEO`->`Settings`
* Scroll to the bottom of the page, check you see the following upsell block:
* Edit `src/promotions/domain/black-friday-promotion.php` change line 18:
```php
new Time_Interval( \gmmktime( 11, 00, 00, 11, 23, 2022 ), \gmmktime( 11, 00, 00, 11, 28, 2023 ) )
```
* Refresh the page and check the block has Black Friday banner and the button label has changed:
* …
=> Add black Friday banner to upsell block in settings

packages/js/src/components/BlackFridayPromotion.js
*
* Removes unwanted comma from the dismissible BF banner in the metabox.
* Removes unwanted whitespace from the BF banner in the sidebar.
*
* Edit `src/promotions/domain/black-friday-promotion.php` change `\gmmktime( 11, 00, 00, 11, 23, 2023 )` to` \gmmktime( 11, 00, 00, 11, 23, 2022 )`
* Open Post and check BF notification in the sidebar and metabox
* Verify that, in the metabox' BF alert, there is no longer a comma between YOAST SEO PREMIUM and Buy now!
* Verify that, in the sidebar' BF alert, there is no longer extra whitespace below Buy now!
* …
=> Fix small BF issues

css/src/yst_plugin_tools.css
*
* Fix sidebar responsiveness in General page.
*
* Edit `src/promotions/domain/black-friday-promotion.php` change line 18:
```php
new Time_Interval( \gmmktime( 11, 00, 00, 11, 23, 2022 ), \gmmktime( 11, 00, 00, 11, 28, 2023 ) )
```
* Make sure Yoast Premium is disabled or not installed.
* Go to `Yoast SEO`->`General`.
* Inspect the page and reduce size of the screen under 1000.
* Check side bar cards are one next to the other.
* Change width to be under 500px.
* Check cards are one unde
r the other.
*
*
Fixes …
=> 1080 minor errors with stretched out sidebar ad on ipad screen resolution

admin/views/licenses.php
*
* Remove Black Friday badge from Premium card in Premium page when user has valid subscription.
*
* Without Premium active and Yoast free install, go to `Yoast SEO`->`Premium`
* Check that you see no Black Friday badges
* Replace the following line in `src/promotions/domain/black-friday-promotion.php` line 18:
```php
new Time_Interval( \gmmktime( 11, 00, 00, 11, 23, 2022 ), \gmmktime( 11, 00, 00, 11, 28, 2023 ) )
```
* Activate premium, deactivate the subscription and go to `Yoast SEO`->`Premium`
* Check you see the Black Friday Badge:
* Activate subscription.
* Go to `Yoast SEO`->`Premium`
* Check premium card has no badge:
* Check other cads for add-ons still have a …
=> Remove BF badge when user has valid subscription in premium page

packages/js/src/decorator/gutenberg.js, packages/yoastseo/spec/scoring/assessments/seo/SingleH1AssessmentSpec.js, packages/yoastseo/src/scoring/assessments/seo/SingleH1Assessment.js
* We want to resolve an unreleased bug where H1s with mark-up are not properly highlighted in the block editor.
* Fixes an unreleased bug where the highlighting for the _single H1_ assessment would not function correctly when the content had markup. 
* In this same PR we also remove a deprecation warning in the console. 
* See the steps to reproduce in [this issue](https://github.com/Yoast/plugins-automated-testing/issues/1089).
* Note that while editing with the eye marker activated, the console error from [this issue](https://github.com/Yoast/plugins-automated-testing/issues/1088) does not appear.
* Finally, note that this was only a problem in the block editor. 
QA can …
=> Fixes incorrect highlighting for H1s with mark-up in the block editor

packages/js/src/analysis/collectAnalysisData.js, packages/yoastseo/src/pluggable.js
*
* Fixes an unreleased bug where the analysis would not work when switching from Elementor to Block editor. 
* The invalid blocks are filtered out from entering the Paper in `collectAnalysisData`. We think this is a safe solution:
* We cannot analyze invalid blocks anyway
* The data we add to wpBlocks in the Paper is only used for position-based highlighting in Block editor. So not providing the whole list of blocks in the "limbo" state (between editors) is not such a big deal since we cannot highlight anything anyway.
* This way, the analysis still works as before
* Create a post in Elementor with the following text:
```
<p></p>
<p>The …
```
=> Fix major errors in case post was created in elementor and switched to block editor

src/builders/indexable-hierarchy-builder.php, src/integrations/watchers/indexable-ancestor-watcher.php, tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
* Reverts Yoast/wordpress-seo#20599
=> Revert 20599 100 investigate wp set object terms doesnt add term into a breadcrumbs

src/integrations/third-party/wordproof.php
* WordPress introduced a new strategy feature in the Script API in version 6.3. See [this post](https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/) for more details. Since Yoast SEO already adds the `async` attribute to its `wordprof` script, we can leverage the new API to do that in a more reliable way.
*Using the strategy feature will make using `async` more reliable than the approach currently used in `add_async_to_script` and also more future-proof. 
* The original PR proposing the change can be found [here](https://github.com/Yoast/wordpress-seo/pull/20712).
* Leverages Script Strategy feature to add the async attribute to the `wordproof` script in case WordPress …
=> Support script strategy

packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js, packages/yoastseo/src/languageProcessing/researches/keywordCount.js
* We changed the way we handled shortcodes in this PR: https://github.com/Yoast/wordpress-seo/pull/20528
* With the above PR, it means that shortcodes enter the Paper as is and not excluded from Paper._text upstream in the worker before running the entire analysis. This is because we're relying on the Paper._text to build a tree with an accurate position information. For assessments that are still not yet adapted to use HTML parser, we filters out the shortcodes on assessment's level before running the assessment's analysis.
* For _keyphrase density_ assessment, we've adapted it to use the HTML Parser, which means that we didn't filter the shortcodes from Paper._text in the assessment level. However, it's important to note that the assessment is still not adapted yet for Japanese. This …
=> Filters shortcode before getting the sentences for Japanese

inc/options/class-wpseo-option.php
There are some typos in the documentation of the `WPSEO_Option` class.
* Improves the inline documentation for the `WPSEO_Option` class. Props to @costdev.
N/A
N/A
N/A
N/A
N/A
=> Docs: Correct some typos in `class-wpseo-option.php`.

packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesFromTreeSpec.js, packages/yoastseo/src/languageProcessing/helpers/sentence/getSentencesFromTree.js, packages/yoastseo/src/parse/structure/Node.js, packages/yoastseo/src/parse/traverse/findAllInTree.js
* The code that was introduced in [this PR](https://github.com/Yoast/wordpress-seo/pull/20741) caused the issues fixed in this PR.
* Fixes an unreleased bug where the analysis would crash when adding an image caption for some languages.
* Fixes an unreleased bug where highlighting for the keyphrase density assessment wouldn't work in the first part of a Yoast block.
* We added a fallback so that if a parent node cannot be found for an implicit paragraph, we use the current node as the parent node.
* The `parentAttributeId` and `isParentFirstSectionOfBlock` values of the Sentence object are only used for position-based highlighting in Yoast blocks. Yoast blocks consists of sub-blocks (e.g. question and answer). In the …
=> Fix error when adding image caption and highlighting not working in Yoast blocks

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
* In this PR, we add "Roma" as a suggested alternative to the non-inclusive phrases "gypsy"/"gypsies". That is because they are often used interchangeably, see for example this [entry in a diversity style guide](https://www.diversitystyleguide.com/glossary/roma-romany-romani/).
* _Inclusive language_ analysis: Adds 'Roma' as a suggested alternative to 'gypsy'.
* [shopify-seo] _Inclusive language_ analysis: Adds 'Roma' as a suggested alternative to 'gypsy'.
* None.
* Enable the Inclusive language analysis.
* Set your site language to English.
* Add the word "gypsy".
* Make sure the inclusive language analysis returns an orange traffic light 🟠 and the …
=> Inclusive language: Adds Roma as a suggested alternative to 'gypsy'

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
* We want to avoid false positives for `normal` and `abnormal` and improve our feedback. Specifically, in this PR, we: 
* no longer target 'normal behavior(u)r'
* introduce a separate feedback string for 'abnormal behavio(u)r'
* introduce a separate feedback string for 'behavio(u)rally normal'
* introduce a separate feedback string for 'behavio(u)rally abnormal'
* More information on this change can be found in [the research task](https://github.com/Yoast/lingo-other-tasks/issues/3). 
* _Inclusive language_ analysis: Improves the feedback for phrases including 'normal' or 'abnormal'.
* [shopify-seo] _Inclusive language_ analysis: Improves the feedback for phrases including 'normal' or 'abnormal'.
* We also changed the string for …
=> Inclusive language: Improves the feedback for 'normal' and 'abnormal'

admin/tracking/class-tracking-settings-data.php, inc/options/class-wpseo-option-wpseo.php, packages/js/src/settings/helpers/search.js, packages/js/src/settings/routes/crawl-optimization.js, src/integrations/settings-integration.php
*
* Add options/upsells to block unwanted bots: `Google-Extended`, `GPTBot` and `CCBot`.
* Make upsell exception when the environment is multisite (due to robots.txt and multisite). Preventing a possibly awkward upsell for functionality that is not available.
* Disable Premium
* Go to the settings
* Search for `bot` and verify you see the 3 new options in the list: 
* Verify that all 3 focus the field
* Verify the upsell looks similar to: 
* Verify the copy is the same as in https://docs.google.com/document/d/1nFaJDKDYr1c0-VGxPkSm_k8nY_v8wnlzBvrTrkythsA
* Including a change in the section and  Google AdsBot descriptions.
* Verify the section link links to …
=> Add options/upsells to block unwanted bots

src/integrations/watchers/indexable-attachment-watcher.php, tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
* We want to reduce the chances of confusion/conflict with the new `wp_attachment_pages_enabled` introduced by WP 6.4.
* Adds support for the new `wp_attachment_pages_enabled` option introduced by WordPress 6.4, reducing the chances of inconsistencies with Yoast SEO's own "Enable media pages" setting.
* I decided to avoid version checks and just go for updating the option if it's there. This way we can also avoid to change the code when we drop support for 6.3
This PR can be acceptance-tested by following these steps:
* make sure you are on a WP 6.2 or 6.3 site
* upload at least one image in Media if you don't have it already
* install Yoast SEO with this patch
* check the settings, you should have "Enable media pages" set to off …
=> Set the `wp_attachment_pages_enabled` option (WP 6.4) when switching "Enable media pages"

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessments.js
* We want to have a consistent meaning of the orange traffic light as ‘potentially non-inclusive’. This PR changes either the written feedback or the traffic light color for phrases where the feedback and traffic light color didn't align.
* Improves the feedback for phrases where the traffic light color and the written feedback didn't align.
* The feedback for 'homosexuals' is further improved by adding a few more alternatives, and simplifying the feedback string to say 'harmful' rather than 'overgeneralize or be harmful' (since overgeneralization falls under being harmful).
* In this PR we also address [this issue](https://github.com/Yoast/lingo-other-tasks/issues/20) to add a rule to not target 'narcissistic' when followed by …
=> Inclusive language: Align traffic light color and feedback for all phrases

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
* There are multiple variations of the feedback strings for "overgeneralizing" phrases. This PR improves the feedback strings so that they are more consistent. In [this research issue](https://github.com/Yoast/lingo-other-tasks/issues/19), it's decided to replace the overgeneralizing/generalizing strings with the `potentiallyHarmful` string. This PR implements that decision.
* _Inclusive language_ analysis: Improves the feedback strings for "overgeneralizing" phrases.
* [shopify-seo] _Inclusive language_ analysis: Improves the feedback strings for "overgeneralizing" phrases.
* [yoastseo] Replaces the feedback strings for generalization/overgeneralization phrases with `potentiallyHarmful` feedback string in _inclusive language_ …
=> Inclusive language: Change the feedback strings for overgeneralizing cases

admin/taxonomy/class-taxonomy.php
* Allow percent-encoding in canonical field.
* Fixes a bug where encoded characters would be stripped from canonical URLs in the taxonomy metabox. Props to [@stodorovic](https://github.com/stodorovic).
* Use sanitize_url instead of sanitize_text_field to sanitize canonical field (same approach as in #14481).
* Try to save encoded URL as canonical in the taxonomy metabox (e.g. `https://mydomain.com/%d8%a7%d8%b3%d9%85-%d8%a2%d8%ae%d8%b1-%d8%a8%d8%a7%d9%84%d9%84%d8%ba%d8%a9-%d8%a7%d9%84%d8%b9%d8%b1%d8%a8%d9%8a%d8%a9/`)
* Verify the canonical link in the front-end output is correctly encoded (Arabic character and no `---`)
* Try to save unencoded Arabic URL as canonical in …
=> Use sanitize_url to sanitize canonical field in the taxonomy metabox

src/helpers/current-page-helper.php, src/presentations/indexable-term-archive-presentation.php
* We want to add some defensive coding so that we don't throw warnings when our code runs.
* Adds defensive coding to the supress warnings on archive pages with the `/%category%/%postname%/` permalink structure. Props to @Mte90.
*
* Install and enable Elementor.
* Make sure Landing pages are enabled here: /wp-admin/admin.php?page=elementor#tab-experiments
* Set your permalink structure to a custom structure with `/%category%/%postname%/`
* Create a new landing page in elementor (it is an option in the templates CPT from elementor)
* Without this PR make sure you get 5 warnings when visiting the front-end of the landing page.
* With the PR make sure they are gone. 
QA can …
=> Adds defensive coding to make sure warnings don't happen.

packages/js/src/components/modals/editorModals/EditorModal.js, packages/js/tests/__mocks__/@yoast/externals/contexts.js, packages/js/tests/insights/components/flesch-reading-ease.test.js, packages/js/tests/insights/components/insights-collapsible.test.js, packages/js/tests/insights/components/insights-modal.test.js, packages/js/tests/insights/components/text-formality.test.js, packages/js/tests/insights/components/text-length.test.js
* Following the issue for upgrading to React 18 and migrating all Enzyme tests to the React testing library.
* Migrates the Insights tests to use the React testing library.
* Fixes a bug where the EditorModal would pass `false` to the SidebarButton's `suffixIcon` instead of `null`, resulting in a React prop type warning.
* Complete the mocks for `@yoast/externals/contexts`, ran into missing `useRootContext` now that we actually render
* There is some funky stuff going on in WP data
* had to "mock" `registerStore` by just passing `default` of the actual import, not sure how else to fix that
* unable to get the container using `withSelect` and `withDispatch` to work, running into the similar `default` error as with `registerStore` …
=> Migrate insights feature tests

packages/js/src/initializers/admin.js
* We want to get rid of a console warning related to the use of a deprecated JQuery statement.
* Avoids using a deprecated JQuery statement resulting in a console deprecation warning. 
* N/A
* Open you browser's console
* Edit a post
* Check that you don't get the following warning
* This PR doesn't change anything functionality-wise, as the toggle the warning refers to is rendered in multisite but is not active
Fixes https://github.com/Yoast/wordpress-seo/issues/20772
=> Fix JQuery deprecation warning

src/actions/wincher/wincher-account-action.php, tests/unit/actions/wincher/wincher-account-action-test.php
* Fix incorrect array access causing warnings in PHP8. See: https://wordpress.org/support/topic/update-21-0-undefined-array-key-months-undefined-array-key-type/
* Fixes a bug where the Wincher integration would cause PHP warnings with PHP 8+. 
* `isset` rather than `??` for compat with PHP5.
1. Set up the plugin on a PHP8 WP installation
2. Connect the Wincher integration to a *paid* Wincher account, if you don't have one, reach out to me in the Slack channel.
3. Open the SEO Performance tab
4. Ensure that no PHP warnings regarding "Undefined array access" were logged to the PHP error log. …
=> Fix get_upgrade_campaign causing undefined array key warnings

admin/metabox/class-metabox.php, packages/js/src/ai-generator/components/modal-content.js, packages/js/src/ai-generator/initialize.js, packages/js/src/post-edit.js, packages/js/src/redux/selectors/index.js, packages/js/src/redux/selectors/isWooSEO.js, packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
* Add AI feature introduction modal to product pages.
* Adds AI introduction modal to product pages when WooCommerce SEO and Premium are not active.
*
* Install Woocommerce and activate
* Install Yoast SEO premium but do not activate
* use the following branch for premium when testing: `disable-ai-feature-without-wooSEO-onproduct-page` (https://github.com/Yoast/wordpress-seo-premium/pull/4110)
* Go to `Products` create a product or edit one.
* Go to the Google preview section and check you see `Use AI` button.
* Click the `Use AI` and check you get the introduction modal and the CTA button has the following label, link, note:
* Label: Unlock with Woo Premium bundle*
* …
=> 81 create upsell for ai on woocommerce product pages

src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php, tests/unit/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell-test.php
* Starting from Yoast SEO 21.6 we want to re-instate the `AI title & description generator` introduction modal.
* Re-introduces the `AI title & description generator` introduction modal.
* N/A
* Make sure you have Premium disabled
* Go to the database table `wp_usermeta`, search for `meta_key` `_yoast_wpseo_introductions` and your `user_id` 
* make sure the `meta_value` is as follows: `a:1:{s:42:"ai-generate-titles-and-descriptions-upsell";b:0;}`
* Go to `Tools`-> `Yoast test` and click on `Reset Free installation success page`
* Deactivate Yoast SEO and activate it back
* Verify you see the installation success page and no modal is shown
* Navigate to any of the Yoast …
=> Remove version constraint for showing the ai introduction modal

css/src/introductions.css, packages/js/src/ai-generator/initialize.js, packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js, src/user-profiles-additions/user-interface/user-profiles-additions-ui.php, tests/unit/user-profiles-additions/user-interface/user-profiles-additions-ui-test.php
* Fix introduction modal styling and copy.
* Adjust styling and copy of the AI introduction copy.
*
* Make sure Yoast SEO Premium is not active.
* Edit a post or page.
* Go to google preview
* Click on `Use AI` button
* Check AI introduction modal:
* The upsell button should have the label: `Unlock with Yoast SEO Premium`
* Check the line "NEW TO YOAST SEO PREMIUM 21.0` should have letter spacing of 0.8.
* Check modal gradient should have the dark color not as the text background.  
*
*
Fixes [Improvements to the introduction …
=> 84 improvements to the introduction modal

packages/js/src/editor-modules.js
* Part of cleaning up the `yoast-components` package usages in Premium
* In a previous step, this KeywordInput component from `yoast-components` was copied to Free: https://github.com/Yoast/wordpress-seo/pull/20284
* This PR exposes that new location so that Premium can use it
* Exposes the KeywordInput via editorModules so that our add-ons can use it.
*
* Open the editor
* In your console: verify that `yoast.editorModules.components.contentAnalysis.KeywordInput` exists
* No need for additional tests.
* Our editor modules API.
Fixes …
=> API: expose the KeywordInputComponent

admin/views/redirects.php
*
* Fixes the redirects page upsell link.
*
* Disable Premium
* Go to the Yoast -> Redirects page
* Verify the upsell button links to `https://yoa.st/redirect-manager-upsell`
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/146
=> Fix redirects upsell link

src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php, src/introductions/application/introductions-collector.php, src/introductions/user-interface/wistia-embed-permission-route.php, src/promotions/application/promotion-manager-interface.php, src/promotions/domain/black-friday-checklist-promotion.php, src/promotions/domain/black-friday-promotion.php
We do not retrieve these classes via our YoastSEO helper. Therefor, we have no reason to expose them. By not exposing we are making it easier for ourselves to maintain code without BC breaking in the future. Although this technically counts as BC break, the code itself is not expected to be used and rather new.
* Remove a list of classes from being accessible via our YoastSEO classes helper.
*
* Devs: search for the classes: they should NOT be using inside our YoastSEO()->classes() API.
* Perhaps a quick smoke test of the affected areas?
* AI introduction things: only possible in for versions between 20.12 - 21.1, perhaps once the upcoming feature branch is merged
* BF …
=> Remove makePublic from non-public classes

packages/js/src/introductions/components/introduction.js, packages/js/src/introductions/components/provider.js, packages/js/src/introductions/store/introductions.js, src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php, src/introductions/application/introductions-collector.php, src/introductions/domain/introduction-interface.php, src/introductions/domain/introduction-item.php, src/introductions/domain/invalid-user-id-exception.php, src/introductions/infrastructure/introductions-seen-repository.php, src/introductions/readme.md, src/introductions/user-interface/introductions-integration.php, src/introductions/user-interface/introductions-seen-route.php, tests/unit/doubles/introductions/introduction-mock.php, tests/unit/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell-test.php, tests/unit/introductions/application/introductions-collector-test.php, tests/unit/introductions/domain/introduction-item-test.php, tests/unit/introductions/domain/introductions-bucket-test.php, tests/unit/introductions/infrastructure/introductions-seen-repository-test.php, tests/unit/introductions/user-interface/introductions-seen-route-test.php
* Make it possible to mark an introduction as seen from JS (i.e. create a route).
* Adds an introductions seen route.
* Rename `name` to `id` as that seems like a better name for a "unique name"
* Use `[\w-]+` matcher for the introduction ID in the route URL, as opposed to a query param without such regex limits. Mainly because this is more REST style
* Deactivate Premium, instructions for with Premium are in the Premium PR
* Either test with Premium or find a way to send a POST request with the right credentials (nonce + cookie) and:
* Send a request to `/wp-json/yoast/v1/introductions/INTRO_ID/seen` where INTRO_ID is the ID of your introduction
* You can add a param …
=> Add introductions seen route

packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
* Update copy for ai introduction modal on product pages.
* Update copy for ai introduction modal on product pages.
*
* Make sure Yoast Premium is not active
* Create or Edit a product
* Go to Google preview
* Click on `Use AI`
* Check the `New to` text and the title and description are as follow:
* New to Text: "New to Yoast SEO Premium + Yoast WooCommerce SEO"
* Title: "Generate product titles & descriptions with AI!"
* Description: "Speed up your workflow with generative AI. Get high-quality product title and description suggestions for your search and social appearance. Learn more"
* Repeat those steps when:
* Premium is active and WooCommerce …
=> update copy in ai introduction modal for products

packages/search-metadata-previews/src/index.js
* [For BC we kept this since the move from `yoast-components`](https://github.com/Yoast/wordpress-seo/commit/2958536a6c0ca8f25a5abe0b36c263d253722034). But we never seemed to use it ourselves. It can be time to remove it! Do you want to use these? Use the replacement variable editor package.
* [@yoast/search-metadata-previews 1.0.0] Removes re-exports of `@yoast/replacement-variable-editor`: `ReplacementVariableEditor`, `replacementVariablesShape`, `recommendedReplacementVariablesShape` and `SettingsSnippetEditor`.
*
* Search for any imports in our add-ons / other projects (Shopify)
* There should not be any usages via the search-metadata-previews package, only direct …
=> Remove re-exports of @yoast/replacement-variable-editor

packages/js/src/ai-generator/components/modal-content.js, packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
* Refactor the ai upsell modal to be more reusable for both admin pages and post editor
* Fix ai upsell modal for yoast admin pages.
*
* Go to the database wp_usermeta table and remove all lines with value `_yoast_wpseo_introductions`
* Check Yoast premium is not active and also Yoast Woo SEO.
* Go to any Yoast admin page and check you see the Ai introduction modal with the following features:
* New to Text: NEW TO YOAST SEO PREMIUM 21.0
* Title: Generate titles & descriptions with Yoast AI!
* Paragraph: Speed up your workflow with generative AI. Get high-quality title and description suggestions for your search and social appearance.
* Button label: Unlock with Yoast SEO …
=> fix introduction modal for admin pages

packages/js/src/first-time-configuration/first-time-configuration-steps.js, packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
* Fix initial state for site name based on fallback on site representation step in first time configuration. 
* Fixes a bug where initial state for site name would be empty when saving site representation step in first time configuration. 
*
* Reset First time configuration process and reset the options using the Yoast helper.
* Go to `Yoast SEO`->`General`->`First time configuration`
* Proceed to Site representation step.
* Do not change the Site name, keep the defaults add an image.
* Save
* Check you do not get the warning: `Please be aware that you need to fill out all settings in this step to get the most value out of structured data...`
* Try to save when any of the …
=> Fix initial state for site name based on fallback

admin/class-yoast-notification-center.php, admin/class-yoast-notification.php, inc/class-upgrade.php, tests/integration/notifications/test-class-yoast-notification-center.php, tests/integration/notifications/test-class-yoast-notification.php, tests/unit/admin/admin-features-test.php, tests/unit/admin/admin-gutenberg-compatibility-notification-test.php, tests/unit/content-type-visibility/application/content-type-visibility-watcher-actions-test.php, tests/unit/inc/addon-manager-test.php, tests/unit/integrations/admin/indexing-notification-integration-test.php, tests/unit/integrations/third-party/wpml-wpseo-notification-test.php, tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
* We want to avoid storing the full `WP_User` object in each user's notification.
* Do not store in the `wp_yoast_notifications` usermeta the full `WP_User` object.
* Notifications already saved in the database are managed on a user-by-user basis by the `Notification_Center::maybe_unset_notification_user_field` method. This is going to be less impactful for sites with a large number of users with respect to using an upgrade routine.
* Go to `Yoast SEO` -> `General` -> `Dashboard` tab
*  take note of the notifications (`Problems` and `Notifications` section) you have there and their state (visible or hidden)
* if you have no notifications, use the `Yoast Test` helper to …
=> Avoid storing the full user object in notifications meta

packages/js/src/first-time-configuration/first-time-configuration-steps.js
*
* Removes a superfluous warning in the first time configuration when the site environment is non-production.
* I continued with the `window.` side-effects pattern instead of abstracting that out of the components because they are already used throughout. The `amount` of the `yoastIndexingData` as well as a lot from `wpseoFirstTimeConfigurationData`. For the sake of keeping this small.
Be sure to test this on a non-production environment.
* Using the Yoast test helper:
* Under Yoast SEO:
* Click `Reset Indexables tables & migrations` to clear the data optimization progress
* Click `Reset First time configuration progress` to start on step one
* Under Development …
=> Add indexation disabled check before showing user an alert

src/generators/schema/person.php, tests/unit/generators/schema/person-test.php
* The `Person` schema piece is wrongly generated on authors archive pages ( so when `indexable type = 'user'`) and the site was previously setup to represent a Person different than the author. We want to avoid this.
* Fixes a bug where an additional `Organization, Person` schema piece is wrongly generated for author pages in case a website representing an organization was previously set to represent a person different than the author.
* The `is_needed` method  of the `Person` schema piece generator has been updated to not take into account the case in which `indexable_type = 'user'`. This is because this piece, being of type `Organization, Person` is meant to represent the website publisher in case the website represents a …
=> Use the Person piece only for publishers.

css/src/modal.css, packages/js/src/components/WincherSEOPerformanceModal.js
* This was caused in 21.5 when we added a border by default Now solved by increasing the top padding of the content (to the same as our upsell modals)
* Fixes a bug where the Wincher modal spacing was not large enough anymore after the header bottom border was added (in 21.5).
* Applying `yoast-gutenberg-modal__no-padding` class to override the WP modal padding to zero and then adding padding to the Wincher content only. This was we should not touch any other modals, plus we do a similar thing with our upsell modals.
* Edit a post
* Click `Track SEO performance` to open the Wincher modal (metabox & sidebar point at the same)
* Verify the content title now has a nice …
=> Fix the spacing in the Wincher modal

src/introductions/application/introductions-collector.php, src/introductions/user-interface/introductions-seen-route.php, tests/unit/introductions/application/introductions-collector-test.php, tests/unit/introductions/user-interface/introductions-seen-route-test.php
* We want to make sure that the given introduction ID is an ID we expect, so that malicious users can not spam the database with unknown IDs.
* Adds additional security to an unreleased API endpoint.
*
🗒️ To send an authorized POST request create an "application password" for your user in `/wp-admin/profile.php` and use that with Basic Auth to authenticate yourself. You can use e.g. [Postman](https://www.postman.com/downloads/) to easily send these POST requests.
* Send an authorized POST request to `/wp-json/yoast/v1/introductions/<RANDOM_STRING>/seen`.
* Check the `usermeta` table in your database for the `_yoast_wpseo_introductions` key for the user that was used to …
=> Adds extra security to new API Endpoint.

packages/js/src/components/WincherTableRow.js
*
* Fixes an unreleased bug where the "View" button in the Wincher modal would not open the link in a new tab.
* We might update the button component to allow a "new tab" behaviour, it would be smarter. Since we are in RC time, I'm fixing the issue in the easiest and most direct way
* Connect your site to Wincher and add a keyphrase
* Check that the "View" button opens in a new tab.
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/1179
=> Add target and rel to the Wincher "View" button

packages/js/src/components/modals/editorModals/EditorModal.js
* I don't quite follow what happened in WP 6.4, but something with detecting which level requested the modal closing made the event not always be defined anymore. I'm thinking we hit [this fallback](https://github.com/WordPress/gutenberg/pull/51602/files#diff-7d9147900701280de3fb09897ba9b4e36f424b18412332fc2f72774ef1afe035R47) in our EditorModal. Now added a safety check in our code.
* This error was only in our EditorModal, which is used in the Wincher and Insights (sidebar only) modals. As well as in our search and social modals (in the sidebar). However, the latter two are set to not close on click outside (due to something in Elementor).
* Also, this component is being exposed via `editorModules`. But not actually used it seems. Not that important here due to fix being inside the …
=> No longer presume the event is defined

packages/js/src/elementor.js, packages/js/src/elementor/containers/SnippetEditor.js, packages/js/src/elementor/redux/selectors/analysis.js, packages/js/src/elementor/replaceVars/elementor-replacevar-plugin.js, packages/js/src/initializers/analysis.js, packages/js/src/initializers/pluggable.js, packages/js/src/insights/initializer.js
* Previously, we only watched the editor content for updating the results in the Insights tab. In this PR, we instead watch the changes in the content **including the modifications**: the `collectData` function takes care of retrieving the content including the modifications (e.g. modifications/content from the ACF fields). This way, when there is a change in the ACF field for example, we would recalculate the analysis for Insights immediately without the need to save the post first.
* Also, previously, we would create a new `Pluggable` -- here we instead check if there is already a `Pluggable` on the window.
* Note that in this PR, we did **not** change anything in the calculation of prominent words, but the reading and word count should now be calculated correctly without requiring …
=> Insights: Watches all data/modifications instead of just the editor content

tests/integration/admin/import/test-class-import-settings.php
* Minor test cleanup
* Minor test cleanup
Support for PHP < 5.3 was dropped long ago.
* _N/A_ If the tests pass, we're good.
=> Tests/WP: remove some redundant skip conditions

packages/js/src/analysis/getApplyMarks.js, packages/js/src/elementor/initializers/editor-store.js, packages/js/src/initializers/analysis.js
* We want to make the highlighting feature available in Elementor. For this, we already create a proof-of-concept (https://github.com/Yoast/lingo-other-tasks/issues/140, https://github.com/Yoast/wordpress-seo/pull/20632). In this PR, we add an action in Free, so we can add the highlighting funcionality in an add-on. This change will also allow developers to implement highlighting for other editors. 
* Adds a JavaScript action (`yoast.analysis.applyMarks`) that allow users to implement the highlighting functionality in other editors. 
* It's search based highlighting what was implemented as a proof-of-concept redesigned and code moved to premium.
* Please check the Premium …
=> Reimplement proof-of-concept for highlighting in Elementor#4125

packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap, packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap, packages/components/src/IconButtonToggle.js, packages/components/tests/__snapshots__/IconButtonToggleTest.js.snap
* We want to ensure that the eye icon in the highlighting button is properly centered. In Elementor, some CSS interfered with our existing `display: inline-block` solution. That's why in this PR, we use CSS flexbox to center the eye icon in the button. 
* Improves the centering of the eye icon in the highlighting button across editors.
* Even though we only found a problem with the positioning in Elementor, this change applies to all editors. Compared to the released version, the eye icon appears a little bit lower. This change was signed off by the UX team.
* Add some content that results in a highlighting button to pop up for any assessment. For …
=> Centers the eye icon in the highlighting button using CSS flexbox

packages/js/src/components/fills/MetaboxFill.js, packages/js/src/components/fills/SidebarFill.js, packages/js/src/elementor/components/fills/ElementorFill.js
* We want to re-order menu items in sidebar and metabox to be consistent with Yoast SEO Premium.
* Re-orders menu items in block editor metabox and sidebar, classic editor metabox and Elementor editor sidebar to be consistent with Yoast SEO Premium.
* The moving around of the `SidebarItem` components has no effect on their rendering order, what matters is the `renderPriority` prop value, I moved them just to reflect their prop value.
* Open a post for editing in the Block editor
* Verify the elements in the metabox are as follows:
* Verify the elements in the sidebar are as follows:
* Activate the Classic editor
* Verify the elements in the metabox are as follows:
* Edit …
=> Re-order menu items to be consistent throughout various editors.

packages/js/src/analysis-worker.js
* Elementor 3.18.0 added(?) `wp-polyfill`. See this PR: https://github.com/elementor/elementor/pull/24424/files
* As a result, it breaks the analysis and causes an error in the console when it enters the worker. This is because `wp-polyfill` is not available inside the worker.
* Fixes a bug where the analysis didn't work inside the Elementor editor when using Elementor version 3.18.0. 
* We add `wp-polyfill` to the `disallowedDependencies`. See also [this PR where this solution was applied to as similar issue.](https://github.com/Yoast/wordpress-seo/pull/19668).
* Activate Yoast SEO 21.6 and Elementor 3.18.0
* Open a post in Elementor 
* Confirm there are no "Refused to …
=> Disallow `wp-polyfill` from running inside the worker

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
*
* Improves the phrasing of some inclusive language feedback strings.
* No feedback strings with double spaces were found, I only found some in the code for the unit tests.
* The word 'instead' was removed from the string `Avoid using <i>%1$s</i> as it is derogatory. Consider using an alternative, such as %2$s instead.` for consistency with other strings. 
* Note that there are still some strings containing the word 'instead', such as: `Be careful when using <i>sociopath</i> as it is potentially harmful. If you are referencing the medical condition, use <i>person with antisocial personality disorder</i> instead, unless referring to someone who explicitly wants to be referred to with this term.`. I decided to keep them there …
=> Fix typos in inclusive language feedback

packages/js/src/components/TimeConstrainedNotification.js, packages/js/src/components/WebinarPromoNotification.js, packages/js/src/components/fills/SidebarFill.js, packages/js/src/components/trustpilot-review-notification/constants.js, packages/js/src/components/trustpilot-review-notification/hooks.js, packages/js/src/components/trustpilot-review-notification/index.js, packages/js/src/components/trustpilot-review-notification/trustpilot-review-notification.js, packages/js/src/containers/PersistentDismissableNotification.js, packages/js/src/elementor/components/fills/ElementorFill.js, packages/js/src/hooks/use-first-eligible-notification.js, packages/js/src/shared-admin/store/link-params.js, packages/js/tests/shared-admin/store/link-params.test.js, src/integrations/alerts/trustpilot-review-notification.php
*
* Adds a notification in the sidebar to leave a quick review.
* Use our dismissible alert mechanism
* Add new "first eligible notification" component to only show one at a time
* Using locationContext in the `context` parameter of the link
Before you start
* Remove all the dismissed alerts: in your DB, remove the user meta: `_yoast_alerts_dismissed`
Block editor
* Open the sidebar
* Which notification you see will depend on if your overall SEO score
* If your post does not have a green bullet, it is expected that you see the Webinar notification
* If you post does have a green bullet, it is expected that you see the …
=> Prompt users to review Yoast on Trustpilot

inc/sitemaps/class-sitemap-image-parser.php
* Add a filter to allow developers to add images to terms in the sitemaps.
* Adds a filter to allow adding images to terms in sitemaps.
* [This documentation](https://yoast.com/help/images-in-the-xml-sitemap/) would need an update after this PR is merged to include the filter for terms.
* Create a post with a category.
* Install `Categories Images` plugin.
* Add an image to the category you added to the post.
* Go to `Yoast SEO`->`XML Sitemaps`
* View the sitemaps-> Category sitemap,  and check you see the category there with 0 images. 
* Install `Code Snippets` plugin
* Add the following PHP snippet:
```php
function add_sitemap_term_url_images( $images, $term_id ) { …
```
=> 19098 custom filter image url for taxonomy sitemap images

packages/js/src/watchers/elementorWatcher.js
* When editing in Elementor, it could take a while before the analysis is refreshed after a change is made. This waiting time is at least 1500 miliseconds and also could be longer (I waited for around 3 seconds in my case). As a result, some applicable assessments would not be immediately displayed in the metabox or the highlighting of Keyphrase density would not be immediately applied correctly, until the analysis is refreshed.
* [Context for the discussion on Slack](https://yoast.slack.com/archives/C027BFR5L/p1702464363362229?thread_ts=1702455658.784279&cid=C027BFR5L)
* Decreases the debouncing time for refreshing the analysis in Elementor from `1500` to `500` ms.
* The debouncing time is changed from `1500` to `500` ms in line …
=> Decrease the waiting time for refreshing the analysis in Elementor

admin/class-premium-upsell-admin-block.php, admin/views/licenses.php, css/src/yoast-extensions.css, packages/js/src/ai-generator/components/modal-content.js, packages/js/src/components/AnalysisUpsell.js, packages/js/src/components/UpsellBox.js, packages/js/src/components/modals/InternalLinkingSuggestionsUpsell.js, packages/js/src/components/modals/KeywordSynonyms.js, packages/js/src/components/modals/MultipleKeywords.js, packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js, packages/js/src/components/modals/SEMrushUpsellAlert.js, packages/js/src/helpers/get-premium-benefits.js, packages/js/src/settings/app.js, packages/js/src/settings/routes/site-features.js, packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js, packages/js/src/shared-admin/components/premium-upsell-card.js, src/presenters/admin/sidebar-presenter.php
*
* Improves the copy of some of our ads.
* Moved the benefits list to a helper, to only have to maintain one list - and added strong tags around to be the same as in other lists
* As per CR: The order of things can be different per language. This gives control to the translators.
* Removed the classes inside licenses.php to be able to keep the same translations, this will save on having to double translate.
Before you start
* Install & activate WooCommerce (not our plugin)
* have [the doc](https://docs.google.com/document/d/1fm2KBnwnnjo-V5-udCadqZUQHJYywC3n4Mzb7rL_ivI/edit) with the required changes ready for comparison
Premium upsell cards
* PHP …
=> Improve copy of plugin ads

admin/views/licenses.php, packages/js/src/settings/routes/site-features.js
*
* Fixes two unreleased problems with the changes in the ads copy.
* I rewrote the part about building the "Outrank your competitors..." string to make sure it's easier to translate.
* Go to Yoast SEO > Settings page
* Observe "Link suggestions" card in Site Structure section
* The title of the card should be "Internal linking suggestions" now
* Go to Yoast SEO > Premium page
* Observe 2nd title "Outrank your competitors..."
* The title should be "Outrank your competitors even further with these Yoast SEO plugins".
* the word "these" was missing
* check that the formatting of the title is as expected.
* …
=> Fix missing words ads

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
* We target words such as "bipolar" when used to describe a personal trait instead of a medical condition (e.g. "They act bipolar in decision-making"). Rules were added to avoid targeting these words in a medical context  (such as "bipolar disorder"), where using them is inclusive. 
* Improves feedback in the inclusive language assessment by excluding false positives for pontentially non-inclusive phrases related to mental health.
* Even though the phrase _schizoaffective disorder_ is used instead of _schizophrenic disorder_, the rule "exclude word when followed by disorder" was added for both the word  _bipolar_ and the word _schizophrenic_  since they share the same string. …
=> Add rules to avoid false positives in medical contexts

packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js, packages/yoastseo/src/languageProcessing/helpers/sanitize/quotes.js, packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
* In Elementor and other editors (Block and Classic), we want to be able to highlight keyphrase occurrences with different types of apostrophe in the text when _keyphrase distribution_ assessment eye button is activated. For example if the keyphrase is `red panda`, we want to be able to highlight `red panda's` and `red panda’s` occurrences in the text.
* However, that wasn't the case yet. Even though we're able to match `red panda` with both `red panda's` and `red panda’s` occurrences, we're not able to highlight the word that contains non-normalized single quotes such as `panda’s`.
* The problem was (in `packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js`):
* Before we're adding the `yoastmark` (the HTML tag that will give the highlighting to the text) to the …
=> Makes sure keyphrase occurrences with different types of apostrophes are highlighted in keyphrase distribution assessment

composer.json, composer.lock
* Be explicit about required PHP extensions
* Be explicit about required PHP extensions
The Filter extension is used unconditionally within the library. All the other are used conditionally.
Discovered using the ComposerRequireChecker tool and manually verified.
Ref: https://github.com/maglnet/ComposerRequireChecker
* _N/A_
=> Composer: update suggested PHP extensions

tests/Unit/bootstrap.php, tests/WP/bootstrap.php
PHP 7.0 introduced a `$levels` parameter, which means that nested calls to `dirname()` are no longer needed.
Ref: https://www.php.net/manual/en/function.dirname.php
=> CS/QA: modernize function calls to dirname()

admin/class-yoast-notification-center.php, admin/taxonomy/class-taxonomy-columns.php, inc/class-wpseo-replace-vars.php, inc/options/class-wpseo-option-titles.php, lib/migrations/adapter.php, lib/migrations/table.php, lib/orm.php, src/integrations/front-end/crawl-cleanup-basic.php
Reformat code where an `if` statement is the only code within an `else` clause to use `elseif`.
=> CS/QA: no "lonely if"

admin/import/plugins/class-import-wpseo.php, inc/sitemaps/class-taxonomy-sitemap-provider.php
The function signature of the `get_terms()` function was changed in WP 4.5.0. This updates the function calls to `get_terms()` within this plugin to use the new expected function call format.
Ref: https://developer.wordpress.org/reference/functions/get_terms/
=> CS/QA: upgrade calls to get_terms()

tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Watcher_Actions_Test.php, tests/Unit/Integrations/Admin/Admin_Columns_Cache_Integration_Test.php
... which essentially meant that the first data sets using that name were not being run in the tests.
The second instance of the array key encountered would overwrite the value of the first, so removing the first of the two array keys will maintain the existing behaviour.
=> CS/QA: fix use of duplicate array keys

tests/Unit/Actions/Indexing/Abstract_Link_Indexing_Action_Test.php, tests/Unit/Actions/Indexing/Post_Link_Indexing_Action_Test.php, tests/Unit/Actions/Indexing/Term_Link_Indexing_Action_Test.php, tests/Unit/Conditionals/WP_Robots_Conditional_Test.php, tests/Unit/Generators/Schema_Generator_Test.php, tests/Unit/Helpers/Date_Helper_Test.php, tests/Unit/Helpers/Indexing_Helper_Test.php, tests/Unit/Helpers/String_Helper_Test.php, tests/Unit/Integrations/Academy_Integration_Test.php, tests/Unit/Integrations/Admin/Activation_Cleanup_Integration_Test.php, tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php, tests/Unit/Integrations/Admin/Crawl_Settings_Integration_Test.php, tests/Unit/Integrations/Admin/Cron_Integration_Test.php, tests/Unit/Integrations/Admin/Import_Integration_Test.php, tests/Unit/Integrations/Admin/Indexing_Notification_Integration_Test.php, tests/Unit/Integrations/Admin/Indexing_Tool_Integration_Test.php, tests/Unit/Integrations/Admin/Installation_Success_Integration_Test.php, tests/Unit/Integrations/Admin/Old_Configuration_Integration_Test.php, tests/Unit/Integrations/Admin/Redirect_Integration_Test.php, tests/Unit/Integrations/Admin/Redirects_Page_Integration_Test.php, tests/Unit/Integrations/Blocks/Structured_Data_Blocks_Test.php, tests/Unit/Integrations/Cleanup_Integration_Test.php, tests/Unit/Integrations/Estimated_Reading_Time_Test.php, tests/Unit/Integrations/Front_End/WP_Robots_Integration_Test.php, tests/Unit/Integrations/Front_End_Integration_Test.php, tests/Unit/Integrations/Settings_Integration_Test.php, tests/Unit/Integrations/Support_Integration_Test.php, tests/Unit/Integrations/Third_Party/WooCommerce_Permalinks_Test.php, tests/Unit/User_Profiles_Additions/User_Interface/User_Profiles_Additions_Ui_Test.php
* Everywhere else, `$this->assert*()` is used, so let's use that here too.
=> CS/QA: don't use static calls to assertion methods

admin/class-admin-asset-manager.php, admin/class-database-proxy.php, admin/class-yoast-dashboard-widget.php, inc/class-wpseo-admin-bar-menu.php, src/integrations/third-party/wordproof.php
* Use nullable types when the default value of a typed parameter is `null`.
=> Modernize: use nullable types

admin/metabox/class-metabox.php, packages/components/src/select/Select.js, packages/components/tests/__snapshots__/SelectTest.js.snap, packages/js/src/components/SchemaTab.js, packages/js/src/settings/routes/templates/post-type.js, src/integrations/settings-integration.php
* When Yoast WooCommerce SEO is installed we already force the page type for products to me `Item Page`, but the UI still shows the possibility to change the post type. We want to fix this discrepancy.
* Disables the post type select both in the product editor metabox and in the Settings page when post type is `product`.
* The filter introduced in https://github.com/Yoast/wpseo-woocommerce/pull/980 is needed to set the default value for products to `ItemPage`.
* Test this PR together with its Yoast WooCommerce SEO counterpart: https://github.com/Yoast/wpseo-woocommerce/pull/980
* Activate Yoast WooCommerce SEO
* Perform the SEO data optimization
* Create a product and …
=> Force page type to itempage for products

.github/workflows/finish-coveralls.yml, .github/workflows/jstest.yml, .github/workflows/test.yml
Sometimes the test and jstest workflows are slow to start, causing the finish-coveralls workflow to have checked for running workflows before they have even started, resulting in a failure (like in [this case](https://github.com/Yoast/wordpress-seo/actions/runs/7273265777/job/19816911703)).
* Fixes a bug where the finish-coveralls CI action would fail when the test actions are slow to start.
* Fixes a bug where the testjs CI action would fail when changes were made any JS pacakge other than yoastseo.
* Fixes a bug where the PHP and JS coverage results would be split into a separate builds on Coveralls on `push` builds.
* I sleep for 30 seconds before checking running actions. This should be more than enough time for the jobs to …
=> Prevent failing finish-coveralls workflow

packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesConsecutiveWords.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesWordsAtPosition.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticiple.js
* The wording of descriptions for a few inclusive language helpers was confusing which made it hard to understand what the code does, this PR fixes it.
* Improves function descriptions for _inclusive language assessment_ helpers.
* The file `isPrecededByException.js` was not adjusted because the helper's behaviour will be changed in this issue: [Inclusive language tech debt: Flip the behavior of the isPrecededByException function#255](https://github.com/Yoast/lingo-other-tasks/issues/255) 
* As a precaution, run `yarn test` and make sure all tests pass.
* …
=> Improve function descriptions for Inclusive language helpers

admin/class-bulk-editor-list-table.php, admin/class-database-proxy.php
* Improved PHP 8.2 compatibility
The `$table_prefix` property was not explicitly declared.
The `$target_db_field` property was not explicitly declared, only in the child classes.
=> PHP 8.2: prevent dynamic property deprecations

src/integrations/third-party/wpml-wpseo-notification.php
WPML changed the glue plugin name to WPML SEO. So, the plugin notification mentioning "Yoast SEO Multilingual" may confuse the users even though the link we added to the notification is correct.
Reference: https://wpml.org/documentation/related-projects/wpml-seo/
* Changing the WPML plugin name to WPML SEO.
* The current notification contains the WPML plugin name as "Yoast SEO Multilingual", but as they changed to "WPML SEO" the users won't be able to find it on the WPML download page
* Changing the name to the correct one used by WPML will be helpful for users who won't check this link we added.
*
* Updates the WPML notification to mention "WPML SEO" instead of "Yoast SEO Multilingual".
* …
=> Change the plugin name showing on the notification from 'Yoast SEO Multilingual' to 'WPML SEO'

packages/js/src/analysis-worker.js
* We want to prevent conflicting dependencies to be loaded in the analysis web worker. Initially, we solved that by adding additional dependencies to the denylist (see https://github.com/Yoast/wordpress-seo/pull/20915, which is **not** merged to `trunk`). However, such an approach is not fail-safe, as other conflicting dependencies could be added in the future. Therefore, in this PR, we instead introduce an allowlist for the dependencies we load into the web worker.
* Uses an allowlist instead of a denylist for the webworker's dependencies.
* We are allowlisting the following dependencies: 
* `lodash`: used for functional programming.
* `regenerator-runtime`: used for (transpiled) async functions.
* `wp-hooks`: dependency for …
=> Uses an allowlist for the webworker's dependencies

packages/js/src/initializers/block-editor-integration.js
In WP 6.5:
* the `openPanels` selector moved from `core/edit-post` to `core`
* the `togleEditorPanelOpened` moved from `core/edit-post` to `core/editor`
The first (select) produced an error, making our integration grind to a halt.
The second (dispatch) produced a deprecation warning.
* Fixes a bug where our block editor integration would no longer work in WP 6.5.
* Using the new location of `toggleEditorPanelOpened` to determine what WP version logic to use:
* I was wondering if it is worth it to go for PHP side passing along the versions (global $wp_version and GUTENBERG_VERSION) -- but that is more complex and the latter is also not working for the Gutenberg `trunk`
* A problem with this detection is that when using Gutenberg …
=> Fix the opening of our document panel in WP 6.5

css/src/metabox.css
With Gutenberg 17.3 (PR https://github.com/WordPress/gutenberg/pull/56635) all the button icons are now displayed as "compact", which makes the width 32px (from 36px). Resulting in no space around the icon (horizontally).
This change removes the icon size override when in compact mode. Effectively reverting the icon size back to be 24px. Leaving the same horizontal space as the WP icons.
* Fixes a bug where the Yoast plugin icon in the block editor would not have any horizontal spacing anymore when rendered in "compact" mode.
*
* Verify the Yoast plugin icon in the sidebar looks normal: 
* Button width of 36px and icon width of 28px
* …
=> Remove plugin icon size override [WP 6.5]

packages/js/src/initializers/block-editor-integration.js
Fix for https://github.com/Yoast/wordpress-seo/pull/21024
Where I noted:
> A problem with this detection is that when using Gutenberg plugin v17.4.1 the Yoast panel does not open. This is due to the selector not being in that version yet, it is scheduled to land in v17.5
Turns out this was only working in 17.4.1 because the old structure was still saved in the database and local storage.
* Fixes a bug where our block editor integration would no longer work with Gutenberg 17.4.1.
* Added all the safety now, after being bitten again 😅 
* Have a fresh site
* Or delete the `wp_persisted_preferences` from your user in the `usermeta` table
* As well as delete the …
=> Fix the opening of our document panel in Gutenberg 17.4.1

src/routes/indexables-head-route.php, tests/Unit/Routes/Indexables_Head_Route_Test.php, tests/WP/Routes/Indexables_Head_Route_Test.php
* We want to fix a bug with the `get_head` REST route and  multiple words search strings. 
* Fixes a bug where the `get_head` REST route would return a `rest_invalid_param` if the URL contains a multiple words search string. props to @lucymtc.
* N/A
* Without this PR, visit `YOUR_HOME_URL/wp-json/yoast/v1/get_head/?url=YOUR_HOME_URL/?s= test search` (substitute `YOUR_HOME_URL` with your actual home URL)
* verify you get the following response:
```
{
"code": "rest_invalid_param",
"message": "Invalid parameter(s): url",
"data": {
"status": 400,
"params": {
"url": "Invalid parameter."
},
"details": []
}
}
```
* With this PR verify you get a valid response instead
This PR …
=> Fix get_head validation callback

admin/metabox/class-metabox.php, packages/components/src/select/Select.js, packages/components/tests/__snapshots__/SelectTest.js.snap, packages/js/src/components/SchemaTab.js, packages/js/src/settings/routes/templates/post-type.js, src/integrations/settings-integration.php
* Revert #20956 to look at it more deeply.
* Reverts "Force page type to itempage for products".
*
*
*
*
Fixes #
=> Revert "Force page type to itempage for products"

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isPrecededByExceptionSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByException.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isPrecededByException.js
* The behavior of the `isPrecededByException` functions returns `false` if the phrase is followed by an exception and `true` when it isn't followed by an exception. The function `isNotPrecededByException` returns otherwise. 
We want to switch the functions around, so that they return the correct values. 
*  It corrects the behavior of the `isPrecededByException` and `isNotPrecededByException` functions.
*  [shopify-seo] It corrects the behavior of the `isPrecededByException` and `isNotPrecededByException` functions.
*
* For developers: Run `yarn test` and make sure all specs pass
**Test the `isPrecededByException` function**
1. Create a post
2. Add a text of at least 300 …
=> 255 inclusive language tech debt flip the behavior of the isprecededbyexception function

packages/js/src/initializers/block-editor-integration.js
* Cherry-picks https://github.com/Yoast/wordpress-seo/pull/21024 for a hotfix release
* Fixes a bug where our block editor integration would no longer work together with Gutenberg 17.5.
* see #21024
* see #21024
* see #21024
*
Fixes #21021
=> Fix the opening of our document panel (Gutenberg 17.5)

packages/js/src/initializers/block-editor-integration.js
* We want to cherry-pick #21030 in the 21.8.1 hotfix
* Fixes a bug where our block editor integration would no longer work together with Gutenberg 17.4.1.
* see #21030
* see #21030
* see #21030 
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/1288
=> Fix the opening of our document panel in Gutenberg 17.4.1 (hotfix)

admin/metabox/class-metabox.php, packages/components/src/select/Select.js, packages/components/tests/__snapshots__/SelectTest.js.snap, packages/js/src/components/SchemaTab.js, packages/js/src/redux/selectors/isWooSEO.js, packages/js/src/settings/routes/templates/post-type.js, src/integrations/settings-integration.php
*
* Selects `ItemPage`  as pagetype for products if Yoast WooCommerce SEO is active.
* I have set this PR changelog to `non-user-facing` as we want the changelog only in Yoast WooCommerce SEO (this PR has no effect without Yoast WooCommerce SEO).
* Follow the instruction in the corresponding Yoast WooCommerce SEO PR: https://github.com/Yoast/wpseo-woocommerce/pull/987
* N/A
Fixes https://github.com/Yoast/plugins-automated-testing/issues/1290
=> Fix wrong woo page type

packages/js/src/settings/routes/site-representation.js, src/integrations/settings-integration.php
*
* Updates the email, phone, vat and tax ids defaults in case Local SEO is active with multiple locations. Updates the error message and link to Local SEO settings.
*
* Activate Yoast SEO premium based on the feature branch `feature/new-organization-schema-fields` and Local SEO based on the branch `restore-email-field-for-location`
* Go to `Yoast SEO`->`Local SEO`
* Set "My business has multiple locations" to yes
* Set "All locations are part of the same business" to no.
* Go to `Yoast SEO`->`Settings`->`Site representation`
* Check the alert message over email and phone is as follows and the link is for Locations page and opens in a new tab:
> You have Yoast Local SEO …
=> Update defaults for multiple locations and alert message

inc/class-rewrite.php
* Fix category redirect when using blog prefix in permalink structure and striping category slug.
* Fixes a bug where category redirect to base url when using blog prefix in permalink structure and strip category slug.
* The blog prefix should be added when it's part of the permalink structure, no matter if it's a multisite or subdirectory.
* There will be one link, `wordpress.test/blog/test-cat` and `wordpress.test/blog/category/test-cat` would be redirected to `wordpress.test/blog/test-cat`. But the difference is that the target link would be `wordpress.test/blog/test-cat` and you can still create a page `wordpress.test/test-cat`.
* Make your permalink structure to be …
=> 20853 disable category prefix category archives can be accessed via 2 urls

packages/js/src/components/WincherPerformanceReport.js, packages/js/src/components/modals/WordProofWebhookFailed.js, packages/js/src/first-time-configuration/tailwind-components/stepper.js, packages/js/src/initializers/block-editor-integration.js, packages/js/src/insights/components/prominent-words.js, packages/js/src/settings/helpers/search.js, packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js, packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
* We want to ensure that translators can properly translate our plugin. This PR adds some translator comments (and improves others) in the JavaScript packages after a run of `wp i18n make-pot . --include="packages/*/src"`. 
* Improves the translator comments for JavaScript translation strings.
* None.
* No tests needed, these are comments and will not change any functionality.
*
*
=> Improves some translator comments

src/context/meta-tags-context.php, src/generators/schema/webpage.php, tests/WP/Generators/Schema/WebPage_Test.php
* We want to encode spaces in URLs which can be present in our schema WebPage properties in case of a multiple keyword search page.
* Encodes possible spaces in URLs used in `@id` and `url` `WebPage` schema piece properties when the schema represents a search results page.
* N/A
* Perform a search with multiple keywords in your website frontend
* Inspect the schema and verify the `@id` and `url` of the `WebPage` schema piece contains `%20` instead of spaces
*
Fixes [#21066](https://github.com/Yoast/wordpress-seo/issues/21066)
=> Encode spaces in webpage id and url

inc/sitemaps/class-post-type-sitemap-provider.php, tests/WP/Doubles/Inc/Post_Type_Sitemap_Provider_Double.php, tests/WP/Sitemaps/Post_Type_Sitemap_Provider_Test.php
*
* Fixes a bug where the image tag would be missing in the home page entry of the XML sitemap when using a static front page.
*
* Install WP + WP SEO
* Create a new page with importing an image.
* Set this page as static home page.
* Visit the `wordpress.test/page-sitemap.xml` and view page source.
* Check the home page code has image tags:
```xml
<url>
<loc>http://wordpress.test/</loc>
<lastmod>2024-01-24T13:19:20+00:00</lastmod>
<image:image>
<image:loc>http://wordpress.test/wp-content/uploads/woocommerce-placeholder.png</image:loc>
    </image:image>
</url>
```
* …
=> Fix filter params for images in sitemap

packages/ui-library/src/elements/file-input/style.css
* Resolves: https://github.com/Yoast/shopify-seo/issues/1549
* [@yoast/ui-library 0.0.1] Fixes a bug where a longer text for the `selectLabel` value would cause alignment issues in the `FileInput` element.
* [shopify-seo] Fixes a bug where the file upload element inside bulk edit and import/export would have strange text alignment  in several languages.
* Changed display flex -> inline-block for label container.
* Start the Storybook (`yarn workspace @yoast/ui-library storybook`)
* Use long selectLabel for file-input 
* expect to see it inline with another part of dropLabel
For Shopify:
* open our app 
* change your shop language to NL/DE
* go to Optimize->Bulk Edit or …
=> Fix multiline label issue for file input

config/scripts/sync-wp-dependencies.js, package.json
We want to sync our JS dependencies to the versions that WordPress provides.
Why? This will make our JS testing and IDE autocompletion actually work with the correct versions. Granted, we actually support multiple versions of WP, this script picks the lowest supported version currently.
* Adds a script to sync the JS dependencies of our packages to the versions used by our lowest supported WordPress version.
* Used a node script, because JS
* Using an allow dependencies list to prevent any extra packages WP uses (that we might also use)
* Using an disallow package list to prevent some of our packages to be included here, because not all of our packages are running inside the WP environment. E.g. our tooling packages
* Huge thanks …
=> Sync JS dependencies (to WP versions)

packages/js/src/components/SidebarCollapsible.js, packages/js/src/elementor/components/fills/ElementorFill.js, packages/js/tests/components/SidebarCollapsibleTest.js, packages/js/tests/components/__snapshots__/SidebarCollapsibleTest.js.snap
* We want to add an `id` to the `SidebarCollapsible` button in the Elementor sidebar in order to make automated testing simpler.
* Adds the possibility to add an `id` to a `SidebarCollapsible` button.
* Adds an `id` to the `Advanced` `SidebarCollapsible` button in the Elementor sidebar. 
* The `id` attribute is added to the button only if the `buttonId` prop of `SidebarCollapsible` is not null. This allows us to incrementally introduce ids when needed.
* Edit a post with Elementor
* Open the `Yoast` sidebar menu
* N/A
Fixes https://github.com/Yoast/wordpress-seo/issues/21035
=> Add id attribute to SidebarCollapsible inner button

admin/filters/class-abstract-post-filter.php, composer.json
*
* Prevents fatal errors when used together with a plugin which hooks into `views_edit-{$post_type}` but doesn't return an array as expected.
*
* Install https://wordpress.org/plugins/woocommerce-product-tabs/ v2.1.0 or [2.1.0.1](https://downloads.wordpress.org/plugin/woocommerce-product-tabs.2.1.0.1.zip)
* v2.1.1 fixes the issue on their side
* see that you don't get a fatal error when visiting the post list
* without this patch you would see:
```
Fatal error: Uncaught Error: WPSEO_Abstract_Post_Filter::add_filter_link(): Argument #1 ($views) must be of type array, null given, called in /home/lopo/Local Sites/development-symlink/app/public/wp-includes/class-wp-hook.php …
```
=> Remove parameter type declaration on method hooked to a WP filter

composer.json, src/context/meta-tags-context.php, src/generators/schema/person.php, src/generators/schema/webpage.php, tests/WP/Generators/Schema/Person_Test.php
* We want to make sure our ProfilePage schema is valid whenever it's used.
* Fixes a bug where the ProfilePage schema node was not valid when it was manually chosen for a page.
* N/A
* Set your site to `person` in the site representation: /wp-admin/admin.php?page=wpseo_page_settings#/site-representation. 
* Select an author on your page.
* Create a new page and set the `Page type` In our Schema settings to `Profile Page`.
* Make sure the following code is visible in your schema and there are no error in the google rich result test (RRT) and schema validator.
NOTE: You will not see ProfilePage in the RRT, but this will work in GSC. See this …
=> Links `Person or Organization` node to the `ProfilePage` Node.

admin/views/licenses.php, css/src/yoast-extensions.css
* We want to update the `Cover all your SEO bases` card in the `Premium` page.
* Adds price and saving information to the `Cover all your SEO bases` card in the `Premium` page.
* N/A
* Go to `Yoast SEO` -> `Premium`
* N/A
Fixes [Plugin ad copy: Add discount on “all plugin subscription” card
#106](https://github.com/Yoast/growth/issues/106)
=> Add discount on all plugins subscription card

src/integrations/front-end-integration.php, tests/WP/Frontend/Front_End_Integration_Test.php
* We want to avoid parsing prev and next link if we have a full url.
* Fixes a bug where next and prev links in query loop would be wrong when disabling `Inherit query from template`.
* Removed code that is no longer supported, for WordPress version 6.1.
* Activate FSE theme, like FSE BlogStory.
* Make sure you have around 10 posts
* In `Settings`->`Reading`->`Blog pages show at most` and change it to 2 so that you would have pagination.
* Edit site through the Site Editor. Appearance->Editor
* Go to Templates ->Blog Home
* Duplicate the Query Loop Block and delete the pagination from the duplication.
* In the block configuration uncheck `Inherit query from template`.
* …
=> Prevent parsing  with full url

tests/WP/Generators/Schema/Person_Test.php, tests/WP/Generators/Schema/WebPage_Test.php
* We want to update some integration tests so that they don't rely on a DI version that can conflict with other tests.
* Updates integration tests to make them more future proof.
*
* N/A
*
*
Fixes #
=> Update tests to not rely on the DI instance of the `Meta_Tags_Context_Memoizer`

packages/js/src/support/app.js
Right now, we only support the English language in support. So, having the Spanish mention confuses the customers, and they reach out to the support team by asking questions in Spanish.
* We removed the Spanish mention from the website and [from the support page](https://yoast.com/help/support/#email), but the Support submenu on the Yoast SEO plugin still shows the Spanish language as supported. Due to this, it confuses the customers, and they reach out to us by sending questions in Spanish language.
Slack: https://yoast.slack.com/archives/C05UTM3LL3X/p1701454733737729
* Removes Spanish from the list of supported languages in the Support page.
*
* …
=> Removed Spanish from the support languages on Yoast SEO > Support page

css/src/yst_plugin_tools.css, packages/js/src/shared-admin/components/premium-upsell-card.js, src/presenters/admin/sidebar-presenter.php
* Adds price and copy
* changed the CTA link to redirect to the checkout page
* We want to update the Yoast SEO sidebar ad.
* Adds more information about Yoast SEO Premium price to the sidebar ad.
*
* Go to `Yoast SEO` -> `General` tab
* N/A
Fixes [Plugin ad copy: add price & microcopy
#103](https://github.com/Yoast/growth/issues/103)
=> Update the sidebar Ad.

packages/ui-library/src/components/textarea-field/index.js
The `TextareaField` used to support properties to disable / mark as read-only, through the rest property in the argument destructuring. When pulled out of the rest property into separate properties, these properties were no longer passed on to the `Textarea` component as part of the expanded props object.
This resulted in the `TextareaField` only being styled as disabled or read-only, while the underlying `<textarea>` actually wasn't in that state and could still be edited.
* Fixes a bug where the "organization description" field would still be focusable via tabbing.
* [@yoast/ui-library 0.0.1] Fixed an unreleased bug where the readonly & disabled props of the `TextareaField` component would not be passed on to the underlying …
=> Ensure disabled and read-only textareas apply this state

composer.json, inc/sitemaps/class-sitemaps-router.php, tests/WP/Sitemaps/Router_Test.php
*
* Fixes a bug where sitemap.xml would redirect to 404 when response from server of  HTTPS property value would be "On".
*
- Make sure the $_SERVER['HTTPS'] variable returns 'On' ( you can set it with xdebug ).
- Go to: https://www.yourwebsite.com/sitemap.xml
*
*
Fixes [Sitemap.xml not redirecting when $_SERVER['HTTPS'] returns 'On' instead of 'on'](https://github.com/Yoast/wordpress-seo/issues/21105)
=> 21105 sitemapxml not redirecting when  serverhttps returns on instead of on

packages/js/src/settings/components/formik-autocomplete-field.js, packages/js/src/settings/components/formik-page-select-field.js, packages/ui-library/src/elements/autocomplete/index.js
* Disable the focus for formik autocomplete fields.
* Disable focus on `Number of Employees` field when it is disabled. 
* [@yoast/ui-library 0.0.1] Adds disabled styling to `AutoComplete` component.
*
* Activate only Yoast SEO free, without premium.
* Go to `Yoast SEO`->`Settings`->`Site representation`
* Go to `Yoast SEO`->`Settings`->`Site basics`
*
*
Fixes ["Number of employees" can be focussed while disabled](https://github.com/Yoast/wordpress-seo/issues/21120)
=> 21120 number of employees can be focussed while disabled

inc/options/class-wpseo-option-social.php, packages/js/src/settings/helpers/validation.js, tests/WP/Inc/Options/Option_Social_Test.php
*
* Adds `x.com` as possible domain for the Twitter validation in our site representation settings.
*
* In the settings, in `Site representation > Other profiles > Twitter`
* Enter a Twitter profile with `x.com`, like `https://x.com/yoast`
* Verify you do not get a validation warning and can save
* Enter a Twitter profile with `twitter.com`, like `https://twitter.com/yoast`
* Verify you do not get a validation warning and can save
* Enter another domain and verify you get a validation warning
* Test with just the handle too?
*
*
Fixes …
=> Add "x.com" as possible domain for the Twitter validation

wp-seo-main.php
*
* Fixes a bug where some custom post types such as Divi layouts could be experiencing problems after activation or deactivation of Yoast SEO.
* Install the Divi theme (ask in Slack if you need it)
* in the Divi Library, create any kind of item, e.g. a section, and save it
* install and activate Yoast SEO
* check that the Divi section can still be edited successfully
* deactivate Yoast SEO
* check that the Divi section can still be edited successfully
*
* any custom post type, so check for regression with the Books and Movies from Test Helper, …
=> Empty rewrite rules on (de)activation instead of flushing them

src/woocommerce-editor/user-interface/woocommerce-editor-seo-group.php, tests/Unit/WooCommerce_Editor/User_Interface/WooCommerce_Editor_SEO_Group_Test.php
* Add a SEO tab next to the General tab in the new Woo editor, when editing a simple product.
* Adds our SEO group to the new WooCommerce block editor when editing a simple product.
* I went with capitals in the class, namespace and test filename, i.e. `WooCommerce` and `SEO`. While not splitting on `_` in the folder structure due to them still being one word/acronym
* I went for the ID `yoast-seo`, i.e. prefixed with `yoast` to try to ensure if is unique
* I did not translate the title because it is our brand name (and changed it to be `Yoast SEO` due to upcoming design peek, though no logo seems possible)
* Enable the new product editor beta: …
=> Adds our SEO group to the WC layout templates

.gitignore, config/grunt/task-config/copy.js, config/webpack/paths.js, config/webpack/webpack.config.base.js, config/webpack/webpack.config.js, packages/js/.eslintrc.js, packages/js/src/woocommerce-editor/blocks/seo/block.json, packages/js/src/woocommerce-editor/blocks/seo/edit.js, packages/js/src/woocommerce-editor/blocks/seo/index.js, packages/js/src/woocommerce-editor/components/seo-slot-fill.js, packages/js/tests/__mocks__/@woocommerce/block-templates.js, packages/js/tests/woocommerce-editor/blocks/seo/__snapshots__/edit.test.js.snap, packages/js/tests/woocommerce-editor/blocks/seo/edit.test.js, packages/js/tests/woocommerce-editor/components/__snapshots__/seo-slot-fill.test.js.snap, packages/js/tests/woocommerce-editor/components/seo-slot-fill.test.js, src/conditionals/conditional-interface.php, src/loadable-interface.php, src/woocommerce-editor/framework/woocommerce-product-block-editor-conditional.php, src/woocommerce-editor/user-interface/woocommerce-editor-seo-block.php, tests/Unit/WooCommerce_Editor/Framework/WooCommerce_Product_Block_Editor_Conditional_Test.php, tests/Unit/WooCommerce_Editor/User_Interface/WooCommerce_Editor_SEO_Block_Test.php
* Add placeholder (slot) to our SEO tab.
* Adds tooling (copy to `blocks` and `artifact` folders) support for `block.json` files within `packages/js/src`. 
* Prevent bundling of any `@woocommerce/` packages, expecting them to all be available on the window within a WP environment.
* Adds a "edit" only `yoast-seo/woocommerce-editor-seo` block, for usage in the WooCommerce product block editor.
* For the block registration, we need access to the `block.json` file. Therefore, we need to ensure the path is the same in development and production (zip).
[This commit](https://github.com/Yoast/wordpress-seo/commit/33ca60e97b382da20f3255b8548d8e88b41f9a21) solves that by effectively making the root blocks folder the "dist" or "build" …
=> WC Editor: add Yoast SEO block

src/context/meta-tags-context.php
* We don't want to show an primary image if there is none.
* Fixes an unreleased bug where image node would be in the schema output for a rest request.
*
* Create a new post without images and remember its ID
* Go to YOUR_BLOG_URL/wp-json/wp/v2/posts/POST_ID
* Make sure that without this PR/RC you see  
```"image": {
"@id": "http://basic.wordpress.test/bla/#primaryimage"
},
```
And no 
```"@type": "ImageObject",
"inLanguage": "en-US",
"@id": "http://basic.wordpress.test/sample-page/#primaryimage",
```
* now activate this RC/PR and make sure the following is gone.
```"image": {
"@id": "http://basic.wordpress.test/bla/#primaryimage"
},
```
* Now add an image to your post …
=> Make sure image is null when it is '' so that the schema generator does not create an empty record.

packages/ui-library/.storybook/preview.js, packages/ui-library/src/elements/autocomplete/style.css, packages/ui-library/src/elements/skeleton-loader/stories.js
* Slate-100 is the background color we use for our UI library powered pages. This adds that as a potential background color to the Storybook to test with.
* Fixes the background of the autocomplete element to span the full width of the element.
* Improves the profile story for the skeleton loader with its own background to look better on other backgrounds.
* [@yoast/ui-library 0.0.1] Fixes a bug where the background of the Autocomplete element would not be applied to the full width of the element.
* Considered to make slate the default background. Decided not to do so, because elements are often used on a Paper/Card/Modal and are therefore on a white background.
**Testing …
=> Add slate background to Storybook

composer.json, src/generators/breadcrumbs-generator.php, tests/Unit/Generators/Breadcrumbs_Generator_Test.php
* We don't want to run an unnecessary query on the homepage that will always return zero results.
* Removes an unnecessary query relating to breadcrumb generation on the homepage.
*
* Enable query monitor
Do these steps for a static and non static homepage:
* Without this PR, go to the homepage and make sure you see the following query (from the `Yoast\WP\SEO\Repositories\Indexable_Hierarchy_Repository->find_ancestors` caller).
* Look at your schema output and take note of the breadcrumb. It should look like:
```
{
"@type": "BreadcrumbList",
"@id": "http://basic.wordpress.test/#breadcrumb",
"itemListElement": [
{
"@type": "ListItem",
"position": 1,
"name": "Home"
}
]
}, …
```
=> Adds exception to the breadcrumb generator that ignores ancestor on the homepage.

packages/js/src/settings/routes/site-representation.js, packages/ui-library/src/elements/text-input/index.js, packages/ui-library/src/elements/text-input/stories.js, packages/ui-library/src/elements/text-input/style.css
*
* Fixes a bug where the Organization's Site founding date would span 2 lines in Chrome, by removing our placeholder.
* [@yoast/ui-library 0.1.0] Fixes a bug where the `TextInput` with type `date` would span 2 lines in Chrome, by removing our placeholder and icon overrides.
* Decided to remove the overrides to keep it simple. Context: https://yoast.slack.com/archives/C03KU0EHCNQ/p1709204321095249
* Go to Settings > Site representation
* Represent an organization
* Go to the founding date 
* Build the storybook
* Go to the TextInput element story
* …
=> 1404 minor organizations founding date field looks broken in new chrome version

packages/js/src/watchers/elementorWatcher.js
* When you save a post with Elementor for the first time we override the slug to the `elementor-*` name. We don't want this to happen and we want to follow the correct slug.
* Fixes a bug where an unneeded redirect would be created when a post was first published in Elementor.
* I added a custom slug creator to make sure we are inline with what the WordPress backend also does when you publish a post.
* I also added a check to only sync this field when to post is still in draft. This is because when you have published a post the slug change needs to be conscious and unrelated to the post title changing.
* Enable Elementor / Premium / Free.
* Create a new post in Elementor …
=> Makes sure the slug is synced correctly when the post is in draft.

config/grunt/task-config/shell.js
* Continuing https://github.com/Yoast/wordpress-seo/pull/20874/ this fixes the build of the assets for Windows environments.
* Fixes the new way of asset building for Windows environments
*
* N/A
*
*
Fixes #
=> Add cross-env before using NODE_ENV

apps/content-analysis/config/paths.js, config/webpack/webpack.config.base.js, packages/components/src/GenerateId.js, packages/js/src/helpers/createInterpolateElement.js, packages/js/src/helpers/replacementVariableHelpers.js, packages/js/src/initializers/post-scraper.js, packages/js/src/workouts/components/WorkoutsPage.js, packages/yoastseo/spec/languageProcessing/languages/en/config/abbreviationsSpec.js, packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getClausesSplitOnStopWords.js, packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/getClauses.js, packages/yoastseo/src/languageProcessing/languages/id/helpers/internal/stem.js, packages/yoastseo/src/languageProcessing/languages/ja/customResearches/findKeyphraseInSEOTitle.js, packages/yoastseo/src/languageProcessing/languages/ru/helpers/internal/stem.js, packages/yoastseo/src/languageProcessing/researches/findKeyphraseInSEOTitle.js, packages/yoastseo/src/markers/addMarkSingleWord.js
* Replace `.substr()` with `.substring()` in JS files since it's deprecated.
* Replacs `.substr()` with `.substring()` in JS files since it's deprecated.
* In substr second parameter is length, in substring second parameter is offset, so corresponding calculation applied to convert length to officet.
* Also substr can consume negative values - in this case it starts counting from the end of the string.
* run unit tests and make sure that all tests pass
* do smoke test for different posts/editors to make sure that everything works as expected
* …
=> Replace .substr() with .substring() (or .slice()) in JS files since it's deprecated

packages/yoastseo/src/languageProcessing/researches/getWordForms.js, packages/yoastseo/src/parse/build/private/tokenize.js
* We profiled our analysis and saw two obvious possibilities for performance enhancements: 
* Use a global `replace` instead of `split` and `join` to replace HTML entities ([reference](https://stackoverflow.com/questions/50463850/split-and-join-function-or-the-replace-function)).
* Use a `Set` to remove duplicates from lists ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)), instead of `uniq` from `lodash`. 
* Improves the performance of the content analysis.
* 
* Confirm all unit tests still pass.
* Smoke test the content analysis, and specifically the keyphrase density assessment. You can take inspiration from this PR: …
=> Small performance enhancements for the content analysis

packages/js/src/settings/routes/templates/post-type.js
~Also decoupled the description from the actual field, so that it can be styled separately.~
* We want to align the `Page type` dropdown field in the `Settings` page to be the same size as the `Article type` field
* Fixes the width of the `Page type` dropdown field in the `Settings` page.
* N/A
* Activate WooCommerce and Yoast SEO Woo
* Go to `Settings` -> `Content type` -> `Products` in the `Schema` section
* check the `Page type` dropdown is disabled and the following text is present under it: `You have Yoast WooCommerce SEO activated on your site, automatically setting the Page type for your products to 'Item Page'. As a result, the Page type selection is disabled.`
* …
=> Re-instate correct max width for page type field.

inc/class-addon-manager.php, tests/Unit/Inc/Addon_Manager_Test.php
* We want to stop showing deprecation warnings when retrieving data for our paid add-ons doesn't populate variables as expected.
* We would like to fix the underlying bug of not having those variables properly populated, but after code inspection, we can't see something that could have interfere with that. Meaning, it might have been a (temporary?) issue of the external service (in this case, MyYoast).
* Stops showing deprecation warnings when retrieving data for paid add-ons goes wrong.
*
You need xDebug to test the fix, since we can't replicate the root cause
* Have an active subscription in yoast.com 
* (I think the easiest way is to create a http://main.local/ site in …
=> Add defensive coding to stop deprecation warnings

src/helpers/image-helper.php, tests/Unit/Helpers/Image_Helper_Test.php, tests/WP/Helpers/Get_Attachment_By_Url_Image_Helper_Test.php
* We don't want unneeded database calls for external images.
* Removes two unnecessary queries on pages where external images are of SEO interest, like author pages with Gravatar author images.
* Removes a duplicated query on author pages with internal images.
*
* Enable QM.
* Make sure author archives are enabled.
* Make an author and set the author of a post to this author.
* Go to the author archive page.
* Without this PR/RC make sure you see the following queries in QM, twice:
```
SELECT `target_post_id`
FROM `wp_yoast_seo_links`
WHERE `url` = '{A_Gravatar_URL}'
LIMIT 1
```
* Take note of the schema and meta tags output on the page.
* Enable the PR and make sure the …
=> Fixes a bug where the attachment would never be marked as external.

admin/watchers/class-slug-change-watcher.php
* We want to have click to buy attributes on all our upsell buttons
* Adds click to buy data attributes to redirect manager upsell button.
*
* Make sure premium is disabled.
* Trash a post and check if the `Get Yoast SEO Premium` button has the following data attributes: 
`data-action="load-nfd-ctb" data-ctb-id="f6a84663-465f-4cb5-8ba5-f7a6d72224b2"`
*
*
Fixes #21230
=> Adds click to buy data attributes.

packages/js/src/settings/helpers/search.js, packages/js/src/settings/routes/site-representation.js
* We want to rename the `leiCode` fields to `LEI code` as the former is just the schema-specific representation of that info and should be made into a more human-readable format.
* Renames the `leiCode` fields to `LEI code` in the plugin's settings
*
* Go to **Yoast SEO**->**Settings**->**Site representation**
* In the **Organization identifiers** section, check that there's the `LEI code` field now (instead of `leiCode` that used to be before this PR)
* Search for both `leiCode` and `LEI code` in the settings search, and both should display the `LEI code` label and setting
* Activate Premium and check the above again …
=> Rename 'leiCode' to 'LEI code'

src/helpers/current-page-helper.php, tests/Unit/Helpers/Current_Page_Helper_Test.php, tests/WP/Helpers/Current_Page_Helper_Test.php
* We want to address an issue created by `ES_WP_Query` used by WordPress VIP when Enterprise Search is enabled.
* Fixes an incompatibility with `ES_WP_Query` library used by WordPress VIP Enterprise Search.
* N/A
<details>
<summary>Install WP VIP development environment</summary>
* Make sure you're using the latest versions of `Node.js` and `npm\ (or at least `Node.js v18` and `npm v8`)
* to check this use `nvm` by typing `nvm use` in the terminal
* to install and use the latest `Node.js` and `npm` type: `nvm install 20 && nvm use 20`
* Install  `VIP_CLI`
* type `npm install -g @automattic/vip`
* Clone the following repository: …
=> Fix ES_WP_Query incompatibility issue

.github/workflows/test.yml, composer.json, composer.lock
*
* Revert Mockery related CI changes
Reverts #21253
Mockery 1.6.11 has been released which solves the problem.
* NA, the tests should just pass
*
*
Fixes #
=> Revert: prevent Mockery to be updated to the buggy 1.6.10 version

tests/Unit/Admin/Suggested_Plugins_Add_Notifications_Test.php, tests/Unit/Admin/Suggested_Plugins_Construct_Test.php
* We want to fix the coverage report that [the original PR](https://github.com/Yoast/wordpress-seo/pull/21198) fail to properly increase.
* While we were at it, we added unit tests for the constructor of `WPSEO_Suggested_Plugins` too.
* Properly reports increase in test coverage in the `WPSEO_Suggested_Plugins` class.
*
* For devs:
* Please be critical in judging whether those tags are properly used. Those new covered functions are passed through the tests but they are not tested against expected values, so feel free to reject this PR, if the tags are added incorrectly here.
* [] QA should use the same steps as above.
* N/A …
=> Fix coverage report for the WPSEO_Suggested_Plugins class

src/helpers/current-page-helper.php, tests/Unit/Helpers/Current_Page_Helper_Test.php
* We want to reinstate the original checks in the `get_term_id` method to keep the exact same behaviour.
* Re-instates the original checks in the `get_term_id` method to ensure API backward compatibility.
* N/A
* Create a file `test.php` in the `mu-plugins` directory of your WordPress installation and paste in it the following snippet
```
<?php
add_action('wp_head', 'test');
function test() {
$h = YoastSEO()->helpers->current_page->get_term_id();
die(var_dump($h));
}
``` 
* Without this branch checked out
* visit a category in the frontend and verify you get a number
* visit a post in the frontend and verify nothing is printed on screen (or something like …
=> Re-instate original checks

src/generators/twitter-image-generator.php, src/helpers/open-graph/image-helper.php, src/helpers/twitter/image-helper.php, src/values/twitter/images.php, tests/Unit/Generators/Twitter_Image_Generator_Test.php, tests/Unit/Helpers/Open_Graph/Image_Helper_Test.php, tests/Unit/Helpers/Twitter/Image_Helper_Test.php
* We want to prevent unsupported image formats to be used for the `twitter:image` meta tag.
* Prevents image formats other than JPG, GIF, PNG and WEBP to be used for the `twitter:image` meta tag.
* Deprecates unused method `is_image_url_valid`.
* N/A
* Set a featured image of an unsupported format (e.g. TIFF; use [this](https://www.simpleimageresizer.com/image-converter) site to convert an image to an unsupported format)
* Visit the post in the frontend
* verify no `twitter:image` nor `open-graph:image` meta tag is present in the page `head`
* Edit the post and set a featured image of a supported type   
Visit the post in the frontend
* verify the …
=> Prevent unsupported images to be used in the twitter image tag

.github/workflows/cs.yml, .phpcs.xml.dist, admin/class-plugin-availability.php, composer.json, composer.lock, config/composer/actions.php, inc/class-addon-manager.php, inc/class-upgrade.php, inc/class-wpseo-admin-bar-menu.php, inc/options/class-wpseo-option-titles.php, inc/sitemaps/class-sitemaps-cache-validator.php, src/editors/application/analysis-features/enabled-analysis-features-repository.php, src/editors/domain/analysis-features/analysis-feature.php, src/editors/domain/analysis-features/analysis-features-list.php, src/generators/breadcrumbs-generator.php, src/helpers/schema/html-helper.php, src/helpers/url-helper.php, src/integrations/front-end/crawl-cleanup-rss.php, src/values/twitter/images.php, tests/Unit/Admin/Suggested_Plugins_Construct_Test.php, tests/Unit/Doubles/Integrations/Settings_Integration_Double.php, tests/WP/Admin/Watchers/Indexable_Ancestor_Watcher_Test.php, tests/WP/Inc/Upgrade_Test.php, tests/WP/Sitemaps/Post_Type_Sitemap_Provider_Test.php, tests/WP/Sitemaps/Renderer_Test.php
* Update dev dependencies
* Update dev dependencies
Nearly all dev dependencies have had new releases. This commit updates the plugin to use the new versions.
For linting, the upgrade will get us preliminary PHP 8.4 support.
For testing, the upgrades will get us continued support for running the tests via a PHAR file after the latest PHPUnit releases, as well as preliminary PHP 8.4 support.
For CS, the upgrades will get us improved syntax support for PHP 8.3, more documentation and a range of bug fixes.
This changes the implementation of the coding standards threshold check to require that both the `YOASTCS_THRESHOLD_ERRORS` environment variable, as well as the `YOASTCS_THRESHOLD_WARNINGS` environment variable match the current …
=> Composer: update dev dependencies + minor CS fixes

inc/class-upgrade.php, tests/WP/Inc/Upgrade_Test.php
* We want to future-proof out plugin by taking into account the changes that will be introduced in WordPress 6.6 by [this](https://core.trac.wordpress.org/ticket/42441) ticket.
* Updates `upgrade_36` upgrade routine and its integration tests to accomodate for the new options autoload behaviour that will be introduced in WordPress 6.6.
* N/A
* With a MySQL client perform the following query to create a new row in the `wp_options`:
```
INSERT INTO wp_options ( option_name, option_value, autoload )
VALUES ( 'wpseo_sitemap_test', 'test', 'yes' );
```
* Go to `Tools` -> `Yoast test`
* In `Plugin options & database versions` set `DB Version` = `3.5` for Yoast SEO
* click save
* …
=> Take into account future changes to WordPress options autoload.

packages/js/src/components/modals/editorModals/SearchAppearanceModal.js
* We want to fix a bug where the snippet editor in the Elementor sidebar would not correctly render the replacement variables values.
* Fixes a bug where the snippet editor in the Elementor sidebar would not correctly render the replacement variables values.
* We introduced the bug with [this PR](https://github.com/Yoast/wordpress-seo/pull/20627): we were using two different `SearchAppearanceModal` components before, one for the block editor and one for Elementor. The PR unifies the two modals but would use the same `SnippetEditorContainer` both for block editor and Elementor.
* Edit a post with Elementor
* Open the Yoast sidebar and click on `Search appearance`
This PR …
=> Use different snippet editor wrappers in Elementor and block editor

packages/js/src/initializers/analysis.js, packages/js/src/initializers/pluggable.js, packages/js/src/woocommerce-editor/initialize.js
* Initialize our editor integration: create out editor store and analysis and expose our APIs
* Initializes our WooCommerce block editor integration in JavaScript, creating our editor store and analysis and exposing our APIs.
**Pluggable**: try `YoastSEO.analysis.run` before `YoastSEO.app.refresh` to refresh the analysis.
This is because I implemented a mix between the current block editor and Elementor. Not exposing `YoastSEO.app.pluggable`, like in Elementor, to try to move to a more module state of pluggable, where we can use the imports internally. But then not using the `runAnalysis`, because that would require having the store subscribes in place and there is really no need as it is an action from outside that updates the …
=> WC editor: create initial Yoast editor integration in JS

composer.json, composer.lock, src/integrations/admin/unsupported-php-version-notice.php
* We want to throw a notice to admins to notify we are dropping compatibility with PHP < 7.4. The date is set to November 1st, 2024.
* Introduces a notice on the WordPress dashboard and the Yoast SEO dashboard to let users know we are dropping support for PHP < 7.4 starting November 1st, 2024.
* We still have the class from the [previous iteration](https://github.com/Yoast/wordpress-seo/pull/19262) as deprecated, so to avoid any conflict/confusion I introduced a new class with a slightly different name
* Run `grunt artifact` to create a zip. This makes it way easier to test on different envs.
* Find a way to have WP running on PHP 7.2 and 7.3.
* e.g. I was able to have a …
=> Use WHIP to deprecate PHP 7.2 and 7.3

composer.json, src/integrations/watchers/indexable-post-meta-watcher.php
* It seems there are scenario's where `deleted_post_meta` is called with an array as the `meta_keys` parameter. We want to safeguard our code, since that gives a fatal in php 8.1
* Fixes a bug where there would be a fatal error when deleting post meta in php 8.1 and higher. props to @izzygld
*
* Make sure you are on php 8.1 or higher.
* Add the following code to your functions.php or a mu plugin.
```
add_action( 'admin_init', 'admin_init_cb', 1 );
function admin_init_cb() {
do_action( 'deleted_post_meta', 1, null, ['this','is','an','array'] );
}
```
* Without this PR/RC make sure you get an fatal error.
* With this pr make sure this error is gone. …
=> Add is_string check to safeguard against array meta keys.

inc/class-upgrade.php, src/integrations/cleanup-integration.php
* To accompany https://github.com/Yoast/wordpress-seo-premium/pull/4277, we want to schedule the Free cleanup further into the future, to avoid a second database operation if we can avoid it
* For that reason, we assume that in most cases Free and Premium will be updated within 24 hours from each other, so this delay of the cleanup schedule will cover most cases
* Schedules the usermeta cleanup further into the future, more specifically 24 hours after the Free upgrade.
* We rely on the delay of the cleanup scheduling, because it covers most cases in the wild. But also, for the cases it doesn't cover, the fallback is not a severe one, we will just perform a second database iteration for the cleanup of the Premium usermeta, so …
=> Schedule the usermeta cleanup 24 hours into the future

composer.json, tests/Unit/Inc/Sitemaps/Sitemaps_Router_Test.php
The test class wasn't running due to the incorrect file name (missing `Test`). Now the tests are being run, the tests were failing.
The first issue is fixed via fixing a typo in a property reference (x2).
However, there is a second issue:
```
1) Yoast\WP\SEO\Tests\Unit\Inc\Sitemaps\Sitemaps_Router_Test::test_template_redirect_exit
Mockery\Exception\InvalidCountException: Method home_url(<Any Arguments>) from Mockery_1 should be called
exactly 1 times but called 2 times.
path/to/wordpress-seo/vendor/mockery/mockery/library/Mockery/CountValidator\Exact.php:38
path/to/wordpress-seo/vendor/mockery/mockery/library/Mockery/Expectation.php:310 …
```
=> Tests: fix incorrect file and class name

packages/ui-library/src/elements/autocomplete/style.css
Fixes: https://github.com/Yoast/shopify-seo/issues/1740 
* In disabled state Autocomplete cursor should be set to not-allowed for whole element, and border color should not change in hover state. 
* [@yoast/ui-library 0.1.0] Improves styling of Autocomplete disabled state.
* Improved CSS styling.
* pull this PR
* run Storybook
* go to Autocomplete component
* set state for component to Disabled = true
* check if cursor on whole element is not-allowed 
* check if after clicking on element border stays gray, not change to primary
Test for Shopify:
- check points from 3 to 6 but on our Overview page -> Category field
Regression test for Free:
* Go to …
=> #1740 - Improve Autocomplete disabled state

composer.json, src/integrations/front-end-integration.php, tests/WP/Frontend/Front_End_Integration_Test.php
*  We want to avoid a PHP deprecation error when instantiating a `WP_HTML_Tag_Processor` by passing `null` as parameter.
* Fixes a bug where a PHP deprecation error would be thrown, when trying to convert a relative URL to an absolute one, with the provided value being `null`.
* N/A
* Make sure you are testing this PR with a version of PHP >= 8.1 and you have Query Monitor active
* Create a post in the block editor
* insert a `query loop` block
* in the block sidebar, toggle `Inherit query from template` off
*  Select the pagination block that has been automatically added, click on the three vertical dots and select `delete`
* Visit the post in the frontend and verify in …
=> Fix PHP deprecation error when passing null instead of string

packages/js/src/shared-admin/helpers/search-appearance-description-mention.js
* We want the date and the separator snippet variables in the meta description text field, to not be displayed for products. 
* Fixes an unreleased bug where the `date` and `separator` replacements variables would inadvertently be displayed in the product's meta description text field. 
*
* Install and activate Free 22.7-RC1 + WooCommerce plugins.
* Create a new product. 
* Go to the SEO/Search appearance tab of the Yoast SEO metabox, and check that the Meta description field doesn't show the Date and Separator variables.
*
* The meta …
=> Removes date and separator from Products meta description text editor field

packages/js/src/structured-data-blocks/faq/block.js, packages/js/src/structured-data-blocks/how-to/block.js
*
*  Improves how the How-To and the FAQ block can be moved and managed in the block editor.
*
*
*
*
Fixes #
=> Improve the blocks behaviour in the editor

packages/js/src/shared-admin/helpers/search-appearance-description-mention.js
* In Firefox, selecting the first word of the description added to the meta description field would also select the fixed variable "Separator". This PR prevents that by adding `&nbsp;` after (and between) the fixed variables.
* Also, in this PR we change the "Separator" to the em dash, to make it's clear that's it's not the same as the "Separator" replacement variable. 
* Fixes an unreleased bug where lack of an element between the fixed variables and the text input by the user could lead to interactions. 
* Fixes an unreleased bug where the fixed variable for Google's separator could be confused with the "Separator" replacement variable. 
* We're using `&nbsp;` as that's the de facto standard to create spacing between elements …
=> Prevents interactions between spans in the meta description field

packages/js/src/components/fills/MetaboxFill.js, packages/js/src/components/fills/SidebarFill.js, packages/js/src/components/slots/MetaboxSlot.js, packages/js/src/components/slots/SidebarSlot.js, packages/js/src/elementor/components/fills/ElementorFill.js, packages/js/src/elementor/components/slots/ElementorSlot.js
* In https://github.com/Yoast/wordpress-seo/pull/20907 we introduced a bug which disrupts the order of the elements in the metabox and sidebar when Yoast SEO Premium is activated. This PR fixes it.
* Fixes a bug where the elements in the Yoast sidebar and metabox are displayed in an incorrect order if Yoast SEO Premium is activated.
* The error boundary enclosing the components if `MetaboxFill`, `SidebarFill` and `ElementorFill` has been removed and placed around the components in `MetaboxSlot`, SidebarSlot` and `ElementorSlot`. This because the components inside each fill are accessed and ordered in the corresponding slots, and because they are all enclosed in the error boundary are seen as a single giant component. Once Premium …
=> Fix metabox and sidebar elements order

inc/options/class-wpseo-option-titles.php, packages/js/src/settings/components/formik-media-select-field.js
*
* Fixes a bug where some Yoast SEO settings could not be imported correctly.
* Fixes a bug where a "Failed to retrieve media" error could prevent selecting a different image or removing the current selection.
* Note that "Tagline" is not a Yoast settings, but we update the WP settings for that. This is why the value is not exported nor imported.
In a site with Yoast SEO Free + Premium (they can be the latest released versions):
1. install the Test Helper and enable the custom post types and taxonomies (Books, Movies and their taxonomies)
2. visit the Yoast settings and make sure to set customized, non-default, recognizable values for the following settings:
* Site …
=> Fix import of `wpseo_titles`

composer.json, src/presenters/open-graph/image-presenter.php, tests/Unit/Presenters/Open_Graph/Image_Presenter_Test.php
* We want to allow users to filter all og:image properties.
* Adds additional filter options for the `og:image` meta tags.
*
* Add an OG image to a post.
* Make sure you have: `meta property="og:image" <meta property="og:image:width"  <meta property="og:image:height"<meta property="og:image:type"`  in your source code.
* Add the following filter and make sure the values change:
```
add_filter( 'wpseo_opengraph_image', 'change_opengraph_image_url' );
add_filter( 'wpseo_opengraph_image_width', 'change_opengraph_image_width' );
add_filter( 'wpseo_opengraph_image_height', 'change_opengraph_image_height' );
add_filter( 'wpseo_opengraph_image_type', …
```
=> Add additional filters to the image presenter.

packages/js/src/structured-data-blocks/faq/block.js, packages/js/src/structured-data-blocks/faq/block.json, packages/js/src/structured-data-blocks/how-to/block.js
* https://github.com/Yoast/wordpress-seo/pull/21329 introduced a limitation of 1 FAQ block per post by mistake, and removed a class from the resulting output for the FAQ and the How To block.
* Fixes a bug preventing multiple _FAQ_ blocks from being added to a post/page.
* Fixes a bug where a class was missing in the output of the _FAQ_ and _How-To_ blocks.
*
* **Important:** test using an artifact instead of just building from the source, since there is an integral part of this PR that is related to copying the blocks JSON to a dist dir and finding it there.
* create a post and add two or more FAQ blocks
* add some questions and answers
* publish it and check the Schema: …
=> Allow multiple FAQ blocks

admin/formatter/class-metabox-formatter.php, tests/WP/Formatter/Metabox_Formatter_Test.php
* This removes a couple of unused array keys.
* Removes some unused translation information from our script data.
*
* There should be no impact. But it is good to smoke test all editors to see that there are no sudden console errors.
* The smoke test should also happen in a language other than English and particularly check the translations in the Yoast metabox and even more specifically in the content analysis.
*
*
Fixes #
=> Remove unused translations

src/integrations/front-end/feed-improvements.php
* We want to fix a bug where we throw a PHP notice when the canonical URL of the parent page wasn't found.
* Fixes a bug where a PHP notice would be thrown on RSS feeds when a canonical URL can not be created for its parent page.
*
_(in all cases, there should be no PHP notices thrown once you load the feeds)_
* Make sure you don't have `Remove post authors feeds` enabled in de crawl optimizations. And make sure you do have author archives enabled.
* Make sure you have 1 author with a post and an indexable.
* Create a fresh author without any posts or indexables.
* Much like the production version: go to http://basic.wordpress.test/author/{authorname}/feed/ where …
=> Adds fallback to main url when the indexable is not available.

packages/js/src/components/contentAnalysis/SeoAnalysis.js
*
* Fixes an unreleased bug where the AI fix assessment buttons would be shown in the in-between page of the Elementor editor.
*
* Activate Elementor and go to create a post with it.
* Make sure you put enough content and set a keyphrase
* Go to `Exit` in the Elementor sidebar and go to the post
* You will land in the Elementor's in between editor page, where there's no block editor nor Elementor editor either. In that page, we shouldn't display the AI fix assessment buttons:
* Now, click on the `Back to WordPress Editor` button and confirm that you indeed want to leave this page
* You'll be presented with the block editor again and now the buttons should be displayed: …
=> Don't show the AI fix assessment buttons in the in-between page of Elementor

packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js, packages/yoastseo/src/languageProcessing/researches/wordComplexity.js, packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
* It's justified for a keyphrase to be a complex words because:
1. It is usually a word that the user searched for and therefore knows
2. keyphrases repeat in a text, sometimes with synonyms, which makes them easier to understand (if not used too many times)
3. Complex words tend to be infrequent and therefore "niche" words, and which is relevant for keyphrases as well, that are totally acceptable to apply in some cases to a "niche" audience.
* Improves _the word complexity assessment_ by preventing keyphrases from being marked as complex.
* [wordpress-seo-premium] Improves _the word complexity assessment_ by excluding keyphrases from the words targeted by the assessment.
* [shopify-seo] Improves _the word complexity assessment_ …
=> Exclude keyphrases from complex words

packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js, packages/yoastseo/spec/scoring/assessments/seo/SubHeadingsKeywordAssessmentSpec.js, packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js, packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
* We do not want to show the sparkle buttons for scenarios we currently do not cover in our prompts.
* Don't show the AI button for _keyphrase in subheading_ assessment and for _keyphrase density_ when the keyphrase is overused in the text.
*
⚠️ Testing only in Free is sufficient
* Create a post in Block/Gutenberg editor
* Add some content to the post. You can use [this post](https://yix.lfg.mybluehost.me/website_795f068c/wp-admin/post.php?post=87&action=edit) alongside the focus keyphrase
* The post above will return 🔴 for Keyphrase in subheading
* `Keyphrase in subheading: Use more keyphrases or synonyms in your H2 and H3 subheadings!`
* Confirm that next to Keyphrase …
=> Don't show sparkle buttons for scenarios we don't cover

css/src/tooltips.css, packages/components/src/AIFixesButton.js, packages/components/src/IconAIFixesButton.js, packages/components/tests/__snapshots__/IconAIFixesButtonTest.js.snap, packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js, packages/js/tests/ai-assessment-fixes/components/AIAssessmentFixesButton.test.js
* We want the `Tooltip` of the AI assessment buttons to be visible on hover over the buttons and to update the text to be: _Optimize with AI_
* Fixes an unreleased bug where the tooltip on the AI assessment buttons would not be visible.
* We have agreed on using a uniform color for the border of the AI assessment buttons. 
* I've refactored the logic that makes the tooltip to be shown by adding or removing the utility classes when the mouse hovers over the buttons. This logic is different than the logic for the other assessment buttons. 
* We have decided to remove the time that delayed the tooltip from being shown. 
* Have Yoast SEO and Yoast SEO Premium activated.
* …
=> Tooltip on ai assessment buttons doesnt show

packages/js/src/settings/routes/site-features.js
*
* Makes `Yoast AI` non-translatable in the feature card
*
* Go to the Yoast->Settings page and check the AI feature card. Confirm it looks like this:
* N/A
*
Fixes #
=> Make Yoast AI non-translatable in feature card

packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
With the refactor of the script data in https://github.com/Yoast/wordpress-seo/pull/21339 we had one change in the data: for terms we now do output a value in `wpseoScriptData.metabox.keyword_usage_post_types`. Before we did not. Unfortunately I missed the console error that produced. This PR is to fix that.
* Fixes an unreleased bug where the previously used keywords was not expecting empty script data.
* [Add safety check](https://github.com/Yoast/wordpress-seo/commit/dd8e71f759d8907bb32200c747afd682c4a6472c) 
We now include an empty array value for terms.
This code will handle an empty array the same as an object with a keyword as key.
Why is it a JS array and not object? It starts as an empty PHP array (I suppose not …
=> Fixes the previously used keywords in terms not expecting script data

admin/metabox/class-metabox.php, src/integrations/third-party/elementor.php
* We forgot to add the removed script data back in Elementor in https://github.com/Yoast/wordpress-seo/pull/21368 😞 
* Fixes an unreleased bug where the website information in the `wpseoScriptData` was no longer present in the Elementor editor.
This PR is adjusting Elementor for:
The removed variables from the `wpseoScriptData.metabox` part:
* Defaults: https://github.com/Yoast/wordpress-seo/pull/21368/files#diff-e578f46d7b0ca259212c2d636041ca36a5de9e6f08d13733890a730354e3886aL56-L69
* Just for posts: https://github.com/Yoast/wordpress-seo/pull/21368/files#diff-3443072aee6094201d9f6c827bb3f27fd6570a9f7769a8cefa9fc8991feb66e8L59-L61
And the removed variables from the `wpseoScriptData` itself:
* …
=> Add website information to the script data in Elementor

config/dependency-injection/deprecated-classes.php, config/dependency-injection/renamed-classes.php, src/deprecated/src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php, src/introductions/application/ai-fix-assessments-upsell.php
* We want to remove deprecation message from admin pages. To do that we need to properly deprecate the whole introduction upsell class and replace it with the new one.
* Remove deprecation message for ai generator for titles and descriptions on Yoast admin pages.
*
* Go to one of yoast admin pages with Premium disabled
* Check you do not see the deprecation message for the `Ai_Generate_Titles_And_Descriptions_Introduction::should_show()` method
* Also smoke test the new upsell appearing properly.
*
Fixes #
=> Deprecate old introduction and fix deprecation messages

css/src/metabox.css
* Provide a nicer user experience in the block editor when using wide screens
* Improves the look of the Yoast SEO metabox in the block editor by centering it and making it stand-out more with using a background color.
* Targeting some specific classes to try and make this only in the block-editor in pure CSS
* ~~Removing `min-height: 100%` to prevent issues with `display: flex`~~
* ~~Check for `.closed` ourselves because `display: flex` overrides the `display: none`~~
* Switched to not using `display: flex`, as the width became as wide as need, resulting in it jumping when you open/close sections
* I enabled all our plugins to test the extra tabs in our metabox
* Edit a …
=> Center the content of the metabox

packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
* Fix content analysis slow down for longer texts with AI activated.
* Fixes an unreleased bug where the content analysis would perform worse when processing longer texts.
* The `researcher.getResearch( "morphology" )` takes some time so it was extracted to higher level from getComplexWords because when we have more than 100 sentences in the post it dramatically slow down processing. 
* Active Premium plugin from branch [feature/fix-assessments](https://github.com/Yoast/wordpress-seo/tree/feature/fix-assessments) and activate AI.
* Create text with many sentences (500+).
* Publish the post and refresh the page.
* Open Premium Analysis - Analysis results.
* Notice the time …
=> With AI activated, content analysis has slowed down for longer texts

packages/search-metadata-previews/package.json, packages/search-metadata-previews/src/snippet-preview/FixedWidthContainer.js, packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js, packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
* Changes are needed for a Premium PR: https://github.com/Yoast/wordpress-seo-premium/pull/4398
* [@yoast/search-metadata-previews 0.1.0] Reads the user agent and shows a different desktop fixed width copy for mobile agents.
* [@yoast/search-metadata-previews 0.1.0] Adds an extra container to the SnippetPreview' FixedWidthContainer, allowing for better outside styling control.
* [@yoast/search-metadata-previews 0.1.0] Changes the FixedWidthContainer to show the scroll hint when a scrollbar is shown instead of whether the `width` prop is larger than the current `width`.
* [@yoast/search-metadata-previews 0.0.1 non-user-facing] Adds a `yarn watch` command for ease of development.
* Using the navigator API to test for the user agent …
=> Tweak SnippetPreview

packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
* We want to disable other AI buttons when one is pressed.
* Disables the rest of the AI buttons when one AI button is pressed. 
*
* Follow the test instructions in https://github.com/Yoast/wordpress-seo-premium/pull/4383.
* Create a post where all the AI buttons are enabled, You can consider [text 3 from the AI test set](https://docs.google.com/spreadsheets/d/1ZHax02aXgjphmhyBe1d7CQN4gcLV-K0u7aeaZdrctAE/edit?gid=333444527#gid=333444527).
* Click on one of them and check the rest are disabled as long as the notification and suggestion are rendered. 
* Check that in this case there is no tooltip on hover.
* …
=> disable AI button when other ai button is pressed.

packages/components/src/IconAIFixesButton.js
* We want to make the aria label not required to have the flexibility not to use the tooltip. Related to [Disable all AI buttons other than the one currently in use](https://github.com/Yoast/wordpress-seo/issues/21481)
* Allow the AI button to be used without tooltip.
*
* Create a post with content and focus keyphrase.
* Make sure the introduction doesn't contain the focus keyphrase.
* Make sure the SEO assessments has also the sparkle for keyphrase density and distribution.
* Click on the sparkle button in the AI assessment fix for keyphrase in introduction. 
* Check the rest of the ai sparkle buttons are disabled and when hovering them you see no tooltip.
* Open dev …
=> Remove aria label required to have the flexibility not to use the tooltip

packages/analysis-report/CHANGELOG.MD, packages/analysis-report/package.json, packages/components/CHANGELOG.MD, packages/components/package.json, packages/replacement-variable-editor/package.json, packages/search-metadata-previews/package.json, packages/social-metadata-forms/package.json, packages/social-metadata-previews/package.json
> [!IMPORTANT]
> Do not rebase this PR. The "Version increase" commit fa510a39754eee264d3cf0a3d2b6189db0e8fdce is the exact version that has been published to NPM. Orphaning this commit will make it impossible to properly determine changes since the published version.
* Prepare and release `@yoast/analysis-report` and `@yoast/components` to NPM again for easier reuse:
- @yoast/analysis-report:2.0.0-alpha.0
- @yoast/components:3.0.0-alpha.1
* Release new package versions.
* Follow-up to #21410 to also publish `@yoast/analysis-report` for consumers.
* Regression test the analysis report in all editors.
* …
=> Release `@yoast/analysis-report` and `@yoast/components` to NPM

packages/ui-library/src/elements/toast/docs/complex-layout.md, packages/ui-library/src/elements/toast/docs/component.md, packages/ui-library/src/elements/toast/docs/index.js, packages/ui-library/src/elements/toast/docs/use-toast-context.md, packages/ui-library/src/elements/toast/index.js, packages/ui-library/src/elements/toast/stories.js, packages/ui-library/src/index.js
* Improve the Storybook documentation of our toast element:
* Improve the alignment of the `with close button` story to better resemble real world usage.
* Add an additional story to showcase a more advanced toast element, using more different components
* [@yoast/ui-library 0.1.0] Exports the `useToastContext` hook to allow dismissing a `Toast` element from a child node.
* Switched ordering of stories to align with the navigation menu
* Reduced boilerplate by using `useToggleState` hook, instead of a combination of `useState` + `useCallback` hooks.
* Exposed the `useToastContext` hook to allow dismissing toasts from child buttons in stories.
* There are already use cases where this can be leveraged.
* Added a (dark mode) code …
=> Improve storybook documentation toast element

composer.json, src/integrations/front-end/crawl-cleanup-rss.php, tests/Unit/Integrations/Front_End/Crawl_Cleanup_Rss_Test.php
* Since WP 6.1 there is a clean native way to disable feeds and we want to use that.
* Updates the crawl cleanup to use the native WordPress way of disabling RSS feeds.
*
* Make sure all toggles in /wp-admin/admin.php?page=wpseo_page_settings#/crawl-optimization in the section Disable unwanted content formats are disabled.
* Open the front-end of a post and make sure the main feed `href="http://basic.wordpress.test/feed/"` and href="http://basic.wordpress.test/comments/feed/"
* Open these links and make sure you seed a feed.
* Enable `Remove global feed` and `Remove global comment feeds` and make sure the links are gone and the feed pages redirect.
---
* Go to an author …
=> Add specific filters to disable feeds.

src/editors/framework/seo/posts/keyphrase-data-provider.php
* Changes back an accidental rename.
* Fixes a bug where the `wpseo_posts_for_related_keywords` filter does not work anymore since it was accidentally renamed.
*
* Open a post and add a keyphrase to that post.
* Paste `wpseoScriptData.metabox.keyword_usage` in the browser console to see the usage of this keyphrase.
* Add the following code to your functions.php:
```
add_filter('wpseo_posts_for_related_keywords', 'enhance_related_keywords');
function enhance_related_keywords($posts) {
$posts['extraPost'] = ['22'];
return $posts;
}
```
* Refresh you post and paste `wpseoScriptData.metabox.keyword_usage` again to see the `extraPost` keyword also added. …
=> rename filter back.

inc/class-wpseo-utils.php, packages/js/package.json, packages/js/src/components/contentAnalysis/SeoAnalysis.js, packages/js/src/redux/reducers/preferences.js
* We do not want to display the AI Optimize buttons when the AI feature as a whole has been disabled.
* Fixes an unreleased bug where the AI buttons would be shown when the AI feature as a whole was disabled.
*
* Enable Yoast SEO premium.
* Go to the Yoast SEO settings and disable the AI feature.
* Edit a post with focus keyphrase and content that doesn't contain it.
* Go to the Premium SEO analysis.
* Check you don't see the Sparkle AI button.
* Go back to Yoast SEO settings and enable to the AI feature.
* Edit the same post and check you see the AI sparkle button.
* …
=> Hides AI buttons when the AI feature is disabled

composer.json, config/dependency-injection/deprecated-classes.php, src/deprecated/src/integrations/admin/disable-concatenate-scripts-integration.php
* We want to deprecate our integration that disables the concatenation of scripts.
* Re-enables the script concatenation that was disabled to prevent a bug with WordPress 5.5.
* [wordpress-seo other] Deprecates the `Disable_Concatenate_Scripts_Integration` class.
*
* There should be no impact from this change.
* The initial [PR](https://github.com/Yoast/wordpress-seo/pull/15923) that introduced this change has some test instructions to follow. Where `load-scripts` is mentioned you should look for that php script in the `head` of your page.
* The initial bug was in the Gutenberg editor. So smoke test that thoroughly to make sure nothing weird happens.
* Note: TasteWP has …
=> Deprecate concatenate scripts integration.

packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js, packages/js/src/redux/actions/AIButton.js, packages/js/src/redux/reducers/AIButton.js, packages/js/src/redux/selectors/AIButton.js, packages/js/tests/ai-assessment-fixes/components/AIAssessmentFixesButton.test.js, packages/js/tests/redux/actions/AIButton.test.js, packages/js/tests/redux/reducers/AIButton.test.js, packages/js/tests/redux/selectors/AIButton.test.js
* With this PR with allow setting a reason for a disabled Yoast AI Optimize button through the Redux store. We basically change the list to an object, with the keys being the buttons that should be disabled, and the values being the reason why they should be disabled.
* Allows setting a reason for a disabled Yoast AI Optimize button.
* We are not using a `Map` because Redux can not store non-serializable objects. 
* Confirm all unit tests pass. 
* See the Premium PR for the remainder of the testing steps.
*
* No other impact.
Fixes …
=> Allows setting a reason for a disabled Yoast AI Optimize button

inc/options/class-wpseo-option-social.php, inc/options/class-wpseo-option.php, tests/Unit/Inc/Options/Option_Social_Test.php
* We want to clean up some unused code in the options handler.
* Removes unused `add_settings_error` function.
*
* Go to wp-admin/admin.php?page=wpseo_page_settings#/site-representation and fill in valid and invalid url's in the Other profiles section to make sure it still validates with the right messages.
* Go to wp-admin/admin.php?page=wpseo_page_settings#/site-connections and fill in valid and invalid connection keys. This can be done by using strings for `Pinterest` to make sure it validates with the right messages.
* 
*
*
Fixes #
=> Remove no longer used `add_settings_error`

packages/js/src/elementor/initializers/editor-integration.js
Fixes two issues coming from: https://github.com/Yoast/wordpress-seo/pull/21514
* timing issue when saving while switching to another post/page
* save action not sending the same data (which broke our Premium redirect notification)
* Fixes an unreleased bug where our save action would not send the same data anymore.
* Fixes an unreleased bug where saving while switching a document would result in a timing issue.
* Added one more "module" variable to keep track of if currently saving or not. Re-used the save hook to get a call when done
* Adapted the AJAX request to always resolve, no longer ignoring errors so we can't get stuck in a frozen state 🧊 
* Activate the top bar …
=> Elementor: fix timing issue after save and before closing the document

packages/js/src/components/SchemaTab.js, packages/js/src/elementor/initializers/editor-store.js, packages/js/src/initializers/editor-store.js, packages/js/src/installation-success.js, packages/js/src/redux/actions/index.js, packages/js/src/redux/reducers/index.js, packages/js/src/redux/selectors/index.js, packages/js/src/shared-admin/store/admin-url.js, packages/js/src/shared-admin/store/index.js, packages/js/tests/shared-admin/store/admin-url.test.js, src/editors/framework/site/base-site-information.php, src/integrations/admin/installation-success-integration.php, tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php, tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
* Lets use `admin_url()` instead of hardcoding to `/wp-admin/`
* Fixes a bug where two of our admin links would not support a possible custom admin URL.
* Add adminUrl slice, copied from Premium (but added tests here) and used script data abstraction to pass the data.
* Go to `/wp-admin/admin.php?page=wpseo_installation_successful_free`
* Open the schema tab
* Edit a post in Elementor
* Open the schema tab
*
*
Fixes #
=> Fix hardcoded `wp-admin` path

src/helpers/first-time-configuration-notice-helper.php, src/integrations/settings-integration.php, wp-seo-main.php
* Refactor filter_input calls in `first-time-configuration-notice-helper.php`.
* Refactor filter_input calls in `settings-integration.php`.
* Removes dependancy on the `filter_input` function
*
* The test the settings, smoke test the settings and see if they still save.
* To check the FTC message. Use the test helper to reset your options and FTC progress.
* Go to any yoastSEO page and see that there is a notification to complete the FTC.
* Remove the notification and refresh and make sure it stays gone.
* …
=> Refactor filter_input and remove dependency.

packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js, packages/yoastseo/src/worker/AnalysisWebWorker.js
* In [this PR](https://github.com/Yoast/wordpress-seo/pull/21400), we introduced a change where we exclude words from the keyphrase being marked as complex words by the word complexity assessment. This change didn't work in Shopify without saving the changes and updating the page. This is because the method that checks whether the readability analysis should be updated did not check whether the keyphrase was updated.
* Note that we didn't have this problem in WordPress, though we are not sure why.
* [shopify-seo] Fixes an unreleased bug where the word complexity assessment wouldn't update when the keyphrase was changed.
*
* Follow the instructions from [this …
=> Fix word complexity assessment not updating in Shopify when the keyphrase is changed

packages/js/src/elementor/helpers/is-form-id.js, packages/js/src/elementor/initializers/editor-watcher.js
*
* Fixes an unreleased bug where slug would change when switching to draft post in elementor editor.
* The check in the action is not enough because the mutatation observer won't turn off
* Create a post with Elementor and keep it as a draft.
* Go back to WordPress admin pages and create another post with Elementor and publish it.
* Edit the published post and inspect the page for hidden field id yoast_wpseo_slug, remember the slug.
* Switch to the draft post within the Elementor editor and check the field with the id yoast_wpseo_slug stays the same.
* Switch back to the original post you published and check the field with the id yoast_wpseo_slug has the same slug and …
=> Only handle editor changes when on the document from our form

packages/analysis-report/src/AnalysisResult.js, packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap, packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
* When adding the AI optimize buttons, we introduced some styling changes to the analysis results to make it look nice when there are two buttons next to an assessment (e.g. highlight and AI buttons). However, this change resulted in very little space left between the assessment text and the buttons in Shopify.
* [shopify-seo enhancement] Increases the spacing between the assessment copy and the highlight buttons.
* [analysis-report] Removes right margins from the `ScoreIcon` and `AnalysisResultText`components and adds a `column-gap` property to the `AnalysisResultBase` component.
* Refactors code related to the spacing between columns in the analysis results (score icon, assessment text, buttons).
* We solved the issue by adding …
=> Add column-gap to each column inside the AnalysisList

inc/class-wpseo-utils.php, src/analytics/user-interface/last-completed-indexation-integration.php, tests/Unit/Analytics/User_Interface/Last_Completed_Indexation_Integration_Test.php
*
* Improves our integration with cache plugins by preventing flushing their cache when not needed.
* [wordpress-seo non-user-facing] Stops using W3 Total cache's deprecated `w3tc_pgcache_flush` function in favor of the `w3tc_flush_posts` one.
* Checked other usages of the `update_option_wpseo` hook to verify we're not breaking something
* Found a couple of them in the `Option_Wpseo_Watcher` that won't run anymore when we store the logging option, but that's ok because they deal only with a different option.
* Complete the SEOO
* Install WP Super Cache and select `Caching On` in **Settings->WP Super Cache** (or W3 Total cache and enable Page Cache in …
=> Stop flushing cache aggressively when not needed

packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
* We can get rid off feedback string variables that are very specific and only used for one phrase.
* Removes unnecessary inclusive language feedback string variables.
* [shopify-seo] Removes unnecessary inclusive language feedback string variables.
*
* Add the non-inclusive phrases 'senile' and 'special needs' to the text
* Confirm that you get the following feedback in the inclusive language analysis:
* 🔴  Avoid using senile as it is potentially harmful. Consider using an alternative, such as a specific characteristic or experience if it is known (e.g. has Alzheimer's). [Learn more.](https://yoa.st/inclusive-language-age?php_version=8.1&platform=wordpress …
=> Remove unnecessary inclusive language feedback string variables

admin/metabox/class-metabox.php, packages/js/src/initializers/featured-image.js, packages/js/src/post-edit.js, src/integrations/third-party/elementor.php
* We want to remove the feature image notice translation from the script data.
* Moves the translation for featured image notice to the feature image integration.
* The featured image integration is supported only by classic editor and block editor. In the block editor we don't have the notice but we are adding the image to the analysis data.
* No support for elementor yet.
* Edit a post in classic editor and try to upload a tinny featured image ( under width and height of 200px).
* Check that you see a red notice: 
> SEO issue: The featured image should be at least 200 by 200 pixels to be picked up by Facebook and other social media sites.
* Upload the same featured …
=> 21555 remove featured image notice translation from wpseoscriptdata

packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js, packages/yoastseo/src/languageProcessing/researches/findKeywordInFirstParagraph.js
* With this PR: https://github.com/Yoast/wordpress-seo/pull/21414 we excluded the image captions from the keyphrase in introduction assessment for all editors. However, the solution still doesn't exclude the image caption inside a classic block in Block editor. This PR is to fix that issue.
* Fixes a bug where an image caption inside a classic block would be considered the introduction when using the _keyphrase in introduction_ assessment in the default editor.
* [yoastseo enhancement] Excludes the image caption inside a classic block from the _keyphrase in introduction_ assessment.
*
* Test together with this accompanying PR in Premium: …
=> exclude image caption inside classic block from keyphrase in intro assessment

admin/class-config.php, admin/taxonomy/class-taxonomy.php
* We want to remove the media translation from the taxonomy editor class following https://github.com/Yoast/wordpress-seo/pull/21553.
* Remove translation for outdated media field.
* Missed translation to be removed in https://github.com/Yoast/wordpress-seo/pull/21553.
* Search there is no instance of `choose_image` in the code base.
*
*
Fixes [Remove media translation from wpseoScriptData](https://github.com/Yoast/wordpress-seo/issues/21554)
=> Remove outdated media translation, related to #21554

src/conditionals/check-required-version-conditional.php, src/initializers/plugin-headers.php, src/integrations/admin/check-required-version.php
*
* Prevents the installation of addons requiring a higher Yoast SEO version than the current one if the `YOAST_SEO_CHECK_REQUIRED_VERSION` is set.
* We need to inject the custom header via an initializer since the cache might be primed with the plugins data earlier in the process
* I did not add tests since the methods are not easy to trigger outside the flow of the plugin update
**Important**: Use the provided zips (see [Slack](https://yoast.slack.com/archives/C03KU0EHCNQ/p1724853605240619))
* Connect a site (e.g. a TasteWP site) to MyYoast (you need all the addons, not just Premium)
* install and activate Free 22.7-requirement-check
* set the feature flag by adding …
=> Add an integration to check the `Requires Yoast SEO` header.

packages/js/src/elementor/initializers/editor-watcher.js
* The editor watcher would still be able to run on a document that is not our form due to our debounce timing. When this document is a draft it would update the slug still! Which should never happen.
* Fixes an unreleased bug where switching from a page to a draft post would cause a slug change.
Preventing the update is already done by comparing the document ID to the form ID in `handleEditorChange`. However, I refactored the whole mutation observer to be stopped when the document changes. And the extra important bit there: also cancelling pending editor changes (i.e. stopping the debounce from triggering later) should be the proper prevention. 
It made sense to then change the mutation observer code to just have 1 active and …
=> Elementor: stop editor watcher when switching the document

packages/ui-library/src/components/autocomplete-field/index.js, packages/ui-library/src/components/autocomplete-field/style.css, packages/ui-library/src/components/tag-field/style.css, packages/ui-library/src/components/toggle-field/style.css
* The autocomplete fields for the policy configurations don't have their descriptions grayed out under the upsell section. This change ensures those descriptions will have the correct opacity.
* As a side effect, this ensures all descriptions in a disabled `AutocompleteField` receive this same opacity.
* This also aligns the disabled behavior between Field components in regards of the used cursor on the disabled description.
* [@yoast/ui-library 0.0.1 bugfix] Fixes a bug where the description of a disabled AutocompleteField would not become grayed out.
* [@yoast/ui-library 0.0.1 bugfix] Fixes a bug where the description of a disabled TagField showed a "not-allowed" cursor.
* [@yoast/ui-library 0.0.1 bugfix] Fixes a bug where the …
=> Improve disabled state of UI library field components

admin/metabox/class-metabox.php, packages/js/src/components/SchemaTab.js, packages/js/src/containers/SnippetEditor.js, packages/js/src/redux/selectors/editorContext.js, packages/js/src/redux/selectors/isWooSEO.js
* We want to remove `woocommerceUpsell` property from `wpseoScriptData` to slim down the scriptData as part of a process to decouple it from the global post.
* Removes the `woocommerceUpsell` property from `wpseoScriptData`.
* In a the PR [Move links from wpseoScriptData to JS](https://github.com/Yoast/wordpress-seo/issues/21580) I removed the links from the sciptData. If that Pr will be merged before this PR, we will need to remove the import of `get` from `lodash`.
* Install Woocommerce.
* Make sure you don't have Woo SEO installed.
* Edit a post and check you get the the upsell ad on the search preview and schema tab.
* …
=> 21588 remove woocommerceupsell from wpseoscriptdata

admin/metabox/class-metabox.php, inc/class-wpseo-meta.php
* Translation are no longer done on server side.
* Removes outdated translations properties from fields definitions.
*
* Those translation are not used anywhere.
*
*
Fixes [Remove outdated properties in WPSEO_Meta for translations](https://github.com/Yoast/wordpress-seo/issues/21575)
=> 21575 remove outdated properties in wpseo meta for translations

admin/class-premium-upsell-admin-block.php, admin/menu/class-base-menu.php, admin/views/licenses.php, css/src/admin-global.css, css/src/adminbar.css, inc/class-wpseo-admin-bar-menu.php, packages/js/src/components/BlackFridayPromotion.js, packages/js/src/components/UpsellBox.js, packages/js/src/elementor/components/fills/ElementorFill.js, packages/js/src/helpers/shouldShowWebinarPromotionNotification.js, packages/js/src/hooks/use-first-eligible-notification.js, packages/js/src/settings/app.js, packages/js/src/shared-admin/components/premium-upsell-card.js, src/integrations/alerts/black-friday-promotion-notification.php, src/integrations/settings-integration.php, src/integrations/support-integration.php, src/presenters/admin/sidebar-presenter.php, src/promotions/domain/black-friday-promotion.php, tests/Unit/Integrations/Support_Integration_Test.php
*
* Adds black friday promotion dates and content.
* I chose to rename the promotion instead of making it global to make sure all dismissed notifications show up again.
* Disable Yoast SEO Premium
* Make sure you don't have any dismissed notification
* go to the db of your installation
* in the table `wp_usermeta` search for the line where `user_id` is your user id and `meta_hey` is `_yoast_alerts_dismissed` 
* remove the content of `meta_value` of that line
* Copy the following in that file:
```
<?php
namespace Yoast\WP\SEO\Promotions\Domain;
/**
* Class to manage the Black Friday promotion.
*/
class Black_Friday_Promotion extends Abstract_Promotion implements …
```
=> Updates BF banners and sets the correct date.

apps/README.md, apps/content-analysis-api/package.json, apps/content-analysis-api/yarn.lock
* In the Content Analysis API, we need to have the Premium configuration present if we want to return feedback for those assessments. This PR ensures that the Premium configuration is present by adding `pretest` to the `postinstall` command. 
* [apps/content-analysis-api] Adds a pretest step to the postinstall script to ensure the Premium configuration is fetched.
* None.
* Remove the Premium configuration (folder `premium-configuration`) from `packages/yoastseo`. 
* Run `yarn install` in `apps/content-analysis-api`. 
* Confirm the folder `premium-configuration` is now present in `packages/yoastseo`. 
_This PR is not relevant for QA_ …
=> Adds pretest to the postinstall to ensure the Premium configuration is fetched

packages/js/package.json, packages/js/src/inline-links/edit-link.js, packages/js/src/inline-links/inline.js, yarn.lock
*
* Fixes a bug where the link popover would be hidden when editing post in tablet/mobile view. Props to [stokesman](https://github.com/stokesman).
* Disabled prop types lint error since Link is not a react component.
For context: [This is a video showing the bug.](https://github.com/Yoast/wordpress-seo/issues/21602#issuecomment-2331853362)
* Edit a post
* Select text and try to add it a link, see that you get a popover with an input to add a link.
* Switch to the tablet or mobile view and try to see that you still get the same popover.
* Quickly smoke test our integration with the block …
=> Implement useAnchor

inc/class-wpseo-utils.php, packages/js/src/redux/reducers/preferences.js, src/editors/framework/integrations/news-seo.php, tests/Unit/Editors/Framework/Integrations/News_SEO_Test.php
*
* Refactor check for news SEO add-on.
*
* Activate News SEO
* Edit a post
* Open console and execute:
```js
wp.data.select( "yoast-seo/editor" ).getPreference( "isNewsEnabled" );
```
* Deactivte News SEO
* Edit a post 
* Open console and execute:
```js
wp.data.select( "yoast-seo/editor" ).getPreference( "isNewsEnabled" );
```
*
*
Fixes [Refactor is news SEO active](https://github.com/Yoast/wordpress-seo/issues/21619)
=> 21619 refactor is news seo active

packages/js/src/components/PrimaryTaxonomyPicker.js, packages/js/src/components/TaxonomyPicker.js
Gutenberg 19.1 added a deprecation warning for SelectControl via https://github.com/WordPress/gutenberg/issues/38730 This opts in to that behavior and adds the margin top to the ExternalLink below (therefor needing block layout to get the margin to take effect)
The `__nextHasNoMarginBottom` prop is available since Gutenberg 13.4, included in WP 6.0. So it should be safe to use.
* Prevents a deprecation warning when editing a post with Gutenberg version 19.1.
*
* Edit a post
* Open the settings panel
* Add multiple categories
* Verify the Primary Taxonomy picker still has the same spacing between the select and the external link below:
* Install and activate Gutenberg 19.1 …
=> Fix SelectControl deprecation warning

inc/class-wpseo-utils.php, packages/js/src/redux/reducers/preferences.js, src/editors/framework/site/base-site-information.php, tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php, tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php, tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
* Refactor isPrivatBlog preference.
* Refactors isPrivateBlog preference.
*
* Go to Settings->Reading and tick the checkbox for `Search engine visibility`
* Edit a post and go to Advanced tab
* Go to Settings->Reading and uncheck the checkbox for `Search engine visibility` 
* Edit a post and go to Advanced tab
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21628
=> 21628 refactor isprivateblog preference

admin/class-config.php, admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, src/integrations/third-party/elementor.php
* 
* Removes outdated user language code property from window object. 
* The property was added on the PHP/JS side in #15083, but then removed on the JS side in #18967 and #19022.
*
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21626
=> cleanup: remove outdated userLanguage property

admin/formatter/class-metabox-formatter.php, packages/js/src/elementor/initializers/editor-store.js, packages/js/src/initializers/editor-store.js, src/editors/framework/site/base-site-information.php, src/editors/framework/site/post-site-information.php, src/editors/framework/site/term-site-information.php, tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php, tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php, tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
*
* Refactor sitewide Social image property.
*
* Activate Yoast Premium
* Go to Yoast SEO->Settings->Site Basics
* Add site image
* Leave the settings and edit a post
* Go to social appearance
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21630
=> 21630 refactor sitewide social image preference

packages/js/src/dashboard/app.js, packages/js/src/dashboard/components/index.js, packages/js/src/dashboard/components/notifications.js, packages/js/src/dashboard/components/problems.js, packages/js/src/dashboard/routes/alert-center.js, packages/js/src/dashboard/routes/first-time-configuration.js, packages/js/src/dashboard/routes/index.js
Removed changes to grid for sidebar recommendation because it should be under alert center component
*
* Add paper styling to different components that are part of the new dashboard.
* I removed the changing of a class related to premium because it should be in the Alert center.
Following this [design ](https://www.figma.com/proto/DXKVj4tji7M65FYCYwBFUl/General-page?page-id=368%3A3494&node-id=459-2694&viewport=257%2C287%2C0.09&t=udRB6dvCvTTkJZHO-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=368%3A3996&hide-ui=1), ignore the sidebar recommendation and the bottom ad card for now.
* Check that the Alert center tab content has the Paper design.
* Check that …
=> feat: added paper inside the components

admin/menu/class-admin-menu.php, css/src/new-dashboard.css, src/dashboard/user-interface/new-dashboard-page-integration.php, tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
*
* Moves the new dashboard page to the root of the Yoast SEO menu
*
* Add the `define( 'YOAST_SEO_NEW_DASHBOARD_UI', true );` define
* Go to the `Yoast SEO` menu item or to the `Yoast SEO->General` menu item 
* Confirm that you see the new dashboard design
* Remove the define and refresh
* Confirm that you see the old page
* Regression test the Yoast menu item in all scenarios, both with the define enabled and disabled (the only difference should be that with the define enabled, you see the new dashboard when expected)
* In multisite
* When not an admin but with other user roles
* With …
=> Make new dashboard page the root of the Yoast SEO menu

admin/class-config.php, src/dashboard/user-interface/new-dashboard-page-integration.php, src/helpers/notification-helper.php, tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
* We want to add the data we need for the notification ui to the script data.
* Adds notification and problem information to the script data.
*
* Make sure you see a notification in the old dashboard. You can make this happen by resetting your indexables.
* Add the following code to you project: `define( 'YOAST_SEO_NEW_DASHBOARD_UI', true );`
* Open the console on the new general page and type `window.wpseoScriptData.notifications.active` And make sure you see a notification. 
*
*
Fixes #
=> 275 preprare backend to hook problems and notifications into alert center front end

admin/class-config.php
Fix for https://github.com/Yoast/wordpress-seo/pull/21647
Errors resulting from not loading in the config_page script & style on other pages when the New Dashboard UI feature flag is enabled.
* Fixes an unreleased bug where the `NEW_DASHBOARD_UI` feature flag would negatively influence other admin pages.
* It should keep the same behavior, except when on the new dashboard page. I.e. dashboard page AND the feature flag
* Enable the feature flag for the new dashboard. By adding the following in `wp-config.php`:
```php
define( 'YOAST_SEO_NEW_DASHBOARD_UI', true );
```
* Be sure to activate Premium, News and Local
* Open the console
* Error was: `[Uncaught ReferenceError: …
=> Fix not loading config_page scripts

admin/class-yoast-notification-center.php
* We want to avoid triggering a fatal error if `exit` is called early in a WordPress request lifecycle.
* Fixes a bug where another plugin running the `exit()` function inside the `plugin_loaded` hook would result in a fatal error. Props to @menno-ll.
* N/A
* In `wp-content/plugins` create a new folder named `zzzz` 
* inside the folder create the file `zzzz.php` and copy-paste the following in it:
```php
<?php
/**
* Plugin Name: ZZZZ
* Version:     1.0.0
* Plugin URI:  https://level-level.com
* Description: Test plugin calling exit
* Author:      Level Level
* Author URI:  https://level-level.com
* Text Domain: zzzz
* Domain Path: /languages/
* License:     GPL v3
*/ …
```
=> Fix fatal error when other plugin runs exit() on plugins_loaded hook.

admin/class-yoast-notification.php, packages/js/src/dashboard/components/alerts-list.js, packages/js/src/dashboard/components/alerts-title.js, packages/js/src/dashboard/components/index.js, packages/js/src/dashboard/components/notifications.js, packages/js/src/dashboard/components/problems.js, packages/js/src/dashboard/initialize.js, packages/js/src/dashboard/store/alert-center.js, packages/js/src/dashboard/store/index.js, packages/js/src/dashboard/store/preferences.js, packages/js/tests/dashboard/components/__snapshots__/alerts-list.test.js.snap, packages/js/tests/dashboard/components/__snapshots__/alerts-title.test.js.snap, packages/js/tests/dashboard/components/__snapshots__/notifications.test.js.snap, packages/js/tests/dashboard/components/__snapshots__/problems.test.js.snap, packages/js/tests/dashboard/components/alerts-list.test.js, packages/js/tests/dashboard/components/alerts-title.test.js, packages/js/tests/dashboard/components/collapsible.test.js, packages/js/tests/dashboard/components/notifications.test.js, packages/js/tests/dashboard/components/problems.test.js, packages/js/tests/dashboard/store/alert-center.test.js, src/dashboard/user-interface/new-dashboard-page-integration.php, src/helpers/notification-helper.php, tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
*
* Adds alert center to dashboard redux store.
* I added a method to get the message from the notification object for the paragraphs. 
* Go to Yoast SEO -> General page and check you notifications and problems. ( You can trigger notification by adding new content types and resetting the indexables in the yoast test helper, you can trigger problems by disabling `Search engine visibility` in the Settings->Reading)
* Add the following line in `wp-config.php` or snippets plugin: 
```php
define( 'YOAST_SEO_NEW_DASHBOARD_UI', true );
```  
* Go to Yoast SEO -> General page
* …
=> Adds alert center redux store

css/src/new-dashboard.css
* We want buttons to look like our normal buttons.
* Changes the ui for the buttons in the notification centre.
*
* Use the Yoast test helper to reset your indexables.
* You should see the `Because some of your SEO data was reset by the Yoast Test Helper, ` notification.
* Make sure the button looks like a `small secondary` button.
*
*
Fixes #
=> 21657 the buttons displayed in the notifications can get a secondary small styling

composer.json, src/integrations/watchers/search-engines-discouraged-watcher.php, tests/Unit/Integrations/Watchers/Search_Engines_Discouraged_Watcher_Test.php
* We want to reset `ignore_search_engines_discouraged_notice` once user set his site to public again.
* Resets the notice for search engines discouraged when changing Search engine visibility to visible.
*
* Go to Settings->Reading and check the checkbox for  Search engine visibility and save.
* Check you see in admin pages and in the notification center the following message:
> Huge SEO Issue: You're blocking access to robots. If you want search engines to show this site in their results, you must [go to your Reading Settings](http://wordpress.test/wp-admin/options-reading.php) and uncheck the box for Search Engine Visibility. `I don't want this site to show in the …
=> refactor: restore the ignore_search_engines_discouraged_notice option

src/editors/framework/site/base-site-information.php, src/editors/framework/site/post-site-information.php, tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php, tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php, tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
* We want to add the Black Friday ads to our Yoast editor  when editing taxonomies.
* Add Black Friday promotion ad to taxonomies editor.
* 
* Make sure Yoast premium is not active.
* Enable Black Friday promotion by editing `src/promotions/domain/black-friday-promotion.php` replace line 16:
```php
new Time_Interval( \gmmktime( 12, 00, 00, 11, 28, 2023 ), \gmmktime( 12, 00, 00, 12, 3, 2024 ) )
```
* Edit a category or any taxonomy and check you see the black friday ad on the editor and when clicking on "Add related keyphrase".
* Click on SEO analysis and click "add synonyms" the upsell modal should contain the Black Friday promotion.   …
=> fix: move promotion properties to site base info

packages/js/src/dashboard/app.js, packages/ui-library/src/components/sidebar-navigation/collapsible.js, packages/ui-library/src/components/sidebar-navigation/icon.js, packages/ui-library/src/components/sidebar-navigation/index.js, packages/ui-library/src/components/sidebar-navigation/item.js, packages/ui-library/src/components/sidebar-navigation/link.js, packages/ui-library/src/components/sidebar-navigation/list.js, packages/ui-library/src/components/sidebar-navigation/menu-item.js, packages/ui-library/src/components/sidebar-navigation/sidebar.js, packages/ui-library/src/components/sidebar-navigation/stories.js, packages/ui-library/src/components/sidebar-navigation/style.css, packages/ui-library/src/components/sidebar-navigation/submenu-item.js
*
* Refactors the UI library SidebarNavigation change from [#21614](https://github.com/Yoast/wordpress-seo/pull/21614).
* [@yoast/ui-library 0.1.0 enhancement] Adds lower level components to SidebarNavigation: List, Item, Collapsible, Link and Icon.
* [@yoast/ui-library 0.0.1 bugfix] Fixes a bug where the SidebarNavigation colors would not be consistent on indentation.
* [@yoast/ui-library 0.0.1 bugfix] Fixes a bug where the SidebarNavigation spacing would cause overlapping when focused or active.
[Abstract out SidebarNavigation building blocks](https://github.com/Yoast/wordpress-seo/commit/6866b5d6c6b45af0619468fa03ee57c230dedcfc) 
The current MenuItem and SubmenuItem are doing too much and are a bit confusing.
This creates sub …
=> Fix SidebarNavigation menu and submenu items

admin/class-admin.php, admin/views/tabs/tool/import-seo.php, src/integrations/admin/first-time-configuration-notice-integration.php, src/integrations/admin/installation-success-integration.php, src/integrations/admin/old-configuration-integration.php, src/integrations/admin/workouts-integration.php, tests/Unit/Integrations/Admin/First_Time_Configuration_Notice_Integration_Test.php, tests/Unit/Integrations/Admin/Installation_Success_Integration_Test.php
*
* Updates the FTC link wherever it's used in the plugin
* Went with replacing each link instead of filtering all the `admin_url` calls, as per [this conversation](https://yoast.slack.com/archives/C03KU0EHCNQ/p1727335955308109?thread_ts=1727332585.854019&cid=C03KU0EHCNQ).
For each of the below tests, test with the `YOAST_SEO_NEW_DASHBOARD_UI` feature flag both enabled and disabled.
**For the FTC admin notice**:
* In a fresh install (or with options reset from the Yoast Test Helper), check that you see the following admin notice:
* Click on the **First Time Configuration** link
* Confirm that you are redirected to the FTC tab in the dashboard
**For the redirection from …
=> Fix FTC navigation

packages/js/src/components/UpsellBox.js
*
* Adds promo code to Black Friday ad in the upsell modals.
*
* Make sure Yoast premium is not active.
* Enable Black Friday promotion by editing `src/promotions/domain/black-friday-promotion.php` replace line 16:
```php
new Time_Interval( \gmmktime( 12, 00, 00, 11, 28, 2023 ), \gmmktime( 12, 00, 00, 12, 3, 2024 ) )
```
* Edit a post and click on the "Add related keyphrase" and "Add synonyms" links.
*
*
Fixes [23.6 - BF - Black Friday promo code is missing in upsell popup](https://github.com/Yoast/plugins-automated-testing/issues/1866)
=> Adds promo code to upsell ad in upsell modals

packages/js/src/shared-admin/components/premium-upsell-card.js, src/presenters/admin/sidebar-presenter.php
*
* Removes the mention of price in the Black Friday sidebar ad in the Yoast admin pages.
*
* Make sure Yoast Premium is not active.
* Enable Black Friday promotion by editing `src/promotions/domain/black-friday-promotion.php` replace line 16:
```php
new Time_Interval( \gmmktime( 12, 00, 00, 11, 28, 2023 ), \gmmktime( 12, 00, 00, 12, 3, 2024 ) )
```
* Go to the General admin page
* Look at the sidebar
* You can verify the same for the other PHP admin page: Tools. However, it uses the same code.
* Go to the Settings admin page
* Look at the sidebar
* …
=> Remove mention of price in BF sidebar ad

src/actions/indexing/abstract-indexing-action.php, src/actions/indexing/indexable-term-indexation-action.php, src/actions/indexing/term-link-indexing-action.php
*
* Fixes a bug where a database error would occur when there were no public taxonomies available for indexing.
*
* In a website with no other custom taxomies (so a website with only Yoast SEO enabled), add the following filter, so as to have no public taxonomies:
```
add_filter( 'wpseo_indexable_excluded_taxonomies', 'exclude_category' );
function exclude_category ( ) {
return ['category', 'post_tag', 'post_format'];
}
```
* Use the Yoast Test Helper to reset indexables and also run the `wp transient delete --all` WP CLI command
* Visit the Yoast SEO->Tools page
**Without this PR**:
* You would get a 
```
WordPress database error: [You have an error in your SQL syntax; …
```
=> Dont query for unindexed stuff if no public taxonomies

packages/js/src/ai-generator/components/modal-content.js, packages/js/src/ai-generator/initialize.js, packages/js/src/redux/reducers/editorContext.js, packages/js/src/redux/selectors/editorContext.js, packages/js/src/redux/selectors/preferences.js, packages/js/src/term-edit.js
* We are going to enable Yoast AI Generate for product taxonomies, see https://github.com/Yoast/wordpress-seo-premium/issues/4482. This PR adds an upsell for that functionality in Free.
* Adds an upsell for Yoast AI Generate on WooCommerce product categories and tags.
* This PR slightly refactors the original implementation. I personally find the code more readable now 😅 
* See [the ATP](https://docs.google.com/document/d/1RGFhYdF2eaBn6BHaA_QGCO3Wjy7ARXP_GNKrnoS6sUA/edit#heading=h.qft97prdszns). 
* Confirm that the upsell is correct for other post types:
* For regular posts and taxonomies, the upsell modal is the same as before (and does not mention "products")
* For …
=> Adds Yoast AI Generate upsell for WooCommerce product categories and tags

config/dependency-injection/deprecated-classes.php, src/context/meta-tags-context.php, src/deprecated/src/helpers/request-helper.php, src/integrations/blocks/breadcrumbs-block.php, src/integrations/front-end-integration.php, src/integrations/third-party/wincher-publish.php, src/surfaces/helpers-surface.php, tests/Unit/Context/Meta_Tags_Context_Test.php, tests/Unit/Integrations/Front_End_Integration_Test.php, tests/Unit/Integrations/Third_Party/Wincher_Publish_Test.php, tests/WP/Frontend/Front_End_Integration_Test.php
*
* Replace custom code with core's `wp_is_serving_rest_request()`
*
All instructions are basically regression tests.
For meta tags context:
* Have a post with no feature image and with an image in the content
* Visit the post with this PR and without and confirm that the meta tags and the schema stays the same
* Visit the post in REST API (aka, `http://ai.local/wp-json/wp/v2/posts/<POST_ID>` with this PR and without and confirm that the `yoast_head` attribute stays the same
* Now add a feature image in the post and repeat the test
For breadcrumb block:
* Have a post with a breadcrumb block
* Visit the post with this PR and without and confirm that the content stays the …
=> Replace request helper usage with core function

packages/js/src/shared-admin/components/premium-upsell-card.js, src/presenters/admin/sidebar-presenter.php
* Change the Black Friday ad title
* Updates the Black Friday ad title.
* N/A
* Make sure Yoast Premium is not active.
* Enable Black Friday promotion by editing `src/promotions/domain/black-friday-promotion.php` replace line 16:
```php
new Time_Interval( \gmmktime( 12, 00, 00, 11, 28, 2023 ), \gmmktime( 12, 00, 00, 12, 3, 2024 ) )
```
* Go to `Yoast SEO` -> `General`
* Verify the Black Friday ad title  in the sidebar is `Buy Yoast SEO Premium` and not `All annual plans incl.`
* Go to `Yoast SEO` -> `Settings and verify the same  
* N/A
Fixes …
=> Change BF ad title

packages/js/src/dashboard/components/sidebar-recommendations.js, packages/js/src/dashboard/routes/alert-center.js
*
* Separate ad from alerts cards grid in the general page, fix grid height and sticky effect to the upsell sidebar.
*
* Deactivate premium if it's active.
* Enable the new general page by adding:
```php
define( 'YOAST_SEO_NEW_DASHBOARD_UI', true );
```
* Check that the ad under the cards in the new general page is not the same width as the cards:
This is an example of how it looks like without this PR:
* Check the alerts card problems and notification can be in different heights, not like in the above screenshot
* Check the sidebar is sticky to the top of the alert center.
* Check sidebar recommendation is responsive.
*
This …
=> Separate ad from the alerts card grid, fix grid and sticky upsell ad

admin/metabox/class-metabox.php
* We want to refactor how we enqueue assets in order to correctly enqueue them in the iframed block editor.
* Addresses a notice in WordPress 6.7 about assets being added to the iframe incorrectly.
* I moved the logic to enqueue assets for the post overview page out of the big `enqueue` callback and gave it a specific callback + action hook.
* Make sure you're on WordPress 6.7
* in case you're not, use the `WordPress Beta Tester` plugin to switch to it 
* Edit a post
* In your console browse verify
* there are no notices like: `yoast-seo-metabox-css-css was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe.`  
* go …
=> Refactor assets enqueing hooks and callbacks

admin/metabox/class-metabox.php
* We need to enqueue our metabox assets differently for non block editor editors.
* Fixes an unreleased bug where the assets for non block editor editors were no longer enqueued.
* I added a `maybe` callback method since at construct time the system does not know if we are in the block editor yet. The `current_screen` methods are not yet defined.
* Make sure all editor metaboxes still work. So classic, block editor, product editor and Elementor.
* Also test that https://github.com/Yoast/wordpress-seo/pull/21696 is still fixed.
* Install [Tabify Edit Screen](https://wordpress.org/plugins/tabify-edit-screen/)
* Go to `Settings` -> `Tabify edit screen`
* click on `Create new …
=> Make sure assets are also enqueued for non block editor editors.

packages/js/src/dashboard/app.js
* We want to hide top notices on first time configuration tab.
* Removes notices on first time configuration tab.
* I'm removing all the notices on first time configuration tab following the snippet from `packages/js/src/initializers/admin.js` (the old general page script):
```js
if ( id === "first-time-configuration" ) {
// All notices when in the first time configuration tab.
jQuery( ".notice-yoast" ).slideUp();
...
} else {
// Show the notices when not in the first time configuration tab.
jQuery( ".notice-yoast" ).slideDown();
...
}
```
* That included the webinar notice.
* Moved the the notices to the Transition components to have smooth tab change.  
* Reset First …
=> Remove notices on FTC tab

admin/class-admin-asset-manager.php, admin/class-asset.php
* This change is to accommodate our changes in https://github.com/Yoast/wordpress-seo-local/pull/2548. Specifically, we needed a way to register scripts with an `async` strategy, so we had to enhance our asset manager API.
* Allows scripts to register their loading strategy.
*
Regression tests:
* Go to Yoast SEO->Settings both with this PR/RC and trunk/released version, check the source code and confirm that all `<scripts>` have stayed the same and in the same spot (header/footer)
* Confirm that you dont get any new console errors
* Repeat the test for:
* The post edit page, in all editors
* The frontend of the site …
=> Enhance the admin asset API to cover loading strategy as well

packages/js/src/elementor/initializers/editor-integration.js, packages/js/src/elementor/initializers/editor-store.js, packages/js/src/elementor/initializers/editor-watcher.js, packages/js/src/elementor/redux/selectors/analysis.js, packages/js/src/elementor/redux/selectors/snippet-editor.js, packages/js/src/elementor/redux/selectors/wincher-seo-performance.js, packages/js/tests/__mocks__/@wordpress/url.js, packages/js/tests/elementor/redux/selectors/snippet-editor.test.js, packages/js/tests/elementor/redux/selectors/wincher-seo-performance.js, packages/js/tests/helpers/fields/AnalysisFields.test.js, packages/js/tests/test-utils.js, src/integrations/third-party/elementor.php
* Changing the slug is not supported in Elementor itself, we added that in via our Search appearance UI. So we should make sure we don't override previous values.
Introducing fallbacks for the slug in Elementor (based on the selectors in Gutenberg/block editor). The slug should be:
* Edited slug
* Saved slug
* Cleaned title
* Entity/document ID
A draft PR without changes has an empty slug. Meaning that unless you edit one, you will use the title. Unless that consist of only clean characters, then you fall back to the ID.
* Fixes a bug in our Elementor integration where previously saved slug values would be ignored for drafts.
See context.
The fallback is done in the slug selector for the Search appearance component.
This means …
=> Fix slug always based on title for drafts

admin/metabox/class-metabox.php
* We want to enqueue assets because we need some of the css to be loaded into the iframe too.
* Takes care of a browser notice about enqueuing an assets incorrectly in the block editor iframe.
* We switched from using `enqueue_block_editor_assets` to `enqueue_block_assets` because some of the metabox css rules are needed in the iframe, too.
* Open your browser console and switch to the network tab
* Edit a post and verify: 
* the Yoast metabox is correctly styled
* highlight some content via the eye icon in the readability analysis and check that the colour is OK (not the default yellow but light purple shade)
* in the browser console you see `metabox-[VERSION].css` being …
=> Fix metabox assets enqueuing

css/src/general-page.css, package.json, packages/js/src/general/components/alerts-list.js, packages/js/src/general/routes/alert-center.js, packages/js/tests/general/components/__snapshots__/alerts-list.test.js.snap, packages/js/tests/general/components/__snapshots__/notifications.test.js.snap, packages/js/tests/general/components/__snapshots__/problems.test.js.snap, packages/tailwindcss-preset/index.js, packages/tailwindcss-preset/package.json, packages/tailwindcss-preset/readme.md, packages/ui-library/package.json, yarn.lock
*
* Fixes the alert center notifications breaking out of the space.
* [@yoast/tailwindcss-preset 1.0.0 enhancement] Adds support for container queries via peer dependency `@tailwindcss/container-queries`.
* [@yoast/ui-library 0.0.1 non-user-facing] Adds support for container queries via peer dependency `@tailwindcss/container-queries` from `@yoast/tailwindcss-preset` (unreleased version).
* Using container queries to test the container width instead of the screen size
* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries
* https://caniuse.com/?search=container%20query
* https://github.com/tailwindlabs/tailwindcss-container-queries
* Some unsets are used to reset WP styling on the button
* white …
=> New general page: fix alert center notification breaking out of space

admin/views/partial-notifications-errors.php, packages/js/src/general/components/alerts-list.js, packages/js/src/general/components/problems.js
* We want to show `Good job! We could detect no serious SEO problems.` instead of `We have detected the following issues that affect the SEO of your site.` if no issues are detected.
* Fixes copy in the Alert center when no problems are detected.
* N/A
* Go to `Settings` -> `Reading`
* tick the `Discourage search engines from indexing this site` checkbox
* Go to `Yoast SEO` -> `General`, you should see a problem titled `Huge SEO Issue: You're blocking access to robots.`
* Hide the problem and verify the `Problems` widget now shows `Good job! We could detect no serious SEO problems.`
* Go to `Settings` -> `Reading`
* untick the `Discourage search engines from indexing this …
=> Fix copy in the Alert center when no problems are detected

src/actions/semrush/semrush-phrases-action.php, tests/Unit/Actions/SEMrush/SEMrush_Phrases_Action_Test.php
*
* Adds columns to the semrush api request.
* I added a check for `columnNames` in the transient otherwise the transient reflects only the data without the new columns. When we will implement the new UI then the new columns needs to be there otherwise the table would break.
* With Premium enabled edit a post and click on `Get related keyphrases`
* Open devtools network tab.
* Connect to semrush and check you get key phrases in a table as usual.
* You should see a request on the network tab. Check the result contain `columnNames` property with an array with 3 items.
*  Checkout this PR and repeat the steps from above, but this time you should a list 5 …
=> Add columns to the semrush api request

packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation-step.js, packages/js/src/general/routes/first-time-configuration.js
*
* Fixes a bug where the First time configuration would not resize properly on smaller width screens.
* Fixes a bug where the First time configuration would have a double separator for the title and content.
[Make indexation step responsive](https://github.com/Yoast/wordpress-seo/commit/0bf615184d00a655177499d5edf221e2fcf58b4a) 
The hardcoded width is preventing collapsing. But it was already moving the image below it.
So I really don't see a need for the width, instead lets try to take a similar amount of space if available.
But don't prevent it from being smaller.
* Go to the First time configuration
* Play around with the screen size
* Verify it now shrinks properly …
=> FTC: remove fixed width and HR

packages/js/src/first-time-configuration/first-time-configuration-steps.js, packages/js/src/general/app.js, packages/js/src/general/routes/alert-center.js
*
* Fixes a bug where the First-time configuration steps would not show updated values if switching to the Alert center.
* Fixes a bug where the First-time configuration notice wouldn't disappear even if the configuration is completed unless the user reloads the page. 
* I kept the solution simple in this PR and decided to keep the window object aligned with the backend. I created a draft issue in the tech debt board to move the FTC state to the Redux store for future iterations.
* By using the `Yoast Test Helper` reset the First-time configuration progress
* Go to `Yoast SEO` -> `General` and make sure you see the following notice
* Go to the First-time configuration
* …
=> General page: Fix First-time configuration state and notice

inc/class-wpseo-admin-bar-menu.php, packages/js/src/first-time-configuration/first-time-configuration-steps.js, packages/js/src/general/app.js, packages/js/src/general/hooks/index.js, packages/js/src/general/hooks/use-notification-count-sync.js, packages/js/src/general/store/alert-center.js, packages/js/src/general/store/index.js, packages/js/src/shared-admin/helpers/index.js, packages/js/src/shared-admin/helpers/notifications-count.js, packages/js/tests/general/store/alert-center.test.js, packages/js/tests/shared-admin/helpers/__snapshots__/notifications-count.test.js.snap, packages/js/tests/shared-admin/helpers/notifications-count.test.js
* Update our notification count (badges) in the Yoast menu and admin bar
* Created from https://github.com/Yoast/wordpress-seo/pull/21747, after a botched rebase.
* Fixes an unreleased bug where the notification count in the admin menu and bar would not update when interacting with the show/hide functionality on the general page.
* Fixes an unreleased bug where completing the SEO data optimization from within the First time configuration would not result in automatically dismissing the respective notification in the general page.
* I was doubting where to place the side-effect for the updates. The action is the correct place in time. But the store reducer/control seems like a bad place to add side-effects. So at first I added it …
=> 21724 new general page updating counters properly new

packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings/cultureAssessmentStrings.js
* The way the feedback string for 'tribe' was created was not readable. 
* Improves the handling of the feedback string for the potentially non-inclusive phrase 'tribe'.
* [shopify-seo] Improves the handling of the feedback string for the potentially non-inclusive phrase 'tribe'.
*
* Create a post and add the phrase `tribe` to it.
* Confirm that the inclusive language analysis shows the following feedback:
* Be careful when using tribe as it is potentially harmful. Consider using an alternative, such as group, cohort, crew, league, guild, team, union instead, unless you are referring to a culture that uses this term. [Learn …
=> Improve handling of the inclusive language feedback string for 'tribe'

admin/views/partial-notifications-errors.php
*
* Fixes an unreleased bug where a PHP notice (warning in PHP 8+) would be thrown when an error was dismissed in the new general page's alert center
*
* Go to the new general page, but make sure you have at least one error there
* To do so, mark the site as discouraged to be indexed by search engines in the site's settings
* Confirm that you get an error in the alert center
* Go and hide/dismiss the error
* Confirm that you dont get a PHP notice (or warning) like: `PHP Notice:  Undefined variable: yoast_seo_i18n_muted_issues_title` in the debug.log
* Without this PR/RC, you would get one
* Now create another error on top of the one you already have
* To do so, activate …
=> Fix PHP warning when errors where dismissed in the alert center

packages/js/src/shared-admin/components/unsaved-changes-modal.js, packages/js/tests/shared-admin/components/unsaved-changes-modal.test.js
*
* Fixes a bug where a React prop type warning would occur in the First time configuration, due to the interface of the useBlocker hook.
[Add default to onDiscard in UnsavedChangesModal](https://github.com/Yoast/wordpress-seo/commit/2e552e7cb4a22e4775a6ca77dd5f83dd537001c5) 
While not necessarily useful without, it is easier to work with like this.
Mostly because the useBlocker from react-router-dom has undefined for the reset and proceed functions unless actively blocking.
We could rewrite the usage there to force not rendering this depending on the state. But that is what the isOpen is supposed to be for already.
* Enable debug output (`SCRIPT_DEBUG`)
* Visit Yoast > …
=> Add default to onDiscard in UnsavedChangesModal

css/src/adminbar.css, inc/class-wpseo-admin-bar-menu.php, packages/js/src/shared-admin/helpers/notifications-count.js, packages/js/tests/shared-admin/helpers/__snapshots__/notifications-count.test.js.snap, packages/js/tests/shared-admin/helpers/notifications-count.test.js
* https://github.com/Yoast/wordpress-seo/pull/21781 brought a regression of showing a bubble with zero notifications on non-Yoast pages:
* We need to hide that there, as we already do in Yoast pages.
* Fixes an unreleased bug, where a bubble with zero notifications would be shown outside Yoast pages.
*
* Make sure that you have no errors/notifications in the General page
* Confirm that you see no notification bubble in the admin bar:
* Go to a non-Yoast page, eg. the plugins page
* Confirm again that you see no notification bubble in the admin bar.
* Go to a Yoast page, eg. the Yoast settings page
* Confirm again that you see no notification bubble in the admin bar
* …
=> Stop showing zero notification bubble outside yoast pages

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigSpec.js, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/createRuleDescriptionsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/createRuleDescriptions.js
* Previously, we retrieved the inclusive language assessment rule descriptions by using a regex to extract them from the functions used to apply the rule. This method was unreliable and didn't work for all rules. Instead, in this PR, a new property is added to each inclusive language assessment with a rule that contains the rule description.
* Adds a rule description property to each inclusive language assessment that has a rule.
* [shopify-seo] Adds a rule description property to each inclusive language assessment that has a rule.
* I chose to duplicate the list of precedence/following exceptions that are passed to the functions that apply the rules, and to the function that generates the rule description. Rather than extracting …
=> Change how we retrieve rule descriptions when generating the inclusive language database

src/integrations/blocks/abstract-dynamic-block-v3.php, src/presenters/breadcrumbs-presenter.php, src/presenters/url-list-presenter.php, tests/Unit/Presenters/Breadcrumbs_Presenter_Test.php
* We want to make sure that our links work in the new Iframe editor.
* improves the compatibility with WordPress 6.7 Iframe editor.
*
* Install Yoast SEO and WP beta
* Activate WP 6.7-betaX
* Create a post and Breadcrumbs block there
* Click on Home in breadcrumbs
* Make sure you open your link in a new tab.
* Save the page en make sure the target blank is not active on the front-end.
*
*
Fixes #
=> Add target blank to server rendering of blocks.

packages/yoastseo/src/languageProcessing/languages/en/config/transitionWords.js, packages/yoastseo/src/languageProcessing/languages/pt/config/transitionWords.js
* This PR expands on the PR [Add new transition words in Portuguese #21712](https://github.com/Yoast/wordpress-seo/pull/21712) submitted as a community patch by @BrunoAseff. 
* Improves the _transition words_ assessment for Portuguese and English by updating the relevant lists of transitions words. Props to [BrunoAseff](https://github.com/BrunoAseff).
* [shopify-seo] Improves the _transition words_ assessment for Turkish and English by updating the relevant lists of transitions words.
* [yoastseo] Expands and updates the transition words lists for Turkish and English. Props to [BrunoAseff](https://github.com/BrunoAseff).
* The community patch PR added "commonly used Portuguese transition words", along with an updated spelling …
=> 21712 add more portuguese transition words

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
* When we replace the SEMrushKeyphraseTable component we lost the link that was included in that component, this PR restores it. 
* Fixes unreleased bug where the "Get more insights..." link was missing from the related keyphrase suggestions modal. 
*
* Edit a post with focus key phrase.
* Click on the "Get related keyphrases" button.
* Log in to Semrush and return to the post, check you are getting a modal with a table of keyphrase suggestions and below a link "Get more insights at Semrush" check the link is "https://www.semrush.com/analytics/keywordoverview/" and contain 2 params q={the focus keuphrase} & db={the country code} …
=> restore the add more insights link

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js, packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
* Show the loading table only when the request status is loading.
* [@yoast/related-keyphrase-suggestions 0.1.0] Adds isLoading prop to related keyphrase table.
* Hides "Get more insights..." link when there are no results.
*
*  Edit a post with focus leyphrase.
* Click on "Get related keyphrases"
* Check you see the loading table before the results appear in the table.
* Change the focus keyphrase and repeat the request until you you see the semrush upsell button.
* Make sure the table is not there and so is the link for getting more insights. 
* …
=> 21811 hide semrush loading table when user needs to upgrade

admin/tracking/class-tracking.php, inc/options/class-wpseo-option-wpseo.php
* Fix wrong phpdoc type https://github.com/Yoast/wordpress-seo/issues/21695
* Fixes documentation for `wpseo_enable_tracking` filter. Props to @kkmuffme.
*
* non-code change
*
* none
Fixes #21695
=> Fix wrong type in docs

packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js, packages/js/src/components/contentAnalysis/SeoAnalysis.js, packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
* Prepare AI Optimize for the readability assessments.
* Prepares AI Optimize for the readability assessments.
* function **renderAIFixesButton** is refactored: new variables are introduced for code readability and copied in the ReadabilityAnalysis component and connected to props and pass to Results component. The function is really simple so it was not extracted into a base component because introducing the base component leads to complexity later when we decide  to move from class components to function components.
* Install free plugin
* Add the following line in the function **getResult** of class **PassiveVoiceAssessment**
`assessmentResult.setHasAIFixes( true );`
* …
=> 474 prepare ai optimize for readability assessments

packages/js/src/dashboard/hooks/use-fetch.js, packages/js/src/dashboard/index.js, packages/js/src/dashboard/scores/components/content-status-description.js, packages/js/src/dashboard/scores/components/score-content.js, packages/js/src/dashboard/scores/components/score-list.js, packages/js/src/dashboard/scores/readability/readability-scores.js, packages/js/src/dashboard/scores/score-meta.js, packages/js/src/dashboard/scores/seo/seo-scores.js
* Reflect the description based on the widget and which score has the highest amount
* Shows description based on which score has the highest amount, in both the SEO and Readability widget of the dashboard.
[Implement descriptions](https://github.com/Yoast/wordpress-seo/commit/933ff1048143c9e8515370f631a99c12ec022bb4) 
Descriptions are based on the analysis type and the score "type"
* I made them hardcoded with lookup on Widget level for SEO/Readability and score in the description. This seemed the most flexible without introducing context or a store or a complicated nested switch if/else. If you have better ideas, please let me know 😄 
[Change the initial isPending to true](https://github.com/Yoast/wordpress-seo/commit/231c22862f …
=> Dashboard: implement descriptions scores 

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js, packages/js/src/redux/reducers/preferences.js, packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js, packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/stories.js
*
* [@yoast/related-keyphrase-suggestions 0.1.0] Changes the format of the search volume in the related keyphrase suggestions table.
* Changes the format of the search volume in the related keyphrase suggestions table.
* 
* Edit a post with. focus key phrase.
* Click on `Get related keyphrases`
* Login to semrush and check you get the table.
* Check the volume has the short format:
* Go to user profile and change the language to Arabic or Hindi and check the Search volume in the table has short format for the specific language.
*
*
Fixes …
=> Change search volume format

packages/js/src/dashboard/scores/components/term-filter.js, packages/js/src/dashboard/scores/seo/seo-scores.js
*
* Clears the selected term when a content type is selected.
* Added a `useEffect` in the outer layer instead of in the TermFilter because the TermFilter does not always get rendered and thus might not get the `useEffect` trigger? 🤷 
* Go to the dashboard
* Select a term
* Select a different content type (that also has a connected taxonomy, like product)
* Search for a term
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/338
=> Dashboard: clear category in case another post type was selected

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js, packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/docs/component.md, packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/docs/index.js, packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/index.js, packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/stories.js, packages/related-keyphrase-suggestions/src/index.js
*
* Implements new design for the Premium upsell ad on the related keyphrase suggestions modal. 
* [@yoast/related-keyphrase-suggestions 0.1.0] Adds the premium upsell ad with new design for the related keyphrase suggestions modal.
*
* Edit a post with focus keyphrase.
* Make sure Yoast premium in disabled or uninstalled.
* Click on "Get related keyphrases".
* Log in to semrush and return to the post to see you are getting the modal with related keyphrase suggestions.
* Check that you see the upsell ad on the top of the modal:
* Enable screen reader and focus on the button, check it says "Opens in a new browser tab"
* Click on the button and check the link opens in a new …
=> add premium upsell component

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js, packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js, packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/stories.js
* The direction of "Add keyphrase" header title should we the opposite of the text direction. 
* The width should be fixed since the success message/remove button are of different width and we don't want that to affect the table/column width when switching the buttons.
* We want to fix the storybook for loading table and prevent rendering data when table is loading.  
* [@yoast/related-keyphrase-suggestions 0.1.0] Fixes "Add keyphrase" title direction and width.
* 
* Activate Yoast Premium
* Edit a post with focus keyphrase
* Click on "Get related keyphrases"
* After logging into Semrush check the table header for get related keyphrase is in one line and when removing or …
=> fix add keyphrase direction and width and loading table storybook

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js, packages/js/src/containers/SEMrushRelatedKeyphrases.js, packages/js/tests/components/SEMrushRelatedKeyphrasesModalContent.test.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/components/MaxRelatedKeyphrases.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestEmpty.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestFailed.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestLimitReached.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/components/index.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/docs/component.md, packages/related-keyphrase-suggestions/src/elements/UserMessage/docs/index.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/index.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/stories.js, packages/related-keyphrase-suggestions/src/index.js
*
* Implements new design for the warnings and errors in the related keyphrases suggestions modal.
* [@yoast/related-keyphrase-suggestions 0.1.0] Changes the design of the warnings and errors alerts in the related keyphrase suggestions.
* The pending notice is dropped since we have the loading table.
* `relatedKeyphrases` is a prop coming from Premium, checking for `relatedKeyphrases` includes checking for premium.
* Check alerts for:
* When there are more than 4 related keyphrases selected.
* When the request failed
* When there are no suggestions in the result
* When the reaching the max requests for semrush:
* The country selector should be hidden.
* The button should …
=> 324 tailwindify the errors and notices in the related keyphrase suggestions modal

packages/js/src/dashboard/scores/components/score-chart.js, packages/js/src/dashboard/scores/components/score-content.js, packages/js/src/dashboard/scores/components/score-list.js, packages/js/src/general/app.js
*
* Addresses some feedback from UX.
All based on `Design finetune meeting` in the [document](https://docs.google.com/document/d/1aiDniY0PPvCnqemWFvQkefGJrw9zgvqcORyumDbxRwI/edit?tab=t.0#heading=h.iorg0wqrs653)
* Go to the Dashboard
* Focus on the chart
* Hover your mouse over the chart and..
* Play around with the width of the screen and..
* Make the screen width 320 pixels wide
* Resize back to normal
*
* The dashboard
Fixes #
=> Dashboard: UX feedback

src/dashboard/infrastructure/scores/readability-scores/readability-scores-collector.php, src/dashboard/infrastructure/scores/seo-scores/seo-scores-collector.php, src/dashboard/infrastructure/taxonomies/taxonomies-collector.php
*
* Adds micro caching around the score queries
* A small change in the visibility of the unrelated `wpseo_{$content_type}_filtering_taxonomy` query is included.
* In `src\dashboard\infrastructure\scores\seo-scores\seo-scores-collector.php` and in `src\dashboard\infrastructure\scores\readability-scores\readability-scores-collector.php` there are two lines that read as `$current_scores = $wpdb->get_row(` in each file. Add a `error_log('QUERY STARTED');` line right before them.
* Within the span of 1 minute, perform GET requests to:
* `/wp-json/yoast/v1/seo_scores?contentType=post`
* `/wp-json/yoast/v1/seo_scores?contentType=post&taxonomy=category&term=<TERM_ID>` where …
=> Add micro caching around the score queries

admin/views/tool-import-export.php
No action is taken on Import from other SEO plugins tool when using translated plugin.
* Fixes Import from other SEO plugins tool actions when the buttons are translated to the installation language. Props to @edpittol.
*
* Install RankMath or other SEO plugin and change some settings.
* Change site language to a different language other than English ( or change language in user profile ).
* Deactivate that SEO plugin and install Yoast SEO
* Go to Yoast SEO and go to Yoast SEO->Tools->Import/export
* Select to import data from another SEO plugin, select the SEO plugin you deactivate.
* Click on "Import" (in a different language)
* Check you get success message that the …
=> Fix l10n import/export tool buttons actions

admin/class-admin-asset-manager.php, css/src/block-editor.css, css/src/metabox.css, src/integrations/blocks/block-editor-integration.php, tests/Unit/Integrations/Blocks/Block_Editor_Integration_Test.php
*
* Enqueues block editor iframe related styles.
*
* Edit a post and verify: 
* Click on readability analysis ( have content that will trigger the eye icon) and  highlight some content via the eye icon in the readability analysis and check that the colour is OK (not the default yellow but light purple shade)
* in the browser console you see `metabox-[VERSION].css` being fetched once
* you don't get a notice in the browser's console stating: `yoast-seo-metabox-css-css was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe.` 
* …
=> 1935 wp 67 238 undefined console error for iframe

packages/js/src/dashboard/scores/components/scores.js, packages/js/src/dashboard/scores/components/term-filter.js
*
* Fixes an unreleased bug where the dashboard widgets wouldnt work when permalinks where set to plain.
*
* Confirm that the dashboard widgets work both for seo scores and readability scores
* Confirm that filtering the scores by taxonomy works as expected
* Go to `Settings->Permalink`, set `Plain` as your site's permalinks and repeat the test above
*
Fixes https://github.com/Yoast/roadmap/issues/535
=> Make score endpoints work in plain permalinks

src/dashboard/application/score-results/abstract-score-results-repository.php, src/dashboard/domain/score-results/score-results-not-found-exception.php, src/dashboard/infrastructure/score-results/readability-score-results/readability-score-results-collector.php, src/dashboard/infrastructure/score-results/seo-score-results/seo-score-results-collector.php, src/dashboard/user-interface/scores/abstract-scores-route.php
*
* Enhances API endpoints by returning a 500 error code when queries fail.
*
* Add the following filter, to make the SEO score query fail:
```
add_filter( 'query', 'fail_seo_score_query' );
function fail_seo_score_query( $query ) {
if ( strpos( $query, "SELECT COUNT(CASE WHEN I.primary_focus_keyword_score >= 0 AND I.primary_focus_keyword_score <= 40 THEN 1 END)" ) !== false ) {
return false;
}
return $query;
}
```
* Do a GET request to `/wp-json/yoast/v1/seo_scores?contentType=post&taxonomy=category&term=1`
* Confirm that you get a 500 error code and a `Score results not found` error message
* Within a minute from the GET request, remove the filter and retry
* Confirm …
=> Return 500 error code when query fails

packages/yoastseo/GLOSSARY.md, packages/yoastseo/OVERVIEW.md
As discussed in [internal Slack](https://yoast.slack.com/archives/C03PRESAXMJ/p1732877907666479), it would be useful to have an overview for engineers who want to interact with the code. Given that a lot of the terminology comes from the linguistic domain, an engineer new to the domain has a hard time following the code itself.
This PR adds an initial draft for such a document.
* [yoastseo] Adds an overview and glossary for the terminology used throughout the package.
* This was entirely AI-generated for now and needs review by domain specialists
No testing needed as this is just documentation.
=> Add draft yoastseo package overview

packages/js/src/dashboard/scores/components/score-content.js, packages/js/src/dashboard/scores/components/score-list.js, packages/js/src/dashboard/scores/components/scores.js, packages/js/src/dashboard/scores/score-meta.js, packages/ui-library/.storybook/style.css, packages/ui-library/src/components/tooltip-container/docs/component.md, packages/ui-library/src/components/tooltip-container/docs/index.js, packages/ui-library/src/components/tooltip-container/docs/with-flex.md, packages/ui-library/src/components/tooltip-container/index.js, packages/ui-library/src/components/tooltip-container/stories.js, packages/ui-library/src/components/tooltip-container/style.css, packages/ui-library/src/elements/tooltip/style.css, packages/ui-library/src/hooks/index.js, packages/ui-library/src/hooks/readme.md, packages/ui-library/src/hooks/use-keydown.js, packages/ui-library/src/index.js
* Wanting a tooltip as per design.
* a11y concerns regarding a tooltip: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role
* Adds a tooltip with information to the not analyzed scores.
* [@yoast/ui-library 0.1.0 enhancement] Adds a TooltipContainer component that handles a11y functionality around the Tooltip element.
* [@yoast/ui-library 0.1.0 enhancement] Adds a `useKeydown` hook to handle the `keydown` event listener subscription.
* [@yoast/ui-library 0.0.1 bugfix] Fixes a bug where the Tooltip would be positioned wrong when using a RTL language.
* Moved the list item to its own component to be able to track the visible per item.
* Confirmed by UX: hovering over the bullet + label + badge will …
=> Dashboard: add tooltip to not analyzed

admin/capabilities/class-register-capabilities.php
Ran into a TypeError that blocks loading of the WordPress admin. Guessing it was introduced by a PHP API change (presently at 8.1.31). Simple enough fix to incorporate.
$user->roles may be undefined, so passing it into in_array() produces a TypeError. Found this to completely block loading of the WP admin. Simple fix of adding a fallback value.
* Fixes a bug where TypeError would occur when checking for capabilities of SEO Manager user role when the roles is not an array. Props to @kfeinUI.
* Issue was produced on WordPress 6.7.1 running PHP 8.1.31.
* In the `wp_config.php` add the following lines (or adjust your config):
```php
define( 'WP_DEBUG', true );
define( …
```
=> class-register-capabilities.php in_array() TypeError fix

packages/js/src/dashboard/components/page-title.js, packages/js/src/dashboard/scores/components/scores.js
*
* Increases the shadow of the header and widgets on the Dashboard page.
* Even though this is technically user-facing. I filed it under non-user-facing due to the scope.
* I did not create a "DashboardPaper" or add a variant to the Paper in the UI library because I have no clue what the future holds
* Check out the Dashboard
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/343
=> Dashboard: increase Paper shadow

packages/js/tests/dashboard/components/page-title.test.js, packages/js/tests/dashboard/fetch/fetch-json.test.js, packages/js/tests/dashboard/fetch/get-response-error.test.js, packages/js/tests/dashboard/fetch/timeout-error.test.js, packages/js/tests/dashboard/fetch/use-fetch.test.js, packages/js/tests/dashboard/scores/components/__data__/categories.json, packages/js/tests/dashboard/scores/components/__data__/content-types.json, packages/js/tests/dashboard/scores/components/__data__/product_cat.json, packages/js/tests/dashboard/scores/components/__data__/scores.json, packages/js/tests/dashboard/scores/components/scores.test.js, packages/js/tests/dashboard/scores/score-meta.test.js
*
* Adds tests for the Dashboard frontend.
* I didn't write tests for `src/dashboard/components/dashboard.js`, the main component that renders the "widgets". This is because:
* it will change when more widgets are added
* the subcomponents are tested already
* Reversed situation for scores, where I did not test individual components, but just Scores.
* Due to not wanting to spend time testing the chart library I opted to just mock that out. Hence the lack of coverage for `score-chart.js` -- We would need to render it properly and test the tooltip on hover.
* Check the code to see if it makes sense
* Run the tests in the `dashboard` folder with coverage: `yarn workspace …
=> Dashboard: add tests for JS side

src/dashboard/infrastructure/content-types/content-types-collector.php
*
* Fixes an unreleased bug where we would show post types with false `show_ui` in the dashboard feature, which would result into linking to non existing admin pages.
* Instead of deciding whether we should fix the source of truth (aka, whether post types with false `show_ui` should be indexable-d), we do the quick fix here and [an investigation task](https://github.com/Yoast/reserved-tasks/issues/359) was created for taking care of this properly in the future.
* Create a post type with false `show_ui` but true `public`:
```
function register_blog_post_type() {
$args = [
'label'              => \__( 'Blog posts', 'yoast-test-helper' ),
'labels'             => [
'name' …
```
=> Exclude post types that have false show_ui from the dashboard feature

src/dashboard/application/score-results/abstract-score-results-repository.php, src/dashboard/application/score-results/current-scores-repository.php, src/dashboard/domain/score-results/current-score.php, src/dashboard/domain/score-results/current-scores-list.php, src/dashboard/infrastructure/score-results/readability-score-results/readability-score-results-collector.php, src/dashboard/infrastructure/score-results/score-results-collector-interface.php, src/dashboard/infrastructure/score-results/seo-score-results/seo-score-results-collector.php, src/dashboard/user-interface/scores/abstract-scores-route.php
*
* Adds troubleshooting mode in score endpoints
* If we're on troubleshooting mode, we bypass cache.
* With POSTMAN, do the usual GET requests for seo and readability scores (see [the original PR](https://github.com/Yoast/wordpress-seo/pull/21847))
* But this time add a `&troubleshooting=1` parameter
* You should now get the same responses like before, but with an added `ids` attribute in each `good`/`ok/`bad`/notAnalyzed` score, which should represent a comma-separated list of post IDs.
* Confirm that those IDs are:
* the same amount that the respective `amount` of the score
* for the posts that exist in the respective `view` links
* Try for both seo and readability …
=> Add troubleshooting mode in score endpoints

tests/WP/Dashboard/Application/Filter_Pairs/Filter_Pairs_Repository_Test.php
* We want to add integration tests for the Filter_Pairs_Repository
* Adds an integration test to make sure the filter pairs repository returns the needed data.
*
*
*
*
Fixes #
=> Creates integration test for the Filter_Pairs_Repository.

packages/related-keyphrase-suggestions/package.json, packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js, packages/related-keyphrase-suggestions/src/components/Modal/index.js, packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/index.js, packages/related-keyphrase-suggestions/src/elements/IntentBadge/style.css, packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/index.js, packages/related-keyphrase-suggestions/src/elements/TableButton/index.js, packages/related-keyphrase-suggestions/src/elements/TableButton/style.css, packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestLimitReached.js
*
* [@yoast/related-keyphrase-suggestions 0.1.0] Fixes a bug where styles on buttons, intent badge and modal links would not adjust to direction when on  rtl view.
*
* Activate yoast premium.
* Change language to one of the rtl languages (Hebrew/Arabic)
* Edit a post with focus keyphrase
* Click on "Get related keyphrases" and log into your semrush account.
* Check you see the modal with a table
* Check the followings:
* Check the links in the footer of the modal has icons in the right direction.
* Check the buttons and their icons has the right space.
* Hover over intent badges and check the tooltip are directly above the badge.
* The semrush upsell button arrow is in …
=> Related key phrase suggestions fix styles for RTL

config/scripts/install-wp-tests.sh
* Update test tooling
* Update test tooling
The upstream `install-wp-tests.sh` script has been updated. This commit incorporates the upstream changes in the local copy used in this repo.
Refs:
* wp-cli/scaffold-command#345
* _N/A_ If the build runs & passes, we're good.
=> WP Tests: update install WP script

composer.json, composer.lock
* Update dependencies
* Update dependencies
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
Ref: https://github.com/composer/installers/releases/tag/v2.3.0
Selectively update test dependencies to get us onto versions compatible with PHP 8.4.
Refs:
* https://github.com/antecedent/patchwork/releases/tag/2.2.0
* https://github.com/antecedent/patchwork/releases/tag/2.2.1
* https://github.com/Brain-WP/BrainMonkey/releases/tag/2.6.2
* …
=> Composer: update various dependencies

tests/WP/bootstrap.php
* Improve test setup
* Improve test setup
When running the tests, three notices along the lines of the below are shown at the top of the test run:
```
PHP Notice:  Function WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.) in /tmp/wordpress/wp-includes/functions.php on line 6114
```
The reason these notices show is that the `blocks/*/*/block.json` files for the Yoast custom blocks do not exist in a plain PHP based test …
=> Tests: fix block type notices

packages/js/src/dashboard/scores/components/score-list.js
*
* Fixes a bug where the View button label in the new dashboard would not be available for translation.
*
* Go to Yoast SEO -> General 
* Check there is no change the View button label and no console error.
*
*
Fixes #
=> Add translation to View label on dashboard

packages/js/src/components/modals/InternalLinkingSuggestionsUpsell.js, packages/js/src/components/modals/KeywordSynonyms.js, packages/js/src/components/modals/MultipleKeywords.js, packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js, packages/js/tests/settings/__snapshots__/search.test.js.snap
* Also fixes snapshot test from [Settings: fix search menu contrast](https://github.com/Yoast/wordpress-seo/pull/21929)
* Adjusts untranslated strings for the Yoast Premium ads modals on the editors.
*
* Regression tests:
* Edit a post without yoast premium and check the ads for premiums contain the string "also gives you"
*  For internal linking suggestions
* Synonyms
* Premium analysis
* Multiple keyphrases
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21922
=> fix translations for ads

packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js, packages/js/src/components/contentAnalysis/SeoAnalysis.js, packages/js/src/redux/reducers/preferences.js, packages/js/src/redux/selectors/preferences.js
*
* Refactor check for if AI Feature is enabled.
* Moved the check from free to premium since it's a premium feature.
* Kept the original check as fallback.
* Without Premium edit a post and check you have a Tab called "SEO analysis" that contain the analysis and a tab for "Premium SEO analysis" which is used as an upsell button.
* Enable Yoast Premium and check the tab label of "Premium SEO analysis" now contains the analysis and the "SEO analysis" is no longer there.
* Enable the AI feature and edit a post, check you can see the Fix assessments AI button when editing.
* Go to Yoast SEO -> Settings -> Site features and disable the AI feature.
* Edit a post and check you …
=> add fallback to isAiFeatureEnabled

packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
*
* Adjusts the design for the related keyphrase suggestions table header  for "Add keyphrase" column.
* [@yoast/related-keyphrase-suggestions 0.1.0] Split the translation for the "Add keyphrase" header cell into 2 lines and align it to the end of the cell.
*
* Edit a post with focus keyphrase when you are logged in to your Semrush account.
* Check the table header for "Add keyphrase" is broken to two lines and aligned to the end of the cell. 
* Make sure that doesn't change when the table is loading.
* Enable Yoast premium and add an remove keyphrases in the table, check that doesn't affect the table or cell width. 
* Check the same for RTL language.
* Check the same in …
=> Related kephrase suggestion table: break translation for "Add keyphrase" and align to end

packages/js/src/redux/reducers/editorContext.js, packages/js/src/redux/selectors/editorContext.js
*
* Fixes a bug where users without Yoast SEO Woo are not greeted with the AI upsell when trying to use the AI feature and are actually able to access the feature, if on a non-english site.
* Fixes a bug where woo SEO upsell would not render when on a locale that translate the product post label.
* Fixes a bug where the Schema type of the product would not be locked when Yoast SEO Woo is enabled.
*
Without Woo SEO and without Premium
* Change locale that changes the product label and edit a product.  
* Check upsell ads for Woo SEO on search appearance and schema tabs - without this PR, the upsells would not appear
* Click on `Use AI` in the search appearance.
* Check you …
=> Check for product by slug

.github/workflows/lint.yml, .github/workflows/test.yml
* Improve CI
* Improve CI
The second time PHP was installed would in a workflow run, wouldn't always install the _latest_ version. Fixed now.
Ref: https://github.com/shivammathur/setup-php/issues/895
* Verify in the workflow output that the second time PHP is installed, the current version of PHP is used, not the Debian default of PHP 8.3.6.
=> GH Actions: ensure second PHP install run always uses latest PHP version

packages/js/src/components/WincherPerformanceReport.js, src/integrations/admin/link-count-columns-integration.php
*
* Removes outdated translation.
*
* Got to posts overview page, and hover over the icons for internal and external links in the table.
* Check you don't see the text "See "Yoast Columns" text in the help tab for more info."
* Check you see the text 'Number of outgoing internal links in this post.' for out going icon and 'Number of internal links linking to this post.' for internal links.
* Enable Wincher integration on the Yoast integration page. Do not connect to Wincher.
* Go to the site dashboard and check the Wincher card. In the text before the table, there should be a link for the word Wincher:
* Click on the link and make sure it redirects to Wincher.
QA can test …
=> 395 outdated translations

packages/js/src/inline-links/inline.js
* Fixes a bug from https://github.com/Yoast/wordpress-seo/pull/20270
* Fixes a bug where editing a link in the block editor would have unexpected consequences when using undo.
The cache via useCallback is too greedy.
Everything is re-created already (no useCallback around all other functions). Therefore, opting to remove the cache (useCallback) here for an easy fix.
* Add the native gutenberg table block: 2×2 table ( the default size )
* Add some text
* Change the text in the 2nd column to be a link
In order for focus reasons:
* Change the link in the 2nd column
* Remove the text in the 1st column
* With the keyboard click on CTRL + Z or …
=> Remove cache around changing link

src/generators/schema/article.php, src/generators/schema/webpage.php, src/presentations/indexable-post-type-presentation.php, tests/Unit/Generators/Schema_Generator_Test.php
*
* Fixes a bug where the `article:modified_time` meta tag would show an earlier time than the `article:published_time` meta tag for scheduled posts.
*
* Go to add a post but instead of publishing it, schedule it in the near future
* Let's say you created it at 10:00am and scheduled it to be live at 10:05am
* Once 10:05am passes, go to check the post's page source (you may need to refresh your site a couple of times, so that the scheduled post gets actually published)
**Without this PR**:
* The `article:modified_time` meta tag would appear and it would be an earlier time than the `article:published_time` meta tag, which is wrong
* In the schema, the `dateModified` …
=> Only show a modified time tag if it's later than the created time

packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js, packages/yoastseo/src/worker/AnalysisWebWorker.js
* Previously, after applying the AI suggestion for sentence length assessments to the editor, if the feedback still has a highlighting button and an AI Optimize button, both buttons don't work. Clicking on the highlighting button fails to highlight the relevant text in the editor. Additionally, the AI Optimize button is disabled as we could not detect blocks that contain long sentences.
* The issue was apparently we failed to retrieve the relevant blocks that contain long sentences because we have an outdated readability analysis result. In the worker, we don't update the readability analysis result when there is a change in the list of Gutenberg blocks (including their client IDs that change after the action of applying AI suggestion). As a result, attempting to retrieve relevant blocks …
=> Updates the readability analysis when the client IDs of the blocks change

apps/content-analysis-api/routes/research.js, packages/yoastseo/src/parse/language/LanguageProcessor.js, packages/yoastseo/src/parse/language/index.js
* After merging #21866 we need to update our content analysis API to allow running the sentence length and paragraph length assessment with a parsed tree. This PR takes care of that and can be seen as a follow-up to #21927.
* [yoastseo] Exports the `LanguageProcessor`.
* [apps/content-analyis-api] Fixes a bug where the sentence and paragraph length researches could not be run.
*
Only for developers:
* In PHPStorm, open `analyze.http` in `apps/content-analysis-api`. 
* Run all test cases and confirm they pass.
*
* No QA needed, changes are …
=> Fixes running researches that require a tree in the experimental content analysis API

packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js, packages/js/src/components/fills/MetaboxFill.js, packages/js/src/components/fills/SidebarFill.js, packages/js/src/components/fills/hooks/useToggleMarkerStatus.js
* Previously, there were several issues with the highlighting button where it was not correctly enabled or disabled:
1. Switching from visual to code editor in Block editor doesn't disable the highlighting button when there is no AI button rendered inside any analysis result tab.
2. When the AI button is rendered inside an analysis result tab, SEO analysis, for instance, closing the tab will disable the highlighting buttons in the Readability and Inclusive language analysis tab if they are present.
3. When the text AI button is rendered inside one of the analysis result tabs (SEO/Readability/Inclusive language analysis), modifying the post that could result in the change of the analysis result score, will disable any existing highlighting score. For example, as described in this issue: …
=> Correctly enable or disable the highlighting button

inc/class-wpseo-replace-vars.php
* Removed second condition with `single_month_title( ' ', false )` in `WPSEO_Replace_Vars::retrieve_date()` as this did not provide any difference.
* This solves #21975
* Simplifies calculating the `date` replacement variable before displaying it in the frontend. Props to @apermo.
*
Check the impact on the date replacement variable
* Go to Yoast SEO->Settings->Date archives and confirm that the SEO title has the `date` replacement variable
* Visit the `example.com/2024` and `example.com/2024/12` date archives (make sure you have at least one post published on December 2024)
* Compare the SEO title of both between this RC and the production version and confirm it's the …
=> refactor: remove duplicate/redundant condition

packages/yoastseo/package.json, packages/yoastseo/tsconfig.json
* We don't want to miss any files when preparing the types.
* We also want to explicitly allow imports with asterisks.
* [yoastseo] Allows transpiling all JavaScript files inside `src` and `vendor` into TypeScript and allows importing modules with an asterisk `*`.
* Adding the `moduleResolution` option in the config allows using import statement with an asterisk `*`. For example, `import * as assessments from "./scoring/assessments";`. Reference: [moduleResolution](https://www.typescriptlang.org/tsconfig/#moduleResolution)
*  Changing `"src/**.js"` to `"src/**/*.js"` in `include` allows the transpiling of all Javascript files inside the `src` folder. Previously, not all JS files were transpiled. By using `**/` now we should be …
=> Allow transpiling all js files inside yoastseo/src and allow import with asterisk *

packages/components/src/image-select/ImageSelect.js, packages/js/src/components/social/FacebookWrapper.js, packages/js/src/components/social/SocialForm.js, packages/js/src/components/social/TwitterWrapper.js, packages/js/src/components/social/useFallbackWarning.js, packages/social-metadata-forms/src/SocialMetadataPreviewForm.js, packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
* AVIF file are currently not supported by Facebook and X: we want to warn users when their fallback image is in that format.
* Issues a warning message when the image automatically selected for a post social preview is in the unsupported AVIF format.
* [@yoast/components 0.0.1] Refactors the logic used by `ImageSelect` to determine which styling to apply.
* [@yoast/social-metadata-forms 0.0.1 other] Adds `usingFallback` prop to `SocialMetadataPreviewForm` component.
* [@yoast/social-metadata-previews 0.0.1 other] Passes `imageFallbackUrl` prop to `SocialPreviewEditor` component.
* I implemented this check in the warppers (`FacebookWrapper` and `TwitterWrapper`) because it wouldn't make sense to have it in the more general …
=> Show alert when avif file is used in social preview

packages/yoastseo/spec/languageProcessing/helpers/sentence/sentencesLengthSpec.js, packages/yoastseo/spec/languageProcessing/helpers/word/getAllWordsFromTreeSpec.js, packages/yoastseo/src/languageProcessing/helpers/word/getAllWordsFromTree.js
* We want to fix a bug where using hyphens at the start or end of a sentence would cripple the content analysis.
* Fixes a bug where using hyphens at the start or end of a sentence would cripple the content analysis when editing a post.
* None.
* Create a new post. 
* Use the steps from #21994. 
* Confirm the bug is no longer reproducible, and the analysis works properly.
* Also confirm that adding multiple hyphens at the start or the end of a paragraph does not resurface the bug.
* Confirm this in multiple editors.
*
* This change primarily …
=> Fixes processing of hyphens at start and end positions

src/dashboard/application/score-groups/seo-score-groups/seo-score-groups-repository.php, src/dashboard/application/search-rankings/top-page-repository.php, src/dashboard/domain/data-provider/data-container.php, src/dashboard/domain/search-console/failed-request-exception.php, src/dashboard/domain/search-rankings/search-data.php, src/dashboard/domain/search-rankings/top-page-data.php, src/dashboard/domain/top-pages/top-page-data.php, src/dashboard/infrastructure/indexables/top-page-indexable-collector.php, src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php, src/dashboard/user-interface/search-rankings/abstract-ranking-route.php
*
* Adds SEO scores in the top 5 pages endpoint
*
* Prepare your local environment by following the `Using the feature in Local site with data from Production site` section in [the relevant doc](https://docs.google.com/document/d/1wnUbAFtVtkGbtmuW-In02YxaUjyCaHOhzgww1eo9Kc8/edit?usp=sharing) to connect your local site with a site with data, to facilitate the below steps.
* You can use the everydayimtravelling.com site for this.
* Use POSTMAN to do a GET request to your site's `https://example.com/wp-json/yoast/v1/top_pages?limit=5` (use the steps in [that article](https://www.oasisworkflow.com/how-to-authenticate-wp-rest-apis-with-postman) to do authenticated requests)
* …
=> Add SEO scores in top pages endpoint

packages/js/src/shared-admin/components/site-kit-consent-modal.js, packages/ui-library/src/components/modal/index.js, packages/ui-library/src/components/modal/stories.js
* UI only
* [@yoast/ui-library 0.0.1] Exposes the `Modal.Panel`' close button as `Modal.CloseButton`. For easier styling overrides via the `className` prop.
* Extracted the close button to prevent having to import the `introduction.css` for the button styling override. As there is no way to target that in JS before this patch
* Added the modal itself, and tested with https://github.com/Yoast/wordpress-seo/pull/21946 -- but now pointing to `trunk` because of force pushes and things. So lets get that merged before testing this.
* The image in the design is just a placeholder, real image coming soon ™️ 
* The shortlink should be: http://yoa.st/sitekit-consent-learn-more -- actual query params need to be added later
* Granting of …
=> Add the Site Kit consent modal

.github/workflows/generate_csv.yml, packages/yoastseo/package.json, packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigSpec.js
* GitHub action to generate the CSV file contents.
This action would allow the creation of the CSV file contents with the inclusive language configuration. This action can be triggered from the GitHub interface. 
- Introduced a GitHub action to generate CSV file contents with the inclusive language configuration. The action can be triggered directly from the GitHub interface.
* YML, JavaScript
1. Go to the "Actions" tab
2. Select "Generate CSV" from the Workflow list
3. Click on "Run workflow" 
4. Refresh the page and click on the run build
5. Click on "run-commands" and wait for the process to complete
6. The contents of the CSV file will be generated and displayed in …
=> Export inclusive language csv contents

src/dashboard/application/search-rankings/top-page-repository.php, src/dashboard/domain/search-console/failed-request-exception.php, src/dashboard/domain/search-rankings/top-page-data.php, src/dashboard/infrastructure/endpoints/search-rankings/top-query-endpoint.php, src/dashboard/infrastructure/indexables/top-page-indexable-collector.php, src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php
*
* Enhances the `Top 5 pages` endpoint with edit links for the URLs
* Enhances the `Top 5 pages` endpoint with better response status codes when site kit requests fail.
* Fixes the endpoints that are included in the dashboard scriptdata.
*
* Prepare your local environment by following the `Using the feature in Local site with data from Production site` section in [the relevant doc](https://docs.google.com/document/d/1wnUbAFtVtkGbtmuW-In02YxaUjyCaHOhzgww1eo9Kc8/edit?usp=sharing) to connect your local site with a site with data, to facilitate the below steps.
**For the edit links**:
* The general rule is that you get edit links only:
* For posts or terms or the homepage …
=> Improves the Top 5 pages endpoint

src/presenters/canonical-presenter.php, src/presenters/open-graph/title-presenter.php
* Fixes #21455
* Fixes deprecation notice thrown by the canonical presenter in environments running PHP >= 8.1. Props to [aanduque](https://github.com/aanduque).
* add the following snippet in your theme's functions.php:
```
add_filter( 'wpseo_canonical', function() { return null; } );
add_filter( 'wpseo_opengraph_title', function() { return null; } );
```
* make sure you are running PHP >= 8.1
* make sure `WP_DEBUG` is `true`
* visit a post in the frontend
* without this patch:
* you get two `trim(): Passing null to parameter #1 ($string) of type string is deprecated` warnings
* with this patch:
* you don´t  get the warning above …
=> Fix deprecation notices in PHP >= 8.1

packages/js/src/analysis/collectAnalysisData.js, packages/js/tests/collectAnalysisData.test.js
* We want to fix a bug where the Yoast SEO analysis removes invalid blocks that display the "Attempt recovery" message.
* Fixes a bug where invalid inner blocks would be removed when saving a post in the block editor.
* We are fixing the problem by cloning the blocks array before making any modification to the array.
* This is necessary because otherwise, invalid blocks will be removed from the editor.
* We are using `JSON.parse` and `JSON.stringify` to clone the blocks over `lodash.cloneDeep` or `structuredClone` for the following reasons:
* [_.cloneDeep](https://lodash.com/docs/4.17.15#cloneDeep) cannot handle private members of classes from the blocks.
* [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/Window/ …
=> Clone the blocks array first before filtering out the invalid blocks and add block length information

src/dashboard/user-interface/configuration/site-kit-configuration-dismissal-route.php, src/dashboard/user-interface/configuration/site-kit-consent-management-route.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Register_Routes_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Register_Routes_Test.php
* We want to make sure we don't throw 500 error codes when the endpoint is misused
* Improves the configuration endpoints by declaring their arguments as required.
*
* Do a POST request to `https://YOUR_WORDPRESS_SITE/wp-json/yoast/v1/site_kit_manage_consent` with no body
**Without this PR:**
* You would get a 500 error code and a fatal error
**With this PR:**
* You would get a 400 error code telling you that you didnt include the required `consent` argument and no fatal error
---
* Do a POST request to `https://YOUR_WORDPRESS_SITE/wp-json/yoast/v1/site_kit_configuration_permanent_dismissal` with no body
**Without this PR:**
* You would get a 500 error code and a fatal …
=> Declare required arguments for the site kit configuration endpoints

packages/js/package.json, packages/js/src/dashboard/index.js, packages/js/src/dashboard/services/data-formatter.js, packages/js/src/dashboard/services/widget-factory.js, packages/js/src/dashboard/widgets/top-pages-widget.js, packages/js/src/general/initialize.js, packages/js/tests/dashboard/__mocks__/data-provider.js, packages/js/tests/dashboard/services/data-formatter.test.js, packages/js/tests/dashboard/widgets/top-pages-widget.test.js
* Create a layer that formats the data for presentation
* Adds a data formatter and implement it in the top pages widget.
* Using the browser APIs for formatting: [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) and [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)
* Retrieving the locale from the HTML `lang` instead of the WP user locale as this seems easier. No script data transfer needed and the WP user locale uses an underscore instead of a dash.
* Using an Object for context for flexibility, more can be added as needed (opposed to the string in the issue)
* Enable the site kit …
=> Add data formatter

packages/ui-library/src/components/modal/index.js
* Fixes a required prop mistake made in [this PR](https://github.com/Yoast/wordpress-seo/pull/21984).
* [@yoast/ui-library 0.0.1] Fixes an unreleased bug where the `Modal.CloseButton` would have the `onClick` prop marked as required, while it would fall back to the Modal's `onClose` if not provided.
*
* Run the tests for JS, specifically the unsaved changes modal test was how I noticed this React prop warning
* Without this PR you get the prop warning:
> Warning: Failed prop type: The prop `onClick` is marked as required in `Modal.CloseButton`, but its value is `undefined`
* With this PR you should no longer get that warning
* Enable script debug so you get React warnings …
=> UI library: Modal.CloseButton should not require the onClick prop

packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js, packages/search-metadata-previews/tests/SnippetPreviewTest.js, packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
* Google doesn't show breadcrumbs in mobile search results anymore (see this [article](https://developers.google.com/search/blog/2025/01/simplifying-breadcrumbs)). This PR makes sure that the breadcrumbs is not rendered in the search snippet preview in mobile mode.
* [@yoast/search-metadata-previews] Removes the breadcrumbs container from the Search snippet preview in Mobile mode.
* Removes the breadcrumbs from the Search snippet preview in Mobile mode.
* [shopify-seo] Removes the breadcrumbs from the Search snippet preview in Mobile mode.
* I also do some girl scouting in the `packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js` file, fixing some typos. …
=> Remove breadcrumbs from mobile search preview

.github/workflows/pr-validation.yml
To improve PR tracking and ensure proper release management, we want to prevent merging PRs unless they have:
1. A **changelog label** that starts with `changelog:`
2. A **milestone assigned**
This PR introduces a **GitHub Action** that enforces these rules, making sure PRs are properly labeled before merging.
* Adds validation to a PR, checking if it has a proper changelog label and milestone attached.
- The GitHub Action runs on all PR updates (`opened`, `edited`, `labeled`, `unlabeled`, etc.).
- It checks for a **changelog label** and **milestone**, failing if either is missing.
1. Open a new PR **without a changelog label or milestone**.
- ❌ The check should fail.
2. …
=> GitHub Action for enforcing PR Validation for Changelog Labels and Milestones

src/dashboard/infrastructure/indexables/top-page-indexable-collector.php
*
* Fixes an unreleased bug where edit links would be shown to users that can't edit posts.
*
* Create an SEO manager and authenticate your POSTMAN requests based on that user.
* Add the following filter so that you remove the capability to edit other people's posts:
```
function remove_edit_others_posts_capability() {
$role = get_role('wpseo_manager'); // Change 'editor' to any role you want to modify
if ($role) {
$role->remove_cap('edit_others_posts');
// $role->remove_cap('edit_terms');
// $role->remove_cap('manage_categories');
}
}
add_action('init', 'remove_edit_others_posts_capability');
```
* Deactivate/reactivate Yoast SEO
* Do a request to the top 5 pages …
=> Don't add edit links in API response if user can't edit posts

packages/js/src/dashboard/index.js, packages/js/src/dashboard/services/data-provider.js, packages/js/src/dashboard/services/widget-factory.js, packages/js/src/dashboard/widgets/site-kit-setup-widget.js, packages/js/src/general/initialize.js, packages/js/tests/dashboard/__mocks__/data-provider.js, packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js, src/dashboard/infrastructure/integrations/site-kit.php, tests/Unit/Integrations/Admin/Integrations_Page_Integration_Test.php
* Decision on when to hide etc, see the [Specific behaviors section](https://docs.google.com/document/d/1BkN2qKkM8sPiNzcoH8eTQv-hcnzfZNfIlPv-SSes1Ug/edit?tab=t.0#heading=h.jm6hr9n0su8l)
* To be implemented in another PR: adding the widgets on granting consent
*  Implements Site Kit setup widget' `Remove permanently` functionality.
* adds the current value to the site kit configuration
* don't show the setup widget if permanently dismissed
* clicking on "Got it!" is non-permanent: so if a user disconnects again, the setup widget should return
* clicking on "Got it!" should still keep hiding the widget on tab change: so I added a cheat in the widget factory
> [!TIP] 
> To …
=> Implement permanent dismiss Site Kit setup widget

src/dashboard/domain/analytics-4/unexpected-response-exception.php, src/dashboard/domain/search-console/unexpected-response-exception.php, src/dashboard/infrastructure/analytics-4/site-kit-analytics-4-adapter.php, src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php
*
* Refactors endpoint to use Google libraries for parsing the responses from Google APIs.
*
For the new exceptions:
* In **src\dashboard\infrastructure\search-console\site-kit-search-console-adapter.php**, change the `$response = self::$search_console_module->get_data( 'searchanalytics', $api_parameters );`  line to `$response = 'foo';` 
* Do a GET request to `/wp-json/yoast/v1/time_based_seo_metrics?options[widget]=page` or `/wp-json/yoast/v1/time_based_seo_metrics?options[widget]=query`
* Confirm that you get a 400 response with the `"error": "The response from Google Site Kit did not have an expected format."` body
* In …
=> Use Google library for parsing GSC responses

packages/js/src/dashboard/components/dashboard.js, packages/js/src/dashboard/components/page-title.js, packages/js/src/general/initialize.js
*
* Updates Dashboard page description.
*
* Enable the Google Site Kit feature flag
* The normal page title at the top of the page should be like this:
* Disable indexables, by adding the `add_filter( 'Yoast\WP\SEO\should_index_indexables', '__return_false' );`  filter
* Refresh the page and the page title should be like this:
* Re-enable indexables and disable the SEO and Readability analysis from your site settings
* Refresh the page and the page title should be like this:
* Now, disable the Google Site Kit feature flag. 
* The normal page title at the top of the page should be like this:
* Disable indexables, by adding the `add_filter( …
=> Update Dashboard page description

admin/class-meta-columns.php
*
* Removes extra span tags in the Post/Page overview. Props to [dilipbheda](https://github.com/dilipbheda).
1. Navigate to the WordPress admin panel: `{siteurl}/wp-admin/`  
2. Click on the "Pages" menu: `{siteurl}/wp-admin/edit.php?post_type=page`  
3. Open the URL in any HTML validator tool or check it using the Firefox web browser.  
4. In Firefox, view the page source to see the error.  
5. With this patch, the error is not there anymore.
Fixes #22052
=> Remove extra span tag

src/dashboard/infrastructure/analytics-4/site-kit-analytics-4-adapter.php
*
* Minor refactor for accessing the metric names in the Organic Session endpoints.
*
* Quickly smoke test that doing GET requests to `/wp-json/yoast/v1/time_based_seo_metrics?options[widget]=οrganicSessionsDaily` and `/wp-json/yoast/v1/time_based_seo_metrics?options[widget]=οrganicSessionsChange` give the same results with this PR and without
* In `src\dashboard\user-interface\time-based-seo-metrics\time-based-seo-metrics-route.php` change the `$request_parameters->set_metrics( [ 'sessions' ] );` lines to `$request_parameters->set_metrics( [ 'sessions', 'totalUsers' ] );` in both lines.
* Repeat the GET requests and again confirm you get the same results with this PR and …
=> Use getName() instead of accessing the name property directly

packages/js/src/dashboard/components/dashboard.js, packages/js/src/dashboard/index.js, packages/js/src/dashboard/services/widget-factory.js, packages/js/src/dashboard/widgets/site-kit-setup-widget.js, packages/js/src/general/initialize.js, packages/js/tests/dashboard/services/widget-factory.test.js, packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js
*
* Shows the "Top 5 most popular content" table on the dashboard on connecting to site kit, replacing the set up widget.
* The table should appear instead of the setup widget. I didn't consider priority, widgets are added from the top.
* Enable feature branch for site kit integration:
```
define( 'YOAST_SEO_GOOGLE_SITE_KIT_FEATURE', true );
```
* Complete the site kit setup on the dashboard.
*
*
Fixes [show site kit widgets immediately after site kit is connected on dashboard](https://github.com/Yoast/roadmap/issues/573)
=> show site kit tabular widget on connecting

packages/js/src/dashboard/components/error-alert.js, packages/js/src/dashboard/components/widget-table.js, packages/js/src/dashboard/widgets/site-kit-setup-widget.js, packages/js/src/dashboard/widgets/top-pages-widget.js
*
* Fixes copy and styling for the site kit widgets. 
* I refactor the top 5 most popular render content to be in a separate component for readability.
* Set up an environment for site kit with the feature branch enabled.
* Check you have the site kit set up widget and click on the 3 vertical dots menu.
* Connect to site kit.
* Check you see the table content.
* Check you see the loading effect on the table.
* Check the x in the table is vertically aligned to the center of the row.
* Hover a grey score bullet on the last row and check the copy in the tooltip is as follow:
> Content analysis hasn't started. Please open this page in your editor, enter a focus keyphrase and …
=> 458 UI feedback small fixes for site kit widgets

packages/js/src/dashboard/components/dashboard.js, packages/js/src/dashboard/services/data-provider.js, packages/js/src/dashboard/services/widget-factory.js, packages/js/src/dashboard/widgets/site-kit-setup-widget.js, packages/js/src/general/initialize.js, packages/js/tests/dashboard/services/widget-factory.test.js, packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js
* Once connected, the site kit widget should be dismissed by the "Got it!" button. 
* Fixes unreleased bug where the site kit widget "Top 5 mot popular content" would disappear on tab navigation.  
*  Since the initial list of widgets before site kit is connected doesn't include the "Top 5 most popular content" widget, I had to add that with condition in the widget factory, that solves the bug where the "Top 5 most popular content" widget would disappear on tab navigation. 
* Adding and removing the widgets from inside the site kit widget would create duplication because of the condition above. The removing or adding would change the state and in turn would re-render the dashboard component. That is why I used the remove callback …
=> fix the widgets visibility on connect and tab navigation

src/dashboard/infrastructure/integrations/site-kit.php
* This removes some information from the script data which is not needed there.
* Removes an unneeded interface from the Site_Kit configuration object which caused JS data to be enqueued in the post editor.
*
* Open the post editor and make sure `wpseoScriptData.metabox.setupUrl` returns undefined.
* To double check do this again with trunk or the previous RC to make sure you see an url.
*
* Enable google site feature flag
`define( 'YOAST_SEO_GOOGLE_SITE_KIT_FEATURE', true );`
* Make sure the dashboard still shows the site kit widgets or the setup widget.
* …
=> Removes unneeded interface

admin/class-bulk-editor-list-table.php, css/src/admin-global.css
#214
* Unblock bottom navigation on the bulk editor & redirects.
* Fixes a bug where the help beacon would be displayed over table pagination on Yoast admin pages.
* css rules added to apply required changes.
* Open **Yoast SEO ** > **Tools** > **Bulk Editor**
* Add more content if required to view navigation
* Reduce screen height if required to allow scroll
* Scroll to bottom and make sure that **Need Help?** badge doesn't overlap with the navigation.
*
* Should not impact other places.
Fixes [#214](https://github.com/Yoast/ux/issues/214)
=> Unblock bottom navigation on the bulk editor & redirects

packages/js/src/dashboard/components/dashboard.js, packages/js/src/dashboard/index.js, packages/js/src/dashboard/services/data-provider.js, packages/js/src/dashboard/services/widget-factory.js, packages/js/src/dashboard/widgets/site-kit-setup-widget.js, packages/js/src/general/initialize.js, packages/js/src/integrations-page/recommended-integrations.js, packages/js/src/integrations-page/site-kit-integration.js, packages/js/tests/dashboard/__mocks__/data-provider.js, packages/js/tests/dashboard/scores/components/scores.test.js, packages/js/tests/dashboard/services/widget-factory.test.js, packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js, packages/js/tests/integrations-page/SiteKitIntegration.test.js
* We want users to be able to see the setup widget again after reverting one of the steps.
* Allows the Site kit setup widget to show up after completing it and then reverting one of the steps.
* Did renaming of `isConnected` to `isConsentGranted` on the frontend only.
* Create a new site and make sure you can still complete the entire Sit Kit setup.
* After fully connecting Site kit disable the plugin and make sure the setup widget now shows the `activate` step.
* Active the plugin again and make sure the widget is now gone again.
*
*
Fixes …
=> Allow going back and forth with the setup widget.

packages/js/src/dashboard/widgets/top-queries-widget.js, packages/js/tests/dashboard/widgets/top-pages-widget.test.js, packages/js/tests/dashboard/widgets/top-queries-widget.test.js, src/dashboard/user-interface/configuration/site-kit-configuration-dismissal-route.php, src/dashboard/user-interface/configuration/site-kit-consent-management-route.php, tests/Unit/Dashboard/User_Interface/Configuration/Abstract_Site_Kit_Configuration_Permanent_Dismissal_Route_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Abstract_Site_Kit_Consent_Management_Route_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Check_Capabilities_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Check_Capabilities_Test.php
*
* Adds error messages for the site kit top queries widget and changes the capabilities for site kit widget.
* 
* Create an environment with site kit feature enabled and connected.
* Create a user with the role of SEO manager.
* Log in as an SEO manager
* Once connected check you see the the site kit widgets "top 5 most popular content" and "Top 5 search queries"
* Check those widgets have the error message:
> You don’t have permission to access this resource. Please contact your admin for access. In case you need further help, please check our [Support page](http://acceptance.test/wp-admin/admin.php?page=wpseo_page_support).
* To allow SEO manager to see the widget, go …
=> fix error handling and capabilities for consent

src/dashboard/infrastructure/integrations/site-kit.php
* This PR was originally created to fix a bug in a specific website that wasn't reproduceable anywhere else, as described in [the original task](https://github.com/Yoast/reserved-tasks/issues/471). 
* The fix of this PR not only fixed that niche bug in that website, but also makes more sense for all cases, even in websites that didn't experience that bug.
* Improves the way we detect if Site Kit has been set up, by using a more appropriate Site Kit function.
* 
* Install the PR/RC in a brand new site and go through the onboarding flow of our Site Kit integration
* As soon as you complete the 3rd step (Site Kit setup), go to our dashboard and confirm that the onboarding …
=> Use Authentication class from Site Kit to detect if it's set up

packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js, packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
*
* Adds _pregnant women_ to the potentially non-inclusive phrases targeted by the inclusive language analysis.
* [shopify-seo] Adds _pregnant women_ to the potentially non-inclusive phrases targeted by the inclusive language analysis.
*
* Add the phrase 'pregnant women' to a new or existing post.
* Confirm that the inclusive language analysis shows the following feedback with an orange traffic light: 
* Be careful when using _pregnant women_ as it can be exclusionary. Unless you are sure that the group you refer to only consists of women, use an alternative, such as _pregnant people_. [Learn more.](https://yoa.st/inclusive-language-gender?php_version=8.1&platform=wordpres …
=> Inclusive language: Add 'pregnant women' to potentially non-inclusive phrases

packages/js/src/introductions/initialize.js
* Remove  **Optimize your SEO content with Yoast AI** modal on Yoast admin pages.
* Removes the Yoast AI Optimize modals from the Yoast admin pages.
* We decided to live introduction behaviour for the feature. So initialComponents moved into beginning and if it's empty to prevent showing backdrop only early return is used.
* Deactivate Yoast Premium plugin.
* Open Yoast Test plugin  and click **Reset First time configuration progress**.
* Open any sql editor or use `wp db query` wp-cli command and remove **_yoast_wpseo_introductions** meta_key from **wp_usermeta** table:
```DELETE FROM `wp_usermeta` WHERE `meta_key` = '_yoast_wpseo_introductions'```
* Deactivate and than …
=> 448 not show ai modal on admin pages

packages/js/src/dashboard/index.js, packages/js/src/dashboard/services/use-remote-data.js, packages/js/src/dashboard/widgets/organic-sessions-widget.js, packages/js/src/dashboard/widgets/organic-sessions/compare.js, packages/js/src/dashboard/widgets/organic-sessions/daily.js, packages/js/src/dashboard/widgets/score-widget.js, packages/js/src/dashboard/widgets/search-ranking-compare-widget.js, packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js, packages/js/src/dashboard/widgets/search-ranking-compare/use-search-ranking-compare.js, packages/js/src/dashboard/widgets/top-pages-widget.js, packages/js/src/dashboard/widgets/top-queries-widget.js, packages/js/src/dashboard/widgets/widget.js, packages/js/src/general/initialize.js, packages/js/tests/dashboard/__mocks__/data-provider.js
* If there is an unexpected error, it would be nice if just that widget is taken out by it. Leaving the rest behaving. This change attempts to get closer to that possibility. It depends on the error still.
* Adds global error catching on a per widget basis.
Fixes Data formatter types since the split of interface in https://github.com/Yoast/wordpress-seo/pull/22075
* It makes sense to me to use the interface as the type, since we just want a `format` method -- how or which particular formatter instance provides that, is not important to the widget
I had some trouble figuring out how to go about the error boundary.
If not in the widget. What decides how it should look like? We would need a generic "widget" look?
So that is why I …
=> Add error boundary on Widget level

composer.json, tests/Unit/Integrations/Watchers/Search_Engines_Discouraged_Watcher_Test.php
This fixes an `Internal.Exception` thrown by PHPCS.
* _N/A_
=> Docs: fix incorrect type specificity

composer.json, composer.lock
* Tidy up `composer.json` file
* Tidy up `composer.json` file
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
* _N/A_
=> Composer: normalize the file

.phpcs.xml.dist
This reverts commit 0990078fcb998e353a4027d3415f9204b16ab966 which is no longer needed as the same fix is included in YoastCS 3.2.0 (update happened in #22122).
* _N/A_
=> Revert "PHPCS: minor ruleset tweak"

admin/class-bulk-editor-list-table.php, admin/class-premium-popup.php, admin/views/tabs/tool/import-seo.php, admin/views/user-profile.php
* Added space at end of the input fields and It is good as per the standard coding format.
* File Path: /wordpress-seo/admin/views/user-profile.php - Will see the space meessing at end of the input filed at line number: 28
* File Path: /wordpress-seo/admin/class-bulk-editor-list-table.php - Same issue at multiple lines. Please review the .diff file.
* File Path: /wordpress-seo/admin/class-premium-popup.php - Same issue at multiple lines. Please review the .diff file.
* File Path: /wordpress-seo/admin/views/tabs/tool/import-seo.php - Same issue at multiple lines. Please review the .diff file.
* Space is missing at end of the input field
* Adds space before the closing slash in self-closing HTML tags to comply with recommended …
=> Fixes issue #31963: Added space at end of the input fields

tests/Unit/Builders/Indexable_Builder/Build_For_System_Page_Test.php, tests/Unit/Builders/Indexable_Builder/Build_Test.php, tests/Unit/Builders/Indexable_Builder/Maybe_Build_Author_Indexable_Test.php, tests/Unit/Builders/Indexable_Builder/Save_Indexable_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Set_Site_Kit_Permanent_Dismissal_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Check_Capabilities_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Constructor_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Get_Conditionals_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Register_Routes_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Get_Conditionals_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Register_Routes_Test.php, tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Conditionals_Test.php, tests/Unit/Editors/Domain/Analysis_Features/Analysis_Features_List_Test.php, tests/Unit/Images/Application/Image_Content_Extractor_Test.php, tests/Unit/User_Meta/Infrastructure/Cleanup_Repository_Test.php, tests/WP/Formatter/Post_Metabox_Formatter_Test.php, tests/WP/Formatter/Term_Metabox_Formatter_Test.php, tests/WP/Images/Application/Image_Content_Extractor_Test.php
Referenced method doesn't exist.
Also test classes should not have both `@coversDefaultClass` + `@covers ::method` AND a `@covers ClassName` at class level.
Having a method level `@covers ::method` tag only works if there is also a class level `@coversDefaultClass`.
As these tests have class level `@covers` tags, Let's remove the invalid ones (which now try to point to global function which don't exist).
* _N/A_
=> Tests: fix variety of broken covers tags

src/dashboard/application/configuration/dashboard-configuration.php, src/dashboard/domain/endpoint/endpoint-list.php, src/dashboard/infrastructure/score-results/readability-score-results/cached-readability-score-results-collector.php, src/dashboard/infrastructure/score-results/seo-score-results/cached-seo-score-results-collector.php, src/editors/application/integrations/integration-information-repository.php, src/editors/application/seo/post-seo-information-repository.php, src/editors/application/seo/term-seo-information-repository.php, src/editors/application/site/website-information-repository.php, src/editors/domain/seo/description.php, src/editors/domain/seo/keyphrase.php, src/editors/domain/seo/social.php, src/editors/domain/seo/title.php, src/editors/framework/integrations/multilingual.php, src/editors/framework/integrations/woocommerce.php, src/editors/framework/seo/posts/description-data-provider.php, src/editors/framework/seo/posts/keyphrase-data-provider.php, src/editors/framework/seo/posts/social-data-provider.php, src/editors/framework/seo/posts/title-data-provider.php, src/editors/framework/site/base-site-information.php, src/editors/framework/site/post-site-information.php, src/general/user-interface/general-page-integration.php, src/user-meta/application/additional-contactmethods-collector.php, src/user-meta/application/cleanup-service.php, src/user-meta/application/custom-meta-collector.php, src/user-meta/user-interface/additional-contactmethods-integration.php, src/user-meta/user-interface/cleanup-integration.php, src/user-meta/user-interface/custom-meta-integration.php, tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php, tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
The "variable" name is only needed with a `@var` tag when using inline docblocks for inline variables. Not when using the `@var` tag for declared properties.
* _N/A_
=> Docs: remove redundant property names in `@var` tags

admin/ajax.php, admin/class-yoast-notification-center.php, admin/views/tool-file-editor.php, inc/sitemaps/class-sitemaps.php
`die()` is an alias, let's use the canonical construct name instead.
* _N/A_
=> CS/QA: prefer exit() over die()

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, admin/views/tabs/dashboard/dashboard.php, inc/class-wpseo-meta.php, inc/class-wpseo-utils.php, lib/orm.php, src/initializers/migration-runner.php, src/integrations/third-party/elementor.php, src/integrations/watchers/indexable-post-watcher.php, src/surfaces/values/meta.php, tests/Unit/Repositories/Indexable_Repository_Test.php
* Improve code documentation
* Improve code documentation
These should always contain a `@var` tag following the following format: `@var Type $name`.
* _N/A_
=> Docs: fix up inline `@var` docblocks

.github/workflows/finish-coveralls.yml, packages/js/src/dashboard/services/widget-factory.js, packages/js/tests/dashboard/services/widget-factory.test.js, phpunit-wp.xml.dist
*
* Fixes a, behind feature flag, bug where the Search Ranking Compare widget would be shown; Despite the user not having the search console view data permissions.
* Also added the check to the tests
* Added scope creep due to coveralls report negative 8.5% code coverage for just 1 JS file WITH test coverage -- I'm not sure it is fixed now, but keeping these changes:
* Exclude `src/generated` folder for integration/WP tests. As we already did for unit tests
* Fix `carryforward` names to match the minimum WP version
* I did NOT commit adding a `base-path` to the JS tests (`base-path: packages/${{ matrix.package }}`) as it did not seem to be a problem. But could be added later if running into more/similar issues
This PR can be …
=> Dashboard: check search console view data permissions before returning the component

packages/js/src/settings/helpers/search.js, packages/js/src/settings/routes/crawl-optimization.js
*
* Updates the Google AI name in the Crawl Optimization settings from _Bard_ to _Gemini_.
*
* Go to Yoast SEO -> Settings
* Search for `google` and check one of the results are: "Prevent Google Gemini and Vertex AI bots from crawling"
* Click on the result and check you reach the `Block unwanted bots` section on the crawl optimization section.
* Check it has the same copy:  "Prevent Google Gemini and Vertex AI bots from crawling".
* You can reach that section also by navigating to Yoast SEO -> Settings -> Advanced -> Crawl optimization.
*
* …
=> fix google ai name in crawl optimization and search

packages/js/src/dashboard/components/trend.js, packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js, packages/js/tests/dashboard/widgets/search-ranking-compare-widget.test.js
*
* Adds tests for the Search Ranking Compare widget.
* I did not test each individual component. Just the widget itself, more like an integration test
* I changed the Trend component to output the sign in the same string, as otherwise I had to account for the indent in the code
* I removed the data truthy check in the content as there is no valid way for that to not be there. If the server responds and there is no error, we have no reason for the data to be suddenly falsy
* Not sure if that describe.each is totally necessary like that, as we repeat other tests. But the setup is the same for those, and I don't mind it also testing the tooltips if there are no averages.
* …
=> Dashboard: add tests for the Search Ranking Compare widget

src/dashboard/infrastructure/integrations/site-kit.php
*
* Fixes a potential fatal error on the dashboard page.
*
* Follow the replication steps from https://github.com/Yoast/wordpress-seo/issues/22154 even with the feature flag off
* Visit the dashboard and confirm you no longer get a fatal error (or a PHP warning)
* Also, visit the dashboard in a site that never had Site Kit, visit the Yoast dashboard and confirm you dont get a fatal error (or a PHP warning)
*
*
Fixes #22154
=> Add defensive coding preventing potential fatal errors in dashboard

packages/dashboard-frontend/src/components/dashboard.js, packages/dashboard-frontend/src/index.js, packages/dashboard-frontend/src/services/widget-factory.js, packages/dashboard-frontend/tests/services/widget-factory.test.js, packages/js/src/dashboard/index.js, packages/js/src/dashboard/services/widget-factory.js, packages/js/tests/dashboard/services/widget-factory.test.js
*
* Fixes the remount of widgets on the dashboard.
* Remove the `widgetInstance` type since it wasn't used any more. The reason for the widget instance in the first place was to support adding the same widget more than once. Currently it is not needed.
* Make sure to configured site kit but do not connect yet.
* Go to Yoast SEO -> General, check the dashboard has the scores widgets and the site kit setup widget.
* Open the network tab and dismiss until next visit the site kit setup widget.
* Check the request for the scores widget was not triggered. ( You can also see the animation is not triggered)
* Connect to site kit, the site kit widgets should appear bellow and …
=> fix the remounting of widgets on dashboard rerender

src/repositories/indexable-cleanup-repository.php, tests/Unit/Repositories/Indexable_Cleanup_Repository_Test.php
Because of the join across the `wp_posts` table, there could potentially be _many_ posts where an author has been updated. Currently, each of those rows are returned but that data is discarded because the `SELECT` statement only grabs `author_id` <=> `post_author` pairings. For large data sets, this leads to an extremely inflated data list of duplicated `author_id` <=> `post_author` (ID) pairings.
With the `GROUP BY` statement, we ensure that only unique `author_id` <=> `post_author` (ID) pairings are returned, leading to much more efficient operation (from a code standpoint).
See this issue: https://github.com/Yoast/wordpress-seo/issues/22064
This PR makes the `update_indexables_author_to_reassigned` operation, and the `wp yoast cleanup` operation, much more efficient, by tackling only …
=> fix: return only unique Author ID <=> Post Author (ID) pairings.

packages/js/src/decorator/helpers/positionBasedAnnotationHelper.js, packages/js/tests/decorator/helpers/positionBasedAnnotationHelper.test.js, packages/yoastseo/src/helpers/htmlEntities.js
* Parts of https://github.com/Yoast/wordpress-seo/pull/21974 intended to solve an issue with the highlighting in case there were NBSP characters present. However, without Premium active, this turned out to be a regression. Therefore, in this PR, we want to revert that part of the PR. We also add one unit test to confirm the current behaviour works. 
* Reverts code that did not solve a highlighting issue with NBSP characters in the Gutenberg editor.
* We here revert commits to `packages/js/src/decorator/helpers/positionBasedAnnotationHelper.js` and `packages/js/tests/decorator/helpers/positionBasedAnnotationHelper.test.js`. 
* The reason that the previous PR passed acceptance is that in Premium, we use the `yoast.analysis.data` …
=> Reverts code that did not solve a highlighting issue with NBSP characters

src/dashboard/domain/traffic/comparison-traffic-data.php, src/dashboard/infrastructure/analytics-4/site-kit-analytics-4-adapter.php
*
* Fixes an unreleased bug with the total Organic Session number that appear in the relevant widget.
*
* For getting the complete data about the last 28 days and the complete data of the 28 days before that, do a GET request to `/wp-json/yoast/v1/time_based_seo_metrics?options[widget]=organicSessionsCompare`
* Confirm that the response you get is like:
```
[
{
"current": {
"sessions": 9
},
"previous": {
"sessions": 12
}
}
]
```
* Go to the actual Google Analytics platform and search for organic sessions of the last 28 days compared with the organic sessions of the 28 days before that and confirm you get the same result
* Specifically, you can do that by changing the date …
=> Handle date ranges in SK responses better

src/dashboard/infrastructure/analytics-4/site-kit-analytics-4-adapter.php, src/dashboard/infrastructure/analytics-4/site-kit-analytics-4-api-call.php, src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php, src/dashboard/infrastructure/search-console/site-kit-search-console-api-call.php, src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php, tests/WP/Dashboard/Infrastructure/Integrations/Is_Site_Kit_On_Boarded_Test.php, tests/WP/Dashboard/Infrastructure/Integrations/Is_Site_Kit_On_Boarded_Without_Site_Kit_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Abstract_Search_Console_Adapter_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Failed_Request_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Unexpected_Response_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Failed_Request_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Unexpected_Response_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Validate_Comparison_Response_Test.php, tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Validate_Response_Test.php
…request.
* We want to use the Site Kit rest api to get our data instead of their internal classes.
* Refactors the API data layer to use the Site Kit REST api.
*
* Smoke test our widgets to make sure they still show their data.
* For example without this PR make a screenshot of all the data points upgrade to the PR and make sure they are the same.
*
*
Fixes #
=> Rework search console and analytics 4 calls to internally use a rest request

packages/yoastseo/package.json, packages/yoastseo/src/languageProcessing/helpers/match/processExactMatchRequest.js, packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
* Currently, the keyphrase length assessment feedback strings that contain the words 'word(s)' or 'character(s)' are not created in a way that makes it easy/possible to translate them correctly in all languages. See https://github.com/Yoast/wordpress-seo/issues/20478 for more detail.
* Improves the translatability of feedback strings for the keyphrase length assessment.
* [shopify-seo] Improves the translatability of feedback strings for the keyphrase length assessment.
* [yoastseo] Improves the translatability of feedback strings for the keyphrase length assessment.
* I lowered the number of maximum eslint warnings from 20 to 19 since I fixed one warnings inside `packages/yoastseo/src/scoring/assessments/readability/KeyphraseLeng …
=> Improve translatability of keyphrase length assessment feedback strings

packages/js/src/general/initialize.js, src/dashboard/application/configuration/dashboard-configuration.php, src/dashboard/infrastructure/integrations/site-kit.php, tests/Unit/Dashboard/Infrastructure/Integrations/Site_Kit_To_Array_No_Conditional_Met_Test.php, tests/Unit/Dashboard/Infrastructure/Integrations/Site_Kit_To_Array_Test.php
* We want to make sure no Site Kit-related logic is run when the feature flag is false.
* Avoids running Site Kit-related logic by checking the feature flag conditional as soon as possible.
* I left the `isFeatureEnabled` attribute in the Site Kit configuration to keep frontend code untouched.
* Enable the feature flag and smoke-test our Site Kit widgets in the dashboard
* Edit `src/dashboard/infrastructure/integrations/site-kit.php` by changing lines 131-132 from:
```
$shared_roles       = ( isset( $dashboard_sharing[ $key ]['sharedRoles'] ) ) ? $dashboard_sharing[ $key ]['sharedRoles'] : [];
$has_viewing_rights = ( \is_array( $shared_roles ) ) ? \array_intersect( …
```
=> Fix feature flag

.github/workflows/browserslist-db.yml
Inspired by the State of the Code from @diedexx 
But then a tryout with a smaller scope: updating the Browserslist database via a GitHub workflow/action
* Introduces a GitHub workflow, that can be manually triggered, to create a PR to update the Browserslist or `caniuse` database.
Using [browserslist-update-action](https://github.com/c2corg/browserslist-update-action) to:
* create the branch
* run `npx update-browserslist-db@latest` to update (see [update-db](https://github.com/browserslist/update-db))
* add files and commit
* create a PR
AFAIK we cannot test this on this repository without merging it first.
I did test this myself by:
* creating a new (private) repository …
=> Add GitHub workflow to update the Browserslist database

admin/ajax.php, inc/class-wpseo-meta.php
I removed the `if` condition before calling `post_types_for_ids()` because it already handles the check internally.
Additionally, I moved the initialization of `$repository = YoastSEO()->classes->get( Indexable_Repository::class );` inside the `if` block to ensure it's only executed when `$post_ids` is not empty.
* Optimizes the function used to fetch post IDs which share the same focus keyphrase. Props to [dilipbheda](https://github.com/dilipbheda).
* Edit a post and give it a keyphrase, e.g. "test"
* Edit another post and give it the same keyphrase
* Open the `SEO analysis` tab in the metabox or in the Yoast sidebar
* Check that you get the message `Previously used keyphrase: you've used this keyphrase multiple times before. Do …
=> Removed unnecessary condition checks

src/dashboard/infrastructure/analytics-4/site-kit-analytics-4-adapter.php
* We no longer rely on internal site kit classes to do our data fetching.
* Removes unused constructor code.
*
* Some smokes tests of the widgets. The code was already not used anymore.
*
*
Fixes #
=> Remove final use of internal Site_Kit code.

src/conditionals/third-party/site-kit-conditional.php, src/dashboard/user-interface/configuration/site-kit-capabilities-integration.php, src/dashboard/user-interface/configuration/site-kit-configuration-dismissal-route.php, src/dashboard/user-interface/configuration/site-kit-consent-management-route.php, src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php, src/dashboard/user-interface/tracking/setup-steps-tracking-route.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Capabilities_Integration_Get_Conditionals_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Get_Conditionals_Test.php, tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Get_Conditionals_Test.php, tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Conditionals_Test.php, tests/Unit/Dashboard/User_Interface/Tracking/Setup_Steps_Tracking_Route_Get_Conditionals_Test.php
* We don't want to load routes that are not needed when Site Kit is disabled.
* Adds some more conditionals for a set of Site Kit dependent routes.
*
* Smoke test the Site Kit setup widget and our widgets to make sure they still work.
* Disable Site Kit
* Make sure there are no errors and the setup still works as expected.
* Try to perform the following REST request with any HTTP client:
```
http://sitekittest.test/wp-json/yoast/v1/site_kit_manage_consent?consent=false
```
* Verify you get a `rest_no_route` response
* Enable Site Kit
* Perform the same request as above and verify you get a `success: true` response this time 
* …
=> Add site kit conditional when needed.

packages/dashboard-frontend/babel.config.js
* Copied this solution from the UI library.
* Fixes an bug where the `dashboardFrontend` script would include all hero icons, instead of the 3 it uses.
Having ES modules allows the plugin to be smarter when bundling (and properly tree-shake). In effect this solves the problem of all bundling all hero icons because of this package using 3 (at the moment)
Documentation: https://babeljs.io/docs/babel-preset-env#modules
* Without this PR
* Build
* Verify that in `packages/dashboard-frontend/build` the contents are with `require` instead of `import`
* Run `yarn webpack-analyze-bundle`
* In the tab about the packages, focus on the `dashboardFrontend` and filter on `@heroicons` …
=> Dashboard-frontend: preserve ES modules in build

admin/tracking/class-tracking-settings-data.php, inc/options/class-wpseo-option-wpseo.php, src/conditionals/google-site-kit-feature-conditional.php, src/dashboard/infrastructure/integrations/site-kit.php, tests/Unit/Dashboard/Infrastructure/Integrations/Abstract_Site_Kit_Test.php, tests/Unit/Dashboard/Infrastructure/Integrations/Site_Kit_To_Array_No_Conditional_Met_Test.php, tests/Unit/Dashboard/Infrastructure/Integrations/Site_Kit_To_Array_Test.php, tests/WP/Dashboard/Infrastructure/Integrations/Is_Site_Kit_On_Boarded_Test.php, tests/WP/Dashboard/Infrastructure/Integrations/Is_Site_Kit_On_Boarded_Without_Site_Kit_Test.php
* We want to change our `DEFINE` feature flag to an option.
* Changes the Google Site Kit feature flag to an options.
*
* Make sure you have this PR/an RC of the test helper: https://github.com/Yoast/yoast-test-helper/pull/242 and install this on a fresh site together with this PR/RC.
* Make sure the dashboard does not show the Site Kit widget.
* Go to `/wp-admin/tools.php?page=yoast-test-helper` and click `Reset Toogle Site Kit feature flag` (the reset is added by the plugin 🤦 ) . This turns it `ON` in this case.
* Make sure the widget is now on.
* Finish the setup and make sure you see working widgets (Or do this on a local system you know is fully configured).
* Click …
=> Change the Site Kit dashboard feature flag to an option.

packages/js/src/ai-generator/components/modal-content.js, packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js, packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js, packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap, packages/js/tests/shared-admin/components/__snapshots__/ai-generate-titles-and-descriptions-upsell.test.js.snap
*
* Adds data attributes to upsell buttons.
*
* Disable premium.
* Go to the post editor and click on the `use ai` button in the metabox for both `SEO title` and `Meta description`.
* In the modal make sure that the `Unlock with Yoast SEO Premium` button has the following two data attributes: 
```
data-action="load-nfd-ctb"
data-ctb-id="f6a84663-465f-4cb5-8ba5-f7a6d72224b2"
```
* Do the same for the  ✨ button in the readability analysis.
* ~~Do the same for the initial upsell popup after first installing the plugin. (This is the same popup as the ✨ one).~~
---
* Make sure you have Woo enabled and premium and our Woo add-on disabled.
* Edit a product and click on `use ai` …
=> Add two CTB button codes with difference for different upsells.

packages/yoastseo/spec/bundledPlugins/previouslyUsedKeywordsSpec.js, packages/yoastseo/spec/scoring/assessments/seo/IntroductionKeywordAssessmentSpec.js, packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInSEOTitleAssessmentSpec.js, packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionKeywordAssessmentSpec.js, packages/yoastseo/spec/scoring/assessments/seo/UrlKeywordAssessmentSpec.js, packages/yoastseo/spec/specHelpers/scoring/relatedKeyphraseAssessorTests.js, packages/yoastseo/spec/specHelpers/scoring/seoAssessorTests.js, packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js, packages/yoastseo/src/scoring/assessments/SCORING SEO.md, packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js, packages/yoastseo/src/scoring/assessments/seo/KeyphraseInSEOTitleAssessment.js, packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionKeywordAssessment.js, packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js, packages/yoastseo/src/scoring/assessors/assessor.js, packages/yoastseo/src/scoring/assessors/collectionPages/cornerstone/relatedKeywordAssessor.js
* We want to remove the guard on the _keyphrase in introduction_, _keyphrase in meta description_, _keyphrase in SEO title_, _keyphrase in slug_ and _previously used keyphrase_ assessments to show them even when there is no content added. This better shows our content analysis capabilities off the bat.
* Makes the following SEO assessments available in the analysis by default, even when no content has been added: _keyphrase in introduction_, _keyphrase in meta description_, _keyphrase in SEO title_, _keyphrase in slug_ and _previously used keyphrase_.
* [shopify-seo] Makes the following SEO assessments available in the analysis by default, even when no content has been added: _keyphrase in introduction_, _keyphrase in meta …
=> Adjust applicability of 5 keyphrase seo assessments

packages/js/src/insights/initializer.js, packages/yoastseo/src/languageProcessing/helpers/prominentWords/determineProminentWords.js
* Prominent words don't change after switching language.
* Adds function words to the prominent words cache function. 
* [yoastseo 3.1.1 bugfix] Fixes a bug where prominents words were not updated when switching languages. 
* Function computeProminentWordsMemoized updated to use as a hash functionWords which are depended on languages. Taking into account that list are very long - hashes from all words are calculated to reduce memoized key size.
* Activate Free and Premium plugins.
* Have the WP language in English (United States)
* Create post with the following content.
> If you're a bright and restless teenager in a small town in the American Midwest, you may well have …
=> Update prominent words when data is changed

packages/yoastseo/spec/languageProcessing/AbstractResearcherSpec.js, packages/yoastseo/spec/languageProcessing/researches/getLongCenterAlignedTextsSpec.js, packages/yoastseo/src/languageProcessing/AbstractResearcher.js, packages/yoastseo/src/languageProcessing/researches/getLongCenterAlignedTexts.js, packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
* Currently, our assessment for long center-aligned elements (the [text alignment assessment](https://github.com/Yoast/wordpress-seo/blob/trunk/packages/yoastseo/src/scoring/assessments/SCORING%20READABILITY.md#9-text-alignment-only-in-premium)) has the `text-align-center` as a hard-coded class. In this PR, we allow overriding this class through the Researcher. This enables integrations to check other classes.
* [yoastseo enhancement] Allow overriding the classes that are used to center elements in the _text alignment_ assessment.
* We're using lodash' `intersection` method as [the same method on `Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/intersection) unfortunately is not yet …
=> Allow overriding the classes that are used to center elements

packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js, packages/js/src/components/contentAnalysis/SeoAnalysis.js, packages/js/src/helpers/shouldRenderAIOptimizeButton.js, packages/js/tests/helpers/shouldRenderAIOptimizeButton.test.js
* We don't want to make the AI Optimize feature available in terms for now. This PR ensures that the AI Optimize button is not shown in terms (in Free).
* Removes AI Optimize button from taxonomies.
* In Premium, through the `Post_Conditional`, we already ensured the AI Optimize integration is not loaded. 
* Create a taxonomy
* The test should be executed in tags, categories, custom taxonomies, WooCommerce Brands, WooCommerce categories, WooCommerce tags, and WooCommerce  attributes
* Set the focus keyphrase
* Add some contents so that you get 🔴 red or 🟠 orange feedback for the following assessments: …
=> Disable AI Optimize button in taxonomies

src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php, tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Metrics_Test.php
*
* Introduces a filter to allow changing the requested dates in the Site Kit integration. Will be used for automated testing.
*
* Quickly double check that the data you see in the Yoast Dashboard with and without this PR are the same (make sure you test in different tabs, to avoid cache)
* Add the following filter in your site:
```
add_filter( 'wpseo_custom_site_kit_base_date', 'custom_site_kit_base_date', 10 );
function custom_site_kit_base_date() {
return 'now';
}
```
* In a new tab, confirm you still get the same data as before.
* Add the following filter in your site:
```
add_filter( 'wpseo_custom_site_kit_base_date', 'custom_site_kit_base_date', 10 );
function …
```
=> Introduce filter to allow changing the requested dates in the Site Kit integration

packages/js/src/ai-generator/components/modal-content.js, packages/js/src/ai-optimizer/components/ai-optimize-button.js, packages/js/src/ai-optimizer/components/modal-content.js, packages/js/src/shared-admin/components/ai-optimize-upsell.js, packages/js/tests/ai-optimizer/components/ai-optimize-button.test.js
* We want to add an upsell for AI Optimize on WooCommerce products. This follows the same logic as we have for the AI Generate functionality. This PR is a follow-up of #21417 and #22214. 
* Ensures that AI Optimize on WooCommerce products can only be used with Yoast SEO Premium and Yoast WooCommerce SEO active, shows an upsell otherwise.
* We're reusing the code in AI Generate to retrieve the correct upsell properties.
> [!NOTE]
> While testing the AI Optimize upsell, smoke test the AI Generate upsell as well, see #22214 for the testing steps.
* Create a WooCommerce product that has any AI Optimize button active. 
* For example, create product that has an introduction, …
=> Adds an upsell for AI Optimize on products

admin/views/class-yoast-feature-toggles.php, inc/options/class-wpseo-option-ms.php, packages/js/src/settings/routes/site-features.js, src/integrations/settings-integration.php, tests/Unit/Admin/Views/Feature_Toggles_Test.php
*
* Adds the proper copy and shortlink in the feature card.
* Disables the feature for multisites.
*
* Go to Yoast SEO -> Settings and confirm that the copy is like this:
> LLMs.txt
>
> Boost the visibility of your content in AI searches. Automatically create an llms.txt file that lists a selection of your site’s content. This helps LLMs access and provide your site's information more easily.
>
> View llms.txt
* Confirm that the shortlink in the Learn more is this: `https://yoa.st/site-features-llmstxt-learn-more`
Also:
* Install the PR/RC in a fresh multisite installation
* Confirm that in the Yoast settings, you see the below:
* Using WP Crontrol, confirm there's no …
=> Add copy and shortlink in feature card

.github/dependabot.yml
* Prevent annoying comments on PRs
* Update Dependabot config
Support for the `reviewers` key in `dependabot.yml` files is being removed by GitHub on May 20th 2025.
The recommendation is to have a `CODEOWNERS` file to set reviewers instead.
For now, this commit removes the `reviewers` key from the `dependabot.yml` file without replacing it. That should prevent comments being left in PRs by the dependabot bot account about the field no longer being supported.
Ref:
* https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-loca …
=> Dependabot: remove reviewers

config/webpack/externals.js, config/webpack/webpack.config.js, packages/js/src/editor-modules.js
* Instead of bundling `@yoast/ai-frontend` in 3 separate entries. Add its own entry to re-use. This saves zip space.
> [!NOTE]
> Somehow all the Hero Icons are bundled -- that was the case before this PR too (so at least not 3 times now? 😅 )
* Moves the `@yoast/ai-frontend` to its own file instead of bundling in individual files.
* Use the build where the CSS is not included, so we don't have to process the CSS via our JS tooling. As that is geared towards just `@yoast/components` for ages.
* Does it still build?
* You could check `yarn webpack-analyze-bundle`
* Before it `ai-frontend` would be there 3 times (each editor file)
* Now it is there alongside our other …
=> Move `@yoast/ai-frontend` to own entry

packages/js/src/settings/helpers/search.js, packages/js/src/settings/routes/site-features.js
* It needs to be lowercase.
* Makes the header of the feature card lowercase.
*
* Go to `/wp-admin/admin.php?page=wpseo_page_settings#/site-features` and make sure the header is `llms.txt` and not `LLMs.txt` and also the button mentions the lower case as well.
* Also when searching for `llm` in the settings search, it shows as lower case too:
*
Fixes https://github.com/Yoast/reserved-tasks/issues/590
=> make LLM -> llm

packages/js/src/elementor/initialize.js, src/integrations/third-party/elementor.php
*
* Fixes a bug where the Yoast introduction in the Elementor editor would not be positioned correctly when on Elementor version 3.30.0.
The editor v2 is taken out of the experimental features in version 3.30.0. Below 3.30.0, we still need the same logic.
Added some stripping of the version as the PHP version_compare must have a semver.
* To ensure you get the introduction:
* In the database, go to the `user_meta` table (default prefix: `wp_`)
* Find the row where the `meta_key` is `elementor_introduction`
* Delete the row entry for your user from your database. 
* Install and activate some 3.30.0 or higher: https://github.com/elementor/elementor/releases
* Edit a post in …
=> Add Elementor version check to determine the introduction version

src/llms-txt/application/markdown-escaper.php
*
* Improves escaping of llms.txt 
*
* Change the Site title into `'Marks & Spencer'<strong>Europe</strong> &#8217;north&#8217; "department"` (note the quotes and the greater/less than symbols and also the `&#8217;` encoded characters. If you go to the frontend and see the title, they are encoded, like: `&#039;Marks &amp; Spencer&#039;&lt;strong&gt;Europe&lt;/strong&gt; &#8217;north&#8217;  &quot;department&quot;`)
* Generate the llms.txt file and run it through a markdown parser like https://markdownlivepreview.com
* The title section begins with `# 'Marks \& Spencer'\<strong\>Europe\</strong\> ’north’ "department"` (the symbols have been decoded and everything that …
=> Improve escaping of llms.txt 

src/ai-http-request/domain/exceptions/remote-request-exception.php, src/ai-http-request/domain/exceptions/wp-request-exception.php
*
* Fixes an unreleased bug where a `Remote_Request_Exception` class couldn't be built because of wrong constructor parameters.
* N/A
**Note**: you don't need to test this with a live site, a regular local one would do.
* Edit `src/ai-http-request/infrastructure/api-client.php`:
* add `use WP_Error` at line 7
* change line 55 from:
```
$response = ( $is_post ) ? \wp_remote_post( $url . $action_path, $arguments ) : \wp_remote_get( $url . $action_path, $arguments );
```
to:
```
$response = new WP_Error('test');
```
* Edit a post and click on `Use AI`
* Verify that:
* You get the following error:
* in the browser console you can see an error as follows:
``` …
```
=> Fix exception

packages/analysis-report/package.json, packages/analysis-report/src/AnalysisList.js, packages/analysis-report/src/AnalysisResult.js, packages/analysis-report/src/SiteSEOReport.js
> [!IMPORTANT]
> Based of https://github.com/Yoast/wordpress-seo/pull/22256
> The merge base should be updated to trunk automatically if that is merged first
* [@yoast/analysis-report 0.1.0] Refactors the `defaultProps` to be `defaultArguments` instead.
[Refactor defaultProps to defaultArguments](https://github.com/Yoast/wordpress-seo/commit/a4ed8374ae5032a73f6d79a40c1df7807a8145d3) 
* fix JS doc
* use prop spreading
* specify which props in "areMarkButtonsHidden"
* remove unused "hasAIButton" prop
* remove import comments (as they interfere with my auto ordering)
[Decrease allowed warning count](https://github.com/Yoast/wordpress-seo/pull/22263/commits/8a2c84c7ee2d38fd5a0455b0d07672c271980796) 
Still 2 more than before the …
=> Analysis Report: Refactor defaultProps to be defaultArguments

admin/taxonomy/class-taxonomy.php, packages/js/src/ai-generator/components/app.js, packages/js/src/ai-generator/components/feature-error.js, packages/js/src/ai-generator/components/google-content.js, packages/js/src/ai-generator/components/introduction.js, packages/js/src/ai-generator/components/sparks-limit-notification.js, packages/js/src/ai-generator/components/tip-notification.js, packages/js/src/ai-generator/components/upsell-modal-content.js, packages/js/src/ai-generator/helpers/index.js, packages/js/src/ai-generator/hooks/index.js, packages/js/src/ai-generator/hooks/use-location.js, packages/js/src/ai-generator/hooks/use-upsell-props.js, packages/js/src/ai-generator/store/index.js, packages/js/src/ai-generator/store/usage-count.js, packages/js/src/ai-optimizer/components/modal-content.js, packages/js/src/redux/reducers/editorContext.js, packages/js/src/redux/selectors/editorContext.js, packages/js/src/redux/selectors/preferences.js
* WIP 
* Refactors ai upsell modal, usage counter and spark notification.
* 
* Edit a post ( on local env, use [fake-ai-notification.patch](https://github.com/user-attachments/files/20628349/fake-ai-notification.patch))
* Click on "Use AI".
* Check you see the upsell, click on try for free button.
* Grant consent.
* Check you can use the AI generator.
* Refresh and click on "Use AI".
* Check you don't see the consent or the upsell.
* Go to Yoast SEO->Settings->Site features
* Disable "SEO analysis"
* Edit a page or post and click on "Use AI"
* Check you get an error message for the SEO analysis.
* Go to profile page and look for "AI feature", click on "Revoke consent" and …
=> 586 create a notification for when the sparks run out

tests/Unit/AI_Free_Sparks/User_Interface/Free_Sparks_Route/Can_Edit_Posts_Test.php, tests/Unit/AI_Free_Sparks/User_Interface/Free_Sparks_Route/Conditional_Test.php, tests/Unit/AI_Free_Sparks/User_Interface/Free_Sparks_Route/Constructor_Test.php, tests/Unit/AI_Free_Sparks/User_Interface/Free_Sparks_Route/Register_Routes_Test.php, tests/Unit/AI_Free_Sparks/User_Interface/Free_Sparks_Route/Start_Test.php
*
* Adds tests to the free sparks rest route.
*
*
*
*
Fixes #
=> Add tests to free sparks route

src/llms-txt/application/file/commands/populate-file-command-handler.php, tests/Unit/Llms_Txt/Application/File/Commands/Populate_File/Handle_Test.php
*
* Improves support for non-english characters in llms.txt, for servers that don't serve .txt files in UTF-8.
*
* Make sure you set your llms.txt file to have a non-english character
* For example, add `ελληνικα` in your Site Title
* Generate your llms.txt file and then view it in the browser
* You'll see the `# Ελληνικα:` part properly and not gorbled
* Add the following snippet, that removes the BOM prefix from the llms.txt file:
```
add_filter( 'wpseo_llmstxt_encoding_prefix', 'custom_llmstxt_encoding_prefix', 10 );
function custom_llmstxt_encoding_prefix() {
return '';
}
```
* Re-generate the file and view it in the browser again
* This time, you'll see that part as …
=> Add BOM for UTF-8 to improve support for non-english characters

src/llms-txt/application/file/commands/populate-file-command-handler.php, src/llms-txt/infrastructure/file/wordpress-file-system-adapter.php
*
* [wordpress-seo bugfix] Fixes a bug where the llmst.txt file wouldn't be able to be generated in wp.com.
* Introduces the `wpseo_llmstxt_filesystem_path` filter that allows editing the file path of the llmst.txt file, to help users in servers with filesystem restrictions.
*
* Re-generate the llms.txt file and confirm that you see it being created in the webroot of your filesytem (aka, the place it was created before this change) (aka, the directory that contains the wp-config.php file)
* Add the following snippet:
```
add_filter( 'wpseo_llmstxt_filesystem_path', 'custom_llmstxt_file_path', 10 );
function custom_llmstxt_file_path() {
return WP_CONTENT_DIR ;
}
```
* …
=> Introduce filter that edits the file path of the llms.txt file

packages/js/src/ai-generator/components/app.js, packages/js/src/ai-generator/components/errors/subscription-error.js, packages/js/src/ai-generator/components/feature-error.js, packages/js/src/ai-generator/components/introduction.js, packages/js/src/ai-generator/components/modal-content.js, packages/js/src/ai-generator/components/upsell-modal-content.js, packages/js/src/ai-generator/initialize.js, packages/js/src/ai-generator/readme.md, packages/js/src/ai-generator/store/free-sparks.js, packages/js/src/ai-generator/store/usage-count.js, packages/js/tests/ai-generator/components/upsell-modal-content.test.js
*
* Implements the flow for the free sparks.
*
* Edit a post ( on local environment use this patch [fake-api.patch](https://github.com/user-attachments/files/20710157/fake-api.patch)).
* Click on `Use AI` button and check you see the upsell modal with the button to try for free.
* Click on the `Try for free` button and check you now see the consent modal.
* Grant consent and check you can see the AI generator
* Generate titles until you reach 10 sparks
* Check you see the toast notification and the "Generate 5 more" button is disabled.
* Close the modal 
* Click on the "Use AI" button and check you now see the upsell modal without the "Try for free" button and with an …
=> 623 create the free and premium ai generate flow

src/llms-txt/application/file/file-failure-notification-presenter.php, src/llms-txt/user-interface/file-failure-llms-txt-notification-integration.php, tests/Unit/Llms_Txt/User_Interface/File_Failure_Llms_Txt_Notification_Integration/Abstract_File_Failure_Llms_Txt_Notification_Integration_Test.php, tests/Unit/Llms_Txt/User_Interface/File_Failure_Llms_Txt_Notification_Integration/Constructor_Test.php, tests/Unit/Llms_Txt/User_Interface/File_Failure_Llms_Txt_Notification_Integration/Maybe_Show_Notification_Test.php, tests/Unit/Llms_Txt/User_Interface/File_Failure_Llms_Txt_Notification_Integration/Register_Hooks_Test.php
* We want to notify customers when we cannot generate a llms.txt for them.
* Enhances the UX of the llms.txt feature, by informing users for potential issues with generating the file, via Yoast's alert center.
*
* Remove your llms.txt file if you have it and make sure our feature is disabled.
* Go to our `alert center` and make sure there are no `problems` relating to the llms.txt feature.
* Enable the feature and make sure it works.
* Go to our `alert center` and make sure there are no `problems` relating to the llms.txt feature.
* Edit your llms.txt file and add a character. This makes it so we no longer `control` the file.
* Either disable and re-enable the feature or …
=> Add warning for when the LLMs.txt cannot be generated in our dashboard.

src/builders/indexable-link-builder.php, tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Delete_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Patch_Seo_Links_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Update_Incoming_Links_For_Related_Test.php
*
* Removes redundant flushing of cache groups when incoming links for posts change.
*
* Follow the test instructions of https://github.com/Yoast/wordpress-seo-premium/pull/4666
*
*
Fixes #
=> Replace flushing cache group with firing action instead

packages/js/src/helpers/shouldRenderAIOptimizeButton.js, packages/js/tests/helpers/shouldRenderAIOptimizeButton.test.js
* We want to disable the sparks button in the analysis for the classic editor.
* Disables the AI sparkle button in the classic editor.
*
* Test this together with https://github.com/Yoast/wordpress-seo-premium/pull/4669
*  
*
*
Fixes #
=> Disable ai optimize button for classic.

packages/js/src/ai-generator/components/app.js
*
* Avoids showing the spinner on both the `Use AI` button when waiting for the usage request to resolve.
* N/A
* Make sure you have previously given the consent
* Edit a post
* Click on `Use AI` and pay attention to both the `Use AI` buttons
* Verify only the one you clicked shows a spinner while waiting 
* N/A
Fixes [#633](https://github.com/Yoast/reserved-tasks/issues/633)
=> Fix spinner in buttons

packages/js/src/ai-generator/helpers/apply-pluggable-replacement-variables.js, packages/js/src/ai-generator/helpers/fetch-suggestions.js, packages/js/src/ai-generator/hooks/use-apply-replacement-variables.js, packages/js/tests/ai-generator/helpers/apply-pluggable-replacement-variables.test.js
*
* Fixes the AI generate replacement variable replacing.
* Also noticed the store data was influenced by this, fixed that by mapping over it instead
* Edit a page and go the the Search appearance.
* Make sure you have `Page` replacement variable in the title (or description).
* Open the AI generator and get some suggestions for the title.
* Verify there is no longer a `%%page%%` in the preview.
*
*
Fixes #
=> Fix apply replacevars

composer.json, inc/options/class-wpseo-option-llmstxt.php, inc/options/class-wpseo-options.php, tests/Unit/TestCase.php
*
* Adds another wpseo option in the database, one that's specific to the llms.txt feature.
*
* Either upgrade to this PR/RC or install and activate it in a fresh site
* Search in your DB and confirm you find the `wpseo_llmstxt` option
* Specifically, that option should have at least the `ids_to_include` sub-setting in it.
* Do the same in a multisite, with the difference that the `wpseo_llmstxt` option will appear in a subsite's separate `wp_X_options` table, only after we visit that subsite after the upgrade/activation of the PR/RC
*
Fixes #
=> Create new option for the llms.txt feature

src/plans/user-interface/plans-page-integration.php, tests/Unit/Plans/User_Interface/Plans_Page_Integration_Test.php
*
* Fixes an unreleased bug where the Plans page would not have a link in the Yoast menu on the frontend.
* No conditionals is fine?
Crucial fix:
Can't hurt to check (again):
Extra safety test:
Due to the no conditionals, always running, it makes sense to me to verify there is no issue in other requests like AJAX.
* Visiting our dashboard triggers a AJAX GET for the scores, you could even search for a term to trigger more
* Changing something in our first time configuration does a AJAX POST to save
Smoke test to be very safe:
Follow the other instructions from https://github.com/Yoast/wordpress-seo/pull/22374
* …
=> Also add the plans page when on the frontend

inc/options/class-wpseo-option-llmstxt.php, inc/options/class-wpseo-option-wpseo.php, packages/js/src/settings/components/formik-indexable-page-select-field.js, packages/js/src/settings/components/formik-page-select-field.js, packages/js/src/settings/components/index.js, packages/js/src/settings/routes/llms-txt.js, packages/js/src/settings/store/index.js, packages/js/src/settings/store/indexable-pages.js, src/integrations/settings-integration.php
*
* Adds multiple dropdowns for the manual selection of pages in the llms.txt file.
Known limitations of this first iteration:
* The UX around the page selection dropdowns is weird. Examples
* When first going into the page and while the `/page` request is still going, clicking an empty dropdown to add a page, doesn't give you a list of pages to choose from or a loading state. And as soon as the `/page` request is done, then suddenly you get a list of pages to choose from. Basically, **a lack of loading state when the initial `/page request is still going**.
* While you are searching for a page and you are typing the letters slowly, you are greeted with a `page not found` message while it searches, until you finish typing. When …
=> 641 create the dropdowns for the manual page selection

packages/js/src/settings/helpers/search.js, packages/js/src/settings/routes/site-features.js
*
* Restores llms.txt feature card that was removed in [Create the llms.txt settings page with some first elements](https://github.com/Yoast/wordpress-seo/pull/22345/files#top) and updates the button to redirect to the llms.txt settings page. 
* Updates the search value target route for llms.txt to the new llms.txt settings page.
*
* Go to Yoast SEO -> Settings -> Site features
* Check the last feature is the llm.txt and is has a button with the label: "Customize llm.txt file"
* Click on the button and check you are redirected to the llm.txt settings page
* Go back to the Sites features tab and disable the llm.txt feature, refresh and check it is save, enable and check it …
=> 658 adjust feature card to point to the new settings page

inc/options/class-wpseo-option-llmstxt.php, packages/js/src/settings/components/formik-indexable-page-select-field.js, packages/js/src/settings/components/formik-page-select-field.js, packages/js/src/settings/routes/llms-txt.js, src/integrations/settings-integration.php, src/llms-txt/domain/content/Post_Collection_Interface.php, src/llms-txt/domain/content/post-collection-interface.php, src/llms-txt/infrastructure/content/automatic-post-collection.php, src/llms-txt/infrastructure/content/manual-post-collection.php, src/llms-txt/infrastructure/content/post-collection-factory.php, src/llms-txt/infrastructure/markdown-services/content-types-collector.php
*
* Adds the back-end part for manual selection of pages for the llms.txt
*
* Make sure you have indexables enabled and the SEOO completed.
* Go to wp-admin/admin.php?page=wpseo_page_settings#/llms-txt and select manual. and choose a page for the `About us page` section. (or any other page in there)
* Save the page and re-generate your llms.txt file (by either running the cron or disabling and enabling the feature.
* Opens your llms.txt file and make sure you see the page you added to the `About us page`.
* Open this page and make it a draft. re-generate your file and make sure its gone.
* Publish it again and now no-index it in the metabox. re-generate your file and make …
=> 644 use manual page selection for llmstxt generation backend side

packages/js/src/settings/store/indexable-pages.js, src/conditionals/llms-txt-enabled-conditional.php, src/integrations/settings-integration.php, src/llms-txt/application/available-posts/available-posts-repository.php, src/llms-txt/domain/available-posts/data-provider/available-posts-data.php, src/llms-txt/domain/available-posts/data-provider/available-posts-repository-interface.php, src/llms-txt/domain/available-posts/data-provider/data-container.php, src/llms-txt/domain/available-posts/data-provider/data-interface.php, src/llms-txt/domain/available-posts/data-provider/parameters.php, src/llms-txt/domain/available-posts/invalid-post-type-exception.php, src/llms-txt/domain/content-types/content-type-entry.php, src/llms-txt/infrastructure/markdown-services/content-types-collector.php, src/llms-txt/user-interface/available-posts-route.php, src/repositories/indexable-repository.php, tests/Unit/Llms_Txt/Infrastructure/Content_Types_Collector/Get_Content_Types_Lists_Test.php
*
* Uses indexables for populating the dropdowns for the manual page selection in llms.txt.
*
* Confirm you have indexables enabled and the SEO optimization completed
* Go to yoast settings->llms.txt
* Click on a dropdown and confirm that you see the 10 most recently modified public pages to select. 
* If you write something in the dropdown, confirm that you see the pages that are properly filtered by what you wrote. The thing you wrote filters page titles.
* Select one page, save, refresh and confirm that it persists
* From the 10 most recently modified public pages that you saw in the previous steps, change some of them likeso:
* Make one private
* Make one draft
* Make …
=> Create new endpoint for getting available pages to be manually selected for llms.txt

packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js, packages/js/tests/components/SEMrushRelatedKeyphrasesModalContent.test.js, packages/related-keyphrase-suggestions/src/elements/UserMessage/index.js
Fixes a refactor mistake from https://github.com/Yoast/wordpress-seo/commit/9a029fca862c3627623453dc337ca40660cafa1b -- not realizing the actual current default was `undefined`.
* Fixes a bug where a request limit warning would be shown, in the Semrush related keyphrases, when no warnings would be applicable.
* [@yoast/related-keyphrase-suggestions 0.0.1 bugfix] Fixes a bug where the UserMessage would always result in a message, while the usages did were not made for that.
Now changing the default to documented `null` both in the UserMessage and the `getUserMessage` that supplies the variant.
* Open a post after integrating the Semrush account
* Be sure you have a focus …
=> Fix Semrush request limit warning in related keyphrases

src/integrations/settings-integration.php, src/llms-txt/infrastructure/content/manual-post-collection.php, tests/Unit/Integrations/Settings_Integration_Test.php
*
* Deals with pages that have been selected and then got deleted/private/noindexed etc.
* Reverts the registering of the policy pages (via the `get_site_basics_policies()` function) back to what it was before the feature branch). Mainly because we now divert enough from that way for the llms.txt pages so we can reduce the impact of our changes now.
* Select a couple of pages to be added manually in the llms.txt file
* After saving the settings, do the following to those saved pages (make sure at least one of them are from the contact/about/term/etc pages and one of them from the content pages):
* Make one private
* Make one draft
* Make one scheduled
* Make one noindexed …
=> Deal with pages that have been selected and then got deleted/private/noindexed etc.

src/conditionals/ai-editor-conditional.php
*
* Takes into account the RC part of the version number when comparing it.
*
* Install and activate Free SEO 25.6-RC2 + Premium 25.6-RC1
* Check you see the "Use AI" button for SEO Title/Description
* Now downgrade Premium to a previous version, like 25.4
* Check you still see the "Use AI" button for SEO Title/Description
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/2417
=> exclude RC suffix for version compare

packages/js/src/ai-generator/components/app.js
We want to check if the user is on product entitiy, woo commerce is installed and woo seo and subscription in invalid before showing subscription error
*
* Shows subscription error in product only when Woo SEO and premium are installed.
*
* Install and activate Woo+Free SEO RC3+ Premium RC1 (no Woo SEO) + valid premium subscription
* Click on "Use AI" and check you see the upsell modal.
* Install Woo seo.
* Click on "Use AI".
* Check you see the subscription error.
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/2419
=> check for woo seo before subscription error

packages/js/src/ai-generator/components/feature-error.js, packages/js/src/ai-generator/components/sparks-limit-notification.js
*
* Updates the Spark limit notification upsell message and button label on a WooCommerce product.
*
* Install woocommerce and create a product.
* Edit a product and use the ai generator ( You can use this patch on local environment [notification-spark-limit.patch](https://github.com/user-attachments/files/21311436/notification-spark-limit.patch)).
* Once you reach the limit, check you see the limit notification with the message and upsell button for Yoast Woocommerce SEO.
* Repeat the steps for regular post and check you see the Premium message and button upsell.
* …
=> 2421 major on a toast for product unlock with woo seo should be displayed

packages/js/src/ai-generator/initialize/filter-focus-keyphrase-errors.js
We want to check the error message before asking for consent.
*
* Show error message for the missing focus keyphrase before giving consent for the ai feature. 
* We decided to do that before consent because we have the upsell before the consent and we want to reduce steps between the upsell modal appears and the ai generator modal.
* Make sure you revoked consent or didn't grant it for the ai feature.
* Edit a post without focus keyphrase.
* Click on "Use AI" button.
* Check you the focus is on the focus keyphrase field and there is an error message:
* …
=> Show focus keyphrase error message without ai consent

packages/js/src/ai-generator/components/app.js
*
* Adjust spinner trigger on "Use AI" to avoid loading state on both title and description buttons.  
*
* Edit a post with focus keyphrase and ai consent.
* Click on "Use AI" button for the title and check you get a spinner only on the button you clicked.
* Close the ai generator modal.
* Click on "Use AI" button for the description and check you get a spinner only on the button you clicked.
*
*
Fixes [[Trivial]25.6: Spinner is on both Use AI btns](https://github.com/Yoast/plugins-automated-testing/issues/2422)
=> Fix spinner on "Use AI" button that is being triggered on buttons there were no clicked

packages/js/src/ai-generator/components/upsell-modal-content.js, packages/js/src/ai-generator/hooks/use-upsell-props.js, packages/js/src/ai-optimizer/components/modal-content.js, packages/js/src/shared-admin/components/ai-optimize-upsell.js
*
* Removes the bundle upsell for Yoast SEO premium and Yoast WooCommerce SEO.
* Make sure you have no premium or woo seo activated.
* Make sure you didn't click on the upsell button before and you have no subscriptions active ( you can use this patch on local environment, [9-sparks-no-subscription-unseen-upsell.patch](https://github.com/user-attachments/files/21342595/9-sparks-no-subscription-unseen-upsell.patch)). 
* Note: if you want to use the actual plugins / licenses you should update the code in this patch and rebuild JS
* Edit a product and click on "Use AI".
* Check you get an upsell for the Yoast WooCommerce SEO only:
* The upsell button should mention Yoast …
=> Remove bundle related props from a upsell

src/llms-txt/user-interface/enable-llms-txt-option-watcher.php, tests/Unit/Llms_Txt/User_Interface/Enable_Llms_Txt_Option_Watcher/Abstract_Enable_Llms_Txt_Option_Watcher_Test.php, tests/Unit/Llms_Txt/User_Interface/Enable_Llms_Txt_Option_Watcher/Check_Llms_Txt_Selection_Test.php, tests/Unit/Llms_Txt/User_Interface/Enable_Llms_Txt_Option_Watcher/Check_Toggle_Llms_Txt_Test.php
> [!NOTE]  
> Even though the PR currently does what's expected, it has not been thoroughly tested or finalized by its author. Consider that, if it's to be resumed.
*
* Re-generates the llms.txt file immediately when there's any change in the selection of the pages to be included.
**About the way we detect changes in the llms.txt settings**:
* We're going to check the following sub-settings of the `wpseo_llmstxt` option with a watcher and trigger a re-generation of the file when there's a change in either:
* `llms_txt_selection_mode`
* `about_us_page`
* `contact_page`
* `terms_page`
* `privacy_policy_page`
* `shop_page`
* `other_included_pages`
* the `other_included_pages` one is an array with maximum 100 elements. this means …
=> Re-generates the llms.txt file immediately when there's any change in the selection of the pages to be included

packages/js/src/ai-generator/initialize/initialize-prompt-content.js
*
* Fixes missing prompt content for the AI generator.
* Changing the `createWatcher` to an import so it doesn't rely on the `editor-modules`, which is API for our add-ons -- not free itself.
* Have only free active ( premium should be deactivated )
* Edit a post and use the AI generator free sparks.
* Open the console and execute:
```js 
wp.data.select("yoast-seo/ai-generator").selectPromptContent()
```
* Check you are getting the post content and not a single dot "."
* In the network tab of your console, find the `get_suggestions/` request
* Verify the payload includes `prompt_content` with (the first paragraphs) of your content and not a single dot "."
QA can test this …
=> import the createWatcher from the helpers

css/src/redirects.css, src/integrations/admin/first-time-configuration-notice-integration.php, src/integrations/admin/redirects-page-integration.php, tests/Unit/Integrations/Admin/Redirects_Page_Integration_Test.php
Fixed styles for redirect page
*
*
Fixes #
=> fix: styles for redirects page

packages/js/src/ai-generator/components/errors/subscription-error.js
*
* Removes the Yoast WooCommerce SEO and Premium bundle upsell link from the `AI Generate` subscription error modal.
*
* Make sure you don't have premium and woo seo license.
* Install and activate Woocommerce.
* Install and activate Woo seo and premium.
* Edit a product and click on the "Use AI" button. 
* Check you get the error message with an upsell link only for woo SEO.
* Enable subscription for Woo SEO.
* Click on Use AI, and check you are getting an subscription error for Premium.
*
*
Fixes [Remove bundle link from AI subscription …
=> remove budle upsell link from the subscription error

.github/workflows/finish-coveralls.yml, .github/workflows/test.yml, tests/Unit/Inc/Addon_Manager_Test.php, tests/Unit/bootstrap.php, wp-seo-main.php, wp-seo.php
* Template PR: https://github.com/Yoast/wordpress-seo/pull/22035
* Sets the minimum supported WordPress version to 6.7.
*
*
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/698
=> Set the minimum supported WordPress version to 6.7

packages/js/src/redirects/components/route-layout.js
*
* Restores the CTB id to the redirects upsell button.
*
* Make sure Yoast SEO premium is deactivated or not installed.
* Go to Yoast SEO -> Redirects
* Inspect the Upsell button and check it has the attributes `data-action` and `data-ctb-id` with the following values.
```js
data-action="load-nfd-ctb"
data-ctb-id="f6a84663-465f-4cb5-8ba5-f7a6d72224b2"
```
*
*
Fixes https://github.com/Yoast/reserved-tasks/issues/721
=> Restores ctb id to the redirects upsell button

admin/class-premium-upsell-admin-block.php, admin/menu/class-base-menu.php, css/src/admin-global.css, css/src/black-friday-banner.css, css/src/yst_plugin_tools.css, inc/class-wpseo-admin-bar-menu.php, packages/js/src/components/BlackFridayPromotion.js, packages/js/src/components/UpsellBox.js, packages/js/src/helpers/shouldShowWebinarPromotionNotification.js, packages/js/src/shared-admin/components/premium-upsell-card.js, packages/js/src/shared-admin/components/premium-upsell-list.js, packages/tailwindcss-preset/index.js, src/general/user-interface/general-page-integration.php, src/integrations/alerts/black-friday-promotion-notification.php, src/integrations/settings-integration.php, src/integrations/support-integration.php, src/presenters/admin/sidebar-presenter.php, src/promotions/domain/black-friday-promotion.php, tests/Unit/General/User_Interface/General_Page_Integration_Test.php, tests/Unit/Integrations/Support_Integration_Test.php
* We want to update the styling for our ads.
* Updates black friday ad styling.
* Just like in https://github.com/Yoast/wordpress-seo/pull/22488 there are tiny differences between the tools page and the other pages.
* Make sure you don't have Premium nor WooCommerce installed
* Go to /src/promotions/domain/black-friday-promotion.php and make sure the bf promotion is active by changing line 16 to:
`new Time_Interval( \gmmktime( 10, 00, 00, 11, 28, 2024 ), \gmmktime( 10, 00, 00, 12, 3, 2026 ) )`
* Visit the following pages:
* `General`
* `Settings`
* `Tools`
* `Support` ( sidebar ad only) 
and verify the footer and sidebar ads are about Yoast SEO Premium and follow the …
=> Update styling for the black friday ads.

css/src/admin-global.css, inc/class-addon-manager.php
*
* Changes the copy for updating plugin notification when there is no subscription and adds a badge for the Black Friday campaign.
*
* Got to the plugins page.
* Install Yoast SEO premium with an old version.
* Check the copy of the update notification is:
* Go to /src/promotions/domain/black-friday-promotion.php and make sure the bf promotion is active by changing line 16 to:  `new Time_Interval( \gmmktime( 10, 00, 00, 11, 28, 2024 ), \gmmktime( 10, 00, 00, 12, 3, 2026 ) )`
* Refresh the plugin page and check the notification has the BF badge:
* …
=> fix notification copy and BF badge

admin/class-admin-asset-manager.php, css/src/adminbar.css, inc/class-wpseo-admin-bar-menu.php, src/plans/user-interface/upgrade-sidebar-menu-integration.php
* We want to add an upgrade button to the sidebar and the admin menu.
* Adds an `upgrade` button to the sidebar and admin menu.
* The sidebar button works with a link to a `page` and the page is just a redirect to the correct yoa.st link.
* Make sure you only have free enabled and not `WooCommerce`(woo) and `Yoast SEO premium`(premium)
* Make sure the sidebar and top bar buttons looks like the ones in the design. For the top bar one make sure the url is:
`admin-bar-get-premium` and for the sidebar one turn on `preserve log` in the dev tools from chrome and make sure the redirect url is: `https://yoa.st/wordpress-menu-upgrade-premium`
* Enable woo and make sure the links …
=> Add upgrade buttons

inc/class-wpseo-admin-bar-menu.php, src/plans/user-interface/upgrade-sidebar-menu-integration.php
* We want to update de button text of the upgrade button for a sale.
* Updates the button label when the Black Friday sale is on.
*
* Make sure the black friday sale is not running and you don't have premium enabled. Make sure that in the WP menu sidebar we render a `upgrade` button in our menu
* Make sure that in our topbar we also render a `upgrade` button.
* Enable the sale and make sure the label changes to `30% off - BF Sale` like in the design.
*
*
Fixes #
=> Render black friday sale label.

packages/js/src/settings/app.js
* The settings dedicated to the `llms.txt` file are in a sub-section of the Settings' `Advanced` section, which is collapsed by default. This means that if the user is directed to the `llms.txt` sub-section they cannot see in which section they are (provided they didn't previously open the `Advanced` section).
* Opens the `Advanced` Settings' section when clicking the `Customize llms.txt file` button.
* 
* Visit `Yoast SEO` -> `Settings`
* Verify the `Advanced` section is collapsed
* In `Site features` enable` the `llms.txt` feature
* Click on `Customize llms.txt file`
* Verify the `Advanced` section is now open …
=> Automatically open the `Advanced` Settings section when visiting `llms.txt` feature

src/context/meta-tags-context.php
Allow changing the main image ID through a filter.
I have a client project which has custom featured images for taxonomies, many other tools, like WooCommerce also do this similarly.
This PR allows me to change the schema output correctly without doing more skechy changes to the full schema output using the `wpseo_schema_webpage` filter.
* Allow changing the main image ID through a filter `wpseo_schema_main_image_id` props: @JoryHogeveen
* I based my changes on other filters already available in this class.
* Simply add a filter and change the main image ID to see changed in schema validators.
Filter example for when the `category` taxonomy has a custom image field named …
=> New filter: `wpseo_schema_main_image_id`

packages/js/package.json, yarn.lock
* This PR is part of https://github.com/Yoast/wordpress-seo-premium/issues/4739
* [wordpress-seo non-user-facing] Updates the `@yoast/ai-frontend` package to the latest version in `package.json` to incorporate the latest improvements and fixes in the `@yoast/ai-frontend` library.
* Fixes a bug where a string in the AI Generate usage counter tooltip was missing in RTL languages.
*
* Set the site language to Arabic
> [!IMPORTANT]
> Please run the testing steps below in RTL and LTR language
<details><summary>Example of usage counter</summary>
</details> 
* Create a post in Block editor/Classic editor/Elementor
* Set a focus keyphrase
* Go to …
=> Update @yoast/ai-frontend dependency to version 0.19.0

src/conditionals/google-site-kit-feature-conditional.php
* The implementation adheres to what has been talked about [here](https://yoast.slack.com/archives/C08LLAMGF1C/p1756904080250839?thread_ts=1756715427.809609&cid=C08LLAMGF1C).
* Allows Site Kit to control the Site Kit feature flag remotely.
*
* Since we don't have a way to use Site Kit's services related to remote feature flag, we will edit the relevant DB option to do the same thing. We could have waited to get the test plugin (mentioned [here](https://yoast.slack.com/archives/C08LLAMGF1C/p1756908187825479?thread_ts=1756715427.809609&cid=C08LLAMGF1C)) from Site Kit, but for velocity purposes, we'll do the below until we get it.
* Make sure you don't have the Site Kit …
=> Use remote feature flag from Site Kit

src/builders/indexable-link-builder.php, tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Delete_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Patch_Seo_Links_Test.php, tests/Unit/Builders/Indexable_Link_Builder/Update_Incoming_Links_For_Related_Test.php
* We need to sent a parameter to the action.
* Adds a parameter to the `wpseo_related_indexables_incoming_links_updated` action.
*
* Test instructions are in https://github.com/Yoast/wordpress-seo-premium/pull/4773
*
*
Fixes #
=> Add parameter to action.

packages/js/src/introductions/components/modals/ai-brand-insights-post-launch.js, packages/js/src/introductions/initialize.js, src/introductions/application/ai-brand-insights-post-launch.php, src/introductions/application/ai-brand-insights-pre-launch.php, tests/Unit/Introductions/Application/AI_Brand_Insights_Post_Launch_Test.php
* N/A
* Adds the post-launch introduction about Yoast AI Brand Insights and removes the pre-launch one. 
* N/A
* Use [this](https://www.figma.com/design/OHKjiKm5cSAS7mzI4hK8dd/Introduction?node-id=1-2331&t=MQ5EbyIPwDdC5W5N-4) Figma design as reference
* Start with just Yoast SEO activated
* With a MySQL client locate the `wp_usermeta` table
* Find the row where `meta_key` = `_yoast_wpseo_introductions` and delete the content of the `meta_value` column: this would **reset all the introductions** you have previously seen
* Visit a Yoast SEO page
* Confirm you see the introduction as in the design for Free
* Confirm you don't see the pre-launch introduction ( Figma design …
=> Add post launch introduction

admin/metabox/class-metabox.php, admin/taxonomy/class-taxonomy.php, src/integrations/third-party/elementor.php
It is a dependency of the analysis package
*
* Removes duplicate enqueue of language script since it's a dependency of the analysis package.
* The language script is a dependency of the `analysis-package` so no need to enqueue it separately. This was done in [Add guard to the loading scripts for features that are disabled in free](https://github.com/Yoast/reserved-tasks/issues/568) as an attempt to prevent the enqueueing of the language script, however it is not possible since it's a dependency of the `analysis-package` so it is already being added.
* Make sure site language is English.
* Edit a post in classic/block-editor/elementor and edit a term. 
* Inspect the page …
=> Removes duplicate enqueue of language script since it's a dependency of the analysis package

packages/js/src/components/contentAnalysis/PremiumSeoAnalysisUpsellAd.js, packages/js/src/components/contentAnalysis/WooSeoAnalysisUpsellAd.js, packages/js/src/components/modals/UpsellModal.js
*
* Fixes an unreleased bug where WooCommerce SEO ad would be visible when not on a product page. 
*
* Edit a post and click on the SEO analysis tab
* Check you see the Premium ad: 
* <img width="611" height="208" alt="Screenshot 2025-09-26 at 16 00 29" src="https://github.com/user-attachments/assets/f44e4f4c-5e7d-4dca-b743-d6b1a1965225" />
* Edit a product and click on the SEO analysis tab
* Check you see the woocommerce seo ad
* Activate Woo SEO analysis and check you see the woocommerce SEO ad has the premium labeled button (Unlock with Premium).
* Check the upsell modals theme is blue with a cart only on a product, there are 3 modal to test, you …
=> fix woo ads on products only

src/integrations/admin/redirections-tools-page.php
* Follows up https://github.com/Yoast/wordpress-seo/pull/22606, to name the new subemnu item in a more clear way, mentioning Yoast.
* Rename new submenu item for redirects, to `Yoast redirects`.
*
* Confirm that the new submenu item under Tools, is named `Yoast redirects`.
*
Fixes #
=> Rename new submenu item for redirects

composer.json, packages/js/src/support/app.js, src/integrations/admin/helpscout-beacon.php, src/integrations/support-integration.php, tests/Unit/Integrations/Support_Integration_Test.php, tests/Unit/Main_Test.php
We want to adapt the behavior of the `Contact our support team` button in the `Support` page to our new Premium and WooCommerce SEO subscription plans.
Currently, only users who have Yoast SEO Premium **installed** can access the Helpscout Beacon through the button, which would have a specific `beacon_id` for Premium.
In light of our switch to plan subscription, we want to:
1. activate the button when the user has one of the two subscription plans active
2. set the `beacon_id` value according to the user's plan: in case the Premium plan is active, we are going to use the Premium `beacon_id`. Coversely, if the WooCommerce SEO plan is active, we will use the WooCommerce SEO `beacon_id`
⚠️ This PR must be tested together with its relative [Premium one …
=> Change helpscout beacon behavior
