- admin/class-admin-utils.php
- admin/class-plugin-availability.php
- admin/class-suggested-plugins.php
- tests/admin/test-class-plugin-availability.php
- tests/admin/test-class-plugin-compatibility.php
- tests/doubles/class-wpseo-plugin-availability-double.php
* Changes how install links are generated for Suggested Plugins by checking whether or not the suggestion is a Premium product or not.
* Install Yoast SEO (`trunk`)
* Go to YoastSEO -> Dashboard and see that there's a notification suggesting you install Yoast WooCommerce SEO (the name should be a link that is broken)
* Go through the same steps and determine that the name is no longer a link.
Fixes #8303
> Fixed issue where links to premium plugins were being created

- admin/google_search_console/views/gsc-redirect-nopremium.php
> CS/XSS: always escape output - 4

- admin/class-social-facebook-form.php
> CS/XSS: always escape output - 2

- js/src/analysis/PostDataCollector.js
Gutenberg moved metaboxes from iframes to the main window. This broke our Gutenberg support.
> Fix the rudimentary Gutenberg support

- admin/google_search_console/views/gsc-display.php
> CS/XSS: always escape output - 3

- admin/pages/network.php
> CS/XSS: always escape output - 5

- admin/pages/tools.php
> CS/XSS: always escape output - 6

- admin/class-meta-columns.php
- admin/config-ui/factories/class-factory-post-type.php
- admin/links/class-link-watcher.php
- admin/metabox/class-metabox.php
- admin/views/tabs/advanced/breadcrumbs.php
- admin/views/tabs/metas/post-types.php
- admin/views/tabs/sitemaps/post-types.php
- inc/options/class-wpseo-option-internallinks.php
- inc/options/class-wpseo-option-titles.php
- inc/options/class-wpseo-option-xml.php
- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-sitemaps.php
- tests/test-class-wpseo-metabox.php
* Added code documentation about choices on not to use the helper function for now.
* Add the following code to your WordPress installation:
```
add_filter( 'wpseo_accessible_post_types', function( $post_types ) {
return array();
});
```
* No post/page overview should have the Yoast Columns
* No post/page overview should have the Yoast Metabox
Fixes #8413
> Hide elements according to accessible post type filter

- admin/views/tabs/advanced/breadcrumbs.php
> CS/XSS: always escape output - 7

- admin/views/tabs/advanced/permalinks.php
> CS/XSS: always escape output - 8

- admin/views/tabs/dashboard/general.php
> CS/XSS: always escape output - 9

- admin/views/tabs/dashboard/security.php
> CS/XSS: always escape output - 10

- admin/views/tabs/dashboard/webmaster-tools.php
> CS/XSS: always escape output - 11

- admin/views/tabs/metas/post-types.php
> CS/XSS: always escape output - 15

- admin/class-premium-upsell-admin-block.php
> CS/XSS: always escape output /escape complete string - 3

- admin/class-yoast-form.php
> CS/XSS: always escape output /escape complete string - 4

- admin/google_search_console/class-gsc-modal.php
> CS/XSS: always escape output /escape complete string - 5

- admin/metabox/class-metabox-form-tab.php
- admin/metabox/class-metabox.php
> CS/XSS: always escape output /escape complete string - 6

- admin/metabox/class-metabox-tab-section.php
> CS/XSS: always escape output /escape complete string - 7

- admin/views/tabs/metas/post-types.php
> CS/XSS: always escape output /escape complete string - 8

- admin/views/tabs/metas/archives.php
> CS/XSS: always escape output - 12

- admin/views/tabs/metas/home.php
> CS/XSS: always escape output - 14

- admin/views/tabs/sitemaps/exclude-post.php
> CS/XSS: always escape output - 16

- admin/views/tabs/sitemaps/user-sitemap.php
> CS/XSS: always escape output - 17

- admin/views/tabs/social/facebook.php
> CS/XSS: always escape output - 18

- admin/views/tabs/social/twitterbox.php
> CS/XSS: always escape output - 21

- admin/views/about.php
> CS/XSS: always escape output - 22

- admin/class-option-tabs-formatter.php
> CS/XSS: always escape output /escape complete string - 2

- admin/views/tool-import-export.php
> CS/XSS: always escape output /escape complete string - 9

- admin/views/tabs/dashboard/knowledge-graph.php
Added link to the Google’s Knowledge Graph article.
* Adds a link to the Google Knowledge Graph article on Yoast.com.
Go to the `/wp-admin/admin.php?page=wpseo_dashboard#top#knowledge-graph` page and verify the link is working and brings you to Yoast.com.
> Link to Google's Knowledge Graph.

- admin/pages/metas.php
_N/A_
* Code style compliance. Functions should be prefixed with a plugin specific prefix.
This is an internal function defined within a view, so the impact on userland code hooking into WPSEO should be negligible.
Yes, please!
> CS: rename function

- admin/class-bulk-editor-list-table.php
> CS/XSS: always escape output /escape complete string - 1

- admin/views/partial-alerts-template.php
> CS/XSS: always escape output /escape complete string - 10

- admin/views/js-templates-primary-term.php
> CS/XSS: always escape output - 23

- admin/views/tool-bulk-editor.php
_N/A_
* Code style compliance. Functions should be prefixed with a plugin specific prefix.
These are two internal functions defined within a view, so the impact on userland code hooking into WPSEO should be negligible.
Yes, please!
> CS: rename two functions

- frontend/class-frontend-woocommerce-shop-page.php
- frontend/class-frontend.php
- frontend/class-primary-category.php
- tests/frontend/test-class-frontend-woocommerce-shop-page.php
This moves the code supplied by @WPprodigy to a separate class and adds unit tests to verify behaviour.
* Add support for custom page titles and meta descriptions on the WooCommerce shop page. Props [Caleb Burks](https://github.com/WPprodigy).
* Injected Frontend for testing purposes.
* Created protected helper function to make testing easier.
* Install WooCommerce and assign a page as the shop page. Edit the shop page's title and meta description, then view shop page.
Fixes https://github.com/Yoast/wordpress-seo/issues/4362
Related https://github.com/Yoast/wordpress-seo/pull/8409
> Use WooCommerce Shop Page SEO data

- frontend/class-frontend.php
* Add support for custom page titles and meta descriptions on the WC shop page.
Only added support for title and description, rather than allthethings. I see there is a plugin specifically for WC enhancements - and this issue was originally moved there, but this feels like something that the core version could support imo. Talked a bit with @jdevalk at WCUS about this.
For background: WooCommerce doesn't have a traditional post archive setup - the site assigns a normal WP page as the shop page. This works similar to how the blog post index system works. As a result, the user can edit the shop page like any other page and do things like change meta descriptions there. However, this page ID needs to be "mapped" for when the actual …
> Use WC shop page title & desc

- inc/class-post-type.php
- tests/inc/test-class-post-type.php
* [bugfix] Remove the `noindex` post-types from the list of relevant post types to show the Yoast SEO Metabox on.
* Remove the filter from the code.
* Configure a post type to have robots `noindex` in the Titles & Metas menu
Fixes https://github.com/Yoast/wordpress-seo/issues/8445
> Remove noindex post type filter

- admin/class-admin-asset-manager.php
* [bugfix] Registers an `Intl` polyfill to make sure the React modules work in older browsers.
* Use a CDN based polyfill solution
* This polyfill will only return the code that is specifically needed for the requesting browser
* Use IE 10 or lower (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
* Go to a page with the Yoast SEO Metabox
To connect to another VirtualBox machine, configure the network to be attached via `NAT`
Add the `local.wordpress.test` to the `C:\Windows\System32\drivers\etc\hosts` file with the IP of the virtual machine running the WordPress installation.
Fixes https://github.com/Yoast/wordpress-seo/issues/8435
> Load Intl polyfill

- admin/formatter/class-metabox-formatter.php
- js/src/analysis/PostDataCollector.js
- js/src/components/contentAnalysis/ReadabilityAnalysis.js
- js/src/components/contentAnalysis/Results.js
- js/src/components/contentAnalysis/mapResults.js
- js/src/edit.js
- js/src/redux/actions/markerButtons.js
- js/src/redux/reducers/markerButtons.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-tinymce.js
* Disables the mark buttons of the content analysis when in text view, and hides them when there is no TinyMCE or `has_marks` is false.
- Check out this branch. 
- Link the `stories/8442-disabled-marking-buttons` branch of `yoast-components` using `yarn link`.
- `composer install`, `yarn install`, `grunt build:js`.
- Write a text that triggers at least one mark button. For example, use `because` in your text to trigger the transition word button.
The buttons should be enabled and have the corresponding tooltip when hovered.
The buttons should be disabled and have the corresponding tooltip when hovered.
This happens, for example, when a page builder has disabled marks. On line 70 of …
> Add functionality to disable and hide marker buttons and add tooltips

- css/src/metabox.scss
* Allow tooltips to overflow the metabox
* Replaces an `overflow: hidden` introduced in https://github.com/Yoast/wordpress-seo/commit/9fbc20062429e29f368c183918cd88f99a5c2c88 with an `after` pseudo element clearfix.
- enable Yoast Seo Video
- in the metabox, switch to the video tab (in a post with no videos so the tab content is very short)
- verify at the bottom fo the metabox there's no visual breakage
with the fix:
without the fix:
Recommendation: avoid to use `overflow: hidden` to contain floated elements. While handy, it cuts-off anything from the element it's applied to, e.g. tooltips, focus styles.
Fixes #8500
> Replace overflow hidden with after pseudo element clearing.

- package.json
- yarn.lock
Bump YoastSEO.js to 1.28.
The changes from YoastSEO.js are already reflected in the changelog.
> YoastSEO.js 1.28

- .travis.yml
- tests/notifications/test-class-yoast-notification-center.php
* Updated the travis matrix by replacing php 7.1 for 7.2 and the WordPress version (4.8) has been replaced for 4.9.
* See if travis passes.
Fixes #8415
> Update travis matrix by adding php 7.2

- admin/class-admin.php
- admin/class-meta-table-accessible.php
- admin/links/class-link-columns.php
- admin/links/class-link-reindex-post-service.php
- admin/links/class-link-table-accessible.php
- admin/links/class-link-watcher.php
- tests/admin/links/test-class-link-columns-count.php
- tests/admin/links/test-class-link-columns.php
- tests/admin/links/test-class-link-content-processor.php
- tests/admin/links/test-class-link-storage.php
- tests/admin/links/test-class-link-watcher.php
* Avoids calling SHOW TABLES queries to check if link and meta tables are present.
* Using a transient name which reflects the value that it holds.
* On each post overview page, two requests are being done to verify the tables are accessible.
* _Use the Query Monitor plugin to get insights in the queries that have been executed_
* On this PR, this only has to be done initially (if the tables exist and are accessible).
* After that only transient requests are needed `wpseo_link_table_inaccessible` & `wpseo_meta_table_inaccessible`.
Fixes #8190
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/1477
> Improve table accessibility checks

- admin/capabilities/class-capability-manager-vip.php
* Fixes VIP compatibility for maintaining role capabilities.
Both WPSEO_Capability_Manager_VIP::add() and WPSEO_Capability_Manager_VIP::remove() call wpcom_vip_remove_role_caps() passing an array of arrays as the second parameter, but this function expects an one-dimensional array of capabilities. This resulted in the following PHP warning when I tried to update WordPress SEO on a VIP Go site:
`Warning: Illegal offset type in wp-content/mu-plugins/vip-helpers/vip-roles.php:139`
Call stack:
```
wpcom_vip_add_role_caps()
wp-content/plugins/wordpress-seo/admin/capabilities/class-capability-manager-vip.php:22
WPSEO_Capability_Manager_VIP->add()
wp-content/plugins/wordpress-seo/inc/class-upgrade.php:401
WPSEO_Upgrade->upgrade_55() …
```
> Pass right parameter when calling wpcom_vip_remove_role_caps()

- grunt/config/eslint.js
- js/src/wp-seo-quick-edit-handler.js
- js/src/wp-seo-recalculate.js
- js/src/wp-seo-replacevar-plugin.js
- js/src/wp-seo-shortcode-plugin.js
In the releasebranch for 6.0 the amount of maxWarnings config has been lowered. But it seems the there are no warnings being fixed. This is resulting in failing builds on travis. The config value is 106 and the amount of found warnings is 108. 
I've chosen to fix some warnings, instead of setting the config value to 108. If I've done my job correctly Travis will be happy.
> Fixes some eslint warnings

- inc/sitemaps/class-sitemap-image-parser.php
* Remove unsupported arguments in PHP 5.2 for a `array_unique` call in the Term image sitemap.
* Create a post with images inside
* Check the sitemap code to see the list of images being present as before
Fixes #8529
> Remove unsupported argument in PHP 5.2

- admin/class-yoast-notification-center.php
These still give the same results after testing this.
* Remove PHP 5.3 arguments on a `json_encode` call in the notification functionality.
* This piece of code is triggered on the `Quick edit` of a post
* Change the slug of a post and save in the quick edit
* A notification should be shown about using premium to create redirects
Fixes #8527
> Remove PHP 5.2 incompatible arguments

- admin/class-admin-asset-manager.php
- inc/language-utils.php
- tests/test-class-wpseo-utils.php
* extract language correctly from locales without country (et, fi), also support 3-letter language codes (rhg)
* use same WPSEO_Utils methods as in scripts_to_be_registered, use user's locale if available (polyfills are related to user's browser)
* fix WPSEO_Language_Utils to split locale when _ is present, else presume locale is language (unless empty)
* set WP install to Estonian (et), Finnish (fi) before applying fix
* you get error :  Undefined offset: 1 in ... /wordpress-seo/admin/class-admin-asset-manager.php
* fix removes error, when inspecting $language variable in debugger it contains correct code
* tested with site running Polylang, worked correctly with et (language …
> fix for #8473 - warning message with language-only locales (et, fi)

- admin/class-option-tab.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
- admin/views/tool-file-editor.php
_Allow more strings to be localized_
These three strings are intended to be translatable labels for the tab, but weren't translatable in these instances.
I've included a minor documentation improvement to clarify this for future usage.
_N/A_
> CS/I18n: make three strings translatable

- inc/class-wpseo-replace-vars.php
_N/A_
The `WPSEO_Utils::standardize_whitespace()` method is called on the line above and already uses `trim()` on the string.
_N/A_
> CS/QA: Remove superfluous function call

- admin/class-meta-columns.php
_N/A_
This method is called four times from within this same file and always passed the output of a call to the WP `selected()` function.
This PR fixes the default parameter value as well as the documentation to be in line with the reality.
_N/A_
> CS/QA: correct method parameter type & default value

- admin/class-help-center.php
* Fixes a bug where the user locale is not used for the Help Center
* Modify your user language to be different from the global site language
> Use user locale for Help Center

- admin/class-social-admin.php
* Makes the upgrade notice on the social media settings tab in the metabox translatable.
* Checkout this branch. Go to a post edit page and open the social media settings. See a notice that will be the same as it was on trunk.
> Make string translatable

- webpack/webpack.config.default.js
* Changes the global `webpackJsonp` variable to `yoastWebpackJsonp` to avoid plugin conflicts.
* Named the new `webpackJsonp` to `yoastWebpackJsonp`
* Make sure `webpackJsonp` doesn't exist anymore in the global namespace and `yoastWebpackJsonp` does.
Fixes #
> Add jsonpFunction to webpack configuration

- css/src/help-center-metabox.scss
* Fixes the styling of the help button on the Google Search Console page.
* I've chosen for wrapping the CSS selector, because the meta box file is required for the help icons. We might consider putting the styling of those buttons in a separate file.
* Checkout trunk.
* View the metabox page on a post edit and the metabox on a taxonomy (category for example) edit page. 
* Go the the Google Search console page and see the button having the same styling as the buttons you've seen on the previous step.
* Now visit another Yoast SEO admin page like the dashboard and see another styling being visible.
* Checkout this branch and do a `grunt build:css` 
* Follow the same steps and see the …
> Wrap the CSS with a selector that is present on metabox containing page.

- admin/pages/dashboard.php
- admin/pages/tools.php
- admin/views/tabs/tool/import-seo.php
- admin/views/tabs/tool/wpseo-export.php
- admin/views/tabs/tool/wpseo-import.php
** Variables should be escaped based on the context in which they are used.
In each of these cases, the _wrong_ escaping function was used for the context.
> CS (non-)compliance/XSS: use the correct escaping function

- admin/class-social-facebook-form.php
** Escape the url when the context in which it will be used is clear, i.e. when it's added to an HTML string, not before.
> CS/QA: escape a URL at the correct place

- admin/views/tabs/sitemaps/general.php
** Includes moving some HTML out of the translatable string.
> CS/XSS: always escape output & move HTML out of translatable string - 2

- admin/views/tabs/advanced/permalinks.php
** Includes moving some HTML out of the translatable string.
> CS/XSS: always escape output & move HTML out of translatable string - 1

- admin/views/user-profile.php
Test this by opening the relevant …
> CS/XSS: always escape output / embedded php - 1

- admin/views/tabs/dashboard/dashboard.php
Test this by opening the relevant …
> CS/XSS: always escape output / embedded php - 3

- admin/views/about.php
Test this by opening the relevant …
> CS/XSS: always escape output / embedded php - 4

- admin/views/tabs/tool/import-seo.php
In this case, creating the text first and escaping in a single-line embedded PHP statement is not an option as the replacement variables contain HTML.
As this is a `<p>` tag, I don't expect any layout issues, but careful scrutiny of the output is recommended.
Test this by …
> CS/XSS: always escape output / embedded php - 5

- admin/views/licenses.php
In the second case, creating the text first and escaping in a single-line …
> CS/XSS: always escape output / embedded php - 6

- admin/views/form/fieldset.php
When a variable is used as part of an attribute or url, it is always better to escape the whole string as that way a potential escape character just before the variable or at the end of the variable value will be correctly escaped.
Test this by opening a relevant admin page in a browser and checking that the page layout has not been affected by this change.
> CS/XSS: always escape output /escape complete string - 12

- inc/sitemaps/class-sitemap-image-parser.php
- tests/doubles/class-sitemap-image-parser-double.php
- tests/sitemaps/test-class-wpseo-sitemap-image-parser.php
* Fixes a bug where sitemaps could not be generated when there are galleries in the content.
* See https://github.com/Yoast/wordpress-seo/pull/8636
* See https://github.com/Yoast/wordpress-seo/pull/8636
Fixes #8634
> Resolve sitemap fatal error

- admin/class-option-tabs-formatter.php
** I've verified all instantiations of the `WPSEO_Option_Tab` class and none of the labels contain HTML, so escaping this output with `esc_html()` is the most appropriate course of action and should be safe.
Test this by opening the relevant admin page in a browser and checking that the page layout has not been …
> CS/XSS: always escape output - 31

- admin/views/about.php
** These variables come from the arrays defined lower down in the same file. None of the array values contain HTML, so this can be safely escaped like this.
> CS/XSS: always escape output - 29

- admin/class-meta-columns.php
** While this function does not echo out the HTML, it is clearly preparing it for output and it's easier to escape when the HTML is being build, then after.
> CS/XSS: always escape output - 28

- admin/class-bulk-editor-list-table.php
** The `$options` variable is echo-ed out only a few lines later, so this HTML build up should be escaped.
> CS/XSS: always escape output - 26

- admin/class-bulk-description-editor-list-table.php
** While this function does not echo out the HTML, it is clearly preparing it for output and it's easier to escape when the HTML is being build, then after.
> CS/XSS: always escape output - 25

- admin/views/partial-alerts-template.php
N.B.: see the commit notes for the individual commits in this PR for more extensive information.
> CS/XSS: always escape output - 24

- admin/views/tabs/dashboard/general.php
** While it may look over the top, this is the correct way of escaping an arbitrary string passed to an `onclick` HTML attribute.
Test this by opening a relevant admin page in a browser and checking that things still work as expected.
> CS/XSS: always escape JS output - 3

- admin/views/tabs/tool/wpseo-export.php
Test this by opening the relevant …
> CS/XSS: always escape output / embedded php - 2

- admin/views/tool-bulk-editor.php
** Variables echo-ed out into an inline javascript block should be escaped using `wp_json_encode()`
Test this by opening a relevant admin page in a browser and checking that things still work as expected.
> CS/XSS: always escape JS output - 1

- frontend/class-frontend.php
- tests/test-class-wpseo-frontend.php
** The `title()` method retrieves the pre-escaped title from the `generate_title()` method. This pre-escaping is incorrect, however as not all theme authors escape correctly and the `esc_html()` method protects against double escaping, I think it's prudent to leave the pre-escaping in place.
https://github.com/Yoast/wordpress-seo/blob/c12c0926044dfc32dded185028637b8945e6fae6/frontend/class-frontend.php#L577
All the same, it makes sense to escape the title when it's being force …
> CS/XSS: always escape output - 32

- admin/tracking/class-tracking-plugin-data.php
- frontend/class-breadcrumbs.php
- frontend/class-frontend.php
- frontend/class-opengraph.php
- frontend/class-twitter.php
- inc/class-wpseo-replace-vars.php
- inc/class-wpseo-utils.php
_N/A_
The `wp_strip_all_tags()` function is more comprehensive than the PHP native `strip_tags()` function.
The advantage of `wp_strip_all_tags()` over `strip_tags()` is that it does not leave the content of removed `<script>` and `<style>` tags behind.
> This differs from `strip_tags()` because it removes the contents of the `<script>` and `<style>` tags. E.g. `strip_tags( '<script>something</script>' )` will return ‘something’. `wp_strip_all_tags()` will return ”
It can also remove superfluous whitespace within the string which may be left behind after removing the tags. For this, the second parameter `$remove_breaks` needs to be passed and set to `true`.
For those function calls where the original input is always expected to …
> CS/QA: use `wp_strip_all_tags()`

- admin/views/tool-import-export.php
** The labels are defined in the array just above the changed line and do not contain HTML, so escaping them with `esc_html()`.
> CS/XSS: always escape output - 33

- .travis.yml
- composer.json
* _N/A_
Validate the composer.json file on highest/lowest Composer compatible PHP build.
Ref: https://getcomposer.org/doc/03-cli.md#validate
Also updates the license identifier in the `composer.json` file to `LGPL-2.0-or-later` (see more about this below).
Notes:
* This check has not been restricted to a specific PHP version as there may be different versions of Composer being run on different Travis PHP images, so validating the file once against the lowest and highest PHP/Composer combi should make sure the file is properly validated.
* `--strict` checking is disabled with reason. As of Composer 1.6.0, the SPDX license identifiers v3.0 for GPL/LGPL/AGPL are supported and the old license identifiers are deprecated.
So using the …
> Travis/Build: validate the composer.json file

- package.json
- yarn.lock
* Bumps the YoastSEO version to 1.29.
* Do a `yarn install`.
> Bump YoastSEO version to 1.29

- admin/class-bulk-editor-list-table.php
* Remove trashed posts from bulk editor overview
Fixes #5959
> Remove trashed posts from bulk editor overview

- admin/class-social-admin.php
** While this function does not directly output HTML, the return value of this function will be send to screen and is easier to escape while building up the HTML, than afterwards.
* Includes layout changes to the statement.
* Includes numbering the placeholders in the top-level string.
* ~~Includes making one previously untranslatable string translatable (`Find out why you should upgrade to`).~~ Already merged via https://github.com/Yoast/wordpress-seo/commit/5e3399c55922e0e2e9bd3ea …
> CS/XSS: always escape output - 34

- admin/views/tabs/social/facebook.php
- admin/views/tabs/social/twitterbox.php
* Clarified Open Graph language for Facebook and Twitter in the Social settings
Verify the new copy in the Facebook and Twitter tabs is OK.
Fixes #6302
> Clarify open graph language in social tabs.

- inc/class-wpseo-replace-vars.php
fix for issue https://github.com/Yoast/wordpress-seo/issues/8661
Auto-generated meta descriptions are now trimmed to the first word boundary before 320 characters.
change trim length to 320 chacters as per Google's most recent snippet length; use substr to trim again to `strrpos($replacement, ' ')` so the meta description is trimmed to the last word boundary
create post with no manually entered excerpt or snippet; set Yoast to create a meta description from %%excerpt%%; check that the generated meta description is trimmed to the nearest word boundary to character 320.
Fixes #
> trim auto-generated meta description to 320 characters

- .gitattributes
* _N/A_
The `export-ignore` directives in the `.gitattributes` file determine which files are excluded when the repository is packaged for distribution, like on tagging a release.
The file exclusion list was out of date.
There is one open question - I'm not sure whether the `webpack` directory needs to be included or excluded. Anyone got some insights into that ?
* Download the zip of the repo and verify that the files mentioned in this PR are no longer there.
> .gitattributes: sync with files currently in the repo

- inc/class-post-type.php
- tests/inc/test-class-post-type.php
* Adds a function that can be used to determine whether or not a (custom) post type is enabled in the REST API.
Please test this in conjunction with https://github.com/Yoast/wordpress-seo-premium/pull/1551 as there's no real proper way to test this otherwise. 
Fixes #8647
> Introduced a function to determine if a post type is REST enabled

- .travis.yml
In our efforts to speed up the travis builds, remove this hard version lock.
Composer is a lot faster starting 1.3 and up, because xdebug will not be loaded when installing.
As this is one of the slower processes in the build steps, this should speed up things considerably.
Related:
Originally introduced in https://github.com/Yoast/wordpress-seo/pull/4361
No longer needed since https://github.com/composer-php52/composer-php52/releases/tag/v1.0.20
> Remove 1.0.0 composer version lock in composer

- admin/class-import-seopressor.php
- admin/views/tabs/tool/import-seo.php
- admin/views/tool-import-export.php
* Add an importer for people wishing to switch over from SEOpressor.
* Adds a new class for the SEOpressor importer.
* This import class imports:
* SEO title
* meta description
* canonical
* OpenGraph (Facebook) title, description, type and image
* Twitter title, description and image
* focus keywords
SEOpressor allows for 3 keywords per post, I've decided to import the first one as the main focus keyword and keyword 2 and 3 are stored in the `focuskeywords` array that Yoast SEO Premium uses.
* Enable SEOpressor on a test site (I have a copy I can send to tester).
* To activate SEOPressor without a license, find `WPPostsRateKeys_Options` in the `wp_options` table (this is an array) …
> Add SEOpressor importer

- admin/class-import-wpseo.php
* Make sure we import meta robots for more than 10 posts when importing from wpseo.de
* Switched to just querying ID's as that's all we need.
> Fix the query to import robots in wpSEO import

- inc/options/class-wpseo-option-social.php
_N/A_
WP offers a `wp_rand()` function as an alternative to the PHP native `rand()` function. Using the WP variant is recommended as it is more secure and less predictable than the values generated by the PHP native functions.
Use of the PHP native `rand()` related functions is discouraged anyway as the values they generate are not not secure. Using functions like `random_int()`, `random_bytes()` and `openssl_random_pseudo_bytes()` are suggested as alternatives.
The WP wrapper function makes use of these alternatives under the hood whenever possible.
Refs:
* https://developer.wordpress.org/reference/functions/wp_rand/
* http://php.net/manual/en/function.rand.php …
> CS/best practices: use `wp_rand()` instead of `rand()`

- admin/class-meta-columns.php
** Remove superfluous variable setting, making it clear that the output is escaped when echo-ed out.
> CS/XSS: always escape output - 27

- admin/pages/network.php
_N/A_
Minimum supported WP version is now 4.8, so no need to still support WP 4.6.
_N/A_
> QA: Remove fall-back for new WP function

- admin/class-social-facebook.php
- inc/class-wpseo-utils.php
- inc/sitemaps/class-sitemaps-renderer.php
- inc/sitemaps/class-sitemaps-router.php
_N/A_
The PHP native `parse_url()` function behaves differently across PHP versions which can lead to unexpected results.
WP offers a cross-PHP-version compatible alternative `wp_parse_url()` which is recommended to use instead.
As of WP 4.7, the WP function supports the `$component` parameter as well and as the WPSEO minimum WP requirements have gone up to WP 4.8, the last remaining calls to the PHP `parse_url()` function can now be replaced with calls to `wp_parse_url()`.
Also see #8035
_N/A_
> CS/best practices: use `wp_parse_url()` instead of `parse_url()`

- admin/class-admin.php
- inc/sitemaps/class-post-type-sitemap-provider.php
* Use _WPSEO_Link_Type_Classifier_ to determine link type in post_type sitemap.
* Clear sitemap cache if option 'home' is changed (Site URL).
* Add option 'home' in array `$cache_clear` ( _WPSEO_Sitemaps_Cache_ ). It purges all sitemaps cache at each changing of _Site URL_.
* WPML uses [debug_backtrace](http://php.net/manual/en/function.debug-backtrace.php) to check 'caller' (_classes/compatibility/wpseo/class-wpml-wpseo-xml-sitemaps-filter.php_) - we need to keep function _get_home_url_.
* Improve compatibility with _Really Simple SSL plugin_ - #8488 props @rlankhorst.
* Move Site URL to HTTPS (Settings/General). Check sitemaps. All sitemaps should contain https in urls.
Fixes …
> Use WPSEO_Link_Type_Classifier to check link type in WPSEO_Post_Type_Sitemap

- frontend/class-frontend.php
* The `current_user_can()` function accepts two arguments `capability` and `object_id`. The `object_id` wasn't added as a parameter before and as such `Undefined offset: 0` PHP notice occur.
* Enable _Redirect ugly URLs to clean permalinks_ option
* Preview any existing post or page
Fixes #8428
> Add Post ID as a parameter to check user capability correctly

- admin/config-ui/class-configuration-storage.php
- admin/config-ui/class-configuration-structure.php
- admin/config-ui/fields/class-field-advanced-settings.php
- tests/config-ui/fields/test-class-config-field-advanced-settings.php
- tests/config-ui/test-class-configuration-structure.php
* Added a step in the configuration wizard for enabling (or disabling) the advanced settings.
* Open the wizard and navigate to step 10.
* Set the advanced settings to show and go to the next step (is for saving the value)
* Navigate to the admin and see that the advanced settings pages are visible.
* Open the wizard again and navigate to step 10
* Set the advanced settings to hide and go to the next step (is still for saving the value)
* Navigate to the admin and see that the advanced settings pages are hidden
Fixes #6919
> Add toggle for advanced settings to wizard

- admin/class-admin-init.php
* Deprecated the hooks `wpseo_metakey` and `wpseo_metakeywords` because these aren't used anymore. There are no alternatives for these.
* Make sure errors and notices will be visible on your installation. Or you can use the  `Query Monitor` plugin
* Add a filter `wpseo_metakey` and a filter `wpseo_metakeywords`. `add_filter( 'wpseo_metakeywords', '__return_false');` This filter can be added on `wp-seo-main.php`
* A notice will be visible.
Fixes #8775
> Deprecate hooks

- admin/class-import-aioseo.php
- admin/class-import-external.php
- admin/class-import-jetpack.php
- admin/class-import-seopressor.php
- admin/class-import-ultimate-seo.php
- admin/class-import-woothemes-seo.php
- admin/class-import-wpseo.php
- admin/views/tool-import-export.php
* Fixes a bug where a PHP notice was given (only in debug mode) when a plugin import has been done. This also fixes the red (error) color of the success notice.
* Do a plugin update on trunk with debug mode enabled. You can install the Query Monitor plugin to get the php notice.
* The color of the success notification is red, this is the error color.
* Checkout this branch and see the php notice gone en the success notification is green (success)
Fixes #8785 
Fixes #8744
> Fix php notice after importing plugin data

- admin/class-yoast-form.php
- admin/pages/xml-sitemaps.php
- admin/views/tabs/metas/post-types.php
- admin/views/tabs/sitemaps/post-types.php
- admin/views/tabs/sitemaps/taxonomies.php
- admin/views/tabs/sitemaps/user-sitemap.php
* Improve the switch toggle settings for assistive technologies
This is a first step to partially address #8756.
- adds the ability to pass an array of visible text and screen reader text to the `toggle_switch()` control
- uses it for all the "In sitemap / Not in sitemap" settings, to start with
- improves docs
- verify each "In sitemap / Not in sitemap" setting has a screen reader text to give context to the option, for example: `In sitemap (posts)`
See #8756
> Add screen reader text to clarify the in sitemap - not in sitemap settings

- inc/sitemaps/class-post-type-sitemap-provider.php
*  Cast ids to integers in class WPSEO_Post_Type_Sitemap_Provider
* Function get_posts (class `WPSEO_Post_Type_Sitemap_Provider` ) retrieve array of posts (as objects, but they are `stdClass` instead `WP_Post`).  All properties are strings, but some properties should be integers ( https://github.com/WordPress/WordPress/blob/4.9.2/wp-includes/post.php#L1973 https://github.com/WordPress/WordPress/blob/4.9.2/wp-includes/post.php#L3003-L3039 ).
*
Fixes #
> Cast ids to integers in class WPSEO_Post_Type_Sitemap_Provider

- inc/options/class-wpseo-options.php
- tests/inc/options/test-class-wpseo-options.php
* no changelog line needed
* Adds a convenience function to quickly get one value from an option, leaving the cache in the `WPSEO_Options` class.
* Returns `null` if the key is not set.
> Add a convenience function to get one value from an option

- inc/options/class-wpseo-options.php
- tests/inc/options/test-class-wpseo-options.php
- tests/test-class-wpseo-utils.php
* Introduces a new `WPSEO_Options::get` and `WPSEO_Options::set` function that only require the key.
* Created a `get_lookup_table` function in the `WPSEO_Options` class to make `set` work easily.
* Use it :)
> Introduce get and set function for WPSEO_Options

- frontend/class-json-ld.php
- tests/test-class-wpseo-json-ld.php
* Only show JSON+LD markup for website + search on the front page.
* Make sure JSON+LD organization markup links to the frontpage. 
* Use `home_url` instead of current page's canonical.
* Removed the use of `$this->options` in favor of `WPSEO_Option::get()`
* Open the homepage, see the search markup.
* Open a single page, see the search markup is gone and see the organization markup points to the homepage.
Fixes #7827
> Improvements to JSON+LD

- .travis.yml
- tests/bootstrap.php
This is defaulted in the plugin already.
As the travis build is using `--dev` it is already set for these builds and triggers an already set warning.
Added a condition around WPSEO_TESTS_PATH to check for existing value if already defined.
Removes `create_function` message from linting results.
> Removes hard define in the bootstrap

- admin/class-import-seopressor.php
_N/A_
* Correctly pass in SQL wildcards. Similar to #8565. Part of clean up after merges.
> Literal percentage signs (%) in the query string must be written as %%. Percentage wildcards (for example, to use in LIKE syntax) must be passed via a substitution argument containing the complete LIKE string, these cannot be inserted directly in the query string. Also see esc_like().
Ref: https://developer.wordpress.org/reference/classes/wpdb/prepare/
_N/A_
> CS/QA: SQL LIKE wildcards should be passed through a replacement variable

- css/src/metabox.scss
Needed after the removal of `StyledSection.scss` in yoast-components see https://github.com/Yoast/yoast-components/pull/416
Removes the `StyledSection.scss` import and moves its content into `metabox.scss`.
Fixes https://github.com/Yoast/yoast-components/issues/415
> Remove StyledSection.scss import and move its content in metabox.scss

- admin/class-primary-term-admin.php
The goal fo this PR is to allow Polylang to synchronize the primary category across post translations. 
Although it is not possible to do this in the wpml-config.xml file (due to the fact that the primary category id must be translated during the process), the basic idea is to obtain the same result for `_yoast_wpseo_primary_category` as already done for [other custom fields](https://github.com/Yoast/wordpress-seo/blob/5.9.1/wpml-config.xml#L8-L10).
This is easily achievable in Polylang, but the issue is that a newly created translation doesn't populate the primary category in the metabox, because the class  `WPSEO_Primary_Term_Admin` does not get the post ID of new posts. The PR allows to get the post ID even for new posts.
Here is the Polylang branch to test the feature if you like to: …
> Allow WPSEO_Primary_Term_Admin to get the id of a new post

- package.json
- yarn.lock
* The issue wasn't actually caused by this, but I still think this is a useful addition to prevent react.propTypes errors since React 16 was introduced in `wordpress-seo`.
*
* Open the onboarding Wizard, make sure it works properly.
Fixes #8845
> Fixed configuration wizard by upgrading material ui

- inc/options/class-wpseo-option-titles.php
- tests/frontend/test-class-wpseo-frontend-redirects.php
* Our new feature to disable attachment URLs entirely is on by default for new sites.
> Disable media by default

- .codeclimate.yml
No reason for CodeClimate to check our parsed files, I'd prefer it checks our `scss` files...
* Excluded the CSS dist dir.
> Exclude CSS dist directory

- admin/class-admin-asset-manager.php
- admin/metabox/class-metabox.php
* Removes jQuery UI autocomplete from the enqueued scripts.
On the plugin version 2.3 autocomplete was used on the focus keyword field and invoked this way:
`jQuery( '#' + wpseoMetaboxL10n.field_prefix + 'focuskw' ).autocomplete( {`
so typically this jQuery UI widgets is invoked on a form field with `.autocomplete()`
- I've searched through the codebase for occurrences of `.autocomplete` and haven't found any
- I've searched also through all the add-ons I could think of
- to test: enable all add-ons, check all the pages: edit post, edit terms, settings, user profile, dashboard
- be sure there are no JS errors
Fixes #6598
> Stop enqueueing jQuery UI autocomplete.

- admin/links/class-link-query.php
- admin/links/class-link-reindex-dashboard.php
- admin/pages/tools.php
- admin/views/tabs/dashboard/general.php
- tests/admin/links/test-class-link_reindex_dashboard.php
- tests/doubles/wpseo-link-reindex-dashboard-double.php
* Moves the `Text link counter calculation` to the `tools` submenu.
* Introduced a new action to hook into to add more tool entries in the list.
* Go to the Tools submenu and see the `Text link counter` section.
* Go to the General tab on the dashboard submenu and see the `Text link counter` being removed.
* Test if the functionality still works.
Fixes #8840
> Move reindex tool to tools tab

- Gruntfile.js
- admin/class-admin-asset-manager.php
- grunt/config/addtextdomain.js
- grunt/config/checktextdomain.js
- grunt/config/clean.js
- grunt/config/cssmin.js
- grunt/config/imagemin.js
- grunt/config/set-version.js
- grunt/config/shell.js
- grunt/config/update-version.js
- grunt/config/watch.js
- grunt/config/wp_deploy.js
- grunt/config/wpcss.js
- grunt/custom/set-version.js
- webpack/paths.js
This PR allows Release Candidate versions to be set via the `grunt update-version` command.
It also introduces a grunt command to update the version to a new one.
Test instructions:
Run the following commands:
- `grunt set-version --new-version=7.0-RC1`
- `grunt update-version`
After this, `grunt build:js build:css` should be run to make sure the assets have the correct version and will be loaded.
See https://github.com/Yoast/wordpress-seo/issues/8885
> Improve version upgrade scripts

- admin/ajax.php
- admin/class-yoast-dashboard-widget.php
* Regression
* Only load the dashboard widget on admin_init
* See no AJAX request have 500 errors anymore.
Fixes #8901
> Only load dashboard on admin_init

- admin/class-admin-help-panel.php
- admin/views/tabs/dashboard/webmaster-tools.php
- admin/views/tabs/metas/archives.php
- admin/views/tabs/metas/general/homepage.php
- admin/views/tabs/metas/general/knowledge-graph.php
- admin/views/tabs/metas/general/title-separator.php
- admin/views/tabs/metas/media.php
- admin/views/tabs/metas/rss.php
- admin/views/tabs/social/accounts.php
- admin/views/tabs/social/facebook.php
- css/src/admin-global.scss
- css/src/metabox.scss
* Update the Admin Help Panel classo to be used in the settings pages too
- moved the CSS to admin global scss
- changed the button color globally so it will be purple also in the metabox and in the search console
- kept the class untouched, but it could probably benefit from a small refactoring to pass an $args array to be used, for example, for the optional wrapper and additional CSS classes; I'd like to review this part later if no objections
- considered a small helper function to print out the help button and content but then decided to not do that as the current class allows to print out them separately, and that's nice
- the styling could be improved, open to suggestions
- …
> Adjust the Help Panel to be used anywhere.

- css/src/toggle-switch.scss
* Standardizes the Switch Toggle controls to use not bold text
- set the `<b>` element printed out by `light_switch()` to a font-weight 400
- removed a CSS rule for a strong element that's actually not used by `light_switch()`
- build hte CSS
- verify `light_switch()`, `toggle_switch()` and their helper functions, always print out a default text that is not bold
Fixes #8919
> Standardize the switch toggles text to be not bold

- admin/config-ui/fields/class-field-post-type-visibility.php
Removes an ending space from a string, thus preventing a warning for translators.
* Optimizes a string for translation
* See if the string still displays correctly.
> Remove ending space from string

- frontend/class-json-ld.php
- tests/test-class-wpseo-json-ld.php
Replaces #8550 
* Changed schema.org output to link to https://schema.org instead of http://, props @vladiiancu, @mariusghitulescu 
Fixes #7849, #8550
> Change schema.org to https

- admin/class-config.php
- admin/views/tabs/dashboard/general.php
* Restoring the default settings now automatically opens the configuration wizard.
General tab looks like this after this change:
* Made the configuration wizard the primary button, as that is now the primary button on the page.
* Open General tab, see restore button has been moved.
* Click restore button, see question has added remark about opening the configuration wizard.
* Confirm default settings have been restored, and that configuration wizard automatically opens.
> Move restore default settings

- inc/wpseo-non-ajax-functions.php
* Remove the Microsoft Edge Site scan link as the tool is no longer functional.
* See the Microsoft Edge Site Scan link in the toolbar. 
* Apply this PR. 
* See it's gone.
Fixes #8908 
Props to @iamazik for initial patch.
> Remove the Microsoft Edge Site scan link

- admin/class-yoast-form.php
- admin/metabox/class-metabox.php
- admin/views/class-view-utils.php
- tests/test-class-wpseo-metabox.php
* Fixes an issue where setting the Yoast SEO Metabox to Show for a particular post type in the Settings, resulted in it being hidden (and vice versa).
* This PR purely wraps `is_metabox_hidden` and checks if the value returned is `true`. Due to the large overhaul in the Settings pages, the old logic of being able to set the Yoast SEO Metabox to hidden went from a 'Do you want to hide the Yoast SEO Metabox? (Yes/No)', to a 'Yoast SEO Metabox (Show/Hide)'. This means the old logic where you answered 'Yes' was being mapped to 'Show', where in reality it's 'Hide'. If anything, this 'fix' is more  cognitive change and not a functional one.
* I'm considering this a temporary fix. It'd be much better to do a (minor) options overhaul to …
> Adds functionality to invert logic for displaying the metabox

- admin/views/tabs/dashboard/webmaster-tools.php
This PR is a first pass to improve the labels, links, and help text on teh Webmaster tools page. Any feedback welcome.
* Improved accessibility and inline Help for the Webmaster Tools settings page.
- removes links from the labels
- makes the labels text a bit more meaningful
- moves the various Webmaster Tools sites links below the fields
- uses `add_query_arg()` for the links, where applicable
- adds a parameter `tid=alternate` to the Google Webmaster Central link to let users land on the right "tab" (see screenshot on the issue)
- uses `rawurlencode()` instead of `urlencode()` to avoid Coding Standards warnings, but please double check this
- tries to improve the text on the top of the page. Note: this text will be hidden in …
> Improve the Webmaster tools page labels, links, and help text.

- admin/pages/metas.php
- languages/wordpress-seo.pot
*Changed 'titles & meta settings' on the templates variables tab in the help center to 'search appearance settings' to correspond to new naming. 
*Go to Search Appearance, click 'need help?'. The first sentence below 'Template Explanation' should start with 'The search appearance...'
Fixes #8923
> 8923 replace titles and metas in help center

- package.json
- yarn.lock
* Updated yoast-components version to 3.0.0 
- committed the yarn.lock file
- seems the yarn.lock file gets other changes, for example the `svg-url-loader` was still there and gets removed, but there are also other changes, please double check
* run yarn to update the packages and see if anything breaks 🙂 
Fixes #8933
> Update yoast components version

- admin/views/tabs/dashboard/dashboard.php
* Makes the "Credits" heading translatable.
Fixes #8994
> Make Credits translatable

- admin/class-plugin-conflict.php
- admin/class-yoast-plugin-conflict.php
- inc/class-upgrade.php
- readme.txt
* Removed the plugin conflict notice for the Head, Footer and Post Injections plugin as it no longer manages OpenGraph tags.
* Install plugin, see notice.
* Apply PR, see notice doesn't show.
* With the notice active
* Reduce the version in the option: `wpseo` to below 7.0
* Make sure the notice is removed after reloading (the upgrade script will be triggered)
Fixes #8951
> Remove header footer plugin conflict notice

- package.json
- yarn.lock
* Upgrades `yoast-components` to `3.0.2`.
* Fixes SVG icons not showing up in help center.
> Upgrade yoast-components to 3.0.2

- admin/menu/class-admin-menu.php
* Renames the Dashboard menu item to General
* Look at the sidebar menu and see the first submenu change to General.
Fixes #9033 
Fixes https://github.com/Yoast/wordpress-seo/issues/8989
> Rename Dashboard to General

- admin/metabox/class-metabox.php
* Changes the wording on the drop down menu in the advanced tab of the metabox. It changed from Yes (Default for Posts) / Yes / No, to:
Default for Posts, currently: Yes / Yes / No
* Make sure the advanced tab is enabled. Go to the metabox under a page or post and check the dropdown menu under "Allow search engines to show this Page in search results?". The naming should have changed according to the description above. 
Fixes #8949
> Changed wording on index-toggle in advanced metabox

- admin/class-help-center.php
- inc/class-wpseo-meta.php
*Checked code for all soft-deprecated methods, actions, hooks or filters to add messages to them. Found one filter and added a deprecation message.  
* There should be no change in behavior of the plugin.  
* Use a plugin like Query Monitor to see debug messages. 
* When the filter 'wpseo_metabox_entries' is applied there should be a deprecation warning. 
Fixes [#8800](https://github.com/Yoast/wordpress-seo/issues/8800)
> Checked code for all soft-deprecated methods, actions, hooks or filters to add messages. 

- grunt/config/aliases.yaml
- grunt/config/update-version.js
* we now have 2 seperate update-version commands
grunt update-version:beta
grunt update-version:release
This commit does not break the original update-version command
* Creating extra grunt aliases
1. Ensure you have all development dependency's for the project
2. Execute the new commands:
`grunt update-version:beta`
`grunt update-version:release`
3. Check if the command did what it was supposed to do.
Fixes #8955
> Moved `Stable Tag` to it's own Grunt update-version command:

- inc/class-wpseo-replace-vars.php
* Adds an extra argument to `wpseo_replacements` filter. This makes it possible to access post, taxonomy or term instances when applying the filter.
* This PR can be tested by adding a filter manually and calling it. For example in the functions.php file which can be found in the wp-admin panel by go to Appearance->Editor. 
* Example code that should now work and would not have worked before:
```
function do_something_with_replacements( $replacements, $args ) {
$replacements['%%my_custom_replacement%%'] = get_post_meta($args->ID, 'my_meta', true);
return $replacements;
};
add_filter( 'wpseo_replacements', 'do_something_with_replacements', 10, 2 );
```
Fixes #7812
> 7812 pass args to replacement filter

- admin/class-import.php
Related: http://php.net/manual/en/function.parse-ini-file.php#99943
By using the `INI_SCANNER_RAW` argument, script variables will not be parsed and just used raw as input.
* Fixes a bug where importing of the values of ini files are being parsed for dynamic content.
* Implement the available argument to not parse dynamic values.
* See #dev-plugin for context
> Avoid ini value parsing

- admin/class-meta-columns.php
- admin/taxonomy/class-taxonomy-columns.php
- tests/doubles/wpseo-meta-columns-double.php
- tests/test-class-wpseo-meta-columns.php
* Fixes an issue where the overview pages were incorrectly showing categories / tags marked as `noindex` when in reality they weren't set to `noindex` (and vice versa). This meant that blue bullets were being shown incorrectly.
* Fixes an issue where setting posts and pages to `noindex` didn't change the overview.
* Individually setting a post to `index` when the post type is set to `noindex`, overrules the parent setting for that specific post/page/category/tag.
* Set `Show Posts in search results?` to "No" in SEO -> Search Appearance -> Content Types.
* Check that the SEO column in the Posts overview only displays blue bullets.
* Override the index setting for a single post (set …
> Fix faulty noindex in post, page, category and tag overview

- admin/statistics/class-statistics-service.php
Replaces #8935 
* Change formatting of text in dashboard widget to improve reading experience.
* Delete transients and view /wp-admin/index.php
Fixes #8125
> David mcleod 8125 change text formatting in dashboard widget

- grunt/config/aliases.yaml
* Fixes an issue where an old alias was still present in the aliases file which lead to `grunt artifact` to fail.
* Run `grunt artifact` and ensure that it completes successfully.
> Removed old command from grunt aliases

- .travis.yml
Attempt to reduce the total build time of a Travis build.
Splitting up Coverage and removing the wait for linting and code style checks from the big build.
> Put coverage in separate build to reduce total build time

- package.json
- yarn.lock
* Content analysis headers are all expanded by default.
* Create a new post or open an existing post.
* Notice all content analysis headers are expanded.
Fixes #8882
> Update yoast components to 3.1.0

- inc/sitemaps/class-author-sitemap-provider.php
- tests/sitemaps/test-class-wpseo-author-sitemap-provider.php
This is a regression from 6.3, so no need for a changelog entry. Added tests to make sure we don't break this again.
* Create author without posts, toggle setting, check XML sitemap.
Fixes #9029
> Fix the fact that author with no posts don't show up in sitemap

- js/src/assessors/taxonomyAssessor.js
- js/tests/helpers/factory.js
- js/tests/taxonomyAssessor.test.js
* Changes the boundaries of the taxonomy text length assessment to the following values:
* Red: 0-200 words (slightly below minimum: 200-250, below minimum: 150-200,  far below minimum: 100-150, very far below minimum: under 100)
* Orange: 200-250 words
* Green: 250+ words
* Makes use of the `TextLength` assessment, passing along the appropriate values instead of making use of the separate `taxonomyTextLength` assessment. (The  `taxonomyTextLength` assessment will subsequently be deleted from yoastseo.js).
* Adds unit tests for the taxonomy assessor.
* Check out the branch. Don't forget to run `grunt build:js`.
* Add a new category in `Posts > Categories`. Add a description.
* Vary …
> Change boundaries of taxonomy text length assessment

- package.json
- yarn.lock
* Adds a filter to mark Spanish sentences as non-passive when certain exception words occur between the auxiliary and the participle. The list of exception words includes all forms of the copula 'estar'.
* Adds transition words assessment for Portuguese, props [amesdigital](https://github.com/amesdigital).
* The snippet preview now shows the mobile preview by default.
* Fixes a bug where division by zero errors in the passive voice assessment would cause `NaN%` to show up in the feedback.
* Fixes a bug where multiple `rel` arguments prevented correct `nofollow` detection.
* Slightly increased the height of the meta description box so it matches the maximum amount of characters without needing a scrollbar. …
> Bump YoastSEO.js to 1.30

- frontend/class-breadcrumbs.php
* Fixes an issue where breadcrumb ancestors wouldn't be displayed for nested pages.
*
* Implement breadcrumbs in your theme.
* Create a new page.
* Create another page and set its parent to the previously made page.
* Visit the newest page and observe that the parent page is properly displayed in the breadcrumbs.
Fixes #9128
> Fixed logic bug so breadcrumb ancestors are properly displayed

- inc/options/class-wpseo-option-titles.php
* Uses the old sanitizing method that was present in 6.3. to sanitize the RSS before and RSS after fields.
* Add a link to the RSS before field in `Search Appearance > RSS`.
* Add `<script>alert('')</script>` to the RSS after field.
* Save the settings.
* Ensure that the link remains, but the `<script>` tag is stripped.
Fixes #9129
> Used the same sanitizing method for RSS, as was being used in 6.3

- inc/class-upgrade.php
- inc/options/class-wpseo-options.php
Because we have introduced the backfilling of the options, these are also being backfilled during the Upgrade routine.
This results in the empty values of the -not yet- migrated options.
By loading the options directly from the database, the settings can be loaded as they exist during the upgrade.
Also, saving the new options directly via `WPSEO_Options::set` provides a simpler way of storing the settings to be migrated.
Removing irrelevant keys can be done more easily, by re-saving the option, which is picked up by the Options framework, which in turn makes sure only valid settings are stored in the database.
* Fixes a bug where the option settings that need to be migrated are backfilled prematurely.
* `save_option_setting` …
> Fix option settings migration

- inc/sitemaps/class-sitemaps.php
Instead of triggering it in the constructor, which is being called on `plugins_loaded`, excluding theme's from ever being able to use it.
* Fixes a bug where adding a `wpseo_sitemap_entries_per_page` which is not being used in rendering the sitemaps. 
* Using the filter just in time.
* Add the following filter in your theme (functions.php):
```
add_filter( 'wpseo_sitemap_entries_per_page', function() {
return 5;
});
```
* Disable the Sitemap feature
* Enable the Sitemap feature (this will reset the cache buster)
* Visit a sitemap post type page and verify the max entries is being respected
Fixes #9166
> Apply filter just-in-time

- package.json
- yarn.lock
* Fixes a bug that broke a filter which marks Spanish and French sentences as non-passive when certain exception words occur between the auxiliary and the participle.
* Test whether the functionality above is present and nothing else breaks.
> Bump to 1.30.1

- inc/class-upgrade.php
Test instructions:
My approach to test different versions:
- Install 6.3.1 in `wordpress-seo-6.3.1` folder
- Install this branch in `wordpress-seo`
- Remove all `wpseo*` settings in the database
- Activate `6.3.1` branch and save the settings you want to test/see
- Deactivate `6.3.1`
- Activate the Yoast SEO with this branch
- See the changes being shown as expected
Set all `metaboxes` to 'disabled' in Post types and Taxonomies and expect them to be disabled after upgrading as well.
Fixes #9190
> Fetch `wpseo_titles` from database as well

- inc/class-upgrade.php
- tests/doubles/class-upgrade-double.php
- tests/test-class-wpseo-upgrade.php
* (Added tests, no changelog relevance)
* Made the `finish_up` method protected, to be able to test it
* Decided not to test the specific upgrade routines, this should be done for upcoming upgrade routines.
* Run PHPUnit
Fixes #9185
> Add tests for upgrade class

- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
- inc/class-wpseo-utils.php
- js/src/ui/trafficLight.js
* Improves the traffic light icon accessibility.
- the metabox and taxonomy metabox classes used the same identical method to output the icon: moved the code to `WPSEO_Utils` to reduce code duplication
- added `role="img" aria-hidden="true" focusable="false"` attributes
- removed an alt attribute that was added via JS
- removed some `xmlns` attributes (invalid HTML, see #9157 )
- build the JS
- check the traffic light icon is displayed and works correctly
- check in IE 11 you have to tab only once when using the keyboard
Fixes #9145
> Move traffic light code to Utils and improve a11y.

- inc/options/class-wpseo-option.php
* Fixes a bug where the rewrite rules aren't removed after stripping the category base. This resulted in an unaccessible page.
* Strip the category base
* See the category page is working.
Fixes #9196
> Flushes the rewrite rules after option update

- admin/onpage/class-onpage.php
- inc/options/class-wpseo-options.php
- tests/onpage/test-class-onpage.php
- wp-seo-main.php
* Removes the backfill hooks when calling `WPSEO_Options::get()` to improve performance.
*
* Determine that the current release (`7.0.3`) has a significant increase in the loading time (in some cases 2x) as per described in the issue.
* Checkout this branch, run the same tests and determine that the loading time decreases.
Fixes #9170
> Removes the backfill hooks when calling `WPSEO_Options::get` to improve performance

- frontend/class-frontend.php
* When setting a page to `noindex` through the `wpseo_robots` filter we now properly remove the `canonical` element.
Fixes #9132
> Fix logic for removing canonical when noindexing

- admin/class-suggested-plugins.php
* Hide suggestions for plugins on the dashboard if Premium plugin is active
* Have ACF, WooCommerce or AMP for WordPress installed. 
* Checkout trunk on this repo.
* Go to the dashboard and see some suggestions.
* Checkout premium trunk
* See the notifications still being present.
* Create a temporary branch on premium and merge this branch into that branch.
* Refresh the dashboard and see the notifications being removed. 
An unfair test is to change the implementation of WPSEO_Utils:: is_yoast_seo_premium by returning that method true. This fakes the premium situation. Or you can define a constant named `WPSEO_PREMIUM_PLUGIN_FILE`
Fixes …
> Hide notification for premium users

- admin/class-customizer.php
- admin/views/tabs/metas/breadcrumbs.php
- frontend/class-breadcrumbs.php
- inc/class-upgrade.php
- inc/options/class-wpseo-option-titles.php
- inc/options/class-wpseo-options-backfill.php
- readme.txt
* Renames `breadcrumbs-blog-remove` to `breadcrumbs-display-blog-page` to fix logic issues. Previously when you enabled the `Show blog page` in the breadcrumb settings, it'd be disabled and vice versa.
*
(Credits to @CarolineGeven for these detailed instructions)
**IMPORTANT: Prior to testing, ensure that the `version` property in your database is set to a value lower than `7.1.0`. The property can be found under the `wpseo` option name in the `wp_options` database table.**
* Go to Settings -> Reading.
* Set a static page for posts page. (Leaving the option unset is fine)
* Create a blog post and insert the `[wpseo_breadcrumb]` shortcode.
* Go to SEO -> Search Appearance -> …
> Renames breadcrumbs-blog-remove to breadcrumbs-display-blog-page

- js/src/analysis/PostDataCollector.js
- js/src/analysis/data.js
- js/src/edit.js
- js/src/helpers/isGutenbergDataAvailable.js
- js/src/wp-seo-post-scraper.js
- js/tests/data.test.js
- js/tests/edit.test.js
- js/tests/isGutenbergDataAvailable.test.js
This PR can be summarized in the following changelog entry: 
* Makes it possible to use the content, slug, title and excerpt from Gutenberg posts in the SEO and readability analysis.
* This is a prototype. Architecture and naming might change in the future.
* Create a post in Gutenberg.
* Make sure all SEO and readability assessments that use the content, slug and/or title work correctly.
* Also make sure all assessments still work correctly in the classic editor.
* Write an excerpt in the document sidebar. Use the %%excerpt%% and %%title%% replace var in the snippet preview.
**Important**: Currently, Gutenberg only saves a slug after publishing the post.
Fixes #9019
> Subscribe to Gutenberg's data API

- js/src/wp-seo-post-scraper.js
Fixes a console error in the classic editor that states that `data.setRefresh` is not defined/not a function.
1. On master, open a post in the classic editor.
2. Check your console and see the error.
3. Check out this branch. Don't forget to build etc.
4. Open a post in the classic editor.
5. The error is gone
> Prevent console error in classic editor

- package.json
- yarn.lock
* Reverts the default view of the snippet preview to desktop.
* Test whether the functionality above is present and nothing else breaks.
> Bump YoastSEO.js to 1.30.2

- admin/pages/dashboard.php
- admin/views/tabs/dashboard/features.php
* The second letter in settings and tabs is not consistently capitalized. The capitalization is the norm (Search Appearance, Search Console, Regex Redirects, Content Types), but tools in _Webmaster tools_ is not capitalized.
* Go to General -> Features (tab) and check the capitalization on XML Sitemaps toggle and other toggles.
* Go to General -> Webmaster tools (tab) to check the tab title.
Fixes #8993
> Consistency in capitalization

- admin/class-admin-init.php
- languages/wordpress-seo.pot
*Added words to improve how to resolve a comment notification 
*n/a
*1. Install plugin
2. Visit comments settings section and click the box in front of  "Break Comments into pages". This will then trigger the new notification 
3. See new notification 
Fixes #https://github.com/Yoast/wordpress-seo/issues/8876
> Added words to improve how to resolve a comment notification 

- admin/import/class-import-settings.php
* No changelog needed.
* Prevents an error on 5.2 (where the third parameter doesn't work anyway) while providing max security on higher PHP versions.
Fixes #9234
> Prevent error on PHP 5.2

- css/src/metabox.scss
* Set box-sizing to border-box on the highest yoast metabox class, and set all children to inherit that box-sizing.
* In keeping with the decision by the Gutenberg team to only set border-box inside Gutenberg, and keep content-box in the metaboxes, we now override that setting in the Yoast SEO plugin.
* In the content analysis metabox, verify that all sections have a width of 640 and are similarly aligned. Appearance in Gutenberg should match that of the classic editor.
* Do some tests to check whether the new inheritance is probably set throughout our plugin, and that there are no conflicts between any box-sizing settings further down the hierarchy.
Fixes …
> set box-sizing for yoast_meta class and force all children to inherit

- frontend/class-json-ld.php
- tests/test-class-wpseo-json-ld.php
* Changed JSON+LD organization output to always point to `#organization` on the homepage instead of the current page.
* See any page's JSON+LD #organization section.
Fixes #9228
> Output home URL before #organization

- admin/class-admin.php
* Removes the Whip notification for WordPress versions starting from 4.9.5
* Change `>=5.4` in the `whip_wp_check_versions` function call to `>=7.3`. This fakes the minimal required PHP version. You can test with a version below 5.4 if you want, will do the same.
* Go to the WordPress dashboard. 
* A notification will be shown.
* Change the 4.9.5 in the version compare to the current WordPress version (4.9.4?). This fakes the minimal required WordPress version to a version that has been released already.
* The notification should be hidden now.
Fixes #9220
> Remove the whip notification

- js/src/wp-seo-post-scraper.js
* Not applicable
* Because the store was set to a new const the 'global' store wasn't set. Solve this by renaming the 'global' store.
* Switching to the readability tab and seeing that the readability results are shown.
Fixes #9325
> Fix bug where switching to readability didn't work

- admin/class-yoast-form.php
* Showing the options below the admin pages has been moved to the Yoast Test helper plugin.
* Made `get_option` public to be able to access it from the Yoast test helper.
* See any admin page, see the options block is gone when `WP_DEBUG` is on.
> Move out options debug code

- admin/class-meta-table-accessible.php
- admin/links/class-link-table-accessible.php
* Don't throw errors when MySQL is set to `sql-mode=ANSI_QUOTES`.
* Use `$wpdb->prepare` properly which foregoes the whole problem described in the issue.
Fixes #9237
> Second try to fix this issue without going down a rabbithole

- admin/metabox/class-metabox.php
- css/src/metabox.scss
* Change the padding to margin to keep the same spacing between the icon and the text on a wide screen.
* Change the smaller screen media style to margin-right and overwrite the padding to zero again to keep the same spacing between the icon and the text.
* Keep the `box-sizing` as `border-box`.
* Inspect the 'Go Premium' link and make sure there is space between the star icon and the link text. Just like it was before we introduced `box-sizing: border-box;` See issue for screenshot comparison.
* Also adjust screen width to smaller and check the same.
Fixes https://github.com/Yoast/gutenberg/issues/51
> Changed padding to margin for the icon in the Go Premium link

- admin/views/tool-import-export.php
* _Security hardening_
Only try and instantiate the class provided via `$_POST` if the class exists.
Prevents a potential fatal error if - for whatever reason/hack or otherwise -, the query argument in the URL does not correspond to one of the WPSEO import classes.
Also: always use parentheses when instantiating an object.
* Using `trunk` - open the import page, edit the HTML so an invalid class is used for `import_external_plugin`/`clean_external_plugin` and see what happens.
* Do the same using this branch.
> CS: clean up after latest merges - prevent fatal error/security hardening

- admin/views/tabs/dashboard/webmaster-tools.php
- frontend/class-frontend.php
- inc/options/class-wpseo-option-wpseo.php
- inc/options/class-wpseo-option.php
- tests/frontend/test-class-wpseo-frontend.php
* Add Baidu Webmaster Tools verification support
* An example Baidu webmaster tools verification can be found on the relevant unit test method.
* Go to Yoast SEO -> Webmaster Tools (tab).
* Add a Baidu webmaster tools verification code.
* Check the homepage source code for the verification meta.
Fixes #5409
> Add Support for Baidu Webmaster Tools Verification

- admin/class-admin-asset-manager.php
- js/src/components/IntlProvider.js
* Removes the intl polyfill and show message on browsers that doesn't support intl.
* Add `window.Intl = undefined` somewhere in the code. For example in the `js/src/components/IntlProvider.js` in the `render` function before the `if` statement.
* Do a `grunt build:js`
* See an error message is given in the Yoast SEO metabox, but also in the admin pages where you can expect the help-center box.
* Remove the `window.Intl = undefined` and do a `grunt build:js`
* Everything should work correctly: Yoast SEO metabox, help-center box on the admin pages. 
Fixes #9063
> 9063 remove intl dependency

- admin/class-meta-columns.php
* Fixed a bug where the keyword filter doesn't work on the post overview.
* Checkout `trunk`
* Follow the steps to reproduce issue #7772. (Have two post with the same focus keyword. Create a third one with the same focus keyword. Follow the link in the analysis that says that the keyword is used multiple time.
* You will see a post overview, but nothing filtered.
* Refresh that overview page and see the posts being filtered.
Fixes #7772
> Make keyword

- inc/sitemaps/class-post-type-sitemap-provider.php
- tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
- tests/sitemaps/test-class-wpseo-sitemaps.php
* Prevent attachments of password protected posts from showing up in XML sitemaps.
* Added check for `post_password = ''` because the `post_status` for a private post _can_ be 'publish', as core checks `post_password`. 
* See #9194, with this patch you should no longer be able to reproduce.
Fixes #9194
> Check for empty post_password

- admin/views/tabs/metas/breadcrumbs.php
* Fixes a bug where non-public taxonomies are settable in the breadcrumbs.
* This fix is made for premium (https://github.com/Yoast/wordpress-seo-premium/issues/1648). It is possible to set prominents words for posttypes in the breadcrumbs.
* Howto test: Merge this branch in a local branch of wordpress-seo-premium. 
* Verify that the prominent words are not visible in the dropdowns under `Taxonomy to show in breadcrumbs for content types`
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/1648
> Only show public taxonomies 

- admin/views/tabs/social/facebook.php
- frontend/class-opengraph.php
- inc/options/class-wpseo-option-social.php
* Bring back the Facebook app_id in the settings and as a metatag
* On the frontend: view the source of a post, page or what you want 
* No app_id is present
* Checkout this branch and go to the Facebook settings: social > facebook
* Set an app id
* Again view the source of post, page on the frontend
* See the app_id being present as a metatag.
Fixes #9323
> Show the facebook app id

- wp-seo-main.php
This reset will be done when there is a difference between the existing and the new version of Yoast SEO.
* Resets the opcode cache when an update has been done.
* I've no clue what opcode cache does and how it works. I've only checked for existence of the function and I called it.
Fixes #9315
> Resets the opcache when function exists

- admin/class-cornerstone-field.php
- css/src/filter-explanation.scss
* Fixes a bug where the pagination overlaps the cornerstone info block on lower resolutions
* Have at least 1 cornerstone post present.
* Checkout `trunk`
* Resize the windows, till you get to this point:
* Checkout this branch and run `grunt build:css`
* It should be fixed now. **Note:** there might be an issue with a top margin, this is not the scope if this issue.
Fixes #9293
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/1664
> Prevent cornerstone info box overlapping

- admin/taxonomy/class-taxonomy-settings-fields.php
- admin/views/user-profile.php
* _Minor I18n improvements_
Regarding the second one (in `user-profile.php`):
PHP open/close tags for multi-line snippets should be on their own line, but this can cause layout issues when the output is directly embedded in certain HTML tags.
By creating a variable beforehand and passing that in, we create a stable result.
Includes some improved output escaping.
* _N/A_
> CS: clean up after latest merges - add missing translators comment

- admin/onpage/class-onpage.php
- tests/onpage/test-class-onpage.php
- wp-seo-main.php
Due to merge conflicts this was broken.
The notification needs to be removed when the service is inactive.
Also doesnt register the REST endpoint when Ryte is disabled.
* _Not applicable_
* Also disabled REST API when feature is disabled.
* See issue.
Fixes #9371
> Restore notification unhook

- inc/class-wpseo-shortlinker.php
* _Not applicable: Regression_
* Just return `free` or `premium` instead of trying to do `license active` logic.
* Merge this into Premium and verify that there are no fatal errors on the `License` or settings-pages.
Fixes #9400
> Just return `free` or `premium`

- admin/links/class-link-columns.php
- tests/admin/links/test-class-link-columns.php
* Prevent hard casting to array on WP internal filter.
* Returned `$columns` when it's not an array.
Fixes #9403
> Fix hard cast to array

- inc/class-wpseo-meta.php
* Adds the ability to filter out strippable characters from the focus keyword so they don't get removed on save. Props to @BHEADRICK.
* Refrained from adding unit tests in this PR due to the complexity of the sanitation function. Will create a new issue for this, as some refactoring might be necessary.
* Create a new post and add a keyword that contains the `"` character in it (i.e. `21" television`).
* Save the post and note that the `"` is stripped from the keyword.
* Add a call to the newly added filter (i.e. `add_filter( 'wpseo_focuskw_strippable_chars', 'function_to_call' );`). Make sure the function you call returns an array _without_ the `"` in it.
A …
> Add ability to filter out strippable characters from the focus keyword

- admin/config-ui/components/class-component-configuration-choices.php
* Alters the configuration service text in the Configuration Wizard when a user is already running Yoast SEO Premium. Previously the text contained a reference to getting a bundled copy of Premium, even if the user was already running Premium.
* Added the logic to Free, as the text is being generated there.
**Free**
* Run `composer install`, `yarn` and `grunt build` prior to testing.
* Start the Configuration Wizard (`SEO -> General`)
* Notice the block on the right of the welcome page of the Configuration Wizard. Please note that the old text (with a reference to a copy of Premium) is still there.
**Premium**
* Pull this branch into a test branch within your …
> Alter configuration service text if the user is already using Premium

- inc/class-post-type.php
- tests/inc/test-class-post-type.php
* Apply features on real publicly queryable post types only.
*
* Create a post type by pasting the next code in de wp-seo-main.php file
```php
// Alert: this is modern php xD
add_action( 'admin_init', function() { 
register_post_type( 'hidden-post-type', [ 'public' => true, 'publicly_queryable' => false ] );
} )
```
* For example: the cornerstone feature still works. But it shouldn't work. Checkout this branch.
* It will be solved now.
Fixes #9085
> Add filter for viewable posttypes

- wp-seo-main.php
* Fixes a bug where the Ryte endpoint is not available to check the Ryte active status
* Just renabled the endpoint again
* Disable the Ryte feature in the Features tab on the General settings page
* Open the dashboard
* See the Ryte request being done to the REST endpoint
* See the Ryte request serving a `ryte: false` response to notify that the service is disabled
Fixes #8698
> Ryte endpoint should be avaible to check for enabled status

- admin/class-admin-init.php
- admin/class-admin-utils.php
- admin/class-admin.php
- admin/class-unsupported-php-message.php
- inc/class-upgrade.php
* Adds messages to the admin regarding our ongoing policy in terms of PHP 5.2 support.
*
* Checkout this branch on a system running PHP 5.2 or lower.
* Login to the admin and see that there's a notification at the top of the screen.
* Navigate to SEO -> Dashboard and see an additional message in the Notification Center.
If you cannot run a version of PHP that is old enough, you can alter your currently running version on line 77 of `class-admin-utils.php` by altering the following:
```
$checker = new Whip_RequirementsChecker( array( 'php' => PHP_VERSION ) );
```
to
```
$checker = new Whip_RequirementsChecker( array( 'php' => '5.2' ) );
```
Fixes #9466
> Implemented a rough version of the PHP 5.2 check

- admin/class-database-proxy.php
- admin/class-meta-storage.php
- admin/links/class-link-storage.php
- tests/admin/links/test-class-link-storage.php
- tests/admin/test-class-database-proxy.php
* Handles the database table prefix flexibly in the `WPSEO_Database_Proxy` class instead of relying on a passed hard-coded table name that includes it. This makes the class behave correctly when switching sites in multisite.
* Registers the database table with the WordPress database object (`$wpdb`). This makes WordPress aware and ensures that it automatically drops them for example when a site is deleted. It also standardizes behavior as other developers often rely on all database tables being present in the WordPress object.
* Store only the unprefixed database table name in the internal property `$table_name` and get the current prefix to use from the database object (`$wpdb`). To be backward-compatible, if a fully qualified …
> Refactor database proxy class to handle table prefix and register table with WordPress

- admin/onpage/class-onpage.php
- tests/onpage/test-class-onpage.php
* Fixes a bug where a non-array value causes a fatal error when `cron_schedules` filter has been executed.
*
* Add a filter `cron_schedules` with high prio that returns an boolean.
```php
add_filter( 'cron_schedules', '__return_false', 1 );
```
* Call the method `wp_get_schedules();`
```php
add_action( 'admin_init', function() {
print_r( wp_get_schedules() );
exit;
} );
```
* See a fatal error being shown.
* Checkout this branch and follow the steps mentioned before. The error should be gone.
Fixes #9450
Fixes #9475
> When the given argument is not an array, just make it an array

- webpack/webpack.config.default.js
This excludes all packages from babel parsing except yoast-components. That makes the build faster and also prevents DraftJS from including a bunch of packages for which we don't have the correct babel plugins and presets.
I also included JSON files in the webpack config, because we need that in yoast-components. And it is just nice to be able to load json files.
* Make sure all the JavaScript still compiles as expected.
> Setup webpack config for the snippet editor

- inc/class-upgrade.php
* Clears all existing cache validator entries from the database. This is a small step towards removing the cache from the database entirely.
* Created a separate method, to use on the following release as well if the caching has not be removed at the moment of the upcoming RC.
* Before checking out the branch
* Visit the sitemaps
* Open the database and go to the `wp_options` table
* Search for `option_name LIKE 'wpseo_sitemap%validator%'`
* See entries being present
* Check out the branch
* Reload a page, to make sure the upgrade routine has been triggered
* Reload the database, see the entries being removed or updated
Fixes #9491
> Remove cache validators on upgrade routine

- js/src/wp-seo-dashboard-widget.js
* Adds to the documentation of `getColorFromScore()` that `noindex` is also an expected outcome.
Fixes https://github.com/Yoast/yoast-components/issues/446
> Added to documentation of getColorFromScore() 

- admin/class-admin-init.php
- admin/class-unsupported-php-message.php
* Alters the copy for the PHP 5.2 support message from 7.5, to 7.7. Additionally, the dates in the copy have been altered as well.
*
* Trigger the PHP upgrade notice (as per instructions in https://github.com/Yoast/wordpress-seo/pull/9467).
* Notice the copy has been altered.
Fixes #9515
> Bumped version for the PHP 5.2 support drop to 7.7

- admin/onpage/class-onpage.php
- frontend/class-frontend.php
- frontend/class-opengraph-image.php
- frontend/class-opengraph.php
- inc/class-wpseo-content-images.php
- inc/class-wpseo-image-utils.php
- inc/sitemaps/class-sitemap-image-parser.php
- phpcs.xml
- tests/frontend/test-class-opengraph.php
- tests/frontend/test-class-wpseo-opengraph-image.php
- tests/test-class-opengraph.php
* Output width and height in OpenGraph meta tags way more often.
* When an image found for OpenGraph is larger than 2MB, choose a smaller version.
* Cache images found in a post so we don't need to do this on every page load.
* When an image has an alt tag, output it as `og:image:alt`.
* Factored out two new classes, `WPSEO_Image_Utils` and `WPSEO_Content_Images`. The former to find attachment ID's from image URLs, find correct image paths and find image file sizes. The latter to find and cache images in post content.
* Play with images in post content, as featured image, specifically set as Facebook image and make sure it all still works as expected, and has width and height output …
> Refactor how we handle OpenGraph images

- admin/class-admin-asset-manager.php
- tests/test-class-admin-asset-manager.php
* Add `$prefix` to the WPSEO_Admin_Asset_Manager class call and make `$prefix` publicly accessible.
*
* Call `$asset_manager = new WPSEO_Admin_Asset_Manager( null, ‘prefix-name’ );`
* Dump `$asset_manager`. The new prefix is now in `$asset_manager->prefix`
Fixes #9492
> Additions to Asset Manager for use in other plugins

- inc/sitemaps/class-sitemaps-renderer.php
- tests/doubles/class-sitemaps-renderer-double.php
- tests/sitemaps/test-class-wpseo-sitemaps-renderer.php
* Fixes a bug where loading the WordPress content directory from a different domain blocked the XML sitemap from loading. 
* Added an additional check in the fallback. 
* Reproduce the original issue by:
Changing your WP content dir in wp-config.php. This can be done by adding the following line:
`define( 'WP_CONTENT_URL',   'http://example.test/wp-content' );`
It's important this is a different site than the one you're testing from. If you get errors loading the plugin make sure both sites have the same version of the plugin installed. 
* Go to your XML sitemap and see the page in blank with a 'Unsafe attempt to load URL' message in the console.
* Switch to the fixed version and …
> 9059 sitemap error with different wp content url

- Gruntfile.js
- grunt/config/eslint.js
- js/tests/.eslintrc
- js/tests/data.test.js
- js/tests/edit.test.js
- js/tests/isGutenbergDataAvailable.test.js
- js/tests/shortcode-plugin.test.js
* Enabled Jest environment in the tests, for obvious reasons.
* Using `undefined` in tests is really useful, so disabling the rule that disallows it.
* Having anonymous React components is useful during mocking, so disabling the rule that requires a display name in the tests.
Scenario 1
* Run `grunt check` and see that the JS tests are now linted.
Scenario 2
* Change something in the tests so it violates our linting rules.
* Run `grunt check` and see that it fails.
> Add ESLinting to tests

- js/src/assessors/taxonomyAssessor.js
- js/tests/taxonomyAssessor.test.js
* Removes the URL length assessment, the stopword in URL assessment, and the stopword in keyword assessment from the taxonomy assessor. These assessments have become obsolete.
* Check out the branch. Don't forget to run `grunt build:js`.
* Add a new category in `Posts > Categories`.
* Make your slug very long, e.g. `new-very-very-very-very-very-very-lengthy-url`. Make sure no feedback is triggered.
* Add a stopword (e.g. `the`) in your slug. Make sure no feedback is triggered.
* Add a stopword (e.g. `the`) in your focus keyword. Make sure no feedback is triggered.
Fixes #9512
> Remove obsolete assessments from taxonomy assessor

- tests/framework/class-wpseo-unit-test-case.php
* This change allows unit tests to use `ms-required` or `ms-excluded` as group annotations, with the effect that the test will only be executed with or without multisite respectively. Otherwise, the test will be marked as skipped. That is an established pattern core uses for their multisite tests.
* While core performs these checks, they are depending on other environments and PHPUnit versions than we are, so the `checkRequirements()` method used by PHPUnit and core needs to be overridden. PHPUnit's `Testcase::getAnnotations()` method returns an array with `class` and `method` keys, where both have a `group` key. If any of those groups contain one of the two groups we're looking for here, the test is skipped accordingly if …
> Add support for multisite-only or single site-only unit tests

- inc/wpseo-non-ajax-functions.php
* Renamed 'Dashboard' to 'General' in admin bar to match naming in side bar. 
* Look under 'SEO Settings' in the admin bar (top of the screen) and see that 'Dashboard' is now named 'General'
Fixes #9543
> Changed 'Dashboard' into 'General' in Admin menu

- admin/class-admin-asset-manager.php
- admin/config-ui/class-configuration-page.php
* N/A
* Move the Gutenberg register to fix them being loaded twice when not on the Configuration Wizard and using Gutenberg.
* Check the Configuration Wizard!
~~* [ ] I have added unittests to verify the code works as intended~~
> Move the Gutenberg register to the configuration page class

- inc/options/class-wpseo-options.php
- tests/inc/options/test-class-wpseo-options.php
* Ensures that multisite options can be retrieved via `WPSEO_Options::get()` in a multisite.
* Since the methods called by `WPSEO_Options::get()` are deeply integrated with other functionality, the most risk-free approach was to manually make the changes in there.
* In a multisite, call `WPSEO_Options::get( 'access' )` or `WPSEO_Options::get( 'defaultblog' )` in `functions.php` or similar, and verify that you get a possible value for the option back (i.e. not NULL).
* Do the same in a non-multisite, to make sure that those calls then return NULL and don't cause unexpected issues (like possibly calling multisite functions in a non-multisite context).
Fixes #9453
> Allow accessing multisite options via `WPSEO_Options::get()`

- frontend/class-frontend.php
- frontend/class-opengraph-image.php
- frontend/class-opengraph.php
- frontend/class-twitter.php
- tests/frontend/test-class-wpseo-opengraph-image.php
* N/A
* Create instance of `WPSEO_Opengraph_Image` with in the constructor a string argument and an instance with no argument.
* This should work now.
> Fixes backwards compatibility for WPSEO_Opengraph_Image class

- inc/class-wpseo-meta.php
- readme.txt
* Reverts the `wpseo_focuskw_strippable_chars` filter as there is some breakage that needs further investigation.
*
* Determine that the filter is no longer being executed when added.
Reverts #9415 
Fixes https://github.com/Yoast/wordpress-seo/issues/9561
> Reverts the wpseo_focuskw_strippable_chars filter

- inc/class-wpseo-content-images.php
- wp-seo-main.php
* N/A
* On post save, just remove the cached images for that post.
* Have images in your content
* View the source of the post page.
* Change the images
* See the OG-tags being changed.
> Remove image cache on post save

- frontend/class-opengraph-image.php
- inc/class-wpseo-image-utils.php
- readme.txt
* Re-adds `wpseo_opengraph_image_size` filter. This will completely override any automatic size determination our code does. This filter now also applies to all ways an `og:image` can be determined: In the content, as a featured image or as set in our Facebook image setting.
* This will completely override any automatic size determination our code does. This filter now also applies to all ways an `og:image` can be determined: In the content, as a featured image or as set in our Facebook image setting.
* Add this filter in your code an set the size to 'large' for example.
* Check the `og:image` tag and see that the 'large' size is used.
* Set the size that is too small.
* Check that …
> Re-adds `wpseo_opengraph_image_size` filter.

- frontend/class-opengraph-image.php
- tests/frontend/test-class-wpseo-opengraph-image.php
* Adds backwards compatibility for the `add_image` function in `WPSEO_OpenGraph_Image`.
*
* Check that the test passes.
Fixes #9609
> Added backwards compatibility to opengraph image class

- frontend/class-opengraph-image.php
- inc/class-wpseo-image-utils.php
- tests/frontend/test-class-wpseo-image-utils.php
When an image was used that didn't meet the image requirements we
didn't try different image sizes. This change makes sure that we
always try the image sizes that are specified in the
`wpseo_image_sizes` filter. Even if the original image is too big.
Fixes #9627
> Fix OpenGraph image detection

- js/src/assessors/taxonomyAssessor.js
- js/tests/taxonomyAssessor.test.js
* n/a
* Keyword length assessment was added to taxonomy assessor test.
- Check out the branch.
- Use the browserified example. Don't forget to run a grunt build:js.
- Add a text
- Keep the keyword empty - you should receive feedback that keyword was not entered
- Enter a keyword - you should receive feedback concerning length of your keyword length.
- Make sure this functionality also works when cornerstone is switched on.
- Check out this in wordpress-seo.
- Run yarn install in the plugin's directory.
- Run yarn add "git+https://github.com/Yoast/yoastseo.js#stories/1312-improve-keyword-length-assessment" in the plugin's directory.
- Navigate to node_modules/yoastseo and run yarn …
> Add keyword length assessment to taxonomy assessor test

- webpack/webpack.config.default.js
* n/a
*
* Attempt to build WordPress SEO with a custom YoastSEO.js branch. Webpack should now succeed.
> Fixed the broken webpack config by adding YoastSEO.js

- webpack/webpack.config.default.js
* This makes building YoastSEO.js work when it is linked using `yarn link`.
* Does @afercia's build work?
> Don't resolve symlinks in webpack

- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
* N/A
* The solutions from https://github.com/Yoast/wordpress-seo/pull/9527 to implement the react snippet preview into the term scraper.
* Update `require` to `import` and reorder them a bit to at least have a division of external & internal.
* Use `define( 'YOAST_FEATURE_SNIPPET_PREVIEW', true );` in `wp-config.php` to display the React version.
* Go to a term edit page.
* Check if the snippet editor behaves the same as the old one.
* Check if the old snippet editor still behaves the same like it did before this.
~~* [ ] I have added unittests to verify the code works as intended~~
Fixes #9536
> Apply post scraper snippet preview things to term scraper

- inc/class-wpseo-meta.php
* Fixes typo in `$field_defs` parameter description for `wpseo_metabox_entries` filter.
Fixes #9363
> Fix typo in 'wpseo_metabox_entries' filter docs

- inc/class-wpseo-image-utils.php
- tests/frontend/test-class-wpseo-image-utils.php
* Fixes a bug where the filesize could not be determined due to invalid absolute path determination.
* Prefix the basedir only if it is not already present at the start of the path.
* Have an image with an absolute path (this is default behaviour in my test environment when uploading an image)
* Make sure the path is correct after running through the absolute path method
* Query Monitor gives a notification of a suppressed warning if it occured before, even with the muted filesize check
Fixes https://github.com/Yoast/wordpress-seo/issues/9682
> Only add basedir if it does not already exists

- js/src/analysis/PostDataCollector.js
- js/src/analysis/snippetEditor.js
- js/src/components/SnippetPreviewSection.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
* N/A
* Add the title & description templates that exist in classic to the React version.
* Apply a template if the variable is empty on load.
* If a value equals a template, use an empty value to send to the server (hidden input).
* Use the initial data set to apply templates.
* Use the store subscribe hook to keep the data free of templates.
* Extract this logic into a separate file.
* Checkout branch & build.
* Use `define( 'YOAST_FEATURE_SNIPPET_PREVIEW', true );` in your `wp-config.php` to enable the React snippet preview.
* Edit the title & description in the snippet editor on posts & pages as well as the taxonomies.
* You should see the initial value in the store after …
> Implement templates in the React Snippet Editor

- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-replacevar-plugin.js
* N/A
* Because we need category replacevars quickly, we decided to add the store to the replacevar plugin and dispatch the data to the store on the spot.
* Custom taxonomies _should_ also work. If the taxonomyName is not `"category"`, we prefix it with `ct_`, and it should be replaceable in the snippet preview. 
* Use the %%category%% replacement in the Snippet Editors, and create some categories on your post. %%category%% should be replaced by all the **checked** variables, separated by a comma (and a space).
* To test the custom taxonomies, make a custom taxonomy (for example "chapter"), and call `%%ct_chapter%%` in the snippet preview. It should be replaced by the chapter title …
> Implement working category replacevar for posts

- .travis.yml
- cli/class-cli-premium-requirement.php
- cli/class-cli-redirect-base-command.php
- cli/class-cli-redirect-command-namespace.php
- cli/class-cli-redirect-create-command.php
- cli/class-cli-redirect-delete-command.php
- cli/class-cli-redirect-follow-command.php
- cli/class-cli-redirect-has-command.php
- cli/class-cli-redirect-list-command.php
- cli/class-cli-redirect-update-command.php
- composer.json
- wp-seo-main.php
* Adds WP-CLI commands to manage redirects.
* The following subcommands are implemented under the `redirect` command root:
`redirect create` - Creates a new Yoast SEO redirect.
`redirect delete` - Deletes an existing Yoast SEO redirect.
`redirect follow` - Follows a Yoast SEO redirect chain to get the final target it resolves to.
`redirect has` - Checks whether a given Yoast SEO redirect exists.
`redirect list` - Lists Yoast SEO redirects.
`redirect update` - Updates an existing Yoast SEO redirect.
* The check for premium has been moved out of the individual commands and will bew processed on the `before_invoke` hook for each premium command. The code can be deployed with the free codebase, as the logic is not contained within …
> Add WP-CLI commands to manage redirects

- js/src/wp-seo-post-scraper.js
* Updates the active keyword in the state whenever changes are made in the keyword field 
* Adds the store dispatch call to the updatedKeyword callback function, which now correctly sets the new keyword before updating the analyses.
* Go to the snippet editor and change the keyword
* The `WPSEO_SET_ACTIVE_KEYWORD` action should be fired
* The `activeKeyword` in the state should be set to the new keyword
Fixes #9704
> Update the active keyword in the state when it has been changed.

- js/src/wp-seo-term-scraper.js
* N/A
* Add data equality checks for the snippet editor data to the term scraper.
* Check if the snippet editor data updates correctly on terms.
Based on https://github.com/Yoast/wordpress-seo/pull/9738
Fixes #
> Add data equality checks for the snippet editor data

- wp-seo-main.php
* Adds WP-CLI commands to manage redirects, use `wp yoast redirect` to see the list of commands available.
* Added `yoast` as command prefix for the CLI commands.
* Enter your Vagrant
* Go to the root of the WordPress installation you have checked out this branch
* Run `wp help yoast` or `wp yoast redirect` to see that the command can be executed and provides information about the commands that can be run.
Fixes #9763
> Prefix CLI command with `yoast`

- js/src/components/SnippetPreviewSection.js
* N/A
* I'm very proud of my one-character fix 🤓 
* Add multiple spaces to the slug field in the snippet editor.
* Those spaces should be changed into a single dash in the slug in the preview.
Fixes https://github.com/Yoast/wordpress-seo/issues/9795
> Strip multiple whitespaces in slug

- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
* When the slug in changed in WP (right under the title), the slug in the snippet preview should be updated as well.
* sent an action updateData to the store, with the new slug. Removed the old method, which uses a function that does not exist anymore.
* Visit a post page. (make sure the permalink structure is post).
* Change the slug (right below the title).
* Check if the slug is also changed in the snippet preview.
* Check console for errors.
Fixes #9771 
Fixes #9767
> Update slug in snippet preview when the slug has been changed in WP

- admin/help_center/class-template-variables-tab.php
- admin/help_center/template-variables-tab.php
- admin/metabox/class-metabox.php
- admin/pages/metas.php
- inc/wpseo-functions-deprecated.php
- tests/admin/help_center/test-class-help-center-template-variables-tab.php
- tests/admin/links/test-class-link-watcher.php
Class that adds the Template Variables Help Center tab.
* Adds a tab to the Help Center on posts/pages and custom post types which explains which template variables can be used in the Snippet Preview.
* Moved all functionality to a class
* Added ability to provide priority for placement-control
* Added registration of required stylesheet in the same class
* Go to a Post/Page edit page
* Open the Help Center
* See the Tab being introduced
* Open the tab
* See the styling of the table being similar as on the Search Appearance Help Center tab
Fixes #9804
> Introduce Template Variables Help Center tab

- grunt/custom/i18n-clean-json.js
Because of the translation toolchain changes the textdomain wasn't set correctly in the JSON files. This change fixes that.
* Build the translation files using `grunt build:i18n`.
* Make sure that the translations for YoastSEO.js (content analysis results) work. I've tested it with Dutch.
Fixes #9766
> Fix translations for YoastSEO.js

- js/src/components/SnippetPreviewSection.js
- js/src/wp-seo-replacevar-plugin.js
* N/A
This solution does not fix the extra replace vars described in the issue.
- `%%ct_product_tag%%`
- `%%ct_pa_product-attribute-slug%%`
* Use the pluggable modifications where plugins can hook into the replacement variables.
* Install the plugins: `WooCommerce`, `Yoast SEO: WooCommerce`, and `Perfect WooCommerce Brands`.
* Create some data: a brand and a product with: short description, sku, price and brand.
* Test if these work in the Snippet Editor.
Fixes #9773
> Fix WooCommerce replacement variables

- admin/class-admin.php
- admin/class-cornerstone.php
- admin/filters/class-cornerstone-filter.php
- admin/filters/class-stale-content-filter.php
- admin/filters/class-stale-cornerstone-content-filter.php
* Adds a filter for stale content (cornerstone content which hasn't been updated in the last 6 months).
* Mark some content as cornerstone content
* Modify the 'post_modified' column for one item in the database (phpmyadmin) with a date set more than 6 months ago.
* The post should be visible in the post overview when using the cornerstone filter and will also be visible with the stale content filter.
* When setting the post_modified date within that last 6 months, the post will be hidden in the stale content filter.
Fixes #8309
> Implement stale content notification

- admin/help_center/class-template-variables-tab.php
- admin/taxonomy/class-taxonomy.php
- tests/admin/help_center/test-class-help-center-template-variables-tab.php
* Adds "Template explanation" tab to the Help Center of the Term edit page.
* As on the Post edit pages, the Help Tab also needs to be present on the term-edit page.
* Go to a term and edit it
* Open the Help Center and see the "Template explanation" tab present.
* The styling of the content should be zebra-striped table rows.
> Add template variable tab to Term Help Center

- inc/class-wpseo-replace-vars.php
- js/src/containers/SnippetEditor.js
- js/tests/containers/SnippetEditor.test.js
- package.json
- yarn.lock
* Changes the maximum length of the the meta description assessment from 320 to 156.
*
Please look at https://github.com/Yoast/YoastSEO.js/pull/1497 and https://github.com/Yoast/yoast-components/pull/547 first.
* Please test in the classic editor.
* Use define( 'YOAST_FEATURE_SNIPPET_PREVIEW', true ); to see the react snippet editor (for example on line 46 in `class-metabox-formatter.php`, or in your `wp-config.php`).
* Link the branches from https://github.com/Yoast/YoastSEO.js/pull/1497 and https://github.com/Yoast/yoast-components/pull/547.
* Link `yoastseo.js` and `yoast-components` to `wordpress-seo`. 
* Link `yoastseo` to `yoast-components` using `ln -s [path to your local …
> Change max meta description length

- admin/help_center/class-template-variables-tab.php
* _N/a_
* None
* Open the Search Appearance > Content types -or- post edit page -or- term edit page
* Open the Help Center
* See the title of the Tab and the Title in the explanation changed to "Snippet variables" instead of "Template explanation"
Fixes #9832
> Change the term "template" to "snippet"

- js/src/analysis/keywordTab.js
Because we only want the CONTENT_ANALYSIS_SET_SEO_RESULTS_FOR_KEYWORD action to dispatch when you have the analysis open, we check for that. 
But when you keyword consists only of numbers ( an unlikely use case, but still ), the check retrieves the keyword from the tab as a number instead of as a string. 
Because of that the strict check fails, the action isn't dispatched, en the entire analysis section collapses. which you can see in the screenshot below.
* Fixed numbers-only keywords causing the analysis to fail.
* Ensured the function fetching the keyword from the tab returns a string. If there's a better way to cast to string, or if it's better to cast only in the function checking if the keyword matches the keyword in the …
> Fixed the analysis failing on numbers only keyword

- admin/formatter/class-metabox-formatter.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-content-fields.php
- js/src/analysis/PostDataCollector.js
- js/src/analysis/TermDataCollector.js
- js/src/analysis/classicEditorData.js
- js/src/components/SnippetPreviewSection.js
- js/src/edit.js
- js/src/wp-seo-metabox.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
- js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
- js/tests/containers/SnippetEditor.test.js
* Hides the React Snippet Editor under a feature flag and restores the old snippet editor.
*
* Make sure the classic snippet editor works as expected.
Fixes #
> Revert "Merge pull request #9720 from Yoast/stories/remove-old-snippet-editor"

- readme.txt
* _The link to the changelog for older versions is now clickable._
For whatever reason, this URL is not automatically made clickable, so let's make sure it's clickable.
This can be seen/experienced on:
* https://wordpress.org/plugins/wordpress-seo/#developers
* When clicking on the "_View version x.x.x details._" link on the `Updates` page from within a WP install.
If someone has a better suggestion for link text, please let me know.
* Not testable until the next release has been posted on wp.org.
> Readme/Changelog: make a link clickable

- js/src/analysis/classicEditorData.js
- js/src/helpers/replacementVariableHelpers.js
- js/tests/helpers/replacementVariableHelpers.test.js
*N/A
* moved seperator decoding logic from yoast components to wpseo. It was an array in yoast components, but is an object here, so adapted the logic to the new situation.
* With wordpress-seo and yoast-components linked, check if all seperators show up as symbols, rather than as codes.
Fixes #https://github.com/Yoast/yoast-components/issues/550
> moved seperator decoding logic from yoast components to wpseo

- admin/class-admin.php
- js/src/wp-seo-admin.js
* Restores the missing warning for wrong replacement variables.
This is a copy of @afercia 's [PR](https://github.com/Yoast/wordpress-seo/pull/9869) just to branch it from release/7.6 without taking trunk commits with it.
* the translation string `variable_warning` used to be localised in the `wpseoAdminL10n` script
* after the Help Center refactoring `wpseoAdminL10n` is now enqueued only in the post and term pages
* this PR restores the missing string putting it in the `wpseoAdminGlobalL10n` localized script
* also, changes the `change` that triggered the check to `input` event:
- modern browsers support the `input` event 
- this way, the warning is displayed as soon as users finish typing a wrong variable, and also on paste
- …
> Restore variable_warning and use onInput.

- admin/class-option-tabs-formatter.php
This allows to hook into `wpseo_option_tab-metas_media` to override the media config data.
* _N/A_
* Add a general filter for tab content
* Add a filter:
```
add_filter( 'wpseo_option_tab-metas_media', function() {
return 'hoi';
});
```
* See the content being displayed on http://local.wordpress.test/wp-admin/admin.php?page=wpseo_titles#top#media
Fixes https://github.com/Yoast/search-index-purge/issues/7
> Add filter for option tab content

- inc/class-upgrade.php
- inc/options/class-wpseo-option-titles.php
Set option value on upgrade routine
Use default "false" for new installs
* _N/A_
* 
*
Fixes https://github.com/Yoast/search-index-purge/issues/21
> Add option to determine Media Purge message on

- frontend/class-frontend.php
- inc/class-rewrite.php
- inc/sitemaps/class-sitemaps-router.php
* Adds X-Redirect-By header to all redirects. Making the origin of redirects much easier to debug.
* Because redirects are not abstracted I just added the `header` call before every redirect.
* Test a redirect using a tool such as `curl -I` and see the X-Redirect-By header
> Add X-Redirect-By header to all redirects

- admin/class-admin-media-purge-notification.php
- admin/class-admin.php
Conditions:
- attachments are not redirect to the file
- attachments are not "noindexed"
Dismissed by setting the option "is-media-purge-relevant" to `false`
Bypassing any introduced functionality
* _N/A_
* Added a hidden field on the newly introduced filter (not returning anything, so not affecting the content)
* Introduced conditions to the manage_notification method
* Have the `is-media-purge-relevant` set to `true` (in `wpseo_titles`, either via Upgrade routine or directly in the database)
* Have the Media settings: 
* See the notification being added to the notification center
* Using the dismiss link will reload the page and the notification should be gone
Fixes …
> Add notification when conditions are met

- inc/class-upgrade.php
Only when all conditions are met the purge is relevant.
If the attachments are no-index'd, the purge is less relevant and we dont want to show any message.
* _N/A_
* Made the checks the same as for the Dashboard notification
* This will not show when `attachments` are set to `noindex`
* Set the media settings to "No", "No"
* Set the version of Yoast SEO back to 7.4 (using the Test Helper plugin)
* Refresh the page
* Set the media settings to "No", "Yes"
* Don't see the yellow message (which is shown without this patch)
Fixes #
> Relevancy check tighten up

- readme.txt
Adds YoastSEO.js changelog items from YoastSEO.js releases 1.32, 1.33, and 1.33.1.
> Add Yoast seo.js changelog items

- js/src/components/SnippetPreviewSection.js
- js/tests/components/SnippetPreviewSection.test.js
* N/A
* Caught them in an if-statement. Tried to do it in the regex at first, but it wouldn't cooperate.
* run the tests.
* Visit the react snippet editor in a post
* write a slug ending in a space, and observe the dash not showing in the snippet preview.
Fixes #9868
> Removed trailing spaces changing to dashes

- admin/class-admin-init.php
* Link to the Customizer control for the tagline directly when highlighting it should be changed.
* When you provide a query argument like `autofocus[panel]`, `autofocus[section]` or `autofocus[control]` to the Customizer, the respective panel/section/control will be initially focused. This can be used here to point the user directly to the correct control for the tagline (the setting is internally called `blogdescription`).
* Ensure that the tagline for your site is set to the default WordPress tagline ("Just another WordPress site" in English).
* Go to the Yoast SEO dashboard, and see the notification that reminds you that you still use the default tagline.
* Click the link and …
> Link to the Customizer control for the tagline directly when highlighting it should be changed

- wp-seo-main.php
* Fix a PHP notice that could be triggered when the `opcache.restrict_api` directive was enabled.
* As decided on the issue, the most straightforward way to fix this is to mute the call to the function. This is safer than trying to read the configuration value directly via `ini_get()` or another way.
* Install an older version of Yoast SEO on your WordPress site via Composer.
* Set the `opcache.restrict_api` directive to '1' in the `php.ini` configuration for the server.
* Update to the version from this PR via Composer.
* Access the WordPress site again, and ensure no notice `Zend OPcache API is restricted by "restrict_api" configuration directive` is thrown.
Fixes #9800
> Mute the call to opcache_reset() to prevent notices when opcache.restrict_api is set

- admin/class-admin.php
- admin/class-yoast-form.php
- admin/class-yoast-network-admin.php
- admin/class-yoast-network-settings-api.php
- admin/menu/class-network-admin-menu.php
- admin/pages/network.php
- admin/views/tabs/network/general.php
- inc/options/class-wpseo-option.php
- tests/admin/test-class-yoast-network-admin.php
- tests/admin/test-class-yoast-network-settings-api.php
* Implements the same tabbed layout in the plugin's network settings screen that is also used in the plugin's site settings screens.
* This is the follow-up PR to #9690. It should be merged into the feature branch for #9447.
* A new `Yoast_Network_Admin` class is introduced that contains network-admin specific hooks and utility methods. It holds for example the method for getting a list of site choices (e.g. for dropdowns), and it also takes care of the restoring site functionality (both of which were previously "inline functions" in the `network.php` screen template file. This class is only initialized if the current context is a multisite and we're currently in the network admin.
* A few improvements over the original …
> Use tabbed layout in the network settings screen

- js/src/analysis/classicEditorData.js
* Fixes a JS error in the post scraper that occurred when the hidden slug input would be there on page load.
Thanks @moorscode for spotting the error ! 
* Fixes jQuery call to fetch the value to default JS.
* Multiple plugins where reported to trigger this error:
- [Shortcodes Ultimate 5.0.4](https://wordpress.org/plugins/shortcodes-ultimate/)
- [Custom Permalinks 1.2.24](https://wordpress.org/plugins/custom-permalinks/)
- [Permalink Customizer 1.3.9](https://wordpress.org/plugins/permalinks-customizer/)
* Install and activate a plugin from the above list.
* Open the JS console.
* Create a page or post and publish it.
* There should no longer be a JS error.
Multiple issues found for …
> Fix JS error in the post scraper

- css/src/yst_plugin_tools.scss
* Fixes a bug where generic css styling has been applied on non Yoast form fields.
*
* Follow the steps in the issue to make sure this pull fixes that issue.
* Make sure nothing has been changed in the styling for the Yoast Settings.
Fixes #9954
Fixes #9969
Fixes #9955
> Wraps generic styles in the class wpseo_content_wrapper

- admin/class-database-proxy.php
- tests/admin/test-class-database-proxy.php
* Fixes a bug where suppressed MySQL errors are logged when 'upserting' a record to our Yoast meta table.
* Have the query monitor active.
* Save a post to the database and MySQL errors are given (on trunk)
* Checkout this branch and see no MySQL errors are given.
Fixes #8650
> Prevent duplicate key errors

- frontend/class-frontend.php
- tests/doubles/frontend-double.php
- tests/frontend/test-class-wpseo-frontend-redirects.php
* Fixes a bug where the attachment url was redirected to `wp-admin` when the attachment is not located on the Site URL domain.
*
* This pull request is pretty hard to test. I've seen this happening on my personal blog where I am using a CDN (Amazon). This is causing wrong redirects in combination with the Offload S3 plugin.
* Please verify if the old situation still works. This means that attachment url will be redirect to the attachment image itself (when the option has been enabled under search appearance - media.
Fixes #9880
> Replace the function wp_safe_redirect by wp_redirect

- js/src/values/defaultReplaceVariables.js
When it had a default, it also (unwantedly) showed up in the list of suggestions where it didn't belong. For example, term_title would show up in the suggestions on a post, and would be replaced by 'undefined'. This is bad UX.
Category was dynamically added and added through the defaults. This resulted in an errror nabout duplicate IDs.
- Go to a post. Type '%t'. `term_title` shouldn't show up in the suggestions.
- Go to a tag. Type '%t'. `term_title` should show up in the suggestions.
- Go to a category. Type '%t'. `term_title` should show up in the suggestions.
- Go to a post. Use %%category%%. No console errors should be thrown about duplicate IDs.
> Remove term_title and category replacement variable defaults

- package.json
- yarn.lock
* N/A
* Updated Draft.js mention plugin to match yoast-components.
* Draft-js and the mention plugin are only used for styling. I updated this because it had a larger margin-top of the snippet editor suggestions popover. And now it has a smaller margin-top.
Fixes #9604
> Update Draft.js mention plugin to match yoast-components

- package.json
- yarn.lock
* Bumps YoastSEO.js to 1.34.0
* Check whether nothing breaks.
> Bump YoastSEO.js to 1.34.0 and yoast-components to 4.2.0

- frontend/class-opengraph-image.php
- frontend/class-twitter.php
* Fixes a bug where images from password protected posts could end up in OG image tags. 
* Create a post and insert a couple of images.
* Password protect the post.
* View the source code of the post and verify that, while the post is password protected, there are OG links to some images. You can recognise these by their `meta property="og:image"` and `meta name="twitter:image"` tags. 
* Switch to this branch and reload the page: The tags should be gone, there should be no links to images in the pw protected post anymore.
Fixes #9988
> Added a password check to the og image output

- admin/class-help-center.php
* Adds a check to only display the Get Premium message next to video tutorials if the user is not running Yoast SEO Premium.
* As the logic for these video descriptions is implemented in the Free version, I decided to add the logic here. Please note that this will also have to be tested in Premium via a separate branch (see test instructions).
**Free**
* After checking out this branch, go to SEO -> General
* Click on the 'Need help?' button.
* Notice the following scenario:
**Premium**
* After checking out the `1696-testing-only` branch in Premium, go to SEO -> General
* Click on the 'Need help?' button.
* Notice the following scenario:
**NOTE: Please delete the `1696-testing-only` …
> Only add Go Premium video description if user is using Free

- js/src/wp-seo-post-scraper.js
* Fixes a problem where multiple keywords would only show results for the main keyword.
* Removed the dispatcher for the set_active_keyword action from getAppArgs. 
This was originally added to make sure the assessment results updated when the keyword was updated. It had the unintended side-effect of resetting the active keyword to the first keyword, regardless of keyword tab. 
After removing this dispatch, all seems fixed, even the original issue doesn't seem present, but please test to make sure the SEO results are updated when you change the focus keyword.
- for wpseo-free:
Checkout this branch.
Change the focus keyword a couple of times
Check if the SEO results keep updating …
> Fixes a problem where multiple keywords would only show results for the main keyword.

- admin/formatter/class-post-metabox-formatter.php
- admin/formatter/class-term-metabox-formatter.php
- js/src/analysis/getTitlePlaceholder.js
- js/src/analysis/snippetEditor.js
- tests/formatter/test-post-metabox-formatter.php
- tests/formatter/test-term-metabox-formatter.php
* Stops `-` being hardcoded in the title template for the snippeteditor.
* Change the separator on Search Appearance
* Removes the template for a post
* Adds a new post and see the right template is used.
* Do the same for the term.
Fixes #9912
> Move title fallback from js to PHP

- js/src/components/contentAnalysis/Results.js
* Fixes an issue where the analysis results where being hidden while updating.
* Use cached analysis results when the new results are equal to `null`.
Check the following steps in both free and premium:
1. Go to Post
2. Scroll to Focus keyword
3. Enter "test"
4. Check that Analysis is updated (Problems with something like "The focus keyword 'test' does not appear in the SEO title.")
5. Change Focus keyword to "testtest"
6. Observe the delay in updating the Analysis
To make it possible to test in premium:
1. Ensure you are in the latest `release/7.7` branch of premium: `git checkout release/7.7 && git pull`.
2. Add free as a remote: `git remote add free …
> Use cached analysis results

- js/src/wp-seo-replacevar-plugin.js
* Fixes a bug where the term title snippet variable would be replaced by 'undefined' instead of an empty string on posts and pages.
* Before, term_title would be separately replaced by the termtitleReplace function before all other replacevars would be replaced via redux or the replacevar plugin. It was being replaced by `this._app.rawData.name`, which is undefined for posts and pages. I've removed the termtitleReplace function, because %%term_title%% can be replaced in the same way as all/most other replacevars.
* Test the %%term_title%% replacevar on posts, custom posttypes, and pages. It should be replaced by an empty string. NB: term_title is not in the suggestions, so you …
> Don't separately replace term_title before redux replacevars are used

- js/src/values/defaultReplaceVariables.js
- js/src/wp-seo-replacevar-plugin.js
* N/A (fix for new thing in 7.7 changelog)
* Adds the userid as replacevar in JS.
* Add %%userid%% in posts, pages, custom stuff.
Fixes #10038
> Deprecate userid in snippet editors

- inc/class-wpseo-replace-vars.php
* Fixes a bug where PHP notices got triggered on archive page when `%%pt_single%%` and/or `%%pt_plural%%` are used as a template.
* Follow the steps mentioned in the issue and see it is solved.
Fixes #10083
> Fix php notice on pt_??? replace vars

- package.json
- yarn.lock
* Bumps yoast-components to 4.3.0
* Check whether nothing breaks.
> Bump yoast-components to 4.3.0

- admin/views/class-view-utils.php
- admin/views/tabs/metas/post-types.php
- js/src/components/SnippetPreviewSection.js
- js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
- yarn.lock
* Disables the Paper styling in Search Appearance and removes a margin that caused for some odd styling.
* Please note that this PR depends on an update from Yoast Components.
* Checkout this branch and ensure the latest **develop** version of Yoast Components is properly installed.
* Navigate to SEO -> Search Appearance and note that there's no Paper style surrounding the Snippet Editor anymore.
* Navigate to Posts -> Add New and ensure the Snippet Editor looks the same way as it used to.
Depends on https://github.com/Yoast/yoast-components/pull/615
> Removed a margin and disabled paper styling in Search Appearance

- package.json
- yarn.lock
* Bumps yoast-components to 4.4.0
* Check whether nothing breaks.
> Bump yoast-components to 4.4.0

- Gruntfile.js
- admin/class-admin-asset-yoast-components-l10n.php
- admin/class-config.php
- grunt/config/aliases.yaml
- grunt/config/clean.js
- grunt/config/convert-pot-to-wp.js
- grunt/config/copy.js
- grunt/config/po2json.js
- grunt/config/shell.js
- grunt/custom/i18n-clean-json.js
- js/src/configuration-wizard.js
- js/src/helpers/i18n.js
- js/src/redux/reducers/snippetEditor.js
- js/src/search-appearance.js
- js/src/values/defaultReplaceVariables.js
- js/src/wp-seo-dashboard-widget.js
- js/src/wp-seo-help-center.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
- js/tests/redux/reducers/snippetEditor.test.js
- package.json
* _Not applicable_
* Copied most of the `yoast-components` translation pipeline.
* Run `grunt build:i18n`.
* Set your installation to Dutch
* You should now see 'Snippetvoorvertooning' in your snippet editor.
Fixes #10010
> Implements translations for wordpress-seo JS textdomain

- admin/watchers/class-slug-change-watcher.php
* n/a
* I've use `is_post_type_viewable` which checks if the post type is publicly queryable or has public access.
* Follow the steps in #10125
* I've change some piece of code (simplified) that needs some verification. Create a menu under appearance and add some menu items to it. Remove a menu item. The notification shouldn't be visible.
Fixes #10125
> Adds logic to check if a post type is viewable

- js/src/analysis/data.js
- js/src/containers/SnippetEditor.js
* N/A
* The replacevar plugin was quite slow in updating the rawData when title and excerpt became empty. On our end (in the redux store) we replaced the empty values with `%%title%%` and `%%excerpt%%` etc., as a fallback for certain replacement variables that weren't filled via React. This caused the title to be replaced with the slow rawData when it was emptied. Now, we do not fallback for fields to which we are subscribed via React.
* Put `%%title%%` in the title snippet editor field.
* Put `%%excerpt%%` and `%%excerpt_only%%` only in the description.
* Put a large title in the editor title.
* Put a large excerpt in the excerpt (excerptception :trollface: )
* Select all in the …
> Skip fallback for empty title and excerpt

- admin/views/tabs/metas/post-types.php
* N/A
* Removed paper style and added a header to more clearly describe what the Breadcrumb title is used for. This combination should fix any margin issues that may have been present.
* Ensure you've ran `yarn`, `grunt build:css` and `grunt build:js`.
* Ensure you have the Yoast Test Plugin installed and have activated the custom post types.
* Go to SEO -> Search Appearance
* Toggle open one of the two custom post types.
* Determine that there's a nice amount of margin + a title present.
Fixes #10132
> Added title for Breadcrumb title field to better describe its goal

- js/src/search-appearance.js
`append` is not supported by IE and Edge. We should use `appendChild` instead.
Fixes an issue where the snippet editors were not shown in IE and Edge.
> Replace append by appendChild

- inc/class-upgrade.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
* Fixes a bug where disabling the `post_format` archive would result in it actually being enabled and vice versa.
* No upgrade routine was introduced because we cannot determine if someone deliberately turned the option on or off. The option itself hasn't changed either.
* Add a new post and set the Post Format to something like Quote. Save the post.
* Go to SEO -> Search Appearance -> Taxonomies -> Format
* Under the Format section, set `Format-based archives` to Enabled and `Show Format in search results?` to Yes.
* Open the sitemap and determine that there's a `post_format-sitemap` entry.
* Click the entry and see that the Post Format you applied to your post, is also listed.
* …
> Fix post format toggle

- inc/class-wpseo-replace-vars.php
- js/src/search-appearance.js
* N/A
* Label creation logic for prefixed replacement variables is now identical to the editor's snippet editor redux store's logic.
* Have custom fields with spaces and without spaces. Also, custom taxonomies if you want/can. Tip: use `yoast-test-helper`.
* See how the labels look in the redux store on a post.
* Verify that they look the same on the search-appearance page.
* Look specifically for the replacevars that have `ct_` (and `ct_desc_`), `cf_`, and `pt_` prefixes.
Fixes #10098
> Implement logic for labels

- admin/config-ui/components/class-component-suggestions.php
* N/A
* Checkout this branch. 
* Go to page 11 of the configuration wizard, see block about the basic SEO training instead of the copywriting block. The text, title, video, and link should be replaced. 
Fixes #10086
> Replaced info on copywriting training with basic seo

- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy.php
- js/src/values/defaultReplaceVariables.js
- readme.txt
* Restores `currentyear` as a snippet variable.
* N/A
* Go to a post. Type %c in a title or description field. 'Current year' should show up. The snippet preview should shoe 2018, and the progress bars should respond to this addition.
* Go to Search Appearance. Type %c in a title or description field. 'Current year' should show up.
Fixes #
> Bring currentyear back as a replacevar

- admin/class-config.php
- admin/formatter/class-metabox-formatter.php
- js/src/components/SnippetPreviewSection.js
- js/src/edit.js
- js/src/search-appearance.js
- js/tests/components/SnippetPreviewSection.test.js
- js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
- package.json
- yarn.lock
**Cannot be merged before https://github.com/Yoast/yoast-components/pull/629 has been merged and yoast-components has been released**
* Fixes the styling of the snippet editor and snippet preview for right-to-left languages in both the metabox and in the Search Appearance settings.
* Uses `is_rtl()` in the php to determine whether we're dealing with an RTL or LTR language. 
* Adds a ThemeProvider that passes the language direction to the components.
* Link https://github.com/Yoast/yoast-components/pull/629
* Set your language to Hebrew, or another RTL language which is translated.
* Go to the metabox and look at the styling of all components in the snippet preview section. Don't …
> Fix styling of snippet editor and preview for RTL

- admin/class-config.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy.php
* Disables WordPress' automatic conversion of emoji to images on every page where the snippet editor is present. This conversion is not compatible with React or content editable fields and broke the snippet editor.
* We need to do this both on term and post edit.
* Use a character such as `✔` in the snippet editor and still be able to remove it.
Fixes #10193
> Disable `wp-emoji` in combination with the snippet editor

- js/src/analysis/snippetEditor.js
- js/tests/analysis/snippetEditor.test.js
* Fixes a bug where title and description templates were saved to the database.
* This bug was caused by adding spaces after each replace var, which meant that the template was compared to the template + a space at the end. Those two values were different, which meant the template + space was saved to the database.
* Solution: Trim title and description data before comparing it to the template.
* Look for the hidden input fields `yoast_wpseo_title` and `yoast_wpseo_metadesc` in the html inspector. It's value should be empty when creating a new post, and stay empty when you open the snippet editor. If you change the title and meta description in the editor, the hidden input field …
> Fix title and description template saving

- admin/views/class-view-utils.php
- admin/views/tabs/metas/media.php
* Adds the white background to the template of media on the search appearance page.
* Added a `paper style` parameter to show-post-type-settings (used by media), false by default, as it used to be. Set it to true where media calls it.
* Visit search appearance > media. Set the toggle to no, check if the seo_title/meda desc have the paper style.
Fixes #10148
> Add paper to the media templates

- admin/taxonomy/class-taxonomy.php
- frontend/class-frontend.php
* Fixes UI issue that happend when do_shortcode was run on category descriptions in the admin list. Additionally, fixed rendering of shortcodes in category descriptions on the frontend. 
* Moved both the method and the filter calling `custom_category_descriptions_add_shortcode_support` from from the admin to the frontend, so it's called in the right place. 
* Deprecated `custom_category_descriptions_add_shortcode_support` in `class-taxonomy.php` instead of removing it since it is public. 
* Go to Posts->Categories, see the category descriptions on the right side. 
* Add a category with shortcodes in the description, for example a [gallery], and note how this results in images in the …
> Removed filter that runs do_shortcode on category descriptions in admin

- admin/views/tabs/metas/post-types.php
- css/src/yst_plugin_tools.scss
- js/src/wp-seo-admin.js
- Improved accessibility of the collapsible sections in Search Appearance > Content Types
- moves the text inside the button to avoid an empty interactive element
- uses `aria-expanded` to give feedback about the toggled state
- completely hides the icon from assistive technologies using `aria-hidden="true"`
- uses the same "circular focus style" used in other places, for example on the Help button
- using a screen reader, go to one of the expandable section headings
- check it's announced with the content type name and the toggled state
- check the toggled state change is announced when toggling the panel
- check the focus style is rendered nicely in all browsers
Re: the focus …
> Improve the Search Appearance - Content Types collapsible sections a11y

- js/src/helpers/i18n.js
* N/A
* Export the `setTextdomainL10n` helper to enable setting a domain in premium.
* Not really needed. Does it still build?
* No Jed error in combination with the fixes issue.
Fixes https://github.com/Yoast/yoast-components/issues/622
> Export text domain helper

- inc/options/class-wpseo-taxonomy-meta.php
*  Fixes a bug where a notice ("Notice: Trying to get property of non-object") is given when the `$term->taxonomy` isn't set before it is used.` Props to [bainternet](https://github.com/bainternet)
Fixes #10143
> Make sure $term->taxonomy is set before using it, fixes #10143

- frontend/class-opengraph.php
* Fix error when $terms[0] does not exist (such as when there is only $terms[1].)
* Use `reset($terms)->name` instead of `$terms[0]->name` because the first element may be `$terms[1]`.
* Use `!empty($terms)` instead of `$terms !== array()` because it is clearer.
* Select more than more category.  
* Do NOT set a Primary category
* Add `'get_the_categories'` filter that unsets `$term[0]` _(as a commercial theme a client was using does. It removes parent categories if child categories are selected.)_
Fixes #
> Fix error when $terms[0] does not exist in open-graph

- js/src/analysis/PostDataCollector.js
* N/A
While debugging something else, came across this direct call of `runAnalyzer`. Changed to call `app.refresh` on blur instead. Going through the debounce.
* Check that the assessments still properly update after blurring the focus keyword fields.
Fixes #
> Change direct call of the analyzer to refresh

- grunt/config/copy.js
* N/A
* Delete "!languages/wordpress-seo.pot" from copy.js because that file no longer exists in the repo.
> Delete potfile from copy.js

- admin/views/tabs/metas/post-types.php
* Fixes a bug where archive settings for post types aren't shown on the search appearance page when the `has_archive` for that post type contains an archive slug. Props to [schurig](https://github.com/schurig)
`$post_type->has_archive` can also be a string. So here we shouldn't match for the type. We just want to know if the value is truthy or not.
* Create a post type with a custom archive name so that `has_archive` is a string
* go on `/wp-admin/admin.php?page=wpseo_titles#top#post-types` and it should show the archive options too (before it didn't)
Fixes #10211
> [FIX] Fix display of post type archive settings

- css/src/metabox.scss
- js/src/components/SnippetPreviewSection.js
- js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
* N/A
The font-size of the sections are not the same. After this `Focus keyword` is the only one not the same, but this is going to get Reactified at some point.
* Removed the heading font size overwrite.
* Check if the heading font-size of the snippet editor is now 16px.
Fixes #
> Remove style overwrite

- inc/class-upgrade.php
* Fixes a bug where the upgrade routing for 7.7 gave performance issues on larger databases.
* Have posts with postmetas for the key `_yoast_wpseo_post_image_cache` - adding these manually. Perhaps the CLI can create large datasets for it (I don't know, it's just an idea)
* Install the Yoast test helper and sets the version to 7.6
* By setting the value, the version will updated directly
* Go to the database and verify that the postmetas for the key `_yoast_wpseo_post_image_cache` are deleted.
Fixes #10209
> Add routine for deleting postmeta by key.

- admin/class-add-keyword-modal.php
- admin/class-keyword-synonyms-modal.php
- admin/class-premium-benefits-for-synonyms-list.php
- admin/metabox/class-metabox-keyword-synonyms-button.php
- admin/metabox/class-metabox.php
- css/src/metabox.scss
- js/src/components/PremiumBenefitsForSynonymsList.js
- js/src/components/modals/KeywordSynonyms.js
- js/src/components/modals/index.js
* N/A
* Add a modal just like add keywords: https://github.com/Yoast/wordpress-seo/pull/9231
* The buy link uses a newly generated shortcode: https://yoa.st/keyword-synonyms-popup/
* Test if the add keyword modal still functions like before.
* Test if modal functions properly:
* Text matches.
* Links to correct url.
* Looks the same as add keyword.
Fixes #10263
> Add premium upsell for synonyms

- js/src/analysis/classicEditorData.js
- js/src/helpers/replacementVariableHelpers.js
- js/src/helpers/stringHelpers.js
- js/src/redux/actions/snippetEditor.js
- js/tests/helpers/replacementVariableHelpers.test.js
- js/tests/helpers/stringHelpers.test.js
- js/tests/redux/reducers/snippetEditor.test.js
* Fixes a bug where HTML entities were not always decoded in the Snippet Variables.
* Decided to use a yoast-components helper function rather than lodash, because it works more generally.
* decodeSeparatorVariable became obsolete, as we now decode any replacement variable value anyways (provided it's a string).
* Verify that HTML entities in replacement variables are correctly decoded.
* Specifically, verify that the bullet separator now works in both the classic editor and in the Gutenberg editor.
Fixes #10279
> Unescape HTML entities in replacement variable value strings

- package.json
- yarn.lock
* Wordpress-seo is now dependent on the yoast-components develop branch, rather than a built version.
* Run `yarn install`, verify that your `yarn.lock` has the develop dependency, and see that yoast-component related things still work (think Snippet Preview etc).
> Set yoast-components dependency to develop branch

- admin/views/tabs/social/pinterest.php
* Changed the link to claim your website on Pinterest to push you to the right location more easily.
> Change Pinterest claim site links

- admin/class-admin-media-purge-notification.php
- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- admin/views/tabs/metas/paper-content/media-content.php
* Fixes a few occurrences of wrong values for the attribute `rel="noopener noreferrer"`
- fixes two typos `referer` vs. `referrer`
- removes two `nofollow` which don't make much sense, as they're used in the admin, and uses proper values `noopener noreferrer`
N/A
Fixes #10327
> Fix noreferer - noreferrer typos and a few missing ones

- admin/views/tabs/metas/paper-content/post_type/post-type.php
* Fixes a bug where saved templates in Search Appearance would be saved incorrectly into the database, resulting in them never being loaded when editing a post, page, etc. and thus displaying the wrong template.
*
* Prior to checking out this branch, create a custom template for posts in the Search Appearance tab.
* Go to add a new post. Notice that the snippet editor does not display the template you set.
* Go back into Search Appearance and change the template for posts.
* Go to add a new post and verify that your custom template is now properly being used.
Fixes #10320
> Fixes Search Appearance templates

- frontend/class-frontend.php
Some themes uses Woocommerce's archive-product.php template for search results. When 0 results are returned global $post variable will be null so there will be notice of "Trying to get property of non-object".
* Fixes bug where php error notices were given when the search result doesn't have any WooCommerce products. Props [jaska120](https://github.com/jaska120)
* I have added is_search() function to outcome situations where $post variable is used as object when it could be null.
* Use theme which uses archive-product.php template file for search results. For example shopkeeper.
Fixes #10300 maybe #10120
> Fix search errors

- admin/class-yoast-form.php
- admin/views/tabs/metas/paper-content/rss-content.php
* Fixes the textareas size in the Search Appearance -> RSS tab
- the `Yoast_Form->textarea()` method accepts 3 arguments but we were passing 4 parameters, the third one was an empty string, thus no attributes were passed
* check the `rows` and `cols` HTML attributes of the two textareas aren't empty and do have the passed values
Screenshot before:
After:
> Fix search appearance RSS textarea size

- inc/class-wpseo-shortlinker.php
Adds the number of days the plugin has been active to the data we sent along when clicking on shortlinks.
* none needed
> Add days active to short links

- js/src/components/MediaUpload.js
* Fixes a bug where adding a company image in step 4 of the configuration wizard, would make the wizard crash.
* This issue was fixed by removing an unused string ref, this does not solve the underlying issue of multiple react instances conflicting on the page.
* Go to step 4 of the configuration wizard and set the radio button to company.
* Upload or select an image and make sure the configuration wizard doesn't crash.
Fixes #10123
> Removed unused ref to avoid error crashing the configuration wizard

- js/src/wp-seo-post-scraper.js
* Disable Yoast SEO markers outside of TinyMCE.
*
* Test whether the markers are disabled in Gutenberg.
* Test whether the markers are still available in TinyMCE.
Fixes #10347
> Disable marker buttons when tinyMCE is not available

- js/src/wp-seo-post-scraper.js
Reverts Yoast/wordpress-seo#10350
This is causing errors on trunk (and was meant to be merged on the release branch).
Trying the changes on the release branch also introduced unwanted functionality.
> Revert "Disable marker buttons when tinyMCE is not available"

- admin/views/tabs/metas/paper-content/post-type-content.php
* Fixes a bug where archive settings for post types aren't shown on the search appearance page when the has_archive for that post type contains an archive slug. Props to [nesinervink](https://github.com/nesinervink)
* Wordpress `register_post_type` accepts both _boolean_ and _string_ `has_archive` values to enable post type archive pages: https://codex.wordpress.org/Function_Reference/register_post_type#has_archive
* Test with both _string_ and _boolean_ `has_archive` values when creating custom post type. "Settings for `post type name` archive" in SEO > Search appearance > Content type menu relevant post type section should be visible.
Fixes #
> Check for truthy has_archive values

- admin/metabox/class-metabox-section-react.php
- admin/metabox/class-metabox-section-reaction.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
* _N/A_
* Introduced a class which can be used on multiple spots, to render the React root node.
* ~This root node has the same name used in the Snippet Preview, the name could be changed later, but for now it already shows the Snippet Editor on the location it is expected.~
* The root node has been renamed to make sure the Snippet Preview can still be used without the feature flag. This means that no components are shown when checking out this branch.
* There should be a `<div id="wpseo-metabox-root" class="wpseo-metabox-root"></div>` in the pages
* Ignored the JavaScript errors relating to the focus keyword not being an element on the pages anymore
* Filtered the Form elements that were registered for the sections by "hidden" …
> Introduces a React root element when feature is enabled

- js/src/components/SidebarItem.js
- js/src/components/higherorder/withYoastSidebarPriority.js
- js/src/edit.js
Unit tests are currently missing but can be added later to not block other work from being merged.
* Adds a sorted sidebar slot to allow mixing free and premium components
* I decided to make our sidebar flexibly extensible from the start.
* build and run
> Add a sorted YoastSidebar slot.

- admin/views/tool-file-editor.php
* Add a missing H1 heading to the Network Admin > SEO > Edit Files page
I see the standard way in the plugin to output the heading (and footer) is by using `Yoast_Form->admin_header()` and `Yoast_Form->admin_footer()`. This also adds the Sidebar, which appears also on Premium, but this seems to be the current standard behavior. For example, the same thing already happens in the MultiSite Settings page.
- test in a multisite install
- go to Network Admin > SEO > Edit Files
- verify there's a main H1 heading "Yoast SEO: Edit Files"
- create a robots.txt file and edit the form
- submit and verify the "success" notice appears nicely and everything works
- test on a single site install
- go to SEO > Tools > File editor
- verify there …
> Add missing heading in network admin edit files page

- js/src/edit.js
* Added the Yoast icon as pinned plugin icon in Gutenberg.
* Kept the styled component in `edit.js` because it's only a resize, which isn't used anywhere else.
* Set the size of the icon at 20x20px to match the other icons in the bar.
* Make sure the following flag is set : `define( 'YOAST_FEATURE_GUTENBERG_SIDEBAR', true );`
* Open a post-edit page.
* Make sure the yoast-sidebar is pinned ( open the yoast sidebar -> click on the star at the top ).
* Check if the icon added in the header toolbar by pinning yoast-seo is the yoast icon ( you can check the issue how it used to look for comparision ). 
Fixes #10295
> Used the yoast plugin icon as pinned plugin icon for gutenberg

- inc/sitemaps/class-sitemaps-router.php
* Fix a bug where `/sitemap.xml` would not correctly redirect to `/sitemap_index.xml` in some environments.
* `$_SERVER['SERVER_NAME']` possibly does not contain the full host used in the current request. `$_SERVER['HTTP_HOST']` should be used instead if available.
* In VVV, set up a subdomain multisite environment similar like this (via `vvv-custom.yml`):
```yml
network-revolution:
repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
hosts:
- network-revolution.test
- subsite1.network-revolution.test
- subsite2.network-revolution.test
- network-revolution2.test
- subsite1.network-revolution2.test
- subsite2.network-revolution2.test
custom:
db_name: …
```
> Fix sitemap.xml not redirecting to sitemap_index.xml.

- inc/sitemaps/class-sitemaps-cache-validator.php
* Fix a bug where sitemap cache transients would not be correctly cleared.
* As described in the issue, clearing the transients from the database in `WPSEO_Sitemaps_Cache_Validator::cleanup_database()` is not enough. Transients without expiration date are also stored in WordPress's internal alloptions cache, so that needs to be cleared. Otherwise, these transients are still available if being retrieved within the same request.
* It's impossible to acceptance-test this PR. The unit test working correctly is a confirmation that it solves the issue.
Fixes #10396
> Delete alloptions cache when clearing sitemap cache transients

- js/src/components/contentAnalysis/Results.js
* Moved language notice props to seperate component
* Done to work together properly with its sibling pr: https://github.com/Yoast/yoast-components/pull/492/files
* Only test in combination with its sibling pr: https://github.com/Yoast/yoast-components/pull/492/files
* Check the sibling pr for test instructions.
Fixes #https://github.com/Yoast/yoast-components/issues/475
> Moved language notice props to seperate component

- js/src/helpers/i18n.js
* N/A
* Adapt the i18n helper to be able to specify the namespace. This is used in premium for the JS translations.
* Check if the default still works: the `window.wpseoYoastJSL10n` object should fill with translations.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/1828
> Adapt i18n helper to be able to specify the namespace

- js/src/components/UpsellBox.js
- js/tests/components/UpsellBox.test.js
- js/tests/components/__snapshots__/UpsellBox.test.js.snap
* N/A
* Created an UpsellBox React component. We decided to not create it in yoast-components, since we are moving to a mono-repo anyways.
* Check out the [sibling branch in yoast-components](https://github.com/Yoast/yoast-components/pull/672), and link it to wordpress-seo with `yarn link`.
* Place this code somewhere you can find it (in the DOM), for example on line 42 in `SnippetPreviewSection.js`:
```
<UpsellBox
benefits={ [
"<strong>Strong text</strong> and not so strong text",
"<strong>Strong text two</strong>",
] }
infoParagraphs={ [
"Text",
[ "Array with ", <a key="1" href="#">links</a>, " test" ],
] }
upsellButtonText="A button"
upsellButton={ {
href: "#",
className: "button …
```
> Create UpsellBox component and test

- tests/bootstrap.php
* Add support for the WP_TESTS_DIR environment variable to the test suite.
* VVV sets `WP_TESTS_DIR` by default, pointing to the core test suite.
* The plugin only uses `WP_DEVELOP_DIR` which needs to be manually set. At least for VVV, having support for `WP_TESTS_DIR` would help a lot for local testing.
* Use the plugin on VVV.
* SSH into your VVV and move to the plugin directory.
* Run `vendor/bin/phpunit` without manually specifying any `WP_DEVELOP_DIR` or `WP_TESTS_DIR` environment variables.
* Ensure it works.
Fixes #10355
> Add support for the WP_TESTS_DIR environment variable to the test suite

- js/src/components/Metabox.js
- js/src/components/Sidebar.js
- js/src/containers/Metabox.js
- js/src/edit.js
* N/A
* Creates a separate slot for the metabox, besides the already existing sidebar slot.
* Also removes `IntlProvider` from react applications on post pages (HelpCenter, Snippet Preview and Content analysis results).
* There are two components: `js/src/components/Metabox.js` and `js/src/components/Sidebar.js`. Give both different contents and make sure the Sidebar and Metabox show the correct content.
Fixes #10454
> Added separate slot, container and component for Metabox

- .travis.yml
* Always run Travis tests against the latest WordPress version instead of hard-coding the latest major release.
* I added a new instruction in the travis script that, if "latest" is specified for `WP_VERSION`, fetches the latest version number from the wordpress.org API.
* Everywhere we currently hard-code "4.9", I changed it to "latest", so that we don't need to worry about it anymore and always test against the actual latest release. This allows to spot bugs that would be specific to 4.9.6 as well for example.
* Not really acceptance-testable. By looking at the Travis test logs for the PR we should be able to determine whether the correct latest WordPress version is fetched where …
> Always run Travis tests against the latest WordPress version

- js/src/helpers/classicEditor.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
This allows us to get Fill's inside the tree outside of Gutenberg.
> Add ability to register components

- admin/formatter/class-metabox-formatter.php
- admin/metabox/class-metabox.php
- js/src/edit.js
- js/src/wp-seo-post-scraper.js
- yarn.lock
* N/A
*
* Make sure the `define( 'YOAST_FEATURE_GUTENBERG_SIDEBAR', true );` is removed from your `wp-config.php` file.
* Make sure the sidebar and new metabox are still being rendered in gutenberg and the new metabox is still being rendered in the classic editor.
Fixes #10373
> Removed gutenberg sidebar feature flag

- js/src/components/CollapsibleCornerstone.js
- js/src/components/Metabox.js
- js/src/components/SidebarCollapsible.js
- js/src/components/contentAnalysis/ReadabilityAnalysis.js
- js/src/components/contentAnalysis/SeoAnalysis.js
- js/src/containers/SnippetEditor.js
- yarn.lock
* _N/A_
* Made sure the `Snippet Preview` is the only opened collapsible by default.
* View the metabox and sidebar in a Gutenberg edit page.
* View the metabox in a Classic Editor edit page.
* View the metabox in a Category edit page.
Fixes https://github.com/Yoast/yoast-components/issues/671
Requires https://github.com/Yoast/yoast-components/pull/682
> Styling improvements

- js/src/wp-seo-wp-globals-backport.js
- webpack/paths.js
- webpack/webpack.config.js
* N/A
* Exposes `styled-components` on `window.yoast.styledComponents` to be used in premium.
* Test in conjunction with `stories/react-multi-keywork` on premium to verify `styled-components` works as expected. The warning thrown in the console should be gone.
> Made styled components a global dependency

- readme.txt
The Howto block is not generally available as it sits behind a feature flag for now.
The Metabox redesign deserved a little mention.
> Changelog tweaks

- js/src/compatibility/compatibilityHelper.js
- js/src/helpers/isGutenbergAvailable.js
- js/src/wp-seo-post-scraper.js
- js/tests/isGutenbergAvailable.test.js
* Fixes a bug where a non-existing global was being checked against to determine whether markers should be displayed is Gutenberg, resulting in markers displaying in Gutenberg.
* Additionally to fixing the marker issue, a small change was made to the Compatibility Helper so that `isClassicEditorHidden` always returns a boolean. 
* Ensure you run `composer du`, `yarn` and `yarn start`.
* Create a post in the Classic Editor that triggers a marker.
* Save the post and switch to the Gutenberg editor.
* Determine that the marker isn't shown for any of the assessments.
Fixes #10505
> Disables markers in Gutenberg

- admin/class-admin.php
- tests/admin/test-class-admin.php
* Make sure the structured data how-to block is removed from the changelog for 8.0.
* Add the feature flag `define( 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS', true);` to `wp-config.php.
* Make sure the "How to" block is available in Gutenberg.
* Remove the feature flag and make sure it's not available anymore.
Fixes #10501
> Structured data blocks feature flag

- .gitignore
- package.json
- webpack/webpack.config.js
- yarn.lock
* I've added a `yarn webpack-analyze-bundle` command which can be used to see how big our bundles are.
* You need to have a bit of patience, on my machine generating the stats took 90s+ consistently.
* I've changed the context of webpack to be the root folder. If I didn't do this the analyzer would show node_modules with their whole paths. This would result in a lot of noise like `/Users/...`.
* Run `yarn webpack-analyze-bundle` and see a nice visualization for all the webpack bundles.
Fixes #
This add the `yarn webpack-analyze-bundle` command which can be used to
analyze which parts of our bundle cause which of its size.
> Add webpack bundle analyzer

- js/src/components/Metabox.js
- js/src/components/Sidebar.js
* Move ThemeProvider inside SidebarItem.
- check the order of the components in the sidebar in free and premium is correct /Cc @moorscode 
Fixes #10513
> Move ThemeProvider inside SidebarItem

- admin/metabox/class-metabox.php
* Makes the `Go Premium` open a new browser tab to the `Reason to upgrade` shortlink, instead of opening an invisible tab in the metabox.
* Also removes the invisible premium tab in the metabox.
* Make sure the `Go Premium` link opens a new tab on the reason to upgrade page on Yoast.com.
Fixes #10511
> Make Go Premium link direct to shortlink instead of metabox tab

- js/src/components/CollapsibleCornerstone.js
* Improves the cornerstone collapsible l10n and a11y.
- makes the collapsible title translatable
- better solution for spacing between the string and the link
- uses `makeOutboundLink()` with a prop `rel={ null }`: this way, the default attribute `rel="noopener noreferrer"` is omitted as advised by @jono-alderson and the a11y message is still rendered
- check in the metabox and sidebar the cornerstone collapsible title and text render correctly
- check the link has `target="_blank"`, the visually hidden a11y message and no `rel="noopener noreferrer"`
Fixes #10524
> Improve cornerstone collapsible l10n and a11y.

- package.json
- yarn.lock
* N/A
* Bumped YoastSEO.js to v1.36.1
* N/A
Fixes #10543
> Bump YoastSEO version to 1.36.1

- admin/class-expose-shortlinks.php
- js/src/components/CollapsibleCornerstone.js
- js/src/configuration-wizard.js
- js/src/containers/SnippetEditor.js
* Replaces all shortlinks used in the React components to be parsed by the `WPSEO_Expose_Shortlinks` class.
*
* Checkout this branch and ensure you've properly run `composer install`, `yarn`, `grunt build` and `yarn start` (if applicable).
* Go to Posts -> Add new.
* Ensure that the "Learn more about the Snippet Preview." link in the Snippet Editor, now also contains information about the PHP version that's being used.
* Ensure that the "Learn more about Cornerstone Content." link in the Cornerstone Content component, now also contains information about the PHP version that's being used.
* Ensure that both links work.
Fixes #10535
> Replaced all shortlinks to use the expose shortlinks class

- webpack/paths.js
* moves `babel-polyfill` as first thing in the Webpack's entry.
Ensuring the transformations made by babel-polyfill happen first, makes Internet Explorer a bit more happy. Inspired by this comment and following ones: https://github.com/facebook/react/issues/8379#issuecomment-264641700
This PR should be carefully tested on a Windows machine with IE11 and also on mac with other browsers to make sure there are no regressions.
- set up a dev environment on a Windows machine ( 😬)
- build the JS: building on Windows you will probably get the error mentioned in https://github.com/Yoast/wordpress-seo/issues/10539#issuecomment-411034485 and you need to manually install `yarn add babel-preset-stage-0`
- edit a post …
> Move babel-polyfill to be the first thing in Webpack's entry

- package.json
Fixes the following Jest error:
```
FAIL
● Test suite failed to run
SecurityError: localStorage is not available for opaque origins at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
at Array.forEach (<anonymous>)
```
* N/A
* Run `npm run test` or `yarn test`.
> Fix Jest security error: localStorage is not available for opaque origins at Window.get localStorage

- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
Fixes the classes that are being output by the HowTo block.
* Fixes the HowTo block receiving the `undefined` class if no additional class is set.
* Add a HowTo Block.
* Don't give it a class name.
* Check the HTML output, it should not receive an `undefined` class.
Fixes #10558.
> HowTo block fix classes

- js/src/components/CollapsibleCornerstone.js
- js/src/components/contentAnalysis/SeoAnalysis.js
- js/src/containers/SnippetEditor.js
- js/src/values/keywordUpsellProps.js
* Replaces all explanation texts with `HelpText` from `yoast-component`.
* 
* Test in combination with https://github.com/Yoast/yoast-components/pull/700 using `yarn-link`.
* Make sure all explanation texts in the metabox and sidebar have color `#767676`.
Fixes Yoast/yoast-components#694
> Replace ExplanationTexts with yoast-component HelpText

- js/src/containers/SnippetEditor.js
- js/tests/containers/SnippetEditor.test.js
* N/A
* There was a typo. It is no more.
* Verify that recommended replacevars still work in the snippet editor. (you should not have a huge list of replacevars, searching should still work).
Fixes #10598
> Fix recommended replacevars

- js/src/components/contentAnalysis/mapResults.js
* Change the fill color of the OK SEO score icon to orange
- see related yoast-components PR https://github.com/Yoast/yoast-components/pull/704
- build the JS
- verify the OK icon background color has changed from yellow `#f5c819` to orange `#ee7c1b`
- to see the black eyes / mouth you need to test with the yoast-components PR from https://github.com/Yoast/yoast-components/pull/704
Fixes https://github.com/Yoast/yoast-components/issues/702
> Change OK score icon color.

- js/src/wp-seo-replacevar-plugin.js
* Retrieves the parent page title via the REST API when using Gutenberg
*
* Add or edit a page in Gutenberg mode
* In the snippet preview use `%%parent_title%%` in the template
* Select a parent page and see the preview showing it's title
Fixes #9263
> Retrieve parent page type using the rest api in gutenberg

- admin/class-admin-asset-manager.php
* Fixes a bug where the metabox isn't loaded correctly when the Classic Editor plugin is active. 
* Install the classic editor plugin
* Have Gutenberg active
* Create a new post and see the metabox isn't loaded correctly.
* Checkout this branche
* Create a branch and see that the metabox is fixed.
Fixes #9991
> Fix classic editor plugin conflict

- package.json
- yarn.lock
* N/A
* Bumped YoastSEO.js to v1.37
* Bumped Yoast Components to 4.9.0
* N/A.
> Bumped version of YoastSEO to 1.37, components to 4.9.0

- admin/class-admin-asset-manager.php
* Fixes a bug where Gutenberg backports were being loaded in the Classical editor, leading to errors in IE11.
*
* Determine that the Classic editor now loads properly in IE11.
Fixes #10571
> Restricts loading of backports if classic editor is currently being used

- admin/class-gutenberg-compatibility.php
- tests/admin/test-class-gutenberg-compatibility.php
* Changes the Gutenberg compatibility checks to work via `version_compare`.
*
**Acceptance test only**
* Checkout this branch, make sure you have run `composer install`. 
* If you're running an environment with `YOAST_SEO_DEV_SERVER` set to true, ensure you also run `yarn`, `yarn upgrade yoast-components` and `yarn start`. Otherwise, you can skip this step.
**Testing steps**
* Ensure you have the latest version (https://downloads.wordpress.org/plugin/gutenberg.3.5.0.zip) of Gutenberg installed and activated.
* Go into SEO -> General and check that **no** notifications are being shown in regards to Gutenberg incompatibility.
* Uninstall Gutenberg and install an older version …
> Fixed broken version compare checks

- inc/class-wpseo-meta.php
- js/src/wp-seo-post-scraper.js
* Makes sure the right cornerstone value is saved.
* Save a post as cornerstone
* Refresh the page, the cornerstone flag is true
Fixes #[1928](https://github.com/Yoast/wordpress-seo-premium/issues/1928)
> Sanitize the saved cornerstone value

- js/src/analysis/CustomAnalysisData.js
- js/src/analysis/analysisData.js
- js/src/helpers/measureTextWidth.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
* n/a
* Adds a function that collects the data from the store, the snippet preview, custom callbacks.
* Implements text width analysis on the plugin side instead of in the YoastSEO.js
*
Fixes https://github.com/Yoast/YoastSEO.js/issues/1676
> Collect data from different sources for the webworker

- admin/metabox/class-metabox.php
- js/src/components/contentAnalysis/ReadabilityAnalysis.js
- js/src/components/contentAnalysis/SeoAnalysis.js
- js/src/components/contentAnalysis/mapResults.js
Originally intended to address the score that changes during the initialisation of a category page.
The issue is that, when opening a category-edit page. The overall SEO score in the metabox is set multiple times. Once it's set to undefined, at this point the overall score is still unknown. Once it's calculated wrongly, giving a wrong score as a result. Only the final score is correct. 
The intention of this PR was originally to try and remove the wrong score that is set in the store at some point in time. That goal hasn't been reached yet.
What this PR does do is that, during the time when the SEO/Readability score is unknown, it replaces the grey analysis result with a spinner showing that it's still being loaded.
* Changes the …
> Use a loader icon when a score is not yet present

- admin/class-admin.php
- admin/class-gutenberg-compatibility.php
- inc/class-structured-data-blocks.php
- inc/structured-data-blocks/class-how-to-block.php
- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
- js/src/structured-data-blocks/how-to/components/HowToStep.js
- wp-seo-main.php
* Fixes the HowTo block outputting JSON directly to the front-end instead of in the appropriate tags when used by authors.
* The json-ld scripts are now rendered server-side, I deemed this the most reliable and secure method of adding the script tags without any risk of code being injected.
* This does mean that the Structured Data Blocks integration needs to be active on both the front-end and the admin and as such I've moved it to `wpseo-main.php`.
* Build the JS.
* Enable the `YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS` feature flag.
* Log in as an author.
* Create a HowTo block.
* It should output the correct json-ld inside the appropriate script tag.
> Render json-ld server side to circumvent tags being stripped from post_content.

- wp-seo-main.php
* N/A
* On trunk, make sure the How To gutenblock is only visible when you have the 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' feature flag in your wp-config.php, and not when .
* Check out this branch. Remove 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' from your wp-config.php. Make sure the How To Gutenblock is still visible in the menu (and is functional, of course)
Fixes #10633
> Remove 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' feature flag 

- js/src/components/Metabox.js
- js/src/components/SnippetPreviewModal.js
- js/src/structured-data-blocks/faq/block.js
- js/src/structured-data-blocks/faq/components/FAQ.js
- js/src/structured-data-blocks/faq/components/Question.js
- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
- js/src/structured-data-blocks/how-to/components/HowToStep.js
* Fixes incorrect import of `@wordpress/i18n`.
*
* Make sure the jed localization error is no longer preset when loading gutenberg.
Fixes #10673
> Fixed incorrect import

- inc/class-wpseo-admin-bar-menu.php
* Fixes a bug where a type error is thrown when the passed score for terms and posts isn't of the type `WP_Post` as this can collide with third-party plugins.
* Instead of forcing the object type I just check if argument is an object and if it contains the needed properties.
* Check if the bullet still works on the adminbar in the frontend when viewing a post and term page.
Fixes #10646
> Check if properties exists instead of forcing a specific object

- admin/class-yoast-network-admin.php
- admin/views/tabs/network/general.php
- admin/views/tabs/network/restore-site.php
- tests/admin/test-class-yoast-network-admin.php
* Shows the title of each site in network site dropdowns, as well as domain and path.
* `Yoast_Network_Admin::get_sites()` now accepts a second parameter to enable showing the title for each site. It is false by default since there may be performance implications for large setups or relatively big setups without a persistent object cache (to retrieve the site title, sites need to be switched).
* Yoast SEO is only using the function for a maximum of 100 sites though, and WordPress core has been doing similar, so we should be fine. Therefore in the two calls of that method, the second parameter is passed as `true`.
* The format of each entry is the following:
* `{$id}: {$domain}{$path} [{$states}]` if `$show_title` is false
* …
> Show more details in multisite site lists

- js/src/structured-data-blocks/how-to/components/HowTo.js
* N/A
* N/A
* Add a how-to block
* Add a time duration
* Enter 0 for hours and minutes
* Publish post, and view it in the frontend: should not show "Time needed: .".
* Go back to editor, enter a non zero number of minutes or hours.
* Update post.
* Verify that it now does show the time needed.
Fixes #10664
> Don't show time needed if human readable string is empty

- js/src/analysis/getMarker.js
- js/src/analysis/refreshAnalysis.js
- js/src/wp-seo-post-scraper.js
* n/a
* Recreates the getMarker function after the web worker is done with the analyses.
* Moves the marker function to a separate file so that it can be used in different locations (e.g., the term scraper once we're able to use marking there).
* Check whether the markings still work.
Fixes #https://github.com/Yoast/YoastSEO.js/issues/1692
> Recreate getMarker function after worker is done

- js/src/analysis/getAnalysisData.js
* N/A
* Fixes the store state by cloning before merging
* In premium you should no longer get an error `unexpected key "synonyms" found in previous state received by the reducer.`
Fixes https://github.com/Yoast/YoastSEO.js/issues/1711
> Fix the store state by cloning before merging

- js/src/wp-seo-post-scraper.js
* n/a
* Backfills `YoastSEO.app.changeAssessorOptions`
* Check whether the cornerstone toggle still works (when it's switched on, the text length assessment should prompt you to write at least 900 words; when it's switched off, that value is 300 words).
* For `useKeywordDistribution` you can manually set `window.YoastSEO.app.changeAssessorOptions( { useKeywordDistribution: true } );`. Usually this option is set in Premium (in `metabox.js`). I'm not sure how we can best test that. 
Fixes https://github.com/Yoast/YoastSEO.js/issues/1708
> Backfill changeAssessorOptions

- wp-seo-main.php
* N/A
* On release/8.1, make sure the How To and FAQ gutenblock are visible without the 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' feature flag in your wp-config.php.
* Check out this branch. Add 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' to your wp-config.php. Make sure the How To and FAQ Gutenblocks are visible in the menu (and is functional, of course)
> Reintroduce structured data blocks feature flag

- admin/class-admin-asset-manager.php
- grunt/config/copy.js
- js/vendor/lodash-noconflict.js
* Fixes an issue where adding the `defer` or `async` attributes to our script handles would result in an error.
* When a plugin or code-snippet would add sync or defer to the lodash script the inline script would refer to `_` even though this wasn't available yet because the `lodash` script was not loaded yet. This PR fixes that by moving the noConflict to a file and enqueuing that file instead.
* Before applying this PR, add this code snippet to your theme's `functions.php`:
```
function defer_parsing_of_js ( $url ) {
if ( FALSE === strpos( $url, '.js' ) ) return $url;
if ( strpos( $url, 'jquery.js' ) ) return $url;
return "$url' defer ";
}
add_filter( 'clean_url', …
```
> Fix error when async or defer is added to scripts

- frontend/class-opengraph-image.php
* None needed.
* Made access to `add_image_by_id` and `add_image_by_url` public so it could be properly used in extensions.
> Give access to image functions for use in extensions

- .github/ISSUE_TEMPLATE/Bug_report.md
Adds "editor affected" checkboxes. Choose from Classic editor, Gutenberg or the Classic editor plugin.
* Not applicable
* Not applicable
* Not applicable
Fixes #
> Update new bug report template

- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
- js/src/structured-data-blocks/how-to/components/HowToStep.js
* 
* Adds a Heading ID property field so a custom ID can be assigned to the heading of the HowTwo block.
* Add a HowTo block.
* Give the HowTo block a title.
* Save the post and view it.
* Check that the proper ID has been set by inspecting the HowTo block's heading (The heading's title. Can be multiple words, but spaces will be substituted with hyphens).
* Go back and edit the post.
* In the block settings, you should now see a Heading ID input field. Enter an ID (can be multiple words, but spaces will be substituted with hyphens).
* Save the post and view it.
* Check that the proper ID has been set by inspecting the HowTo block's heading.
Fixes #10655
> Added an Heading ID field in the HowTo block options

- admin/taxonomy/class-taxonomy.php
- js/src/analysis/getIndicatorForScore.js
- js/src/components/contentAnalysis/SeoAnalysis.js
* Fixes a bug where loading spinners wouldn't show up on term pages.
* Also optimized some of the indicator's code as it was overriding / checking things at weird times throughout the code.
* Ensure that you now see spinner icons when a term is still loading the analysis.
Fixes #10720
> Loading spinner for term pages

- js/src/wp-seo-replacevar-plugin.js
* N/A
* Reintroduced the code from https://github.com/Yoast/wordpress-seo/pull/10587/files that was lost during a merge conflict. 
* I've added a `this.declareReloaded();` within `if ( ! isUndefined( fetchedParents[ newParent ] ) ) {`.
Without that, the replacevar doesn't update when a previously selected (and thus previously fetched) parent is reselected again. 
* Add or edit a page in Gutenberg mode
* In the snippet preview use %%parent_title%% in the template
* Select a parent page and see the preview showing its title. Switch between different parent pages. Also, make sure to reselect a parent page that has been selected before, because that was broken in the previous …
> Reintroduce parent title code for gutenberg

- frontend/class-opengraph-image.php
- tests/frontend/test-class-wpseo-opengraph-image.php
* Fixes a bug where the OpenGraph image wouldn't show correctly for the frontpage in a few situations. Props @mt8 for the solution direction.
1. Set an image in SEO → Social → Facebook → Frontpage settings.
2. Set a different image for your latest post.
3. Set the homepage to show the latest posts in Settings → Reading.
4. Check the source of the homepage, it will show the image you set in step 1, instead of the one in step 2.
Fixes #10391
> Fix OpenGraph image output for homepage

- js/src/redux/selectors/results.js
* This selector is automatically exposed to `wp.data.select( "yoast-seo/editor" )` which we can use in premium.
* Run `wp.data.select( "yoast-seo/editor" )` in the console and see that you see the status of the mark buttons.
Relates to https://github.com/Yoast/YoastSEO.js/issues/1723
> Expose mark button status as a selector

- js/src/analysis/usedKeywords.js
* N.A.
* Sets the previously used keywords assessment to run when it's loaded not just when keywords have been changed while loading.
* Have a post with a keyword that you've used before.
* Load the post edit.
* You should immediately see the assessment that you've used this keyword before.
Fixes https://github.com/Yoast/wordpress-seo/issues/10741
> Always refresh previously used keywords.

- wp-seo-main.php
* N/A
* On trunk, make sure the How To and FAQ gutenblocks are only visible when you have the 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' feature flag in your wp-config.php, and not when you don't.
* Check out this branch. Remove 'YOAST_FEATURE_GUTENBERG_STRUCTURED_DATA_BLOCKS' from your wp-config.php. Make sure the How To and FAQ Gutenblock are still available.
Fixes #10778
> Remove Gutenblocks featureflag

- frontend/class-opengraph.php
Changes `og:url` to never have the paginated state of a page.
Google has a concept of `rel="next"` / `rel="prev"` in combination with `rel="canonical"` to deal with paginated states of archives. Facebook however has no such thing. Sharing page 2 of an archive therefore doesn't make all that much sense, especially as the content of that page is always going to be transient, because of the reverse chronological order of archives in WordPress.
* The `og:url` of archive URLs (category archives, author archives, blog archives) now always shows the non-paginated URL for that archive.
* Go to page 2, 3, 4 of any archive, see the `og:url` is pointing to page 1.
> Make og:url unpaginated by default

- tests/bootstrap.php
* Fixes an issue where the test suite would not execute correctly without a `WP_PLUGIN_DIR` environment variable specified.
* The correctly plugins directory will always be one level higher than the `wordpress-seo` plugin directory, so we can easily auto-detect it, independently of the `WP_PLUGIN_DIR` environment variable.
* This makes it easier to run test, as we no longer require to set up this environment variable on your setup (for example on VVV).
* Use a setup like VVV.
* Run the plugin from a WordPress installation that is different from the one that hosts the WordPress core test suite you used (the core test suite's location used is typically set in either the `WP_TESTS_DIR` …
> Auto-detect value for the WP_PLUGIN_DIR constant when loading the test suite

- inc/class-wpseo-admin-bar-menu.php
* Replaces the "Check Inlinks (OSE)" menu item from the Yoast Admin bar dropdown "Analyze this page" from the Moz OpenSite Explorer (OSE) to Google Search Console as the former service is being disabled on August 30th 2018.
* Change link to Google Search Console
* Go to a page on the front-end of the site
* Use the "Y"-oast dropdown in the Admin Bar
* Open "Analyze this page"
* Use the "Check links to this URL"
* See that it opens Google Search Console with the URL of the current page
Fixes #10490
> 10490 replace inlinks taget url gsc

- grunt/config/aliases.yaml
- grunt/config/clean.js
- grunt/config/copy.js
- grunt/config/glotpress_download.js
- package.json
- yarn.lock
* _N/A_
But only sometimes. This was because it would be overwritten by its formal counterpart. It seemed random because the last one to download would be the file on disk.
This required a change in grunt-glotpress, because it didn't expose the slug before. The slug has the formal/informal information. With this change we can change the fileFormat. That makes sure that the files are not overwritten.
Some additional changes are necessary to cleanup the languages folder. All files with suffixes are removed. This is because we currently don't support any formal languages. We can fix this later.
* Run `yarn`
* Run `grunt build:i18n` and see that all languages are correctly downloaded.
> Fix bug where nl_NL would not contain all translations

- grunt/config/clean.js
- grunt/config/compress.js
* _N/A_
* Increases the zip compression level in the grunt configuration, this results in a highly reduced artifact filesize.
* Run `yarn`
* Run `grunt artifact`
* See the `artifact.zip` filesize being smaller than without this PR.
Fixes #
> Reduce zip size with compression level

- js/src/analysis/constants.js
- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-term-scraper.js
* Fixes an issue where the user input would trigger an analysis every time.
* Added a debounce of 1 sec to the refresh.
* Check how often the refresh is getting called when you spam.
Fixes https://github.com/Yoast/YoastSEO.js/issues/1742
> Add debounce to refresh

- js/src/structured-data-blocks/faq/components/Question.js
* N/A
* Howto block now has strongs, so made the FAQ block look more alike.
* Verify that both in the editor and in published posts the FAQ block has no headers, but strongs.
> Replace h3 with strong

- admin/views/sidebar.php
Excludes product names from being translated.
This avoids bad translations and makes it easier for all languages to get a complete translation (because less needs to be translated).
* _N/A_
* Open the Yoast configuration pages and see the sidebar (advertisements) having the product names you expect them to have. (No visual changes from before this PR)
Fixes #
> Excludes product names from being translated

- frontend/class-twitter.php
- tests/frontend/test-class-twitter.php
* n/a
* Use the WordPress function that is doing the same, this prevents us to rely on a `global`. 
* Copied from #10827 
* Create a post that uses snippet variables in its twitter card title and description, see them work.
* Create a category / tag that uses snippet variables in its twitter card title and description, see them work.
* [] I have added unittests to verify the code works as intended
> Uses the function instead of the global

- admin/class-admin-asset-manager.php
* Fixes `TypeError: Cannot read property 'getCollectionByRoute' of undefined` error when editing a post in gutenberg.
* Before Gutenberg 3.7, we were depending on Gutenberg loading Wordpress's `wp-api`. Since 3.7, Gutenberg is not loading `wp-api` anymore, which broke our implementation and resulted in the Gutenberg editor crashing. This PR adds `wp-api` to our asset manager as a dependency of post scraper.
* Download Gutenberg 3.7 from the repo.
* Open `Settings` (GearWheel) > `Document` > `Categories`
* Open a post. See the editor crashing:
* Checkout this branch and build it. Open a post, and see the editor working.
Fixes #10867
> Add wp-api dependency to post-scraper script

- frontend/class-opengraph.php
* Properly output the manually set canonical as the `og:url` on pages where it is set manually.
* Set a manual canonical on a category and see if the `og:url` reflects that canonical.
Fixes #10837
> Fix OpenGraph output for overridden canonicals

- css/src/structured-data-blocks.scss
* N/A
I've tried several things, seems Firefox Quantum reserves some space for the "spin buttons" in the number input fields  even if they're hidden. See codepen https://codepen.io/afercia/full/dqNVNr/ in Firefox and compare it to the rendering in Chrome.
The only thing I've found that worked in Firefox was `letter-spacing: -1px` but it didn't work in Edge. So the only solution I see is:
- reduce the left/right padding
- make the text in the input fields horizontally centered
- build the CSS and JS
- add a How-to block, open the Time needed form
- check the placeholders, especially the `MM` one are fully visible in Firefox
- same in Edge
Screenshot:
Fixes #10780
> Adjust the how-to time needed input fields styling.

- js/src/components/SnippetPreviewModal.js
* N/A
This PR restores the plugin modal scrolling when the viewport height is smaller than the modal height.
Previously, the modal used an inline style set via the component `style` prop:
`style={ { height: "initial", minHeight: "50px" } }`
The modal content uses `overflow: auto` to make its content scrollable but the scrolling mechanism needs a computed height to work. It doesn't work with `height: initial` or `height: auto` so this inline style is not a viable option. The PR removes this inline style. Now the modal content is scrollable again. The downside is that on big screens the modal height won't be based on its content height any longer and it will be the default height of the Gutenberg component (70%). This should be …
> Make the snippet preview modal content always scrollable

- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
* Removed title from How To structured data block.
* Initial focus is moved to "Add duration" button.
* Add a `How To` block in Gutenberg.
* Make sure focus is moved to the `Add Duration` button.
Fixes #10845
> Remove title from how to block

- tests/formatter/test-metabox-formatter.php
As the language folder has been removed from the repo, this no longer works in Travis.
* _N/A_
* ~Moved the location to store the file to the tests directory.~
* Creates the language folder if it does not exist yet
* See the Travis builds pass again.
Fixes #
> Fix the fake language file test

- .travis.yml
I noticed some odd behaviour when running Yoast SEO alongside another plugin I'd written that uses styled components. In newer version their rehydration step will cause other instances of styled components stylesheets to be wiped out which isn't ideal.
The `SC_ATTR` environment variables allows you to scope the attribute of the generated stylesheet to avoid these conflicts. See the pertinent changelog here: https://github.com/styled-components/styled-components/releases/tag/v3.2.4
It might be good to incorporate this into the npm or grunt script somehow for local builds too but I couldn't work out the best place in relation to grunt and webpack.
* n/a
> Set SC_ATTR when building to prevent conflicts

- inc/structured-data-blocks/class-how-to-block.php
* N/A
* Also removed `title`, which was removed from the How To block  in #10889
* In gutenberg, create a how-to block with a duration, including at least 1 day.
* Press `preview`. Inspect the output of the How To block in the post.
* The output of the how to blick is prepended with a `div` with type `application/ld+json`.
* Copy the contents of this div into `https://search.google.com/structured-data/testing-tool/u/0/?hl=nl`
* Verify that the duration format in the structured data is correct, using https://en.wikipedia.org/wiki/ISO_8601#Durations.
Fixes #10892
> Added days to how-to block's structured data

- package.json
- webpack/webpack.config.js
- yarn.lock
* N/A
* Removes `gutenberg` as a npm package.
* All parts of Gutenberg that we need have been released as npm packages over the past few months (e.g. `@wordpress/i18n`). We're currently using those packages, which means we don't need the Gutenberg npm package anymore.
* Check out this branch
* Reset `node_modules` (`rm -rf node_modules && yarn install`)
* Build the project (don't use the dev-server)
* Make sure Yoast SEO works properly in Gutenberg as well as in the classic editor.
> Remove gutenberg as js dependency

- admin/class-plugin-conflict.php
When both Yoast SEO and All in One SEO Pack plugins are active, Yoast SEO will show a notice on Yoast SEO dashboard.
* Install and activate Yoast SEO;
* Install and activate All in One SEO Pack;
* Go to Yoast SEO general dashboard to check for the notice.
Fixes #10901
> Add Plugin Conflict Entry for All in One SEO Pack

- admin/class-admin-asset-manager.php
- js/src/wp-seo-metabox-category.js
* Fix primary taxonomy replacement variable in the classic editor.
* Create a post, add a title and save it.
* Add the `Primary category` replacement variable.
* Select a different primary category, make sure it updates.
Fixes #10902
> Update store if primary taxonomy term has changed in classic editor

- js/src/wp-seo-metabox-category.js
* N/A
- removes a `console.log` leftover after #10911
> Remove console.log leftover 

- inc/class-structured-data-blocks.php
* Adds Yoast branding to structured data blocks group
*
* Check if the structured data blocks group in Gutenberg is prepended with "Yoast SEO"
Fixes #10915
> Adds yoast branding to structured data blocks group

- frontend/class-opengraph.php
I'm changing the date time string to Bangla character which is Unicode. You can see the code [here](https://gist.github.com/AminulBD/7ae9ac9f5043db986433f28ba69f6cea) This function makes the date time string to Unicode characters which are invalid for facebook. That's why the date time should not be localized or translated by any other method.
Problem screenshot:
* Prevent localize the Open Graph publish and modify DateTime string.
*
* Install and activate the plugin from the gist linked above.
* Make sure the OpenGraph meta tags for dates do not show localized numbers.
> Publish and modify date time should not be localized

- inc/wpseo-functions.php
- tests/test-wpseo-functions.php
Add API function to get all WPSEO related capabilities.
Used the capability manager class instance.
Call the function. It should return the following:
`Array ( [0] => wpseo_bulk_edit [1] => wpseo_edit_advanced_metadata [2] => wpseo_manage_options )`
Fixes #9300
> API function/method: Get all WPSEO related capabilities

- package.json
- yarn.lock
* n/a
* Bumps YoastSEO.js to v. 1.39.2
* See https://github.com/Yoast/YoastSEO.js/pull/1787
> Update YoastSEO.js to 1.39.2

- js/src/components/PrimaryTaxonomyFilter.js
* N/A
*
* Install the classic editor plugin. Go to Settings > Writing. Set Classic editor settings to `Use the Gutenberg editor by default and include optional links back to the Classic editor.`
* Open a post and open the document sidebar (click the gear icon). You should see an error in the category picker. When you copy the error using the button, and paste it somewhere, you should see the error mentioned in https://github.com/Yoast/wordpress-seo/issues/10850. 
* Open the 'Tags' collapsible in the document sidebar. The editor should not crash and the tags panel should show. 
* Test the primary taxonomy picker in Gutenberg without the classic editor plugin active.
Fixes #10931
> Render error in separate if statement from primary taxonomy support

- inc/options/class-wpseo-option-titles.php
We all know that Google sometimes modifies the SEO title in the search results and when it does, it mostly used the colon `:` to separate the site title and tagline. Not only that, the colon `:` takes much shorter space than others and it also looks good in search results.
* Go to Yoast SEO -> Search Appearance -> Title Separator.
Fixes #10099
> Add Colon as a title separator

- js/src/components/higherorder/appendSpace.js
- js/src/structured-data-blocks/faq/components/FAQ.js
- js/src/structured-data-blocks/faq/components/Question.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
- js/src/structured-data-blocks/how-to/components/HowToStep.js
* N/A
* I've used a HOC to append a space to components. This HOC cannot be used for the duration string in the HowTo block (because that's not a component), which is why I added a space manually there.
* Go to our settings > Search Appearance > Content Types > Posts. Set the metadescription field to `%excerpt%` 
* Create a HowTo block. Fill in all fields. Don't forget the time needed input.
* Create an FAQ block. Fill in all fields.
* Publish/Save the post and view the post/preview.
* Look at `<meta name="description"`  in the page source (right click --> view page source).
* It should be a generated metadescription. This PR makes sure that there are spaces added between all …
> Add spaces to structured data output

- css/src/structured-data-blocks.scss
- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
* Adds a setting and filter allowing users to edit the text describing the needed time for a how-to guide.
* Added a filter to allow to change the text via filter.
* Used the same structure as existing settings for the how-to block.
* Prioritised the user-input in the settings over the filter.
* build this branch `yarn, grunt build:js && grunt build:css && yarn start`
* Create a new post. add a how-to block to the new post. 
* Check that the text before the needed time reads `time needed:`.
* go to the settings of the how-to block.
* Check that the default text of `time needed:` is in the input field as a placeholder.
* Change the placeholder text in the …
> Add time needed setting with filter

- js/src/analysis/getIndicatorForScore.js
- js/src/components/contentAnalysis/mapResults.js
* Fixes the import of `scoreToRating` in `mapResults.js` to be consistent with the import of the same function in `getIndicatorForScore.js`.
* This is needed for `YoastSEO.js` to be correctly integrated after its migration from `require`s to ES6 modules.
**Note**: To be able to test this PR you will need the changes in [this PR](https://github.com/Yoast/YoastSEO.js/pull/1795) in `YoastSEO.js`. It makes sure that the code in `YoastSEO.js` is correctly exported as ES6 modules.
So either make sure that a local `YoastSEO.js` repo is linked to your local `wordpress-seo` repo and checkout the appropriate branch (`1794-Convert-requires-to-es-modules-index-js`), or wait until the PR in …
> Fixes import of scoreToRating.

- admin/class-admin-asset-analysis-worker-location.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy.php
- readme.txt
- tests/admin/test-class-admin-asset-analysis-worker-location.php
* Fixes a fatal error on the Term and Post-edit pages when the server is running on PHP 5.2.
* Do not change parameters of interface functions.
* Check the tests in version 7.2
Fixes #10925
> Fix admin asset location interface implementation

- inc/structured-data-blocks/class-faq-block.php
- inc/structured-data-blocks/class-how-to-block.php
- js/src/structured-data-blocks/faq/block.js
- js/src/structured-data-blocks/faq/components/FAQ.js
- js/src/structured-data-blocks/how-to/block.js
* Fix json ld title for how to and FAQ block
* Used `get_post` to retrieve title for post.
* Create a post with a title.
* Publish and view the post, inspect the page and look for the generated `json/ld` on the page.
> Fix json ld title how to block

- package.json
- yarn.lock
* n/a
* Bumps the version of Yoast Components to 4.11.0.
* Test changelog items of Yoast Components 4.11.
> Update Yoast Components to v.4.11.0

- frontend/class-opengraph.php
* Fixes incorrect time in OG metadata for published_time.
* published_time used post_date instead of post_date_gmt, leading to a local time without a timezone modifier in the metadata. 
**How to reproduce:** 
* Go to `Settings->General`, set timezone to **"UTC+2"**.
* Create a new post, put the local UTC time in the title (just to make it easier to read). In this example let's say it's '14:19'. If you want to double check the current utc time,  type "current utc time" in google, to make sure you are comparing the news sitemap time with the correct time. 
* Now open the post and view its source. Look for the `meta property="article:published_time"`, it should be "16:19:05+00:00", …
> Fix bug where local time instead of UTC time is used for publication_time in metadata. 

- package.json
- yarn.lock
* _N/A_
* Sassdash has fixed the deprecations, so we can just upgrade sassdash to get rid of the deprecations
* Checkout `trunk`.
* Run `yarn`.
* Run `grunt build:css`.
* See a ton of `DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal in Sass 4.0. Use call(get-function("--join")) instead.`.
* Checkout this branch (`upgrade-sassdash`)
* Run `yarn`.
* Run `grunt build:css`.
* Don't see the deprecation warnings.
> Remove deprecation warnings from `grunt build:css`

- inc/structured-data-blocks/class-faq-block.php
- inc/structured-data-blocks/class-how-to-block.php
Changes `@context` param from `http://schema.org` to `https://schema.org` in structured data blocks output.
* _N/A_
* N/A
* Create a post in Gutenberg, add a FAQ and How to structured data block, with some data.
* Preview the post and inspect the html, and search for the `application/ld+json` script tags output by the FAQ and How To blocks.
* Make sure that the `@context` parameter has the value `https:\/\/schema.org` and **not** `http:\/\/schema.org`.
Fixes #
> Change http://schema.org url to https in json/ld

- frontend/class-opengraph.php
- tests/frontend/test-class-opengraph.php
* Fixes a bug where snippet variables would not be replaced in the `og:description` of taxonomies when they were added in the Facebook Description input field.
* Create a category.
* Go to social settings  > Facebook in the metabox. 
* Use replacevars in the Facebook Description.
* Save and publish the post.
* Go to the frontend and inspect the page.
* The content of `<meta property=“og:description”` should show replaced replacevars.
* Repeat these steps for tags and custom taxonomies.
Fixes #11002
> Replace replacevars in Facebook description

- inc/structured-data-blocks/class-how-to-block.php
- tests/doubles/class-how-to-block-double.php
- tests/inc/structured-data-blocks/test-class-how-to-block.php
* Rename `associatedMedia` property in the How To block's structured data output to `image`, to reflect a change in Google's guidelines.
* Remove superfluous `position` property from the How To block's structured data output.
*
* In Gutenberg, create a new post with a How To block.
* Add a how to step with a title and description.
* Add a how to step with a title, description and an image.
* Publish the post and inspect the `application/ld-json` script element.
* Optionally copy the content of the `script` element into https://jsonformatter.curiousconcept.com/ for better readability.
* Make sure all changes described in #11001 have been applied.
* Also copy the contents into …
> Fixed How To json/ld formatting and added unit-test

- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/components/HowTo.js
* N/A
* Adds `defaultDurationText` to fall back to when no `durationText` is specified. Because saving the default duration text (where the js filter is applied) as the `durationText` attribute makes it populate the field in the block settings when the editor is reloaded, and this is not what we want.
* Follow the steps in #10983.
* Also test if overriding the duration text in the block settings still works, and try reverting to the default duration text again after that.
Fixes #10983
> Added default duration text attribute to use as fallback

- inc/structured-data-blocks/class-faq-block.php
- tests/doubles/class-faq-block-double.php
- tests/inc/structured-data-blocks/test-class-faq-block.php
* Rename `associatedMedia` property in the FAQ block's structured data output to `image`, to reflect a change in Google's guidelines.
* Moved the `@type` and `name` properties to the root of the FAQ block's structured data output.
* Nested `Question` objects in the newly introduced `mainEntity` propery in the FAQ block's structured data output.
* 
* In Gutenberg, create a new post with a FAQ block.
* Add a question with a question, answer and image.
* Add a question with a question and an answer.
* Publish the post and inspect the `application/ld-json` script element.
* Optionally copy the content of the `script` element into https://jsonformatter.curiousconcept.com/ for better …
> Fixed FAQ json/ld formatting and added unit-test

- js/src/structured-data-blocks/how-to/block.js
- js/src/structured-data-blocks/how-to/legacy/8.2.js
- js/src/structured-data-blocks/how-to/legacy/index.js
* N/A
* Added a version specific file (`8.2.js`) in a new legacy folder for an older version of the `How To` block, to keep track of what version a migration belongs to.
* Check out this branch and build it. You can also first verify the issue, starting from the next step.
* Install [`wordpress-seo`](https://github.com/Yoast/wordpress-seo/releases/tag/8.2) version `8.2` into a separate folder (**not** `wordpress-seo`, or whatever folder your development version is in) in your `plugins` folder.
* Activate `Yoast SEO` version `8.2`.
* Create a new post in Gutenberg.
* Add a `How To` block, with a description, a duration and various steps. Don't forget to add an image in at least one …
> Added deprecation for 8.2 how to blocks

- js/src/values/defaultReplaceVariables.js
* N/A
* N/A
* Checkout this branch. 
* Open or create a post. Enter a focus keyword.
* Go to the snippet editor and type`%f`. You'll see 'focus keyphrase' in the dropdown.
* Select 'focus keyphrase'. The label of the snippet variable should read 'focus keyphrase' as well.
* **NB** The snippet variable value doesn't update when you change the focus keyword after you've put the snippet variable in the snippet editor. This is not related to this PR.
Fixes #11041
> Change keyword snippet variable label

- admin/google_search_console/class-gsc-table.php
* Fixes a bug where 'future' date are shown because of wrong interpretation of the date.
This pull should be tested by uploading it as 
* Have some Google Search console data. The best data would be the data from Yoast.com.
* View the option (options table in the database) and the option name `wpseo-gsc-issues-web-not_found` (to make it more readable: unserialize it with unserialize.me (=website))
* Compare the dates with the ones that are displayed in the overview page in the plugin. Most dates will be from september, which might seem okay, but are not.
* See the correct dates are shown.
**For acceptance/integration testers:**
You need very specific live site …
> Use raw the date in GSC for rendering the dates

- inc/options/class-wpseo-option-titles.php
- tests/inc/options/test-class-wpseo-option-titles.php
Called every time `get_option( 'wpseo_titles' )` or `WPSEO_Options::get_all()` is called, `WPSEO_Option_Titles::enrich_defaults()` does a lot of processing (`get_post_types()`, `get_taxonomies()`, etc.)
Microoptimized and cached (with smart invalidation) now.
* Optimize and cache `WPSEO_Option_Titles::enrich_defaults()`
* Uses the WordPress Cache API
* Developed and discussed (in Russian) here https://youtu.be/9ieVrctyMls
* Profile the difference to feel it. Here's a snippet I used (10 CPTs, 10 taxonomies, 10000 iterations):
```
for ( $i = 0; $i < 10; $i++ ) {
register_post_type( "custom-post-type-$i", array( 'public' => true ) );
register_taxonomy( "custom-taxonomy-$i", …
```
> Cache WPSEO_Option_Titles::enrich_defaults()

- frontend/class-opengraph-image.php
* Fixes a bug where a `undefined index` notice is given when an OG image url doesn't have a correct path. Props to @Julian-B90 
* To reproduce this issue create a new post and go to the Yoast Seo social tab, under "Facebook Image" enter ```http://063540.jpfdsfdsfsdg``` or any other broken url. After saving and opening the post you should see an error: ` Notice: Undefined index: path in /srv/www/wordpress-default/public_html/wp-content/plugins/wordpress-seo/frontend/class-opengraph-image.php on line 569`
* Checkout this branch, build, and reload the page. The error should be gone and the page should function normally. 
Fixes #10715
> fix Undefined index:

- package.json
- yarn.lock
* n/a
* Bumps Yoast Components to v. 4.12.1
> Bump Yoast Components to 4.12.1

- admin/taxonomy/class-taxonomy-content-fields.php
- js/src/wp-seo-term-scraper.js
* Introduces the `wpseo_taxonomy_content_fields` filter to add additional fields to the taxonomy metabox.
* This should be tested in combination with https://github.com/Yoast/wordpress-seo-premium/pull/1998
Fixes #[397](https://github.com/Yoast/wordpress-seo-premium/issues/397)
> Applies a filter to add some fields to the metabox

- package.json
- readme.txt
- yarn.lock
* Fixes a bug that caused keywords beginning with the Turkish characters `İ` / `i` and `I` / `ı` not to be recognized when changing that character from lowercase to uppercase and vice versa.
* See https://github.com/Yoast/YoastSEO.js/pull/1624
> Bump YoastSeo.js to 1.40

- admin/class-admin-asset-manager.php
* _N/A_
* Our `babel-polyfill` can always be registered so just add it to our script list.
* When Gutenberg's polyfill is not present then we need to fallback to our own polyfill.
* Gutenberg 3.7 + This patch and before this patch.
> Fix babel polyfill in Gutenberg 3.7

- js/src/helpers/i18n.js
* Compatibility with Gutenberg 4.0.
In Gutenberg 4.0 and the related release of `@WordPress/i18n`, the `getI18n` function will be removed from the API.
Like @atimmer wrote in #10945 :
>We are currently using getI18n() to retrieve the Jed instance from Gutenberg. (...) We don't strictly need it, but we were using it to detect if translations were already loaded, to prevent doing it a second time.
With this implementation we always (re)load the translations, even if they were already loaded. However, this load action is quite cheap, so this shouldn't cause any problems.
* (in Gutenberg, run composer install, npm install and npm run build)
* Checkout master/use 8.3.
* Set your site …
> Remove currentTranslations check because the used geti18n will be removed soon

- admin/class-gutenberg-compatibility.php
* N/A
* We only support the latest version of Gutenberg. 3.9 is the latest version at this moment.
* Install and activate an old version of Gutenberg (< 3.9.0)
* Go to the Yoast Dashboard.
* See this notification:
* Install and activate Gutenberg 3.9.0.
* Go to the Yoast Dashboard.
* See no notification.
> Set minimum supported Gutenberg version to 3.9

- admin/class-admin-init.php
* _N/A_
Plugins/themes should use their own text domain. however, in some cases, using the WP Core translation for a string is warranted, like in this case.
The WP Core text-domain is `default` and while all gettext function call have a [default value of `default` for the `$domain` parameter](https://developer.wordpress.org/reference/functions/__/), explicitly setting the `$domain` in a gettext function call to `default` documents that the intention for this function call was to use the WP Core translation.
For CS purposes, the line still has to be ignored (for now) as it doesn't use the WPSEO text domain.
Once WPSEO upgrades to a more recent version of WordPressCS, the ignore …
> CS/I18n: fix missing text domain in gettext call

- admin/ajax.php
- admin/class-admin-utils.php
- admin/class-admin.php
- admin/class-help-center.php
- admin/class-meta-table-accessible.php
- admin/config-ui/class-configuration-options-adapter.php
- admin/config-ui/class-configuration-page.php
- admin/links/class-link-reindex-dashboard.php
- admin/links/class-link-table-accessible.php
- admin/taxonomy/class-taxonomy.php
- frontend/class-frontend.php
- frontend/class-opengraph.php
- inc/class-wpseo-content-images.php
- inc/class-wpseo-utils.php
- inc/options/class-wpseo-options.php
- inc/sitemaps/class-post-type-sitemap-provider.php
- inc/sitemaps/class-sitemaps-admin.php
- inc/sitemaps/class-taxonomy-sitemap-provider.php
- inc/wpseo-non-ajax-functions.php
* _N/A_
This PR addresses some inconsistencies related to deprecated functions. It basically applies the following rules:
* Deprecated functions/methods should be at the end of the file/class.
* They should be preceded by a `/* *** DEPRECATED METHODS *** */` delimiter to clearly indicate the start of the deprecated functions.
* Deprecated functions should be ignored for the purposes of calculating code coverage via PHPUnit and therefore should each have a `@codeCoverageIgnore` tag in their docblock.
Loosely related to #11058 in that it already moves the two methods that ticket targets down. The functional deprecation of those methods is _not_ addressed in this PR. …
> CS/QA: deprecated functions consistency

- composer.json
- composer.lock
- phpcs.xml
* _N/A_
The PHPCompatibility ruleset is part of YoastCS 1.0+. However, as the WPSEO plugin does not yet comply with the WordPressCS rules from the more recent WPCS/YoastCS versions, WPSEO cannot yet update to YoastCS 1.0+ and still uses YoastCS 0.4.3 which contains WPCS 0.10.0 in combination with PHP_CodeSniffer 2.8.1.
The `PHPCompatibility(WP)` project, fortunately, is still compatible with older PHP_CodeSniffer versions, so while we're working through the WPCS issues, we _can_ already activate the PHPCompatibility checks for WPSEO Free, and by extension, Premium.
To do so:
* The `PHPCompatibilityWP` dev dependency has been added to the `composer.json` file.
* The `config-yoastcs` script in the `composer.json` file has been …
> Build/PHPCS: add PHP cross-version compatibility checks

- js/src/containers/SnippetEditor.js
* N/A
N/A
* Use Gutenberg master.
* Checkout hotfix/8.3.1
* Open a post in the classic editor. See the error from the issue.
* Open a post in the classic editor. Open your console. See that the error is gone.
Fixes #11113
> Add text domain to solve Jed localization error

- yarn.lock
* _N/A_
* 4.7.* of node-sass was not compatible without our version of sassdash. This fixes that.
* Make sure you can build the CSS using `grunt build:css` and the CSS looks good in the plugin.
* Test with a zip to see if this fixes #11112, #11103. It should though.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2024
Fixes #11112
Fixes #11103
> Fixes errors when building CSS

- admin/views/tabs/dashboard/features.php
- admin/views/tabs/network/features.php
* N/A
- fieldset legends should only contain the name of the fieldset, to give a name to the controls they group
- in #10844 the Help button and text was passed as part of the `toggle_switch()` 3rd parameter, which ended up within the fieldset legend
- this PR passes the Help as 4th parameter, which is the one to be used for the Help
- also removes an inline style: we already have the `.yoast-measure` CSS class to apply a `max-width: 600px`
- go to SEO > General > Features  `wp-admin/admin.php?page=wpseo_dashboard#top#features`
- verify there are no visual or functional changes to the toggles and their Help
- on a multisite installation, go to Network > SEO > General > Features …
> Move the help out of the new "feature toggles" legend

- admin/endpoints/class-endpoint-indexable.php
Should be no changelog as the indexable rest endpoint hasn't been released yet.
* Makes the indexable endpoint unique and future proof on the basis of URL alone.
* A post's indexable should be accessible with `/wp-json/yoast/v1/indexables/post/<POST_ID>`.
* A term's indexable should be accessible with `/wp-json/yoast/v1/indexables/term/<TERM_ID>`.
Fixes #11138.
> Fix indexable endpoint singular route.

- admin/config-ui/fields/class-field-google-search-console-intro.php
* Add `target="_blank"` to the "How to connect to GSC" link to open a new tab when click.
* None
* Go to the Configuration Wizard.
* Go to step 8 "Google Search Console".
* Click the link "how to connect Google Search Console to your site."
Fixes #11028
> Add target="_blank" to open new tab when click

- admin/class-yoast-form.php
* _N/A_
See #11067. This PR basically applies the same for a newly deprecated method.
* _N/A_
> CS: Consistency, newly deprecated method

- admin/class-add-keyword-modal.php
- admin/class-admin-init.php
- admin/class-admin.php
- admin/class-database-proxy.php
- admin/class-meta-storage.php
- admin/class-plugin-availability.php
* _N/A_
See:
This commit addresses multi-line function calls where parameters did not each start on a new line.
* _N/A_
> CS: Each parameter should start on a new line in multi-line function calls

- admin/class-asset.php
> CS: Move multi-line parameters out of function calls [2]

- tests/admin/test-class-plugin-compatibility.php
* _N/A_
Functions should be lowercase with words separated by underscores, i.e. `snake_case`.
As methods are case-insensitive in PHP, renaming this will not have any runtime impact.
If the emphasis on `without` is really that important, it might be a better idea to add documentation to the method instead of using all caps in the method name.
* _N/A_
> CS: fix method name

- admin/google_search_console/class-gsc-marker.php
* _N/A_
Decrementors exist for a reason :wink: 
* _N/A_
> CS/best practices: use incrementor/decrementor were appropriate

- tests/frontend/test-class-wpseo-opengraph-image.php
* _N/A_
The `wp_rand()` function is less predictable than the `mt_rand()` function and therefore the better function to use.
Refs:
* https://developer.wordpress.org/reference/functions/wp_rand/
* http://php.net/manual/en/function.mt-rand.php
This is a change to the random number generation used in a unit test and should have no noticeable effects. All should be good if the unit test still passes.
* _N/A_
> QA: use `wp_rand()` instead of `mt_rand()` [2]

- inc/class-wpseo-image-utils.php
* _N/A_
The `wp_rand()` function is less predictable than the `mt_rand()` function and therefore the better function to use.
Refs:
* https://developer.wordpress.org/reference/functions/wp_rand/
* http://php.net/manual/en/function.mt-rand.php
* Good question, but testing this would be a good idea.
Basically, the caching of the post ID retrieval based on an attachment URl, including using the cache when available and setting it when not, should be unaffected.
> QA: use `wp_rand()` instead of `mt_rand()` [1]

- admin/class-premium-upsell-admin-block.php
* Fixes a small typo.
* Not relevant
* Check the upsell notice in your dashboard at the bottom of the page, it should show "Go Premium" instead of "Go premium". 
Fixes #9302
> Fix capital in Go Premium upsell admin block

- admin/class-premium-upsell-admin-block.php
- css/src/yst_plugin_tools.scss
* N/A.
* To reproduce: click "SEO" or "SEO->General" in the sidebar to the left in wp-admin. Scroll down and see the Premium upsell box with the "Go Premium!" title. 
* If the box is not there you may have dismissed it in the past. In that case you can get it back by going into the database. Go into the table `wp_usermeta`, look for the meta_key `wp_yoast_promo_hide_premium_upsell_admin_block` and change its meta_value into `0`.
* Checkout this branch and look at the box again, the styling should have been changed according to the instructions in the issue (#10982). Make sure to do a hard refresh if the styling does not change.
* Also make sure the button functions properly and goes …
> Updated styling of the premium upsell box in the settings. 

- js/src/components/MediaUpload.js
* N/A
When hiding or removing from the DOM an UI control that's currently focused, there's a focus loss. This should be avoided at all costs, as it's a terribly confusing experience for keyboard and assistive technology users. Either don't remove a focused element (preferable) or manage focus programmatically, moving it to the most logical place.
This PR avoifs a focus loss when removing an uploaded image in the configuration wizard.
- go to the configuration wizard, step 4
- choose company
- choose an image
- now, using only the keyboard, remove the image:
- notice focus is lost (there's no focused element in the page); the focus loss is more evident in some browsers, for example IE11
Note: for testing purposes, I recommend to …
> Configuration wizard: manage focus when removing uploaded image.

- admin/views/tabs/metas/paper-content/date-archives-settings.php
* Date archives help text contains faulty information
* Removed an incorrect part of the Date archive settings description.
* Go to search appearance > taxonomies.
* Click to question mark.
Fixes #9317
> #9317 Fixed the date archives settings description.

- js/src/components/AnalysisUpsell.js
- js/src/components/contentAnalysis/SeoAnalysis.js
* N/A
*
* Link `yoast-components` branch `11199-add-upsell-link-button-component` and build the project.
* In Gutenberg, make sure the upsell like shown in #11199, is visible in both the sidebar (Where the button should be under the text) and in the metabox (Where the button should be right of the text).
* In the classic editor, make sure the upsell is visible in the metabox.
* Merge this branch into `wordpress-seo-premium`.
* Make sure upsell is not shown in both Gutenberg and the classic efitor.
Fixes #11199
> Added the AnalysisUpsell component for the word forms upsell

- admin/views/tabs/social/facebook.php
* Fixes a bug where the home description can contain HTML resulting in unexpected characters on the Facebook social settings
* Set the description for the home page ( search appearance ) to something like: `Description "/>`
* Open the facebook settings ( social ) and see some weird output `"/>`, that doesn't belong there.
* See it is gone.
Fixes #11230
> Use esc_attr for the value

- inc/sitemaps/class-sitemaps-cache.php
- tests/sitemaps/test-class-wpseo-sitemaps-cache.php
* Fixes a bug where author caches would be attempted to be invalidated despite not all conditions being met.
*
* There is no real way to test this from a user's perspective, as it's not user-facing. The only way to validate that this is working correctly, is to see that the tests pass.
Fixes #11255
> Ensure invalidation of author caches happen when all conditions are met

- js/src/components/contentAnalysis/SeoAnalysis.js
* N/A
* In order to position the question mark link,
* It would make it a lot more complex to make the question mark and brackets unbolded. That's why I decided to keep it bold. @hedgefield does agree.
* Link https://github.com/Yoast/yoast-components/pull/757
* Look at the metabox and sidebar and see if they match the screenshots from the issue.
Fixes Yoast/wordpress-seo#11235
Requires Yoast/yoast-components#757
> Replace keyword help text by a question mark link

- js/src/components/contentAnalysis/SeoAnalysis.js
Renames `FocusKeywordLink` to `HelpLink` and export it for reuse.
> Rename FocusKeywordLink and export it.

- inc/class-wpseo-meta.php
* Reverts the commit https://github.com/Yoast/wordpress-seo/commit/91aa78bce6a90f40237aa3e37c7eb4cb5e9a6cd3 to be able to save focus keyphrases enclosed in double quotes. This is needed to be able to make morphology-suppressing functionality functioning again.
* The original modification that stripped double quotes from the focus keyphrase field was introduced as a security patch. This security issue is no more relevant after reactifying the focus keyphrase component. Thus, the stripping can be deprecated. 
* Build the branch together with the release-yoast-seo/9.0 (e.g., using `yarn link`).
* Check if changing focus keyphrase field works as expected when creating, saving, changing …
> Re-allow double quotes in the focus keyphrase field

- js/src/components/AnalysisUpsell.js
* N/A.
* Added a new styled.div to give the caret in the button padding. Another solution would be to give the styled.svg component in yoast-components an additional prop for receiving padding. 
* Before checking out this branch, check the current situation. You should see that in the metabox, in the "Focus keyphrase" section the "Go Premium!" button is to the far right. Also, the caret in the button is right behind the text, without any space between. 
* Checkout this branch, build and look at the style again: The button should be outlined with the snippet preview. The upsell box (text and button) should have the same with as the snippet preview. Also, space should be added between …
> Updated styling of button to match design

- admin/class-expose-shortlinks.php
- inc/class-wpseo-shortlinker.php
- tests/inc/test-class-wpseo-shortlinker.php
* N/A
* This PR allows exposing of the query arguments that were previously only available in the Shortlinker so that they can be passed along to the webworker / YoastSEO.js via the `expose_shortlinks` function as a hard-coded property of `default_query_args`. See https://github.com/Yoast/wordpress-seo/issues/11254 as to why this is necessary.
* For RC testers: this is a non-userfacing change. The user-facing change will be made in https://github.com/Yoast/YoastSEO.js/issues/1876.
* Ensure that links that are currently being exposed via the `Expose_Shortlink` class still properly append the query arguments. Some links can be found in the Snippet Editor. 
* Ensure that the …
> Extract URL-encoded query arguments into its own function

- inc/class-upgrade.php
- inc/sitemaps/class-sitemaps-admin.php
- inc/sitemaps/class-sitemaps-cache.php
- inc/sitemaps/class-sitemaps.php
- tests/sitemaps/test-class-wpseo-sitemaps-cache.php
- tests/sitemaps/test-class-wpseo-sitemaps.php
* Improves the performance of the sitemap by disabling cache for it by default.
* Checkout trunk and make sure caching is enabled.
* Open the database (phpmyadmin) and navigate to the `wp_options` table. Use the search and for the field `option_name` you enter `%transient%` as searchphrase. 
* You should have a couple of transiens with `yst` in it.
* Checkout this branch. 
* In the Yoast Test helper plugin set the version to 8.4
* Go to the database and see the transients are gone
* Refresh the sitemap_index.xml and verify no transients are being saved.
Fixes #11258
> Disable sitemap cache by default

- js/src/components/contentAnalysis/SeoAnalysis.js
* N/A
* Rename labelSiblingElement to helpLink. See https://github.com/Yoast/wordpress-seo-premium/pull/2060#discussion_r225431144
* Link https://github.com/Yoast/yoast-components/pull/758
* Check if the question mark help link in the metabox and sidebar is still functioning and not throwing prop errors.
Fixes Yoast/wordpress-seo-premium/issues/2058
>  Rename labelSiblingElement to helpLink

- admin/class-social-admin.php
- admin/class-yoast-form.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-fields-presenter.php
- admin/taxonomy/class-taxonomy-social-fields.php
- frontend/class-opengraph-image.php
- inc/class-wpseo-meta.php
- inc/options/class-wpseo-option-social.php
- inc/options/class-wpseo-taxonomy-meta.php
- js/src/wp-seo-admin-media.js
- tests/taxonomy/test-class-taxonomy-presenter.php
* Changes OpenGraph image handling to always use an image from the media library. This makes the performance of the OpenGraph image handling much better.
* I haven't changed anything to the Twitter image, because it doesn't have dimension information. I did add the ID field to the twitter image field, because that could prove useful in the future.
* The frontend will try to use the attachment ID, if there isn't an ID it will save the ID it finds from `attachment_url_to_postid`. This means that every page that doesn't have an ID saved yet, will get an ID after loading it once. This should massively reduce the amount of calls to `attachment_url_to_postid`.
* Because I changed the image URL field to be readonly, I've added a "Remove …
> Always use an ID for the OpenGraph image

- admin/class-expose-shortlinks.php
- inc/class-wpseo-shortlinker.php
- js/src/analysis/getDefaultQueryParams.js
- js/src/analysis/worker.js
- tests/inc/test-class-wpseo-shortlinker.php
* N/A
* Change the exposed shortlinks `default_query_params` to be an array instead of a string [introduced in PR](https://github.com/Yoast/wordpress-seo/pull/11285). Because this is how it is handled on the JS side.
* Includes the `default_query_params` in the analysis worker initialize call.
* Ensure that the `default_query_params` key has been properly exposed and contains the correct system information. The easiest way to check this is by calling `wpseoAdminL10n.default_query_params` in your browser's console.
* _Can only be done in development_ See the console for the first `wrapper -> worker initialize` message. Ensure `queryStringAppender` is included in the configuration …
> Change the exposed shortlinks default_query_args to be an array instead of a string

- admin/class-customizer.php
* _N/A_
While working on the multi-line function call changes, I noticed that the `WPSEO_Customizer` class contained a lot of duplicate code.
This PR:
* Abstracts the duplicate code to a private `add_setting_and_control()` utility/helper method.
* Moves the default settings used by nearly all of the methods to class properties.
* Adjusts the code in the methods to use the helper methods instead.
While working on this, I noticed one inconsistency: the breadcrumb separator setting has a different ID, `breadcrumbs-sep`, from the associated control `(wpseo-)breadcrumbs-separator`.
In all the other cases, these are in sync.
Please let me know if I should update this PR to let these IDs always be in sync.
In …
> Refactor the `WPSEO_Customizer` class

- admin/views/sidebar.php
* Wrap string "Remove these ads?" in `esc_html_e()` function to allow translation
* Use the exact same gettext functions for similar strings in the same sidebar
* Sweep the code again with Poedit
* Translate new string
* Visit Yoast SEO dashboard to check if the string is translated
Fixes #11195
> [i18n] Add missing gettext function

- js/src/components/contentAnalysis/SeoAnalysis.js
* N/A
* I've changed the default of `results` in mapStateToProps to make it more sensible.
* The overallScore prop is no longer required. The default value is `null`, to make sure the loading spinner is shown as long as there is no overallScore set. 
* The marksButtonStatus prop is no longer required. The default value is `null`, to make sure there are no prop type warnings on the first pass of mapStateToProps, before the marksButtonStatus is set.
* Checkout release/9.0. Open the analysis at a post. Check that the console errors from the issue are there.
* Checkout this branch. Open the analysis at a post. Check that the console errors from the issue are gone.
Fixes #11323
> Fix SeoAnalysis proptype errors

- css/src/admin-global.scss
* N/A
* N/A
* Test for all buttons listed here https://github.com/Yoast/wordpress-seo/issues/10980#issue-359451824 that the line height is in proportion, when the text is spread over multiple lines (on small screens).
* Also check that those buttons still look nice on bigger screens.
Before:
After:
Fixes #11189
> Fix upsell button line height

- js/src/components/AnalysisUpsell.js
* N/A
- allows the flex items to be sized accordingly to their content:
- test in IE11 the buttons in the metabox and sidebar look OK; previously, they looked this way:
- check in modern browsers there are no visible changes (see screenshots below)
Chrome before:
Chrome after:
Fixes #11331
> Fix Go Premium button flexbox in IE11

- frontend/class-opengraph-image.php
- frontend/class-twitter.php
- tests/doubles/class-opengraph-image-double.php
- tests/frontend/test-class-twitter.php
- tests/frontend/test-class-wpseo-opengraph-image.php
* N/A
1. Checkout `release/9.0`
1. Set a default opengraph image under Yoast - Social - Facebook
Create a post (without any images being set in there)
1. Open the post and view its source. Verify that the default og image has been set as `og:image` metatag.
1. Edit the post by adding some images to its content.
1. View the source again and see the metatag is still there.
1. Checkout this branch
1. Refresh the page and see the first content image is set in the metatag
Fixes #11345
> Only show default opengraph image when content doesn't contain images.

- composer.json
- composer.lock
- inc/sitemaps/class-sitemap-image-parser.php
- phpcs.xml
* _N/A_
[PHPCompatibility 9.0.0](https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.0.0) has just been released and renames all sniffs.
[PHPCompatibilityWP 2.0.0](https://github.com/PHPCompatibility/PHPCompatibilityWP/releases/tag/2.0.0) has been released alongside it.
* Updated the version restrictions in `composer.json` & updated the `composer.lock` file.
- As this PR takes us past the sniff re-names, we can now safely use a `^2.0` type version requirement.
- I've done a selective update, updating just the PHPCompatibility and Security Advisories packages.
- The `config-yoastcs` script has been updated for a change (new dependency) in PHPCompatibilityWP.
Unfortunately, we still can't use a Composer plugin for …
> CS/QA: Update for PHPCompatibility 9.0.0 / PHPCompatibilityWP 2.0.0

- js/src/components/contentAnalysis/ReadabilityAnalysis.js
- js/src/components/contentAnalysis/SeoAnalysis.js
* N/A
* Remove readability help text.
* Add question mark help link to readability analysis.
* Change the colors of the link. The colors should be similar to those of the question marks in the settings. This means: grey by default and when active, and blue when focus or hovered. I used colors from the colors.json, which means that the colors are slightly different from those in the SEO settings (where WP colors are used).
* Check that the readability help text is gone.
* Check that there is a question amrk help link after 'analysis results' in the readability analysis, and check if the styling is right.
* Check the colors of the link button in the keyword analysis sections. Don't …
> Add question mark help link to readability analysis and change its color

- inc/class-wpseo-meta.php
* Fixes a bug where notices were being thrown when quick editing a post and no post type object could be found.
Fixes #10970
> Fix minor php notice

- package.json
- yarn.lock
* n/a
* Update YoastSEO.js to 1.41.0.
* Check whether the functionality introduced in YoastSEO.js works:
* Fixes a bug where the keyword would not be found in the slug when containing punctuation, for example the keyphrase `apples & pears` in the slug `apples-pears`.
* Introduces two new principles for keyword recognition:
* Makes keyphrase recognition flexible with regards to word order. This means that the keyphrase `SEO WordPress plugin` will be found in the sentence `This is the most popular SEO plugin for WordPress.` In order to use exact matches, the keyphrase can be enclosed in quotation marks.
* When matching keyphrases for the various assessments, the analysis only targets …
> Update YoastSEO.js to 1.41.0

- js/src/structured-data-blocks/how-to/block.js
* N/A
* Before, Gutenberg didn't check if the type of the attributes was the correct one. Days, hours and minutes were defined as type `number`, but were saved as `string`s  in the database. When you reopened the post, the mismatch causes the attributes to be stipped completely, which results in block validation errors. 
* Install the Gutenberg 4.1 RC from https://make.wordpress.org/test/2018/10/19/call-for-testing-gutenberg-4-1-pre-release/
* See https://github.com/Yoast/wordpress-seo/issues/11364 for steps to reproduce. Make sure you set a duration in your how to block.
* Don't forget to test with Gutenberg 4.0 as well to make sure nothing breaks.
Fixes #11364
> Change the type of the days, hours and minutes attributes from number to string

- admin/class-admin-init.php
I preferred to maintain the Wordpress look and feel for the warning box. But I may change it according to the issue if necessary.
* Adds a warning notification to the permalink settings page, linking to a KN article. Props to @valtlfelipe 
*
* Going to Permalink settings page
Fixes #9616
> Add permalink warning on settings page

- js/src/wp-seo-admin-media.js
- readme.txt
* Fixes error with using `$` in wp-seo-admin-media.js. Now we use `jQuery` instead.
Fixes #11378
> Use $ jQuery shortcut only within jQuery wrapper

- js/src/wp-seo-featured-image.js
* Fixes a bug where the featured image was not recognized in the SEO analysis when using Gutenberg. 
* The featured image has no id anymore in Gutenberg, used the store instead to get the data for the analysis. 
* Reproduce by creating a new post, with Gutenberg activated, and adding a new featured image. The SEO analysis should still give the red dot: 'Image alt attributes: No images appear on this page. Add some!'. 
* Open the same post in the classic editor and see the image is recognised correctly there.
* Checkout this branch and go back to the post in the Gutenberg editor: The image should now be recognised (orange dot). If you change the image's alt text so it includes your …
> Fixes a bug where the featured image was not recognised in our SEO analysis is in Gutenberg. 

- grunt/config/aliases.yaml
- grunt/config/clean.js
* N/A
* Split `grunt clean:build-assets` into `grunt clean:build-assets-js` and `grunt clean:build-assets-css`, which are added to `grunt build:js` and `grunt build:css` respectively. This makes sure that old built CSS and JS files are always removed on every build. This change was induced by returning css build errors, as reported in https://github.com/Yoast/wordpress-seo/issues/11412 and https://github.com/Yoast/wordpress-seo/pull/11117.
* Removes `before-rtlcss`, because` 'clean:build-assets-css'` now does the same (and `"css/dist/toggle-switch/*.css"` no longer exists).
* Run `grunt clean:build-assets` and see that  `grunt clean:build-assets-js` and `grunt …
> Add clean tasks to build:js and build:css

- js/src/wp-seo-featured-image.js
* N/A
* In https://github.com/Yoast/wordpress-seo/pull/11377 functionality to include Gutenberg featured images in the analysis. However, when no featured image was set, an API call with id `0` was done, resulting in a 404. This PR returns if the assumed featureImageId is 0, meaning no API will be done.
* Check out and build release/9.1.
* Open a new Gutenberg post. Open the document sidebar (where you can set a featured image, but don't do that ;) ). See the following console errors:
* Open an existing Gutenberg post without a featured image. Open the document sidebar and see the same console errors.
* Check out this branch. Repeat the first two steps, and see no API call returning …
> Fix featured image API call

- admin/class-bulk-editor-list-table.php
- admin/google_search_console/class-gsc-category-filters.php
* Improve the accessibility of the "Bulk editor" and "Search console" tables.
* adds an `aria-current="page"` to the list table current view link, also for consistency with what WordPress does
- navigate through the "Bulk editor" and "Search console" tables "views" (e.g. All, Published, Scheduled... Not found...)
- verify the current link (the bolded one with a `current` CSS class) has an `aria-current="page"` attribute
Fixes #7933
> Add `aria-current` to the list tables current view link

- package.json
- yarn.lock
* n/a
* Bump YoastSEO.js to v1.41.1 and Yoast Components to 1.41.1.
* Test whether the fixes from these two PRs work:
* https://github.com/Yoast/YoastSEO.js/pull/1918
* https://github.com/Yoast/YoastSEO.js/pull/1910
Fixes #
> Update YoastSEO.js and components

- admin/class-premium-popup.php
- admin/class-premium-upsell-admin-block.php
- admin/views/licenses.php
- admin/views/sidebar.php
- admin/watchers/class-slug-change-watcher.php
- css/src/_icons.scss
- css/src/admin-global.scss
- css/src/extensions.scss
- css/src/yoastcom/_promoblock.scss
- js/src/components/UpsellBox.js
- js/tests/components/__snapshots__/UpsellBox.test.js.snap
* N/A
- introduces a new (left) caret icon 
- instead of using background images directly on the button, use the image as background of an inline `<span>` element so it behaves like inline content
- refactors the CSS to use `inline-flex` so the text and the icon are better aligned vertically
- the upsell button can now be used also without an icon (if necessary) so it's better reusable
- reuses the `yoast-button-upsell` also in the Extensions page
- adds the "new tab message" to all links that open in a new tab in the extensions page
- incorporates the line-height fix from #11334 
The upsell button needs to be checked everywhere it appears, and also in the responsive view. As far as I know, it is used:
- in the notice when …
> (new) Improve the upsell button caret icon position in RTL languages

- inc/class-wpseo-utils.php
* Fixes a bug where the Yoast metabox is visible even when the attachment urls are redirected to the attachment file itself.
*
* Disable the media feature under search appearance - media
* Edit a media item and see the yoast metabox being visible
* The metabox should be gone. 
Fixes #
> Checks if attachments are disabled for Yoast SEO

- frontend/class-opengraph.php
There are some locales missing the name because I could not found anything about it.
* Adds the latest og:locale options provided by Facebook
* 
* Because it's a datalist it is hard to test. You might want to set one of the locales and see it appearing as OG tag on the frontend. Non-allowed locales will result in 'en_US'
Fixes #10415
> Update og:locale options

- package.json
- yarn.lock
* n/a
* Bumps YoastSEO.js to v. 1.42.0.
* Check whether the following works: 
* https://github.com/Yoast/YoastSEO.js/pull/1823
* https://github.com/Yoast/YoastSEO.js/pull/1912
Fixes #
> Bump YoastSEO.js to 1.42.0

- admin/metabox/class-metabox.php
* N/A
* Sets the `__block_editor_compatible_meta_box` flag to true in our metaboxes. Right now this does not do anything, but it may prevent incompatibility warning messages in the future. 
* Though the flag is specifically for metaboxes, there have also been reports that the warning message is also shown in dashboard widgets. This seems to have been unintended (as wp internally uses `add_meta_box` in it’s `wp_add_dashboard_widget` function). As far as I know this has been fixed: I have not been able to reproduce the message in the widget. 
* As this is a fix to prevent something from changing, there is no change to test. Nothing should break though.
* If you really, really want to …
> Set Gutenberg compatibility flag to true for meta boxes

- admin/class-config.php
- admin/class-export.php
- admin/import/class-import-settings.php
- admin/views/tabs/tool/wpseo-export.php
- admin/views/tabs/tool/wpseo-import.php
- admin/views/tool-import-export.php
- tests/admin/import/test-class-import-settings.php
- tests/doubles/class-import-settings-double.php
- wp-seo-main.php
* Replaces Settings ZIP download (export) and upload (import) functionality with Settings fields.
* Go to Tools → Export settings, export a site’s settings.
* Copy the exported settings.
* Go to Tools → Import settings and paste those exported settings.
* Modify the settings slightly, for instance changing twitter card format from `summary_large_image` to `summary` to see if settings have been truly imported.
> Change import settings logic

- admin/views/user-profile.php
* Hides SEO title and metadescription fields on the author edit page when the author archives are disabled
*
* Disable the author archives 
* Edit an author and see that you can give a title and metadescription. You also can set the noindex value for the author.
* See the three fields are hidden.
Fixes #11497
> Hides the fields when author archives are disabled

- js/src/wp-seo-replacevar-plugin.js
* N/A
* This pull introduces a fallback where the replacementVariables from the store are used to replace missed replacement variables.
* Test this together with https://github.com/Yoast/wordpress-seo-premium/pull/2112
> Add fallback to replace everything from the store

- admin/class-admin-asset-manager.php
* _N/A_
* After Herre's PR refactoring the wp assets, this method is no longer in use.
> Remove unused method

- css/src/admin-global.scss
* Tooltips: remove local fix for Edge support
* Removed a deprecated browser fix.
* Open your WP Admin Area in the Microsoft Edge browser on a desktop device.
* Go to the Admin Post List (/wp-admin/edit.php).
* Hover the Internal Links counter.
* Everything should look as usual.
Fixes #7461
> #7461 Removed the local Tooltips fix for Edge support.

- css/src/yoast-components.scss
* Fixes a bug where texts in the configuration wizard would overlap each other and break out of the columns in Internet Explorer 11. Props [DrGrimshaw](https://github.com/DrGrimshaw)
* Use of IE specific media queries so as to not affect other browsers
* Use IE11 to view the welcome page of the configuration wizard
Fixes #11332
> Issue Fix: 11332 - Conf wizard welcome page in IE11

- inc/exceptions/class-invalid-argument-exception.php
- src/yoast-model.php
- tests/doubles/class-wpseo-gutenberg-compatibility-double.php
- tests/doubles/wpseo-link-reindex-dashboard-double.php
- tests/sitemaps/test-class-wpseo-sitemaps-router.php
- tests/src/integration-tests/config/upgrade-test.php
- tests/src/unit-tests/config/upgrade-test.php
- tests/src/unit-tests/formatters/indexable-term-formatter-test.php
- tests/src/unit-tests/wordpress/integration-group-test.php
* _N/A_
Various minor documentation fixes:
* Spelling and punctuation.
* Blank line above the first `@tag`
* No two consecutive blank lines in a docblock.
* All function parameters should be documented.
* `@param` comments should specify parameter type + have a comment explaining what the parameter signifies.
* _N/A_
> CS: various minor docs fixes

- inc/class-wpseo-meta.php
* Removing check for register_meta as it will be sticking around. Discussed in this issue: https://github.com/Yoast/wordpress-seo/issues/6688
* Less code, less bloat!
* N/A
Fixes #
> register_meta is here to stay

- js/src/wp-seo-term-scraper.js
* Fixes a bug where non-functional markers are shown for taxonomy pages .
*
1. Checkout trunk 
1. Do the yarn and build magic
1. Edit an taxonomy by pasting text into its description
1. Go to the analysis and see some marker icons.
1. Press one the marker icons and see it is not working
1. Checkout this branch
1. Do the build magic (again)
1. Do step 3 again
1. Go to the analysis and verify the marker icons are gone. 
Fixes #10563
> Hide the markers by default

- tests/src/unit-tests/wordpress/integration-group-test.php
* _N/A_
... to comply with the WP variable name naming convention, which is still `snake_case`.
* As these are variables in a unit test file, all should be good if the unit tests pass.
> CS: rename two local variables

- admin/filters/class-cornerstone-filter.php
* Fixes a bug where the cornerstone filter is still visible when the metabox is disabled.
* Disable the Yoast metabox for the posttype: post
* Go the the post overview and see the cornerstone filter still being visible.
* Refresh the post overview page and verify that the cornerstone filter is gone.
Fixes #9294
> Use the has_metabox_enabled filter

- frontend/class-breadcrumbs.php
- frontend/class-json-ld.php
* Adds the page number to the breadcrumbs when an archived page is entered.
* Added `hide_in_schema ` to the breadcrumb to filter this out from the `schema.org` output. This can be change/undone when #9664 will be fixed.
* Have a lot of posts, this results in pagination on the archives.
* When navigation to the second page you will see 'Page 2' in the breadcrumbs.
* The Page 2 shouldn't be added to the JSON-LD Schema.org output
* Addition of the page number should only be applied for paginated pages like: the index and archives.
Fixes #1928
> Adds page number to the visible breadcrumbs

- admin/class-extension.php
- admin/class-extensions.php
- admin/views/licenses.php
Adjust the copy of the Local SEO upsells to include the important Local SEO for Woo entry.
* Removes Local SEO for WooCommerce from the Premium page as this plugin is merged into Local SEO since 9.2.
* N/A
* Go to the Premium page under SEO
* See Local SEO for WooCommerce is no longer there
* See the Local SEO upsells being updated
* See the order of extensions being changed
Fixes #11561
> Remove Local for Woo from the extensions page

- frontend/class-opengraph.php
- inc/class-wpseo-replace-vars.php
* Fixes a bug where escaped HTML is shown in the OpenGraph description.
* This should be tested on a Gutenberg post
* For the meta description use the `%excerpt%` replacement variable. Have no excerpt entered and enter some text as content. 
* Leave the OpenGraph description empty
* Save the post
* Go to the frontend and see a normal non escaped HTML string as meta description.
* But the `OG:description` will contain escaped HTML. For an example see the screenshot below:
* Checkout this branch and see it is solved.
> Strip html tags og desc

- frontend/class-json-ld.php
- tests/test-class-wpseo-json-ld.php
Also prevents escaping of the output when possible (PHP 5.4+).
* Changes the output of schema preventing unnecessary escaping of forward slashes, only available on sites running PHP 5.4 or higher.
* Changes the website schema `@id` attribute to include the home URL to be a unique identifier.
* See the descriptions in the relevant issues
* Open the homepage and view the source, the structured data (ld+json)
`<script type='application/ld+json'>{"@context":"https://schema.org","@type":"WebSite","@id":"http://local.wordpress.test/#website","url":"http://local.wordpress.test/","name":"Default","potentialAction":{"@type":"SearchAction","target":"http://local.wordpress.test/?s={search_term_ …
> Prepend home URL to @id of WebSite

- js/src/wp-seo-post-scraper.js
* Fixes a bug where the marker buttons would still be enabled in the text view, despite not being functional.
*
* Create a post in the Gutenberg editor and ensure that you see at least one eye marker button in the readability or SEO analysis.
* Ensure that the marker button properly works.
* Switch to the Code View by selecting the three dots in the upper-right corner.
* See that the eye marker button(s) is/are disabled.
* Save the post in the current view and refresh the page.
* Open up the readability analysis and see that the markers are still properly disabled on a page reload.
Fixes #11593
> Implemented extra check to disable the markers if we're in the text view

- admin/class-admin-asset-manager.php
* Fixes a bug where the configuration wizard would not load in Internet Explorer 11 when Gutenberg was active.
* Because IE11 needs wp-polyfill to be registered before react, we add wp-polyfill as a dependency to react. If Gutenberg would do this, this fix can be reverted. I've created a PR on Gutenberg: https://github.com/WordPress/gutenberg/pull/11916.
* Follow the steps from the issue.
Fixes #11597
Fixes #11603
> Add wp-polyfill as dependency to react to fix IE11 bug

- js/src/wp-seo-post-scraper.js
Fixes Classic Editor functionality after the merge from https://github.com/Yoast/wordpress-seo/pull/11602
> Wrap in Gutenberg conditional

- package.json
- yarn.lock
* n/a
* Bumps the version of YoastSEO.js to 1.43.0.
Check whether the following work:
* Fixes assessments failing when using a `<` sign in the content. https://github.com/Yoast/YoastSEO.js/pull/1898
* Fixes a bug where paragraphs were sometimes not correctly detected because paragraph tags were not automatically added in WordPress-like fashion. https://github.com/Yoast/YoastSEO.js/pull/1911
* Disables the non-functioning markers for the subheading distribution assessment. https://github.com/Yoast/YoastSEO.js/pull/1958
> Bump YoastSEO.js to 1.43.0

- js/src/decorator/gutenberg.js
- js/tests/decorator/__mocks__/@wordpress/rich-text/index.js
- js/tests/decorator/gutenberg.test.js
* N/A
*
* in Gutenberg, create an article with the following paragraph:
`
Parked men were sitting in a parked car, parked, waiting to pick someone up. Parked men were Sitting in a parked car, parked, waiting to pick someone up d. Parked men were Sitting in a parked car, parked, waiting to pick someone up. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ipsum mi, malesuada convallis purus ut, feugiat tempus arcu. Integer id blandit mauris. Nullam quis mauris rutrum, imperdiet sapien ut, porta est. Quisque commodo odio at dolor tempor pulvinar. Fusce lorem tellus, faucibus et auctor at, porttitor non purus. Duis bibendum quam non tortor blandit, nec varius felis tincidunt. …
> Allow repeated sentences and multiple parts within a sentence to be annotated.

- admin/class-admin.php
- admin/notifiers/class-stale-content.php
- tests/doubles/class-stale-content-notification.php
- tests/notifiers/test-class-stale-content-notification.php
* Shows a notice about stale content, when the recalibration beta is enabled.
*
* Enable the recalibration beta under features
* See you have a notice on the dashboard that tells about the stale content and which refers to the post overview.
* Disable the post type `post` by adding the following filter somewhere in your code (wp-seo-main.php):
```
global $wp_post_types;
unset( $wp_post_types['post'] );
} );
```
* Now the notice refers to the page overview.
* Also disabled the post type `page` by adding:
```
global $wp_post_types;
unset( $wp_post_types['page'] );
} );
```
* Now the notice says something general.
* …
> Adds stale content notice

- frontend/class-breadcrumbs.php
* Uses class _WPSEO_WooCommerce_Shop_Page_ instead of function [_wc_get_page_id_](https://docs.woocommerce.com/wc-apidocs/function-wc_get_page_id.html).
* Class _WPSEO_Breadcrumbs_ already uses class _WPSEO_WooCommerce_Shop_Page_, but there is old code which uses WC api. This PR makes consistency in usage of class _WPSEO_WooCommerce_Shop_Page_.
* Testing isn't needed because this PR uses already tested methods from class _WPSEO_WooCommerce_Shop_Page_. Also, it's possible to repeat test from PR #10229.
Fixes inconsistency in class _WPSEO_Breadcrumbs_.
> Uses class WPSEO_WooCommerce_Shop_Page in Class WPSEO_Breadcrumbs

- js/src/components/PrimaryTaxonomyPicker.js
- js/src/components/TaxonomyPicker.js
* Fixes a bug where the 'Select primary category' label in the primary taxonomy picker would overlap the 'Add new category' button.
* I've added an extra `<div>` around the select (=dropdown) to add padding between the label and the dropdown, because:
- adding padding/margin to the label above select didn't do anything
-  styled-components can't add padding/margin to a `<select>`
* I've tested this with a screenreader, which seems to handle the added `<div>` well (i.e. not announcing it/not requiring extra tabs to reach the actual `<select>`)
On trunk:
* Open the document panel in the Gutenberg sidebar. 
* Open the categories collapsible
* Select multiple categories, now the "Select …
> Fix overlapping primary category label

- .travis.yml
* Tested against PHP 7.3 and the upcoming WP 5.0 release.
Once PHP 7.3-beta came out, the `nightly` build on Travis became PHP 7.4-dev and builds haven't been tested against PHP 7.3 for months now.
Travis has (finally) made a PHP 7.3 alias available, so I've updated the "highest" build to test against PHP 7.3 so there won't be any unwelcome surprises when PHP 7.3 comes out.
As WP 5.0 is being developed against a dedicated branch and `latest` is WP 5.1 (to be), WPSEO wasn't being tested against WP 5.0, so - until WP development moves back to `trunk` -, the `WP_VERSION` for bleeding edge should be `5.0`, not `latest`.
* _N/A_
Once the …
> Build/Travis: test builds against PHP 7.3 / WP 5.0

- grunt/config/set-version.js
- grunt/custom/update-recalibration.js
* N/A
Due to the grunt task of the `set-version` not being called with a task specification, the current process also runs the recalibration set-version task with the version of the plugin.
The recalibration task is temporary. Therefore, it seems better to adjust that task than to adjust the process.
* Move recalibration from set-version into update-recalibration.
* Checkout the release branch: `git checkout release/9.3`.
* Run the set version command as used in the process: `grunt set-version --new-version=9.3-test`.
* Check `package.json` to see what changed: `git diff package.json`.
* Verify that both the pluginVersion and the recalibrationVersion are now on `9.3-test`. This is …
> Fix recalibration version being set as plugin version

- frontend/class-frontend.php
Genesis disables it’s internal SEO features if Yoast is active so there is no risk of duplicate rel links.
Fixes https://github.com/Yoast/wordpress-seo/issues/9331
* Remove Genesis checks in adjacent_rel_links() method.
* Genesis disables its SEO functionality when Yoast is active so there is no risk of duplicate links. Right now we have no links in Genesis because of this check.
Genesis by itself shows rel prev/next links.
Genesis with Yoast does not show rel prev/next links.
Genesis with Yoast and the following filter does show rel prev/next links:
`add_filter( 'wpseo_genesis_force_adjacent_rel_home', '__return_true' );`
* Genesis with Yoast and no additional code will now show …
> Remove Genesis checks in adjacent_rel_links()

- admin/config-ui/fields/class-field-google-search-console-intro.php
- admin/google_search_console/views/gsc-display.php
- admin/links/class-link-compatibility-notifier.php
- admin/links/class-link-notifier.php
- admin/links/class-link-table-accessible-notifier.php
- admin/notifiers/class-post-type-archive-notification-handler.php
- admin/views/tabs/metas/paper-content/media-content.php
- admin/views/tabs/metas/taxonomies.php
* Removes new lines and tabs from translation strings
* Removes unnecessary spaces from strings beginning
* Removes unnecessary space from string ending
* Separate common sentences to reuses strings and avoid translation repeating
* Used same code patterns used along the existent code
* Separated strings wherever exists a line break
* Kept sentences several strings in the same string if there weren't a line break
Fixes #9353
> [i18n] Remove new lines and tabs to improve i18n and l10n

- js/src/analysis/data.js
- js/src/decorator/gutenberg.js
- js/src/redux/selectors/results.js
- js/tests/data.test.js
* N/A
*
* In Gutenberg, create a new post and write some content that will trigger readability assessments with markers. For instance paragraph length.
* Enter a keyphrase that is found within your content.
* Now activate a marker.
* Edit the content of your post and notice that the markers are updated after a short while.
Also:
- Test functionality in Classic editor markings
- Test functionality in Classic Editor plugin
Fixes #11571
> Call marker function again when content changed in Gutenberg

- js/src/components/contentAnalysis/Results.js
* Fix the headings hierarchy in the analysis results.
In Chrome, you can check the heading hierarchy using this Chrome extension:
HeadingsMap
https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi
- before switching to this branch, open a post that has analysis results
- expands the readability and focus keyphrase panels (in Gutenberg, also in the sidebar)
- use HeadingsMap and observe the headings hierarchy jumps from h2 to h4
- switch to this branch, build the assets
- repeat the steps above and verify the headings hierarchy is now correct
Fixes #11362
> Fix the analysis results headings hierarchy

- js/src/decorator/gutenberg.js
* [not user-facing] Fixes a bug where the h1 content would also be marked in the text in the single h1 header assessment.
* Adds an additional `ASSESSMENT_SPECIFIC_ANNOTATION_ATTRIBUTES` object to the gutenberg decorator, to allow specific assessments to only be applied to certain blocks.
* Activate the recalibration beta under `SEO` > `General` > `Features`.
* Create a new post in Gutenberg.
* Add some content. [Lorem ipsum](https://nl.lipsum.com/feed/html)
* Add a second H1 header. This can be accomplished by adding a Heading block and setting it to a `H1` in the block settings in the sidebar.
* Name the header `Test`.
* In the content also add the word `Test` a couple of times.
* …
> Added specific annotation attributes for singleH1 assessment

- admin/class-yoast-form.php
- admin/config-ui/fields/class-field-choice.php
- admin/config-ui/fields/class-field-separator.php
- admin/views/tabs/metas/paper-content/general/title-separator.php
- inc/options/class-wpseo-option-titles.php
* Improve accessibility of the Title Separator setting.
This is a first pass at adding aria labels to the title separators UI. Just a POC for now, code needs to be optimized and polished. I'd greatly appreciate some feedback.
In the configuration wizard, all the separator symbols already have aria-labels to expand the symbols name to a human friendly wording. Instead, in the Search Appearance there are no aria-labels so screen readers won't announce correctly some of the characters or may even also not announce them at all, depending also on the verbosity setting of the screen reader.
Also, the `wpseo_separator_options` filter never worked in the configuration wizard so adding a new separator will show up in the Search Appearance …
> Add aria labels to the title separators UI in the Search Appearance

- webpack/webpack.config.js
This speeds up builds where the cache is loaded from around 2 minutes to 30s.
* _N/A_
* The default cache directory is fine for us:
> the loader will use the default cache directory in node_modules/.cache/babel-loader or fallback to the default OS temporary file directory if no node_modules folder could be found in any root directory.
* Build using `grunt webpack:buildDev`
* Build again using `grunt webpack:buildDev`. The build time should be MASSIVELY sped up.
* Change a JavaScript file to add a test `console.log`.
* Build again using `grunt webpack:buildDev`.
* The change should be present if you load your files in the browser. (Make sure the dev server is turned off, although it …
> Enable babel-loader cache in development

- frontend/class-woocommerce-shop-page.php
- tests/doubles/class-wpseo-woocommerce-shop-page-double.php
- tests/frontend/test-class-woocommerce-shop-page.php
- tests/frontend/test-class-wpseo-frontend-woocommerce-shop.php
* Adds method `is_woocommerce_active` and check is woocommerce activate before registering hooks.
* Adds static variables to "cache" results of functions [`is_shop`](https://docs.woocommerce.com/wc-apidocs/function-is_shop.html) and [`wc_get_page_id`](https://docs.woocommerce.com/wc-apidocs/function-wc_get_page_id.html).
* Adds method `is_woocommerce_active` which uses method `WPSEO_Utils::is_woocommerce_active` to check is woocommerce active. I've added new method because I want to overwrite it in "double" class to "simulate" that woocommerce is active.
* Addes "caching" for method is_shop_page to improve performance (prevents multiple calls of WC/WP API). Check if `$wp_query` exists to prevents too early "caching"  (and wrong …
> Little optimization for class WPSEO_WooCommerce_Shop_Page

- admin/class-admin-asset-manager.php
- webpack/webpack.config.js
After the upgrade to webpack 4 the assignment to the window was broken.
* _N/A_
- Don't have Gutenberg active.
- Click around in the plugin: dashboard, metabox, configuration wizard etc. 
- Don't see the following errors anywhere:
> Fix building of wp-* scripts

- inc/class-wpseo-admin-bar-menu.php
This is a partial fix for a similar issue to #10836 when using the WP Property plugin. The plugin creates the `$post` object as an instance of `stdClass` rather than `WP_Post`. Which is likely in itself a bad coding practice from the WP Property plugin. I wanted to share the code that got it working for me as a potential fix to the Timber issues as well.
* Verifies that variable `post` is an instance of `WP_Post` in `WPSEO_Admin_Bar_Menu ::get_singular_post()`. Props to [@yingles](https://github.com/yingles).
* `is_a` function http://php.net/manual/en/function.is-a.php
* Using the WP Property plugin navigate to the Property custom post type and see if the Admin Bar loads or gets a PHP Fatal Error
Fixes potentially #10836
> checking if post object is_a WP_Post in get_singular_post function

- frontend/class-frontend.php
* Uses method `is_simple_page` instead of `is_singular` in method robots. It's a little optimization and it covers all "simple" pages (not only shop page as now). Props to: [stodorovic](https://github.com/stodorovic)
* N/A This is a code-only change and should have no effect on the functionality.
Partially fixes: #9402.
> Uses method is_simple_page instead of is_singular in method robots

- inc/sitemaps/class-taxonomy-sitemap-provider.php
* _N/A_
See:
* https://github.com/WordPress-Coding-Standards/WordPress-Coding- Standards/releases/tag/1.1.0
* https://github.com/WordPress-Coding-Standards/WordPress-Coding- Standards/issues/1330
* either …
> CS: Move multi-line parameters out of function calls [7]

- admin/config-ui/components/class-component-configuration-choices.php
> CS: Move multi-line parameters out of function calls [6]

- admin/onpage/class-ryte-service.php
* _N/A_
See:
* https://github.com/WordPress-Coding-Standards/WordPress-Coding- Standards/releases/tag/1.1.0
* https://github.com/WordPress-Coding-Standards/WordPress-Coding- Standards/issues/1330
* either …
> CS: Move multi-line parameters out of function calls [5]

- admin/class-admin-asset-manager.php
* N/A
* Undo recalibration file for non-worker. See original implementation PR: https://github.com/Yoast/wordpress-seo/pull/11575/files#diff-9b8b9d5ca686b29d63b5d9a9b95db6a6
This is because there are no recalibration things used from this version. All of those exist in the web worker space.
* Build the plugin from this branch: `composer install && yarn && grunt build:css && grunt build:js`.
* If you are using the webpack development server you should then run `yarn start`, if not ignore this. But please ensure your `wp-config.php` setting for this matches.
* Verify that the analysis file is not downloaded from MyYoast anymore:
- Disable the recalibration beta: `SEO -> General -> …
> Undo special recalibration version for the non-worker analysis file

- package.json
* N/A
* `&&` doesn't work on Windows. However, no one from the team uses the dev server on Windows. 
* I added both webpack:buildProd as well as webpack:buildDev: minified because that is where the 404 were coming from, and unminified for easy debugging.
* Add `define( 'YOAST_SEO_DEV_SERVER', true );` to your wp-config.php.
* Install Gutenberg + the classic editor plugin.
* Make sure there are no built js files in js/dist
* On trunk: 
- `composer install && yarn install && grunt build:css && yarn start`
- Navigate to a post edit screen in either the classic editor plugin or the default classic editor, and see the following errors: 
* On this branch:
- `composer install && yarn …
> Add grunt webpack:buildProd && grunt webpack:buildDev to yarn start command

- js/src/redux/selectors/results.js
This branch is a rebase of PR#[11709](https://github.com/Yoast/wordpress-seo/pull/11709), which was based on trunk. 
* N/a
* Follow the steps in #11703 to reproduce the issue.
* Is should be solved.
Fixes #11703
> Prevent an error in Gutenberg when Readability marker is active

- admin/views/paper-collapsible.php
* Fixes a bug where the search appearance setting for a custom posttype named `profile` will have the wrong styling.
* I've chosen to prefix the id of the paper collapsible block
* Add the code from issue #11618 to have a custom post type named profile
* Go search appearance and open tab post types.
* See the styling of the profile will be wrong
* Checkout this branch and see it is solved.
Fixes #11618
> Prefix the collapsible paper block id

- admin/views/tabs/metas/paper-content/author-archive-settings.php
- js/src/wp-seo-admin.js
* Disables the `Show archives for authors without posts in search results?` toggle when the `Show author archives in search results?` toggle is disabled on the `Search Appearance` > `Archives` Page.
*
* Checkout this PR and build the project.
* Go to `SEO` > `Seach Appearance` > `Archives` > `Author archive settings`.
* Enable `Show author archives in search results?` and `Show archives for authors without posts in search results?`.
* Now disable `Show author archives in search results?`, and notice that the `Show archives for authors without posts in search results?` toggle is switched to `Off` and disabled.
* Save the options and notice teh changes are saved.
Fixes #9098
> Disable archives for authors without posts toggle when author archives are disabled

- inc/sitemaps/class-post-type-sitemap-provider.php
* Fixes a bug where private post types would have a sitemap with their 'private' entries.
*
* Register a private ( `'public' => false` )  post type with the name: entries
* View the sitemap_index.xml and see the post type not being visible
* View the `entries-sitemap.xml` and see you get a sitemap with the private entry you just added
* Refresh the `entries-sitemap.xml` and see you get a 404
* Done!
Fixes #
> Adds an post type accessible check

- admin/class-premium-upsell-admin-block.php
- js/src/components/contentAnalysis/RecalibrationBetaNotification.js
* [not-userfacing] Fixes nested links.
- nested links not only are invalid HTML... they do affect keyboard accessibility and the way links are reported by assistive technologies
- this PR fixes the "Recalibration beta" link and the upsell link in the block at the bottom of the settings pages
- activate the Recalibration beta feature
- build the assets
- check the Recalibration beta link in the metabox and in the Gutenberg sidebar
- verify there's just one link, no nested links
- verify there are no visual regressions
before:
after (slightly better aligned):
- go to any settings page
- at the bottom of the page, in the upsell block, check the upsell link "Get Yoast SEO Premium" 
- verify there's just one link, no nested links
- …
> Fix nested links

- admin/capabilities/class-capability-manager-integration.php
- admin/class-yoast-network-admin.php
- admin/class-yoast-notification-center.php
- admin/config-ui/fields/class-field-multiple-authors.php
- admin/config-ui/fields/class-field-success-message.php
- admin/filters/class-abstract-post-filter.php
- admin/google_search_console/class-gsc-table.php
- admin/google_search_console/class-gsc.php
- admin/google_search_console/views/gsc-display.php
- admin/metabox/class-metabox.php
- admin/onpage/class-onpage-request.php
- admin/taxonomy/class-taxonomy.php
- admin/views/js-templates-primary-term.php
- admin/views/tabs/metas/paper-content/breadcrumbs-content.php
- admin/views/tabs/metas/paper-content/general/knowledge-graph.php
- admin/views/tabs/metas/paper-content/media-content.php
- admin/views/tool-bulk-editor.php
- inc/class-wpseo-admin-bar-menu.php
- inc/class-wpseo-replace-vars.php
- inc/options/class-wpseo-taxonomy-meta.php
- inc/sitemaps/class-author-sitemap-provider.php
> CS: Move multi-line parameters out of function calls [3]

- admin/class-add-keyword-modal.php
- admin/class-admin-asset-manager.php
- admin/class-admin-asset-yoast-components-l10n.php
- admin/class-config.php
- admin/class-help-center.php
- admin/class-keyword-synonyms-modal.php
- admin/class-multiple-keywords-modal.php
- admin/config-ui/class-configuration-page.php
- admin/config-ui/class-configuration-service.php
- admin/formatter/class-metabox-formatter.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy.php
- inc/class-wpseo-utils.php
- tests/formatter/test-metabox-formatter.php
- tests/inc/test-language-utils.php
- tests/test-class-wpseo-utils.php
* Deprecates the methods `WPSEO_Utils::get_user_locale()` and `WPSEO_Utils:: get_language()`
* There is no visual change. Everything should still work without errors.
Please don't forget to check and merge these two pulls as well:
https://github.com/Yoast/wordpress-seo-premium/pull/2166
https://github.com/Yoast/wordpress-seo-local/pull/1312
Fixes #11058
> Deprecates language utils in WPSEO_Utils

- inc/sitemaps/class-post-type-sitemap-provider.php
- tests/doubles/class-wpseo-post-type-sitemap-provider-double.php
- tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
* Moves logic for page_on_front and page_for_posts outside "loop" in `class-post-type-sitemap-provider.php`.
* Improves method `get_first_links` for pages. If front page is set as static, then retrieves post for _page_on_front_ and put it on the begin of page sitemap. I've left same logic as before (home_url is added if _page_on_front_ isn't set).
* If _page_on_front_ is set then addes it in array `$posts_to_exclude` to avoid processing of front page in "loop". It's done after filter `wpseo_exclude_from_sitemap_by_post_ids` to prevent removing front page from page sitemap.
* If _page_for_posts_ is set then addes it in filter `wpseo_exclude_from_sitemap_by_post_ids` to remove it from page sitemap. …
> Improve logic for page_on_front and page_for_posts in sitemaps

- admin/class-yoast-dashboard-widget.php
- admin/onpage/class-onpage.php
- js/src/wp-seo-dashboard-widget.js
* Fixes a bug where we keep calling the Ryte endpoint even if the Ryte feature has been disabled.
*
* Disable the Ryte feature under Yoast -> Features
* Go to the dashboard
* In the network tab of the debugging tools a request to yoast/v1/ryte has been done.
* See the request not being done.
Fixes #11750
> Check if Ryte has been enabled before doing the request

- admin/class-meta-columns.php
- admin/formatter/class-term-metabox-formatter.php
* Renames the "Focus KW" column to "Keyphrase" on the content-type overview pages.
*
*
Fixes #11794
> Rename Focus KW to Keyphrase in Screen Options

- package.json
- webpack/webpack.config.js
* N/A
* Output unminified files that should be minified (backports and "no externals") with a `.min.js` extension when running `grunt build:js` and `yarn start`, because the backend will always request these files as minified files. This way we don't have to do a `webpack:buildProd` when starting the dev server.
* Do a `grunt clean` to remove all built assets.
* Run `grunt webpack:buildDev`. Notice that the backports, babel-polyfill and analysis worker files are output with a `.min.js` extension.
* Do a `grunt clean` again.
* Make sure you have the `YOAST_SEO_DEV_SERVER` flag enabled.
* Run `yarn start`.
* Notice it's faster to start up the dev server now.
Improves on #11695
> Only run a single js build on yarn start

- package.json
- yarn.lock
* n/a
* Bumps the version of YoastSEO.js to 1.44.0.
Check whether the following work:
* Fixes a bug where keyphrases weren't recognized in the URL when the words in the URL were separated by underscore characters instead of hyphens. https://github.com/Yoast/YoastSEO.js/pull/1979
* Fixes a bug that caused numbers to be stripped when marking a keyphrase containing a number, e.g. `Yoast SEO 9.3`. https://github.com/Yoast/YoastSEO.js/pull/2016
* Improves error handling in the analysis web worker by rejecting the last request instead of just throwing an error. https://github.com/Yoast/YoastSEO.js/pull/2035
> Bump YoastSEO.js to 1.44.0

- tests/test-class-wpseo-statistics.php
* _N/A_
Remove some code duplication by setting a repeated array up as a class property instead.
* _N/A_
> CS: Move static arrays to a class property [7]

- tests/notifications/test-class-yoast-notification-center.php
* _N/A_
Remove some code duplication by setting a repeated array up as a class property instead.
* _N/A_
> CS: Move static arrays to a class property [6]

- tests/inc/test-class-wpseo-admin-bar-menu.php
* _N/A_
Remove some code duplication by setting a repeated array up as a class property instead.
* _N/A_
> CS: Move static arrays to a class property [5]

- frontend/class-twitter.php
* _N/A_
As the "valid types" array doesn't change, there is no need to declare it in the function itself.
Declaring them in a class property improves the readability and maintainability of the code.
* _N/A_
> CS: Move static arrays to a class property [3]

- admin/taxonomy/class-taxonomy-social-fields.php
> CS: Move multi-line parameters out of function calls [11]

- tests/test-class-admin-asset-manager.php
> CS: Move multi-line parameters out of function calls [10]

- src/wordpress/integration-group.php
> CS: Move multi-line parameters out of function calls [13]

- admin/class-help-center.php
- admin/metabox/class-metabox.php
- admin/views/tabs/metas/paper-content/date-archives-settings.php
- inc/class-wpseo-replace-vars.php
- inc/options/class-wpseo-option-titles.php
- tests/config-ui/test-class-configuration-components.php
- tests/src/unit-tests/config/database-migration-test.php
- tests/src/unit-tests/config/plugin-test.php
- tests/src/unit-tests/formatters/indexable-post-formatter-test.php
- tests/test-class-wpseo-statistics.php
* _N/A_
* When an array only contains one item, it doesn't _need_ to be multi-line and if the array is within a function call, having it as single line prevents having to create a separate variable for it.
* Similarly, when an array doesn't contain associative keys, it also doesn't _need_ to be multi-line. In the case of single-use arrays within a function call within a control structure condition, reformatting the conditions to span multiple lines, while having the non-associative array as single-line, can improve readability and again prevent having to create a separate variable for the array.
* Lastly, function call arguments should be indented one tab from the line containing …
> CS: Miscellanous other function call related fixes

- inc/class-wpseo-admin-bar-menu.php
> CS: Move multi-line parameters out of function calls [12]

- src/yoast-model.php
> CS: Move multi-line parameters out of function calls [9]

- admin/config-ui/class-configuration-options-adapter.php
- admin/filters/class-cornerstone-filter.php
- admin/formatter/class-metabox-formatter.php
- admin/links/class-link-column-count.php
- admin/links/class-link-factory.php
- admin/links/class-link-reindex-dashboard.php
- admin/links/class-link-storage.php
- admin/menu/class-replacevar-editor.php
- admin/menu/class-replacevar-field.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
- admin/taxonomy/class-taxonomy.php
- admin/views/tool-file-editor.php
- admin/views/tool-import-export.php
- inc/class-upgrade.php
- inc/class-wpseo-meta.php
- inc/structured-data-blocks/class-faq-block.php
- inc/structured-data-blocks/class-how-to-block.php
- migrations/20171228151840_WpYoastIndexable.php
- tests/admin/import/test-class-import-premium-seo-pack.php
- tests/admin/import/test-class-import-squirrly.php
- tests/config-ui/test-class-configuration-options-adapter.php
- tests/config-ui/test-class-configuration-service.php
- tests/frontend/test-class-wpseo-opengraph-image.php
- tests/notifications/test-class-yoast-notification-center.php
- tests/sitemaps/test-class-wpseo-sitemap-image-parser.php
- tests/src/unit-tests/config/database-migration-test.php
- wp-seo-main.php
* _N/A_
See:
This commit addresses multi-line function calls where parameters did not each start  on a new line.
* _N/A_
> CS: Each parameter should start on a new line in multi-line function calls [2]

- tests/admin/test-class-admin-asset-dev-server-location.php
* _N/A_
Remove some code duplication by setting a repeated array up as a class property instead.
* _N/A_
> CS: Move static arrays to a class property [4]

- tests/admin/help_center/test-class-help-center-template-variables-tab.php
- tests/admin/test-class-admin-asset-seo-location.php
- tests/admin/test-class-yoast-network-settings-api.php
- tests/admin/watchers/test-class-slug-change-watcher.php
- tests/frontend/test-class-opengraph.php
- tests/frontend/test-class-twitter.php
- tests/inc/options/test-class-wpseo-options-backfill.php
- tests/sitemaps/test-class-wpseo-sitemaps-cache.php
- tests/sitemaps/test-class-wpseo-sitemaps.php
- tests/src/unit-tests/config/plugin-test.php
- tests/test-class-admin-asset-manager.php
- tests/test-class-admin-asset.php
- tests/test-class-wpseo-json-ld.php
* _N/A_
See:
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/ 1330
* either …
> CS: Move multi-line parameters out of function calls [8]

- admin/class-admin-init.php
* Yoast CS: Adds isset() check on superglobal. 
* Fixes the following errors: 
```
FILE: admin\class-admin-init.php
--
--------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------
101 \| ERROR \| Detected usage of a non-validated input variable: $_SERVER
101 \| ERROR \| Missing wp_unslash() before sanitization.
101 \| ERROR \| Detected usage of a non-validated input variable: $_SERVER
101 \| ERROR \| Missing wp_unslash() before sanitization.
--------------------------------------------------------------------------
```
* This PR should not change anything nor …
> Yoast CS: Adds isset() check on superglobal. 

- inc/sitemaps/class-sitemaps-router.php
* N/A - Fixes the input issues in inc/sitemaps/class-sitemaps-router.php
* Fixes the following issues:
```
FILE: inc\sitemaps\class-sitemaps-router.php
--
-------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 3 LINES
-------------------------------------------------------------------------
83 \| ERROR \| Detected usage of a non-validated input variable: $_SERVER
83 \| ERROR \| Missing wp_unslash() before sanitization.
84 \| ERROR \| Detected usage of a non-validated input variable: $_SERVER
84 \| ERROR \| Missing wp_unslash() before sanitization.
89 \| ERROR \| Missing wp_unslash() before sanitization.
-------------------------------------------------------------------------
```
This …
> Yoast CS: Add sanitization for inc\sitemaps\class-sitemaps-router.php

- admin/config-ui/fields/class-field-company-or-person.php
- admin/config-ui/fields/class-field-environment.php
- admin/config-ui/fields/class-field-google-search-console-intro.php
- admin/config-ui/fields/class-field-multiple-authors.php
- admin/config-ui/fields/class-field-post-type-visibility.php
- admin/config-ui/fields/class-field-social-profiles-intro.php
- admin/config-ui/fields/class-field-title-intro.php
* _N/A_
This is a bit of an awkward one as it is unclear to me whether these phrases had line-breaks in them on purpose or accidentally.
If on purpose: the phrases were now often broken up mid-way in a sentence.
For translators, line-breaks in translatable strings -especially when at semi-random places - are difficult to work with as words have different lengths in different languages, let alone in different writing systems.
If there was a purpose to the line-breaks, it would be great to know the reason and we can figure what would be a better solution (if any).
* _N/A_
This is a code-only change and should have no effect on the …
> CS/I18n: Remove line breaks from translatable strings

- admin/class-bulk-editor-list-table.php
* N/A - Fixes the input issues in file class-bulk-editor-list-table.php
* Should fixes a lot of the following issues:
```
FILE: admin\class-bulk-editor-list-table.php
--
FOUND 15 ERRORS AND 12 WARNINGS AFFECTING 9 LINES
110 \| ERROR   \| Detected usage of a non-validated input variable: $_SERVER
\|         \| (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)
110 \| ERROR   \| Missing wp_unslash() before sanitization.
\|         \| (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
110 \| ERROR   \| Detected …
```
> Yoast CS: Do sanitization and nonce verification in class-bulk-editor-list-table.php

- tests/admin/test-class-yoast-network-admin.php
- tests/src/unit-tests/exceptions/no-indexable-found-test.php
* _N/A_
* Code style compliance. Adds missing `@throws` tags for functions which throw exceptions.
N.B.: The exception names used in the `@throws` tags for `tests/src/unit-tests/exceptions/no-indexable-found-test.php` presume that PR #11852 will be merged (soon).
* _N/A_
> Documentation: add missing @throws tags

- webpack/webpack.config.js
* [not-user-facing] Fixes an issue where the development build did not work for `wp-seo-analysis-worker`.
* Change the output filename of the analysis worker in webpack.
* Separate webpack configs for the no-externals and analysis worker. Due to babel polyfill always being required as minified (and that's correct).
* Switch to this branch.
* Run `yarn install`
* Note: disable the dev server flag.
* Run `composer install`
* Run `grunt build`.
* Verify the file exists: `js/dist/wp-seo-analysis-worker-94-beta1.js`.
* Verify the metabox works as expected (no 404 errors).
* Run `composer install --no-dev`
* Run `grunt release`.
* Verify the file exists: …
> Fix possible unminified build for the analysis worker

- inc/class-wpseo-utils.php
* N/A - Adds sanitization and use unslash for `inc\class-wpseo-utils.php`
* Fixes the following issues:
```
FILE: inc\class-wpseo-utils.php
--
FOUND 4 ERRORS AFFECTING 2 LINES
91 \| ERROR \| Missing wp_unslash() before sanitization.
\|       \| (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
91 \| ERROR \| Detected usage of a non-sanitized input variable: $_SERVER
\|       \| (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
108 \| ERROR \| Missing wp_unslash() before sanitization.
\|       \| …
```
> Yoast CS: Resolve unslash and sanitization issues

- admin/ajax.php
* N/A - Fixes the input issues in ajax.php
* Should fix these issues:
```
FILE: admin\ajax.php
--
------------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------
257 \| ERROR \| Detected usage of a non-validated input variable: $_POST
257 \| ERROR \| Missing wp_unslash() before sanitization.
257 \| ERROR \| Detected usage of a non-sanitized input variable: $_POST
258 \| ERROR \| Detected usage of a non-validated input variable: $_POST
258 \| ERROR \| Missing wp_unslash() before sanitization.
258 \| ERROR \| Detected usage of a non-sanitized input variable: $_POST …
```
> Yoast CS: Fixes the input issues in ajax.php

- composer.json
* _Improved compatibility with Windows for developers_ (if this should be mentioned at all)
1. While the PHPCS related scripts already worked on Windows, the "prefix" related scripts did not.
For a call to those to work on Windows, a path to a `bin` script like `./vendor/bin/php-scoper` should be changed to `\"vendor/bin/php-scoper\"`.
2. Next, we run into another problem, which is that the system default PHP version will be used instead of the PHP version which is set for Composer.
Note: As far as I know, this issue is platform independent.
To explain: A dev may have several PHP versions installed on their system and can point Composer to use a certain version. If so, when running `composer install` et al, that PHP version will …
> Composer: improve compatibility with Windows OS

- admin/class-expose-shortlinks.php
- js/src/components/contentAnalysis/SeoAnalysis.js
* [not user facing] Adds Shortlinker data to the upsell buttons in the metabox and sidebar under the "Focus keyphrase"
* Used the Shortlink Exposer
*
Fixes #11887
> Add missing tracking data to shortlink

- admin/endpoints/class-endpoint-file-size.php
- inc/options/class-wpseo-option.php
- src/config/database-migration.php
- tests/admin/links/test-class-link-type-classifier.php
- tests/admin/services/test-class-indexable-post-provider.php
- tests/admin/test-class-admin-recommended-replace-vars.php
- tests/admin/test-class-database-proxy.php
- tests/admin/watchers/test-class-slug-change-watcher.php
- tests/config-ui/components/test-class-component-connect-gsc.php
- tests/doubles/wpseo-config-component-connect-google-search-console-mock.php
- tests/doubles/wpseo-role-manager-mock.php
- tests/framework/class-wpseo-unit-test-case-frontend.php
- tests/frontend/test-class-front-end-page-type.php
- tests/frontend/test-class-opengraph.php
- tests/inc/test-class-wpseo-admin-bar-menu.php
- tests/notifications/test-class-yoast-notification-center.php
- tests/notifications/test-class-yoast-notification.php
- tests/recalculate/test-class-recalculate-scores-ajax.php
- tests/test-class-primary-term-admin.php
* _N/A_
More of the same as #11876, but now mostly for the `tests` directory.
* _N/A_
> Documentation: use full docblocks for properties

- src/yoast-orm-wrapper.php
* _N/A_
Rename ORMWrapper::_create_model_instance() method to get rid of the underscore prefix.
While the class extends an external dependency, this method does not overload a method from the parent class, so can be safely renamed.
Includes adjusting all calls to the method.
* Check if the Travis build still passes.
> Rename ORMWrapper::_create_model_instance() method

- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
- admin/views/licenses.php
* [not user facing] Replaces duplicate usage of `pe-premium-page` shortlink with unique ones that better describe the context they are used in.
* Converted the Premium extension configuration to use the `buyUrl` and `infoUrl` formats introduced recently.
Taxonomy
* Go to the Taxonomy metabox
* Use the `Go premium` link on the top-right
* Hover the `More info` link
* Make sure the shortlink does not use `pe-premium-page`
Content type
* Go to the Post metabox
* Hover or Click the `Go premium` link on the top-right
* Make sure the shortlink does not use `pe-premium-page`
Licenses/Premium
* Go to the "Premium" menu item under "SEO"
* Hover or Click on the Premium "buy" or "info" links …
> Make Go Premium links more unique

- frontend/class-remove-reply-to-com.php
* N/A
* Fixes the following issues:
```
FILE: frontend\class-remove-reply-to-com.php
--
FOUND 3 ERRORS AND 1 WARNING AFFECTING 3 LINES
51 \| ERROR   \| Missing wp_unslash() before sanitization.
\|         \| (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
52 \| ERROR   \| Detected usage of a non-validated input variable: $_SERVER
\|         \| (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)
52 \| ERROR   \| Missing wp_unslash() before sanitization.
\|         \| …
```
> Yoast CS: Adds sanitization in file class-remove-reply-to-com.php

- admin/metabox/class-metabox.php
* [not user facing] Fixes a problem introduced in trunk where the input was sanitized too aggressively on multi-select input (advanced robots settings)
* Convert no input for multiselect to empty array
* Added array map for input data instead of plain `sanitize_text_field` which will convert any array to an empty string.
* Open a post/page and set advanced robots to a certain value
* Save the settings
* (Reload the page when using Gutenberg)
* See the settings being saved
Fixes https://github.com/Yoast/wordpress-seo/issues/11917
> Don't sanitize text field for array

- admin/pages/courses.php
* Fixes the WordPress admin menu and footer in the Courses page
Currently, the Courses page uses the `Yoast_Form` method `admin_header()` but omits to use `admin_footer()`. This breaks the admin layout and menu because of malformed HTML.
However, the Courses page is a special page that needs to display only the courses cards. Using `admin_footer()` would require to remove a few action hooks, including the one used to print out the "promo block" at the bottom of the page.
I'd propose to avoid this overhead altogether, as there's no need to use `Yoast_Form` in the first place:
- we don't need the form: there's nothing to submit
- we don't need the CSS table layout that is normally used in the admin pages (primarily meant for the …
> Fix the Courses page layout.

- admin/google_search_console/class-gsc-table.php
* Improves the Google Search Console table accessibility by removing a doubled button.
- In WP 4.3 some changes were introduced to make the tables responsive, introducing new methods in the table Class
- this PR just overrides one of the methods introduced in WP 4.3 which, in combination with our custom implementation, printed out a double button to expand a table row
- go in the GSC table page, authenticate to see the table filled with rows
- on trunk:
- in the responsive view, check there are actually 2 buttons to expand a row: they're perfectly overlapped so check the markup
- check there's now just one button
Fixes #5958
> GSC table: Avoid to print out the same button twice

- frontend/class-json-ld.php
* Removes all JSON output from 404 pages.
* Go look at a 404. See JSON is gone.
> Don't run our JSON code on 404 pages

- tests/test-class-wpseo-metabox.php
* _N/A_
This comment is a left-over from before the `WPSEO_Admin_Asset_Manager::PREFIX` prefix was used and the prefix was set from within the test method. (checked via file history trace)
* _N/A_
> Documentation: remove outdated comment

- admin/class-admin-asset-manager.php
As these files are shipped with the plugin, we need to cache-bust them with the version of the plugin. False will use the current WordPress version, which refrains us from keeping them up to date.
Fixes the following CS errors:
```
FILE: admin\class-admin-asset-manager.php
FOUND 13 ERRORS AND 1 WARNING AFFECTING 13 LINES
191 | ERROR   | Version parameter is not explicitly set or has been set to an equivalent of
|         | "false" for wp_register_script; This means that the WordPress core version will be
|         | used which is not recommended for plugin or theme development.
|         | …
```
> Add WPSEO_VERSION as version to WordPress_register_script

- admin/google_search_console/class-gsc-table.php
* _N/A_
Properties should not be prefixed with an `_` to indicate visibility. This is an outdated PHP4-style habit.
In this case, the property name can not be changed as the property comes from the WP native `WP_List_Table` class which this class extends, but as the property is declared in the parent class and the property declaration in this child class does not overwrite a default value or change the visibility of the property, there is no need to declare it in the child class in the first place, so we may as well remove it.
* _N/A_
> CS: remove an unnecessary property declaration

- admin/class-export.php
- admin/class-extension-manager.php
* _N/A_
* The next version of YoastCS will detect and start complaining about whitespace between incrementor/decrementor operators and the variable they apply to.
* The next version of WPCS (2.0.0) will start complaining about the order in which scope keywords for properties are set. The expected order is `visibility [static] $property`.
* _N/A_
> CS: Fix newly detected issues

- .travis.yml
- composer.json
- phpcs.xml.dist
* _N/A_
A bit hacki-di-hacky, but it works.
This adds a separate Composer script to allow both devs, as well as Travis, to test code in the Premium repo against YoastCS 1.2.1, even though the Free plugin is not ready to upgrade yet.
To still allows devs to easily switch between testing the Free repo against the old requirements and the Premium repo against the new ones, the update to YoastCS 1.2.1 for the Premium CS check is reverted after the CS checks have run.
Also takes note of the fact that `premium-check-cs` script contains **2** PHPCS runs.
The PHPCompatibility `testVersion` can not be set per directory (inherent to how config settings work in PHPCS), however the `testVersion` as set in a ruleset, can - since PHPCS 3.3.0 - …
> Travis/Composer: update YoastCS to 1.2.1 for the Premium plugin only

- grunt/config/copy.js
* Prevents `vendor_prefix/j4mie/idiorm/demo.php` from being released.
*
* Do grunt artifact and check if the file exists in the artifact folder.
Fixes #11962
> Add exclusion entry

- admin/class-expose-shortlinks.php
- admin/metabox/class-metabox.php
- admin/taxonomy/class-taxonomy-metabox.php
- js/src/redux/reducers/preferences.js
- js/src/wp-seo-metabox.js
* N/A
*
* Do the yarn and grunt magic
* Edit or add a term (e.g. a category)
* See there is an additional `add related keyphrase` item in the metabox. It should shown an upsell.
* Verify that other upsells are shown as well: morphology, add synonyms, add related keyphrase
* Make sure the links in the upsells have term in the url and are different compared to the ones for a post.
* Makes sure `Go Premium` at the top of the metabox refers to an external page.
Fixes #11293
Fixes #11898
> Add upsells to terms

- js/src/helpers/isGutenbergDataAvailable.js
* Fixes a bug where errors are given on classic editor when Gutenberg assets are enqueued.
*
* Install the `Classic editor` and the `Advanced Rich Text Tools for Gutenberg`
* Add or Edit a post in Classic Editor mode
* Check if there are any console errors
* Follow the steps before and verify the errors are gone.
Fixes #11919
> Add check to make sure edit-post is loaded

- frontend/class-frontend.php
- inc/class-rewrite.php
- inc/sitemaps/class-sitemaps-router.php
* Moves the `x-redirect-by` header below each `wp_redirect`/`wp_save_redirect` function call. This prevents the header from being overwritten by WordPress 5.1
*
* Open Chrome in incognito mode (or a similar feature in your preferred browser).
* Open the Network tab in the devtools, and make sure `Preserve log` action is checked.
* In the browser navigate to `http://local.wordpress.test/sitemap.xml`.
* Make sure you are redirected to `http://local.wordpress.test/sitemap_index.xml`.
* In the devtools, look for the request with the name `sitemap.xml` and status `301`.
* Inspect the `Request Headers` of this request and make sure it has the `X-Redirect-By: Yoast SEO` header.
Fixes …
> Move the x-redirect-header below the redirect method

- frontend/class-twitter.php
* Fixes a bug where the empty twitter description is shown instead of the term description itself.
* To reproduce follow the steps in #11701 
* This pull should fix that
Fixes #11701
> Use AND instead of OR

- inc/options/class-wpseo-option-social.php
- tests/doubles/class-wpseo-option-social-double.php
- tests/inc/options/test-class-wpseo-option-social.php
Also added some unit tests
* Fixes a bug where undefined warnings are given for two recently added social options.
*
* _This issue might be hard to test, because of error reporting. Therefore I've also added unit tests._
* Have error reporting enabled
* Remove the `wpseo_option` option (`wp_options`) from the database. Or set its value to: 
```
a:20:{s:13:"facebook_site";s:12:"http://sdddd";s:13:"instagram_url";s:0:"";s:12:"linkedin_url";s:0:"";s:11:"myspace_url";s:0:"";s:16:"og_default_image";s:0:"";s:18:"og_frontpage_title";s:0:"";s:17:"og_frontpage_desc";s:0:"";s:18:"og_frontpage_image";s:0:"";s:0:"";s:9:"opengraph";b:1;s:13:"pinterest_url";s:0:"";s:15:"pinterestverify";s:0:"";s:1 …
```
> Check if value exists in dirty

- js/src/components/ConnectGoogleSearchConsole.js
* Adds a missing label element for a field input in the Configuration Wizard
Very small patch to:
- remove the placeholder text
- remove an `aria-labelledby` attribute that points to nothing
- add a visible `<label>` element
Before:
After:
Note: the visible label is standard for all the input fields in the Wizard, for example:
- build the assets
- go in the WIzard > step 8
- if already authenticated, click "Reauthenticate with Google:
- the auth code input field appears
- verify the new label is properly associated (click on it)
Fixes #11045
> Add missing label element in the Configuration Wizard

- inc/class-wpseo-content-images.php
- wp-seo-main.php
* Removes an unnecessary instantiation of `WPSEO_Content_Images`
* This class has an empty `register_hooks` method. This method contained logic to remove cache, but that has been removed in 7.7. Decided to deprecate the method and remove that instantiation of the class.
* Make sure everything still works. There is no visible change.
Fixes #11319
> Register hooks isn't doing anything, remove it

- js/src/wp-seo-replacevar-plugin.js
Fixes error when wp.api.models.Page is called to get Parent page.
Issue reported on https://github.com/Yoast/wordpress-seo/issues/11767
* Fixes error when wp.api.models.Page is called before the function was ready.
* Likely occurs in particular connection speeds.
* When it occurs can be produced consistently on all browsers when editing Child page to a New tab
* Error is not present on refresh.
* Using wp.api.loadPromise.done to ensure the wp.api.models.Page is only called when it is ready.
* Create a new page enter a title and publish ( Page A )
* Create another page ( Page B ) and choose Page A as a parent page from page attributes. Publish the page.
* Goto page-list screen in …
> call wp.api.models.Page when ready

- frontend/class-breadcrumbs.php
* Fixes a bug where the blog page will be shown on non singular posts.
* Did some refactoring to make the method more readable.
* Sets a page as the post page ( this will be the 'blog page' )
* Go to the Yoast SEO - Search Appearance -> Breadcumbs and enable the 'show blog page' toggle
* Go to a post and see the blog page as a breadcrumbs
* Go to the category and see the blog page still being visible as breadcrumb
* Go to a empty category and the blog page will be hidden
* Checkout this branch and see the previous the previous 2 being solved.
Fixes #10949
> Add check to verify if current page is a singular post

- admin/links/class-link-columns.php
- admin/metabox/class-metabox.php
- js/src/wp-seo-edit-page.js
- tests/admin/links/test-class-link-columns.php
* Improves the Internal links table headers text for better translations and accessibility.
- changes the table headers text from `# links to this post` / `# internal links to` to batter translatable `Internal links` and `Received internal links` as asked in #7655
- makes the tooltips only a visual aid: screen reader users will perceive the visually hidden text, which is simpler and shorter, instead of the whole tooltip text. this addresses #7385 
- removes some no longer used JS
- moves the enqueueing of the related CSS and JS above a conditional check that was preventing the tooltip to work correctly in the Pages screen. See #11829
- in the Posts and Pages screens, check:
- the tooltips on the internal links icons still work …
> Improve internal links table headers strings and accessibility.

- js/src/courses-overview.js
* [not user-facing] Fixes a bug where course bundles on the course page would have a button with an empty href.
* @diedexx added an isBundle boolean to the feed.
* Link yoast-components `dont-show-empty-read-more-button` branch to this branch.
* Go to the courses page.
* Check *all* buttons and links.
- For bundles: 
- For single courses:
Fixes #12030
> Add isBundle prop to courses overview

- package.json
- yarn.lock
* n/a
* Changes yoast-components dependency from release branch to `develop` to make sure we get no conflicts when merging changes introduced in both `wordpress-seo` and `yoast-components`.
*
> Change yoast-components dependency to develop

- frontend/class-handle-404.php
Co-authored-by: stodorovic
* Uses filter [old_slug_redirect_url](https://developer.wordpress.org/reference/hooks/old_slug_redirect_url/) to prevent redirects for feeds if post slug is changed. Props to [stodorovic](https://github.com/stodorovic).
* Create post with slug "test_post".
* Check feed /test_post/feed/ - it shows correct feed.
* Go to change post slug to "test_post1".
* Browse to old feed /test_post/feed/ - it should show 404 error.
Fixes #12041
> Prevents redirect for old post feeds

- frontend/class-breadcrumbs.php
* Replaces the quotes in search breadcrumb for smart quotes.
*
* Have breadcrumbs in your theme (https://kb.yoast.com/kb/implement-wordpress-seo-breadcrumbs)
* To get the breadcrumbs in the search results, specifically put the code in `header.php` or `search.php`
* Search in your blog
* See the smart quotes around the search term in the breadcrumbs.
Fixes #11754
> Use smart quotes

- admin/class-plugin-availability.php
- admin/config-ui/fields/class-field-multiple-authors.php
- admin/config-ui/fields/class-field-site-name.php
* _N/A_
`{string}` is not a recognized, nor an accepted parameter type annotation in PHP.
The corrected information is based on the code found within the affected functions.
* _N/A_
> Documentation: fix incorrect info in method @param tags

- frontend/class-breadcrumbs.php
* _N/A_
These functions were documented with the hook documentation for the hook called within the function.
The hook documentation has now been placed with the hook call and a proper function docblock has been added for both functions.
* _N/A_
> Documentation: fix mixed up hook/function documentation

- admin/metabox/class-metabox.php
* N/A - Bring back the extension of `WPSEO_Meta`
* In #11978 we uncoupled the `WPSEO_Meta` entirely. This might break older versions of our extensions. We decided to bring back the extension of `WPSEO_Meta` to have backwards compatibility. In a future release we can remove the `extends` safely because the extensions will be more up-to-date for most sites.
* Check if the metabox doesn't break with old versions of extensions, for example Video SEO 9.4.
> Extends the WPSEO_Meta class

- admin/metabox/class-metabox.php
* [not userfacing] Improve link to googlewebmastercentral in the meta box advanced tab
- adds rel=noopener
- changes http to https
- adds visually hidden message "Opens in a new browser tab"
- go in the meta box > Advanced tab
- check the link "Cross domain canonical" is now `https`
- as this link uses `target="_blank"` and doesn't point to yoast.com, it needs a `rel="noopener"` attribute and a visually hidden message "Opens in a new browser tab", check it has those
Fixes #12018
> Improve link to googlewebmastercentral.

- js/src/wp-seo-post-scraper.js
- js/src/wp-seo-shortcode-plugin.js
* [not-user-facing] Changes YoastShortcodePlugin to not use app directly.
* Pass the functions used instead of the app.
* Enable worker logs in `/VVV/www/wordpress-default/public_html/wp-config.php` enable the flags `define( 'YOAST_SEO_DEBUG', true );` and `define( 'YOAST_SEO_DEBUG_ANALYSIS_WORKER', 'TRACE' );`.
* Go to a post.
* Open the console and look at the currently supported shortcodes by running:  `wpseoShortcodePluginL10n.wpseo_shortcode_tags`.
* Test if a shortcode does not end up in the text that the analysis receives:
* Add a shortcode that is not supported.
* Ensure the paper text does not include the tags of those, but it does include the content in between the tags.
* …
> Refactor YoastShortcodePlugin to not use app directly

- inc/class-wpseo-replace-vars.php
* Adds `$taxonomy` to the arguments passed to the `wpseo_terms` filter. Props to [polevaultweb](https://github.com/polevaultweb)
* Adds a filter:
```
add_filter( 'wpseo_terms', function( $output , $taxonomy ) {
var_dump( $taxonomy); 
return $output;
}, 10, 2 );
```
* On `trunk` the second argument isn't passed, so it should give a php warning/error
* On this branch it will print the taxonomy value. 
Fixes #12118
> Add $taxonomy to the arguments passed to the `wpseo_terms` filter.

- src/models/seo-meta.php
- src/yoast-model.php
* _N/A_
Properties should not be prefixed with an `_` (to indicate visibility or for whatever other reason). This is an outdated PHP4-style habit.
Renaming the property and instances of it in child classes fixes this.
As the `Yoast_Model` class is set up as a parent class, this should be considered a BC-break.
* _N/A_
> CS: don't use underscore prefixed property names [1]

- src/yoast-orm-wrapper.php
* _N/A_
Properties should not be prefixed with an `_` (to indicate visibility or for whatever other reason). This is an outdated PHP4-style habit.
Renaming the property and instances of it in child classes fixes this.
While the `ORMWrapper` class extends the `ORM` class, the naming of this property does not appear to be dictated by the parent class, so it should be safe to rename it.
**Note**: This should be considered a BC-break.
* Good question.... ask @atimmer
> CS: don't use underscore prefixed property names [3]

- src/yoast-model.php
* _N/A_
Properties should not be prefixed with an `_` (to indicate visibility or for whatever other reason). This is an outdated PHP4-style habit.
Renaming the property and instances of it in child classes fixes this.
As the `Yoast_Model` class is set up as a parent class, this should be considered a BC-break.
Note: this PRs renames the `$_table` property as well as the (undeclared) `$_table_use_short_name` property.
* _N/A_
> CS: don't use underscore prefixed property names [2]

- .travis.yml
- phpunit.xml
* [not-user-facing] Optimizing the Travis builds to reduce the work that needs to be done before the checks pass
**PHPUnit `/src/tests` PHP version requirements**
Instead of requiring PHP 5.3 we up the minimum required version for the tests to 5.6
This allows us to have one modern test suite next to the legacy test suite. Instead of having one for 5.2, 5.3 and 5.6+
This is also needed for preparation of the WordPress test mocking framework.
**Explicitly set PHPUNIT execution**
Instead of assuming that PHPUnit must be run when Coverage is not being run.
This will speed up the build because the 7.3 linting/phpcs build doesn't also have to run all the tests.
**Remove unwanted builds**
* Removing PHP 5.3 build
* Removing PHP 7.0 …
> Prepare for PHP 5.2-5.5 drop

- inc/class-wpseo-replace-vars.php
* Fixes a problem where the `focus keyphrase` replacement variable was not correctly applied on a term page.
* Added early returns instead of setting the variable
* Create a category item or a tag (term).
* Make sure in search appearance the default seo title is set as described in the issue. 
* Save the term and view the page
* Make sure the replacement has been applied on the expected location
Fixes #8225
> Add condition to retrieve focuskw for term

- package.json
- yarn.lock
* Bumped `yoastseo` to 1.47
* Bumped `yoast-components` to 4.20
*
*
Fixes #
> Bumped yoastseo and yoast-components for 9.6 release

- src/config/dependency-management.php
- src/loaders/oauth.php
The dependency management class needs to be initialized to make sure class aliases are created for the non-namespaced dependencies when the plugin is installed via composer or with the `no-dev` flag.
* [non-user-facing] Fixes the automated testing failures. This will make sure the class-aliases are loaded.
* Makes sure the dependency manager is loaded
* This will be loaded twice in the current architecture, I'm working on a change in setup to better deal with this
* Remove *all the folders* inside the `vendor_prefixed` directory
* Remove the`vendor_prefixed/dependencies-prefixed.txt` file
* Run `composer install --no-dev`
* Have Query Monitor enabled 
* Visit any page where we are …
> Ensure dependency management

- js/src/helpers/taxonomy-replacevars.js
- js/src/wp-seo-replacevar-plugin.js
* Fixes a bug where taxonomy terms weren't shown correctly in the Snippet Preview, for example when using the `Categories`, `Tags` or any custom taxonomy replacement variable.
* This implementation fixes the `Category`, `Tag` and all custom taxonomy replacement variables.
* I have not written unit tests since the code relies heavily on wordpress' data api.
* Give it a title and save it.
* Add the `Category` replacement variable in the snippet editor.
* Add one or more categories and make sure the title is properly updated.
* Do the same thing for tags and one or more custom taxonomies.
Fixes #8555
> Fix replacevars in Snippet Editor for taxonomies.

- inc/endpoints/class-myyoast-connect.php
- tests/inc/endpoints/test-class-myyoast-connect.php
- wp-seo-main.php
* N/A - Adds an endpoint for connecting with MyYoast
*
* You can believe the unit tests, if these pass it is okay. But if you want to do a complicated test, please follow these steps:
* Have #12131 merged in trunk and trunk in this branch.
* Save a client id by adding the following code (somewhere in the WordPress runtime (wp-seo-main.php for example:
```php
add_action( 'init', function() { 
$client = new WPSEO_MyYoast_Client();
$client->save_configuration( array( 'clientId' => 'the-client-id' ) ); 
} );
```
* Fire a `POST` request to {your-test-domain}/wp-json/yoast/v1/myyoast/connect with the following arguments in the body: url = {your-test-domain}, clientId = 'the-client-id' and …
> Adds the myyoast connect endpoint

- admin/metabox/class-metabox.php
- js/src/helpers/taxonomy-replacevars.js
- js/src/wp-seo-replacevar-plugin.js
* [not-userfacing] Fixes error when editing page.
*
* Create a new page or open an existing page.
* Make sure no console errors occur.
* Add a taxonomy to your page post type, you can install the following plugin for that.
[register-category-for-pages.php.zip](https://github.com/Yoast/wordpress-seo/files/2884056/register-category-for-pages.php.zip)
* Make sure no console errors occur.
* Also check if posts still work.
Fixes #
> Fix replacevar plugin error in trunk

- admin/class-my-yoast-route.php
- inc/class-addon-manager.php
- tests/admin/test-class-my-yoast-route.php
- tests/doubles/class-admin-addon-manager-double.php
- tests/inc/test-class-addon-manager.php
Also added unittests.
* N/A - Filled the extensions value, because we have the WPSEO_Addon manager now
* I was using `array_filter` in combination with the `ARRAY_FILTER_USE_KEY` constant. Unfortunately this constant is **too modern** for  WordPress. This is because it has been introduced in PHP 5.5. 
* Decided to make a private method with a similar routine. 
* Added  a `@coveCoverageIgnore` 
* This method can be replaced with a array_filter + constant implementation when WordPress has minimal 5.6 support.
* N/A Functionality is covered in unit tests and we will connect everything together later on.
Fixes #12250
> Fills the extensions value in the redirect.

- admin/capabilities/class-abstract-capability-manager.php
- admin/capabilities/class-capability-manager-integration.php
- admin/class-admin-user-profile.php
- admin/class-meta-columns.php
- admin/class-option-tabs.php
- admin/class-plugin-compatibility.php
- admin/class-social-admin.php
- admin/class-suggested-plugins.php
- admin/class-yoast-form.php
- admin/class-yoast-notification-center.php
- admin/class-yoast-plugin-conflict.php
- admin/metabox/class-metabox-section-react.php
- admin/metabox/class-metabox-tab-section.php
- admin/metabox/class-metabox.php
- admin/services/class-indexable-post-provider.php
- admin/services/class-indexable-term-provider.php
- admin/services/interface-indexable-provider.php
- admin/statistics/class-statistics-service.php
- admin/taxonomy/class-taxonomy-columns.php
- admin/taxonomy/class-taxonomy-fields-presenter.php
- admin/taxonomy/class-taxonomy-fields.php
- admin/taxonomy/class-taxonomy-social-fields.php
- admin/views/class-yoast-feature-toggles.php
- frontend/class-breadcrumbs.php
- frontend/class-twitter.php
* _N/A_
The contents of parameter tags should be aligned like so:
```php
* @param[1 space]int [1 space after longest entry]$var     [1 space after longest entry]Description.
* @param[1 space]bool[1 space after longest entry]$variable[1 space after longest entry]Description.
```
* _N/A_
> Documentation: improve method docblock @param tag formatting

- js/src/wp-seo-replacevar-plugin.js
* Fixes a bug where selecting a parent page for a page would lead to console errors and a not-working 'parent page' snippet variable.
* Anonymous functions (`function()`) have an own context, while arrow functions refer to the context they are defined in (the 'parent' context).
* See issue.
Fixes #12267
> Replace function() by arrow function to make 'this' have the correct reference

- webpack/webpack.config.js
* Since the VVV default configuration has been updated (see [here](https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1650)), the local WordPress installations have been renamed `wordpress-one` and `wordpress-two` rather than `wordpress-local`.
* This PR adds these two installs to the default allowed hosts in the webpack config.
* Start `one.wordpress.test` in your browser (you have to have the local VVV installation called `wordpress-one`).
* In the browser console, find the error message `ERR_CONNECTION_REFUSED`.
* After building and running `yarn start`, the error message should have disappeared.
* The same steps apply to `two.wordpress.test`.
> Additional default allowed hosts in webpack.config.js

- tests/admin/test-class-yoast-network-admin.php
- tests/config-ui/test-class-configuration-endpoint.php
- tests/notifications/test-class-yoast-notification-center.php
* N/A - Fixes the tests.
* ~Fixes a bug where the `wpmu_new_blog` hook has been called. This hook is deprecated in WordPress 5.1 and replaced by `wp_insert_site`~
* ~See: https://developer.wordpress.org/reference/hooks/wpmu_new_blog/~
* See: https://make.wordpress.org/core/2019/01/11/new-rest-api-notice-in-5-1/ - See the part about unit tests to have context.
* The unit test should pass. 
Fixes #
Replaces #12286
> Handling the deprecated hook wp 5.1

- inc/class-wpseo-meta.php
- tests/test-class-wpseo-meta.php
Make sure the data provided is also stored and retrieved in the same way.
* Fixes a bug where slashed data would be transformed to unslashed data after saving and reloading a post.
* Slash the data, because `update_metadata` will unslash it and we have already unslashed it.
* Added tests for slashed values.
* Added tests for serialized values, where serialized and unregistered could result in an error before.
* Testing registered and unregistered fields, where the `get_value` function now gets used; also introducing a helper function for registration.
* Documentation improvements.
* Go to a post and add escaped data like `\"test\"` into a metabox input, for example, focus keyphrase. …
> Always slash data for post meta values

- inc/class-upgrade.php
* Fixes a bug where the recalibration beta notification would still show after the beta ended. 
* The upgrade routine did not correctly remove the notification from the database. This PR introduces a new function `clean_all_notifications` which clears all notification from the database field 'wp_yoast_notifications' in the table 'wp_usermeta'. 
* Reproduce the issue as described in #12281. 
* Checkout this branch / install the build zip. The notification should be gone. 
* If this is difficult to test or you don't have an installation where the notification still shows you can bring it back to test it. Add the following function to `class-upgrade.php`
```
/**
* Returns the …
```
> Update the upgrade routine to correctly clear the beta notification

- inc/class-wpseo-meta.php
- tests/test-class-wpseo-meta.php
Reverts Yoast/wordpress-seo#12282
> Revert "Always slash data for post meta values"

- inc/class-upgrade.php
* [not-userfacing] Combines two separate upgrade routines for 10.0.
* [not-userfacing] Checks if 
* Also makes sure `wpseo_recalibration_beta_mailing_subscription` option is removed upon upgrading to 10.0.
* Make sure the `Yoast Test Helper` is installed.
* Make sure you still have the `wpseo_recalibration_beta_mailing_subscription` option is present. If not check out 9.5 to reactivate it.
* Make sure the `recalibration_beta` value is present in the `wpseo` option in the `wp_options` table.
* In the Yoast Test helper set the version to 9.6 and save. This triggers the 10.0 upgrade routine.
* Check if the `wpseo_recalibration_beta_mailing_subscription` option has been removed from the …
> Merged upgrade routines

- package.json
- yarn.lock
* [non-user-facing] Version bump for YoastSEO (to 1.48.0)
[non-user-facing] Version bump for Yoast Components (to 4.21.0)
* Build the files, see no errors. 
Fixes #
> Update yoastseo and yoast component versions. 

- admin/config-ui/components/class-component-suggestions.php
* Replaces all references to the Basic SEO training in the configuration wizard with references to the Keyword research training.
*
* In the dashboard, go to the configuration wizard, step 11.
* You should see the following training suggestion:
* The suggestion should now look as follows:
* (At the moment, the Keyword research training button still results in a Page not found error, but this should change once 10.0 is released.)
Fixes #12314
> Replaced all references to Basic SEO training with Keyword research training

- inc/options/class-wpseo-taxonomy-meta.php
- tests/inc/options/test-class-wpseo-taxonomy-meta.php
* Fixes a bug where related keyphrases and synonyms could be transformed after saving and reloading a taxonomy.
* Fixes a bug where a taxonomy's focus keyphrase could not include double quotes.
* Added validation for the related keyphrases (`wpseo_focuskeywords`) and synonyms (`wpseo_keywordsynonyms`).
* Removed the use of `stripslashes` for the breadcrumb title, focus keyphrase title, description, score and default fields.
* Removed the sanitizing of `"` and `&quot` from the focus keyphrase.
* Added tests for `WPSEO_Taxonomy_Meta::validate_term_meta_data()`.
* Merge this PR in premium to test it.
* Go to a taxonomy page.
* Enter a text with some escaped characters, like `\"test\"`. …
> Fix taxonomy meta validation

- tests/admin/test-class-yoast-network-admin.php
- tests/notifications/test-class-yoast-notification-center.php
- wp-seo-main.php
* Replaces the`wpmu_new_blog` by the `wp_insert_site` hook in websites running WP5.1 or higher. 
* Removed the workaround for the failing tests introduced earlier in #12291, to test if the tests pass now. 
* `Use another hook (`wp_initialize_site `), because in that hook the tables will be created`
The issue is hard to test as the deprecation warning is not shown, problably because the page redirects.I would expect a deprecation warning when adding a new site under WP 5.1 on a multisite but no deprecation warning is thrown. The solution is to use WP_DEBUG_LOG.
To reproduce the issue: 
* Open a multisite, make sure the installed WordPress version is 5.1 or higher. 
* In your …
> Replace deprecated hook `wpmu_new_blog` by `wp_insert_site`

- wp-seo-main.php
* N/A - Additional improvement for #12320
* Removed the workaround for the failing tests introduced earlier in #12291, to test if the tests pass now. 
The issue is hard to test as the deprecation warning is not shown, probably because the page redirects.I would expect a deprecation warning when adding a new site under WP 5.1 on a multisite but no deprecation warning is thrown. The solution is to use WP_DEBUG_LOG.
To reproduce the issue: 
* Open a multisite, make sure the installed WordPress version is 5.1 or higher. 
* In your `wp-config.php` file add the line `define( 'WP_DEBUG_LOG', true );`
* Go to 'My sites' -> 'Network Admin' -> 'Sites'
* Click 'Add New' and add a new site. 
* …
> Use the same callback function for the hook

- admin/class-admin.php
- admin/class-unsupported-php-message.php
- composer.json
- composer.lock
This time we check against PHP version 5.6
* Shows a notice on both the WordPress and Yoast dashboards when the current PHP version is below 5.6.
*
* Have an older version of PHP installed. (I've no clue how to achieve that).
* Or you can fake the version by changing the >= `5.6` to `>=7.6` here: https://github.com/Yoast/wordpress-seo/compare/feature/oauth-connection-ui...12163-add-whip-message?expand=1#diff-e8ce9a043bfa6ca96ed62eb9f0de63b6R141
* Go to the WordPress main page and see a big error.
* Go to the Yoast dashboard and see the same error
* Go to another page and see no error.
Fixes #12163
> Bring back the whip message

- frontend/class-opengraph-image.php
* [not-userfacing] Removes the `og:image:alt` tag from Yoast SEO.
*
* In your WordPress environment, go to `Posts`, choose a post to edit, and go to the social media tab.
* Upload a Facebook image to the post, and make sure you fill out the `Alt Text` field under `ATTACHMENT DETAILS`.
* Update, view post and inspect.
* In `Elements`, under `head`, you should see the `og:image:alt` tag with as its content the text you just entered.
* Refresh your post and inspect again. The `og:image:alt` tag should be gone.
Fixes #12210
> Removed the alt image tag for Open Graph.

- frontend/class-breadcrumbs.php
* Improve the breadcrumbs accessibility by adding `aria-current` to the active item
- adds `aria-current` to the active item
- gets rid of a phpcs warning
- removes reference to RDFA from an old docblock 
Add the breadcrumbs in the `single` template of your theme, following the example on https://kb.yoast.com/kb/implement-wordpress-seo-breadcrumbs/
```
if ( function_exists( 'yoast_breadcrumb' ) ) {
yoast_breadcrumb( '<p id="breadcrumbs">', '</p>' );
}
```
Visit a single post page and verify the breadcrumbs active item as an `aria-current="page"` attribute
Fixes #12109
> Add aria-current to the breadcrumbs active item.

- inc/class-wpseo-admin-bar-menu.php
* [not user facing] Add missing screen reader text to the SEO score icon in the front end
This PR fixes the last part of #5145, the other parts have already been addressed with the refactoring of the admin bar menu in #9944.
- uses the translated score to build a string `SEO score: %s`
- in the front end, the score icon will use this string 
- in the admin this string will be used only initially on page load: when the analysis kicks in, it will replace the screen reader text on the fly
- preview posts with different SEO scores
- verify the SEO score icon in the admin bar has a hidden screen reader text with the string `SEO score: %s` where `%s` is of course replaced with the actual score
Note: there's a bit of inconsistency …
> Add the SEO score text to the admin bar icon.

- css/src/metabox.scss
* [visuals] Changes the alignment of Yoast labels in the publish-box to match the default WordPress content alignment.
*
* Create or edit a page or post and check the alignment of all labels in the publish-box.
Fixes #4929
> Changes alignment of labels in publish-box
